### ISSUE TITLE
[Extension] thumbnails

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#10]
while thumbnails should be a separate service it needs to respect the access permissions, otherwise it might leak information.

oCIS Extension based on https://github.com/owncloud/ocis/issues/54

We can
- [ ] use a content hash of the original file and the thumbnail size for the name of the thumbnail, render it on the fly, cache it on the server side and in the browser. If you don't already have the content hash you can only brute force thumbnails. Without authentication an attacker might be able to iterate over known hashes, which might leak compromising information.
- [ ] optionally, to increase security, check if the user is logged in
- [ ] optionally, to increase security even further, check file permissions and deny thumbnail access if the user has no access.

They can be implemented incrementally.

**Comment by michaelstingl** [comment]
Previous pain or ideas around this topic…

- Aspect ratio / scale options https://github.com/owncloud/core/issues/16250 , https://github.com/owncloud/core/issues/31268
- Etag for previews https://github.com/owncloud/core/issues/35029
- Share thumbnails? https://github.com/owncloud/core/issues/31855
- Run async / in background https://github.com/owncloud/core/issues/11685
- Discussion around supported file/MIME types https://github.com/owncloud/core/issues/13647 , https://github.com/owncloud/core/issues/31267
- Multiple thumbnails services for different file types https://github.com/owncloud/core/issues/24480
- Extract thumbnails embedded in EXIF https://github.com/owncloud/core/issues/7232

**Comment by michaelstingl** [comment]
@TheOneRing links for EXIF orientation madness:
- https://github.com/recurser/exif-orientation-examples
- https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/
- https://magnushoff.com/articles/jpeg-orientation/

Please check if this is properly handled by the library you're using.

**Comment by felixboehm** [comment]
https://github.com/cs3org/reva/pull/298

**Comment by PVince81** [comment]
On the front end side, the way I see it:
- files app must support fetching file thumbnails for displaying in the current file list: https://github.com/owncloud/phoenix/issues/276
- optionally: we can provide a way to view bigger previews in the top of sidebar like we had in OC 10. Could be native or could be provided by an extension
- later on: gallery view frontend extension that either provides another view of the file list (needs extension point to register multiple views for the file list => https://github.com/owncloud/phoenix/issues/2585)

For finding out about preview URLs, multiple options:
1) reuse the same URL / path we had in OC 10 (by convention, keeps compatibility)
2) expose thumbnail URL in PROPFILE/filelist responses in all supported protocols (maybe MSGraph has this already?)

**Comment by DeepDiver1975** [comment]
MS Graph API already has a Thumbnail spec

**Comment by PVince81** [comment]
Had a chat with @TheOneRing to understand how the current implementation of the thumbnail server works. As far as I understood:
- the thumbnail server:
   - receives a Webdav URL including authentication token and parameters for the thumbnail.
   - sends a request to the Webdav URL with HEAD (to check etag) and GET to receive the file in question
   - the response body of the first requests will contain the generated thumbnail
   - caches the requested thumbnails in memory (for now), so the HEAD / etag check can save having to do the Webdav request to get the thumbnail

**Comment by butonic** [comment]
As @DeepDiver1975 mentioned we should make the thumbnail service serve the endpoints as exposed in the ms graph api https://docs.microsoft.com/en-us/graph/api/driveitem-list-thumbnails?view=graph-rest-1.0&tabs=http

**Comment by PVince81** [comment]
As far as I can see it would require the router to let extensions register to dynamic routes, not only route prefixes. Here for example: /drives/{drive-id}/items/{item-id}/thumbnails

**Comment by PVince81** [comment]
Further ideas:
- the service could have the ability to pregenerate thumbnails when passing in a folder URL. it should then recursively traverse it and create thumbnails of all known file types in there with a standard/configured size, so they are pre-cached. This would be useful for gallery-like usage.

**Comment by michaelstingl** [comment]
Added support for modern media formats like HEIC & HEVC in https://github.com/owncloud/ocis/issues/10#issuecomment-543248302

**Comment by wkloucek** [comment]
thumbnails extension is there. Some more to do here?

**Comment by michaelstingl** [comment]
> thumbnails extension is there. Some more to do here?

Link to qa/test results? Are my items from https://github.com/owncloud/ocis/issues/10#issuecomment-543248302 already covered? Otherwise we'd need new issues…

**Comment by refs** [comment]
> > thumbnails extension is there. Some more to do here?
> 
> Link to qa/test results? Are my items from [#10 (comment)](https://github.com/owncloud/ocis/issues/10#issuecomment-543248302) already covered? Otherwise we'd need new issues…

I'd close this and take care of creating new issues addressing @michaelstingl comments 👍
