### ISSUE TITLE
Once micro cli has been updated, update dependencies

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#100]

**Comment by DeepDiver1975** [comment]
Upstream changes are already in place - https://github.com/micro/micro/commit/4ab48bc8158b8a56f2d2ab46f786e2328a39799a - next release should have this ...

**Comment by refs** [comment]
but we still have this dependency of v1 in places like:

https://github.com/owncloud/ocis/blob/master/pkg/flagset/flagset.go#L4

and

https://github.com/owncloud/ocis/blob/master/pkg/command/hello.go#L7 (through the extension)

and

https://github.com/owncloud/ocis/blob/master/pkg/command/hello.go#L4

and more importantly: https://github.com/owncloud/ocis/blob/master/pkg/command/hello.go#L4

When it comes to the micro runtime commands yes, they'd be updated.
