### ISSUE TITLE
Activities. can not distinguish between edit and uploaded file

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#10001]
## Steps to reproduce
1. edit a file
2. check the activity 
3. activity shows `added`

## Expected behavior
- activity shows `edited`
<img width="586" alt="image" src="https://github.com/user-attachments/assets/d906de9b-a764-4c3f-bf15-ae7f263db774">

## Actual behavior
- activity shows `added`
- `moss added New file.odt to Maurice Moss`

**Comment by kobergj** [comment]
Needs moving the event creation from eventsmiddleware to decomposedfs as described here: https://github.com/owncloud/ocis/issues/9481
