### ISSUE TITLE
Activities. no event for downloading file

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#10007]
Expected: 
<img width="723" alt="image" src="https://github.com/user-attachments/assets/02672e8e-fa27-4af9-b814-fbba2b19f566">
Actual: no events -> backend issue

**Comment by kobergj** [comment]
@butonic This is currently not possible as we cannot differentiate between a public link download and an authenticated download. We could log all downloads of a file. Would that fix the issue?

**Comment by micbar** [comment]
> This is currently not possible as we cannot differentiate between a public link download
Don't we have an attribute in the cs3 user object?

**Comment by micbar** [comment]
> > This is currently not possible as we cannot differentiate between a public link download

Don't we have an attribute in the cs3 user object?

**Comment by kobergj** [comment]
> Don't we have an attribute in the cs3 user object?

Afaik only in the opaque. But that gets lost along the way.

**Comment by kobergj** [comment]
Note: With `currently not possible` I of course mean `not possible without major changes`

**Comment by kobergj** [comment]
Should be straightforward after https://github.com/owncloud/ocis/pull/10116 has landed
