### ISSUE TITLE
Invalid file-names can be created using the TUS protocol

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1001]
1. create a base64 encoding of a file name
  - `echo "filewithLF-and-CR" | base64` (has a `\r\n`) at the end
  - `echo -n "    "  | base64` filename contains only spaces
  - `echo -n "folder/file" | base64`
  - `echo -n "my\\file" | base64`
2. send a create resource request `curl -XPOST https://localhost:9200/remote.php/dav/files/Einstein/ -ueinstein:relativity -k  -v -H'Tus-Resumable: 1.0.0' -H'Upload-Length: 10' -H'Upload-Metadata: filename <your-base64-encoded-file-name>'`
3. remember the URL from the Location header
4. upload data: `curl -k -XPATCH <your TUS resource Location> -ueinstein:relativity -H'Content-Type: application/offset+octet-stream' -H'Tus-Resumable: 1.0.0' -H'Upload-Offset: 0' -d'1234567890' -v`
5. Try to download the file in phoenix?

**Comment by C0rby** [comment]
In the current master the file names are being validated and requests with invalid names get rejected.
