### ISSUE TITLE
ACTIVITYOG_SERVICE_ACCOUNT_SECRET

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#10013]
## Describe the bug
https://owncloud.dev/services/activitylog/ mentions `ACTIVITYOG_SERVICE_ACCOUNT_SECRET` as configuration option. All others actually have the `ACTIVITYLOG_` prefix.

## Steps to reproduce
1. visit https://owncloud.dev/services/activitylog/

**Comment by mmattel** [comment]
For ease of identifying the issue, the character `L` is missing:

`ACTIVITYLOG_`
`ACTIVITYOG_SERVICE_ACCOUNT_SECRET`
