### ISSUE TITLE
OCIS Full docker-compose.yml example

### ISSUE THREAD

**Issue by Simon99de** [owncloud/ocis#10016]
## Describe the bug
i think there is something missing in the file, because only traefik is installed without ocis or anything else

## Steps to reproduce
1. https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_full/docker-compose.yml

## Expected behavior
ocis should also be included, shouldn't it?

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by abrasher** [comment]
All the other compose yamls files are included by editting the .env file. At the bottom of the .env file, there is:
```
COMPOSE_FILE=docker-compose.yml${OCIS:-}${TIKA:-}${S3NG:-}${S3NG_MINIO:-}${COLLABORA:-}${MONITORING:-}${CLOUD_IMPORTER:-}${CLAMAV:-}${ONLYOFFICE:-}${INBUCKET:-}
```

which by default, ocis is included as the .env file also includes
```
## Infinite Scale Settings ##
# Beside Traefik, this service must stay enabled.
# Disable only for testing purposes.
# Note: the leading colon is required to enable the service.
OCIS=:ocis.yml
```

which basically makes running docker-compose up into docker-compose up -f docker-compose.yml -f docker-compose ocis.yml (-f "other.yml files that are enabled")

**Comment by Simon99de** [comment]
Oh, I didn't know that yet with the configs etc. and don't know how it works if there are several inf files, because I can't install it via the consohle, only via composer file or manually enter everything.

**Comment by micbar** [comment]
Please read https://owncloud.dev/ocis/deployment/ocis_full/

Also the .env file itself has a lot of annotations https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_full/.env

Please ask, if anything is unclear in the wording or could be improved.

@mmattel @tbsbdr FYI

**Comment by mmattel** [comment]
We have full blown step-by-step examples documented in our [Admin Documentation](https://doc.owncloud.com) for deploying on your own server or via Hetzer as provider. Please have a look at:
* [Own server using rolling releases](https://doc.owncloud.com/ocis/next/depl-examples/ubuntu-compose/ubuntu-compose-prod.html)
* [Own server using production releases](https://doc.owncloud.com/ocis/5.0/depl-examples/ubuntu-compose/ubuntu-compose-prod.html)

As @micbar noted, let us know if things need improvement in the admin docs.
To do so, file an issue in https://github.com/owncloud/docs-ocis

**Comment by Simon99de** [comment]
Infinite Scale based on Ubuntu LTS and docker compose

OK, I thought infinte Scale only runs on docker (that's a mistake)
It requires the operating system and docker, I only read that in one of the links.

Can you run ocis with just docker, ngnx proxy manager, and one of the 3 servers to process data? I then use Zima OS, (Nas operating system)

**Comment by micbar** [comment]
Infinite scale runs on docker.

Docker runs on a Hostsystem.
