### ISSUE TITLE
superfluous response.WriteHeader call is polluting the server log

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10023]
ocis log in CI https://drone.owncloud.com/owncloud/ocis/38776/16/3
k6 nightly: https://drone.owncloud.com/owncloud/ocis/38773/73/2

How reproduce:
- build ocis `make -C ocis clean generate build`
- start ocis `ocis/bin/ocis init` and `ocis/bin/ocis server`
- see server log

Actual: the log is unreadable. tons of errors
a lot of errors in ocis log: 
`2024/09/11 09:00:59 http: superfluous response.WriteHeader call from github.com/cs3org/reva/v2/internal/http/interceptors/log.(*responseLogger).WriteHeader (log.go:154)`

I thought the cause was https://github.com/owncloud/ocis/pull/9956, but after trying to revert this commit -> the problem still exists.

**Comment by kobergj** [comment]
Seems fixed. Doesn't appear in newer pipelines. Please reopen if it comes back.
