### ISSUE TITLE
OCM federation sharing issue

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#10025]
Using the federation setup from the web repo, ocis code master from friday last week.
I created two new ordinary users:

`vlad` (sharer, `ocis.owncloud.test`) and
`ludmilla` (sharee `host.docker.internal`).

The federation invite worked flawless (`vlad` generate token, `ludmilla` accept token).
With both users, I created a file fo share.
`vlad` shares his file with `ludmilla` and the file is immediately shown in shared files on `ludmillas` side.

**Issue:**
Now doing the things backwards:
`ludmilla` shares her file with `vlad` but the file is not shown in shared files on `vlad` side, though it shows shared at `ludmilla`.

@fschade
@butonic fyi

**Comment by fschade** [comment]
@micbar something for that sprint or not?

**Comment by mmattel** [comment]
Linking to #9735

**Comment by ScharfViktor** [comment]
I guess https://github.com/owncloud/ocis/issues/9534 is similar. 

you can find actual behavior in the comments
