### ISSUE TITLE
oCIS 6.3 - Access Token Expired - "Resource not found"

### ISSUE THREAD

**Issue by dj4oC** [owncloud/ocis#10038]
## Describe the bug
when I wait long enough until my access token is expired, I see an message: "Resource not found. We went looking everywhere, but were unable to find the selected resource." This message is missleading, especially since the developer console actually shows the correct message "access token expired".

## Steps to reproduce
1. Login and open on office document
2. Wait until access token is expired
3. try to open a space 

## Expected behavior
show a message: your access token is expired, would you like to login again?

## Actual behavior
Empty file listing with message: Resource not found. We went looking everywhere, but were unable to find the selected resource.

## Setup
oCIS 6.4 with Keycloak

**Comment by micbar** [comment]
@kulmann @JammingBen any ideas?

**Comment by micbar** [comment]
@dj4oC are you using ocis_keycloak docker compose?

because it could also be a missing csp config.

**Comment by micbar** [comment]
6.4 must be wring @dj4oC 
You reported that before 6.4.0 has been released.

**Comment by kulmann** [comment]
@dj4oC can you share details on how you achieved `2. Wait until access token is expired`? By closing your notebook lid and waiting more than 5 minutes? Or does the token renewal not work?

**Comment by JammingBen** [comment]
I assume this is https://github.com/owncloud/web/issues/11478, which was supposed to be fixed. I'll re-open the issue, IMO we can close here then.

The issue has been around for a bit, nothing we broke with the recent versions 6.3 oder 6.4.

**Comment by micbar** [comment]
I have no token renewal issues when the browser tab is open.

**Comment by JammingBen** [comment]
> I have no token renewal issues when the browser tab is open.

The issue occurs when the token can't be renewed for some reason (e.g. when your computer goes into standby and is therefore not able to perform a renewal).
