### ISSUE TITLE
6.4.0 Logout during uploads

### ISSUE THREAD

**Issue by BEBU88** [owncloud/ocis#10054]
Since the update to 6.4.0 I occasionally get logged out from the web during uploads. The console is giving me this error followed by the info 'user unloaded':

> web-app-files-BboIcf5h.mjs:1 jhe: Unknown error
>     at x_.request (https://URL/js/index.html-DEs9cLQA.mjs:5:37861)
>     at async x_.propfind (https://URL/js/index.html-DEs9cLQA.mjs:5:35973)
>     at async Object.getPathForFileId (https://URL/js/index.html-DEs9cLQA.mjs:5:22211)
>     at async d (https://URL/js/index.html-DEs9cLQA.mjs:5:20332)
> (anonym) @ web-app-files-BboIcf5h.mjs:1
> (anonym) @ SpaceInfo-C4GhJqzv.mjs:7
> Promise.then
> i @ SpaceInfo-C4GhJqzv.mjs:7
> a @ SpaceInfo-C4GhJqzv.mjs:7
> ot @ SpaceInfo-C4GhJqzv.mjs:7
> (anonym) @ SpaceInfo-C4GhJqzv.mjs:7
> vt @ SpaceInfo-C4GhJqzv.mjs:10
> _run @ SpaceInfo-C4GhJqzv.mjs:10
> bt @ SpaceInfo-C4GhJqzv.mjs:10
> u @ SpaceInfo-C4GhJqzv.mjs:10
> run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> perform @ SpaceInfo-C4GhJqzv.mjs:10
> (anonym) @ web-app-files-BboIcf5h.mjs:1
> a @ SpaceInfo-C4GhJqzv.mjs:7
> ot @ SpaceInfo-C4GhJqzv.mjs:7
> (anonym) @ SpaceInfo-C4GhJqzv.mjs:7
> vt @ SpaceInfo-C4GhJqzv.mjs:10
> _run @ SpaceInfo-C4GhJqzv.mjs:10
> bt @ SpaceInfo-C4GhJqzv.mjs:10
> u @ SpaceInfo-C4GhJqzv.mjs:10
> run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> perform @ SpaceInfo-C4GhJqzv.mjs:10
> oe @ web-app-files-BboIcf5h.mjs:1
> (anonym) @ web-app-files-BboIcf5h.mjs:1
> (anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> t.__weh.t.__weh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Kh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Promise.then
> Mk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> fg @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> m @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> k0 @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> wk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> bl @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> set value @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> Pe @ vue-router-CBOIpbFo.mjs:5
> (anonym) @ vue-router-CBOIpbFo.mjs:5
> Promise.then
> U @ vue-router-CBOIpbFo.mjs:5
> M @ vue-router-CBOIpbFo.mjs:5
> (anonym) @ index.html-DEs9cLQA.mjs:5
> m @ vue-router-CBOIpbFo.mjs:5
> (anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
> so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> r @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
> index.html-DEs9cLQA.mjs:5 user unloaded…
> web-app-files-BboIcf5h.mjs:1 cancel
> oe @ web-app-files-BboIcf5h.mjs:1
> await in oe
> (anonym) @ web-app-files-BboIcf5h.mjs:1
> (anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> t.__weh.t.__weh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Kh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Promise.then
> Mk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> fg @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> m @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> k0 @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> wk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> bl @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> set value @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
> Pe @ vue-router-CBOIpbFo.mjs:5
> (anonym) @ vue-router-CBOIpbFo.mjs:5
> Promise.then
> U @ vue-router-CBOIpbFo.mjs:5
> M @ vue-router-CBOIpbFo.mjs:5
> (anonym) @ index.html-DEs9cLQA.mjs:5
> m @ vue-router-CBOIpbFo.mjs:5
> (anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
> so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
> r @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17

Setup: ocis 6.4 in Docker with Keycloak

**Comment by micbar** [comment]
@kulmann @JammingBen any ideas?

**Comment by BEBU88** [comment]
I did some research here. It looks like it has nothing to do with the uploads. While I upload some files I switch between a various number of spaces. These spaces have round about 300-400 files in place which took quite a while to load. So I did this without uploading files and it happened again shortly after token renewal. For me it looks like the requests for loading the space use the old access token if token renewal happens while the space is still loading:: 

index.html-DEs9cLQA.mjs:5 AccessToken Expiring：
PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48 Laden von Abrufen beendet: POST „https://auth.URL/realms/URL/protocol/openid-connect/token“.
fetchWithTimeout @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48
postForm @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48
exchangeRefreshToken @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48
await in exchangeRefreshToken
useRefreshToken @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48
_useRefreshToken @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48
signinSilent @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:48
await in signinSilent
signinSilent @ index.html-DEs9cLQA.mjs:5
h.onmessage @ index.html-DEs9cLQA.mjs:5
index.html-DEs9cLQA.mjs:5 New User Loaded. access_token： --- , refresh_token: ---
PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22 
        
        
       PROPFIND https://ocis.URL/remote.php/dav/meta/f04c64bf-ca42-4c55-aa6b-79c1acea51ae%241f311060-3b8b-4e77-9290-77389ef58ba7 401 (Unauthorized)
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
execute @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
patchInline @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
execute @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
patchInline @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
fp @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
customRequest @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
request @ index.html-DEs9cLQA.mjs:5
propfind @ index.html-DEs9cLQA.mjs:5
getPathForFileId @ index.html-DEs9cLQA.mjs:5
d @ index.html-DEs9cLQA.mjs:5
listFiles @ index.html-DEs9cLQA.mjs:5
await in listFiles
(anonym) @ web-app-files-BboIcf5h.mjs:1
a @ SpaceInfo-C4GhJqzv.mjs:7
ot @ SpaceInfo-C4GhJqzv.mjs:7
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
vt @ SpaceInfo-C4GhJqzv.mjs:10
_run @ SpaceInfo-C4GhJqzv.mjs:10
bt @ SpaceInfo-C4GhJqzv.mjs:10
u @ SpaceInfo-C4GhJqzv.mjs:10
run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
perform @ SpaceInfo-C4GhJqzv.mjs:10
(anonym) @ web-app-files-BboIcf5h.mjs:1
a @ SpaceInfo-C4GhJqzv.mjs:7
ot @ SpaceInfo-C4GhJqzv.mjs:7
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
vt @ SpaceInfo-C4GhJqzv.mjs:10
_run @ SpaceInfo-C4GhJqzv.mjs:10
bt @ SpaceInfo-C4GhJqzv.mjs:10
u @ SpaceInfo-C4GhJqzv.mjs:10
run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
perform @ SpaceInfo-C4GhJqzv.mjs:10
oe @ web-app-files-BboIcf5h.mjs:1
(anonym) @ web-app-files-BboIcf5h.mjs:1
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
t.__weh.t.__weh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Kh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Promise.then
Mk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
fg @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
m @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
k0 @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
wk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
bl @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
set value @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
Pe @ vue-router-CBOIpbFo.mjs:5
(anonym) @ vue-router-CBOIpbFo.mjs:5
Promise.then
U @ vue-router-CBOIpbFo.mjs:5
M @ vue-router-CBOIpbFo.mjs:5
(anonym) @ index.html-DEs9cLQA.mjs:5
m @ vue-router-CBOIpbFo.mjs:5
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
r @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22 Abrufen konnte nicht geladen werden: PROPFIND „https://ocis.URL/remote.php/dav/meta/f04c64bf-ca42-4c55-aa6b-79c1acea51ae%241f311060-3b8b-4e77-9290-77389ef58ba7“.
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
execute @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
patchInline @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
execute @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
patchInline @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
fp @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
customRequest @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:22
request @ index.html-DEs9cLQA.mjs:5
propfind @ index.html-DEs9cLQA.mjs:5
getPathForFileId @ index.html-DEs9cLQA.mjs:5
d @ index.html-DEs9cLQA.mjs:5
listFiles @ index.html-DEs9cLQA.mjs:5
await in listFiles
(anonym) @ web-app-files-BboIcf5h.mjs:1
a @ SpaceInfo-C4GhJqzv.mjs:7
ot @ SpaceInfo-C4GhJqzv.mjs:7
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
vt @ SpaceInfo-C4GhJqzv.mjs:10
_run @ SpaceInfo-C4GhJqzv.mjs:10
bt @ SpaceInfo-C4GhJqzv.mjs:10
u @ SpaceInfo-C4GhJqzv.mjs:10
run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
perform @ SpaceInfo-C4GhJqzv.mjs:10
(anonym) @ web-app-files-BboIcf5h.mjs:1
a @ SpaceInfo-C4GhJqzv.mjs:7
ot @ SpaceInfo-C4GhJqzv.mjs:7
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
vt @ SpaceInfo-C4GhJqzv.mjs:10
_run @ SpaceInfo-C4GhJqzv.mjs:10
bt @ SpaceInfo-C4GhJqzv.mjs:10
u @ SpaceInfo-C4GhJqzv.mjs:10
run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
perform @ SpaceInfo-C4GhJqzv.mjs:10
oe @ web-app-files-BboIcf5h.mjs:1
(anonym) @ web-app-files-BboIcf5h.mjs:1
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
t.__weh.t.__weh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Kh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Promise.then
Mk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
fg @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
m @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
k0 @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
wk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
bl @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
set value @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
Pe @ vue-router-CBOIpbFo.mjs:5
(anonym) @ vue-router-CBOIpbFo.mjs:5
Promise.then
U @ vue-router-CBOIpbFo.mjs:5
M @ vue-router-CBOIpbFo.mjs:5
(anonym) @ index.html-DEs9cLQA.mjs:5
m @ vue-router-CBOIpbFo.mjs:5
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
r @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
web-app-files-BboIcf5h.mjs:1 jhe: Unknown error
    at x_.request (https://ocis.URL/js/index.html-DEs9cLQA.mjs:5:37861)
    at async x_.propfind (https://ocis.URL/js/index.html-DEs9cLQA.mjs:5:35973)
    at async Object.getPathForFileId (https://ocis.URL/js/index.html-DEs9cLQA.mjs:5:22211)
    at async d (https://ocis.URL/js/index.html-DEs9cLQA.mjs:5:20332)
(anonym) @ web-app-files-BboIcf5h.mjs:1
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
Promise.then
i @ SpaceInfo-C4GhJqzv.mjs:7
a @ SpaceInfo-C4GhJqzv.mjs:7
ot @ SpaceInfo-C4GhJqzv.mjs:7
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
vt @ SpaceInfo-C4GhJqzv.mjs:10
_run @ SpaceInfo-C4GhJqzv.mjs:10
bt @ SpaceInfo-C4GhJqzv.mjs:10
u @ SpaceInfo-C4GhJqzv.mjs:10
run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
perform @ SpaceInfo-C4GhJqzv.mjs:10
(anonym) @ web-app-files-BboIcf5h.mjs:1
a @ SpaceInfo-C4GhJqzv.mjs:7
ot @ SpaceInfo-C4GhJqzv.mjs:7
(anonym) @ SpaceInfo-C4GhJqzv.mjs:7
vt @ SpaceInfo-C4GhJqzv.mjs:10
_run @ SpaceInfo-C4GhJqzv.mjs:10
bt @ SpaceInfo-C4GhJqzv.mjs:10
u @ SpaceInfo-C4GhJqzv.mjs:10
run @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
perform @ SpaceInfo-C4GhJqzv.mjs:10
oe @ web-app-files-BboIcf5h.mjs:1
(anonym) @ web-app-files-BboIcf5h.mjs:1
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
t.__weh.t.__weh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Kh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Promise.then
Mk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
fg @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
m @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
k0 @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
wk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
bl @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
set value @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
Pe @ vue-router-CBOIpbFo.mjs:5
(anonym) @ vue-router-CBOIpbFo.mjs:5
Promise.then
U @ vue-router-CBOIpbFo.mjs:5
M @ vue-router-CBOIpbFo.mjs:5
(anonym) @ index.html-DEs9cLQA.mjs:5
m @ vue-router-CBOIpbFo.mjs:5
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
r @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
index.html-DEs9cLQA.mjs:5 user unloaded…
web-app-files-BboIcf5h.mjs:1 cancel
oe @ web-app-files-BboIcf5h.mjs:1
await in oe
(anonym) @ web-app-files-BboIcf5h.mjs:1
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
t.__weh.t.__weh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Kh @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Dk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Promise.then
Mk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
fg @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
m @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
k0 @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
wk @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
bl @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
set value @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:9
Pe @ vue-router-CBOIpbFo.mjs:5
(anonym) @ vue-router-CBOIpbFo.mjs:5
Promise.then
U @ vue-router-CBOIpbFo.mjs:5
M @ vue-router-CBOIpbFo.mjs:5
(anonym) @ index.html-DEs9cLQA.mjs:5
m @ vue-router-CBOIpbFo.mjs:5
(anonym) @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17
so @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
Hn @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:13
r @ PortalTarget.vue_vue_type_script_lang-4g7zqQEe.mjs:17

**Comment by BEBU88** [comment]
I did some further research. As I mentioned it only happens, if a new access_token is requested and the space is still loading. It also happens only if I switch between different spaces very quickly (e.g put files into different spaces for upload) because this increases the loading time of the spaces. I have round about 500 spaces. Every time I go back to the spaces list there are several  PROPFIND and GET request for every space. These requests are going on in the background after a space is selected which leads to a slower loading of the space. If I just wait for all request being processed before selecting a space from the list this space is loading within a second, even with 500 files. So maybe it could be helpful, to abort these requests after a space is selected.

**Comment by JammingBen** [comment]
Thanks for the detailed information! I couldn't find time last week to dig into this, but it's on my agenda for this week.

> It also happens only if I switch between different spaces very quickly (e.g put files into different spaces for upload) because this increases the loading time of the spaces.

So you enter a space, upload some files, and while the upload is ongoing, you navigate to another space?

> These requests are going on in the background after a space is selected which leads to a slower loading of the space. If I just wait for all request being processed before selecting a space from the list this space is loading within a second, even with 500 files. So maybe it could be helpful, to abort these requests after a space is selected.

Just to make sure: by "selecting a space" you mean selecting it by clicking the checkbox, or actually navigating into them?

**Comment by BEBU88** [comment]
> So you enter a space, upload some files, and while the upload is ongoing, you navigate to another space?

Yes, but you don‘t need to upload files. You just have to navigate into a space, quickly go back to the list of spaces and navigate into another space. As soon as you open the list of spaces the complete list loads again as you can see a lot of requests in the console. You then navigate into another space. The list of spaces keeps loading in the background and slows down the request to open the selected space. 

It also slows down creation of new spaces. Create a new space, navigate into this newly created space, go quickly back to the list of spaces and create a new one. 

I have round about 500 spaces with a custom space picture for each one.

> Just to make sure: by "selecting a space" you mean selecting it by clicking the checkbox, or actually navigating into them?

I actually navigate into them as described above.

**Comment by JammingBen** [comment]
https://github.com/owncloud/web/pull/11631 should be a big improvement in the scenario you described above. It will be included in the upcoming rolling release with oCIS 6.5.0 next week.

**Comment by tbsbdr** [comment]
fixed
