### ISSUE TITLE
[QA] Test coverage for allowing to disable versioning

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/ocis#10095]
## Description
oCIS has introduced new env `OCIS_DISABLE_VERSIONING` to disable resource versioning. By default it is disabled(`OCIS_DISABLE_VERSIONING:Flase`).

Test cases:
- [x] disable versioning  https://github.com/owncloud/ocis/pull/10170
  - [x] first `OCIS_DISABLE_VERSIONING` to `true` and create resource versions then set `OCIS_DISABLE_VERSIONING` to `false` and check resource version
  - [x] check version of resource
      - [x] Personal space
      - [x] Shares space
      - [x] Project space
  - [x] create resource versions with default oCIS and disable versioning using env and check file versions

**Comment by amrita-shrestha** [comment]
every scenario is covered so closing this issue
