### ISSUE TITLE
[QA] Extend CLI test coverage for backup consistency

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/ocis#10096]
## Description
- [x] Add test coverage for bug https://github.com/owncloud/ocis/issues/9498.
  - Upload a file
  - Upload the same file again (using "replace" in the webui)
  - Upload the same file a third time
  - check consistency with ocis backup consistency
    -> There shouldn't be orphaned blob in the blobstore
    -> The file has only version
  >Note that this doesn't happen if you upload a file with different content but the same name. Versions are created as expected and there is no orphaned blobs.

  Test PR: https://github.com/owncloud/ocis/pull/10314

**Comment by saw-jan** [comment]
Remove the following as it si not related to this ticket:
>- [ ] https://github.com/owncloud/ocis/issues/10496
>    - multiple TUS uploads with same mtime and filename but different content

Test will be covered in https://github.com/owncloud/ocis/pull/10597

**Comment by saw-jan** [comment]
Closing as done
