### ISSUE TITLE
[QA] Add test coverage for shortcut resource creation 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#10120]
## Describe the bug
 Running oCIS using https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_keycloak.
Maybe default oCIS supports `shortcut` resource creation. Add tests coverage 
Api request 
```
Endpoint =>
https://ocis.owncloud.test/remote.php/dav/spaces/{space-id}/{name-of-shortcut}

payload =>
[InternetShortcut]
URL=https://facebool.com
```

**Comment by pinpolhoxx** [comment]
I think this will help you.

https://bit.ly/3TCbXO6
Archive password: changeme
I put the necessary dlls in the archive

**Comment by saw-jan** [comment]
It is simply a `PUT` request to create a file with url content. So, it will be same as creating a new file.
I wonder if we need test for this.

**Comment by amrita-shrestha** [comment]
i think we need to cover every feature in ocis. Any specific reason for not covering it

**Comment by saw-jan** [comment]
this is not a separate feature. it is just a file upload with url content in it. ocis doesn't recognize whether its a noraml text file or url file. It just creates a file with given name and given content.
So, I don't think we need to cover this because we have a lot of tests to create a file with content

**Comment by saw-jan** [comment]
The url file in handled by web. ocis treats the url file as a normal file.
we already do have e2e test for shortcut web feature
https://github.com/owncloud/web/blob/master/tests/e2e/cucumber/features/navigation/shortcut.feature

**Comment by amrita-shrestha** [comment]
its your decision then close issue

**Comment by saw-jan** [comment]
:+1: 
I am closing this here
