### ISSUE TITLE
[QA] Add test coverage for sharer being member of shared group

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#10124]
## Describe the bug
Extend our test coverage for scenarios when the sharer is a group member. Users share resources to groups and users check his/her own share-by-me and share-with-me

## Steps
- user 'Alice' added to group `grp1`
- user `Alice` share resource `file.txt` to group `grp1`
- user `Alice` check his/her share-by-me or share-with-me
  - according to old share api user `Alice` contain share resource on share-with-me 

## Test coverage
- different drive
   - share-by-me 
   - share-with-me

**Comment by prashant-gurung899** [comment]
Closing this issue as tests are covered in PR: https://github.com/owncloud/ocis/pull/10349
