### ISSUE TITLE
6.4.1 Release

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10123]
### Prerequisites

* [ ] Collaboration Gateway client pool selector https://github.com/owncloud/ocis/pull/10133
* [ ] DEV: release reva v.
* [ ] DEV: bump reva to v.
* [ ] DEV: bump web to v.

## QA Phase
* [ ] QA: Performance test 
* [ ] QA: Compatibility testing between 
* [ ] QA: e2e with different deployment: 

### After QA Phase
* [ ] DEV: Create branch `release-x.x.x` 
  * [ ] DEV: bump ocis version in necessary files
  * [ ] DEV: `ocis-pkg/version/version.go`
  * [ ] DEV: `sonar-project.properties`
  * [ ] DEV: released deployment versions
  * [ ] DEV: prepare changelog folder in `changelog/x.x.x_???`
  * [ ] DEV: add release to 
* [ ] DEV: Create final signed tag
* [ ] DEV: Check successful CI run on `vx.y.z` tag / BLOCKING for all further activity
* [ ] Merge release notes 
* [ ] roll out release on 
* [ ] roll out rolling release on 

****

**Comment by butonic** [comment]
this will also release https://github.com/owncloud/ocis/pull/10102, right?

**Comment by ScharfViktor** [comment]
close to favor #10186
