### ISSUE TITLE
Activity: folder variable missing if folder renamed

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#10148]
## Describe the bug
If I rename a folder, the activity events loose context, see screenshot.

## Steps to reproduce
1. Create a folder "test"
2. Create a subfolder "subtest"
3. Open the activities sidebar panel for "test"

## Expected behavior
Old activity events still show the old folder name from before the rename

## Actual behavior
The folder context is missing entirely (see screenshot)

<img width="1624" alt="Screenshot 2024-09-24 at 13 12 50" src="https://github.com/user-attachments/assets/53845c5d-a95a-44be-8cda-ec29f8c5b1aa">

**Comment by 2403905** [comment]
It happens because the old ref.Path that we keep in the event is not relevant for getting the resource information after renaming. 
We can use the part of the path for that. But it will not work when the resource id has been used for renaming (MOVE)
FYI @kobergj
