### ISSUE TITLE
[QA] sharing a file fails on eos

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1015]
Deployed ocis-1.0.0-rc6 via hetzner-deploy/make_ocis_eos_compose_test.sh

* connect a desktop client with user marie, let it sync and watch for issues while doing the next steps
* on the WBE-UI:
    * log in as einstein
    * share file Portrait.jpg with user marie
    * create a public share link for the file Portrait.jpg
* with a fresh browser session, log in as marie, 
    * accept the share,
    * go to 'All Files' -> Shares, Portrait.jpg is there. OK
    * click open the file, it fails showing a red triangle with exlamation mark.
* with a fresh browser session, visit the public share link
    * the link opens showing a view with file Portrait.jpg
    * click open the file, it fails showing a red triangle with exlamation mark.
* marie's desktop client tries to sync down the accepted share, but fails with internal error 500.

 12/3/20 11:46:04 AM,                                             Shares/Portrait.jpg,               testpilotcloud3,Server replied "500 Internal Server Error" to "GET https://X.X.X.X:9200/remote.php/webdav/Shares/Portrait.jpg" (skipped due to earlier error, trying again in 42 minute(s))

**Comment by jnweiger** [comment]
RC6 has still the old eos 4.5.6
To be retested with RC7 on updated eos 4.8.28

**Comment by micbar** [comment]
Upstream https://github.com/owncloud/ocis-reva/issues/12
