### ISSUE TITLE
Keycloak is outputting error - ggopenid misspelled instead of just openid

### ISSUE THREAD

**Issue by Schmagz** [owncloud/ocis#10182]
## Describe the bug
Keycloak is outputting error `Invalid scopes: ggopenid profile email` even though "ggopenid" is not specified, nor in keycloak or i ocis - it should be just "openid".

`type="LOGIN_ERROR", realmId="XXX", realmName="ocis", clientId="web", userId="null", ipAddress="XX.XXX.XXX.X", error="invalid_request", reason="Invalid scopes: ggopenid profile email", response_type="code"`

Don't know where OCIS get this misspelled "ggopenid" from? Is it hardcoded? I even set "`WEB_OIDC_SCOPE=openid profile email`" but it doesnt make any difference.

## Steps to reproduce
1. Login to owncloud desktop app or web client.

## Expected behavior
No error should be displayed.

## Setup
OCIS verison 5.0.7
Web client 8.0.5
Win desktop app 5.3.1

</body>
</html>

**Comment by micbar** [comment]
Which keycloak client config are you using?

**Comment by Schmagz** [comment]
Hello, the config is not used (commented out by default), keycloak is launched with systemd default settings except adding nginx settings.

**Comment by rhafer** [comment]
@Schmagz How to do run ocis? Can you please paste you config (cleared of any passwords) and env vars you're setting?

Also: Which version of Keycloak are you on? And how did you setup the `web` client in keycloak.

**Comment by Schmagz** [comment]
I just searched through the last couple of days logs and it doesn't seem to appear after that one afternoon when I opened this issue. I can't recall exactly what changes that have been made since so I guess it's best to close this as solved. (I wish I could tell what the solution was though).
