### ISSUE TITLE
Seperate metrics from the debug server

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#10187]
At the moment we server the `/metrics` , `/healthz` and `/readyz` through the debug server in each service. This should be seperated since those endpoints should be reachable all the time, without enabling the debug server. 

# Possible implementations

- Add an additional server for metrics and status endpoints
- Implement those endpoints into the regular http server of each server.

It would also make sense to add the `/config` endpoint there (open for discussion).

Follow-up to: https://github.com/owncloud/ocis/issues/8783

**Comment by tbsbdr** [comment]
wont fix
