### ISSUE TITLE
Activity: new renamed folder name shown in previous folder share activity

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/ocis#10210]
## Describe the bug
Sharing folder activity before renaming the folder contains the renamed folder name.

## Steps to reproduce
1. Create a folder "FOLDER"
2. Share folder "FOLDER" via link
3. Rename folder "FOLDER" to "FOLDER RENAMED"

## Expected behavior
Old activity before renaming should contain old folder name i.e. "FOLDER" in this case.

## Actual behavior
New renamed folder name is shown in previous activity.

![image](https://github.com/user-attachments/assets/886eb644-0041-4ade-b2ca-73e75018d01e)

**Comment by micbar** [comment]
Nice catch! @tbsbdr
