### ISSUE TITLE
OCM. user loses the first share

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10222]
```
Web UI 10.3.0
Ocis: 6.5.0
```

Steps: 
`Given using server "LOCAL"`
`And "Alice" has generated invitation` - IMPORTANT to reproduce this bug: leave `open-cloud-mesh` app after this step
`And using server "REMOTE"`
`And "Brian" has accepted invitation`
`And "Brian" shares folder to "Alice"`
`"Alice" opens shares with me`

Expected: "Alice" has shared folder

Actual: "Alice" hasn't shared folder
if "Alice" opens `open-cloud-mesh` app again and after that "Brian" shares new folder to "Alice" - "Alice" can get new share but first share stills lost 

CC @kobergj

**Comment by ScharfViktor** [comment]
retested. It's not reproducing. probably fixed here https://github.com/owncloud/ocis/pull/10243

**Comment by ScharfViktor** [comment]
I could reproduce it again during the creating test https://github.com/owncloud/web/pull/11821

https://federation-ocis-server:10200/graph/v1beta1/me/drive/sharedWithMe has no files in response (but has folder)
<img width="1274" alt="Screenshot 2024-10-28 at 07 54 19" src="https://github.com/user-attachments/assets/2c8be919-cf5e-42b3-9c6c-5db9722c3da1">

**Comment by dragonchaser** [comment]
Investigating

**Comment by ScharfViktor** [comment]
tested again - seems that was fixed https://github.com/owncloud/ocis/commit/4792071d3d3600bac58e494dc13cf34605e15db0
