### ISSUE TITLE
Activities. downloaded activity shown while opening file via public link

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/ocis#10231]
## Describe the bug
Response message for downloading file is also given when file is opened via public link.

## Steps to reproduce
1. Create a file "testfile.txt".
2. Create public link share for file "testfile.txt".
3. As an unauthenticated user, open the file via public link using password.
4. Download the file.

## Expected behavior
Expected to see only one downloaded response message only when file is downloaded:
`testfile.txt was downloaded via public link XIunelbcNmBOhTS`

## Actual behavior
Two downloaded response message shown:
        - when file is opened.
        - when file is downloaded.

![image](https://github.com/user-attachments/assets/006354d3-9ed9-4b6c-9051-d11b4c51f780)

**Comment by saw-jan** [comment]
Should we accept this behaviour as the expected one? (though the event now is disabled)

CC @2403905 @kobergj
