### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by rusneustroevkz** [owncloud/ocis#10246]
## Describe the bug
Repository not found.

## Steps to reproduce
1. Visit https://github.com/gdexlab/go-render

### go.mod
https://github.com/thomaspoignant/go-feature-flag/blob/main/go.mod#L19

**Comment by micbar** [comment]
Please add more information. Which problem do you want to solve?

**Comment by rusneustroevkz** [comment]
i can't download https://github.com/thomaspoignant/go-feature-flag because of this package https://github.com/gdexlab/go-render not found
<img width="645" alt="Screenshot 2024-10-07 at 12 14 08" src="https://github.com/user-attachments/assets/1cdb42c2-7d59-4d8b-b4be-7cdedacae6d1">

**Comment by rusneustroevkz** [comment]
SOLVED! me help adding proxy server to go package management
```export GOPROXY=https://proxy.golang.org```

**Comment by micbar** [comment]
Maybe a valid point, but why is this related to that repository?

**Comment by micbar** [comment]
IMHO we do not import these packages in this project.

**Comment by rusneustroevkz** [comment]
@micbar check here https://github.com/thomaspoignant/go-feature-flag/blob/main/go.mod#L19
<img width="1247" alt="Screenshot 2024-10-07 at 13 42 28" src="https://github.com/user-attachments/assets/198e05e6-8350-4bf4-aa7a-0a21454b50a8">

**Comment by micbar** [comment]
where do we use that package?

**Comment by rusneustroevkz** [comment]
i'm sorry, create issue is not need repo

**Comment by rhafer** [comment]
Actually reva is using gdexlab/go-render in a view places: https://github.com/cs3org/reva/blob/edge/internal/http/services/archiver/handler.go#L43 mostly for debug logging AFAICS. Maybe it's time to look for alternatives.

**Comment by thomaspoignant** [comment]
I found randomly this conversation, I am the maintainer of `go-feature-flag`, I will take care of this one and try to replace this dependency which has disappeared.

Thanks @rusneustroevkz but next time post the issue directly on the repo 😉

**Comment by rhafer** [comment]
Opened https://github.com/cs3org/reva/issues/4912 because this is actually a reva issue.
