### ISSUE TITLE
Different remaining space base shown in space list and sidebar

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#10268]
There is also a bit of discrepancy in the UI regarding the remaining space.

In the space list (when using the table view instead of the grid view) we see the remaining diskspace listed as the remaining quota which is at least misleading, when quota > remaining diskspace.
![image](https://github.com/user-attachments/assets/862af0fe-91f6-4d52-8e0e-55d7ded5499d)

The the details view on the sidebar we the the quota usage calcuated based on the quota and actual space usage.
![image](https://github.com/user-attachments/assets/363f89d8-2b81-482c-b71a-4f4db48ecb2b)
 
This is at least confusing. Also I am wondering if we really should expose the remaining diskspace at all, independent of which blobstore is being used. At least we should make a clear differentiation between how much quota is used and the amount of remaining diskspace.

_Originally posted by @rhafer in https://github.com/owncloud/ocis/issues/9245#issuecomment-2368429330_

**Comment by kobergj** [comment]
Already landed in master
