### ISSUE TITLE
[QA] Client does not resume download from ocis after restart

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1026]
Client 2.7.2 on Linux connected to ocis-1.0.0-rc6 deployed via hetzner-deploy/make_ocis_eos_compose_test.sh

* connect client to server as user moss, wait for initial sync
* throttle the client bandwidth to 100kb download speed.
* add an 11 MB file to the server (in a different way, not through this client)
* the client starts downloading.
* when half of the file is downloaded, (after ca 1min) quit the client and restart the client.
* the client does not continue where it left off. The half downloaded file gets truncated.

![image](https://user-images.githubusercontent.com/1108546/101103876-2b3cc180-35ca-11eb-94c6-ebe1744df95e.png)

Expected behaviour: Using TUS, the client picks up the left-over temporary file and continues at its end.

Reported from CI a long time ago

## found when starting to run API tests with OCIS

try to download only a range of a file, e.g.: curl http://localhost:9140/remote.php/webdav/home/welcome.txt -u einstein:relativity -H "Range: bytes=51-77"
Expected behaviour:

only a range of the file should be downloaded
Actual behaviour:

the complete file is downloaded

**Comment by individual-it** [comment]
ToDo for QA-Team:
- [ ] implement range request tests for oc10, those then should also work in OCIS after the functionality is added (I guess it works using the `Range` https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests)

**Comment by individual-it** [comment]
here also an old issue about range download https://github.com/owncloud/ocis-reva/issues/12

**Comment by C0rby** [comment]
This seems to be working now. Range requests have been implemented 11 months ago.
Range requests via curl and resumed download in the client work. :+1:
