### ISSUE TITLE
[QA] OCM - a federated folder randomly shows 'enable sync' message

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#10271]
## Describe the bug
A user who received a shared folder via federation sees a random message, when trying to enter the folder.

## Steps to reproduce
Setup three machines with e.g.

env OCIS_DNSNAME=dog-DATE OCIS_VERSION=daily ./deploy_ocis_bare_metal.sh
env OCIS_DNSNAME=cat-DATE OCIS_VERSION=daily ./deploy_ocis_bare_metal.sh

* user alice at cat visits the sciencemesh app and create an invite token for user bob at dog.
* user bob at dog enters the token, and shares a folder smallpics (continaing some png and jpg images) with alice ad cat
* user alice clicks Shares in the left sidebar, and clicks smallpics, a message appears: BAD
![image](https://github.com/user-attachments/assets/69835d96-e756-4754-88d1-f50f2e068c63)
* alice follows the instructions, and switches from the 'v enable sync' to the '(-) disable sync' seting.
* alice retries to enter the folder, it works now. OK
* A while later, alice tries again, and the message re-appears. BAD, the setting is still '(-) disable sync' 
* Alice will randonly see the message sometimes, and sometimes directly the folder contents. Both, with disabled and enabled sync.

## Expected behavior
* Sync should be default enabled. No?
* At least after manually enabling, it should work consistently.

Seen with both, ocis-6.5.0 and today's daily build 2024-10-09

**Comment by JammingBen** [comment]
I guess this will be fixed via https://github.com/owncloud/web/pull/11758

**Comment by jnweiger** [comment]
Still seen with https://download.owncloud.com/ocis/ocis/daily/ocis-testing-linux-amd64 this morning.

**Comment by JammingBen** [comment]
Web has not yet been updated in oCIS, this will happen at the end of this week.

**Comment by jnweiger** [comment]
As per today's daily, receiving an invitation fails with "An error occured".  The mentioned request ID is not helpful:

journalctl -u ocis | grep c1743203-e594-43e2-9a9b-cd171d0e971b
Oct 22 12:55:52 jw-ocis-daily-7tq ocis[5867]: {"level":"debug","service":"ocm","pkg":"rhttp","traceid":"8cd34e0101c98b9e008fcfa29b658f51","request-id":"c1743203-e594-43e2-9a9b-cd171d0e971b","path":"/accept-invite","time":"2024-10-22T12:55:52Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/http/services/sciencemesh/sciencemesh.go:139","message":"sciencemesh routing"}
Oct 22 12:55:52 jw-ocis-daily-7tq ocis[5867]: {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"c1743203-e594-43e2-9a9b-cd171d0e971b","traceid":"8f21d8c0cc9da90fc051c2ef5789c222","remote-addr":"87.156.130.141","method":"POST","status":401,"path":"/sciencemesh/accept-invite","duration":49.400679,"bytes":74,"time":"2024-10-22T12:55:52Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
