### ISSUE TITLE
Activity. "was downloaded via public link" activity looks as spam

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10293]
ocis 6.5.0
web. 10.3.0

related: https://github.com/owncloud/ocis/issues/10295

Steps: 
- admin creates space (or folder) and uploads inside 10 .png and .txt files
- admin creates public link to space/folder
- public opens link -> makes refresh page twice or more
- admin opens activity

Actual: hundreds of activities that public downloads file
<img width="1154" alt="Screenshot 2024-10-14 at 12 26 40" src="https://github.com/user-attachments/assets/3dacfac3-bc98-43f3-b1b1-e298ef0059e9">

**Comment by dragotin** [comment]
If we could destinguish a notification type and the affected resource, the clients could "condens" the view, ie by displaying "file foobar.png was downloaded 15 times".

According to @kulmann the activity identifier is missing in the activity data. Please add that  @micbar. After that, @bkulman please build a more condensed view.

**Comment by ScharfViktor** [comment]
the problem here is that activity generates for GET preview and HEAD preview request
- admin adds 5 .png files to folder and creates public link to folder
- public opens link (admin gets 5 activity for HEAD preview request, and 5 activities for GET preview request) 
- public opens file detail (+1 activity again)
- public opens one .png file in the image preview (+5 activity again)
- public refresh page (+10 activities again)

Total: 26 activities that `file.png was downloaded via public link WylawZkpQWBVlpe`. 
Public hasn't downloaded the file once.

**Comment by kobergj** [comment]
> Public hasn't downloaded the file once.

This isn't correct. When you open a public link (or refresh it) the file WILL be downloaded from the webclient. You don't have the effect when opening a folder.

> "file foobar.png was downloaded 15 times".

This is probably the best option. Not sure if aggregating frontend or backend side is better. Probably both has its (dis-) advantages.

**Comment by kobergj** [comment]
> IMHO was downloaded in user context that is pressing the download button for the resource and getting file in file system?

I agree. But the server only sees the request to download the file, not the user pressing the download button. This is only happening on the client side.

**Comment by butonic** [comment]
Hm when I share an image with a public link and then open the link in a private window I can see an actual GET request to the full image, but I had to search the UI for the actual download action. So in theory we can differentiate thumbnail and actual download requests.

**Comment by micbar** [comment]
# Decision

- Fix it or
- Disable it if the fix exceeds the time slot

**Comment by saw-jan** [comment]
>Public hasn't downloaded the file once.
>>This isn't correct. When you open a public link (or refresh it) the file WILL be downloaded from the webclient. You don't have the effect when opening a folder.

We have an open issue for this behavior: https://github.com/owncloud/ocis/issues/10231
