### ISSUE TITLE
Activity. link token in activity confused users

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10295]
I found a few problems while increasing the coverage for activity.feature

ocis  6.5.0
web. 10.3.0

~~1. ## superfluous activities fixed via https://github.com/owncloud/web/pull/11770~~
~~Steps:~~
~~- admin creates space link (view role by default)~~
~~- admin changes link role to edit role~~
~~- admin sees activity~~

~~Actual:~~
<img width="1760" alt="Screenshot 2024-10-11 at 14 42 09" src="https://github.com/user-attachments/assets/b403ff4c-b126-4599-ad9a-a4758818a284">

~~reason: we send `@libre.graph.displayName` and `type` in the PATCH body request if we only update displayName or type(permission)~~

1.1  ## superfluous activities - https://github.com/owncloud/ocis/issues/10293
~~Steps: ~~
~~- admin creates space link with edit role~~
~~- public updates file file.txt (public opens file in text editor- put content-> save->close editor)~~
~~- admin sees activity~~

~~Actual: ~~
<img width="458" alt="image" src="https://github.com/user-attachments/assets/374a0377-1d7f-47a4-9816-a2d2f4a296d1">

~~Expected: `file.txt was downloaded via public link fguCwoKHERsDYim` is superfluous.~~

2. ## link token in activity confused users. I first noticed this when I updated the link password and wondered if I was seeing the password in activity (it was link token)
Steps:
- admin creates 2 space links (Unnamed link and new link)
- admin changes role of the new link
- admin sees activity

Actual: `Admin updated permission for a link fhLLZLQKeooTvry on s2`
I know that `fhLLZLQKeooTvry` is link token 
But for many users, this may not be obvious
<img width="428" alt="image" src="https://github.com/user-attachments/assets/18830d7a-9483-4e28-a2b7-278a1a1f0afa">

Expected: `Admin updated permission for a link new on s2` 
If we have both Unnamed links -> here is question but maybe better to provide `Admin updated permission for a link Unnamed on s2`. not sure here

**Comment by AlexAndBear** [comment]
Transferred to ocis repo, as #1 has been fixed via https://github.com/owncloud/web/pull/11770

**Comment by 2403905** [comment]
@micbar @AlexAndBear Web sends the `displayName: "Unnamed link"` each time for the link create request. That makes all links identical for the user after the `webUrl` has been hidden.

**Comment by AlexAndBear** [comment]
@2403905 Well, this is on purpose, users can update the links later and give them names (but I don't think this is the usual case). 

@ScharfViktor suggested

> If we have both Unnamed links -> here is question but maybe better to provide Admin updated permission for a link Unnamed on s2. not sure here

**Comment by 2403905** [comment]
@AlexAndBear  Does it look good to the user?
<img width="424" alt="Screenshot 2024-11-25 at 18 36 07" src="https://github.com/user-attachments/assets/4e835c90-cd63-40f1-9d11-bb7d381e11fa">

**Comment by AlexAndBear** [comment]
@2403905 I don't get the question

**Comment by micbar** [comment]
Or, alternatively show the proposed display name in a pre filled input field, where the user could change it during creation already. I think only a very few users get the fact that the tree dots are offering a rename.

**Comment by JammingBen** [comment]
It was a decision @tbsbdr , @kulmann and I made together to communicate to the user that these links have not been given a name (yet). I don't really understand how this looks like a bug 🤔 The redesign just made the name more prominent, I don't think many users noticed the name before at all.

**Comment by AlexAndBear** [comment]
Talked with @micbar and @2403905 about the "Unnamned link" thingy, and decided to leave everything as it is, for now

**Comment by ScharfViktor** [comment]
> Talked with @micbar and @2403905 about the "Unnamned link" thingy, and decided to leave everything as it is, for now

I think we're off track:

how should looks activity? 
- with link token
<img width="381" alt="Screenshot 2024-11-26 at 14 15 09" src="https://github.com/user-attachments/assets/7d523b78-0229-412c-b34b-2bbf504f8146">

or
- with link name: `Admin updated permission for a link Unnamed on s1`

**Comment by 2403905** [comment]
It will be like this

<img width="435" alt="Screenshot 2024-11-26 at 16 28 53" src="https://github.com/user-attachments/assets/874f3d9c-d0f3-43c9-9970-feb94ef9623c">
