### ISSUE TITLE
[Desktop] Capability needed to announce availability of new WebDAV endpoint

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#1030]
Desktop client supports both old (`/remote.php/webdav/`) and new (`/remote.php/dav/files/username/`) WebDAV endpoint.

In oC10, backend announced capability implicit with availability of chunking NG `"chunking": "1.0",`.

oCIS never learned chunking, so it announces `"bigfilechunking": false,` and `"chunking": "",`, but this means desktop client assumes only old WebDAV endpoint is available.

```
PROPFIND https://ocis.owncloud.works/remote.php/webdav/
```

**Problem:**
New features like TUS are only implemented against new WebDAV endpoint, so desktop client uses a wild mixup of old and new WebDAV endpoint:

```
POST https://ocis.owncloud.works/remote.php/dav/files/username/
```

Enterprise admins and network/endpoint security folks won't like such behaviour.

(Latest Android and iOS apps only support new WebDAV endpoint, so not a problem for them)

@TheOneRing any wishes how such a capability could look like?

**Comment by TheOneRing** [comment]
The old endpoint is needed for the old chunking, so we could also assume the old chunking is not available if tus is enabled.

**Comment by michaelstingl** [comment]
> we could also assume the old chunking is not available if tus is enabled.

Yes, if TUS is announced, new endpoint will definitely work 👍 

@butonic @MarWeb88 CERN edge cases we forgot?

**Comment by refs** [comment]
ping @butonic
