### ISSUE TITLE
[QA] OCM: upload into received federated folder shows an error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#10305]
## Describe the bug
A user who received a shared folder via federation cannot view images. The image viewer hangs

## Steps to reproduce
Setup two federated machines with e.g.

env OCIS_DNSNAME=dog-DATE OCIS_VERSION=daily ./deploy_ocis_bare_metal.sh
env OCIS_DNSNAME=cat-DATE OCIS_VERSION=daily ./deploy_ocis_bare_metal.sh
ocm_trust.sh dog-20241015.jw-qa.owncloud.works cat-20241015.jw-qa.owncloud.works

* admin adds the instances to each other's ocmproviders.json .
* user alice at cat visits the sciencemesh app and create an invite token for user bob at dog.
* user bob at dog enters the token, and shares a folder smallpics (continaing some png and jpg images) with alice ad cat
* user alice clicks Shares in the left sidebar, and clicks smallpics ( see #10271 )
* user alice uploads a folder (with 15 files) into the received share. The upload succeeds, but an error is shown:

![image](https://github.com/user-attachments/assets/6b349b7d-9eee-4f93-9594-1038eebd0f11)
----

* Clicking on 'details' make the error disappear, instead of showing details. BAD

Seen with https://download.owncloud.com/ocis/ocis/daily/ocis-testing-linux-amd64 today morning.

Infinite Scale 6.5.0+6bde4ef95 Community
ownCloud Web UI 10.3.0

**Comment by JammingBen** [comment]
https://github.com/owncloud/ocis/issues/10285 related maybe?

**Comment by saw-jan** [comment]
> #10285 related maybe?

ocis crash is fixed but the upload (tus upload) still doesn't work

**Comment by ScharfViktor** [comment]
Maybe a misconfiguration? after last @rhafer fix https://github.com/owncloud/ocis/pull/10501
I can: 
- upload to shared folder - https://github.com/owncloud/ocis/issues/10489
- see thumbnails - https://github.com/owncloud/ocis/issues/10495



https://github.com/user-attachments/assets/bfb92ae9-a9d5-410a-baf9-4d92df2ba7bb

**Comment by saw-jan** [comment]
>Maybe a misconfiguration? after last @rhafer fix https://github.com/owncloud/ocis/pull/10501

Yeah, the upload works on the share received from the federation server. So, it's likely a config issue in the federation server
