### ISSUE TITLE
Missing Strings for Translation

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#10336]
Collection of strings that are not offered in transifex for translation

- [ ] Role description `View, download, ... including the history`
![screenshot_003215](https://github.com/user-attachments/assets/2281dc56-d65f-47dc-bf61-69cfa0bcb2a0)

- [ ] `Extract here` from the unzip extension

**Comment by JammingBen** [comment]
Role descriptions are fully translated by now: 
<img width="409" alt="image" src="https://github.com/user-attachments/assets/ece2a35f-76b7-49d4-9deb-6cd55125885f">

`Extract here` is translated in the new `0.3.0` release of the unzip app.
