### ISSUE TITLE
OCM cannot open shared file

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#10358]
## Describe the bug
When I share a file using OCM, I cannot open it as the share receiver.

## Steps to reproduce
1. use the OCM deployment example from https://github.com/owncloud/ocis-charts/pull/701/
2. share a text file from oCIS 1 to oCIS 2
3. open the text file as share receiver

## Expected behavior

The text file can be opened and edited.

## Actual behavior

https://ocis.kube.owncloud.test/remote.php/dav/spaces/89f37a33-858b-45fa-8890-a1f2b27d90e1%24c04eee26-d9b9-4238-9b51-4aeb3b9f330b!Lw%3D%3D fails with HTTP 500

```
proxy-65d7c5746f-qp4nj proxy {"level":"error","service":"proxy","error":"failed to verify access token: token is malformed: token contains an invalid number of segments","authenticator":"oidc","path":"/dav/ocm/5caffad9-acff-480b-a370-5e3c1e0e87cb/","user_agent":"Go-http-client/1.1","client.address":"10.244.0.1","network.peer.address":"","network.peer.port":"","time":"2024-10-21T09:37:47Z","message":"failed to authenticate the request"}
proxy-65d7c5746f-qp4nj proxy {"level":"error","service":"proxy","error":"failed to verify access token: token is malformed: token contains an invalid number of segments","authenticator":"oidc","path":"/dav/ocm/5caffad9-acff-480b-a370-5e3c1e0e87cb/","user_agent":"Go-http-client/1.1","client.address":"10.244.0.1","network.peer.address":"","network.peer.port":"","time":"2024-10-21T09:37:47Z","message":"failed to authenticate the request"}
```

## Setup

oCIS 6.5 deployed with https://github.com/owncloud/ocis-charts/pull/701/

**Comment by rhafer** [comment]
I've been able to reproduce the problem using the above referenced ocis-charts PR.  I am still trying to figure out what exactly is wrong because it works just fine for me in a manually created docker setup.

**Comment by rhafer** [comment]
Argh: https://github.com/owncloud/ocis/blob/master/services/ocm/pkg/revaconfig/config.go#L166

We're setting the `data_server_url` for the ocm storageprovider is set to the listen address of the http endpoint. Which in case of a helm deployment is `0.0.0.0:9280`. That can't work as a download url.

To fix we need to introduce a `data_server_url` setting similar to what we have already for the other storage providers.

**Comment by rhafer** [comment]
The above reference PR should fix the issue.

@wkloucek This requires setting OCM_OCM_STORAGE_DATA_SERVER_URL in the ocm helm deployment obivously. (See e.g. storage-users)
