### ISSUE TITLE
Authentication failed LDAP

### ISSUE THREAD

**Issue by pauleseifert** [owncloud/ocis#10350]
## Describe the bug
There seems to be a problem with the certificate check in ocis5.0.8. I don't use LDAP for authentication and set up a basic docker configuration. Please find my docker-compose below. 

When I want to log in to the web portal, I get an authentication failed error. The corresponding debug from the container is:

`2024-10-18T12:27:03Z ERR IdentifierIdentityManager: fetch failed to get user from userID error="ldap identifier backend get user connect error: LDAP Result Code 200 \"Network Error\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-10-18T12:27:03Z is after 2024-10-18T08:29:32Z" line=github.com/owncloud/ocis/v2/ocis-pkg/log/logrus_wrapper.go:50 service=idp `

Setting the environment variable OCIS_LDAP_INSECURE: true resolves the issue. However, I would expect that the certificate either renews itself or is not checked since I haven't integrated an LDAP service. 

Could it be related to PROXY_ENABLE_BASIC_AUTH: true, which I need for webdav? If yes, what should I change in the config?

## Steps to reproduce
1. Spin up ocis5.0.8 on docker.
2. let the LDAP certificate, created at setup, expire.
3. try to log in.

## Expected behavior
Login 
## Actual behavior
A clear and concise description of what happened.
Authentication failure
## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```docker compose
networks:
  <redacted>:
    external: true
services:
  ocis:
    hostname: owncloud
    image: owncloud/ocis:5
    dns:
      - 1.1.1.1
    networks:
      - <redacted>
    environment:
      OCIS_SERVICE_ACCOUNT_ID: "<redacted>"
      OCIS_SERVICE_ACCOUNT_SECRET: "<redacted>"
      OCIS_INSECURE: false
      #OCIS_LDAP_INSECURE: true
      FRONTEND_ARCHIVER_MAX_SIZE: "53687091200"
      OCIS_LOG_COLOR: true
      OCIS_LOG_PRETTY: true
      PROXY_ENABLE_BASIC_AUTH: true
      OCIS_URL: "<redacted>"
      OCIS_LOG_LEVEL: debug
    volumes:
      - <redacted>
    restart: unless-stopped
```

</p>
</details>

**Comment by micbar** [comment]
> Setting the environment variable OCIS_LDAP_INSECURE: true resolves the issue. However, I would expect that the certificate either renews itself or is not checked since I haven't integrated an LDAP service.

We have the requirement that we are "secure by default". Auto-Renewal is out of scope for the built-in Idm.

## Solution

Just delete `ldap.crt` and `ldap.key` and restart.

**Comment by maxcynicle** [comment]
I've been locked out of my OCIS instance since June, and I finally chanced upon this. Can confirm the above works for me.

**Comment by pauleseifert** [comment]
Can confirm that too but why have the pain of manually deleting the cert, redeploy the instance to create a new one than just automatically renewing the cert?

**Comment by micbar** [comment]
> Can confirm that too but why have the pain of manually deleting the cert, redeploy the instance to create a new one than just automatically renewing the cert?

You asked for it 😄 Let me explain.

The built-in LDAP server is there to test ocis and run some evaluation setups. The default setup needs to be "secure by default" because most people would run it on a shared environment.
So the expiration time of the Certs is long enough. 

For running ocis continuously in production we always suppose to use a productive LDAP server like OpenLDAP.

**Comment by thieman** [comment]
If I'm understanding correctly, this is a pretty terrible end user experience. If OCIS is fine issuing the cert in the first place, then it needs to also be fine renewing it. Otherwise, this ends up randomly breaking your install without the operator even understanding that this was their responsibility in the first place (the situation I find myself in now). I get the desire to be secure-by-default, but there must be a way to achieve that without surprise breakages down the line.

**Comment by micbar** [comment]
You should use a proper OpenLdap service and take care of the cert by a certbot like letsencrypt.

**Comment by HardoA** [comment]
Same issue here. A quick solution to delete the files but I agree that this is a terrible user experience for folks who do not use LDAP with a simple install.

Can we get a solution for this or should simple installs expect to have to do this manual step every time a cert expires? In that case I rather migrate to an alternative option.

**Comment by pauleseifert** [comment]
I think it could be more prominently highlighted in the installation guides that an LDAP service is required to run OCIS permanently. However, I agree that it makes sense to separate user management from the file service.

**Comment by jacobgkau** [comment]
Do you have an officially recommended third-party LDAP service that's supported, since that's apparently an undocumented requirement to keep a server running without manual intervention such as deleting certificate files every time they expire?

**Comment by jacobgkau** [comment]
@micbar Do you have an officially recommended third-party LDAP service that's supported, since that's apparently an undocumented requirement to keep a server running without manual intervention such as deleting certificate files every time they expire?

**Comment by micbar** [comment]
Yes. It is openLdap. There are containers from bitnami which are quite good.

**Comment by jacobgkau** [comment]
Gotcha. OpenLDAP requires a handful of configuration files and dozens of lines of configuration (with commands interspersed between different points in the configuration) to get basic functionality for even a single user up-and-running. The Bitnami container's readme examples show setting a list of usernames and passwords as environment variables when launching the container, which seems super clunky and not very secure, itself.

Would an alternative implementation like lldap (which actually provides a point-and-click way to change a user's password, for example) work with ownCloud, or does OCIS require additional LDAP features only present in OpenLDAP?

**Comment by micbar** [comment]
@rhafer Could you help out?

**Comment by kaivol** [comment]
This seems to be the same issue as https://github.com/owncloud/ocis/issues/8552.

If I understood the discussion correctly at the time, the consensus was that the current setup is okay and that for the _single binary setup_ we do not actually need TLS for LDAP.

**Comment by thieman** [comment]
Can you clarify the current state? Can we _currently_ disable TLS and therefore use `lldap`? Or are you saying we would like to be able to do that in the future? It seems like quite a few of us have simple installs for personal use, I'd like the simplest possible LDAP solution that will stop my instance from bricking itself once a year.

**Comment by thieman** [comment]
Also, is it possible to migrate to a new LDAP provider on an existing instance? Are there any steps required there to preserve the existing user data?
