### ISSUE TITLE
OCM invitations are stored in-memory

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#10354]
## Describe the bug
To me it looks like OCM invitations are stored in memory, which is a no-go for production systems.

## Steps to reproduce
1. Generate an OCM invitation
2. Restart the OCM service
3. List the invitations

## Expected behavior
The invitation is still there.

## Actual behavior
The invitation is gone.

## Setup

Running oCIS 6.5 using the chart and deployment example from https://github.com/owncloud/ocis-charts/pull/701

**Comment by micbar** [comment]
@butonic please clarify if that is true.

@wkloucek do you persist the volume where the ocm share stores the json file?

**Comment by wkloucek** [comment]
> do you persist the volume where the ocm share stores the json file?

Seems like no. Thanks for that pointer.

**Comment by wkloucek** [comment]
Fixed by enabling OCM persistent volume for the deployment example in https://github.com/owncloud/ocis-charts/pull/701/commits/fb4b91bb38127cf48f775d550368ac7ab6c75663

Sorry for the noise! :grimacing:
