### ISSUE TITLE
[QA] add tests for new template for WebOffice

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#10367]
ocis has various template files for OnlyOffice and Collabora. 

https://github.com/owncloud/ocis/pull/10276
https://github.com/owncloud/ocis/issues/9785

- [x] check for app/list
```json
    {
      "mime_type": "application/vnd.oasis.opendocument.spreadsheet-template",
      "app_providers": [
        {
          "address": "com.owncloud.api.collaboration.OnlyOffice",
          "name": "OnlyOffice",
          "description": "Open office documents with Collabora",
          "icon": "https://onlyoffice.owncloud.test/web-apps/apps/documenteditor/main/resources/img/favicon.ico",
          "secure_view": false,
          "target_ext": "xlsx"
        }
      ]
    }
```
check for `mime_type` and `target_ext`

| OnlyOffice                                                              | Collabora                                                |
|-------------------------------------------------------------------------|----------------------------------------------------------|
| application/vnd.ms-word.template.macroenabled.12                        | application/vnd.oasis.opendocument.spreadsheet-template  |
| application/vnd.oasis.opendocument.text-template                        | application/vnd.oasis.opendocument.text-template         |
| application/vnd.openxmlformats-officedocument.wordprocessingml.template | application/vnd.oasis.opendocument.presentation-template |
| application/vnd.oasis.opendocument.spreadsheet-template                 |                                                          |
| application/vnd.ms-excel.template.macroenabled.12                       |                                                          |
| application/vnd.openxmlformats-officedocument.spreadsheetml.template    |                                                          |
| application/vnd.oasis.opendocument.presentation-template                |                                                          |
| application/vnd.ms-powerpoint.template.macroenabled.12                  |                                                          |
| application/vnd.openxmlformats-officedocument.presentationml.template   |                                                          |

- [x] check for app/open with `template_id` parameter

**Comment by amrita-shrestha** [comment]
test has been added
