### ISSUE TITLE
Open native apps from web UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#1037]
I often receive private links while being on my desktop computer or on my mobile device. To analyse log files or edit source code, I often prefer native 3rd party applications. It would be handy if I could open the ownCloud native apps from the web UI.

![CleanShot 2020-12-08 at 17 18 25](https://user-images.githubusercontent.com/214010/101510594-6ba99000-397a-11eb-8f09-da358555c8d8.png)

(Showing the iOS action entry only when iOS browser is detected, with "magic link" like `owncloud://cloud.example.com/f/12345` to open this resource in the iOS app, similar for desktop and Android)

Inspiration for desktop: https://github.com/nextcloud/desktop/issues/1321

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
