### ISSUE TITLE
[QA] review all TODOs in test code

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#10389]
There are few TODOs in our test code instead of commenting on the code a issue should be created for it.

- [TrashbinContext.php](https://github.com/owncloud/ocis/blame/261387637dd9165269d25fbf358026d92776bec5/tests/acceptance/bootstrap/TrashbinContext.php#L724) @S-Panta https://github.com/owncloud/ocis/pull/10424
- [behat.yml](https://github.com/owncloud/ocis/blob/261387637dd9165269d25fbf358026d92776bec5/tests/acceptance/config/behat.yml#L17) https://github.com/owncloud/ocis/pull/10434
- [WebDav.php](https://github.com/owncloud/ocis/blob/261387637dd9165269d25fbf358026d92776bec5/tests/acceptance/bootstrap/WebDav.php#L1582)  https://github.com/owncloud/ocis/issues/10435 https://github.com/owncloud/ocis/pull/10436
- [WebDavHelper.php](https://github.com/owncloud/ocis/blame/261387637dd9165269d25fbf358026d92776bec5/tests/acceptance/TestHelpers/WebDavHelper.php#L876C9-L876C13)  https://github.com/owncloud/ocis/issues/10529 https://github.com/owncloud/ocis/pull/10535
- [searchFederationUsers.feature](https://github.com/owncloud/ocis/blame/261387637dd9165269d25fbf358026d92776bec5/tests/acceptance/features/apiOcm/searchFederationUsers.feature#L713) -> Tracked in:https://github.com/owncloud/ocis/issues/10073

**Comment by S-Panta** [comment]
Closing this issue as ocm related issue is tracked by https://github.com/owncloud/ocis/issues/10073
