### ISSUE TITLE
Post Request To TUS Upload A File To A Non-Existing Directory Responds With 200 Status but The Patch Request Response does not contain a body

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1039]
## Description: 
Post Request To Upload A File To A Non-Existing Directory Responds With 200 Status And The Patch Request Response doesnot contain a body, even though the header has body specifications.

 The Post request such as : ` curl --user "admin:admin" --header "Tus-Resumable: 1.0.0" --header "Upload-Length: 16" --header "Upload-Metadata: filename L25vbkV4aXN0ZW50Rm9sZGVyL3RleHRmaWxlLnR4dA==" --user-agent "GuzzleHttp/7" --header "X-Forwarded-For: 127.0.0.1" --data "uploaded content" https://localhost:9200/remote.php/webdav/ -v -k ` gives the `HTTP/1.1 201 Created` response in owncloud-storage. 

The respone contains: 

`Location: https://localhost:9200/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjU5MzUyODU2LCJpYXQiOjE2MDc1MTI4NTYsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1NS9kYXRhL3R1cy9hZDIwNjFhOS01MTkzLTQwNjUtYjI5NS0wZjVlMWI5N2EyNTQifQ.enfE8jL-5AHomRE2eY8QOsPVg06O3dPZJon44ILZx78`

And then the Patch request as: `curl -XPATCH "https://localhost:9200/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjU5MzUyODU2LCJpYXQiOjE2MDc1MTI4NTYsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1NS9kYXRhL3R1cy9hZDIwNjFhOS01MTkzLTQwNjUtYjI5NS0wZjVlMWI5N2EyNTQifQ.enfE8jL-5AHomRE2eY8QOsPVg06O3dPZJon44ILZx78" -H 'Content-Length: 16' --user 'admin:admin' -H 'Content-Type: application/offset+octet-stream' -H 'Upload-Offset: 0' -H 'Tus-Resumable: 1.0.0' --data "uploaded content" -v -k` gives the response as : 
```
 HTTP/1.1 404 Not Found
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 09 Dec 2020 07:18:36 GMT
< Tus-Resumable: 1.0.0
< Upload-Offset: 16
< Vary: Origin
< X-Content-Type-Options: nosniff
transfer closed with 17 bytes remaining to read
```

**Comment by jasson99** [comment]
This might be related to: https://github.com/owncloud/ocis/issues/949

**Comment by kobergj** [comment]
Seems fixed. Ocis returns `412 Precondition Failed` now when trying to upload to a not existing folder.
