### ISSUE TITLE
Size of uploaded folder differs from upload to upload

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#10396]
## Describe the bug
I have a folder with 10 6 byte files, meaning the folder has a size of 60 bytes. When uploading the folder several times, the folders have a different size in the `PROPFIND` response.

## Steps to reproduce
1. Create a folder with multiple small files, e.g. 10 6 byte files.
2. Upload the folder multiple times.
3. Do a `PROPFIND` on the parent folder and compare the `oc:size` properties in the response.

## Expected behavior
All folders should have the same size.

## Actual behavior
The size might differ from folder to folder.

**Comment by rhafer** [comment]
@JammingBen  Are you still able to reproduce this? It seems to work just fine here with the latest code.

I assume you're uploading with the WebUI?
Any special config options for oCIS?

**Comment by JammingBen** [comment]
Now I can't reproduce it either. Maybe it has been fixed, maybe I messed something up 🤷
