### ISSUE TITLE
E-Mail-Notification Templates - Received mails are blank. 

### ISSUE THREAD

**Issue by 2xDIYGN** [owncloud/ocis#10406]
## Describe the bug

When receiving a E-Mail notifiation while branding is enabled with a custom mail-template the standard message body is blank.

## Steps to reproduce
1. Deploy ocis 5.0.7 with Helm
2. Enable e-mail Notifications branding and add  configrefs containing Mail-Template in the values.yaml
3. Send a test mail by adding a user to a space 

## Expected behavior

E-Mail notifications should contain the standard message body when using a custom template. 
If the branding is disabled the standard message body is being correctly send.

## Actual behavior
A clear and concise description of what happened.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.
ocis 5.0.7 deployed with HELM

This is how the received mail looks like:
![Screenshot 2024-10-22 143957](https://github.com/user-attachments/assets/ded32fd7-7c66-4f85-baf0-8765d742efce)

And this is the source html of the received mail:
![Screenshot 2024-10-22 144730](https://github.com/user-attachments/assets/8810a5f6-017c-46bc-b76b-54f98b6a417c)

Following email.text.tmpl and email.html.tmpl were used in configmaps:
![Screenshot 2024-10-22 1420](https://github.com/user-attachments/assets/340d7b0f-46a2-4dea-9543-bd9cf00f85dd)
![Screenshot 2024-10-22 144604](https://github.com/user-attachments/assets/dd025450-6b67-4d7b-9c80-e7c7dad2e6f0)

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by fschade** [comment]
Thanks for the Report, can you please Share the config and Template as gist?

**Comment by 2xDIYGN** [comment]
Hello, here is the link: https://gist.github.com/2xDIYGN/d2d8036c41dce4d060779c02127356bf

**Comment by 2403905** [comment]
I assume that the HELM replaced the email variables because the syntactic the similar `{{ .Greeting }}`

**Comment by butonic** [comment]
you can try sth like this:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: text-mail-templates
data:
  email.text.tmpl: |-
    {{`{{ .Greeting }}
    {{ .MessageBody }}
    {{if ne .CallToAction "" }}
    {{ .CallToAction }}
    {{end}}
    ---
    TEST.
    https://test.example.com/`}}
```
the curly `{{` ... `}}` should ignore any go rules inside the template

**Comment by 2403905** [comment]
@2xDIYGN Is your issue resolved?
