### ISSUE TITLE
Podman rootless + nginx proxy manager: failed to authenticate the request

### ISSUE THREAD

**Issue by danielpinto8zz6** [owncloud/ocis#10446]
## Describe the bug
Hi, I'm using podman rootless with nginx proxy manager as reverse proxy, after running the init setup and running the container, I'm not able to login, I got the following error: 
```
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://my-address.void/.well-known/openid-configuration\": dial tcp 10.0.0.4:443: connect: connection refused","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2024-10-31T01:47:30Z","message":"failed to authenticate the request"}
```

## Steps to reproduce
1. Init config
```
podman run --rm -it \
    --network=npm \
    --userns=keep-id \
    --user 1000:1000 \
    -v /owncloud/config/:/etc/ocis:Z \
    docker.io/owncloud/ocis init
```
2. Run podman ocis quadlet:
```
[Unit]
Description=OwnCloud Quadlet

[Container]
ContainerName=owncloud
HostName=owncloud

Image=docker.io/owncloud/ocis:latest

Environment=OCIS_INSECURE=true
Environment=OCIS_LOG_LEVEL=error
Environment=PROXY_HTTP_ADDR=0.0.0.0:9200 \
Environment=PROXY_TLS=false
Environment=OCIS_URL=https://my-address.void

PublishPort=9200:9200

Network=npm

User=1000
Group=1000
UserNS=keep-id

Volume=/owncloud/config:/etc/ocis:Z
Volume=/owncloud/data:/var/lib/ocis:z

AutoUpdate=registry

[Service]
Restart=unless-stopped

[Install]
WantedBy=default.target
```

3. Login with the init credentials

## Expected behavior
User login correctly

## Actual behavior
Login fails with following error:
```
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://my-address.void/.well-known/openid-configuration\": dial tcp 10.0.0.4:443: connect: connection refused","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2024-10-31T01:47:30Z","message":"failed to authenticate the request"}
```

**Comment by rhafer** [comment]
Does `my-address.void` resolve to the correct IP address inside the container. It needs to resolve to the IP that your nginx reverse proxy is running on.  (i.e. the ocis running inside the container needs to be able to access  itself via the reverse proxy)

**Comment by danielpinto8zz6** [comment]
Yes, I think so:
![Screenshot_20241031_145340](https://github.com/user-attachments/assets/60b6b7aa-e1be-49f0-abf4-271d358ffce7)
Maybe do I need to add extra configurations?

**Comment by danielpinto8zz6** [comment]
![Screenshot_20241105_185040](https://github.com/user-attachments/assets/bea334b3-678d-471e-bc47-6716ba985e3a)
Aparently it can resolve the address but got connection refused

**Comment by rhafer** [comment]
> Aparently it can resolve the address but got connection refused

But is it the correct IP? If yes, there might be some firewall blocking the traffic.

**Comment by danielpinto8zz6** [comment]
Yes it is, I cannot access localhost either

**Comment by danielpinto8zz6** [comment]
Ok, I got the issue,
Because I'm running rootless podman, I don't use ports 80 or 443, instead I have a firewall rule that redirects all trafic from 8080 and 8443 to the corresponding 80 and 443, and the problem is that this firewall rule is bypassed inside the container
