### ISSUE TITLE
500 Internal Server Error on Post request for TUS upload to a non-existing folder on the received share

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1047]
## Description:
- When the user tries to upload a file in the non-existing folder on the received share, the POST request responds with an internal server error

## Steps To Reproduce:
- Einstein creates folder "/FOLDER"
- Einstein shares folder "/FOLDER" with "Marie"
- Marie accepts share "/FOLDER" offered by user "Einstein"
- Marie uploads file with content "uploaded content" to "/Shares/FOLDER/nonExistentFolder/textfile.txt" using Tus Protocol

 Post request: `curl --user "marie:radioactivity" --header "Tus-Resumable: 1.0.0" --header "Upload-Length: 16" --header "Upload-Metadata: filename L1NoYXJlcy9GT0xERVIvbm9uRXhpc3RlbnRGb2xkZXIvdGV4dGZpbGUudHh0" --data "uploaded content" https://localhost:9200/remote.php/webdav/ -v -k`

The post request responds with:
`< HTTP/1.1 500 Internal Server Error
`

**Comment by jasson99** [comment]
The stack trace on the ocis server is as follows:
`2020-12-11T12:49:09+05:45 ERR error listing attributes error="xattr.list /var/tmp/ocis/owncloud/4c510ada-c86b-4815-8820-42cdf82c3d51/files/files/FOLDER.d1607670156/nonExistentFolder : no such file or directory" ipath=/var/tmp/ocis/owncloud/4c510ada-c86b-4815-8820-42cdf82c3d51/files/files/FOLDER.d1607670156/nonExistentFolder pkg=rgrpc service=storage traceid=059175fda58d31f39d4feea0a8576820
goroutine 62 [running]:
runtime/debug.Stack(0xc000697700, 0xc0017ab680, 0xbfece45a53d21804)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/cs3org/reva/internal/grpc/interceptors/recovery.recoveryFunc(0x3dbdce0, 0xc0008ec270, 0x3399700, 0x558a050, 0x14074d9, 0x0)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/internal/grpc/interceptors/recovery/recovery.go:48 +0x26
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x3dbdce0, 0xc0008ec270, 0x3399700, 0x558a050, 0x39018a8, 0xc000a2ec40, 0x13cc026)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/recovery/interceptors.go:61 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0xc000a2f44e, 0x3dbdce0, 0xc0008ec270, 0xc000013620, 0xc000a2f4d0)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/recovery/interceptors.go:29 +0x6d
panic(0x3399700, 0x558a050)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/cs3org/reva/pkg/storage/fs/owncloud.(*ocfs).InitiateUpload(0xc001838040, 0x3dbdce0, 0xc0008ec750, 0xc0008ec780, 0x10, 0xc0008ec7b0, 0x0, 0x8, 0xc000697860)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/pkg/storage/fs/owncloud/upload.go:131 +0x2d1
github.com/cs3org/reva/internal/grpc/services/storageprovider.(*service).InitiateFileUpload(0xc0000ef570, 0x3dbdce0, 0xc0008ec750, 0xc0008ec000, 0xc0000ef570, 0x3213da0, 0x3d0ef18)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/internal/grpc/services/storageprovider/storageprovider.go:322 +0x196
github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1._ProviderAPI_InitiateFileUpload_Handler.func1(0x3dbdce0, 0xc0008ec750, 0x369e7a0, 0xc0008ec000, 0x37459a0, 0xc000697800, 0x3dbdce0, 0xc0008ec750)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/go-cs3apis@v0.0.0-20201118090759-87929f5bae21/cs3/storage/provider/v1beta1/provider_api.pb.go:3833 +0x86
github.com/cs3org/reva/internal/grpc/interceptors/auth.NewUnary.func1(0x3dbdce0, 0xc0008ec270, 0x369e7a0, 0xc0008ec000, 0xc0002e55e0, 0xc0002e5600, 0x0, 0x0, 0x0, 0x0)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/internal/grpc/interceptors/auth/auth.go:124 +0xaa8
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3dbdce0, 0xc0008ec270, 0x369e7a0, 0xc0008ec000, 0x1412ac8, 0xc0008c5b60, 0x8, 0x58c23e8)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x3dbdce0, 0xc0008ec270, 0x369e7a0, 0xc0008ec000, 0xc0002e55e0, 0xc0002e5620, 0x0, 0x0, 0x0, 0x0)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/recovery/interceptors.go:33 +0xcb
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3dbdce0, 0xc0008ec270, 0x369e7a0, 0xc0008ec000, 0xc000100000, 0x7fca6f903560, 0x0, 0xc0002e5700)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/cs3org/reva/internal/grpc/interceptors/log.NewUnary.func1(0x3dbdce0, 0xc0008ec270, 0x369e7a0, 0xc0008ec000, 0xc0002e55e0, 0xc0002e5640, 0x0, 0xc0002e56e0, 0x1, 0x1)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/internal/grpc/interceptors/log/log.go:39 +0x9b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3dbdce0, 0xc0008ec270, 0x369e7a0, 0xc0008ec000, 0x2, 0x3dbdce0, 0xc0008ec270, 0xc0008ec240)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/cs3org/reva/internal/grpc/interceptors/token.NewUnary.func1(0x3dbdce0, 0xc0008ec210, 0x369e7a0, 0xc0008ec000, 0xc0002e55e0, 0xc0002e5660, 0x37b3bc0, 0xc00052bf20, 0x3dbdce0, 0xc0008ec210)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/internal/grpc/interceptors/token/token.go:44 +0xb4
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3dbdce0, 0xc0008ec210, 0x369e7a0, 0xc0008ec000, 0xc0008ec210, 0xc0007bfc00, 0x4f, 0x1f4)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/cs3org/reva/internal/grpc/interceptors/appctx.NewUnary.func1(0x3dbdce0, 0xc0008c5fb0, 0x369e7a0, 0xc0008ec000, 0xc0002e55e0, 0xc0002e5680, 0x27c8a3a, 0x35a1e60, 0xc0002e56a0, 0xc0002e55e0)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201203135805-655c9babdc3f/internal/grpc/interceptors/appctx/appctx.go:36 +0x4fc
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3dbdce0, 0xc0008c5fb0, 0x369e7a0, 0xc0008ec000, 0xc0017e4500, 0xc0002e5380, 0xc000971b08, 0x1372558)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x3dbdce0, 0xc0008c5fb0, 0x369e7a0, 0xc0008ec000, 0xc0002e55e0, 0xc0002e5600, 0xc0017d5b78, 0x1412668, 0x362ad80, 0xc0008c5fb0)
	/home/jasminebaral/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xd5
github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1._ProviderAPI_InitiateFileUpload_Handler(0x37f2900, 0xc0000ef570, 0x3dbdce0, 0xc0008c5fb0, 0xc00052be60, 0xc001820480, 0x3dbdce0, 0xc0008c5fb0, 0xc0003fa480, 0x87)
	/home/jasminebaral/go/pkg/mod/github.com/cs3org/go-cs3apis@v0.0.0-20201118090759-87929f5bae21/cs3/storage/provider/v1beta1/provider_api.pb.go:3835 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000409380, 0x3dde260, 0xc000546300, 0xc0017e4500, 0xc001820630, 0x55a7af0, 0x0, 0x0, 0x0)
	/home/jasminebaral/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000409380, 0x3dde260, 0xc000546300, 0xc0017e4500, 0x0)
	/home/jasminebaral/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd3f
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000055180, 0xc000409380, 0x3dde260, 0xc000546300, 0xc0017e4500)
	/home/jasminebaral/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/jasminebaral/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
2020-12-11T12:49:09+05:45 ERR runtime error: invalid memory address or nil pointer dereference pkg=rgrpc service=storage traceid=059175fda58d31f39d4feea0a8576820
2020-12-11T12:49:09+05:45 ERR unary code=Internal end="11/Dec/2020:12:49:09 +0545" from=tcp://127.0.0.1:45248 pkg=rgrpc service=storage start="11/Dec/2020:12:49:09 +0545" time_ns=21407010 traceid=059175fda58d31f39d4feea0a8576820 uri=/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileUpload user-agent=grpc-go/1.26.0
2020-12-11T12:49:09+05:45 ERR unary code=Unknown end="11/Dec/2020:12:49:09 +0545" from=tcp://127.0.0.1:42156 pkg=rgrpc service=storage start="11/Dec/2020:12:49:09 +0545" time_ns=35571588 traceid=059175fda58d31f39d4feea0a8576820 uri=/cs3.gateway.v1beta1.GatewayAPI/InitiateFileUpload user-agent=grpc-go/1.26.0
2020-12-11T12:49:09+05:45 ERR error initiating file upload error="rpc error: code = Unknown desc = gateway: error calling InitiateFileUpload: rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" path=/home/Shares/FOLDER/nonExistentFolder/textfile.txt pkg=rhttp service=storage traceid=059175fda58d31f39d4feea0a8576820
2020-12-11T12:49:09+05:45 ERR http end="11/Dec/2020:12:49:09 +0545" host=127.0.0.1 method=POST pkg=rhttp proto=HTTP/1.1 service=storage size=0 start="11/Dec/2020:12:49:09 +0545" status=500 time_ns=58778355 traceid=059175fda58d31f39d4feea0a8576820 uri=/remote.php/webdav/ url=/remote.php/webdav/
`

**Comment by kobergj** [comment]
Same as in https://github.com/owncloud/ocis/issues/1039 The panic is fixed and the endpoint returns `412 Precondition Failed` now.
