### ISSUE TITLE
OCM. user loses the shared folder that was copied

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10488]
ocis: 6.6.1+6f3322a3d
web: 11.0.1

setup: https://github.com/owncloud/web/blob/master/docker-compose.yml or https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm
Steps: 

- 2 users create connection
- `user1` creates folder `f1` with content and shares to `user2` -> `user2` can see folder `f1`
- `user1` copies folder `f1` to -> `f1 (1)` and shares again

Expected: user2 can see `f1 (1)` folder in Shares
Actual: user2 doesn't see `f1 (1)` folder in Shares

https://github.com/user-attachments/assets/c6fb37b0-4a28-4f11-9280-9a843534ce1d

maybe related https://github.com/owncloud/ocis/issues/10222

**Comment by rhafer** [comment]
This seems to be a problem with userCache in the graph service. (Creating multiple shares for the same user fails if the subsequent share is create before the user is expired in the cache).

Setting `GRAPH_SPACES_USERS_CACHE_TTL=1` seems to workaround the issue. A real fix is on the way.
