### ISSUE TITLE
Custom logo only loads after login

### ISSUE THREAD

**Issue by TommyTran732** [owncloud/ocis#10527]
## Describe the bug
The custom logo only loads after login. When logged out, OCIS loads the default ownCloud logo.

## Steps to reproduce
1. Set a custom logo
2. Logout
3. Visit the OCIS in incognito mode (to make sure caching is not a factor at play here)

## Expected behavior
The custom logo loads regardless of whether the user is logged in.

## Actual behavior
The custom logo only loads after login.

## Setup
Just the OCIS container and NGINX reverse proxy.

**Comment by micbar** [comment]
@TommyTran732 I think this behavior is acceptable. You do not change the logo that often.

Background: If we change the default caching headers on the logo, it will be loaded on every page load. That overhead seems too high for this context IMHO.

**Comment by TommyTran732** [comment]
@micbar 

This isn't about cache headers or changing the logo frequently. The login page simply does not display the custom logo ever. In the HTML it loads `/static/whatever` instead of `/branding/custom-logo-name.png`.

**Comment by micbar** [comment]
Please check ocis 6.6.1, it has been implemented lately.

**Comment by kulmann** [comment]
@TommyTran732 is this only about the login page of the internal IdP or did you catch this behaviour on other pages as well? E.g. in public links, on the `access-denied` page (you can simply navigate to that manually: `/access-denied`), etc.

For the login page of the internal IdP, it's like @micbar already said, it has only recently been implemented.

**Comment by TommyTran732** [comment]
Ah thank you. I am using 5.0.8, and yes it was the internal IdP.
