### ISSUE TITLE
[OCM] sharee cannot access the federation shares via normal webdav paths

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#10536]
## Steps to reproduce
1. Create a federation share of a folder (`remoteFolder`)
2. as sharee, try to do PROPFIND
```bash
curl -XPROPFIND 'https://ocis-server:9200/remote.php/dav/files/admin/Shares/remoteFolder' -uadmin:admin -vk

curl -XPROPFIND 'https://ocis-server:9200/remote.php/dav/spaces/{shares-space-id}/remoteFolder' -uadmin:admin -vk
```
```bash
< HTTP/1.1 404 Not Found
```

**But** the share is **accessible** using **mount-point-id** and **remote-item-id**
```bash
# mount-point-id
curl -XPROPFIND 'https://ocis-server:9200/remote.php/dav/spaces/89f37a33-858b-45fa-8890-a1f2b27d90e1$6953d7bc-1c57-4f2a-8977-10bdfbcb2ff6' -uadmin:admin -vk

# remote-item-id
curl -XPROPFIND 'https://ocis-server:9200/remote.php/dav/spaces/89f37a33-858b-45fa-8890-a1f2b27d90e1$6953d7bc-1c57-4f2a-8977-10bdfbcb2ff6!Lw%3D%3D' -uadmin:admin -vk
```
```
< HTTP/1.1 207 Multi-Status
```

Since this is a remote share, maybe the behaviour is expected.

Related: https://github.com/owncloud/web/issues/11753
Web using remote id: https://github.com/owncloud/web/pull/11758

**Comment by ScharfViktor** [comment]
I can confirm. cc @rhafer

**Comment by rhafer** [comment]
```
curl -XPROPFIND 'https://ocis-server:9200/remote.php/dav/files/admin/Shares/remoteFolder' -uadmin:admin -vk

curl -XPROPFIND 'https://ocis-server:9200/remote.php/dav/spaces/{shares-space-id}/remoteFolder' -uadmin:admin -vk
```

Both of these can only work for "normal" user and group shares. As requests to these paths are handled by the sharestorageprovider. Federated shares are handled by a different storageprovider.

AFAICS there is currently no way to list received ocm shares via webdav (or access them by mount path). You can get the id via sharedWithMe on  the graph service (like web does)

```
curl -k -u moss:vista  'https://ocis-federation.owncloud.test/graph/v1beta1/me/drive/sharedWithMe'
```
Then take the `id` values of  the embedded `remoteItem`.

**Comment by saw-jan** [comment]
yes, remoteItem id from `sharedWithMe` and mount-point id from `me/drives` both works.
If this is expected and there will be no furtuher improvements/changes regarding this then we can close this one.
