### ISSUE TITLE
[QA] RC7 user cannot logout. sometimes

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1055]
Deployed ocis v1.0.0-rc7 via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* login user moss
* create new user testy
* logout moss, login testy
* open the 9dots menu, see 2 entries
* open the settings page
* switch to german
* open the 9 dots menu, see three entries.
* logout. The logout fails. the redirect immediately logs in the user again.
* a few minutes later, logout works.

Not 100% reproducable.

**Comment by jnweiger** [comment]
On a fresh instance:
* login einstein
* 5 seconds later: try log out. redirect happens, user is logged in again.
* 5 seconds later: try log out. redirect happens, user is logged in again.
* 5 seconds later: try log out. redirect happens, user is logged in again.
* 5 seconds later: try log out. redirect happens, user is logged in again.
* 5 seconds later: try log out. logout succeeds.

It does not depend on other actions. It seems more important to try immediatly, not wait too long.

**Comment by jnweiger** [comment]
Reproducable with current master as of 2020-12-14 15:00h

**Comment by refs** [comment]
closing as I wasn't able to reproduce it [with the current master](https://github.com/owncloud/ocis/commit/8fa89f50676d065fc469ccb780037135a29639f4). Please reopen if I'm wrong ^^
