### ISSUE TITLE
[QA] RC7 restore from trashbin fails, when parent folder is missing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1057]
Deployed ocis v1.0.0-rc7 via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* log in as einstein via web UI,
* create folder nnn
* upload screenshot.png into folder nnn
* delete screenshot.png, delete folder nnn
* visit deleted files, try to restore nnn/screenshot.png 
![image](https://user-images.githubusercontent.com/1108546/101828419-d0f3b180-3b31-11eb-9d97-ca3781c7362e.png)
* the restore fails. BAD
![image](https://user-images.githubusercontent.com/1108546/101828081-60e52b80-3b31-11eb-815e-60a3393356d2.png)

Expected behaviour: missing parent folders are created as part of the restore (or the user is asked where to restore to)

Workaround: first restore nnn or create a fresh folder nnn, then restore nnn/screenshot.png

The restore also fails when the parent folder was renamed.

**Comment by individual-it** [comment]
- [ ]  ToDo QA team: check if tests exist for this case, if not add (API) tests, if yes see why they have not cached that issue before

**Comment by individual-it** [comment]
This issue need to be fixed on the UI level, the API just does a `MOVE` so if the original folder does not exist a new destination need to be given.
I will retest with web & oc10

**Comment by individual-it** [comment]
same issue with oc10 & web but the error message is nicer 
![image](https://user-images.githubusercontent.com/2425577/102452565-a68a8280-4062-11eb-983a-671f54752ce4.png)
