### ISSUE TITLE
Minimal description in dev docs for auth-app token generation via API necessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#10605]
Referencing: https://github.com/owncloud/ocis/issues/10292#issuecomment-2468888596 and https://github.com/owncloud/ocis/issues/10292#issuecomment-2482315480

We have a minimal [auth-app via API](https://owncloud.dev/services/auth-app/#via-api) documentation, just saying that there is an endpoint.

We should add some basic documentation as described in the linked issue how the endpoint is used.

@micbar @2403905

**Comment by mmattel** [comment]
Examples so we dont forget:

```
curl --location 'https://localhost:9200/auth-app/tokens' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic ZWluc3RlaW46cmVsYXRpdml0eQ=='

curl --location --request POST 'https://localhost:9200/auth-app/tokens?expiry=2m' \
--header 'Accept: application/json' \
--header 'Authorization: Basic ZWluc3RlaW46cmVsYXRpdml0eQ=='

curl --location --request DELETE 'https://localhost:9200/auth-app/tokens?token=%242a%2411%24hT5F3WidzRcz5yWIz1TGdu6w3QEbozGdKO9zTpdyV6zWpuloQi7Xe' \
--header 'Accept: application/json' \
--header 'Authorization: Basic ZWluc3RlaW46cmVsYXRpdml0eQ=='
```

User admin creates the token for user einstein.
https://owncloud.dev/services/auth-app/#via-impersonation-api
The auth-app service provides an Impersonation API to create (POST) tokens at /auth-app/tokens.
```
curl --location --request POST 'https://localhost:9200/auth-app/tokens?userID=4c510ada-c86b-4815-8820-42cdf82c3d51&userName=einstein&expiry=4h' \
--header 'Accept: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

**Comment by micbar** [comment]
Referencing https://github.com/owncloud/ocis/pull/9755#issue-2453271785
