### ISSUE TITLE
Cannot login using OIDC (Authentik) from 6.X to 7.x rc: 401 unauthorized

### ISSUE THREAD

**Issue by Crashman1983** [owncloud/ocis#10623]
I have a working instance of OCIS 5.0.x with OICS based on authentik. If I upgrade to 6.x.x user login does not work anymore. I just get an empty page and error logs with 401 error. 
Since I did not change the OIDC configuration and there is no good user manual,  don't know what to do to make it work.

`2024-11-22T04:56:44.489953237Z 2024-11-22T04:56:44Z ERR failed to authenticate the request | service=proxy error=failed to get userinfo: 401 Unauthorized:  authenticator=oidc path=/api/v0/settings/roles-list user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15 client.address=192.168.2.140 network.peer.address= network.peer.port= line=github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/oidc_auth.go:198 

`
## Steps to reproduce
1. switch from 5.0.x to 6.x.x or 7.x
2. try to login

## Expected behavior
OIDC log should work as with 5.0.x

## Actual behavior
blank page with rotating icon on top

## Setup
docker compose running with portainer
current authentik instance

**Comment by micbar** [comment]
I would think, without knowing your setup, that you are suffering from a missing CSP config.

Please see how to do that in our keycloak example in https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_keycloak/config/ocis/csp.yaml#L9

You need to add the csp.yaml file to your volume in /etc/ocis and set the correct env variable.

**Comment by Crashman1983** [comment]
Thanks, got it working. Never mind that I need to use this file for other IDPs as well, because it is used in the KEYCLOAK example.

But I had to add PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: "groups" to my compose file and I added the ocisAdmin group to authentik.

**Comment by micbar** [comment]
@mmattel we need a short note in the upgrade guide about CSP and external Identity Providers.

**Comment by mmattel** [comment]
I have added CSP to the upcoming [migration documentation](https://github.com/owncloud/docs-ocis/pull/1029).
It is also added in the upcoming [release notes](https://github.com/owncloud/docs-main/pull/81).

**Comment by prohtex** [comment]
> I have added CSP to the upcoming [migration documentation](https://github.com/owncloud/docs-ocis/pull/1029). It is also added in the upcoming [release notes](https://github.com/owncloud/docs-main/pull/81).

Yes, this is crucial info!
