### ISSUE TITLE
Allow configuring Microsoft formats, ODF formats, or both in "New" dropdown

### ISSUE THREAD

**Issue by dwhite5914** [owncloud/ocis#10637]
## Is your feature request related to a problem? Please describe.
In our lab, we use only use Microsoft Office formats. When using the OCIS Collaboration Server and clicking the "New" button, the dropdown menu shows both ODF format and Microsoft format options. It also shows ODF formats above Microsoft formats, which is annoying since we don't use these formats and I would like to encourage a workflow where Microsoft formats are preferred.

## Describe the solution you'd like
As an admin, when using the OCIS Collaboration Server, I would like the ability to configure what options appear in this menu and in what order. This could be some sort of configuration file or environment variable(s).

## Describe alternatives you've considered
A possible alternative could be a single environment variable that allows you to toggle just the groups (Microsoft, ODF, or both) rather than full control over which documents appear and in what order.

## Additional context
This should apply generally, but I am using a three container podman setup with OCIS server, OCIS Collaboration Server, and OnlyOffice Document Server.

**Comment by micbar** [comment]
I think your requirements are fulfilled. Please check out how to configure the app registry.

https://doc.owncloud.com/ocis/5.0/deployment/services/s-list/app-registry.html#mime-type-configuration-creation-allow-list

You can see how we do that in our docker-compose examples https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_full/config/ocis/app-registry.yaml

**Comment by dwhite5914** [comment]
@micbar Yes, this works for me! It turns out I had an issue with my app-registry.yaml file that was preventing it from taking effect. I'll close since the feature exists. Thanks!
