### ISSUE TITLE
Creating public links from desktop client is broken

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1067]
Trying to create a public link via context menu in Finder on macOS causes the following error in the desktop client:
`The file can not be shared because it was shared without sharing permission.`
Also happening for a folder that was created on my desktop.

Confirmed to be the same on linux:
https://github.com/owncloud/ocis/issues/828#issuecomment-742641849

Tested on ocis.owncloud.works

**Comment by refs** [comment]
I'd change priorities 🤔

**Comment by ScharfViktor** [comment]
works correctly, I suggest closing
re-tested with desktop client:
`ownCloud 2.8.2 (build 4246) ea9d50 May 28 2021 15:59:36
Libraries Qt 5.12.10, OpenSSL 1.1.1k 25 Mar 2021
Using virtual files plugin: suffix
`
Trying to create a public link via context menu in Finder on macOS:
1. choose "owncloud->share" 
![image](https://user-images.githubusercontent.com/84779829/132206033-f3cda2b3-2366-449c-a3ce-7a99a3e715ac.png)
2. then opens desktop client without errors. We can create share or public links
<img width="809" alt="Screenshot 2021-09-06 at 12 56 40" src="https://user-images.githubusercontent.com/84779829/132207128-730a3ccd-5455-4690-a2c9-cb018a4110fc.png">
3 link created
![Screenshot 2021-09-06 at 13 00 05](https://user-images.githubusercontent.com/84779829/132207427-c9976774-49bd-4cef-8d34-36a76fe37550.png)
