### ISSUE TITLE
[OCM] federation shares missing `name` and `root.remoteItem` values in the drives list

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/ocis#10689]
## Describe the bug
`name` and `root.remoteItem` are missing in driveType `mountpoint` while listing drives.

## Steps to reproduce
1. `And "Alice" has generated invitation`
2. `And using server "REMOTE"`
3. `And "Brian" has accepted invitation`
4. `And using server "LOCAL"`
5. And user "Alice" has created a folder "FOLDER" in space "Personal"
6. `When "Alice" shares folder to "Brian"`
7. as `Brian`, get all the drives
```console
  curl 'https://localhost:10200/graph/v1.0/me/drives' \
  -uBrian:1234 -vk | jq 
```
## Expected behavior
Expected to have `name` and `root.remoteItem` for driveType `mountpoint`.

## Actual behavior
```json
{
  "value": [
    {
      ...
    },
    {
      ...
    },
    {
      "driveType": "mountpoint",
      "id": "89f37a33-858b-45fa-8890-a1f2b27d90e1$febb0e7e-56e4-449a-b16f-5ace56dc14ce",
      "name": "",
      "owner": {
        "user": {
          "displayName": "",
          "id": "2c215cf8-6ccb-4eeb-92f8-61864b5bab40"
        }
      },
      "root": {
        "id": "89f37a33-858b-45fa-8890-a1f2b27d90e1$febb0e7e-56e4-449a-b16f-5ace56dc14ce",
        "webDavUrl": "https://localhost:10200/dav/spaces/89f37a33-858b-45fa-8890-a1f2b27d90e1$febb0e7e-56e4-449a-b16f-5ace56dc14ce"
      },
      "webUrl": "https://localhost:10200/f/89f37a33-858b-45fa-8890-a1f2b27d90e1$febb0e7e-56e4-449a-b16f-5ace56dc14ce"
    }
  ]
}
```

**Comment by saw-jan** [comment]
@rhafer is this fixable?

**Comment by rhafer** [comment]
> @rhafer is this fixable?

Good question. I need to check.

**Comment by rhafer** [comment]
Something is borked here. I don't think ocm shares should be reflected in the `/me/drives/` output at all. :thinking:

**Comment by rhafer** [comment]
Hm, I just noticed that our `sharedWithMe` endpoints return the virtual share jail as the parentReference for ocm shares. This is wrong as well. The share jail has nothing to do with ocm shares, it's just for "normal" shares.

**Comment by rhafer** [comment]
> @rhafer is this fixable?

@saw-jan I guess it is possible set set a name. I am not so sure about the `root.remoteItem`. What exactly do you need it for?

**Comment by saw-jan** [comment]
we use `name` and `remoteItem` to check for the share and sharer for normal shares. and reported it because federated share doesn't have them.

**Comment by rhafer** [comment]
> we use `name` and `remoteItem` to check for the share and sharer for normal shares. and reported it because federated share doesn't have them.

Ok. I guess the `/me/drives` endpoint is probably the wrong endpoint to use for federated shares. "normal" shares are represented there via `mountpoint` type drives (unless they have sync disabled I think). But federated shares don't have a concept of the sync enabled/disabled (accepted/ unaccepted) state. The fact that they are currently showing up in `/me/drives` is a bug (at least that's what we figured after some discussion yesterday).

I think `/v1beta1/me/drive/sharedWithMe` should have all the information you need (for "normal" and federated shares).

**Comment by saw-jan** [comment]
Okey, that means with the fix `/me/drives` should not list the ocm shares
