### ISSUE TITLE
[QA] Shares folder has too many actions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1071]
Deployed ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* accept a share from another user. A Shares folder appears (EOS: Shares folder is always there). OK.
* With this Shares folder: try rename, move, delete, share, link .... All these actions fail. Okayish.

![image](https://user-images.githubusercontent.com/1108546/101927446-c807ec00-3bd4-11eb-8756-d047a32afb38.png)

Expected Behaviour: No actions are available for the Shares folder, except click to enter.

**Comment by refs** [comment]
Who can we involved to get more visibility on this? /cc @micbar

**Comment by micbar** [comment]
it is on the roadmap for the design initiative

**Comment by micbar** [comment]
@kulmann transfer to web?

**Comment by kulmann** [comment]
Can we send less permissions on the folder instead? I.e. read only + no sharing permission. That should solve the issue already, because the web ui is respecting those permissions.

**Comment by pascalwengerter** [comment]
@kulmann have we resolved this? 🤔

**Comment by kulmann** [comment]
> @kulmann have we resolved this? 🤔

yes 😍 `move`, `rename` and `delete` are gone from the list of actions 💪
