### ISSUE TITLE
[QA] check ocm .well-known endpoint

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#10726]
Implementation: https://github.com/owncloud/ocis/pull/9815
Know about  well-know https://en.wikipedia.org/wiki/Well-known_URI
Endpoint: `GET` `https://localhost:9200/.well-known/ocm`
Response:
```json
{
   "enabled": true,
   "apiVersion": "1.1.0",
   "endPoint": "https://localhost:9200/ocm",
   "provider": "oCIS",
   "resourceTypes": [
      {
         "name": "file",
         "shareTypes": [
            "user"
         ],
         "protocols": {
            "webdav": "/dav/ocm"
         }
      }
   ],
   "capabilities": [
      "/invite-accepted"
   ]
}
```

Test cases:
- [x] check the response of `.well-known/ocm`

**Comment by nabim777** [comment]
Test for checking the response has been added https://github.com/owncloud/ocis/pull/10782
So, closing this issue
