### ISSUE TITLE
[QA] Trashbin cannot delete a deep tree

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1077]
Deployed ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

  *  log in as einstein via web ui,
  * upload a deep tree with 1000 files ca 900MB (from randfiles.py)
  * delete the top folder
  * visit the trashcan
  * try delete the deep tree. It fails. BAD
![image](https://user-images.githubusercontent.com/1108546/101964801-e12f8d80-3c12-11eb-8ef0-23ffbdb8373f.png)

Expected behaviour: delete works. such a tree is very hard to delete piecewise.

Restore works fine, though.
[1211c.log.zip](https://github.com/owncloud/ocis/files/5682088/1211c.log.zip)

**Comment by individual-it** [comment]
- [ ] ToDo for QA-team: reproduce the issue on API level and add an API test for this case

**Comment by individual-it** [comment]
@jnweiger is that about the deep tree, or just about having a file in the folder, seems like I cannot delete a folder that contains a file from the trashbin

**Comment by individual-it** [comment]
here the issue about deleting nested folders from trashbin https://github.com/owncloud/product/issues/188

**Comment by individual-it** [comment]
maybe related https://github.com/owncloud/ocis/issues/1116

**Comment by jnweiger** [comment]
Reproduced on ocis-1-0-0-rc8 with a small tree
2 folders deep, 4 files.

**Comment by refs** [comment]
confirming that happens [with the latest master](https://github.com/owncloud/ocis/commit/8fa89f50676d065fc469ccb780037135a29639f4)

**Comment by C0rby** [comment]
It works now in the current master and released version.
