### ISSUE TITLE
Phoenix rename causes orphaned os thread

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1098]
https://github.com/owncloud/ocis/commit/cc312d7aa23be888c15ca5cd0ec897846cd4850f disables `go-micro` web service that conflicts with since we're not making use of that micro router, so disabling is a fail safe.

A more resilient strategy would be to namespace micro runtime subcommands, so ocis has a full range of names to choose from

**Comment by kulmann** [comment]
Hotfix is here (and merged): https://github.com/owncloud/ocis/pull/1109

As mentioned, we could and should do better.

**Comment by pascalwengerter** [comment]
@refs @kulmann can this issue be closed?
