### ISSUE TITLE
ocs capabilities are currently read from config file

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#11]
how we could we make the ocs capabilities endpoint return the list of capabilities dynamically instead of having that huge config section?
- [ ] document all known capabilities and their effect
  - starting point https://doc.owncloud.com/server/developer_manual/core/apis/ocs-capabilities.html#available-capabilities
  - document the effect the capabilities have on the clients
    - [desktop](https://github.com/owncloud/client/blob/e6274b5304fb5204de749c77b18c9813aa18ad1d/src/libsync/capabilities.cpp)
    - [android](https://github.com/owncloud/android/blob/bf86491c7f1eb77d654bd9819e4f540eef02bea8/owncloudApp/src/main/java/com/owncloud/android/capabilities/db/OCCapability.kt)
    - [iOS new](https://github.com/owncloud/ios-app/search?p=1&q=capabilities&unscoped_q=capabilities)
    - [phoenix](https://github.com/owncloud/phoenix/search?q=capabilities&unscoped_q=capabilities)
- derive from other config options?

**Comment by refs** [comment]
duplicated of https://github.com/owncloud/ocis/issues/29
