### ISSUE TITLE
Generate remote config for OCIS

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1100]
As per the moment of this writing running ocis on a remote host requires some deal of configuration. While setting it up with CERN we capture those steps on [this living document](https://gist.github.com/refs/91d634ebdc83efb1a1dc99ae322a6e0b).

The proposal is to make OCIS out of the box run on a remote machine to prepare its config in order to have a fully functional OCIS available to the outside world. There is a lot of room for improvement in developer experience, this is a small step towards an easier "vanilla" adoption.

Feedback from @labkode

> To improve the usability, will be good that when running OCIS with the base URL for example, the config is generated accordingly

## Links in this issue

1. https://gist.github.com/refs/91d634ebdc83efb1a1dc99ae322a6e0b

## Solution

- We implemented the ENV variable `OCIS_URL` which will be used in all depending services
- If you start ocis for the first time with the `OCIS_URL` set to a real hostname, it will write a `identifier-registration-yml` with the correct Urls

**Comment by refs** [comment]
bump. Still relevant.

**Comment by refs** [comment]
@micbar I'd love to work in this and at the same time "variadic arguments for `ocis run` command to run selected extensions and not the default set". Any chance we can pull it in a near sprint?

**Comment by micbar** [comment]
yes. let us pull it in.
