### ISSUE TITLE
[QA] Potential security risk warning

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1103]
Deployed ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* After accepting the self signed cert from traeffik
* while the blue login page loads, a warnign is shown:

![image](https://user-images.githubusercontent.com/1108546/102207771-d9037680-3ece-11eb-8d79-c0e6d17a4363.png)

Can this be avoided? Is this due to the self signed cert?

**Comment by refs** [comment]
cc @C0rby

**Comment by C0rby** [comment]
Yeah, Firefox is displaying this warning for self-signed certificates but it should disappear when you accepted the cert.

**Comment by C0rby** [comment]
When a valid certificate is used the warning is not shown so I don't think there is anything to do here.

**Comment by refs** [comment]
> When a valid certificate is used the warning is not shown so I don't think there is anything to do here.

Thanks for the input!
