### ISSUE TITLE
PROPFIND on trashbin with Depth: infinity only shows the first level

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1116]
1. create a folder
2. upload a file into the folder
3. delete the folder
4. query the trashbin with `Depth: infinity` - `curl -k -u einstein:relativity -X PROPFIND https://localhost:9200/remote.php/dav/trash-bin/einstein  -H'Depth: infinity' -d'<?xml version="1.0"?> <d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:ocs="http://open-collaboration-services.org/ns"> <d:prop><oc:trashbin-original-filename/><oc:trashbin-original-location/><oc:trashbin-delete-timestamp/><d:getlastmodified/></d:prop> </d:propfind>' |xmllint --format -`

expected:
all levels of trashbin content are displayed

actual:
only first level is displayed:

```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/trash-bin/</d:href>
    <d:propstat>
      <d:prop>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <oc:trashbin-original-filename/>
        <oc:trashbin-original-location/>
        <oc:trashbin-delete-datetime/>
        <d:getcontentlength/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/trash-bin/4c510ada-c86b-4815-8820-42cdf82c3d51:23c0af3a-610f-46b8-b5d8-0d93f81db096/</d:href>
    <d:propstat>
      <d:prop>
        <oc:trashbin-original-filename>New folder</oc:trashbin-original-filename>
        <oc:trashbin-original-location>New folder</oc:trashbin-original-location>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <oc:trashbin-delete-timestamp/>
        <d:getlastmodified/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>

**Comment by individual-it** [comment]
- [ ] ToDo QA-team create API tests for this case

**Comment by dpakach** [comment]
Another side-effect of this issue we cannot restore an subfolder or file from a deleted folder which can be done in oc10

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
still relevant
