### ISSUE TITLE
Href in trashbin PROPFIND response is wrong

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1120]
1. as `einstein` upload a file: `curl -k 'https://localhost:9200/remote.php/webdav/file.txt' -XPUT -ueinstein:relativity -d"123"`
1. as `einstein` delete the file `curl -k 'https://localhost:9200/remote.php/webdav/file.txt' -XDELETE -ueinstein:relativity`
1. check the content of the trashbin: `curl -k 'https://localhost:9200/remote.php/dav/trash-bin/einstein' -X PROPFIND -ueinstein:relativity | xmllint --format -`
   => the href is shown as: `/remote.php/dav/trash-bin/4c510ada-c86b-4815-8820-42cdf82c3d51:f46e6676-56e7-478e-88f9-6d4139d3ef23`
1. trying to restore (MOVE) this file will fail with HTTP 405 `curl -k 'https://localhost:9200/remote.php/dav/trash-bin/4c510ada-c86b-4815-8820-42cdf82c3d51:f46e6676-56e7-478e-88f9-6d4139d3ef23' -X MOVE -H'Destination: https://localhost:9200/remote.php/dav/files/einstein/textfile0.txt' -ueinstein:relativity -v`
   the correct path is `remote.php/dav/trash-bin/einstein/4c510ada-c86b-4815-8820-42cdf82c3d51:f46e6676-56e7-478e-88f9-6d4139d3ef23`
   `curl -k 'https://localhost:9200/remote.php/dav/trash-bin/einstein/4c510ada-c86b-4815-8820-42cdf82c3d51:f46e6676-56e7-478e-88f9-6d4139d3ef23' -X MOVE -H'Destination: https://localhost:9200/remote.php/dav/files/einstein/textfile0.txt' -ueinstein:relativity -v` works

   Web uses the correct path and not the one that is given in `href`, so the restore works there

**Comment by C0rby** [comment]
This should also be fixed.
