### ISSUE TITLE
Deleting a received share-folder moves it to trash-bin but does not unshare it

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1123]
1. as `einstein` share a folder with `marie`
2. as `marie` accept the share
3. as `marie` delete `Shares/<received-share>`
4. as `marie` check the trash-bin => the received share is listed there
5. as `marie` check `shared-with-me` => the share is listed as `accepted` and can be declined and accepted again, that will bring it back to `/Shares`
6. as `einstein` check the people of the shared folder `marie` is still listed

expected:
in oC 10 shares cannot be deleted but only unshared, they don't end up in the trash-bin

**Comment by HariBhandari07** [comment]
JankariTech Reminder: Sawjan is writing test to demonstrate the bug

**Comment by saw-jan** [comment]
@individual-it what are the Expected-Behaviors for this?

**Comment by individual-it** [comment]
in oC 10 shares cannot be deleted but only unshared, they don't end up in the trash-bin

**Comment by phil-davis** [comment]
> in oC 10 shares cannot be deleted but only unshared, they don't end up in the trash-bin

"received shares cannot be deleted by the share receiver but only unshared"

when a share receiver sends a `DELETE` API request for the resource (file or folder) that they have received, the received share is "unshared" - it should go back to "pending" state, and can be accepted again by the share receiver.

Nothing is actually "really deleted" and so nothing should end up in the trashbin.

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
It works correctly, not in the expected-failures.
We can close
