### ISSUE TITLE
[QA] Share owner cannot delete  other user's files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1126]
Deployed ocis rc8  via ocis/deployments/examples/ocis_traefik/
 https://ocis.rc.owncloud.works

(From @refs )

- login as admin
- create folder A
- share folder A with Marie as Editor
- login as Marie
- upload a file to folder A
- login as admin
- navigate to folder A and try to delete the file that Marie uploaded to /a
    - will fail. BAD
- navigate one dir up (../)
- delete the shared folder with Marie
- will succeed. Okayish

Expected behaviour: deleting a file from a share user should work for the owner.
Other share users can delete hers, just not the owner.

Maybe releated to: #1118

**Comment by individual-it** [comment]
- [ ]  ToDo QA-team: check if there are API tests for this case, if not add

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0

It works correctly. there is no mention in the /expected-failures
We can close

**Comment by phil-davis** [comment]
Agree - this is a "simple" sharing sequence that works nowadays.
