### ISSUE TITLE
oCIS status.php returns Wrong Version and productname

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#1127]
With version oCIS 1.0.0 the status.php returns 
```
{
    "installed": true,
    "maintenance": false,
    "needsDbUpgrade": false,
    "version": "10.0.9.5",
    "versionstring": "10.0.9",
    "edition": "community",
    "productname": "ownCloud"
}
```

We accept that as a known issue, but need to change it asap. Important: We need to synchronize that with all clients.

**Comment by jnweiger** [comment]
Duplicate of https://github.com/owncloud/ocis/issues/310#issuecomment-658810176

**Comment by dragotin** [comment]
closing to avoid duplicates.
