### ISSUE TITLE
[QA] File deleted by share receiver are not in her trashcan

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1128]
Deployed ocis-1.0.0-rc8 via ocis/deployments/examples/ocis_traefik/

* login in as einstein
* Upload a folder Music with three mp3 files.
* Share the folder with user Marie as Editor
* login in  new browser session as Marie, accept the folder
* enter folder Shares/Music, delete crypt-o.mp3
* check deleted files. It is not there. BAD
* with user einstein's session, check deleted files, it is there, but with a strange `.../` prefix. Okayish
![image](https://user-images.githubusercontent.com/1108546/102489499-d68b5300-406d-11eb-9952-680b6796a13e.png)

* with Marie's session, create a New Folder within Music and delete it again.
* check deleted files, the New Folder is there. OK
* * with user einstein's session, check deleted files, it is not there. BAD.

expected behaviour: as with oc10: both share owner and deleting user have copies in their trashcans. 
(or at least owner has it all. ow could we ever puzzle a folder back together, if multiple parties created things, and then one person deletes them?)

**Comment by phil-davis** [comment]
Similar to #1124 ?

**Comment by refs** [comment]
can confirm still happens [on the current master](https://github.com/owncloud/ocis/commit/8fa89f50676d065fc469ccb780037135a29639f4)

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
still happens

**Comment by ScharfViktor** [comment]
closed in favor #1124
