### ISSUE TITLE
[QA] Deleted user's browser session hangs in exit loop

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1129]
Deployed ocis-1.0.0-rc8 via ocis/deployments/examples/ocis_traefik/

* moss creates user testy
* user testy logs in
* moss deletes user testy
* user testy while still logged in) gets errors. Okayish
* user testy logs out, sees the exit page:
![image](https://user-images.githubusercontent.com/1108546/102491041-f0c63080-406f-11eb-8316-a838d679f559.png)
* press exit to log in with another account
* the exit page reapperars. No login window. BAD

Expected behaviour: the browser cookies / tokens are invalidated during exit, a fresh login whould be possible.

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: create UI test for this case

**Comment by dpakach** [comment]
Added tests for this on https://github.com/owncloud/web/pull/4543

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
When deleted user  logs out, see:
![image](https://user-images.githubusercontent.com/84779829/132313819-48d9c600-ac02-452d-b460-32c91f2c6011.png)

It works correctly, not in the expected-failures.
We can close
