### ISSUE TITLE
Do not embed coreCommit and webCommit in .drone.star

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1132]
If the actual commit values are in `.drone.star` then the values seen in the branch get "locked in" as the values used in CI.

See https://github.com/owncloud/ocis/pull/1117#issuecomment-747571408 for some explanation of how the core tests being run and the expected-failures file in use can get out-of-sync with each other.

Think how we can avoid this problem. Maybe put `coreBranch` `coreCommit` `webBranch` `webCommit` in some other file that the CI can read?

**Comment by wkloucek** [comment]
What about an .env file? This is easily parsable.
This also would also enable deduplication here:

https://github.com/owncloud/ocis/blob/738a32f9b184dbc04bef723725fa22d9deb91486/tests/acceptance/docker/Makefile#L21-L22

**Comment by phil-davis** [comment]
This is also being done in `owncloud/web` PR https://github.com/owncloud/web/pull/4556
