### ISSUE TITLE
Configure default write location

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#114]
Currently konnectd's default writes a private key and a self signed certificate to the binary running location, leaving the programmer to either exclude this files from the git tree or in general adding some noise. If this is intended only for development [we can use a tmp dir](https://golang.org/pkg/io/ioutil/#TempDir)

![image](https://user-images.githubusercontent.com/6905948/74651075-56613c00-5183-11ea-9c67-771a329f96b3.png)

**Comment by IljaN** [comment]
Currently ocis-konnectd is doing the writing. But lets leave the issue here, as this might concern other services as well in the future.

**Comment by refs** [comment]
or delete generated artifacts on shutdown

**Comment by IljaN** [comment]
Okay I realize now that it polutes the config dir in the code-tree. Didn't think about this case because I always run the binary with ocis/bin as $PWD.

Would a .gitignore entry be okay for a start? But then we need to add files to ocis .gitignore which belong to other repos (ocis-konnectd) :thinking:.

>  or delete generated artifacts on shutdown
This would work for developers but on a production system we probably won't have the permission to create anything  in $PWD at all.

**Comment by IljaN** [comment]
IIRC reva uses ./var. Would this be a valid approach?

**Comment by IljaN** [comment]
IIRC other high-profile golang projects createe a directory in $XDG_CONFIG_HOME unless a flag overrides this behaviour. This would cover both use-cases i.e running in development or testing vs running as daemon.

**Comment by refs** [comment]
or just add it to your global gitignore

**Comment by IljaN** [comment]
> or just add it to your global .gitignore

Then every developer needs to remember to do it. Bad DX ;)

IMO using the XDG standard would be the right approach. What do you think?

**Comment by IljaN** [comment]
> IMO using the XDG standard would be the right approach. What do you think?

Hmhh... but this would break windows and osx builds. So we would need to have an os-specific abstraction for it.
https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x

**Comment by refs** [comment]
...I was in the process of typing this down :D

**Comment by refs** [comment]
In theory the accounts / settings service should account for storing any configuration parameter, a private key and cert counts as that I guess.

**Comment by IljaN** [comment]
@refs look what I found: https://github.com/kirsle/configdir

**Comment by refs** [comment]
IMHO this is a super easy quick win @micbar

**Comment by micbar** [comment]
Super easy quick fix for me would be more like effort 1 or 3 😄

**Comment by refs** [comment]
@micbar https://github.com/owncloud/ocis/pull/2129

**Comment by refs** [comment]
@IljaN https://golang.org/pkg/os/#UserConfigDir
