### ISSUE TITLE
Upload a file using TUS resource URL as an other user should not work

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#1141]
1. Create a base64 encoding of a file name
- `echo -n "textFile.txt" | base64` (example dGV4dEZpbGUudHh0)
2. As user Einstein send a `POST` request to create resource. 
- `curl -k -X POST -u einstein:relativity   https://localhost:9200/remote.php/dav/files/Einstein/  -H 'Tus-Resumable: 1.0.0' -H 'Upload-Length: 10' -H 'Upload-Metadata: filename dGV4dEZpbGUudHh0' -v` 
This will give a resource location url. Something like this: ```https://localhost:9200/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjYwMTIzMjM3LCJpYXQiOjE2MDgyODMyMzcsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1NS9kYXRhL3R1cy81MzhiYjkxYS0xNDYzLTQzZjgtYjZjMi1kOWU5NjgwZWFkYmMifQ.jHRQAGzS-MCXhWeDH-DqCZbGm0FcedVh4v5W0GHqpDU)```, 
3. Remember the location URL.
4. As user Moss send `PATCH` upload data to the location url:
- `curl -k -X PATCH <your TUS resource Location> -u moss:vista -H 'Content-Type: application/offset+octet-stream' -H 'Tus-Resumable: 1.0.0' -H 'Upload-Offset: 0' -d '1234567890' -v`

### Actual Result:
```
 HTTP/1.1 204 No Content
 Date: Fri, 18 Dec 2020 09:21:07 GMT
 Tus-Resumable: 1.0.0
 Upload-Offset: 10
 Vary: Origin
 X-Content-Type-Options: nosniff
```
- File `textFile.txt` is listed for user `Einstein` and can be downloded.

### Expected Result:
```
 HTTP/1.1 403 Forbidden
 Date: Fri, 18 Dec 2020 09:30:16 GMT
 Tus-Resumable: 1.0.0
 Vary: Origin
 X-Content-Type-Options: nosniff
```
- File `textFile.txt` should not be listed for user `Einstein`

**Comment by butonic** [comment]
@micbar @refs @C0rby do we really want to enforce a check on this path? This means the dataprovider needs to be aware of users. The upload URL `https://localhost:9200/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjYwMTIzMjM3LCJpYXQiOjE2MDgyODMyMzcsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1NS9kYXRhL3R1cy81MzhiYjkxYS0xNDYzLTQzZjgtYjZjMi1kOWU5NjgwZWFkYmMifQ.jHRQAGzS-MCXhWeDH-DqCZbGm0FcedVh4v5W0GHqpDU` has been created and signed by the storage provider. It contains an expiry:
```
{
  "aud": "reva",
  "exp": 1660123237,
  "iat": 1608283237,
  "target": "http://localhost:9155/data/tus/538bb91a-1463-43f8-b6c2-d9e9680eadbc"
}
```

To me this looks very much like a presigned url: "Here is a link you can use to upload bytes. I don't care who you are.".

This would decouple dataproviders from having to be aware of who makes the request. This scales better when uploding many small files.

**Comment by C0rby** [comment]
@butonic, yes I think you got a point.
Although checking the uploader would increase the defense in depth, it is very unlikely for an attacker to get hold of the upload URL.

We can close this issue and remove the tests IMO.

**Comment by butonic** [comment]
@swoichha @phil-davis This works as designed. The internal upload URL is contained in a JWT which is signed by the server. And the visible URL with the JWT only reaches the user that initiated the upload in a HTTPS protected connection.

The test can be removed. Or do you see a thread model that is not adressed by using HTTPS  and JWTs being signed?

**Comment by phil-davis** [comment]
> The test can be removed. Or do you see a threat model that is not addressed by using HTTPS and JWTs being signed?

I agree. The "other user" "Brian"  would have to be already on the same local client computer as the first user "Alice", and have access to the file system, memory... of "Alice". If that is so, then "Brian" has almost completely stolen the local identity of "Alice" anyway. There is no way that "Brian" can intercept and decrypt the "token" that Alice is using to do the upload.

https://github.com/owncloud/core/pull/39041 skips the scenario when on OCIS or reva.
