### ISSUE TITLE
File/folder date differs from oC10 date - Android no longer can parse it

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#1154]
I've seen this with owncloud.ocis.works

Android 2.15.3 shows all dates as Jan 1st 1970

Android 2.15.3 | iOS 11.4.4
-- | --
<img src="https://user-images.githubusercontent.com/214010/102867879-b676dd80-4439-11eb-8e35-25f418bc0a7f.png" width="400"> | <img src="https://user-images.githubusercontent.com/214010/102867882-b70f7400-4439-11eb-9434-1f5fa7f4a074.png" width="400">

@phil-davis did you notice any API differences to oC10?
/cc @abelgardep @theScrabi

**Comment by abelgardep** [comment]
oc10 Format: `Fri, 18 Dec 2020 08:36:59 GMT`
ocIS Format: `Tue, 22 Dec 2020 16:38:55 +0000`

We used the first one -> https://tools.ietf.org/html/rfc7231#section-7.1.1.1

Anyway, if we need to fix it, we can find the date parser in dav4android: https://gitlab.com/ownclouders/dav4android/-/blob/oc_support_2.1.5/src/main/kotlin/at/bitfire/dav4jvm/HttpUtils.kt#L21

**Comment by michaelstingl** [comment]
Sounds like https://github.com/owncloud/android/issues/2999

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: add tests to check the time format is correct

**Comment by HariBhandari07** [comment]
Jankaritech Reminder: Sawjan is working on this issue

**Comment by individual-it** [comment]
see also https://github.com/owncloud/ocis-reva/issues/236#issuecomment-706186104

**Comment by saw-jan** [comment]
> * [ ]  ToDo QA-team: add API tests to check the time format is correct

Test has already been added.
See:
https://github.com/owncloud/core/blob/c660329663e15d64ae760f59d5d9a74e75e7081d/tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature#L291-L302

**Comment by C0rby** [comment]
@abelgardep @michaelstingl, I think it's working now. Can you confirm and if so close this issue?

**Comment by phil-davis** [comment]
Note: https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
This scenario (currently at line 300) is passing CI:
```
  Scenario Outline: Propfind the last modified date of a folder using webdav api
    Given using <dav_version> DAV path
    And user "Alice" has created folder "/test"
    When user "Alice" gets the following properties of folder "/test" using the WebDAV API
      | propertyName      |
      | d:getlastmodified |
    Then the single response should contain a property "d:getlastmodified" with value like "/^[MTWFS][uedhfriatno]{2},\s(\d){2}\s[JFMAJSOND][anebrpyulgctov]{2}\s\d{4}\s\d{2}:\d{2}:\d{2} GMT$/"
    Examples:
      | dav_version |
      | old         |
      | new         |
```
That checks for the string "GMT" at the end.

**Comment by michaelstingl** [comment]
> @abelgardep @michaelstingl, I think it's working now. Can you confirm and if so close this issue?

Yeah, looks good 👍
