### ISSUE TITLE
Follow the file hierarchy standard? dev or admin audience?

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1163]
I think we should follow the https://de.wikipedia.org/wiki/Filesystem_Hierarchy_Standard which in our case means:
- `/srv` _Site-specific data served by this system, such as data and scripts for web servers, data offered by FTP servers, and repositories for version control systems (appeared in FHS-2.3 in 2004)._
    - `/srv/ocis/<service>/<whatever>`. The FHS does not describe the tree layout beneath `/srv` but we should move our data to a common `ocis` subdir
-  `/var/tmp` _Temporary files to be preserved between reboots._
    - this actually makes sense ... and is different from just  `/tmp`

The problem with moving data to `/srv/ocis` is that that folder is not user writeable. Which uncovers the actual issue:

Is the ocis binary targeted at developers or at admins trying to run the setup?
- developers want to run ocis as bare bones as possible to debug it and poke at it
- admins want to deploy or install it ... so it runs with a dedicated user, uses proper paths like `/srv` for the data and is started onboot automatically. This is usually done by packaging ocis for distributions, which is something we are not really targeting, yet.

I propose we use path defaults that can be written to by the current user because we currently mainly target developers. But shouldn't we then default to the local directory? hm ... If we are talking about paths ... keep windows in mind.

The admin audience should be covered by docker compose files. The docs explain the necessary env vars which would allow running ocis on bare metal as well. Currently, running ocis on a remote machine can be done with `OCIS_URL=https://remote.host.tld:1234 PROXY_HTTP_ADDR=0.0.0.0:1234 ocis server` .... but that does not install ocis as a process ... we are not there yet.

affects https://github.com/owncloud/ocis/pull/1048

**Comment by butonic** [comment]
We could introduce an `OCIS_PATH_PREFIX` that defaults to `''`. All paths could use locations that make sense for a real deployment. Like `/srv/ocis/storage/...`. for served files, `/tmp` for temporary files (well actually our uploads should go into srv as well because they can be resumed ...)
Developers can prefix all paths with eg. `/tmp`, `/var/tmp` or `./` for the local directory.
On windows it could be used to prefix paths with `C:\Program Files\ocis\` ... but this needs testing.

**Comment by refs** [comment]
> Is the ocis binary targeted at developers or at admins trying to run the setup?

I guess this depends on where in the development we are. Ideally, it should address both Personas concerns, giving an admin complete control and the developer enough flexibility.

> but that does not install ocis as a process

as a daemon? 👿 

> OCIS_PATH_PREFIX

I guess the entire path concepts needs to be slightly documented, if not in code. Our path handling is a bit insidious. In a cli help, how would you describe `OCIS_PATH_PREFIX`? The next line got me lost:

`[...] All paths could use locations that make sense for a real deployment`

**Comment by refs** [comment]
I think it should be pretty high on the priority list and this is an issue / feature to watch. This addresses a real concern I've been having for quite some time at least. 👍
