### ISSUE TITLE
refactor check deleted_mtime tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1166]
tests added in https://github.com/owncloud/core/pull/38239 & modified in https://github.com/owncloud/core/pull/38252 need some refactoring 

1. Step sentence to make sure the reader understands that the step checks the actual mtime not only the existence of the element
2. upload the file with an old mtime to make sure the deletion_mtime is really the deletion time and not the mtime that was set during upload
3. make lines shorter 

CC @phil-davis @saw-jan

**Comment by dpakach** [comment]
done in https://github.com/owncloud/core/pull/38260
