### ISSUE TITLE
Ocis cli does not show any error message when executing a wrong command

### ISSUE THREAD

**Issue by erwinpalma** [owncloud/ocis#1171]
### General

When I run a wrong command into the ocis cli, it does not show any message.

![image](https://user-images.githubusercontent.com/30660343/103564047-24051e00-4ebe-11eb-9fc5-823fbda28f49.png)

### Steps to reproduce

1. Run `./ocis server`
2. Launch ./ocis using arbitrary text. `./ocis wrong-command`
3. Or launch `./ocis wrong command`

### Expected behavior
If one parameter or command is missing, should show a warning message or the list of available commands

```
./ocis wrong-command
Command "wrong-command" not found, list of available commands 

NAME:
   ocis - ownCloud Infinite Scale Stack

USAGE:
   ocis [global options] command [command options] [arguments...]

VERSION:
   1.0.0
...
```

### Server configuration
**Operating system**:
Mac OS X

**ownCloud version:** (see ownCloud admin page)
ocis version 1.0.0

**Comment by micbar** [comment]
@erwinpalma thank you for reporting.

Sounds like a good enhancement.

**Comment by pascalwengerter** [comment]
Somehow has changed, just tried this with current master and it prints `No help topic for 'arbitray'. Closing this issue as fixed (even though the printed message could be more informative)
