### ISSUE TITLE
Simplify OIDC configuration

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1175]
For remote deployments it is siffucient to set `OCIS_URL` and `PROXY_HTTP_ADDR`.

We should be able to clonfigure all related services to use a specific OpenID identity provider using a single env var as well.

`OIDC_ISSUER` sounds about right. It could go into
- `STORAGE_OIDC_ISSUER`
- `PROXY_OIDC_ISSUER`
- `WEB_OIDC_AUTHORITY`
- `STORAGE_LDAP_IDP`

Not related:
- `KONNECTD_ISS` because konnetd is to be replaced with `OIDC_ISSUER`

We could even make the proxy forward `/.well-known/openid-configuration` to the actual issuer (taking into account `WEB_OIDC_METADATA_URL` which should probably be called `OIDC_CONFIGURATION_URL` or `OPENID_CONFIGURATION_URL`)?

@fschade I see `OIDC_HOST` in k6 ... is that the OIDC_ISSUER? 

Opinions?

**Comment by fschade** [comment]
Yes it is, OIDC_ISSUER sounds good to me. If we can decide this as a name I could change it in the cdperf too. Thanks for taking care

**Comment by IljaN** [comment]
> We could even make the proxy forward /.well-known/openid-configuration to the actual issuer (taking into account WEB_OIDC_METADATA_URL

This might have security implications. AFAIK  the openid-configuration should be served from the idp-domain. A HTTP-Redirect should be okay though.

**Comment by fschade** [comment]
Renaming in to issuer is done in cdperf. Thanks for pointing this out

https://github.com/owncloud/cdperf/blob/6f9b9f739564458a3ac9b7e8ce1d73e770a1cc03/scripts/cdperf#L12

**Comment by wkloucek** [comment]
we have `OCIS_OIDC_ISSUER` which can be used to set the url of the external idp
