### ISSUE TITLE
Reduce CI complexity using OCIS_URL

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1187]
PR #1148 implemented an environment variable `OCIS_URL` 
From that environment variable a lot of other values are deduced that are suitable for an install where "everything" runs on a single host. That should be relevant for CI.

Investigate the environment variables being used in CI to define the OCIS configuration. Try to use `OCIS_URL` instead, and get rid of as many "random" environment variables as possible.

Do the same in `owncloud/web` and get the configuration of the web-on-OCIS UI test pipelines "the same" as the way they are configured when running web UI test pipelines in OCIS CI.

**Comment by dpakach** [comment]
@phil-davis the env var is already applied in ocis CI,web was done in owncloud/web#4600, can we close this now?
