### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#119]
1. [x] Select a port from the [list of available port ranges](https://github.com/owncloud/ocis/wiki/Ports)
2. [x] Register route handlers
3. [x] Proxy TLS support 
4. [x] Ocis-konnectd toggle tls (https://github.com/owncloud/ocis-konnectd/issues/37)
5. [x] Update the default registration yaml (https://github.com/owncloud/ocis-konnectd/issues/32)
6. [x] Bridge host address configurable
7. [ ] Add ocis-bridge to runtime to start with ocis-server

### pre-requirements

until point 4 (ocis-konnectd tls toggler) if available, you'd need to manually disable tls on the konnectd extension and update your `go.mod` with your local `ocis-konnectd`. Hence why this is using `go run` for ease of mind.

Create the require folder structure by reva

```console
mkdir /var/tmp/reva/{data,root}
```

## 1. Run `ocis` fullstack server

```console
KONNECTD_ISS=https://localhost:9200 \
REVA_OIDC_ISSUER=https://localhost:9200 \
PHOENIX_OIDC_AUTHORITY=https://localhost:9200 \
PHOENIX_WEB_CONFIG_SERVER=https://localhost:9200 \
go run cmd/ocis/main.go server
```

## 3. Log in

credentials:

```console
username: albert
password: relativity
```

## 4. Once you log in you should see the files app

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/ocis/issues/136

**Comment by IljaN** [comment]
@micbar Is ocis-bridge command still a priority?
