### ISSUE TITLE
Show username in collaborators/share tab

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1190]
ocis.owncloud.works does not show the email or username in the list of recipients.

**Comment by refs** [comment]
@butonic can you be more specific? Where exactly? :)

**Comment by butonic** [comment]
Hm this should be working as of nov last year: https://github.com/owncloud/web/pull/4203

**Comment by LukasHirt** [comment]
> but I cannot see the email on demo.owncloud.com when trying to find recipients or when accepting shares

@butonic Check if it's enabled in the settings. Admin -> Sharing -> Extra field to display in autocomplete results. When it's enabled, I can see it just fine:

<img width="532" alt="Screenshot 2021-02-04 at 1 49 07" src="https://user-images.githubusercontent.com/25989331/106828863-450e8980-668b-11eb-937e-f7e02c743c69.png">

<img width="531" alt="Screenshot 2021-02-04 at 1 49 17" src="https://user-images.githubusercontent.com/25989331/106828869-463fb680-668b-11eb-9547-fd0cc2fd3dfa.png">

<img width="558" alt="Screenshot 2021-02-04 at 1 49 23" src="https://user-images.githubusercontent.com/25989331/106828871-46d84d00-668b-11eb-9131-97b03913bf80.png">

**Comment by kulmann** [comment]
ownCloud Web simply renders whatever value `shareWithAdditionalInfo` of a `sharee` holds.
Doing a quick `git grep "shareWithAdditionalInfo"` in the reva and ocis repo shows 0 results.

See relevant ownCloud 10 code here:
https://github.com/owncloud/core/blob/39b3dd7627465eb316d1b707bd21cb0b6b3c972e/apps/files_sharing/lib/Controller/ShareesController.php#L206
https://github.com/owncloud/core/blob/39b3dd7627465eb316d1b707bd21cb0b6b3c972e/apps/files_sharing/lib/Controller/ShareesController.php#L278

**Comment by butonic** [comment]
fix landed in ocis master with https://github.com/owncloud/ocis/pull/1588

**Comment by labkode** [comment]
Can we have it configurable? choose between username and mail. Maybe have a template? like storage user layout?

**Comment by labkode** [comment]
@butonic

**Comment by butonic** [comment]
currently hardcoded to email, needs to be made configurable to at least username or email. best would be a template.

**Comment by labkode** [comment]
Same template mechanism we use for the storage layout, that would be great

**Comment by labkode** [comment]
@butonic when you're back let's catch up on this

**Comment by ishank011** [comment]
Done https://github.com/cs3org/reva/pull/1588

**Comment by ishank011** [comment]
@pascalwengerter this can be closed
