### ISSUE TITLE
Make expected failures files more readable

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1193]
I'd like to make the expected failures file more prominent and reference it as the known issues.

The file currently contains a line for every failing test an a header like this:
```
#
# https://github.com/owncloud/ocis/issues/824 PUT request with missing parent must return status code 409
#
apiAuthWebDav/webDavPUTAuth.feature:38
#
```

We could markdownify this and
- convert the failing features to markdows lists
- link to the issue as we currently do
- give some context 

With markdown we can now
- add a L2 or L3 header and deep link them
- add a link to every feature to let a failing test render the url to feature file on github.
- add a link from the README.md to the expected-failure-*.md files and encourage people to find things to work on

AFAICT grepping the features from the markdown will be a little more effort then just `grep -v '#'` but since it follows the list semantics `grep '* '` or using sed to extract out links should do the trick.

**Comment by HariBhandari07** [comment]
@butonic I have created a PR that converts expected failures text file in owncloud web to markdown. What do you think of this PR https://github.com/owncloud/web/pull/4612  . Any suggestion is appreciated.

**Comment by phil-davis** [comment]
Implemented in cs3org/reva by https://github.com/cs3org/reva/pull/1407

expected-failures `.md` files are in use everywhere now.
