### ISSUE TITLE
Big file upload (and download) runs into 10 sec timeout

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#120]
Reproduce:

- Run ocis server
- Login to webui
- Create big file ```fallocate -l 6G bigfile.bin```
- Click +New => Upload File => bigfile.bin
- Upload Fails :boom: 

File with 1 GB works.

Relevant Loglines
```
6:00PM ERR home/ilja/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocdav/put.go:219 > error doing http request error="Put http://localhost:9156/data/albert/6g.bin: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" pid=26242 pkg=rhttp traceid=c37834485d7339d24ae135da647d08ce
6:00PM ERR home/ilja/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/log/log.go:112 > http end="24/Feb/2020:18:00:25 +0100" host=::1 method=PUT pid=26242 pkg=rhttp proto=HTTP/1.1 size=0 start="24/Feb/2020:18:00:15 +0100" status=500 time_ns=10020856613 traceid=c37834485d7339d24ae135da647d08ce uri=/remote.php/webdav/6g.bin url=/remote.php/webdav/6g.bin
6:00PM ERR home/ilja/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/dataprovider/put.go:39 > error uploading file error="ocFS: error writing to tmp file /var/tmp/reva/data/albert/files/._reva_atomic_upload556955768: unexpected EOF" pid=26365 pkg=rhttp traceid=c37834485d7339d24ae135da647d08ce
```

**Comment by labkode** [comment]
@IljaN we need to configure by config the HTTP client timeout

**Comment by butonic** [comment]
reva currently uses an http client that has the timeout set to 10 sec: https://github.com/cs3org/reva/blob/0dbce24f7e8b508c1ecab2d145979562888a7a76/pkg/rhttp/client.go#L37

We need to increase that or better yet, make it configurable for the ocdav up and download.

**Comment by kiranparajuli589** [comment]
Is the issue resolved? Cause I got this while trying with 10GB file upload:
![output](https://user-images.githubusercontent.com/39373750/90128935-731faa80-dd87-11ea-87f2-fb2a44d4792e.gif)
**P.S.**: Sync with `desktop client` is also working well with such large files.

**Server Configurations**
- latest ocis master
