### ISSUE TITLE
oCIS and NFS (kernel 5.9 test environment)

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#1200]
According to https://stackoverflow.com/questions/24629459/how-to-use-extended-file-attributes-on-nfs NFS does not natively support extended file attributes.

We should integrate NFS into our Test-Suite to verify oCIS is working.

**Comment by refs** [comment]
doing a shallow search: https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.9-NFS-Server-User-Xattr

**Comment by Escubaer** [comment]
If possible we should also run/test against NetApp NFSv4 ... they have ACLs since quite some time.

**Comment by hodyroff** [comment]
If possible we should also run against NetApp NFSv4 ... they have ACLs implemented for a longer time.

**Comment by dragotin** [comment]
Ok, good news with Linux NFS from kernel 5.9. Still a test environment would be good.

**Comment by refs** [comment]
@dragotin updated the issue description to be more actionable 👍

**Comment by kobergj** [comment]
As extended attributes are not ocis default any more and this ticket is 3 years old I am closing this for now.
