### ISSUE TITLE
Sort out open issues in archived repos

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1215]
When the mono-repo thing was implemented, a number of "OCIS extension" repos were archived. But there were open issues in those repos. We cannot comment on or close those issues now. For example: https://github.com/owncloud/ocis-reva/issues/262

Many of them are referenced in the expected-failures files.

- [x] look through the issues and make a list of which ones can be closed and which ones should still be open.
- [x] unarchive the repos (need to co-ordinate with someone who has the privileges)
- [ ] close issues that should be closed
- [x] move issues that are still open to `owncloud/ocis`
- [x] archive the repos again
- [x] adjust the links in the expected-failures files in `owncloud/ocis` #1485 
- [x] adjust the links in the expected-failures files in https://github.com/cs3org/reva/

**Comment by phil-davis** [comment]
Note: issues from `owncloud/ocis-reva` have been moved to `owncloud/ocis`

**Comment by HariBhandari07** [comment]
Here's a list of all the issues that were imported from various ocis extension repos:

### ocis-glauth
- https://github.com/owncloud/ocis/issues/1479
- https://github.com/owncloud/ocis/issues/1478

### ocis-webdav
- https://github.com/owncloud/ocis/issues/1477
- https://github.com/owncloud/ocis/issues/1476
- https://github.com/owncloud/ocis/issues/1475

### ocis-thumbnail
- https://github.com/owncloud/ocis/issues/1474
- https://github.com/owncloud/ocis/issues/1473
- https://github.com/owncloud/ocis/issues/1472
- https://github.com/owncloud/ocis/issues/1471
- https://github.com/owncloud/ocis/issues/1470
- https://github.com/owncloud/ocis/issues/1469

### ocis-pkg
- https://github.com/owncloud/ocis/issues/1468
- https://github.com/owncloud/ocis/issues/1467
- https://github.com/owncloud/ocis/issues/1466
- https://github.com/owncloud/ocis/issues/1465
- https://github.com/owncloud/ocis/issues/1464
- https://github.com/owncloud/ocis/issues/1463
- https://github.com/owncloud/ocis/issues/1462
- https://github.com/owncloud/ocis/issues/1461

### ocis-settings
- https://github.com/owncloud/ocis/issues/1460
- https://github.com/owncloud/ocis/issues/1459
- https://github.com/owncloud/ocis/issues/1458
- https://github.com/owncloud/ocis/issues/1457
- https://github.com/owncloud/ocis/issues/1456
- https://github.com/owncloud/ocis/issues/1455
- https://github.com/owncloud/ocis/issues/1454
- https://github.com/owncloud/ocis/issues/1453
- https://github.com/owncloud/ocis/issues/1452
- https://github.com/owncloud/ocis/issues/1451
- https://github.com/owncloud/ocis/issues/1450
- https://github.com/owncloud/ocis/issues/1449
- https://github.com/owncloud/ocis/issues/1448
- https://github.com/owncloud/ocis/issues/1447
- https://github.com/owncloud/ocis/issues/1446
- https://github.com/owncloud/ocis/issues/1445
- https://github.com/owncloud/ocis/issues/1444
- https://github.com/owncloud/ocis/issues/1443
- https://github.com/owncloud/ocis/issues/1442
- https://github.com/owncloud/ocis/issues/1441

### ocis-proxy
- https://github.com/owncloud/ocis/issues/1440
- https://github.com/owncloud/ocis/issues/1439
- https://github.com/owncloud/ocis/issues/1438
- https://github.com/owncloud/ocis/issues/1437
- https://github.com/owncloud/ocis/issues/1436
- https://github.com/owncloud/ocis/issues/1435
- https://github.com/owncloud/ocis/issues/1434
- https://github.com/owncloud/ocis/issues/1433
- https://github.com/owncloud/ocis/issues/1432
- https://github.com/owncloud/ocis/issues/1431
- https://github.com/owncloud/ocis/issues/1430


### ocis-konnectd
- https://github.com/owncloud/ocis/issues/1429
- https://github.com/owncloud/ocis/issues/1428
- https://github.com/owncloud/ocis/issues/1427

### ocis-store
- https://github.com/owncloud/ocis/issues/1426
- https://github.com/owncloud/ocis/issues/1425
- https://github.com/owncloud/ocis/issues/1424

### ocis-ocs
- https://github.com/owncloud/ocis/issues/1423
- https://github.com/owncloud/ocis/issues/1422
- https://github.com/owncloud/ocis/issues/1421
- https://github.com/owncloud/ocis/issues/1420
- https://github.com/owncloud/ocis/issues/1419
- https://github.com/owncloud/ocis/issues/1418
- https://github.com/owncloud/ocis/issues/1417
- https://github.com/owncloud/ocis/issues/1416
- https://github.com/owncloud/ocis/issues/1415
- https://github.com/owncloud/ocis/issues/1414
- https://github.com/owncloud/ocis/issues/1413
- https://github.com/owncloud/ocis/issues/1412
- https://github.com/owncloud/ocis/issues/1411

### ocis-phoenix
- https://github.com/owncloud/ocis/issues/1410
- https://github.com/owncloud/ocis/issues/1409
- https://github.com/owncloud/ocis/issues/1408

### ocis-accounts
- https://github.com/owncloud/ocis/issues/1406
- https://github.com/owncloud/ocis/issues/1405
- https://github.com/owncloud/ocis/issues/1404
- https://github.com/owncloud/ocis/issues/1403
- https://github.com/owncloud/ocis/issues/1402
- https://github.com/owncloud/ocis/issues/1401

**Comment by phil-davis** [comment]
I will look through and close any moved issues that can be closed. Then we can close this issue.

**Comment by phil-davis** [comment]
I have pinged the relevant people to look at their issues and close if no-longer relevant.
