### ISSUE TITLE
Delete shares from user when user is deleted

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1226]
See https://github.com/owncloud/ocis-reva/issues/262.

We need to remove the user's shares from shares.json and publicshares.json (which act like caches)

Might need some kind of notification system in reva where the deletion/disappearance of a user would propagate an event to all the storage providers so they can proceed to delete any user related metadata.

@butonic

**Comment by phil-davis** [comment]
IMO we do not have any special code any more in the test suite for cleaning up shares when a user is deleted. It seems to work OK, at least with the "owncloud" and "ocis" storages that are in automated CI.

Maybe this has been all fixed?

**Comment by phil-davis** [comment]
Closing as this is also covered by #1258 - I will check there.
