### ISSUE TITLE
[public link]File converted into folder when copying folder into file 

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#1232]
### Description
In the public link, if the public copy folder in the file using API request then the file is converted into a folder by overwriting the file. 
Something similar happens in https://github.com/owncloud/core/issues/37683,but here the difference is that even though the HTTP status code is 204 when we check fort the content for copy1.txt it is same as the original which means it was not overwritten and there is no file copy1.txt/testfile.txt.

### Steps to reproduce
1. Create a user `Alice`
2. User `Alice` creates a folder `PARENT1`
3. User `Alice` creates another folder `PARENT1/testFolder`
4. User `Alice` uploads a file with content `some data` to `PARENT1/testFolder/testfile.txt`
5. User `Alice` uploads a file with content `some data 1` to `PARENT1/copy1.txt`
6. User `Alice` creates a public link share with path `PARENT1` and permissions `read,update,create,delete`
[User gets a token in the response eg:YZgUPJKKDhbi]
7. The public copies folder `testFolder` to `copy1.txt` using new public webdav api:
```
curl -X COPY -H "Destination: https://localhost:9200/remote.php/dav/public-files/YZgUPJKKDhbi/copy1.txt" 'https://localhost:9200/remote.php/dav/public-files/YZgUPJKKDhbi/testFolder' -k -v
```
8. After copying folder structure will look like
--->PARENT1--->copy1.txt--->testfile.txt
--->PARENT1--->testFolder--->testfile.txt

### Expected behaviour
A 403 Forbidden error
### Actual behaviour
```
 HTTP/1.1 204 No Content
 Access-Control-Allow-Origin: *
 Content-Security-Policy: default-src 'none';
 Date: Mon, 13 Jul 2020 09:22:09 GMT
 Vary: Origin
 X-Content-Type-Options: nosniff
 X-Download-Options: noopen
 X-Frame-Options: SAMEORIGIN
 X-Permitted-Cross-Domain-Policies: none
 X-Robots-Tag: none
 X-Xss-Protection: 1; mode=block
```

### Checking Content 
To make sure if the file has been overwritten:
```
curl -X GET http://localhost:9140/remote.php/webdav/PARENT1/copy1.txt -u alice:1234 -k   
some data 1% 

curl -X GET http://localhost/core/remote.php/webdav/PARENT1/copy1.txt/testfile.txt -u alice:1234 -k -v

HTTP/1.1 500 Internal Server Error
 Access-Control-Allow-Origin: *
 Content-Security-Policy: default-src 'none';
 Vary: Origin
 X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTk0NjQyMTc2LCJpYXQiOjE1OTQ2Mzg1NzYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJBbGljZSJ9LCJ1c2VybmFtZSI6IkFsaWNlIiwibWFpbCI6ImFsaWNlQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiQWxpY2UifX0.B2JIkA1JPoZmIi-4aOics2WzTa8weco_H3YLr0LUb_M
 X-Content-Type-Options: nosniff
 X-Download-Options: noopen
 X-Frame-Options: SAMEORIGIN
 X-Permitted-Cross-Domain-Policies: none
 X-Robots-Tag: none
 X-Xss-Protection: 1; mode=block
 Date: Mon, 13 Jul 2020 11:09:36 GMT
 Content-Length: 0

```

**Comment by ScharfViktor** [comment]
At step 7 I see an error in the description or something I do not understand. We cannot copy a folder to a file
If there is an error in the description here and you copy `copy1.txt` to `testFolder` then the case works, we get
```
Request Method: COPY
Status Code: 201 Created
```

If so, please close it

**Comment by amrita-shrestha** [comment]
> At step 7 I see an error in the description or something I do not understand. We cannot copy a folder to a file If there is an error in the description here and you copy `copy1.txt` to `testFolder` then the case works, we get
> 
> ```
> Request Method: COPY
> Status Code: 201 Created
> ```
> 
> If so, please close it

@ScharfViktor actually copying folder into file should be forbidden but we get `204 http status code` which is odd behaviour

**Comment by amrita-shrestha** [comment]
### Current behavior 
#### Checking context
```
curl -X GET http://localhost:9140/remote.php/webdav/PARENT1/copy1.txt -u alice:1234 -k  
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK

< 
* Connection #0 to host localhost left intact

```
```
curl -X GET http://localhost/core/remote.php/webdav/PARENT1/copy1.txt/testfile.txt -u alice:1234 -k -v

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< 
* Connection #0 to host localhost left intact
some data% 
```

**Comment by saw-jan** [comment]
I believe these are the expected behaviors:

 1. COPY `myfile.txt` -> `myFolder`
    - folder `myFolder` is moved to trashbin
    - file `myFolder` is created
2. COPY `myFolder` -> `myfile.txt`
    - file `myfile.txt` is moved to trashbin
    - folder `myfile.txt` is created

@ScharfViktor Please, confirm the behavior then maybe we can close this one

CC @amrita-shrestha

**Comment by fschade** [comment]
@ScharfViktor, please see the comment above, i assign the ticket to you

**Comment by ScharfViktor** [comment]
> @ScharfViktor Please, confirm the behavior then maybe we can close this one

re-tested also for public link case. Works fine
