### ISSUE TITLE
Share id for public link share is non numerical value

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/ocis#1236]
To reproduce the issue:

1. from ocis repo start phoenix `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/

2. upload a file or a folder 

`curl -X PUT http://localhost:9140/remote.php/webdav/hari.txt -d "123" -u user1:1234`

3. make sure the file is uploaded

`curl -X PROPFIND http://localhost:9140/remote.php/webdav/hari.txt -u user1:1234 | xmllint --format -`

4. create a public share

`curl -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -u user1:1234 -d "permission=31&path=hari.txt&shareType=3" | xmllint --format -`

Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <id>weWsCSWkNzXNlhN</id>
    <share_type>3</share_type>
    <uid_owner>user1</uid_owner>
    <displayname_owner>User One</displayname_owner>
    <permissions>1</permissions>
    <stime>1595221894</stime>
    <parent/>
    <expiration/>
    <token>jfosLkBPGlcMPTI</token>
    <uid_file_owner>user1</uid_file_owner>
    <displayname_file_owner>User One</displayname_file_owner>
    <additional_info_owner/>
    <additional_info_file_owner/>
    <state>0</state>
    <path>/hari.txt</path>
    <item_type>file</item_type>
    <mimetype>text/plain</mimetype>
    <storage_id>1284d238-aa92-42ce-bdc4-0b0000009154</storage_id>
    <storage>0</storage>
    <item_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjMyNTljYzAzLTZlZDYtNDhiZS04Y2QyLTU5Mzc4OTc0MTdmZQ==</item_source>
    <file_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjMyNTljYzAzLTZlZDYtNDhiZS04Y2QyLTU5Mzc4OTc0MTdmZQ==</file_source>
    <file_parent/>
    <file_target>/hari.txt</file_target>
    <share_with_additional_info/>
    <mail_send>0</mail_send>
    <name/>
    <url>https://localhost:9200/#/s/jfosLkBPGlcMPTI</url>
  </data>
```

As you can see `<id>weWsCSWkNzXNlhN</id>` is non-numerical value

### Expected Behavior
For normal core or phoenix setup
Request:
`curl -u admin:admin -X POST http://localhost/core2/ocs/v1.php/apps/files_sharing/api/v1/shares -d 'path=/hari.txt' -d 'shareType=3' -d 'permissions=31' | xmllint --format -`

Response:

```
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message/>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data>
    <id>241</id>
    <share_type>3</share_type>
    <uid_owner>admin</uid_owner>
    <displayname_owner>admin</displayname_owner>
    <permissions>1</permissions>
    <stime>1595222644</stime>
    <parent/>
    <expiration/>
    <token>o35PBVN0iP3SdrC</token>
    <uid_file_owner>admin</uid_file_owner>
    <displayname_file_owner>admin</displayname_file_owner>
    <additional_info_owner/>
    <additional_info_file_owner/>
    <path>/hari.txt</path>
    <item_type>file</item_type>
    <mimetype>text/plain</mimetype>
    <storage_id>home::admin</storage_id>
    <storage>1</storage>
    <item_source>2147489241</item_source>
    <file_source>2147489241</file_source>
    <file_parent>3</file_parent>
    <file_target>/hari.txt</file_target>
    <name/>
    <url>http://localhost/core2/index.php/s/o35PBVN0iP3SdrC</url>
    <mail_send>0</mail_send>
    <attributes/>
  </data>
</ocs>
```

As you can see, share id is numerical value (`<id>241</id>`)

**Comment by refs** [comment]
confirm still happens in the current master.

**Comment by phil-davis** [comment]
Is this a bug or a feature?
Is there a spec somewhere that says that the `id` must be an ordinary positive integer?
(and are there clients in-the-wild that depend on it being an ordinary positive integer?)

**Comment by refs** [comment]
>  Is there a spec somewhere that says that the id must be an ordinary positive integer?

not that I'm aware of. As far as I can think, id's in oc are increment because of the underlying db, but since we don't have that limitation in ocis, there is not really a spec.

@micbar could we bring this topic in the next retro/sprint/meeting/standup?

**Comment by refs** [comment]
> (and are there clients in-the-wild that depend on it being an ordinary positive integer?)

@phil-davis I found a bug on phoenix once where the client used `parseInt` to parse the id as an integer (no idea why), and it caused things to go south. But no idea if any other client has this parsing. This is the PR in question https://github.com/owncloud/web/pull/2494/files

**Comment by kulmann** [comment]
I see no reason why we would enforce the share ids to be `uint`s. We don't aim for backwards compatibility from oCIS to oc10. Closing here.

**Comment by butonic** [comment]
actually we must support strings here ... the shareid in cs3 is a string
