### ISSUE TITLE
User-sync endpoint does not exist

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1241]
`/cloud/user-sync` end point exists in oC10 for syncing a user in an auth backend (e.g. LDAP).

https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiMain/userSync.feature has some core "unhappy path" test scenarios. oC10 `user_ldap` app has "happy path" scenarios.

Is this endpoint to be supported in OCIS?

**Comment by refs** [comment]
We need input here regarding Phil's question.

**Comment by refs** [comment]
cc @pmaier1 @micbar can some of you provide some input regarding the need of this?

**Comment by micbar** [comment]
Will not be supported in ocis.

User Sync is only needed in oc10 because we have to align the accounts table with the LDAP server.

ocis follows a different concept.

We can skip that permanently for ocis.

**Comment by refs** [comment]
👍 thanks! closing

**Comment by phil-davis** [comment]
PR https://github.com/owncloud/core/pull/38832 tags the related scenarios so that we do not waste time running them in OCIS CI.
