### ISSUE TITLE
Ability to specify user name in Webdav path despite UUID mode

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1244]
Since https://github.com/owncloud/ocis/pull/409 and https://github.com/cs3org/reva/pull/1052 the Webdav path is now requiring UUIDs instead of user name.

However, @butonic said that we should also supposed specifying a user name there.

This ticket is to track this task / discussion.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
