### ISSUE TITLE
Moving resource loses associated shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1251]
This is using the OC storage ~~I haven't tested with EOS~~
Works fine on EOS.

Scenario: tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature:180

Basically:

### Steps

1. Create folder "test"
1. Create public links for "test"
1. Rename "test" to "test_renamed"
1. Check the public link list for "test_renamed"

### Expected
Links are still there

### Actual
Links disappeared and are likely still linked to the other path ?!
Or maybe a cache issue ?

I thought shares were associated by resource id.

@refs

**Comment by refs** [comment]
Leaving open and tagging as belonging to the oc storage.

**Comment by refs** [comment]
OC storage is not encouraged anymore.
