### ISSUE TITLE
Normalize ID for User Shares and Public Shares

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1252]
Currently user shares ids look like `66f8be01-dde6-44be-ba39-c82547452a6`, whereas public share ids look like: `nZXGYAnLunrr`. While this work, it's very inconsistent, and needless to say that public links are more susceptible to collisions.

It is likely that the public share id format depends on the driver used to create it. A good entry vector for this ticket [can be found here](https://github.com/cs3org/reva/blob/e8f1815d1b5be48f414b6d00652c243dc20c58ae/pkg/publicshare/manager/json/json.go#L109-L111)

**Comment by butonic** [comment]
Closin: the `jsoncs3` share manager introduced a spaceid prefix for the shareid. But that id is internal. In URLs users will only see references to resources. As per https://owncloud.dev/ocis/adr/0011-global-url-format/ all Browser visible URLs are built in the form of
```
https://<host>/files</namespaced/alias></relative/path/to/resource>?id=<resource_id>
```
short forms eg for public links
```
https://<host>/s/CZVyDYbFdOHDCoR/
```
will be 'unpacked' by the web ui into eg
```
https://<host>/files/link/public/CZVyDYbFdOHDCoR?items-per-page=100&fileId=1284d238-aa92-42ce-bdc4-0b0000009157%242a76bef4-e1f5-4e85-9569-fa3b7ef07fab%2101b5cf89-222b-4d81-b663-4312bdd9f4da
```
which fits the mixed URL scheme.
