### ISSUE TITLE
Share additional info

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1253]
In OC 10 there's an option to display additional information for shares like "user id" or "user email" to help distinguish similar names (like Thomas Müller)

Need to implement this in ocis.

These are returned in the field "additional_info" and "additional_info_owner".

**Comment by pmaier1** [comment]
I remember recent discussions about this topic. Please check whether it is fixed. If not, this is a new feature which needs to be addressed via the roadmap. (cc @phil-davis )

**Comment by phil-davis** [comment]
@dpakach I don't remember if we have tests for this. Maybe there are some tests for the end-to-end behavior in the old web UI against oC10 - but those are not relevant to oCIS. Maybe there are some API tests - I am not sure.

Please get someone to investigate.

**Comment by pmaier1** [comment]
> For new webUI with ocis:
In ocis, by default share collaborators are listed along with the email. UI Tests from 'web' doesn't seem to work well with 'ocis' as backend.

Thanks for the research. This needs fixing in oCIS. The expectation is that this behaves like "new webUI with oc10".

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
