### ISSUE TITLE
No longer hardcode permissions

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#1255]
In reva `internal/http/services/owncloud/ocdav/propfind.go` search for `// TODO(jfd) no longer hardcode permissions`

Currently the code looks like this `response.Propstat[0].Prop = append(response.Propstat[0].Prop, s.newProp("oc:permissions", "WCKDNVR"))`

**Comment by refs** [comment]
This has been addressed [here](https://github.com/cs3org/reva/pull/1368)
