### ISSUE TITLE
Handle weak etags

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#1256]
In reva `internal/http/services/owncloud/ocdav/propfind.go` search for `// TODO(jfd) handle weak tags that start with 'W/'`

**Comment by refs** [comment]
Care to add a more elaborate description? :)

**Comment by C0rby** [comment]
Yes, I must say this is an awful issue...

The propfind handler currently doesn't handle [Weak etags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests#weak_validation). 

https://github.com/cs3org/reva/blob/47119beffae215190124e98e063f1734b9e75938/internal/http/services/owncloud/ocdav/propfind.go#L356

I don't really remember why I opened this issue. But mayby @jfd can clarify what exactly needs to be done.

**Comment by kobergj** [comment]
I know why this issue is stale! We pinged to wrong person :fearful: 

So now, three years later: @butonic do you know what this ticket is about? Is it still needed? If not please close the ticket!

**Comment by kobergj** [comment]
Just discussed. Ticket can be closed. We dont need weak etags
