### ISSUE TITLE
Migration: SAML --> OIDC

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#126]
In OCIS every user is authenticated using OpenID Connect.
If the instance uses SAML to authenticate users it already uses an IdP.

The authentication needs to change from SAML to OIDC. 

To make guest and local users available to the IdP ocis-glauth can be used to access the existing oc10 accounts and authenticate them using LDAP.

We should test and document how this works using konnectd or keycloak.

**Comment by refs** [comment]
Having a concept would also help understanding CERN deployment using Keycloak.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
