### ISSUE TITLE
Return correct permission set in propfind response.

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#1260]
In the owncloud storage driver `pkg/storage/fs/owncloud/owncloud.go` search for the method `convertToResourceInfo`. In this method the returned ResourceInfo contains a hard-coded PermissionSet.

**Comment by refs** [comment]
no longer the case:

https://github.com/cs3org/reva/blob/47119beffae215190124e98e063f1734b9e75938/pkg/storage/fs/owncloud/owncloud.go#L682-L684
