### ISSUE TITLE
File-id changes on every upload

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1262]
1. setup OCIS with EOS as described in https://github.com/owncloud-docker/compose-playground/tree/master/examples/eos-compose-acceptance-tests
2. load test users `ldapadd -x -D "cn=admin,dc=owncloud,dc=com" -w admin -H ldap://localhost -f ./config/example-ldap-users-groups.ldif`
3. upload a file `curl -k -u user1:1234 -X PUT https://localhost:9200/remote.php/dav/files/user1/file.txt -d "123" -v`
4. check the file-id of the uploaded file `curl -k -u user1:1234 -X PROPFIND https://localhost:9200/remote.php/dav/files/user1/file.txt -d '<?xml version="1.0"?> <d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">  <d:prop><oc:fileid /></d:prop></d:propfind>'`
5. upload different data to the same file again
6. check the file-id again

result: the file-id changes on every upload. The outcome of that is that file-versions don't work.

**Comment by ScharfViktor** [comment]
> @ScharfViktor, can we close it?

 I guess yes, please open if it still relevant
