### ISSUE TITLE
Prevent creating public share for the home root folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1265]
in apiSharePublicLink1/createPublicLinkShare.feature scenario "Do not allow public sharing of root"

It returns 200 instead of 403

**Comment by refs** [comment]
> The core scenario is currently still failing on OCIS due to an unexpected OCS status code. When that is sorted out, maybe the rest of the checks will pass.

This seems like a quick win, cc @micbar

**Comment by micbar** [comment]
@butonic @individual-it fixing the status code looks like a quick win

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/pull/37943 implemented separate test scenarios for this on oC10 and oCIS.

On oCIS, creating a public link share of the root is allowed. The behavior on oC10 and oCIS is accepted to be different.
