### ISSUE TITLE
Public link enforce permissions

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1269]
Make sure permissions are enforced and return 403 instead of 500.
In the case of upload-only links, any Webdav operation would usually return 404 (need to be verified with the API tests)

Supersedes https://github.com/owncloud/ocis-reva/issues/285 and https://github.com/owncloud/ocis-reva/issues/291

- [ ] prevent upload, move, etc on read-only share
- [ ] prevent anything but upload on upload-only endpoint (return 404 for any other operation)
- [ ] upload-only doesn't behave correctly when overwriting: https://github.com/owncloud/ocis-reva/issues/286

**Comment by refs** [comment]
this is a big technical debt currently present in the codebase.

**Comment by butonic** [comment]
this is covered by sharing NG
