### ISSUE TITLE
When sharing a file mime-type field is set to `application/octet-stream`

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1271]
1. setup OCIS with EOS as described in https://github.com/owncloud-docker/compose-playground/tree/master/examples/eos-compose-acceptance-tests
2. load test users `ldapadd -x -D "cn=admin,dc=owncloud,dc=com" -w admin -H ldap://localhost -f ./config/example-ldap-users-groups.ldif`
3. upload a file `curl -k -u user1:1234 -X PUT https://localhost:9200/remote.php/dav/files/user1/file.txt -d "123" -v`
4. share the file: `curl -u user1:1234 -X POST "http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares" -H "OCS_APIREQUEST: true" -d path=file.txt -d shareType=0 -d shareWith=user0 | xmllint --format -`

Result:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <id>f0641e4b-851f-4117-8105-f06e1eafee36</id>
    <share_type>0</share_type>
    <uid_owner>user1</uid_owner>
    <displayname_owner/>
    <permissions>19</permissions>
    <stime>1593086158</stime>
    <parent/>
    <expiration/>
    <token/>
    <uid_file_owner>user1</uid_file_owner>
    <displayname_file_owner/>
    <additional_info_owner/>
    <additional_info_file_owner/>
    <state>0</state>
    <path>/file.txt</path>
    <item_type>file</item_type>
    <mimetype>application/octet-stream</mimetype>
    <storage_id>1284d238-aa92-42ce-bdc4-0b0000009158</storage_id>
    <storage>0</storage>
    <item_source>213406187520</item_source>
    <file_source>213406187520</file_source>
    <file_parent/>
    <file_target>/file.txt</file_target>
    <share_with>user0</share_with>
    <share_with_additional_info/>
    <mail_send/>
  </data>
</ocs>
```

~~Might not be limited to EOS, need to be retested with OC storage~~

**Comment by kobergj** [comment]
Closing as this is too old.
