### ISSUE TITLE
Deleting a public link after renaming a file

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#1275]
`tests/acceptance/features/apiSharePublicLink1/deletePublicLinkShare.feature:24`
Deleting a public link after renaming a file is not working.

```
OCS status code is not the expected value 100 got 400
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'100'
        +'400'
```

**Comment by refs** [comment]
continue in https://github.com/owncloud/ocis/issues/1251
