### ISSUE TITLE
Share providers error handling

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1278]
When calling GetPublicShare on a non-existing share id, it should return the GRPC code NotFound instead of failing the call completely.

Currently it appears that the JSON handler is using strings as errors, so need to replace this with proper error objects to be able to distinguish between a legitimate "share not found" error and a "something went horribly wrong while reading the file"

- [ ] user shares
- [ ] public shares

@refs FYI

**Comment by refs** [comment]
done in https://github.com/cs3org/reva/pull/921
