### ISSUE TITLE
implement oc chunking/checksum using tus metadata

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1279]
I ran into checksum problems. Maybe the tus chunking extension is not what we want because it may discard whole chunks?

See clarification in https://github.com/tus/tus-resumable-upload-protocol/issues/143#issuecomment-497933853
>> all client disconnects would remove the last chunk.

> Yes, that's true and one of the major drawbacks of checksum extension.

 - we can send the checksum in the metadata, but for large files that would
 require reading the file twice.
 - the client might calculate the checksum while sending, the server as well and can return the checksum in the response. but that would require resending the whole file in case of an error.
 - actually this is the right thing to do
 - together with the concatenation extension the full bandwith can be used
- but tusd does not support it, yet

AFAICT we can send the checksum in the metadata to mimic the current checksum protocol: https://doc.owncloud.org/desktop/2.4/architecture.html#upload

**Comment by butonic** [comment]
@michaelstingl could you comment on https://github.com/tus/tusd/issues/353#issuecomment-596185770 and explain why the `Tus-Min/Max-Chunk-Size` header makes sense for us?

**Comment by michaelstingl** [comment]
@butonic no need for min/max from my POV. TUS already supports fixed chunk sizes. We can have a quick call later.

**Comment by butonic** [comment]
@michaelstingl IIRC you wanted to be able to let the admin configure the chunksize to make uploads pass firewalls and intermediary services ...

**Comment by individual-it** [comment]
@butonic I don't think we have done checksums in TUS tests yet.
Please create an issue to create acceptance tests for that with a link to the PR and the part of the TUS protocol docs how it suppose to work and we can add tests for it

**Comment by butonic** [comment]
Initial Checksum support in https://github.com/cs3org/reva/pull/1400

**Comment by michaelstingl** [comment]
> @michaelstingl IIRC you wanted to be able to let the admin configure the chunksize to make uploads pass firewalls and intermediary services ...

Yes, already solved with fixed-size chunk information in header. Why do we need min/max for that?

**Comment by michaelstingl** [comment]
@butonic see my updated comment ⬆️

**Comment by michaelstingl** [comment]
> Yes, already solved with [`tus-max-size`](https://tus.io/protocols/resumable-upload.html#tus-max-size) chunk information in header. Why do we need another min/max for that?

Oh, crap. Not my day today. `tus-max-size` is the "maximum allowed size of an entire upload". I need to check first.

**Comment by felix-schwarz** [comment]
As far as OC is concerned, there already is a `max_chunk_size` in the `files` > `tus_support` part of capabilities that the iOS client is already supporting:

```json
"files" : {
	"tus_support" : {
		"max_chunk_size" : $maxChunkSizeInBytes
	}
	…
}
…
```

IMO in its current form the [Checksum extension](https://github.com/tus/tus-resumable-upload-protocol/blob/1.1/protocol.md#checksum) is not suitable for mobile clients, as it requires that all data of an incomplete `PATCH` request be discarded, contradicting efforts like the `Upload-Tag` extension that tries to save bandwidth by _not_ re-transmitting already sent data.

A possible solution I can see is to take a transactional approach, where the checksum is recorded after each `PATCH` request, allowing a rollback and retransmission, with commits happening whenever checksums match:
- a chunk is sent via `PATCH`, including the checksum for the chunk in the header
- if the request succeeds:
	- if checksum is correct, the chunk gets committed
	- if checksum is incorrect, the chunk gets thrown out and an error returned
	- (so far, that's essentially how the existing Checksum extension works)
- if the connection breaks down and the request is incomplete:
	- the subsequent `HEAD` request from the client on the upload resource returns additional info:
		- the offset range (begin offset - end offset) of the incomplete chunk
		- a server-computed checksum over the received parts of the incomplete chunk
	- the client can now use that info to check if the checksum matches that part of the file
		- if it matches, client sends a `PATCH` request
			- with extra range+checksum metadata `commit-upload-range=500-700,commit-upload-checksum=sha256:a76…` in the header to commit the partial upload
			- otherwise continues the upload from the end of the partial upload (standard tus `PATCH` syntax)
		- if it does not match, client sends a `PATCH` request
			- resuming from the start of the corrupted chunk (standard tus `PATCH` syntax), causing the server to throw out the uncommitted chunk
- rinse and repeat until the upload is complete

This could be implemented as an extension to the existing Checksum extension.

**Comment by butonic** [comment]
To make chunked upload requests always land on the same dataprovider, the internal upload url can be used to route all requests to the data provider that is responsible for the upload.

🤔 I think this is already done ;-) @kulmann implmented the datagateway and dataprovider part for that IIRC.

**Comment by felix-schwarz** [comment]
I have finished a first draft for the proposal of a `Partial Checksum` tus extension here:

https://github.com/felix-schwarz/tus-resumable-upload-protocol/blob/extension/partial-checksum/protocol.md#partial-checksum

 Feedback welcome! I plan to submit the PR for it soon.

**Comment by felix-schwarz** [comment]
After further editing for clarity and some simplifications regarding headers, I just created the PR: https://github.com/tus/tus-resumable-upload-protocol/pull/172

**Comment by butonic** [comment]
Notdhing to add! Great writeup that integrates well with the core resumable upload nature of TUS!

**Comment by butonic** [comment]
W still need to announce checksumming support in the TUS headers: https://github.com/owncloud/ocis/issues/1747

**Comment by butonic** [comment]
tracking wrong checksum for TUS in https://github.com/owncloud/ocis/issues/1755

**Comment by butonic** [comment]
https://github.com/cs3org/reva/pull/1400 got merged, closing this issue as open bugs are tracked in dedicated issues.

**Comment by michaelstingl** [comment]
> @michaelstingl could you comment on [tus/tus-resumable-upload-protocol#93](https://github.com/tus/tus-resumable-upload-protocol/pull/93) and explain why the `Tus-Min/Max-Chunk-Size` header makes sense for us? It seems they are looking for good reasons to add it: [tus/tusd#353 (comment)](https://github.com/tus/tusd/issues/353#issuecomment-596185770)

Done: https://github.com/tus/tus-resumable-upload-protocol/pull/93#issuecomment-802344992
