### ISSUE TITLE
Allow running reva with custom config.toml

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1280]
To allow enabling custom services we should add an environment variable that allows pointing reva to a custom config.toml.

However, since ocis-reva is just a wrapper around reva to preconfigure it I wonder how much we would gain. If you add a custom service to reva you will not be able to just run it with reva without compiling it.

Maybe it makes more sense to swap ocis with reva during deployment, then. Utlimately, the service will talk cs3 ... it does not matter if it is the ocis or reva binary. Especially when ocdav and ocs hes moved to ocis-webdav and ocis-ocs ...

🤔

**Comment by refs** [comment]
@butonic @IljaN is this still relevant?

**Comment by wkloucek** [comment]
I wouldn't support that... We deeply integrate REVA and will even more in the future (registry topic). All relevant REVA config options should be exposed to the oCIS config
