### ISSUE TITLE
Default capabilities for normal user and admin user not same as in oC-core

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#1285]
# Description
Default capabilities set to normal user using `ocis-reva `and `oC core` as backend are different.

# Steps to Reproduce:
1. export `REVA_USERS_DRIVER=demo` 
2. start `ocis-reva` server
3. Send a `curl` request to get `default capabilities` set for that user and save the response
```sh
curl -X GET http://localhost:9140/ocs/v1.php/cloud/capabilities -v -u einstein:relativity | xmllint --format -
```
4. Now create a normal user from `oc-backend` using occ command or UI whatever you prefer
5. Send another curl request to get default capabilities set for user created from oc-backend and save the response
```sh
curl -X GET http://localhost/core/ocs/v1.php/cloud/capabilities -v -u new:new | xmllint --format -
```

## Current Behaviour
Comparing two response I got, values for `default_permissions`, `defaultPublicLinkShareName`, `search_min_length` in files_sharing capabilities are different
 **Differences in two responses: only capabilities part of response xml that has different values are shown below)**
Form ocis-reva response
```xml
<capabilities>
	<files>
		<privateLinks>0</privateLinks>
		<bigfilechunking>0</bigfilechunking>
	</files>
	<files_sharing>
		<share_with_group_members_only>1</share_with_group_members_only>
		<share_with_membership_groups_only>1</share_with_membership_groups_only>
		<search_min_length>3</search_min_length>
		<default_permissions>22</default_permissions>
		<user_enumeration>
			<enabled>1</enabled>
			<group_members_only>1</group_members_only>
		</user_enumeration>
		<public>
			<send_mail>1</send_mail>
			<expire_date>
				<enabled>1</enabled>
			</expire_date>
		</public>
		<user>
			<send_mail>1</send_mail>
		</user>
	</files_sharing>
</capabilities>
```
And same from oC-core server
```xml
<capabilities>
    <files>
        <privateLinks>1</privateLinks>
        <privateLinksDetailsParam>1</privateLinksDetailsParam>
        <bigfilechunking>1</bigfilechunking>
    </files>
    <files_sharing>
        <public>
          <expire_date>
            <enabled/>
          </expire_date>
          <send_mail/>
          <defaultPublicLinkShareName>Public link</defaultPublicLinkShareName>
        </public>
        <share_with_group_members_only/>
        <share_with_membership_groups_only/>
        <user_enumeration>
          <group_members_only/>
        </user_enumeration>
        <default_permissions>31</default_permissions>
        <search_min_length>2</search_min_length>
    </files_sharing>
</capabilities>
```

Full response is here:
[Response with ocis-reva as server](https://gist.github.com/kiranparajuli589/55fbfae562c34dfbedde2f7e1ebd285e)
[Response with oc-core as server](https://gist.github.com/kiranparajuli589/83bf749c26aa8c650f614d54002c8261)

**Comment by kiranparajuli589** [comment]
`Update`:
User capabilities with
- **ocis:** https://gist.github.com/kiranparajuli589/dcd9bd4018ec14198fe9cd4751b0dda8
- **oC10:** https://gist.github.com/kiranparajuli589/5b40eb7fdb4cc029a9a0cc3f3e19f12e

**Comment by kiranparajuli589** [comment]
> `Update`: User capabilities with
> 
> * **ocis:** https://gist.github.com/kiranparajuli589/dcd9bd4018ec14198fe9cd4751b0dda8
> * **oC10:** https://gist.github.com/kiranparajuli589/5b40eb7fdb4cc029a9a0cc3f3e19f12e

response updated with respect to the current latest versions of oC10 and oCIS.

**Comment by grgprarup** [comment]
Admin user capabilities for ocis and oc10 are also different:
- oCIS https://gist.github.com/grgprarup/43d9df31d469ca0cf146696ae6c64c39
- oC10 https://gist.github.com/grgprarup/b40bf74c9f7b0e52639c14813096f719

**Comment by SwikritiT** [comment]
There still are tests linked t this issue in the expected to fail file https://github.com/owncloud/ocis/blob/ca929abd3aa1745912e33a99a83cc2c7ac0c3a06/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L640

But I think we review the tests and also need to clarify if the capabilities are even supposed to be same for oc10 and oCIS now


cc @saw-jan @PrajwolAmatya

**Comment by saw-jan** [comment]
CC @phil-davis @micbar @ScharfViktor

**Comment by phil-davis** [comment]
@saw-jan please get someone to record the current capabilities responses of oC10-core and ocis for a normal user, and a user with "admin" rights.

Many of the differences in the original post are just different default settings, and I think that we can adjust the ocis test scenario(s) to expect the settings that are set in the default ocis config for CI.

Anyway, let's see what the current differences are, and then decide.

**Comment by S-Panta** [comment]
The admin and normal user in both OC10 and ocis have the same capability. However, the admin/normal users' capability of OC10 and ocis doesn't match. 

- oCIS: https://gist.github.com/S-Panta/6689cda6c81f1bb2fe54a4167d370508
- oC10:https://gist.github.com/S-Panta/e02c62bf356e62de7e02715842bf8e0a

The parameter of `supportedTypes` inside `checksums`, `chunking` inside `dav` differs , `propfind` property inside `dav` is missing in oCIS.

**Comment by SwikritiT** [comment]
> The admin and normal user in both OC10 and ocis have the same capability. However, the admin/normal users' capability of OC10 and ocis doesn't match.
> 
> * oCIS: https://gist.github.com/S-Panta/6689cda6c81f1bb2fe54a4167d370508
> * oC10:https://gist.github.com/S-Panta/e02c62bf356e62de7e02715842bf8e0a
> 
> The parameter of `supportedTypes` inside `checksums`, `chunking` inside `dav` differs , `propfind` property inside `dav` is missing in oCIS and many more.

cc @phil-davis

**Comment by ScharfViktor** [comment]
We're not comparing ocis to oc-10 anymore. 
I fixed and deleted tests from expected failures here #9374
- which expected that `properties:capabilities->properties:files_sharing->properties:user->properties:profile_picture=true` -> now it's `false`
- `files_sharing-> default_permissions=31` we're not gonna fix it. 
- file-> blacklisted_files we have differebt aproach in ocis: https://github.com/owncloud/ocis/blob/master/deployments/examples/service_policies/policies/utils.rego
