### ISSUE TITLE
[BugOrFeature] Difference in response content of status.php and default capabilities

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#1286]
## Steps to reproduce:
1. start ocis-reva server with **demo users driver**
2. send curl request to get status.php as:
```sh
curl http://localhost:9140/status.php -v -u einstein:relativity | jq
```
Response data:
```json
{
  "installed": true,
  "maintenance": false,
  "needsDbUpgrade": false,
  "version": "10.0.9.5",
  "versionstring": "10.0.9",
  "edition": "community",
  "productname": "ownCloud"
}
```
3. now send another curl request to get capabilities
```sh
curl -X GET http://localhost:9140/ocs/v1.php/cloud/capabilities -v -u einstein:relativity | xmllint --format -
```
Here, inside the response xml `status` is as:
```xml
<status>
          <installed>1</installed>
          <maintenance>0</maintenance>
          <needsDbUpgrade>0</needsDbUpgrade>
          <version>10.0.11.5</version>
          <versionstring>10.0.11</versionstring>
          <edition>community</edition>
          <productname>reva</productname>
</status>
```

Is values of `productname`, `versionstring`, and `version` are meant to be different in above two requests?

**Comment by phil-davis** [comment]
@kiranparajuli589 does this still happen?

(If so, then something needs to be decided about what is the "product" and advertising the OCIS version (or the oC10 version that this OCIS is most-compatible with, or?))

**Comment by kiranparajuli589** [comment]
> @kiranparajuli589 does this still happen?

yes @phil-davis, the response for `/status.php` is the same as mentioned in the description.
<pre><font color="#5FD700">❯</font> curl -k -u admin:admin https://localhost:9200/status.php | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   197  100   197    0     0    810      0 --:--:-- --:--:-- --:--:--   807
<font color="#4D55F5"><b>{</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;installed&quot;</b></font><font color="#4D55F5"><b>: </b></font>true<font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;maintenance&quot;</b></font><font color="#4D55F5"><b>: </b></font>false<font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;needsDbUpgrade&quot;</b></font><font color="#4D55F5"><b>: </b></font>false<font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;version&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;10.0.9.5&quot;</font><font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;versionstring&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;10.0.9&quot;</font><font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;edition&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;community&quot;</font><font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;productname&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;ownCloud&quot;</font>
<font color="#4D55F5"><b>}</b></font>
</pre>

**Comment by phil-davis** [comment]
`apiCapabilities/capabilitiesWithNormalUser.feature:11` is a failing test scenario linked to this issue.

**Comment by phil-davis** [comment]
The test scenario `apiCapabilities/capabilitiesWithNormalUser.feature:11` currently fails with:
```
      Failed field core status@@@productname
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'ownCloud'
      +'reva'
```

We can easily adjust the test so that it expects the value "reva" when testing on `cs3org/reva` - I will have a look at doing that.

But what value should we report for `productname` when the system is oCIS?

**Comment by dragotin** [comment]
Both status.php and the capabilities report the same currently, yet they do report 
```
[:~/owncloud.com/ocis] master(+3/-1)+* ± curl -k https://localhost:9200/status.php{
    "installed": true,
    "maintenance": false,
    "needsDbUpgrade": false,
    "version": "10.0.11.5",
    "versionstring": "10.0.11",
    "edition": "community",
    "productname": "reva",
    "product": "reva"
```
It says reva and not oCIS.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
