### ISSUE TITLE
Checksum feature (OCIS storage driver)

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1291]
- [ ] ~OCFS: for now, only store checksum as given by client using arbitrary metadata but don't compute anything on server side~
- [ ] ~EOS: rewire to return EOS computed checksum~

The scope of this issue covers only the ocis storage and the DAV api.

**Comment by refs** [comment]
being currently worked on https://github.com/cs3org/reva/pull/1400

**Comment by refs** [comment]
reducing the scope of this issue to the ocis storage driver.

**Comment by C0rby** [comment]
Was implemented.
