### ISSUE TITLE
Renaming a resource to banned name is allowed

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/ocis#1295]
### Description
Renaming a file or folder to the banned name for eg; `\name` is not forbidden

### Steps to reproduce:
1. upload a file `curl -X PUT -uadmin:admin -k https://localhost:9200/remote.php/webdav/file1.txt -d"123"`
2. rename the file `curl -X MOVE -uadmin:admin -k https://localhost:9200/remote.php/webdav/file1.txt -H "Destination: https://localhost:9200/remote.php/webdav/\file1.txt" -v`
3. list files: `curl -X PROPFIND -uadmin:admin -k https://localhost:9200/remote.php/webdav | xmllint --format -`

a file with the name `<d:href>/remote.php/webdav/%5cfile1.txt</d:href>` is listed

It's also possible to upload a file with that name:
`curl -X PUT -uadmin:admin -k https://localhost:9200/remote.php/webdav/%5cfile2.txt -d"123"`

The same behavior is noticed for the folder.

**Comment by refs** [comment]
confirm it still occurs [with the latest master](https://github.com/owncloud/ocis/commit/f97f0d734261598315fdaeca309ecd1482ca6ed9).

**Comment by pascalwengerter** [comment]
Where is a `banned` name configured?

**Comment by individual-it** [comment]
I think the thought is that filenames with a `\` will get us into trouble on windows systems
I've updated the original post to make it easier to reproduce.
also web happily uploads a file with a `\` in its name, but it cannot download such a file again

If a `\` is a legal character in a files name then the issue needs to be moved to web, if not creating such files need to be prevented

**Comment by phil-davis** [comment]
Fixed by https://github.com/cs3org/reva/pull/1900
And by the reva update to OCIS: https://github.com/owncloud/ocis/pull/2334
