### ISSUE TITLE
Not all capabilities are configurable in Reva

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1299]
The file "pkg/command/frontend.go" defines a lot of capabilities and seem to be assuming that all values passed here will be processed by Reva.

However I discovered that only the config attributes that have `mapstructure` set in Reva will actually be overridable: https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/data/capabilities.go#L82

while others don't have this set.

We should review the list of capabilities and decide which should be configurable.
Then the frontend.go file should only contain the ones that are actually configurable.

This is the reason why the chunking capability override did not work back then in https://github.com/owncloud/ocis-reva/pull/145

@butonic FYI

**Comment by kobergj** [comment]
Basically works like this now.
