### ISSUE TITLE
Better naming for Reva.Gateway.URL

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1304]
`localhost:1234` is not a real URL it is actually a host & port. But Addr is reserved for Host and port to listen to.

we could prefix it with `cs3://`

https://github.com/owncloud/ocis-reva/blob/master/pkg/config/config.go#L50

**Comment by kobergj** [comment]
If it is about the corresponding EnvVar, we renamed it to `REVA_GATEWAY`. Assuming this closes the ticket.
