### ISSUE TITLE
Trashbin Delete not working

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#1307]
Delete a file and try to remove that file from the trasibn we get error.
```
curl 'http://172.17.0.1:9140/remote.php/dav/trash-bin/TU1/test.html.d1585113012' -X DELETE -u tu1:1234 -v
```
...
< HTTP/1.1 405 Method Not Allowed
...
```

**Comment by refs** [comment]
cc @IljaN , you were working on this. Perhaps if you manage to fix it this issue can be closed?

**Comment by C0rby** [comment]
It's working now.
