### ISSUE TITLE
Versions Cleanup not available

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#1310]
Currently there is no way to clean the versions AFAIK. 
In oc10 we use `occ versions:cleanup` but there is no occ equivalent in OCIS.

**Comment by pascalwengerter** [comment]
@dpakach if you re-open stalebot issues please either add a `Technical Debt` or `Bug` label so it doesn't get stale-d again in the future ;)

**Comment by micbar** [comment]
@individual-it @phil-davis This should not be part of the expected failures, as not in GA scope for oCIS

**Comment by phil-davis** [comment]
Note: expected-failures-webUI-on-OCIS-storage.md has
```
### [Versions Cleanup not available](https://github.com/owncloud/ocis/issues/1310)
- [webUIFilesActionMenu/versions.feature:37](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIFilesActionMenu/versions.feature#L37)
- [webUIFilesActionMenu/versions.feature:48](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIFilesActionMenu/versions.feature#L48)
- [webUIFilesActionMenu/versions.feature:63](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIFilesActionMenu/versions.feature#L63)
```

There are test steps like:
```
And the administrator has cleared the versions for user "user0" in the server
And the administrator has cleared the versions for all users in the server
```

This issue is not mention in expected-failures for API tests.

Some tag needs to be added to those web test scenarios so that they get skipped (and can be unskipped some time in the future), or delete the scenarios???

**Comment by SwikritiT** [comment]
The related tests have been skipped in https://github.com/owncloud/web/pull/7282. The CI should fail in the next web id bump and it can be removed from ocis as well.
