### ISSUE TITLE
Register services in the micro registry

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1318]
- allow service names to be configurable
- use default names like `com.owncloud.ocis.reva.storage.eos`, `com.owncloud.ocis.reva.gateway` ... `com.owncloud.ocis.storage.owncloud`
  - they can be given more meaningful names by the admin, eg. `com.mycompany.zones.public`?

**Comment by refs** [comment]
We've done this already.

**Comment by wkloucek** [comment]
was already closed
