### ISSUE TITLE
There is no such thing like a "super-user"

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1319]
who should be able to set settings of the instance?

> in oc10 there is the "admin" user that has special permissions e.g. set instance wise settings, enable apps, create users, etc.
There is now an "admin" role also in ocis, that role can administer users and groups.
So part of it is actually solved, but there is no ocis user that can administer instance wide settings. If that is by design we should close this ticket

**Comment by refs** [comment]
The ticket description will not really help when looking for it, what is the scope of this issue? How can this be turned into a meaningful discussion? :)

**Comment by individual-it** [comment]
in oc10 there is the "admin" user that has special permissions e.g. set instance wise settings, enable apps, create users, etc.
There is now an "admin" role also in ocis, that role can administer users and groups. 
So part of it is actually solved, but there is no ocis user that can administer instance wide settings. If that is by design we should close this ticket

**Comment by refs** [comment]
Ah, thanks for providing context!

**Comment by micbar** [comment]
This issue has been fixed in 2.0.0-beta1

The admin userID is not hardcoded anymore.

Admin permissions are granted based on roles.
