### ISSUE TITLE
System configuration options missing

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1323]
## System Configurations
- [ ] blacklisted_files
- [ ] blacklisted_files_regex
- [ ] excluded_directories
- [ ] excluded_directories_regex
- [ ] Disabling versions

**Comment by refs** [comment]
Closing and opening an issue with a broader scope.

**Comment by refs** [comment]
This ticket needs some care, and actually collect the missing config options.

**Comment by grgprarup** [comment]
Acceptance test scenarios removed with PR https://github.com/owncloud/ocis/pull/5633 related to this issue.

**Comment by micbar** [comment]
This is not needed anymore in todays context.
