### ISSUE TITLE
Deleted files come and go in the trashbin listing

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1324]
1. delete a file
2. send a PROPFIND to the trashbin endpoint

for me it takes 5-10 sec till that deleted file is shown in the trashbin

**Comment by refs** [comment]
ping @individual-it re-test with the latest master and keep open/close? 🙏

**Comment by individual-it** [comment]
Cannot reproduce the issue anymore, tested with OWNCLOUD & OCIS storage
it must have been fixed in between
