### ISSUE TITLE
Various sharing settings cannot be set

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1328]
- [ ] default / enforce expiry date
- [ ] shareapi_exclude_groups
- [ ] shareapi_only_share_with_membership_groups
- [ ] shareapi_auto_accept_share
- [ ] shareapi_enabled
- [ ] shareapi_allow_resharing
- [ ] shareapi_allow_group_sharing
- [ ] shareapi_allow_public_notification
- [ ] shareapi_enforce_links_password_read_only
- [ ] shareapi_enforce_links_password_read_write
- [ ] shareapi_enforce_links_password_read_write_delete
- [ ] shareapi_enforce_links_password_write_only
- [ ] shareapi_default_expire_date
- [ ] shareapi_expire_after_n_days
- [ ] shareapi_enforce_expire_date

**Comment by micbar** [comment]
Will be implemented on spaces, not per instance.

**Comment by phil-davis** [comment]
Then we should sort out skipping the related core API tests, and relevant oCIS-spaces-specific test scenarios can be added as the space settings options become available.

**Comment by phil-davis** [comment]
"Will be implemented on spaces, not per instance."

Closing this issue. As sharing settings/options are implemented in oCIS spaces, specific tests can be added along with each feature.
