### ISSUE TITLE
Make federation tests work

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1329]
- [ ] share between OCIS & OCIS
- [ ] ~~share between OCIS & oC10~~ not needed

**Comment by refs** [comment]
This needs a broader scope. Leaving it open but it MUST be back referenced to this issue when working on federated shares.

**Comment by micbar** [comment]
@ScharfViktor OCM in ocis is implemented. We need tests now.

**Comment by ScharfViktor** [comment]
at the QA meeting we decided: 
- test federation share only between two ocis instance
- test share using sharingNG (waiting https://github.com/owncloud/ocis/pull/8909) 
- link for docs https://doc.owncloud.com/ocis/5.0/deployment/services/s-list/ocm.html#creating-shares

**Comment by ScharfViktor** [comment]
closed as completed https://github.com/owncloud/ocis/pull/9414

Increased coverage of ocm tests will be in the next Prs
