### ISSUE TITLE
No way to enforce token auth

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1332]
in oC10 its possible to enforce token auth and disallow basic auth

**Comment by pmaier1** [comment]
This does not make sense considering the way oCIS handled authentication. Please adjust tests and remove from expected failures.

**Comment by phil-davis** [comment]
@dpakach we can tag the related tests with notToImplementOnOcis

**Comment by SwikritiT** [comment]
@phil-davis the tests linked to this issue have been removed from the expected-to-fail file. Maybe we can close this?
