### ISSUE TITLE
OCS apps endpoint does not exist

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1334]
the endpoint `/ocs/v1.php/cloud/apps` seems not to exist

**Comment by refs** [comment]
ping @individual-it , I'm not familiar with this endpoint but we do have `/ocs/v1.php/apps`, is it the same endpoint? If not, do we plan porting this feature into OCIS as part of the feature parity? /cc @micbar

**Comment by individual-it** [comment]
in OC10 that API provides access to the apps, list which one are enabled, trigger the status, etc.
Not sure if we need it in OCIS

**Comment by micbar** [comment]
@michaelstingl do we need that endpoint for clients?

**Comment by michaelstingl** [comment]
> @michaelstingl do we need that endpoint for clients?

no

**Comment by micbar** [comment]
This has no relevance anymore after #6993
