### ISSUE TITLE
OCS config endpoint only accessible by authorized users

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1338]
`ocs/v1.php/config` needs authorisation in OCIS, in oC10 its a public endpoint

**Comment by refs** [comment]
confirm it still happens [with the latest master](https://github.com/owncloud/ocis/commit/f97f0d734261598315fdaeca309ecd1482ca6ed9).

**Comment by wkloucek** [comment]
will be fixed by https://github.com/cs3org/reva/pull/2503

**Comment by wkloucek** [comment]
No longer the case for current master, try at eg. https://ocis.ocis-web.latest.owncloud.works/ocs/v1.php/config
