### ISSUE TITLE
Must show error if required setup is not in place

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#134]
The documentation states that a redis server is required and also some storage folders must be created beforehand.

### Steps

1. Start `ocis server` without starting redis nor preparing storage folders.

### Expected result

Error must be shown that redis is not available.
Error must be shown that the storage folders are not available.

### Actual result
No such errors, the output looks like everything is working fine which is misleading.

**Comment by refs** [comment]
The default storage has shifted to the ocis storage, this is no longer relevant in the case of a default run, only when the OwnCloud storage is explicitly required.
