### ISSUE TITLE
Uploading with old-chunking does not work

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1343]
trying to upload the file does not show any issues, but the result cannot be listed

```
$ curl --user user0:123456 http://localhost:9140/remote.php/webdav/home/file-chunking-1234-2-0 --request PUT -d"AAA" -H "OC-Chunked:1"
$ curl --user user0:123456 http://localhost:9140/remote.php/webdav/home/file-chunking-1234-2-1 --request PUT -d"BBB" -H "OC-Chunked:1"
$ curl --user user0:123456 http://localhost:9140/remote.php/webdav/home --request PROPFIND | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   854  100   854    0     0  50235      0 --:--:-- --:--:-- --:--:-- 50235
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/webdav/home/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjU1NDQwMDAwOmVjNzMwZGI3LTEyNjYtNDUwNC1iODYwLWQzMzNkMTliNTMxNw==</oc:id>
        <oc:fileid>MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjU1NDQwMDAwOmVjNzMwZGI3LTEyNjYtNDUwNC1iODYwLWQzMzNkMTliNTMxNw==</oc:fileid>
        <d:getetag>"d37e5cdffff691d3d6701109d75df380"</d:getetag>
        <oc:permissions>WCKDNVR</oc:permissions>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:getcontenttype>httpd/unix-directory</d:getcontenttype>
        <oc:size>4096</oc:size>
        <d:getlastmodified>Tue, 21 Jan 2020 07:52:05 UTC</d:getlastmodified>
        <oc:favorite>0</oc:favorite>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>

```

**Comment by dpakach** [comment]
@butonic @refs will the chunking upload ever be implemented in ocis? If not we can remove the tests that are currently being run(but fails) for the chunking upload.

**Comment by refs** [comment]
Hi @dpakach !

It depends on the backend - decomposedfs uses tus by default, but I know by a fact that EOS uses the old chunking and not tus. My gut feeling tells me to remove the tests for the current decomposedfs because we use tus, but perhaps @pmaier1 or @micbar can bring more to the table.

**Comment by dpakach** [comment]
Since there has not been any updates here, I will skip those tests as we dont run tests with EOS here. We can reenable them in the future if it is required.

**Comment by phil-davis** [comment]
Note: "old" v1 chunking is supported on reva and OCIS. Many of the scenarios are now passing. So we do want to keep running chunking v1 test scenarios in reva and oCIS.

**Comment by SwikritiT** [comment]
there are tests linked to this issue

https://github.com/owncloud/ocis/blob/09ff21ace56566127e3e328dd1a179936f918734/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L1404-L1414

**Comment by ScharfViktor** [comment]
we didn't move tests `apiWebdavUpload1/uploadFileToExcludedDirectory` to ocis and we have now no tests in the expected failures and

**Comment by SwikritiT** [comment]
> we didn't move tests `apiWebdavUpload1/uploadFileToExcludedDirectory` to ocis and we have now no tests in the expected failures and

Why didn't we move them are they not relevant for the current ocis?

**Comment by SwikritiT** [comment]
> > we didn't move tests `apiWebdavUpload1/uploadFileToExcludedDirectory` to ocis and we have now no tests in the expected failures and
> 
> Why didn't we move them are they not relevant for the current ocis?

https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectory.feature
They used `occ` commands to do the certain operation so probably because of that?
But is this issue still relevant for ocis?

**Comment by micbar** [comment]
Not relevant for ocis anymore.
