### ISSUE TITLE
CORS issue upon startup

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#136]
### Steps

1. Follow the instructions

### Expected result
Ability to login

### Actual result
<img width="957" alt="image" src="https://user-images.githubusercontent.com/277525/76437365-c1d0af00-63b9-11ea-8a71-28ebea18ac7e.png">

### Version
git master d4f7f29275adfd6bb1a72267727522f20c265c68

**Comment by PVince81** [comment]
Solution is to implement a reverse proxy: https://github.com/owncloud/ocis/issues/119

**Comment by PVince81** [comment]
The workaround is to open https://localhost:9130/.well-known/openid-configuration and accept the certificate. Then refresh the login page.

**Comment by micbar** [comment]
Proxy is already implemented.
Need to be part of the `server` command.

@IljaN In scope for this sprint.
We are currently working on a demo deployment.
