### ISSUE TITLE
Do not duplicate configuration between oCIS & Reva

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1379]
We currently have to maintain/be aware of two sets of parameters, one for oCIS and one for Reva. The connection point is the `flagset.go` files. By doing so we're compromising to maintain config parameters up to date with reva. In other words we're forwarding configuration from oCIS to Reva. While this is okay, it is not ideal to have two different codebases tied by their parameters.

A proposal is to normalize oCIS to understand certain Reva configuration (or vice versa). The main issue is that both projects have entirely different approaches to configuration. Reva relies on [hashicorp/mapstruct](https://github.com/mitchellh/mapstructure) whereas oCIS relies on [spf13/Viper](https://github.com/spf13/viper).

**Comment by kobergj** [comment]
Doesn't make sense to tackle any more. Effort would be too big considering the benefit.
