### ISSUE TITLE
Can't login to OCIS (runtime error in konnect)

### ISSUE THREAD

**Issue by m0nhawk** [owncloud/ocis#1395]
## Describe the bug

Can't login to OCIS with default user, getting error: "Login Error You are not allowed to use this application."

## Steps to reproduce

1. Try to login with `admin`/`admin`.

## Expected behavior

Successful login.

## Actual behavior

1. Redirected to https://.../#/access-denied
2. "Login Error You are not allowed to use this application."
<details>
<img width="496" alt="Screen Shot 2021-01-23 at 1 38 20 AM" src="https://user-images.githubusercontent.com/8220926/105572265-b8271000-5d1b-11eb-992c-4bd71705c044.png">
</details>

## Setup

Dedicated server with Traefik and OCIS based on [this](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_traefik) with few changes to environmental variables. Running `latest (sha256:ae3b15b708)`. Domain is replaced with `...`.

<details>
<p>

```console
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - KONNECTD_ISS=https://...
      - REVA_OIDC_ISSUER=https://...
      - REVA_DATAGATEWAY_URL=https://.../data
      - REVA_FRONTEND_URL=https://...
      - PHOENIX_OIDC_AUTHORITY=https://...
      - PHOENIX_WEB_CONFIG_SERVER=https://...
      - PHOENIX_OIDC_METADATA_URL=https://.../.well-known/openid-configuration
      - KONNECTD_TLS=0
      - KONNECTD_LOG_LEVEL=debug
      - KONNECTD_IDENTIFIER_REGISTRATION_CONF=/etc/ocis/identifier-registration.yml
      - OCIS_URL=https://...
      - OCIS_LOG_LEVEL=${OCIS_LOG_LEVEL:-debug} # make oCIS less verbose
      - PROXY_TLS=false
```

</p>
</details>

## Additional context
Debug log attached.

[ocis.log.tar.gz](https://github.com/owncloud/ocis/files/5859850/ocis.log.tar.gz)

Relevant part of log:

```
ocis              | {"level":"debug","service":"glauth","handler":"ocis","num_entries":1,"binddn":"cn=konnectd,ou=sysusers,dc=example,dc=org","basedn":"dc=example,dc=org","filter":"(objectClass=posixaccount)","src":{"IP":"127.0.0.1","Port":55226,"Zone":""},"time":"2021-01-23T07:23:59.184629558Z","message":"AP: Search OK"}
ocis              | 2021-01-23 07:23:59.185102 I | http: panic serving 127.0.0.1:37418: runtime error: slice bounds out of range [4:3]
ocis              | goroutine 3043 [running]:
ocis              | net/http.(*conn).serve.func1(0xc001abcbe0)
ocis              | 	/usr/local/go/src/net/http/server.go:1801 +0x147
ocis              | panic(0x362f620, 0xc0015af220)
ocis              | 	/usr/local/go/src/runtime/panic.go:975 +0x47a
ocis              | stash.kopano.io/kc/konnect/identity/clients.(*Registry).getDynamicClient(0xc00013ab40, 0xc000f6efe8, 0x3, 0x3, 0x512b620)
ocis              | 	/srv/app/pkg/mod/stash.kopano.io/kc/konnect@v0.33.3/identity/clients/registry.go:321 +0x19c
ocis              | stash.kopano.io/kc/konnect/identity/clients.(*Registry).Get(0xc00013ab40, 0x3bd5a60, 0xc000143da0, 0xc000f6efe8, 0x3, 0x1, 0x1)
ocis              | 	/srv/app/pkg/mod/stash.kopano.io/kc/konnect@v0.33.3/identity/clients/registry.go:315 +0xc5
```

**Comment by wkloucek** [comment]
Thanks for opening this issue.

> Domain is replaced with ....

Looks like your domain name is invalid. Could you give it a try with some compliant domain name? You also could give it a try with the IP address of your oCIS host.

**Comment by m0nhawk** [comment]
I meant that for issue I replaced the domain with `...`, I have a correct FQDN in the actual config and logs.

**Comment by wkloucek** [comment]
> I meant that for issue I replaced the domain with `...`, I have a correct FQDN in the actual config and logs.

Ok thanks for clarifying.

@IljaN can you have a look?

**Comment by IljaN** [comment]
@m0nhawk Could you please provide the output of following commands?
```docker exec -it ocis_traefik_ocis_1 printenv```
and
```
docker exec -it ocis_traefik_ocis_1 cat /config/identifier-registration.yaml
```
Thanks!

**Comment by m0nhawk** [comment]
_(domain is replaced by `...`, it's real in config)_

`printenv`
<details>
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=e2e69f079bd0
TERM=xterm
PROXY_HTTP_ADDR=0.0.0.0:9200
REVA_OIDC_ISSUER=https://...
REVA_DATAGATEWAY_URL=https://.../data
REVA_FRONTEND_URL=https://...
PHOENIX_OIDC_AUTHORITY=https://...
PHOENIX_WEB_CONFIG_SERVER=https://...
PHOENIX_OIDC_METADATA_URL=https://.../.well-known/openid-configuration
KONNECTD_TLS=0
KONNECTD_LOG_LEVEL=info
KONNECTD_IDENTIFIER_REGISTRATION_CONF=/etc/ocis/identifier-registration.yml
OCIS_URL=https://...
OCIS_LOG_LEVEL=info
PROXY_TLS=false
HOME=/root
</details>

`cat /config/identifier-registration.yaml` (taken from [here](https://github.com/owncloud/ocis/blob/8dd28582ccbdb21756b2e53e6498e96e43793192/konnectd/assets/identifier-registration.yaml) and removed the localhost URL's - but with them it was the same, also I tried with commenting out the mobile apps).
<details>
---

# OpenID Connect client registry.
clients:
  - id: web
    name: ownCloud web app
    trusted: yes
    insecure: yes
    redirect_uris:
      - https://.../
      - https://.../oidc-callback.html
      - https://.../oidc-silent-redirect.html
    origins:
      - https://...

  - id: ocis-explorer.js
    name: oCIS Graph Explorer
    trusted: yes
    insecure: yes

  - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
    secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
    name: ownCloud desktop app
    application_type: native
    insecure: true

  - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
    secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
    name: ownCloud Android app
    application_type: native
    redirect_uris:
      - oc://android.owncloud.com

  - id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
    secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
    name: ownCloud iOS app
    application_type: native
    redirect_uris:
      - oc://ios.owncloud.com
      - oc.ios://ios.owncloud.com


#  - id: playground-trusted.js
#    name: Trusted OIDC Playground
#    trusted: yes
#    application_type: web
#    redirect_uris:
#       - https://my-host:8509/
#    origins:
#       - https://my-host:8509

#  - id: playground-trusted.js
#    name: Trusted Insecure OIDC Playground
#    trusted: yes
#    application_type: web
#    insecure: yes

#  - id: client-with-keys
#    secret: super
#    application_type: native
#    redirect_uris:
#      - http://localhost
#    trusted_scopes:
#      - konnect/guestok
#      - kopano/kwm
#    jwks:
#      keys:
#        - kty: EC
#          use: sig
#          kid: client-with-keys-key-1
#          crv: P-256
#          x: RTZpWoRbjwX1YavmSHVBj6Cy3Yzdkkp6QLvTGB22D0c
#          y: jeavjwcX0xlDSchFcBMzXSU7wGs2VPpNxWCwmxFvmF0
#    request_object_signing_alg: ES256

#  - id: first
#    secret: lala
#    application_type: native
#    redirect_uris:
#      - my://app

#  - id: second
#    secret: lulu
#    application_type: native
#    redirect_uris:
#      - http://localhost

# External authority registry.
authorities:
#  - id: my-univention
#    name: Univention
#    client_id: kopano-konnect
#    authority_type: oidc
#    jwks:
#      keys:
#        - kty: EC
#          use: sig
#          kid: example-key-1
#          crv: P-256
#          x: RTZpWoRbjwX1YavmSHVBj6Cy3Yzdkkp6QLvTGB22D0c
#          y: jeavjwcX0xlDSchFcBMzXSU7wGs2VPpNxWCwmxFvmF0
#    default: yes
#    authorization_endpoint: https://my-univention/signin/v1/identifier/_/authorize
#    response_type: id_token
#    scopes:
#      - openid
#      - profile
#    identity_claim_name: preferred_username
#    identity_aliases:
#      external-user-a: local-user-a
#      external-user-b: local-user-b
#    identity_alias_required: true
</details>

**Comment by IljaN** [comment]
I am able to reproduce the error

**Comment by IljaN** [comment]
Hey @m0nhawk 

could you please provide the output of: 
```
docker exec -it ocis_traefik_ocis_1 cat /etc/ocis/identifier-registration.yml
```

I can reproduce this error by having an empty identifier-registration.yaml. On the server-startup there should be lines like this which show from where the client config is loaded.

```
2021-02-01T15:01:18+01:00 DBG parsing identifier registration conf from /home/ilja/code/ocis/idp/config/identifier-registration.yaml service=idp
2021-02-01T15:01:18+01:00 DBG registered client application_type=web client_id=web insecure=true origins=["https://localhost:9200"] redirect_uris=["https://localhost:9200/","https://localhost:9200/oidc-callback.html","https://localhost:9200/oidc-silent-redirect.html"] service=idp trusted=true with_client_secret=false
2021-02-01T15:01:18+01:00 DBG registered client application_type=web client_id=ocis-explorer.js insecure=true origins=[] redirect_uris=[] service=idp trusted=true with_client_secret=false
2021-02-01T15:01:18+01:00 DBG registered client application_type=native client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69 insecure=true origins=[] redirect_uris=[] service=idp trusted=false with_client_secret=true
2021-02-01T15:01:18+01:00 DBG registered client application_type=native client_id=e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD insecure=false origins=[] redirect_uris=["oc://android.owncloud.com"] service=idp trusted=false with_client_secret=true
2021-02-01T15:01:18+01:00 DBG registered client application_type=native client_id=mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1 insecure=false origins=[] redirect_uris=["oc://ios.owncloud.com","oc.ios://ios.owncloud.com"] service=idp trusted=false with_client_secret=true
```
Could you check if the path in the first line matches the environment variable KONNECTD_IDENTIFIER_REGISTRATION_CONF=/etc/ocis/identifier-registration.yml from your configuration?

**Comment by m0nhawk** [comment]
For some reasons it doesn't treat `KONNECTD_IDENTIFIER_REGISTRATION_CONF` well, I have the following in the logs:

```
ocis              | {"level":"debug","service":"idp","time":"2021-02-01T17:54:36.199900476Z","message":"parsing identifier registration conf from /config/identifier-registration.yaml"}
ocis              | {"level":"debug","service":"idp","time":"2021-02-01T17:54:36.200140427Z","message":"parsing authorities registration conf from /config/identifier-registration.yaml"}
```

**Comment by m0nhawk** [comment]
I have moved my config to `/config.identifier-registration.yaml` and still have the same error:

```
ocis              | {"level":"debug","service":"idp","time":"2021-02-01T18:08:52.255309828Z","message":"parsing identifier registration conf from /config/identifier-registration.yaml"}
ocis              | {"level":"debug","service":"idp","application_type":"web","client_id":"phoenix","insecure":true,"origins":["https://..."],"redirect_uris":["https://.../","https://.../oidc-callback.html","https://.../oidc-silent-redirect.html"],"trusted":true,"with_client_secret":false,"time":"2021-02-01T18:08:52.255466422Z","message":"registered client"}
ocis              | {"level":"debug","service":"idp","application_type":"native","client_id":"xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69","insecure":true,"origins":[],"redirect_uris":[],"trusted":false,"with_client_secret":true,"time":"2021-02-01T18:08:52.25550217Z","message":"registered client"}
ocis              | {"level":"debug","service":"idp","application_type":"native","client_id":"e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD","insecure":false,"origins":[],"redirect_uris":["oc://android.owncloud.com"],"trusted":false,"with_client_secret":true,"time":"2021-02-01T18:08:52.255513681Z","message":"registered client"}
ocis              | {"level":"debug","service":"idp","application_type":"native","client_id":"mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1","insecure":false,"origins":[],"redirect_uris":["oc://ios.owncloud.com","oc.ios://ios.owncloud.com"],"trusted":false,"with_client_secret":true,"time":"2021-02-01T18:08:52.255524301Z","message":"registered client"}
ocis              | {"level":"debug","service":"idp","time":"2021-02-01T18:08:52.255535402Z","message":"parsing authorities registration conf from /config/identifier-registration.yaml"}
```

**Comment by IljaN** [comment]
Hmhhh this looks correct now. Have you ensured that you have a fresh session in the browser? Try to login in a incognito tab.

**Comment by IljaN** [comment]
Also I noticed that you still have "client-id=phoenix", it looks like the config file is outdated because it is called "web" now. 
See: https://github.com/owncloud/ocis/blob/master/idp/assets/identifier-registration.yaml

**Comment by m0nhawk** [comment]
Yes, I'm using only Incognito.

Changing to `web` fixes this issue. 

Now I probably have an issue with my Traefik setup with:

```
ocis              | {"level":"error","service":"proxy","error":"Get \"https://.../.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","time":"2021-02-02T15:27:29.110217725Z","message":"could not initialize oidcAuth provider"}
```

But that's another issue.

**Comment by IljaN** [comment]
@m0nhawk Thanks for the report! Created a new issue as konnect as it should fail more obviously.
