### ISSUE TITLE
basic remote setup is outdated

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1397]
https://owncloud.github.io/ocis/deployment/basic-remote-setup/

does not take into account the OCIS_URL and that we are now generating the identifier registration.yml.

https://owncloud.github.io/ocis/deployment/basic-remote-setup/#use-docker-compose even mentions the playground

kill it with 🔥

**Comment by dragotin** [comment]
Started here: https://github.com/owncloud/ocis/pull/1398

**Comment by wkloucek** [comment]
Also started something here: #1209
But I run into some trouble which requires code changes and I had not yet enough time to continue

**Comment by wkloucek** [comment]
@butonic please have a look at #1209 if it fixes this
