### ISSUE TITLE
Notifications endpoint

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#14]
currently cs3 has no notification mechanisms, but we should plan and collect ideas so we can collaborate on this at the conference, eg:
- [ ] long polling?
    - can be done efficiently with golang
    - http vs grpc
- [ ] do we need a CS3 endpoint?
- [ ] needs to aggregate changes from various resources
  - seperate service with it's own cache
  - storage providers the user has access to
  - sharing events
  - actvities app
- [ ] document how to disable the polling using capabilities

**Comment by madsi1m** [comment]
Can we have at least a dummy page for this so web browser console logs doesn't complain?

**Comment by madsi1m** [comment]
https://github.com/cs3org/reva/pull/417

**Comment by refs** [comment]
@madsi1m in theory notifications can be disabled on your configuration:

https://github.com/cs3org/reva/blob/9db3db0b635220af892be62b55207176aa88159e/internal/http/services/owncloud/ocs/capabilities.go#L209-L214

**Comment by madsi1m** [comment]
Is that a different thing? The requests i see come from Phoenix

**Comment by refs** [comment]
to be entirely clear @madsi1m, the error you're seeing in the console is

![image](https://user-images.githubusercontent.com/6905948/70425765-12123b00-1a72-11ea-8652-050b2ef30f9f.png)

**Comment by madsi1m** [comment]
yup, the same, the pull request sends a 200 to that endpoint

**Comment by butonic** [comment]
currently ocis registers the following storages
```
/                   local storage
    ├── home        owncloud driver with path wrapper, jailing the user into his home
    └── oc          owncloud driver
```

etag changes in /home or /oc will not propagate up into tho root, which is by design. otherwise / would become a bottleneck.

The desktop client should only need to (long) poll a single endpoint (per instance) to discover changes. A proper implementation would separate the two underlying problems to implement this:
- a delta endpoint that uses tokens to only show new changes to clients
- a notification mechanism to notify all registered clients of a change

Instead of a delta endpoint we can use the state based sync, but we need a notification mechanism that:
1. can tell the clients in which folder to start the state based sync (eg. directly in /oc/einstein/documents)
2. can handle backpressure to protect clients from handling 100k notifications at once
3. can work in a globally distributed environment
  - the challenge here is that events need to be added to a single queue which should avoid locking

As an alternative for the notification mechanism we could poll all storages a user has access to on the server side and aggregate the etags. I'd prefer to avoid spamming stat calls like that, even if they are cached by the vfs in the kernel. Some storage drivers may have to do network trips to answer stat, which - if uncached - would quickly become a (latency, bandwith or cost) problem.

**Comment by madsi1m** [comment]
Dumb question here: Could we change the sync client to sync just one storage endpoint? Maybe have /home by default.
Also allow multiple sync endpoints in the branded client, so users can pick which storage’s you sync.

It seems all the possible solutions have pros and cons. The delta of state per endpoint is my favourite and worth exploring further.

**Comment by labkode** [comment]
I agree with @madsi1m that is the more user-friendly approach. We do basically here with CERNBox[0].

However, shares and projects they should be exposed inside the user home directory as having the user to sync one by one shares and projects is counter-productive (we have this burden since long-time).

![home-global](https://user-images.githubusercontent.com/5175912/72882732-652f0d00-3d03-11ea-913f-0d15c597bde7.png)

**Comment by butonic** [comment]
Needs an ADR
