### ISSUE TITLE
remove `pkg/proto/v0/accounts.mock.go`

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1401]
get rid of handwritten `pkg/proto/v0/accounts.mock.go` after https://github.com/owncloud/ocis-accounts/pull/103 is merged and ocis-proxy is using the new mock.

**Comment by phil-davis** [comment]
@butonic this is an old issue that was transferred from the archived `ocis-accounts` repo a few weeks ago.
Please close if no longer relevant.

**Comment by refs** [comment]
@butonic I could bring the diff from https://github.com/owncloud/ocis-accounts/pull/103/files to accounts. Do we want this?

**Comment by wkloucek** [comment]
accounts service was completely removed, therefore no longer valid
