### ISSUE TITLE
Make service work with other registry than mdns

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#1403]
https://github.com/owncloud/ocis-accounts/blob/0d4e6a4a16ec2446270fc591eaddef2b6cf06d38/pkg/service/v0/settings.go#L96

Same as: https://github.com/owncloud/ocis-proxy/issues/38

**Comment by phil-davis** [comment]
@IljaN this is an old issue that was transferred from the archived `ocis-accounts` repo a few weeks ago.
Please close if no longer relevant.

**Comment by IljaN** [comment]
Fixed
