### ISSUE TITLE
makefile differs from eg ocis-hello wrt protobuf

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1406]
This Makefile has a PHONY `pb` target just runs protoc ... whereas ocis-hello uses the more make way of [listing the generated files as build targets](https://github.com/owncloud/ocis-hello/blob/master/Makefile#L169-L194)

We should agree to a common format. I think ocis-hello does this the rigth way. (👍 if you agree, 👎 
 if you don't)

Furthermore, I seem to miss dependencies, but there is no make deps or anything:
```
make pb
protoc --go_out=. --micro_out=. pkg/proto/v0/*.proto
google/protobuf/empty.proto: File not found.
pkg/proto/v0/accounts.proto:5:1: Import "google/protobuf/empty.proto" was not found or had errors.
pkg/proto/v0/accounts.proto:10:14: "google.protobuf.Empty" is not defined.
make: *** [Makefile:161: pb] Fehler 1
```

**Comment by phil-davis** [comment]
outdated
