### ISSUE TITLE
Registry based proxy routing configuration

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1410]
We should be able to derive the list for apps for the config.json from the micro registry. This will get rid of hardcoded configs checked into assets folders. And the service addresses can change dynamically, too.

**Comment by phil-davis** [comment]
@butonic this is an old issue that was transferred from the archived `ocis-phoenix` repo a few weeks ago.
Please close if no longer relevant.

**Comment by pascalwengerter** [comment]
@refs does #2708 touch/fix this?

**Comment by refs** [comment]
@pascalwengerter nope

**Comment by wkloucek** [comment]
This is how it should be done:
- when a service registers itself at the registry, it can add routing information for the proxy in the metadata
- the proxy regularly queries all services and checks the metadata for routing information

Challenges:
- REVA services also must support it (we have multiple http based services in REVA, eg. datagateway, appprovider, ocdav, ...)

**Comment by micbar** [comment]
we discussed this and the outcome was that making that dynamic is too risky.
