### ISSUE TITLE
Getting user from /ocs/v2.php/cloud/user endpoint doesn't work

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#1415]
When we try to get user without any uid and gid from endpoint `/ocs/v2.php/cloud/user`, we get `statuscode 400` and  `error message  "missing user in context"`

### Actual behavior 
It gives error message
```
curl -X GET -k -H "OCS-APIREQUEST=true" https://localhost:9200/ocs/v2.php/cloud/user -u admin:admin -v | xmllint --format -

100   155  100   155    0     0  15500      0 --:--:-- --:--:-- --:--:-- 15500
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>missing user in context</message>
  </meta>
</ocs>
```
### Expected behavior 
Something similar to of `/ocs/v2.php/cloud/users/admin` 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>200</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <users>
        <username>admin</username>
        <userid>admin</userid>
       ....
    </users>
  </data>
</ocs>
```

**Comment by phil-davis** [comment]
@dpakach @swoichha this is an old issue that was transferred from the archived `ocis-ocs` repo a few weeks ago.
Please close if no longer relevant.

I don't see this issue mentioned in expected-failures.
