### ISSUE TITLE
Add OIDC Testuite to CI 

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#1429]
There is an (official?) oidc testuite to test IDPs for standard conformance. Needs some research if/how it is usable.

https://github.com/openid-certification
https://github.com/openid-certification/oidctest
https://openid.net/certification/

**Comment by phil-davis** [comment]
@IljaN @DeepDiver1975 this is an old issue that was transferred from the archived `ocis-konnectd` repo a few weeks ago.
Please close if no longer relevant.
