### ISSUE TITLE
rename proxy to gateway

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1432]
ocis-proxy is the entrypoint for all requests. it might be confused with reverse proxy, but it does a lot more:
- it authenticates users using oidc
- it fetches the account uuid
- it mints an internal token that other services like reva or settings use to authenticate the request and get acccess to the basic account properties without having to make a call to ocis-accounts
- it CAN act as a proxy ... but it actually implements the [microservice gateway pattern](https://microservices.io/patterns/apigateway.html)

see also: https://auth0.com/blog/an-introduction-to-microservices-part-1/
![Microservices2 1](https://user-images.githubusercontent.com/956847/85158864-0becea80-b25d-11ea-9460-b9d6a38b4dc1.png)

**Comment by phil-davis** [comment]
@butonic this is an old issue that was transferred from the archived `ocis-proxy` repo a few weeks ago.
Please close if no longer relevant.

**Comment by kobergj** [comment]
> Please close if no longer relevant.

I think after another 3 years we can fairly say that this is no longer relevant.
