### ISSUE TITLE
previews cannot be fetched through the proxy

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1433]
when requesting the previews through port 9140 it works but not through 9200

**Comment by phil-davis** [comment]
@individual-it this is an old issue that was transferred from the archived `ocis-proxy` repo a few weeks ago.
Please close if no longer relevant.

**Comment by individual-it** [comment]
I think this works now, I see preview requests coming via :9200
`https://localhost:9200/remote.php/dav/files/admin/Screenshot%20from%202020-12-08%2010-17-55.png?a=1&c=a0e1f6cf1bccf1b3e43c4485b2b6f10d&preview=1&scalingup=0`
