### ISSUE TITLE
document why we mint an x-access-token header

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1434]
we mint our own token after authenticating the request.
internal services use that token to authenticate requests
reva uses x-access-token for the same thing
we reuse that token, so the reva gateway does not have to reauthenicate using oidc

**Comment by phil-davis** [comment]
@butonic this is an old issue that was transferred from the archived `ocis-proxy` repo a few weeks ago.
Please close if no longer relevant.

**Comment by butonic** [comment]
closing in favor of https://github.com/owncloud/ocis/issues/4701
