### ISSUE TITLE
Make uuid middleware work with other service-registry than mdns

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#1435]
See https://github.com/owncloud-docker/compose-playground/blob/master/examples/services/add-user/add-user.go#L17 for an example. Maybe there is even a better way which does not require instantiation of a new service?

Micro controls the service-registry type with the environment variable MICRO_REGISTRY. This setting does not work because the proxy is not wrapped in a micro-service. 

Two possible routes to fix this:
- Use the micro way and wrap the proxy in to a service.
- Manually instantiate a dummy service and use it`s client. (like in the example above)

**Comment by phil-davis** [comment]
@IljaN @butonic this is an old issue that was transferred from the archived `ocis-proxy` repo a few weeks ago.
Please close if no longer relevant.
