### ISSUE TITLE
Look in to automatic redirect from http to https

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#1437]
Need more research how to do this in context of proxy. As the current implementation only works with x-forwarded-proto. Maybe set HSTS header?

**Comment by phil-davis** [comment]
@IljaN this is an old issue that was transferred from the archived `ocis-proxy` repo a few weeks ago.
Please close if no longer relevant.

**Comment by C0rby** [comment]
Is no longer relevant.
