### ISSUE TITLE
Viper ignores cli flags (Viper + urfave/cli)

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1440]
For more context take a look at https://github.com/owncloud/ocis-proxy/pull/13

But essentially when using command flags and a config file loaded by Viper, flags are not taking into account.

There is a section on working with flags on Viper, but attempts to make it work with our flag sets were unsuccessful.

- [Working with Flags](https://github.com/spf13/viper#working-with-flags)

**Comment by phil-davis** [comment]
@refs this is an old issue that was transferred from the archived `ocis-proxy` repo a few weeks ago.
Please close if no longer relevant.
