### ISSUE TITLE
http and grpc server have their own service handler instance

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1441]
Both the http and the grpc/http2 server create their own service handler instance. This might lead to problems, as both service instances are accessing the same files. So if concurrent requests come in we don't have a chance to lock properly.

We could either get rid of the http server entirely (api gateway) or move the service handler instance to a higher level, so that both servers can reuse the same shared service handler instance.

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by kulmann** [comment]
Will become irrelevant when we switch to an API gateway in our current proxy service.
