### ISSUE TITLE
Introduce role management permission

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1443]
We need a role management permission and add it to the admin role in order to be able to restrict role management endpoints.

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by kulmann** [comment]
We have role management permissions already https://github.com/owncloud/ocis/blob/eab96d59a83f748b04abb6116ed06f13db1ea0cd/settings/pkg/service/v0/service.go#L455
