### ISSUE TITLE
no validation for SaveValue

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1445]
`SaveValue()` does not have any validation
- values outside the defined bracket (Min, Max) can be written
- values of different types can be written

**Comment by phil-davis** [comment]
@individual-it this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by individual-it** [comment]
looking at https://github.com/owncloud/ocis/blob/master/settings/pkg/proto/v0/settings.pb.micro_test.go this seems still be relevant

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
