### ISSUE TITLE
Operations concept in permissions

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1446]
As of now, permissions are built referencing operations on resources. The types of operations are hardcoded:
https://github.com/owncloud/ocis-settings/blob/a828816458d634851251f20ce7b2c83f22ba8c52/pkg/proto/v0/settings.proto#L331

There are concerns about this that need to be discussed ASAP:
- questionable if hardcoded operations give us sufficient flexibility
- how to combine certain operations into one? e.g. for permissions on settings, it is probably not necessary to distinguish `CREATE` and `UPDATE` operations and only have a `WRITE` operation instead.

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by kulmann** [comment]
We added some more operations. The topic will come up in the future again, but on a broader scope. This ticket here is probably not that relevant.
