### ISSUE TITLE
Translate dynamically rendered strings

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1447]
Bundles and settings come with a displayName, which is rendered in the UI, e.g. here https://github.com/owncloud/ocis-settings/blob/a828816458d634851251f20ce7b2c83f22ba8c52/ui/components/SettingsBundle.vue#L4

As transifex works by extracting strings from the templates, these displayNames will not be visible in any translation files. We need to investigate, how to make e.g. the displayName translatable.

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by kulmann** [comment]
We did not figure out yet, how to solve this. Still relevant.

**Comment by jvillafanez** [comment]
I guess the easiest option is for the UI to assume the string is translated already, so it can be shown as it is. This means that the translation should happen in the server.
One problem to take into account is how the language is chosen. Taking into account the mobile clients might be configured in a different language, I guess the clients will need a way to send which language the messages should be translated to.

As far as I know, this is how it's implemented in OC10.

An alternative could be to provide a translation service so the UI can ask for the translation there, but this seems quite complex taking into account that it's easy for the translations to de-sync when the original string is in a different service.
