### ISSUE TITLE
Discussion: how to handle extension displayNames and icons?

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1450]
## Context:
We are injecting navItems into the sidebar from loaded settings bundles. Each extension with at least one settings bundle will have it's own sidebar nav item. So if there are e.g. `Profile` and `Notifications` settings bundles coming from `ocis-accounts` we will have a navItem in the sidebar for `ocis-accounts`.

## Problem:
We only have the extension id as of now (in the example above: `ocis-accounts`). But we want to show a proper display name and an icon in the sidebar.

## Solution 1:
We could include a meta data field in the settings bundle, allowing to define the extension displayName and icon. A disadvantage would be that the extension meta data would be present in all settings bundles and could even be different on for the same extension. So possible problem with consistency of data and definitely data duplication.

## Solution 2:
We could add an endpoint for registering extension meta data and store meta data about extensions in the settings service. Then build sensible fallbacks in the ui, if an extension has no meta data registered (e.g. default icon and build a displayname from the extension id by replacing dashes with spaces and making first letters of every word uppercase).

## Solution 3:
Like Solution 2, but as a whole new service (extension meta data service). 🤷

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by kulmann** [comment]
still relevant, but not that pressing at the moment

**Comment by kulmann** [comment]
Not relevant anymore, we don't have the settings UI anymore.
