### ISSUE TITLE
list values can contain different types of values

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1454]
`SaveSettingsValue()` accepts list values that contain different type of values (int & string)
is there a use-case for that?

**Comment by phil-davis** [comment]
@individual-it this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by individual-it** [comment]
I cannot find that function anymore in the settings code, I guess this can be closed.
CC @kulmann 
Feel free to reopen if its still relevant
