### ISSUE TITLE
Write documentation for roles & permissions concept

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1456]
Write documentation for roles & permissions concept. This is intended to be a living document and it should reflect decisions made during the development process. The end result being a document in a state that mirrors the settings service functionality regarding roles and permissions.

**Comment by phil-davis** [comment]
@kulmann @refs this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.

**Comment by refs** [comment]
> @kulmann @refs this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
> Please close if no longer relevant.

This one is still relevant 👍
