### ISSUE TITLE
Roles & Permissions

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1457]
Things to do for roles & permissions:
- [x] Concept session
- [x] protobuf spec for roles and permissions (intertwined with settings bundles)
- [x] grpc services for... https://github.com/owncloud/product/issues/85
  - [x] registering roles and permissions (along with settings bundles)
  - [x] getting and setting roles of a user
- [ ] when getting settings bundles for a user, filter out settings that are available for the user

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.
