### ISSUE TITLE
Ideas for settings bundles / settings

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1458]
This issue is for collecting ideas for settings bundles and settings

### accounts services
- language
- timezone

### Phoenix / Files app
- default sort column (scopes `system` and `folder:fileid`)
- preferred quick actions (scopes `system` and `folder:fileid`)

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-settings` repo a few weeks ago.
Please close if no longer relevant.
