### ISSUE TITLE
make listening to localhost only the default

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#146]
We are hardcoding several services to localhost when running them via ocis, but not all. 

The question is what ocis is intended to provide: an easy developer deployment or a tool to start a production deployment? The former would mean locking things to localhost by hardcoding it in the services may be the better approach. The latter would lead to a more flexible solution which allows people to shoot themselves in the foot. We need to provide secure defaults either way.

IMO letting all services listen to localhost might be ok for a development setup ... and should be the default for all extensions. Then ocis does not need to hardcode the host and address in the subcommands like in https://github.com/owncloud/ocis/pull/145#pullrequestreview-375836587. And all services started via ocis can be configured va env vars, eg. to let the proxy listen for connections on all ip adresses.

@refs @micbar @PVince81 @C0rby @IljaN @felixboehm opinions? localhost by default? would that work for every service? leave a :+1: or :-1: more feedback welcome!

**Comment by C0rby** [comment]
I agree to defaulting to localhost but keeping it configurable

**Comment by labkode** [comment]
@butonic I would map it to 0.0.0.0 as many times localhost is not the pc you are working but your dev machine that you have ssh-ed into.

**Comment by butonic** [comment]
I was thinking about the compromise of letting every service listen to localhost and make the proxy listen on 0.0.0.0, but that setup is useless, because the oidc provider needs to know the issuer url. So in order to log into a remote machine you would *always* have to set an env variable to get the iss set up properly. Hm we could default to [the hostname](https://golang.org/pkg/os/#Hostname) instead of locahost for the oidc issuer. If that is set up properly it should *just work*:tm: 

When ssh-ing into another machine you can also port forward the proxy port and use ocis on localhost.

**Comment by butonic** [comment]
Related https://github.com/owncloud-docker/compose-playground/pull/9

**Comment by refs** [comment]
[this PR](https://github.com/owncloud/ocis/pull/132/files#diff-3dc44b8a3898c1e906ebb82f0ca8e9b4L37) addresses this. But only tangentially

**Comment by micbar** [comment]
The only scenario running without any specific config is `localhost`
