### ISSUE TITLE
Weird version semantics

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1462]
In other modules like ocis-settings, we are importing the so-called v2 of ocis-pkg as `github.com/owncloud/ocis-pkg/v2 v2.2.2-0.20200812103920-db41b5a3d14d` (when using go get with `@master`)

However the commit "db41b5a3d14d" is on master, and not on the "v2" branch.
And the "v2" branch seems much older than master.

Is this intended ? What is the purpose of the "v2" branch then ?
And where is the old v1 version then ?

@butonic @refs

**Comment by phil-davis** [comment]
@refs this is an old issue that was transferred from the archived `ocis-pkg` repo a few weeks ago.
Please close if no longer relevant.
