### ISSUE TITLE
Reva data model usage

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#1464]
In the proxy, we're minting the account uuid into the `x-access-token`:
https://github.com/owncloud/ocis-proxy/blob/ea254d6036592cf9469d757d1295e0c4309d1e63/pkg/middleware/account_uuid.go#L107
https://github.com/owncloud/ocis-proxy/blob/ea254d6036592cf9469d757d1295e0c4309d1e63/pkg/middleware/account_uuid.go#L120

We now have a middleware in ocis-pkg that dismantles the `x-access-token` from the request header, extracts the account uuid and puts it into the context. With that we're somewhat tying our data model to Reva internally. 
https://github.com/owncloud/ocis-pkg/blob/3242d532fda09ec6336e35b7fa09698752f34077/middleware/account.go#L49

This issue serves as a reminder, if we want to change this in the future.

**Comment by phil-davis** [comment]
@kulmann this is an old issue that was transferred from the archived `ocis-pkg` repo a few weeks ago.
Please close if no longer relevant.
