### ISSUE TITLE
Pre-generate thumbnails for a specific account

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1469]
Add CLI command to pre-generate multiple thumbnail sizes for all files of a given account.
Optionally add a "path" argument to limit the pre-generation to a given path.

@pmaier1

**Comment by phil-davis** [comment]
this is an old issue that was transferred from the archived `ocis-thumbnails` repo a few weeks ago.
@micbar or ? Is this still "a thing"?
Please close if no longer relevant.

**Comment by micbar** [comment]
@C0rby Still valid?

**Comment by C0rby** [comment]
This wasn't worked on and I think it depends on a product decision if we want to implement it.

**Comment by micbar** [comment]
Closing. If this feature is needed, it will be planned on the roadmap.
