### ISSUE TITLE
Rename oCIS' Proxy to ocis-proxy

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#147]
The way the oCIS command ties together all services, `proxy` is an existing go-micro service, and it must be renamed on our end.

**Comment by PVince81** [comment]
renamed where ? in code or in documentation ?

**Comment by refs** [comment]
My bad @PVince81, I didn't provide enough context.

Context: https://github.com/owncloud/ocis/blob/master/pkg/micro/runtime/runtime.go#L25

Micro has a service named Proxy. The current runtime implementation doesn't play well with 2 subcommands with the same name, and since we don't use `micro/proxy` it can be entirely removed from our runtime.

I recently opened a ticket describing possible [alternatives to the current runtime](https://github.com/owncloud/ocis/issues/231), but for the scope of this issue, any micro subcommand SHOULD be removed (and tested on the developer side that behaves the same way).

**Comment by PVince81** [comment]
So does it mean it's commented out in all our ocis-* services and we need to delete that line there ?

**Comment by refs** [comment]
exactly

**Comment by wkloucek** [comment]
@refs seems to be done? https://owncloud.github.io/extensions/proxy/configuration/#proxy-server

**Comment by refs** [comment]
thanks @wkloucek
