### ISSUE TITLE
 thumbnail service currently doesn't work with basic auth

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#1471]
When requesting the previews through port 9200 with etag in the request 
`curl -k https://172.17.0.1:9200/remote.php/dav/files/Alice/docker.png\?x\=32\&y\=32\&forceIcon\=0\&preview\=1\&c\=5475a8682a0a32e042bf7e2f68300303 -u Alice:1234 -v --output test1.png`
we are getting `HTTP/1.1 400 Bad Request` .

While checking `ocis-thumbnails` log we get an error `WRN Failed to execute error="{\"id\":\"com.owncloud.api.thumbnails\",\"code\":500,\"detail\":\"could not get username: could not parse auth token: square/go-jose: compact JWS format must have three parts\",\"status\":\"Internal Server Error\"}" duration=0.050836 method=Thumbnails.GetThumbnail service=thumbnails`

### Screenshots
![Screenshot from 2020-08-04 15-06-08](https://user-images.githubusercontent.com/17021686/89279191-cf3b4e00-d666-11ea-8eb6-19aefc248cfd.png)

**Comment by phil-davis** [comment]
this is an old issue that was transferred from the archived `ocis-thumbnails` repo a few weeks ago.
@individual-it @swoichha is this still relevant?

**Comment by C0rby** [comment]
When ocis is started with the option PROXY_ENABLE_BASIC_AUTH=true it should work.
