### ISSUE TITLE
run oC10 preview API tests in this repo and fix them

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1472]
- [x] resolutions cannot be set by occ command, but with `THUMBNAILS_RESOLUTIONS` env
 variable
- [x] previews cannot be accessed through port 9140 but only 9200
- [x] move issues that still exist from ocis-reva repo to this repo #2075

**Comment by phil-davis** [comment]
This is an old issue that was transferred from the archived `ocis-thumbnails` repo a few weeks ago.
@individual-it @swoichha is this a thing that still needs to de done "some day"?

**Comment by kiranparajuli589** [comment]
> * [x]  resolutions cannot be set by occ command, but with `THUMBNAILS_RESOLUTIONS` env
>   variable

separate issue created for preview dimensions settings at https://github.com/owncloud/ocis/issues/2070
