### ISSUE TITLE
Don't depend on the etag query parameter

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#1473]
Currently clients have to send the etag in the request but in OC10 it was not strictly required.
Change the implementation of the service to not depend on the etag.
`https://demo.owncloud.com/remote.php/dav/files/demo/meme1.jpg?c=d04ca18aff0316743074b68a9a13149c&x=32&y=32&forceIcon=0&preview=1`
`c=d04ca18aff0316743074b68a9a13149c` is the etag part.

**Comment by phil-davis** [comment]
@C0rby this is an old issue that was transferred from the archived `ocis-thumbnails` repo a few weeks ago.
Please close if no longer relevant.
