### ISSUE TITLE
Change current authentication method against the webdav api

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#1474]
Currently the service just resends the JWT token sent by the user. This can be seen as imersonisation, is a hacky solution and can bring problems[1].

My proposel is to use the OAuth2 Token Exchange flow[2].

[1] [Scott Brady Delegation Patterns](https://www.scottbrady91.com/OAuth/Delegation-Patterns-for-OAuth-20)
[2] [OAuth2 Token Exchange](https://www.rfc-editor.org/rfc/rfc8693)

**Comment by phil-davis** [comment]
@C0rby  this is an old issue that was transferred from the archived `ocis-thumbnails` repo a few weeks ago.
Please close if no longer relevant.

**Comment by C0rby** [comment]
Closing because the thumbnails service isn't supposed to do webdav requests in the future anyways.
