### ISSUE TITLE
Support the OC10 backend

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#1478]
After a recent change in https://github.com/owncloud/ocis-glauth/pull/19, the option to set OC10 as a backend was removed.
This breaks the bridge setup between oc10 and phoenix (https://owncloud.github.io/ocis/bridge/) where glauth is used.

For the bridge setup to work there needs to be a way for glauth to talk to the OC10 graphapi to get the users.

**Comment by phil-davis** [comment]
@dpakach this issue was transferred from the "old" `ocis-glauth` repo. Is it still "a thing"?
If not, then please close.

**Comment by kulmann** [comment]
The bridge setup is working properly. Closing here.
