### ISSUE TITLE
White login page 

### ISSUE THREAD

**Issue by Aruscha** [owncloud/ocis#1487]
Hello,

I have a problem with the software.
No matter on which device :
On a Pi
A VM
A LXC
In Docker
And installed on my laptop (LInux).

I always get only a white page when opening OwnCloud.
But there is nothing in the logs, they are clean.

Anyone have an idea what the problem is ?

**Comment by wkloucek** [comment]
How do you run oCIS? Please paste the commands here.

**Comment by Aruscha** [comment]
> How do you run oCIS? Please paste the commands here.

# download
curl https://download.owncloud.com/ocis/ocis/1.1.0/ocis-1.1.0-linux-amd64 --output ocis

# make binary executable
chmod +x ocis

# run
./ocis server


As it says in the manual

**Comment by wkloucek** [comment]
And then you go to https://localhost:9200 an only see a white page?

**Comment by Aruscha** [comment]
> And then you go to https://localhost:9200 an only see a white page?

Yes... Except when I take a beta version of 1.0. 0. Then comes the Webgui where login is

Only when I click on it nothing happens
In the developer tools of my browser you will see this:
OpenID-connection 
ERR_CONNECTION_REFUSE

**Comment by wkloucek** [comment]
Could you please provide logs of the `./ocis server` output?

**Comment by Aruscha** [comment]
> Could you please provide logs of the `./ocis server` output?

https://pastebin.com/y4R8Jt3a

 uploaded to pastebin.com 
I hope we find the error

**Comment by refs** [comment]
This I suspect is the same [as this issue](https://github.com/owncloud/ocis/issues/1354). I smell mDNS issues and would love for you to try `etcd` as service registry. We could continue the discussion offer at #1354 , and will close this one, as it is a duplicated.
