### ISSUE TITLE
The devdocs duplicate all cli end env vars

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#149]
The current getting-started.md of many extensions contains the list of available env vars and config flags. This is a maintenance burden.

We should move the configuration to a dedicated configuration.md which explains which config file is read, and which precedence env vars and cli flags have. We can also link to the bug in viper that prevents cli flags from being used properly with nested structs.

The getting-started.md should be used to describe how to get the extension up and running and how it can be tested. For ocis-glauth I would eg. add an ldapsearch query.

**Comment by micbar** [comment]
Work in progress https://github.com/owncloud/ocis/pull/173

**Comment by micbar** [comment]
Flagset extractor was introduced.

Needs to be propagated to all extensions.

https://github.com/owncloud/enterprise/issues/4019

Closed here.
