### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by erwinpalma** [owncloud/ocis#1538]
## Description

Create good documentation for System Administrators/Implementers. There are multiple types of documents, for instance: Guides, manuals, how-tos, etc, but they should have the same context.

## User stories

- As SysAdmin, I want to read an articule, where I can read an overview about what I am going to implement.
- As SysAdmin, I want to get a functional file example, where I base my installation.
- As SysAdmin, I want a well-structured index, which can I find the information quickly.
- As SysAdmin, I want a real-life use case, where I can understand what I am doing in an easy way 
- As SysAdmin, I want a Trobleshuting where can I find a solution if I get an error.
- As SysAdmin, I want an item "called best practices" where I can get more information about implementation.

## Acceptance Criteria

A readable guide with the use case.
A how-to focused to implementers/SysAdmins

## Additional context

I tried to follow the steps for some topics, but it was too complicated to follow them.

**Comment by erwinpalma** [comment]
@micbar, how can I help you to contribute to it?

Should I create a draft about the structure of the documents?

Erwin

**Comment by micbar** [comment]
@erwinpalma @mmattel this could be transferred to owncloud/docs

**Comment by dragotin** [comment]
I guess @mmattel and @EParzefall are aware and working :-D
