### ISSUE TITLE
A deleted folder `with & in it` does not appear in the trashbin 

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1547]
1. Create folder `with & in it` 
2. Delete it
3. List the trash in the web ui
4. `with & in it` is missing but should show up

**Comment by phil-davis** [comment]
QA test automation:
- [ ] review core API test coverage of trashbin scenarios with unusual file names ( `&` `#` `?` `%` `@` are the everyday causes of trouble)

**Comment by dpakach** [comment]
assigned @saw-jan for checking the existing tests

**Comment by saw-jan** [comment]
> QA test automation:
> 
> * [ ]  review core API test coverage of trashbin scenarios with unusual file names ( `&` `#` `?` `%` `@` are the everyday causes of trouble)

Cannot find API test coverage of trashbin scenarios with unusual file names.
I will be making a PR on it.
