### ISSUE TITLE
expected failures on EOS storage get out of date

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1549]
We did not manage to get the core API tests running in CI with EOS storage. That means that we do not get automated feedback abut which things are passing and failing with EOS storage. So the contents of https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-API-on-EOS-storage.md get out-of-date.

What should we do about that?

- try harder to get the tests running in CI with EOS storage
- get someone to locally run the tests "every so often" and adjust the expected-failures file
- something else?

**Comment by phil-davis** [comment]
@dpakach can you add some comments about what was difficult when trying to run EOS in CI.

**Comment by butonic** [comment]
There is also work on a Cephfs storage driver. One by @thmour one by @aduffeck Something the keep in mind...

**Comment by individual-it** [comment]
issues in CI see https://github.com/owncloud/ocis/issues/586 & https://github.com/owncloud/product/issues/156
but currently we are even failing to run EOS locally or on hetzner servers see https://github.com/owncloud/ocis/issues/541#issuecomment-766819314

**Comment by refs** [comment]
How important is this? Bringing @micbar to the party. It sounds relevant enough to pull it into the backlog.

**Comment by micbar** [comment]
@refs @phil-davis at the moment, this is not possible.

**Comment by phil-davis** [comment]
When someone wants to know how well EOS storage is working, we could get another someone to run the core API tests locally against an EOS storage setup. And they could update the expected-failures. It just depends on how often to put in the effort of this.

**Comment by butonic** [comment]
eos tests are no longer covered by ocis ci. it should run in reva or elsewhere.
