### ISSUE TITLE
Dav request with multiple slashes `//` gives http 301 Moved Permanentaly

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#1595]
## Describe the bug

Making a DAV request on WebDAV endpoint with multiple slashes after remote.php gives HTTP 301 Moved Permanently. The response contains a `Location` header with the correct endpoint without multiple slashes. Some clients will redirect to that endpoint with GET request. So making DELETE request with multiple slashes end up being GET request.
eg.
```
curl -XDELETE https://localhost:9200//remote.php/dav/files/admin/FOLDER -u admin:admin -vk 
```

## Steps to reproduce
```
curl -XDELETE https://localhost:9200//remote.php/dav/files/admin/FOLDER -u admin:admin -vk 
```
## Expected behavior
Handle the request ignoring the multiple shashes 
OR
Handle by redirect with the correct request method 
Maybe use [HTTP 308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308)

## Actual behavior
As the response gives 301 moved with correct url in Location header, some clients will redirect with GET.
```
curl -XDELETE https://localhost:9200//remote.php/dav/files/admin/FOLDER -u admin:admin -vk  
*   Trying 127.0.0.1:9200...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=Acme Corp; CN=OCIS
*  start date: Jan  4 14:03:57 2021 GMT
*  expire date: Jan  4 14:03:57 2022 GMT
*  issuer: O=Acme Corp; CN=OCIS
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user 'admin'
> DELETE //remote.php/dav/files/admin//FOLDER HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Date: Thu, 04 Feb 2021 10:25:15 GMT
< Location: /remote.php/dav/files/admin/FOLDER
< 
* Connection #0 to host localhost left intact
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by ScharfViktor** [comment]
1. Create folder `curl -vk -u admin:admin -X MKCOL https://localhost:9200/remote.php/dav/files/admin/folderQWE`
2. Delete folder using double slashes `curl -X DELETE https://localhost:9200//remote.php/dav/files/admin/folderQWE -u admin:admin -vk`

request with double slashes give me 404 "Not Found"

![image](https://user-images.githubusercontent.com/84779829/132332511-c600e0dd-f4bc-41ab-b2c8-3890e34c9629.png)


 
@dpakach still relevant?

**Comment by dpakach** [comment]
@ScharfViktor thanks, seems to have been fixed.
