### ISSUE TITLE
Add TUS checksumming tests

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1599]
TUS and OC upload checksums were implemented in https://github.com/cs3org/reva/pull/1400
The TUS `checksum` extension is described in https://tus.io/protocols/resumable-upload.html#checksum with a clarification on what happens when a PATCH request is disconnected in https://github.com/tus/tus-resumable-upload-protocol/issues/143#issuecomment-497933853 (the server must discard all received bytes for that PATCH request and the client needs to restart the chunk)

This is part of https://github.com/owncloud/ocis/issues/1279

**Comment by swoichha** [comment]
Blocked due to https://github.com/owncloud/ocis/issues/1747

**Comment by swoichha** [comment]
# Acceptance tests to be added:
- [ ] for issue https://github.com/owncloud/ocis/issues/1747
- [ ] for chunking (correct / wrong / partly wrong)
- [ ] for sharing (upload as shares / receiver, check both sides)

**Comment by swoichha** [comment]
All required tests for TUS checksum have been added so closing this issue for now.
