### ISSUE TITLE
Health seems to be in bad state, after run the server

### ISSUE THREAD

**Issue by erwinpalma** [owncloud/ocis#1601]
## Describe the bug

Following the documentation, I ran the command `./ocis health --help` and I get the output.
<details>
<p>

```
./ocis health --help

NAME:
   ocis health - Check health status

USAGE:
   ocis health [command options] [arguments...]

OPTIONS:
   --debug-addr value  Address to debug endpoint (default: "0.0.0.0:9010") [$OCIS_DEBUG_ADDR]
   --help              Show the help (default: false)
```

 </p>
</details>

So I decided to use the argument `--debug-addr`, and here are my findings:

### Error 1

The documentation says **Address to debug endpoint (default: "0.0.0.0:9010")** but when I run the suggested command I get the error **connection refused**

```
--debug-addr 0.0.0.0:9010
{"level":"fatal","service":"ocis","error":"Get \"http://0.0.0.0:9010/healthz\": dial tcp 0.0.0.0:9010: connect: connection refused","time":"2021-02-05T12:31:09.697578+01:00","message":"Failed to request health check"}
```
### Error 2

So, due to the ocis server only runs in localhost using the listening port 9200 I adapted the parameter to use those values, getting the message **Health seems to be in bad state**. here are all the combinations that I use:

```console
./ocis health --debug-addr 127.0.0.1:9200
{"level":"fatal","service":"ocis","code":400,"time":"2021-02-05T13:29:24.436104+01:00","message":"Health seems to be in bad state"}

./ocis health --debug-addr localhost:9200
{"level":"fatal","service":"ocis","code":400,"time":"2021-02-05T13:29:31.142776+01:00","message":"Health seems to be in bad state"}

./ocis health --debug-addr 0.0.0.0:9200
{"level":"fatal","service":"ocis","code":400,"time":"2021-02-05T13:29:37.047044+01:00","message":"Health seems to be in bad state"}
```
so, what does it mean the error if the server is running?

## Steps to reproduce

1. run `./ocis server`
2. run ./ocis health --debug-addr 0.0.0.0:9200

## Expected behavior
A clear and concise description of what happens and how to handed it .

## Actual behavior

Un clear error message

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
VERSION:
   1.1.0-rc1
```

</p>
</details>

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
still relevant

**Comment by butonic** [comment]
Some backgroud for implementation: Kubernetes restarts pods when their health endpoint reports an error. To prevent kubernetes from killing all the services a health implementation must never check depending services. It can check if it can write something to a tmp file or if environment variables are set. A sanity check of the configuration. But that's it.

See #3508 for a reference implementation

**Comment by micbar** [comment]
The health subcommand has been removed.

We have public endpoints on all services.


## Example

```sh
curl http://localhost:9205/healthz

OK
```
