### ISSUE TITLE
Example configuration files JSON and YAML are empty 

### ISSUE THREAD

**Issue by erwinpalma** [owncloud/ocis#1602]
## Is your feature request related to a problem? Please describe

The documentation https://owncloud.github.io/ocis/configuration/#configuration-using-config-files says _if you want to get a full example configuration just take a look at our repository [...]_ but if you open the example file it is emty.

Files affected: example.json and example.yml

![image](https://user-images.githubusercontent.com/30660343/107034832-9025bb00-67b7-11eb-8917-2aa2af898a85.png)

![image](https://user-images.githubusercontent.com/30660343/107034860-9a47b980-67b7-11eb-92d2-d1b1e768a604.png)

## Describe the solution you'd like

A functional example file in both formats

**Comment by refs** [comment]
Closing as duplicated of #1745
