### ISSUE TITLE
Enable OCIS to log to a file

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis#1619]
As per other software (nginx, apache, ...) and to make OCIS deployment more dev/admin friendly, 
OCIS should have an option to log to a file. 

Zerolog allows for that as we are using in in Reva so it comes out of the box.

## Acceptance criteria
- config option in oCIS that will configure log output for all services, defaults to stdout
- config option in individual services to override the global option
- ~~unit test for config option (don't test the logger :-P)~~

**Comment by butonic** [comment]
I don't think we should implement logging to a file. logging to stdout/stderr is already handled out of the box by docker and systemd.

When starting it as a systemd unit stdout logging is already taken care of, see http://0pointer.de/blog/projects/journalctl.html
> [...] the journal is a component of systemd, that captures Syslog messages, Kernel log messages, initial RAM disk and early boot messages as well as messages written to STDOUT/STDERR of all services, indexes them and makes this available to the user. It can be used in parallel, or in place of a traditional syslog daemon, such as rsyslog or syslog-ng. [...]

The official docker containers for nginx and apache even redirect their logfiles to stdout to let docker capture them, see https://docs.docker.com/config/containers/logging/

Logfiles seem to be a step back, don't they?

**Comment by labkode** [comment]
Let me explain you the workflow we have for logs:

Our daemons create log files that are stored in the local filesystem for a period of time (3 months).
A fluentd agent tails the logs file and ships them to a centralized sink for post-processing and ultimately to ES/InfluxDB.

By having OCIS not having the possibility to write to a file when technically is possible, means that we need to configure another dependency (rsyslog or systemd) to accomplish that.  Less external dependencies the better, etcd is also another one part of the picture.

I thought to the goal was to run OCIS of the box, but this is currently not possible as many core functionalities are delegated to external services.

**Comment by wkloucek** [comment]
Related discussion on Talk https://talk.owncloud.com/channel/infinitescale?msg=EXpyWL3vhPvi8uP8P
