### ISSUE TITLE
ocis should use an internal account id as the reva opaque id

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#163]
see https://github.com/owncloud/ocis-reva/pull/113/files#diff-057efc5475447324ae0c6ac35d58c281R9
and https://github.com/owncloud/ocis-reva/pull/113/files#diff-5f64a5d53cecdcaa009d9eec6930f6adR102-R109

**Comment by IljaN** [comment]
I propose: https://github.com/google/uuid

**Comment by labkode** [comment]
@IljaN yes, we should change the uuid package to the one used by Google

**Comment by refs** [comment]
> @IljaN yes, we should change the uuid package to the one used by Google

done: https://github.com/cs3org/reva/blob/f2b63bfd6825e52dba6cbbd478a8ec57317e0892/go.mod#L28
