### ISSUE TITLE
Version cannot be restored when file has been renamed

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1635]
## Steps to reproduce
https://drone.cernbox.cern.ch/cs3org/reva/567/18/7
```
  Scenario: the version history is preserved when a file is renamed                              # /drone/src/tmp/testrunner/tests/acceptance/features/apiVersions/fileVersions.feature:399
    Given user "Alice" has uploaded file with content "old content" to "/textfile.txt"           # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "new content" to "/textfile.txt"             # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has moved file "/textfile.txt" to "/renamedfile.txt"                        # FeatureContext::userHasMovedFile()
    When user "Alice" restores version index "1" of file "/renamedfile.txt" using the WebDAV API # FilesVersionsContext::userRestoresVersionIndexOfFile()
      FilesVersionsContext::listVersionFolder Received empty response where XML was expected (Exception)
    Then the HTTP status code should be "201"                                                    # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the content of file "/renamedfile.txt" for user "Alice" should be "old content"          # FeatureContext::contentOfFileForUserShouldBe()
```

## Expected behavior
On oC10 this scenario passes - I can rename a file then still restore an old version.

## Actual behavior
The same scenario does not work on OCIS.
ToDo: investigate and provide more detail...

## Setup
CI

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0:
It's strange that the test passes

1. upload file.txt
2. create new version of the file (another size)
3. rename file to "newFile.txt"
4. restore old version (size didn't change).
5. go back to main menu (size didn't change). 
6. reload page (returns the old file name and size). Bad- we get errors

Expected result: name of the file is "newFile.txt", size as a first version

Actual result: name of the file "file.txt". size as a first version. can't find file
`GET https://localhost:9200/remote.php/dav/files/marie/file.txt?a=1&c=c852218b7215cce9939b34aa270b80d1&preview=1&scalingup=0&x=36&y=36` 

return 404 Not Found
`<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception>Sabre\DAV\Exception\NotFound</s:exception><s:message>File with name file.txt could not be located</s:message></d:error>`

video:

https://user-images.githubusercontent.com/84779829/132354942-eaaf6316-87db-49d7-9f20-81b3bdc1ae33.mov

**Comment by ScharfViktor** [comment]
tested on`ocis 6.0.0 `
works fine
