### ISSUE TITLE
Unable to find environment-variables

### ISSUE THREAD

**Issue by mabushey** [owncloud/ocis#1640]
https://owncloud.github.io/ocis/configuration/#environment-variables :
`If you prefer to configure the service with environment variables you can see the available variables below.`

Nope, I can't see them. Where would I find this list?

**Comment by IljaN** [comment]
The env vars are noted after the cli arg separated by the pipe.
```
-log-pretty | $OCIS_LOG_PRETTY
Enable pretty logging. Default: false.
```
In the example above OCIS_LOG_PRETTY is the env-var.

**Comment by mabushey** [comment]
Huh? I have no clue what you mean. I'm asking where the [missing] list/table of env vars is located.

**Comment by wkloucek** [comment]
You can find the env vars in the respective extension configuration section eg. https://owncloud.github.io/extensions/proxy/configuration/

**Comment by mabushey** [comment]
Are you trolling me? I report that that link is missing the entire env var table, and you link me back to it?

**Comment by mabushey** [comment]
I'm just going to close this out. I'll stick to Nextcloud. I wish you guys the best, you need it.

**Comment by wkloucek** [comment]
> Are you trolling me? I report that that link is missing the entire env var table, and you link me back to it?

We are not trolling you. The env var tables are spread across the different extensions. Therefore you only have a few env vars on the main command / your given link. As my colleague tried to explain that the env vars are one section below your linked section:
![image](https://user-images.githubusercontent.com/34452982/108468976-ccf9b380-7287-11eb-9455-6015abfc2beb.png)


The other env vars are available on the respective extension configuration page: lhttps://owncloud.github.io/extensions/_______extension-name_______/configuration/ eg. https://owncloud.github.io/extensions/proxy/configuration/

**Comment by mabushey** [comment]
I'm not looking to output logs. What would posses you pipe logs into [the location of] some variable? Is this some Windows convention? I'm perfectly OK with letting docker/kubernetes handle the logs. I would like to use the stock entry point.

**Comment by mabushey** [comment]
That's not a bash fragment other than the --option, is it? Can you guys please change the docs to replace the pipe (|) with an or (||) or better yet, use a syntax like:
`CLI: --option   ENV: $ENV_VAR`
