### ISSUE TITLE
not working behind nginx

### ISSUE THREAD

**Issue by cscholz** [owncloud/ocis#1644]
## Steps to reproduce

1. configure nginx es reverse proxy
2. start oc server

## Expected behavior
Login page should be loaded

## Actual behavior
blank page. Site title show "Owncloud" also with favicon

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

**/etc/nginx/sites-enabled/https_oc.domain.tld.conf**
`server {
        listen          80;
        listen          443 ssl http2;
        server_name     oc.domain.tld;
        access_log      /var/log/nginx/oc.domain.tld-access.log;
        error_log       /var/log/nginx/oc.domain.tld-error.log;

        ssl_certificate         /etc/nginx/ssl/domain.tld_fullchain.pem;
        ssl_certificate_key     /etc/nginx/ssl/domain.tld.key;

        # OSCP stapling
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/ssl/domain.tld_fullchain.pem;

        client_max_body_size    40M;

        if ($scheme != "https") {
            rewrite ^ https://$host$uri permanent;
        }

    location / {
       proxy_pass                               https://127.0.0.1:9200;
       proxy_set_header Host                    $http_host;
       proxy_set_header X-Real-IP               $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto       $scheme;
    }`

**Starting oc as**
`OCIS_URL=https://oc.domain.tld PROXY_HTTP_ADDR=0.0.0.0:9200 ocis server`

</p>
</details>

**Comment by IljaN** [comment]
Is there any movement in the ocis logs during the request? Thanks for reporting!

**Comment by cscholz** [comment]
**Start command**
`OCIS_URL=https://oc.cscholz.io PROXY_HTTP_ADDR=0.0.0.0:9200 OCIS_LOG_LEVEL=debug ocis server`

**Log output**

- 2021-02-14T15:28:41+01:00 DBG  bytes=920 duration=7.297783 method=GET path=/ proto=HTTP/1.1 request=ad60c6a5-f9ee-4ece-9110-0388743cf853 service=web status=200
- 2021-02-14T15:28:41+01:00 DBG  bytes=86483 duration=0.359506 method=GET path=/node_modules/requirejs/require.js proto=HTTP/1.1 request=7ae31ca1-4c73-49b8-b9ba-f620f0ae54c5 service=web status=200
- 2021-02-14T15:28:41+01:00 DBG  bytes=411811 duration=0.991695 method=GET path=/css/core.css proto=HTTP/1.1 request=4d3e0493-1c18-45e1-b674-99f9e1547626 service=web status=200
- 2021-02-14T15:28:41+01:00 DBG  bytes=2162556 duration=3.686376 method=GET path=/core/core.bundle.js proto=HTTP/1.1 request=2b615bf1-a8be-4c0e-99c9-4f95beb607fb service=web status=200
- 2021-02-14T15:28:42+01:00 DBG  bytes=435 duration=0.282233 method=GET path=/config.json proto=HTTP/1.1 request=bab76a92-a773-4f38-a779-936cf9504c53 service=web status=200
- 2021-02-14T15:28:42+01:00 DBG  bytes=19 duration=0.06714 method=GET path=/favicon.ico proto=HTTP/1.1 request=ede9ffb7-95cd-4b44-afeb-83fd6c6fdc87 service=web status=404
- 2021-02-14T15:28:42+01:00 DBG  bytes=274 duration=0.134282 method=GET path=/manifest.json proto=HTTP/1.1 request=7f163f0c-707c-4b69-9bc1-74de8fbf5fb6 service=web status=200
- 2021-02-14T15:28:42+01:00 DBG  bytes=923035 duration=1.72753 method=GET path=/apps/files/files.bundle.js proto=HTTP/1.1 request=fd5bc4fc-d4cc-4d12-b1df-9dcbcc1d370f service=web status=200
- 2021-02-14T15:28:42+01:00 DBG  bytes=19 duration=0.068191 method=GET path=/img/app.png proto=HTTP/1.1 request=9f296473-8987-4b78-9ffb-2b9f511bd12f service=web status=404
- 2021-02-14T15:28:42+01:00 DBG  bytes=130929 duration=0.388828 method=GET path=/apps/media-viewer/media-viewer.bundle.js proto=HTTP/1.1 request=48ab7a25-1b48-48f8-922c-9528b0bdef94 service=web status=200
- 2021-02-14T15:28:42+01:00 DBG director found path=/settings.js policy=reva prefix=/settings.js routeType=prefix service=proxy
- 2021-02-14T15:28:42+01:00 INF access-log from=127.0.0.1:38360 method=GET path=/settings.js service=proxy
- 2021-02-14T15:28:42+01:00 DBG  bytes=109379 duration=10.027816 method=GET path=/settings.js proto=HTTP/1.1 request=b0883d1a-1362-4723-8844-3be3bd9c6c4a service=settings status=200
- 2021-02-14T15:28:42+01:00 DBG director found path=/accounts.js policy=reva prefix=/accounts.js routeType=prefix service=proxy
- 2021-02-14T15:28:42+01:00 INF access-log from=127.0.0.1:38364 method=GET path=/accounts.js service=proxy
- 2021-02-14T15:28:42+01:00 DBG  bytes=149637 duration=9.305634 method=GET path=/accounts.js proto=HTTP/1.1 request=660e8128-0526-4cfe-95ff-9e096b289797 service=accounts status=200
- 2021-02-14T15:28:42+01:00 DBG  bytes=495 duration=0.136091 method=GET path=/themes/owncloud.json proto=HTTP/1.1 request=a8187407-685c-43f9-a14b-a89df8baf37c service=web status=200
- 2021-02-14T15:28:42+01:00 DBG  bytes=615 duration=0.103099 method=GET path=/themes/owncloud/favicon.jpg proto=HTTP/1.1 request=9f7f7bda-6721-4f23-b001-934c556333fc service=web status=200

**Firefox network analyzer**
![image](https://user-images.githubusercontent.com/3398846/107879526-9a436a00-6ed9-11eb-8340-017336d9a28f.png)

OpenID Configuration connection tries to connect to localhost

**Comment by butonic** [comment]
@cscholz Please check your `config/identifier-registration.yaml` it may have been generated with `localhost` on the first run if it happend without the `OCIS_URL` env var set.

Whate does the `config.json` contain? It should point to the correct `https://oc.***/.well-known/openid-configuration/` endpoint. There is the [`WEB_OIDC_AUTHORITY`](https://github.com/owncloud/ocis/blob/master/web/pkg/flagset/flagset.go#L198) env var to set it. While it defaults to `https://localhost:9200` it should be set to `OCIS_URL`.

**Comment by cscholz** [comment]
> @cscholz Please check your `config/identifier-registration.yaml` it may have been generated with `localhost` on the first run if it happend without the `OCIS_URL` env var set.
> 
> Whate does the `config.json` contain? It should point to the correct `https://oc.***/.well-known/openid-configuration/` endpoint. There is the [`WEB_OIDC_AUTHORITY`](https://github.com/owncloud/ocis/blob/master/web/pkg/flagset/flagset.go#L198) env var to set it. While it defaults to `https://localhost:9200` it should be set to `OCIS_URL`.


Thank you. You are right. OCIS_URL was stored incorrectly in identifier-registration.yaml. I had expected that using the environment variable would override this value. It is also described that way in the documentation. So it is not a bug.

Suggestion: Using environment variables again should update the identifier-registration.yaml.
