### ISSUE TITLE
Unify dependencies

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis#1653]
As of today, the core OCIS has multiple go modules inside and they all share very much the same dependencies.
For example, to bump Reva version one needs to change many mods:

```
ocis-pkg/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
onlyoffice/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
settings/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
store/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
thumbnails/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
web/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
webdav/go.sum:github.com/cs3org/reva v1.5.1/go.mod h1:abC1Lo0ZKwkKloomTPZWunV/lUJvewkty1pI41zn2Ic=
```

Perhaps for core service, a single go.mod makes more sense

**Comment by labkode** [comment]
Raising this again. The developer experience to test changes in ocis dependencies (reva for example) is extremely complex. 
OCIS will benefit from having a single go.mod file to its core product (github.com/owncloud/ocis). 
@dragotin @micbar

**Comment by ishank011** [comment]
Closed by https://github.com/owncloud/ocis/pull/2344
