### ISSUE TITLE
first request with a recreated user returns a 401 error

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1675]
## Describe the bug

when a user is deleted and recreated the first request with that user returns a `401` error, all next requests succeed 

## Steps to reproduce

1. start ocis with `PROXY_ENABLE_BASIC_AUTH=true bin/ocis server`
2. create user `curl -k -X POST https://localhost:9200/ocs/v2.php/cloud/users -d userid="jasmine" -d email="jasmine@example.com" -d username="jasmine" -d password="1234" -u admin:admin`
3. use the new user, e.g. send a `PROPFIND`: `curl -k -X PROPFIND https://localhost:9200/remote.php/webdav -u jasmine:1234 -v`
4. delete the user: `curl -k -X DELETE https://localhost:9200/ocs/v2.php/cloud/users/jasmine -u admin:admin`
5. create it again: `curl -k -X POST https://localhost:9200/ocs/v2.php/cloud/users -d userid="jasmine" -d email="jasmine@example.com" -d username="jasmine" -d password="1234" -u admin:admin`
6. use the new user, e.g. send a `PROPFIND`: `curl -k -X PROPFIND https://localhost:9200/remote.php/webdav -u jasmine:1234 -v` => Response is `HTTP/1.1 401 Unauthorized`
7. use the user again: `curl -k -X PROPFIND https://localhost:9200/remote.php/webdav -u jasmine:1234 -v` => Response is as expected `HTTP/1.1 207 Multi-Status`

## Expected behavior
the first request after user creation should be already successful 

## Actual behavior
the first request always fails with `HTTP 401`

## Setup
<details>
<p>

```console
BRANCH=master
PROXY_ENABLE_BASIC_AUTH=true
```

</p>
</details>

## Additional context
this seems not to be a timing issue but always the first requests fails, also when using other endpoints

**Comment by butonic** [comment]
needs to be reevaluated after spaces are used to create and delete user homes (`personal` spaces)

**Comment by saw-jan** [comment]
re-tested `oCIS 1.19.1`. The issue no longer occurs.
Everything works as expected.

TODO:
- [ ] check `owncloud-sdk` tests

**Comment by saw-jan** [comment]
Task completed! Closing here
