### ISSUE TITLE
Shift responsibility from reporting settings bundle to the Settings service instead of accounts

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1685]
Service initialization should be stateless. Services should not depend on others when booting up, and currently the Accounts service does.

**Comment by butonic** [comment]
We plan to replace the accounts service with a combination of [libregraph idm](https://github.com/libregraph/idm) and the cs3 userprovider. the accounts service will be removed as a consequence.

- [ ] initializing the roles should move from the accounts service to the setting service
- [ ] the proxy can be hard coded to use the cs3 userprovider, drop the `PROXY_ACCOUNT_BACKEND_TYPE`
- [ ] move the file based index from the accounts service to a lib
- [ ] (optional) use da lib in  [libregraph idm](https://github.com/libregraph/idm)? to provide a file only backend .. .or just use https://github.com/tidwall/buntdb
- [ ] get rid of accounts service

**Comment by micbar** [comment]
We fixed this in `2.0.0-beta1`
