### ISSUE TITLE
How to communicate with reva from ocis?

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#169]
The default micro-grpc client expects that all services are available via service-discovery. As ocis-reva is not fully integrated in to micro (no service discovery) hard-coded addresses need to be used:

- [x] Generate micro-protoc client from reva-gateway
- [ ] Try with hard-coded address

Ideally we should integrate ocis-reva in to micro`s mdns.

Or use bare-bones google-grpc-client? Is it conceptually  possible to use a generated protoc-micro client with a non-micro server?

@refs @butonic

**Comment by refs** [comment]
> Is it conceptually possible to use a generated `protoc-micro` client with a non-micro server?

No. Method signatures are completely different. You could however write a small compatibility layer between micro / google-grpc-client, but I haven't explored that approach 🤔 

We should definitely add reva services to the registry, but that's the tricky part, and where glue code / compatibility layer comes in.

Another approach would be implementing Reva Gateway as a micro/micro service and registering only this service, wrapping calls to reva services on a micro/micro method signature.

**Comment by IljaN** [comment]
Problem I see is that we have limited access to the reva-internals. From a quick look we basically run cli-commands in our wrapper: https://github.com/owncloud/ocis-reva/blob/master/pkg/command/gateway.go.

Maybe we need to further "librarify" reva.

**Comment by refs** [comment]
Extending Reva to run as a micro/micro is worth exploring. As in "run alongside a micro service mesh", It would need to know which registry is in use of course.

**Comment by IljaN** [comment]
For now we register the reva-endpoint in the go-micro service registry without bootstrapping reva as a a full service.

See: https://github.com/owncloud/ocis-reva/pull/131
