### ISSUE TITLE
oCIS can only be used with one IDP

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#1694]
## Is your feature request related to a problem? Please describe.
You can use oCIS with only one IDP at a time because it eg. must be configured in `STORAGE_LDAP_IDP` for user lookups by claim when sharing a folder.

## Describe the solution you'd like
oCIS can have users managed by multiple IDPs. Therefore user accounts must be linked to an IDP like shares are already linked.

## Additional context

Reva always uses the IDP url from `STORAGE_LDAP_IDP` for user lookups by claim:
https://github.com/cs3org/reva/blob/e861f8d76ccc87d4e47d2d2d1c2fc4c8381db185/pkg/user/manager/ldap/ldap.go#L171-L174

Comparison of the `STORAGE_LDAP_IDP` and the IDP from the user session:
https://github.com/cs3org/reva/blob/e861f8d76ccc87d4e47d2d2d1c2fc4c8381db185/pkg/share/manager/json/json.go#L389

**Comment by wkloucek** [comment]
@rhafer this is also related to user management in the auto provisioning case.

**Comment by jvillafanez** [comment]
I'm not an expert in the topic, but what about using an identity broker (https://www.keycloak.org/docs/latest/server_admin/#_identity_broker)?

In theory, if I understood right, ownCloud would connect to the identity broker provided by keycloak (in this particular case), and it would be keycloak's responsibility to connect to other idps

```
owncloud -> keycloak broker -> kopano
                            -> google
                            -> ....
```

**Comment by wkloucek** [comment]
> I'm not an expert in the topic, but what about using an identity broker (https://www.keycloak.org/docs/latest/server_admin/#_identity_broker)?

that should be already possible :+1:

**Comment by wkloucek** [comment]
Closing here since I honestly believe this is out of scope. As pointed out in https://github.com/owncloud/ocis/issues/1694#issuecomment-913546081, brokering is the way to go right now.
