### ISSUE TITLE
CLI-Tools concept

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#170]
As the need for the first cli-tool (user-import) arises we need a rough concept:
 - Admin-tool / Utilities are shipped within the single-binary i.e ```ocis tool import-user``` or ```ocis i mport-user```

- Need to be shipped stand-alone in case ocis runs in single-service mode?
    - Always use ocis on the client-side for administrative tasks?
     - Need away to send messages to an already running ocis-instance
     -  Authentication? I like the reva-concept where every cli-command is authenticated.

**Comment by butonic** [comment]
related https://github.com/owncloud/ocis/pull/93#issuecomment-578196068

I vote for a dedicated `ocis-cli` repo, similar to other extensions. The cli works standtalone and in ocis we can import the cli commands from `ocis-cli`.
