### ISSUE TITLE
Trying to share already shared file/folder to same user/group doesn't have meaningful/clear response

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#1710]
## Steps to reproduce
1. share a file to user or group
```bash
curl -u admin:admin -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares \
-d path="parent.txt" -d "shareType"=1 -d shareWith="g101"
```
2. again try to share same file with same user or group
```bash
curl -u admin:admin -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares \
-d path="parent.txt" -d "shareType"=1 -d shareWith="g101"
```

## Expected behavior
response similar to oC10
```xml
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>failure</status>
    <statuscode>403</statuscode>
    <message>Path already shared with this group</message>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data/>
</ocs>
```

## Actual behavior
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>996</statuscode>
    <message>grpc create share request failed</message>
  </meta>
</ocs>
```

## Setup
oCIS built from the latest master

**Comment by saw-jan** [comment]
ToDo QA-team:
- [ ]  add an API test for this

**Comment by saw-jan** [comment]
re-tested oCIS latest master (`55269c23d`) still relevant

**Comment by micbar** [comment]
OCS is deprecated.

**Comment by micbar** [comment]
@saw-jan @ScharfViktor 
We should remove all OCS related tests from the expected failures please.

**Comment by saw-jan** [comment]
>We should remove all OCS related tests from the expected failures please.

And without the failing test scenarios as well?

**Comment by micbar** [comment]
Yes please.

**Comment by saw-jan** [comment]
I have opened a separate ticket to remove the ocs related tests from the expected-failure list.
https://github.com/owncloud/ocis/issues/9324

So maybe we can close this one here.

**Comment by ScharfViktor** [comment]
> So maybe we can close this one here.

let close issue during the deleting from expected-failure list and rewriting new with Sharing NG (if needed)

**Comment by grgprarup** [comment]
The test for sharing NG is added in the PR https://github.com/owncloud/ocis/pull/8181 . The removal of failing test will be done in PR https://github.com/owncloud/ocis/pull/9421/.
