### ISSUE TITLE
Can't login to oCIS

### ISSUE THREAD

**Issue by m0nhawk** [owncloud/ocis#1736]
## Describe the bug

Clean installation with Traefik, based on the docker-compose from [here](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_traefik).

## Steps to reproduce

1. Try to login with any default account (`admin`/`admin` for example).

## Expected behavior
Successful login.

## Actual behavior
1. Redirected to https://.../#/access-denied
2. "Login Error You are not allowed to use this application."
<details>
<img width="496" alt="Screen Shot 2021-01-23 at 1 38 20 AM" src="https://user-images.githubusercontent.com/8220926/105572265-b8271000-5d1b-11eb-992c-4bd71705c044.png">
</details>

## Setup

Dedicated server with Traefik and oCIS based on [this](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_traefik) with few changes to environmental variables. Running `latest (sha256:a48685626a)`. Domain is replaced with `...`.

<details>
<p>
```console
      - KONNECTD_IDENTIFIER_REGISTRATION_CONF=/config/identifier-registration.yaml
      - OCIS_URL=https://...
      - OCIS_DOMAIN=...
      - OCIS_LOG_LEVEL=${OCIS_LOG_LEVEL:-debug}
      - OCIS_LOG_PRETTY=true
      - IDP_LDAP_BIND_PASSWORD=password
      - STORAGE_LDAP_BIND_PASSWORD=password
      - OCIS_JWT_SECRET=password
```
</p>
</details>

## Additional context
From Traefik I see the following:
```
reverse-proxy     | 1.2.3.4 - - [27/Feb/2021:05:33:52 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/2.0" 500 0 "-" "-" 2793 "ocis@docker" "https://172.18.0.15:9200" 10000ms
```

From oCIS logs:
```
ocis              | 2021-02-27T05:34:02Z ERR could not initialize oidcAuth provider error="Get \"https://.../.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" service=proxy
```

I'm not sure how to proceed.

**Comment by IljaN** [comment]
Try opening https://$YOUR_DOMAIN/.well-known/openid-configuration. It looks like this url is not reachable. Is the ocis container able to resolve the domain?  

Unrelated: Please note that the docker tag latest is the current master branch so you might want to use a [release-tag](https://hub.docker.com/layers/owncloud/ocis/1.2/images/sha256-7d7497a8a1b3daf14d87a9c779c35bcfe2a5ce4d9e84043c6ffa3de2ea4bc92b?context=explore) instead. But this is probably unrelated to your issue as we continuously test the traefik example.

**Comment by m0nhawk** [comment]
>Is the ocis container able to resolve the domain?
This was the catch, I was already checking `/.well-known/openid-configuration` endpoint, and it was working correctly. But, from container it was not resolving correctly.

After some investigation, I found out that I have some strange firewall rules which were preventing communicating to host from the Docker container.

Now it works!
