### ISSUE TITLE
Generate the Documentation for file based configuration

### ISSUE THREAD

**Issue by lquenti** [owncloud/ocis#1745]
## First things first, I'd love to do it myself 
I would just need some small initial help, further described below.

## Is your feature request related to a problem? Please describe.
I'm currently struggeling to set up the JSON/YAML configuration based setup, listed as a possibility [here](https://owncloud.github.io/ocis/configuration/#configuration-using-config-files). 

It references to [`ocis/ocis/config/example.{json,yml}` on `master`](https://github.com/owncloud/ocis/tree/master/ocis/config), but there are only empty files. 

## Describe the solution you'd like

I have found multiple ways to solve it while investigating:

### 1. Write the file and update it manually

This seems to be a non optimal solution, as it is easy to forget updating it. But it is very simple and would greatly benefit the documentation readability until something better is implemented.

### 2. Generate the documentation through the [flaex](https://github.com/owncloud/flaex). 

This seems to also be not an optimal solution, as flaex is made to generate independent files for each extension, not combining it in one big json/yml. 

I haven't looked much into flaex and I don't know where it is all used beside the `Makefile`s in the repository, so I don't know what it would break, if anything. But it seems so... dirty.

### 3. Extract small parsable information through flaex, use a small script (or new go tool) to put it together

This seems like a good solution, because it leverages flaex and therefore the script would create next to none code duplication.

I just don't know whether this would violate the idea behind flaex, but it seems to work with the definition provided by it's [`README.md`](https://github.com/owncloud/flaex/)

> Extract flags from the ocis project-components to create documentation.

Your opinion? And what do you prefer, a small script or a small go tool?

### 4. Generate it with the Flagsets though an entirely new tool

I think this solution just makes sense if the third one violates how flaex is intended to be used, as it would be a lot of more work to maintain 2 tools with similar usage.

## Additional context

I haven't found the config file structure that is expected by ocis. If someone could give me a small example for both languages here, I think I could implement the rest myself, which I am more than happy to do! 

And if the solution is to write another go tool, what is the best way to do it? Just writing it as a repo owned by me, using an apache 2 license and then transfer it to the owncloud github orga? I sadly don't have much experience with big open source projects :(

**Comment by refs** [comment]
Hi @lquenti! Thanks for opening a ticket. This is something we're currently working on, so I fear that documenting it would be a moving target and it will quickly be outdated.

Good entry points to wrap your head around how configuration using a big ol' file works is having a look at a set of PR's that got merged this Monday [1](https://github.com/owncloud/ocis/pull/1762) and [2](https://github.com/owncloud/ocis/pull/1815). #1762 deals with an entire new runtime moving away from os threads, and we managed to squeeze configuring this runtime using a unified config file; in regards to #1815, the command aggregator is now aware of this higher level config file as an environment variable and a CLI flag.

There is more context you would need to have that is also brought up [here](https://github.com/owncloud/ocis/pull/675) as it is also relevant to document which config takes precedence.

As I mentioned, this is a moving target and there are known issues. For instance, `storages` config keys are mapped to a go-syntax representation of the type, minus the package name. You can see it as what the `%#v` verb prints for any given type. This implies that this config is valid:

```yaml
proxy:
  http:
    addr: "0.0.0.0:6200"
accounts:
  http:
    addr: "0.0.0.0:8888"
Storage:
  Reva:
    StorageMetadata:
      Port:
        HTTPAddr: "0.0.0.0:7777"
```

Where as this renders invalid:

```yaml
proxy:
  http:
    addr: "0.0.0.0:6200"
accounts:
  http:
    addr: "0.0.0.0:8888"
storage:
  reva:
    storage_metadata:
      port:
        http_addr: "0.0.0.0:7777"
```

I'd love to jump in a zoom call and explain you further, if you have the time :)
