### ISSUE TITLE
convert simple TAG into a command

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#177]
Currently, we are using a `simple` build tag to start a subset of the services in the extensions documentation. To reduce the magic developers need to understand we want to convert this into a dedicated `ocis simple` command.

It will start the same subset of services.

Furthermore, if developers went to implement an extension that needs to interact with the storage layer they can use the `server` command.

**Comment by micbar** [comment]
Decision: Kill the `simple` tag

**Comment by refs** [comment]
simple tag is dead 💀
