### ISSUE TITLE
Different ocs status-text and status-code in oCIS and oC10 using ocs api v1

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#1777]
## Describe the bug
OCIS returns different status and statuscode for some requests:
- add/remove user to non-existing group
- add/remove non-existing user to a group
- get/edit/delete non-existing user
- edit not allowed user attribute
- get non-existing user's groups 

### In oCIS
```bash
curl -X POST -u admin:admin https://localhost:9200/ocs/v1.php/cloud/users/demo/groups -d groupid="non-existing"
```
```xml
<ocs>
  <meta>
    <status>error</status>
    <statuscode>998</statuscode>
    <message>The requested group could not be found</message>
  </meta>
</ocs>
```
### In oC10
```bash
curl -X POST -u admin:admin http://localhost/core/ocs/v1.php/cloud/users/demo/groups -d groupid="non-existing"
```
```xml
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>failure</status>
    <statuscode>102</statuscode>
    <message/>
  </meta>
  <data/>
</ocs>
```

## Expected behavior
oC10 and oCIS ocs response to be identical

**Comment by saw-jan** [comment]
similar issue https://github.com/owncloud/ocis/issues/521

**Comment by saw-jan** [comment]
ToDo QA-team: 
- [ ]  adjust owncloud-sdk tests related to this issue

**Comment by saw-jan** [comment]
similar https://github.com/owncloud/ocis/issues/1777

**Comment by phil-davis** [comment]
@saw-jan is this still an issue?

I don't see it mentioned in any OCIS expected-failures files.

**Comment by phil-davis** [comment]
@saw-jan is this still an issue?

**Comment by saw-jan** [comment]
Yeah, I can confirm it.
This issue is mentioned in `owncloud-sdk`'s tests

**Comment by saw-jan** [comment]
re-tested oCIS latest master (`55269c23d`) and `oC 10.9.2 prealpha (git)` still relevant

**Comment by micbar** [comment]
We will not invest more effort into OCS, because that API is deprecated.
