### ISSUE TITLE
the runtime always initializes all services

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#178]
https://github.com/owncloud/ocis/pull/116/files#diff-688ef0465a76180b75455f7a3661829fR72 started to add all default extensions when creating a runtime with `New()`.

Noticed while cleaning up https://github.com/owncloud/ocis/pull/176.

Related https://github.com/owncloud/ocis/issues/77, https://github.com/owncloud/ocis/issues/177

**Comment by micbar** [comment]
needs concept work.

**Comment by micbar** [comment]
@refs Can you update the ticket regarding the new runtime?

**Comment by refs** [comment]
@micbar absolutely. It is only a recollection of my thoughts, it needs to be worked on, as the work in progress is not really entirely functional. [Here is the ticket](https://github.com/owncloud/ocis/issues/231)

**Comment by refs** [comment]
closing since the new runtime got merged
