### ISSUE TITLE
Improve discoverability of oCIS demo users

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#1782]
## Is your feature request related to a problem? Please describe.
Just tried to figure out which example users I can use when running oCIS locally. The link on https://owncloud.github.io/clients/web/backend-ocis/ (`when signing in, use one of the available test users`) is broken, and a short discussion with @butonic revealed it's not as easily discoverable as we would like it to be.

## Describe the solution you'd like
- Fix the broken link mentioned above
- Create an overview for the (local) demo users that is easily discoverable using the search functionality on owncloud.github.io

## Describe alternatives you've considered
Digging through the `ocis` repo of course eventually yields the same results, but isn't as user friendly.

**Comment by wkloucek** [comment]
The link works for me:
![image](https://user-images.githubusercontent.com/34452982/114352038-aa8b6480-9b6b-11eb-8e6a-d602961556a5.png)

I will try to make it more prominent / accessible today.

**Comment by wkloucek** [comment]
@pascalwengerter @butonic What do you think about this approach?
I added an extra site below getting started and present the demo users in a table (#1907)
![image](https://user-images.githubusercontent.com/34452982/114430318-9b81d200-9bbe-11eb-9082-8565f0ea3f15.png)

**Comment by pascalwengerter** [comment]
Love it!

**Comment by wkloucek** [comment]
Fixed by #1907
