### ISSUE TITLE
Fix package name for proto files

### ISSUE THREAD

**Issue by ishank011** [owncloud/ocis#1826]
Can't upgrade protobuf to v1.26.0 since proto files across the repo have the same `go_package` name (https://github.com/owncloud/ocis/blob/master/accounts/pkg/proto/v0/accounts.proto#L3, https://github.com/owncloud/ocis/blob/master/settings/pkg/proto/v0/settings.proto#L4)

Refer https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

**Comment by wkloucek** [comment]
@ishank011 would #1875 fix your problem? ;-)

**Comment by ishank011** [comment]
@wkloucek looks good, thanks!
