### ISSUE TITLE
Different handling of duplicate accounts

### ISSUE THREAD

**Issue by axstet** [owncloud/ocis#1828]
Duplicate accounts are handled differently on `ocis add` and `ocis update` using official 1.3.0 preview.
On an environment with the test users try:

```
ocis accounts add --enabled --displayname Test --username test --mail moss@example.org --password test
> could not create account {"id":"com.owncloud.api.accounts","code":409,"detail":"account already exists","status":"Conflict"}
```

```
ocis accounts add --enabled --displayname Test --username test --mail fake@example.org --password test
ocis accounts update --mail moss@example.org <new-account-id>
```

First example throws error, second example works fine resulting in two users having same mail address.

**Comment by wkloucek** [comment]
we removed the accounts service, therefore no longer an issue
