### ISSUE TITLE
ARMv6 image cannot find some 64-bit symbols

### ISSUE THREAD

**Issue by oliva** [owncloud/ocis#1839]
## Describe the bug
The linux/arm/v6 image variant references some symbols that do not exist on that platform

## Steps to reproduce

1. Use a machine with armv6 or armv7 platform
2. Run the image

## Expected behavior
The oCIS main process starts

## Actual behavior
The process fails, not finding some 64-bit symbols related to time

## Setup
Run the container on an armv7 machine (eg. Raspberry Pi 1-3, ODROID-XU4)

<details>
Tested not working on versions 1.1, 1.2, 1.3 and latest
<p>

```console
$ uname -m
armv7l

$ docker run --rm -it --net host docker.io/owncloud/ocis:1.3.0
Error relocating /usr/bin/ocis: __nanosleep_time64: symbol not found
Error relocating /usr/bin/ocis: __dlsym_time64: symbol not found
Error relocating /usr/bin/ocis: __gettimeofday_time64: symbol not found
Error relocating /usr/bin/ocis: __utimes_time64: symbol not found
Error relocating /usr/bin/ocis: __localtime64: symbol not found
Error relocating /usr/bin/ocis: __time64: symbol not found
Error relocating /usr/bin/ocis: __stat_time64: symbol not found
Error relocating /usr/bin/ocis: __fstat_time64: symbol not found
Error relocating /usr/bin/ocis: __lstat_time64: symbol not found
```

</p>
</details>

## Additional context
Some research suggests that updating the base OS to Alpine 3.13 (currently 3.12.4) might mitigate this issue
https://stackoverflow.com/questions/66253493

**Comment by wkloucek** [comment]
Thanks for the bug report. I will do an upgrade of the base image later and let you know when it is ready :-)

**Comment by oliva** [comment]
Thanks, I can verify that on recent images the issue is fixed.
