### ISSUE TITLE
docker-arm "generate go" step fails in CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1840]
See demo in PR #1838 

https://drone.owncloud.com/owncloud/ocis/4264/77/3

In docker-arm "generate go" step it fails with `make: bash: Operation not permitted`

The same CI fail as is happening in other PRs like #1833

**Comment by phil-davis** [comment]
That uses `webhippie/golang:1.15` 
https://hub.docker.com/r/webhippie/golang says that the docker images were updated 17 hours ago. I guess that the problem will be there somewhere.

**Comment by wkloucek** [comment]
I will look into it :-/
