### ISSUE TITLE
Previews via webDAV API tests fails on OCIS

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#187]
# Steps to reproduce
- Create an user and upload an image
- User downloads the preview of image file with width "32" and height "32" 
e.g. `curl http://172.17.0.1:9140/remote.php/dav/files/admin/testavatar.jpg\?x\=32\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v --output test.jpg`

# Expected
-  Preview of width "32" and height "32" should be downloaded

# Actual
- Preview of width and height same as the uploaded image is downloaded

#
 
While running the webDAV API test on OCIS it fails and gives output
 ``` 
width not as expected
Failed asserting that 1240 matches expected '32'.
```

"1240" is the width of the uploaded file

**Comment by C0rby** [comment]
The previews currently only work if the requests go through the proxy (port 9200) or if the ocis-webdav service is called directly  (port 9115, but it only serves thumbnails for now the rest is still in ocis-reva)

**Comment by PVince81** [comment]
is this because of authentication ?

so need to adjust the tests to use 9200, probably as part of https://github.com/owncloud/phoenix/issues/3601 @dpakach

**Comment by C0rby** [comment]
No this is because currently the webdav code is seperated.
Most of it is in reva but the code related to thumbnails is in ocis-webdav.
The proxy is redirecting the requests to the correct services.

**Comment by PVince81** [comment]
so what would be the next step to resolve this ?

**Comment by C0rby** [comment]
Either this

> so need to adjust the tests to use 9200, probably as part of owncloud/phoenix#3601

Or change the port of the preview tests to 9115.

**Comment by individual-it** [comment]
blocked by https://github.com/owncloud/ocis-thumbnails/issues/39

**Comment by refs** [comment]
@C0rby is this still the case? if not, feel free to close the issue.

**Comment by C0rby** [comment]
Technically this should work now. I just don't know if we need to change some configuration or so.
Needs to be checked.

**Comment by C0rby** [comment]
Some context:
Requests authenticated with basic auth have to go through the oCIS proxy. There the proxy mints a JWT and puts it into the request context. This way the tests should be able to execute the tests using basic auth.

**Comment by C0rby** [comment]
It works now when oCIS is started with `PROXY_ENABLE_BASIC_AUTH=true` and the requests are done against the proxy
