### ISSUE TITLE
ocis 1.3.0 binaries fail on different OCs

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/ocis#1879]
## Describe the bug

Ocis fails or login fails on different OCs following the instructions for binaries https://owncloud.dev/ocis/getting-started/
Its new installation, not migration from 1.2.0

## Steps to reproduce

1. `curl https://download.owncloud.com/ocis/ocis/1.3.0/ocis-1.3.0-linux-amd64 --output ocis` //different link for each OC from https://download.owncloud.com/ocis/ocis/1.3.0-rc1/2. `chmod +x ocis`
3. `./ocis server `(`ocis server` for Windows)

## Expected behavior
Ocis runs

### Ubuntu

* ocis runs

### CentOS 7

* ocis runs but login fails
* ocis runs with etcd:
```
sudo yum install etcd
systemctl start etcd
MICRO_REGISTRY=etcd ./ocis server
```
### MacOS Catalina (v. 10.15.7)

* ocis runs but login fails
* ocis runs but login fails with etcd

### Windows 10

* ocis fails

## Additional context
Logs on different OCs in attached pdf
[OCIS binaries on OCs.pdf](https://github.com/owncloud/ocis/files/6235380/OCIS.binaries.on.OCs.pdf)

**Comment by refs** [comment]
@elizavetaRa Hi! I wasn't able to reproduce it on macOS Big Sur 11.2.1, downloading the binary and login works 🤔

**Comment by elizavetaRa** [comment]
@pascalwengerter yes, this can be closed :)
