### ISSUE TITLE
Requesting a file preview with an invalid size results in HTTP code 200

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#188]
# Steps to reproduce

- User downloads the preview of file with invalid width/height `0` 
e.g. `curl http://172.17.0.1:9140/remote.php/dav/files/admin/lorem.txt\?x\=0\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v`

# Expected
-  HTTP code 400 - Bad Request

# Actual
- HTTP code 200 - OK

**Comment by refs** [comment]
@C0rby still the case?

**Comment by C0rby** [comment]
I don't know about that one. There is no validation for x > 0 and y > 0 IIRCT.
This needs to be checked.

**Comment by C0rby** [comment]
It's true that the service returns a 200.
I just compared the behavior of the oC10 thumbnails service and the oCIS thumbnails service.

In oC10 when I request a thumbnail with the dimensions x=1,y=32 then I get an image 1px wide and 32px heigh.
In oCIS  we currently take the larger of the two dimensions and recalculate the smaller dimension to match the original aspect ratio.

For that reason requesting x=0 is a valid option in the oCIS service. But maybe we need to clarify if this is even wanted.

**Comment by kiranparajuli589** [comment]
when preview of a file is requested with x/y = `0`, `0.5`, `-1`, `false`, `true`, `A`, `%2F`:
```
> GET /remote.php/dav/files/admin/lorem.txt?a=1&c=c158956012c358dc9906e9f750c6fc8b&preview=1&scalingup=0&x=32&y=0 HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> 

100   219  100   219    0     0   8760      0 --:--:-- --:--:-- --:--:--  8760
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Cannot set height of 0 or smaller!</s:message>
</d:error>
```
```
> GET /remote.php/dav/files/admin/lorem.txt?a=1&c=c158956012c358dc9906e9f750c6fc8b&preview=1&scalingup=0&x=0&y=32 HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> 

100   218  100   218    0     0   6812      0 --:--:-- --:--:-- --:--:--  6812
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Cannot set width of 0 or smaller!</s:message>
</d:error>
```

**Comment by C0rby** [comment]
Yes, the service was updated to reject the size `0`. It needs to be at least 1.

**Comment by phil-davis** [comment]
@swoichha I think that this issue has been fixed. There are no entries for it in expected-failures. The related `previews.feature` scenarios are passing on OCIS:
`Scenario Outline: download previews with invalid width`
`Scenario Outline: download previews with invalid height`

I think we can close this.

**Comment by ScharfViktor** [comment]
I checked. issue fixed. 
When you request a preview of a file with an invalid size, you get 400 with the message "Cannot set width of 0 or smaller!" that it matches the expected result.
I suggest to close. What do you say?

**Comment by phil-davis** [comment]
Agree - closing.
