### ISSUE TITLE
Drop or fully implement WEB_UI_CONFIG_THEME env variable

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#1899]
## Is your feature request related to a problem? Please describe.
Currently, oCIS offers a `WEB_UI_CONFIG_THEME` env variable that isn't used anywhere. Now that theming has landed in `web` and will be released into oCIS soon, we should figure out if we want to.
In `web`, the admin has the possiblity of providing a `theme.json` locally (for development) or via URL (for production usage). By using an env variable, he/she could reference a local file from within the current machine where oCIS gets started.

## Describe the solution you'd like
From my POV, there's two options:
- drop the `WEB_UI_CONFIG_THEME` variable in favor of loading themes via URL in the web's `config.json`
- implement the `WEB_UI_CONFIG_THEME` to be dynamically inserted in the web configuration **if it is set** by the admin, expecting that explicitly setting an env variable takes precedence over whatever is written in the config file already

## Additional context
Documentation on theming in web lives [here](https://owncloud.dev/clients/web/theming/).

**Comment by refs** [comment]
> implement the WEB_UI_CONFIG_THEME to be dynamically inserted in the web configuration if it is set by the admin, expecting that explicitly setting an env variable takes precedence over whatever is written in the config file already

I'd be in favor of this option, it sits nicely on top of the current config loading priorities 👍

**Comment by refs** [comment]
not staled, just needs to be scheduled 👍

**Comment by wkloucek** [comment]
should be done together with https://github.com/owncloud/ocis/issues/2523

**Comment by micbar** [comment]
Everything is working and [documented](https://owncloud.dev/services/web/). Closing.
