### ISSUE TITLE
Requesting a folder preview with results in HTTP error 501

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#190]
# Steps to reproduce
- User downloads the preview of folder with width "32" and height "32" 
e.g. `curl http://172.17.0.1:9140/remote.php/dav/files/admin/subfolder\?x\=32\&y\=32\&forceIcon\=0\&preview=1 -u admin:admin -v` 

# Expected
-  HTTP code 400 - Bad Request

# Actual
- HTTP code 501 - Not Implemented

**Comment by refs** [comment]
tested with: `curl -k https://localhost:9200/remote.php/dav/files/admin/docker\?x\=32\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v` got the expected result. Closing.
