### ISSUE TITLE
use git commit hash as a docker image tag

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1900]
that would make it easier to "cache" the ocis artifact in other repos that need it and that way don't need to rebuild it e.g. web
see https://github.com/owncloud/web/pull/4880#issuecomment-816429736 & https://github.com/owncloud/web/pull/4880#issuecomment-816443269

**Comment by wkloucek** [comment]
If we use this, we need to specify the oCIS commit SHA in the Starlark Drone definition in the Web repository. Currently this is done in another file which then behaves differently on PRs (merging does not happen for Drone definition). Is this a problem?

**Comment by wkloucek** [comment]
> If we use this, we need to specify the oCIS commit SHA in the Starlark Drone definition in the Web repository. Currently this is done in another file which then behaves differently on PRs (merging does not happen for Drone definition). Is this a problem?

@individual-it is this a blocking limitation for you?

**Comment by individual-it** [comment]
If I understand that correctly that would imply that in the test runs of web we would only to be able to use an ocis commit id from a commit of the master branch of ocis.
And the commit id would not be set in `.drone.env` but will be set in `.drone.star`

So to see if tests of a specific web feature branch run correctly with a specific feature branch in ocis we would have to set the the commitid and branch name in ocis: https://github.com/owncloud/ocis/blob/master/.drone.env

e.g. if you made a change to ocis that also require test changes in web
1. making branches in both repos with the changes
2. point both `.drone.env` to the corresponding branch on other side
3. merge web PR
4. point the web commit id in ocis to the new master commit id of web
5. merge ocis PR
6. point the ocis commit id in web to the new master commit id of ocis

1. making branches in both repos with the changes
2. point `.drone.env` in ocis to the corresponding branch in web
3. after tests on ocis side become green merge the PR
4. point the commit id of the ocis build in `.drone.star` to the newly build docker container of ocis
5. after tests in web become green merge the PR
6. point `.drone.env` in ocis again to master and the new commit id of web

the workflow would not be soo much different and not more complicated, the only downside I see is that the developers need to understand and remember that the web repo works differently with the commit ids than the ocis

@dpakach @phil-davis thought?

**Comment by individual-it** [comment]
as discussed with @wkloucek this seems to create more issues that solve, so closing this
