### ISSUE TITLE
Requesting a file preview of other user results in HTTP code 200 

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#191]
# Steps to reproduce
- User downloads the preview of of other user's file with width "32" and height "32" 
e.g. ` curl http://172.17.0.1:9140/remote.php/dav/files/user1/lorem.txt\?x\=32\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v
` 

# Expected
-  HTTP code 404 - Not Found

# Actual
- HTTP code 200 - OK

**Comment by dschmidt** [comment]
I assume this is a duplicate of this https://github.com/owncloud/ocis-thumbnails/issues/5

**Comment by swoichha** [comment]
@dschmidt You are right. I didn't know that this issue already exist.
