### ISSUE TITLE
Sharing is not successful for the renamed resources

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1943]
## Describe the bug

When a user shares a renamed file/folder with a user or group, the share is not completed. 

## Steps to reproduce

1. Create user `user1`
2. Login as user `admin` and create folder `originalFolder`
3. Rename folder `originalFolder` to `renamedFolder`
4. Share folder `renamedFolder` to user `user1`

## Expected behavior
The share should be created successfully with no error message displayed in the webUI

## Actual behavior
An error message is displayed in the UI as the screenshot below and the share is not created. When we get all the shares shared with user `user1`, the renamed file/folder share is not present. 
![Screenshot from 2021-04-21 10-21-30](https://user-images.githubusercontent.com/40829116/115498619-a3600700-a28d-11eb-9f48-e4cab24f0c04.png)

When we create the share as:
`curl -k -X POST https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/shares\?format\=json -d path="Duplicate" -d shareWith="user1" -d shareType="0" -u admin:admin -v;`
The response is: 

```
 HTTP/1.1 500 Internal Server Error
{"ocs":{"meta":{"status":"error","statuscode":996,"message":"grpc create share request failed"}}}% 
```

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
. 
there are such errors when we restore renamed file, but this case works correct
I suggest to close

**Comment by phil-davis** [comment]
@jasson99 please close if this is fixed.
