### ISSUE TITLE
Sharing indicator is different in oc10 and ocis

### ISSUE THREAD

**Issue by Talank** [owncloud/ocis#1948]
## Steps to reproduce

1.
2.
3.

## Actual behavior
A clear and concise description of what happened.

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by pascalwengerter** [comment]
Closed as duplicate in favor of more detailed #1949
