### ISSUE TITLE
sharing indicator is different in oc10 and ocis

### ISSUE THREAD

**Issue by Talank** [owncloud/ocis#1949]
## Describe the bug
Sharing indicator is shown differently in ocis and oc10 in items inside a re-shared folder.

## Steps to reproduce

```gherkin
- Given user "Alice" and user "Brian" has been added to group "grp1"
- And user "Alice" has created folder "simple-folder", and "simple-folder/simple-empty-folder" 
- And user "Alice" has created file "simple-folder/lorem.txt"
- And user "Alice" has shared folder "simple-folder" with user "Brian"
- And user "Brian" has accepted the share "simple-folder" offered by user "Alice"
- And user "Brian" has shared folder "Shares/simple-folder" with group "grp1"
- When user "Brian" has logged in using the webUI
- And the user opens folder "Shares" using the webUI
- Then the following resources should have share indicators on the webUI
      | fileName      | expectedIndicators |
      | simple-folder | user-direct        |
```

## Expected behavior
Both oc10 and ocis should have same sharing indicators

## Actual behavior
Sharing indicator in oc10 is `Directly shared with people`
Sharing indicator in ocis is `Shared with people through one of the parent folders`

## Screenshots
**in oc10**
![oc10](https://user-images.githubusercontent.com/27364813/115545008-05872f00-a2c3-11eb-9405-8c80eb7cd1d1.png)

**in ocis**
![in ocis](https://user-images.githubusercontent.com/27364813/115545093-1f287680-a2c3-11eb-8d80-80544a731208.png)

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0 and web 4.1.0 and docker oC10 version 10.8.0

Sharing indicator in ocis is 'Show invited people'

![image](https://user-images.githubusercontent.com/84779829/132490312-4f84e3c5-ac92-4715-824e-609d5e47d49f.png)


Sharing indicator in oc10 is 'Show invited people'

![image](https://user-images.githubusercontent.com/84779829/132490485-2d5f1804-9db2-4baf-8ee0-6879189a8987.png)
