### ISSUE TITLE
Error in accept and decline share using webUI

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1950]
## Describe the bug

When a pending share is tried to be accepted/declined using webUI, an error is shown. However, the share is accepted even with an error in the UI.

## Steps to reproduce

1. Create user `Alice` and `Brian`
2. As user `Alice`, share a new created folder `simple-folder` with user `Brian`
3. As user `Brian`, decline the pending share using the decline action button
4. As user `Brian`, accept the pending share using the accept action button

## Expected behavior
The share should be accepted/declined without any error in the webUI.

## Actual behavior
With the decline action, an error is shown in the webUI. And the share is still in pending state until the page is reloaded.
![Screenshot from 2021-04-21 16-52-39](https://user-images.githubusercontent.com/40829116/115544930-f1433200-a2c2-11eb-80c0-74ad74064081.png)

With the accept action, an error is shown in the webUI. However, the share is shown as accepted only after the page reload.

![Screenshot from 2021-04-21 16-52-56](https://user-images.githubusercontent.com/40829116/115544924-ee484180-a2c2-11eb-909e-412eb93c3fde.png)

![Screenshot from 2021-04-21 16-53-09](https://user-images.githubusercontent.com/40829116/115545234-4aab6100-a2c3-11eb-9b5a-d265922642b4.png)

**Comment by kulmann** [comment]
Related to https://github.com/owncloud/web/issues/4946

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0 and web 4.1.0
Works correct, @jasson99 please close

Decline action:

![Screenshot 2021-09-08 at 12 16 04](https://user-images.githubusercontent.com/84779829/132491724-0769fdf0-1177-49fc-83b5-3dfc47f06bdf.png)

Accept action after decline:

![Screenshot 2021-09-08 at 12 17 51](https://user-images.githubusercontent.com/84779829/132491996-cc5f9e38-7c60-46c1-95f5-fb40cc6609ad.png)
