### ISSUE TITLE
Prevent access to pending shares

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/ocis#1958]
## Is your feature request related to a problem? Please describe.
Related to https://github.com/owncloud/web/pull/4989. The statuses pending/accepted/declined don't makes sense if you can see/edit/download pending files. It causes that there is no difference between pending and accepted status and user is not motivated to execute an action.

## Describe the solution you'd like
Prevent access to pending files

## Describe alternatives you've considered
Show description of share (that would be another feature for sharing user: add description to the file by sharing)

**Comment by phil-davis** [comment]
This does not have an entry in expected-failures, which is surprising. There should be an API test that checks that the files/folders in a share are not accessible until the share has been accepted.

QA ToDo:
- [ ] add an API test scenario(s) for this in the core API test suite

Then we will also know if this problem happens in oC10 core, as well as in oCIS.

**Comment by kiranparajuli589** [comment]
I'll try add the API test scenario today!

**Comment by phil-davis** [comment]
We added tests to core with https://github.com/owncloud/core/pull/39635
Those will get run from oCIS when the core commit id is updated in the next few days. Then we should see some related test fails get added to oCIS expected-failures. Then this can be handed to devs to make it work.

Re-opening.
