### ISSUE TITLE
Default user seach minimum characters for autocompletion

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1961]
## Describe the bug

When we try to share a resource with a user, and type two characters of user name as in oc10-web, autocompletion is not performed. The default minimum characters for autocompletion seems to be 3 which is different to that of oc10-web.

## Steps to reproduce

1. Create user `user1`
2. As admin, try to share any created resource, say `lorem.txt` with user `user1`, typing `us` in the share-with field

## Expected behavior
User `user1` should have been listed in the autocompletion list

## Actual behavior
No user is listed. The intended user is listed only when at least 3 characters, such as `use` of the user's name are typed.

**Comment by SwikritiT** [comment]
@ScharfViktor after this issue I think this is configurable https://github.com/owncloud/ocis/pull/4229 
https://github.com/owncloud/ocis/blob/f7c89d1b427a56a24839a81045ab03f3b8c788b6/.drone.star#L1678

I think can be closed?

**Comment by ScharfViktor** [comment]
I agree. I tried change value to "2" here: https://github.com/owncloud/ocis/blob/master/services/frontend/pkg/config/defaults/defaultconfig.go#L42
It works
