### ISSUE TITLE
Mediaviewer is not working on public link view

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ocis#1965]
## Describe the bug

The action `Open in Mediaviewer` does not work properly.

## Steps to reproduce

1. Share a image file public
2. Open the link
3. Select the action `Open in Mediaviewer` 

## Expected behavior
The image will be shown in Mediaviewer

## Actual behavior
![image](https://user-images.githubusercontent.com/33026403/115926510-4037c580-a483-11eb-82f7-8e3565133a50.png)

## Setup

Tested with ocis.owncloud.works

## Additional context
I would love to provide you the information which version is running on ocis.owncloud.works, but there is no version string shown in the UI.

**Comment by ScharfViktor** [comment]
It still relevant. Found during release v1.15.0 testing
server log:
`2021-11-22T14:08:41+01:00 WRN Failed to execute error="{\"id\":\"com.owncloud.api.thumbnails\",\"code\":500,\"detail\":\"could not get image from source: could not get the image \\\"https://127.0.0.1:9200/remote.php/dav/public-files/OjmCGmxcENopiVi/fileForUpload.png/fileForUpload.png\\\". Request returned with statuscode 403 \",\"status\":\"Internal Server Error\"}" duration=49.259541 method=Thumbnails.GetThumbnail service=thumbnails
2021-11-22T14:08:41+01:00 ERR could not get thumbnail error="{\"id\":\"com.owncloud.api.thumbnails\",\"code\":500,\"detail\":\"could not get image from source: could not get the image \\\"https://127.0.0.1:9200/remote.php/dav/public-files/OjmCGmxcENopiVi/fileForUpload.png/fileForUpload.png\\\". Request returned with statuscode 403 \",\"status\":\"Internal Server Error\"}" service=webdav`

**Comment by wkloucek** [comment]
I retested with oCIS 1.16.0-rc1 and at it works for me.
