### ISSUE TITLE
App Passwords / Tokens for legacy WebDAV clients

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#197]
After removing support for Basic Auth (see https://github.com/owncloud/ocis/issues/196), legacy WebDAV clients would need App Passwords / Tokens to connect, similar to the feature in oC10:
https://doc.owncloud.org/server/user_manual/personal_settings/security.html#app-passwords-tokens

**Comment by refs** [comment]
see https://github.com/owncloud/ocis/issues/196#issuecomment-748197877

**Comment by michaelstingl** [comment]
> see [#196 (comment)](https://github.com/owncloud/ocis/issues/196#issuecomment-748197877)

I don't get it? Basic auth will be disabled in prod environment? Can't use 3rd party WebDAV clients with with prod oCIS?

**Comment by refs** [comment]
@michaelstingl my bad, had a fast finger on the trigger.

AFAIK basic auth is intended only for testing, so work on getting basic auth production-ready needs to happen to also account for app passwords / tokens.

**Comment by michaelstingl** [comment]
To clarify (similar to oC 10 implementation), real account credentials should not work with basic auth, but users can create additional credentials that allow basic auth with 3rd party WebDAV clients. Perfect would be, if those additional credentials can only be used for file operations, and don't grant access to user or admin settings.

**Comment by refs** [comment]
thanks for the input @michaelstingl ! I'm unfamiliar with the feature, but it looks like this needs a concept for an implementation in OCIS. Will bring it up when I finish this grooming round with the team.

**Comment by michaelstingl** [comment]
closed accidentally?

**Comment by micbar** [comment]
yes, closed accindentally?

**Comment by wkloucek** [comment]
Rclone supports OIDC -> see our docs here: https://owncloud.dev/clients/rclone/webdav-sync-oidc/

**Comment by dragotin** [comment]
Closing this as now handled in #7711
