### ISSUE TITLE
Human readable error message when trying to share the "Shares" folder

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#1974]
## Is your feature request related to a problem? Please describe.
By mistake I just tried sharing my "Shares" folder with another user (say: Admin tried sharing his "Shares" with Einstein). The corresponding error message was a rather obscure one and will perhaps confuse a non-technical user:

<img width="967" alt="Screenshot 2021-04-27 at 15 23 20" src="https://user-images.githubusercontent.com/16822008/116258322-c185a580-a76c-11eb-8105-8dd6995650d3.png">

## Describe the solution you'd like
A clear, human-readable and from a non-technical user perspective understandable error message on why the action I just took failed - something along the lines of `Sorry, you can't share your "Shares" folder with another user`. Bonus points for `i18n`.

## Describe alternatives you've considered
Handling this from inside the `web` repo is possible, but then each client (mobile, desktop, ...) needs to implement it themselves.

## Additional context
Perhaps needs some further discussion and sketching regarding share types, spaces, access rights etc

**Comment by phil-davis** [comment]
@pascalwengerter can you check that this is still an issue?

**Comment by pascalwengerter** [comment]
@phil-davis Fixed now, thanks for taking care 🙌🏽
