### ISSUE TITLE
Option to disable validation certificate hostnames without SNI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#198]
For client testing, I need to test with an IP that can accessed from my local network, and for debugging, I need to run `mitmproxy`.

This is my setup:
```
git clone https://github.com/owncloud-docker/compose-playground.git

cd compose-playground/ocis

sed -i -e 's/your-url/192.168.103.195/g' config/identifier-registration.yml

cat << EOF > .env
OCIS_BASE_URL=192.168.103.195
OCIS_HTTP_PORT=9200
OCIS_DOCKER_TAG=latest
EOF

docker-compose -f ocis.yml -f ../cache/redis-ocis.yml up
```

Sadly, I get ugly errors. It's easy to reproduce if I `curl` through `mitmproxy`:
```
% curl -x 192.168.103.195:8080 -k https://192.168.103.195:9200/status.php
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>TlsProtocolException(&quot;Cannot establish TLS with 192.168.103.195:9200 (sni: None): TlsException(&#x27;Cannot validate certificate hostname without SNI&#x27;)&quot;)</p>
            </body>
        </html>%    
```

`docker-compose` log isn't very useful:
```
ocis_1   | 2020-04-08 23:29:01.489013 I | http: TLS handshake error from 172.24.0.1:42202: EOF
```

**Comment by refs** [comment]
related? https://github.com/mitmproxy/mitmproxy/issues/1846#issuecomment-266416869

**Comment by C0rby** [comment]
> related? [mitmproxy/mitmproxy#1846 (comment)](https://github.com/mitmproxy/mitmproxy/issues/1846#issuecomment-266416869)

Yes, @refs is right. Starting mitmproxy with -k should solve the issue.
The problem is that mitmproxy can't verify the certificates because of the missing SNI but even if it would be there it couldn't verify the certificates because they are self signed.

**Comment by IljaN** [comment]
@michaelstingl You could look in to using https://github.com/FiloSottile/mkcert this will allow you to easily create a self-trusted cert which is trusted on your machine.

**Comment by michaelstingl** [comment]
should work for me. thanks!
