### ISSUE TITLE
Sync when sharing to 100k users

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#20]
Let me describe how reva and CS3 are going to handle the following corner case:

# The scenario

```
Feature: Sharing to 100k users

  Background:
    Given there is a group "everyone" with 100k users
    And "Alice" shared "/Projects/X/docs/" with the group "everyone"
    And each user in "everyone" has accepted the "docs" share and mounted it to a random subfolder
    And each user in "everyone" has started a desktop client

  Scenario: change discovery
    When "Alice" changes "/Projects/X/docs/readme.md"
    Then each client will get a changed etag in the PROPFIND /, Depth 0 Response and start the discovery

  Scenario: change notification
    When "Alice" changes "/Projects/X/docs/readme.md"
    Then each client will receive a push notification that his mounted file changed
```

# The problem

The moment Alice shares this to a group with 100k users 100k new mount points are created and 100k storages need to propagate the etag. In oc10 we do that by collecting all affected nodes in the filecache and their parents up to the root and then update them all at once. which causes a hotspot for the root nodes of storages that are affected by a lot of changes. That is more likely to happen by the number of incoming shares a user has mounted. It literally causes locking issues in the database.

# The solution

In reva we limit the etag propagation to the storage provider in which it occured. There is a storage registry which knows where a user has mounted a share. Actually the moint point is persisted by the storage provider and a ListCollectionResponse will contain the mount point as a resource with type [RESOURCE_TYPE_REFERENCE](https://cs3org.github.io/cs3apis/#cs3.storageproviderv0alpha.ResourceType). The StorageRegistry is just a cache for the mount points so subsequent discovery can be done without having to traverse the whole tree.
The reva gateway can always calculate the etag of the / of a users home by querying the etags of all storages the user has access to and picking the youngest etag. This is cached to eliminate subsequent queries when nothing has changed.
When a file changes reva decides when to change the etag of every users discovery PROPFIND to / that has access. We don't just invalidate the etag because that would mean 100k clients trying to do a discovery at once. reva needs to be able to control when the clients will get notified of a change. Eventual sync is what users expect here.

# Technical options

## distributed etag propagation
We could store the etag in the storage provider and do a cross storage etag propagation by propagating the change up to all mounting storages. however that would require linking all receiving storages to the shared storage, which leads to a child knowing about its parents.

It also reproduces the original problem but instead of the database the storage provider now has to deal with the hotspot of a frequenly changing home etag.

## active etag tree caching
We could use the gateway to cache the etag for every node from the root of a users home to every mount point. The sync discovery can always calculate the etag for a node in the tree by determining the responsible storage based on the mount points (that can be retrieved from the storage providers and are cached by the storage registry). The result of walking the mount tree and calculating the etag for the "virtual" nodes can be cached: when the first propfind causes the calculation of all these nodes the discovery can use the cache in the subsequent sync. Only the root node of the users homes will remain cached because that is what clients keep polling.

It avoids the hotspot by keeping the frequently changing nodes in a cache while at the same time giving reva the control over when to invalidate the cache. Instead of just using a TTL a background process can actively fill and overwrite the cache of virtual nodes to throttle the sync activity by thousands of clients to a manageable load.

# Future considerations

## push based sync
All of the above is the backbone of the state based sync that is currently used by the ownCloud client. With the new architecture implementing a notification or push based sync becomes more interesting because we can build it into the revad service.

We can either use the notifications endpoint or introduce long polling to the files dav endpoint. In either case we can return a response to the client when the cached etag of the root node is changed.

## delta based sync
When a client goes offline a lot of changes might happen before he comes back online. The fallback mechanism will always be a state based sync that relies on the etag. However, using the notifications endpoint we can retrieve all notifications (including file changes) since the last request (usually tracked with a token). Using this token we can keep track of where a client is in the history of changes, omit the discovery and directly sync the changed files.

This requires keeping track of changes (which should be a separate activity service that just caches changes) as well as the current position of clients in that history. In oc10 the activity app uses a sub optimal way of storing changes and is truncated only after 356 days. There is a lot of room for improvement and we can limit the activity history cache to 30 days by default. (it should be possible to reconstruct older changes at least partly based on the versions in a storage) In case a client comes along whose token is older than the known history we tell him to go use the state based sync.

**Comment by butonic** [comment]
This needs to become an ADR

**Comment by fschade** [comment]
Please open again if the ticket is still relevant

**Comment by micbar** [comment]
Too late for an ADR 😇
