### ISSUE TITLE
Requesting a text file preview 

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#200]
# Steps to reproduce
- Create an user and upload an text file
- User downloads the preview of text file with width "32" and height "32" 
e.g. `curl http://172.17.0.1:9140/remote.php/dav/files/admin/lorem.txt\?x\=32\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v --output test.jpg`

# Expected
-  Preview of width "32" and height "32" should be downloaded

# Actual
- Preview of size 0 bytes is downloaded

**Comment by individual-it** [comment]
issues might be that we are using the wrong port https://github.com/owncloud/ocis-thumbnails/issues/29 & that the previews require, but should not the etag https://github.com/owncloud/ocis-thumbnails/issues/28

**Comment by swoichha** [comment]
Currently thumbnail service doesn't work with basic auth. So, we cannot get preview using `9200` and using `9140` gives the actual file instead of `preview` as the thumbnail service and the rest of the webdav service are still separated in two services and until they are merge we can't access the thumbnail service under the port `9140`. See https://github.com/owncloud/ocis-thumbnails/issues/39
