### ISSUE TITLE
Speed up the process of updating dependencies in go.mod

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#201]
- [x] agree to a process we want to use to update dependencies
  - changelog should be more than just 'updated ocis-xyz to v1.2.3'
~- [ ] investigate how much this can be automated~

**Comment by micbar** [comment]
@IljaN Subject for the next sprint.

**Comment by refs** [comment]
We currently replace all dependencies and version only the end product (ocis). This issue will be relevant in the future when we start versioning dependencies, such as accounts (owncloud/ocis/accounts) and so on...

**Comment by micbar** [comment]
still needed

**Comment by micbar** [comment]
Process from #2342  and https://github.com/owncloud/ocis/blob/8a645f6ac67de87e2cbbcf9441cbeed8583950c1/changelog/unreleased/update-reva-v1.11.0.md is good. Always include the changelog from reva and web.
