### ISSUE TITLE
Loads of cookies + same-site cookie warnings in oCIS

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#2012]
## Describe the bug

A lot of cookie warnings in the console when using oCIS + new web frontend.

## Steps to reproduce

1. Run oCIS on master with the new web frontend
2. Use Firefox
3. Check the console and see the following:

<img width="1426" alt="Screenshot 2021-05-04 at 16 18 48" src="https://user-images.githubusercontent.com/16822008/117027225-69aee780-acf4-11eb-800c-f9778362ea5d.png">

## Expected behavior
No warnings & error messages.

## Actual behavior
A lot of warnings.

**Comment by pascalwengerter** [comment]
@fschade and @refs could you have a look into this? Not sure where it's coming from (Reva?) and how to fix it

**Comment by wkloucek** [comment]
I added a PR to set SameSite settings to strict. This should be ok to us since all communication happens on a single domain.
