### ISSUE TITLE
Deleting newly created user doesn't work if the user has not done any requests

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#2027]
## Steps to reproduce
1. create a new user 
```bash
curl -X POST -u admin:admin https://localhost:9200/ocs/v1.php/cloud/users \
-d userid="user101" -d email="test@mail.com" -d password="1234" -v
```
2. try to delete user
```bash
curl -X DELETE -u admin:admin https://localhost:9200/ocs/v1.php/cloud/users/user101 -v
```
**[status is `200` with  empty response body but user has not been deleted]**

3. get user
```bash
curl -X GET -u admin:admin https://localhost:9200/ocs/v1.php/cloud/users/user101 -v
```
User can be found:

> ```xml
> <?xml version="1.0" encoding="UTF-8"?>
> <ocs>
>   <meta>
>     <status>ok</status>
>     <statuscode>100</statuscode>
>     <message>OK</message>
>   </meta>
>   <data>
>     <enabled>true</enabled>
>     <id>user101</id>
>     <display-name>user101</display-name>
>     <displayname>user101</displayname>
>     <email>test@mail.com</email>
>     <quota>
>       <free>2840756224000</free>
>       <used>5059416668</used>
>       <total>2845815640668</total>
>       <relative>0.18</relative>
>       <definition>default</definition>
>     </quota>
>     <uidnumber>20032</uidnumber>
>     <gidnumber>30000</gidnumber>
>   </data>
> </ocs>
> ```

4. Now make any request with that user (*first request will be `401` as in https://github.com/owncloud/ocis/issues/1675
So try second time*)
```bash
curl -u user101:1234 -X MKCOL https://localhost:9200/remote.php/webdav/FOLDER -v
```
5. Delete user as in `step 2`
**Now the response will be `200` with some `XML` body**

> ```xml
> <ocs>
>   <meta>
>     <status>ok</status>
>     <statuscode>100</statuscode>
>     <message>OK</message>
>   </meta>
>   <data></data>
> </ocs>
> ```

## Expected behavior
User can be deleted

## Actual behavior
User deletion doesn't work

## Setup
<details>
<p>

```console
OCIS_VERSION=ec5bdada
BRANCH=master
```

</p>
</details>

**Comment by saw-jan** [comment]
TODO:
- [ ] adjust the code block added in PR https://github.com/owncloud/owncloud-sdk/pull/835

https://github.com/owncloud/owncloud-sdk/blob/d9e21ce454035ed9dc3423ffc640c6d76a29f1b0/tests/providerTest.js#L209-L213

**Comment by individual-it** [comment]
Good catch :+1: 

What requests do make it work? Does it need to be a requests that creates a file/folder or is a  `PROPFIND` enough? Accessing `/ocs/v2.php/cloud/capabilities` seems not to be enough because then you would not have the issue in the SDK tests

**Comment by saw-jan** [comment]
PROPFIND request also works but don't know about other requests
Logging in using webUI and then deleting user with curl also works

**Comment by phil-davis** [comment]
Note: the test code in https://github.com/owncloud/owncloud-sdk/pull/835 now does a loop of 2 requests to `/ocs/v2.php/cloud/capabilities` to work-around this newly-created-user problem. Remove the work-around when this issue is fixed.

**Comment by saw-jan** [comment]
TODO:
- [ ] Remove the work-around when this issue is fixed (https://github.com/owncloud/owncloud-sdk/pull/835)

**Comment by dpakach** [comment]
Possibly related to https://github.com/owncloud/ocis/issues/2272

**Comment by saw-jan** [comment]
re-tested `oCIS 1.19.1`. Looks like the issue has been fixed.

Create user:
```
curl -XPOST -uadmin:admin https://host.docker.internal:9200/ocs/v1.php/cloud/users \                                 
-d userid="user101" -d email="test@mail.com" -d password="1234" -vk

< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
< Content-Length: 154
< Content-Security-Policy: frame-ancestors 'none'
< Content-Type: application/xml; charset=utf-8
< Date: Wed, 06 Apr 2022 08:41:12 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Last-Modified: Wed, 06 Apr 2022 08:41:12 GMT
< Ocs-Api-Version: 1
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Ocs-Version: 55593b7e
...
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>102</statuscode>
    <message>account already exists</message>
  </meta>
</ocs>
```

Delete user:
```
curl -XDELETE -uadmin:admin https://host.docker.internal:9200/ocs/v1.php/cloud/users/user101 -vk

< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
< Content-Length: 144
< Content-Security-Policy: frame-ancestors 'none'
< Content-Type: application/xml; charset=utf-8
< Date: Wed, 06 Apr 2022 08:42:18 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Last-Modified: Wed, 06 Apr 2022 08:42:18 GMT
< Ocs-Api-Version: 1
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Ocs-Version: 55593b7e
...
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data/>
</ocs>
```

**Comment by saw-jan** [comment]
> TODO:
> 
> * [ ]  Remove the work-around in https://github.com/owncloud/owncloud-sdk after this issue gets fixed
>   https://github.com/owncloud/owncloud-sdk/blob/cbfd34abda770857b495e183e6a02d8e98880fd2/tests/providerTest.js#L210-L221

This task needed to be done

**Comment by pascalwengerter** [comment]
> > TODO:
> > 
> > * [ ]   Remove the work-around in https://github.com/owncloud/owncloud-sdk after this issue gets fixed
> >   https://github.com/owncloud/owncloud-sdk/blob/cbfd34abda770857b495e183e6a02d8e98880fd2/tests/providerTest.js#L210-L221
> 
> This task needed to be done

Thanks for the hint, I added this to the long overdue oCIS commit ID bump in the SDK in here https://github.com/owncloud/owncloud-sdk/pull/926

**Comment by saw-jan** [comment]
Task completed! Closing here
