### ISSUE TITLE
Update webUI suite names in drone file

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#2029]
The suite names in for webUI tests in drone file are out-of-date. Some test suites have been changed in the `web` repo, so need to update the webUI suite names here.

Some pipeline are not testing anything due to change in test suite name in the web repo, see https://drone.owncloud.com/owncloud/ocis/4947/64/6

**Comment by phil-davis** [comment]
It seems odd that the test runner does not exit with an error status when the test suite name does not exist.

Maybe `run.sh` should have an extra check that the folder for the suite exists in `tests/acceptance/features` and if not, then exit early with error status. That would make CI fail in this case.

**Comment by saw-jan** [comment]
@phil-davis Could you open an issue for that, so that we can look on that afterward.

**Comment by phil-davis** [comment]
> @phil-davis Could you open an issue for that, so that we can look on that afterward.

https://github.com/owncloud/web/issues/5089
