### ISSUE TITLE
Remove chunking from capabilities

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#203]
Tested with:

- http://ocis-latest.owncloud.com/
- ownCloud-2.7.0.666-daily20200408.pkg
- File upload > 10MB

oCIS as of today doesn't support chunking (https://github.com/owncloud/ocis/issues/195), and there's no short term plan for full implementation.

Please stop announcement of chunking capabilities. (see comments https://github.com/owncloud/ocis/issues/194#issuecomment-611448917 & https://github.com/owncloud/ocis/issues/194#issuecomment-611449840)

### Calling capabilities

Request:
```
GET https://ocis-latest.owncloud.com/ocs/v1.php/cloud/capabilities?format=json
```

<details>
  <summary>Click to expand response</summary>

```
{
    "ocs": {
        "data": {
            "capabilities": {
                "checksums": {
                    "preferredUploadType": "SHA256",
                    "supportedTypes": [
                        "SHA256"
                    ]
                },
                "core": {
                    "pollinterval": 60,
                    "status": {
                        "edition": "community",
                        "installed": true,
                        "maintenance": false,
                        "needsDbUpgrade": false,
                        "productname": "reva",
                        "version": "10.0.11.5",
                        "versionstring": "10.0.11"
                    },
                    "webdav-root": "remote.php/webdav"
                },
                "dav": {
                    "chunking": "1.0",
                    "chunkingParallelUploadDisabled": false,
                    "reports": [
                        "search-files"
                    ],
                    "trashbin": "1.0"
                },
                "files": {
                    "bigfilechunking": false,
                    "blacklisted_files": [],
                    "privateLinks": false,
                    "undelete": true,
                    "versioning": true
                },
                "files_sharing": {
                    "api_enabled": true,
                    "auto_accept_share": true,
                    "default_permissions": 22,
                    "federation": {
                        "incoming": true,
                        "outgoing": true
                    },
                    "group_sharing": true,
                    "public": {
                        "enabled": true,
                        "expire_date": {
                            "enabled": true
                        },
                        "multiple": true,
                        "password": {
                            "enforced": true,
                            "enforced_for": {
                                "read_only": true,
                                "read_write": true,
                                "upload_only": true
                            }
                        },
                        "send_mail": true,
                        "social_share": true,
                        "supports_upload_only": true,
                        "upload": true
                    },
                    "resharing": true,
                    "search_min_length": 3,
                    "share_with_group_members_only": true,
                    "share_with_membership_groups_only": true,
                    "user": {
                        "send_mail": true
                    },
                    "user_enumeration": {
                        "enabled": true,
                        "group_members_only": true
                    }
                },
                "notifications": {
                    "ocs-endpoints": [
                        "list",
                        "get",
                        "delete"
                    ]
                }
            },
            "version": {
                "edition": "reva",
                "major": 10,
                "micro": 11,
                "minor": 0,
                "string": "10.0.11"
            }
        },
        "meta": {
            "message": "OK",
            "status": "ok",
            "statuscode": 100
        }
    }
}
```
</details>

### Workaround

```
OWNCLOUD_CHUNK_SIZE=0 \
/Applications/owncloud.app/Contents/MacOS/owncloud \
--logfile -
```

**Comment by PVince81** [comment]
I'd like to have a try at this.

@butonic should the chunking code be removed completely or kept for later ?
if we need to keep it then we should add a config switch, default off, for enabling experimental chunking (since it's broken)

**Comment by PVince81** [comment]
I've grepped through reva code and it seems the chunking can be enabled through the config file.

Proposed change:
- [ ] change default config file (in cmd.go) to not set the chunking version: https://github.com/butonic/reva/blob/master/cmd/reva/gen/gen.go#L176
- [ ] change capabilities.go to not set chunking version to 1.0 by default: https://github.com/butonic/reva/blob/master/internal/http/services/owncloud/ocs/handlers/cloud/capabilities/capabilities.go#L109
- [ ] don't create chunks folder when disabled: https://github.com/butonic/reva/blob/master/internal/http/services/owncloud/ocdav/ocdav.go#L78
- [ ] optional: when chunking capability is disabled, also return an error in case the chunk header is sent: https://github.com/butonic/reva/blob/master/internal/http/services/owncloud/ocdav/put.go#L123

**Comment by PVince81** [comment]
as far as I saw there is some chunking v1 code in ocdav in reva, so it does "support" it but I guess it's broken in some way

here's a PR to remove the capability entry in reva: https://github.com/cs3org/reva/pull/678

**Comment by PVince81** [comment]
as far as we saw, chunking v1 (the old one which uses PUT with special file names) is already disabled in ocis-reva as the "bigfilechunking" capability value is set to false

we discovered that the desktop client is not reading that value, raised here: https://github.com/owncloud/client/issues/7849

**Comment by PVince81** [comment]
removed chunking v2 advertising from ocis-reva here: https://github.com/owncloud/ocis-reva/pull/145

I consider this task done from my side.
Next up would be scheduling the client side change.

**Comment by michaelstingl** [comment]
@PVince81 steps to test-drive this with a client?

**Comment by PVince81** [comment]
best is to wait for the release of ocis-reva which will make the setup easier. (cc @micbar)

setting up basically means following the instructions in the README of the OCIS repo: https://github.com/owncloud/ocis#development

**Comment by PVince81** [comment]
apparently the change in ocis-reva was not enough, also need the change in reva:  https://github.com/cs3org/reva/pull/678
