### ISSUE TITLE
create tests to get shares by id & do accept and decline them

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2059]
this tests are needed for ocis but need to be added in core repo

- [x] get share by valid id (https://github.com/owncloud/core/pull/38757)
- [x] accept share (https://github.com/owncloud/core/pull/38757)
- [x] decline share (https://github.com/owncloud/core/pull/38757)
- [ ] try all actions with valid and invalid ids
- [ ] check response of of all  see https://github.com/cs3org/reva/issues/1684

**Comment by phil-davis** [comment]
Note: tests should also run and pass in oC10

**Comment by dpakach** [comment]
@individual-it I added some tests in https://github.com/owncloud/core/pull/38757, I cannot think of any other scenarios regarding this. can we close this?

**Comment by individual-it** [comment]
CC @kulmann I'm closing this for now, please reopen or create a new issue if you feel more tests are needed
