### ISSUE TITLE
download previews of other users file

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2071]
## Describe the bug

Different error message for a request to download previews of other users file

## Steps to reproduce
- create two users in both backends `uu1`, `uu2`
- as user `uu1` upload file `lorem.txt`

## Actual Behaviour
- as user `uu2` request for preview of `lorem.txt`
  - in `ocis`
      ```sh
      curl -k -u uu2:uu2 https://localhost:9200/remote.php/dav/files/uu1/lorem.txt\?a=1\&c=xxxx\&preview=1\&scalingup=0\&x=32\&y=32 -v | xmllint --format -
      ```
      **Response:**
      ```sh
      <?xml version="1.0" encoding="UTF-8"?>
      <d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
        <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
        <s:message>File with name lorem.txt could not be located</s:message>
      </d:error>
      ```
  - in `oc10`
      ```sh
      curl -k -u uu1:uu1 http://localhost/core/remote.php/dav/files/admin/lorem.txt\?c\=xxxxxx\&x\=64\&y\=64\&forceIcon\=0\&preview\=1 -v | xmllint --format -
      ```
     **Response:**
      ```sh
      <?xml version="1.0" encoding="utf-8"?>
      <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
        <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
        <s:message>File not found: lorem.txt in 'uu1'</s:message>
      </d:error>
      ```
## Expected Behaviour

Same error message in both backend

## Setup

```
export ACCOUNTS_HASH_DIFFICULTY=4 \
export OCIS_URL='https://localhost:9200' \
export STORAGE_HOME_DRIVER='owncloud' \
export STORAGE_USERS_DRIVER='owncloud' \
export STORAGE_DRIVER_OCIS_ROOT='/tmp/ocis/storage/users' \
export STORAGE_DRIVER_LOCAL_ROOT='/tmp/ocis/local/root' \
export STORAGE_DRIVER_OWNCLOUD_DATADIR='/tmp/ocis/owncloud/data' \
export STORAGE_METADATA_ROOT='/tmp/ocis/metadata' \
export STORAGE_HOME_DATA_SERVER_URL='http://localhost:9155/data' \
export STORAGE_USERS_DATA_SERVER_URL='http://localhost:9158/data' \
export WEB_UI_CONFIG=$HOME/www/ocConfigs/ocis-config.json \
export WEB_ASSET_PATH=$HOME/www/web/dist \
export IDP_IDENTIFIER_REGISTRATION_CONF=$HOME/www/ocConfigs/idp.yml \
export PROXY_ENABLE_BASIC_AUTH=True \
export OCIS_LOG_LEVEL='warn' \
export ACCOUNTS_DATA_PATH="/tmp/ocis-accounts/" \
export SETTINGS_DATA_PATH="/tmp/ocis/settings" \
export STORAGE_SHARING_USER_JSON_FILE="/tmp/ocis/shares.json" \
export STORAGE_DRIVER_OWNCLOUD_REDIS_ADDR='localhost:6379'
```

<details>
<p>

```console
OCIS_VERSION=latest
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

## Additional context
Test covered [here](https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavPreviews/previews.feature#L117-L133)

**Comment by phil-davis** [comment]
When "bad things happen" we expect that the response HTTP status and exception are the same from all back-end implementations.

Do we also expect/require that the response message text is the same for all implementations?
Or are implementations allowed to respond with differences in the message text?

@micbar @dragotin or anyone. How strict is the compatibility requirement?

**Comment by micbar** [comment]
@phil-davis IMO this is an easy fix and having slightly different response texts is bad.

So let us be strict here.

**Comment by ScharfViktor** [comment]
re-tested oCIS version 1.12 and oC10 version 10.8
still relevant

**Comment by amrita-shrestha** [comment]
exist on spaces dav-version also

**Comment by saw-jan** [comment]
From https://github.com/owncloud/ocis/pull/6897#pullrequestreview-1549355311

>Exactly what I meant +1 We have two options
>
>- drop oc10 compatibility and adjust test expectation
>- always return error messages like File not found: lorem.txt in ''

>We are going for option 1 - We keep our error message and adjust test expectation. We accept that we will have a different error message than oc10.

So, the difference is expected and we have to change the test expectaion too.

Todo:
- [ ] change test expectation

**Comment by saw-jan** [comment]
I will close the issue here.

**Comment by amrita-shrestha** [comment]
moving to done as more than one issue related to one PR
