### ISSUE TITLE
Update `gid` does not work if same as `uid`

### ISSUE THREAD

**Issue by axstet** [owncloud/ocis#2089]
## Describe the bug

Update `gid` does not work if same as `uid`.

## Steps to reproduce

1. ```ocis accounts inspect bc596f3c-c955-4328-80a0-60d018b4ad57```
2. ```ocis accounts update --uidnumber 90000 --gidnumber 90000 bc596f3c-c955-4328-80a0-60d018b4ad57```
3. ```ocis accounts inspect bc596f3c-c955-4328-80a0-60d018b4ad57```
4. ```ocis accounts update --uidnumber 90001 --gidnumber 90000 bc596f3c-c955-4328-80a0-60d018b4ad57```
5. ```ocis accounts inspect bc596f3c-c955-4328-80a0-60d018b4ad57```

## Expected behavior

Both `uid` and `gid` are always updated.

## Actual behavior

From 1 to 3 only `uid` is set. From 3 to 5 also `gid` is set.

## Setup

Stock v1.6.0

**Comment by wkloucek** [comment]
We removed the accounts service, therefore no longer an issue
