### ISSUE TITLE
[QA] add ability to run the full webUI CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2107]
Sometimes developers want to run the whole web UI test suites. For example, when updating the reva version into OCIS it will be nice to know that the whole set of web UI tests will pass.

Adjust `.drone.star` CI so that all the web UI tests run if:
- [x] the CI is for a tag (https://github.com/owncloud/ocis/pull/2123) or
- [x] the PR has `full-ci` in the PR title (in any mix of case - `full-CI` `Full-CI` `FULL-CI` should all work) #2116 

By doing this, the full CI can be run as needed without actually having to edit `.drone.star`
(If the developer has to edit `.drone.star` then there is the chance that the edit will accidentally get committed in the PR, and if that happens the the full CI would get accidentally switched on in master)

While doing this, try to avoid explicitly listing all the web UI acceptance test suite names. (see #2097 which is removing the explicit list of suite names). Maybe implement the "run_parts" system that we use in oC10 core `run.sh` for running all test suites in a number of parallel pipelines.

**Comment by phil-davis** [comment]
There is more to come!

**Comment by phil-davis** [comment]
@kiranparajuli589 the "full-ci on tag" part now needs to happen. See comment https://github.com/owncloud/ocis/pull/2116#issuecomment-855462259

**Comment by dpakach** [comment]
@phil-davis @kiranparajuli589  is this issue complete? can we close it?

**Comment by phil-davis** [comment]
Done
