### ISSUE TITLE
File is still present in the file list after declining a share

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2112]
## Steps to reproduce

1. As Einstine upload file `lorem.txt` and share with `Marie`
2. As marie accept the share and check the files in `Shares` folder, the file `lorem.txt` is listed
3. Now go to shared with me page, decline the share and recheck the `Shares` folder

## Expected behavior
lorem.txt should not be present

## Actual behavior
lorem.txt is present in the `Shares` folder

**Comment by phil-davis** [comment]
@dpakach the description sounds like it happens in web? Please confirm.

**Comment by kiranparajuli589** [comment]
issue seems to be in `ocis`, `PROPFIND` request to the shares folder contains the declined resource.

**Comment by kulmann** [comment]
Yes, obviously it surfaces in web, but this is in API issue.

**Comment by dpakach** [comment]
Yes, I agree, this is not really a ui issue so I'll close this it's better described with api steps in https://github.com/owncloud/ocis/issues/2128. I'll reopen that issue.
