### ISSUE TITLE
 Login with capital UserID leads to a browser loop condition

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#2114]
## Describe the bug

Login with capital UserID leads to a browser loop condition

## Steps to reproduce

1. Login with `Marie` instead of `marie`
2. Browser continuously loads url `https://localhost:9200/?code=EmLTKR-p4JbHrsYnz463tFSwZC7G77-H&code=Szo40YmbN8xJZLzbjvdpfYdMImlCmYxI&code=vuz8_DLbnoYrb0_Jc5PBq1kLch1Lbtmv&code=B25NgWO6U89KSluYWxosPdoeuDf43r__&code=nGbTuWEnxL7X2zY-X510OnfcVCbvjCli&code=OaQXTMrgzMiUAjnO1gEOIEHlY3AhlL-0&code=a1nmNFfocvHmthLMXri2J-vo8osJqIvf&code=a_dZhiO3mjP0Pb6EbHB1aPHzU4QfHVE0&code=iV66G7ov5ncCSZbjt9kCAZGVNA3JTv1L&code=y0g_X951oiHpi9OSQecoVzA2je1wCtSH&code=_RucU5UhtNTXq94fQVs_BffKzFdzYrY0&code=lenh_LQvGOpCM1U2lLstBpWAPAFj6zV0&code=ceiHM5togUu9qUSbjNfnik2XufXkl6jH&code=NeTnYlsSQlscfR_kLNql6ZsNcAnVHsbI&code=wWDtAETf5MkM5Jpc1tgeyx-ZE-56kC9U&code=e5UxUDX7pDWmYYeSzz7ucwGmeeJCZZG9&code=kUDYQwJiN3UKylV0neFDg0_E3fWung4b&code=XtQYoUPIYN4HzTXRtJBYlOZWx8Mq-2tY&code=XrcuFJjb9pZl1FN10tJ7-BMyNdwufwqb&code=cwj9SdLVjMtBJ89Z9e085lSfD2kWReJU&code=rHcdnsUhumR6aboEM4GKK8VMjbXE_ZuT&code=Yc8gHKkXEyq1cM6VozPMWNQO3stoVIAf&code=jDEgYT3duZDlVcwzJ5kEjvWsn3bOTH85&code=Xe-BKosQM1Msh3-r8mLDvKTj6wyBQ0Qt&code=wUSh2413hI7nKFOBdE6Vi92m5T41xTx-&code=dfJp3XeLmU9HHfUAS1ByVaYoNnWrQ9Pf&code=ay7RWsuZts_0ZYW1t7_jnyoOnDmQRBeO&code=KOQrBIqUb0xl7vepFEd3N315bqBotjbO&code=0uHUvGGlJW3hJx4qzwDO4jLtlfhzZOEF&code=90qLuUpJ2eZ_y43Ps0i9iJ8KlADEqPKj&code=FmgRfloX7j0yC6aSyRWRmUo72Tq7zazq&code=9kOzwuo9VVopAvvf7hQie3YIP2ZWjFA4&code=Ho8xbeJb_EFm55s8xbrG9G0ZGj6tKFBq&code=5hl_-K4rzA0z-PxOrSy9Jyfe1NvUspnN&code=I1haBv3GSJ89It9qy-LzREZT0lVOAj1P&code=b8DHsQofLxclTljr3wvEpjMU2YYkGErH&code=UTjPK4SQvqZ3DFyZfiO7TnNEOUm_JOZR&code=X8Xv95ZrZIlSlClxIWwLiOrl_ilUuJzy&code=LxkAyDtkauXY4ydi3lMM26gaPE84txi5&code=0Yxkp16h-mjnq1xRWMMbJDP8BTFxAXG1&code=Pc60ifEXez4i3arUGu3XcFrRZa4PTJ5K&code=l9K_wBVCsxHr0xhGDFHMb1DFbLLoO-RE` and always adds a new `code=$value` to each new request
3. You can exit this state only by closing the browser window

## Expected behavior
Successful Login

## Actual behavior
Loop condition

## Setup

Local build of ocis master

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by wkloucek** [comment]
@micbar I can login just fine with the latest oCIS (1.12.0). All caps (`MARIE`) also works fine. https://github.com/libregraph/lico/blob/b584e03722244bc9a20ed3eea576eaba6387e5c0/identifier/backends/ldap.go#L321 seems to be case insensitive.
