### ISSUE TITLE
Settings Language dropdown not populated on first run

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#2126]
### Steps to reproduce
1. clone ocis
2. `cd owncloud/ocis/ocis`
3. `make build ocis`
4. `bin/ocis server`
5. browser -> localhost:9200
6. login as einstein (or any other user)
7. go to `Settings`
8. Languages dropdown is unpopulated

### Expected behaviour
It should display `English` for the logged in user.

### Actual behaviour
It shows nothing.

![screencast 2021-06-07 10-38-55](https://user-images.githubusercontent.com/6905948/120986632-1578a680-c77d-11eb-853b-5ffbaf3dc648.gif)

**Comment by jvillafanez** [comment]
https://github.com/owncloud/ocis/pull/2465 fixes the this issue.

**Comment by pascalwengerter** [comment]
Closed via #2465
