### ISSUE TITLE
Enablement for OnlyOffice integration

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#2132]
# Feature

Use OnlyOffice with a Full Stack ocis Instance.

## Building Blocks
![OnlyOffice-oCIS](https://user-images.githubusercontent.com/4378513/121024670-bcbd0400-c7a4-11eb-888d-b97a5855b037.png)

### Challenges

1) How would the document server authenticate requests whithout a user context?
2) How does the connector service create a user context for the Storage Server?

**Comment by micbar** [comment]
@butonic @wkloucek @dragotin 

We need to help OnlyOffice on the Fastlane IMO.

@wkloucek How does the Collabora / WOPI Server stack solves this issue conceptually?

**Comment by pascalwengerter** [comment]
@rpocklin saw you working on sth similar in `web` so adding you to the loop / keeping you posted 😉

**Comment by pmaier1** [comment]
@antipkin-A @linneys FYI

**Comment by wkloucek** [comment]
# Questions

1. How should one configure CS3 client when working from our plugin? Is 
there a possibility to load the pre-configured client?

    - REVA gateway client example https://github.com/cs3org/reva/blob/183af2f94288991e177b41e6bbe44aaa9cfe3baf/cmd/reva/grpc.go#L49

2. How can we send an authorized CS3 API request on behalf of the user 
from plugin backend? In the chat you specified that such a request might 
be sent via go context, but afterwards it is unclear for us which key 
has to be used, i.e. the key that other services will check for the 
authorization token presence.

    - oCIS proxy always sends REVA token with requests (https://github.com/owncloud/ocis/blob/2927dc45c39793e42ce686c6cf1508118eab744d/proxy/pkg/middleware/account_resolver.go#L123), therefore it is present in the "x-access-token" header

    - this token can than be put in an ctx https://github.com/cs3org/reva/blob/183af2f94288991e177b41e6bbe44aaa9cfe3baf/cmd/reva/grpc.go#L44-L45 and the context needs to be passed to the grpc request https://github.com/cs3org/reva/blob/183af2f94288991e177b41e6bbe44aaa9cfe3baf/cmd/reva/upload.go#L106

3. Do you have any simple usage example of CS3 API InitiateFileDownload 
and InitiateFileUpload methods?

    - upload https://github.com/cs3org/reva/blob/master/cmd/reva/upload.go
    - download https://github.com/cs3org/reva/blob/master/cmd/reva/download.go

4. Is there any data that must be additionally encrypted when sent to 
the Document Server that might be hosted on another server?

    - https should be always used (with insecure option for development)
    - there is no file encryption

# Implementation recommendation
1. app provider
    - demo implementation only https://github.com/cs3org/reva/blob/master/pkg/app/provider/demo/demo.go
    - wopi example https://github.com/cs3org/reva/blob/f004c26ecbc20e21543d6db27e2d5bfce9022146/pkg/app/provider/wopi/wopi.go#L120



# App provider workflow

1. only office driver registers itself at the app registry https://github.com/cs3org/reva/blob/f004c26ecbc20e21543d6db27e2d5bfce9022146/pkg/app/provider/demo/demo.go#L35 with mimetypes it can handle and additional information https://github.com/cs3org/cs3apis/blob/63c2cee07f9008758a48691dfa45e4181b800b81/cs3/app/registry/v1beta1/resources.proto#L34-L59 
2. if a user decides to open a file with only office "GetAppURL" will be called in the only office driver: https://github.com/cs3org/reva/blob/f004c26ecbc20e21543d6db27e2d5bfce9022146/pkg/app/provider/demo/demo.go#L42-L48. This will lead ownCloud Web to open the given content in an iframe (as a form post or with a http get, is currently being implemented).

In order for this to work you need a server that:
- serves some html wich can be embedded into that iframe

The html in the iframe can receive a token and additional information via from parameters (form post) or as headers (http get).

The token can then be used to load the document via the CS3APIs and display it (from the backend which also served the html)

**Comment by wkloucek** [comment]
In order that OnlyOffice works with the CS3 WOPI server, we need this patch: https://github.com/cs3org/wopiserver/pull/47

Then following deployment can open and edit files with OnlyOffice: https://github.com/owncloud/ocis/pull/2478

**Comment by glpatcern** [comment]
> In order that OnlyOffice works with the CS3 WOPI server, we need this patch: [cs3org/wopiserver#47](https://github.com/cs3org/wopiserver/pull/47)

Actually with the latest fixes where Reva mints short tokens for WOPI, that patch ought to be obsolete. And if not, to be rediscussed but I still have the conceptual concern I had put there: I don't think it's good for WOPI to inspect the Reva token, so far WOPI considers it totally as an opaque info representing the user's credentials.

**Comment by kulmann** [comment]
Yes, I think we can close here. Anything else (bugs or future features) deserves new, dedicated issues.
