### ISSUE TITLE
[Trashbin] restoring a file in existing location gives incorrect status code

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2139]
## Describe the bug

when restoring a file to an existing location should overwrite existing file and give status code 204 - No content (this is what we get in owncloud 10) but gives 201

## Steps to reproduce

1. Create a file `lorem.txt`
2. Delete `lorem.txt`
3. create another file `lorem.txt`
4. From traashbin restore original `lorem.txt`

## Expected behavior
file is overwritten with status code 204

## Actual behavior
file should be overwritten with status code 201

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by kiranparajuli589** [comment]
Update: status code is as expected `204` and file also exists for the owner!

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0 and oC10 in docker(v.10.8)

Restore file in Oc10: ` MOVE http://host.docker.internal:8080/remote.php/dav/trash-bin/admin/2133`
and in oCIS: `MOVE https://localhost:9200/remote.php/dav/trash-bin/admin/0316ab63-4076-4d51-bee8-ce2f18d69d0e`
have same behavior

actual behavior: file is not overwritten. status code `412 Precondition failed`
with response:

`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>The destination node already exists, and the overwrite header is set to false</s:message>
  <s:header>Overwrite</s:header>
</d:error>`


<img width="1416" alt="Screenshot 2021-09-09 at 12 23 37" src="https://user-images.githubusercontent.com/84779829/132669510-3f6d3a60-e9df-427a-ad8d-b08b3a8f878f.png">

@dpakach do you sure that file should be overwrite?

**Comment by dpakach** [comment]
seems like the issue is fixed so closing it.
