### ISSUE TITLE
Implement async progress reporting for upload / assembly

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#214]
When finishing a large upload the assembly of a 40 GB file might take a long time. Currently, tus has no extension for this and the [`concatenation` extension](https://tus.io/protocols/resumable-upload.html#concatenation) explicitly states:

> The response to a HEAD request for a final upload SHOULD NOT contain the Upload-Offset header unless the concatenation has been successfully finished. After successful concatenation, the Upload-Offset and Upload-Length MUST be set and their values MUST be equal. The value of the Upload-Offset header before concatenation is not defined for a final upload.

transloadit is mentioning the `/assembly` endpoint https://github.com/tus/tusd/wiki/Uploading-to-Transloadit-using-tus and also that it uses a socket.io server that can be used to track the progress:  https://github.com/tus/tusd/wiki/Uploading-to-Transloadit-using-tus#getting-progress-and-more-events-over-web-sockets

The tusd handler has a hook mechanism that can be used to expose progress.

Or we could let clients make HEAD requests against the upload and return a read only progress property in the metadata ... as a quick hack ...

**Comment by butonic** [comment]
thx @michaelstingl for asking about this

**Comment by butonic** [comment]
@felixboehm I wonder if we can use websockets for clients and how this integrates with a push server ...

**Comment by michaelstingl** [comment]
I think as a fallback, we'll always need pull/polling-based approach. But it would be cool to have the more fancy options too.

**Comment by butonic** [comment]
AFAICT an upload has multiple phases:
- transfer (bring bytes to the storage, but not yet accessible to the user)
- assembly (optional, if multiple chunks need to be assembled)
- preprocessing (optional, eg virus scanning, content manipulation)
- finishing (make available to the user)
- postprocessing (content indexing, thumbnail generation ...)

The tus protocol only covers the first and second phase, transfer and assembly.

When no preprocessing happens, we can return the etag and new fileid immediately.
While preprocessing  is in progress we want to show the progress when listing the containing folder. This might be a custom PROPFIND request or property? during progress the etag and fileid won't hale changed, but we might return a `progress` property? Similar to the async / lazy ops header, which returns a location that clients can use to poll for changes.

AFAICT we need to either extend the FinishUpload method of the tus backend implementations or register hooks that can start the preprocessing properly, keep track of progress and finalize the upload by making the file available to the user / moving it to the correct destination.

postrocessing should not produce anything the clients need.

But for all of this we need a workflow. AFAICT the client may not get a new etag until the upload has passed the finishing phase.

**Comment by PVince81** [comment]
as discussed, we'd need to invent a new TUS extension for async.
the extension would return extra headers to signal that it's going into async mode (like Lazy-Ops)

**Comment by refs** [comment]
@butonic want to keep this open?

**Comment by butonic** [comment]
cc @dragotin  This boils down to a state machine for uploads. Then file listings could return the state of a file as well: `transfer`, `assembly`, `preprocessing`, `finishing`, `postprocessing`. See https://github.com/owncloud/ocis/issues/214#issuecomment-630684815

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
