### ISSUE TITLE
Uploading a file with invalid SHA1 checksum passes successfully

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2142]
## Describe the bug

When Uploading a file with invalid SHA1 hash, the upload is successful 
## Steps to reproduce

1. try to upload a file witn invalid checksum
```
curl -XPUT https://localhost:9200/remote.php/dav/files/admin/checksumfile1.txt -d 'hello world' -H 'OC-Checksum: SHA1:test'  -u admin:admin -vk
```

## Expected behavior
the upload should fail with status 400 and appropriate message

## Actual behavior
the upload is successful

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
the behavior matches the expected result:
<img width="1229" alt="Screenshot 2021-09-09 at 13 12 37" src="https://user-images.githubusercontent.com/84779829/132676420-60dc8f32-8faf-431c-bb7e-e22caa9e4f35.png">
`<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception>Sabre\DAV\Exception\BadRequest</s:exception><s:message>The computed checksum does not match the one received from the client.</s:message></d:error>`

@dpakach please close it
