### ISSUE TITLE
Creating a public link with all permissions(31) fails

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2145]
## Describe the bug

Creating a public link with all permissions(31) fails

## Steps to reproduce

1. create a folder sfold
2. Create public link for folder sfold with permissions 31 (all)
```
curl -XPOST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d shareType=3 -d path=/sfold -d permissions=31 -u admin:admin -kv 
```
## Expected behavior
successfully create link with all permissions

## Actual behavior
Request fails with following message
```
> POST /ocs/v1.php/apps/files_sharing/api/v1/shares HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 38
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 38 out of 38 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 170
< Content-Type: text/xml; charset=utf-8
< Date: Wed, 09 Jun 2021 08:36:17 GMT
< Vary: Origin
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<ocs><meta><status>error</status><statuscode>400</statuscode><message>Could not read permission from request</message></meta></ocs>%  
```
## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
It works correct
`curl -XPOST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d shareType=0 -d path=/folder1 -d permissions=31 -d shareWith=marie -u admin:admin -kv `

return without errors
<img width="1114" alt="Screenshot 2021-09-09 at 15 34 54" src="https://user-images.githubusercontent.com/84779829/132695980-4252bf76-bc31-4d87-9bab-c46e803f5a0e.png">

@dpakach please close it
