### ISSUE TITLE
Cannot move a file to a shared folder

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2146]
## Describe the bug

user cannot move a file to a shared folder

## Steps to reproduce

1. as admin create and share folder `sfold` with einstein with editor permission
2. as einstein upload lorem.txt
3. as einstein accept `sfold` offered by admin
4. try to move file lorem.txt to `Shares/sfold`

## Expected behavior
file is moved successfully

## Actual behavior
cannot move the file and gives following error
```
An error occurred while moving lorem.txt
Unknown error
```
## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by jasson99** [comment]
Is it same as this issue? https://github.com/owncloud/ocis/issues/764

**Comment by ScharfViktor** [comment]
> Is it same as this issue? #764

This is the same case "move the file to  Shares/subfolder"
@dpakach please close as a duplicate
