### ISSUE TITLE
Group name with emoji can be created but file cannot be shared with such groups

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2157]
## Steps to reproduce

1. Create a group with emoji in its name
```
curl -XPOST https://localhost:9200/ocs/v2.php/cloud/groups -d groupid='😀 😁' -u admin:admin -kv

<ocs><meta><status>ok</status><statuscode>200</statuscode><message>OK</message></meta><data></data></ocs>%                                                                                               

```
2. Add user einstein to group `😀 😁`
```
curl -XPOST https://localhost:9200/ocs/v2.php/cloud/users/einstein/groups -d groupid='😀 😁' -u admin:admin -kv

<ocs><meta><status>ok</status><statuscode>200</statuscode><message>OK</message></meta><data></data></ocs>%                                                                                                    
```
3. Try to share a file to `😀 😁` as admin
```
 curl -XPOST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d shareType=1 -d path=/sfold -d permissions=15 -d shareWith='😀 😁' -u admin:admin -kv
```
## Expected behavior
sharing is successful
## Actual behavior
sharing fails with following response
```
<ocs><meta><status>error</status><statuscode>998</statuscode><message>group not found</message></meta></ocs>%                                                                                                 
```
## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by ScharfViktor** [comment]
tested on `ocis 6.0.0`

we use SharingNg and share using groupId or userId

to find user or group which name contains emoji we use `GET` `graph/v1.0/groups?%24search=` endpoint


I tried to find by 😀 (%F0%9F%98%80) and it works
<img width="1151" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/a9291e58-ec93-4cc3-bf6a-9efb1de01200">

since we don't support OCS we'll not fix this bug
