### ISSUE TITLE
Sort out "Won't fix" entries in API expected-failures files

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2160]
The expected-failures files have a section at the end headed "Won't fix"

Look through the entries and sort them out into these 2 categories:
1) won't implement - things are are "features" of oC10 but are not being implemented on OCIS
2) different behavior - things that are features of both oC10 and OCIS but the behavior is known to be different in some minor way, and will stay different

For (1) "won't implement", skip the scenarios in core - so that we do not waste time constantly running them in OCIS CI for no benefit.

For (2) "different behavior", re-work the core test code and/or scenarios to cope with the expected different behavior. In some cases you might skip the existing scenario on OCIS, and add another scenario for the OCIS behavior, and skip that on oC10. In some cases it might be OK to modify the underlying test code so that it knows what minor difference to expect when running on OCIS.

Then update the core test commit id in OCIS, and we should be able to delete all the scenarios in the "Won't fix" section.

**Comment by dpakach** [comment]
Blocked until https://github.com/owncloud/ocis/issues/1343#issuecomment-872196526 and https://github.com/owncloud/ocis/issues/1321#issuecomment-871905753 gets sorted out

**Comment by phil-davis** [comment]
IMO we know the answers to the linked comments above and can sort out more of the "won't fix" items.

**Comment by phil-davis** [comment]
Note: "old" v1 chunking is supported on reva and OCIS. Many of the scenarios are now passing. So we do want to keep running chunking v1 test scenarios in reva and oCIS.

It is the "new" v2 chunking "NG" that does not have support in reva/oCIS. The tests for "chunking NG" are no longer being run in reva/oCIS CI.

The desktop sync client is able to use "chunking NG" if it is available and advertised by the server. That will not happen on reva/oCIS. reva/oCIS will be able to use the TUS protocol. And the desktop sync client will use TUS.

**Comment by dpakach** [comment]
seems like all issues are resolved here so closing.
