### ISSUE TITLE
Adding public upload to a read only shared folder as a receipient is allowed 

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#2164]
## Describe the bug

When a recipient of a share with permissions "share, read" creates a public link shares with settings `publicUpload=true`, the public link is created.

## Steps to reproduce

1. As user `Alice` create folder `test`
2. As user `Alice` share folder `test` to user `Brian` with permissions `read, share`
3. As user `Brian`, accept the share `test` offered by user `Alice`
4. As user `Brian`, create a public link share with path `/Shares/test` and and `publicUpload: true`

## Expected behavior
The OCS status code should be `404`

## Actual behavior
The OCS status code is `200`

**Comment by pmaier1** [comment]
The solution to this is part of the "Resharing" feature.

**Comment by rhafer** [comment]
Resharing was implemented with https://github.com/owncloud/ocis/pull/3904

the remaing expected failures should be addressed in: https://github.com/cs3org/reva/pull/3207
