### ISSUE TITLE
Update displayname to empty value is successful

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#2167]
## Describe the bug

When the displayname of an user is updated to an empty value, it is successful.

## Steps to reproduce

1. Create user `brand-new-user`
2. Change the displayname of the user `brand-new-user` to `A New User`
3. Change the displayname of the user `brand-new-user` to `""`

```
curl -k -X PUT https://localhost:9200/ocs/v1.php/cloud/users/brand-new-user -H OCS-APIREQUEST="true" -d key="displayname" -d value="" -u admin:admin | xmllint --format - 

<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data/>
</ocs>
```

4. Get the user information:

```
curl -k -X GET https://localhost:9200/ocs/v1.php/cloud/users/brand-new-user -H OCS-APIREQUEST=true -u admin:admin | xmllint --format -                                             

<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <enabled>true</enabled>
    <id>brand-new-user</id>
    <display-name/>
    <displayname/>
    <email>brand-new-user@example.com</email>
    <quota>
      <free>2840756224000</free>
      <used>5059416668</used>
      <total>2845815640668</total>
      <relative>0.18</relative>
      <definition>default</definition>
    </quota>
    <uidnumber>20006</uidnumber>
    <gidnumber>30000</gidnumber>
  </data>
</ocs>

```

## Expected behavior
The display name of the user should not be updated to an empty value. The display name should be equal to the username.

## Actual behavior
The display name of the user is updated to an empty value.

**Comment by phil-davis** [comment]
Probably you should be able to update the display name to an empty value, but then a request for user information should return the user-name in the display name. (oC10 does something like this - need to check exactly what happens)

**Comment by jasson99** [comment]
> Probably you should be able to update the display name to an empty value, but then a request for user information should return the user-name in the display name. (oC10 does something like this - need to check exactly what happens)

yes, that is exactly the behavior in oc10. But in ocis, the display name has no value now, after it has been set to empty
Maybe I should make the actual and expected behavior clearer.

**Comment by ScharfViktor** [comment]
we no longer support endpoint ocs. so we can close it
