### ISSUE TITLE
Trying to access another user's file gives http 403 instead of 404

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2175]
## Describe the bug

Trying to delete another user's file gives http 404 instead of 403

## Steps to reproduce

1. as admin try to delete Einstein's files
```
❯ curl -XDELETE https://localhost:9200/remote.php/dav/files/einstein/parent -kv -u admin:admin                    
> DELETE /remote.php/dav/files/einstein/parent HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< Content-Length: 0
< Content-Security-Policy: default-src 'none';
< Date: Mon, 14 Jun 2021 07:15:54 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 
* Connection #0 to host localhost left intact 

```
## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

## Additional context
**note** actual bug report in https://github.com/owncloud/ocis/issues/2175#issuecomment-860547288

**Comment by karakayasemi** [comment]
I guess, in this case, 404 is the correct response to not leak a user's file list to another user.

**Comment by phil-davis** [comment]
@dpakach I guess oC10 is returning 403? Is that true?

If oC10 is different, then we need to discuss that in oC10.

**Comment by pascalwengerter** [comment]
Adding @C0rby here for security insights :)

**Comment by dpakach** [comment]
@phil-davis I rechecked, but I actually made a mistake in the original issue. 
the issue is that it gives 403 when it's supposed to give 404. But a really strange thing is when we request for admin user's files, it gives 404.

**Comment by dpakach** [comment]
## Steps to reproduce

Steps to reproduce the behavior:
1. Create two users user1 and user2
2. As user1 create file `lorem.txt`
1. as user2 try to delete user1's files
```
❯ curl -XDELETE https://localhost:9200/remote.php/dav/files/user1/lorem.txt -kv -u user2:user2         
> DELETE /remote.php/dav/files/user1/lorem.txt HTTP/1.1
> Host: localhost:9200
> Authorization: Basic dXNlcjI6dXNlcjI=
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Content-Length: 0
< Content-Security-Policy: default-src 'none';
< Date: Mon, 14 Jun 2021 09:37:54 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 
* Connection #0 to host localhost left intact    

```
## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

## Additional context
Add any other context about the problem here.

**Comment by phil-davis** [comment]
@dpakach and is oC10 different? Please mention how oC10 behaves, so we know if we also need to think about the oC10 implementation.

**Comment by dpakach** [comment]
@phil-davis I've updated the explaination, oc10 gives 404 which is correct behavior

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
@dpakach looks like it's fixed.
Admin is  trying to remove the Maries file:

![Screenshot 2021-09-13 at 10 05 57](https://user-images.githubusercontent.com/84779829/133047242-d66d0e59-edd5-49d8-9928-bf9aa89093c3.png)
