### ISSUE TITLE
Blacklist file extensions

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#2177]
Currently there is no way of preventing users to block certain file extensions to be uploaded. A precedent of this was reported in #1345, where doing `curl 'http://localhost:9140/remote.php/webdav/home/.htaccess' -X PUT -d "mydata" -u user0:123456 -v` works because `.htaccess` is treated as a normal file, and there is no Apache server behind that complains.

A more robust solution will mean that Storage drivers need to advertise which file extensions are supported.

**Comment by kobergj** [comment]
This is implemented now :fireworks: So I am closing this because we actually implemented this but didn't close it. Hurray!
