### ISSUE TITLE
Keep Track of oCIS Performance

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2178]
oCIS trades read requests for write requests to avoid write bottlenecks. One of the tradeoffs is having to stat all intermedtiate path segments when trying to determine the permission of a leaf in a deep tree structure. We need to measure and clarify the impact.

I propose to write a test case that does the following:
1. create a folder
2. stat the folder
3. go into the created folder
4. go to 1

This will create a deep tree structure: `/f1/f2/f3/.../fx`

There are two parameters:
1. folder depth (x) = how deep should the tree be, default to 1000
2. how many stat requests (n) should be made, default to 4

The first stat request will not hit any cache and might take longer, so it should be measured separately
The next three (n-1) stat requests can be aggregated later in postprocessing

Ultimately, this should allow us to produce a graph where
- the x axis represents the tree depth
- the y axis represents the timings
- we have three functions plotted:
  1. the time it takes to MKDIR
  2. the time it take to make the first PROPFIND
  3. the time it take to make subsequent PROPFINDs
 

The csv would have the
- folder depth in the rows
- 1. column = MKDIR
- 2. column = first stat
- 3. column = second stat
- ...

profit!

**Comment by dragotin** [comment]
Meanwhile we have different K6 based tests that give us a good profile of the performance of oCIS in general.

What I would like to have is a nightly running job that runs a representative K6 job every night on the same hardware and stores a) the full report and b) a few (3-5) numbers as key measures that represent the performance.  @fschade can help picking a useful K6 script.

Following a KISS idea a good first step would be to store these  key values into an ongoing list and somebody checking the values manually (yes...), to learn if that is useful. Grafana and 100% solutions later ;-)

The purpose is not to make an absolute statement of performance, but to realize changes from day to day and be able to identify perf drops.

@tbsbdr @micbar can we add that to the backlog pls?

**Comment by dj4oC** [comment]
is there any update / new numbers since 4th of Dec.?

**Comment by ScharfViktor** [comment]
> is there any update / new numbers since 4th of Dec.?

there have been some improvements:
- on the server side
- #8191 #8082 #7896 #7869

Found and fixed bugs due to k6: 
- #8171 #8180

You can open the dashboard using credentials [see here](https://confluence.owncloud.com/display/OT/K6+benchmark+visualization)

**Comment by ScharfViktor** [comment]
I added the link https://grafana.k6.infra.owncloud.works/d/P4D1D31A5B69203FF/test?orgId=1&refresh=15m in CI as the final step of this task. Other improvements will be new tasks
