### ISSUE TITLE
Public link expiration time is not valid in public link

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2181]
## Describe the bug

As described in https://github.com/owncloud/core/pull/38813, shares should work until the end of the expire day. but the API only reports `2021-06-19 00:00:00` as `expiration`.

## Steps to reproduce

1. create a public link and set expiration date of +3 days
2. request the public link using the sharing API
eg.
```
curl https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/shares/AqWajhFNREvFkux\?format\=json -u admin:admin -k | jq
```

## Expected behavior
expiration property has timestamp of the end of the day.
eg. 
```
"2021-06-19 23:59:59"
```
## Actual behavior
expiration property has timestamp of the beginning of the day.
eg. 
```
"2021-06-19 00:00:00"
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by phil-davis** [comment]
It will be easiest if OCIS and reva also make the same adjustment to the reported share expiration time.
Otherwise, we need to adjust the test code to expect that the oC10 implementation returns 23:59:59 and the OCIS implementation returns 00:00:00

@kulmann @micbar can we adjust OCIS and reva ASAP to report 23:59:59 ?

**Comment by phil-davis** [comment]
This was a breaking API change that was attempted in core PR https://github.com/owncloud/core/pull/38813

But it was found that at least the desktop client depends on the current "unfortunate" `00:00:00` timestamp: https://github.com/owncloud/client/issues/8733

So the change has been reverted in oC10 core: https://github.com/owncloud/core/pull/38856

For the moment, both oC10 core and OCIS stay with reporting `00:00:00`.

So they are "feature ;) compatible". I am closing this issue.
