### ISSUE TITLE
Folder overwrite on shared files doesn't works correctly on copying file

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#2183]
## Steps to reproduce

1. as admin create folders `sfold/sfold2/sfold3`
2. as einstein create folders `new/new2`
3. as admin share `sfold` to einstein
4. as einstein accept the share offered by admin
5. as einstein try to copy `new` to `Shares/sfold/sfold2`
```
curl https://localhost:9200/remote.php/webdav/new -XCOPY -H Destination:https://localhost:9200/remote.php/webdav/Shares/sfold/sfold2 -vk -u einstein:relativity
```
## Expected behavior
As einstein folder `Shares/sfold/sfold2/sfold3` should not exist and `Shares/sfold/sfold2/new2` should exist 

## Actual behavior
As einstein folder `Shares/sfold/sfold2/sfold3` exists and `Shares/sfold/sfold2/new2` doesn't exists

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0 and oC10 version 10.8
@dpakach are you sure that the expected behavior is correct?
have the same behaviors:

Directory structure OC10:

- all files
  - sfold
    - sfold2
      - sfold3
      - new
        - new2

Directory structure oCIS:

- all files
  - Shares
    - sfold
      - sfold2
        - sfold3
        - new
          - new2

**Comment by dpakach** [comment]
@ScharfViktor yes, the expected behavior is correct. 
I just rechecked it and seems like it has been fixed now.
I'm closing this issue.
