### ISSUE TITLE
config.json should be protected if user is not allowed to view it.

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#2184]
## Is your feature request related to a problem? Please describe.
associated https://github.com/owncloud/web/issues/4007, in a nutshell the config.json need to be protected.

## Describe the solution you'd like
Protect the file and make it possible to ship a per user config.json 

## Describe alternatives you've considered
-

## Additional context
-

**Comment by wkloucek** [comment]
I don't get it how that should work. Web needs to load the openIDConnect information from the config.json BEFORE authenticating!? How can we then serve this file ONLY for authenticated users?

```json
{
   "server":"https://ocis.ocis-traefik.latest.owncloud.works",
   "theme":"owncloud",
   "version":"0.1.0",
   "openIdConnect":{
      "metadata_url":"https://ocis.ocis-traefik.latest.owncloud.works/.well-known/openid-configuration",
      "authority":"https://ocis.ocis-traefik.latest.owncloud.works",
      "client_id":"web",
      "response_type":"code",
      "scope":"openid profile email"
   },
   "apps":[
      "files",
      "media-viewer"
   ],
   "external_apps":[
      {
         "id":"settings",
         "path":"/settings.js"
      },
      {
         "id":"accounts",
         "path":"/accounts.js"
      }
   ],
   "options":{
      "hideSearchBar":true
   }
}
```
(taken from https://ocis.ocis-traefik.latest.owncloud.works/config.json)

**Comment by wkloucek** [comment]
@fschade @kulmann is this still valid? Please also see my concerns above.

**Comment by kulmann** [comment]
I still like the idea, but we would need to split the config into a global (public) config and an individual (per user, authenticated) config. Not relevant right now. Will become relevant later this year I think.

**Comment by wkloucek** [comment]
> I still like the idea, but we would need to split the config into a global (public) config and an individual (per user, authenticated) config. Not relevant right now. Will become relevant later this year I think.

Sounds reasonable. I will close this issue then, since there is nothing to do right now and we already have https://github.com/owncloud/web/issues/4007 in place.
