### ISSUE TITLE
[QA] add test for folder with dot in its name

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2193]
## Describe
- Add  tests for conflicting folder describe [here](https://github.com/owncloud/ocis/issues/1216#issuecomment-766572181) 

## Motivation & Context
- https://github.com/owncloud/ocis/issues/1216. This issue is closed as the bug does not exists now but tests would be nice for this kind of behaviour so that we can catch if it fails afterwards

**Comment by swoichha** [comment]
@sakshamgurung is working on this
