### ISSUE TITLE
Fix "error when reading settings values from file system" logs in settings UI tests

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#2208]
## Describe the bug

Errors/warnings in settings UI tests

## Steps to reproduce

1. Run settings UI tests locally or check e.g. https://drone.owncloud.com/owncloud/ocis/5569/54/7
2. See `Error while reading the settings values from file system... `

## Expected behavior
No error messages

## Actual behavior
Lots of `Error while reading the settings values from file system... ` in the logs

**Comment by dpakach** [comment]
there is code to restore the settings of the user after running the tests because deleting the user would not do that before, but looks like that is fixed now and is not required anymore
