### ISSUE TITLE
Empy OCS response for a share create request using a disabled user

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2212]
## Steps to reproduce

1. have a test user `uu1`
2. create a file `test.txt` using user `uu1`
3. disable user `uu1` using `admin`
4. try to create a share using user `uu1`
    ```sh
    curl -k -u test: test https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d path=test.txt -d shareWith=admin -d shareType=0 -v             
    ```

## Expected behavior
with OC10 Backend:
```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>User disabled</message>
 </meta>
 <data/>
</ocs>
```

## Actual behavior
with OCIS backend
<pre><font color="#FF0000">❯</font> curl -k -u test:test https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d path=test.txt -d shareWith=admin -d shareType=0 -v                  
*   Trying 127.0.0.1:9200...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=Acme Corp; CN=OCIS
*  start date: Jun 22 08:14:25 2021 GMT
*  expire date: Jun 22 08:14:25 2022 GMT
*  issuer: O=Acme Corp; CN=OCIS
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user &apos;test&apos;
&gt; POST /ocs/v1.php/apps/files_sharing/api/v1/shares HTTP/1.1
&gt; Host: localhost:9200
&gt; Authorization: Basic dGVzdDp0ZXN0
&gt; User-Agent: curl/7.68.0
&gt; Accept: */*
&gt; Content-Length: 41
&gt; Content-Type: application/x-www-form-urlencoded
&gt; 
* upload completely sent off: 41 out of 41 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
&lt; HTTP/1.1 401 Unauthorized
&lt; Date: Thu, 24 Jun 2021 10:12:58 GMT
&lt; Content-Length: 0
&lt; 
* Connection #0 to host localhost left intact
</pre>
## Setup

Please describe how you started the server and provide a list of relevant environment variables.
```console
export OCIS_URL=https://localhost:9200
export STORAGE_HOME_DRIVER=$DRIVER
export STORAGE_USERS_DRIVER=$DRIVER
export STORAGE_DRIVER_OCIS_ROOT=/tmp/ocis/storage/users
export STORAGE_DRIVER_LOCAL_ROOT=/tmp/ocis/local/root
export STORAGE_METADATA_ROOT=/tmp/ocis/metadata
export STORAGE_DRIVER_OWNCLOUD_DATADIR=/tmp/ocis/owncloud/data
export STORAGE_HOME_DATA_SERVER_URL=http://localhost:9155/data
export STORAGE_USERS_DATA_SERVER_URL=http://localhost:9158/data
export STORAGE_SHARING_USER_JSON_FILE=/tmp/ocis/shares.json
export PROXY_ENABLE_BASIC_AUTH=True
export WEB_UI_CONFIG=$HOME/www/ocConfigs/ocis-config/ocis-config.json
export IDP_IDENTIFIER_REGISTRATION_CONF=$HOME/www/ocConfigs/ocis-config/idp.yml
export OCIS_LOG_LEVEL="error"
export SETTINGS_DATA_PATH=/tmp/ocis/settings

if [ $DRIVER == "owncloud" ]
then
	export STORAGE_DRIVER_OWNCLOUD_REDIS_ADDR=localhost:6379
else
	export STORAGE_DRIVER_OWNCLOUD_REDIS_ADDR=
fi
```

<details>
<p>

<pre>  <font color="#0087AF">  </font><font color="#00AFFF"><b>~</b></font><font color="#0087AF">/www/</font><font color="#00AFFF"><b>ocConfigs</b></font><font color="#0087AF"> </font><font color="#5FD700">   master </font><font color="#D7AF00">!1 </font><font color="#5FD700">❯</font> curl -k -u admin:admin https://localhost:9200/status.php | jq      <font color="#5F8787">  15:57:58</font>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   197  100   197    0     0   1358      0 --:--:-- --:--:-- --:--:--  1349
<font color="#4D55F5"><b>{</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;installed&quot;</b></font><font color="#4D55F5"><b>: </b></font>true<font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;maintenance&quot;</b></font><font color="#4D55F5"><b>: </b></font>false<font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;needsDbUpgrade&quot;</b></font><font color="#4D55F5"><b>: </b></font>false<font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;version&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;10.0.9.5&quot;</font><font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;versionstring&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;10.0.9&quot;</font><font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;edition&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;community&quot;</font><font color="#4D55F5"><b>,</b></font>
<font color="#4D55F5"><b>  </b></font><font color="#839496"><b>&quot;productname&quot;</b></font><font color="#4D55F5"><b>: </b></font><font color="#659900">&quot;ownCloud&quot;</font>
<font color="#4D55F5"><b>}</b></font>
</pre>

</p>
</details>

**Comment by micbar** [comment]
OCS is deprecated.
