### ISSUE TITLE
share-permissions is not updated for receiver after sharer updates share

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2213]
## Describe the bug

While using `owncloud` driver, share permission update does not reflect for sharee

## Steps to reproduce

1. create two users `uu1` & `uu2`
2. upload a file `tmp.txt` using user `uu1`
3. share file `tmp.txt` with user `uu2`
4. accept incoming share using user `uu2`
5. update share permission  to `update, read` using user `uu1`

## Expected behavior
with ocis storage driver:
<pre><font color="#5FD700">❯</font> curl -k -u uu2:uu2 -X PROPFIND https://localhost:9200/remote.php/webdav/Shares/tmp.txt -d &apos;&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;d:propfind
      xmlns:d=&quot;DAV:&quot;
      xmlns:oc=&quot;http://owncloud.org/ns&quot;
      xmlns:ocs=&quot;http://open-collaboration-services.org/ns&quot;
&gt;
      &lt;d:prop&gt;&lt;ocs:share-permissions/&gt;&lt;/d:prop&gt;
&lt;/d:propfind&gt;
&apos; | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   613  100   394  100   219  12312   6843 --:--:-- --:--:-- --:--:-- 19156
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:multistatus xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot; xmlns:oc=&quot;http://owncloud.org/ns&quot;&gt;
  &lt;d:response&gt;
    &lt;d:href&gt;/remote.php/webdav/Shares/tmp.txt&lt;/d:href&gt;
    &lt;d:propstat&gt;
      &lt;d:prop&gt;
        &lt;share-permissions xmlns=&quot;http://open-collaboration-services.org/ns&quot;&gt;3&lt;/share-permissions&gt;
      &lt;/d:prop&gt;
      &lt;d:status&gt;HTTP/1.1 200 OK&lt;/d:status&gt;
    &lt;/d:propstat&gt;
  &lt;/d:response&gt;
&lt;/d:multistatus&gt;
</pre>

## Actual behavior
<pre><font color="#FF0000">❯</font> curl -k -u uu2:uu2 -X PROPFIND https://localhost:9200/remote.php/webdav/Shares/tmp.txt -d &apos;&lt;?xml version=&quot;1.0&quot;?&gt;            
&lt;d:propfind
      xmlns:d=&quot;DAV:&quot;
      xmlns:oc=&quot;http://owncloud.org/ns&quot;
      xmlns:ocs=&quot;http://open-collaboration-services.org/ns&quot;
&gt;
      &lt;d:prop&gt;&lt;ocs:share-permissions/&gt;&lt;/d:prop&gt;
&lt;/d:propfind&gt;
&apos; | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614  100   395  100   219  11617   6441 --:--:-- --:--:-- --:--:-- 18058
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:multistatus xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot; xmlns:oc=&quot;http://owncloud.org/ns&quot;&gt;
  &lt;d:response&gt;
    &lt;d:href&gt;/remote.php/webdav/Shares/tmp.txt&lt;/d:href&gt;
    &lt;d:propstat&gt;
      &lt;d:prop&gt;
        &lt;share-permissions xmlns=&quot;http://open-collaboration-services.org/ns&quot;&gt;19&lt;/share-permissions&gt;
      &lt;/d:prop&gt;
      &lt;d:status&gt;HTTP/1.1 200 OK&lt;/d:status&gt;
    &lt;/d:propstat&gt;
  &lt;/d:response&gt;
&lt;/d:multistatus&gt;
</pre>

## Setup

Please describe how you started the server and provide a list of relevant environment variables.
`storage driver`: `owncloud`

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by ScharfViktor** [comment]
not relevant after deleting resharing feature
