### ISSUE TITLE
sharing the shares folder to users exits with different status code than in oc10 backend

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2215]
## Describe the bug

Sharing the shares folder to users exits with a different status than in `oc10` backend.
Response OCS status code for the different versions are also different.

## Steps to reproduce

1. create users `uu1`, `uu2` and `uu3`
2. upload a file `tmp.txt` using user `uu1`
3. share file `tmp.txt` with user `uu2` using user `uu1`
4. accept incoming share using user `uu2`
5. share folder `Shares` with user `uu3`

## Expected behavior
In Oc10 backend:
Request fails with
- OCS status code: `403`
- OCS status message: `Path contains files shared with you`

## Actual behavior
Request fails with
- with ocs-api version: `1`
    - OCS status code: `996`
- with ocs-api version: `2`
    - OCS status code: `500`

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console

export OCIS_URL=https://localhost:9200
export STORAGE_HOME_DRIVER=$DRIVER
export STORAGE_USERS_DRIVER=$DRIVER
export STORAGE_DRIVER_OCIS_ROOT=/tmp/ocis/storage/users
export STORAGE_DRIVER_LOCAL_ROOT=/tmp/ocis/local/root
export STORAGE_METADATA_ROOT=/tmp/ocis/metadata
export STORAGE_DRIVER_OWNCLOUD_DATADIR=/tmp/ocis/owncloud/data
export STORAGE_HOME_DATA_SERVER_URL=http://localhost:9155/data
export STORAGE_USERS_DATA_SERVER_URL=http://localhost:9158/data
export STORAGE_SHARING_USER_JSON_FILE=/tmp/ocis/shares.json
export PROXY_ENABLE_BASIC_AUTH=True
export WEB_UI_CONFIG=$HOME/www/ocConfigs/ocis-config/ocis-config.json
export IDP_IDENTIFIER_REGISTRATION_CONF=$HOME/www/ocConfigs/ocis-config/idp.yml
export OCIS_LOG_LEVEL="error"
export SETTINGS_DATA_PATH=/tmp/ocis/settings

if [ $DRIVER == "owncloud" ]
then
	export STORAGE_DRIVER_OWNCLOUD_REDIS_ADDR=localhost:6379
else
	export STORAGE_DRIVER_OWNCLOUD_REDIS_ADDR=
fi

```

</p>
</details>

**Comment by SwikritiT** [comment]
The behavior has changed a little bit now in OCIS
it gives `404` OCS status code in both versions with message `No share permission`
And gives `404` HTTP status in ocs-api version 2

in oc10 the status is `403` for all with message `Path contains files shared with you`

**Comment by pascalwengerter** [comment]
@kiranparajuli589 @SwikritiT can this be closed since the shares jail has been implemented?

**Comment by kiranparajuli589** [comment]
This topic is no longer relevant. Closing.

**Comment by kiranparajuli589** [comment]
Reopening as the behavior is still the same. The steps are as described in the scenrio here [apiShareManagementBasicToShares/createShareToSharesFolder.feature:714](https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature#L714)
 While sharing the `Shares` folder using **new** or **old** DAV version, **oCIS** server responds with status code `404` and message `No share permission`.

if this is the expected feature we've to adjust the tests.

**Comment by SwikritiT** [comment]
We still have the test related to this issue in expected to fail
https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature

The test is tagged to wrong issue https://github.com/owncloud/ocis/blob/c8f8bc55e22597bc3d53b63b2f38f345b4814b07/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L645

Sharing the `Shares` folder in OC10 now responds
```bash
curl --user swikriti:0123456789 -v \
     "http://host.docker.internal:8080/ocs/v1.php/apps/files_sharing/api/v1/shares" \
     --data 'path=/Shares' \
     --data 'shareType=0'  \
     --data 'permissions=31' \
     --data 'shareWith=admin'
```
```bash
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>You are not allowed to share /swikriti/files/Shares</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```


While in ocis 
```bash
curl --user einstein:relativity -vk \
     "https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares" \
     --data 'path=/Shares' \
     --data 'shareType=0'  \
     --data 'permissions=31' \
     --data 'shareWith=marie'
```
```bash
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<ocs><meta><status>error</status><statuscode>404</statuscode><message>No share permission</message></meta></ocs>% 
```

Both return with `404` but the message is different. The text expectation is `400` , what is the expection here? if `404` is okay then tests need adaptaion, if not is `400` the expected status code? Or we do not care about `new` or `old` DAV versions.  The error message also is not appropriate in ocis. 

cc @ScharfViktor @micbar

**Comment by phil-davis** [comment]
The oC10 core test scenario is now here:
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature#L728C3-L728C3

That expects OCS status code 403. And that is passing in oC10 core. So I am a bit surprised that the example `curl` command to oC10 is responding with `404`

**Comment by SwikritiT** [comment]
There's this test here
https://github.com/owncloud/core/blob/684cea2b152e7f18fd8b5e228a65a3197bcdefb7/tests/acceptance/features/apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature#L10

That works according to the curl request
Maybe the status code is different depending on if the `Shares` folder is empty or has some resources

**Comment by SwikritiT** [comment]
yes if the `Shares` has resources then the curl responds with following in OC10
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Path contains files shared with you</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>

```

However, the behaviour is the same for oCIS

**Comment by phil-davis** [comment]
OK - then @micbar @ScharfViktor or whoever need to decide what are the expected/required responses in these situations.
After that, we can adjust the tests to match the requirements. An then a developer can adjust code to make the tests pass (if neded)

**Comment by ScharfViktor** [comment]
Re-sharing has been deleted so now user hasn't permission to share folder `Shares` -> 403 with `No share permission` message
