### ISSUE TITLE
Deleting a received folder moves it to trashbin

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#2217]
## Describe the bug
When a received folder is deleted, it is moved in to trashbin of the receiver.

## Steps to reproduce

1. Create folder `shared` as user `Alice`
2. Upload a file to `shared/shared_file.txt`
3. Share folder `shared` with user `Brian`
4. As Brian, accept the share `shared` offered by user `Alice`
5. As Brian, rename folder `Shared/shared` to `Shares/renamed_shared`
6. As user Brian, delete folder `Shares/renamed_shared`

## Expected behavior
The deleted folder `Shares/renamed_shared` should not exist in the trashbin

## Actual behavior
The deleted folder `Shares/renamed_shared` exists in the trashbin
## Setup

<details>
<p>

```console
STORAGE=ocis-storage
```

</p>
</details>

**Comment by jasson99** [comment]
![Screenshot from 2021-06-25 13-33-49](https://user-images.githubusercontent.com/40829116/123389868-0c2f6c80-d5ba-11eb-9e05-bb1570041af1.png)

**Comment by phil-davis** [comment]
AFAIK this is the behavior in oC10 and the existing "traditional" webUI.
I think this is the correct behavior.
Comments please...

**Comment by phil-davis** [comment]
> AFAIK this is the behavior in oC10 and the existing "traditional" webUI.
> I think this is the correct behavior.
> Comments please...

My mistake - this is about the share receiver "deleting" the actual incoming shared folder. That action is actually an "unshare". Nothing should be deleted - Alice still has all her files, Brian can go to "Shared with you" and accept the share again, and will also regain access to the files again.

**Comment by ScharfViktor** [comment]
it is fixed, the behavior is as expected
re-tested ocis version 1.12

@jasson99 I suggest to close it
