### ISSUE TITLE
restoring a file to an already existing path does not override the file

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2221]
## Describe the bug

Restoring a file to an already existing path does not override the file.
Happens only with `owncloud` storage driver.

## Steps to reproduce

1. create a user `uu1`
2. upload a file `/textfile.txt` with content `file to delete`
3. create a folder `/Parent`
4. upload a file `textfile.txt` with content `parent file content` inside `/Parent` folder
5. delete the file `/textfile.txt`
6. restore the last deleted file with original path `/textfile.txt` to `/Parent/textfile.txt`

## Expected behavior
- restoring a file to an already existing path should override the file
- content of file `/Parent/textfile.txt` for user `uu1` should be `file to delete`
## Actual behavior
- The downloaded content was expected to be `file to delete`, but actually is `parent file content`. HTTP status was 200

## Setup

The test is only failing for `owncloud` storage driver

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=latest
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

## Additional context
Drone link: https://drone.owncloud.com/owncloud/ocis/5644/37/7
Tests are included here
https://github.com/owncloud/core/blob/57dbfd8b9982740e8cbdb2a24060aee326d2b15d/tests/acceptance/features/apiTrashbin/trashbinRestore.feature#L95-L112

**Comment by phil-davis** [comment]
Note: the scenario is intermittent. Sometimes the file has the restored content, sometimes it still has the original content. But the HTTP status of the trashbin-restore API call is always the same - `204`. So the caller cannot know from the status if the restore was successful.

**Comment by phil-davis** [comment]
The test scenarios were removed from expected-failures in PR #2227 
The problem was fixed by cs3org/reva PR https://github.com/cs3org/reva/pull/1833
