### ISSUE TITLE
Bring back logtostderr for swagger in Makefiles

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#223]
swagger does support `logtostderr=true` but we removed it 

`swagger_out=logtostderr=true:pkg/proto/v0` is fine

**Comment by PVince81** [comment]
would be good to add clearer instructions and context about what needs to be done

**Comment by PVince81** [comment]
@jfd any more instructions ? seems to require too much insider knowledge to get started as "good first issue"

**Comment by IljaN** [comment]
I assume grepping trough all ocis-repos and re-adding swagger_out=logtostderr=true...

**Comment by IljaN** [comment]
Basically a revert of those changes: https://github.com/owncloud/ocis-konnectd/commit/c6c28c49b85cb742feac6de0c36ea8bf4c9698c5#diff-b67911656ef5d18c4ae36cb6741b7965R196

**Comment by refs** [comment]
staled. more description needed.
