### ISSUE TITLE
Viewer cannot share a shared resource

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2260]
## Describe the bug

ocis roles are not similar to oc10

## Steps to reproduce

1. create two users `uu1` and `uu2`
2. upload a file `lorem.txt` using user `uu1`
3. share `lorem.txt` with use `uu2` using user `uu1`
4. login as user `uu2`
5. accept the latest incoming share from user `uu1` for `lorem.txt`
6. try to share `lorem.txt` using user `uu2`

## Expected behavior
with `oc10` backend
- share is created with permissions: `17`
- `viewer` can share the shared resource with other users/groups

## Actual behavior
with `ocis` backend,
- share is created with permissions `1`
- `viewer` do not have permission to share
- with `editor` role, `editor` can share the shared resource

## Screenshots
Role Dropdown for ocis frontend:
![Screenshot from 2021-07-05 14-44-47](https://user-images.githubusercontent.com/39373750/124447934-9a1d0b80-dda1-11eb-852b-d4b4dc5e64bf.png)
Role Dropdown for oc10-web frontend:
![Screenshot from 2021-07-05 14-44-59](https://user-images.githubusercontent.com/39373750/124447974-a739fa80-dda1-11eb-8e99-4931ed05b836.png)

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=git
BRANCH=latest master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by kiranparajuli589** [comment]
Also, with `ocis` backend:
#### when a share is created with the following params: 
```
'path' => '/lorem.txt',
'shareWith' => 'Carol',
'shareType' => '0',
'permissions' => '31'
```
#### share is created with permission 19
<details>

<summary>Response</summary>

<p>

```console
{
  ocs: {
    meta: { status: 'ok', statuscode: 200, message: 'OK' },
    data: {
      id: 'b2b8799f-d554-44f6-af7c-1b641b92166b',
      share_type: 0,
      uid_owner: 'Alice',
      displayname_owner: 'Alice Hansen',
      additional_info_owner: 'alice@example.org',
      permissions: 19,
      stime: 1625477023,
      parent: '',
      expiration: '',
      token: '',
      uid_file_owner: 'Alice',
      displayname_file_owner: 'Alice Hansen',
      additional_info_file_owner: 'alice@example.org',
      state: 0,
      path: '/lorem.txt',
      item_type: 'file',
      mimetype: 'text/plain',
      storage_id: '1284d238-aa92-42ce-bdc4-0b0000009157!0586653e-7778-43c0-a179-2d70f9835d62',
      storage: 0,
      item_source: 'MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjA1ODY2NTNlLTc3NzgtNDNjMC1hMTc5LTJkNzBmOTgzNWQ2Mg==',
      file_source: 'MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjA1ODY2NTNlLTc3NzgtNDNjMC1hMTc5LTJkNzBmOTgzNWQ2Mg==',
      file_parent: '',
      file_target: '/lorem.txt',
      share_with: 'Carol',
      share_with_displayname: 'Carol King',
      share_with_additional_info: 'carol@example.org',
      mail_send: 0,
      name: ''
    }
  }
}

```

</p>
</details>

**Comment by phil-davis** [comment]
> share is created with permission 19

That is what happens in oC10: https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature#L83

"# Ask for full permissions. You get share plus read plus update. create and delete do not apply to shares of a file"

**Comment by kiranparajuli589** [comment]
`UPDATE`
At the date of the comment, following the steps from the issue description:
- `uu2` can share the received share with other users/groups
- share is created with permission `17` (now similar to oc10)

**Comment by grgprarup** [comment]
This issue is blocked for now due to other related issues of resharing shared resources on the web with `OCIS` backend. https://github.com/owncloud/web/issues/7179
This https://github.com/owncloud/web/pull/7086 is the PR related to resharing on web+ocis.

**Comment by SwikritiT** [comment]
Resharing is now available in ocis and it can be configured in UI through variable `FRONTEND_ENABLE_RESHARING: "true"`. Depending on if this variable is set or not the `share` permission is available in UI so closing. There will be a follow-up PR to remove the linked tests from expected failure.

**Comment by SwikritiT** [comment]
Follow-up PR here: https://github.com/owncloud/web/pull/7246
