### ISSUE TITLE
Docs for setting up dev env with branches from other services/repos

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#227]
Here are my notes to add docs about setting up dev env with other branches:

The example focusses on checking out a specific PR for a change in the reva repo:

1. Use the README info to setup the basic ocis dev env: https://github.com/owncloud/ocis/blob/master/README.md
1. Clone the reva repo 'git clone https://github.com/cs3org/reva.git`
1. Install the [hub command](https://hub.github.com/) to checkout PRs from forks
1. In the "reva" repo, checkout the PR for ocdav which is https://github.com/cs3org/reva/pull/674, using the command: `hub pr checkout 674`
1. In the "ocis" checkout, edit "go.mod" and **append** the following line:
```
replace github.com/cs3org/reva => ../reva
```
the path "../reva" is the path to your reva checkout
(this will replace the reva library "deep replace" as used by other deps like ocis-reva)

1. then in the "ocis" checkout, run the compilation always with `make clean build` (don't forget the clean)
1. then run the ocis server with: `bin/ocis server`
1. test that you can connect with curl: `curl -u einstein:relativity -X PROPFIND -k https://localhost:9200/remote.php/webdav/ | xmllint --format -`

**Comment by PVince81** [comment]
- [ ] TODO: add link to the Phoenix docs ? https://owncloud.github.io/clients/web/backend-ocis/

**Comment by refs** [comment]
The getting started section on the docs should cover this concerns 👍 (https://owncloud.github.io/ocis/development/getting-started/)
