### ISSUE TITLE
Clarify how storage providers can be made highly available

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2279]
To make a storage provider highly available we made the oCIS driver map all cs3 operations to storage native  operations. While this ensures consistency when using the decomposedfs it does require deconstructing the filesystem. Currently, the ocis driver and the s3ng driver use the decomposedfs. Both drivers stone metadata in the filesystem. The oCIS driver stores blobs on disk, whereas s3ng stores them on S3 (tested on ceph).

The metadata on the filesystem requires a distributed filesystem if more than one storage provider should be able to access the same metadata, aka high availability. Distributed filesystems are ... finicky, and need to be tuned to the workload.

Generally speaking there are two paths forward:
- Rely on the filesystem for everything. AFAICT only eos, cephfs and gifs are of relevance
- don't bother with redundancy and rely on the orchestrator to start a storage provider on demand. We could store metadata in SQLite / [litestream](https://litestream.io/), blobs on S3. Startup of a storage provider for this is done in seconds. Which is tolerable for all scenarios I can currently think of. It should feel like the initial login takes a moment longer. When the operator detects errors in the transport layer we can kill the old instance and spawn a new one. Which makes more sense for a microservice architecture.

What about extremely large storage spaces? We could recommend eos, cephfs or gpfs for those scenarios. In order to migrate storage spaces between these systems we need to decouple the space and node id's from the underlying storage though. This can be done with a key value store that is used to look up nodeid to parentid mapping (do not use a nodeid to path mapping as this requires updating the path of all children when renaming a folder).

The nodeid to parentid lookup is part of the decomposedfs. We should use the store interface from go micro so we can swap the implementation.

We should add this to an ADR...

**Comment by kobergj** [comment]
I dont believe anything will happen here.
