### ISSUE TITLE
could not create symlink for 'personal' space

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2290]
## Describe the bug

While using oCIS 1.9.0-RC1 the log ouptut will be spammed with following message:
```
could not create symlink for 'personal' space 13a483b9-5b6c-4dec-a6aa-90eda42327e0, symlink ../../nodes/13a483b9-5b6c-4dec-a6aa-90eda42327e0 /var/tmp/ocis/storage/users/spaces/personal/13a483b9-5b6c-4dec-a6aa-90eda42327e0: file exists
```

## Steps to reproduce

1. run oCIS 1.9.0-RC1 and move to all files and watch the server log

## Expected behavior
No error logs

## Actual behavior
A lot of error logs with the message above.

even when using the logger printing on a file, the terminal will be spammed with the print message

`OCIS_LOG_FILE=/Users/test/logs/test.log ocis/bin/ocis server`

![Clipboard - July 13, 2021 3_34 PM](https://user-images.githubusercontent.com/4378513/125464488-41dcd08f-8240-4a1a-a2d5-57e1046127b5.png)

**Comment by micbar** [comment]
ok decision with @butonic @dragotin 

Not a release blocker.

only affects the decomposedfs.

**Comment by wkloucek** [comment]
fixed in https://github.com/cs3org/reva/pull/1992
