### ISSUE TITLE
User gets an error when accepts a file

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#2291]
## Describe the bug
The error is floating. 
<img width="1384" alt="Screen Shot 2021-07-13 at 11 41 24 AM" src="https://user-images.githubusercontent.com/84779829/125435425-f726cc59-f331-4345-b8f5-c2823694e6c4.png">

## Steps to reproduce

1. User1 share file or folder to User2
2. User2 clicks file "Accept" and gets error {"ocs":{"meta":{"status":"error","statuscode":996,"message":"grpc update received share request failed"}}}

## Expected behavior
The user can see a second file in the folder Shared

## Actual behavior
Second file is in status "Accepted" but user can't see file n the folder Shared
## Setup

```console
OCIS_VERSION=v1.9.0 reachable at https://localhost:9200
BRANCH=v1.9.0-rc1
```

**Comment by wkloucek** [comment]
@ScharfViktor I can not reproduce this bug. Accepting shares works fine for me

**Comment by kulmann** [comment]
Accepting previously declined shares is broken. Already tracked in https://github.com/owncloud/ocis/issues/2011
I think this is a duplicate of #2011 - if yes, then please close this one.

**Comment by ScharfViktor** [comment]
Yes, this is duplicate of [2130](https://github.com/owncloud/ocis/issues/2130).
