### ISSUE TITLE
Ocis Runtime

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#231]
## What?

The [ocis runtime (at the moment of this writing)](https://github.com/owncloud/ocis/blob/5ed1bc08a24c6b707a5266ebf85151429277a371/pkg/micro/runtime/runtime.go) uses the [micro/go-micro](https://github.com/micro/go-micro/tree/master/runtime) runtime to initialize ocis services. There are some fundamental issues that were overlooked when implementing the initial solution:

- The supervisor process always restarts the service on any system `SIGINT` or `SIGTERM`, making it a bad candidate for development hot services reload.

- Life cycle methods (run, kill, ps...) are not really working, since ocis extensions are not really children of a [micro runtime service](https://github.com/micro/micro/tree/master/runtime); or in other words, they were not launched using the micro runtime command. This is because the micro runtime runs services from sources, and that brings a whole set of problems such as: a host connected to the internet to fetch source files (since the micro runtime service builds and runs services this way).

## Current Solution

As it can be seen, the current approach emulates pretty much that of micro/go-micro. The important bit is [this set of lines](https://github.com/owncloud/ocis/blob/5ed1bc08a24c6b707a5266ebf85151429277a371/pkg/micro/runtime/runtime.go#L117-L130):

```golang
for _, s := range r.services {
	args := []string{os.Args[0]}

	args = append(args, s.Name)
	gorunArgs := []gorun.CreateOption{
		gorun.WithCommand(args...),
		gorun.WithEnv(env),
		gorun.WithOutput(os.Stdout),
	}

	go (*r.R).Create(s, gorunArgs...)
}
```

While this approach works, it has the aforementioned drawbacks. It also prevent us to have cli flags on the spawned processes, making it tricky to modify behavior except for environment flags.

### Using a supervisor

Golang's approach to dealing with daemons is, well, not to. They recommend instead to use a proper supervisor like systemd, upstart, daemontools... etc ([src](https://forum.golangbridge.org/t/daemon-process-in-golang/5542/5))

### Runtime Service

Having our very own runtime service + cli interfacing this service, so we can send messages that internally translate into RPC or REST calls. So for instance:

```console
$ ocis runtime stop phoenix // does a RPC request to the runtime and sends a SIGKILL / SIGTERM to the phoenix process
```

This entails a whole new realm of problems, for instance, the target process might (and probably won't) be running in the same machine.

### Writing our own supervisor

I haven't dig this option deeper, but I got a ["working" prototype here](https://gist.github.com/refs/b2161859f3cf8900c6e82b3b79d0a27c). This piece of code can arbitrarily run any ocis extension, it will run in the foreground, but in a different session it can be invoked again, sending messages to the children processes.

**Comment by PVince81** [comment]
is this done ? close or open further tickets for later ?

**Comment by refs** [comment]
done on github.com/refs/pman/
