### ISSUE TITLE
Review "local" API acceptance tests in OCIS and reva

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2313]
There are "local" acceptance tests in:
https://github.com/owncloud/ocis/tree/master/tests/acceptance/features

https://github.com/cs3org/reva/tree/master/tests/acceptance/features

Some of those are to demonstrate good expected behavior of things that are not features of the oC10 core API acceptance test suite. That is good - review those just to know that they still seem useful.

Some of them are "bug demo" scenarios that demonstrate existing "bad behavior". Nowadays we have expected-failure files, so we already know if a developer improves behavior and some core API test scenarios start to pass. Maybe we don't need these "bug-demo" scenarios any more. Review them and decide what to do with them.

**Comment by SwikritiT** [comment]
@phil-davis I think we can close this issue now

**Comment by phil-davis** [comment]
Agree - closed
