### ISSUE TITLE
Change the file content of a received share does not work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#2319]
Describe the bug
A test is written that demonstrates the error. The test will work when the bug is fixed https://github.com/owncloud/web/pull/5548

Steps to reproduce

User1 creates file and shares file to User2
User2 accepts file and try to upload file with some name
Or run test: yarn run test:acceptance:ocis tests/acceptance/features/webUIUserJourney/journey1.feature:29

Expected behavior
Created new version

Actual behavior
403 Forbinden

<img width="1433" alt="126222608-93d08ac5-61e4-4a10-ada2-d0444a085ecf" src="https://user-images.githubusercontent.com/84779829/126740773-a6121524-7ea8-46f3-bcd9-10be5164614b.png">

Setup
Please describe how you started the server and provide a list of relevant environment variables.

OCIS_VERSION=v1.9.0 reachable at https://localhost:9200
BRANCH=v1.9.0-rc1

**Comment by phil-davis** [comment]
Note: issue #2267 reports the same thing for the API. API  test coverage was added in core PR https://github.com/owncloud/core/pull/38944

I expect that this UI problem will be fixed at the same time as the API problem is fixed.
