### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis#235]
When using OCIS, there are two improvements we have identified:

* We would like to configure OCIS will plain simple configuration files apart from environment variables
* OCIS redefines Reva configuration parameters, making it difficult to understand the connection between OCIS config and Reva config (in practical terms means having to look at the code to see how a OCIS config maps to a Reva config), cannot we just use the same ?

**Comment by refs** [comment]
> We would like to configure OCIS will plain simple configuration files apart from environment variables

Each service will pick up default configs from predefined locations (see https://github.com/owncloud/ocis/blob/8fa89f50676d065fc469ccb780037135a29639f4/proxy/pkg/command/root.go#L83-L85)

> OCIS redefines Reva configuration parameters, making it difficult to understand the connection between OCIS config and Reva config (in practical terms means having to look at the code to see how a OCIS config maps to a Reva config), cannot we just use the same?

Agree. Would like not to repeat variables there. Needs some concept. Closing and opening a follow up on the second point.
