### ISSUE TITLE
webUILogin/openidLogin.feature:38 test fails in OCIS master

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2350]
Demonstration PR #2346 
https://drone.owncloud.com/owncloud/ocis/6203/44/6
```
runsh: Total unexpected failed scenarios throughout the test run:
webUILogin/openidLogin.feature:38
```

This is an existing problem in master. Somehow we merged something into `owncloud/ocis` that broke a web test scenario.

Note: ordinary PRs only run the web smokeTest scenarios. So we do not notice if there is a regression where all the core API tests pass, the web smokeTests pass, but some other web test(s) fail. We only ffind this out when someone runs `full-ci`

**Comment by phil-davis** [comment]
Note: the scenario passes every time in `owncloud/web` - see demonstration PR https://github.com/owncloud/web/pull/5622

**Comment by kulmann** [comment]
Fix already is on the web release-4.0.0 branch as @pascalwengerter pointed out. The selector for error messages on the ocis login page changed. Still wondering though how that commitid update for ocis didn't have issues in CI then.

**Comment by phil-davis** [comment]
I don't understand why this fails in the current OCIS master, with the current web-commit-id that CI is using.
It passes in `owncloud/web` current master, with whatever OCIS commit-id is specified there.
So something has been merged to `owncloud/ocis` `master` branch that has broken this - regardless of any pending "release" PRs in `owncloud/web` and `owncloud/ocis`

This highlights the problem that we do not run the full set of web test scenarios for OCIS PRs. We notice "some time later" that there is a problem.

Probably this will get sorted out with the upcoming web and ocis releases. But if there were not releases already in progress, then we would have to investigate separately.

**Comment by phil-davis** [comment]
> Still wondering though how that commitid update for ocis didn't have issues in CI then.

If `full-ci` was not run, then we would not notice that a web test scenario failed.

**Comment by kulmann** [comment]
IMO not running full CI in ocis is fine. This is a special case: we changed UI code that is located in the ocis repo (idp module) but has a test scenario in another repo (web).  This feels weird and shouldn't be a reason against a sparse webUI CI in ocis in general.

Things we could do:
- add snapshot tests for our customized parts of the idp UI (feels meh)
- live with it because it's a rare edge case that we change idp UI 😅
- set up e2e tests for the idp module like we have it for the accounts and settings UIs with their own pipelines
- ...

What do you think @phil-davis ? 🤔

**Comment by phil-davis** [comment]
I vote for "live with it".

There are some elements of the web UI workflow whose source code is not in `owncloud/web`. But tests in `owncloud/web` need to be able to know about those elements in order to traverse the pages to get through real web UI tests. If those elements change in a not-backward-compatible way, then the web test code has to change. That's life.

**Comment by phil-davis** [comment]
This scenario is no longer in expected-failures. It is passing since a while ago.
