### ISSUE TITLE
Add metadata cache and propagation strategy on s3

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#24]
To quickly answer which files changed we need to have an mtime and etag for directories.
for s3 we cannot store matadata for keys that represent directories, because they get lost when adding a key to the prefix ... at least with minio that is the case.
for local storage that supports extended attributes we can store the etag as an extended attribute.  for local and s3 we need to do directory size accounting.

to enable stateless sync mtime, etag and size need to be propagated up the tree. The data needs to be stored in the storage for persistence. A cache on top can then be used to improve query speed.

This is related to being able to set arbitrary properties: https://github.com/owncloud/nexus/issues/28 not all s3 implementations allow metadata (minio does not)

So a storage needs a metadata persistence strategy / implementation? Hm, what is the cs3 api for this? AFAICT it is implicit. When executing PROPFINDS sync with the desktop clients will work if the etag changes ...

What about a propagation strategy? sync? async?
- sync only for litmus?
- async only for owncloud clients?
- what should the default be?
  - when switching to cs3 directly, any clients MUST default to async!

Tagging is modeled as a different service in cs3: https://github.com/cernbox/cs3apis/blob/master/cs3/tag/v0alpha/tag.proto AFAICT it needs an update to use CS3 References instead of filename strings.

As a cache a k/v store like https://github.com/dgraph-io/badger makes sense. Can we split the actual storage metadata from blob storage? That is kind of what is necessary for s3 if we were to use it exclusively, anyway. For now implement in local and s3, then extract common pieces?

**Comment by refs** [comment]
@butonic can this be closed? or should be moved elsewhere? Is it still relevant?

**Comment by dragotin** [comment]
I think it can be closed as it is implemented by @butonic and @aduffeck. Please reopen if I am wrong.
