### ISSUE TITLE
lock breaker groups are not implemented

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2413]
core PR https://github.com/owncloud/core/pull/38222 "Add app config to allow groups of users to be lock breakers" was recently implemented in core oC10.

Of course that is not implemented in oCIS.

Do we tag it as a feature "to be implemented" or "not to be implemented"?

**Comment by phil-davis** [comment]
@pmaier1 ?

**Comment by pmaier1** [comment]
Thanks for opening the ticket. This feature is part of https://github.com/owncloud/ocis/issues/1284 which will be handled via the roadmap. Additionally, I expect that we'll not use group memberships for this but the roles and permissions system in oCIS. I guess this qualifies as "not to be implemented".

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/39120 tags the scenarios `notToImplementOnOCIS`

**Comment by phil-davis** [comment]
The test scenarios are tagged and not run in oCIS. I guess I close this issue, and there will be a "roadmap issue" somewhere that tracks all these kind of "configuration option features".
