### ISSUE TITLE
stringslices with default value cannot be set in config files

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2416]
glauth has the `backend-server` default to `https://demo.owncloud.com/apps/graphapi/v1.0`. Trying to set this in a config file via, eg.:
```toml
[glauth.backend]
servers = ["https://cloud.ocis.test/apps/graphapi/v1.0"]
```
does not work.

The `server.go` file always overwrites the config from the file with the cfg from the context:
```go
			cfg.Backend.Servers = ctx.StringSlice("backend-server")
```

Wrapping it in a check if it was set like this:
```go
			// StringSliceFlag doesn't support Destination
			// UPDATE Destination on string flags supported. Wait for https://github.com/urfave/cli/pull/1078 to get to micro/cli
			if len(ctx.StringSlice("backend-server")) > 0 {
				cfg.Backend.Servers = ctx.StringSlice("backend-server")
			}
```

Still does not fix it because the flag is declared with a default in flagset.go:

```go
		&cli.StringSliceFlag{
			Name:    "backend-server",
			Value:   cli.NewStringSlice("https://demo.owncloud.com/apps/graphapi/v1.0"),
```

I can _fix_ this for the backend-server by defaulting to `""`, but thas needs to be addressed when reworking the configuration.

**Comment by butonic** [comment]
This boolean also cannot be set from a config file:
```
[storage.reva.gateway]
disable_home_creation_on_login = true
DisableHomeCreationOnLogin = true
disablehomecreationonlogin = true
```
`STORAGE_GATEWAY_DISABLE_HOME_CREATION_ON_LOGIN=true` picks it up

**Comment by kobergj** [comment]
To vague and not commented since 3 years. Closing.
