### ISSUE TITLE
Generation of embed.go files from repo root broken

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#2421]
## Describe the bug

`embed.go` files are not updated anymore upon running `make generate` in repo root

## Steps to reproduce

1. Change something in accounts/, settings/ or onlyoffice/ service
2. Run `make generate` in repo root

## Expected behavior
Updated `embed.go` files in version control

## Actual behavior
No updated `embed.go` files in version control

## Quickfix
`cd` into the respective folders and run `make embed.yml` (thanks @C0rby for the hint)

EDIT: Also affects `make generate` inside the web/ directory, discovered it when following the [web release guidelines](https://owncloud.dev/extensions/web/releasing/#updating-ocis-web)

**Comment by wkloucek** [comment]
regression introduced in #2379 by removing `GENERATE ?= $(PACKAGES)`.
fix in #2449
