### ISSUE TITLE
oCIS-wopi example fails with permission error

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#2436]
## Describe the bug

Came across this when working on #2418, should be easy to fix

## Steps to reproduce

1. Follow https://owncloud.dev/ocis/deployment/ocis_wopi/ guide
2. Starting oCIS Docker container fails with `Can't modify config/config.json - permission denied`
3. Disabling line 5&6 in `entrypoint-override.sh` and adding the `WEB_UI_CONFIG: "/config/config.dist.json"` in the docker-compose lets the oCIS Docker container start

## Expected behavior

Guide _just works_

## Actual behavior

Modification needed, no custom domains possible

## Setup

oCIS 1.11.0-rc1

**Comment by pascalwengerter** [comment]
Turns out the same is true for the `ocis hello` as mentioned in the public rocket chat https://talk.owncloud.com/channel/ocis?msg=JXQjAF9YZ5FrgpX9W

**Comment by wkloucek** [comment]
regression introduced in https://github.com/owncloud/ocis/pull/2380 since we don't use root anymore and the file is not writeable by the non-root user. Will have a look :-)
