### ISSUE TITLE
Full ci on tag

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#2439]
## Describe the bug
while tagging today release (1.11.0) the ci only runs partial (https://drone.owncloud.com/owncloud/ocis/6518).
can we alway run full-ci on tagging?

Cc.: @individual-it

**Comment by phil-davis** [comment]
We did this in web issue https://github.com/owncloud/web/issues/5500 PR https://github.com/owncloud/web/pull/5502

Hopefully some similar code changes here will do the job.

**Comment by individual-it** [comment]
CI started after deleting and recreating the tag, see https://drone.owncloud.com/owncloud/ocis/6523

And the build https://drone.owncloud.com/owncloud/ocis/6518 was not even on tag but on push

**Comment by individual-it** [comment]
here the build on tag-creation that was "empty" https://drone.owncloud.com/owncloud/ocis/6516

**Comment by individual-it** [comment]
full CI started on tag here https://drone.owncloud.com/owncloud/ocis/6528
I will close the issue for now, feel free to reopen if that happens again
