### ISSUE TITLE
Breaking change in tracing setup, no more jaeger agent possible

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2453]
## Describe the bug

After #2372 it's not possible anymore to use jaeger agent. oCIS services now want to send traces directly to the jaeger collector. 

This is the respective code path:

https://github.com/owncloud/ocis/blob/d714cdae69beeb91b99282b21ffa180f34b992cc/ocis-pkg/tracing/tracing.go#L27-L31

This is a conflict to our recommendation on https://owncloud.dev/ocis/deployment/monitoring-tracing/ and the monitoring / tracing examples (https://github.com/owncloud-devops/monitoring-tracing-client, https://github.com/owncloud-devops/monitoring-tracing-server).

Especially for our fleet of continuously deployed oCIS examples, we are dependent on jaeger agent, since this supports adding tags:

https://github.com/owncloud-devops/monitoring-tracing-client/blob/176b5d268cd9d125a53dcd93dfd631226463e72a/docker-compose.yml#L53

These tags allow us to filter oCIS instances in our single jaeger instance (https://jaeger.infra.owncloud.works/search) where all oCIS demo instances are reporting to.

## Steps to reproduce

1. start one of our oCIS deployment examples with the monitoring / tracing additions
https://github.com/owncloud/ocis/blob/d714cdae69beeb91b99282b21ffa180f34b992cc/deployments/examples/ocis_traefik/monitoring_tracing/docker-compose-additions.yml#L5-L8
2. start the monitoring / tracing client besides it (https://github.com/owncloud-devops/monitoring-tracing-client/blob/master/docker-compose.yml)

## Expected behavior
oCIS sends traces to the jaeger agent, which forwards them to the jaeger collector and you can see them in the jaeger UI.

## Actual behavior
oCIS says  `2021/08/31 00:21:50 Post "": unsupported protocol scheme ""`

**Comment by wkloucek** [comment]
@micbar @refs is this something for the fastlane or next sprint?

**Comment by refs** [comment]
mea culpa. Fastlane, I'll get to it now, as I believe it should be a quick one. Sorry for the regression, I assumed too much :)

**Comment by wkloucek** [comment]
> mea culpa. Fastlane, I'll get to it now, as I believe it should be a quick one. Sorry for the regression, I assumed too much :)

No worries. Single oCIS deployments may also use the Collector directly, but since we have 10+ extensions / service creating traces, it also may make sense to always use an Agent!?

**Comment by refs** [comment]
> it also may make sense to always use an Agent!?

I think you're right, as we should probably deploy an agent for example as a sidecar process with our services, whereas we would deploy only a collector, as its own service.

I would still keep creating an exporter from a collector endpoint if the config so requires it, but take precedence an agent. Opening a PR soon and we can move the discussion over there. Will link it here when I have it.
