### ISSUE TITLE
Infinite login loop after changing the language

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/ocis#2463]
## Describe the bug

After a user changes the language, relogin with the same user causes an infinite loop. It seems the browser keeps adding additional parameters.
```
https://my.server/?code=PkX-i3ke7xWm4R8GQOIahXkTV7AWh20o&code=7ilYI8HOdw-uz2YdG0ImdI8tJKRYgxfu&code=PvhNKfm-8YPxCC1KBd1gYyI5Y05LfISd&code=h3LDejHbWnVoa18WVYpGUoAhAdxCCNg6&code=5IXI7C1ggwg_o_Vwq3aQsr_YHK6w5NSf&code=4WqQxwUydxwiEvI2wZ7Q5KDXeoNN5RJp&code=0DG2aD0SFlHqsVaU7d7ucgrncshNUfsw&code=sK4sykPk6ZEukFz34wC2wOHalp6sKkgD&code=68WyBuMGO8yFX-sfdx2BXRYXH1vV5dk6&code=s4CLZtK4jGd5Q0Q412yOZfF2wgbqrdq8&code=PfVyTuCoefUrFVhHoPd7ZVUB_V9RpI5z&code=Z-VOiGcMqV7T2spNNPUsvZGXrjov022V&scope=profile%20email%20openid&scope=profile%20email%20openid&scope=openid%20profile%20email&scope=openid%20profile%20email&scope=openid%20profile%20email&scope=email%20openid%20profile&scope=profile%20email%20openid&scope=email%20openid%20profile&scope=openid%20profile%20email&scope=openid%20profile%20email&scope=email%20openid%20profile&scope=openid%20profile%20email&session_state=5e60adfd336a2313916ba00bd613fcc034d1b40aba16ea95a6c68e4dae719695.0jnNK-dDljOy2XzmYlEh3vkSDs0qKJsYfgmK-SNBX-U%3D&session_state=6d4c801a08340e9bcffc8797dbff6fd5e83819314176b3a2b57ca1381d9372be.G1LJ4COpei4IZHvw9Lz_IOopAx2gQM6fgBCR-qcRhYo%3D&session_state=0e00aa729512d539e87a5bcdda2e2d494442b5cb8a205c79b0f330ed16023011.f0A1MRXCcpy2xmKvpkABzjQ2B_7FGSjlFM1Sze5Hc0k%3D&session_state=fb75e72bc379a845678827076658274520abf0e5605a7122ee661d385c220212.eQw54F1H3iukeimaSES0Uz8npu0vznVrrahkisiwLYo%3D&session_state=1c5b0d3ba0a939fbf7a7995b62195ad29c6eb9e79ef006921fc56efef03c3707.mtp0hGcg-LHOU1QioCqPmaz_0Pd_m5ug0T5bQ9gYchc%3D&session_state=156ee88101e730a1ace65c07b9674eb8abff5cb61eddda279fd4fde21ffa3128.v5OZGEBdDs0ow2afKuvOdb6x2DNkXp9ka2nyeNsDWPc%3D&session_state=4cab3129c4b937b74ac5cdd2993ff0001f9d635a46d2794f9f3ef7deb165dfbc.bx5DEZf2foAAdtpy1jZ5reMRWOvnOUfbYBUuwyS8WP0%3D&session_state=e9f084945ebc86960eea45c2ee73550948efdd3b939dd0353015efd630abeba9.9XnE07Jg7CmdyNC6gzBHgHBg4ehXEIeKnUuPWl7I6PU%3D&session_state=bcc23aebbfbbe445c00e93302b0afdd0bdb0a5173b8593c8ff0602ff4b124fa8.xbz0wuXwZHE7qMeTCbsUEPNt-VbWoGBvj1GWKbj7978%3D&session_state=4678edf5a53b207b4733eeb39560e77b524297ea558012250f6fbfdc45b34de3.qNGL5VOAblqeDgcG5_UgB2fHUyKFNl0zA3nbc-U1raI%3D&session_state=f79c5338a2743bc8d07a8915f52334600fce3a272f4f0563e6d3814c1b110a4c.63z7grPPeejTE48wPKcVLVfPBuuSRkmrZzIbVULNRPc%3D&session_state=09c4093e68ed1d329a23d12c79ceb17b343f970d3596abc5e9394fe14f1b8e97.TM4ucG6M-ENNewlxFxj5lr3FbAt6nW7pCwOIyXpUMLY%3D&state=oidc-callback.html&state=0dc0b15390994164a9ab6f96418be0fboidc-callback.html&state=28e6435b4c994aff867c8512e9ab6c7aoidc-callback.html&state=a3432223048e4d9f8de7d24023d680c7oidc-callback.html&state=55deea3c0dea4a6ba5d7e501c09da0cdoidc-callback.html&state=6b30a3faa869452f8e8db5c7796561afoidc-callback.html&state=095437c7cc4d48a8b0f4032219224b65oidc-callback.html&state=cce829732eba41c886b40c5bb7a3e42foidc-callback.html&state=23c666bb4b544c5f90053cfcaee599c6oidc-callback.html&state=aeceb9dcbd514cb9a64c9b2b438cf882oidc-callback.html&state=d1d391ede1bc415fa7206037fbe0b7ccoidc-callback.html&state=b8ff8807a7ca49a2b445600b0745c756oidc-callback.html&state=a8fd194c1b8d4f72833b6b48454be475#/
```

## Steps to reproduce

1. Login as Einstein
2. Go to the settings and change the language (checked with "español" and "galego")
3. Logout
4. Login again with Einstein

## Expected behavior
The user can login normally

## Actual behavior
The browser keeps reloading a blank page

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

Built from "default_language_english" branch via `make build` in the ocis directory.
The server was started normally with `ocis server` without any env variable other than the `OCIS_URL`
<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by jvillafanez** [comment]
Taking into account that it didn't happen 100% of the times, it might be a side effect of the junk accumulated in the browser's local storage.
I haven't been able to reproduce the issue with a browser in incognito mode.

**Comment by wkloucek** [comment]
> Taking into account that it didn't happen 100% of the times, it might be a side effect of the junk accumulated in the browser's local storage. I haven't been able to reproduce the issue with a browser in incognito mode.

If opening ownCloud Web in a new tab also solves the problem, this is a problem with the session storage (only valid for one tab). I had that in https://github.com/owncloud/web/issues/5612.

I also think that I saw the infinite login loop - even without changing the language.

There are also one more tickets with the exact same error: https://github.com/owncloud/ocis/issues/2114

**Comment by jvillafanez** [comment]
I haven't taken a look at the code there, but I guess we're picking the credentials from the browser storage and we're likely picking the wrong ones. I'm not sure if it's possible to show a warning somehow, even if it's only in the browser console, to detect this case

**Comment by kobergj** [comment]
Since there were no comments in the last 3 years, it is likely this was fixed meanwhile.
