### ISSUE TITLE
Don't store config files or resources in the home directory

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#2485]
## Describe the bug
The default location for `PROXY_TRANSPORT_TLS_CERT`, `PROXY_TRANSPORT_TLS_KEY`, `GLAUTH_LDAPS_CERT` and `GLAUTH_LDAPS_KEY` is in the home directory of the user running ocis.

Usually services are run by a service user without a home directory. If that is the case then the default locations won't work and startup fails.
## Steps to reproduce

1. Create a system user `useradd -r ocis`
2. Run oCIS with that user `sudo -u ocis bin/ocis`
3. See that oCIS fails to start

## Expected behavior
A sensible location should be used. Preferably all configuration files and resources should be stored in the same location.

**Comment by pascalwengerter** [comment]
Starting oCIS via docker or systemd makes it a hard requirement to set either `STORAGE_LDAP_CACERT` or `STORAGE_LDAP_INSECURE` env variable for users without home directory. We should prioritize fixing this issue since it causes problems, e.g. in the `web` CI and all the deployment examples

**Comment by kobergj** [comment]
Supposedly fixed.
