### ISSUE TITLE
Add API acceptance tests for `/archiver` endpoint

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2510]
PR https://github.com/cs3org/reva/pull/2066 added a `/download_archive` API endpoint.

PR #2509 exposes the endpoint in oCIS.

Add some acceptance tests that check the endpoint works.

This is an oCIS-reva feature. The test scenarios can be added as a new test suite directly in this oCIS repo. Then we can probably move copy them into `cs3org/reva` as well.

**Comment by individual-it** [comment]
Now also the resources ID are supported in order to specify the content of the archive to download. see https://github.com/cs3org/reva/pull/2100

**Comment by individual-it** [comment]
WIP: #2717

**Comment by individual-it** [comment]
the endpoint name in ocis is `/archiver` not `/download_archiver`

**Comment by individual-it** [comment]
Some tests have been added (see PRs in the list above)
I'm closing this issue now, feel free to reopen if more tests are required. Ideas for more tests would be
- invalid data
- mixed path & ids potential issue: https://github.com/cs3org/reva/pull/2100#issuecomment-966190851
- different permissions on received shares
- etc

CC @micbar @ScharfViktor
