### ISSUE TITLE
enable archive download by resourceid

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2521]
As a follow-up of cs3org/reva#2066
The current implementation only handles path based requests.

For the spaces concept we need to be able to download archives that contain a list of resource ids.

**Comment by jvillafanez** [comment]
I guess the question here is, who's going to convert the resource id to a path?

So far, ocis is mostly routing the request to the archiver service. As such, converting the resource id to a path doesn't seem possible in ocis unless we change the approach.

The alternative is that the archiver handles the resource id by itself, converting it to a path if needed. In this case, ocis shouldn't need any change, but reva.

**Comment by butonic** [comment]
The case I have in mind is when the resourceid comes from a `PROPFIND /dav/spaces/<spaceid></optional/relative/path>`. The references we give to the archiver are opaque to it. It only needs to fetch the resources using references that contain the spaceid and the path. They were introduced with https://github.com/cs3org/reva/pull/1721 and are used whenever accessing a storage space. They can also transport plain paths, so it should be possible to extend the axisting `/archive` implementation with relative references.

**Comment by wkloucek** [comment]
Will be fixed by https://github.com/cs3org/reva/pull/2100

**Comment by kulmann** [comment]
Linked PR is merged, archive download by base64 encoded resourceid now works. Closing here.
