### ISSUE TITLE
archiver capabilities for maximum number of files and size

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2537]
For the archiver, it has a maximum number of files and a maximum size that I think they should be in the capabilities. The client could prevent requests that we know that will fail.

_Originally posted by @jvillafanez in https://github.com/owncloud/ocis/issues/2529#issuecomment-925629371_

**Comment by micbar** [comment]
@prohtex It is not a web implementation, the archives are created on the backend side.

**Comment by prohtex** [comment]
> @prohtex It is not a web implementation, the archives are created on the backend side.

Gotcha, thanks!
