### ISSUE TITLE
oCIS FS: zero size file uploads create a blob entry in upload target

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2609]
## Describe the bug

Upload a zero size file to oCIS running on oCIS FS. 

## Steps to reproduce

1. Upload a zero size file using oC Web
2. Refresh the page

## Expected behavior
You see exactly the file you uploaded

## Actual behavior
You see the file you uploaded and a file with a UUIDv4.

## Setup
oCIS master on e4cc2a5b29bcb1ae9c8a2fec62575c1ff678b5b3, but same behaviour was on oCIS 1.12.0

**Comment by wkloucek** [comment]
oCDAV also has a special case for zero byte uploads
https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocdav/tus.go#L262

**Comment by nikslor** [comment]
Not sure if it's relevant; I think I also see this when using rclone to sync files to oCIS.

![image](https://user-images.githubusercontent.com/1211300/143554614-767516c5-2217-4337-8f00-e4d166b9d842.png)
