### ISSUE TITLE
[TUS] Generate correct Permissions Header 

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#2626]
After a TUS upload, oCIS reply on the last chunk contains a header that delivers the permissions of the file that was just uploaded. The header is called `OC-Perm`.

In the current implementation in `reva/internal/http/services/owncloud/ocdav/tus.go` the permissions are not correctly computed, but only deliver a placeholder.

The permissions need to be correctly computed.

@wkloucek

**Comment by wkloucek** [comment]
@dragotin please review https://github.com/cs3org/reva/pull/2179
