### ISSUE TITLE
shareTypes property of shared resource is empty

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/ocis#2640]
## Describe the bug

`resource.fileInfo[DavProperty.ShareTypes]` returns an empty array in web for shared resources (in owncloud test environment only for public links, in CERNBox for both links and users.)

## Steps to reproduce

1. In web create a public link, the indicator is shown
2. reload the page
3. the indicator is missing

## Expected behavior
Indicators are always shown for resources that are shared with people and via link

## Actual behavior
log of `resource.fileInfo[DavProperty.ShareTypes]` returns an empty array

## Setup

- test in https://ocis.ocis-web.latest.owncloud.works/ --> link indicator not showing up
- locally with ocis-1.13.0 the same
- by CERNBox both link and user share indicators are missing

## Additional context
![0](https://user-images.githubusercontent.com/7430156/137936700-7bdb4bdf-ec21-4217-8a7d-89435b29f1d4.gif)

**Comment by C0rby** [comment]
This PR should fix it for public links: https://github.com/cs3org/reva/pull/2213

**Comment by wkloucek** [comment]
fixed in oCIS 1.16.0-rc1 as described in https://github.com/owncloud/ocis/issues/1038#issuecomment-990711232
