### ISSUE TITLE
Spaces: Icon for space

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/ocis#2661]
## Is your feature request related to a problem? Please describe.
Customisable icons for spaces would increase the discoverability

## Describe the solution you'd like
Each space could report an uri to an image that can be used to make the space visually discoverable.

**Comment by michaelstingl** [comment]
Also default icons should be linked in the Spaces API, even if no individual Space icon was uploaded. Especially to differentiate Home/Personal Space and Shares Space from all the other ones.

**Comment by kulmann** [comment]
Heads up: I heard today that the `.space` folder is not a thing anymore.

**Comment by michaelstingl** [comment]
@micbar said, Spaces cover images already will be exposed via the API (MVP scope). Can be extended with additional icon endpoint. (post MVP)

Open topics:
- Does API contain link to URL or icon cover images/content? (base64 or SVG content preferred)
- Clients should be able to detect icon changes

@micbar could you describe how such a cover image/icon entity with metadata could look like? (open PR)

**Comment by refs** [comment]
https://github.com/owncloud/open-graph-api/pull/9

**Comment by michaelstingl** [comment]
> Also default icons should be linked in the Spaces API, even if no individual Space icon was uploaded. Especially to differentiate Home/Personal Space and Shares Space from all the other ones.
> 
> In the first iteration, this attribute could be hardcoded – no backend logic needed.

Alternative approach for default Space icons uses the `theme.json`:
- https://github.com/owncloud/web/issues/8424

@fmoc @TheOneRing
