### ISSUE TITLE
Download of file inside public link is named after the token

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis#2670]
## Describe the bug

Given a public link like this:
![Screenshot 2021-10-25 at 07 26 13](https://user-images.githubusercontent.com/5175912/138639127-30f19c5b-788a-449e-a788-10d89f7543ad.png)

When I download the file, the downloaded file is named:
`rWAjMExZgbrkhml`, note there is NO extension. 

Such behaviour is terrible from a usability perspective.

I imagine something like this is missing or is wrong:
https://github.com/cernbox/revaold/blob/67b606cb07160c6d937cbe05840aea70d05a30cd/ocproxy/api/api.go#L3547

**Comment by labkode** [comment]
@wkloucek in the video I don't see the downloaded files.
Have you checked they are downloaded with the correct name?

**Comment by wkloucek** [comment]
> @wkloucek in the video I don't see the downloaded files. Have you checked they are downloaded with the correct name?

you can see them in the bottom left corner

**Comment by butonic** [comment]
AFAICT fixed by https://github.com/cs3org/reva/pull/2303
