### ISSUE TITLE
OIDC discovery endpoint returns wrong domain

### ISSUE THREAD

**Issue by NexZhu** [owncloud/ocis#2676]
## Describe the bug

I set up oCIS with Kopano Konnect as the IDP following the oCIS+Keycloak example.

Now, oCIS web works fine: visiting `owncloud.mydomain.com` will redirect me to `konnect.mydomain.com` and I can login with OIDC successfully.

But when trying to connect with desktop client, it will show the login form on `owncloud.mydomain.com` instead of redirecting me to `konnect.mydomain.com`.

After some investigation, I found that my OIDC discovery endpoint `https://owncloud.mydomain.com/.well-known/openid-configuration` is returning oCIS's domain `owncloud.mydomain.com` instead of the IDP's domain `konnect.mydomain.com`:
```json
{
    "issuer": "https://owncloud.mydoamin.com",
    "authorization_endpoint": "https://owncloud.mydoamin.com/signin/v1/identifier/_/authorize",
    "token_endpoint": "https://owncloud.mydoamin.com/konnect/v1/token",
    "userinfo_endpoint": "https://owncloud.mydoamin.com/konnect/v1/userinfo",
    "end_session_endpoint": "https://owncloud.mydoamin.com/signin/v1/identifier/_/endsession",
    "check_session_iframe": "https://owncloud.mydoamin.com/konnect/v1/session/check-session.html",
    "jwks_uri": "https://owncloud.mydoamin.com/konnect/v1/jwks.json",
    ...
}
```

As a comparison, your test server's OIDC discovery endpoint `https://ocis.team.owncloud.works/.well-known/openid-configuration` will return the domin `keycloak.team.owncloud.works`:
```json
{
    "issuer": "https://keycloak.team.owncloud.works/auth/realms/oCIS",
    "authorization_endpoint": "https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/auth",
    "token_endpoint": "https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/token",
    "introspection_endpoint": "https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/token/introspect",
    "userinfo_endpoint": "https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/userinfo",
    "end_session_endpoint": "https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/logout",
    "jwks_uri": "https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/certs",
    ...
}
```

## Steps to reproduce

1. Deploy and configure oCIS+Konnect according to the documentation and oCIS+Keycloak deployment example.
2. Visit oCIS's ODIC discovery endpoint.

## Expected behavior
Endpoint return URLs with IDP's domain `konnect.mydomain.com`.

## Actual behavior
Endpoint return URLs with oCIS's domain `owncloud.mydomain.com`.

## Setup

Deployment environment: Kubernetes with Nginx ingress.

Used image version: owncloud/ocis:1.13.0

oCIS deployment environment variables:

<details>
<p>

```console
  ACCOUNTS_DEMO_USERS_AND_GROUPS: false
  OCIS_URL: https://owncloud.mydomain.com
  OCIS_DOMAIN: owncloud.mydomain.com
  PROXY_TLS: false
  # OIDC
  PROXY_AUTOPROVISION_ACCOUNTS: "true"
  PROXY_OIDC_ISSUER: https://konnect.mydoamin.com
  WEB_OIDC_AUTHORITY: https://konnect.mydoamin.com
  WEB_OIDC_CLIENT_ID: owncloud-web
  WEB_OIDC_METADATA_URL: https://konnect.mydoamin.com/.well-known/openid-configuration
  STORAGE_OIDC_ISSUER: https://konnect.mydoamin.com
  STORAGE_LDAP_IDP: https://konnect.mydoamin.com
  # STORAGE_OIDC_ID_CLAIM: preferred_username
  # Defaults to `OCIS_URL`, causing problem when oCIS pod request itself
  # because of `externalTrafficPolicy`=`Local`
  STORAGE_FRONTEND_PUBLIC_URL: http://localhost:9200
  IDP_LDAP_BIND_PASSWORD:
  STORAGE_LDAP_BIND_PASSWORD:
  OCIS_JWT_SECRET:
  STORAGE_TRANSFER_SECRET:
  OCIS_MACHINE_AUTH_API_KEY:
```

</p>
</details>

**Comment by rhafer** [comment]
> Oh thanks! I didn't notice that, maybe this should be in the docs too?

I've added a note about the redirect. To the deployment example.
