### ISSUE TITLE
Configuration Parsing v2

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#2704]
## Parsing Order

1. default struct value
2. ocis.yaml
3. extension.yaml (if any) do not fail if none is available
4. ENV variables

---

## Braindump (needs formatting)

- no more cli flags
	- remove flagsets
	- no more flag parsing on urfave/cli commands
- ocis.[yaml, json, toml...] is the main source of truth
- extension config file overwrite ocis.yaml values
- default struct values for config prior to parsing
- shared config values
	- i.e: OCIS_URL, OCIS_LOG_LEVEL...
- adopt go-micro config interface
	- start with the file implementation: https://github.com/asim/go-micro/tree/master/config/source/file
- no hot reload on env variables changes
	- env variables are parsed last
---

- we can still make use of CLI flags for things such as `help` but not for changing behavior
- this should theoretically bring us closed to a shared config concept with CERN, as there are no more flagsets and we will be basing our configuration on a `struct`

**Comment by wkloucek** [comment]
> ok, here is a small preview of this: #2708

That one wasn't that small in the end ;-)

I'm closing this issues, since the PR was already merged
