### ISSUE TITLE
User loses accepted share if owner changes the contents of the file

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#2706]
## Setup:
run ocis with docker:
Ocis v1.14.0
Web v4.4.0

## Steps to reproduce

1. admin creates or upload file.txt (also relevant for md and io)
2. admin opens file in "markdown-editor" and adds content
3. admin shares file to Marie
4. Marie accepts file and can see
5. admin opens file in "markdown-editor" and adds new content

## Expected behavior
Alice can see file and new content in 

## Actual behavior
Alice loses the file (file is not in the shares folder)

https://user-images.githubusercontent.com/84779829/139431995-4566e934-0e27-41e8-97cf-635605b777c7.mov

When the user changes a file in the "markdown-editor", the following parameters are changed:
![image](https://user-images.githubusercontent.com/84779829/139432073-6fb1c5c3-9509-4f64-918b-ffcd5923c3e4.png)

**Comment by wkloucek** [comment]
I could reproduce this by uploading the same file again (creating a version). After that the share receiver doesn't see the share anymore.

**Comment by dpakach** [comment]
this issue is also reproduced when share receiver with edit permission tries to edit the file even though the request gives 403 response.
```
❯ curl -XPUT https://localhost:9200/remote.php/webdav/Shares/shareFile.txt -u tu1:tu1 -d "hello new file" -vk
> PUT /remote.php/webdav/Shares/shareFile.txt HTTP/1.1
> Host: localhost:9200
> Authorization: Basic dHUxOnR1MQ==
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 14
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 14 out of 14 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Content-Length: 0
< Content-Security-Policy: default-src 'none';
< Date: Tue, 16 Nov 2021 08:50:18 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 
* Connection #0 to host localhost left intact

**Comment by ScharfViktor** [comment]
Re-tested 
ocis v.1.18.0 docker
web v.5.2.0

Cannot reproduce bug
