### ISSUE TITLE
App provider: public link user is displayed as the sharing user in the office app

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2709]
## Describe the bug
The public link user is displayed as the original sharing user in the office app.

## Steps to reproduce

1. einstein creates a public share of documents
2. open office files on the public link

## Expected behavior
the user is called "anonymous"

## Actual behavior
the user is called "einstein"

https://user-images.githubusercontent.com/34452982/139468892-aeecf955-278b-4835-b2c4-14ec6a0d483c.mp4

**Comment by micbar** [comment]
@wkloucek @C0rby  can we change the displayname in the token?

**Comment by wkloucek** [comment]
probably fixed by https://github.com/cs3org/reva/blob/32b439e51b946d0d1089f5bcb21135fad59b0574/pkg/app/provider/wopi/wopi.go#L141-L158, will need to check

**Comment by C0rby** [comment]
Yeah, good question how.
The problem is that for shares the share creator/owner gets impersonated, that is why the applications show their name.

**Comment by wkloucek** [comment]
No longer the case
