### ISSUE TITLE
Client redownloads files from ocis after local removal

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#271]
Test setup via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_test.sh

    git clone https://github.com/owncloud-docker/compose-playground.git
    cd compose-playground/compose/ocis
    sed -i -e 's/your-url/$ipaddr/g' config/identifier-registration.yml
    echo >> .env OCIS_BASE_URL=$ipaddr
    echo >> .env OCIS_HTTP_PORT=9200
    echo >> .env OCIS_DOCKER_TAG=1.0.0-beta4
    docker-compose -f ocis.yml -f ../cache/redis-ocis.yml up

connect user einstein through both web UI and desktop client.
Folder upload 'Music' contianing an mp3 file through the we ui.

The client downloads the folder and its contents. OK
Remove the folder locally.
![image](https://user-images.githubusercontent.com/1108546/81666378-42576e80-9442-11ea-8ef2-50b0e1171b7e.png)
The folder gets re-donwload. BAD
![image](https://user-images.githubusercontent.com/1108546/81666490-65821e00-9442-11ea-8f0d-5ec4b38507b6.png)

Expected behaviour: The folder should also be deleted in ocis.

**Comment by kobergj** [comment]
Sorry I'm closing this because it is just too old. Please reopen if ticket needs fixing on newer ocis versions.
