### ISSUE TITLE
mass upload via client produces MKCOL errors

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#272]
Test setup via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_test.sh

    git clone https://github.com/owncloud-docker/compose-playground.git
    cd compose-playground/compose/ocis
    sed -i -e 's/your-url/$ipaddr/g' config/identifier-registration.yml
    echo >> .env OCIS_BASE_URL=$ipaddr
    echo >> .env OCIS_HTTP_PORT=9200
    echo >> .env OCIS_DOCKER_TAG=1.0.0-beta4
    docker-compose -f ocis.yml -f ../cache/redis-ocis.yml up

connect user einstein with the desktop client.
wait until the initial sync is done.
Then copy a folder with ca 30 jpeg photos into the sync folder of the desktop client.
`cp -a ~/testpics ~/ownCloud2`
![image](https://user-images.githubusercontent.com/1108546/81697744-8ad45380-9465-11ea-896d-140e0a753728.png)

client log
```
  5/12/20 3:29:18 PM,                          testpics/photo_2020-05-11_18-10-59.jpg,                     ownCloud2,Server replied "404 Not Found" to "MKCOL https://116.203.242.78:9200/remote.php/dav/uploads/einstein/1650630572" (skipped due to earlier error, trying again in 1 minute(s))
  5/12/20 3:29:18 PM,                          testpics/photo_2020-04-29_17-21-20.jpg,                     ownCloud2,Server replied "404 Not Found" to "MKCOL https://116.203.242.78:9200/remote.php/dav/uploads/einstein/3339200750" (skipped due to earlier error, trying again in 1 minute(s))
  5/12/20 3:29:18 PM,                          testpics/photo_2020-04-29_17-21-15.jpg,                     ownCloud2,Server replied "404 Not Found" to "MKCOL https://116.203.242.78:9200/remote.php/dav/uploads/einstein/3029869760" (skipped due to earlier error, trying again in 1 minute(s))
  5/12/20 3:29:18 PM,                          testpics/photo_2020-04-29_17-21-03.jpg,                     ownCloud2,Server replied "404 Not Found" to "MKCOL https://116.203.242.78:9200/remote.php/dav/uploads/einstein/31011025" (skipped due to earlier error, trying again in 1 minute(s))
  5/12/20 3:29:18 PM,                          testpics/photo_2020-04-29_17-20-50.jpg,                     ownCloud2,Server replied "404 Not Found" to "MKCOL https://116.203.242.78:9200/remote.php/dav/uploads/einstein/2735690951" (skipped due to earlier error, trying again in 1 minute(s))
  5/12/20 3:29:18 PM,                          testpics/photo_2020-04-29_17-20-21.jpg,                     ownCloud2,Server replied "404 Not Found" to "MKCOL https://116.203.242.78:9200/remote.php/dav/uploads/einstein/1239652929" (skipped due to earlier error, trying again in 1 minute(s))
....
```
After a few seconds the red error messages are removed from the client settings window, and the green checkmark indicates, that all was synced to the server:
![image](https://user-images.githubusercontent.com/1108546/81698598-878d9780-9466-11ea-9372-0e8ef21aa6e0.png)
 
This indicator is wrong. Only the folder was created at the server. Nothing is uploaded. Checked with web UI.
(@TheOneRing the client should not show the green checkmark, when the uploads actually fail)

Ater a few minutes, the same uploads are attempted again. Again failing, reported with a larger retry timeout then.

**Comment by michaelstingl** [comment]
@jnweiger any file > 10MB? I'd guess https://github.com/owncloud/ocis/issues/194

**Comment by jnweiger** [comment]
no. my jpegs are 3 to 4 mb. There was one 14MB .mp4 in the folder when I started, But I carefully removed that, to not trigger too many bugs at once :-)

**Comment by individual-it** [comment]
@jnweiger can you check the ocis logs if you are also running into #268 ?

**Comment by jnweiger** [comment]
I am getting multiple different errors now....

![desktop-client-upload-ocis](https://user-images.githubusercontent.com/1108546/81827287-e9b6cd00-9538-11ea-8422-2a86d0fc33f6.gif)

Will try again later, to reprodce correctly, then I'll attach a log.

**Comment by michaelstingl** [comment]
@jnweiger can you still reproduce with the latest 2.7 daily builds?

Please always specify the exact client build information.

**Comment by jnweiger** [comment]
Retested with rc1 and desktop client beta4: upload of 1000 random files succeeds. closing here.
