### ISSUE TITLE
Provisioning API does not provide last_login in response

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2729]
## Describe the bug

core PR https://github.com/owncloud/core/pull/39351 added a `last_login` data item to the Provisioning API get-user response.

oCIS does not have that yet. That causes the changed/enhanced Provisioning API get-user test scenarios to fail (see expected-failures changes in PR #2727

**Comment by micbar** [comment]
The OCS Api is deprecated since version 5.0.0 and will no longer receive any bugfixes.
