### ISSUE TITLE
tar archive encodes file-names wrongly

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2743]
## Describe the bug
file-names with non-latin characters are not displayed correctly with some tar tools

## Steps to reproduce

1. create a folder
2. upload a file into the folder that contains non-latin in the file-name
3. download the complete folder using the archiver endpoint. Make sure `Windows NT` is not send in the `User-Agent` header. So on Windows the user-agent need to be faked or use `curl`
4. this should give a `.tar` file as download, if you are given a `.zip` file the user-agent header contains the string `Windows NT`
5. inspect the tar archive on Windows or unpack the archive using php:
    ```
    <?php
    $archive = new PharData('file.tar');
    $archive->extractTo('/tmp/test');
    ```

## Expected behavior
file-names should contain all non-latin characters

## Actual behavior
This works fine with Linux `tar` command, but not with any Windows tool I tried or PHP
Instead I get all non-latin characters removed from the file-names and an additional folder called `PaxHeaders.0`, this folder contains text files, where the content is the correct name of the actual file

![utf-archive](https://user-images.githubusercontent.com/2425577/141073024-3b1e7427-4e1e-4280-8a42-7fa6084fafbd.png)
 
`PaxHeaders.0`: `27 path=my_data/öäü.txt`

## Additional context
This is ether a problem in how the tar files are constructed in ocis or some widely used library for clients has an issue

**Comment by kulmann** [comment]
I think this belongs into the `cs3org/reva` repo where the archiver is implemented.

**Comment by individual-it** [comment]
moved to https://github.com/cs3org/reva/issues/2255
