### ISSUE TITLE
implement ocis storage-authmachine subcommand

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2778]
while a command exists in https://github.com/owncloud/ocis/blob/eb3e0151f46cb0bc7740a1cfcc69934d502c6a1c/storage/pkg/command/authmachine.go#L23

and is started when starting ocis in https://github.com/owncloud/ocis/blob/eb3e0151f46cb0bc7740a1cfcc69934d502c6a1c/ocis/pkg/runtime/service/service.go#L108

there is no ocis subcommand for it in https://github.com/owncloud/ocis/tree/6d5a3733ffaf45690c66dca97c790aa21af94eae/ocis/pkg/command

**Comment by wkloucek** [comment]
fixed by https://github.com/owncloud/ocis/pull/2910
