### ISSUE TITLE
downloading an archive with non existing / accessible id returns HTTP/500

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2795]
## Describe the bug

(Tracking ticket for expected failures)

Downloading an archive with no existing or non accessible id returns HTTP/500 instead of an expected HTTP/400

https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiArchiver/downloadByPath.feature#L69

**Comment by phil-davis** [comment]
Similar to https://github.com/cs3org/reva/issues/2292 ?

**Comment by wkloucek** [comment]
> Similar to [cs3org/reva#2292](https://github.com/cs3org/reva/issues/2292) and #2768 ?

Yes, basically the oCIS tracking ticket of cs3org/reva#2292

**Comment by ScharfViktor** [comment]
retested on `ocis-6.0.0`

when `GET https://localhost:9200/archiver?id=nonexistingUUiD` -> 404 not found
