### ISSUE TITLE
add performance measurement

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#28]
first approach would be to run smashbox or the phoenix ui tests along with a monitoring tool.
- [ ] add prometheus to docker-compose.yml
  - not really needed for `make future`
  - start only for a `make demo` that can be used to demo how a production environment would look like?
- [ ] add `make performance-metrics`
  while prometheus is running
  - run smashbox
  - run the phoenix ui tests
  afterwards print cpu, memory and io graphs as a snapshot for the testing duration.
  - [ ] generate PDF with metrics

**Comment by refs** [comment]
Closing in favor of the current performance measurement efforts.
