### ISSUE TITLE
oCIS API testing Roadmap

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#2808]
### Quota Tests 
- Quick win, Use graphAPI to set the quota
- ref https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/bootstrap/SpacesContext.php#L396

### Move the share jail

- from `/home/Shares` to `/Shares`

### New WebDavURLS
- Add the new webdav urls as a third variant
- `https://ocis.test/dav/spaces/<uuid>` for the personal space folder
- They should behave like the existing urls

### Before GA
- SearchAPI Tests
- tbd how to implement
- probably webDAV REPORT

### WebDAV Locking
- "nice to have"
- not sure if tackled before GA
- Currently o10 is using WebDAV exclusive Locks

### Local API tests
- Add the localArchiver test to reva

### EOS in Reva
- will be added to the Reva CI

**Comment by individual-it** [comment]
issue for WebDAV Urls #2854

**Comment by phil-davis** [comment]
This is an overview issue and should stay open.

**Comment by phil-davis** [comment]
Scenarios that I thought of today while looking at what is already in the oCIS https://github.com/owncloud/ocis/tree/master/tests/acceptance/features/apiSpaces suite today:

- move and copy of resources
- do things between personal and project spaces
- do things between 2 project spaces
- edge cases for more invalid attempts to do stuff (trying to move/copy/upload somewhere that you are not allowed or does not exist)
- add some edge cases for "strange" resource names (UTF-8 resource names)

**Comment by ScharfViktor** [comment]
> 

I created ticket https://github.com/owncloud/ocis/issues/4087

**Comment by ScharfViktor** [comment]
> Scenarios that I thought of today while looking at what is already in the oCIS https://github.com/owncloud/ocis/tree/master/tests/acceptance/features/apiSpaces suite today:
> 
> * move and copy of resources
> * do things between personal and project spaces
> * do things between 2 project spaces
> * edge cases for more invalid attempts to do stuff (trying to move/copy/upload somewhere that you are not allowed or does not exist)
> * add some edge cases for "strange" resource names (UTF-8 resource names)

I created tiket https://github.com/owncloud/ocis/issues/4087
