### ISSUE TITLE
Upload empty file creates file called ``uuid`` in root folder

### ISSUE THREAD

**Issue by axstet** [owncloud/ocis#2814]
## Describe the bug

Upload empty file creates file called ``uuid`` in root folder.

## Steps to reproduce

1. Setup OCIS
2. Log into web client
3. Upload empty file

## Expected behavior
Selected file is uploaded.

## Actual behavior
Selected file is uploaded but also a file named after ``uuid`` of uploaded file is created in root folder.

## Setup

Stock 1.15

**Comment by wkloucek** [comment]
duplicate of https://github.com/owncloud/ocis/issues/2609
