### ISSUE TITLE
Get latest web acceptance tests running in oCIS CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2847]
The web acceptance tests recently started making use of the test middleware to execute various scenario setup `Given` steps.

The `web` in oCIS is now being updated, The oCIS drone CI needs to have the test middleware running so that the web tests can pass.

PR #2846 bumps web to 4.6.0 - make CI pass.

**Comment by phil-davis** [comment]
web PR https://github.com/owncloud/web/pull/5136 implemented the middleware in web CI. drone starlark changes there are probably what is needed in oCIS.

**Comment by dpakach** [comment]
done in https://github.com/owncloud/ocis/pull/2848
this will be fixed in https://github.com/owncloud/ocis/pull/2846

**Comment by phil-davis** [comment]
The commit has been cherry-picked to #2846 and CI is running. Waiting for the result.

**Comment by dpakach** [comment]
https://github.com/owncloud/ocis/pull/2846 has been merged
