### ISSUE TITLE
PROPFIND on spaces subfolder shows `d:href` without path

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2862]
## Describe the bug
the PROPFIND request on a subfolder of a space returns the list of containing files but the `d:href` to the file does not contain the subfolder name

## Steps to reproduce

1. create a folder called `new`
2. upload a file into the newly created folder
3. find the space id of the personal space: `curl -k -ueinstein:relativity https://localhost:9200/graph/v1.0/me/drives/ | jq`
4. use the space it to query the content of the created folder via WebDAV API `curl -k -ueinstein:relativity -XPROPFIND 'https://localhost:9200/dav/spaces/<spaceid>/new' | xmllint --format -`

## Expected behavior
the `<d:href>` element should be
`<d:href>/dav/spaces/<space-id>/new/file.txt</d:href>`

## Actual behavior
The path is missing from the `href`
`<d:href>/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157!9727e92b-9ebd-4193-85fb-5051a8afabdc/file.txt</d:href>`

running PROPFIND on the file itself gives the correct data
`curl -k -ueinstein:relativity -XPROPFIND 'https://localhost:9200/dav/spaces/<spaceid>/new/file.txt' | xmllint --format -`

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_INSECURE=true PROXY_ENABLE_BASIC_AUTH=true bin/ocis server
```

</p>
</details>

**Comment by micbar** [comment]
Fix when a user / client reports an end user facing bug.

**Comment by ScharfViktor** [comment]
works correct. retested on `ocis-6.0.0`


- create `new/sub ` and `new/file.txt`
-send `PROPFIND https://localhost:9200/dav/spaces/personalUUID/new`
response: 
```
<d:response>
        <d:href>/dav/spaces/c9dd994c-ec63-4d28-9036-fa340cb0f0ab$80adc74f-3e88-44d8-8e04-e85bf5aa698a/new/file.txt</d:href>
</d:response>
<d:response>
        <d:href>/dav/spaces/c9dd994c-ec63-4d28-9036-fa340cb0f0ab$80adc74f-3e88-44d8-8e04-e85bf5aa698a/new/sub</d:href>
</d:response>
```
