### ISSUE TITLE
content of folder shares are not displayed through the spaces WebDAV API

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2863]
## Describe the bug
the content of a received folder share cannot be queried by PROPFIND for the content of that folder

## Steps to reproduce

1. as einstein share a folder to marie that contains some files
2. as marie accept the share
3. as marie find the spaceid of the personal space: `curl -k -umarie:radioactivity https://localhost:9200/graph/v1.0/me/drives/ | jq`
4. as marie PROPFIND the received share using the spaces API: `curl -k -umarie:radioactivity -XPROPFIND 'https://localhost:9200/dav/spaces/<spaceid>/Shares/new' | xmllint --format -`

## Expected behavior
the response should contain all elements inside that folder

## Actual behavior
folder content is not listed

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_INSECURE=true PROXY_ENABLE_BASIC_AUTH=true bin/ocis server
```

</p>
</details>

**Comment by ScharfViktor** [comment]
it seems outdated. we don't use `https://localhost:9200/dav/spaces/<spaceid>/Shares` to get share
