### ISSUE TITLE
Copying zero byte file returns 201 status code but is not successful

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#2868]
## Steps to reproduce

1. Go to https://ocis.ocis-web.latest.owncloud.works
2. Create folder in root, upload zero byte file to root
3. Try to copy zero byte file to folder

## Expected behavior
Copy of zero byte file exists inside folder

## Actual behavior
No file in copy target folder (yet the copy request has a status code of 201)

## Note
This was discovered by  an acceptance test in web. My workaround for the acceptance test suite was to upload a file with >0 byte content 🤷🏽  debatable whether we should test both scenarios, but at least discovered this bug...

**Comment by wkloucek** [comment]
Will be fixed by cs3org/reva#2374
