### ISSUE TITLE
[tests-only] Balance out length of web acceptance test pipelines

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2872]
Similar to https://github.com/owncloud/web/issues/6095

A recent full-ci run was done for #2871 - drone logs https://drone.owncloud.com/owncloud/ocis/8322

1) have a look at that CI run and comment in this issue about the range of run-times of the 20 web-tests pipelines

Then we can discuss/decide if it is worth manually allocating test suites to pipelines, to balance the run times better. (Currently they are auto-split into 20 pipelines)

If so, then:

2) Balance out the number of features/scenarios in each pipeline so that each pipeline can finish in about the same time (let's aim for about 15 minutes maximum for a pipeline). Do not increase the total number of pipelines.

**Comment by amrita-shrestha** [comment]
new issue has been created in the QA  repo.So closing this issue
