### ISSUE TITLE
Update capabilities

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#29]
## Describe the bug
Currently, the capabilities are configured manually with defaults set to outdatet versions. We need a better concept how to generate the list of capabilities and remove old ones.

## Steps to reproduce
curl the capabilities endpoint

## Expected behavior
An up to date list of capabilities, dynamically generated by the current live configuration of all extensions.

## Actual behavior
Static list of capabilities that does not reflect the truth.

## Example
TUS capability ... which is actually not a global config but a per folder thing ...

**Comment by micbar** [comment]
Fixed
