### ISSUE TITLE
Public link url gives error after the share is renamed.

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#2915]
## Description
When trying to access the public link url after the shared resource is renamed, the url redirects to an error.

## Steps to reproduce:

- start ocis
- login to phoenix
- upload a file
- create a public link
- look for the share and the public link
- rename the file
- look for the share and the public link

### with API:

- upload: `curl -k -u einstein:relativity -X PUT https://localhost:9200/remote.php/webdav/lorem.txt -d"123"
create public link: curl -k -u einstein:relativity 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' --data-raw 'shareType=3&path=%2Florem.txt&permissions=1'`

- check link: `curl -k -u einstein:relativity 'https://ocis-server:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' | xmllint --format -`
 
This gives the following response:
```
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>iCfugGLfjfrihre</id>
      <share_type>3</share_type>
      <uid_owner>4c510ada-c86b-4815-8820-42cdf82c3d51</uid_owner>
      <displayname_owner>Albert Einstein</displayname_owner>
      <permissions>1</permissions>
      <stime>1607511410</stime>
      <parent/>
      <expiration/>
      <token>YxrVQhrPGTOXeUd</token>
      <uid_file_owner>4c510ada-c86b-4815-8820-42cdf82c3d51</uid_file_owner>
      <displayname_file_owner>Albert Einstein</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <state>0</state>
      <path>/lorem.txt</path>
      <item_type>file</item_type>
      <mimetype>text/plain</mimetype>
      <storage_id>1284d238-aa92-42ce-bdc4-0b0000009157</storage_id>
      <storage>0</storage>
      <item_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjYwNjY4ODViLWMwYzMtNGE4My04ZTRiLTQ5YTU5MGYwM2RiNg==</item_source>
      <file_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjYwNjY4ODViLWMwYzMtNGE4My04ZTRiLTQ5YTU5MGYwM2RiNg==</file_source>
      <file_parent/>
      <file_target>/lorem.txt</file_target>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name/>
      <url>https://localhost:9200/#/s/YxrVQhrPGTOXeUd</url>
    </element>
</data>
</ocs>



```
And the url redirects to the share.

- rename: `curl -k -u einstein:relativity -X MOVE https://localhost:9200/remote.php/webdav/lorem.txt -H"Destination: https://localhost:9200/remote.php/webdav/new-lorem.txt"`

- check link: `curl -k -u einstein:relativity 'https://ocis-server:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' | xmllint --format -`
 This gives the following response:
```
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>iCfugGLfjfrihre</id>
      <share_type>3</share_type>
      <uid_owner>4c510ada-c86b-4815-8820-42cdf82c3d51</uid_owner>
      <displayname_owner>Albert Einstein</displayname_owner>
      <permissions>1</permissions>
      <stime>1607511410</stime>
      <parent/>
      <expiration/>
      <token>YxrVQhrPGTOXeUd</token>
      <uid_file_owner>4c510ada-c86b-4815-8820-42cdf82c3d51</uid_file_owner>
      <displayname_file_owner>Albert Einstein</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <state>0</state>
      <path/>
      <item_type/>
      <mimetype>seconds:1607511410 nanos:855737410 </mimetype>
      <storage_id/>
      <storage>0</storage>
      <item_source/>
      <file_source/>
      <file_parent/>
      <file_target/>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name/>
      <url>https://localhost:9200/#/s/YxrVQhrPGTOXeUd</url>
    </element>
  </data>
</ocs>

```
And the url redirects to a page with error message as: 
```
An error occurred while loading the public link
Error: Unknown error
```
![Screenshot from 2020-12-09 16-52-43](https://user-images.githubusercontent.com/40829116/101622346-08356600-3a3f-11eb-843f-b2b18b82881d.png)

**Comment by phil-davis** [comment]
@Talank please post the details about this. Link to the test(s) that cover this case.
I can't find this issue in expected-failures. Is this still a bug, or is it fixed?

**Comment by SwikritiT** [comment]
@phil-davis 

There's no error shown now when we navigate the link. I tried with both the API and WebUI and both of them work. 

Through API:
1. upload a file : `curl -k -u einstein:relativity -X PUT https://localhost:9200/remote.php/webdav/lorem.txt -d"123" `
2. create a public link: `curl -k -u einstein:relativity 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' --data-raw 'shareType=3&path=%2Florem.txt&permissions=1'`
3. check link:  `curl -k -u einstein:relativity 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' | xmllint --format -`
 ```console
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>TLyicbxeGOrbNtz</id>
      <share_type>3</share_type>
      <uid_owner>einstein</uid_owner>
      <displayname_owner>Albert Einstein</displayname_owner>
      <additional_info_owner>einstein@example.org</additional_info_owner>
      <permissions>1</permissions>
      <stime>1645507832</stime>
      <parent/>
      <expiration/>
      <token>ZkjaPJybdGNrRXv</token>
      <uid_file_owner>einstein</uid_file_owner>
      <displayname_file_owner>Albert Einstein</displayname_file_owner>
      <additional_info_file_owner>einstein@example.org</additional_info_file_owner>
      <state>0</state>
      <path>/lorem.txt</path>
      <item_type>file</item_type>
      <mimetype>text/plain</mimetype>
      <storage_id>shared::/lorem.txt</storage_id>
      <storage>0</storage>
      <item_source>NGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxOjRiNzU5OTQzLTJiNjktNDg0Zi04NmJkLWE1OTA4YTJkZDQ0Mw==</item_source>
      <file_source>NGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxOjRiNzU5OTQzLTJiNjktNDg0Zi04NmJkLWE1OTA4YTJkZDQ0Mw==</file_source>
      <file_parent/>
      <file_target>/lorem.txt</file_target>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name/>
      <url>https://localhost:9200/#/s/ZkjaPJybdGNrRXv</url>
    </element>
  </data>
</ocs>

```
 4 . navigate the link : works

![before-rename](https://user-images.githubusercontent.com/41103328/155069837-8953b9d2-89f7-4f6e-911c-29145af01e4e.png)

5. Rename the file: `curl -k -u einstein:relativity -X MOVE https://localhost:9200/remote.php/webdav/lorem.txt -H"Destination: https://localhost:9200/remote.php/webdav/new-lorem.txt"`
6. Check the link: `curl -k -u einstein:relativity 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' | xmllint --format -`
```console
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>TLyicbxeGOrbNtz</id>
      <share_type>3</share_type>
      <uid_owner>einstein</uid_owner>
      <displayname_owner>Albert Einstein</displayname_owner>
      <additional_info_owner>einstein@example.org</additional_info_owner>
      <permissions>1</permissions>
      <stime>1645507832</stime>
      <parent/>
      <expiration/>
      <token>ZkjaPJybdGNrRXv</token>
      <uid_file_owner>einstein</uid_file_owner>
      <displayname_file_owner>Albert Einstein</displayname_file_owner>
      <additional_info_file_owner>einstein@example.org</additional_info_file_owner>
      <state>0</state>
      <path>/new-lorem.txt</path>
      <item_type>file</item_type>
      <mimetype>text/plain</mimetype>
      <storage_id>shared::/new-lorem.txt</storage_id>
      <storage>0</storage>
      <item_source>NGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxOjRiNzU5OTQzLTJiNjktNDg0Zi04NmJkLWE1OTA4YTJkZDQ0Mw==</item_source>
      <file_source>NGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxOjRiNzU5OTQzLTJiNjktNDg0Zi04NmJkLWE1OTA4YTJkZDQ0Mw==</file_source>
      <file_parent/>
      <file_target>/new-lorem.txt</file_target>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name/>
      <url>https://localhost:9200/#/s/ZkjaPJybdGNrRXv</url>
    </element>
  </data>
</ocs>
```
7. navigate the link : also works no errors are shown
![after-rename](https://user-images.githubusercontent.com/41103328/155070320-b3495d13-304d-4351-904b-819c63a8e01a.png)

One thing that I noticed is that the renaming of the file is not propagated properly in the webUI. The name of the file before and after renaming is the same `lorem.txt` when accessed through the link. I'm not sure if that's supposed to be the expected behaviour.

**Comment by SwikritiT** [comment]
I tried to do the similar thing in core backend too

1. Upload the file: `curl -k -u test:test -X PUT http://localhost/core/remote.php/webdav/lorem.txt -d"123"`
2.  Create a public like: `curl -k -u test:test 'http://localhost/core/ocs/v1.php/apps/files_sharing/api/v1/shares' --data-raw 'shareType=3&path=%2Florem.txt&permissions=1'`
3. check the link: ` curl -k -u test:test 'http://localhost/core/ocs/v1.php/apps/files_sharing/api/v1/shares' | xmllint --format -`
```console
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message/>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data>
    <element>
      <id>4723</id>
      <share_type>3</share_type>
      <uid_owner>test</uid_owner>
      <displayname_owner>test</displayname_owner>
      <permissions>1</permissions>
      <stime>1645514673</stime>
      <parent/>
      <expiration/>
      <token>F1PV7g5kPw6Bq8n</token>
      <uid_file_owner>test</uid_file_owner>
      <displayname_file_owner>test</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <path>/lorem.txt</path>
      <mimetype>text/plain</mimetype>
      <storage_id>home::test</storage_id>
      <storage>13026</storage>
      <item_type>file</item_type>
      <item_source>2147718295</item_source>
      <file_source>2147718295</file_source>
      <file_parent>2147716504</file_parent>
      <file_target>/lorem.txt</file_target>
      <name/>
      <url>http://localhost/core/index.php/s/F1PV7g5kPw6Bq8n</url>
      <mail_send>0</mail_send>
      <attributes/>
    </element>
  </data>
</ocs>
```
4.  Navigate to the link : works
![oc10-before-rename](https://user-images.githubusercontent.com/41103328/155083793-8f4b6782-a3ff-470e-ba68-e73e5fa923b9.png)

5.  rename the file : ` curl -k -u test:test -X MOVE http://localhost/core/remote.php/webdav/lorem.txt -H"Destination: http://localhost/core/remote.php/webdav/new-lorem.txt"`
6. check the shares: `curl -k -u test:test 'http://localhost/core/ocs/v1.php/apps/files_sharing/api/v1/shares' | xmllint --format -    `
here the `new name` is propagated in `path` but `file_target` contains the old name
```console
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message/>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data>
    <element>
      <id>4723</id>
      <share_type>3</share_type>
      <uid_owner>test</uid_owner>
      <displayname_owner>test</displayname_owner>
      <permissions>1</permissions>
      <stime>1645514673</stime>
      <parent/>
      <expiration/>
      <token>F1PV7g5kPw6Bq8n</token>
      <uid_file_owner>test</uid_file_owner>
      <displayname_file_owner>test</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <path>/new-lorem.txt</path>
      <mimetype>text/plain</mimetype>
      <storage_id>home::test</storage_id>
      <storage>13026</storage>
      <item_type>file</item_type>
      <item_source>2147718295</item_source>
      <file_source>2147718295</file_source>
      <file_parent>2147716504</file_parent>
      <file_target>/lorem.txt</file_target>
      <name/>
      <url>http://localhost/core/index.php/s/F1PV7g5kPw6Bq8n</url>
      <mail_send>0</mail_send>
      <attributes/>
    </element>
  </data>
</ocs>

```
7. navigatio
![oc10-after-rename](https://user-images.githubusercontent.com/41103328/155084385-d4567603-a829-4692-8aec-b5d42c00e474.png)
n to the link works:

**Comment by SwikritiT** [comment]
@phil-davis I found this one test that `renames a folder shared through` public link but it's skipped in  OC10 https://github.com/owncloud/core/blob/a0a4064c77a3576763885f83d57ca4c558348b8c/tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature#L81
and present in expected to failure file in OCIS https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature#L118

**Comment by SwikritiT** [comment]
@phil-davis this issue no longer exists. The test and expected to fail have been updated. I think we can close this issue no.
