### ISSUE TITLE
webUIFiles/breadcrumb.feature:50 test fails in nightly builds

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2942]
this fails since a while in nightly runs e.g. https://drone.owncloud.com/owncloud/ocis/8636/32/9

**Comment by kiranparajuli589** [comment]
seems like a bug to me.
if ocis is started with webConfig:
```json
{
      "options": {
          "homeFolder": "/0"
      }
}
```

then breadcrumb for folder "0" is set the web UI

But, if we start ocis without `homeFolder` option and update it after the ocis service has started, the the changes in not reflected on the web UI

**Comment by kiranparajuli589** [comment]
separate issue created describing the bug
