### ISSUE TITLE
web config update is not properly reflected after the ocis start

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2944]
## Describe the bug

`ocis` use the env `WEB_UI_CONFIG` to look for and update the web ui config. If we start the server and then make some change in the config file, the changes are not reflected on the webUI until the restart.

## Steps to reproduce

1. start `ocis` server with `homeFolder` options not set in the WEB_UI_CONFIG file.
2. update the options `homeFolder` to "/0"
3. login as `einstein`

## Expected behavior
- breadcrumb for folder "/0" should be displayed

## Actual behavior
- breadcrumb for folder "/0" is not displayed (remains unchanged to only All files)
see the passing build at https://drone.owncloud.com/owncloud/ocis/8595/33/9

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

> latest ocis master from github

```console
#!/bin/bash
export OCIS_URL="https://localhost:9200"
export PROXY_ENABLE_BASIC_AUTH=True
export WEB_UI_CONFIG="/$HOME/www/useful/ocis-config/web-config.json"
export WEB_ASSET_PATH="$HOME/www/web/dist/"
export IDP_IDENTIFIER_REGISTRATION_CONF="/$HOME/www/useful/ocis-config/idp.yml"
export OCIS_LOG_LEVEL="error"
export OCIS_INSECURE="true"

if [ "$DRIVER" = 'owncloud' ]
then
	export STORAGE_HOME_DRIVER="owncloud"
	export STORAGE_USERS_DRIVER="owncloud"
else
	export STORAGE_HOME_DRIVER="ocis"
	export STORAGE_USERS_DRIVER="ocis"
fi

# assumes ocis repo cloned at"$HOME"/go/src/github.com/owncloud/ocis
"$HOME"/go/src/github.com/owncloud/ocis/ocis/bin/ocis server

```

</p>
</details>

## Additional context
- was started from ee57288309f9d89f74a1d872635d8c34caf76db9 (https://github.com/owncloud/ocis/pull/2818)
- https://github.com/owncloud/ocis/issues/2942

**Comment by kiranparajuli589** [comment]
cc @wkloucek

**Comment by grgprarup** [comment]
The issue might be fixed.
https://drone.owncloud.com/owncloud/web/38355/20/13#:~:text=Scenario%3A%20Check%20breadCrumb,is%20not%20visible%20.
https://drone.owncloud.com/owncloud/ocis/25804/72/13#:~:text=Scenario%3A%20Check%20breadCrumb,is%20not%20visible%20.
So, closing this issue.
