### ISSUE TITLE
Parallel deployment tests are failing with the latest oCIS docker image

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#2950]
https://drone.owncloud.com/owncloud/ocis/8664/56/14
oCIS log:
```
{"level":"error","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"error: already exists: decomposedfs: spaces: space already exists","status":{"code":7,"message":"already exists","trace":"00000000000000000000000000000000"},"request":{"opaque":{"map":{"spaceid":{"decoder":"plain","value":"OTVjYjg3MjQtMDNiMi0xMWViLWEwYTYtYzMzZWY4ZWY1M2Fk"}}},"owner":{"id":{"opaque_id":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad"}},"type":"metadata","name":"Metadata"},"time":"2022-01-12T01:00:34Z","message":"failed to create storage space"}
{"level":"error","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"error: not found: 95cb8724-03b2-11eb-a0a6-c33ef8ef53ad/index.cs3","status":{"code":6,"message":"path not found when statting","trace":"00000000000000000000000000000000"},"reference":{"resource_id":{"storage_id":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad","opaque_id":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad"},"path":"./index.cs3"},"time":"2022-01-12T01:00:34Z","message":"failed to stat"}
{"level":"error","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"error: not found: 890df00a-5035-4204-8132-b140954f788c/non_unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.Id","status":{"code":6,"message":"path not found when statting","trace":"00000000000000000000000000000000"},"reference":{"resource_id":{"storage_id":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad","opaque_id":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad"},"path":"./index.cs3/non_unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.Id"},"time":"2022-01-12T01:00:34Z","message":"failed to stat"}
```

After this PR https://github.com/owncloud/ocis/pull/2739 was merged. oCIS docker image got updated with the changes and now the parallel deployment tests are failing with the latest oCIS image.

The reason that the PR passed the CI is that in parallel deployment the oCIS server is built from the docker image, not from the current branch. This means the oCIS server will not get the changes from the current branch.

So two things to do:
- [ ] Find out why the parallel deployment tests failed with the latest changes
- [ ] Build oCIS server from the current branch (PR branch) for parallel deployment tests so that the changes are tested early.

**Comment by micbar** [comment]
@butonic @kobergj Seems that we missed something. Can you dig into that?

**Comment by saw-jan** [comment]
Maybe fixed by PR https://github.com/owncloud/ocis/pull/2952

**Comment by phil-davis** [comment]
Note: PR #2955 temporarily disabled the tests in CI, so that full-ci can "pass" for now.

Whichever PR actually fixes the problem, that will need to enable the tests in CI again.

**Comment by wkloucek** [comment]
Tracking ticket for fix in REVA edge: https://github.com/owncloud/ocis/issues/2972

**Comment by wkloucek** [comment]
Since https://github.com/owncloud/ocis/pull/3052 the parallel deployment uses the same oCIS binary as all other tests and tests are again passing
