### ISSUE TITLE
Search user by full name doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#2966]
web 4.9.0
ocis(docker) 1.16.0

Steps:
- Admin add file
- go to share dialog 
- add to invite input  "Marie Curie"

Actual result: user not found
![Screenshot 2022-01-14 at 15 04 32](https://user-images.githubusercontent.com/84779829/149529398-4386ef4d-9c58-4c77-b05b-4a98d86fb50e.png)

Search by mail or name - works
![Screenshot 2022-01-14 at 15 03 32](https://user-images.githubusercontent.com/84779829/149529734-70801ec5-19b1-440d-a6bf-6013998e5595.png)

**Comment by rhafer** [comment]
This seems to be a problem in glauth (or the accounts backend of glauth). Apparently filtering on "displayName" (the attribute that contains the full name does not work:

Doing the search manually gives no result as well,
```
 ldapsearch -x -H ldap://127.0.0.1:9125 -b dc=ocis,dc=test -D "cn=admin,dc=ocis,dc=test" -w admin '(&(objectclass=posixaccount)(displayname=mar*))'
# extended LDIF
#
# LDAPv3
# base <dc=ocis,dc=test> with scope subtree
# filter: (&(objectclass=posixaccount)(displayname=mar*))
# requesting: ALL
#

# search result
search: 2
result: 0 Success

# numResponses: 1
```

I guess this issue will go away once we switch away from glauth

**Comment by ScharfViktor** [comment]
I re-tested it on  `ownCloud Web UI 5.5.0-rc.5   Infinite Scale 0.0.0+5526d6179 Community`

search user by full name `Marie Skłodowska Curie` works.
![Screenshot 2022-05-11 at 16 03 32](https://user-images.githubusercontent.com/84779829/167868826-1692c7d2-987a-4733-ae36-98d11434132c.png)
