### ISSUE TITLE
OCIS accepts token from any oidc client

### ISSUE THREAD

**Issue by mortbauer** [owncloud/ocis#2967]
## Description

- OCIS does accept any valid token from the IDP.
- so also any other oidc client getting a access_token from the idp can access all owncloud user data
- that feels wrong

### Background
- OIDC is first authentication see for example [1](https://www.pingidentity.com/en/resources/client-library/articles/openid-connect.html)
- if one wants to use OIDC also for authorization this can be done via scopes see for example [2](https://auth0.com/docs/get-started/apis/scopes/openid-connect-scopes)

## Steps to reproduce

1. create another oidc client on the idp
2. create an access token for the new idp
3. try to access ocis data with that token -> it will actually work

## Expected behavior

ocis should require some additional scope to verify that the client has the rights to access the data on the behalf of the user

## Actual behaviour

ocis just accepts the token

**Comment by micbar** [comment]
@mortbauer Thanks for reporting. We will take a look.

**Comment by micbar** [comment]
@rhafer Can you take a look?

**Comment by mortbauer** [comment]
Have to say that bug is probably wrong categorisation, but feature also didn't feel right

**Comment by rhafer** [comment]
@mortbauer Would you mind sharing a few more details for how to reproduce this issue? I guess I am misunderstanding the issue, but isn't this more of an issue of how the IDP is configured rather than an issue in ocis itself? So a few more details would help here.

BTW, what setup are using. Is this base on the keycloak setup from the example deployments?

**Comment by mortbauer** [comment]
Hey @rhafer, I don't think it is a thing of the idp, here my thoughts:

here a quote from the [auth0 docs on scopes](https://auth0.com/docs/get-started/apis/scopes): 

> Often, new applications will want to make use of the information that has already been created in an online resource. To do so, the application must ask for authorization to access this information on a user's behalf. Scopes define the specific actions applications can be allowed to do on a user's behalf.

So I would understand it that way that ocis should define some scopes, for example `read.userdata`, `write.userdata` ...  and then other applications (clients in oauth2 terms) request access to these scopes, the user than has to grant these apps these scopes and the idp then will attach these scopes (from the app requested, and from the user granted scopes) to the access_token. The app then will try to access the resource which lives in ocis, and ocis should check if the needed scopes for an api endpoint are attached to the token, similar as it is also checking the userid.

Here is another [Auth0 Doc on Api Scopes](https://auth0.com/docs/get-started/apis/scopes/api-scopes) which seems also quite illustrating.

So I still might be wrong because I'm still fairly new to the oauth2 stuff, but I'm quite confident that I'm not.

And my setup is currently an adaptation from the keycloak deployment example, however I use ory hydra instead of keycloak.

**Comment by rhafer** [comment]
@mortbauer Ah, ok. I think now I got it. Yeah, currently ocis doesn't make use of any custom scopes (not sure what's the right OIDC terminology for this.) We really just use OIDC for authentication and requesting the basic user claims (so the "default" oidc scopes openid, profile, email). We currently  don't handle authorization (i.e. which app is able to do what inside ocis) via OIDC scopes. And to my knowledge there are no concrete plans currently in this direction. But your feedback about what use cases you have for this is quite welcome. (Though I agree, that this doesn't quite fit into the bug categorization)

But somehow I understood your initial request in a very different way. You mentioned that you can setup another oidc_client inside you IDP, request a token for that client and use that token to access ocis. Is that really true? If yes, there still seem to be a bug lurking somewhere because AFAIU the client should check whether the token was issued for the right audience. So if you have some more details on reproducing this, that would be very welcome.

**Comment by C0rby** [comment]
> We really just use OIDC for authentication and requesting the basic user claims (so the "default" oidc scopes openid, profile, email). We currently don't handle authorization (i.e. which app is able to do what inside ocis) via OIDC scopes. And to my knowledge there are no concrete plans currently in this direction. But your feedback about what use cases you have for this is quite welcome. (Though I agree, that this doesn't quite fit into the bug categorization)

Yeah after looking into our approach for a bit I found that we do the following:

- The end-user authenticates via OIDC and the client then receives an ID token and an access token.
  The access token is just a generic token without any scopes etc.
- On every API request the access token is sent as a bearer token
- The bearer token is used to request the OIDC `/userinfo` endpoint at the IdP
- The user info is used in further steps

So technically we aren't really using OAuth2, only OIDC. And yes any client which can authenticate against the IdP would then be able to send requests to oCIS.

At the moment I couldn't find any information of what should be the standard behavior. So this ticket requires some more research IMO.

**Comment by butonic** [comment]
hm, the graph api uses scopes to grant access to certain resources: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes

The client could request [`scope=https://cloud.ocis.test/Files.ReadWrite.All`](https://docs.microsoft.com/en-us/graph/permissions-reference#files-permissions) to
> Allows the app to read, create, update, and delete all files the signed-in user can access.

**Comment by micbar** [comment]
Refinement:

- We should verify the token audience

**Comment by rhafer** [comment]
> Refinement:
> 
>     * We should verify the token audience

Even that proves to be tricky.
- In ocis (the "resource-server" in oidc/oauth terms) we only ever get to see the access_token. The id_token is kept by the client (web, desktop, ...)
- The access_token is used to query the userinfo from the idp (the userinfo doesn't contain any `aud`/`scope` claims obviously)
- The access_token itself is defined to be opaque. So there is not guarantee that we can extract an info from it (it's implementations specific)
- Many IDPs issue JWT formatted access tokens so we could try to parse the access token as a JWT
  - however there is still no guarantee that we'll find any `aud` (and/or `scope`) claims in there
    - currently the default lico IDP seems to set the audience in the access token to the client_id of the client that requested the token i.e. when logging in via web the `aud` claim in the access token is `web`
    - with keycloak this seems to be a little different. Currently I always get `account` as the `aud` claim. But that seem to depend on the specific configuration of keycloak (@wkloucek since you seem to have dealt with keycloak a bit more, do you have any idea what we'd need to set there to get a proper `aud` claim in the access token)
- In order to properly parse and validate any JWT formatted access token we would need to download the proper keys from the `jwks` endpoint (as announced via `.well-known/openid-configuration`) github.com/MicahParks/keyfunc could help with that.
- Yet another way of extracting information from the access token is to use the introspection endpoint (as defined in RFC7662) that some IDP (e.g. keycloak) provide. Others done.

So it does not seem possible to implement this in a generic way, that works will all IDPs at once.
Implementing an audience check for keycloak and lico at least seems possible (by parsing the access token as JWT), question is, what is the correct audience to check for? @C0rby any suggestion?

Parsing the access_token would also have the benefit of making our token_cache work more efficient (and reduce the number of userinfo requests) as we could properly extract the expiration time from it (which is currently broken).

**Comment by rhafer** [comment]
I've added https://github.com/owncloud/ocis/pull/4135 as an initial attempt to fix the access_token verification. (We still need to figure out if and how we want to uses any claims for additional authorization checks)

**Comment by wkloucek** [comment]
@rhafer In Keycloak one could configure following mapper:
![image](https://user-images.githubusercontent.com/34452982/177932939-f939e465-0805-408e-9dba-021ce0f0039a.png)

Then you would have the `ocis-backend` in aud in the access-token:

```json
{
  "exp": 1657263051,
  "iat": 1657262751,
  "auth_time": 1657262749,
  "jti": "80602de4-2474-4be0-afea-113c568063a9",
  "iss": "https://keycloak.ocis-keycloak.latest.owncloud.works/auth/realms/oCIS",
  "aud": [
    "ocis-backend",
    "account"
  ],
  "sub": "0a9f434c-4864-49cf-ac15-46ed0f49d59b",
  "typ": "Bearer",
  "azp": "web",
  "session_state": "ec105bd9-9045-4c3a-897d-bf07a02eb951",
  "allowed-origins": [
    "https://ocis.ocis-keycloak.latest.owncloud.works"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "sid": "ec105bd9-9045-4c3a-897d-bf07a02eb951",
  "email_verified": true,
  "name": "Albert Einstein",
  "preferred_username": "einstein",
  "given_name": "Albert",
  "family_name": "Einstein",
  "email": "einstein@example.org"
}
```

**Comment by rhafer** [comment]
> @rhafer In Keycloak one could configure following mapper:
>
> `[...]`
> 
> Then you would have the `ocis-backend` in aud in the access-token:
> 
> `...`

Yes. I guess the main question is how far we want to go here.  And what requirements we have want to impose on the (external) IDPs. The original goal was to ["verify the token audience`](https://github.com/owncloud/ocis/issues/2967#issuecomment-1167224901)

Which again raised a couple of open questions:

* The audience of which token? (The ID token usually has a different audience than the Access Token)
  * The ID token's audience can only be verified by the client (web, mobile, desktop, ...). As ocis will not see any ID token by default (only  access_tokens). Does the currently happen in web? (@kulmann, @fschade maybe)
* For access tokens (if they are JWT) we could add configuration options to the proxy to require them to contain a specific value in  the `aud` claim. (based on the work in #4135)
* For non JWT access tokes we would need to add support for querying the introspection endpoint ([see here](https://github.com/owncloud/ocis/issues/2967#issuecomment-1177356412))

@micbar @pmaier1 I think we need some guidance here on what is in  scope here for the release. (Or whether this (or parts of it) is something for later)

**Comment by TuxCoder** [comment]
Hello all,
I join the discussion as I not found this issue and accidantly created a new one, thanks to @micbar  for linking the issue.
I recommend to take a look there: https://github.com/owncloud/ocis/issues/4304

The nice solution is as @rhafer mention with ether JWT (what has some optional requirements to the IDP / clients),
or/and by doing a scope check with the `introspection endpoint`.

If you are going not to be a sub issuer of an external one, eg. allowing to used a shared IDP,
I really recommend to handle scopes proper, eg. define scopes for read/write/management/... access.

I think the "hack" with the `aud` paramter would be more like a workaround not also not bring all the benefits,
eg. one app as one token to access all the data required over multiple services.
I would also need to look into the standard how good it can be implemented,
specially the dynamic client registration could be fun.

Also using some keyclok features to remap stuff is not recommended, as it breaks easily compatibility, 
as I had with some other "features" from keyclok.

-> define scopes, check for it, other stuff is a hack


some refs/example usages for webdav scopes:

    https://www.oauth.com/oauth2-servers/scope/defining-scopes/
    https://developers.google.com/identity/protocols/oauth2/scopes#drive
    https://www.dropbox.com/developers/documentation/http/documentation

I think a good list to start with is, please comment on better suggestions:

    owncloud - access all ?needed?
    owncloud.manage - change settigns, all other stuff?
    owncloud-share - create share link
    owncloud-share.readonly - create readonly share link, needed?
    webdav - read/write access to webdav
    webdav.readonly - read only access to webdav

I'm a bit against a url as scope, as the url has not actual to do something with the current instance,
so IMHO a normal string is better, but is more a personal opinion

There are currently no definition for webdav read/write as fare as I knwon, but probably we can have a working suggestion?
would be awesome for compatibility between services / clients, but probably also not realistic :/

I'm also not so into the owncloud logic itself so I have from one hand a better from another hand worse suggestions.

If you have any question I can probably help a bit, play for like 2years with oauth2 server now.

**Comment by TuxCoder** [comment]
> Why do you think this is a hack? This is basically what is defined in RFC9068 (admittedly is still pretty fresh) which makes checking the aud claim a required step for validating an access token. I admit though, that we're not fully implementing what's defined in that RFC, as many providers do not implement that RFC yet.

I did't know about RFC9068 but as you mention it is pretty new and a optional extension to oauth2.
 -> do you know any supported servers?

The `aud` clams comes from OIDC not from JWT [1], or from other JWT RFC[2] as it is linked in OIDC but is newer, ...
It is older than 7years, ok.... :)
But also refrenced in rfc7519 !?
ok I'm a bit confused but here is my interpretation:

`aud` vs `scopes`
`aud` is part of OIDC but not of Oauth2, but the OCIS-Service is an Oauth2-ressorce server, not an OIDC server!
-> hack, _use something as not intended_


IMHO is the big benefit of oauth2 that you can restrict the right of a client / application. _This app can only read files, this can do read/writes, this application can also mange it (change settings, ...)_ and combine easily multiple services

The `aud` paramter can probably be used to limit the usage of the token, but you can not set the authorization in a restricted way.

The work to implement `aud` or implement `scope` is more or less the same,
implementeing the `introspection endpoint`, check the paramters (aud or scopes)
change clients
 - change reqesting param (aud or scope)
 - change default clients on server
 - change dynamic client registration param (aud or scope)

The biggest different is the definition of the scopes, but this also brings all the advantages.

Also from the security perspective you need at lest a separation to other application,
but scopes are completely fine and an additional `aud` is not needed.

In a OIDC context and I only going to use OIDC to login a user as this buttons "Login with $Company",
with the token_id is the usage of the `aud` something different, as you wanna check it.
This is the token that I requested, It contains there normally the client_id[3]

JWT vs  `introspection endpoint`
booth are ways to verify a token and get metadata.
Cons:
 - can not be revoked
 - lot of substandard with optional signing cipher
 - possible data leek, as token contains userdata, logging behavior / GDRP complains are more complicater

Pro:
 - can be verified decentralized


> As mentioned earlier in this https://github.com/owncloud/ocis/issues/2967#issuecomment-1144582080 we currently are not really using oauth for authorization. Mainly we're just using the OIDC layer on top of oauth for authentication. As you already noted in your original issue, adding support for scopes requires adjustments in a lot of places (basically all clients and most, if not all of the ocis services).

I mean your api / bearer auth is IMHO a great example how to implement a oauth2-resource server,
except from missing scope check.
But this is definitive  a oauth2-resource server and it is implemented as it, only missing the proper checks
eg. api (webdav, well-known urls, ...) is good, what is a big point IMHO

I also could get a token over `oidc-agent` and use it in rclone to have a working webdav mount to OCIS.
(and only needed some fixes for the official client, with ory/hydra)
depends on scopes I can use the same token for mail / calendar / ....

Example usecase:
At the moment I know davx5 as a great example, that would support webdav mounts and caldav/cardav,
only the oauth2 is missing there, after that it would work perfectly by having one token with rights to use webdav (ocis scope) and calendar (at the moment custom scopes) to use it in both services.
Without handling any password or be able to access more than needed. 

OCIS need to be adjusted on some places, but the most work is defining scopes and implement introspect api.
the rest is some config lines spreed over the clients / docu.

>  So this will be need a longer running effort and still requires quite a bit of additional research.
What is currently unclear or unsure to implement?


[1] https://openid.net/specs/openid-connect-core-1_0.html
[2] https://datatracker.ietf.org/doc/html/rfc7519
[3] https://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by rhafer** [comment]
> > , as many providers do not implement that RFC yet.
> 
> I did't know about RFC9068 but as you mention it is pretty new and a optional extension to oauth2. -> do you know any supported servers?

I don't know of any open-source implementation unfortunately. There see however to be a couple of commercial offering that claim to already support it.  And many servers that issue JWT access tokens should already be pretty close to the spec.

[..]

> IMHO is the big benefit of oauth2 that you can restrict the right of a client / application. _This app can only read files, this can do read/writes, this application can also mange it (change settings, ...)_ and combine easily multiple services
> 
> The `aud` paramter can probably be used to limit the usage of the token, but you can not set the authorization in a restricted way.

True. Remember that we only added this as a first step for doing a more thorough validation of the access token.

> JWT vs `introspection endpoint` booth are ways to verify a token and get metadata. 
> [..]

Right. In the longer run we want to implement both ways. We started the JWT based approach as it was an easy win. I am pretty
sure support for using the introspection endpoint will come rather sooner than later.

> > As mentioned earlier in this [#2967 (comment)](https://github.com/owncloud/ocis/issues/2967#issuecomment-1144582080) we currently are not really using oauth for authorization. Mainly we're just using the OIDC layer on top of oauth for authentication. As you already noted in your original issue, adding support for scopes requires adjustments in a lot of places (basically all clients and most, if not all of the ocis services).
> 
> I mean your api / bearer auth is IMHO a great example how to implement a oauth2-resource server, except from missing scope check. But this is definitive a oauth2-resource server and it is implemented as it, only missing the proper checks eg. api (webdav, well-known urls, ...) is good, what is a big point IMHO
> 
> I also could get a token over `oidc-agent` and use it in rclone to have a working webdav mount to OCIS. (and only needed some fixes for the official client, with ory/hydra) depends on scopes I can use the same token for mail / calendar / ....
> 
> Example usecase: At the moment I know davx5 as a great example, that would support webdav mounts and caldav/cardav, only the oauth2 is missing there, after that it would work perfectly by having one token with rights to use webdav (ocis scope) and calendar (at the moment custom scopes) to use it in both services. Without handling any password or be able to access more than needed.
> 
> OCIS need to be adjusted on some places, but the most work is defining scopes and implement introspect api. the rest is some config lines spreed over the clients / docu.

I don't want to argue with you much about that. Since I agree with most of what you are saying here ;-). We're simply not there yet and this will take some time. I just can't make much promises on how long it'll take us to get there. (And of course, as this is an open source project, patches are always welcome)

**Comment by TuxCoder** [comment]
Thank you very much for clarifying the road map!
For me it only sounded strange to start with JWT access token and I expected that owncloud was going into that direction only.

The new OICS implementation looks really good compared to most other stuff from the architecture,
so I'm interested in trying it out, probably a bit to excited.

I sadly not a `go`-programmer, reading is ok but would need some time to learn to write.
So I think I'm better on the testing side.

Will passion wait, and will do a test in my system as a release is ready :)

**Comment by micbar** [comment]
2.0.0-beta.6 was released yesterday which contains the token validation.

**Comment by micbar** [comment]
I am removing this from the beta board because we have achieved what is needed for GA.
