### ISSUE TITLE
Cannot share files with another user using 'owncloud' storage driver

### ISSUE THREAD

**Issue by rpocklin** [owncloud/ocis#2969]
## Describe the bug

Basic sharing fails on the published docker images for ocis.

## Steps to reproduce

1. Run the following:
```
OCIS_DOCKER_TAG=owncloud/ocis:1.16.0
DATA_DIR=/tmp/ocis
docker run --rm -ti -p 9200:9200 --env-file ./.env -v $DATA_DIR:/var/lib/ocis $OCIS_DOCKER_TAG
```

where the contents of `.env` is:
```
STORAGE_USERS_DRIVER=owncloud
STORAGE_HOME_DRIVER=owncloud
OCIS_LOG_LEVEL=warn
OCIS_INSECURE=true
PROXY_ENABLE_BASIC_AUTH=true
```
2.  Login as `admin:admin` via `https://localhost:9200` in Chrome.
3. Upload a small file (anything).
4. Attempt to share with demo user `marie`.
![image](https://user-images.githubusercontent.com/876651/149709904-ef4bd6e9-ef3f-4054-967b-85c91a01feb7.png)

## Expected behavior
Expected to work - it works fine if both references to the `owncloud` storage driver are not specified in the `.env` file, suggesting either `ocis` is the default storage driver, or something else (which i'm unsure about also).  If either `STORAGE_USERS_DRIVER` or `STORAGE_HOME_DRIVER` are defined, it the sharing fails.

## Actual behavior
Error screen appears.

Error logs from `ocis` docker instance:
```
{"level":"error","service":"storage","pkg":"rgrpc","error":"ocfs: error resolving reference: error: not found: 53148608-0709-4f3a-b247-ff1e89f487bd","time":"2022-01-17T04:49:21Z","caller":"/go/pkg/mod/github.com/cs3org/reva@v1.14.0/internal/grpc/services/storageprovider/storageprovider.go:1052","message":"error setting grants"}
{"level":"error","service":"storage","pkg":"rgrpc","error":"gateway: grpc failed with code CODE_INTERNAL","time":"2022-01-17T04:49:21Z","caller":"/go/pkg/mod/github.com/cs3org/reva@v1.14.0/internal/grpc/services/gateway/usershareprovider.go:574","message":"error committing share to storage grant"}
```

Error screenshot:
![image](https://user-images.githubusercontent.com/876651/149711550-e498f11f-8fda-45a1-93e4-4aaa3b28af64.png)

Occurs with v1.13.0, v1.15.0 and v1.16.0 of the oCIS docker images.

## Setup

Running on Windows / WSL2 with Docker 4.2.0 (Ubuntu shell)

## Additional context
I will do testing shortly on Mac/OSX to see if the host environment affects this behaviour.
I have tried clearing the `/tmp/ocis` folder and re-creating.  It removes the previously uploaded files but does not fix the issue.

**Comment by rpocklin** [comment]
Okay no worries - could I suggest the driver be deprecated in the code or removed completely?

**Comment by wkloucek** [comment]
Docs already mention it as deprecated, but I'll care for removing all code and references ;-) Thanks for this finding!

![image](https://user-images.githubusercontent.com/34452982/151946643-9c6975db-bb5d-4e25-8c72-ee44b5ea964c.png)

**Comment by rpocklin** [comment]
> Docs already mention it as deprecated, but I'll care for removing all code and references ;-) Thanks for this finding!
> 
> ![image](https://user-images.githubusercontent.com/34452982/151946643-9c6975db-bb5d-4e25-8c72-ee44b5ea964c.png)

Yes, I noticed they added that quietly a few days after I raised this PR =)
