### ISSUE TITLE
complete ownCloudSQL driver implementation on REVA edge

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2972]
## Is your feature request related to a problem? Please describe.
The ownCloud SQL driver in REVA edge is missing  the `ListStorageSpaces` implementation (https://github.com/cs3org/reva/blob/edge/pkg/storage/fs/owncloudsql/owncloudsql.go#L1953-L1956)

## Describe the solution you'd like
We can use the ownCloud SQL driver in oCIS with REVA edge and therefore the interface must be implemented completely

## Describe alternatives you've considered
- 

## Additional context
- Parallel deployment in oCIS was disabled after REVA ege was pulled in https://github.com/owncloud/ocis/pull/2955
- https://github.com/owncloud/ocis/issues/2950

**Comment by wkloucek** [comment]
@aduffeck can you please take care?

**Comment by aduffeck** [comment]
:+1: I'm on it

**Comment by wkloucek** [comment]
implementation was merged in oCIS with https://github.com/owncloud/ocis/pull/3052
