### ISSUE TITLE
Search sharee by username is broken

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#2999]
## Describe the bug
Searching a sharee by displayname seems to be broken, the backend only considers the username when searching for users.

## Steps to reproduce
1. run ocis v1.16.0
2. open webui
3. share folder with string 'marie c' -> works

1. run ocis from master
2. open webui
3. share folder with string 'marie c' -> does not work

request done by the frontend: `https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=marie%20c&itemType=folder&page=1&perPage=200&format=json`

## Expected behavior
find the user by displayname

## Actual behavior
only considers the username when searching for a sharee

https://github.com/cs3org/reva/blob/3d065e97841af9abbeb416ec03ff39c550b8e2bd/pkg/user/manager/ldap/ldap.go#L286-L292

**Comment by fschade** [comment]
cc ^ @rhafer

**Comment by phil-davis** [comment]
same as #2966 ?

**Comment by rhafer** [comment]
Yeah seems to be the same issue. Though it seems that my conclusion in #2966 is wrong. Need to take a closer look.

**Comment by fschade** [comment]
yup same, closing in favor of #2966
