### ISSUE TITLE
Viewer and editor has the possibility to disable the space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#3031]
ocis v.1.16.0 local
api-tests: https://github.com/owncloud/ocis/pull/3032

Failed scenarios: 

1. A user (role doesn't matter) can delete a Space use the webDav API
- for deleting personal space we use another method `curl -k -s -u admin:admin -X DELETE 'https://localhost:9200/graph/v1.0/drives/space_uuid' -H 'Purge: T'` 
- But we can drop space using `curl -k -s -u admin:admin -X DELETE 'https://localhost:9200/dav/spaces/space_uuid'` 
- I understand that the client will not call this method, but it is a vulnerability. We should probably disable using the method without parameters after space_uuid. Something like `405 Method Not Allowed`

2. A viewer/editor can disable space
3. A viewer/editor can delete space

- users call method `curl -k -s -u marie:radioactivity -X DELETE 'https://localhost:9200/graph/v1.0/drives/space_uuid' and get 204 (Expected: 403)
- after that, they can't see the space `curl -k -s -u marie:radioactivity -X GET 'https://localhost:9200/graph/v1.0/me/drives' because they haven't permissions. and they cannot delete space

**Comment by kobergj** [comment]
reva part is fixed here https://github.com/cs3org/reva/pull/2828

@ScharfViktor I'm returning `BadRequest` instead `MethodNotAllowed` when trying to delete a space via dav. That seemed more logical to me. I can update the test with the ocis PR.
Any objections?

**Comment by ScharfViktor** [comment]
> reva part is fixed here [cs3org/reva#2828](https://github.com/cs3org/reva/pull/2828)
> 
> @ScharfViktor I'm returning `BadRequest` instead `MethodNotAllowed` when trying to delete a space via dav. That seemed more logical to me. I can update the test with the ocis PR. Any objections?

405 was not a strict condition. "Bad request" is okay, too. Thanks for fixing

**Comment by kobergj** [comment]
PR was merged. Issue is solved
