### ISSUE TITLE
Create app provider new file fails

### ISSUE THREAD

**Issue by diocas** [owncloud/ocis#3034]
Probably should be in REVA, no?

We've added the new file creation (via app provider) in web (owncloud/web#5890) but now it's failing with a 500 from the server. The reply message we get is "error calling InitiateFileUpload" and I see some "user.ocis.quota: no data available" messages in the logs, but don't know if they are related.

**Comment by pascalwengerter** [comment]
@wkloucek let's look into this tomorrow, I've run into a bunch of errors around the app provider when trying out `web` stuff today

**Comment by wkloucek** [comment]
> @wkloucek let's look into this tomorrow, I've run into a bunch of errors around the app provider when trying out `web` stuff today

I already looked into it and also have a WIP PR (https://github.com/cs3org/reva/pull/2443) couldn't finish that though, because we broke compatibility to the WOPI server when merging edge. (ongoing discussion is happening how to proceed)

**Comment by wkloucek** [comment]
working on https://ocis.ocis-wopi.latest.owncloud.works/. Was fixed in https://github.com/cs3org/reva/pull/2869. Also described in https://github.com/owncloud/ocis/issues/3505
