### ISSUE TITLE
File version api for spaces is not implemented

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#3079]
## Describe 

Using the `new` WebDAV we can list file versions.

## Steps to reproduce

Steps to reproduce the behaviour:

1. create user `uu1`
2. upload `a.txt` with content 'upload version1'
3. upload `a.txt` with content 'upload version2'
4.  using spaces WebDAV API list file version
```bash
curl -vks -XPROPFIND -u uu1:password https://localhost:9200/remote.php/dav/meta/{fileid}/v | xmllint --format -

```
For spaces  I tired below endpoint.It return HTTP status code 404
```bash
curl -vks -XPROPFIND -u uu1:password https://localhost:9200/remote.php/dav/spaces/{spaceid}meta/{fileid}/v | xmllint --format -

```
### Question 

- Is there any endpoint in spaces for the file version?
- If the file version isn't implemented on spaces, will this feature will be implemented?

**Comment by phil-davis** [comment]
I added the "bug" label to stop the bot from closing this.

I guess that spaces will have versions ability? If so, how does the versions endpoint work for a space?

**Comment by ScharfViktor** [comment]
re-tested on v1.20.0

versions endpoint works for space. I suggest to close issue

`curl -vks -XPROPFIND -u uu1:password https://localhost:9200/remote.php/dav/meta/074c7aaf-5e6a-4a97-8d95-b97afc425379!1921c44e-f64d-453c-9e9b-dc0c569eed34/v | xmllint --format -
`
![Screenshot 2022-04-14 at 13 20 16](https://user-images.githubusercontent.com/84779829/163381295-b7072a81-25eb-46de-844c-bb143901897f.png)
