### ISSUE TITLE
trashbin api for spaces is not Implemented

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#3084]
### Description
using `new` webdav we can use the trash-bin API.
```bash
curl -XPROPFIND https://localhost:9200/dav/trash-bin/user1 -H 'Content-Type: application/xml; charset=UTF-8' -H 'Depth:1' -d '<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:prop></d:prop> </d:propfind>' -uuser1:123456 -kv | xmllint --format -

```
Does `spaces` webdav implemented for trash-bin API?

**Comment by C0rby** [comment]
It was implemented here: https://github.com/cs3org/reva/pull/2628
And merged to oCIS here: https://github.com/owncloud/ocis/pull/3330
