### ISSUE TITLE
can't access public link resources with spaces webdav API

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#3085]
### Description
Using the `new` WebDAV API, public link resources are accessed using the link token. But it cannot be performed using the spaces WebDAV since we do not have a proper user to request for the `spaceid`.

### Question
- Is there any way to access public link resources by public users using the spaces WebDAV API?
- If not will this feature ever be implemented?

**Comment by phil-davis** [comment]
@SagarGi please check if this is still a problem. If so, then we can add a tag so that the bot does not try to close this.

I guess that a public link should be able to be created and used on a resource in a space!

**Comment by SagarGi** [comment]
@phil-davis for a public accessing the public link for the resource, the space id still cannot be created (when public make a request using spaces WebDav API)

for the below request

`When the public lists the resources in the last created public link with depth "0" using the WebDAV API`

It says 

```console
getPersonalSpaceIdForUser webdav propfind for user cbDEADiQdnFCPsL failed with status 401 - so the personal space id cannot be discovered
```

**Comment by phil-davis** [comment]
@SagarGi I wonder why the test code has to try to find a space-id?

I thought that the "last created public link" would have a path like:
`http://172.17.0.1:8080/index.php/s/5kNPEAXJgpYCo58`

And that accessing that when accessing that "magic string" `5kNPEAXJgpYCo58` "share", the server will do whatever it needs to do in the back-end to find the resources(s) that are part of the public link (find the relevant space...)

I guess it is not relevant/useful for "the public" to discover public links by browsing space-ids and then browsing in the space to find public links that are offered for resources in the space. That would be a breach of public link security - a member of "the public" really has to know the "magic string" like `5kNPEAXJgpYCo58` to be allowed access to the resource(s).

So we should adjust such tests - probably just delete the examples for "public links using spaces webDAV API"?

@micbar or anyone - is my analysis correct?

**Comment by SagarGi** [comment]
@phil-davis i also think it is not relevant for the public as space-id is for a user. we have actually added spaces examples in some suites probably regarding this issue.

**Comment by phil-davis** [comment]
@butonic @micbar or? cc @individual-it 

We have the long-time-existing WebDAV endpoints which have a way to access public links using the public link token (and optional password, if set).

Going forward, will those remain the only ways to access a public link?

The public link may be a share of a "personal" resource, that is in the user's personal space, which has the personal space id of that user. The public link may be a share of a resource in a "project" space, which has a space id that different from any user.

Will there be any ways to access public links somehow via the "spaces" concept and endpoints?

**Comment by micbar** [comment]
> Is there any way to access public link resources by public users using the spaces WebDAV API?
They can only be accessed via the WebDAV endpoint with the link token.

example URL

`https://ocis.ocis-traefik.latest.owncloud.works/remote.php/dav/public-files/BjNhZgrkZTWJHej`
