### ISSUE TITLE
Document how to run parallel deployment tests locally.

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#3097]
Sometimes we may want to run parallel deployment tests in our own machine so it is good to have documentation on how to do that.

Todo:
- [x] Add/Update necessary setup configs if necessary
- [x] Add  documentation on how to run parallel deployment tests

**Comment by wkloucek** [comment]
Can't this be done with the docker-compose setup https://github.com/owncloud/ocis/tree/master/deployments/examples/oc10_ocis_parallel ?

**Comment by saw-jan** [comment]
Yes, we can use docker-compose setup from deployment examples but for the tests, we need to provide `oc10` server host as well as `ldap` server host which are only known via `docker inspect` (also the IP is dynamic).
If that would be fine then we might not need the extra setup. My intention was to create a similar setup like in drone setup for running the tests locally.

**Comment by wkloucek** [comment]
> 

You can just use the service names for dns resolution if you run the test suite also inside docker. Or we could add exposed ports to the example, so that you got the oC10 and LDAP ports available on your localhost. Would that help?

**Comment by saw-jan** [comment]
I will try that one. Thanks :+1:

**Comment by saw-jan** [comment]
@wkloucek I forgot the main thing. We also need to enable `testing` app in oc10 server which is not done in `deployments/examples`.
Should I update there like we do for drone? What would you suggest?

**Comment by wkloucek** [comment]
I'm ok with as long as we can hide it after a feature flag and it doesn't bloat too much ;-) It shouldn't be active by default since the main purpose of these examples is to educate people how to run stuff.
But you could just add another init shell script like [this](https://github.com/owncloud/ocis/blob/master/deployments/examples/oc10_ocis_parallel/config/oc10/10-custom-config.sh)
