### ISSUE TITLE
Document different deployments

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#31]
nexus should not only allow setting up
- [x] a developer environment with `make future` but also
- a production environment with
  - [ ] [kubernetes](https://github.com/owncloud/nexus/issues/11)?
  - [ ] [ansible](https://github.com/owncloud/nexus/issues/20)
  - [ ] docker swarm?

The idea is to give admins a recommended way to run ownCloud in production, including
- high availability,
- backup
- upgrades
- monitoring and
- incident reporting

**Comment by refs** [comment]
see https://github.com/owncloud/ocis/issues/30

**Comment by butonic** [comment]
outdated
