### ISSUE TITLE
Space change description doesn't work via GraphAPI Patch

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3103]
## Is your feature request related to a problem? Please describe.
Calling the endpoint PATCH `https://localhost:9200/graph/v1.0/drives/15c2a7cf-e649-454d-a6aa-f27326d75749` with payload
```
{"description":"New description"}: 
```
Will return 200, but the description won't change 

## Describe the solution you'd like
Make it work

**Comment by JanAckermann** [comment]
@C0rby @micbar FYI

**Comment by ScharfViktor** [comment]
Can confirm, change of description does not work
cases with the change of name and quota work

Steps
- add description: `curl -k -X PUT https://localhost:9200/dav/spaces/87907541-479f-4f8f-a5a8-9088547e9ac8/.space/description.md -d "Add a description to your spaces" -u admin:admin`
- see description: `curl -k https://localhost:9200/dav/spaces/87907541-479f-4f8f-a5a8-9088547e9ac8/.space/description.md -u admin:admin`
- change description `curl -k -X PATCH https://localhost:9200/graph/v1.0/drives/87907541-479f-4f8f-a5a8-9088547e9ac8 -d '{"name":"newName", "quota": {"total": 20}, "description": "newDescr"}' -u admin:admin`

Result
- name changed
- quota changed
- description has not changed

**Comment by C0rby** [comment]
I guess changing the description and space image via the API is not implemented yet but is planned AFAIK.

**Comment by micbar** [comment]
yes. will improve.
The space.yaml was a first shot.

But clients should not be aware of that file.

We provide all information via the API in the future.

**Comment by micbar** [comment]
was fixed by #3168

**Comment by micbar** [comment]
works with `POST` on the initial creation and with `PATCH` now.
