### ISSUE TITLE
Renaming a Space works in list endpoint, single get still shows the old name

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3104]
## Describe the bug

Renaming a Space works in list endpoint, single get still shows the old name

## Steps to reproduce

1. Rename a Space
2. List drives shows the new name
3. Get single drive shows the old name

## Expected behavior
Get single drive should show the new name

## Actual behavior
Get single drive shows the old name

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by JanAckermann** [comment]
FYI @C0rby @micbar

**Comment by micbar** [comment]
thanks, will take a look now

**Comment by micbar** [comment]
@butonic @kobergj It is a caching issue in the gateway or in the registry.

It only happens when i send a filter by id in the cs3api request.

**Comment by micbar** [comment]
@JanAckermann fix in https://github.com/cs3org/reva/pull/2500

**Comment by micbar** [comment]
merged, needs update in ocis.

will be part of #3094 correct? @kobergj ?

**Comment by kobergj** [comment]
Yes. I will update reva in https://github.com/owncloud/ocis/pull/3094 after https://github.com/cs3org/reva/pull/2458 is merged

**Comment by micbar** [comment]
#3094 is merged
