### ISSUE TITLE
excessive thread count and excessife filedscriptor count

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#311]
I've started an ocis-eos instance according compose-playground/examples/eos-compose instrutions.

We have several hundred `xrootd` threads, each of them with ca 100 filedscriptors open. Most of them on sockets and pipes.
I asume that many of the threads or filedescriptors are redundant.

```
$ ps -eLf | grep xrootd | wc -l
654
```

See attached lsof output for a list of filedescriptors.
[ocis-eos-3h-idle-lsof.txt.zip](https://github.com/owncloud/ocis/files/4776880/ocis-eos-3h-idle-lsof.txt.zip)

Good news: The amount of process threads and filedescriptors is still roughly the same after 4 hours of waiting.

**Comment by IljaN** [comment]
Maybe related to https://github.com/owncloud/ocis/issues/268 and thus fixed, please retest with beta5

**Comment by jnweiger** [comment]
Retested with rc1: Seems one leak was fixed, now another one surfaced. Details tracked in #268 - closing here.
