### ISSUE TITLE
Don't create a .space folder while adding a new space

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3112]
## Is your feature request related to a problem? Please describe.
Since we don't rely on a .space folder, we don't want to create it while adding a new space

## Describe the solution you'd like
Don't create a .space folder

**Comment by JanAckermann** [comment]
FYI @micbar @butonic @C0rby

**Comment by micbar** [comment]
was fixed by https://github.com/cs3org/reva/pull/2519
