### ISSUE TITLE
Decomposed FS: Prevent code from broken metadata

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#3114]
## Describe the bug

For example, if in `func SetMetadata()` we're setting multiple xattr's in a row. The method is left if any of the xattrs fails. However, actually the previously changed xattr's should be rewinded in case one of the latter fails to maintain consistent meta data.

Reference example:
https://github.com/cs3org/reva/blob/17606d3fbadf41bd3656a82472e19ddc51e5221c/pkg/storage/utils/decomposedfs/node/node.go#L126

## Steps to reproduce

This is hard to reproduce, but can be seen in code review. This would be very hard to debug later...

## Expected behavior

If we can not set all metadata, set none to not leave inconsistencies behind.

There might be more examples in the code for similar behaviour.

**Comment by kobergj** [comment]
Implemented meanwhile afaik.
