### ISSUE TITLE
add spaces webdav for apiWebdavUpload1 suite

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#3124]
### Description
- add spaces WebDAV URL for `apiWebdavUpload1` suite from `oc/core`
- includes:
  - uploadFile.feature
  - uploadFileAsyncUsingChunking.feature
  - uploadFiletoBlacklistedName.feature
  - uploadFileToBlacklistedNameAsyncNewChunkinf.feature
  - uploadFileToExcludeDirectory.feature
  - uploadFileToExcludedDirectoryAsyncUsingNewChunking.feature

### Related
- part of https://github.com/owncloud/ocis/issues/2854

**Comment by SwikritiT** [comment]
The PR for this issue has been merged. Closing this
