### ISSUE TITLE
add spaces webdav for apiShareOperationsToShare1 suite

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#3136]
### Description
- add spaces WebDAV URL for `apiShareOperationsToShare1` suite from `oc/core`
- includes:
  - accessToShare.feature
  - accessToSharesFolders.feature
  - changingFilesShares.feature
  - gettingShares.feature
  - gettingSharesPendingFiltered.feature
  - gettingSharesReceivedFiltered.feature
  - gettingSharesReceivedFilteredEmpty.feature
  - gettingSharesSharedFiltered.feature
  - gettingSharesSharedFilteredEmpty.feature

### Related
- part of https://github.com/owncloud/ocis/issues/2854

**Comment by SwikritiT** [comment]
The PR for this issue has been merged closing this
