### ISSUE TITLE
Webdav endpoint fails (immediately after logging in)

### ISSUE THREAD

**Issue by rpocklin** [owncloud/ocis#3152]
## Describe the bug

Running the example docker compose containers located [here](https://github.com/rpocklin/ocis/tree/ocis-docker-proxy/deployments/examples/ocis_proxy) starts up the `ocis server` successfully every time, however, when navigating to and logging in to `https://ocis.owncloud.test" (using 'admin:admin') sometimes (but not every time) the following request fails, which is executed by the frontend after logging in:

PROPFIND https://ocis.owncloud.test/remote.php/webdav/

Giving a result of 404 (not found).

I believe there may be a dependency-ordering or internal configuration related issue when the server starts up, given that this does not occur consistently it may be a temporal issue related to when services start and their order.

## Steps
1.  Start up docker compose containers (eg. using `start.sh`)
2. Navigate to https://ocis.owncloud.test (you may have to add a host alias of 127.0.0.1)
3. Login as 'admin:admin'
4. View the network tab (open before logging in) and check the response from the following request (PROPFIND) **https://ocis.owncloud.test/remote.php/webdav/**
5. Verify if you can see any folders or be able to upload files in the UI (eg. can see 'Shares' folder).

## Expected behavior
The user logs in successfully without any failed API requests, repeatedly, the webdav API call should return a 207 response code with a payload.

## Actual behavior
Every 3rd or 4th time the API request fails with a 404 (proxy makes request to storage-frontend which fails).

![image](https://user-images.githubusercontent.com/876651/153524529-30244b9d-ac53-4acc-be89-8c4f40fa002f.png)

Error log from ocis container:
```
{"level":"debug","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"grpc-go/1.44.1-dev","from":"tcp://127.0.0.1:48818","uri":"/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProviders","start":"11/Feb/2022:01:30:07 +0000","end":"11/Feb/2022:01:30:07 +0000","time_ns":103300,"code":"OK","time":"2022-02-11T01:30:07Z","message":"unary"}

{"level":"error","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"Decomposedfs: root has no parent","status":{"code":15,"message":"error creating space","trace":"00000000000000000000000000000000"},"request":{"opaque":{"map":{"space_id":{"decoder":"plain","value":"ZGRjMjAwNGMtMDk3Ny0xMWViLTlkM2YtYTc5Mzg4OGNkMGY4"}}},"owner":{"id":{"idp":"https://ocis.owncloud.test","opaque_id":"ddc2004c-0977-11eb-9d3f-a793888cd0f8","type":1},"username":"admin","mail":"admin@example.org","mail_verified":true,"display_name":"Admin","groups":["users"],"opaque":{"map":{"roles":{"decoder":"json","value":"WyI3MTg4MTg4My0xNzY4LTQ2YmQtYTI0ZC1hMzU2YTJhZmRmN2YiXQ=="}}},"uid_number":20004,"gid_number":30000},"type":"personal","name":"Admin"},"time":"2022-02-11T01:30:07Z","message":"failed to create storage space"}

{"level":"debug","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"grpc-go/1.44.1-dev","from":"tcp://127.0.0.1:43778","uri":"/cs3.storage.provider.v1beta1.ProviderAPI/CreateStorageSpace","start":"11/Feb/2022:01:30:07 +0000","end":"11/Feb/2022:01:30:07 +0000","time_ns":127600,"code":"OK","time":"2022-02-11T01:30:07Z","message":"unary"}

{"level":"debug","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"grpc-go/1.44.1-dev","from":"tcp://127.0.0.1:48750","uri":"/cs3.gateway.v1beta1.GatewayAPI/CreateHome","start":"11/Feb/2022:01:30:07 +0000","end":"11/Feb/2022:01:30:07 +0000","time_ns":1073000,"code":"OK","time":"2022-02-11T01:30:07Z","message":"unary"}

2022-02-11T01:30:07Z ERR error when calling Createhome error="gateway: grpc failed with code CODE_INTERNAL" service=proxy

2022-02-11T01:30:07Z DBG director found path=/remote.php/webdav/ policy=ocis prefix=/remote.php/ routeType=prefix service=proxy

{"level":"debug","service":"storage","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2022-02-11T01:30:07Z","message":"access token is already provided"}
```
## Setup

This container uses the `owncloud/ocis:latest` docker image tag pulled from dockerhub.

**Comment by kulmann** [comment]
Thank you for your bug report. This perfectly describes all the systems of the underlying https://github.com/owncloud/ocis/issues/2995 - @rpocklin could you add your issue description (including image and everything) as a comment to that ticket and close here?

**Comment by rpocklin** [comment]
> Thank you for your bug report. This perfectly describes all the systems of the underlying #2995 - @rpocklin could you add your issue description (including image and everything) as a comment to that ticket and close here?

Done.
