### ISSUE TITLE
0 byte TUS upload results in an 500 error

### ISSUE THREAD

**Issue by gabi18** [owncloud/ocis#3154]
Here the log of the upload.
```
02-11 09:57:18:631 [ info sync.httplogger ]:	"70a906aa-7baa-4a75-8d6f-94e341e4a709: Request: POST https://ocis.ocis-traefik.latest.owncloud.works/remote.php/dav/files/admin/ Header: { X-OC-Mtime: 1644569723, Content-Type: application/offset+octet-stream, Content-Length: 0, Upload-Offset: 0, Tus-Resumable: 1.0.0, Upload-Metadata: filename L05ldWVyIE9yZG5lci9OZXcgQml0bWFwIGltYWdlLmJtcA==,checksum U0hBMSBkYTM5YTNlZTVlNmI0YjBkMzI1NWJmZWY5NTYwMTg5MGFmZDgwNzA5, Upload-Length: 0, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Windows) mirall/2.10.1git (ownCloud, windows-10.0.22000 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: 70a906aa-7baa-4a75-8d6f-94e341e4a709, Original-Request-ID: 70a906aa-7baa-4a75-8d6f-94e341e4a709, } Data: []"
02-11 09:57:18:634 [ info sync.httplogger ]:	"2bcb7b53-dd4f-4383-8508-801a48ba1aba: Response: POST 500 https://ocis.ocis-traefik.latest.owncloud.works/remote.php/dav/files/admin/ Header: { Access-Control-Allow-Headers: Tus-Resumable, Upload-Length, Upload-Metadata, If-Match, Access-Control-Allow-Origin: *, Access-Control-Expose-Headers: Tus-Resumable, Location, Content-Length: 0, Content-Security-Policy: default-src 'none';, Date: Fri, 11 Feb 2022 08:57:17 GMT, Location: https://ocis.ocis-traefik.latest.owncloud.works/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjQ0NjU2MjM3LCJpYXQiOjE2NDQ1Njk4MzcsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1OC9kYXRhL3R1cy8wN2EwODIwYS1iNjZmLTQ3NWUtOTBjYS0xZmY1YzhmYzhjMmUifQ.QUpi4AxMvTARME9jU0WFHgPFzRAtVR94IKzpPpW8CCs, Tus-Extension: creation,creation-with-upload,checksum,expiration, Tus-Resumable: 1.0.0, Upload-Expires: , Upload-Offset: 0, Vary: Origin, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block, } Data: []"
```
--------

Seen with ownCloud-2.10.0-rc3.

Steps to reproduce:
- login to ocis.ocis-traefik.latest.owncloud.works -> login is successful
- open Explorer and create a new file

Result:
Client shows a red error message "Host requires authentication" for a while, then the 'i' and message is shown in 'Not synced' tab.

 
![ocis-file-upload](https://user-images.githubusercontent.com/75983861/148926413-30aadecc-c84e-41d2-8785-76cd34e09e6c.png)

[20220105_1143_owncloud.log.0.gz](https://github.com/owncloud/client/files/7845727/20220105_1143_owncloud.log.0.gz)
[20220105_1142_owncloud.log.2.gz](https://github.com/owncloud/client/files/7845729/20220105_1142_owncloud.log.2.gz)
[20220105_1142_owncloud.log.1.gz](https://github.com/owncloud/client/files/7845730/20220105_1142_owncloud.log.1.gz)
[20220105_1142_owncloud.log.0.gz](https://github.com/owncloud/client/files/7845731/20220105_1142_owncloud.log.0.gz)
[20220105_1059_owncloud.log.0.gz](https://github.com/owncloud/client/files/7845732/20220105_1059_owncloud.log.0.gz)
 
Download of files works.

**Comment by C0rby** [comment]
It seems to have something to do with the content-type header.

This request results in a 500 server error
```
curl -sk -u admin:admin -X POST https://localhost:9200/remote.php/dav/files/admin/ -H 'Content-Length: 0' -H 'Upload-Offset: 0' -H 'Tus-Resumable: 1.0.0' -H 'Upload-Metadata: filename emVyb2J5dGVz' -H 'Upload-Length: 0' -H 'Content-Type: application/offset+octet-stream'
```

This one without the content-type header works
```
curl -sk -u admin:admin -X POST https://localhost:9200/remote.php/dav/files/admin/ -H 'Content-Length: 0' -H 'Upload-Offset: 0' -H 'Tus-Resumable: 1.0.0' -H 'Upload-Metadata: filename emVyb2J5dGVz' -H 'Upload-Length: 0'
```

**Comment by C0rby** [comment]
Hm after debugging a bit it seems to have something to do with our changes regarding zero byte file uploads: https://github.com/cs3org/reva/pull/2309

The file is never actually being written and in the end when we try to stat the uploaded file it fails because it wasn't created...

**Comment by C0rby** [comment]
So the issue is that TUS expects that a 0 byte upload is finished early. See this line: https://github.com/tus/tusd/blob/0d781500f958e2d69098bc485aa2575f23ee3270/pkg/handler/unrouted_handler.go#L406

But when we are uploading a file we aren't actually using the TUS handler, instead we have our own handler which is initiating a new upload. https://github.com/cs3org/reva/blob/d217886c962b05ab7aa751923016e3ccb4dd7534/internal/http/services/owncloud/ocdav/tus.go#L195

Then we call the datatx handler for the actual upload. https://github.com/cs3org/reva/blob/d217886c962b05ab7aa751923016e3ccb4dd7534/internal/http/services/owncloud/ocdav/tus.go#L242

Since this is a patch request we end up in this handler which ends prematurely for 0 byte uploads. https://github.com/tus/tusd/blob/0d781500f958e2d69098bc485aa2575f23ee3270/pkg/handler/unrouted_handler.go#L540-L544

I think a possible solution could be to call `TouchFile` for 0 byte uploads but this isn't implemented yet.

**Comment by micbar** [comment]
@C0rby TouchFile is the best solution IMO, the EOS driver implemented it some weeks ago.

**Comment by gabi18** [comment]
The current behaviour when uploading a 0 byte file for 'einstein' to ocis.owncloud.com is that the path shown ".../dav/spaces/..." not ".../dav/files..." as before.
![0-byte_upload](https://user-images.githubusercontent.com/75983861/166887825-fa3de9f9-8736-452e-b26f-c58f9b975610.png)

**Comment by gabi18** [comment]
Retested with testpilotcloud 3.0.0.7819-daily20220617 (on openSUSE 15.3) and oCIS 2.0.0-beta.4+ba9a48a51 (docker)

Steps done:
- open file browser 
- create a new file

Result: file isn't synced, 'Not synced tab' shows "500 Internal Server Error"

![0-byte-error](https://user-images.githubusercontent.com/75983861/175893555-22f09051-9fb5-4245-b8cb-bda8444bec10.png)


```
06-27 10:07:37:024 [ info sync.httplogger ]:	"d265ff0d-182a-4ae1-8efb-a8b02d309b81: Request: POST https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 Header: { X-OC-Mtime: 1656317254, Content-Type: application/offset+octet-stream, Content-Length: 2, Upload-Offset: 0, Tus-Resumable: 1.0.0, Upload-Metadata: filename L1RleHQgRmlsZS50eHQ=,checksum U0hBMSBkZDEyMjU4MWM4Y2Q0NGQwMjI3ZjljMzA1NTgxZmZjYjRiNmYxYjQ2, Upload-Length: 2, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Linux) mirall/3.0.0.7819-daily20220617 (testpilotcloud, opensuse-leap-5.3.18-150300.59.71-default ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: d265ff0d-182a-4ae1-8efb-a8b02d309b81, Original-Request-ID: d265ff0d-182a-4ae1-8efb-a8b02d309b81, } Data: [2 bytes of application/offset+octet-stream data]"
06-27 10:07:37:024 [ info sync.networkjob ]:	Created OCC::SimpleNetworkJob("https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51","POST", "d265ff0d-182a-4ae1-8efb-a8b02d309b81", "d265ff0d-182a-4ae1-8efb-a8b02d309b81") for OCC::PropagateUploadFileTUS(0x4d0d710)
06-27 10:07:37:030 [ info gui.socketapi ]:	Received SocketAPI message <-- "RETRIEVE_FILE_STATUS:/home/gabriele/testpilotcloud - Albert Einstein@localhost/Personal" from QLocalSocket(0x2b0d830)
06-27 10:07:37:030 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:SYNC:/home/gabriele/testpilotcloud - Albert Einstein@localhost/Personal" to QLocalSocket(0x2b0d830)
06-27 10:07:37:034 [ info sync.httplogger ]:	"d265ff0d-182a-4ae1-8efb-a8b02d309b81: Response: POST 500 (Error: Error transferring https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 - server replied: Internal Server Error) https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 Header: { Access-Control-Allow-Headers: Tus-Resumable, Upload-Length, Upload-Metadata, If-Match, Access-Control-Allow-Origin: *, Access-Control-Expose-Headers: Tus-Resumable, Location, Content-Length: 0, Content-Security-Policy: default-src 'none';, Date: Mon, 27 Jun 2022 08:07:37 GMT, Location: https://localhost:9200/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjU2NDAzNjU3LCJpYXQiOjE2NTYzMTcyNTcsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1OC9kYXRhL3R1cy82YmFkMDlkZi1kYTI3LTQ1NGUtYjc2YS0yMmU4MzVmZDMzMTgifQ.CQKGraAK2L7BHTLhwLJeMoAv_RWQZ4WHEPg-xtC4IgY, Tus-Extension: creation,creation-with-upload,checksum,expiration, Tus-Resumable: 1.0.0, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block, } Data: []"
06-27 10:07:37:034 [ warning sync.networkjob ]:	OCC::SimpleNetworkJob("https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51","POST", "d265ff0d-182a-4ae1-8efb-a8b02d309b81", "d265ff0d-182a-4ae1-8efb-a8b02d309b81", "Error transferring https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 - server replied: Internal Server Error") QNetworkReply::InternalServerError "Server replied \"500 Internal Server Error\" to \"POST https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51\"" 500
06-27 10:07:37:034 [ debug sync.propagator.upload.tus ]	[ OCC::PropagateUploadFileTUS::slotChunkFinished ]:	"/Text File.txt" "POST"
06-27 10:07:37:034 [ debug sync.propagator.upload ]	[ OCC::PropagateUploadFileCommon::commonErrorHandling ]:	""
06-27 10:07:37:034 [ warning sync.propagator.upload ]:	void OCC::PropagateUploadFileCommon::abortWithError(OCC::SyncFileItem::Status, const QString&) "Text File.txt" "Server replied \"500 Internal Server Error\" to \"POST https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51\""
```

[testpilotcloud.log.0-byte-error.gz](https://github.com/owncloud/ocis/files/8989982/testpilotcloud.log.0-byte-error.gz)

**Comment by gabi18** [comment]
With the same test setup as above ( testpilotcloud 3.0.0.7819-daily20220617, oCIS 2.0.0-beta.4+ba9a48a51) the server also replies the 500 internal error now when trying to upload a non empty file (TextFile.txt, 16 bytes) to 'Personal'.

Uploading a small file was successful before with earlier versions of client and oCIS. I will check which versions...

![server-error](https://user-images.githubusercontent.com/75983861/175932992-9f83e57f-b46c-4114-9689-3db2d339b51f.png)

![file-upload-error](https://user-images.githubusercontent.com/75983861/175931562-347157c9-b366-4eb7-9f1c-5b5a4c65733d.png)

```
06-27 11:29:58:960 [ info sync.httplogger ]:	"e42aaa7d-8d68-4708-a12d-4e920ffc0ae7: Request: POST https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 Header: { X-OC-Mtime: 1656322070, Content-Type: application/offset+octet-stream, Content-Length: 16, Upload-Offset: 0, Tus-Resumable: 1.0.0, Upload-Metadata: filename L1RleHRGaWxlLnR4dA==,checksum U0hBMSA0M2QwOTZhYjkwYWUzOTliMTRlMTU3OGZiYTM0NWMwNDZlN2U5ODZm, Upload-Length: 16, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Linux) mirall/3.0.0.7819-daily20220617 (testpilotcloud, opensuse-leap-5.3.18-150300.59.71-default ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: e42aaa7d-8d68-4708-a12d-4e920ffc0ae7, Original-Request-ID: e42aaa7d-8d68-4708-a12d-4e920ffc0ae7, } Data: [16 bytes of application/offset+octet-stream data]"
06-27 11:29:58:960 [ info sync.networkjob ]:	Created OCC::SimpleNetworkJob("https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51","POST", "e42aaa7d-8d68-4708-a12d-4e920ffc0ae7", "e42aaa7d-8d68-4708-a12d-4e920ffc0ae7") for OCC::PropagateUploadFileTUS(0x355e0b0)
06-27 11:29:58:971 [ info sync.httplogger ]:	"e42aaa7d-8d68-4708-a12d-4e920ffc0ae7: Response: POST 500 (Error: Error transferring https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 - server replied: Internal Server Error) https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 Header: { Access-Control-Allow-Headers: Tus-Resumable, Upload-Length, Upload-Metadata, If-Match, Access-Control-Allow-Origin: *, Access-Control-Expose-Headers: Tus-Resumable, Location, Content-Length: 0, Content-Security-Policy: default-src 'none';, Date: Mon, 27 Jun 2022 09:29:58 GMT, Location: https://localhost:9200/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjU2NDA4NTk4LCJpYXQiOjE2NTYzMjIxOTgsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1OC9kYXRhL3R1cy9jMzgyMjg5ZC00M2I5LTQ2MWYtYTYyYy03NDE2N2JmMDFlY2IifQ.5beLfud0Mep9KyhVq_k5P9unL8glJXG35qA43s6bluE, Tus-Extension: creation,creation-with-upload,checksum,expiration, Tus-Resumable: 1.0.0, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block, } Data: []"
06-27 11:29:58:971 [ warning sync.networkjob ]:	OCC::SimpleNetworkJob("https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51","POST", "e42aaa7d-8d68-4708-a12d-4e920ffc0ae7", "e42aaa7d-8d68-4708-a12d-4e920ffc0ae7", "Error transferring https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51 - server replied: Internal Server Error") QNetworkReply::InternalServerError "Server replied \"500 Internal Server Error\" to \"POST https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51\"" 500
06-27 11:29:58:971 [ debug sync.propagator.upload.tus ]	[ OCC::PropagateUploadFileTUS::slotChunkFinished ]:	"/TextFile.txt" "POST"
06-27 11:29:58:971 [ debug sync.propagator.upload ]	[ OCC::PropagateUploadFileCommon::commonErrorHandling ]:	""
```
[TextFile.log.gz](https://github.com/owncloud/ocis/files/8991554/TextFile.log.gz)

**Comment by gabi18** [comment]
Uploading a non empty file to ocis.ocis-traefik.released.owncloud.works (Beta3) using testpilotcloud 3.0.0.7819-daily20220617 works without error.

**Comment by gabi18** [comment]
Another logfile from a test with  testpilotcloud 3.0.0.7819-daily20220617, oCIS 2.0.0-beta.4+ba9a48a51 and file with 0 byte (the file created in 'dolphin' in https://github.com/owncloud/ocis/issues/3154#issuecomment-1167039505 has in fact 2 bytes).

[ocis-0-byte.log.gz](https://github.com/owncloud/ocis/files/8998295/ocis-0-byte.log.gz)

**Comment by TheOneRing** [comment]
Appears to be an unrelated issue, works fine with the traefik example.

**Comment by gabi18** [comment]
> Another logfile from a test with testpilotcloud 3.0.0.7819-daily20220617, oCIS 2.0.0-beta.4+ba9a48a51 and file with 0 byte (the file created in 'dolphin' in [#3154 (comment)](https://github.com/owncloud/ocis/issues/3154#issuecomment-1167039505) has in fact 2 bytes).
> 
> ```
> 06-28 08:35:09:628 [ info sync.httplogger ]:	"4212fddf-0455-48c8-a377-fd7e30d98673: Request: GET https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c/NullByte.txt Header: { Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Linux) mirall/3.0.0.7819-daily20220617 (testpilotcloud, opensuse-leap-5.3.18-150300.59.71-default ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: 4212fddf-0455-48c8-a377-fd7e30d98673, Original-Request-ID: 4212fddf-0455-48c8-a377-fd7e30d98673, } Data: []"
> ...
> 06-28 08:35:09:643 [ info sync.httplogger ]:	"4212fddf-0455-48c8-a377-fd7e30d98673: Response: GET 500 (Error: Error transferring https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c/NullByte.txt - server replied: Internal Server Error) https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c/NullByte.txt Header: { Access-Control-Allow-Origin: *, Content-Length: 0, Content-Security-Policy: default-src 'none';, Date: Tue, 28 Jun 2022 06:35:09 GMT, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block, } Data: []"
> ```
> 
> [ocis-0-byte.log.gz](https://github.com/owncloud/ocis/files/8998295/ocis-0-byte.log.gz)

-> this logging is from downloading a 0 byte file

**Comment by gabi18** [comment]
Confirmed fixed with ocis.ocis-traefik.released.owncloud.works productversion: "2.0.0-beta.4" (client: ownCloud-3.0.0-daily20220628.7878.x64.msi)

**Comment by thrhgh** [comment]
Hi guys.
According to this thread, the issue should be resolved in the current release.

However, I just receive the same issue with 0 byte transfers in the current ownCloud ocis server (4.0) which I run as a docker container and with the 4.2 Linux Desktop client on Fedora.

![0bytetransfer](https://github.com/owncloud/ocis/assets/69689551/087fc89a-4af6-4733-af07-048dbf0f1e9f)

Any suggestions on how to fix it?
