### ISSUE TITLE
WebDAV reads get stuck

### ISSUE THREAD

**Issue by rontrompert** [owncloud/ocis#3156]
## Describe the bug

Reading files from OCIS using webdav get stuck.

## Steps to reproduce

1. docker pull owncloud/ocis
2. docker run --rm -ti -p 9200:9200 -v /my/dir/:/var/lib/ocis/ -e OCIS_INSECURE=true -e PROXY_ENABLE_BASIC_AUTH=true owncloud/ocis
3. rclone copy --transfers=4 --no-check-certificate myfiles/ ocis:myfiles
4. rclone copy --transfers=4 --no-check-certificate ocis:myfiles copyofmyfiles

## Expected behavior
After pulling and running the container and uploading a directory with files the entire folder is downloaded again. You would expect it to be completely downloaded. 

## Actual behavior
In mid air transfers get stuck. The server logs no errors. It just hangs.

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
docker pull owncloud/ocis
docker run --rm -ti -p 9200:9200 -v /my/dir/:/var/lib/ocis/ -e OCIS_INSECURE=true -e PROXY_ENABLE_BASIC_AUTH=true owncloud/ocis
```
</p>
</details>

## Additional context
The same problem occurs using only 1 stream to download the file. This is the rclone config file:
```
[ocis]
type = webdav
url = https://hostname:9200/remote.php/webdav/
vendor = owncloud
user = einstein
pass = something garbled
```
Replacing 'vendor=owncloud' by 'vendor=other' yields the same result. It is also not rclone related since the same happens using curl. 
When a file gets stuck (file19 in this case) the server logs the following:
```
{"level":"info","service":"storage","pkg":"rgrpc","data-server":"http://localhost:9155/data","ref":{"path":"/home/100files/file19"},"time":"2022-02-11T13:34:08Z","message":"file download"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request":"f2c53685fb2a/0XINyFycE5-000938","remote-addr":"127.0.0.1:45900","method":"GET","status":200,"path":"/data","duration":607.662598,"bytes":100000000,"time":"2022-02-11T13:34:09Z","message":"access-log"}
```

**Comment by micbar** [comment]
@rontrompert I tried to reproduce your problem

How big was your directory?

I uploaded and downloaded an extracted complete tarball from oc10 locally. It worked without errors.

Did you see any errors in the ocis log?

**Comment by rontrompert** [comment]
The directory contained 100 files.

**Comment by micbar** [comment]
ok, i tested with several thousand small files.

**Comment by rontrompert** [comment]
When I test it when the container runs on the same host as where I am running the rclone command, then everything looks fine. But when rclone runs on an other host then things get stuck.

**Comment by kobergj** [comment]
To old. Probably fixed meanwhile.
