### ISSUE TITLE
Re-adding a removed user to a space results in an error

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#3183]
## Steps to reproduce

1. Add a user to a space: `curl -k -s -u admin:admin 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' -H 'Content-Type: application/x-www-form-urlencoded' -d 'space_ref=760d266c-9d15-437b-bb1d-289667938517&shareType=0&shareWith=einstein&role=viewer' -i`
2. Remove that user: `curl -k -s -X DELETE -u admin:admin 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/760d266c-9d15-437b-bb1d-289667938517?shareWith=einstein'`
3. Try to add the user again

## Expected behavior
This should work without error.

## Actual behavior
The following error occours: `error sending a grpc create share request`. Other users can still be added, it only affects users that where removed once.

@C0rby @micbar fyi

**Comment by C0rby** [comment]
Strange, I tested exactly this scenario when I was working on this but I'll take another look.

**Comment by C0rby** [comment]
Are those your actual requests? I'm asking because you are setting the shareType to '0' (= user share) instead of '7' (= spaces membership)

**Comment by C0rby** [comment]
No, worries. :muscle:
