### ISSUE TITLE
Expand the drive GET-endpoints with user information

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#3195]
Currently I can get the userIds for a drive while querying the drive:

```
"permissions":[
               {
                  "grantedTo":[
                     { "user":{ "id":"ddc2004c-0977-11eb-9d3f-a793888cd0f8" } },
                     { "user":{ "id":"ddc2004c-0977-11eb-9d3f-a793888cd0f9" } }
                  ]
               }
            ],
```

To get the actual user information, I need to query all those ids separately. It would be nice to make use of the graph API and add a possibility for clients to expand the query to also include user objects.

Alternatively a user-list-query where I can filter via an array of userIds would be handy.

**Comment by micbar** [comment]
Implemented on the user endpoint.
