### ISSUE TITLE
Oauth: Preselecting user during authentication stopped working

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/ocis#3196]
## Describe the bug

When re authenticating the desktop client, we pass the username for the account that requires authentication.
```
https://ocis.ocis-traefik.latest.owncloud.works/signin/v1/identifier?client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&code_challenge=l24oTnpkqaqjEFbNCPtFrvE37hPpmYZmvqFRUmHDX8U&code_challenge_method=S256&flow=oidc&login_hint=einstein&prompt=select_account+consent&redirect_uri=http%3A%2F%2F127.0.0.1%3A62130&response_type=code&scope=openid+offline_access+email+profile&state=PNx9VUd7T4aHxxj1sqqnbei73EBWB4Gav8TZdJ3eSVo%3D&user=einstein
```

In the past, that user was preselected in the login ui.
It seems this is no longer the case.

## Steps to reproduce

1. Register an account with the desktop client
2. Log out
3. Log in

## Expected behavior
The user is preselected.

## Actual behavior
![image](https://user-images.githubusercontent.com/200626/154652516-0d67c099-379a-4f55-8eb2-26a353e10f3f.png)

## Setup
https://ocis.ocis-traefik.latest.owncloud.works/

**Comment by micbar** [comment]
Same on the remote instance

````
https://ocis.ocis-traefik.latest.owncloud.works/signin/v1/chooseaccount?client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&code_challenge=46FJTRSPaUk9QdjXRdY6wrMUrElU2HI0u9s7mUpIQsE&code_challenge_method=S256&flow=oidc&login_hint=marie&prompt=select_account+consent&redirect_uri=http%3A%2F%2F127.0.0.1%3A52718&response_type=code&scope=openid+offline_access+email+profile&state=5bTgc5Nwayx8b9NlidwmhJ6osL-YwGTkp2msgS3sdwc%3D&user=marie
```

![1645177440325](https://user-images.githubusercontent.com/4378513/154657928-8957dd11-b15e-4e8b-9900-1e78568842a5.png)

**Comment by TheOneRing** [comment]
Thats your logged in account, if you are logged in as einstein and try to relogin with marie, it will only suggest einstein.

**Comment by TheOneRing** [comment]
I haven't used ocis for a couple of month.

@IljaN you where involved the first time it was fixed, I think.
Any idea?

**Comment by micbar** [comment]
@IljaN ^

**Comment by TheOneRing** [comment]
ping

**Comment by pascalwengerter** [comment]
Added the bug label which should stop the stale-bot from trying to close the issue

**Comment by rhafer** [comment]
@TheOneRing @IljaN did this really ever work with ocis? I have some doubts.

Apart from that I think it's better if clients send the the desired username via the `login_hint` parameter. This is actually specified in the OIDC standards (even if optional). I don't know the history of the  `user` parameter, but it seems somewhat specific to ownCloud classic.

Unfortunately `login_hint` currently isn't supported by our builtin minimal IDP :disappointed: not sure how must effort it would be to  add it. But it works e.g. with keycloak and others.

**Comment by TheOneRing** [comment]
The desktop client uses both, `login_hint` (oidc) and `user` (owncloud 10).
Where early setups of ocis using a different IDP?

**Comment by micbar** [comment]
according to @pmaier1 there are no plans to implement that in LibreConnect.
