### ISSUE TITLE
Spaces quota should show the quota which has been actually set

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3233]
## Is your feature request related to a problem? Please describe.
Currently, the spaces API returns the field `total` which represents the set quota, 
if the set quota is higher then the available hard drive space `total` will show the available hard drive space.
The information on which quota has been actually set is not available anymore.  
 

## Describe the solution you'd like
Introduce a new field that will represent the actual set quota value

**Comment by JanAckermann** [comment]
@C0rby @micbar FYI

**Comment by micbar** [comment]
See https://github.com/owncloud/libre-graph-api/pull/32

**Comment by C0rby** [comment]
@JanAckermann, does this help you for this case? https://github.com/owncloud/ocis/pull/3368

**Comment by JanAckermann** [comment]
@C0rby yes

**Comment by C0rby** [comment]
@JanAckermann, I updated the code and comment here: https://github.com/owncloud/ocis/pull/3368
Basically a quota of `0` means unlimited. This way if you set `0` when updating the quota of a space you unrestrict it.

**Comment by JanAckermann** [comment]
THX, will start implementing approx next week

**Comment by C0rby** [comment]
The `total` now always shows the set quota or it's omitted if no quota was set.
