### ISSUE TITLE
Add ability to unrecstrict quota on spaces

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3234]
## Is your feature request related to a problem? Please describe.
Currently, it is not possible to set the space quota to unlimited, so I need to set a possible high quota even if I don't want to.

## Describe the solution you'd like
Add the possibility to un-restrict space quota via GraphAPI, add a field to quota which represents if the quota is unrestricted or not

**Comment by JanAckermann** [comment]
@micbar @C0rby FYI

**Comment by micbar** [comment]
See https://github.com/owncloud/libre-graph-api/pull/32

**Comment by C0rby** [comment]
@micbar @butonic, since the PR was closed we still don't have a way to represent an 'unrestrict' quota value.
How do we want to move on with this? I wouldn't have a problem with adding a new field to the libregraph API.

**Comment by C0rby** [comment]
With these changes it is now possible to unrestrict quota by setting '0' as the quota value.

**Comment by C0rby** [comment]
The changes are now in oCIS master. If there is still a bug or if changes are required please reopen this ticket or open a new one.

**Comment by JanAckermann** [comment]
:heart:
