### ISSUE TITLE
Spaces: translation of private link to drive id + path

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ocis#3245]
In OC10, private links can be resolved by performing a `PROPFIND` on `remote.php/dav/meta/[privateLinkFileID]`, requesting the `oc:meta-path-for-user` property.

The response from the OC10 server will then contain the item's path.

How is this handled in oCIS with spaces, where a single account can have multiple spaces (and therefore any number of different WebDAV endpoints)?

Ideally, it should be possible to translate a private link to drive id + path with a single request.

**Comment by michaelstingl** [comment]
oC10 also responded with a 30x and the full path, but that‘s not a beautiful API. (see https://github.com/owncloud/enterprise/issues/2173#issuecomment-319187738)

**Comment by michl19** [comment]
Please have a look at Web UI Url format at https://owncloud.dev/ocis/adr/0011-global-url-format/

**Comment by micbar** [comment]
We have the dav meta endpoint implemented now.
