### ISSUE TITLE
Implement an API endpoint to find out the default value for spaces quota

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3248]
## Is your feature request related to a problem? Please describe.
In the WebUI, I want to give the user a chance to set the quota to 'Default'. In order to do so, I need to know which is the default value.

## Describe the solution you'd like
An easy accessible API endpoint

**Comment by butonic** [comment]
Hm, is that a role property? https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta

**Comment by phil-davis** [comment]
Do we want to be able to set the quota to:
a) explicitly the value of the current default - e.g. if the default is currently 5GB then a client would find that out and then send an explicit request to set it to 5GB, and the quota of that space would stay at 5GB.
or
b) set the quota to "default" (a special value), and if the default happens to be 5GB today, and 10GB next week, then the space will be allowed 5GB today, and next week will automagically allow 10GB of storage

**Comment by micbar** [comment]
Techincally in ocis it is a setting. This ticket is only about the `default` value.

The actual value can com from the IDM (LDAP)

But the frontend needs to know the default for visual indication in the dropdown list.

IMO this could be covered by capabilities.

**Comment by C0rby** [comment]
> IMO this could be covered by capabilities.

But is it a capability though or is it rather a global setting?
Anyways, if I were to implement it as a capability, where would I store the value and how would I set it? Should it be updateable?

**Comment by JanAckermann** [comment]
any updates on this ? @C0rby

**Comment by C0rby** [comment]
No, this hasn't been tackled yet.
I still need some input from other oCIS team members about how we want to deal with global settings.

> But is it a capability though or is it rather a global setting?
Anyways, if I were to implement it as a capability, where would I store the value and how would I set it? Should it be updateable?

@micbar @butonic?

**Comment by butonic** [comment]
Interesting, I remeber discussing a new `/storages` resouce with @micbar in the graph api which admins will need to determine which storage to use for a new space, which one to use for `personal` spaces, which one for `project` space and when moving spaces between storages.

IMO that would also be a place to store the default quota for spaces (per storage provider).

We could start with a minimal implementation that can be statically configured with the storage provider id and the default quota for spaces on that storage. 

hm we may want to extend the GetQuota call on storageproviders to returns free disk space on the storage.

**Comment by micbar** [comment]
Not needed anymore because the default quota is now coming from the role.
