### ISSUE TITLE
Add documentation to Libre IDM service

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#3259]
# Description

## User Stories

* > As an oCIS adminisrator I want to know how to use the IDM service
* > As an oCIS contributor I want to understand the basic concept and implementation of the IDM service

## Acceptance Criteria
[ ] oCIS extenstion documentation exists

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by mmattel** [comment]
Hooking myself and @EParzefall in to get notified when the Libre IDM service gets live. Also see #3474
