### ISSUE TITLE
Storage VS storage provider VS storage driver

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#326]
to properly address user homes and shares they should be treated as dedicated storages.
A `storage` is a tree that propagates its etag up to the root and nowhere else

A `storage provider` can serve multiple `storages`, eg multiple home storages. each `storage` is addressed by an opaque id (which might be the root folder id)

The `storage driver` implements the storage api that is used by the storage provider to talk to the underlying storage system, eg eos, posix or an s3 dialect.

The `storage registry`should be able to list all storages a user has access to, including their last known etag and the mount point. the root etag can be cached in the storage registry, greatly reducing the need to send stats to the actual storage. (shared storages will only be stated once per cache ttl reached)

the ocdav api can can use the mount point to calculate the correct etag for intermediate paths so clients can still do a stdate based sync and change discovery.

**Comment by butonic** [comment]
cc @labkode

**Comment by micbar** [comment]
@pmaier1 @felixboehm This is very important for the project spaces concept.

**Comment by micbar** [comment]
@butonic @labkode Is there an overview / docs or drawing about the current reva architecture

For me, it is not clear which details of the summarry from @butonic are already implemented.

**Comment by dragotin** [comment]
I moved this topic to a story for the next sprint, see https://jira.owncloud.com/browse/OCIS-1717

Closing this here as all from here should be covered.
