### ISSUE TITLE
Adapt ocis to the new folder layout of the download mirrors

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#3263]
# Description

Create three Top folders

- `daily`
- `stable`
- `testing`

Put all the RCs and pre releases in the `testing` folder.
Put the daily build from master in `daily`

**Comment by micbar** [comment]
@wkloucek this was discussed with @xoxys already. It has no urgency but should not be forgotten.

**Comment by xoxys** [comment]
Not urgent means don't need to be done last week, this week or even next week. But as we would like to go forward with the mirror restructuring, getting this done in the next two weeks would be helpful. If you can't do it, I can move the existing files on my own and create a PR to adjust the drone config.

**Comment by micbar** [comment]
older release binaries are reodered.

@wkloucek I am missing the version tag in the filenames for version 1.19.0 and 1.19.1
IMO it is a good thing when you have some downloaded ocis versions in your Downloads Folder. They have no parent folder there. On the download mirrors this information looks redundant, but I would like to have it back.

**Comment by wkloucek** [comment]
> 

https://github.com/owncloud/ocis/pull/3429 brings it back

**Comment by micbar** [comment]
Thanks @wkloucek 

@xoxys  IMO this task is now complete.
