### ISSUE TITLE
Unable to sign-in with native apps with OIDC

### ISSUE THREAD

**Issue by coucoulala** [owncloud/ocis#3280]
## Describe the bug

While having an external OIDC provider configured for authentication, one is unable to sign-in with native apps. This is because the opened popup shows a username and password login page, instead of redirecting to the OIDC provider or showing a redirect button.

## Steps to reproduce

1.
2.
3.

## Actual behavior
A clear and concise description of what happened.

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by wkloucek** [comment]
Native clients discover the OIDC provider by looking at the well-known endpoint: `https:<your-ocis-domain>/.well-known/openid-configuration`. oCIS brings an own OIDC provider by default, that listens at exactly that path. If you use an external OIDC provider, you can stop the builtin one by running `ocis kill idp`. Then you shouldn't no longer see the login screen.

You need to ensure that the `https:<your-ocis-domain>/.well-known/openid-configuration` endpoint has the same content as `https:<your-oidc-provider>/.well-known/openid-configuration`, by setting up a reverse proxy in front of oCIS that relays this info from the IDP. Unfortunately oCIS currently cannot do this with builtin methods (like ownCloud 10 does). If you use Traefik we have an example here: https://github.com/owncloud/ocis/blob/5f5e935f7a9a188a10d3c65e8246011972be9e07/deployments/examples/ocis_keycloak/docker-compose.yml#L131-L139

This topic is missing in the documentation and needs to be added
