### ISSUE TITLE
[Proposal] Restructure project root

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#3286]
@wkloucek and I have been discussing how to improve the project structure.
At the moment the project root in https://github.com/owncloud/ocis/ is a bit cluttered/unintuitive. 
It would be helpful to restructure this.

## Describe the solution you'd like

The proposed changes would look like this:
```
https://github.com/owncloud/ocis/
+- extensions
  +- accounts
    +- docs
      +- [ contains only extension specific documentation and templates ]
  +- proxy
  +- web
  +- webdav
  +- ...
+- docs
  +- [ contains only basic skel for the docs (headers, footers etc.) and generated docs, no templates.
+- ocis-pkg
  +- clihelper
  +- cors
  +- middleware
  +- ...
+- ocis [ ocis meta package ]
  +- docs [ general docs (e.g. how to get ocis running standalone...)
+- protogen
+- deployments
+- tests  
```

## Additional context
In the last weeks 2 additional extensions have been added, thus making harder to navigate through the repository. 
In the future we plan to add a lot more extensions, in the current structure this will make it even harder to get a proper oversight over the project.

## Discuss
- What would be the best to do this since this will break lots of PRs

**Comment by butonic** [comment]
I like moving the extensions into a subfolder.

> What would be the best to do this since this will break lots of PRs

The sooner the better.
