### ISSUE TITLE
add testing tools

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#33]
Since nexus is a repo that ties together several repos to build a development environment we need a way to run a testsuite. I would like to use smashbox or our acceptance tests, but AFAIK both need access to the instance to speed up user creation and cleanup.

AFAICT, we should be able to run the phoenix test suite as described in https://github.com/owncloud/phoenix#run-acceptance-tests

## Litmus tests
To ensure basic webdav functionality
- [x] use https://github.com/owncloud-docker/litmus to test reva

## API tests
To test corner cases
- [ ] copy api tests from core
- [ ] reimplement steps for nexus / reva / ldap

## Phoenix tests
are tracked in https://github.com/owncloud/phoenix/issues/682.
- [ ] add a `make acceptance-tests` that tests the development instance brought up with `make future`
  - it can assume the ldap users from owncloudqa to be available

## User management
is done via ldap so we can directly use those users and test
- [ ] login and logout
- [ ] file and folder management features: create, list, stat, rename, move, delete
- [ ] file type specific features: edit text files, thumbnail generation, markdown preview ...

## Sharing
can be divided in three topics: file and folder management for
- [ ] internal file sharing (let's call this collaboration) with: create, list, stat, rename, move, delete on shared folder, sharing, unsharing, resharing
- [ ] public file sharing with: create, list, stat, rename, move, delete on shared folder, sharing, unsharing
- [ ] federated sharing ... ohhhh, how can we run two instances ... with: create, list, stat, rename, move, delete on shared folder, sharing, unsharing, resharing

## Search
- [ ] not yet implemented, see https://github.com/owncloud/nexus/issues/17

## External storages
The storage implementation uses a new architecture. For now, webdav access to the whole tree should be possible. In the future clients should look up the correct storage using the broken and then dircetly talk to the responsible storage provider. An external storage is wrapped by a storage provider.
- [ ] Testing file and folder management on external storages ... if we have them

- [ ] a config file containing the list of users and groups to be used for testing so we can run this not only against the `make future` dev environment but also against any other instance

**Comment by refs** [comment]
The concept in this issue is documented [here](https://owncloud.github.io/ocis/development/testing/).
