### ISSUE TITLE
non admin space manager can not list space members

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3303]
## Describe the bug

A non admin space manager (eg. Katherine from https://github.com/owncloud/ocis/pull/3297) can create a new space and add space members. But it can not see who is already a member of the space.

## Steps to reproduce

1. Log in as Katherine
2. Create a new space
3. add Albert to the space
4. refresh the page
5. See, that Katherine is the only member of the space
6. Login as Einstein
7. See, that you have the space where Katherine invited you
8. See, that Katherine is also a member in the space

## Expected behavior
Katherine should see that Albert is a member in the space

## Actual behavior
Katherine does not see that Albert is a member in the space

**Comment by ScharfViktor** [comment]
I have another questions, is it correct that user with manager role can see another manager's project space and the personal spaces of other users?
Steps:
- Katherine with "Spacemanager" role creates project space "finance department"
- User1 from another department with "Spacemanager" role can see space "finance department" and public space Katherine. 

The good news is that User1 can't create files or see what's inside. He can only delete a space, but this is an existing issue https://github.com/owncloud/ocis/issues/3031
