### ISSUE TITLE
Settings service should use the indexer

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3304]
## Is your feature request related to a problem? Please describe.
The settings service is used to store permissions and roles. The lookup is currently very expensive, since we read all permissions and roles from storage to see if we have something matching.

## Describe the solution you'd like
Use an index to optimize the queries. (Like eg. the accounts service does)

## Describe alternatives you've considered
-

## Additional context
-

**Comment by rhafer** [comment]
@wkloucek The cache should help I guess. At least the results of all the ReadDir and SimpleDownload resquest are cached. Though I am not entirely sure which exact request you think could be speed up by the use of indexes. Do you happen to remember a specific call that you had in mind when opening this issue?
