### ISSUE TITLE
Images in Spaces do not open in Mediaviewer

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#3315]
## Describe the bug

If there is an image in a oCIS space, it displays a neat thumbnail, which is nice.

If user clicks on the file, which should open the image in the media viewer, the media viewer opens but the media viewer stays empty.

This error message can be seen in the server log:
```
.GatewayAPI/Stat","start":"14/Mar/2022:16:16:29 +0100","end":"14/Mar/2022:16:16:29 +0100","time_ns":10276833,"code":"OK","time":"2022-03-14T16:16:29+01:00","message":"unary"}
{"level":"warn","service":"thumbnails","method":"Thumbnails.GetThumbnail","duration":10.489829,"error":"{\"id\":\"com.owncloud.api.thumbnails\",\"code\":404,\"detail\":\"could not stat file: stat: error: not found: Guidelines\",\"status\":\"Not Found\"}","time":"2022-03-14T16:16:29+01:00","message":"Failed to execute"}
{"level":"debug","service":"webdav","request":"","proto":"HTTP/1.1","method":"GET","status":404,"path":"/remote.php/dav/files/admin/Guidelines/roald-amundsen-luft.jpg","duration":191.468596,"bytes":242,"time":"2022-03-14T16:16:29+01:00"}
```

## Steps to reproduce

1. Upload an image into a folder in a project space
2. Click on the image file to show it in the viewer
3. See that the image viewer stays blank

**Comment by C0rby** [comment]
Can you run `make generate` in your ocis root then `make clean build` and try again? It should already work and it seems like your mediaviewer is outdated because the requested URL is wrong.

**Comment by dragotin** [comment]
I saw that with the 1.18 release, sorry for not mentioning in the first place. I assume that was fixed after that?

**Comment by pascalwengerter** [comment]
> I saw that with the 1.18 release, sorry for not mentioning in the first place. I assume that was fixed after that?

IIRC also @dschmidt brought some fixes to the `web` part of things in https://github.com/owncloud/web/pull/6456

**Comment by C0rby** [comment]
Ah yes, I think it was only introduced after the 1.18 release.

**Comment by ScharfViktor** [comment]
re-tested in v 1.20.0. 
works correctly I suggest to close
