### ISSUE TITLE
Shares: server reported no etag

### ISSUE THREAD

**Issue by sushmita56** [owncloud/ocis#3353]
## Description

The error `Shares: server reported no etag` comes up as soon as I added the OCIS-traefik server on the ownCloud desktop app for manual testing. 

## Screenshot
![Screenshot from 2022-03-21 16-13-11](https://user-images.githubusercontent.com/66173400/159249276-b54f8e19-cbbf-4d0a-9ac9-b6fbe0c977a7.png)

**Comment by micbar** [comment]
IMO we cannot change the clients out there.

So i vote for solution 2: only return a shares jail when there are shares.

**Comment by butonic** [comment]
I'm not saying wo change all the clients to fix this problem. All I am saying is that clients should be more forgiving. A resource does not have an etag. So what? That only means clients cannot decide when to descend into a folder. I think Postel's law applies: [be conservative in what you do, be liberal in what you accept from others.](https://en.wikipedia.org/wiki/Robustness_principle).

Desktop and mobile and even web clients could ignore the folder and only update local metadata when the user manually descends / explores the tree.

But that is a different issue and should be tracked elsewhere / at another time.

**Comment by micbar** [comment]
@butonic so quick solution: always have an etag. Needs fix in beta.

**Comment by micbar** [comment]
@felix-schwarz @TheOneRing Is it also possible to not have a share jail when there are no shares?

**Comment by michaelstingl** [comment]
> @felix-schwarz @TheOneRing Is it also possible to not have a share jail when there are no shares?

In the legacy WebDAV endpoint, the share jail is just a regular folder for the clients. So if there is no folder, there’s not a problem.

**Comment by felix-schwarz** [comment]
> @felix-schwarz @TheOneRing Is it also possible to not have a share jail when there are no shares?

I don't see a problem with that at the moment. It just wouldn't show up in the drive/spaces list then.

**Comment by TheOneRing** [comment]
This issue is about the legacy endpoint, which might still be used after the ocis release, as we are not able to migrate all clients.
In order to mute the error, the legacy endpoint could provide a dummy etag if the mapped shares jail does not report any?

For the listing of drives, I'm pretty sure I can handle it in the client, so no need to modify anything there.

**Comment by micbar** [comment]
Fixed by https://github.com/cs3org/reva/pull/2664
