### ISSUE TITLE
Include the space name in the OCS sharing API

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#3359]
Web needs the space name in the OCS sharing API in case of shared spaces (via link), as well as shared resources within a space. Otherwise we'd need to query the space for each share to get the space name.

Having the space name in regular PROPFIND requests would also be nice, but not a must for now.

Is this possible?

@C0rby @micbar fyi

**Comment by C0rby** [comment]
Is the space name required for shared with other AND shared with me?

**Comment by C0rby** [comment]
@JammingBen, see the question above. I already implemented this for shared with others but shared with me is a bit trickier.
Do we need that for both? If so I need to figure out a way to make it work.

**Comment by JammingBen** [comment]
Sorry, totally forgot to answer. I'm afraid we need it for both cases.

**Comment by C0rby** [comment]
No, worries. Ok, then more work is needed. :+1:

**Comment by kulmann** [comment]
@C0rby any update on this? 😅

**Comment by C0rby** [comment]
No, I haven't been working on this. But maybe it also makes sense to wait on this until we have the static registry back in oCIS since this will kind of dictate the implementation of this.

**Comment by micbar** [comment]
@C0rby Could you please check again the feasibility?

**Comment by micbar** [comment]
@pmaier1 @tbsbdr Is this ok from a product POV? Do we leak information?

**Comment by C0rby** [comment]
> @C0rby Could you please check again the feasibility?

This is still not easily possible, AFAICT.

**Comment by micbar** [comment]
still an issue

**Comment by dragonchaser** [comment]
According to @JammingBen not relevant atm, closing.
