### ISSUE TITLE
graph api - /users endpoint expose role field 

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3364]
## Describe the solution you'd like
Expose the user's role field

**Comment by rhafer** [comment]
Roles are currently not exposed via the graph API. As already mentioned elsewhere I think this as to be implemented on the client-side for now talking to the settings service. (Similar to what the "old" accounts UI is doing)

**Comment by rhafer** [comment]
Closing this, as we  added support for "appRoleAssignments" to the graph API in #5318, which provides the requested feature.
