### ISSUE TITLE
Different data in the space responses

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#3378]
ocis version 1.18.0 via docker

### Steps:
- Admin creates space and shares to marie with viewer role
- Admin changes role to editor
- Admin creates folder inside space

#### Actual result:
request GET `https://host.docker.internal:9200/graph/v1.0/me/drives?%24top=0&%24skip=0&%24orderby=name+asc&%24filter=driveType+eq+project`
role, etag, lastModifiedDateTime  changed

request GET `https://host.docker.internal:9200/graph/v1.0/drives/spaceId`
role, etag, lastModifiedDateTime  didn't change

#### Expected result:
both requests get the same data in response

it is a little unclear for me. what changes should change lastModifiedDateTime and eTag?
When I create or delete objects in space, lastModifiedDateTime and eTag are changing
When I share, rename, move objects etc, lastModifiedDateTime and eTag aren't changing. It's correct?

How this is works incorrect on the client can be seen here:
https://github.com/owncloud/web/issues/6651

**Comment by micbar** [comment]
I think this is a caching issue in the gateway

**Comment by ScharfViktor** [comment]
Re-tested, changing the role in both requests works. 

But after creating folder or uploading files eTag and lastModifiedDateTime  in request `https://host.docker.internal:9200/graph/v1.0/drives/spaceId` don't change. Is it still a cache problem?

**Comment by ScharfViktor** [comment]
Re-tested. works correct. no difference between responses
