### ISSUE TITLE
moving a file to the "Shares" folder deletes the file

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3383]
## Describe the bug

a file cannot be moved to the "Shares" folder, but if you try it will be deleted

## Steps to reproduce

1. create a file
2. move the file to the "Shares" folder
3. reload the page

## Expected behavior
file should still be there

## Actual behavior
file is deleted

## Setup

only tried with web, need to reproduce with the API

**Comment by pascalwengerter** [comment]
Not sure how much it's worth pouring energy into this, ideally the `Shares` folder is not visible on the web UI after the current sprint since the sharing jail is currently being implemented by @kulmann

**Comment by ScharfViktor** [comment]
retested on ocis 2.0.0-beta1

impossible to reproduce because the folder Shares now does not exist
