### ISSUE TITLE
Use the Id parameter to recognize spaces

### ISSUE THREAD

**Issue by ishank011** [owncloud/ocis#3388]
https://github.com/owncloud/ocis/blob/a99f725c0084776c0094fb67681225416bfacefd/graph/pkg/service/v0/drives.go#L525-L531

Why aren't we using `space.Id` anywhere? Just recognizing a space by a single ID is wrong as there can be clashes across storage providers, and not all providers will be using UUIDs.

**Comment by ishank011** [comment]
@butonic @C0rby @micbar

**Comment by micbar** [comment]
@ishank011 The StorageID is the spaceID and must be unique

**Comment by micbar** [comment]
The resourceID is always `StorageID!OpaqueID`

**Comment by ishank011** [comment]
> The resourceID is always `StorageID!OpaqueID`

I think you mean `Id`, right? The `Root` object should correspond to the reva resource IDs.

**Comment by micbar** [comment]
1) What is a storage Space?

A storage space is a Folder on a storage provider which is marked as a space Root. It is used as a root reference for relative paths inside a root. A Single Storage Provider can host unlimited numbers of storage Spaces

2) What is a spaceID

The spaceID is the ID of the RootFolder of a space. This folder has a ResourceID. The ResourceID of a SpaceRoot always consists the same StorageID and OpaqueID. That means on a a Space Root `StorageID == OpaqueID`.  Therefore the space id only uses the ID once. For example a spaceID could look like `f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c!f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c`. On a space both IDs are equal so we only need to use one.

**Comment by butonic** [comment]
1. An `id` in the graph API is an opaque string
2. We construct it by concatenating the CS3 `{storageid}!{opaqueid}`.
3. When dealing with a space root the `storageid` and `opaqueid` are actually the same.
4. To shorten the `id` we allow omitting the `opaqueid`
5. Shares that are represented as a space have `storageid` that identifies the space and an `opaqueid` that together identify the shared resource. The `spaceid` still follows the same pattern: `{storageid}!{opaqueid}`

**Comment by butonic** [comment]
@ishank011 we should probably have a quick call to clarify things?

**Comment by micbar** [comment]
All Storage providers need to provide UUIDs. That is a hard requirement. We cannot rely on Inodes or something which is not a  "logical unique identifier". SpaceIDs must survice cross storage moves.

**Comment by ishank011** [comment]
@micbar migration scenarios should be handled separately in case of conflicts IMO, given the frequency of such events happening compared to how much we use space lookups.

In our deployment, counting each share as a space, we have 500k+ spaces and for each metadata call, retrieving all of those and checking that there's an ID match is not a good idea at all. Also, given how heterogenous our drivers are, implementing this functionality in all of those adds a pretty big overhead.

**Comment by ishank011** [comment]
Even if you have a separate category for shares, the scalability issue still remains.

**Comment by micbar** [comment]
What do you suggest?

**Comment by labkode** [comment]
@micbar 

See diagram below.

The current implementation does not rely on SpaceID (storageID + opaqueID) to find storages, but solely on the storageID, that is not enough to route a request (broken label in the diagram).

Also, as @ishank011 explained, the way matching is done to identify a space in a storage provider is inefficient.

A spaceID created as StorageID+OpaqueID gives two benefits:
a) provides routing information based on the storageID and 
b) provides global uniqueness based on OpaqueID

So the implementation for routing should take into account this layout to avoid this self-inflicted ineficiency, and in case the spaceID does not contain the StorageID, then you fallback to ask every single storage provider to find the space (current implementation).

Regarding the shares, we need to discuss it, either they are spaces and treat it as such or they are a different entity and they are managed in a different way. We need to understand the inner mechanics for implementation in EOS.



![spaces-ishank](https://user-images.githubusercontent.com/5175912/160597737-79349f9b-2334-426b-9613-614b416b418c.png)

**Comment by micbar** [comment]
@labkode @micbar The current implementation uses the spaceID

https://github.com/owncloud/ocis/blob/4cbec0adab7385edf16921c3c76c2b96f5c3e229/graph/pkg/service/v0/drives.go#L494-L496

**Comment by ishank011** [comment]
@micbar any update after our discussion on how the spaces registry works?

**Comment by micbar** [comment]
this is the one about the registry https://github.com/owncloud/ocis/issues/3431

**Comment by micbar** [comment]
And there is a description which @butonic created one year ago about the resourceIDs https://owncloud.dev/extensions/storage/proposedchanges/#space-providers

We just didn't implement it yet.

But we concluded that we would need the storageproviderID also and switch to the static registry also on the `edge` branch.


IMO this would unblock everything.

**Comment by ishank011** [comment]
@micbar sounds really good. Thanks a lot!

**Comment by micbar** [comment]
@butonic has this been fixed already?
