### ISSUE TITLE
to implement search add REPORT verb to ocdavsvc

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#34]
phoenix uses it to search files. cs3apis do not talk about search. 

- add it to reva?
- ~add it to nexus?~
  - as elasticsearch + reva service?
  - as reva servisce that walkse the tree recursively? for testing?
- add [elasticsearch to storages](https://github.com/owncloud/nexus/issues/16) directly? Why if cs3 has no api endpoint for it? should we add search to cs3?
- if we use elasticsearch should we use proper query language?

**Comment by refs** [comment]
Closing in favor of the current efforts in performance.
