### ISSUE TITLE
sending invalid data to graph API still returns HTTP 200

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3402]
## Describe the bug

e.g sending a random file-id as the "image" folder does not give back any indication that something went wrong. Though the information is not saved the API returns HTTP 200

## Steps to reproduce

not-existing fileId as image
1. create two random UUIDs and join them with an `!` e.g. `0076ce93-81b3-48e3-94ff-eba9e1e8bd19!56bd2f80-d372-4cd7-a0f2-399497b91191`
2. set this UUID combination as space image: `curl -k -u admin:admin https://localhost:9200/graph/v1.0/drives/e85e1492-6e06-4f2b-90b1-926c0e4efa93 -X PATCH -d{"special":[{"specialFolder":{"name":"image"},"id":""}]}`

negative number as quota:
`curl -k -u admin:admin https://localhost:9200/graph/v1.0/drives/e85e1492-6e06-4f2b-90b1-926c0e4efa93  -X PATCH -d'{"quota":{"total": -100}}' -v`

## Expected behavior
4xx Error

## Actual behavior
```
< HTTP/1.1 200 OK
< Content-Length: 757
< Content-Type: application/json; charset=utf-8
< Date: Mon, 28 Mar 2022 06:21:21 GMT
< X-Graph-Version: 1d25f03de
< 
{"description":"some text\u003cbr\u003e\u003cb\u003easdaa\u003c/b\u003e","driveAlias":"नेपालि नाम","driveType":"project","id":"e85e1492-6e06-4f2b-90b1-926c0e4efa93","lastModifiedDateTime":"2022-03-28T11:57:37.369520145+05:45","name":"नेपालि नाम","owner":{"user":{"id":"ddc2004c-0977-11eb-9d3f-a793888cd0f8"}},"quota":{"remaining":4999819593,"state":"normal","total":5000000000,"used":180407},"root":{"eTag":"\"d44ea27e076edd788ee94d047d702ca3\"","id":"e85e1492-6e06-4f2b-90b1-926c0e4efa93!e85e1492-6e06-4f2b-90b1-926c0e4efa93","permissions":[{"grantedTo":[{"user":{"id":"ddc2004c-0977-11eb-9d3f-a793888cd0f8"}}],"roles":["manager"]}],"webDavUrl":"https://localhost:9200/dav/spaces/e85e1492-6e06-4f2b-90b1-926c0e4efa93"}}
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_INSECURE=true PROXY_ENABLE_BASIC_AUTH=true bin/ocis server
```

</p>
</details>

**Comment by individual-it** [comment]
@ScharfViktor  issues seems to have been fixed 
should we write API tests for those cases?

**Comment by ScharfViktor** [comment]
yes, it would be nice to have tests. 
I'll add tests and after that close issue
