### ISSUE TITLE
trying to delete the Shares Jail space results in an error 500

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3403]
## Describe the bug

API call to delete the shares jail are responded with an error 500

## Steps to reproduce

1. `curl -k -u admin:admin https://localhost:9200/graph/v1.0/drives/<share-jail-space-id> -X DELETE -v`

## Expected behavior
I think HTTP 400, 401 or 403 would be a reasonable answer

## Actual behavior
HTTP 500

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_INSECURE=true PROXY_ENABLE_BASIC_AUTH=true bin/ocis server
```

</p>
</details>

## Additional context
Logs:
```
{"level":"error","service":"storage","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"grpc-go/1.45.0","from":"tcp://127.0.0.1:39624","uri":"/cs3.storage.provider.v1beta1.ProviderAPI/DeleteStorageSpace","start":"28/Mar/2022:12:41:58 +0545","end":"28/Mar/2022:12:41:58 +0545","time_ns":67228,"code":"Unimplemented","time":"2022-03-28T12:41:58+05:45","message":"unary"}
{"level":"error","service":"graph","time":"2022-03-28T12:41:58+05:45","message":"error deleting storage space"}
```

**Comment by ScharfViktor** [comment]
<img width="1118" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/115c0f0d-e744-48de-93f9-63ed2d5ea621">

Already fixed. Now we get `405 Method Not Allowed`
