### ISSUE TITLE
generated yaml config has no underscores

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#3410]
eg `base_dn` is defined in https://github.com/owncloud/ocis/blob/master/glauth/pkg/config/config.go#L33 but rendere as `basedn` in https://owncloud.dev/extensions/glauth/configuration/#example-yaml-config

**Comment by rhafer** [comment]
cc @dragonchaser

**Comment by wkloucek** [comment]
https://github.com/go-yaml/yaml/issues/424
