### ISSUE TITLE
ocis binaries must be PIE

### ISSUE THREAD

**Issue by crrodriguez** [owncloud/ocis#3411]
I was asked to investigate how to package this for a linux distribution, but I better start with the bugs of the existing packages instead :-)

## Describe the bug

pre-built binaries are by all practical means wrongly compiled, by default go generates binaries that are not position independent, this will eventually lead to triggering selinux exec* restrictions, not to mention full ASLR is inactive.

This strange anacronism was fixed at some point in the past and go now has a -buildmode=pie  which the pre-built binaries need to use.

**Comment by micbar** [comment]
@crrodriguez please test again with the v1.19.0-rc1 release
