### ISSUE TITLE
User assignments-list gets longer after every restart on default users 

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3432]
## Describe the bug

User assignments-list gets longer after every restart on default users 
![image](https://user-images.githubusercontent.com/26169327/161036335-0c60cb16-9a6b-44ad-b6e2-7376547543d5.png)

## Steps to reproduce

1. Start ocis
2. POST https://localhost:9200/api/v0/settings/assignments-list with payload `{
    "account_uuid": "058bff95-6708-4fe5-91e4-9ea3d377588b"
}`
4. Observe the length of the assignments
3.  Kill ocis
4. Start ocis
5.  POST https://localhost:9200/api/v0/settings/assignments-list with payload `{
    "account_uuid": "058bff95-6708-4fe5-91e4-9ea3d377588b"
}`
6. Observe that the assignment list have more items, than before

## Expected behavior
The assignment list should not have more items after kill and start ocis for no reason

## Actual behavior
User assignments-list gets longer after every restart on default users 

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by rhafer** [comment]
Some notes: This only happens when using the "metadata" storage for settings (which is our default since a few weeks). When using "metadata" the default assignments are only created when processing the first (wrirte)r equest on the settings API.

**Comment by rhafer** [comment]
This but  is definitely still present in current master:


```
ocis/bin/ocis init --insecure true --ap admin
PROXY_ENABLE_BASIC_AUTH=true ocis/bin/ocis server
```

now list assignments:

```
curl -XPOST "https://localhost:9200/api/v0/settings/assignments-list" -d'{"account_uuid": "me"}' -uadmin:admin -k | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   334  100   312  100    22   2310    162 --:--:-- --:--:-- --:--:--  2492
{
  "assignments": [
    {
      "id": "8129e0fc-8956-47cc-b997-157667bd316c",
      "accountUuid": "09a0500d-f175-4778-9f4d-c1ec1d69b5e5",
      "roleId": "71881883-1768-46bd-a24d-a356a2afdf7f"
    },
    {
      "id": "1a638431-a524-4e51-bbe5-ef53e5193a2c",
      "accountUuid": "09a0500d-f175-4778-9f4d-c1ec1d69b5e5",
      "roleId": "71881883-1768-46bd-a24d-a356a2afdf7f"
    }
  ]
}
```

Having the admin role assigment twice is already a bug. But when you restart restart ocis and list assignments again you get it listed 4 times.:

```
curl -XPOST "https://localhost:9200/api/v0/settings/assignments-list" -d'{"account_uuid": "me"}' -uadmin:admin -k | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628  100   606  100    22   3376    122 --:--:-- --:--:-- --:--:--  3488
{
  "assignments": [
    {
      "id": "8129e0fc-8956-47cc-b997-157667bd316c",
      "accountUuid": "09a0500d-f175-4778-9f4d-c1ec1d69b5e5",
      "roleId": "71881883-1768-46bd-a24d-a356a2afdf7f"
    },
    {
      "id": "1a638431-a524-4e51-bbe5-ef53e5193a2c",
      "accountUuid": "09a0500d-f175-4778-9f4d-c1ec1d69b5e5",
      "roleId": "71881883-1768-46bd-a24d-a356a2afdf7f"
    },
    {
      "id": "67a28885-6f75-43f9-87f6-2fb528136f4e",
      "accountUuid": "09a0500d-f175-4778-9f4d-c1ec1d69b5e5",
      "roleId": "71881883-1768-46bd-a24d-a356a2afdf7f"
    },
    {
      "id": "17a99600-196d-4f68-b31c-f6ccf083440b",
      "accountUuid": "09a0500d-f175-4778-9f4d-c1ec1d69b5e5",
      "roleId": "71881883-1768-46bd-a24d-a356a2afdf7f"
    }
  ]
}
```

I think this only happens for admin and demo-users.
