### ISSUE TITLE
aborting an upload in the web ui results in a truncated upload

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#3438]
When uploading a 200MB File with the web UI @enbrnz and @ChrisEdS could reproduce a truncated upload by:
1. Start uploading a large file
2. Reload the page while upload is in progress
3. file shows in the web ui, but with less bytes

I expect aborted uploads to not overwrite the existing file. Only when the upload finishes should the new file be shown in the webui.

Might be a simple PUT vs TUS upload problem???

@ChrisEdS what instance were you testing against? ocis or oc10?

**Comment by ChrisEdS** [comment]
Reproducible at https://ocis.ocis-web.latest.owncloud.works/

**Comment by kobergj** [comment]
Probably fixed meanwhile. Closing.
