### ISSUE TITLE
Starting ocis server as ordinary user creates an error message from the idp extension on startup

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3457]
## Describe the bug
When starting `ocis server` **as ordinary user** in a directory where this user **does not have write permissions**, you get an error message from the `idp` extension not being able to create a directory - this seems to be a bug.

```
{"level":"fatal","service":"idp","error":"mkdir ./config: permission denied","time":"2022-04-04T15:23:44+02:00","message":"could not create default config"}
```

## Steps to reproduce
```
cd /
ocis server
```

## Expected behavior
No error message

## Actual behavior
Error message

## Setup
No yaml or env used

```console
OCIS_VERSION=v1.9.0
downloaded from https://download.owncloud.com/ocis/ocis/
```

## Additional context
none

@rhafer (as discussed), @micbar @butonic 
@EParzefall fyi

**Comment by wkloucek** [comment]
Oh I see you're using oCIS 1.9, which is quite outdated. If you're using a more recent oCIS version, eg. oCIS 1.19.1, it shouldn't write to the current directory anymore

**Comment by mmattel** [comment]
Then you need to update the channel: https://download.owncloud.com/ocis/ocis/stable/?sort=name&order=desc

![image](https://user-images.githubusercontent.com/3321281/162160286-ca65c5df-2b25-44eb-a725-e1b3ec0e7974.png)

**Comment by mmattel** [comment]
@wkloucek forget my last post - f*** sort order - this needs to be fixed on the webserver!

![image](https://user-images.githubusercontent.com/3321281/162162216-d90ab256-ebc1-41bf-82ef-dcbd448df4b5.png)

**Comment by wkloucek** [comment]
I see no more action here, please reopen if still valid
