### ISSUE TITLE
Share with group using IDM doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#3466]
ocis local version: 1.19.1

**preparation**:
- stop ocis 
- clean ocis `rm -rf /Users/scharfviktor/.ocis`
- start ocis with idm (see how here: https://owncloud.dev/extensions/idm/setup/)

**Steps**: 
- admin creates folder "f1"
- admin shares folder with group "physics-lovers" (marie is member of this group). Or create a new group and add Marie to it

**Expected result**: share to group is created 

**Actual result**: 

- ***first request - find group in sharing dialog***

GET `https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=physics-lovers&itemType=folder&page=1&perPage=200&format=json`

group didn't found:
![Screenshot 2022-04-05 at 16 51 44](https://user-images.githubusercontent.com/84779829/161783590-f19f28d9-5287-4055-a112-262e46ad5940.png)

in oc10
![Screenshot 2022-04-05 at 16 50 15](https://user-images.githubusercontent.com/84779829/161783688-1aafe510-3316-40cc-87c9-710129aa88c5.png)

- ***second request that doesn't work correct - send create share:*** 

`curl --location --request POST 'https://host.docker.internal:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--form 'shareType="1"' \
--form 'path="/f1"' \
--form 'permissions="1"' \
--form 'shareWith="physics-lovers"'`

get 200 with response: `<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>998</statuscode><message>group not found</message></meta></ocs>`

**Comment by ScharfViktor** [comment]
@rhafer could you please see bug. We want to have sharing to group in ocis beta

**Comment by rhafer** [comment]
@ScharfViktor Should work after we get https://github.com/cs3org/reva/pull/2708 merged and ocis config updated accordingly. (Which I am currently working on)
