### ISSUE TITLE
fix dependencies of the idp ui

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3493]
The IDP UI has dependencies on following dependencies, that do currently not match our allowed license patterns and are therefore ignored (https://github.com/owncloud/ocis/blob/21e37fc8565cbfc698f9430513f305d80b542ddd/idp/package.json#L11):
- kpop (is Apache 2.0, but license is not included in the package.json file, PR pending https://github.com/Kopano-dev/kpop/pull/32)
- po2json (is  GNU)
- unicoderegexp (is BSD 3, but no standard license, https://github.com/One-com/unicoderegexp/blob/master/LICENSE)

**Comment by wkloucek** [comment]
Probably we should also switch to the new Lico based UI!? https://github.com/libregraph/lico/blob/4c5f17e836263a62834d410ab1f00ab0a52cd14a/identifier/package.json

**Comment by pascalwengerter** [comment]
> 

Might need a discussion with @kulmann if we add it to one of the next `web` sprints maybe?

**Comment by wkloucek** [comment]
> > 
> 
> Might need a discussion with @kulmann if we add it to one of the next `web` sprints maybe?

Let's wait for https://github.com/Kopano-dev/kpop/pull/32#issuecomment-1092811568

**Comment by wkloucek** [comment]
@pascalwengerter https://github.com/Kopano-dev/kpop/pull/32#issuecomment-1092922349 -> Could you have a look into what we would need to do, to be more similar to the current Lico UI?
