### ISSUE TITLE
check nodejs based dependencies

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3495]
check the completeness of nodejs based license checker. We could indirectly consume libraries without knowing about it (because we don't build everything from source, like we do it in go)

**Comment by pascalwengerter** [comment]
@wkloucek what's the best approach here? Add a license-checker yarn step to the `settings` & `idp` (afaik the only services having JS dependencies) and run it in CI?

**Comment by wkloucek** [comment]
> @wkloucek what's the best approach here? Add a license-checker yarn step to the `settings` & `idp` (afaik the only services having JS dependencies) and run it in CI?

I think the only way to do it is to benchmark it against a paid tool like [Fossa](https://fossa.com/). I did this once, but didn't do a in-depth comparison

**Comment by pascalwengerter** [comment]
Needs work akin to https://github.com/owncloud/web/blob/40a5d2240ffe52896bbaa5e775fc156078b69f22/package.json#L16 in the `settings` and `idp` extensions, @micbar could you add one of the necessary labels so the stale-bot doesn't get involved?
Still highly relevant given the unknowns and depth of JS dependencies and the fact that oCIS is in GA now

**Comment by wkloucek** [comment]
This got no attention so far
