### ISSUE TITLE
Elasticsearch for searching metadata

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#35]
to provide search capabilities we need to add elasticsearch as part of the new architecture so storage providers can use it instead of having to walk down the file hierarchy recursively.

next step is to schedule this. AFAICT we need a new api in the CS3 storage provider or a dedicated service, similar to the data provider.

**Comment by wkloucek** [comment]
does this still fit into the current storage-only architecture?

**Comment by refs** [comment]
ping @butonic is this still relevant or can it be closed?

**Comment by micbar** [comment]
Closing. This is not technical debt. Ocis 2.0.0-beta1 has filename search based on bleve.

All further Search features will be handled in separate Epics and User stories.
