### ISSUE TITLE
generate config examples

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#350]
Reading the config section from the devdocs of ocis-reva I am seeing this:
> So far we support the file formats JSON and YAML, if you want to get a full example configuration just take a look at [our repository](https://github.com/owncloud/ocis/tree/master/config), there you can always see the latest configuration format. These example configurations include all available options and the default values. The configuration file will be automatically loaded if it’s placed at `/etc/ocis/ocis.yml`, `${HOME}/.ocis/ocis.yml` or `$(pwd)/config/ocis.yml`

The example config files ara currently hand written and contain only the generic config. We could generate them using the default values. If they are empty comment them in the config file (or, as a convention for json files prefix the property using a `#`)

- [ ] the link to `our repository` points to ocis-proxy

**Comment by refs** [comment]
config examples can be [found in the docs](owncloud.github.io/)
