### ISSUE TITLE
fix error message for ocis accounts list if the runtime is not running

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3500]
## Is your feature request related to a problem? Please describe.
When you run `ocis accounts list` and the runtime has not been started, you get a wired error message which should be fixed. This is the current output:

```
ocis accounts list
could not list accounts {"id":"go.micro.client","code":500,"detail":"service com.owncloud.api.accounts: not found","status":"Internal Server Error"}
```

## Describe the solution you'd like
We have already fixed error messages in other commands related to the runtime and the text could be reused, see: https://github.com/owncloud/ocis/pull/3481 (improve runtime connect error messages)

Fixing is an easy win.

## Describe alternatives you've considered
No alternative to a well reading text...

@micbar @butonic @wkloucek 
@EParzefall  fyi

**Comment by micbar** [comment]
accounts service will be deleted.
