### ISSUE TITLE
Minor wording fix: ocis accounts list --> Mail --> Email

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3501]
## Is your feature request related to a problem? Please describe.
When typing `ocis accounts list` you get the list of users. The headline states writes beside other elements `Mail`

Same for `Id` --> `ID`

## Describe the solution you'd like
The word `Mail` should be fixed to `Email`
Note that this change also must go into the `ocis accounts inspect ...` output.

`ocis accounts update/create` uses `--mail` instead of `--email` including the help text message - to be fixed.

Note that `ID` is written ok in the inspect output.

## Describe alternatives you've considered
There is never an alternative for correct writing 😄 

## Additional context
none

@micbar @wkloucek @butonic 
@EParzefall FYI

**Comment by micbar** [comment]
accounts will be dropped completely. No point in improving it.
