### ISSUE TITLE
[ocis] backchannel logout endpoint

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3521]
## Is your feature request related to a problem? Please describe.
When a client ends the OIDC session, oCIS still caches the OIDC session for some time. If the client would use an access token of the invalidated session, oCIS would still accept it (until the session cache expired or the access token expired)

## Describe the solution you'd like
Implement a backchannel logout url to immediately invalidate the session.

## Describe alternatives you've considered
Have short lived access tokens

## Additional context
When we have multiple proxy instances (scale out), we need to introduce a shared cache between the instances or ensure that the session is invalidated in all caches.

CC @C0rby

**Comment by dj4oC** [comment]
ping @micbar @wkloucek @butonic 
please take into account of infinite scale release 3.0

**Comment by micbar** [comment]
done via #6007
