### ISSUE TITLE
[Spaces] [Desktop] Migrate existing sync folder pairs to Spaces

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#3528]
## Is your feature request related to a problem? Please describe.

Some users have an advanced setup of sync folder pairs in their desktop sync client, and they want to migrate to new, Spaces-based WebDAV URL's, without setting everything up again.

Here is an example:
![CleanShot 2022-04-13 at 12 41 24](https://user-images.githubusercontent.com/214010/163163668-fc93c874-f2e9-4d94-9199-b0f62698da47.png)

In the clients config file it's stored like this:

```
0\FoldersWithPlaceholders\1\targetPath=/home
0\FoldersWithPlaceholders\2\targetPath=/eos/user/c/XXXXXXXXX/Documents
0\FoldersWithPlaceholders\3\targetPath=/eos/project/p/privacy/Data Protection Day/2022/videos
0\FoldersWithPlaceholders\4\targetPath=/eos/project/r/recast/atlas/ATLAS-CONF-2018-041
0\FoldersWithPlaceholders\5\targetPath=/eos/user/g/XXXXXX/AwesomeWorkshopFeb2020
```

## Describe the solution you'd like

Desktop can `PROPFIND` each remote location to get the fileID

**REQUEST**
```
PROPFIND /remote.php/webdav/eos/project/p/privacy/Data Protection Day/2022/videos/
<?xml version="1.0" encoding="utf-8" ?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
    <a:prop>
    <oc:id/>
    </a:prop>
</a:propfind>
```

**RESPONSE**
```
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
    <d:response>
        <d:href>/remote.php/webdav/eos/project/p/privacy/Data Protection Day/2022/videos/</d:href>
        <d:propstat>
            <d:prop>
                <oc:id>4c510ada-c86b-4815-8820-42cdf82c3d51!8fe7054f-2a17-4d52-aedf-79febacfb5bd</oc:id>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

For migration, the desktop client should:

1. `PROPFIND https://host/remote.php/webdav/{targetPath}` with the `oc:id` property to look up the resource `id`,
2. `GET https://host/graph/v1.0/me/drive/items/{id}` to look up the `parentReferece` of the item which would give him the space and the relative path in the space. 

When a `targetPath` resolves to a non root resource, eg `https://cloud.ocis.test/graph/v1.0/me/drive/items/4c510ada-c86b-4815-8820-42cdf82c3d51!8fe7054f-2a17-4d52-aedf-79febacfb5bd` the `parentReference` has a `path`, `name` and `id` property:
```
...
    "parentReference": {
        "driveId": "4c510ada-c86b-4815-8820-42cdf82c3d51",
        "driveType": "project",
        "id": "4c510ada-c86b-4815-8820-42cdf82c3d51!e8294f79-79b4-4c7d-b5db-7dce94f6a1cc",
        "name": "videos",
        "path": "/drive/root:/videos"
    },
...
```

When a `targetPath` resolves to a space root, eg `https://graph.microsoft.com/v1.0/me/drive/items/4c510ada-c86b-4815-8820-42cdf82c3d51!4c510ada-c86b-4815-8820-42cdf82c3d51` the `parentReference` has no `path`, `name` or `id` because it is the root:
```
...
    "parentReference": {
        "driveId": "4c510ada-c86b-4815-8820-42cdf82c3d51",
        "driveType": "project"
    },
...
```

@butonic please elaborate on the piece that's missing in oCIS for this.

/cc @TheOneRing @dragotin @micbar @C0rby @fmoc

**Comment by butonic** [comment]
The graph `/(me/)drive(s)/items/` endpoint needs to return the `parentReference` property. `driveId` and `driveType` should be known, but parent `id` and `name` migth require an additional stat (or we add it to the ResouceInfo, IIRC @wkloucek and @glpatcern could also use at least a parent id). The path might require an additional GetPath() request.

**Comment by labkode** [comment]
@michaelstingl 
This approach won't work for our environment as the sync clients connect directly to EOS (that exposes the WebDAV endpoint) and is OCIS-agnostic.

Therefore, if we follow this approach when the sync client asks OCIS for the Space regarding a file id OCIS won't be able to answer.

After discussing with @dragotin and @butonic, a better proposal is to make the sync client as dumb as possible and enabling the desktop client to send the client config to the server to the server can reply with the desired configuration.

That will make it generic enough for any migration and server will control the migration, which is a great addition to control the migration on a per-user basis.

As discussed, I'll write a proposal API that the sync client could contact and we follow up there. 

I close this issue then.

![oc-migration-desktop](https://user-images.githubusercontent.com/5175912/165051078-faa2366d-9f6b-4bb2-afd2-43cb4da9e82a.png)
