### ISSUE TITLE
Clicking on `Favorites` throws `Loading folder failed…`

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ocis#354]
I just tested the current beta on `ocis-latest.owncloud.com`.

When clicking on `Favorites` I get an `Unknown error`.

![image](https://user-images.githubusercontent.com/33026403/86274245-ab04d100-bbd1-11ea-9ffe-2bea8e524c6c.png)

**Comment by PVince81** [comment]
I think favorites are not supported yet in OCIS.

Ideally we should make a capability out of it and then disable it from the UI when not supported.
It might happen that some storage doesn't support extended metadata so tagging a file as favorite there would not work.

On the other hand, it feels weird to rely on storage capabilities for something like a favorite. Maybe we should store that information elsewhere, in some "ocis-favorites" service that is storage independent.

The capability approach would require adding some values in OC 10 as well to have the favorite visible again when used with ocis-web.

**Comment by PVince81** [comment]
I've raised https://github.com/owncloud/ocis-reva/issues/361 for finishing the favorites implementation eventually.

For the scope of this ticket:

- [ ] add capability in OC 10 and enable it
- [ ] adjust ocis-web to disable the favorite feature when the capability is not set

This would remove the feature from the UI until it is properly implemented.

**Comment by LukasHirt** [comment]
@PVince81 Let's close this ticket? ocis-web PR got merged as well
