### ISSUE TITLE
[New/Spaces webdav] HTTP status code differ while deleting file of another user's trash bin

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#3544]
## Describe the bug

HTTP status code while deleting files from another user's trash bin is different in spaces WebDAV and new WebDAV.

## Steps to reproduce

1. create user 'user1' and 'user2'
2. as  'user1' upload file 'textfile0.txt' with content 'test'
3. as 'user1' delete file 'textfile0.txt'
4. as 'user2' try to delete file 'textfile0.txt' from the trashbin of user 'user1'

`curl -ks -u user2:password -X DELETE https://localhost:9200/remote.php/dav/spaces/trash-bin/{spaceid_user1}/{fileid} -v`

## Expected behavior
In both new/spaces WebDAV, the same HTTP status code
`HTTP/1.1 401 Unauthorized`

## Actual behavior
In new WebDAV, `HTTP/1.1 401 Unauthorized`
In spaces WebDAV, `HTTP/1.1 409 Conflict`

## Setup

<details>
<p>

```console
OCIS_VERSION=latest
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by saw-jan** [comment]
closing in favor of https://github.com/owncloud/ocis/issues/9791
With new dav path the server returns `404`
