### ISSUE TITLE
Preview API endpoint returns Markdown for Markdown files

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ocis#3558]
## Describe the bug

Sending a request to the preview API for markdown files returns a markdown response.

## Steps to reproduce

1. Create a markdown file.
2. Send a request to the preview API for the file, f.ex. `/dav/spaces/480d46a8-4b90-41ca-83bc-a22382197355/Neue%20Datei.md?y=180&preview=1&x=180&c=%229e7a719aa193438dc187dfbbc93a66ad%22&a=1`

## Expected behavior
The server returns a `404` response.

## Actual behavior
The server responds with a `200` response and delivers the markdown file (empty file here):

```
Method:      GET
URL:         https://localhost:9200/dav/spaces/480d46a8-4b90-41ca-83bc-a22382197355/Neue%20Datei.md?y=180&preview=1&x=180&c=%229e7a719aa193438dc187dfbbc93a66ad%22&a=1
Request-ID:  8DAB351F-69E7-4E4E-9709-D74C74C53C38
Error:       -
Req Signals: coreOnline, authAvailable
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
200 NO ERROR
Content-Type: text/markdown
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none';
Content-Disposition: attachment; filename*=UTF-8''Neue Datei.md; filename="Neue Datei.md"
X-Xss-Protection: 1; mode=block
X-Download-Options: noopen
Oc-Checksum: SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709
Oc-Etag: "9e7a719aa193438dc187dfbbc93a66ad"
X-Permitted-Cross-Domain-Policies: none
Date: Thu, 21 Apr 2022 15:40:16 GMT
X-Robots-Tag: none
Content-Length: 0
Oc-Fileid: 480d46a8-4b90-41ca-83bc-a22382197355!25224c79-8a22-4b59-b30a-7099bc36f12c
X-Content-Type-Options: nosniff
Etag: "9e7a719aa193438dc187dfbbc93a66ad"
X-Frame-Options: SAMEORIGIN
Last-Modified: Thu, 14 Apr 2022 21:54:53 +0000
```

## Additional context
This caused a visual issue in the development builds of the iOS client with spaces support: the response was converted into a text resource and then "rendered" in place of the thumbnail, causing the item's cell to span several screens due to line breaks and word wrapping.

**Comment by felix-schwarz** [comment]
It appears this was the consequence of missing routes for previews, which will be addressed by https://github.com/owncloud/ocis/pull/3567 .

**Comment by felix-schwarz** [comment]
A `404` for markdown files would be fine, too. Just not the file itself (which I believe was caused by the missing routing of preview requests on the DAV endpoint URLs from the drives list).

**Comment by C0rby** [comment]
Ah I see. Yes, after the changes it should return a 404. :+1:
