### ISSUE TITLE
MarkdownEditor is not working

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ocis#356]
By clicking on a Markdown (or TXT) file I am offered to open it with the Markdown Editor. 

![image](https://user-images.githubusercontent.com/33026403/86275293-54989200-bbd3-11ea-8397-dcbb6122620b.png)

But only an empty UI appears.

![image](https://user-images.githubusercontent.com/33026403/86275169-274be400-bbd3-11ea-9550-3b9bc6236095.png)

Tested with `ocis-latest.owncloud.com`

**Comment by micbar** [comment]
Thank you!
