### ISSUE TITLE
[Proposal] Use stable tag for most recent stable release of ocis

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#3578]
At the moment we have versioned tags on dockerhub for ocis (e.g. `owncloud/ocis:1.20`) and also a `latest` tag which is pointing to master. I suggest adding an additional tag `stable` which is pointing to the most recent release of ocis (e.g. `owncloud/ocis:1.20` would be the same as `owncloud/ocis:latest` while 1.20 is the stable release). 
Advantage of this would be that one would not need to update the composefiles used for deployment and it would be less confusing (at least for me) what the purpose of the lastest tag is.

/cc @mmattel

**Comment by mmattel** [comment]
Thanks for informing us, I am going to make an internal `fixme` note in the container documentation with a link to this issue to track progress.

**Comment by wkloucek** [comment]
How would the `stable` behave for a major version change? You already can use `owncloud/ocis:1` for what you have in mind. Plus it doesn't break for a major release ;-)

**Comment by dragonchaser** [comment]
@wkloucek  `stable` == latest stable we support and yes you are right, major releases would most likely result in breakage in that case.
