### ISSUE TITLE
Authorization for tus-uploads on password protected links

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#3588]
When I'm uploading a file via tus to a password protected public link, the initial `POST` request succeeds without problems: `https://localhost:9200/remote.php/dav/public-files/WoXYZdRaXgPZEZZ/`. The auth header is e.g. `Basic cHVibGljOnRlc3Q=`.

Now the second request, a `HEAD` request, with the exact same auth header stays in a `pending` state in the browser network tab. Instead, the classic Basic-Auth-Browser-Window pops up and asks for credentials as the backend response includes `Www-Authenticate` in its response headers.

The oCIS error log prints `ERR error fetching from accounts-service error="{\"id\":\"com.owncloud.api.accounts\",\"code\":401,\"detail\":\"account not found or invalid credentials\",\"status\":\"Unauthorized\"}" query="login eq 'public' and password eq 'test'" service=proxy`

I'm not a 100% sure if this is a frontend or a backend issue. But the requests seem to be correct for me, so my first impression is that something in oCIS goes wrong here.

Edit: I also ran the head request via curl, which is giving me `401 Unauthorized` as well.

**Comment by micbar** [comment]
@kobergj FYI

**Comment by kobergj** [comment]
Fix was merged. Problem is gone with current master

@JammingBen we can remove the workaround now

**Comment by JammingBen** [comment]
Thx, works fine 👍  See https://github.com/owncloud/web/pull/6890 for frontend follow up.
