### ISSUE TITLE
Shares api expose incoming shares, even if payload `shared_with_me: true` is not provided

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3592]
## Describe the bug

Shares api exposes incoming shares, even if payload `shared_with_me: true` is not provided

## Steps to reproduce

1. Create user admin
2. Create user einstein
3. Create file.txt as admin
4. Share file.txt with einstein
5. Curl  Request URL: `https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?reshares=true&include_tags=false&share_types=0%2C1%2C4%2C6
` with user einstein
6. See that the response provides the incoming share for user einstein from the user admin

## Expected behavior
Like in oc10, incoming shares should only be exposed in the shares API if the payload contains `shared_with_me: true

## Actual behavior
Incoming shares are exposed even if the payload doesn't contain `shared_with_me: true

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by C0rby** [comment]
I can't reproduce this with the current master branch.

The response looks like this:
```
curl -s -k -u einstein:relativity https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares\?reshares\=true\&include_tags\=false\&share_types\=0%2C1%2C4%2C6
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>ok</status><statuscode>100</statuscode><message>OK</message></meta><data></data></ocs>% 
```

**Comment by micbar** [comment]
@JanAckermann Can you confirm?

**Comment by JanAckermann** [comment]
Confirming, fixed
