### ISSUE TITLE
Uploading empty files via tus is not working

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#3599]
Uploading empty files (0 bytes) via tus is currently not working.

When trying to upload such file, the initial `POST` request will be send (e.g. to `https://localhost:9200/remote.php/dav/files/admin`), but no further `PATCH` requests will be send as there is no data to send. This is correct behavior, therefore Web expects oCIS/Reva to create such files on the initial `POST` request in case `Content-Length` is `0`.

**Comment by pascalwengerter** [comment]
Closed as duplicate of #3154, thanks for reporting!
