### ISSUE TITLE
Public link quick action button is not working

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#3610]
## Describe the bug
When clicking on the quick action button to create a public link, a public link doesn't create (nothing happens).

## Steps to reproduce

1. login with valid credential
2. navigate to file page
3. click on public link quick action button
![action1](https://user-images.githubusercontent.com/54478846/165690798-5cd5d5b4-75c0-49fd-82fa-b9cb7fa70723.png)

## Expected behavior
![corepublic](https://user-images.githubusercontent.com/54478846/165695991-744a72a3-8a32-4eaf-ac53-19458bad45b8.png)

## Actual behavior
no owncloud log occurs regarding public link creation
![quickactionbutton](https://user-images.githubusercontent.com/54478846/165690981-d04bd21b-3d66-49ba-be27-0fa642bac95a.png)
## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION= latest
BRANCH= master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by micbar** [comment]
@amrita-shrestha This should be fixed in the current release 2.0.0-beta1

For me it is working, i just retested.

Fell free to close this issue.
