### ISSUE TITLE
Demo User Creation post first start of ocis

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3617]
Based on an issue and discussion with @rhafer, see [Demo User Creation Question](https://github.com/owncloud/ocis/issues/3593#)

ATM, you need to set the environment variable `IDM_CREATE_DEMO_USERS` on **FIRST** start of ocis if you want to have demo users created. A later possibilty is currently not given.

This is a bad situation for any testers as the "quickly" will run ocis to see what it is about without going into depth and read the documentation in detail. Later when they see they want to extend the playground with demo users, they cant do this anymore. This situation is not acceptable nor explainable. In a nutshell, you cant tell potential customers you are f*** up and need to delete your environment and restart the thing.

**Therefore it is necessary**, that the creation of demo users is not dependent on first start but can be done at any later time.

@micbar @wkloucek @butonic @rhafer

@EParzefall fyi

**Comment by micbar** [comment]
ping to keep open

**Comment by dragonchaser** [comment]
This is IMHO a massive security issue. We should not have any default values in prod systems (and not be able to create these). 
I suggest closing this. If a user needs demo users for testing, they should be created manually.

**Comment by mmattel** [comment]
ATM we actually have in the documentation the task to set the demo user env on first startup including that you need to resetup the system if you have forgotten to set but wanted it and a description how to post delete the demo users if set on first startup. I am fine with closing.
