### ISSUE TITLE
run full-ci not on tagging but on tip the branch and then tag without CI

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3630]
an idea for the release process would be not run full-ci on tagging but before that and then tag without running tests but only building

CC @micbar

**Comment by micbar** [comment]
@individual-it Qa p3 IMO

**Comment by micbar** [comment]
@SwikritiT Thanks! It works nice.

There are still 3 pipelines which we could drop for the tagging. I added a screenshot.

![1658239579724](https://user-images.githubusercontent.com/4378513/179770993-55f3cc4f-7aa3-4add-adf2-60a9e7f9279e.png)

**Comment by SwikritiT** [comment]
> @SwikritiT Thanks! It works nice.
> 
> There are still 4 pipelines which we could drop for the tagging. I added a screenshot.
> 
> ![1658239579724](https://user-images.githubusercontent.com/4378513/179770993-55f3cc4f-7aa3-4add-adf2-60a9e7f9279e.png)
I'll make a PR for it.
