### ISSUE TITLE
`ocis init`  with diff mode

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#3645]
It would be nice add an additional diff flag to ocis init (`ocis init --diff`) which would, instead of creating a new `ocis.yaml`, output a patch that represents the changes that would be made to the config file upon re-run. This would give us the opportunity to represent breaking changes and new config variables to admins without requiring to do a deep dive into the documentation upon each major release to search for changes.

/cc @mmattel

**Comment by mmattel** [comment]
Not only on restarting with the init flag, but this could also be used like a dry-run flag on first start as the file does not extist and therefore all is in the diff ! 😄

**Comment by micbar** [comment]
Slightly related to #3917 

@pmaier1 needs clarification for GA

**Comment by pmaier1** [comment]
After GA.

**Comment by dragonchaser** [comment]
This would also be a nice feature for L1/L2 support to run against the customers/users config and see potential errors.

**Comment by mmattel** [comment]
This would be a very helpful change with regards to the upgrading documentation and eases the upgrade process a lot.

**Comment by kobergj** [comment]
I would rather go for an automated approach: Have new command `ocis upgrade` (naming tbd) that does the update automatically. To be safe about breaking change this should only print out the changes it wants to do, but don't execute them. After you checked them  you can then add them to your ocis config by running `ocis upgrade --execute` (naming tbd)

**Comment by dragonchaser** [comment]
@micbar can we move that into the next planning and talk about it?

**Comment by dragonchaser** [comment]
Closing here for now, the upgrade is more complex and we should create a separate ticket for that.
