### ISSUE TITLE
No help topic for 'init'

### ISSUE THREAD

**Issue by mrblumi** [owncloud/ocis#3682]
## Describe the bug

When running `./ocis init --config-path /path/to/config` as suggested [here in the docs](https://owncloud.dev/ocis/deployment/systemd/) I receive the output `No help topic for 'init'` and nothing else happens

## Steps to reproduce

1. wget https://github.com/owncloud/ocis/releases/download/v1.20.0/ocis-1.20.0-linux-amd64
2. chmod +x ocis-1.20.0-linux-amd64
3. ./ocis-1.20.0-linux-amd64 init --config-path /path/where/configs/should/go

## Expected behavior
I would expect some basic configuration files to be created in the provided path - or at least anything to happen...

## Actual behavior
Nothing - ocis only prints `No help topic for 'init'` to the console

## Side notes
I tried this on a fresh install of Arch Linux (x86_64, kernel version 5.17.5-arch1-1) and on several other Arch installations - maybe this might be important, I am not that familiar with go...

**Comment by wkloucek** [comment]
Oh sorry, the documentation is ahead of the release in this case. `ocis init` is not included in oCIS 1.20.0 Tech Preview as stated in the documentation. It will be included in the upcoming 2.x versions, 2.0.0-alpha1 has it already https://github.com/owncloud/ocis/releases/tag/v2.0.0-alpha1

Sorry for the confusion

**Comment by mrblumi** [comment]
Nice :) I will use this one. I wasn't aware that there was already a built version of the 2.0.0-alpha1 candidate. Shall I close this issue?
