### ISSUE TITLE
Ansible deployment

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#37]
The idea is to be able to deploy and maintain a production instance with nexus as the starting point. This would allow support to reproduce issues based on the ansible scripts.

- [ ] add a `make deployment` that uses a dedicated repository with ansible scripts

**Comment by refs** [comment]
Is this still relevant?

**Comment by refs** [comment]
ping @butonic

**Comment by wkloucek** [comment]
Seems to be fixed with our [continuous deployed examples](https://owncloud.github.io/ocis/deployment/continuous_deployment/)
