### ISSUE TITLE
Propfind on Share Jail (type: virtual) does not list items

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/ocis#3719]
## Steps to reproduce

1. Create some shares with user A
2. Accept with user B
3. Propfind on dav url for Share Jail of user B

## Expected behavior
The state of Share Jail and all its child items to be reported

## Actual behavior
A clear and concise description of what happened.

Only the state of the Share Jail, not of its children is reported.

**Comment by butonic** [comment]
fixed by https://github.com/owncloud/ocis/pull/3842

**Comment by butonic** [comment]
https://github.com/owncloud/ocis/pull/3842 is merged
