### ISSUE TITLE
Share jail: how to rename shares?

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#3721]
## Describe the bug

Before the share jail, renaming a share is a `MOVE` on the mountpoint in the personal home via webdav v2 personal home.
After the share jail, renaming a share would be a `MOVE` on a webdav root, i.e. `dav/spaces/<share jail id>!<share id>`. Which is kind of expected. But this brings up the question of how to rename a share per user. Is that forbidden in oCIS for now? Does it need an entirely new concept?

We've disabled renaming shares in the web ui for now when the share jail is enabled via capabilities. So this is not urgent, but still a regression.

**Comment by butonic** [comment]
https://github.com/cs3org/reva/pull/2884 got merged. It should be possible to do a rename in the share jail.

**Comment by butonic** [comment]
I think we can drop the needs concept tag

**Comment by butonic** [comment]
stat and move requests need to handle more cases to make this possible. work is started with https://github.com/cs3org/reva/pull/2886 but I'll go play with the parallel deployment now ...

**Comment by butonic** [comment]
should be fixed with https://github.com/cs3org/reva/pull/2904, https://github.com/cs3org/reva/pull/2886 was only a partial fix

**Comment by butonic** [comment]
With https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.3 the share jail can be used to rename a share mount point by sending a `MOVE /dav/spaces/{sharejailid}/oldname` with a `Destination: .../dav/spaces/{sharejailid}/newname`.
