### ISSUE TITLE
ocis init - naming of ocis in the questionaire

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3722]
Due to the recent changes in naming ocis -> Infinite Scale, we should rename the question on initialisation:

`Do you want to configure ocis with certificate checking disabled?`
-->
`Do you want to configure Infinite Scale with certificate checking disabled?`

This must be part of our beta rollout.
Note that we have already renamed it in the admin docs

@micbar @wkloucek @butonic 
@EParzefall fyi

**Comment by butonic** [comment]
clarification: internally the codename remains `ocis`. User facing texts, as in documentation or UI strings will be `Infinite Scale`.

@micbar @jrinkewitz please confirm

**Comment by jrinkewitz** [comment]
confirmed



--

Store. Share. Work.

https://owncloud.com



Jakob Rinkewitz

Head of Marketing



email: ***@***.***

phone: +49 171 5520108



ownCloud GmbH

Rathsbergerstrasse 17

90411 Nuremberg, Germany



Managing Directors: Tobias Gerlinger, Holger Dyroff

Court of Registry: Amtsgericht Nuremberg

Commercial Register No.: 28050









-----Original message-----
