### ISSUE TITLE
`HEAD` request for versions fails with `501 Not Implemented`

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#3741]
## Steps to reproduce

1. Create a new version for an existing file.
2. Try to make a `HEAD` request for this file (sth. like `https://localhost:9200/remote.php/dav/meta/1284d238-aa92-42ce-bdc4-0b0000009157%24859585a6-b91a-4f34-b1ec-7f9b17e4247c\!2b6dd664-af8e-47e4-afe4-78e645d7fa2d/v/2b6dd664-af8e-47e4-afe4-78e645d7fa2d.REV.2022-05-09T09%3A16%3A57.345711753Z`) -> fails with `501 Not Implemented`. A copy request for this same URL works fine.

**Comment by ScharfViktor** [comment]
> @ScharfViktor We should create an API test for that.

sure, I'll do it
