### ISSUE TITLE
Avoid cgo dependencies

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis#375]
following https://ops.tips/notes/glibc-golang-learnings/#how-can-i-see-what-requires-cgo
I see these cgo dependencies for ocis:

```
crypto/x509
github.com/mattn/go-sqlite3
os/user
plugin
runtime/cgo
```

Ideas howto remove those?

**Comment by IljaN** [comment]
os/user dependency could be potentially removed by https://github.com/cs3org/reva/issues/964

**Comment by IljaN** [comment]
From https://golang.org/doc/go1.11

> The os/user package can now be built in pure Go mode using the build tag "osusergo", independent of the use of the environment variable CGO_ENABLED=0. Previously the only way to use the package's pure Go implementation was to disable cgo support across the entire program.

**Comment by IljaN** [comment]
After further research it seems that we can't get rid of cgo fully as the glibc is requried for LDAP-DNS queries and mDNS lookups via golang stdlib.

https://golang.org/pkg/net/#hdr-Name_Resolution

Generally all of cgo can be disabled by CGO_ENABLED=0 but any problems with linking will surface during runtime. 

There are some very hacky workarounds which embed the dynamic lib in to the binary:
https://www.arp242.net/static-go.html
https://www.osso.nl/blog/golang-statically-linked/

**Comment by refs** [comment]
todo: add tradeoffs from not using cgo

**Comment by IljaN** [comment]
bump

**Comment by refs** [comment]
update: these are the current packages using CGo:

```console
~/code/owncloud/ocis/ocis/cmd/ocis master
❯ go list -f "{{if .CgoFiles}}{{.ImportPath}}{{end}}" $(go list -f "{{.ImportPath}}{{range .Deps}} {{.}}{{end}}") ./...
github.com/mattn/go-sqlite3
net
os/user
plugin
runtime/cgo
```

**Comment by pascalwengerter** [comment]
@refs could you check again and close if applicable?
