### ISSUE TITLE
Issues with audit service

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#3753]
Results from smoke testing the audit service
- [x] Typo in public link created event: `user '1717570b-cd90-465b-97f4-b3e01f0a1104' created a public to file '36d8ff14-4a32-4013-88cf-38a18414df3e' with id 'PvmHJaJJCXukypZ'`
- [x] Audit service logs error when creating a folder: `ERR can't handle event of type 'events.ContainerCreated'`
- [x] Missing acting user for most events
- [x] Missing timestamp for most events
- [x] #4583
- [x] the link ID is missing on `LinkAccessed` events that are not successful (eg. wrong password)
   - https://github.com/cs3org/reva/pull/3993
   - #6554
- [x] ProviderID is missing on space `disabled` and `deleted` events
  #6548 
- [x] `UserFeatureChanged` events do not reflect what was changed and do not include roles 
       #6537 
- [x] creating directories does not log the user

**Comment by wkloucek** [comment]
partly fixed by https://github.com/owncloud/ocis/pull/3941 and https://github.com/cs3org/reva/pull/2945

**Comment by C0rby** [comment]
This is happening because we are publishing the event when `GetPublicShareByToken` was called but this method is also being called to authenticate the request and so on. Because of that the event gets published multiple times.

**Comment by butonic** [comment]
creating directories does not log the user:
```
{"RemoteAddr":"","User":"","URL":"","Method":"","UserAgent":"","Time":"","App":"admin_audit","Message":"user 'ddc2004c-0977-11eb-9d3f-a793888cd0f8' created folder '1284d238-aa92-42ce-bdc4-0b0000009157$ddc2004c-0977-11eb-9d3f-a793888cd0f8!ddc2004c-0977-11eb-9d3f-a793888cd0f8/Neuer Ordner (4)'","Action":"container_create","CLI":false,"Level":1,"Path":"./Neuer Ordner (4)","Owner":"","FileID":"1284d238-aa92-42ce-bdc4-0b0000009157$ddc2004c-0977-11eb-9d3f-a793888cd0f8!ddc2004c-0977-11eb-9d3f-a793888cd0f8/Neuer Ordner (4)"}
```
