### ISSUE TITLE
Single File user shares preview broke and download action missing

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#3760]
## Describe the bug

1. Share A single file with user einstein
2. Log in as einstein
3. Browse to the shares page (No thumbnail expected for "pending" shares
4. Accept the share

## Expected behavior
See a single file in the lis with preview image and download action

## Actual behavior

- No dowload action
- Preview is broken

## Screenshot
![1652194110429](https://user-images.githubusercontent.com/4378513/167657092-d0b703e0-b007-4ef6-93e6-525544daf733.png)

## Setup
https://ocis.ocis-traefik.released.owncloud.works/ ocis version `2.0.0-beta1`

**Comment by micbar** [comment]
@kulmann FYI

**Comment by kulmann** [comment]
Download action for single files and for folders will become available in web with https://github.com/owncloud/web/pull/6936
But single file shares result in `download` being the filename of the downloaded file

**Comment by micbar** [comment]
@kulmann my observations are interesting.

1) The thumbnails work if you append the Filename to the ID in the webDAV URL

2) Where does web get the filename for the download? From the HEAD request?

**Comment by micbar** [comment]
found 2) out thanks to @fschade 

It was the content disposition header. Was fixed already in reva edge https://github.com/cs3org/reva/pull/2855

1) fix PR is ready
