### ISSUE TITLE
docs: Outdated docs (mentioning glauth, accounts and other outdated things)

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#3766]
## Describe the bug

The follwoing files in our dev docs this mention the accounts and/or glauth services and also look outdated in some other ways

- [ ] ocis/deployment/bridge.md
- [x] ocis/development/beta-testplan.md
- [x] ocis/development/getting-started.md
- [ ] ocis/flow-docs/login-flow.md
- [ ] ocis/flow-docs/request-flow.md
- [ ] ocis/getting-started/_index.md
- [ ] ocis/static/ocis-config-redesign.drawio.svg
- [ ] ocis/storage-backends/eos.md
- [ ] ocis/migration.md
- [ ] ocis/storage_registry_discovery.md
- ~~ocis/release_notes.md~~ (obsolete)

https://github.com/owncloud/ocis/pull/3685

**Comment by mmattel** [comment]
I made the list on top a checkmarked list and checked all non existing entries via a double check.

The remaining elements must be manually removed by a _brave_ one 😅 before closing that issue.

**Comment by dragonchaser** [comment]
- ocis/deployment/bridge.md -> is this still planed? If not -> remove

**Comment by micbar** [comment]
> dev.owncloud.com -> mermaid is broken, all flow charts are defective
@mmattel how can we fix this?

That is DEV responsability. We need to find out, could be needed to bump hugo or the geekdoc theme version.

**Comment by dragonchaser** [comment]
ok looking into it

**Comment by dragonchaser** [comment]
found it, current implementation does not support `<br>` tags in mermaid graphs anymore :facepalm:

**Comment by mmattel** [comment]
Closing, no issues open anymore
