### ISSUE TITLE
upload failure message when disk full

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3767]
## Describe the bug

when uploading a file on a oCIS instance with full disk we don't have a speaking error message.

## Steps to reproduce

1. have an oCIS instance
2. have your disk full
3. upload a file larger than the remaining free disk space

## Expected behavior
Have an error message: "upload failed because not sufficient space on  the target system"

## Actual behavior
error message: "upload failed"

![image](https://user-images.githubusercontent.com/34452982/167845257-ee6130ff-87de-4fea-ab71-58713c8c66d5.png)

The log says:
`{"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"error: insufficient storage: disk full","status":{"code":19,"message":"insufficient storage","trace":"00000000000000000000000000000000"},"time":"2022-05-11T11:58:59Z","message":"failed to initiate upload"}`

## Setup

oCIS 2.0.0-beta1 on a server with constrained disk

**Comment by pascalwengerter** [comment]
If OCIS responds with e.g. a [407](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/507) we could check for that in web and then render (translated) strings to the UI, which AFAIK the backend is not able to

**Comment by dragonchaser** [comment]
There is a PR on reva: https://github.com/cs3org/reva/pull/2891 to fix this.
@pascalwengerter a 507 is returned as soon as said PR is merged, I thin kthis needs handling in the UI.
