### ISSUE TITLE
Use service names as endpoint prefix

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#377]
Currently, the accounts service requires a proxy entry for `/accounts.js`, `/api/v0/accounts/`and maybe `/api/v0/groups/`.

The proxy should expose services based on their service name, eg:
- `/accounts/`
- `/hello/`
- `/ocs/`
- `/ocdav/`
- `/reva/`
- `/thumbnails/` (or rename to `thumbs`?)

all should route to the corresponding services

for phoenix (web) / should be the root of the app, (well it should be configurable), but the rest could be exposed at `/phoenix/` or `/web/`

related:
- https://github.com/owncloud/ocis-accounts/pull/50#pullrequestreview-446436426
- https://github.com/owncloud/ocis-proxy/pull/65

**Comment by butonic** [comment]
cc @kulmann

**Comment by refs** [comment]
Currently, the proxy config addresses exactly this, but a new concept for default extensions is welcomed.

**Comment by refs** [comment]
This should is still relevant.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
