### ISSUE TITLE
As admin, I can access user management after demoting myself

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/ocis#3784]
## Describe the bug
I shouldn't be able to access to the user management page (or access as regular user) and I shouldn't be able to perform actions if I become a regular user.

## Steps to reproduce

1. As user "admin", go to the user management page
2. Edit user "admin" and set the role to "user"
3. Try to perform any additional operation

## Expected behavior
Operation on step 3 shouldn't be possible because he isn't an admin any longer.
Alternatively, the user "admin" shouldn't be able to change his own role.

## Actual behavior
* Operation on step 1 is successful (not sure if it should be or not)
* user "admin" is listed as regular user
* user "admin" can still perform operations
* It seems other users with the admin role behave as expected.

## Setup
Basic oCIS 2.0.0.beta1 with the demo users enabled. The rest of the setup is the default one.

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

## Additional context
It seems this happens only with the "admin" user, so maybe the "admin" user keeps the admin role. However, if this is the case, he shouldn't be able to have a different role.

**Comment by micbar** [comment]
this should be fixed in 2.0.0-beta5

**Comment by michl19** [comment]
Fixed by #4181

**Comment by micbar** [comment]
According to our improvements regarding the release flow, this is a very good example where we need to write a new test to prevent further regressions.

@dragotin @ScharfViktor JFYI

**Comment by ScharfViktor** [comment]
Re-tested: 
Actual result: admin can change his own role and after that he cannot manage users

@micbar what we expect? I thought we prohibit admit to edit own role https://github.com/owncloud/ocis/issues/3713#issuecomment-1167260076
