### ISSUE TITLE
CI binary build for windows?

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3789]
Accidentially stumbled over this and I was questioning myself why we have a CI binary build for Windows but Windows is not in our support matrix (WSL), maybe a leftover?...

@wkloucek @micbar 

![image](https://user-images.githubusercontent.com/3321281/168085438-0f701fbb-dd68-4fb3-92c9-03621c760f99.png)

**Comment by wkloucek** [comment]
Darwin (MacOS) should also not be in the support matrix.

In reality sometimes the build alone found some special cases about MacOS / Windows. Therefore I would rather keep these steps.

Don't know if we should only build supported target platforms. This would be rather a decision from PO.

**Comment by mmattel** [comment]
bump
