### ISSUE TITLE
Reminder: co-dependencies / merge preparation

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#380]
The most recent changes in
- [ocis-proxy](https://github.com/owncloud/ocis-proxy/pull/66) and
- [ocis-account](https://github.com/owncloud/ocis-accounts/pull/50)

depend on each other.

When preparing to merge (soon to be) releases of those repos into ocis, we need to merge them at the same time. Otherwise ocis will break.

**Comment by kulmann** [comment]
cc @micbar @PVince81

**Comment by PVince81** [comment]
I assume with "merge" of the releases you mean updating go.mod. This should likely be done in a single PR with all releated dependencies to be updated.

**Comment by kulmann** [comment]
Correct, that's what I meant.

Don't know if the repositories are ready for releases, yet, so I wanted to have a reminder here. Happy to hear about a better way to track this. :-)

**Comment by micbar** [comment]
@kulmann @butonic how far are we?

**Comment by kulmann** [comment]
@micbar current status is here: https://github.com/owncloud/ocis/pull/409

**Comment by kulmann** [comment]
There are issues with LDAP+accounts-service

**Comment by refs** [comment]
irrelevant with the monorepo + local replaces approach.
