### ISSUE TITLE
`OCIS_INSECURE=true' breaks  the graph api

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3812]
## Describe the bug
setting the environment variable OCIS_INSECURE=true breaks the graph api ldaps connection because GRAPH_LDAP_INSECURE needs always be true, since we have a ldaps connection to the idm and don't use the ca cert in the graph extension

As a workaround for our deployment examples we set:
```
      OCIS_INSECURE: "${INSECURE:-false}"
      GRAPH_LDAP_INSECURE: true
```

**Comment by TheOneRing** [comment]
```
docker-compose pull
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.ocis.environment.GRAPH_LDAP_INSECURE contains true, which is an invalid type, it should be a string, number, or a null

**Comment by rhafer** [comment]
Should be fixed with the above PR
