### ISSUE TITLE
REVA services have wrong name in traces

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3815]
## Describe the bug

REVA services have wrong names in traces: 
![image](https://user-images.githubusercontent.com/34452982/168846031-8afba2e2-c449-4af3-be93-d2035217dbfa.png)

This is because the tracing provider is stored at package level (and therefore our reva services overwrite their names => last one wins) https://github.com/cs3org/reva/blob/627d0d3f2cd15ebd359c010ce65013fdc778ba8b/pkg/trace/trace.go#L38-L39

**Comment by rhafer** [comment]
fixed via https://github.com/cs3org/reva/pull/2962
