### ISSUE TITLE
Demo user katherine got lost

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/ocis#3823]
When starting a new ocis setup with DEMO_USERS=true the user katherine  will no longer be created.

**Comment by mmattel** [comment]
@TheOneRing I just can encourage you to read the public admin docu, in particular the [Default Users and Groups](https://doc.owncloud.com/ocis/next/deployment/general/general-info.html#default-users-and-groups) section, but you should not limit reading to this section. I highly recommend to go thru the various chapters to get an insight.

The environment variable `DEMO_USERS` has been replaced by `IDM_CREATE_DEMO_USERS` and is bound to the `ocis init` command.
