### ISSUE TITLE
Some services missing on the oCIS service registry

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3826]
## Describe the bug

Some services are missing on the oCIS service registry. Check that all are availablee.

## Steps to reproduce

1. `ocis server`
2. `ocis version`

## Expected behavior
All running extensions are listed

## Actual behavior
Not all extensions are listed, eg. NATS, IDM, ...

**Comment by dragonchaser** [comment]
IDM & NATS are not grpc or http services, no need to list them.
