### ISSUE TITLE
New resharing concept breaks testsuite

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#3828]
## Describe the bug

With the new reshare concept some tests are failing. We need to discuss how we can adjust them (or if the reshare concept is faulty)
See https://github.com/cs3org/reva/pull/2877

## Steps to reproduce
With reva from https://github.com/cs3org/reva/pull/2877 and master ocis run test mentioned in list

## Expected behavior
The test should pass

## Actual behavior
The tests fail

**Comment by micbar** [comment]
@phil-davis @individual-it we need to work together on this. The main problem is that the bitmask for the permissions has `31` as a representation for `all permissions` which is not true anymore.

**Comment by kobergj** [comment]
@phil-davis @micbar @individual-it sorry this ticket is not ready yet. I'm still trying to figure out which tests need to be fixed. So nothing to do atm. Sorry for confusion

**Comment by kobergj** [comment]
Update: reva seems fine with the changes, we have just some spaces ocis test failing. They are explicitly testing that resharing does not work. So these need to be changed. See list of failing tests in ocis PR:
https://github.com/owncloud/ocis/pull/3804/files#diff-733a682a252e8a35d985692d58d7b793107aa0abe81eac800edd774e3415fc07R26-R34

**Comment by micbar** [comment]
@kobergj thanks!

I am fine with adding these tests to the expected failures now.

@ScharfViktor Can then evaulate changes to the gherkin steps later.

**Comment by ScharfViktor** [comment]
> 

Yes, sure. I'll do it

**Comment by kobergj** [comment]
Just small info: Web is already working on sending roles instead of int permissions. @fschade is that already merged?

**Comment by kobergj** [comment]
@individual-it @phil-davis 

We found an issue with the reva test suite. You can see it in `apiShareReshareToShares3/reShareUpdate.feature:153` for example.

We think the problematic test line is:
`And user "Alice" has updated the last share of "Alice" with`
The `last` share will send a request for the wrong share (here `4` instead of the correct `3`) 
It is probably related to int ids of reva, as the test works correct against ocis (which is using uuids)

For now this not blocking us, as tests get green anyways, but I have no clue how many other tests are affected.

cc @fschade @micbar

**Comment by phil-davis** [comment]
Note: I am working on issue https://github.com/owncloud/core/issues/40093 in PR https://github.com/owncloud/core/pull/40095 - that aims to make all those "somebody does something related to the last share" steps work regardless of the format of share-ids. The test code will remember more of the shares that it created in a scenario, and will avoid ever having to do a "general API query" to discover the shares that exist - no more making a "partly-educated guess" about what "the last share" refers to.

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/40114 is in review. Hopefully it all passes and can be merged overnight. Then I will bump the core-commit-id in reva and oCIS. That should help with test steps about "the last share"

**Comment by micbar** [comment]
Done
