### ISSUE TITLE
oCIS http broker

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3829]
## Describe the bug

When starting oCIS, a gomicro http broker is started automatically, even through oCIS uses NATS as event broker.

## Steps to reproduce

1. `ocis server'
2. `ss -lntp | grep "ocis"`
3. see two random ports, one of them is ocdav the other one is the http broker

See also https://github.com/asim/go-micro/blob/13b76331ec6f31f4122ade7c2e06e009ffae2b4d/broker/broker.go#L45-L47

## Expected behavior
No unused http broker is started

## Actual behavior
An unused http broker is started and binds to a random port on 127.0.0.1

**Comment by C0rby** [comment]
@wkloucek, how do you know it's a HTTP broker?
