### ISSUE TITLE
Improve users/groups graph api endpoint

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#3837]
To build up a performant user management with user and group assignments it is necessary to improve the graph API:

1. `/graph/v1.0/users/` endpoint should include a field where assigned groups are listed (maybe $expand is necessary)
2. `/graph/v1.0/users/{id}/` endpoint should include a field where assigned groups are listed (maybe $expand is necessary)
3. `/graph/v1.0/groups/` endpoint should include a field where assigned users are listed (maybe $expand is necessary)
4. `/graph/v1.0/groups/{id}/` endpoint should include a field where users are listed (maybe $expand is necessary)
5. ~We need an endpoint to set the user's group with one request instead of adding and deleting group relations by single requests~
6. ~We need an endpoint to set the group's users with one request instead of adding and deleting user relations by single requests~

5 & 6 extracted into it's own [issue](https://github.com/owncloud/ocis/issues/3963)

**Comment by JanAckermann** [comment]
FYI @butonic 

**Please NOTE:** The API specification clain that point 1-4 is already possible, what is not the case. We SHOULD really not add things to our API specification which are not included yet, the specification should represend the current state AND NOT contain future improvements

**Comment by micbar** [comment]
let us treat it as a bug and fix it.

**Comment by kulmann** [comment]
I agree, 5 & 6 can be mitigated client side for the moment. 1-4 would be good to have.

**Comment by fschade** [comment]
@dragonchaser, point 5 & 6 is extracted into a separate issue to keep this rolling.

https://github.com/owncloud/ocis/issues/3963
