### ISSUE TITLE
the reva share manager is inefficient

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#3839]
# stats every shared resource
```go
	// TODO: This is a hack for now.
	// Can we do that cleaner somehow?
	// The `ListStorageSpaces` method in sharesstorageprovider/sharesstorageprovider.go needs the etags.
	shareMetaData := make(map[string]share.Metadata, len(res.Shares))
	for _, rs := range res.Shares {
		// Stat .. here, only for etag and mtime? and then we throw the rest away?
		sRes, err := s.Stat(ctx, &provider.StatRequest{Ref: &provider.Reference{ResourceId: rs.Share.ResourceId}})
		if err != nil {
			logger.Error().
				Err(err).
				Interface("resourceID", rs.Share.ResourceId).
				Msg("ListRecievedShares: failed to stat the resource")
			continue
		}
		if sRes.Status.Code != rpc.Code_CODE_OK {
			logger.Error().
				Interface("resourceID", rs.Share.ResourceId).
				Msg("ListRecievedShares: failed to stat the resource")
			continue
		}
		shareMetaData[rs.Share.Id.OpaqueId] = share.Metadata{ETag: sRes.Info.Etag, Mtime: sRes.Info.Mtime}
	}
```
The sharesstorageproevider not only needs the etag and mtime. It may need a full stat response to build the virtual share jail https://github.com/owncloud/ocis/issues/3719

The sharesstorageprovider should make the stat requests itself. PR in https://github.com/cs3org/reva/pull/2885

And it can omit that for unmounted shares ... which brings us to the next issue...

# cannot filter by un/accepted shares
When listing mountpoints unaccepted shares can be omitted. The CS3 API needs a filter to allow filtering.
tracked in https://github.com/owncloud/ocis/issues/3843

**Comment by micbar** [comment]
Done by #4431 and #4436 and #4539 and #4430
