### ISSUE TITLE
CS3 API needs a ListReceivedShares filter by state, ...

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#3843]
... so the sharesstorageprovider can limit the amount of shares it has to deal with to only the accepted ones. Currently, there is no state filter: https://cs3org.github.io/cs3apis/#cs3.sharing.collaboration.v1beta1.Filter

Related:
https://github.com/cs3org/reva/issues/2881
https://github.com/owncloud/ocis/issues/3839

**Comment by C0rby** [comment]
The filter has been added to the CS3API.
