### ISSUE TITLE
send (MOVE,COPY) requests to another user's webDav endpoints as normal user gives 400 instead of 404

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#3882]
## Steps to reproduce

1. As user alice create file `textfile0.txt`
2. As user Brian send `MOVE` request to Alices endpoint `/remote.php/dav/files/Alice/textfile0.txt`

## Expected behavior
As in oc10 it should return with `403`
```
MOVE /core/remote.php/dav/files/Alice/textfile0.txt HTTP/1.1
Host: 172.17.0.1
User-Agent: GuzzleHttp/7
Destination: /path/to/destination
Authorization: basic QnJpYW46MTIzNA==
OCS-APIREQUEST: true
Content-Length: 13

doesnotmatter
HTTP/1.1 403 Forbidden
Date: Thu, 26 May 2022 10:07:22 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Set-Cookie: oc5soe2gvutv=2rmte6l4ik88ptsp32670gbn84; path=/core; HttpOnly; SameSite=Strict
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=gHxym9szoLrNrSsPX%2Bp%2BIMQ7dq5sfyU4ApcVWsykP8mjCOjE4i%2F9DqW9ubaw4cNHGGYk3orY0IhgHKZHj4JKRRqbQUSkMop5PUS3rTYDxRHfnvyX0Hg5Hp%2FEn1CII25C; expires=Thu, 26-May-2022 10:27:22 GMT; Max-Age=1200; path=/core; HttpOnly; SameSite=Strict
Content-Security-Policy: default-src 'none';
Set-Cookie: oc5soe2gvutv=evmhenrj369hc3cll51133brdu; path=/core; HttpOnly; SameSite=Strict
Set-Cookie: cookie_test=test; expires=Thu, 26-May-2022 11:07:22 GMT; Max-Age=3600
Content-Length: 272
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>Requested uri (/path/to/destination) is out of base uri (/core/remote.php/dav/)</s:message>
</d:error>

```

## Actual behavior
Returns `400`
```
MOVE /remote.php/dav/files/Alice/textfile0.txt HTTP/1.1
Host: localhost:9200
User-Agent: GuzzleHttp/7
Destination: /path/to/destination
Authorization: basic QnJpYW46MTIzNA==
OCS-APIREQUEST: true
Content-Length: 13

doesnotmatterHTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Length: 0
Content-Security-Policy: default-src 'none';
Date: Thu, 26 May 2022 10:32:55 GMT
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-Xss-Protection: 1; mode=block
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=latest
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by butonic** [comment]
Actually, ocis and oc10 should return 415 (Unsupported Media Type) as per [RFC4918 Section 8.4 - Required Bodies in Requests](https://datatracker.ietf.org/doc/html/rfc4918#section-8.4):
>   Some of these new methods do not define bodies.  Servers MUST examine
>   all requests for a body, even when a body was not expected.  In cases
>   where a request body is present but would be ignored by a server, the
>   server MUST reject the request with 415 (Unsupported Media Type).
>   This informs the client (which may have been attempting to use an
>   extension) that the body could not be processed as the client
>   intended.

**Comment by SwikritiT** [comment]
Reopening this as there are still some tests linked to this issue in expected to fail
https://github.com/owncloud/ocis/blob/0676828f08d7402a896cc1773ce80c5b80bf5bb0/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L901-L907

We probably need to split the tests according to the behavior of oc10 and ocis because it oc10 the request returns `403`
```feature
Scenario: send MOVE requests to another user's webDav endpoints as normal user
    When user "Brian" requests these endpoints with "MOVE" about user "Alice"
      | endpoint                                           |
      | /remote.php/dav/files/%username%/textfile0.txt     |
      | /remote.php/dav/files/%username%/PARENT            |
      | /remote.php/dav/files/%username%/PARENT/parent.txt |
    Then the HTTP status code of responses on all endpoints should be "403"
```

TODO QA Team:
- [ ] make the tests to match the current ocis behaviour and remove the tests linked to this issue from expected to failure

**Comment by SwikritiT** [comment]
> So I just tested this and requests to another users resources now always return 404. I also opened a PR for the request body check: [cs3org/reva#2974](https://github.com/cs3org/reva/pull/2974)

@C0rby Hi are you sure this is fixed the test still report that the status code is `400` locally and also fails on CI. gives me the same response through curl
https://drone.owncloud.com/owncloud/ocis/13478/41/7

``` console
Scenario: send MOVE requests to another user's webDav endpoints as normal user # /drone/src/oc10/testrunner/tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature:57
    When user "Brian" requests these endpoints with "MOVE" about user "Alice"    # OCSContext::userSendsRequestToTheseEndpointsWithOutBody()
      | endpoint                                           |
      | /remote.php/dav/files/%username%/textfile0.txt     |
      | /remote.php/dav/files/%username%/PARENT            |
      | /remote.php/dav/files/%username%/PARENT/parent.txt |
    Then the HTTP status code of responses on all endpoints should be "403"      # FeatureContext::theHTTPStatusCodeOfResponsesOnAllEndpointsShouldBe()
      Responses did not return expected http status code
      Failed asserting that 400 is identical to 403.
```

**Comment by kiranparajuli589** [comment]
blocked util https://github.com/owncloud/ocis/issues/3882#issuecomment-1185255031 is answered.

**Comment by amrita-shrestha** [comment]
blocked until this issue resolved : https://github.com/owncloud/ocis/issues/5009

**Comment by saw-jan** [comment]
https://github.com/owncloud/ocis/issues/3882#issuecomment-1156408457
>So I just tested this and requests to another users resources now always return 404.
I also opened a PR for the request body check: https://github.com/cs3org/reva/pull/2974

Trying to MOVE with another user's endpoint return `404`
```bash
curl -XMOVE "https://localhost:9200/remote.php/dav/files/demo/myfile.txt" \
-H"Destination: https://localhost:9200/remote.php/dav/files/admin/moved.txt" \
-uadmin:admin -vk
```
```bash
< HTTP/1.1 404 Not Found
< Content-Length: 0
```

So, closing this here

**Comment by saw-jan** [comment]
Tests fixed in https://github.com/owncloud/ocis/pull/8460
