### ISSUE TITLE
Check if extended attributes can be set on startup is missing

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#3919]
## Observed behavior:

When starting ocis on a file-system that does not support extended attributes, ocis does not fail it starts and fails creating the personal-space.

## Expected behaviour:

Ocis tries to set a extended attribute on a temporary file in the used storage(s) (e.g. system-storage, user-storage etc.) and fails gracefully when not be able to set/read those attributes.

/cc @butonic @mmattel

**Comment by mmattel** [comment]
When a code change is made an merged, I will add a note in the admin docs accordingly.

**Comment by micbar** [comment]
ocis doesn't use xattrs anymore.
