### ISSUE TITLE
clarify service vs. extension

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#3926]
When going over the dev docs @mmattel noticed that I was referring to `ocdav` as a service, whereas most places use the term `extension`. Even the folder containing all ocis extensions / services is called `extensions`. But what are we extending? The ocis platform? Currently, the ocis extensions provide the core functionality of ocis. There is a difference between these _core_ extensions and actual extensions like a calender or contacts extension.

@C0rby pointed out that all extensions we currently have are actually not really _extensions_, but services that make up the ocis platform.

While we could keep calling all ocis services _extensions_ it would be clearer to call them _ocis services_. That would allow distinguishing them from _ocis extensions_ which extend the _ocis platform_ that in turn consists of at least the set of _ocis services_.

Would that mean we rename the `extensions` folder to services?

@micbar @dragotin @dragonchaser @C0rby @kobergj @owncloud/pm thoughts?

**Comment by mmattel** [comment]
Any clearance we make now, will avoid confusion and creative/challenging "explanations" later on.

**Comment by dragonchaser** [comment]
Renaming `extensions` => `services` makes sense to me, in the future we could add a new `extensions` directory where we pin third-party extensions we want to bundle using git sub-modules.

**Comment by dragotin** [comment]
So far, AFAIK we only have services that are bundled by default and make the functionality of oCIS. Extensions are optional for me, and could be maintained elsewhere as @dragonchaser says.

So I support the rename as well.

**Comment by pmaier1** [comment]
I agree with the arguments in the OP and support the rename as well.
