### ISSUE TITLE
OCDAV environment variable question

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3929]
There are two env's with questions:

`OCDAV_DEBUG_ZPAGES`
Description:
Enables zpages, which can be used for collecting and viewing traces in-me

Question: what is `in-me`...?

`OCDAV_SHARES_NAMESPACE`
Default:
/Shares

Question: why starting with a capital letter?

@butonic maybe you can help

**Comment by wkloucek** [comment]
Both issues fixed in the linked PRs
