### ISSUE TITLE
Tracing storage

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#393]
### Scenario

As a customer / client, I would like to keep hold of the traces within my deployment, and not having them obliterated on every restart.

### Background

- [jaeger uses memory as default storage](https://www.jaegertracing.io/docs/1.16/#technical-specs)

**Comment by wkloucek** [comment]
Using ElasicSearch for Jaeger Collecotor as storage: https://github.com/owncloud-devops/monitoring-tracing-server
