### ISSUE TITLE
File in collabora opens in read-only mode for the owner

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#3936]
Test with wopi:

- start docker-compose up -d https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml
- admin creates file odt (file should be opened in collabora)
- add content and save. 
- close file and open again

Actual result: file opens in read-only permissions mode

![Screenshot 2022-06-08 at 18 01 32](https://user-images.githubusercontent.com/84779829/172666122-e52ec270-019e-4604-8332-31e0b219c255.png)

ocis_wopi_collabora log

```
wsd-00008-00404 2022-06-08 16:05:47.519043 [ docbroker_017 ] WRN  Un-successful WOPI::Lock with status 409, failure reason: "The file is locked by Collabora" and response: {"message": "The file is locked by Collabora"}| wsd/Storage.cpp:977

wsd-00008-00404 2022-06-08 16:05:47.519195 [ docbroker_017 ] ERR  Failed to lock!| wsd/DocumentBroker.cpp:882
```

**Comment by wkloucek** [comment]
Looks like a locking race condition. The first Collabora session holds the lock and did not yet release it because it didn't yet save the file. Then the second Collabora session already tries to open the still locked file and fails.

We should at least investigate in how we can improve this.

**Comment by micbar** [comment]
Needs investigation. The unlock should happen.

**Comment by wkloucek** [comment]
> Needs investigation. The unlock should happen.

The unlock happens. But not as fast as the user opens again that file. And since the session is currently closing, you can't just resume the edit.

**Comment by ScharfViktor** [comment]
Couldn't reproduce it. no log in collabora
