### ISSUE TITLE
Investigate Go Vendoring

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#3937]
During a discussion with @rhafer  we came to the conclusion that it would make sense to investigate if we can vendor our dependencies using `go mod vendor`. This should result in faster CI-Builds and, in case of module de-publication by its original author, we would not have a broken source tree.

**Comment by individual-it** [comment]
PR here https://github.com/owncloud/ocis/pull/4032 but the PR got closed, so closing this also
