### ISSUE TITLE
collect statistics about how much which tests are failing

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3938]
we should collect statistics about which tests fails how often, currently this only happens manually on the nightly, but we could automatize the system

idea by @rhafer

**Comment by rhafer** [comment]
This is (was) what I was referring to: https://docs.openstack.org/contributors/code-and-documentation/elastic-recheck.html

However it seems that the project has been wound down and is no longer maintained (lack of resources). http://lists.openstack.org/pipermail/openstack-discuss/2021-May/022439.html (for details)

**Comment by kiranparajuli589** [comment]
These are some points to think about before the implementation. I've put my thought into every question. Please comment if that is unnecessary or not resonable.

### Where to store the collected statistics?
- online database where we can push content after every drone build

### What to save?
- scenario name
- error log
- timestamp
- suiteName
- isRunningWithOcis
- buildId

## Which type of tests need statistics collection?
- [ ] unit tests (probably not needed)
- [ ] cs3APITests
- [ ] localAPITests
- [ ] coreAPITests
- [ ] web-ocis tests
- [ ] parallel deployment tests

## What can we achieve with the statistics collected?
- filtration by 
  - suite, timestamp, scenarios, errors

## Where/How to show/preview the stat collected?
- some static web pages

> I didn't dig deeper for OpenStack (referred by @rhafer) because as he said, it's no longer maintained.

cc @individual-it @phil-davis @rhafer

**Comment by individual-it** [comment]
The question is what we really want to achieve? For me it would be interesting to know what tests are flaky, for that it would be good to know:
1. which tests failed on merge (because that should not happen as they already ran in the PR)
2. which tests failed in nightlies
3. which tests failed and passed on retry (in normal PRs I would not collect data of tests that failed because we don't know if it failed because of a bug or because of a flaky test)

**Comment by individual-it** [comment]
according to the meeting 28.07.2022 we will collect the data manually for now from the nightly runs
