### ISSUE TITLE
build retries for ocis pipelines that are unstable because of external dependencies

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3962]
some pipelines are unstable because external dependencies fail. 
see reports in #3921 

steps that require pulling deps from remote places should be rerun in the case of failure

**Comment by rhafer** [comment]
It might make sense to just bundle all the external dependencies with the code. For go related things this should be fairly easy  (`go mod vendor` ) (see #3937). Not sure about nodejs.

**Comment by rhafer** [comment]
Note, we're also rebuilding (and with that downloading all it's dependencies over and over again) `golangci-lint` with every linter run (that is more that 20 times per CI run AFAICS).

Would be nice if we could cache the resulting `golangci-lint` binary as well (or you a prebuilt one).

**Comment by phil-davis** [comment]
Note: an easy first step would be to use `retry -t3 yarn install` to retry `yarn install` if/when it fails. That might avoid some pipeline failures.

**Comment by individual-it** [comment]
simple solution: https://github.com/owncloud-ci/retry

**Comment by individual-it** [comment]
I believe we will need both, but we can implement the cache first.

**Comment by SwikritiT** [comment]
> I believe we will need both, but we can implement the cache first.

@individual-it cache has been implemented in https://github.com/owncloud/ocis/pull/4085, shall we move forward with this as well?

**Comment by individual-it** [comment]
yes we could, but would only needed for the install before cache

**Comment by grgprarup** [comment]
Retries for `yarn install` has been implemented in https://github.com/owncloud/ocis/pull/4223. I think we can close this issue.
@individual-it @kiranparajuli589

**Comment by phil-davis** [comment]
The related PR #4223 had to explicitly fetch the retry code from owncloud-ci/retry

I was a bit surprised that the docker image did not already have that. I raised issue https://github.com/owncloud-ci/retry/issues/7 - I will follow that up separately.

**Comment by kiranparajuli589** [comment]
Caching **web**:
**owncloud/web** repo is cloned:
- during yarnCache
- every time for the UI-Test-Pipelines

We can cache the web and use it for building yarnCache and also use it inside the UI-Test-Pipelines as the test runner.

**Comment by kiranparajuli589** [comment]
Should we also retry for the followings :thinking: 
- [ ] make command in `makeNodeGenerate()`
- [ ]  make command in `makeGoGenerate()`
- [ ] make command in `build()`

cc @individual-it

**Comment by dragonchaser** [comment]
for `makeNodeGenerate()` and `makeGoGenerate()` would be aweseome

**Comment by SwikritiT** [comment]
@kiranparajuli589 All the to-do's have been done. Can be closed now?
