### ISSUE TITLE
Antora table generator needs an update

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3969]
As discussed with @dragonchaser 
Referencing: https://github.com/owncloud/ocis/pull/3960 (add more config option documentation)

We have in the description of `OCDAV_FILES_NAMESPACE` an entry looking like this: `/dav/files/{username}`.
This renders totally fine, but we do get a "missing attribute: username" warning. This is because Antora thinks it is an attribute and must resolve it. There is atm no parameter availabe for complete table cells to tell Antora to keep the layout but not to resolve attributes inside the cell.

Solution: The text in the table needs to be parsed to turn:
`/dav/files/{username}` into `/dav/files/\{username}` (or `/dav/files/\{username\}`).
Means escaping at minimum the opening curly brace.

The Antora rule for an attribute is:
opening curly brace,
directly followed by one or more alpha-numeric characters including dash and underscore,
no blanks,
closing curly brace

BUT, there is also the case like `/users/{{.Id.OpaqueId}}` where no escaping must be done!!
Means `{{` stays as it is.

**Comment by wkloucek** [comment]
wouldn't it make more sense to use something generic like this? https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/

**Comment by mmattel** [comment]
I got feedback from the antora devs where I have to test this if it works correctly:

> Is there another way to tell a complete cell not to resolve attributes but render in the default style?

The preferred way to handle this case is to escape the attribute reference as that communicates the intent correctly.

One other option you have is to turn it into an AsciiDoc table cell and remove the attributes sub on the paragraph.

```
a|
[subs=-attributes]
This is content {something}
```

If the latter works what I will test, we can make a relatively easy change. I let you know the result.

**Comment by mmattel** [comment]
OK, I did the tests and came to following result:

No complicated and time consuming regex is necessary, only a small change in the table creation process:

* Change each 3rd AND 4th entry but not the header lines to the following:
This affects the `Default Value` and the `Description` columns
```
| whatever text
```
-->
```
a| [subs=-attributes]
whatever text
```
Note that if there is no `whatever text` present, it does not make any harm to either only have a
`a| [subs=-attributes]` entry and continue with the next cell definition or the latter with an additional empty new line. Example:

```
a| [subs=-attributes]
| new cell
```
behaves identical with
```
a| [subs=-attributes]

| new cell
```
Means you can decide programatically what fits better

@dragonchaser with this info, you can start implementing it
