### ISSUE TITLE
etag propagation is not always synchronous

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3988]
in some cases etags are not propagated synchronous, e.g. tests like `apiWebdavEtagPropagation1/moveFileFolder.feature:184` or `apiWebdavEtagPropagation2/copyFileFolder.feature:188` fail randomly in CI

@butonic could you please define cases where the etag propagation is allowed to be async, so that we can adjust the tests accordingly

**Comment by butonic** [comment]
A proper implementation on the client and server side would use the `Prefer: respond-async` header as defined in https://datatracker.ietf.org/doc/html/rfc7240#section-4.1 AFAICT that is not the case and the tests currently correctly test synchronous etag propagation.

@dragotin @felix-schwarz  IIRC the clients need the file id in the response of a PUT request, right? What about the etag?

We can add `Prefer: respond-async, wait=5` to indicate that clients are willing to wait 5sec for a response. But these headers all only apply the the resource that was PUT.

I would argue that a `Prefer: respond-async, wait=5` header would allow the server to respond synchronously with all the metadata that is available for the resource, eg fileid, mtime, size, etag ... while at the same time allowing async etag propagation up the tree. `respond-async` means that the client does not need any response, which is true if clients would generate uuid fileid they send along in a PUT request, TUS upload or MKCOL request.

**Comment by dragotin** [comment]
As of now, the clients expect the ETag in response to the PUT (or the last action in the chunked uploads). 
See https://github.com/owncloud/client/blob/master/src/libsync/propagateuploadng.cpp#L572 for the Desktop example, if the etag is empty, that results in an error.

We do not want to change that now.

That is also what we are aiming for with the asynchronous upload: The ETag is returned immediately with the last PUT, and the server takes care to set/change the ETag accordingly.
 
Note that theETag just needs to change, no further semantics, so it should be not so difficult for the server to even do that synchronous.

**Comment by phil-davis** [comment]
Note: we generally see this issue in tests that do a MOVE or COPY or some upload-overwrite, the response to the request has an eTag for the particular resource. But also the eTAG of parent folders up to the root is expected to change. The delay (async behavior) is observed when the test scenario "quickly" does API requests that check the eTag of the parent, grand-parent etc folders.

So, IMO, the current implementation is OK - clients will get an appropriate eTAG in the response for the resource that they just uploaded, copied, moved... Other clients are polling higher folders to "notice" an eTag change, and then discover and sync the changes from the server to their local storage. Those clients might not notice the higher-level eTag change for a few seconds. (Typically in practice we see that the higher-level eTags are updated within 1 second anyway). For clients that are polling at around 30 second intervals anyway, 1 or 2 seconds delay in the root eTag changing is not really going to be significant.

**Comment by dragotin** [comment]
Ah, seems I overlooked that it is about the ETag change of the directories *above* the uploaded item, not the item itself. 

I agree, that sounds ok if that does not happen immediately.

**Comment by felix-schwarz** [comment]
@butonic At the moment, the iOS client uses neither `oc-fileid` nor `oc-etag`. It instead does a subsequent `PROPFIND` on the expected destination path to fetch all metadata on the file in one go.

So the expectation from the iOS client is that when the server response to the upload request has been received:
- a subsequent `PROPFIND` (Depth 0) on the expected destination path should work and not return an error
- a subsequent `PROPFIND` (Depth 1) on the parent folder should include the file in its response

The iOS client should not run into any issues if the `Etag` updates to all parent folders is happening with delay / asynchronously. The only effect of that should be that updates on _other_ devices that include the new file are delayed.

Regarding returning metadata in the upload response, as discussed in the past, I'd love to see a mechanism for clients to specify which properties of an uploaded file should be returned in the response through special request and response HTTP headers. F.ex. by tunneling a WebDAV request/response via `oc-dav-request` and `oc-dav-response` headers.

**Comment by butonic** [comment]
With regard to the latter, could you point me to an issue? I'd like to propose using the `Prefer` header here as well, eg. `Prefer: include-annotations="display.subject"` as described by https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_Preferenceincludeannotationsodatainc However, I assume the annotations are not meant to solve that case.

Unfortunately, [the IANA preference registry](https://www.iana.org/assignments/http-parameters/http-parameters.xhtml#preferences) has no property we could use to tell the server which properties to return in the response.

Related: https://github.com/owncloud/ocis/issues/3782

But all this is not about the original question: when is async etag propagation allowed? Do clients expect the root etag to change synchronously?

Maybe a simple `Prefer: return=representation` or `Prefer: return=minimal` as described in https://datatracker.ietf.org/doc/html/rfc7240#section-4.2 is sufficient.

**Comment by dragotin** [comment]
I think it can be summarized:
* Async propagation of the ETag  up the dir tree is fine. Clients can deal with that. Testsuite needs to as well.
* Clients make benefit if the last action (last move for example) returns the **ETag**, **remote permissions** and **FileID** metadata header. If one of them is missing that either causes an error (FileID) or additional subsequent PROPFINDs. Both is not optimal.

**Comment by evert** [comment]
Thank you!!

**Comment by dragotin** [comment]
well yes. I am kinda lost how that relates to the initial problem of this issue. I think @phil-davis has a reasonable answer, so I am closing this one. Feel free to re-open.
