### ISSUE TITLE
parallel deployment: owncloud-sql publicshare driver

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4002]
## Is your feature request related to a problem? Please describe.
As a user of the parallel deployment (oC10 and oCIS next to each other on the same data), I want also to have the same public shares available on both backends.

## Describe the solution you'd like
Have an owncloud-sql driver like we have it for shares.

## Describe alternatives you've considered
-

## Additional context
-

**Comment by butonic** [comment]
fixed with https://github.com/cs3org/reva/pull/3497
