### ISSUE TITLE
Step `make ci-node-generate` is failing consistently

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#4008]
## Describe the bug
command `make ci-node-generate` is hard failing in `CI` and `local` environments.

The error is:
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[1]: *** [Makefile:36: pull-assets] Error 2
make: *** [Makefile:158: ci-node-generate] Error 1
```

**Comment by pascalwengerter** [comment]
The web version that oCIS is trying to pull/extract wasn't created&uploaded in the web release pipeline apparently, it's currently re-running (https://drone.owncloud.com/owncloud/web/26364) and should ideally appear [here](https://github.com/owncloud/web/releases/tag/v5.6.0) soon and fix this issue

**Comment by micbar** [comment]
Cause: There is a release artifact missing on ownCloud web `v5.6.0`


`@curl --fail -slL -o- https://github.com/owncloud/web/releases/download/v5.6.0/web.tar.gz | tar xzf - -C assets/`

**Comment by saw-jan** [comment]
Should be fixed by now. Closing here!
