### ISSUE TITLE
To get response while searching on ocis, we have to wait `1` second 

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#4018]
### Description

After the `files | folder` have been uploaded and while running tests for the search request, the tests fails on assertion because the response for the search was not received, but if we wait for `1` second the tests passes. This seems strange for the `ocis` backend comparing to the oc10.

### Steps to reproduce
1. create a user `u11`
2. upload file `upload.txt`
3. upload folder `upload`

After that run the tests for searching with `upload`.

Note: This test result can only be reproduced while executing test. Not possible to reproduce with curl command.

### Behaviour on wireshark

While waiting for 1 second

```console

REPORT /remote.php/dav/files/u11 HTTP/1.1
Host: host.docker.internal:9200
User-Agent: GuzzleHttp/7
Authorization: Basic dTExOjEyMzQ1Ng==
X-Request-ID: apiWebdavOperations/search.feature:43-27
Content-Length: 192

<?xml version='1.0' encoding='utf-8' ?>
	<oc:search-files xmlns:a='DAV:' xmlns:oc='http://owncloud.org/ns' >
		<oc:search>
			<oc:pattern>upload</oc:pattern>
		</oc:search>
	</oc:search-files>HTTP/1.1 207 Multi-Status
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
Content-Length: 1341
Content-Security-Policy: frame-ancestors 'none'
Content-Type: application/xml; charset=utf-8
Date: Thu, 23 Jun 2022 08:38:31 GMT
Dav: 1, 3, extended-mkcol
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Thu, 23 Jun 2022 08:38:31 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Webdav-Version: 2.0.0-beta.3+a5dfd89e2

<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$b11d65c2-be22-47d5-981b-fca3977d6fee%21b11d65c2-be22-47d5-981b-fca3977d6fee/upload</d:href><d:propstat><d:prop><oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$b11d65c2-be22-47d5-981b-fca3977d6fee!3f083b05-586c-4bf8-9c41-8c84bd784faa</oc:fileid><d:getetag></d:getetag><d:getlastmodified>2022-06-23T08:38:30Z</d:getlastmodified><d:getcontenttype>httpd/unix-directory</d:getcontenttype><d:resourcetype><d:collection/></d:resourcetype><oc:size>0</oc:size><oc:score>0</oc:score></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$b11d65c2-be22-47d5-981b-fca3977d6fee%21b11d65c2-be22-47d5-981b-fca3977d6fee/upload.txt</d:href><d:propstat><d:prop><oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$b11d65c2-be22-47d5-981b-fca3977d6fee!3cc017b1-708f-4655-9712-1af12ab3eaad</oc:fileid><d:getetag></d:getetag><d:getlastmodified>2022-06-23T08:38:30Z</d:getlastmodified><d:getcontenttype>text/plain</d:getcontenttype><d:resourcetype></d:resourcetype><d:getcontentlength>15</d:getcontentlength><oc:score>0</oc:score></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>

```

For Not waiting 1 second

```console
REPORT /remote.php/dav/files/u11 HTTP/1.1
Host: host.docker.internal:9200
User-Agent: GuzzleHttp/7
Authorization: Basic dTExOjEyMzQ1Ng==
X-Request-ID: apiWebdavOperations/search.feature:43-27
Content-Length: 192

<?xml version='1.0' encoding='utf-8' ?>
	<oc:search-files xmlns:a='DAV:' xmlns:oc='http://owncloud.org/ns' >
		<oc:search>
			<oc:pattern>upload</oc:pattern>
		</oc:search>
	</oc:search-files>HTTP/1.1 207 Multi-Status
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
Content-Length: 113
Content-Security-Policy: frame-ancestors 'none'
Content-Type: application/xml; charset=utf-8
Date: Thu, 23 Jun 2022 08:41:05 GMT
Dav: 1, 3, extended-mkcol
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Thu, 23 Jun 2022 08:41:05 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Webdav-Version: 2.0.0-beta.3+a5dfd89e2

<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"></d:multistatus>
```

### Environment
ocis = latest docker pull

**Comment by SagarGi** [comment]
Build https://drone.owncloud.com/owncloud/ocis/12759 passes when we wait for 1 sec 
Build https://drone.owncloud.com/owncloud/ocis/12745/48/6 fails when we donot wait for 1 sec

for this PR https://github.com/owncloud/core/pull/40159(waiting 1 sec and not waiting for 1 sec)

**Comment by phil-davis** [comment]
Any of the oCIS developers: after uploading a file/folder and getting the success response for that, is there something async happening in the oCIS backend in/between services that would prevent and incoming search-pattern request from discovering the very-new file/folder?

Maybe "something happens" and the names of the resources in the storage are not immediately/synchronously "visible" to all services that need to see them?

**Comment by aduffeck** [comment]
@phil-davis @SagarGi with ocis indexing of newly uploaded files or directories is decoupled and happens asynchronously. Uploads trigger an event to be emitted over NATS which will be picked up by the search service and only then the items will be indexed and be made available to the search.

So what you are seeing in the tests is the expected behaviour, the asynchronicity comes with a slight delay until the new items can be found.

**Comment by SagarGi** [comment]
A second wait has been added in tests for ocis while searching. So closing this discussion.

**Comment by phil-davis** [comment]
Note: there is no special guarantee that 1 second is enough. But it "works" quite consistently in practice with our tests. If we find that CI fails sometimes due to the trigger being slow, then we will have to add extra logic to the tests which tries again a few times at x second intervals until either the search-pattern response matches what the test expects, or we give up and fail the test.
