### ISSUE TITLE
Download via phoenix says "from: blob:"

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#402]
Reproduce on ocis 1.0.0-beta8 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

firefox https://xxx.xxx.xxx.xxx:9200

* log in as einstein, click in a file, e.g. 'Speech.ogg' the web UI suggests downoad,
* click on 'downoad' 
* a requester appears
![image](https://user-images.githubusercontent.com/1108546/88187676-20931880-cc37-11ea-8639-eecc9e6e1de6.png)

What is the meaning of 'from: blob:' - is this some techical artefact, that should be hidden?
It looks like something is missing after the colon. 
This is possibly irritating to the user.

Expected result: irritating terms like 'blob' don't appear.

**Comment by micbar** [comment]
pre singned urls have fixed that.

The blob: download was just a workaround

**Comment by jnweiger** [comment]
confirmed fixed with RC1 docker
