### ISSUE TITLE
drives graph api - users?$expand=drive|drives not working - /drives endpoint not implementented in generated api

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#4027]
1. calling https://localhost:9200/graph/v1.0/users?$expand=drive or https://localhost:9200/graph/v1.0/users?$expand=drives does not expose drives, while generated API specs say it should
2. https://localhost:9200/graph/v1.0/drives endpoint works in graph explorer but is not exposed in generated API

**Comment by JanAckermann** [comment]
FYI @butonic

**Comment by dragonchaser** [comment]
After discussing this issue with @butonic, @rhafer & @JanAckermann we came to the following consensus:

Due to the expensive nature of the request, we decided to implement the expand options for `drive` and `drives` only on requests for single users.

**Comment by JanAckermann** [comment]
any update on this?
