### ISSUE TITLE
docs: Document meaning of ETags in developer docs

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#4042]
As @butonic correctly states in https://github.com/owncloud/ocis/issues/3988#issuecomment-1167681224 we need to document the concept of the ETags (and possibly CTags in the future) in the developer documention.

References:
* #3988 
* #3782 
* https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md#restrictions-and-limitations
* And a classic of the ownCloud literature: https://dragotin.wordpress.com/2015/03/13/owncloud-etags-and-fileids/

**Comment by kobergj** [comment]
etags now mentioned in devdocs. closing.
