### ISSUE TITLE
Public link resharing permissions

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#4061]
## Describe the bug
a user is able to create a public link as an editor even if he only has viewer permissions for the incoming share

## Steps to reproduce
1. user a shares a resource to user b as viewer
2. user b creates a public link of the share with editor permissions

## Expected behaviour
the backend does not allow to create public links with higher permissions then the user has 

## Current behaviour
the backend allows the creation

**Comment by phil-davis** [comment]
Similar to https://github.com/owncloud/ocis/issues/3881

https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-API-on-OCIS-storage.md has:
```
#### [Increasing permission of a public link of a folder that was initially shared with share+read permissions is allowed](https://github.com/owncloud/ocis/issues/3881)

- [apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature:159](https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature#L159)
- [apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature:160](https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature#L160)
- [apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature:181](https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature#L181)
- [apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature:182](https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature#L182)
```

There are failing API tests that cover this problem.

**Comment by kobergj** [comment]
https://github.com/cs3org/reva/pull/3023
