### ISSUE TITLE
Migration needs to be able to set metadata without propagation

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#41]
# New migration approach
After the architecure changed from oc10 to ocis we can now move whole spaces from the old storage provider with the `owncloudsql` driver to a new storage provider with a different driver, eg. `ofqs` or `cephfs`. This operation also needs to be abe to import metadata witout causing a propagation. Same problem as with the old approach below.

# Old migration approach
The import reads a json file line by line and updates the metadata like etags and shares via the CS3 API. Unfortunately, the order of files and folders might cause a files etag to overwrite a previously set etag for a folder. To solve this properly it would be great if the SetArbitraryMetadata call had a `nopropagation` flag.

**Comment by refs** [comment]
is this still relevant? perhaps @IljaN can shade some light?

**Comment by micbar** [comment]
this is outdated. Migration concepts are different today.
