### ISSUE TITLE
Cannot add user as Manager to Space using external IdP(keycloak)

### ISSUE THREAD

**Issue by cakiwi** [owncloud/ocis#4104]
## Describe the bug

A user cannot be invited/added to a space with the Manager role when using Keycloak

## Steps to reproduce

1. Login as einstein to autoprovision. Logout.
1. Login as admin
2. Create a new space
3. Add member einstein as manager

## Expected behavior
User should be added/invited to workspace as Manager

## Actual behavior
Modal:
Error while sharing.
invalid role for space member 

Can only be added as a viewer or editor

## Setup
owncloud/ocis:2.0.0-beta.4

https://owncloud.dev/ocis/deployment/ocis_keycloak/

## Additional context
`POST 	/ocs/v1.php/apps/files_sharing/api/v1/shares`
`response: 200`

Body:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>400</statuscode><message>invalid role for space member</message></meta></ocs>Add any other context about the problem here.
```

**Comment by micbar** [comment]
This is possible currently "after" einstein has logged in at least once.

This could currently be fixed by not using autoprovisioning. You would need to have a Directory connected to Keycloak **and** Infinite Scale via LDAP.

**Comment by micbar** [comment]
@cakiwi sorry, you are correct. This bug is in 2.0.0-beta.4

It has already been fixed. Beta.5 will release the fixed version.

**Comment by rhafer** [comment]
according to that last comment this was fix. So I'll close it.
