### ISSUE TITLE
Removal of Space Manager leave unmanageable space.

### ISSUE THREAD

**Issue by cakiwi** [owncloud/ocis#4105]
## Describe the bug

When the only Manager of a space is removed the space cannot be managed.  Not visible by Admin or Space Admin roles.

## Steps to reproduce

1. As Moss Create a Space
2. Add users. Add a User, Space Admin and Admin
3. Delete Moss.

## Expected behavior
Space should be manageable or assigned to new manager.

## Actual behavior
Nobody can manage space.
Shares cannot be managed.
List of users in space disappears.

## Setup
2.0.0-beta.4
https://owncloud.dev/ocis/deployment/ocis_keycloak/
or 
https://owncloud.dev/ocis/deployment/ocis_traefik/

**Comment by micbar** [comment]
This is ugly. We implemented a check when we remove a user from a space, but this is deleting a user. I think we cannot control "deleting" a user. assume that something goes wrong with a member of an organisation, you should always be able to delete a toxic user. So the solution would be to "recover orphaned spaces"

related to #4196

**Comment by micbar** [comment]
closing here in favour of #4196
