### ISSUE TITLE
Data loss during cut&paste cross-space

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#4114]
### Steps to reproduce
1. Select any file in your personal space
2. Use `ctrl+x` (linux/windows) or `cmd+x` (mac) to cut the file
3. Navigate into a project space
4. Use `ctrl+v` (linux/windows) or `cmd+v` (mac) to paste the file

### Expected behaviour
a) File gets moved successfully OR b) in case of an error the file stays in the original location

### Actual behaviour
Apparently cross-space move (internally: copy & delete) is not possible at all or not correctly implemented in web (needs investigation). The much bigger issue in this case is, that the failing move request fails results in data loss: the file doesn't get copied successfully but gets deleted from the original location anyway.

Needs investigation if the two bugs are backend only, frontend only or a mix of both.

### Solution

1) Cross space moves do not work, the fix in reva changes the behavior
    - no data loss
    - Returns `502 Bad Gateway` according to spec
2)  Web also needs to change the behavior, to not offer MOVE across storage spaces. COPY and DELETE works just fine. @tbsbdr @pmaier1

**Comment by tbsbdr** [comment]
> 2\. Silently transform a cross storagespace MOVE into a COPY&DELETE

userfacing crossstorage "move" should be possible - users won't distinguish between a crossstorage and non-crossstorage move I guess (they are used to easily move a file from HDD to a USB stick). The main problem is, that a cross storage move (copy & delete) can take a long time, right? If yes, I'd propose the following:

1.  inform the user, ask for confirmation beforehand: like:  
    "Change who has access? This item will be visible to everyone who can see \[taget-folder-name\] You are about to move 35 GB. This will take several minutes. Are you sure you want to proceed? \[cancel\]\[proceed\]"
2.  Show a move progress indicator and an option to cancel if the user realizes that the operation takes too long:   
    "Moving |=====---------------| 25% completed. Cancel will revert your changes. No data will be lost. \[Cancel\]"

@micbar would that be the right ui-behaviour?
