### ISSUE TITLE
Unable to add files: Resource not found We went looking everywhere, but were unable to find the selected resource.

### ISSUE THREAD

**Issue by TroyWilson1** [owncloud/ocis#4119]
## Describe the bug
After launching the server from a docker image no errors are reported and the login page is properly displayed with https certs working as expected. After typing the username and password a one line error shows up on the server.
```
{"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2022-07-06T16:11:58Z","message":"list spaces returned empty list"}
```
Login is successful but no files are displayed with error "Resource not found We went looking everywhere, but were unable to find the selected resource."

Login is successful but no files are displayed with error "Resource not found We went looking everywhere, but were unable to find the selected resource."

## Steps to reproduce

1. Launch server: ``` sudo docker run --name owncloud --rm -it -p 9200:9200 --mount type=bind,source=/store/ocis/ocis-config,target=/etc/ocis --mount type=bind,source=/store/ocis/ocis-data,target=/var/lib/ocis -e OCIS_INSECURE=false -e PROXY_TRANSPORT_TLS_KEY=./certs/privkey.pem -e PROXY_TRANSPORT_TLS_CERT=./certs/fullchain.pem -e OCIS_URL=https://files.website.com:9200 owncloud/ocis ```
2. 
3. 
4.
5.

## Actual behavior
A clear and concise description of what happened.

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.
```
sudo docker run --name owncloud --rm -it -p 9200:9200 --mount type=bind,source=/store/ocis/ocis-config,target=/etc/ocis --mount type=bind,source=/store/ocis/ocis-data,target=/var/lib/ocis -e OCIS_INSECURE=false -e PROXY_TRANSPORT_TLS_KEY=./certs/privkey.pem -e PROXY_TRANSPORT_TLS_CERT=./certs/fullchain.pem -e OCIS_URL=https://files.website.com:9200 owncloud/ocis

```
<details>
<p>

```console
error message:
{"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2022-07-06T16:37:13Z","message":"list spaces returned empty list"}

```

</p>
</details>

## Additional context
Everything looks great and was working perfectly before I moved from self signed insecure to secure with let's encrypt keys. I'm more than happy to help in anyway that I can. 

<img width="913" alt="dashboard" src="https://user-images.githubusercontent.com/11077207/177600926-dbe600eb-e599-4653-8635-e472b4758627.png">

**Comment by micbar** [comment]
Seems like a configuration error. In our deployment examples ocis works fine with real SSL certificates. This needs debugging.

Do you have a `/store` folder on your system?
It seems that ocis fails to create a personal space.

But to understand that, we would need more server logs.

Happy to help!
