### ISSUE TITLE
Space Admin still has access to the project despite being removed from it 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#4127]
I had a little query about project spaces. Consider the following scenario:
1. Admin adds Einstein as space admin
2. Einstein creates a space project team1
3. Einstein creates a folder test
4. Add user Moss to project team1 with role manager
5. Einstein removes himself from the space
6. Einstein still has access to the space in the sense that he can rename, delete, restore and share the folder `test` and other resources made before `Einstien` was removed from the space.

The only thing Einstein cannot do is add new members and create/upload new resources on the root level. Einstein can create/upload resources inside `test/`
Is this expected/known behavior/issue?
Is it because Einstein is a space admin and he created the project?

**Comment by micbar** [comment]
Fixed by #4244

**Comment by SwikritiT** [comment]
closing this as solved
