### ISSUE TITLE
adoc table generator misses to export go slice []string for types

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4128]
We have done some improvements to the adoc table generator for the documentation, but one item does not get exported. This is when it comes to exporting the type in particular `[]string`. You can see that nothing gets exported when looking into [thumbnails_configvars.adoc](https://raw.githubusercontent.com/owncloud/ocis/docs/services/_includes/adoc/thumbnails_configvars.adoc) at field `THUMBNAILS_RESOLUTIONS` (you must use raw to see the generated not rendered content). The two plus symbols are necessary and added by the adoc template to tell antora to pass the value inbetween. The value would be correct when looking like: `+[]string+`

@dragonchaser

**Comment by dragonchaser** [comment]
Since this is working as expected in `https://github.com/owncloud/ocis/blob/master/docs/helpers/environment-variable-docs-generator.go.tmpl` I would assume this is a bug in `https://github.com/owncloud/ocis/blob/master/docs/helpers/adoc-generator.go.tmpl`
