### ISSUE TITLE
`carddav` and `caldav` endpoints do not work

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#4130]
## Describe the bug
I want to create a calendar using API like in oc10.

**Qs: Are carddav and caldav endpoints implemented? If not will they?**

## Steps to reproduce
1. Try to create a calendar
```bash
curl -uadmin:admin -XMKCALENDAR "https://host.docker.internal:9200/remote.php/dav/calendars/admin/MyCalendar" \
-d'<c:mkcalendar xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:d="DAV:" xmlns:a="http://apple.com/ns/ical/" xmlns:o="http://owncloud.org/ns">
    <d:set>
        <d:prop>
            <d:displayname>test</d:displayname>
            <o:calendar-enabled>1</o:calendar-enabled>
            <a:calendar-color>#21213D</a:calendar-color>
            <c:supported-calendar-component-set>
                <c:comp name="VEVENT"/>
            </c:supported-calendar-component-set>
        </d:prop>
    </d:set>
</c:mkcalendar>' -vk
```
```xml
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< Content-Length: 205
< Content-Security-Policy: default-src 'none';
< Content-Type: text/xml; charset=utf-8
< Date: Thu, 07 Jul 2022 10:13:34 GMT
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 

<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found in root</s:message>
</d:error>
```

## Expected behavior
to create a new calendar

## Actual behavior
responses `404` with `File not found in root` message

## Setup
oCIS: master build: `b4a930dd4`

**Comment by micbar** [comment]
@saw-jan @phil-davis this is not implemented. We should skip all the calDAV and CardDAV tests. There is no point in running these tests in CI.

**Comment by saw-jan** [comment]
[QA] ToDo:
- [ ] do not run caldav and carddav tests in oCIS (tag them with `@notToImplementOnOCIS`)

**Comment by pascalwengerter** [comment]
> [QA] ToDo:
> 
>     * [ ]  do not run caldav and carddav tests in oCIS (tag them with `@notToImplementOnOCIS`)

I think semantically it should "only" be `skipOnOCIS` since we eventually want to add those APIs AFAIK

**Comment by phil-davis** [comment]
In core I see that there are already tags like `@caldav` and `@carddav`.
IMO the way-to-go is to explicitly skip those tags in oCIS and reva CI.
Then it is simple to remove the skipping when someone is doing a PR to implement those things.

**Comment by micbar** [comment]
Solution: skip all CalDAV and CardDAV tests for now.

**Comment by SagarGi** [comment]
Skipped on OCIS with this https://github.com/owncloud/ocis/pull/4199 PR. Will be skipped on Reva during commit bumping

**Comment by kiranparajuli589** [comment]
done with #4199
