### ISSUE TITLE
ownCloudSQL sharing driver auto accepts shares

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4141]
## Describe the bug
The ownCloudSQL sharing driver auto accepts shares.

## Steps to reproduce

Use the parallel deployment. Share from oCIS to oC10 and the other way round. Also share from oC10 to oC10 and oCIS to oCIS.

## Expected behavior
The sharing is consistent across the backends (and configurable like in oC10).

## Actual behavior
Depending on the backend, shares are auto accepted or not.

## Additional context
auto acceptance of shares is configurable in oC10. We could adapt the settings there to match the behavior of oCIS. Though this may not always be possible at a customers deployment.

**Comment by phil-davis** [comment]
Note: for automated testing we need to make sure to run all parallel-deployment tests with auto-accept off on oC10 (to match the way oCIS is started). I know there are various test scenarios that have enable auto-accept on-the-fly (which can be done on oC10 without completely restarting the whole system-under-test). But having that mismatch between the behavior on oC10 and on oCIS will be very confusing for test scenarios - and also confusing for production deployments!

When deploying an oC10+oCIS parallel system, it seems "a good thing" (tm) to make sure that all the settings in oC10 are set to match what has been configured (or is hard-coded) behavior in oCIS.

**Comment by micbar** [comment]
according to PM this is ok for GA
