### ISSUE TITLE
Lacks some features in conjunction with OIDC. (And not only).

### ISSUE THREAD

**Issue by rtest12** [owncloud/ocis#4150]
There is no way to manage users, created through OIDC.
At the moment, I don't see any other user accounts in the menu at all. I would like to be able to see how much space each user occupies, and the ability to clear account data if it necessary. In keycloak, you can only create and change registration data, you can delete the registration, but you cannot, for example, delete the account itself with the data inside the OCIS.  Ideally, it would be good if three strings were obtained from the keycloak, one with administrator rights, the second with the avatar, the third with the disk space quota. Perhaps one more attribute, in case it's assumed that not all users registered in keycloak are allowed to enter the ocis.  
Also, there is an unnecessary user creation button in the web ocis, it displays a menu, but does not work, it's better to remove it. Also now, due to the lack of administrator rights, I can’t even create a new space. 
Thanks.

**Comment by micbar** [comment]
> At the moment, I don't see any other user accounts in the menu at all. I would like to be able to see how much space each user occupies, and the ability to clear account data if it necessary. 

This use case (ocis.ocis-keycloak.latest.owncloud.works) works with autoprovisioning.
We will create all users on the fly which are created in the IdP. They currently all get the "user" role assigned when logging in for the first time.

The Admin User (with the admin role in ocis) can only see the users in the ocis user management after they have logged in at least once. After that, he/she can change their roles in the ocis User management.

> you can delete the registration, but you cannot, for example, delete the account itself with the data inside the OCIS.

The ocis admin user can delete every single user in the ocis user management.

> Also, there is an unnecessary user creation button in the web ocis, it displays a menu, but does not work, it's better to remove it

This is a bug. It will be fixed in 2.0.0-beta.5 (only admin users can see the ocis user management)

> deally, it would be good if three strings were obtained from the keycloak, one with administrator rights, the second with the avatar, the third with the disk space quota. Perhaps one more attribute, in case it's assumed that not all users registered in keycloak are allowed to enter the ocis.

We have that feature on the roadmap, to map specific OIDC claims to ocis user properties, but after the 2.0.0 release.

**Comment by rtest12** [comment]
> This use case (ocis.ocis-keycloak.latest.owncloud.works) works with autoprovisioning. We will create all users on the fly which are created in the IdP. They currently all get the "user" role assigned when logging in for the first time.
> 
> The Admin User (with the admin role in ocis) can only see the users in the ocis user management after they have logged in at least once. After that, he/she can change their roles in the ocis User management.

This is the standard oidc scheme, but it's a bit different. If oidc authorization is enabled, then there is no way to log in as a local administrator, there is an automatic redirect in the same place. It turns out that you must first enable oidc, log in, then disable oidc, then log in as a local administrator and make the created account also an administrator, then enable oidc again...



> is is a bug. It will be fixed in 2.0.0-beta.5 (only admin users can see the ocis user management)

ok



> We have that feature on the roadmap, to map specific OIDC claims to ocis user properties, but after the 2.0.0 release.

It would be great

**Comment by rhafer** [comment]
> If oidc authorization is enabled, then there is no way to log in as a local administrator, there is an automatic redirect in the same place. It turns out that you must first enable oidc, log in, then disable oidc, then log in as a local administrator and make the created account also an administrator, then enable oidc again...

Yeah currently we're lacking a good mechanism to initialize a users role from the claims that the IDP provides. As @micbar  already pointed out new users just get the "user" role assigned. There is no good way to make a new user an admin currently.

@rtest12 Are you using ocis with an external LDAP server? Or are you using the builtin idm? When using the internal one. You could just create a user named `admin` in your external idp. That should automatically have the `admin` role assigned in `ocis`.  This is of course not  really nice and there is a lot of room for improvment, but with that you wouldn't at least need the back and forward with enabling/disabling the external IDP.

**Comment by rtest12** [comment]
> When using the internal one. You could just create a user named `admin` in your external idp. That should automatically have the `admin` role assigned in `ocis`

Great, it worked, that's enough for me, thanks

**Comment by micbar** [comment]
good to know!

**Comment by NexZhu** [comment]
@rhafer I'm using an external OIDC provder backed by an external LDAP server.
I've set `PROXY_AUTOPROVISION_ACCOUNTS` to `true`.
But after logging in with my account with OIDC and disable `externalUserManagement` and logging in with the OCIS admin account, I can't see my account in user management, there's only one admin account.
Does this mean something's wrong with my setup?
So how do I set my account's role?

**Comment by NexZhu** [comment]
@micbar @rhafer Hi, I need some help. I checked CLI help of `users` `idp` `idm` services, no way to set roles of my OIDC backed user, and when I switched `externalUserManagement` to `false` and login as `admin`, my OIDC backed user is not showing up in user management, what else can I try? Thank you!

**Comment by rhafer** [comment]
@NexZhu Sorry for not getting back earlier. I've just overlooked your comment as this issue was already closed sometime ago. Would you mind opening a new issue for you problem (referencing this one)? I am trying to look into that as soon as time permits. BTW, are you still on beta8? If yes, I'd suggest to move to RC1 and re-test with that. It was released a couple of days ago.

**Comment by NexZhu** [comment]
OK, thanks! I will try RC1 tomorrow.

**Comment by NexZhu** [comment]
@rhafer This is no longer an issue with the `adminUUID` option of the latest Helm chart, thank you!
