### ISSUE TITLE
[qa-team] irrelevant log in the localAPITests afterScenario

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#4173]
See the localAPITests builds, the run is totally polluted with:
```
 ╳  No drives were found on that endpoint
      ╳  Failed asserting that an array has the key 0.
      │
      └─ @AfterScenario # SpacesContext::cleanDataAfterTests()
```
The error seems not relevant and only makes the build log dirty.

Example build link: https://drone.owncloud.com/owncloud/ocis/13347/40/8

**Comment by micbar** [comment]
I think we are failing to delete the spaces.
