### ISSUE TITLE
Server errors when updating the token

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4175]
ownCloud Web UI 5.7.0-rc.4 
ocis local

Precondition: Change the refresh time of the token to 2 min. [/ocis/services/idp/pkg/config/defaults/defaultconfig.go](https://github.com/owncloud/ocis/blob/master/services/idp/pkg/config/defaults/defaultconfig.go#L65)

Steps: 
- Open client
- Wait to updating token: request POST `https://localhost:9200/konnect/v1/token`
- See ocis log

Actual: 
<img width="929" alt="Screenshot 2022-07-11 at 21 04 09" src="https://user-images.githubusercontent.com/84779829/178443432-05713f35-2351-4dbc-be12-cc022976d465.png">
log:
[logOcis.txt](https://github.com/owncloud/ocis/files/9090991/logOcis.txt)

**Comment by rhafer** [comment]
After re-running this with latest web (rc5), we're not really able to reproduce this. However:

The `2022-07-12T11:46:07+02:00 ERR Failed to get userinfo error="401 Unauthorized: " service=proxy` message a very likely cause by a client trying to use an expired token. The message does not really indicate a server error. They don't seem to happen with latest master. Could have been some old browser tab. (the desktop client seems to have an issue with refreshing tokens though, I'll open a separate issue for that).

**Comment by micbar** [comment]
closing, not reproducable with latest ocis
