### ISSUE TITLE
"Failed to send a message" error when sharing the resource

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4182]
ocis local or docker 
v 2.0.0-beta4 

Steps:

- admin creates folder and shares to marie

Actual: error message in ocis log: `2022-07-12T16:25:01+02:00 ERR failed to send a message error="could not send mail: dial tcp 127.0.0.1:1025: connect: connection refused" event=ShareCreated service=notifications`

**Comment by wkloucek** [comment]
we should change the default of `NOTIFICATIONS_EVENTS_ENDPOINT` to "" (the empty string) and adapt the logic of the notifications service to handle the empty string by not doing anything. Currently it tries to send emails on 127.0.0.1:1025 and in many cases there isn't a smtp server listening.

**Comment by wkloucek** [comment]
We also could decide to not start the notifications service in the supervised / runtime mode (`ocis server`) like we do with the audit service. One would then need to start it separately or via the `OCIS_RUN_SERVICES` env variable.

**Comment by kobergj** [comment]
Fixed by a recent notifications refactoring of @2403905 

It now instead logs on info level:
```
2023-06-21T14:32:55+02:00 INF failed to send a message. SMTP host is  not set line=./ocis/services/notifications/pkg/channels/channels.go:104 mail=SendMessage service=notifications
```

Good enough for me. Feel free to reopen if you need any changes to the message or behaviour
