### ISSUE TITLE
Admin cannot get and delete another user's space 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4194]
After deleting a user, the user's personal and project spaces still exist. 
Of course the user can delete all his data before leaving the company (for example).

But what to do with the data when the user is deleted? 
here is two way:
- automatically delete all data during the deletion of a user
- admin should be able to delete user's data and for this we should fix:

GET personal and project space another user:
`curl -vk 'https://localhost:9200/graph/v1.0/drives/personalSpaceDeletedUserUUID' -u admin:admin -vk` 404 not found

`2022-07-13T15:17:56+02:00 ERR failed to list storage spaces error="error: permission denied: user admin is not allowed to Stat the space 534bb038-6f9d-4093-946f-133be61fa4e7" filters=[{"Term":{"Id":{"opaque_id":"1284d238-aa92-42ce-bdc4-0b0000009157$534bb038-6f9d-4093-946f-133be61fa4e7!534bb038-6f9d-4093-946f-133be61fa4e7"}},"type":2},{"Term":{"SpaceType":"+grant"},"type":4}] pkg=rgrpc service=storage-users status={"code":8,"message":"permission denied","trace":"00000000000000000000000000000000"} traceid=00000000000000000000000000000000
2022-07-13T15:17:56+02:00 ERR no space found driveID=1284d238-aa92-42ce-bdc4-0b0000009157$534bb038-6f9d-4093-946f-133be61fa4e7 service=graph`

DELETE personal/project space:
`curl -vk -XDELETE 'https://localhost:9200/graph/v1.0/drives/personalSpaceDeletedUserUUID' -u admin:admin -vk` 403

`2022-07-13T15:27:49+02:00 ERR failed to delete storage space error="error: permission denied: user is not allowed to delete spaces 534bb038-6f9d-4093-946f-133be61fa4e7" pkg=rgrpc service=storage-users status={"code":8,"message":"permission denied","trace":"00000000000000000000000000000000"} storage_space_id={"opaque_id":"1284d238-aa92-42ce-bdc4-0b0000009157$534bb038-6f9d-4093-946f-133be61fa4e7"} traceid=00000000000000000000000000000000`

@micbar @individual-it @pmaier1 what do you think?

**Comment by pmaier1** [comment]
I think the behavior is as designed. Admins should not be able to access/delete personal spaces. Instead, deleting a user should also delete their personal space. For project spaces we still need a permission that can be assigned to an administrative role to allow certain people to manage e.g., orphaned spaces.
