### ISSUE TITLE
`webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:41` is passing on ocis

### ISSUE THREAD

**Issue by sushmita56** [owncloud/ocis#4197]
The scenario `webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:41` was expected to fail but is now passing on OCIS and is causing OCIS to fail in the [nightly build](https://drone.owncloud.com/owncloud/ocis/13427).

![Screenshot from 2022-07-14 10-07-14](https://user-images.githubusercontent.com/66173400/178898333-f54c5deb-6532-48f2-90a7-557ef496db3a.png)

![Screenshot from 2022-07-14 10-45-52](https://user-images.githubusercontent.com/66173400/178902824-aa1f3cfa-cb25-4ab6-b949-05e758bc4267.png)

Todo: 
- [x] Investigate it (Checked it manually and locally)
- [ ] Remove it from expected to failure https://github.com/owncloud/ocis/pull/4198

**Comment by SwikritiT** [comment]
The passing test has been removed from expected to fail. So closing this issue
