### ISSUE TITLE
Remove googlefonts in IDP UI

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#4212]
## Steps to reproduce

1. Visit initial oCIS IDP login mask
2. See request to fonts.googleapis.com
3. Get concerned from a privacy standpoint

## Expected behavior
Embed the font similar to how it has been done in MSTeamsgen or replace it with a different one. Happens in https://github.com/owncloud/ocis/blob/56f8fc510f61e665dadc4bdcbff971cac7300131/services/idp/public/index.html#L8

**Comment by pascalwengerter** [comment]
Found out about this when having an abysmal wifi connection and trying to access my dev environment - it wouldn't load for an absurd amount of time while it was supposedly trying to download the font 🤷🏽

**Comment by pmaier1** [comment]
@micbar @kulmann Why does LICO do this and can we get rid of it? Please schedule. GA blocker. cc @tbsbdr

**Comment by micbar** [comment]
> Why does LICO do this and can we get rid of it?

I suppose it was brought in by us inside the owncloud branded login page.

**Comment by C0rby** [comment]
We are using the Open Sans font only as a fallback. We could just remove it and fallback to any 'sans-serif' font. The fallback wont be necessary though since we are serving the "Inter" font ourselves.
