### ISSUE TITLE
Redirect loop on missing extended attributes in the metadata storage

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#4224]
## Describe the bug

After a badly time reboot (running ocis debug session), the extended attributes in the metadata-storage where gone (`~/.ocis/storage/metadata/spaces/re/dacted-uuid-49fc-8203-0558109d1b4f/nodes/re/da/ct/ed/-uuid-469c-b126-fee53edbd8ba`). When logging into the web interface it went into a redirect loop.

## Expected behavior
Login working properly.

## Actual behavior
WebUI went into login redirect loop.

## Setup

Arch Linux, home directory on ext4 partition.

**Comment by micbar** [comment]
@kulmann web or backend ticket 😄 ?

**Comment by dragonchaser** [comment]
why not both, there should be a "please contact your admin" message when that happens.

**Comment by kulmann** [comment]
@dragonchaser  Could you add steps how to recreate the state?

**Comment by dragonchaser** [comment]
@kulmann sure
```
$> cd .ocis/storage/metadata
$> find |grep accounts
$> cd <resultfolder from step above>
```
you will find 3 symlinks there `accounts, bundles, values`
```
$> xattr -c {accounts,values,bundles}
```
then start ocis and try to login
