### ISSUE TITLE
A member of the space cannot see the public links of another manager 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4260]
ownCloud Web UI 5.7.0-rc.5
ocis: 2.0.0-beta.5

Steps:

- Katherine creates project space "first" and shares it via public link "link1"
- Katherine shares space to Einstein as manager

Actual: Einstein can create link but cannot see link1

- Einstein creates public link2

Actual: Katherine can see link2 

Expected: user with manager role can manage to project space. Einstein should see link1

![Screenshot 2022-07-22 at 12 03 28](https://user-images.githubusercontent.com/84779829/180416767-5ac0e6b9-c18b-44e9-87d5-078cdf67b20e.png)

**Comment by micbar** [comment]
all space members should see all shares.

**Comment by ScharfViktor** [comment]
Re-tested 
ocis: after merging https://github.com/owncloud/ocis/pull/4244
web fresh with docker 

works correct:
<img width="1435" alt="Screenshot 2022-08-02 at 11 45 36" src="https://user-images.githubusercontent.com/84779829/182345528-416b784c-8599-49b0-84d3-35ad10c54f1b.png">


note: if you run ocis localy, ocis uses the latest stable version of the web (v5.7.0-rc.5).
old web call method `ocs/v1.php/apps/files_sharing/api/v1/shares?reshares=true` and members cannot see public link

all will be well when we update the web in ocis

**Comment by ScharfViktor** [comment]
@micbar Do we want to show public links (for folders or files) to members of the space?
if yes, I can create separate issue

**Comment by micbar** [comment]
Yes. All members of a space should see the share indicators and the shares.
