### ISSUE TITLE
Remove graph-explorer from ocis monorepo

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4275]
## Is your feature request related to a problem? Please describe.
We ship the graph-explorer with oCIS so that people can easily discover the Graph API.

The ownCloud graph-explorer is an outdated fork of Microsoft graph-explorer. It uses Node 10 and received the last commit in 2020. We can't check it's dependencies licenses (https://github.com/owncloud/ocis/issues/3492).
Furthermore it only can be used only with Kopano Lico based IDPs, because it has some hardcoded values https://github.com/owncloud/graph-explorer/blob/5dca02fcbda58324ce1f27b68c27d52e2a6b14dc/src/app/authentication/auth.ts#L16-L22.

## Describe the solution you'd like
Remove it and drop the fork. Bundle the auto generated Swagger UI https://owncloud.dev/libre-graph-api.

## Describe alternatives you've considered
Update and maintain the graph-explorer.

## Additional context
-

**Comment by micbar** [comment]
@mmattel @C0rby let us tackle that before GA

**Comment by butonic** [comment]
I really don't like the swagger ui. I don't see a way to customize queries to play with the API. Can we move it to a seperate repo so that developers can use it? maybe as an example similar to ocis-hello? The we can add it to a developer environment...

**Comment by mmattel** [comment]
Shall I remove the `graph-explorer` service from the ocis admin docs now?

**Comment by micbar** [comment]
yes, please.

**Comment by butonic** [comment]
removed by https://github.com/owncloud/ocis/pull/4733, closing

**Comment by butonic** [comment]
bringing it back as a standalone service is tracked in https://github.com/owncloud/ocis/issues/4739
