### ISSUE TITLE
Groups displayed as UUID on the Account page

### ISSUE THREAD

**Issue by xoxys** [owncloud/ocis#4283]
## Describe the bug

![image](https://user-images.githubusercontent.com/3391958/180962666-80cbe71c-0f50-430c-b16d-31b120b397ee.png)

## Expected behavior

Value from the attribute set by `LDAP_GROUP_SCHEMA_DISPLAYNAME` should be used instead. The default should be `cn` already but even it if the env var is explicitly set to `cn` the ID is displayed.

## Setup

Container (owncloud/ocis:2.0.0-beta.5) + External OpenLDAP

**Comment by micbar** [comment]
needs to be aligned with the web team @kulmann 

This should use the graphApi to get the user information

**Comment by rhafer** [comment]
> This should use the graphApi to get the user information

Agreed. Ideally this would be using a query like `https://localhost:9200/graph/v1.0/me/?$expand=memberOf`. Unfortunately `/me` does not support $expand yet. Should be fairly straightforward to add though. Should we do that?

A workaround would be to use `https://localhost:9200/graph/v1.0/users/<userid>/?$expand=memberOf` that should already work.

Currently the Account page is still using the ocs API  it seems, which just returns the group id in the result.

**Comment by micbar** [comment]
> Agreed. Ideally this would be using a query like https://localhost:9200/graph/v1.0/me/?$expand=memberOf. Unfortunately /me does not support $expand yet. Should be fairly straightforward to add though. Should we do that?

Yes, let us do that.

**Comment by micbar** [comment]
@kulmann @tbsbdr This needs also a web issue.

**Comment by rhafer** [comment]
> @kulmann @tbsbdr This needs also a web issue.

I've opened https://github.com/owncloud/web/issues/7554 for that.
