### ISSUE TITLE
accepting matching name shared resources from different users/groups sets no serial identifiers on the resource name for the receiver

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#4289]
## Step to reproduce
1. using `marie` upload `parent.txt`
2. using `moss` upload `parent.txt`
3. using `richard` upload `parent.txt`
4. using `katherine` upload `parent.txt`
1. using `marie` create folder `parent`
2. using `moss` create folder `parent`
3. using `richard` create folder `parent`
4. using `katherine` create folder `parent`

7. using `katherine`, `marie`, `moss` & `richard` share `parent.txt` & `parent` with `einstein`
8. accept all 8 pending shares using `einstein`
9. PROPFIND `/Shares` directory

## Actual behavior
Contains 9 `d:response` items with following `href`:
- <d:href>/remote.php/webdav/Shares/</d:href>
- <d:href>/remote.php/webdav/Shares/parent%20%286%29/</d:href>
- <d:href>/remote.php/webdav/Shares/parent%20%281%29/</d:href>
- <d:href>/remote.php/webdav/Shares/parent/</d:href>
- <d:href>/remote.php/webdav/Shares/parent%20%285%29.txt</d:href>
- <d:href>/remote.php/webdav/Shares/parent%20%282%29.txt</d:href>
- <d:href>/remote.php/webdav/Shares/parent%20%281%29.txt</d:href>
- <d:href>/remote.php/webdav/Shares/parent.txt</d:href>
- <d:href>/remote.php/webdav/Shares/parent%20%285%29/</d:href>

![Screenshot from 2022-07-27 14-49-43](https://user-images.githubusercontent.com/39373750/181208263-78db822f-9478-4c6e-941d-ef0b847d6369.png)

Also with oC10 server, the duplication management is started with `(2)` but here it is from `(1)`

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

Fresh installation using script https://github.com/kiranparajuli589/oc-scripts/blob/main/services/ocis.sh

</p>
</details>

**Comment by grgprarup** [comment]
This seems to duplicate https://github.com/owncloud/ocis/issues/4674 and https://github.com/owncloud/ocis/issues/8471. It was fixed so I'm closing this.
