### ISSUE TITLE
Renaming a shared resource: new resource name is not updated on share-receiver side (already accepted)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#4293]
### Steps to reproduce
1. Share a file "my File" with Albert
2. Albert accepts the share
3. Rename the file to "For Albert"
4. Albert does not see the new filename "For Albert"

https://user-images.githubusercontent.com/26610733/181059557-c39e1e00-cc19-4d68-9e6d-5ad5041de61e.mp4

### Expected behaviour
Albert should see the new filename

### Actual behaviour
Albert does not see the new filename

**Comment by micbar** [comment]
This has been specified like in oc10.

After you have accepted a share, it becomes a mount for the receiver (albert in this case)
From that moment on, its name is under the control of the receiver.
The receiver and the owner can rename the resource independently.

In this case: Works as designed.
