### ISSUE TITLE
Parallel deployment test pipelines  failing intermittently

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#4296]
For example: https://drone.owncloud.com/owncloud/ocis/13884/77/15
```
BEHAT_BIN=vendor-bin/behat/vendor/bin/behat BEHAT_YML=tests/parallelDeployAcceptance/config/behat.yml /drone/src/oc10/testrunner/tests/acceptance/run.sh --type api
bash: /drone/src/oc10/testrunner/tests/acceptance/run.sh: No such file or directory
make: *** [test-paralleldeployment-api] Error 127
Makefile:112: recipe for target 'test-paralleldeployment-api' failed
```

I saw this for a few hours a couple of days ago. It is happening again today. I have only seen it for the parallel deployment test pipelines.

There are currently not many parallel deployment test scenarios being run anyway, so we have skipped the pipelines for now - to avoid this flakyness. See #4295 

Need to investigate why this happens. Presumably there is some issue with the new caching of the Behat test dependencies, and somehow the dependencies that should have been saved in cache from an earlier pipeline are not actually getting restored.

**Comment by SwikritiT** [comment]
We're not running any parallel deployment pipelines right now in CI. We probably won't run them at least within the foreseeable future, so closing this.
We can create new issue if we end up running them and we see these issues
