### ISSUE TITLE
[Tests] Detect file descriptor leaks

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#430]
To avoid situations where file descriptors or network connections stay open like in https://github.com/owncloud/ocis-accounts/issues/79 (and there were other issues earlier), we could add some file descriptor counter before and after the test runs.

If the number increases significantly, we fail the test.

Now with ocis the number of file descriptors is different for each service, so would need to track this for each service separately.

Thoughts ? @individual-it @refs @butonic

**Comment by individual-it** [comment]
we could integrate that test into `run.sh` or in the `drone.star`

**Comment by individual-it** [comment]
output amount of the descriptors per ocis service (tested when run ocis single-binary)

```
IFS=$'\n'; for i in `ps xao pid,cmd | grep ocis | grep -v grep`; do PID=`echo $i | cut -d" " -f3`; SERVICE=`echo $i | cut -d" " -f5`; COUNT_DESCRIPTORS=`lsof -p $PID 2> /dev/null | wc -l`;  echo $SERVICE $COUNT_DESCRIPTORS; done`
```

**Comment by individual-it** [comment]
amounts after a clean start of ocis:
```
server 24
proxy 28
store 29
settings 33
phoenix 27
graph 27
graph-explorer 27
ocs 27
webdav 27
reva-frontend 23
reva-gateway 29
reva-users 23
reva-auth-basic 23
reva-auth-bearer 23
reva-storage-home 23
reva-storage-home-data 23
reva-storage-eos 23
reva-storage-eos-data 23
reva-storage-oc 23
reva-storage-oc-data 23
reva-storage-public-link 24
accounts 40
glauth 24
konnectd 27
thumbnails 26
api 31
web 27
registry 26
reva-sharing 24
```

and after running all API tests (using #409 but not https://github.com/owncloud/ocis-ocs/pull/29)

the question would be, what to set as threshold? 1000?

```
server 24
proxy 219
store 29
settings 33
phoenix 27
graph 27
graph-explorer 27
ocs 3600
webdav 27
reva-frontend 390
reva-gateway 42
reva-users 24
reva-auth-basic 24
reva-auth-bearer 23
reva-storage-home 25
reva-storage-home-data 145
reva-storage-eos 23
reva-storage-eos-data 23
reva-storage-oc 25
reva-storage-oc-data 112
reva-storage-public-link 26
accounts 3609
glauth 29
konnectd 27
thumbnails 26
api 31
web 27
registry 26
reva-sharing 25

**Comment by individual-it** [comment]
# idea how to fail CI in case of a file descriptor leak:

## in the SUT container in drone:

1. send `'bin/ocis server'` in the background => `'bin/ocis server &'`
2. after `'bin/ocis server &'` have a script that:
   1.  loops forever
   2. collects every 10sec `lsof` statistics (see https://github.com/owncloud/ocis/issues/430#issuecomment-668970049)
   3. writes the statistics into a file in the shared space e.g somewhere inside `/srv/app/tmp/reva`

## in the test-runner container in drone:

after `'make test-acceptance-api'` have a script that:
  1. sleep for 21sec (to make sure the `lsof` statistics are written again after all the tests finished and the garbage collector had time to clean up)
  2. reads the file written by the script running in the SUT container
  3. checks the numbers and if any service has > 512 open fd, fails CI with a nice message

## future ideas:
- not only check the last status after all tests ran, but save the history and see if there has been a problem during the run
- do the same for UI tests

**Comment by PVince81** [comment]
not sure if it has to be that complicated.
in my mind I was thinking mostly about running some check before and after a test: before the test, take note of the number of file descriptors and compare with the number that exist after the test. if that value increased too much over a threshold, make the test fail, a relative threshold, not absolute

**Comment by phil-davis** [comment]
The challenge is exactly how to "run some check". The test-runner is outside of the system-under-test. So the test-runner needs some way to be able to "ask" the system-under-test for some back-end performance-resource statistics.

One way to do that is like @individual-it suggested - have some background loop that is saving the statistics in the back-end of the system-under-test to somewhere that is exposed to the test-runner. Then the test-runner can look at the numbers whenevr it likes.

**Comment by dpakach** [comment]
Seems like the lsof command doesn't work inside the docker container. It gives the same result for me all the times
```

root@bdba8bd13503: /srv/app/ocis # lsof -p 15799 2> /dev/null | wc -l
444

root@bdba8bd13503: /srv/app/ocis # lsof -p 15759 2> /dev/null | wc -l
444

```

**Comment by individual-it** [comment]
looks like docker needs `--privileged` switch https://unix.stackexchange.com/questions/136690/how-can-i-substitute-lsof-inside-a-docker-native-not-lxc-based#264253

**Comment by individual-it** [comment]
I cannot see any way forward here :-(
In drone there is no way to run code on the docker host and it would be insecure to run the privileged mode.
I will close this issue now, please feel free to reopen if you have more ideas
