### ISSUE TITLE
wrong validation of access token / authentication bypass

### ISSUE THREAD

**Issue by TuxCoder** [owncloud/ocis#4304]
## Describe the bug

The access token is currently validated against the oidc-`userinfo` endpoint. https://github.com/owncloud/ocis/blob/master/services/proxy/pkg/middleware/oidc_auth.go#L82
This is ok if the oauth2-`client` is the website server and it's the only one that handles the token (website is the oauth2-client).

But owncloud uses this token also to access resources eg. webdav and other rest calls.
eg. ocis is a oauth2 `resource-server`.
ref: https://datatracker.ietf.org/doc/html/rfc6749#section-1.2

This leads to a problem, if you what to use one OIDC provider for multiple stuff or want to separate access for different apps.
(create-share, read-data, write-data, ...)

This is not a problem, when you are not going to separate the access.

As I see the security risk at the moment not so high, I think it makes more sense to discuses this publicly.
But it ether leads to security problem if ocis is connected to an external OIDC provider or it has to be a separate oauth2-issuer for owncloud, what is against how oauth2 should work.
The "old" OC10 implementation is not affected, as it uses the approach from solution2

### attack example

example deployment from : https://*.ocis-keycloak.latest.owncloud.works

IDP: https://keycloak.ocis-keycloak.latest.owncloud.works
oc instance: https://ocis.ocis-keycloak.latest.owncloud.works
attacker: https://web.evil

oc uses keycloak as IDP
attacker has an valid oauth2 client for IDP

attacker website get the user to authenticate on web.evil with the common identity provider.
the user gives only "rights"/scope for accessing the profile/email address (OIDC-login).
attacker can now not only access information about the user (userinfo-endpoint)
it can use the same access-token to access data on the oc instance,
as there is no scope/client_id limitation done.

## Solution / Proposals 1

OAuth2 "defines" for this purpose the **Introspection** api:
 * https://datatracker.ietf.org/doc/html/rfc7662
 * https://www.oauth.com/oauth2-servers/token-introspection-endpoint/
 * https://github.com/keycloak/keycloak-documentation/blob/main/authorization_services/topics/service-rpt-token-introspection.adoc
 * https://www.ory.sh/docs/hydra/reference/api#operation/introspectOAuth2Token
 * https://www.ory.sh/docs/hydra/guides/oauth2-token-introspection

I don't know about a standard definition for:
 * Introspection_url endpoint location
 * webdav access / create-share - scope for oauth2
 * Introspection should have authentication, eg. basic-auth (or bearer-auth )

keycloak has the endpoint for the Introspection_endpoint in the `.well-known/openid-configuration` config,
but I don't know about a rfc, that defines that, also authentication is required.
also basic-auth, need to be handeld out of bound.
ref: https://ocis.ocis-keycloak.latest.owncloud.works/.well-known/openid-configuration

with ory/hydra I have to put a authorization by myself in front of it, no exposure in well-known

dovecot (mail-server) solved the Introspection issue by let the user configure it by a parameter.
I would suggest to go with that way.
ref: https://doc.dovecot.org/configuration_manual/authentication/oauth2/

some refs/example usages for webdav scopes:
 * https://www.oauth.com/oauth2-servers/scope/defining-scopes/
 * https://developers.google.com/identity/protocols/oauth2/scopes#drive
 * https://www.dropbox.com/developers/documentation/http/documentation

I think a good list to start with is, please comment on better suggestions:
 * owncloud - access all ?needed?
 * owncloud-manage - change settigns, all other stuff?
 * owncloud-share - create share link
 * owncloud-share-readonly - create readonly share link, needed?
 * webdav - read/write access to webdav
 * webdav-readonly - read only access to webdav

### changes needed
 * implement a Introspection api - not public accessible 
 * change proxy-middle ware to use introspect instant of userinfo_endpoint
 * forward scope information to sub services
 * validating scope in sub service or in the proxy
 * change client apps to request the correct scope
   - web front, android app,  ios app, desktop app
   - change auth request scope
   - change dynamic client registration scope

## Solution / Proposals 2

owncloud runs its own IDP additional to the external one (keyclock, hydra, ...)
if a client wants access, the client gets not directly forwarded to the external IDP.
it request an token from owncloud but owncloud does a OIDC token request on the external IDP and forward the authentication.
if granted the owncloud IDP get the userinformation and crates a "local" token with itself as issuer,
user will see second consent page.

This would prevent from cross contamination of other access tokens from the external provider.

### changes needed:
 * change login screen to allow external login with account (can be multiple provider)
 * add OIDC handling, check aud == client_id, ...
 * settings for configuration (openid-well-known endpoint, client_id, client_secret)

## Additional context

IMHO is solution2 also a valid approach, I know from `gitea`, `matrix` and  `OC10` that do it like this,
this allows it also to handle scope management / consent locally by owncloud

Cons is, that you have not the fine granularity of restricting different stuff with scopes.
So I would still recommend to do solution1 to have that feature.

If you want to have one access token that is valid at ocis and for example an calendar service, you need to take solution1.

This is a big topic and I see this as a start of an open discussion.
I'm not into go programming, so I would let the devs do that.

**Comment by micbar** [comment]
Thank you very much @TuxCoder for this detailed and professional bug report.

We are already working on one aspect of it in #2967 

We will fix it for General Availability in the scope of that linked ticket.

**Comment by TuxCoder** [comment]
Hello @micbar 
Ah yes this is a duplicate, don't know how I did not found it before.
Will try to help there with my feedbak
