### ISSUE TITLE
Sessions are not stored

### ISSUE THREAD

**Issue by ishank011** [owncloud/ocis#432]
The user needs to login every time to access ocis from a different tab.

**Comment by micbar** [comment]
The session is coming from the IDP

The Login Button on the first page in phoenix is only there for branding purposes.
We will add a config to disable that page by default.

**Comment by ishank011** [comment]
@micbar sure, for OIDC that would be taken care of, but if we want to use basic auth, the problem would still be there.

**Comment by pmaier1** [comment]
https://github.com/owncloud/product/issues/170

**Comment by refs** [comment]
done on https://github.com/owncloud/product/issues/170
