### ISSUE TITLE
Renaming a received share effects in sharees list api but not on single resource

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#4322]
## Describe the bug

Renaming a recieved share effects in sharees list api but not on single resource 

## Steps to reproduce

1. Albert shares with Alice a folder named folder
2. Alice renames the shared folder (mountpoint) to sharedFolder 
3. Calling https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?include_tags=false&state=all&shared_with_me=true shows  the new name in the path
4. Calling https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/21da5f9d-2b7d-47e5-bf07-e3843c33d88f shows the old (original) name in path

## Expected behavior
New name should be listed in path calling single get share

## Actual behavior
Old (original) name listed in path calling single get share

**NOTE:** There is also a slight difference in the path property calling:
https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?include_tags=false&state=all&shared_with_me=true 
path contains /**Shares**/sharedFolder 
while calling https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/21da5f9d-2b7d-47e5-bf07-e3843c33d88f
path contains /folder 

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by JanAckermann** [comment]
FYI @C0rby @micbar

**Comment by micbar** [comment]
Needs quick fix.

**Comment by JanAckermann** [comment]
@micbar Is this still in planning?

**Comment by C0rby** [comment]
@JanAckermann, can you provide me with an example curl request to rename a share?
I currently get a `409 Conflict` response and don't know if my request is missing anything.
