### ISSUE TITLE
Changing personal drive quota on another user as admin is not possible

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#4325]
## Describe the bug

Changing personal quota on another user as admin is not possible

## Expected behavior
Changing personal quota on another user should be possible

## Actual behavior
Changing personal quota on another user is not possible

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by JanAckermann** [comment]
Blocks https://github.com/owncloud/web/issues/7059

**Comment by ScharfViktor** [comment]
Can confirm. I came across this too
admin or spaceAdmin can change only its own quota. 

`curl -X PATCH 'https://localhost:9200/graph/v1.0/drives/<anotherUserPersonalSpaceId>' -H "Content-Type: application/json" --data '{"quota":{"total":1000000}}' -uadmin:admin -vk`

**Comment by micbar** [comment]
Reva fix in https://github.com/cs3org/reva/pull/3133

**Comment by micbar** [comment]
needs reva update.

**Comment by micbar** [comment]
fixed by #4369
