### ISSUE TITLE
graph api drive quota should expunge total:0 if set so (unrestricted)

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#4328]
## Expected behavior
Quota should show total 0 if set so

## Actual behavior
total property is missing entirely 

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by michl19** [comment]
sending 0 value is possible
