### ISSUE TITLE
Nightly failed on apiWebdavPreviews/previews.feature:219

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#4339]
Build: https://drone.owncloud.com/owncloud/ocis/14181/52/7
```feature
@skipOnOcV10.6 @skipOnOcV10.7 @skipOnOcV10.8.0
  Scenario: updates to a file should change the preview for both sharees and sharers                                      # /drone/src/oc10/testrunner/tests/acceptance/features/apiWebdavPreviews/previews.feature:219
    Given the administrator has set the default folder for received shares to "Shares"                                    # OccContext::theAdministratorHasSetTheDefaultFolderForReceivedSharesTo()
    And auto-accept shares has been disabled                                                                              # FeatureContext::autoAcceptSharesHasBeenDisabled()
    And user "Brian" has been created with default attributes and without skeleton files                                  # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Alice" has created folder "FOLDER"                                                                          # FeatureContext::userHasCreatedFolder()
    And user "Alice" has uploaded file with content "file to upload" to "/FOLDER/lorem.txt"                               # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has shared folder "FOLDER" with user "Brian"                                                         # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "Brian" has accepted share "/FOLDER" offered by user "Alice"                                                 # FeatureContext::userHasReactedToShareOfferedBy()
    And user "Alice" has downloaded the preview of "/FOLDER/lorem.txt" with width "32" and height "32"                    # FeatureContext::userDownloadsThePreviewOfWithWidthAndHeight()
    And user "Brian" has downloaded the preview of "Shares/FOLDER/lorem.txt" with width "32" and height "32"              # FeatureContext::userDownloadsThePreviewOfWithWidthAndHeight()
    When user "Alice" uploads file "filesForUpload/lorem.txt" to "/FOLDER/lorem.txt" using the WebDAV API                 # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "204"                                                                             # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And as user "Alice" the preview of "/FOLDER/lorem.txt" with width "32" and height "32" should have been changed       # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
    And as user "Brian" the preview of "Shares/FOLDER/lorem.txt" with width "32" and height "32" should have been changed # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
    When user "Brian" uploads file with content "new uploaded content" to "Shares/FOLDER/lorem.txt" using the WebDAV API  # FeatureContext::userUploadsAFileWithContentTo()
    Then the HTTP status code should be "204"                                                                             # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And as user "Alice" the preview of "/FOLDER/lorem.txt" with width "32" and height "32" should have been changed       # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
      HTTP status code 404 is not the expected value 200
      Failed asserting that 404 matches expected 200.
    And as user "Brian" the preview of "Shares/FOLDER/lorem.txt" with width "32" and height "32" should have been changed # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
```

**Comment by SagarGi** [comment]
```
72 scenarios (72 passed)
1296 steps (1296 passed)
4m53.91s (19.93Mb)
runsh: Total 72 scenarios (72 passed, 0 failed)
runsh: Exit code of main run: 0
```
Tried it to reproduce locally but not reproducable. I will try ti fail it on CI.

**Comment by SagarGi** [comment]
Passing consistently in CI as well https://drone.owncloud.com/owncloud/ocis/14187/40/8

**Comment by saw-jan** [comment]
@SagarGi Re-appeared today: https://drone.owncloud.com/owncloud/ocis/14356/51/7

**Comment by SagarGi** [comment]
ok i will be looking into it today as well.

**Comment by SagarGi** [comment]
The above scenario is not reproducible but can be reproduce when we keep the both content same as the above error says.
May be `When user "Alice" uploads file "filesForUpload/lorem.txt" to "/FOLDER/lorem.txt" using the WebDAV API` this step could be replace with `When user "Alice" uploads file with content "new uploaded content one" to "/FOLDER/lorem.txt" using the WebDAV API` since others scenarios are using the update step like this. @saw-jan

**Comment by amrita-shrestha** [comment]
> @SagarGi Re-appeared today: https://drone.owncloud.com/owncloud/ocis/14356/51/7 But in different step:
> 
> ```
>   @skipOnOcV10.6 @skipOnOcV10.7 @skipOnOcV10.8.0
>   Scenario: updates to a file should change the preview for both sharees and sharers                                      # /drone/src/oc10/testrunner/tests/acceptance/features/apiWebdavPreviews/previews.feature:219
>     Given the administrator has set the default folder for received shares to "Shares"                                    # OccContext::theAdministratorHasSetTheDefaultFolderForReceivedSharesTo()
>     And auto-accept shares has been disabled                                                                              # FeatureContext::autoAcceptSharesHasBeenDisabled()
>     And user "Brian" has been created with default attributes and without skeleton files                                  # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
>     And user "Alice" has created folder "FOLDER"                                                                          # FeatureContext::userHasCreatedFolder()
>     And user "Alice" has uploaded file with content "file to upload" to "/FOLDER/lorem.txt"                               # FeatureContext::userHasUploadedAFileWithContentTo()
>     And user "Alice" has shared folder "FOLDER" with user "Brian"                                                         # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
>     And user "Brian" has accepted share "/FOLDER" offered by user "Alice"                                                 # FeatureContext::userHasReactedToShareOfferedBy()
>     And user "Alice" has downloaded the preview of "/FOLDER/lorem.txt" with width "32" and height "32"                    # FeatureContext::userDownloadsThePreviewOfWithWidthAndHeight()
>     And user "Brian" has downloaded the preview of "Shares/FOLDER/lorem.txt" with width "32" and height "32"              # FeatureContext::userDownloadsThePreviewOfWithWidthAndHeight()
>     When user "Alice" uploads file "filesForUpload/lorem.txt" to "/FOLDER/lorem.txt" using the WebDAV API                 # FeatureContext::userUploadsAFileTo()
>     Then the HTTP status code should be "204"                                                                             # FeatureContext::thenTheHTTPStatusCodeShouldBe()
>     And as user "Alice" the preview of "/FOLDER/lorem.txt" with width "32" and height "32" should have been changed       # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
>     And as user "Brian" the preview of "Shares/FOLDER/lorem.txt" with width "32" and height "32" should have been changed # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
>     When user "Brian" uploads file with content "new uploaded content" to "Shares/FOLDER/lorem.txt" using the WebDAV API  # FeatureContext::userUploadsAFileWithContentTo()
>     Then the HTTP status code should be "204"                                                                             # FeatureContext::thenTheHTTPStatusCodeShouldBe()
>     And as user "Alice" the preview of "/FOLDER/lorem.txt" with width "32" and height "32" should have been changed       # FeatureContext::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged()
>       WebDav::asUserThePreviewOfPathWithHeightAndWidthShouldHaveBeenChanged previous and current previews content is same but expected to be different
>       Failed asserting that Binary String: 0xffd8ffdb008400080606070605080707070909080a0c140d0c0b0b0c1912130f141d1a1f1e1d1a1c1c20242e2720222c231c1c2837292c30313434341f27393d38323c2e333432010909090c0b0c180d0d1832211c213232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232ffc00011080020002003012200021101031101ffc401a20000010501010101010100000000000000000102030405060708090a0b100002010303020403050504040000017d01020300041105122131410613516107227114328191a1082342b1c11552d1f02433627282090a161718191a25262728292a3435363738393a434445464748494a535455565758595a636465666768696a737475767778797a838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae1e2e3e4e5e6e7e8e9eaf1f2f3f4f5f6f7f8f9fa0100030101010101010101010000000000000102030405060708090a0b1100020102040403040705040400010277000102031104052131061241510761711322328108144291a1b1c109233352f0156272d10a162434e125f11718191a262728292a35363738393a434445464748494a535455565758595a636465666768696a737475767778797a82838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae2e3e4e5e6e7e8e9eaf2f3f4f5f6f7f8f9faffda000c03010002110311003f00f62123e3ef374f5a52efc82ed8c64fcc6b4fec36ff00dc3ff7d1a058db8fe03ff7d1a00ccdce40cbb67fdea7c137972077deea3b6e3fe35a1f61b70a1769c0ff0068d392d2042484ce7fbc73fce8027a28a2800a28a2803fffd9
> is not equal to <text>.
>     And as user "Brian" the preview of "Shares/FOLDER/lorem.txt" with width "32" and height "32" should have been changed
> ```

Re-occurred at  build: https://drone.owncloud.com/owncloud/ocis/14706/51/7

**Comment by SagarGi** [comment]
This issue cannot be reproduce locally. And all the failures seems to be with the content check. It fails sometimes on upper upload(change content) or for the second change(change content). Upon investigation the failure seems to be due to same content (can be reproduce when we make the content same when updating). But the tests is checking status code that file has been updated. But still intermittently failing.

**Comment by SagarGi** [comment]
https://github.com/owncloud/ocis/pull/4435 this is a debug PR with step  ` And the content of file "/FOLDER/lorem.txt" for user "Alice" should be "updated file one"` . And is passing consistently on debug build. But cant certainly say that it could be the main reason reason of failure. But might help for debugging if it fails in coming days.

**Comment by SagarGi** [comment]
Tried with uploading large file and problem does not seem to be on upload content. Very Hard to reproduce locally or in CI.

**Comment by kiranparajuli589** [comment]
Adding the content assertion step is surely helpful, but just for the debugging purpose. Strange that the multiple runs missed the flakiness. Maybe try with some different scenarios (not only single multiple scenarios). Or we may have to wait for to see if it is resolved already.

**Comment by SagarGi** [comment]
Not seen in recent build i am putting this to backlog. Can be brought back if reoccured

**Comment by SwikritiT** [comment]
As this issue has not been reproduced for a while now, @grgprarup is going to do a final check and maybe we can close this if it is not reproducible.

**Comment by grgprarup** [comment]
Tried to reproduce this issue and is not reproducible locally and passing on recent nightly builds. So closing this issue.
