### ISSUE TITLE
ocs/v1.php/cloud/users/{userId} -> quota -> wrong relative amount

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#4357]
## Describe the bug

ocs/v1.php/cloud/users/{userId} -> quota -> wrong relative amount 

![image](https://user-images.githubusercontent.com/26169327/183437956-935c8549-7667-4313-86e4-0040491b6690.png)

## Steps to reproduce

1. Set personal drive quota to 100MB 
2. Upload a file with 69MB
3. See quota relative property in `ocs/v1.php/cloud/users/admin` endpoint

```
<quota
>
<free
>
30818752
</free
>
<used
>
69181248
</used
>
<total
>
100000000
</total
>
<relative
>
0.69181246
</relative
>
</quota>
```

## Expected behavior
Should be: 69.181246

## Actual behavior
Is: 0.69181246

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by micbar** [comment]
Checked with ocs spec, should be real percentage like @JanAckermann states it.

**Comment by rhafer** [comment]
Will be fixed with https://github.com/cs3org/reva/pull/3238

**Comment by SwikritiT** [comment]
@roshanlc is working on this
