### ISSUE TITLE
account information in phoenix show username and groups as UUID

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#437]
1. Check out PR #409
1. login as "einstein" into phoenix
1. go to the accounts page

![image](https://user-images.githubusercontent.com/2425577/88880293-116e2500-d24c-11ea-8fb9-f0ac451fd0a4.png)

**Comment by PVince81** [comment]
- [ ] split into two tickets, groups to be addressed separately. userid more important as that would be a regression

**Comment by LukasHirt** [comment]
> split into two tickets, groups to be addressed separately. userid more important as that would be a regression

Username ticket - #440 
Groups ticket - #441

Closing this issue in favour of those two.
