### ISSUE TITLE
Can not upload empty file

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#4383]
When trying to upload an empty file via the web ui to a share, uploading fails.

## To reproduce

- `touch foo.txt`
- try to upload foo.txt

**Comment by micbar** [comment]
The sharestorageprovider and maybe also the publicshareprovider needs to implement `TouchFile`.

**Comment by individual-it** [comment]
QA-team should implement API tests for that if not existing yet

**Comment by SagarGi** [comment]
API tests has been added with this PR https://github.com/owncloud/core/pull/40311

**Comment by micbar** [comment]
brought to ocis via #4590
