### ISSUE TITLE
Display group name instead of id at the accounts page

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/ocis#441]
In the account page, groups being displayed with their id instead of a name. Happening only against oCIS, oC10 works fine.

![image](https://user-images.githubusercontent.com/25989331/89884753-41151980-dbca-11ea-9a8f-67d69c10cafd.png)

**Comment by refs** [comment]
as of today, not happening anymore with OCIS:

![image](https://user-images.githubusercontent.com/6905948/104305835-7b624a00-54cd-11eb-971d-669fc7e29ebf.png)
