### ISSUE TITLE
implement migration for sc3 to jsoncs3 sharemanager

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#4430]
https://github.com/cs3org/reva/pull/3148 introduces a new `jsoncs3` manager to fix performance problems of the `cs3` share manager.

We need to provide a migration to 
- [ ] Load() shares inte the `jsoncs3` share manager and
- [ ] Dump() them from `cs3`.
- [ ] test with the migrate command

**Comment by aduffeck** [comment]
This has been implemented with the merge of reva 2.9 (https://github.com/cs3org/reva/pull/3171)
