### ISSUE TITLE
implement jsoncs3 publicshare manager

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#4431]
similar to https://github.com/cs3org/reva/pull/3148 we need to apply the approach of the `jsoncs3` share manager to the `cs3` publicsharemanager.

Currently, a folder with 100 files takes 5sec to list in the web ui, because it asks for the `oc:share-types` property. It will internally stat every resurce in the listing...

related: https://github.com/cs3org/reva/issues/2976

**Comment by aduffeck** [comment]
This has been implemented with the merge of reva 2.10 (https://github.com/cs3org/reva/pull/3199)
