### ISSUE TITLE
Public cannot open link to project space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4452]
ownCloud Web UI 5.7.0-rc.10 
Infinite Scale 2.0.0-beta.7

Steps:

- admin creates project space
- admin creates public link to project space
- public try to open link

Actual: 
![image](https://user-images.githubusercontent.com/84779829/186425349-5518d8e1-44e8-4791-9b61-abdee6bbdf68.png)

**Comment by ScharfViktor** [comment]
regression. it's strange why the api tests didn't detect it. i'll find out.

**Comment by C0rby** [comment]
I can't reproduce this.

**Comment by kulmann** [comment]
Me neither.

**Comment by ScharfViktor** [comment]
rm -rf ocis, make clean, make build, make generate on fresh master. Start ocis again and I could reproduce it:
 https://user-images.githubusercontent.com/84779829/186431751-d3967ba9-7afc-471f-b06e-b8a68e9058f0.mov

**Comment by C0rby** [comment]
Nope, I still can't reproduce it.
But in your video there is this strange UI glitch and error message. Did you generate first and then build? Because that is the correct order.

**Comment by ScharfViktor** [comment]
> Nope, I still can't reproduce it. But in your video there is this strange UI glitch and error message. Did you generate first and then build? Because that is the correct order.

Now it's all good. Thanks @C0rby
