### ISSUE TITLE
User cleanup during API acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#4457]
Issue #4390 (PRs #4433 #4441 #4456 ) implements cleanup of personal spaces and project spaces at the end of each API test scenario - good.

But I think that only happens for the local API acceptance test suites. The `AfterScenario` is in `SpacesContext`, and `SpacesContext` is never loaded when the core API tests are run. The core API tests create users, and those users have a personal space when the test suite is run against an oCIS server. (The core API tests never create a porject space, so we do not need to worry about cleaning up those)

1) Design and implement a way to get at least the needed personal-space-cleanup code to run after each core scenario finishes.

The Behat test-runner does not guarantee the order that `AfterScenario` methods are run. It could be that the `AfterScenario` that deletes users runs before the `AfterScenario` that cleans up spaces. This could be a problem in both local and core API acceptance test runs.

2) Design and implement a way to make sure that project spaces and personal spaces are cleaned up before users are deleted.

**Comment by grgprarup** [comment]
The clean-up of spaces after user deletion is implemented by these PRs
https://github.com/owncloud/ocis/pull/4532, https://github.com/owncloud/ocis/pull/4533
Now, the user spaces created after running core test from ocis and ocis local tests are deleted properly.
So closing this issue on behalf of the above PRs.
