### ISSUE TITLE
Option to give 0B quota instead of `no restriction `

### ISSUE THREAD

**Issue by T0mWz** [owncloud/ocis#4468]
## Describe the bug

It should be possible to give an account a quota of 0 bytes so that it is not able to upload its own data, but can only upload/edit in shares or spaces.

## Steps to reproduce

1. Try to assign a quota of 0GB to an account

## Expected behavior
Make a difference between unlimited and 0 bytes.

## Actual behavior
Quota is interpreted as no restrictions / unlimited

## Setup
 * ownCloud Web UI 5.7.0-rc.10
 * Infinite Scale 2.0.0-beta.7 Community

**Comment by micbar** [comment]
@T0mWz 

Thanks for the ticket.

The CS3Apis and the ocis implementation has decided to use the uint `0` as `unlimited`. This is a property of a storage space.

A different story is the use case that a user should have no storage space to write files. This will be a permission in the future.
