### ISSUE TITLE
the state of `Shares Jail` quota and resources inside it  is always shown as exceeded 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#4472]
## Steps to reproduce

1. As user1 share folder `folder_from_brian` to user2
2. As user2 accept the share
3. As user2 list the drives 
```
curl -u user2:123456 -k -X GET https://host.docker.internal:9200/graph/v1.0/me/drives -v | jq
```
## Expected behavior
The share jail should have certain quota and it shouldn't be shown exceeded while you can still upload files inside it 

## Actual behavior
The quota of share jail is shown `exceeded` and `total`, `remaining`, `used` is shown as `0` , while the user can still get other shares and can upload to the received shares or edit the content.
```
{
  "value": [
    {
      "driveAlias": "virtual/shares",
      "driveType": "virtual",
      "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
      "lastModifiedDateTime": "2022-08-29T08:53:18.815867714Z",
      "name": "Shares Jail",
      "quota": {
        "remaining": 0,
        "state": "exceeded",
        "total": 0,
        "used": 0
      },
      "root": {
        "eTag": "\"0067646d9dc32d042992cea8eed61953\"",
        "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
        "webDavUrl": "https://host.docker.internal:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668"
      }
    },
    {
      "driveAlias": "mountpoint/test.txt",
      "driveType": "mountpoint",
      "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!97f15415-8a6c-4550-bc4d-4afdbd86ca15",
      "name": "test.txt",
      "owner": {
        "user": {
          "id": "15d8da09-aa40-43a3-9da4-09693d44bfd9"
        }
      },
      "quota": {
        "remaining": 0,
        "state": "exceeded",
        "total": 0,
        "used": 0
      },
      "root": {
        "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!97f15415-8a6c-4550-bc4d-4afdbd86ca15",
        "remoteItem": {
          "eTag": "\"850dc3467bdecf0cf5e18b1c9d1a6438\"",
          "file": {
            "mimeType": "text/plain"
          },
          "id": "1284d238-aa92-42ce-bdc4-0b0000009157$15d8da09-aa40-43a3-9da4-09693d44bfd9!d067edf2-0b09-4111-aa3b-c09b321d56b6",
          "lastModifiedDateTime": "2022-08-29T08:53:18.767409136Z",
          "name": "test.txt",
          "size": 17,
          "webDavUrl": "https://host.docker.internal:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$15d8da09-aa40-43a3-9da4-09693d44bfd9%21d067edf2-0b09-4111-aa3b-c09b321d56b6"
        },
        "webDavUrl": "https://host.docker.internal:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668%2197f15415-8a6c-4550-bc4d-4afdbd86ca15"
      }
    },
    {
      "driveAlias": "mountpoint/folder_from_brian",
      "driveType": "mountpoint",
      "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!4c8dccf6-c732-433b-aa29-04e61c7f96e2",
      "name": "Folder_From_Brian",
      "owner": {
        "user": {
          "id": "15d8da09-aa40-43a3-9da4-09693d44bfd9"
        }
      },
      "quota": {
        "remaining": 0,
        "state": "exceeded",
        "total": 0,
        "used": 0
      },
      "root": {
        "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!4c8dccf6-c732-433b-aa29-04e61c7f96e2",
        "remoteItem": {
          "eTag": "\"0067646d9dc32d042992cea8eed61953\"",
          "folder": {},
          "id": "1284d238-aa92-42ce-bdc4-0b0000009157$15d8da09-aa40-43a3-9da4-09693d44bfd9!d29ffd45-06a2-43c5-ba68-c99ef4c5fbad",
          "lastModifiedDateTime": "2022-08-29T08:53:18.815867714Z",
          "name": "Folder_From_Brian",
          "size": 17,
          "webDavUrl": "https://host.docker.internal:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$15d8da09-aa40-43a3-9da4-09693d44bfd9%21d29ffd45-06a2-43c5-ba68-c99ef4c5fbad"
        },
        "webDavUrl": "https://host.docker.internal:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668%214c8dccf6-c732-433b-aa29-04e61c7f96e2"
      }
    },
    {
      "driveAlias": "personal/user2",
      "driveType": "personal",
      "id": "1284d238-aa92-42ce-bdc4-0b0000009157$6a561bf6-86ea-493d-b69c-6a47d2477929",
      "lastModifiedDateTime": "2022-08-29T08:52:19.631345194Z",
      "name": "Alice",
      "owner": {
        "user": {
          "id": "6a561bf6-86ea-493d-b69c-6a47d2477929"
        }
      },
      "quota": {
        "remaining": 73058181120,
        "state": "normal",
        "total": 0,
        "used": 0
      },
      "root": {
        "eTag": "\"f0bc0ed0719493c93868514b41cd3ff8\"",
        "id": "1284d238-aa92-42ce-bdc4-0b0000009157$6a561bf6-86ea-493d-b69c-6a47d2477929",
        "webDavUrl": "https://host.docker.internal:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$6a561bf6-86ea-493d-b69c-6a47d2477929"
      }
    }
  ]
}

```
## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by SwikritiT** [comment]
Also, I couldn't change the quota of the `shares jail`. I don't know if it's designed that way or if it's to be implemented. It gives me `500 Internal Server Error` 

cc @micbar @ScharfViktor

**Comment by ScharfViktor** [comment]
state is calculated and exceeded because we do not set a quota for shares jail. When user get share, he doesn't spent his storage and we do not limit his incoming files (no setting quota of the shares jail)

I don't see an error here IMHO

**Comment by phil-davis** [comment]
For `"driveAlias": "virtual/shares"` that seems reasonable - the user cannot write directly there (cannot create a new folder or file at the root of the shares jail).

For `"driveAlias": "mountpoint/folder_from_brian"` - that is a folder from Brian. If the share receiver has write access to the share, then the share receiver can upload files into that folder. Brian has some remaining quota, and the share receiver can upload files to `folder_from_brian` until they use up all of Brian's quota. If the remaining quota would be mentioned, then client's could decide in advance if there is insufficient quota to upload a file. But I think that there was some discussion elsewhere recently about this - that we did not want to easily expose "personal" information about the storage of Brian.

**Comment by ScharfViktor** [comment]
Yes, it is interesting case. 
- Brian creates folderToMarie and shares to Marie with editor role
- Marie can upload a data to folder and spends a Brians quota
- Brian cannot set quota to folder or quota to "mountpoint/folderToMarie" because he is not admin

what is the right behavior here?
- brian asks admin to set quota for "mountpoint/folderToMarie"
- brian has abbility to set shares folder quota 
- do nothing
- other suggestions

**Comment by phil-davis** [comment]
I suspect "do nothing" - in oC10 when Brian shares `folderToMarie` to Marie, and gives write access to Marie, then Marie can upload as much as she likes until the files take all the remaining quota of Brian. Brian (or the admin) has no way to specify a "subquota" for `folderToMarie

Allowing Brian to set a "subquota" on each folder that he shares, that would be a whole new feature - if someone wants it, and someone agrees to it, and someone codes it - that's a lot of "someones"!`.

**Comment by dragonchaser** [comment]
After discussion with @micbar we decided to remove the quota array from the api response for now.

**Comment by micbar** [comment]
1) We should remove the quota field completely from the shares jail because this is a virtual collection of multiple origins

2) We should discuss how we show the quota on mountpoints @tbsbdr @butonic

**Comment by dragonchaser** [comment]
Should we split that into two tickets then?

**Comment by dragonchaser** [comment]
I have opened a follow-up issue vor post 3.0.0.
