### ISSUE TITLE
[Previews] Incorrect handling of EXIF orientation flags for thumbnail generation

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#4477]
## Describe the bug

Previews and thumbnails of images with EXIF orientation flag are displayed sideways or upside down.

## Steps to reproduce

1. Upload example files from https://github.com/recurser/exif-orientation-examples
2. Browse them in the web UI

## Expected behavior

Thumbnail generation should respect the embedded EXIF orientation flag

## Actual behavior

![CleanShot 2022-08-30 at 16 55 28](https://user-images.githubusercontent.com/214010/187470281-556f61eb-90f2-4a24-8601-f77f2faf10fb.png)

## Setup

https://ocis.ocis-keycloak.latest.owncloud.works

```
[Log]  ownCloud Web UI 5.7.0-rc.10  (web-runtime-315e35bd.js, line 1)
[Log]  Infinite Scale 2.0.0-beta.7+d4b9e9b3b Community  (web-runtime-315e35bd.js, line 1)
```

## Additional context

More learnings over the years: https://github.com/owncloud/ocis/issues/1378

/cc FYI @fschade

**Comment by micbar** [comment]
@C0rby Is this a quick win in the current implementation?

**Comment by C0rby** [comment]
I think this should be fairly simple to implement
