### ISSUE TITLE
Graph API capability

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#4481]
## Is your feature request related to a problem? Please describe.
The ownCloud Web client needs to know whether or not it should query the graph api or a different api (e.g. graph or OCS for obtaining names of groups of a user).

## Describe the solution you'd like
Minimal solution: introduce a new capability object `graph` with props `enabled` and `version`, as already done for e.g. `spaces` capability.
More advanced solution: inside the `graph` capability from the minimal solution we could add a list of available endpoints. Not sure if that makes sense.

## Describe alternatives you've considered
None. Happy about ideas.

**Comment by butonic** [comment]
I would like to see a discovery mechanism for the graph endpoint that works similar to the openid connect discovery: https://openid.net/specs/openid-connect-discovery-1_0.html

When the user enters his username or email in the login form a discovery is used to find the IdP as well as the graph endpoint. The graph endpoint and its capabilities can then be described in the same way as IdP metadata: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

Now, the discovery is optional and the default url could be our old status.php or capabilities endpoint, but I think it makes more sense to use https://cloud.ocis.test/graph/v1.0/$metadata as that holds all metadata for an odata endpoint: https://docs.microsoft.com/en-us/graph/traverse-the-graph

You can take a look at https://graph.microsoft.com/v1.0/$metadata to see the ms graph metadata. 

To answer the original question: for now use a config property for the web ui that defines how the web ui should decide:

for oc10 deployments
```
"discovery": {
  "oidc": {"static": "https://idp.ocis.test"}, // or relative urls?
  "capabilities": {"static": "https://oc10.ocis.test"},
```

for ocis
```
"discovery": {
  "oidc": {"static": "https://idp.ocis.test"},
  "graph": {"static": "/graph/v1.0"},
}
```

in the future
```
"discovery": {
  "oidc": "auto",
  "graph": "auto",
}
```

thoughts?

**Comment by rhafer** [comment]
> You can take a look at https://graph.microsoft.com/v1.0/$metadata to see the ms graph metadata.

Did that. I am not sure what to say ... it's overwhelming.
I am not exactly sure how that would provide the information we actually need though. Ok it exposes a list of all the types and relations (and more) that are supported by a certain API.

But what the WebUI additionally needs is e.g. possibility to figure out which user properties are readonly and which are writeable in the current configuaration. So when e.g. an external IDM is used mark all the user properties apart from `accountEnabled` as readonly.

**Comment by kulmann** [comment]
Not relevant anymore, since web is only talking with ocis by now 🥳
