### ISSUE TITLE
Search/REPORT can't find sub-folder in a recieved shared folder

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#4489]
## Describe the bug

Search/REPORT can't find sub-folder in a recieved shared folder

## Steps to reproduce

1. As 'einstein' create a folder 'share' and inside 'share' a folder named 'demo' 
2. Share folder 'share' with user 'marie'
3. As user 'marie' search for 'demo' via DAV REPORT
4. Folder 'demo' not in response

## Expected behavior
Folder 'demo' should be in response

## Actual behavior
Folder 'demo' is not in response

**Comment by JanAckermann** [comment]
FYI  @aduffeck @kobergj

**Comment by michl19** [comment]
Works in experimental branch. Let us try to backboard search capabilities into master.

**Comment by aduffeck** [comment]
Hm, has this been fixed meanwhile? I don't see any relevant commits in master since this issue was filed but I can't reproduce the problem in current master. Both the top share folder and its child folders are being found on the grantee side for me.

**Comment by aduffeck** [comment]
@JanAckermann can you please check if you still see this issue? I can't reproduce.

![image](https://user-images.githubusercontent.com/203813/190351247-752d15a2-0f9d-4ca5-afac-2cb79e371d22.png)

**Comment by JanAckermann** [comment]
@ScharfViktor at the time it wasn't working, as the folder 'share' was returned in the search result.
NVM bug seems to be fixed, closing.

**Comment by aduffeck** [comment]
I think I have to reopen this, I just ran into a similar problem on my local instance with some entities not being found. It seems to be related to public shares. Investigating....

**Comment by saw-jan** [comment]
@roshanlc has a PR to add test cases https://github.com/owncloud/ocis/pull/5456

**Comment by SwikritiT** [comment]
Tests added 
- [ ] stable-2.0 https://github.com/owncloud/ocis/pull/5456
- [ ] master

**Comment by SagarGi** [comment]
> * [ ]  Add tests coverage for spaces endpoint also Refactor the current feature file
>   https://github.com/owncloud/ocis/blob/754cc767a5427525a8b5a6ce0c2e67aa240fe50d/tests/acceptance/features/apiContract/sharesReport.feature#L17-L52
>   
>   Here this step uses spaces Webdav
> 
> ```
>     And the "REPORT" response to user "Brian" should contain a mountpoint "folderMain" with these key and value pairs:
>       | key              | value                |
>       | oc:fileid        | UUIDof:SubFolder1    |
>       | oc:file-parent   | UUIDof:folderMain    |
>       | oc:shareroot     | /folderMain          |
>       | oc:name          | SubFolder1           |
>       | d:getcontenttype | httpd/unix-directory |
>       | oc:permissions   | S                    |
> ```
> 
> This one uses old and new Webdav
> 
> ```
> When user "Brian" searches for "SubFolder1" using the WebDAV API 
> ```
> 
> If we want to test search /report response for old/new dav then why we are using step using space webdav question

I am not sure if there is a `spaces` endpoint for `REPORT` method. I tried with personal space id but the response seems to be empty. And also the UI uses the `new` webdav endpoint for searching files and folders.


![new](https://user-images.githubusercontent.com/46086950/231667764-4e193aaa-6ec8-4c98-b2e5-f0eace80c477.png)
