### ISSUE TITLE
TUS upload fail, was: 1.800 GB disk full after syncing only 850 GB

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#4516]
# Reproduce / what I did

1.  setup ocis beta 7 according to [https://owncloud.dev/ocis/deployment/basic-remote-setup/](https://owncloud.dev/ocis/deployment/basic-remote-setup/) (on my Odroid HC4 NAS, Armbian 22.08 Jammy, Kernel 5.10 )
2.  Config ocis data path to a dedicated HDD (EXT4) `/media/ocisdata`
3.  create user "tb", set quota to 2TB
4.  (the only users are "admin" and "tb"; admin has not uploaded a single file)
5.  Setup sync via Desktopclient 2.11.1 (build 8438) with external HDD (exFAT, no VFS)
6.  Synced ~850 GB with the server, but disk usage is at ~1.800 GB

![](https://user-images.githubusercontent.com/26610733/188509587-5556427d-5db9-4849-9177-07e197f7bff3.png)

# Expected behaviour

*   Disk usage should be ~850 GB

# Current behaviour

*   Disk usage is ~1.800 GB

unsure if this a bug or layer 8 issue.

**Comment by tbsbdr** [comment]
@micbar @dragotin do you have any idea what could cause this problem? It blocks me from using ocis for my family-cloud

**Comment by tbsbdr** [comment]
it says:

![](https://user-images.githubusercontent.com/26610733/190169676-b1a8e4dd-c5cf-4041-a051-f8bb6856be9e.png)

**Comment by tbsbdr** [comment]
More infos for debugging:

Blocksize of the is 4k:

```shell
odroidhc4:users:# tune2fs -l /dev/sda2
tune2fs 1.46.2 (28-Feb-2021)
Filesystem volume name:   OCDATA
Last mounted on:          /media/ocisdata
Filesystem UUID:          30c0abd2-01fe-4aad-b941-6b4b59ae0d23
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent flex_bg sparse_super large_file huge_file uninit_bg dir_nlink extra_isize
Filesystem flags:         signed_directory_hash
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              122093568
Block count:              488345366
Reserved block count:     60
Free blocks:              13172139
Free inodes:              122069680
First block:              0
Block size:               4096
Fragment size:            4096
Reserved GDT blocks:      907
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
RAID stride:              32716
Flex block group size:    16
Filesystem created:       Mon Nov 26 08:23:39 2018
Last mount time:          Mon Sep  5 22:53:16 2022
Last write time:          Mon Sep  5 22:53:16 2022
Mount count:              74
Maximum mount count:      -1
Last checked:             Mon Feb 28 05:37:21 2022
Check interval:           0 (<none>)
Lifetime writes:          6252 GB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:           256
Required extra isize:     28
Desired extra isize:      28
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      0b30a227-754e-41fb-bfb2-bfe6547a3758
Journal backup:           inode blocks
```

Metadata size seems ok

```shell
odroidhc4:users:# cd /media/ocisdata/storage
odroidhc4:storage:# du -sh *
3.1M metadata
1.8T users
odroidhc4:storage:#
```

upload directory seems to big:

```shell
odroidhc4:storage:# cd users
odroidhc4:users:# du -sh *
40K indexes
1.2T spaces
632G uploads
odroidhc4:users:#
```

`users` contains 15k directories:

```shell
odroidhc4:users:# find /media/ocisdata/storage/users -type d | wc -l
15613
```

 The data I store on the HDD are movies with filesizes 5-10 GB per Movie.

**Comment by dragotin** [comment]
Tried that with 2.4 GB from my local harddisk:
```
[kf:~] $ du -sh Downloads/
2,4G    Downloads/
[kf:~] $ 
```
which results in the harddisk usage in .ocis:
```
[kf:~/.ocis/storage] $ du -sh *
88K     metadata
2,6G    users
```

**Comment by tbsbdr** [comment]
ok, thx! will retry.

closing as not reproducible.

**Comment by kulmann** [comment]
Well, isn't it worth to dig deeper into the humongous upload folder? `632G uploads` certainly feels wrong.

**Comment by dragotin** [comment]
Tested with @tbsbdr again today (Hardware ODroid)

We set up vanilla oCIS beta8 and tried to upload a movie collection of 33 GB via sync client. For that, we created a new VFS folder on windows and moved the files into that. 

Uploading started ok'ish, just extremely slow. The server was bored most of the time, maybe because moving and VFS required so much client power?

At some point, the client reported bugs. On the server, most of the files (all?) are still in the upload folder. The nodes seem to be created.

Uploading a large single file via tus works fine. The problem only seems to happen with uploading many files via tus.

@TheOneRing  @butonic pls try to reproduce.

**Comment by TheOneRing** [comment]
Tus in 2.11 is broken.
Please test with 3.0

Ocis should block legacy clients https://github.com/owncloud/client/issues/9612

**Comment by dragotin** [comment]
What? That would mean we loose the ability to run oCIS with clients earlier than 3.0. That is **not ok**. We did a lot of compromises in the backend to be able to "satisfy" older clients - loosing that now on the last meters is not doable.

@micbar @michaelstingl pls look into that and find a compromise.

**Comment by tbsbdr** [comment]
Problem still exists with Desktop client 3.0 (though upload is much faster and stable - feels almost illegal fast 😼 )

"uploads" folder gets huge:

```shell
tg@odroidhc4:~$ du -sh /data/ocisdata/storage/users/*
28K /data/ocisdata/storage/users/indexes
104G /data/ocisdata/storage/users/spaces
164G /data/ocisdata/storage/users/uploads
```

**Comment by butonic** [comment]
Whenever an upload is finished, regardless which protocol (TUS or plain PUT) is used, `finishUpload()` and consecusively `discardChunk()` are called. It wipes the info and the bin file corresponding to the upload.

@tbsbdr To check what is going on could you post an `ls -lh /data/ocisdata/storage/users/uploads`. And maybe cat one of the json files in there?

**Comment by butonic** [comment]
AFAICT we currently have no cleanup job that removes unfinished uploads. The problem here is that the client started several uploads in parallel and they could not finish because collectively they filled the disk. Leading to a situation where no upload could finish.

**Comment by micbar** [comment]
We agreed that we can prevent this by checking the "uploads which are in progress" during "InitiateUpload".

**Comment by tbsbdr** [comment]
If `df` shows 100% usage of ocisdata:

*   ❌ Delete file via Web UI -> not possible (see above [https://github.com/owncloud/ocis/issues/4516#issuecomment-1258053676)](https://github.com/owncloud/ocis/issues/4516#issuecomment-1258053676))
*   ✅ Delete smalish file via cli, then: delete file via Web UI -> OK
*   ✅ Empty trashbin, then: delete file via Web UI -> OK
*   ✅ `ocis storage-users uploads list`:

```shell
Incomplete uploads:
- 4fc553f2-5bef-4530-9e39-324192c11732 (Ad Astra - Zu den Sternen (2019) 2160p AAC.mkv, Size: 5455061493, Expires: 2022-09-29T12:02:45+02:00)
- 643b98e5-aca9-45b0-91c8-c2f7ae47b9ef (Alien - Covenant (2017) 1080p AC3.mkv, Size: 2611262911, Expires: 2022-09-29T12:02:27+02:00)
- 9fdb7c60-e3f5-46b0-b9be-e862f70ad963 (American Beauty (1999) 480p AAC.mkv, Size: 1205082574, Expires: 2022-09-29T12:10:09+02:00)
- a94ea515-0cd7-4af2-b9a3-745874f0e641 (ubuntu-22.04.1-desktop-amd64.iso, Size: 3826831360, Expires: 2022-09-29T11:54:39+02:00)
- da8134df-e136-40fb-8301-8c3da5df84cd (A Quiet Place 2 (2021) 1080p EAC3 Atmos.mkv, Size: 5891564750, Expires: 2022-09-29T12:05:23+02:00)
- eebf3f37-a452-4d51-ba9e-21e8f786bebb (A Cure for Wellness (2017) 1080p DTS.mkv, Size: 7191004798, Expires: 2022-09-29T12:05:35+02:00)
```

*   ❌ `ocis storage-users uploads clean`:

```shell
Cleaned uploads:
tg@odroidhc4:~/ocis$
```

uploads is not cleaned:

```shell
tg@odroidhc4:~/ocis$ ll /data/ocisdata/storage/users/uploads/
total 14139120
drwx------ 2 tg tg       4096 Sep 28 12:23 ./
drwx------ 5 tg tg       4096 Sep 26 14:48 ../
-rw-rw-r-- 1 tg tg 2180592896 Sep 28 12:04 4fc553f2-5bef-4530-9e39-324192c11732
-rw-rw-r-- 1 tg tg        810 Sep 28 12:04 4fc553f2-5bef-4530-9e39-324192c11732.info
-rw-rw-r-- 1 tg tg 2524936448 Sep 28 12:04 643b98e5-aca9-45b0-91c8-c2f7ae47b9ef
-rw-rw-r-- 1 tg tg        783 Sep 28 12:04 643b98e5-aca9-45b0-91c8-c2f7ae47b9ef.info
-rw-rw-r-- 1 tg tg 1147789312 Sep 28 12:10 9fdb7c60-e3f5-46b0-b9be-e862f70ad963
-rw-rw-r-- 1 tg tg        778 Sep 28 12:10 9fdb7c60-e3f5-46b0-b9be-e862f70ad963.info
-rw-rw-r-- 1 tg tg  253411840 Sep 28 11:54 a94ea515-0cd7-4af2-b9a3-745874f0e641
-rw-rw-r-- 1 tg tg        742 Sep 28 11:54 a94ea515-0cd7-4af2-b9a3-745874f0e641.info
-rw-rw-r-- 1 tg tg 4502818816 Sep 28 12:07 da8134df-e136-40fb-8301-8c3da5df84cd
-rw-rw-r-- 1 tg tg        830 Sep 28 12:07 da8134df-e136-40fb-8301-8c3da5df84cd.info
-rw-rw-r-- 1 tg tg 3868848128 Sep 28 12:07 eebf3f37-a452-4d51-ba9e-21e8f786bebb
-rw-rw-r-- 1 tg tg        792 Sep 28 12:07 eebf3f37-a452-4d51-ba9e-21e8f786bebb.info
```

**Comment by micbar** [comment]
@tbsbdr @dragotin 
All possible options here were discussed with the team.

### Outcome

- The uploads in the upload folder are valid and could be resumed by the client any time
- We should not "just" delete incomplete uploads 
- We should not "reserve" disk space at the beginning of each upload because
  - This makes denial-of service attacks easier
  - We cannot optimize for the worst case, in many cases (S3NG) the upload folder space gets more free space when another upload finishes successfully
- It is very hard to prevent some free space on the disk because
  - no quota limit is hit
  - the different filesystems could provide not exact values about the remaining space (e.g. butterFS)
- We need to assume that the admin always provides enough memory
- We should always make it a best practise to put the data folder on a different partition than the OS

This needs better documentation, follow up in https://github.com/owncloud/docs-ocis/issues/248

**Comment by michaelstingl** [comment]
> * The uploads in the upload folder are valid and could be resumed by the client any time
> * We should not "just" delete incomplete uploads

oC10 cleans unfinished uploads/chunks after 24h
