### ISSUE TITLE
Global search doesn't work correctly sometimes

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#4517]
## Describe the bug

Global search doesn't work correctly 

## Steps to reproduce

1. As einstein create folders
```
      folder       
      new-folder   
      FolDer       
      folderPublic 
      test         
```
2. Search for `folder`

## Expected behavior
Only folders with `folder` in their name should be displayed

## Actual behavior
Test is also displayed
![Screenshot from 2022-09-05 16-20-52](https://user-images.githubusercontent.com/41103328/188541540-eea33e2f-5b27-42ca-81b1-ad245d0fb0f1.png)

This is another case where `files` is also displayed
![afterreload](https://user-images.githubusercontent.com/41103328/188541566-6f8459f7-abaa-4b26-affb-94b2a5496e60.png)

## Setup
OCIS: latest master

**Comment by ScharfViktor** [comment]
re-tested on fresh master. I couldn't reproduce this. 
![Screenshot 2022-10-06 at 10 26 12](https://user-images.githubusercontent.com/84779829/194262779-086a0369-a707-4444-bd90-43bd69943326.png)

**Comment by SwikritiT** [comment]
> re-tested on fresh master. I couldn't reproduce this. ![Screenshot 2022-10-06 at 10 26 12](https://user-images.githubusercontent.com/84779829/194262779-086a0369-a707-4444-bd90-43bd69943326.png)

I'll try again and close this if I can't reproduce it either

**Comment by SwikritiT** [comment]
Not reproducible in the current master. I am closing this as fixed.
