### ISSUE TITLE
[Spaces] Add webUrl to Spaces endpoint

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#4523]
## Is your feature request related to a problem? Please describe.

Client users need an easy way to open the root of a Space in the web browser. Then they can perform management tasks, that are not available in the clients itself.

## Describe the solution you'd like

Add webUrl to Spaces endpoint

## Describe alternatives you've considered

I thought about QuickLink creation, but not every user has the permission to do so.

## Additional context

![188572875-3e531a56-49f0-4ee0-8280-50fcba60f78a](https://user-images.githubusercontent.com/214010/188631422-4444e5fd-779e-4600-ab2d-07a826103185.png)

(from https://github.com/owncloud/client/pull/10079#issuecomment-1237761189)

@micbar @fmoc @TheOneRing

**Comment by fmoc** [comment]
The drives Graph API endpoint already provides `webUrl`, but the strings are just empty. The server just needs to fill in the right URL to show them in the browser. Then, the client should be able to enable these buttons.
