### ISSUE TITLE
Develop a Device Management App

### ISSUE THREAD

**Issue by macrodisplays** [owncloud/ocis#4554]
## Is your feature request related to a problem? Please describe.
I want to manage all client devices.

## Describe the solution you'd like
It is better to to have new App which is used to  manage all client devices which have already installed the owncloud client apps.

## Additional context
nextcloud have such client management app.

**Comment by micbar** [comment]
1) this is part of the IDM solution.

In the ocis single binary, we ship LibreIDM as a very small Identity Management System.

2) oCIS only supports OpenIDConnect.
All common OIDC providers (keycloak, authentik, Azure..) have this feature built in.
