### ISSUE TITLE
`x-oc-mtime` header is not being respected in tus requests

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#4559]
## Describe the bug

https://github.com/owncloud/web/pull/7630 includes the `x-oc-mtime` header in XHR and tus upload requests. While XHR works fine, it seems that the header has no effect for tus requests.

## Steps to reproduce

1. Get Web running with current master
2. Upload a file that has been modified a few days ago

## Expected behavior
The "modified column" should show the proper modified date.

## Actual behavior
It shows "0 seconds ago".

**Comment by micbar** [comment]
@JammingBen 

From my POV i see no  `x-oc-mtime` header sent by the web client during tus uploads. I see a big combined header with `upload metadata`

**Comment by JammingBen** [comment]
@micbar Are you sure you have Web with current master running? The `x-oc-mtime` header should be available. Or does oCIS expect it to be received otherwise, maybe somehow included in `Upload-Metadata`?

![image](https://user-images.githubusercontent.com/50302941/190101589-d7d108a2-b86e-4359-86a0-5066be5704ea.png)

**Comment by micbar** [comment]
As far as I read the code, a non-tus request works with the `x-oc-mtime` header and tus requests expect the mtime in the upload metadata.

@JammingBen Happy to check that out together with you

**Comment by JammingBen** [comment]
> tus requests expect the mtime in the upload metadata.

Ahh I didn't know this. Let me try it out, I'll come back to you 👍

**Comment by JammingBen** [comment]
Yessss, adding `mtime` in upload metadata solved it, thanks!
