### ISSUE TITLE
Resolve undefined step for ocis `localAPITests`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#4563]
### Description
Seems like we have got some undefined or unimplemented steps on ocis for the step below. Find the step and resolve the undefined step. Also investigate why drone is not responding for undefined step.

Build Link : https://drone.owncloud.com/owncloud/ocis/15382/41/7

```console
382 scenarios (372 passed, 4 failed, 6 undefined)
4017 steps (3998 passed, 4 failed, 6 undefined, 9 skipped)
16m39.97s (21.22Mb)

--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @Then as user :arg1 file :arg2 inside space :arg3 should contain a property :arg4 with value :arg5
     */
    public function asUserFileInsideSpaceShouldContainAPropertyWithValue($arg1, $arg2, $arg3, $arg4, $arg5)
    {
        throw new PendingException();
    }

    /**
     * @Then as user :arg1 folder :arg2 inside space :arg3 should contain a property :arg4 with value :arg5
     */
    public function asUserFolderInsideSpaceShouldContainAPropertyWithValue($arg1, $arg2, $arg3, $arg4, $arg5)
    {
        throw new PendingException();
    }```

**Comment by SagarGi** [comment]
@phil-davis  Upon debugging, the main problem why drone is not responding is due to expected to failure linting on `ocis`. Though the undefined steps makes the exit code `1` but the error for the not shown in the console for the undefined step and upon linting the expected to failure the it makes exit code `0` (success). May be a refactor to `run.sh` is required to make it work for the undefined step on `ocis`

**Comment by phil-davis** [comment]
> May be a refactor

Yes, we need to somehow detect if the Behat run had any undefined steps. If so, then fail the pipeline straight away - do not bother trying to check expected-failures etc.

**Comment by amrita-shrestha** [comment]
both pr has been merged so closing
