### ISSUE TITLE
WOPI / Office collaboration with one view-only collaborator

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4570]
## Describe the bug

OnlyOffice and Collabora differ in their behavior when it comes to collaboration sessions with one view-only collaborator 

## Steps to reproduce

1. Create a document
2. share it with another user with read only permissions
3. open the document as sharee
4. open the document as share receiver

## Expected behavior
When the sharee edits the document, the share receiver will see the changes in real time.

## Actual behavior
This is only valid for Collabora. In OnlyOffice the share receiver will not see any changes, even with a reload.

## Setup

oCIS with WOPI deployment example.

## Additional context
Maybe this is not implemented by OnlyOffice - we need to check. Maybe we need

**Comment by micbar** [comment]
@tbsbdr @hodyroff This would be interesting to discuss with OnlyOffice.

Is our expected behavior correct? Collabora handles it differently.

Product Question.

**Comment by wkloucek** [comment]
Maybe this is dependent on the `UserCanAttend` property from the CheckFileInfo response?? https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/files/checkfileinfo/checkfileinfo-response#usercanattend

**Comment by wkloucek** [comment]
@dj4oC maybe something to discuss with OnlyOffice

**Comment by wkloucek** [comment]
Closing here since nobody ever responded here
