### ISSUE TITLE
Notification service env variable update needed

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4589]
As discussed with @kobergj 

* The `NOTIFICATIONS_SMTP_INSECURE` is not clear because `NOTIFICATIONS_SMTP_ENCRYPTION` already contains the item `none`.
* `NOTIFICATIONS_SMTP_SENDER` has as default `owncloud` and as text: `Sender address of emails that will be sent.` --> A sender address, at least for me, is in form `owncloud@example.com`. It could be that this is the senders name. In any case either the default or the description may need an update

**Comment by mmattel** [comment]
Got it:

* Proposal:
`Allow insecure connections to the SMTP server.` -->
`Allow insecure connections to the SMTP server, like for self signed certificates.`
* We have an issue in the transformation to adoc tables, because `ownCloud <noreply@example.com>` does get rendered as `owncloud` (without the email address)

I will look for the latter on monday. It is hard to work in the train right now, internet breaks often.

**Comment by dragonchaser** [comment]
IMHO `Allow insecure connections to the SMTP server.` implicates certificate related settings for me, there is no need for additional description.

**Comment by mmattel** [comment]
not stale

**Comment by kobergj** [comment]
@mmattel can this be closed now since we have https://github.com/owncloud/ocis/issues/4607 ? Or is there something else to do with this ticket?

**Comment by mmattel** [comment]
Can be closed since we have https://github.com/owncloud/ocis/issues/4607
