### ISSUE TITLE
enable more trashbin tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#459]
try to enable tests
- [ ] https://github.com/owncloud/ocis-reva/issues/112
- [ ] https://github.com/owncloud/ocis-reva/issues/118
- [ ] https://github.com/owncloud/ocis-reva/issues/52

**Comment by individual-it** [comment]
looks like the API tests are all enabled and listed in the expected failures files.
the webUI tests that are skipped mainly fail because of https://github.com/owncloud/product/issues/186 https://github.com/owncloud/product/issues/188 & https://github.com/owncloud/ocis-reva/issues/111

**Comment by Talank** [comment]
All the skipped tests still fail and none can be enabled. The main reason for failure is as said by @individual-it in the above comment.
