### ISSUE TITLE
Preparation before GA. Test documentation. 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4595]
We have [Beta test plan](https://owncloud.dev/ocis/development/beta-testplan) where we suggest to user setup ocis different deployment methods using [documentation](https://doc.owncloud.com/ocis/next/)

documentation offered by internal users in GA phase and we need to check documentation before GA. 

## setup ocis with different deployment methods: 

- [x] binary-setup https://doc.owncloud.com/ocis/next/deployment/binary/binary-setup.html @bishwasojha
- [x] container setup https://doc.owncloud.com/ocis/next/deployment/container/container-setup.html @ScharfViktor 
- [x] Container Orchestration: 
- - [x] [docker-compose] (https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#docker-compose) @ScharfViktor 
- - [x] [kubernetes](https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes-and-helm) @saw-jan 
- - [x] [helm](https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes-and-helm) @saw-jan (https://github.com/owncloud/docs-ocis/pull/245)

## different identity managers
- [x] [idm](https://doc.owncloud.com/ocis/next/deployment/services/idm.html) @ScharfViktor 
- [x] [ldap](https://owncloud.dev/ocis/deployment/ocis_ldap/) @kiranparajuli589 

## different storage systems
- [x] [nfs](https://owncloud.dev/ocis/storage-backends/dcfsnfs/) @SwikritiT  
- - [x] https://github.com/owncloud/ocis/pull/4708
- - [x] https://github.com/owncloud/docs-ocis/pull/247
- [x] [s3](https://owncloud.dev/ocis/deployment/ocis_s3/) @SwikritiT 
- - [x] https://github.com/owncloud/ocis/pull/4709

**Comment by ScharfViktor** [comment]
@individual-it

**Comment by kiranparajuli589** [comment]
### different identity managers
##### LDAP (https://owncloud.dev/ocis/deployment/ocis_ldap/)
oCIS gets stuck in the log-in loop.

**Steps:**
- Server: `Ubuntu 22.04.1 LTS`
- 4 Domains were set up as mentioned in the docs
  ```
  # /etc/hosts
  127.0.0.1 cloud.owncloud.test
  127.0.0.1 keycloak.owncloud.test
  127.0.0.1 ldap.owncloud.test
  127.0.0.1 traefik.owncloud.test
  ```
- cloned oCIS & cd to `ocis/deployment/examples/ocis_ldap`
- `.env` file updated as [content of `.env` file](https://gist.github.com/kiranparajuli589/ae4846cf7c55df29a7b31aa56c9c39df 'See content of the .env file')
- `docker compose up`

**Results:**
- LDAP up and running @ https://ldap.owncloud.test
- oCIS up and running @ https://traefik.owncloud.test
- traefik up and running @ https://cloud.owncloud.test

- trying to login with a non-existant user or wrong pass in oCIS, the login is blocked :+1: 
- but, while trying to log in with a valid user/pass, the UI loops as this:
[Screencast from 29-9-22 12:06:27 अपराह्न +0545.webm](https://user-images.githubusercontent.com/39373750/192954473-c83ccc50-a472-44be-a4fd-5569ca3634c1.webm)
  oCIS logs on this behaviour is as:
  ``` console
  ocis_ldap-ocis-1          | {"level":"error","service":"proxy","error":"Get \"https://cloud.owncloud.test/.well-known/openid-configuration\": x509: certificate is valid for d0a21b5faa31b24a9728fbe427fbfd2d.10b658a96e74f7df7b30daef0b94e110.traefik.default, not cloud.owncloud.test","time":"2022-09-29T06:19:31.874905028Z","message":"could not initialize oidcAuth provider"}
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 fd=13 ACCEPT from IP=172.22.0.5:57584 (IP=0.0.0.0:389)
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=0 BIND dn="cn=admin,dc=owncloud,dc=com" method=128
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=0 BIND dn="cn=admin,dc=owncloud,dc=com" mech=SIMPLE ssf=0
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=0 RESULT tag=97 err=0 text=
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=1 SRCH base="uid=admin,ou=users,dc=owncloud,dc=com" scope=0 deref=0 filter="(&(objectClass=ownCloud)(objectClass=inetOrgPerson))"
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=1 SRCH attr=dn mail displayName sn givenName ownclouduuid binary uid
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
  ocis_ldap-ldap-server-1   | 633538f3 conn=1532 fd=13 closed (connection lost)
  ```

- while trying to play with LDAP CLI following things were noticed
  - outside the container (TLS connection fails):
    ```console
    ❯ ldapsearch -x -b dc=owncloud,dc=com -H ldaps://localhost
    ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
    ```
    but insecure connection succeded,
    ```
    ❯ ldapsearch -x -b dc=owncloud,dc=com -H ldap://localhost
    # extended LDIF
    #
    # LDAPv3
    # base <dc=owncloud,dc=com> with scope subtree
    # filter: (objectclass=*)
    # requesting: ALL
    #
    
    # search result
    search: 2
    result: 32 No such object
    
    # numResponses: 1

    ```
  - inside the container (both TLS & insecure connection works):
    ```console
    # ldapsearch -x -b dc=owncloud,dc=com -H ldaps://localhost
    # extended LDIF
    #
    # LDAPv3
    # base <dc=owncloud,dc=com> with scope subtree
    # filter: (objectclass=*)
    # requesting: ALL
    #
    
    # search result
    search: 2
    result: 32 No such object
    
    # numResponses: 1
    ```

**Summary**:
The actual login request exits with `200` then, the oCIS tries to fetch the user information from the `cloud/v1/users` endpoint which then fails with status `401`. The TLS connection between oCIS and ldap server may be the not working properly here.

cc @wkloucek @rhafer @saw-jan @SwikritiT

**Comment by SwikritiT** [comment]
> ### different identity managers
> #### For LDAP (https://owncloud.dev/ocis/deployment/ocis_ldap/) docs
> oCIS gets stuck in the log-in loop.
> 
> **Steps:**
> 
> * Server: `Ubuntu 22.04.1 LTS`
> * 4 domains were set up as mentioned in the docs
>   ```
>   # /etc/hosts
>   127.0.0.1 cloud.owncloud.test
>   127.0.0.1 keycloak.owncloud.test
>   127.0.0.1 ldap.owncloud.test
>   127.0.0.1 traefik.owncloud.test
>   ```
> * cloned oCIS & cd to `ocis/deployment/examples/ocis_ldap`
> * `.env` file updated as [content of `.env` file](https://gist.github.com/kiranparajuli589/ae4846cf7c55df29a7b31aa56c9c39df)
> * `docker compose up`
> 
> **Results:**
> 
> * LDAP up and running @ https://ldap.owncloud.test
> * oCIS up and running @ https://traefik.owncloud.test
> * traefik up and running @ https://cloud.owncloud.test
> * trying to login with a non-existant user or wrong pass in oCIS, the login is blocked +1
> * but, while trying to log in with a valid user/pass, the UI loops as this:
>   [Screencast from 29-9-22 12:06:27 अपराह्न +0545.webm](https://user-images.githubusercontent.com/39373750/192954473-c83ccc50-a472-44be-a4fd-5569ca3634c1.webm)
>   oCIS logs on this behaviour is as:
>   ```
>   ocis_ldap-ocis-1          | {"level":"error","service":"proxy","error":"Get \"https://cloud.owncloud.test/.well-known/openid-configuration\": x509: certificate is valid for d0a21b5faa31b24a9728fbe427fbfd2d.10b658a96e74f7df7b30daef0b94e110.traefik.default, not cloud.owncloud.test","time":"2022-09-29T06:19:31.874905028Z","message":"could not initialize oidcAuth provider"}
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 fd=13 ACCEPT from IP=172.22.0.5:57584 (IP=0.0.0.0:389)
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=0 BIND dn="cn=admin,dc=owncloud,dc=com" method=128
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=0 BIND dn="cn=admin,dc=owncloud,dc=com" mech=SIMPLE ssf=0
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=0 RESULT tag=97 err=0 text=
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=1 SRCH base="uid=admin,ou=users,dc=owncloud,dc=com" scope=0 deref=0 filter="(&(objectClass=ownCloud)(objectClass=inetOrgPerson))"
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=1 SRCH attr=dn mail displayName sn givenName ownclouduuid binary uid
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
>   ocis_ldap-ldap-server-1   | 633538f3 conn=1532 fd=13 closed (connection lost)
>   ```
> * while trying to play with LDAP CLI following things were noticed
>   
>   * outside the container (TLS connection fails):
>     ```
>     ❯ ldapsearch -x -b dc=owncloud,dc=com -H ldaps://localhost
>     ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
>     ```
>     
>     
>         
>           
>         
>     
>           
>         
>     
>         
>       
>     but insecure connection succeded,
>     ```
>     ❯ ldapsearch -x -b dc=owncloud,dc=com -H ldap://localhost
>     # extended LDIF
>     #
>     # LDAPv3
>     # base <dc=owncloud,dc=com> with scope subtree
>     # filter: (objectclass=*)
>     # requesting: ALL
>     #
>     
>     # search result
>     search: 2
>     result: 32 No such object
>     
>     # numResponses: 1
>     ```
>   * inside the container (both TLS & insecure connection works):
>     ```
>     # ldapsearch -x -b dc=owncloud,dc=com -H ldaps://localhost
>     # extended LDIF
>     #
>     # LDAPv3
>     # base <dc=owncloud,dc=com> with scope subtree
>     # filter: (objectclass=*)
>     # requesting: ALL
>     #
>     
>     # search result
>     search: 2
>     result: 32 No such object
>     
>     # numResponses: 1
>     ```
> 
> **Summary**: The actual login request exits with `200` then, the oCIS tries to fetch the user information from the `cloud/v1/users` endpoint which then fails with status `401`. The TLS connection between oCIS and ldap server may be the not working properly here.
> 
> cc @wkloucek @rhafer @saw-jan @SwikritiT @ScharfViktor

Facing a similar problem while trying to test this documentation https://owncloud.dev/ocis/deployment/ocis_s3/

**Comment by ScharfViktor** [comment]
container setup:
env: mac m1, macOs Monterey v.12.3.1. 

`docker run --rm -it \
    --mount type=bind,source=$PWD/ocis/ocis-config,target=/etc/ocis \
    owncloud/ocis init` doesn't work if you run `sudo chown -Rfv 1000:1000 $PWD/ocis/`





after starting ocis 
```
docker run \
    --name ocis_runtime \
    --rm \
    -it \
    -p 9200:9200 \
    --mount type=bind,source=$PWD/ocis/ocis-config,target=/etc/ocis \
    --mount type=bind,source=$PWD/ocis/ocis-data,target=/var/lib/ocis \
    -e OCIS_INSECURE=true \
    -e PROXY_HTTP_ADDR=0.0.0.0:9200 \
    -e OCIS_URL=https://<your-hostname>:9200 \
    owncloud/ocis
```

Logging in is not possible:
`{\"id\":\"com.owncloud.api.settings\",\"code\":502,\"detail\":\"circuit breaker is open\",\"status\":\"Bad Gateway\"}","time":"2022-09-29T08:52:41.892291347Z","message":"Could not load roles"}`

https://user-images.githubusercontent.com/84779829/192990296-b5e1bdb4-f2cb-4028-8328-d5a6e01c123e.mov

**Comment by rhafer** [comment]
@kiranparajuli589 

> **Steps:**
> 
>     * Server: `Ubuntu 22.04.1 LTS`
> 
>     * 4 domains were set up as mentioned in the docs
>       ```
>       # /etc/hosts
>       127.0.0.1 cloud.owncloud.test
>       127.0.0.1 keycloak.owncloud.test
>       127.0.0.1 ldap.owncloud.test
>       127.0.0.1 traefik.owncloud.test
>       ```
> 
>     * cloned oCIS & cd to `ocis/deployment/examples/ocis_ldap`
> 
>     * `.env` file updated as [content of `.env` file](https://gist.github.com/kiranparajuli589/ae4846cf7c55df29a7b31aa56c9c39df)

You have `INSECURE=false` but are using traefik's default self-sign certificate. This can't work. That is basically what the error log is trying to say:

> `ocis_ldap-ocis-1          | {"level":"error","service":"proxy","error":"Get \"https://cloud.owncloud.test/.well-known/openid-configuration\": x509: certificate is valid for d0a21b5faa31b24a9728fbe427fbfd2d.10b658a96e74f7df7b30daef0b94e110.traefik.default, not cloud.owncloud.test","time":"2022-09-29T06:19:31.874905028Z","message":"could not initialize oidcAuth provider"}`

The proxy is trying to open an TLS connection to the idp, but can't verify the certificate because the hostname is not matching. The solution is to either get proper certificates, or run with insecure enabled.

**Comment by kiranparajuli589** [comment]
@rhafer, thx. now I understand the error message.

But, According to the [documentation],

> You are installing oCIS on a server and Traefik will obtain valid certificates for you so please remove INSECURE=true or set it to false.

For this, do you suggest we test with `INSECURE=true`?
Also, If we want to get proper certificates, can you please suggest to us how to find/build one?

**Comment by micbar** [comment]
@kiranparajuli589 Traefik can obtain proper certificates, but only if you run ocis on a publicly reachable domain.

Traefik can generate LetsEncrypt Certs. LetsEncrypt does an ACME Challenge via a `.well-known` path on the public domain. That doesn't work if you run the docker-compose example locally.

**Comment by kiranparajuli589** [comment]
@rhafer @micbar thx for the clarifications.
tried with `INSECURE: true` and everything works fine (since we were testing locally).

p.s. testing using some server and public domain is not yet tested.

**Comment by SwikritiT** [comment]
> @rhafer @micbar thx for the clarifications. tried with `INSECURE: true` and everything works fine (since we were testing locally).
> 
> p.s. using some server and public domain is not yet tested.

Same for S3 storage

**Comment by saw-jan** [comment]
While trying oCIS deployment in Kubernetes with helm chart, there were some commands and config changes required which are proposed in PR https://github.com/owncloud/docs-ocis/pull/245

**Comment by SwikritiT** [comment]
@ScharfViktor Every checklist in this issue have been checked, maybe we can close this now?
