### ISSUE TITLE
Directory listing fails when filenames contain ampersand

### ISSUE THREAD

**Issue by willmackay** [owncloud/ocis#4612]
## Describe the bug

If a directory contains filenames with an ampersand, the Owncloud web page does not display any files in that directory. Instead, it says "Resource not found". This happens when an existing file is renamed to include an ampersand, or when you upload a folder containing files that already have an ampersand.

## Steps to reproduce

1. Upload file with ampersand in name, or rename existing file to add an ampersand
2. Refresh directory listing

## Expected behavior
Directory listing should show new or changed file with ampersand in filename.

## Actual behavior
"Resource not found" error and no files in directory display.

## Setup

I run OCIS behind Nginx on a VM. There is no container.

This is my /etc/ocis/ocis.env file:
```
PROXY_HTTP_ADDR=127.0.0.1:9200
OCIS_URL=https://ocis.alyrica.net
OCIS_BASE_DATA_PATH=/var/lib/ocis
OCIS_LOG_PRETTY=true

```
This is my systemd service file:
```
[Unit]
Description=OCIS server
After=network.target

[Service]
Type=simple
User=ocis
Group=ocis
EnvironmentFile=/etc/ocis/ocis.env
ExecStart=ocis server
Restart=always
LimitNOFILE=100000

[Install]
WantedBy=multi-user.target
```

## Additional context
Please see attached screenshots.
![1  Before rename](https://user-images.githubusercontent.com/24301649/191099151-13f874d5-ec0d-452a-8417-cb36b6d3cc51.png)
![2  Renamed but before refreshing](https://user-images.githubusercontent.com/24301649/191099160-8df94ef6-cc65-4ecb-b988-6adeb506c136.png)
![3  After refreshing](https://user-images.githubusercontent.com/24301649/191099169-c5d1f0ff-d06d-4e11-80e6-78bdd449102e.png)

**Comment by SwikritiT** [comment]
similar issue here https://github.com/owncloud/ocis/issues/4474

**Comment by phil-davis** [comment]
Duplicate - closing here. Thanks for reporting.

**Comment by kulmann** [comment]
@willmackay please subscribe to https://github.com/owncloud/ocis/issues/4474 if you want to get notified when the bug is fixed. :-)  Thanks again for your detailed report, much appreciated!
