### ISSUE TITLE
Debuggable setup with WOPI and Collabora/OnlyOffice

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#4617]
## Is your feature request related to a problem? Please describe.
Every time I have to debug something with Collabora/OnlyOffice I spend the majority of the time with preparing a debuggable setup.

## Describe the solution you'd like
I would like a copy/paste documentation or a script which provides this setup.

## Describe alternatives you've considered
No alternative.

## Additional context
We have this [example docker deployment](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_wopi) but in that setup I can't start a debugger or record the execution using [rr](https://rr-project.org/).

**Comment by micbar** [comment]
The new ocis_full example can be used as debuggable setup, using the `make debug-docker` to create an ocis container with delve.
