### ISSUE TITLE
"Open in browser" does not open a browser

### ISSUE THREAD

**Issue by algihu** [owncloud/ocis#4618]
## Describe the bug

Using the Windows desktop app pointed to an OCIS instance, when I right-click on a synced file in Windows Explorer and select "Open in browser" nothing happens. No error is shown but also nothing is opened at all.

## Steps to reproduce

1. Set up ownCloud Desktop App (Windows) pointed to an OCIS server
2. In Windows Explorer navigate to any file in ownCloud and right-click on it
3. In the context menu, select ownCloud-->Open in browser

## Expected behavior
My browser should open to the ownCloud portal

## Actual behavior
Nothing seems to happen at all.

![Open in browser](https://user-images.githubusercontent.com/111002145/191362770-fb858857-22fa-44d3-a093-8eadca4e107d.gif)
## Setup

Installed/Started OCIS 2.0.0-beta.8 using the quick start guide here: https://doc.owncloud.com/ocis/next/quickguide/quickguide.html

Installed ownCloud Desktop App 2.11.1 (build 8438) and configured it to sync as virtual files to my OCIS instance.

Added some files via Windows explorer and waited for them to sync.

I am using a Windows 10 machine with multiple browsers installed (Edge, Chrome, Firefox) with Edge set as the default.

**Comment by micbar** [comment]
@algihu Thanks for the bug report.

This feature is not implemented yet on the ocis Server Side, and the web client

We will support this with the new Desktop Client 3.0.0 and the ocis 2.0.0-rc1

Please see https://github.com/owncloud/web/issues/7304 and https://github.com/owncloud/web/issues/6247 for progress
