### ISSUE TITLE
Allow public link sharing only for certain groups feature not implemented

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#4623]
### Description

We have scenarios in core like 
```
Scenario: users not present in public share shares groups cannot create a new public link share
    Given parameter "public_share_sharers_groups_allowlist_enabled" of app "files_sharing" has been set to "yes"
    And parameter "public_share_sharers_groups_allowlist" of app "files_sharing" has been set to '["grp1"]'
    When user "Alice" creates a public link share using the sharing API with settings
      | path | fileToShare.txt |
    Then the OCS status code should be "403"
    And the HTTP status code should be "200"
    And the OCS status message should be "Public link creation is only possible for certain groups"
```

Where we use occ command to enable `public_share_sharers_groups_allowlist_enabled`  but apparently on `ocis` this could not be possible. There are tests scenarios that are expected to failure file because we cannot set with command. So just need the confirmation or information regarding it if it will be implemented, otherwise we could add tags and remove them from expected to failure.

**Comment by SagarGi** [comment]
@phil-davis @micbar if you could give some details regarding it?

**Comment by phil-davis** [comment]
This is an example of one of many options available in oC10 that control certain things that users can or cannot do. oCIS does not have any option like this. I think that there is an issue somewhere that mentions lots of these oC10 sharing options - and AFAIK there will be future decisions about which options might be implemented the same in oCIS, which will have a similar but slightly different implementation, and which will not be implemented in oCIS.

i will look for the issue...

**Comment by phil-davis** [comment]
It is issue #1328 - https://github.com/owncloud/ocis/issues/1328#issuecomment-1190046452
"Will be implemented on spaces, not per instance." - @micbar I suppose that this optional setting `public_share_sharers_groups_allowlist_enabled`, if implemented on oCIS, would also not be a system-wide setting?

**Comment by individual-it** [comment]
according to @micbar this will be most likely implemented per space, so these kind of tests will not be applicable this way in ocis, so they should be tagged with `@notToImplementOnOcis`

**Comment by amrita-shrestha** [comment]
currently, this test has been skipped for ocis. After the feature has been added to ocis QA team can add testcases.

**Comment by SwikritiT** [comment]
What I got from this discussion is that these settings will be implemented in ocis but not as they are currently in core and the relates tests have been skipped (or probably removed after the latest moving of tests from core to ocis). When the new feature is added maybe we will have a new issue to write tests on them. 

Maybe this issue can be closed? or any other reason we should have it open?

cc: @phil-davis @individual-it @amrita-shrestha

**Comment by phil-davis** [comment]
@SwikritiT correct - when a similar feature is implemented for ocis, then QA team and the developers can create test scenarios for the feature.

We should remove any existing test scenarios related to this issue from the ocis acceptance test suite(s). If that has already been done, then close this issue.

**Comment by SwikritiT** [comment]
TODO QA Team:-
- [ ] search if there are any tests related to this issue, if yes remove them  from the ocis acceptance test suite
- [ ] close the issue

**Comment by PrajwolAmatya** [comment]
The steps related to occ commands have been removed, so closing this issue.
