### ISSUE TITLE
[QA] Login to beta9 fails runtime error: invalid memory

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#463]
Reproduce on ocis 1.0.0-beta9 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

*  try log in user einstein with firefox

The user sees
![image](https://user-images.githubusercontent.com/1108546/90604819-b8b3fb80-e1fd-11ea-87e4-2594340cbc68.png)

the docker-compose logs say
```
ocis          | 2020-08-19 07:20:28.277868 I | http: panic serving 2.247.254.67:39256: runtime error: invalid memory address or nil pointer dereference
ocis          | goroutine 286 [running]:
ocis          | net/http.(*conn).serve.func1(0xc000b2c500)
ocis          |         /usr/local/go/src/net/http/server.go:1772 +0x139
ocis          | panic(0x2be7200, 0x4837f50)
ocis          |         /usr/local/go/src/runtime/panic.go:975 +0x3e3
ocis          | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x34a3ae0, 0xc0005312c0, 0x344a620, 0xc00010fb00, 0x0, 0x0, 0x0)
ocis          |         /root/go/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x5e
ocis          | github.com/owncloud/ocis-proxy/pkg/middleware.OpenIDConnect.func1.1(0x3496da0, 0xc000b81180, 0xc000b28800)
ocis          |         /root/go/pkg/mod/github.com/owncloud/ocis-proxy@v0.6.0/pkg/middleware/openidconnect.go:75 +0x24d
ocis          | net/http.HandlerFunc.ServeHTTP(0xc00056aea0, 0x3496da0, 0xc000b81180, 0xc000b28800)
ocis          |         /usr/local/go/src/net/http/server.go:2012 +0x44
ocis          | github.com/owncloud/ocis-proxy/pkg/middleware.RedirectToHTTPS.func1(0x3496da0, 0xc000b81180, 0xc000b28800)
ocis          |         /root/go/pkg/mod/github.com/owncloud/ocis-proxy@v0.6.0/pkg/middleware/https_redirect.go:17 +0x1af
ocis          | net/http.HandlerFunc.ServeHTTP(0xc0005b62c0, 0x3496da0, 0xc000b81180, 0xc000b28800)
ocis          |         /usr/local/go/src/net/http/server.go:2012 +0x44
ocis          | net/http.serverHandler.ServeHTTP(0xc000b80000, 0x3496da0, 0xc000b81180, 0xc000b28800)
ocis          |         /usr/local/go/src/net/http/server.go:2807 +0xa3
ocis          | net/http.(*conn).serve(0xc000b2c500, 0x34a3a20, 0xc000036b00)
ocis          |         /usr/local/go/src/net/http/server.go:1895 +0x86c
ocis          | created by net/http.(*Server).Serve
ocis          |         /usr/local/go/src/net/http/server.go:2933 +0x35c
ocis          | 2020-08-19T07:20:28Z DBG  bytes=836895 duration=0.820707 method=GET path=/apps/pdf-viewer/a8f3ddea23560dc6624f.worker.js proto=HTTP/1.1 request=1e1e43d5-8d3f-447b-a187-22256ba00770 service=phoenix status=200
```

Expected behaviour: login worked with beta8.

Note that this is the first time for me to try beta9. Are changes needed to in the docker-compose setup?

**Comment by phil-davis** [comment]
@individual-it made some changes last night to a docker-compose that we are using for some performance testing.
https://github.com/owncloud-docker/compose-playground/pull/44
That fixed my problem with logging in to `einstein`

I guess something similar might be needed for whatever docker-compose that you are using.

**Comment by jnweiger** [comment]
Explosions with invalid memory or nil pointer dereference are a bug in the code.
Regardless of how the setup is done, the code should do proper memory management.This needs fixing.
Having that said, not triggering the explosion by running things differently is -- of course - also a good thing for now. :-)

I am not using my own docker-compose. I try to stick to the official one. Otherwise I'd be afraid that my findings would be mostly invalid.
The docker-compose is the one from https://github.com/owncloud/ocis/ and I apply the official instructions from https://owncloud.github.io/ocis/eos/#docker-dev-environment-for-eos-storage to it.
The instructions don't say which repo or docker-compose should be used. The ocis repo is my assumption. Please confirm.

The docker-compose.yml files in https://github.com/owncloud-docker/compose-playground/blob/master/examples/benchmark/ocis/docker-compose.yml and https://github.com/owncloud/ocis/blob/master/docker-compose.yml differ substantially.

benchmark uses `image: owncloud/ocis:latest`
ocis uses: `image: owncloud/eos-ocis-dev:latest`

benchmark does not work with eos. Does it?

**Comment by phil-davis** [comment]
benchmark is not with EOS. benchmark is using the `owncloud/ocis:latest` that gets updated automagically when code is merged to `owncloud/ocis` GitHub repo.

I gave the benchmark docker-compose.yml as an example because it is working right now, and might give a hint to someone about what to do.

**Comment by jnweiger** [comment]
@thanks. The patch from https://github.com/owncloud-docker/compose-playground/pull/44 fixes the docker-compose for me too!

**Comment by jnweiger** [comment]
While retesting with only one or both of these changes, I get inconsistent results: sometimes, even when having both, login crashes with this nil pointer. :-(

**Comment by jnweiger** [comment]
> While retesting with only one or both of these changes, I get inconsistent results: sometimes, even when having both, login crashes with this nil pointer. :-(

- the system was in an inconsitent state. Multiple compose down/up, cookies invalid, sessons timed out, ... -
- retesting with a fresh system: `KONNECTD_TLS: 1` is not needed.

**Comment by butonic** [comment]
should be fixed now that https://github.com/owncloud/ocis/pull/484 is merged. reopen if problem persists

**Comment by jnweiger** [comment]
## retested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

Fixed. No login errors seen with RC1.
