### ISSUE TITLE
A public share with viewer role can still edit office documents in OnlyOffice/Collabora

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#4632]
## Steps to reproduce

1. Publicly share an office file with the viewer role
2. Open the public share
3. Edit the public share
4. As the sharer, open the shared file
5. See the changes made by the share

## Expected behavior
A share with viewer role should not be able to edit the file

## Actual behavior
A clear and concise description of what happened.
File was changed

**Comment by C0rby** [comment]
@micbar, I guess this is also a blocker, right?

**Comment by micbar** [comment]
Fixed by #4689
