### ISSUE TITLE
Check expected-failures files for invalid and closed issues

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#4635]
A script is now available to check for invalid and closed issues. https://github.com/owncloud/core/pull/40377

Use it to check the expected-failures files in oCIS and reva (master and edge) and fix any problems.

**Comment by amrita-shrestha** [comment]
Reported closed issue in ocis expected failure file:
- [ ] https://github.com/owncloud/ocis/issues/4678
- [ ] https://github.com/owncloud/ocis/issues/4679
- [ ] https://github.com/owncloud/ocis/issues/4680
- [ ] https://github.com/owncloud/ocis/issues/4681
- [ ] https://github.com/owncloud/ocis/issues/4682
- [ ]  https://github.com/owncloud/ocis/issues/4695

**Comment by amrita-shrestha** [comment]
all closed issue in expected failure file has been removed so closing this issue
