### ISSUE TITLE
[Docs] Auto-generate documentation of the config / env variables

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#4668]
## Is your feature request related to a problem? Please describe.

From a discussion with @tbsbdr : 

> Do we have an overview of all OCIS config / env variables? I find it quite tedious to find the right variable names like `OCIS_BASE_DATA_PATH` in the documentation.

## Describe the solution you'd like

Documentation of the config / env variables should be maintained in the source code, and automagically extracted for docs in every pull request. We already do this with the oC10 config.php parameters and for the iOS app MDM and branding parameters:

- https://doc.owncloud.com/server/10.11/admin_manual/configuration/server/config_sample_php_parameters.html
- https://doc.owncloud.com/ios-app/11.10/appendices/mdm.html

## Describe alternatives you've considered

Maintenance without automation just don't scale.

## Additional context

For the iOS app and iOS SDK MDM and branding parameters, we have the compiled app running with GitHub actions:
https://github.com/owncloud/ios-app/blob/master/.github/workflows/configuration-documentation.yml

A [`CONFIGURATION.json`](https://github.com/owncloud/ios-app/blob/master/doc/CONFIGURATION.json) gets created, and a [gomplate template](https://github.com/owncloud/ios-app/blob/master/tools/GenerateDocs/templates/configuration.adoc.tmpl) is used to generate a [`configuration.adoc`](https://github.com/owncloud/ios-app/blob/master/doc/configuration.adoc). It gets then embedded in the [`mdm.adoc`](https://github.com/owncloud/docs-client-ios-app/blob/master/modules/ROOT/pages/appendices/mdm.adoc) page.

/cc @mmattel @d7oc

**Comment by micbar** [comment]
This is already implemented from the very beginning of the project.

The challenge is that we have around 30 services and a lot of settings. We need more hand-crafted and manual documentation about the config options. The list alone, as we have it today is somehow overwhelming.

There are existing tickets for that #3917 #4178 

Closing this here. Please check the other tickets for progress.
