### ISSUE TITLE
Check closed  issue `No share indicators inside share jail` still exist in expected-to-failure

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#4678]
[No share indicators inside share jail ](https://github.com/owncloud/web/issues/6894) issue has been closed but still their are some scenario under this issue.Check why there are scenario under [No share indicators inside share jail ](https://github.com/owncloud/web/issues/6894) closed issue

https://github.com/owncloud/ocis/blob/a67e354eb48b8bafccb07be9eb8b04be909d56c3/tests/acceptance/expected-failures-webUI-on-OCIS-storage.md?plain=1#L37-L46

**Comment by SagarGi** [comment]
### Findings:
For features: 
```
webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:100
webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:121
webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:80
webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:42
webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:61
webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:80
```
These tests tries to open `Shares` that is in root in `oc10` web but in `ocis` no shares folder is there since there is a separate `Shares` jail for it which is why the tests is failing.

Also for features:
```
webUISharingPublicManagement/publicLinkIndicator.feature:64
webUISharingPublicManagement/publicLinkIndicator.feature:80
webUISharingPublicManagement/publicLinkIndicator.feature:98
```
These tests fails because when a user shares a folder to other in `oc10`(if Shares is not created by default) then the shared resources exist in the All files section of UI but in `ocis` it is not possible since it has dedicate place `Shares` jail for shared resources. 

These tests can be skipped on ocis and can be added to implementation on playwright. @SwikritiT @amrita-shrestha ?

**Comment by SwikritiT** [comment]
> ### Findings:
> For features:
> 
> ```
> webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:100
> webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:121
> webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:80
> webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:42
> webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:61
> webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:80
> ```
> 
> These tests tries to open `Shares` that is in root in `oc10` web but in `ocis` no shares folder is there since there is a separate `Shares` jail for it which is why the tests is failing.
> 
> Also for features:
> 
> ```
> webUISharingPublicManagement/publicLinkIndicator.feature:64
> webUISharingPublicManagement/publicLinkIndicator.feature:80
> webUISharingPublicManagement/publicLinkIndicator.feature:98
> ```
> 
> These tests fails because when a user shares a folder to other in `oc10`(if Shares is not created by default) then the shared resources exist in the All files section of UI but in `ocis` it is not possible since it has dedicate place `Shares` jail for shared resources.
> 
> These tests can be skipped on ocis and can be added to implementation on playwright. @SwikritiT @amrita-shrestha ?

Yes skip them as there's never going to be `Shares` folder in Ocis in UI level but do add a comment n why the tests are skipped in ocis so that it's easier in future if someones happens to go through the tests again

**Comment by SagarGi** [comment]
Can be closed since this PR is merged https://github.com/owncloud/web/pull/7766
