### ISSUE TITLE
Check closed issue `Upload of folder with same name shows error` still exist in expected-to-failure

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#4682]
[Upload of folder with same name shows error  ](https://github.com/owncloud/web/issues/6996) issue has been closed but still their are some scenario under this issue.Check why there are scenario under [Upload of folder with same name shows error  ](https://github.com/owncloud/web/issues/6996) closed issue

https://github.com/owncloud/ocis/blob/a67e354eb48b8bafccb07be9eb8b04be909d56c3/tests/acceptance/expected-failures-webUI-on-OCIS-storage.md?plain=1#L238-L242

**Comment by SagarGi** [comment]
This is the debug Build: 
https://drone.owncloud.com/owncloud/ocis/15865/42/13

```runsh: Total unexpected failed scenarios throughout the test run:
webUIUpload/upload.feature:120
webUIUpload/uploadEdgecases.feature:53
webUIUpload/upload.feature:138
webUIUpload/upload.feature:130
webUITrashbinRestore/trashbinRestore.feature:244
webUIUpload/upload.feature:94
webUIUpload/upload.feature:111
runsh: Total unexpected passed scenarios throughout the test run:
webUITrashbinRestore/trashbinRestore.feature:260
webUIUpload/upload.feature:129
webUIUpload/upload.feature:142
webUIUpload/upload.feature:159
webUIUpload/uploadEdgecases.feature:69
```

**Comment by SagarGi** [comment]
@amrita-shrestha and @saw-jan this issue can be closed.

**Comment by SwikritiT** [comment]
The related tests in this closed issue will be removed once the web commit id id bumped so I'll be closing this issue now.
