### ISSUE TITLE
 Closed issue `No robots.txt available` still exist in expected-to-failure

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#4685]
[No robots.txt available](https://github.com/owncloud/ocis/issues/1314) issue has been closed but still, there are some scenarios under this issue. Check why there are scenarios under [No robots.txt available](https://github.com/owncloud/ocis/issues/1314) closed issue

https://github.com/owncloud/ocis/blob/a67e354eb48b8bafccb07be9eb8b04be909d56c3/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L517-L520

**Comment by SwikritiT** [comment]
@amrita-shrestha maybe we can close this issue now and other issues related to PR https://github.com/owncloud/core/pull/40392 ?

**Comment by amrita-shrestha** [comment]
This issue related PR has been merged so closing
