### ISSUE TITLE
Wrong link generation for space & share link

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#4688]
When inviting people to a space there is a bug in the share link that is generated for the email:

https://github.com/owncloud/ocis/blob/a5521161f8c5ec60186db3d6d0b06cd420b2915e/services/notifications/pkg/service/service.go#L159

same for shares:

https://github.com/owncloud/ocis/blob/a5521161f8c5ec60186db3d6d0b06cd420b2915e/services/notifications/pkg/service/service.go#L272

It uses the `.Idp` url instead of the instance url.

**Comment by rhafer** [comment]
I'll look into this. As I am working on the other notifications issue already.
