### ISSUE TITLE
recreate graph-explorer extension in dedicated repo

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#4739]
after [removing the graph-explorer](https://github.com/owncloud/ocis/pull/4733) we should
- [ ] introduce an owncloud/graph-explorer repo
- [ ] import the deleted code from https://github.com/owncloud/ocis/pull/4733
- [ ] add a deployment scenario/documentation that shows how to include it, maybe only for certain users (the proxy can do that already)

it would serve as an example for a more interesting service than *[ocis_hello](https://owncloud.dev/extensions/ocis_hello/)*

**Comment by C0rby** [comment]
> it would serve as an example for a more interesting service than [ocis_hello](https://owncloud.dev/extensions/ocis_hello/)

I don't think the `graph-explorer` is a tool that one would want it production. I see it more as a tool for developers.
If we want to showcase the "extension system" then we could implement something simple like a very simple pastebin/gist clone.

**Comment by kobergj** [comment]
bye bye graph-explorer!
