### ISSUE TITLE
"Precondition Failed" when uploading a file into a folder with the "?" character

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4745]
ownCloud Web UI 5.7.0
Infinite Scale 2.0.0-beta.8+e053f7095 Community

Steps:

- create folder with simbol "?" `new?folder`
- try to upload the file to the folder

Actual: 412 Precondition failed
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/84779829/194094077-cc5782f8-64c0-48d6-8551-59b7d6d50a4a.png">

log: 
`ocis_1             | 2022-10-05T15:02:31Z ERR failed to initiate upload error="error: not found: New" pkg=rgrpc service=storage-users status={"code":6,"message":"path not found when initiating upload","trace":"00000000000000000000000000000000"} traceid=00000000000000000000000000000000`

**Comment by ScharfViktor** [comment]
not relevant. works correct

**Comment by micbar** [comment]
the question mark needs to be urlencoded.

**Comment by ScharfViktor** [comment]
yes, it is. so I closed this issue

<img width="509" alt="Screenshot 2023-09-19 at 17 00 02" src="https://github.com/owncloud/ocis/assets/84779829/c47d997a-4680-4f41-8da8-800dcfbb0f80">
