### ISSUE TITLE
Stat cache doesn't get invalidated when using redis

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4772]
## Describe the bug

I'm using redis for the gateway cache:

```
GATEWAY_CACHE_STORE: redis
GATEWAY_CACHE_NODES: redis-master.ocis-redis.svc.cluster.local:6379
```

When I upload a file into my home space, the etag of the homespace does not change. When I delete the file, the etag of the homespace does not change.

When I delete all keys in redis, the etag of my homespace changes.

## Steps to reproduce

1. run oCIS with redis gateway cache
2. upload / delete files
3. see the etag not changing

## Expected behavior
The etag is changing properly

## Actual behavior
The etag stays the same

**Comment by butonic** [comment]
You need to configure the same redis database for the data provider that is started as part of the storage-users service.
