### ISSUE TITLE
S3NG: EOF if blob is not accessible

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4785]
## Describe the bug

When using S3NG and a file's blob is not accessible, we get no real error code but an EOF on downloading the file.

## Steps to reproduce

1. run the [oCIS S3](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_s3) example
2. upload a file
3. delete the blob via the minio GUI
4. download the file inside ownCloud Web

## Expected behavior
We get a Webdav spec compliant status code that the file can not be downloaded

## Actual behavior
EOF errors throughout all service that participate in that request

```
ocis_s3-ocis-1  | {"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","svc":"datatx","handler":"download","error":"The specified key does not exist.","time":"2022-10-11T15:25:04.942148689Z","message":"error copying data to response"}
ocis_s3-ocis-1  | {"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","error":"unexpected EOF","time":"2022-10-11T15:25:04.942366289Z","message":"error writing body after headers were sent"}
ocis_s3-ocis-1  | {"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","content-length":75416,"transferred-bytes":0,"time":"2022-10-11T15:25:04.94238269Z","message":"content length vs transferred bytes mismatch"}
ocis_s3-ocis-1  | 2022/10/11 15:25:04 httputil: ReverseProxy read error during body copy: unexpected EOF
ocis_s3-ocis-1  | 2022/10/11 15:25:04 httputil: ReverseProxy read error during body copy: unexpected EOF
ocis_s3-ocis-1  | {"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","svc":"datatx","handler":"download","error":"The specified key does not exist.","time":"2022-10-11T15:25:04.986053716Z","message":"error copying data to response"}
ocis_s3-ocis-1  | {"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","error":"unexpected EOF","time":"2022-10-11T15:25:04.986354823Z","message":"error writing body after headers were sent"}
ocis_s3-ocis-1  | {"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","content-length":75416,"transferred-bytes":0,"time":"2022-10-11T15:25:04.986369841Z","message":"content length vs transferred bytes mismatch"}
ocis_s3-ocis-1  | 2022/10/11 15:25:04 httputil: ReverseProxy read error during body copy: unexpected EOF
ocis_s3-ocis-1  | 2022/10/11 15:25:04 httputil: ReverseProxy read error during body copy: unexpected EOF
```

## Additional context
We didn't have this problem by deleting an actual blob. Somehow our S3 client / S3 bucket caused a "The specified key does not exist." error (which is coming from the minio-go lib).

We don't know if the client (connection) or the S3 server was stuck, but a restart of the storage-users service resolved the issue.

During that error state, we discovered the EOF bug described above.

**Comment by kobergj** [comment]
Mmh. We do return the error from minio-go client correctly: https://github.com/cs3org/reva/blob/experimental/pkg/storage/fs/s3ng/blobstore/blobstore.go#L130-L133 

So somehow minio-go is just logging the error, but not returning it.
