### ISSUE TITLE
Capabilities indicate (currently) non-existing federation support

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ocis#4788]
## Describe the bug

Capabilities currently return `true` for
```
files_sharing.federation.incoming
files_sharing.federation.outgoing
```

even though the server does not support federated sharing. The endpoint `/ocs/v2.php/apps/files_sharing/api/v1/remote_shares` only returns a 404 status.

## Steps to reproduce

1. Log into ocis instance
2. Retrieve capabilities
3. Retrieve remote_shares for an item 

## Expected behavior
The capabilities should reflect the actual capability of the server.

## Actual behavior
The capabilities do not match the availability of the federated sharing endpoint.

**Comment by butonic** [comment]
currently hardcoded as true: https://github.com/owncloud/ocis/blob/24807bbac81dcd60a37fce1957c76a28c703d397/services/frontend/pkg/revaconfig/config.go#L236-L239
