### ISSUE TITLE
Failed to list storage spaces for members of the space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4795]
ownCloud Web UI 6.0.0-rc.2 
Infinite Scale 2.0.0-beta.8+24807bbac Community 

Steps: 

- Admin shares project space to einstein as editor
- Einstein opens space

Actual: 
no errors on web. einstein can open space and edit
but there is server log: 
`2022-10-12T14:43:34+02:00 ERR failed to list storage spaces error="error: permission denied: user 4c510ada-c86b-4815-8820-42cdf82c3d51 is not allowed to list spaces of other users" filters=[{"Term":{"User":{"opaque_id":"fe84d02b-c2f6-4a6a-bb20-5cef2dc63129"}},"type":6}] pkg=rgrpc service=storage-users status={"code":8,"message":"permission denied","trace":"00000000000000000000000000000000"} traceid=00000000000000000000000000000000`

**Comment by 2403905** [comment]
Is it still a relevant issue?

**Comment by 2403905** [comment]
Is it still a relevant issue?

**Comment by micbar** [comment]
This is outdated.
