### ISSUE TITLE
Copy or move on an existing resource doesn't create a new version but deletes instead

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#4797]
## Steps to reproduce

1. Via WebUI: As admin, create the following resources:
   * `folder/test.txt`
   * `test.txt`
2. Now copy `test.txt` into `folder/test.txt` and select "Replace" as option (the WebUI sets `Overwrite: T` as header)

## Expected behavior
`folder/test.txt` should have two versions.

## Actual behavior
`folder/test.txt` only has one version. The overwritten version has been deleted and can be found in the trash bin.

cc @micbar GA-Blocker?

**Comment by ScharfViktor** [comment]
Ooh, this happens during copying. Uploading or moving a file with the "Replace" option works correctly. We have an api test for uploading with "Replace", but no tests for copying with "Replace". I will create tests for this case.

**Comment by aduffeck** [comment]
This has been fixed with https://github.com/cs3org/reva/pull/3896

**Comment by ScharfViktor** [comment]
still relevant: https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiSpacesShares/moveSpaces.feature#L322

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/ocis/assets/84779829/d2d2ebf1-9a80-4cc5-933f-f63226216ade

**Comment by micbar** [comment]
## Re Tested on ocis master:

Works as expected

### Move

- Moving a file to an existing file should replace the file and move the existing file with all versions to the trashbin.
- Moving a file should also move the shares and tags and all other metadata

**Comment by ScharfViktor** [comment]
web issue for double file on page https://github.com/owncloud/web/issues/9152
