### ISSUE TITLE
[ocis] Auto-accept shares

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#4834]
## Value

Satisfy CERN requirements

## Acceptance Criteria
- The user can decide how the auto-accept behavior (user setting like "Get Mail Notifications")
- The admin can configure the default value for auto-accepting (default: auto-accept is enabled)
- Communicate auto-accept via capability (according to oc 10 behaviour)

**Comment by kulmann** [comment]
cc @micbar please prioritize as you see fit

**Comment by kulmann** [comment]
More context: what we will implement in web to mitigate the described scenario is the following: https://github.com/owncloud/web/issues/7803#issuecomment-1280679439

This is all we can do without having the shareId. As you can see, the user experience is not ideal. If shares would be auto-accepted users would see that error state in web only for declined shares.

**Comment by tbsbdr** [comment]
Confirmed.

Note: With VFS as default for the Desktop client, the default for shares should be to see them and in case if you dont want to see them, hide them. (discussed here: owncloud/web#7551 )

**Comment by dragotin** [comment]
@micbar this issue is considered to need backend changes, could you look into and scope that?
