### ISSUE TITLE
502 Bad Gateway on /ocs/v2.php/cloud/user?format=json

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#4858]
## Describe the bug

Desktop client can't login, because the user endpoint (` /ocs/v2.php/cloud/user?format=json`) responds with `502 Bad Gateway`

## Steps to reproduce

1. Install 3.0 pre-release client (https://github.com/owncloud/client/releases?q=v3.&expanded=true)
2. Connect with `ocis.ocis-keycloak.latest.owncloud.works` or `ocis.ocis-keycloak.released.owncloud.works`
3. Enter credentials in web browser (`einstein:relativity`)

## Expected behavior

Desktop client should connect and start syncing.

## Actual behavior

Desktop client shows error. (see screenshot)

## Setup

Don't see because of https://github.com/owncloud/ocis/issues/4818

## Additional context

Related?
- https://github.com/owncloud/ocis/issues/4616

### Request and Response

```
10-19 15:49:15:123 [ info sync.httplogger ]:	"9f44eb0d-bafc-481f-967e-7b0b140d914b: 
Request: GET https://ocis.ocis-keycloak.latest.owncloud.works/ocs/v2.php/cloud/user?format=json 
Header: { Authorization: Bearer [redacted], OCS-APIREQUEST: true, User-Agent: Mozilla/5.0 (Macintosh) mirall/3.0.0.8819-daily20221019 (testpilotcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: 9f44eb0d-bafc-481f-967e-7b0b140d914b, Original-Request-ID: 9f44eb0d-bafc-481f-967e-7b0b140d914b, } 
Data: []"

10-19 15:49:15:295 [ info sync.httplogger ]:	"9f44eb0d-bafc-481f-967e-7b0b140d914b: 
Response: GET 502 (Error: Error transferring https://ocis.ocis-keycloak.latest.owncloud.works/ocs/v2.php/cloud/user?format=json - server replied: Bad Gateway,duration(0h, 0min, 0s, 172ms)) https://ocis.ocis-keycloak.latest.owncloud.works/ocs/v2.php/cloud/user?format=json 
Header: { Date: Wed, 19 Oct 2022 13:49:15 GMT, Content-Length: 11, Content-Type: text/plain; charset=utf-8, } 
Data: [Bad Gateway]"
```

### Screenshot

<img width="1458" alt="CleanShot 2022-10-19 at 16 15 12@2x" src="https://user-images.githubusercontent.com/214010/196717953-ac2150e0-2b90-48d6-93ce-b68488058b7d.png">

**Comment by micbar** [comment]
should be fixed by #4867 

Waiting for CI to finish the deployment
