### ISSUE TITLE
Search by renamed incoming resource does not work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4866]
ownCloud Web UI 5.7.0 
 Infinite Scale 2.0.0-beta.8+07475407d Community 

Steps:
1. Log in as admin and create the following resources:
   * `foo.txt`
   * `folder/foo.txt`
2. Shares both `test.txt` files with user `einstein`
3. As `einstein`, accept both shares
4. One of them will be mounted as `foo (1).txt` (need refresh page)
5. Rename the other received file to  `foo renamed.txt`
6. Try to find by `foo`

Expected: search gives 2 files: `foo (1).txt` and `foo renamed.txt`

Actual: search gives 2 files: `foo.txt` . If we rename file to `new name.txt` and try to find by `new` - we will not find the file

![Screenshot 2022-10-20 at 16 10 38](https://user-images.githubusercontent.com/84779829/196975025-38312f4e-0ef0-42c9-afc1-15c67e3f13f5.png)

![Screenshot 2022-10-20 at 16 27 56](https://user-images.githubusercontent.com/84779829/196977148-3385914f-34e8-4ebd-848d-e72d1779e60e.png)

**Comment by JammingBen** [comment]
Some more context can be found here: https://github.com/owncloud/ocis/issues/4796#issuecomment-1283662871 and https://github.com/owncloud/ocis/issues/4796#issuecomment-1283694534. It basically affects the OCS as well as the webdav API.
