### ISSUE TITLE
FreeBSD 13/stable build problem - looks like freebsd is unsupported totally.

### ISSUE THREAD

**Issue by jostreff** [owncloud/ocis#4880]
## Describe the bug
Can't be build from source still on FreeBSD stable/13-n252824-84b4709f38f with "gmake generate ; gmake build" as described.

## Steps to reproduce
# gmake generate
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/app-provider“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/app-provider“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/app-registry“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/app-registry“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/audit“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/audit“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/auth-basic“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/auth-basic“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/auth-bearer“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/auth-bearer“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/auth-machine“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/auth-machine“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/frontend“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/frontend“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/gateway“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/gateway“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/graph“
/root/go/bin/mockery-v2.10.4 --dir pkg/service/v0 --case underscore --name GatewayClient
23 Oct 22 15:46 EEST INF Starting mockery dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Walking dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Generating mock dry-run=false interface=GatewayClient qualified-name=github.com/owncloud/ocis/v2/services/graph/pkg/service/v0 version=v2.10.4
/root/go/bin/mockery-v2.10.4 --dir pkg/service/v0 --case underscore --name HTTPClient
23 Oct 22 15:46 EEST INF Starting mockery dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Walking dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Generating mock dry-run=false interface=HTTPClient qualified-name=github.com/owncloud/ocis/v2/services/graph/pkg/service/v0 version=v2.10.4
/root/go/bin/mockery-v2.10.4 --dir pkg/service/v0 --case underscore --name Publisher
23 Oct 22 15:46 EEST INF Starting mockery dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Walking dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Generating mock dry-run=false interface=Publisher qualified-name=github.com/owncloud/ocis/v2/services/graph/pkg/service/v0 version=v2.10.4
/root/go/bin/mockery-v2.10.4 --srcpkg github.com/go-ldap/ldap/v3 --case underscore --filename ldapclient.go --name Client
23 Oct 22 15:46 EEST INF Starting mockery dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Walking dry-run=false version=v2.10.4
23 Oct 22 15:46 EEST INF Generating mock dry-run=false interface=Client qualified-name=github.com/go-ldap/ldap/v3 version=v2.10.4
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/graph“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/groups“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/groups“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/idm“
gmake[1]: Няма нищо за правене за „generate“.
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/idm“
gmake[1]: влизане в директория „/usr/home/jostreff/ocis/services/idp“
yarn install --immutable
➤ YN0028: The lockfile would have been created by this install, which is explicitly forbidden.
➤ YN0000: Failed with errors in 0s 7ms
gmake[1]: *** [Makefile:61: node_modules] Грешка 1
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/idp“
gmake: *** [Makefile:128: generate] Грешка 1## Expected behavior

## Actual behavior
I see you're already in beta, but there still seem to be gaps in support for my favorite server OS.

## Setup
FreeBSD 13.1-STABLE #85 stable/13-n252824-84b4709f38f

go118-1.18.7                   Go programming language
go119-1.19.2                   Go programming language
gmake-4.3_2                  GNU version of 'make' utility
node16-16.17.1_1             V8 JavaScript for client and server

yarn --version
3.2.3
npm --version
8.19.2

**Comment by micbar** [comment]
seems like a yarn issue. @kulmann any ideas?

**Comment by kulmann** [comment]
If I remember correctly the idp web frontend needed node v14 for building successfully. For the current master / the upcoming ocis v2.0.0-rc.1 node v16 should work.

**Comment by jostreff** [comment]
I see that moving to `pnpm` solved `make generate` problems on FreeBSD with node.js 16.17.1 for sure.

Now it breaks on next step with
```# github.com/cs3org/reva/v2/pkg/storage/utils/localfs
/root/go/pkg/mod/github.com/cs3org/reva/v2@v2.10.1-0.20221103130432-65012c8466b4/pkg/storage/utils/localfs/localfs_unix.go:80:11: invalid operation: stat.Blocks - stat.Bavail (mismatched types uint64 and int64)
/root/go/pkg/mod/github.com/cs3org/reva/v2@v2.10.1-0.20221103130432-65012c8466b4/pkg/storage/utils/localfs/localfs_unix.go:81:15: invalid operation: stat.Bavail * uint64(stat.Bsize) (mismatched types int64 and uint64)
gmake: *** [../.make/go.mk:102: bin/ocis] Error 2```

**Comment by micbar** [comment]
Should be fixed by https://github.com/cs3org/reva/pull/3559
