### ISSUE TITLE
Unexpected HTTP response: 500. Please check your connection and try again.

### ISSUE THREAD

**Issue by melbruki** [owncloud/ocis#4891]
Hello I am a casual user just testing out OCIS I think its great I like how there are no dependencies this makes running on k8s nice, but I noticed problems I will list them out below. I have this running inside of microk8s I noticed these problems when I added another replica, I have a total of 2 replicas and 3 nodes. I am using metallb and a LB IP to access OCIS. I dont have a certificate installed however I enabled to allow insecure access in my deployment file. below are the issues I have encountered so far. note that these problems appeared after i added another replicas and started to test failover

1.error message "Unexpected HTTP response: 500. Please check your connection and try again."  after inputting my username and password. I did restart my browser, however still the same. This problem is intermittent
2. after logging in page dosnt fully load loading circle spins but page never completely loads. I have logged out and logged in shutdown my browser, but results are mixed. usually this happens after a node goes down
3. I drag and drop a file to upload however upload fails

**Comment by micbar** [comment]
hi @melbruki 

I don't know the details of your setup. The ocis container starts an ocis process inside the container if not configured different, in an "all-in-one" process. To scale ocis, you cannot just duplicate the whole ocis container and do a loadbalancing  in front of it if you do not share a "read-write-many" storage.

We are using our ocis helm chart to deploy ocis on k8s where we start the single ocis services.

Docs are here https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#using-helm-charts-with-infinite-scale

If you provide more details, we can get a better view on what you are trying to achieve.

**Comment by melbruki** [comment]
I am using read write many (rook-ceph), both pods start and run and even when one node goes down I'm still able to access the login page as expected from the remaining pod just how you would imagine And on occasion I am able to even login and it functions normally 

The purpose is high availability, it's setup using your docker image where all of the services/ extension are running in one pod.  I prefer to keep all the services contained in the single pod. 

However using this setup I have mixed results  as described in my previous post. 

I looked at the logs and there's messages about can't reach ldap server and tls handshake failure. I can send you the exact log messages if that would help.

**Comment by melbruki** [comment]
@micbar can you please answer this when you have time or at least tell me if it is a bug so I dont waste my time trying to get it to work.
I would like to offer this to some of my clients.

thank you

**Comment by micbar** [comment]
@wkloucek can you do a quick review of this problem? From my POV it should work. TLS problems are always deployment specific problems.

**Comment by melbruki** [comment]
@wkloucek @micbar  thank you I will be on the look out for this simpler setup in the future. 
Also I didn't see any documentation as to what each service does just on how to modify it and what services are in general,I think including something like that would be helpful. For example what exactly is the idm service and what does it do.  Maybe you already have something like that but I didn't find it
