### ISSUE TITLE
Uploading large files fails when using the desktop client

### ISSUE THREAD

**Issue by Horstexplorer** [owncloud/ocis#4904]
Hi! I am unable to upload larger files to my ocis instance using the desktop client.

It works perfectly fine for files <~100mb but for larger ones, it seems to upload about 100-150MB and then skip the file. After a second of wait it usually retries and fails with a "File is currently in use" type of error.
Uploading those files via the web ui works without any issues. An oc10 instance also will process them just fine (mostly).
I am using the desktop client 2.11.1 (build 8438) on Windows 11 (22621.675) with the ocis beta 8 running inside the official docker container on another system.

As the logs may contain some data which I probably shouldnt share to the public I replaced some names and shorted it down a little. 

The log of the ocis instance
[server_log.txt](https://github.com/owncloud/ocis/files/9863568/server_log.txt)

And two from the client. Due to it retrying to upload it created about 8 of them.
The "File is currently in use" type of error seems to have only appeared in the last log while it may have automatically retried the upload in the other ones.

[Client log 0, 1, 2](https://github.com/owncloud/ocis/files/9863652/20221025_1637_1_owncloud.log)
[Client log 6](https://github.com/owncloud/ocis/files/9863619/20221025_1637_owncloud.log)
[Client log 7](https://github.com/owncloud/ocis/files/9863607/20221025_1638_owncloud.log)

**Comment by micbar** [comment]
@TheOneRing @michaelstingl Does that error sound familiar?

I could not reproduce it with my 2.11.1 on the ocis team instance.

![Bildschirmfoto 2022-10-25 um 23 02 14](https://user-images.githubusercontent.com/4378513/197882057-3d2d4125-2d44-4bd6-8c7e-870bf16dab08.png)

![Bildschirmfoto 2022-10-25 um 23 04 15](https://user-images.githubusercontent.com/4378513/197882080-ca2b54a4-efde-4ee0-8b73-42fe35a9aa0a.png)

**Comment by michaelstingl** [comment]
Does it also happen with the public demo instances?
https://owncloud.dev/ocis/deployment/continuous_deployment/

Can't find the `POST` requests in the logs you provided. Please enable HTTP logging.

You can "File Drop" more log files here:
https://cloud.owncloud.com/index.php/s/fkfX79RbYxEWzdV

**Comment by michaelstingl** [comment]
@micbar @TheOneRing I uploaded the previous log files here:
https://cloud.owncloud.com/index.php/f/5915568

**Comment by TheOneRing** [comment]
2.11 does not support ocis.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/9472

**Comment by michaelstingl** [comment]
> 2.11 does not support ocis.

@Horstexplorer you could also try with the 3.0 pre-release builds:
https://owncloud.com/beta-testing/#desktop-daily

Use the Testpilot build to not mess up with your production ownCloud client.

**Comment by Horstexplorer** [comment]
> you could also try with the 3.0 pre-release builds:

The pre-release build seems to be working properly! 
I have tried the macOS version of 2.11 as well and this also appears to work with no problems.
So it may be that Windows is acting up again. Either way it seems to be fixed in the upcoming release.

Thank you for your help!

**Comment by TheOneRing** [comment]
We had a file locking issue, those only exist on WIndows.
