### ISSUE TITLE
Update Web service configuration

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4921]
## Is your feature request related to a problem? Please describe.
Update the Web configuration in the oCIS Web service so that it reflects the current Web configuration.

## Describe the solution you'd like
Have it all here: https://github.com/owncloud/ocis/blob/6c4b54015a2bbc94eb9600c5d90c2b9f7134883e/services/web/pkg/config/config.go#L33-L88

cc @kulmann

**Comment by kulmann** [comment]
I don't understand the proposed the solution. Do you mean that the options should be root level attributes in the `WebConfig` struct?

**Comment by micbar** [comment]
> I don't understand the proposed solution. Do you mean that the options should be root level attributes in the WebConfig struct?

We should have a config struct representing the available options and defaults.

**Comment by micbar** [comment]
Available options: https://owncloud.dev/clients/web/getting-started/#options

Missing: `logoutUrl`
