### ISSUE TITLE
webdav readme possible update

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4926]
We just have written a [nice readme](https://github.com/owncloud/ocis/pull/4912) for webdav.

Now, when looking into the admin docs where we this description needs to be transported to, I found an [interesting sentence](https://doc.owncloud.com/ocis/next/deployment/services/webdav.html#introduction) that already existed:

`The Infinite Scale WebDAV service provides preview (thumbnails) endpoints on the WebDAV API and therefore extends the main WebDAV API provided by the OCDAV service.`

The question is, should the new readme improved with the content:
`The WebDAV API extends the API provided by the OCDAV service`?

@kobergj maybe you can help

**Comment by butonic** [comment]
Hm, no. The ocis webdav service implements an aspect of the oc10 webdav api that is left out of the ocdav handler: thumbnails.
