### ISSUE TITLE
Split docker-compose to have setups for OC storage and EOS storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#493]
The current docker-compose is a mix between OC storage and EOS storage, but actually if you look more closely, it is anyway starting all these EOS dockers.

We should split the docker-compose file into several ones
- one for OC storage only
- one for EOS storage only

The current state is causing unnecessary confusion, especially considering that in the eos.md documentation one needs to restart some services with different config values. The more confusion, the slower the development because of potential human errors.

@butonic FYI

**Comment by PVince81** [comment]
I think we should address this before more devs start working on EOS as copy-pasting those commands from the docs is tedious and error-prone.

**Comment by refs** [comment]
The current development docs are up to date, rendering this issue not so important anymore. See https://owncloud.github.io/ocis/development/getting-started/ for more information.
