### ISSUE TITLE
Add minimal service description to each `main.go`

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#4933]
I would expect to have each services `main.go` to have a minimal description of the purpose what said service purpose is.

**Example files:**
https://github.com/owncloud/ocis/blob/master/services/storage-system/cmd/storage-system/main.go
https://github.com/owncloud/ocis/blob/master/services/ocdav/cmd/ocdav/main.go

/cc @mmattel

**Comment by kobergj** [comment]
How would this "minimal service description` defer from the `README.md` files?

**Comment by dragonchaser** [comment]
obsolete since READMEs are available now
