### ISSUE TITLE
Description missing for OCIS_GRPC_TLS_ENABLED in multiple locations (services)

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4936]
Running: `grep -rn "yaml:" | grep "env:" | grep -v "desc:"` 

Checking if the descriptions are definitely missing by looking into the ocis admin docs into the services

**Services list** where `OCIS_GRPC_TLS_ENABLED` has no description:

* auth-machine
* storage-users
* groups
* storage-shares
* storage-publiclink
* storage-system
* auth-basic
* sharing
* gateway
* app-provider
* app-registry
* auth-bearer
* users

**Services list** where `REVA_GATEWAY_TLS_MODE` and `REVA_GATEWAY_TLS_CACERT` has no description:

* thumbnails
* notifications

Note, see #4935 (Add REVA_ env description for WebDav) where the above was missing too - fixed.

@wkloucek @micbar @rhafer pls fix by adding a description.
@dragonchaser fyi

**Comment by rhafer** [comment]
Will be fixed with #4910
