### ISSUE TITLE
apiTests implementation

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4937]
list of missing api test:
TODO: find the missing tests. compare with https://cloud.owncloud.com/index.php/s/GrNcjPrHw3s4oGq 

Graph api
- [x] info about user /graph/v1.0/me?%24expand=memberOf @SagarGi https://github.com/owncloud/ocis/pull/5084
- [x] create user https://github.com/owncloud/ocis/pull/4902
- [x] get user. check also `https://localhost:9200/graph/v1.0/users/uuid?%24select=&%24expand=drive` The user can only get his drive data https://github.com/owncloud/ocis/pull/5149
- [x] delete user @grgprarup https://github.com/owncloud/ocis/pull/5102
- [x] edit user @grgprarup https://github.com/owncloud/ocis/pull/5150
- [x] create group @saw-jan (https://github.com/owncloud/ocis/pull/4992)
- [x] get group @saw-jan  (https://github.com/owncloud/ocis/pull/5005)
- [x] edit group @saw-jan (https://github.com/owncloud/ocis/pull/5101)
- [x] delete group. check that user has no deleted group @saw-jan (https://github.com/owncloud/ocis/pull/5076)
- [x] add user to group @saw-jan (https://github.com/owncloud/ocis/pull/5093)
- [x] delete user from group @saw-jan (https://github.com/owncloud/ocis/pull/5104)

another:
- [x] share space to group. @grgprarup https://github.com/owncloud/ocis/pull/5023 (https://github.com/owncloud/ocis/issues/5036#issuecomment-1336362711)
- [x] share space without manager permission @grgprarup https://github.com/owncloud/ocis/pull/5047/
- [x] share disabled space is not possible (ink public link) @grgprarup https://github.com/owncloud/ocis/pull/5048
- [x] role assignment. check that user or Space manager cannot assign role https://github.com/owncloud/ocis/pull/5088
- [x] expand existing share tests to `permissions: 0` internal @grgprarup https://github.com/owncloud/ocis/pull/5100
- [x] - **tests have already been implemented** users members of the project space cannot get disabled space. They should get empty response, except `space Admin`
- [x] public with viewer role cannot create/delete/change resource @SagarGi https://github.com/owncloud/ocis/pull/5182

Contract testing: https://github.com/owncloud/ocis/pull/4886
- [x] propfind request of space `remote.php/dav/spaces/<space-id>` @SwikritiT  https://github.com/owncloud/ocis/pull/5138
- [x] increase the number of propfind tests. members of the space (viewer, editor, manager) check the response of the PROPFIND API @SagarGi https://github.com/owncloud/ocis/pull/5252
- [x] post share request here is bug https://github.com/owncloud/ocis/issues/5139 there may be others @SwikritiT https://github.com/owncloud/ocis/pull/5235
- [x] get request /graph/v1.0/me/drives @saw-jan https://github.com/owncloud/ocis/pull/5151

I'll add more missed tests. I'll implement also test, please assign yourself what kind of case you will develop
cc @individual-it

**Comment by SagarGi** [comment]
i will also be joining to this.

**Comment by SagarGi** [comment]
All the API tests listed have been added. So closing this issue. Another issue can be created if there are remaining API tests to add.
