### ISSUE TITLE
[Space webdav]Can't delete `Shares` named folder in Personal space

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#4945]
## Describe the bug

Can't delete Shares folder on the Personal spaces

## Steps to reproduce

1. `einstein` creates a folder `FOLDER`
2. `einstein` shares the folder with the role `editor` to `admin`
3. `admin` accepts the shares
4. `admin ` create `Shares` folder on the Personal space
5. `admin` tries to delete the `Shares` folder on the Personal space

```
curl https://host.docker.internal:9200/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157%24some-admin-user-id-0000-000000000000/Shares -X DELETE -u admin:admin -vk

```

## Expected behavior
User should able to delete `Shares ` folder on the personal space

## Actual behavior
Response:
```
> DELETE /remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157%24some-admin-user-id-0000-000000000000/Shares HTTP/1.1
> Host: host.docker.internal:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Content-Length: 220
< Content-Security-Policy: default-src 'none';
< Content-Type: text/xml; charset=utf-8
< Date: Tue, 01 Nov 2022 04:56:07 GMT
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host host.docker.internal left intact
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception>Sabre\DAV\Exception\Forbidden</s:exception><s:message>Permission denied to delete ./Shares</s:message></d:error>% 

```

**Comment by micbar** [comment]
@dragonchaser @amrita-shrestha Why should we delete the `Shares` folder? It only appears on the legacy webDAV endpoints. From my POV the behavior is fine.

**Comment by dragonchaser** [comment]
Shared jail can not be deleted, works as intended (and functionality might differ from oc10 behaviour => may need adaption in the testsuite) /cc @individual-it

**Comment by dragonchaser** [comment]
Misunderstanding on my behalf, this seems to be an issue with the hard-coded string for the shares jail, will investigate.

**Comment by dragonchaser** [comment]
https://github.com/cs3org/reva/pull/3432

**Comment by dragonchaser** [comment]
Will be fixed with next reva version bump in ocis.

**Comment by micbar** [comment]
Currently this is not in the 2.0.0-rc.1
