### ISSUE TITLE
env descriptions need an update when PR is transported to master

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4959]
See comments in: https://github.com/owncloud/ocis/pull/4958 (configure max_acquire_lock_cycles & reva bump) merged to experimental

@kobergj @fschade

**Comment by kobergj** [comment]
Here: https://github.com/owncloud/ocis/pull/4965

**Comment by kobergj** [comment]
@mmattel could you double check my description in the PR? Then we can close this ticket.
