### ISSUE TITLE
Changing the link role to "internal" gives 404

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4979]
Infinite Scale 2.0.0-beta.8+1f53ec525 Community 
ownCloud Web UI 6.0.0-rc.4 

Steps: 
- create file or folder
- create public link 
- change the role of the link to `internal`

Actual result:
request:
```
curl 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/VWHKBjPKgiGJrxo' \
  -X 'PUT' \
  --data-raw 'permissions=0&name=Link&expireDate=' \
```
response:
code 200. error in body response: `<ocs><meta><status>error</status><statuscode>404</statuscode><message>no share permission</message></meta></ocs>`

**Comment by micbar** [comment]
Fixed on master.

**Comment by SwikritiT** [comment]
TODO QA team 
- [ ] add API tests for changing the role of the public link to internal

**Comment by SwikritiT** [comment]
@roshanlc is working on adding the tests for this

**Comment by saw-jan** [comment]
Tests added in PR  https://github.com/owncloud/ocis/pull/5415
