### ISSUE TITLE
[ocis] Edit username

### ISSUE THREAD

**Issue by pmaier1** [owncloud/ocis#4988]
Currently it is not possible to change the user id / user name in the user management UI. As the backend allows this, we should also offer this in the web frontend.

/cc @tbsbdr @kulmann

**Comment by rhafer** [comment]
> It seems that OCIS currently doesn't allow renaming the user name, do I miss something?

That's right. And I think we communicated lots of times that renames (using the internal user management) don't work currently. So I am mildly surprised to see this becoming a GA Blocker now. It will require some bigger changes to libregraph/idm, it currently lacks support for the MODRDN (rename) Operation.

BTW, when using an external user management renames shouldn't be an issue.

**Comment by micbar** [comment]
> BTW, when using an external user management renames shouldn't be an issue.

That would be enough IMO 
@pmaier1 Do you agree?

**Comment by rhafer** [comment]
Note to whoever is looking into this: Renaming can be a bit tricky in the LDAP backend, as we need to update the users group membership as well (i.e. update the `member` Attribute of the groups with the new LDAP DN of the user)
