### ISSUE TITLE
Rework oCIS README.md

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#4995]
The README.md is a bit outdated.

- The first sentence is not longer true, we are not longer in a "technical preview state".
- Explain what Infinite Scale is (and maybe what it is not)
  - What is it used for?   
  - Architecture and why we choose it
  - Open source
  - Reva as a component
- Explain for whom it is
- References to clients

In chapter **"Run Infinite Scale"**:
- Brief explanation of what the key message is: Simple deployment with single binary, scaling deployments with Kubernetes
- Links to the right repositories (ie. with Helm charts)

In chapter **"Documentation"**:
- One sentence each to explain what kind of documentation is linked.

In chapter **"Contributing"**:
- A bit more verbosity, even if that is all mentioned in the Contribution guidelines already.

**Comment by mmattel** [comment]
For ease of writing, you may want to look at the intro and referenced pages of the [ocis admin documentation](https://doc.owncloud.com/ocis/next/) as we already have done a lot of work here.
