### ISSUE TITLE
Questions to public link role "internal" ?

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5000]
@ScharfViktor @tbsbdr maybe you can help

* When setting the the role of a [public link](https://user-images.githubusercontent.com/3321281/200371684-e1b014b7-0248-433e-b065-800a8e52e40c.png), which permissions does the role `internal` have compared to `viewer` or `editor`.
* How does one get "invited" into a public link? The text says the following but where to enter?
![image](https://user-images.githubusercontent.com/3321281/200375011-5874899a-5c24-4e5a-b3f9-a0200eb4fb7e.png)

**Complete sharing frame**

![image](https://user-images.githubusercontent.com/3321281/200375512-41880898-88ae-4e4e-8fde-2cdc4b8a758b.png)

**Comment by mmattel** [comment]
Hey, issue number 5000 :angel:

**Comment by micbar** [comment]
1) Internal

means that this is just a link to a resource which grants no additional access. You can access the resource only if you have an account and are part of the space or share. That is the meaning of invited. You see that `share with people` is the same like `invite people`.

2) Public access grants access to a resource even if you have no account. All people who now the link and the optional password can access the resource.

**Comment by kulmann** [comment]
@mmattel think of the link as a `pointer`. For your understanding (but of course not sufficient for a reader of the documentation): Once created it has the same functionality as a private link. But you can switch between "public" (via the roles viewer, editor, uploader) and "internal" at any time.

**Comment by micbar** [comment]
> Once created it has the same functionality as a private link

Yes. This is the new "private link". We want to discontinue the wording "private link"

it is just "Link"

- Link with internal access
- Link with public access

**Comment by micbar** [comment]
clarified
