### ISSUE TITLE
Shared by name is not updated after a share is removed

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#5006]
### Description
This issue is to know if the following story is intended (expected) behaviour on ocis.
This issue can be understood more clearly with steps to reproduce.

### Steps to reproduce
1. create three user `user1`, `user2`, and `user3`
2. `user1` creates a folder `folder`
3. `user1` creates a file `folder/myfile.txt`
4. `user1` shares the folder to `user2` with role `editor`
5. `user2` accepts the share from `user1`
6. `user2` again shares the resource `folder/myfile.txt` to `user3`
7.  `user3` accepts the share from `user2`
8. `user1` removes the shares with `user2`

Results form the above steps:

1. `user1` has a changed shared with from `user2` to `user3` as

![Screenshot from 2022-11-08 16-44-47](https://user-images.githubusercontent.com/46086950/200548182-de52c46d-84b4-4906-9b4d-37dac89110ca.png)

which seems fair since `user2` as shared the resources with `user3` and the file is still there (not deleted)

#### AND

2. `user2` has no resource in `shared with me` and `shared with others` as

![Screenshot from 2022-11-08 16-51-15](https://user-images.githubusercontent.com/46086950/200548795-87a8a972-c180-4abd-8664-150bf274f24f.png)

![Screenshot from 2022-11-08 16-44-20](https://user-images.githubusercontent.com/46086950/200548825-1c30f596-3366-44f1-916c-9749d8f2efd4.png)

#### BUT

3. `user3` has shared by name as `user2`

![Screenshot from 2022-11-08 16-43-47](https://user-images.githubusercontent.com/46086950/200549098-c91f142a-65b7-4529-8e5a-ed0ee3f63011.png)

NOTE: Just wanted to know if the name is also to be changed since after `user1` removed the share from `user2` the shared with me is updated to `user3` like wise the shared by name.

### Environment
OCIS = docker image

**Comment by gedw99** [comment]
Adding myself as also interested in this
