### ISSUE TITLE
[oc10|ocis] No version exist after restoring file version of same file uploaded

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5010]
### Description
**`In ocis and oc10,`**
when the user uploads the same file twice then one file version exists but when we upload the same file a third time then no file version is added. If we restore the version then the version list gets empty.

#### Question
- Is this actual behaviour?

### Steps to reproduce
1. `admin` upload a file `file.txt` 
2. `admin ` again upload the same file `file.txt` then the file version is created
3. `admin` upload the same file `file.txt` for the third time then no file version is created

### Actual behaviour
While uploading the same file a second time, one file version is created
![uploadfileforsecondtimeoc10](https://user-images.githubusercontent.com/54478846/199905867-d3d2e8eb-bf24-4424-bd5f-6aa76d5a6e23.png)

While uploading the same file a third time, no file version is created
![uploadfilethirdtimeinoc10](https://user-images.githubusercontent.com/54478846/199906266-496c2648-3fb2-4230-a32c-01d99ace1997.png)

If we restore the version, then the version list gets empty

![versionemptyinoc10](https://user-images.githubusercontent.com/54478846/199906506-8f80e82b-21a5-4d0d-9bdd-33853099ad91.png)

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: both

**Comment by dragotin** [comment]
If both systems behave the same, I suggest to close this as "works as designed", as nothing dramatic happens. The not logic thing is that the second upload does create a version, even though that would not be needed.

Also, if the file is restored and the version list is empty that is not dramatic as there simply is not a different version of the file.

**Comment by SwikritiT** [comment]
TODO QA team
- [ ] check if there are tests covering this issue 
- [ ] if not add tests
