### ISSUE TITLE
Cover Smoke Tests with E2E

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#5013]
# Description

The release smoke tests should be fully covered by E2E tests

**Comment by ScharfViktor** [comment]
I compared and checked coverage: 
we don't have tests for these steps. but some are impossible to create, some probably aren't necessary

- [ ] upload big file - we keep all uploaded file in repo https://github.com/owncloud/web/tree/master/tests/e2e/filesForUpload so we cannot keep big file. Probably we can generate file before uploading and check: details, pause and cancel upload
- [ ] upload a lot of small files  - try to generate files before uploading
- [ ] check pagination. in the user, group, files, space section
- [ ] upload folder - https://github.com/owncloud/web/issues/2222 - not possibe
- [ ] upload folder drag and drop - not possible https://github.com/owncloud/web/issues/6051 
- [ ] upload file drag and drop - need to figure out how

cc @individual-it @saw-jan

**Comment by PrajwolAmatya** [comment]
Does pagination work in users and group section? I tried creating multiple users and groups (>100) and all of them are on the same page and it seems like there is no pagination feature on the page.
@ScharfViktor

**Comment by PrajwolAmatya** [comment]
So we do not need to add test for those for now.
@kulmann @ScharfViktor

**Comment by ScharfViktor** [comment]
> @ScharfViktor Is this done now?

Yes, I wanted to close after merging https://github.com/owncloud/web/pull/9082
