### ISSUE TITLE
Cover Space Features with E2E tests

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#5014]
# Description

The space Feature is brand new. We have too little coverage to prevent Regressions

**Comment by saw-jan** [comment]
@ScharfViktor 
I think space features are covered with e2e tests. Is there anything we can add? or if not we can close this ticket.

**Comment by ScharfViktor** [comment]
Yes, we can only add test for new feature and close ticket 

<img width="810" alt="Screenshot 2023-06-05 at 09 52 17" src="https://github.com/owncloud/ocis/assets/84779829/fe8f5ac6-33f7-474e-ba46-95e73c8e8389">

**Comment by saw-jan** [comment]
Add project space test case:
- [ ] download project space
