### ISSUE TITLE
Cover Link resolving with E2E tests

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#5015]
# Description

The new links feature has not enough test coverage to prevent regressions.

## Tests needed for

- Public Links
- Alias Links
- Private Link resolving

**Comment by saw-jan** [comment]
@ScharfViktor 
I think links test cases are covered with e2e tests. Is there anything we can add? or if not we can close this ticket.

Did we have tests for `Alias Links`?

**Comment by ScharfViktor** [comment]
I want to refactoring existing tests and enable tests for public link of project space

**Comment by ScharfViktor** [comment]
closed as comleted
