### ISSUE TITLE
Public cannot download folder via the public link of the project space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5027]
ownCloud Web UI 6.0.0-rc.6
Infinite Scale 2.0.0-rc.1

Steps:

- up ocis or use https://ocis.ocis-wopi.released.owncloud.works/
- user creates project space (space contains folder with content)
- user creates public link for space
- public opens link and try downloads folder

Actual: not possible to download folder

![image](https://user-images.githubusercontent.com/84779829/201088558-bedf8d09-82a6-4449-886e-1917169fdbcb.png)

ocis_log:

`{"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"GET","uri":"/archiver?public-token=eTIYZKkkWqiQoso&id=1284d238-aa92-42ce-bdc4-0b0000009157$9c741128-f470-4267-a0fe-7eb1656f3baf!bed1319d-30d7-4904-b2ce-8ee541962d58","url":"/archiver?public-token=eTIYZKkkWqiQoso&id=1284d238-aa92-42ce-bdc4-0b0000009157$9c741128-f470-4267-a0fe-7eb1656f3baf!bed1319d-30d7-4904-b2ce-8ee541962d58","proto":"HTTP/1.1","status":500,"size":98,"start":"10/Nov/2022:12:10:20 +0000","end":"10/Nov/2022:12:10:20 +0000","time_ns":8793417,"time":"2022-11-10T12:10:20.375181713Z","message":"http"}`

**Comment by SwikritiT** [comment]
The bug is a little bit different now. We can download the folder from the public link of a `space` but not from the folder inside the space.

1. create space `space`
2. create a folder inside the space `test-folder/new-folder`
3. create a public link for the folder `test-folder` 
4. navigate to the public link and try to download folder `new-folder`

Expectation: It should work

Actual behavior: It doesn't

![Screenshot from 2022-12-15 09-38-45](https://user-images.githubusercontent.com/41103328/207769113-845e82f1-6b7f-4433-a9ed-d0280981dbcf.png)

server log:
```console
web_ocis  | 2022-12-15T03:52:28Z ERR error when calling Createhome error="gateway: grpc failed with code CODE_PERMISSION_DENIED" service=proxy
web_ocis  | 2022-12-15T03:52:28Z ERR error resolving reference resource_id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"b2c80be1-8310-45fc-b015-4af21af6aaf4" space_id:"06ed60a3-0a98-4f7c-9914-c0daf30ab17d" > path:"."  under scope publicshare:OfPYouacfcxXXjB error="error: permission denied: access forbidden via public link" pkg=rgrpc service=gateway traceid=00000000000000000000000000000000
web_ocis  | 2022-12-15T03:52:28Z ERR error resolving reference resource_id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"b2c80be1-8310-45fc-b015-4af21af6aaf4" space_id:"06ed60a3-0a98-4f7c-9914-c0daf30ab17d" > path:"."  under scope publicshare:OfPYouacfcxXXjB error="error: permission denied: access forbidden via public link" pkg=rgrpc service=gateway traceid=00000000000000000000000000000000
web_ocis  | 2022-12-15T03:52:28Z ERR unary code=PermissionDenied end="15/Dec/2022:03:52:28 +0000" from=tcp://127.0.0.1:49962 pkg=rgrpc service=gateway start="15/Dec/2022:03:52:28 +0000" time_ns=2883858 traceid=00000000000000000000000000000000 uri=/cs3.storage.registry.v1beta1.RegistryAPI/ListStorageProviders user-agent="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
web_ocis  | 2022-12-15T03:52:28Z ERR error: not found: gateway could not find space for ref=resource_id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"b2c80be1-8310-45fc-b015-4af21af6aaf4" space_id:"06ed60a3-0a98-4f7c-9914-c0daf30ab17d" > path:"."  pkg=rhttp service=frontend
```

ocis started with image: `owncloud/ocis:latest`

**Comment by SwikritiT** [comment]
> QA:
> 
> * [ ]  Check if we have tests for it or not. If not add the test

I couldn't find any tests, I'll add some

**Comment by SwikritiT** [comment]
> @micbar @aduffeck The bug is a little bit different now. We can download the folder from the public link of a `project space` but not from the folder inside the project space.
> 
> 1. create project space `test-space`
> 2. create a folder inside the project space `test-folder/new-folder`
> 3. create a public link for the folder `test-folder`
> 4. navigate to the public link and try to download folder `new-folder`
> 
> Expectation: It should work
> 
> Actual behavior: It doesn't
> 
> ![Screenshot from 2022-12-15 09-38-45](https://user-images.githubusercontent.com/41103328/207769113-845e82f1-6b7f-4433-a9ed-d0280981dbcf.png)
> 
> server log:
> 
> ```
> web_ocis  | 2022-12-15T03:52:28Z ERR error when calling Createhome error="gateway: grpc failed with code CODE_PERMISSION_DENIED" service=proxy
> web_ocis  | 2022-12-15T03:52:28Z ERR error resolving reference resource_id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"b2c80be1-8310-45fc-b015-4af21af6aaf4" space_id:"06ed60a3-0a98-4f7c-9914-c0daf30ab17d" > path:"."  under scope publicshare:OfPYouacfcxXXjB error="error: permission denied: access forbidden via public link" pkg=rgrpc service=gateway traceid=00000000000000000000000000000000
> web_ocis  | 2022-12-15T03:52:28Z ERR error resolving reference resource_id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"b2c80be1-8310-45fc-b015-4af21af6aaf4" space_id:"06ed60a3-0a98-4f7c-9914-c0daf30ab17d" > path:"."  under scope publicshare:OfPYouacfcxXXjB error="error: permission denied: access forbidden via public link" pkg=rgrpc service=gateway traceid=00000000000000000000000000000000
> web_ocis  | 2022-12-15T03:52:28Z ERR unary code=PermissionDenied end="15/Dec/2022:03:52:28 +0000" from=tcp://127.0.0.1:49962 pkg=rgrpc service=gateway start="15/Dec/2022:03:52:28 +0000" time_ns=2883858 traceid=00000000000000000000000000000000 uri=/cs3.storage.registry.v1beta1.RegistryAPI/ListStorageProviders user-agent="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
> web_ocis  | 2022-12-15T03:52:28Z ERR error: not found: gateway could not find space for ref=resource_id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"b2c80be1-8310-45fc-b015-4af21af6aaf4" space_id:"06ed60a3-0a98-4f7c-9914-c0daf30ab17d" > path:"."  pkg=rhttp service=frontend
> ```
> 
> ocis started with image: `owncloud/ocis:latest`

created new issue here https://github.com/owncloud/ocis/issues/5229

**Comment by SwikritiT** [comment]
> QA:
> 
> * [x]  Check if we have tests for it or not. If not add the test -> tests added in [[tests-only][full-ci]Add api tests public link folder download #5232](https://github.com/owncloud/ocis/pull/5232)

Tests to cover this has been added.
