### ISSUE TITLE
[API] user can share `space` to group

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#5036]
## Describe the bug
The user cannot share (add members in) `space` with `group` using the webUI. But through `API` request user can share `space` with `group`.

## Steps to reproduce

1. Create user `Alice`, `Brian`, `Carol`
2. As `admin`, create group `group1`
3. As `admin`, add users `Brian` and `Carol` to group `group1`
4. As `admin`, give `Space Admin` role to user `Alice`
5. As `Alice` create space `share space`
6. As `Alice`, share space `share space` to group `group1`

## Expected behavior
Sharing space with the group is not allowed
HTTP status code must be 4XX

## Actual behavior
Sharing space to the group is possible through API request
HTTP status code `200`
All the group members can see the shared space and elements in the space.

API request was sent using postman and generated curl request is
```feature
curl -L -X POST "https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares" \
-H "Authorization: Basic YWxpY2U6MTIzNDU2" \
-H "Content-Type: application/x-www-form-urlencoded" \
--data-urlencode "space_ref=1284d238-aa92-42ce-bdc4-0b0000009157$76ab09b7-0c7e-4bf7-b6a3-282ff9fc5005" \
--data-urlencode "shareType=7" \
--data-urlencode "shareWith=group2" \
--data-urlencode "role=viewer"
```
Acceptance test  build: https://drone.owncloud.com/owncloud/ocis/16757/43/6
<details>
<summary>Acceptance test scenario</summary>

```feature
Scenario Outline: A user share a space to group
    Given group "group2" has been created
    And the administrator has added a user "Brian" to the group "group2" using GraphApi
    And the administrator has added a user "Bob" to the group "group2" using GraphApi
    When user "Alice" shares a space "share space" to group "group2" with role "<role>"
    Then the HTTP status code should be "200"
    And the OCS status code should be "200"
    And the OCS status message should be "OK"
    And the user "Brian" should have a space called "share space" with these key and value pairs:
      | key       | value       |
      | driveType | project     |
      | id        | %space_id%  |
      | name      | share space |
    And the user "Bob" should have a space called "share space" with these key and value pairs:
      | key       | value       |
      | driveType | project     |
      | id        | %space_id%  |
      | name      | share space |
    Examples:
      | role    |
      | manager |
      | editor  |
      | viewer  |
```
</details>

## Setup

<details>
<p>

```console
OCIS=latest master
```

</p>
</details>

**Comment by phil-davis** [comment]
why is this a problem?
I suppose it is a bit unnecessary for the whole space to be shared with a group (or with individual users). Alice can grant the group (or individual users) a role for the space (Viewer, Editor etc), and that is the "spaces" way of giving "root level" access to the space.

Is there a requirement somewhere that the root of a space cannot be shared to a group (or an individual user)?

**Comment by micbar** [comment]
@phil-davis @grgprarup This is not directly a problem. More like "unexpected" functionality. In the WebUI, sharing a space to a group doesn't work.

This is a very appreciated feature, but I doubt that it is implemented cleanly covering the corner cases (user is member more than one group, user is also member via user share, which permissions to use when we "merge" them and so on)

@butonic @dragotin any opinion?

**Comment by pasnox** [comment]
I think the general issue is wrong.
The reporter states than users should not be able to share spaces to groups, and that the api allow that (the web ui does not).
In reality, the web ui suggest you CAN share spaces to USERS and GROUPS, it just does not works from the web UI, so the api is correct. The issue is the web UI.
You can notice that it is expected to works by reading the inline doc in the share box (clicking the "?" link), it is stated we can share to users and groups.
So for me the issue is that web ui should make sharing to groups working correctly.

**Comment by grgprarup** [comment]
> I think the general issue is wrong. The reporter states than users should not be able to share spaces to groups, and that the api allow that (the web ui does not). In reality, the web ui suggest you CAN share spaces to USERS and GROUPS, it just does not works from the web UI, so the api is correct. The issue is the web UI. You can notice that it is expected to works by reading the inline doc in the share box (clicking the "?" link), it is stated we can share to users and groups. So for me the issue is that web ui should make sharing to groups working correctly.

Thank you for the clarification. So the problem is with WebUI, and the current behavior of API is an expected feature `the user can share space with the group`. API test has been added in PR https://github.com/owncloud/ocis/pull/5023 with current behavior. So, can we close this issue and create a new issue in the web repo?

**Comment by individual-it** [comment]
@grgprarup please create an issue in web and here create tests with all corner cases, that will show what is already implemented and what not
