### ISSUE TITLE
[release] Bring account management permissions into ocis

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#504]
Steps necessary for bringing account management into ocis:

- [x] ocis-settings:
  - [x] merge https://github.com/owncloud/ocis-settings/pull/66 (minor fixes for saving and fetching values)
  - [x] merge https://github.com/owncloud/ocis-settings/pull/59 (new endpoints for permissions + let ListRoles be filtered by given set of roleIDs)
  - [x] merge https://github.com/owncloud/ocis-settings/pull/67 (service handler mocks)
  - [x] update to ocis-settings@master in ocis-proxy
  - [x] merge https://github.com/owncloud/ocis-settings/pull/69 (use roleIDs from metadata context)
  - [x] update to ocis-settings@master in ocis

- [x] ocis-proxy
  - [x] merge https://github.com/owncloud/ocis-proxy/pull/95 (fetch role ids and write them into access token)
  - [x] update to ocis-proxy@master in ocis

- [x] ocis-pkg
  - [x] merge https://github.com/owncloud/ocis-pkg/pull/59 (roleIDs into context helper + roles cache + roles cache update middleware)
  - [x] update to ocis-pkg/v2@master in ocis-accounts

- [x] ocis-accounts:
  - [x] merge https://github.com/owncloud/ocis-accounts/pull/95 (assign user role as default role on account provisioning)
  - [x] merge https://github.com/owncloud/ocis-accounts/pull/102 (assign user as default role for builtin users (einstein, marie, richard) + add a new user `Maurice Moss` and assign admin role)
  - [x] merge https://github.com/owncloud/ocis-accounts/pull/100 (use roles cache for doing permission checks)
  - [x] update to ocis-accounts@master in ocis

Kind of related to the recent changes in ocis-settings:
- [x] ocis-hello:
  - [x] merge https://github.com/owncloud/ocis-hello/pull/85 (adapt to new settings data model and bring permissions)
  - [x] update to ocis-hello@master in ocis

AFTER merge of the ocis PR:
- change ocis branch and commit-id in .drone.star to master@latest in
  - [x] ocis-accounts
  - [x] ocis-settings

**Comment by kulmann** [comment]
PR is this: https://github.com/owncloud/ocis/pull/505

**Comment by kulmann** [comment]
Approach to inject a dynamic menu item for the ocis-accounts UI based on permissions doesn't work from within the accounts js app, because it doesn't get loaded until the user navigates into it. So we need yet another approach. Rewire how the external apps are loaded in phoenix.

cc @PVince81

**Comment by PVince81** [comment]
@LukasHirt can you confirm ? I seem to remember that any app can register dynamic items even before one navigates to.

it does require pre-loading the app.

@kulmann is it possible to preload the app then?

**Comment by PVince81** [comment]
otherwise dynamic app icons in app switcher don't make much sense

**Comment by LukasHirt** [comment]
> can you confirm ? I seem to remember that any app can register dynamic items even before one navigates to.

All nav items should be loaded even before visiting the extension. We are however filtering them. https://github.com/owncloud/phoenix/blob/master/src/store/navigation.js

**Comment by kulmann** [comment]
That is only true for the nav items that are statically defined in code in the respective `app.js`, `default.js` or whatever it is called in the respective app. We cannot work with Promises in that part of the code, so no possibility to provide a nav item only if a permission exists. Can you confirm that @lhirt ? Because then we need to come up with another way of loading the nav items. If we can use Promises in that code, please show me how it's done :-)

**Comment by LukasHirt** [comment]
Hmm, right. We'd need to introduce some function to inject them. Since it's in the store it could be done quite easily be calling some mutation from within accounts extension.
