### ISSUE TITLE
Integrations: Infinite Scale DICOM

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#5055]
This is an example for an integration/extension project with Infinite Scale.

The [DICOM server orthanc](https://www.orthanc-server.com)  is a successful and mature open source DICOM server that stores and manages medical images. It is very well documented and commercial support is offered.

Orthanc offers a variety of REST APIs and a plugin structure which allow implementation of storage backends. With that, the following integrations could be built:
1. Orthanc uses Infinite Scale as storage backend leveraging Infinite Scales WebDAV API. Dicom files are organized by spaces to (for example) reflect the medical organization / units. 
2. Orthanc authentication uses OIDC
3. The DICOM Viewer is integrated with the ownCloud Web extension system
4. ownCloud Web displays DICOM metadata if clicked on a DICOM file

More ideas to come?

**Comment by gedw99** [comment]
DICOM support . That’s really useful . +1 from me

**Comment by rhafer** [comment]
The DICOM viewer has been implemented meanwhile: https://github.com/owncloud/web-app-dicom-viewer
