### ISSUE TITLE
[Performance] 2nd upload of 10k files much much slower than 1st upload

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#5062]
## Describe the bug

When a upload the 10k files from https://github.com/owncloud/ocis/issues/5061 a 2nd time (new sync run), the performance is horrible.

## Steps to reproduce

1. Create 1000x small files in a folder `for n in {0..999}; do dd if=/dev/urandom of=random$( printf %03d "$n" ).file bs=1 count=$(( RANDOM + 1024 )); done`
2. Duplicate this folder 10x
3. Sync all this files in a single sync run with 3.0-prerelease desktop client
4. Wait a bit
5. Duplicate the folder, which triggers a new sync run

## Expected behavior

2nd upload of 10k files shouldn't be slower than first upload.

## Actual behavior

2nd upload is horrible slow.

![Picture 1](https://user-images.githubusercontent.com/214010/202157732-31f85be6-5098-4fa2-8a7d-47c0fc0b09fa.png)

### oCIS Server:

https://ocis.owncloud.com/

### Desktop Client

```
% /Applications/owncloud.app/Contents/MacOS/owncloud --version
ownCloud ownCloud 3.0.0.9105-daily20221115
https://github.com/owncloud/client/commit/4614194ca6295c00f21e573565c643e0bfc472b0
Libraries Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022
Using virtual files plugin: suffix
osx-21.5.0
```

Desktop was started this way:
```
QT_LOGGING_RULES='*=false;sync.httplogger=true' \
/Applications/owncloud.app/Contents/MacOS/owncloud \
--logdebug --logflush --logfile ~/upload.log --showsettings
```

Desktop client was running on Mac mini in Hetzner datacenter. (1 Gbit/s)

## Additional context

Desktop log uploaded here:
- https://cloud.owncloud.com/index.php/f/5924519

**Comment by butonic** [comment]
We need to double check that the search service is the culprit:
- https://github.com/owncloud/ocis/issues/5063
- or redo these tests without starting the search service

We deliberately made the search service discover changes in a space by starting at the root and descending into changed directories: https://github.com/owncloud/ocis/pull/4777/files

We also increased the debounce time to wait at least a second before stariting to index the space: https://github.com/owncloud/ocis/pull/4964

Finally, we made the search service only run one indexer per space: https://github.com/owncloud/ocis/pull/5001

At some point we have to index. I do not see an easy way to give requests by the search service less priority. 

AFAICT the read requests and the update requests are fighting for locks. I think we can mitigate a lot of syscall by caching the node metadata in memory and using a single stat call to invalidate the cache. This would be similar to how the jsoncs3 provider caches the data. I did start moving all metadata properties into the node struct in https://github.com/cs3org/reva/pull/3261 but it bitrotted as the GA became more pressing.

@aduffeck might have an opinion on what currently happens in the code.

IMO the search service is using ListConstainer to read directories while the client is uploading files. Every upload propagates to the root. the decomposedfs is reading nodes by id ... all the nodes are in the same space ... spread out over several subdirs ... 🤔

**Comment by michaelstingl** [comment]
> * or redo these tests without starting the search service

Happy to re-test, but I'd need help with a simpler way to generate such graphs. Dashboard? Script that parses the desktop log files?

**Comment by butonic** [comment]
to reproduce the graphs in jaeger on `v2.0.0-rc.1` I uploaded 1k files, paused the sync, copied another 1k files and unpaused the sync with the testclient:

![image](https://user-images.githubusercontent.com/956847/203816015-33d77622-4a10-487e-af8b-2e43e67ff50f.png)

I then did this again with the search service disabled

![image](https://user-images.githubusercontent.com/956847/203815931-6eb5c0e2-385c-469c-9a4f-736307d7d620.png)

And then using ocis master (with search enabled) using only 500 files:

![image](https://user-images.githubusercontent.com/956847/203816301-0db0870b-0bc0-496b-8ca8-2cf2c49a394e.png)

As you can see there are more outliers, but overall not nearly as bad as in `v2.0.0-rc.1`

**Comment by micbar** [comment]
@dragotin @michaelstingl @tbsbdr @hodyroff  I think this is enough for GA.

Lets unblock this.

**Comment by dragotin** [comment]
What I see is: With latest master, in the second run *most* of the request are still very fast, only a few are breaking out up to 500 msec.
If that interpretation is correct, I think that is an awesome result.

**Comment by tbsbdr** [comment]
> Lets unblock this.

yes, results look GA ready.

**Comment by micbar** [comment]
Ok, closing. We will improve metadata handling in the decomposedFS further.
