### ISSUE TITLE
storage uuids are not randomized with init

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#5064]
Currently every deployment uses tha same uuid for the users storage ... that is a non starter for a federated deployment.

We have to initialize the Storageid for the users storage (which in fact currently also is our project storage ... so it is already misused, but that is a separate issue) so that it is possible to determine the storageprovider and distinguish an which instance a space is located ...

https://github.com/owncloud/ocis/blob/da1c18afd8934db1fe7cde89e1e0e9197f33a6c0/services/gateway/pkg/revaconfig/config.go#L130 needs to be made configurabe and set to a random uuid with init

### All WebDAV urls will change

The providerID is the first part of the ID string in the url. It will change from the existing hardcoded uuid (`1284d238-aa92-42ce-bdc4-0b0000009157`) to a new random uuid.

```diff
- "webDavUrl": "https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51"
+ "webDavUrl": "https://localhost:9200/dav/spaces/bc631809-54a9-4b1e-9d6e-d9bdf5088eab$4c510ada-c86b-4815-8820-42cdf82c3d51"
```
#### Consequences for Clients

- Web: Can handle it
- iOS: Can handle it
- Android: not known
- Desktop: All sync connections need to be recreated

### Alternative Solution

- Fallback to the existing mount ID
- This is not a good approach IMO, we really risk to have a lot of storage providers out there with the same ID
- Later migrations will be even more painful

**Comment by micbar** [comment]
@michaelstingl @TheOneRing This would become a problem for all existing sync connections for the desktop because all WebDAV Urls will change.

**Comment by michaelstingl** [comment]
@micbar could you post the full information of a Space before and after this change from the Graph API?

**Comment by micbar** [comment]
@wkloucek what is the gain of value?

If we do it now, only a few people need to recreate the desktop sync.

If we do nothing now, we would have thousands of storage providers out there which all have the same provider id. This will explode and cause a lot of painful migrations.

**Comment by butonic** [comment]
The problem I see with the hardcoded UUID for the storageprovider is that we will get collisions of storage provider ids that exist in multiple ocis deployments. hmmm ... clients will have to deal with that anyway because there might be malicious instances that could reuse the storageid of a resoucre to try and confuse clients to send them data ...

the current  user storage uuid was handcrafted by me to contain the port number at the end ... to make debugging easier ... but the idea was always to initialize with a unique identifier.

while cern is using human readable names I am strongly recommending uuids because we will run into merge scenarios. And for those provider id collisions ... suck big time. Maybe I overthought this. But I have been ther and I don't want to start rolling out ocis deployments with the same fallback uuid everywhere.

I would change the uuid now.
