### ISSUE TITLE
Is it possible to add some additional options from config.json to docker-compose?

### ISSUE THREAD

**Issue by rtest12** [owncloud/ocis#5081]
The site describes various variables that can be configured in config.json, but how do you use them in docker? I've looked all over but couldn't find anything about this. Thank you.

**Comment by rtest12** [comment]
I saw it, but there is not much there, for example, all the parameters from this page are missing
https://owncloud.dev/clients/web/getting-started/

**Comment by pascalwengerter** [comment]
> I saw it, but there is not much there, for example, all the parameters from this page are missing https://owncloud.dev/clients/web/getting-started/

I think that's mixing it up a bit (or maybe I'm wrong here also), but `web` _project_ gets configured using a config file (the link you provided) and then gets delivered from the _oCIS web service_ (https://owncloud.dev/services/web/configuration/) where you can e.g. use an env var to link to your `config.json`

**Comment by rtest12** [comment]
> config.json

That is, I can add my own config.json to .yml file (and how to spell it correctly?), but can I add only those parameters that I need in the config.json file itself, without having to manually do the entire config?

**Comment by pascalwengerter** [comment]
> > config.json
> 
> That is, I can add my own config.json to .yml file (and how to spell it correctly?), but can I add only those parameters that I need in the config.json file itself, without having to manually do the entire config?

Let me add @kulmann here because he has the best insights into how this is going to evolve in the near future I suppose :)

**Comment by kulmann** [comment]
Hey @rtest12 there is a list of env variables for the `web` service here:
https://doc.owncloud.com/ocis/next/deployment/services/s-list/web.html

It shows some env vars which can be used to modify values inside the default config.json that's shipped by oCIS. More specifically:
- `WEB_UI_CONFIG_SERVER` for setting the server URL (also set by `OCIS_URL`)
- ... and the OIDC config values:
  - `WEB_OIDC_METADATA_URL` for the well known endpoint
  - `OCIS_OIDC_ISSUER` for the oidc issuer
  - `WEB_OIDC_CLIENT_ID` for the web client id
  - `WEB_OIDC_RESPONSE_TYPE` for the oidc response type
  - `WEB_OIDC_SCOPE` for the scopes that you want to request from the idp

More env vars could be added here as needed: https://github.com/owncloud/ocis/blob/master/services/web/pkg/config/config.go#L34

Are there any specific value(s) you're looking for?
