### ISSUE TITLE
Group having percentage (%) can be created but cannot be GET

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#5083]
## Describe the bug

A group having only `%` as a special character in its name can be created but cannot GET it.

**NOTE**: but if the group name has more other special characters then GET request works
For Example:
`50%pass` -> GET fails :x:
`50%pass+pass` -> GET works :heavy_check_mark: 

## Steps to reproduce

1. Create a group with % in its name
```bash
 curl -XPOST "https://localhost:9200/graph/v1.0/groups" -d'{"displayName":"50%pass"}' -uadmin:admin -vk
```
```bash
< HTTP/1.1 200 OK
< Content-Length: 70
< Content-Type: application/json; charset=utf-8
< Date: Mon, 21 Nov 2022 04:57:06 GMT
< X-Graph-Version: 2.0.0-rc.1+1329daffc
< 
{
  "displayName": "50%pass",
  "id": "e643c421-ff19-44fa-839d-9e419889441d"
}
```
2. try to GET the group (`url encoded groupname`)
```bash
curl "https://host.docker.internal:9200/graph/v1.0/groups/50%25pass" -uadmin:admin -vk
```

## Expected behavior
to GET group details

## Actual behavior
400 bad request
```bash
< HTTP/1.1 400 Bad Request
< Content-Length: 322
< Content-Type: application/json; charset=utf-8
< Date: Mon, 21 Nov 2022 04:57:49 GMT
< X-Graph-Version: 2.0.0-rc.1+1329daffc
< 
{
  "error": {
    "code": "invalidRequest",
    "innererror": {
      "date": "2022-11-21T04:57:49Z",
      "request-id": "cc648ecd9a72/vFtv8pfDzE-001490"
    },
    "message": "unescaping group id failed"
  }
}
{
  "error": {
    "code": "invalidRequest",
    "innererror": {
      "date": "2022-11-21T04:57:49Z",
      "request-id": "cc648ecd9a72/vFtv8pfDzE-001490"
    },
    "message": "missing group id"
  }
}
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by rhafer** [comment]
It  looks like `chi` is alreay unescapeing the URLParams for us and we're trying to unescape an already unescaped URL param (https://github.com/owncloud/ocis/blob/master/services/graph/pkg/service/v0/groups.go#L104)

Need to take a closer look as we're doing this a quite a few more places than just the groups API.

**Comment by Excds** [comment]
> It looks like `chi` is alreay unescapeing the URLParams for us and we're trying to unescape an already unescaped URL param (https://github.com/owncloud/ocis/blob/master/services/graph/pkg/service/v0/groups.go#L104)

So, there is some inconsistency on _if_ decoding happens automatically or not. Found a chi issue which seems related to this: https://github.com/go-chi/chi/issues/641

Tested adding a _very stupid_ workaround:
```
func maybeDecode(r *http.Request, param string) (string, error) {
	if r.URL.RawPath != "" {
		return url.PathUnescape(param)
	}

	return param, nil
}
```
Sure, this solves the problem, but it seems to me like a quite not so nice way to go. WDYT @rhafer?
