### ISSUE TITLE
[Theming] Make the web theming endpoint an official oCIS theming endpoint, so other clients could use it too

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#5090]
## Is your feature request related to a problem? Please describe.

There are use cases, where clients should get some theming information dynamically from the connected server. That's how the decoupled web frontend works, but other clients could use it as well.

## Describe the solution you'd like

Make the web theming endpoint an official oCIS theming endpoint, so other clients could use it too

## Describe alternatives you've considered

Otherwise it would need a new endpoint

## Additional context

Web docs:
https://owncloud.dev/clients/web/theming/

**Comment by micbar** [comment]
Closing, outdated
