### ISSUE TITLE
[ocis] Rename groups

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#5099]
## Describe the bug

Renaming group display name doesn't work

## Steps to reproduce

1. create a new group
```bash
curl -XPOST "https://host.docker.internal:9200/graph/v1.0/groups" -d'{"displayName":"grp1"}' -uadmin:admin -vk
```
2. Check the newly created group and get the group-id
```bash
curl "https://host.docker.internal:9200/graph/v1.0/groups" -uadmin:admin -vk
```
3. Rename the group
```bash
curl -XPATCH "https://host.docker.internal:9200/graph/v1.0/groups/7950285f-536d-4925-bbae-39831e2845fc" \
-d'{"displayName": "group101"}' -uadmin:admin -vk
```
```bash
< HTTP/1.1 204 No Content
< Date: Wed, 23 Nov 2022 08:59:17 GMT
< X-Graph-Version: 2.0.0-rc.1+0d6a99331
<
```
4. Check the groups (:x: group name has not been changed)

## Expected behavior
expected that the group is changed to new name

## Actual behavior
group name is not changed

## Setup

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by rhafer** [comment]
Hm, currently renaming a group is not supported ;-( . We don't support LDAP ModRDN (the rename operation) yet. The 204 status code is wrong.

**Comment by ScharfViktor** [comment]
will this be implemented in the future? Now I don't even know if we need tests that fail

**Comment by rhafer** [comment]
> will this be implemented in the future?

I hope so.

**Comment by rhafer** [comment]
Update the ModRDN operation is now supported in libregraph-idm (https://github.com/owncloud/ocis/pull/5618).

Group renames however are still not implemented.

**Comment by ScharfViktor** [comment]
failed tests  for editing group as `$x<=>[y*z^2]!` and `50%pass` still exist

I could reproduce it localy. we get 204 but groupName didn't change
