### ISSUE TITLE
Share via link cannot be set to `Internal` role

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ocis#5107]
## Describe the bug
Share via link cannot be set to `Internal` role

## Steps to reproduce

1. Create a file
2. Create a Quicklink
3. Try to change the role to `Internal`

## Expected behavior
Changing the Quicklink to `Internal` works

## Actual behavior
Changing to `Internal` role is not possible
![image](https://user-images.githubusercontent.com/33026403/203551415-8cbbd165-874c-46ac-a488-d973a3fed1f6.png)

![image](https://user-images.githubusercontent.com/33026403/203552075-e716cccb-faee-49a9-b3b6-d386aa3d4c89.png)

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

oCIS 2.0.0 RC1
ownCloud Web 6.0.0 RC6

</p>
</details>

**Comment by tbsbdr** [comment]
@kulmann GA-blocker or this already known?

**Comment by ChrisEdS** [comment]
Not reproducible on master. Sorry for the noise.
