### ISSUE TITLE
Release branches for documentation

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#5160]
We need release branches for each ocis-Release.

**Proposal**

When we make a release we branch the current output in the format `docs-stable-vX.X` and in additon we create a tag on the docs branch in the format `docs-vX.X`. The tag and the head of the new branch must represent the documentation of the release in the `stable-vX.X` branch and the `vX.X` release tag. The branches & tags should be created automatically via the CI.

/cc @mmattel

**Comment by mmattel** [comment]
We currently have for 2.0 a release branch for docs `docs-stable-2.0`.
Same as we have for ocis `stable-2.0`

I do not know if there is already a process implemented that a new docs branch is created when a new stable version is released.

**Comment by micbar** [comment]
This is a manual process. But implemented :-)
