### ISSUE TITLE
Set default quota for new users

### ISSUE THREAD

**Issue by dorianim** [owncloud/ocis#5178]
## Is your feature request related to a problem? Please describe.
We are planning to set up OCIS with an existing identity provider (Keykloak). All users registered there will be able to create an account in OCIS. Per default, they have an infinite quota, which we'd like to restrict.

## Describe the solution you'd like
An environment variable / config option like `GRAPH_SPACES_DEFAULT_QUOTA` but for the personal quota of new users.

**Comment by shishouyuan** [comment]
I like this. 

Besides, it would great to have a global default group that all users belong to, so that we can share files with `EVERYONE`. 

By the way, I found there is an option called `role_quotas` with the proxy servcie. Is it a little bit strange to be set in proxy service?
