### ISSUE TITLE
enable sharing tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#518]
- [ ] core API tests
- [ ] Phoenix UI tests

Questions to discuss:
1. in ocis every share needs to be accepted first, how should we deal with that in the tests
    1. make the step `Given parameter "shareapi_auto_accept_share" of app "core" has been set to "yes"` set some flag, so that the tests know to accept shares without it being mentioned in the Gherkin
    2. duplicate tests
2. in OCIS shares are accessible via the `Shares` folder. 
    1. make the test be aware of that, so that it does not need to be mentioned in the Gherkin. But how to deal with when the tests check the existence of files/folders? The test code would have to know that this particular item is to be expected in the Shares folder or outside. 
    2. add `%SharesFolder%` in front of every item that is expected to be a Share, in ocis-tests substitute that to `Shares`. This would not work for tests that expect the receiving item to ass `(2)` to the name if an item with the same name exists
    3. duplicate tests

CC @phil-davis @dpakach @PVince81 @kulmann

**Comment by phil-davis** [comment]
Also see https://github.com/owncloud/ocis-reva/issues/415 - which is a more general issue to enable as many API test scenarios as "reasonable" so that they are run in CI, listed in expected-failures and "ready to be made to pass"

**Comment by phil-davis** [comment]
Note: PR https://github.com/owncloud/core/pull/37774 did enable a small number tests that happened to pass.

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/37881 has the way forward for this. It creates new sharing scenarios that have `share_folder` set to `Shares` and auto-accept of shares off. That corresponds to the default OCIS settings. Those new scenarios run on both ownCloud10 and OCIS. See the PR for a detailed description of what is done with tags, scenario background, accepting received shares etc.

This issue can now be assigned to someone to do similar with the remaining sharing API tests.

**Comment by phil-davis** [comment]
I moved this to ToDo in Sprint 20-17 because there seems be no other sprint to choose.

**Comment by HariBhandari07** [comment]
- [ ] apiShareReshare1

- [ ] apiShareReshare2

- [ ] apiShareReshare3

**Comment by phil-davis** [comment]
@HariBhandari07 please also assign anyone else who is working on this.

**Comment by dpakach** [comment]
### WebUI Tests

- [ ] webUIResharing
- [ ] webUIRestrictSharing
- [ ] webUISharingAcceptShares
- [ ] webUISharingAutocompletion
- [ ] webUISharingExternal
- [ ] webUISharingFilePermissionMultipleUsers
- [ ] webUISharingFilePermissionsGroups
- [ ] webUISharingFolderAdvancedPermissionMultipleUsers
- [ ] webUISharingFolderAdvancedPermissionsGroups
- [ ] webUISharingFolderPermissionMultipleUsers
- [ ] webUISharingFolderPermissionsGroups
- [ ] webUISharingInternalGroups
- [ ] webUISharingInternalUsers
- [ ] webUISharingNotifications
- [ ] webUISharingPermissionsUsers

**Comment by dpakach** [comment]
## Webui tests to enable in CI
- [ ]  webUIResharing
- [ ]  webUIRestrictSharing
- [ ]  webUISharingAcceptShares
- [ ]  webUISharingAutocompletion
- [ ]  webUISharingExternal
- [ ]  webUISharingFilePermissionMultipleUsers
- [ ]  webUISharingFilePermissionsGroups
- [ ]  webUISharingFolderAdvancedPermissionMultipleUsers
- [ ]  webUISharingFolderAdvancedPermissionsGroups
- [ ]  webUISharingFolderPermissionMultipleUsers
- [ ]  webUISharingFolderPermissionsGroups
- [ ]  webUISharingInternalGroups
- [ ]  webUISharingInternalUsers https://github.com/owncloud/phoenix/pull/4161
- [ ]  webUISharingNotifications
- [ ]  webUISharingPermissionsUsers https://github.com/owncloud/phoenix/pull/4161
