### ISSUE TITLE
[Feature request] Add a comments / answers / emotions mechanism in the Spaces

### ISSUE THREAD

**Issue by pasnox** [owncloud/ocis#5180]
## Is your feature request related to a problem? Please describe.
The space feature is really good idea, it could be better if comments and emotions support could be added to files, especially images.

## Describe the solution you'd like
Having a way to attach comments / answers to any files in spaces to transform flat spaces into a minimalist social network, by example private galleries for family sharing. 
Also, having a way to add emotions would be awesome as well.

**Comment by hodyroff** [comment]
Thanks for your feedback. One of the questions in our/my mind is if we open a connection to a chat system or really implement this independently ... eg. we could if desired attach an element chat to each space and visualize that ... what do you think?

**Comment by tbsbdr** [comment]
@pasnox could you give an example where this is put into action in a good way to make sure that we are all on the same page?

**Comment by pasnox** [comment]
> Thanks for your feedback. One of the questions in our/my mind is if we open a connection to a chat system or really implement this independently ... eg. we could if desired attach an element chat to each space and visualize that ... what do you think?

I would like focused comments sections PER files, not a whole / global chat.
But the chat idea could comes handy as well, as a way to keep in sync outside the scope of files (but per spaces)

**Comment by pasnox** [comment]
> @pasnox could you give an example where this is put into action in a good way to make sure that we are all on the same page?

Hm, I do not have any example on how this feature would / could looks like. In a first version we could imagine it being implemented as a side box, like the actions, shares etc on the right side. And if it become popular refactor the spaces UI a bit.
Another option could also be just to extends the Preview (ie, introduce a SpacePreview or SocialPreveiw) which operate on he given file where emotion ans comment system would be more friendly.

**Comment by tbsbdr** [comment]
Not planned in the foreseable future; we can reopen if this gets more requests

**Comment by pasnox** [comment]
😱
