### ISSUE TITLE
Login missing, theme.json and openid-configuration net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by rheaalleen** [owncloud/ocis#5185]
## Describe the bug

After setting up a binary installation the login portal never shows and the site stays blank.

theme.json and openid-configuration show as failed in network tab of browser

![ocis](https://user-images.githubusercontent.com/52893816/205617573-80c70ef5-cfcd-4f5e-a64f-0c28378414f9.png)

## Steps to reproduce

Basic installation following https://owncloud.dev/ocis/getting-started/#binaries

## Setup

.env
```
OCIS_BASE_DATA_PATH=/owncloud 
OCIS_INSECURE=false 
PROXY_HTTP_ADDR=0.0.0.0:9200 
OCIS_URL=https://localhost:9200 
PROXY_TLS=false 
```
config.yaml is unchanged since ocis init.

Using no .env files results in the same problem

**Comment by kulmann** [comment]
Hey, for localhost with self signed certificate, please set `OCIS_INSECURE=true` (you have it as `false` in your environment)

**Comment by rheaalleen** [comment]
Hey, forgot to mention. I tried various configurations, including true/false but it didnt change the result.

When I set it to false I get additional errors

![image](https://user-images.githubusercontent.com/52893816/205627755-fab3ab62-c20b-4184-bd18-dc4cf8a29908.png)

Browser Console 

![image](https://user-images.githubusercontent.com/52893816/205627886-1304608c-2207-4036-a8aa-ae0f2c2f704d.png)

**Comment by micbar** [comment]
@rheaalleen Seems that the browser cannot reach the backend.

Can you post your nginx config?

**Comment by micbar** [comment]
Maybe it helps to know that OCIS_URL always needs to point to the exact url and port which is reachable from the outside.

If the nginx runs on :443 than OCIS_URL should point to `https://you-domain.tld`

**Comment by rheaalleen** [comment]
Thanks, some progress. I saw that in in earlier env I had it configured twice, once with IP and another with URL. Guess I missed that and only enabled IP.

Now it shows an Error 400

![image](https://user-images.githubusercontent.com/52893816/205661706-73e3c0be-8931-4cbb-b4c5-a4406f05a9f1.png)

**Comment by micbar** [comment]
I have seen that error in a slightly similar case, @enbrnz Can you remember your experiments with apache as a reverse proxy?

**Comment by Jeansy91** [comment]
Hey, I faced the same issue.
Try adding `proxy_set_header      Origin $scheme://$server_name;` to  `location /`, otherwise it recognizes a mismatch between host and origin.

**Comment by rheaalleen** [comment]
@Jeansy91 Thanks, that brought some progress

Now I get an Error 500

![image](https://user-images.githubusercontent.com/52893816/205833596-e59d3a70-613c-4969-9cb5-fe87614efe33.png)

From a running OCIS instance where I changed nothing except the NGINX header conf suddenly ldap/graph errors

![image](https://user-images.githubusercontent.com/52893816/205833361-5cfe64f4-02b9-48e7-8c74-1c79734532cb.png)

**Comment by rheaalleen** [comment]
I´ve found similar problems in #4520 but no solution

**Comment by C0rby** [comment]
@rheaalleen, could you start ocis with debug log level and post the log output, please?

**Comment by rheaalleen** [comment]
@C0rby Sure, syslog enough or any specific too?

**Comment by rheaalleen** [comment]
syslog filtered for ocis

[syslog.txt](https://github.com/owncloud/ocis/files/10176776/syslog.txt)

**Comment by C0rby** [comment]
Thanks, the syslog is fine. I'll have a look if I can see what went wrong.

**Comment by C0rby** [comment]
Ok, I have a hunch that the configured passwords don't match anymore with the passwords stored in the user storage. This could happen when you regenerate the config `ocis init` without deleting the user storage beforehand.

Could you try a couple of things?
First we have released a stable version of ocis. Could you download and use this one? You can find it here: https://download.owncloud.com/ocis/ocis/stable/2.0.0/

Then could you empty your data directory? `/owncloud` in your case.
And then run the `ocis init` command again. This will recreate the technical users in the storage (`/owncloud`) and the config file `ocis.yaml`.

After that the config should be in sync with the stored users and you should hopefully be able to log in.

**Comment by rheaalleen** [comment]
Huzzah, success.

After a quick reconfiguration of my LXC (mounted a SMB instead of NFS) I can now say its working.

Guess the DATA_DIR env variable is at the same time misleading and doing what is says. I was under the impression this only affects the data (uploaded stuff) itself and not the whole data of OCIS. Of course this would stay consistent every time I remade the LXC and mounted the share again, leaving old data intact and not useable by new OCIS.

Now to get Authentik as IDP working.

Thanks 
@C0rby
@Jeansy91
@micbar

**Comment by C0rby** [comment]
Glad to hear that it works now. :+1:
