### ISSUE TITLE
Make the virtual "Shares" Space permanent

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#5190]
## Is your feature request related to a problem? Please describe.

Having the virtual "Shares" Spaces appear and disappear all the time is a horrible user experience for users of the desktop client.

The biggest problems:

### 1) New account, where user didn't receive or didn't accept a share yet

Current desktop app doesn't add new Spaces dynamically and doesn't notify users about new, available Spaces. Only when setting up a new account, all available Spaces get synced locally. When virtual "Shares" Space isn't available from the beginning, some users will probably never find their received Shares.

### 2) User declines the last share or got removed from a share

This leaves the desktop app in a very weird state:

- https://github.com/owncloud/client/issues/10278
- https://github.com/owncloud/client/issues/10285

## Describe the solution you'd like

Virtual "Shares" Space should be permanent from the first time a user connects, and should never disappear later.

## Describe alternatives you've considered

I thought about workaround hacks in the desktop app, but this doesn't sound useful.

## Additional context

Empty, permanent virtual "Shares" Space got removed, I think because of difficulties with eTags.

@micbar I'd like to discuss this again

/cc @HanaGemela @TheOneRing @tbsbdr

**Comment by micbar** [comment]
> Empty, permanent virtual "Shares" Space got removed, I think because of difficulties with eTags.

It was removed on request of some team, I don't remember exactly why. Let us make a decision before we add / remove this on regular intervals 🙈

**Comment by micbar** [comment]
Decision was made: We need to always have the Share Jail present on the graph and webDav enpoints. Empty Share Jails need an artificial eTag.

**Comment by felix-schwarz** [comment]
@micbar As far as iOS is concerned, you can pick any eTag. Format/length doesn't matter to it.

**Comment by TheOneRing** [comment]
I agree with @felix-schwarz

**Comment by C0rby** [comment]
@TheOneRing @felix-schwarz 
Here is what I have so far:
```
curl -s -k -u admin:admin https://localhost:9200/graph/v1.0/me/drives | jq .
{
  "value": [
    {
      "driveAlias": "personal/admin",
      "driveType": "personal",
      "id": "a22e9474-88b5-45d4-9692-69be6eaa5b69$88c85652-76d0-4265-bbb3-56cf474186ae",
      "lastModifiedDateTime": "2022-12-22T10:24:13.069518955+01:00",
      "name": "Admin",
      "owner": {
        "user": {
          "id": "88c85652-76d0-4265-bbb3-56cf474186ae"
        }
      },
      "quota": {
        "remaining": 235721998336,
        "state": "normal",
        "total": 0,
        "used": 0
      },
      "root": {
        "eTag": "\"eae44aa8f9aab8e76e0b5f2a652ce63a\"",
        "id": "a22e9474-88b5-45d4-9692-69be6eaa5b69$88c85652-76d0-4265-bbb3-56cf474186ae",
        "webDavUrl": "https://localhost:9200/dav/spaces/a22e9474-88b5-45d4-9692-69be6eaa5b69$88c85652-76d0-4265-bbb3-56cf474186ae"
      },
      "webUrl": "https://localhost:9200/f/a22e9474-88b5-45d4-9692-69be6eaa5b69$88c85652-76d0-4265-bbb3-56cf474186ae"
    },
    {
      "driveAlias": "virtual/shares",
      "driveType": "virtual",
      "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
      "name": "Shares",
      "quota": {
        "remaining": 0,
        "state": "exceeded",
        "total": 0,
        "used": 0
      },
      "root": {
        "eTag": "DECAFC00FEE",
        "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
        "webDavUrl": "https://localhost:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668"
      },
      "webUrl": "https://localhost:9200/f/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668"
    }
  ]
}
```

If that is all that is needed I'll open up a PR or do you need any more changes?

**Comment by felix-schwarz** [comment]
I agree that `DECAFBAD` and think `BADEAFFE` would have been more fun, but I don't think it's `BADC0DED` because of that. 🤪

Looks good to me!

**Comment by micbar** [comment]
Needs reva update.

**Comment by michaelstingl** [comment]
Looks good on `https://ocis.ocis-traefik.latest.owncloud.works/`

![CleanShot 2023-02-09 at 16 47 24](https://user-images.githubusercontent.com/214010/217863604-57c7e709-e2ee-4e60-88d8-7d08d7b481e6.png) | ![CleanShot 2023-02-09 at 16 48 40](https://user-images.githubusercontent.com/214010/217863929-f4dcc065-7a5e-4f29-9d71-8cdb646f3db1.png)
-- | --

```
ownCloud Web UI 7.0.0-rc.11 
Infinite Scale 2.0.0+26f7523ff Community 
```
