### ISSUE TITLE
test client VFS with ocis

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#52]
- [x] client does not yet support oidc: https://github.com/owncloud/client/issues/7482
  - emulate oauth2 app?
- [ ] test VFS

**Comment by michaelstingl** [comment]
> [x] client does not yet support oidc: [owncloud/client#7482](https://github.com/owncloud/client/issues/7482)

2.7.0 daily builds fully support oCIS-OIDC :
https://download.owncloud.com/desktop/daily/?sort=time&order=desc

**Comment by michaelstingl** [comment]
> * [ ]  test VFS

VFS should work independent from backend. No backend logic needed.
