### ISSUE TITLE
Apache as a reverse proxy: Unexpected HTTP response: 400

### ISSUE THREAD

**Issue by Orangian** [owncloud/ocis#5212]
Hi,
I've been trying to get the binary release of OCIS 2.0.0 working, but I keep running into the issue where I get "Unexpected HTTP response: 400. Please check your connection and try again." when I successfully log in. Unsuccessfully logging in says that my password is incorrect. Since I'm using a reverse proxy, I've disabled HTTPS, as Apache will take care of that. Even connecting directly (without apache) results in the same error. Here is my ocis.env: 
```
OCIS_INSECURE=true

OCIS_URL=https://DOMAIN:443

#PROXY_URL=http://localhost:9200

INSECURE=true

#OCIS_URL=https://DOMAIN:9200

#PROXY_URL=https://DOMAIN:9200

PROXY_TLS=false

```
Output of journalctl -u ocis: `Dec 09 13:20:31 DOMAIN systemd[1]: Started OCIS server.`

The offending request in Firefox is to `/signin/v1/identifier/_/logon`, with an HTTP 400 in response.

**Comment by Orangian** [comment]
Apologies for closing this. I thought I had it solved, but I did not. I attempted to use the solution presented in [3981](https://github.com/owncloud/ocis/issues/3981), however, that did not work.

**Comment by Orangian** [comment]
It appears that this only occurs when reverse proxied through Apache. It also occurs using self generated certificates, but no longer does when using valid ones. As I would really prefer using Apache as my reverse proxy, it would be greatly appreciated if someone could take a look and tell me what the issue is, as it is going over my head. In issue 3981, it appeared that switching from NGINX to Traefik fixed the issue with the proxy, but I cannot do that in my setup.

Here are the response headers from the browser when encountering the issue:

```
Request URL: https://ocis.qern-industries.pw/signin/v1/identifier/_/logon
Request Method: POST
Status Code: 400 
Remote Address: 24.218.176.144:443
Referrer Policy: strict-origin-when-cross-origin
cache-control: no-cache, no-store, must-revalidate
content-length: 91
content-security-policy: frame-ancestors 'none'
content-type: text/plain; charset=utf-8
date: Sun, 11 Dec 2022 03:09:46 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
last-modified: Sun, 11 Dec 2022 03:09:46 GMT
pragma: no-cache
server: Apache
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: DENY
x-idp-version: 2.0.0
:authority: ocis.qern-industries.pw
:method: POST
:path: /signin/v1/identifier/_/logon
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 200
content-type: application/json
kopano-konnect-xsrf: 1
origin: https://ocis.qern-industries.pw
referer: https://ocis.qern-industries.pw/signin/v1/identifier?client_id=web&code_challenge=IMwb-hXoJ0maxKUVsRh2ZW7WBAuzR2IhekkgEdwLUTQ&code_challenge_method=S256&flow=oidc&redirect_uri=https%3A%2F%2Focis.qern-industries.pw%2Foidc-callback.html&response_mode=query&response_type=code&scope=openid+profile+email&state=b6e07793453f4867be297b95b6323cd3
sec-ch-ua: "Chromium";v="97", " Not;A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

400 Bad Request - invalid redirect_uri: https://ocis.qern-industries.pw/oidc-callback.html

```

**Comment by micbar** [comment]
@Orangian can you post your apache config?

Please try to add `ProxyPreserveHost on`

**Comment by Orangian** [comment]
[Here is the main site config.](https://gist.github.com/Orangian/3c44c9c27c7cbc4318fffa45d90cd49c)
[Here are the SSL settings included on the second to last line.](https://gist.github.com/Orangian/c98c117eaf9b78df27472b41648f6a49)
I'll try oCIS without security config included.

**Comment by Orangian** [comment]
Apologies, however, the same issue occurs even with the linked Apache setup.

**Comment by Orangian** [comment]
I replaced apache2.conf with the default provided by Debian, and the same issue occurs.

**Comment by micbar** [comment]
@Orangian Sorry, i overlooked the real cause of the problem.

I see now that you want to run ocis on `http`. This is the issue. Ocis needs to run on `https` because the bundled openIDconnect provider (libreConnect) does not work on `http`.

It is also best practise to have all service to service connections configured with TLS.

**Comment by Orangian** [comment]
Apologies! It appears that I forgot to inform you that I set it back to using HTTPS during my troubleshooting and still experienced the same issue. As this issue appears to persist no matter what I do, I am going to create a new VM with only oCIS and Apache and report back.

**Comment by Orangian** [comment]
On a brand new Debian 11 VM with Apache2 installed, the error still occurs. The service file was the one copied exactly from the oCIS docs, with oCIS 2.0.0 copied to /usr/local/bin. Attached below are the oCIS.env files, along with the apache virtualhost. Valid certificates were used on a subdomain owned by me. The only deviations from the default Debian apache configuration were the enabling of ocis.conf via a2ensite ocis.conf, as well as enabling the modules proxy, ssl, and proxy_http through a2enmod. 

[The configuration files are here.](https://gist.github.com/Orangian/d67f54e3452e270f9045a80db03553bd)

**Comment by Orangian** [comment]
Moving to Caddy as a reverse proxy, along with Authentik. As others have had success, I expect it to work with them.

**Comment by Orangian** [comment]
Yes, Caddy worked fine. I can post my config in a few hours.

**Comment by TermeHansen** [comment]
@Orangian Suddenly I got through. I think what made the difference now was that I changed:

`OCIS_URL: "https://${OCIS_DOMAIN}:443"
`
to 
`OCIS_URL: "https://${OCIS_DOMAIN}"
`
in the ocis `docker_compose.yaml`.

No special handling in the CaddyFile was needed.
