### ISSUE TITLE
oCIS docker behind apache proxy

### ISSUE THREAD

**Issue by unsalkorkmaz** [owncloud/ocis#5214]
## Is your feature request related to a problem? Please describe.

I love using https://www.virtualmin.com/ for managing my server. Mails, dns, ssl certificates, databases etc.. I believe installing virtualmin on a bare server and then using dockers for unique applications such as self-hosted gitlab or oCIS is best way for a single server management. (I am open to suggestions)

## Describe the solution you'd like

I saw [docker-compose](https://doc.owncloud.com/ocis/next/deployment/deployment/deployment_examples.html#docker-compose) example but it uses traefik as server. I want to see if it is possible  to create an environment with using docker-compose behind an apache  as proxy server.

## Describe alternatives you've considered
I am using [Onlyoffice Workspace](https://www.onlyoffice.com/workspace.aspx) with apache proxy server atm and it works but would love to try oCIS too

**Comment by micbar** [comment]
See #https://github.com/owncloud/ocis/issues/5212

@mmattel We should add a working apache reverse proxy config example.

@enbrnz can provide one

**Comment by enbrnz** [comment]
```
root@ocis:~# cat /etc/apache2/sites-enabled/reverse-proxy-ssl.conf 
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName <SSL_FQDN>
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    ProxyPass / https://127.0.0.1:9200/ #or wherever your ocis is accessible
    ProxyPassReverse / https://127.0.0.1:9200/
    ProxyPreserveHost on #important, otherwise 400 errors from idp

    SSLCertificateFile /path/to/fullchain.pem
    SSLCertificateKeyFile /path/to/privkey.pem
</VirtualHost>
</IfModule>
```

**Comment by mmattel** [comment]
@enbrnz we just have created a documentation for a [small scale systemd based deployment](https://doc.owncloud.com/ocis/next/examples/small-scale.html) using nginx and certbot. Could you help tranforming the nginx + certbot part into apache + certbot? I could then adapt the page accordingly

**Comment by unsalkorkmaz** [comment]
I dont want to open a duplicate topic.. same problem. apache with docker-compose. Your solution is for systemd Service.

**Comment by mmattel** [comment]
A first step is made with systemd. You can speedup things providing content 😃 Add your proposal as issue in the docs-ocis repo, you can use markdown if you want. I will then transform this into antora/asciidoc and embed it into the structure properly.

**Comment by unsalkorkmaz** [comment]
Sorry if this sounds stupid but I have no idea how oCIS works in docker-compose. I wanna try but I only use apache. I cant provide any proposal tbh

**Comment by mmattel** [comment]
We have atm a description for docker and docker compose. The latter has a link to exemples, just take a look into our docs. This is partially very detailed stuff. You can take the reverse proxy part from systemd. A small deployment desription for docker/docker compose needs to be made. Note that even you have ocis up and running, you will have to configure it according your needs, see the docs for details. We are doing our very best describing scenarious, pls be patient, this will take a bit.
