### ISSUE TITLE
Collabora does not survive to a server restart ( oCIS with WOPI server example )

### ISSUE THREAD

**Issue by simone-viozzi** [owncloud/ocis#5215]
## Describe the bug

I followed the WOPI deployment example ( [link1](https://owncloud.dev/ocis/deployment/ocis_wopi/) / [link2](https://doc.owncloud.com/ocis/next/configuration/office-integration.html) ).

The deployment works, but collabora disappear after a server restart.

## Steps to reproduce

1. `git clone https://github.com/owncloud/ocis.git`
2. edit the `.env` file
3. `docker-compose up -d`, collabora works and I can edit docx files ( three dots -> open in collabora) / creating them ( new file -> ... )
4. `docker-compose restart`: everything still works
5. reboot the server
6. collabora disappear from the owncloud web interface, i can no longer open a file in collabora / create an odf / docx file

## Expected behavior

Everything keeps working after a server restart.

## Actual behavior

Collabora integration broke after a server restart.

## Setup

- docker-compose: same as [link](https://github.com/owncloud/ocis/blob/4123c7e2d8e534082a04a51a568b3ed0831c64c6/deployments/examples/ocis_wopi/docker-compose.yml) ( current master )
- config folder: same as current master
- env file:

```env
# If you're on a internet facing server please comment out following line.
# It skips certificate validation for various parts of oCIS and is needed if you use self signed certificates.
INSECURE=false

### Traefik settings ###
# Serve Traefik dashboard. Defaults to "false".
TRAEFIK_DASHBOARD=true
# Domain of Traefik, where you can find the dashboard. Defaults to "traefik.owncloud.test"
TRAEFIK_DOMAIN=traefik.<...>
# Basic authentication for the dashboard. Defaults to user "admin" and password "admin"
TRAEFIK_BASIC_AUTH_USERS=admin:<...>
# Email address for obtaining LetsEncrypt certificates, needs only be changed if this is a public facing server
TRAEFIK_ACME_MAIL=<...>

### oCIS settings ###
# oCIS version. Defaults to "latest"
OCIS_DOCKER_TAG=2.0.0
# Domain of oCIS, where you can find the frontend. Defaults to "ocis.owncloud.test"
OCIS_DOMAIN=ocis.<...>
# oCIS admin user password. Defaults to "admin".
ADMIN_PASSWORD=<...>
# The demo users should not be created on a production instance
# because their passwords are public. Defaults to "false".
DEMO_USERS=

### Wopi server settings ###
# cs3org wopi server version. Defaults to "v8.3.3"
WOPISERVER_DOCKER_TAG=
# cs3org wopi server domain. Defaults to "wopiserver.owncloud.test"
WOPISERVER_DOMAIN=wopiserver.<...>
# JWT secret which is used for the documents to be request by the Wopi client from the cs3org Wopi server. Must be change in order to have a secure Wopi server. Defaults to "LoremIpsum567"
WOPI_JWT_SECRET=<...>

### Collabora settings ###
# Domain of Collabora, where you can find the frontend. Defaults to "collabora.owncloud.test"
COLLABORA_DOMAIN=collabora.<...>
# Admin user for Collabora. Defaults to blank, provide one to enable access
COLLABORA_ADMIN_USER=admin
# Admin password for Collabora. Defaults to blank, provide one to enable access
COLLABORA_ADMIN_PASSWORD=<...>

### OnlyOffice settings ###
# Domain of OnlyOffice, where you can find the frontend. Defaults to "onlyoffice.owncloud.test"
ONLYOFFICE_DOMAIN=onlyoffice.<...>

# If you want to use debugging and tracing with this stack,
# you need uncomment following line. Please see documentation at
# https://owncloud.dev/ocis/deployment/monitoring-tracing/
#COMPOSE_FILE=docker-compose.yml:monitoring_tracing/docker-compose-additions.yml
```

## Additional context

The problem could be related to docker itself / os.

```bash
> docker --version
Docker version 20.10.21, build baeda1f82a
> docker-compose --version
docker-compose version 1.29.2, build 5becea4c
> inxi --verbosity=1 --filter --no-host --width
System:
  Kernel: 6.0.11-arch1-1 arch: x86_64 bits: 64 Console: pty pts/3
    Distro: Arch Linux
CPU:
  Info: 6-core AMD Phenom II X6 1090T [MCP] speed (MHz): avg: 811
    min/max: 800/3200
Graphics:
  Device-1: AMD Redwood XT [Radeon HD 5670/5690/5730] driver: radeon v: kernel
  Display: server: No display server data found. Headless machine?
    tty: 193x38
  API: N/A Message: No display API data available in console. Headless
    machine?
Drives:
  Local Storage: total: 4.2 TiB used: 413.33 GiB (9.6%)
Info:
  Processes: 259 Uptime: 32m Memory: 7.73 GiB used: 3.74 GiB (48.4%)
  Init: systemd Shell: Zsh inxi: 3.3.23
```

Docker logs:
- ocis_wopi_wopiserver_1: no logs
- [ocis_wopi_traefik_1.log](https://github.com/owncloud/ocis/files/10200182/ocis_wopi_traefik_1.log)
- [ocis_wopi_onlyoffice_1.log](https://github.com/owncloud/ocis/files/10200186/ocis_wopi_onlyoffice_1.log)
- [ocis_wopi_ocis-appprovider-onlyoffice_1.log](https://github.com/owncloud/ocis/files/10200187/ocis_wopi_ocis-appprovider-onlyoffice_1.log)
- [ocis_wopi_ocis-appprovider-collabora_1.log](https://github.com/owncloud/ocis/files/10200188/ocis_wopi_ocis-appprovider-collabora_1.log)
- [ocis_wopi_ocis_1.log](https://github.com/owncloud/ocis/files/10200189/ocis_wopi_ocis_1.log)
- [ocis_wopi_collabora_1.log](https://github.com/owncloud/ocis/files/10200190/ocis_wopi_collabora_1.log)

**Comment by micbar** [comment]
You are experiencing a knonw issue #3832

**Comment by simone-viozzi** [comment]
Oh, sorry,
You can mark this as duplicate and close it then.

Unrelated question, can I deploy ocis without WOPI / collabora / office, and then add them after a while?
Maybe when the next release is out, for example.

**Comment by simone-viozzi** [comment]
Thanks a lot for the insight!
