### ISSUE TITLE
Ocis needs both oidc and ldap?

### ISSUE THREAD

**Issue by ishioni** [owncloud/ocis#5216]
This is just a general question because i don't exactly follow. Does ocis need both oidc and ldap for external user management? I want to use it with conjunction with authentik and this is the first time i encounter this combo. I'd rather it only use oidc for IDP, so just wanted some clarification of this.

**Comment by micbar** [comment]
Ocis uses LDAP to store the users internally.

You can use ocis with authentik in "autoprovisioning" mode. That means, it will add any new users during first login. That will also mean, that you can share only with users which have logged in al least once.

The external LDAP server brings two advantages:

1) It scales better. E.g. an openLDAP server is proven and stable technology. The build in ocis LDAP is only for small deployments.
2) All users are available for sharing immediately

**Comment by ishioni** [comment]
Oh, so the ldap is an internal ldap server for ocis only?

**Comment by micbar** [comment]
> Oh, so the ldap is an internal ldap server for ocis only and it's internal use?
It is an LDAP server which only supports a sub-set of LDAP operations https://github.com/libregraph/idm

It is included in the ocis single binary to have an "out of the box" ready to start solution.

**Comment by ishioni** [comment]
@micbar Thanks for the info! I'm gonna try it now
