### ISSUE TITLE
[OCIS] Cannot create public links with permissions.

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#5248]
Trying to set permissions on public links fails
```
curl -XPOST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d path=/hello -d permissions=7 -d shareType=3 -u einstein:relativity -ks | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```

**Comment by amrita-shrestha** [comment]
# Link Share
### 0.  Permission 0
- OCIS - created with <permissions>0</permissions> (internal)
 - OC10 - share created with <permissions>1</permissions>

### 1. Default - Permission 1
- OCIS - created with <permissions>1</permissions>
 - OC10 - same as OCIS
 
### 2. Permission 2
- OCIS - Share not created 
```<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 - Share with permission `1` is created. `Viewer` role assigned.

### 3. Permission 3
- OCIS - <permissions>3</permissions>
- OC10 - same as ocis

### 4. Permission 4
- OCIS 
 ```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>404</statuscode>
    <message>No share permission</message>
  </meta>
</ocs>
```
- OC10
```
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>failure</status>
    <statuscode>404</statuscode>
    <message>Public upload is only possible for publicly shared folders</message>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data/>
</ocs>
```

### 5. Permission 5
- OCIS - created with permission <permissions>1</permissions>

- OC10 -  same as ocis

### 6. Permission 6
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 - Share with permission `1` is created. `Viewer` role assigned.

### 7. Permission 7
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 - Share with permission `1` is created. `Viewer` role assigned.

### 8. Permission 8
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>404</statuscode>
    <message>No share permission</message>
  </meta>
</ocs>

```
- OC10 - Share with permission `1` is created. `Viewer` role assigned.

### 9. Permission 9
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 - Share with permission `1` is created. `Viewer` role assigned.

### 10. Permission 15
- OCIS - created with <permissions>3</permissions>
- OC10 - same as ocis

### 11. Permission 16
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 - Share with permission `1` is created. 

### 12. Permission 17 (Share+ read)
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 - Share with permission `1` is created. `Viewer` role assigned.

### 13. Permission 19 (Share+ read+update)
- OCIS - Share not created 
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```
- OC10 share created with <permissions>1</permissions>

**Comment by amrita-shrestha** [comment]
Discussed share permission in this https://github.com/owncloud/ocis/issues/4052#issuecomment-1168655027.
This issue can be closed
