### ISSUE TITLE
Api tests scenario related to share permission needs changes 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5249]
The behavior of share permission is acting differently in ocis and oc10 . 
Discussed in this comment: https://github.com/owncloud/ocis/issues/4052#issuecomment-1168655027
According to this comment, it is actual behavior so we need to refactor our test scenario of share permission in ocis
Related issue 
- https://github.com/owncloud/ocis/issues/1277
- https://github.com/owncloud/ocis/issues/5248
- https://github.com/owncloud/ocis/issues/4052 **( main discussion happened here)**

### Example
In this tests scenario permission is 7 but currently permission 7 is unavailable in ocis 
```feature
  Scenario Outline: Public can or can-not delete file through publicly shared link depending on having delete permissions using the public WebDAV API
    Given user "Alice" has created a public link share with settings
      | path        | /PARENT       |
      | permissions | <permissions> |
    When the public deletes file "parent.txt" from the last public link share using the <public-webdav-api-version> public WebDAV API
    Then the HTTP status code should be "<http-status-code>"
    And as "Alice" file "PARENT/parent.txt" <should-or-not> exist

    Examples:
      | permissions               | http-status-code | should-or-not | public-webdav-api-version |
      | read,update,create        | 403              | should        | new                       |

```

QA Todo
- [ ] search for similar tests scenario which uses share permission refactor scenario (there are other permission which behave different in oc10 and ocis please check in detail)
- [x] remove the issue from the expected-failure file

**Comment by amrita-shrestha** [comment]
@saw-jan @kiranparajuli589 @SwikritiT @individual-it @phil-davis

**Comment by amrita-shrestha** [comment]
1. Permission 7 (read, update,create)
- OCIS - Share not created
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>Could not read permission from request</message>
  </meta>
</ocs>
```

- OC10 - Share with permission 1 is created. Viewer role assigned.

@kobergj @kulmann @fschade is this actual behavior?

**Comment by kulmann** [comment]
@micbar ^

**Comment by phil-davis** [comment]
IMO the currently-implemented general rule is:

In oC10: ignore permissions that are not useful/relevant to the resource (for example, create permission is not relevant to a shared file - the file is already created when it is shared). Mask off the irrelevant permission bits, and create (or update) the share with just the useful permission bits from those requested.

In ocis: if the requested permissions include permissions that are not useful/relevant to the resource, then fail the request. The client must request only permission bits that are useful/relevant.

Can someone confirm that these 2 different implementations are both acceptable?

Then we can make the understand what to expect for each backend.

**Comment by micbar** [comment]
> Can someone confirm that these 2 different implementations are both acceptable?

@phil-davis Thanks for your analysis. That is obviously a difference. From my POV, the permission bitmask is nearing deprecation an is only be there because of legacy reasons. I am always against "magical" Api behavior, especially in this case where we are dealing with permissions. The API should return "Bad Request" and a reason. 

Conclusion: we accept the behavior as it is.

**Comment by phil-davis** [comment]
@amrita-shrestha you (or you can assign someone) can "skip on ocis" the oC10 scenarios that fail because of this different behavior. Then out scenarios that demonstrate the agreed ocis behavior.

Maybe it will be easiest to have examples for ocis in the existing scenario outlines?

Anyway, however you do it, coordinate with @kiranadh1452 as he copies various parts of the core acceptance tests across to the ocis repo - we don't want to accidentally lose anything.

**Comment by saw-jan** [comment]
Will be blocked until https://github.com/owncloud/ocis/issues/5094 is completed

**Comment by amrita-shrestha** [comment]
- [ ] coreApiSharePublicLink1
- [ ] coreApiSharePublicLink2
- [ ] coreApiSharePublicLink3
- [ ] coreApiShareReshareToShares1
- [ ] coreApiShareReshareToShares2
- [ ] coreApiShareReshareToShares3
- [ ] coreApiShareUpdateToShares
- [ ] coreApiSharees

**Comment by amrita-shrestha** [comment]
all PR has been merged so closing this issue
