### ISSUE TITLE
libregraph api: allow creating users without email

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#5253]
The login at the IDP may happen by username and the user may have no email. We should allow provisioning users without an email.

Furthermore, keep in mind: multiple accounts may share the same email.
- [x] make email optional for users
- [x] test if the email is actually required somewhere

**Comment by ScharfViktor** [comment]
need change test after fixing https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/createUser.feature#L27

- we allow creating user with same email: https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/createUser.feature#L24
