### ISSUE TITLE
Rename global_configvars.adoc to extended_configvars.adoc 

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5259]
When writing the rogue envvar code #5164, the exported adoc file was named: `global_configvars.adoc`.

Post a discussion with @kobergj this file (and possibly other related ones) needs to be renamed:
`global_configvars.adoc` --> `extended_configvars.adoc`

This is because we will get a file with real global envvars which then will have the global part in its name.

Also see: https://github.com/owncloud/docs-ocis/pull/335 (Special Scope Environment Variables)

**Comment by kobergj** [comment]
fixed here: https://github.com/owncloud/ocis/pull/5272
