### ISSUE TITLE
libregraph: Increase limit for adding multiple group members at once

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#5262]
In alignment with the MS Graph we currently limit the number of members that can be added via a single PATCH request on `graph/v1.0/groups/{group-id}` to 20 (hardcoded). Same for the educationClass resource.

At least for educationClass resources it would make sense to increase that limit to e.g. 40 to be able to popluation a whole class in one request.

We might just want to make that limit configurable.

**Comment by ainmosni** [comment]
Closed in #5357
