### ISSUE TITLE
[QA] Group membership shows internal ids only

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#529]
Seen with `docker run --rm -ti -p 9200:9200 owncloud/ocis:1.0.0-rc1`
Log in as einstein, click on the user name 'Albert Einstein' in the top righthand corner.

The group membership is displayed as
![image](https://user-images.githubusercontent.com/1108546/92481246-5a6bae80-f1e6-11ea-84df-f816a41c43a4.png)

Expected behaviour: group names are listed instead of the internal ID's, e.g. 'violin-haters', 'physics-lovers'.

**Comment by refs** [comment]
duplicated of https://github.com/owncloud/ocis/issues/441

not happening anymore: 
![image](https://user-images.githubusercontent.com/6905948/104306885-d21c5380-54ce-11eb-8a5d-1c47de745031.png)
