### ISSUE TITLE
Remnants of rogue file names and other maintenance tasks

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5293]
Some file names should be harmonized to avoid confusion + maintenance tasks:

- [x] `docs/helpers/rogueEnv.go` -->`docs/helpers/extendedEnv.go`
- [x] `docs/templates/ADOC_global.tmpl` --> `docs/templates/ADOC_extended.tmpl`
(merge #5292 first)
- [x] backport the file from the:
`docs` branch `ocis/services/_includes/adoc/extended_configvars.adoc` -->
`docs-stable-2.0` branch `ocis/services/_includes/adoc/extended_configvars.adoc`
(merge #5292 first)
fixed via #5298
- [x] it would be great that when running `make docs-generate` that the directory:
`docs/services/_includes` and
`docs/services/_includes/adoc`
are emptied, except the `.gitignore` and the `_index.md` file. This has to do with local building and testing - else you keep remnants forever. The bash command to do so could be (tested)
`find docs/services/_includes/ -type f \( -name "*" ! -name ".git*" ! -name "_*" \) -delete`
- [x] when running `make docs-generate` two go files not in the scope of docs always get changed, a blank comment line gets added in `settings.pb.go` and `thumbnails.pb.go` (protogen/gen/ocis + subdir). Run locally to see the change. The blank comment line could be added by default then this gets avoided. A fix has been proposed, see #5294, needs checking if ok to do so.

Regarding `make docs-generate`, I have tested removing stuff locally and all files are regenerated as expected.

**Comment by kobergj** [comment]
All fixed
