### ISSUE TITLE
The branches docs-stable-x.0 have no protection rules

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5299]
There are no protection rules for the `docs-stable-x.0` branches.
I identified this as we had to add a file that is relevant for that branch but was added post the branch was created.

@micbar is this intended that you just can merge a PR without any review in that branch?

Also see the issue: #5298 where codacy complains about not being "setup"...

**Comment by mmattel** [comment]
keep open

**Comment by mmattel** [comment]
keep alive

**Comment by mmattel** [comment]
**Important info:**
* `docs-stable-x` gets daily "resetted" by the CI based on content from the source `stable-x`, or on merge in `stable-x`. Means that any info falsly or whyever committed into `docs-stable-x` gets reverted back to the original state.
* The question now is, do/can we protect against any manual changes not coming from `stable-x`. If not, we have to be aware that there is the possibility for "bogus" content for max 24h.

**Comment by micbar** [comment]
No harm was done. Closing.
