### ISSUE TITLE
[QA] Phoenix HTTP headers have wrong phoenix version

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#531]
tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

The HTTP headers contain 0.0.0 as Phoenix version:
![image](https://user-images.githubusercontent.com/1108546/92494883-842cd180-f1f6-11ea-9a50-702ad6c3c82c.png)

Expected behaviour: either the version of ocis-phoenix (0.13.0) or the version of phoenix (0.16.0) should be shown. Preferably the latter, as this is harder to find.

**Comment by jnweiger** [comment]
Maybe https://github.com/owncloud/ocis-phoenix/blob/master/pkg/version/version.go#L9 does not get defined by the build system?

**Comment by refs** [comment]
I do not see that header anymore. @LukasHirt do you know if it is still relevant? If note, feel free to close

**Comment by LukasHirt** [comment]
> I do not see that header anymore. @LukasHirt do you know if it is still relevant?

TBH haven't seen that header before 🤷  Need to check

**Comment by kulmann** [comment]
The header is `x-web-version` now. It comes from here and we still have it for all services: https://github.com/owncloud/ocis/blob/846279966725883f8ebec200f2d8128229928111/web/pkg/server/http/server.go#L35

It still has the value `0.0.0`.

**Comment by refs** [comment]
Thanks for the update! will leave open then

**Comment by micbar** [comment]
Fixed with `2.0.0-beta1`
