### ISSUE TITLE
Space tag search broken

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#5323]
## Describe the bug

When searching for tags inside a space the result set is empty

## Steps to reproduce

1. create space
2. upload resource
3. tag resource
4. click tag

## Expected behavior
the tagged resource should be listen in the ui.

## Actual behavior
no results found

**Comment by fschade** [comment]
the problem appears as soon as a group is a manager of a space, then the ev.SpaceOwner is the group and therefor coan't be impersonated.

solutions:
- introduce a service user (internal super user)
- dereference the group members and use the first valid user (reva event)
- ignore groups and only allow valid users in the event (reva event)

@micbar lets discuss after tomorrows standup.

**Comment by micbar** [comment]
Good analysis.

Maybe @aduffeck has an idea.

**Comment by fschade** [comment]
https://github.com/cs3org/reva/pull/3091#issuecomment-1195706323

**Comment by fschade** [comment]
maybe i was wrong above, the used owner seems to be the space id....
strange....

![Bildschirm­foto 2023-01-04 um 17 01 51](https://user-images.githubusercontent.com/49308105/210597170-cd567199-6d52-4df7-8a5b-cb06bc47224e.png)
![Bildschirm­foto 2023-01-04 um 17 01 44](https://user-images.githubusercontent.com/49308105/210597181-8b9f91b1-fa5a-4abe-9b91-ef7ce5afe05e.png)

**Comment by fschade** [comment]
lets see what ci is saying and if we opened a can of worms....
https://github.com/cs3org/reva/pull/3583

**Comment by kobergj** [comment]
Closing this since corresponding PR is merged.
