### ISSUE TITLE
Cleanup core API test codes from oCIS

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#5337]
Copying core API tests completed with PRs https://github.com/owncloud/ocis/pull/5280 and https://github.com/owncloud/ocis/pull/5306

Features and test codes need some cleanup:
- [x] remove core bug demonstration tests (`***Issue***.feature`) @grgprarup https://github.com/owncloud/ocis/pull/5485, https://github.com/owncloud/ocis/pull/5489
- [x] remove any scenarios that are tagged `@skipOnOcis`, `@notToImplementOnOcis` @grgprarup 
  - [x] `@notToImplementOnOcis` https://github.com/owncloud/ocis/pull/5491
  - [x] `@skipOnOcis` https://github.com/owncloud/ocis/pull/5520
- [x] look through the filter tags and sort out which ones we still care about.
- [ ] cut-down the filter-tags list and remove scenarios for any tags that we know are never going to be relevant to ocis or reva
Current skipped tags: (@amrita-shrestha  https://github.com/owncloud/ocis/pull/6165)` ~@skipOnGraph&&~@skipOnOcis&&~@notToImplementOnOCIS&&~@toImplementOnOCIS&&~comments-app-required&&~@federation-app-required&&~@notifications-app-required&&~systemtags-app-required&&~@local_storage&&~@skipOnOcis-OCIS-Storage&&~@caldav&&~@carddav&&@api&&~@skip`
  - [ ] ~@skipOnGraph~
  - [ ] ~@skipOnOcis-S3NG-Storage~
  - [ ] ~@skipOnStable3.0~ decided to not remove
  - [ ] ~@provisioning_api-app-required~ 
  - [ ] ~@skip~
  - [ ] ~@skipOnStorage:ceph~
  - [ ] ~@skipOnStorage:scality~
  - [ ] ~@skipOnOcis-OCIS-Storage~
  - [ ] @skipOnRevaMaster  now tests doesn't run on reva master https://github.com/owncloud/ocis/pull/9446
  - [x]  @skiponldap
  - [x] ~@skipOnOcis
  - [x] ~@notToImplementOnOCIS
  - [x] ~@toImplementOnOCIS
  - [x] ~comments-app-required
  - [x] ~@federation-app-required
  - [x] ~@notifications-app-required
  - [x] ~systemtags-app-required
  - [x] ~@local_storage
  - [x] @preview-extension-required
  - [x] ~@caldav
  - [x] @skipOnOcV10
  - [x] @api (not needed now) https://github.com/owncloud/ocis/pull/6957 https://github.com/owncloud/ocis/pull/7027
  - [x] @skipOnBruteForceProtection
  - [x]  @issue-brute_force_protection 
  - [x] @files_sharing-app-required 
  - [x] @files_trashbin-app-required
  - [x] @files_versions-app-required
  - [x]  @files_trashbin_app
  - [x] @skipOnEncryptionType:user-keys
  - [x] @encryption-issue
- [x] search and remove irrelevant context and helper files (such as `TranslationHelper`, `TagsHelper`, `TagsContext` and other) @ScharfViktor I will remove it while implementing tag tests. #5391 
- [x] remove "the administrator has enabled DAV tech_preview" strps and code. That was an oC10-only thing. @grgprarup https://github.com/owncloud/ocis/pull/5526
- [x] OCC commands related codes @grgprarup 
  - https://github.com/owncloud/ocis/pull/5631
  - https://github.com/owncloud/ocis/pull/5632
  - https://github.com/owncloud/ocis/pull/5633
  - https://github.com/owncloud/ocis/pull/5642
  - https://github.com/owncloud/ocis/pull/5612
  - https://github.com/owncloud/ocis/pull/5691
  - https://github.com/owncloud/ocis/pull/5824
  - https://github.com/owncloud/ocis/pull/5856
- [x] Remove core related implementations and codes @grgprarup 
   - https://github.com/owncloud/ocis/pull/5837
   - https://github.com/owncloud/ocis/pull/6096
- [x] Refactor code where `isTestingOnOcisOrReva` is used @grgprarup https://github.com/owncloud/ocis/pull/5705
- [x] Refactor code where `isTestingOnOcis` is used @grgprarup https://github.com/owncloud/ocis/pull/5780
- [x] Refactor code where `isTestingOnOc10` is used @grgprarup https://github.com/owncloud/ocis/pull/5722
CC @individual-it @phil-davis Please, add other necessary cleanup todos if any.
- [x] Remove `@issue-` tag as they are issues of core, and change `@issue-ocis-` tag to `@issue-` @grgprarup https://github.com/owncloud/ocis/pull/5983/
- [x] Remove the steps like 
     - [x] Given auto-accept shares has been disabled` and functions related to it https://github.com/owncloud/ocis/pull/6207
     - [x] parameter "shareapi_share_dialog_user_enumeration_group_members" of app "core" has been set to "yes" https://github.com/owncloud/ocis/pull/6096
     - [x] parameter "shareapi_auto_accept_share" of app "core" has been set to "no" https://github.com/owncloud/ocis/pull/6096
- [x] Remove scenarios related to
     - [x] federated shares https://github.com/owncloud/ocis/pull/6511
     - [x] root shares
- [x] Refactor scenario with comment and merge scenario if possible for more detail visit: https://github.com/owncloud/ocis/pull/6225#discussion_r1184741160
- [x] Convert scenario outline to the scenario if possible like below scenario https://github.com/owncloud/ocis/pull/6694
     ```
     @smokeTest @issue-2128
  Scenario Outline: decline an accepted share
    And the sharing API should report to user "Brian" that these shares are in the declined state
      | path                    |
      | <declined_share_path_1> |
      | <declined_share_path_2> |
    @issue-2540
    Examples:
      | declined_share_path_1 | declined_share_path_2 |
      | /Shares/PARENT/       | /Shares/textfile0.txt |
     ```
- [x] Refactor scenario outlines with`@personalSpace` tag, we might not need to separate the outline with the `/spaces` endpoint anymore  @grgprarup  https://github.com/owncloud/ocis/pull/6250
```
**Point to be noted:** We skipped the space Dav version-related tests in Reva so we implement @personalSpace
Discussed in: https://github.com/cs3org/reva/pull/2451#issuecomment-1016227463` so we have to look at whether Reva supports space dav or not ❓ 
```
- [x] We have issue tags like ` @issue-product-`, need to clarify if we still need them, and if not maybe we can remove them https://github.com/owncloud/ocis/pull/6708 
- [x] `TEST_OCIS` env https://github.com/owncloud/ocis/issues/7300  https://github.com/owncloud/ocis/pull/7376/
- [x] Refactor the example table heading so it will be uniform, `dav_version`, `dav-path-version`, `dav-path` (not dav_path), @S-Panta https://github.com/owncloud/ocis/pull/6697

**Comment by amrita-shrestha** [comment]
> we have issue tags like  @issue-product- , need to clarify if we still need them , and if not maybe we can remove them

@SwikritiT  product repo was used a long time ago for discussions/issues about features and how they should be implemented. It is not used anymore.

**Comment by phil-davis** [comment]
> What should we do?

Check that the "product" issues are still correct - most of them should have been moved to the ocis repo. And update them to have the current ocis issue number. That will make it easy for developers to find the issue - they will not have to realize about the history of the "product" repo.

If there are ocis issues still open in the product repo, then we should review them (write updated information about the issue) and if still relevant, moved them to the ocis repo. Ping me if you cannot move them yourself.

**Comment by saw-jan** [comment]
We can do a final check and then close this one.

CC @amrita-shrestha @nirajacharya2

**Comment by saw-jan** [comment]
@amrita-shrestha let's close this one if everything in done

**Comment by nabim777** [comment]
All task has been done. so, closing this issue
