### ISSUE TITLE
[ocis] Add mechanism to commit and freeze writing to storage for taking a backup

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5351]
# Is your feature request related to a problem? Please describe.
References: owncloud/docs-ocis#208 (backup and restore)

# Describe the solution you'd like
When having a running production instance, especially in bigger environments, you need to take regular consistent backups. Consistent means, that both files and metadata are in sync.

It is therefore necessary to trigger a buffer flush and temporary freeze state where no write actions occur while reading is still allowed. When the backup has been taken, the freeze state can be released and writing will be allowed again.

Because storage systems (or some filesystems) provide snapshot capabilities (both POSIX and S3), the time needed for taking a snapshot is quite short and only takes seconds. The physical backup - if needed - like to a secondary media is then based on the snapshot taken and not on the life filesystem.

To trigger a freeze and release event, an external source like a script needs to be able to tell ocis the request and gets as return the state. In addition, a query must be possible to return the current state, necessary when somethings went wrong and you need to interfere based on the response.

The freeze and release state must be reboot persistent.

Though I am not a developer, my gut feeling tells me that a new service should be implemented using the event bus to cover this topic.

# Describe alternatives you've considered
Fully stop and restart ocis - which is imho no real alternative.

# Additional context
Desperately needed as no one can live ourdays without having a backup.
20.23.08.29: based on sales feedback, customers expect to have such a feature mandatory present in the product. It is therefore a sales success factor and priority should be raised accordingly.

**Comment by butonic** [comment]
Decomposedfs uses locks to make filesystem access atomic. Since all persistent storage happens via the cs3 api and the decomposedfs an atomic backup can be achieved by using a filesystem like xfs, btrfs or zfs to take a snapshot and back that up.

**Comment by butonic** [comment]
We will need a way to flush the IO in the storage driver, allow on external tool to do a snapshot, and then resume IO.

**Comment by butonic** [comment]
some background on snapshots in eg netapps persistance with WAFL: https://en.wikipedia.org/wiki/Write_Anywhere_File_Layout

**Comment by mmattel** [comment]
Note that in case we add that, notifications can be provided via the userlog service.

**Comment by mmattel** [comment]
dont close

**Comment by mmattel** [comment]
keep open

**Comment by butonic** [comment]
related:
- https://github.com/owncloud/ocis/issues/6559
- https://github.com/owncloud/ocis/issues/6051

**Comment by mmattel** [comment]
Just to keep in mind: https://owncloud.dev/services/storage-users/#graceful-shutdown

**Comment by micbar** [comment]
We discussed that in the light of the new backup and restore project. We think, that is not doable and not desired.

## Reasoning

1. Putting ocis into "read-only" mode is not possible due to SLA
2. Enforcing "read-only" mode over multiple replicas of ocis services would require a consensus process and would  therefore be "slow to reach"
3. Ocis Storage operations should be atomic that snapshots are possible at any time

**Comment by mmattel** [comment]
> 3. Ocis Storage operations should be atomic that snapshots are possible at any time

This is per design not possible as you have TWO write operations. One for the bob and one for the metadata. On big instances, these go to two different targets with different latencies. I already discussed that with @butonic and he agreed that this point is valid. _Never_ expect a "silent" system when an admin goes for a backup.

In my 16y of high end storage, this kind of misconception was the one which caused the most confuses and data corruptions. This is why databases return a commit back positive to the requestor only when the log has been written as you can restore that commit with its data at any time. As ocis does not have this, you must create consistency manually and the way described is the only one possible - anything else is  whish and hope.

I made my point and it is up to management to decide the right thing.
