### ISSUE TITLE
Provide Drive ID and File ID of matching Shares Jail item from sharing endpoints

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ocis#5355]
### Scenario:
- user `admin` shares the file `Chemiephoto.JPG` with `einstein` from a space that `einstein` has no access to
- user `einstein` (re)shares the file to `admin`
- user `einstein` requests a list of items he shares with others via `/ocs/v2.php/apps/files_sharing/api/v1/shares`

### Problem:
- the returned share's XML for the re-share of `Chemiephoto.JPG` shares no ID with what's returned by the `PROPFIND` for the Shares Jail
- to determine the share's File ID in the Shares Jail, the client would need to look through the `mountpoint` drives returned by `/graph/v1.0/me/drives` and check if any of the drive's `root.remoteItem.id` matches the share's `id`, then use that drives `root.id` to find the matching item in Shares Jail

### Additional Problem:
For shares shared *with* the user, the client already needs to perform string operations to gain the File ID of the item in the Shares Jail and keep track of the context (is a share representing an item "shared with" or "shared by"?) a share was received in.

Here's the current implementation:

```objc
NSString *itemSource;

if ((itemSource = shareNode.keyValues[@"item_source"]) != nil)
{
	if ([itemSource containsString:@"!"] && [state isEqual:OCShareStateAccepted] && (share.category == OCShareCategoryWithMe))
	{
		// Compute location and FileID in Shares Jail
		share.itemFileID = [OCDriveIDSharesJail stringByAppendingFormat:@"!%@", shareID]; // Item ID in Shares Jail = OCDriveIDSharesJail + "!" + shareID (via https://github.com/owncloud/web/blob/master/packages/web-client/src/helpers/space/functions.ts#L53 )
		share.itemLocation = [[OCLocation alloc] initWithDriveID:OCDriveIDSharesJail path:[@"/" stringByAppendingString:sharePath.lastPathComponent]]; // Item is located in Shares Jail
	}
	else
	{
		// OCIS (drive ID could be extracted from item_source, which follows format "[driveID]![fileID]")
		NSArray<NSString *> *itemSourceIDs = [itemSource componentsSeparatedByString:@"!"];

		if (itemSourceIDs.count == 2)
		{
			share.itemFileID = itemSource;
			share.itemLocation = [[OCLocation alloc] initWithDriveID:itemSourceIDs.firstObject path:sharePath];
		}
	}
}
```

I'm fine with having to do a simple string operation to extract the Drive ID from the File ID, but the client shouldn't have to know the context of a response to determine whether to use a Drive ID - or throw away the contained drive ID and use a completely different Drive ID (Shares Jail) altogether.

## Describe the solution you'd like
The sharing APIs should directly provide the Drive ID / File ID (`oc:id`) of the shared file in a non-`mountpoint` drive the user has access to:

- if the user shares a file from a drive the user has access to, it should point to the item on that drive.
- if the user re-shares a file from a drive the user has no access to, it should point to the item in the Shares Jail.

What the client should not need to do is retrieve data from multiple endpoints, align that data, or - worst case - go through trial and error to determine the location of an item returned by the Sharing API on a non-`mountpoint` drive.

## Additional context
Some responses as context for the described scenario:

From `/ocs/v2.php/apps/files_sharing/api/v1/shares`:

```xml
<element>
	<id>1284d238-aa92-42ce-bdc4-0b0000009157:88439805-75db-4b24-85b3-548af3a7afeb:e7155749-251f-44b6-b3ed-de6185866ba6</id>
	<share_type>0</share_type>
	<uid_owner>einstein</uid_owner>
	<displayname_owner>Albert Einstein</displayname_owner>
	<additional_info_owner>einstein@example.org</additional_info_owner>
	<permissions>17</permissions>
	<stime>1673193340</stime>
	<parent></parent>
	<expiration></expiration>
	<token></token>
	<uid_file_owner>88439805-75db-4b24-85b3-548af3a7afeb</uid_file_owner>
	<displayname_file_owner></displayname_file_owner>
	<additional_info_file_owner></additional_info_file_owner>
	<state>0</state>
	<path>/Chemiephoto.JPG</path>
	<item_type>file</item_type>
	<mimetype>image/jpeg</mimetype>
	<storage_id>shared::/Shares/Chemiephoto.JPG</storage_id>
	<storage>0</storage>
	<item_source>1284d238-aa92-42ce-bdc4-0b0000009157$88439805-75db-4b24-85b3-548af3a7afeb!905da7cc-9a5c-4de3-bbec-d336416f639d</item_source>
	<file_source>1284d238-aa92-42ce-bdc4-0b0000009157$88439805-75db-4b24-85b3-548af3a7afeb!905da7cc-9a5c-4de3-bbec-d336416f639d</file_source>
	<file_parent>1284d238-aa92-42ce-bdc4-0b0000009157$88439805-75db-4b24-85b3-548af3a7afeb!88439805-75db-4b24-85b3-548af3a7afeb</file_parent>
	<file_target>/Shares/Chemiephoto.JPG</file_target>
	<share_with>admin</share_with>
	<share_with_user_type>0</share_with_user_type>
	<share_with_displayname>Admin</share_with_displayname>
	<share_with_additional_info>admin@example.org</share_with_additional_info>
	<mail_send>0</mail_send>
	<name></name>
</element>
```

From `PROPFIND` on Shares Jail (`/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/`):

```xml
<d:response>
	<d:href>/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/Chemiephoto.JPG</d:href>
	<d:propstat>
		<d:prop>
			<d:resourcetype></d:resourcetype>
			<d:getlastmodified>Thu, 08 Dec 2022 08:23:23 GMT</d:getlastmodified>
			<d:getcontentlength>1268382</d:getcontentlength>
			<d:getcontenttype>image/jpeg</d:getcontenttype>
			<d:getetag>"d1d23d13fd496717fe0e26a0a17fbaf2"</d:getetag>
			<oc:id>a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!1284d238-aa92-42ce-bdc4-0b0000009157:88439805-75db-4b24-85b3-548af3a7afeb:e9e32aa7-aeef-42e7-a72a-1d10b98b76f0</oc:id>
			<oc:size>1268382</oc:size>
			<oc:permissions>SR</oc:permissions>
			<oc:favorite>0</oc:favorite>
			<oc:share-types>
				<oc:share-type>0</oc:share-type>
			</oc:share-types>
		</d:prop>
		<d:status>HTTP/1.1 200 OK</d:status>
	</d:propstat>
</d:response>
```

From `/graph/v1.0/me/drives`:

```json
{
  "driveAlias": "mountpoint/chemiephoto.jpg",
  "driveType": "mountpoint",
  "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!1284d238-aa92-42ce-bdc4-0b0000009157:88439805-75db-4b24-85b3-548af3a7afeb:e9e32aa7-aeef-42e7-a72a-1d10b98b76f0",
  "name": "Chemiephoto.JPG",
  "owner": {
    "user": {
      "id": "88439805-75db-4b24-85b3-548af3a7afeb"
    }
  },
  "quota": {
    "remaining": 0,
    "state": "exceeded",
    "total": 0,
    "used": 0
  },
  "root": {
    "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!1284d238-aa92-42ce-bdc4-0b0000009157:88439805-75db-4b24-85b3-548af3a7afeb:e9e32aa7-aeef-42e7-a72a-1d10b98b76f0",
    "remoteItem": {
      "eTag": "\"d1d23d13fd496717fe0e26a0a17fbaf2\"",
      "file": {
        "mimeType": "image/jpeg"
      },
      "id": "1284d238-aa92-42ce-bdc4-0b0000009157$88439805-75db-4b24-85b3-548af3a7afeb!905da7cc-9a5c-4de3-bbec-d336416f639d",
      "lastModifiedDateTime": "2022-12-08T08:23:23.013321488Z",
      "name": "Chemiephoto.JPG",
      "size": 1268382,
      "webDavUrl": "https://ocis.test.local/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$88439805-75db-4b24-85b3-548af3a7afeb%21905da7cc-9a5c-4de3-bbec-d336416f639d"
    },
    "webDavUrl": "https://ocis.test.local/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:88439805-75db-4b24-85b3-548af3a7afeb:e9e32aa7-aeef-42e7-a72a-1d10b98b76f0"
  },
  "webUrl": "https://ocis.test.local/f/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:88439805-75db-4b24-85b3-548af3a7afeb:e9e32aa7-aeef-42e7-a72a-1d10b98b76f0"
}
```

**Comment by micbar** [comment]
@felix-schwarz The related issue tries to get rid of the shares-jail at all. That would not change the ocs api.

**Comment by felix-schwarz** [comment]
@micbar The iOS client currently relies on the Shares Jail for files shared with the user. Having every shared item in a space of its own rather than the Shares Jail would inflate the drives list, break the current implementation (for desktop also IIRC /cc @TheOneRing) and overall lead to even more complexity client-side 😕

**Comment by micbar** [comment]
I know, but i fear that is the way to go when we use "collaborative storage"

The path to a shared file should be the same for the sharer and all the sharees.

**Comment by felix-schwarz** [comment]
I think rather than having every client collect pieces from the server, put them together and resolve inconsistencies, it would be more efficient to have the server put the pieces together and have the clients collect the completed picture that it can use easily.

The server already has to have these pieces when it puts the drives list together - or compiles responses to requests to the sharing API.

Having a dedicated space for shared files, signal changes through its ETag and allow clients to collect and track metadata through WebDAV is an efficient way to keep the client up-to-date on files shared with the user and leverage existing client-side infrastructure to offer rich functionality.

I see and understand the point of having a single path for shared files for sharer and sharees, but don't understand why that would require removing the Shares Jail:
- the existence of "virtual" drives with WebDAV endpoints to provide item lists in itself doesn't mean the returned items can't _also_ be returned in the drives list, for clients/infrastructure that prefer it that way
- WebDAV returns item locations as `<d:href>`, which is documented as [`must contain a URI or a relative reference`](https://datatracker.ietf.org/doc/html/rfc4918#section-14.7). While at the moment it usually contains relative references, it could as well serve a URL, which can be the same for sharer and all the sharees.

**Comment by labkode** [comment]
> * the existence of "virtual" drives with WebDAV endpoints to provide item lists in itself doesn't mean the returned items can't _also_ be returned in the drives list, for clients/infrastructure that prefer it that way

This is a good compromise. The possibility to have one single URL that people can copy and paste from their browser environments (it's what actually people do) does not imply the sync client (or mobile) should behave the same.

The requirement for having a "Share Jail" relates to the fact of replicating information. If the client is as dumb as the WebUI and does not need to keep local state, then, you don't need it. I assume from this discussion that the IOS client does sync data locally and therefore would benefit from a non-clashing list of shares from the server. 

Another aspect to consider its that the full path of the share is unique and the requirement of the share jail is only relevant if this information is persisted in a filesystem-like view, I don't know if that is the case of the IOS client, but if the backend is a DB you can show two identical names decorated with metadata (owner, fullpath on hover ...) etc ...
