### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/ocis#537]
Provide changelog with each release 
Currently a list what has changed between beta8 and RC1 is missing. This is crucial for QA

**Comment by phil-davis** [comment]
There was also beta9, so I guess there was no changelog for changes between beta8 and beta9

**Comment by wkloucek** [comment]
Works since v1.0.0-rc8. Also see changelog for v1.0.0: https://github.com/owncloud/ocis/releases/tag/v1.0.0
