### ISSUE TITLE
Content of the 'docs-stable-2.0' branch gets magically deleted 

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5377]
There is a strange situation we have to fix asap.

@micbar you have created the branch named `docs-stable-2.0` (see #5170) where we reference content from the ocis admin docs.

Then @kobergj has created a new autogenerated adoc file `extended_configvars.adoc` in the master branch which was not present when the above branch was created but relevant for it. Therefore I "backported" it, see PR #5298 (Create extended_configvars.adoc).

Now, we have created in the same context as above the `global_configvars.adoc` in master. When in preparation to backport it to `docs-stable-2.0`, I saw that the extended file is no longer present though the PR was merged.

@micbar can you bring in some light (and possible fix it) why it can be that files from `docs-stable-2.0` disappear? Could it be - whithout having this checked - that other files in that branch get updated too. Files in this branch should not get touched by any auto-process inside the ocis repo. These files need to stay "frozen".

Fixing this is important, because when we add/re-add the files necessary and they vanish again, we are in trouble.

**Comment by micbar** [comment]
@mmattel The `docs-stable-2.0` branch gets written when we change the `stable-2.0` branch. All auto generated branches cannot "mix" with manually added files.

**Comment by micbar** [comment]
> Fixing this is important, because when we add/re-add the files necessary and they vanish again, we are in trouble.

If you need something in the `docs-stable-2.0` branch, it should be generated from the `stable-2.0` branch.

**Comment by mmattel** [comment]
> it should be generated from the stable-2.0 branch.

Oh, I was not aware of that...
Let me summarize, pls correct if I am wrong. If we need to add something into `docs-stable-2.0`, we create a PR with target `stable-2.0`. When merged, the changes will automatically be transported into `docs-stable-2.0` - right?

**Comment by micbar** [comment]
Not excactly, but basically yes.

The content of the docs branches is only auto generated stuff, there are no manual additions. So all content needs to be generated from the source branches.

That means the CI pipeline on the `stable2.0` branch should be responsible to also create the `extended_configvars.adoc` file.

That means that @kobergj s changes to the generation Workflow needs to be ported from `master` to `stable-2.0`
