### ISSUE TITLE
[QA] Own user account should not appear listed in Add Collaborator list

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#538]
Tested with ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh

### Steps to reproduce

1 . Open the 3 dots menu and start typing the name of the user account

<img width="1280" alt="Screenshot 2020-09-09 at 16 11 59" src="https://user-images.githubusercontent.com/10596560/92610104-9f134a80-f2b7-11ea-9225-83a71693bdfe.png">

**Note**

We get the error when we try to make the share clicking on Add collaborators button

<img width="1270" alt="Screenshot 2020-09-09 at 16 23 31" src="https://user-images.githubusercontent.com/10596560/92611269-e817ce80-f2b8-11ea-8069-f5c86b796d7b.png">

**Comment by refs** [comment]
not happening anymore. Tested with the [current master at the moment of this writing](https://github.com/owncloud/ocis/commit/846279966725883f8ebec200f2d8128229928111)
