### ISSUE TITLE
The created tag is not immediately available to the user in the project space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5384]
ocis local - master branch

Preparation:
- create a project space with 2 folders `f1` and `f2`

Steps:
- create and add a new `new tag` for the `f1` folder
- try adding a `new tag' for the "f2" folder

#### Actual result: no `new tag` tag in the list 
GET `https://localhost:9200/graph/v1.0/extensions/org.libregraph/tags` gives me empty array `{"value":[]}`
Search doesn't get result by `Tags:new tag`

https://user-images.githubusercontent.com/84779829/212011852-c15192b4-8201-4c71-8635-1fe6a9abed4c.mov

but if we create new folder in the project space - the created tag appears

https://user-images.githubusercontent.com/84779829/212012195-a746656f-f898-4a22-bb47-76fd7eb48302.mov

**Comment by fschade** [comment]
should be fixed, was part of the getOwner confusion we had (https://github.com/cs3org/reva/pull/3597).
Workaround to not use spaceOwner for tag indexing can be found here: https://github.com/owncloud/ocis/pull/5405.

Can you please test if this fixes your issue?

**Comment by ScharfViktor** [comment]
yes, tests were passed in CI https://drone.owncloud.com/owncloud/ocis/18295

I deleted tests from expected failures
