### ISSUE TITLE
oCIS Extensions

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis#54]
The oCIS Extensions are basic building blocks for product transition strategy.
An extensions can consists of several parts and will always be a dedicated microservice, which can be run standalone, or bundled in the oCIS binary. Also for some extensions we want to provide compatibility with oc10.

![oCIS Extension](https://user-images.githubusercontent.com/1204907/69426383-71134880-0d2d-11ea-896d-63dc04756b03.png)

Goal: In a prototyping phase followed by Milestone "Extensions", we want to 
- find the right technologies and approaches for all extension parts
- provide a single binary with config conventions, allowing to start the full stack
- provide docs and examples on how to build an Extension

Related
- Extensions and Clients https://github.com/owncloud/ocis/issues/59

**Comment by butonic** [comment]
![kapi](https://user-images.githubusercontent.com/956847/69727536-06924c00-1123-11ea-9245-044bc2c93fcf.png)

**Comment by refs** [comment]
the original concept deviated slightly from this solution. The graph API is not centralised.
