### ISSUE TITLE
Deletion time in trash bin shows a wrong date

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#541]
Tested with ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh

<img width="1273" alt="Screenshot 2020-09-10 at 09 26 46" src="https://user-images.githubusercontent.com/10596560/92696401-1bef0480-f34a-11ea-8075-20dced664038.png">

**Comment by individual-it** [comment]
tried on OCIS storage and it looks like the `deletion-time` is actually the mtime or the upload time

**Comment by individual-it** [comment]
- [ ]  todo QA-Team: make API tests to check the deletion time.
      It's reported in the `oc:trashbin-delete-datetime` field when doing a PROPFIND on the trashbin endpoint. e.g.: `curl 'http://localhost/owncloud-core/remote.php/dav/trash-bin/admin/' -uadmin:admin -X PROPFIND -d'<?xml version="1.0"?><d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"> <d:prop><oc:trashbin-original-filename /><oc:trashbin-original-location /><oc:trashbin-delete-datetime /><d:getcontentlength /> <d:resourcetype /></d:prop></d:propfind>'`

**Comment by HariBhandari07** [comment]
Reminder to JankariTech Team: Swikriti and Sajan are working on this issue.

**Comment by refs** [comment]
@HariBhandari07 is this still relevant? :)

**Comment by individual-it** [comment]
- [ ] ToDo QA-team retest on EOS storage (most likely the issue still exists with EOS)

**Comment by saw-jan** [comment]
couldn't setup ocis with eos storage using docs from [here](https://owncloud.github.io/ocis/storage-backends/eos/)
whenever `STORAGE_HOME_DRIVER=eoshome` is set, cannot upload files (upload button is disabled)
and cannot login after setting Metadata storage for eos

**Comment by individual-it** [comment]
@ishank011 can you try to reproduce it, we fail to get EOS running

**Comment by ishank011** [comment]
@individual-it will take a look. We start separate reva servers for the storage providers so there might be some things missing in the native ocis EOS providers.

Also, I'm not sure why the upload button is disabled, but this commit https://github.com/cs3org/reva/pull/1415 is needed for uploads to go through, as we don't support TUS in EOS and we need to broadcast this to the clients.

**Comment by phil-davis** [comment]
This needs to be retried (after it sitting here for so long), and report back on what happens.
- [ ] try with the "regular" oCIS storage and (hopefully) confirm that the issue was fixed
- [ ] try with EOS storage and report back the result

We are not running EOS storage in test pipelines in CI, and that is not likely to happen any time soon. So we just need to report the current manual observations, then this can be either closed, or removed from the QA-team project(s).

**Comment by grgprarup** [comment]
> This needs to be retried (after it sitting here for so long), and report back on what happens.
> 
> * [ ]  try with the "regular" oCIS storage and (hopefully) confirm that the issue was fixed
> * [ ]  try with EOS storage and report back the result
> 
> We are not running EOS storage in test pipelines in CI, and that is not likely to happen any time soon. So we just need to report the current manual observations, then this can be either closed, or removed from the QA-team project(s).

Findings: 
- with regular oCIS storage the deletion time in the trash bin is working fine :+1:

**Comment by individual-it** [comment]
I think this can be closed for now
