### ISSUE TITLE
ApiTest. new tests

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5413]
### Tags:

method `PUT /tag`
- [x] add a tag for incoming resources if the user has permission
- [x] create tag in the incoming share
- [x] create tag as space member if you have permisiions 

method `GET /tag`
- user has tag and can find by tag if
- [x] he created tag
- [x] he has accepted share with tag
- [x] he is member of the project space where tag uses
- [x] he restores resource with tag from trash bin

- user hasn't tag and cannot find by tag if
- [x] last tag was deleted from resource
- [x] last resource with tag was deleted
- [x] share was declined or removed

method `DELETE /tag`
- user can delete tag if
- [x] he is creator
- [x] he has share with edit permission
- [x] he is member of the space with edit permissions

https://github.com/owncloud/ocis/pull/5391 and https://github.com/owncloud/ocis/pull/5417 
### Sharing space to group. Add more corner cases
- [x] Share space to group and check response https://github.com/owncloud/ocis/pull/5492
- [x] Delete group from space #5365
- [x] increases permissions for one member of the group #5536

### Expiration date for share
- [x] create share with expiration date https://github.com/owncloud/ocis/pull/5424
- [x] change expiration date https://github.com/owncloud/ocis/pull/5424
- [x] delete expiration date https://github.com/owncloud/ocis/pull/5537
- [x] check the end of expiration date  https://github.com/owncloud/ocis/pull/5819
https://github.com/owncloud/core/blob/9cd6e8949d910e1085edc63ff92ffdf61488bceb/tests/acceptance/features/bootstrap/Sharing.php#L4037
https://github.com/owncloud/testing/blob/master/lib/ExpireShare.php

### Re-share resource with expiration date
- [ ] 

### Expiration date for share space 
- [x] create share with expiration date https://github.com/owncloud/ocis/pull/5562
- [x] change expiration date https://github.com/owncloud/ocis/pull/5605
- [x] delete expiration date https://github.com/owncloud/ocis/pull/5606
- [x] check the end of expiration date https://github.com/owncloud/ocis/pull/5819

**Comment by SwikritiT** [comment]
In the case of `checking the end of the expiry date` doing it as we did in core with the testing app might not be possible for us in ocis. Previously I completely overlooked the fact that in `testing app` administrator internally changes the expiration date of a share of the respective user and set the expiration to yesterday.

https://github.com/owncloud/testing/blob/6965caa176d83df8f5111aa64e91c1de34ce48e0/lib/ExpireShare.php#L43
https://github.com/owncloud/testing/blob/6965caa176d83df8f5111aa64e91c1de34ce48e0/lib/ExpireShare.php#L53
https://github.com/owncloud/testing/blob/6965caa176d83df8f5111aa64e91c1de34ce48e0/lib/ExpireShare.php#L76

@ScharfViktor should we go with what you initially mentioned setting the expiration date of `1min` nad letting that time pass and then checking if the share has expired?

**Comment by SwikritiT** [comment]
Also, I couldn't determine what should be the format of the expiration date. When I send the curl request with expiration date format `2023-03-23T23:59:59.999+05:45` like sent from the UI
I get 
```console
{"ocs":{"meta":{"status":"error","statuscode":400,"message":"could not parse expireDate"}}}
```

If I just send the date it also gives me 
```
{"ocs":{"meta":{"status":"error","statuscode":400,"message":"could not parse expireDate"}}}
```

This format works on the tests `2042-01-01T23:59:59+0100` but not with curl or postman. 
So what exactly should the format be like? 

cc @ScharfViktor

**Comment by ScharfViktor** [comment]
> This format works on the tests `2042-01-01T23:59:59+0100` but not with curl or postman. So what exactly should the format be like?

I don't have an answer to that question either. see #5452

**Comment by SwikritiT** [comment]
> > @ScharfViktor should we go with what you initially mentioned setting the expiration date of `1min` and letting that time pass and then checking if the share has expired?
> 
> We can, but timing is not good solution. Probably we can create method-helper which will change date to yesterday.
> 
> I checked and it works in ocis:
> 
> ```
> curl --location --request PUT 'https://host.docker.internal:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/shareId' \
> --form 'expireDate="2023-02-10T23:59:59.999+01:00"' \
> --form 'role="viewer"'
> ```
when I tried to set the date time to yesterday (through tests) , the status code was 200 but the date wasn't changed. but i tried it with the space , I'll try it again and see how it goes.

**Comment by SwikritiT** [comment]
> > @ScharfViktor should we go with what you initially mentioned setting the expiration date of `1min` and letting that time pass and then checking if the share has expired?
> 
> We can, but timing is not good solution. Probably we can create method-helper which will change date to yesterday.
> 
> I checked and it works in ocis:
> 
> ```
> curl --location --request PUT 'https://host.docker.internal:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/shareId' \
> --form 'expireDate="2023-02-10T23:59:59.999+01:00"' \
> --form 'role="viewer"'
> ```

Hi @ScharfViktor yes it works for both resource and space. Maybe I did something wrong previously

**Comment by ScharfViktor** [comment]
closed as complited
