### ISSUE TITLE
Preview or viewing of shared animated GIFs return a 500 error

### ISSUE THREAD

**Issue by Excds** [owncloud/ocis#5418]
## Describe the bug

When sharing an animated GIF with another user, the preview of the image doesn't work and the actually returned error message is:
`<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception></s:exception><s:message>{&#34;id&#34;:&#34;go.micro.client&#34;,&#34;code&#34;:500,&#34;detail&#34;:&#34;can&#39;t encode this type&#34;,&#34;status&#34;:&#34;Internal Server Error&#34;}</s:message></d:error>`

## Steps to reproduce

1. Clone master branch of ocis, build and run with creating demo users.
2. Log in as moss, upload an animated gif and share it with einstein.
3. Log in as einstein and accept the invitation for shared file.

## Expected behavior
In the list of shared files, there should be an animated thumbnail of the GIF.

When clicking on the file to view it, you should be shown the animation.

## Actual behavior
In the list of files shared with einstein, the shared file is listed, but there is no thumbnail available.

When clicking on the file to view it, you only get shown the filename.

Note: It works fine to download the file.

## Setup

Build and run demo setup as described in the README.

**Comment by individual-it** [comment]
similar thing happens when naming a file that is not a valid JPG `something.jpg` 
```
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception></s:exception><s:message>{&#34;id&#34;:&#34;com.owncloud.api.thumbnails&#34;,&#34;code&#34;:500,&#34;detail&#34;:&#34;could not get image&#34;,&#34;status&#34;:&#34;Internal Server Error&#34;}</s:message></d:error>
```

**Comment by SwikritiT** [comment]
TODO Team
- [ ] add test coverage for this issue

**Comment by amrita-shrestha** [comment]
> TODO Team
> 
> * [ ]  add test coverage for this issue

Currently, API tests don't cover space webdav of preview in personal space and share space. 
- [ ] Add tests coverage in new webdav 
- [ ] Add preview tests coverage for space webdav
