### ISSUE TITLE
Sharing to a group with an expiration date does not work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5442]
Steps:
- use https://ocis.ocis-traefik.latest.owncloud.works/
- as admin create folder and share it to `physics-lovers` group with expiration date
- login as einstein (member of the group) and  see `expiration` in the POST `https://ocis.ocis-traefik.latest.owncloud.works/ocs/v2.php/apps/files_sharing/api/v1/shares/pending/shareId?format=json `or GET `https://ocis.ocis-traefik.latest.owncloud.works/ocs/v1.php/apps/files_sharing/api/v1/shares/shareId`
Request Method: GET

Expected: value `expiration` isn't empty
Actual: share has empty `expiration` value

https://user-images.githubusercontent.com/84779829/213747373-e24fd282-241b-4188-8871-1a704c3b18ce.mov

cc @C0rby

**Comment by dragonchaser** [comment]
![image](https://github.com/owncloud/ocis/assets/1058116/ccfad52c-28cd-4256-8c09-057e9e02e0dd)

It does not have an expiry date on the sharers side either...

**Comment by dragonchaser** [comment]
Will be introduced to ocis with the next reva bump.
