### ISSUE TITLE
[QA] Sort out test-acceptance-core-api in cs3org/reva

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#5450]
PR #5430 changed the "make" target `test-acceptance-core-api` to `test-acceptance-from-core-api` in ocis.

`cs3org/reva` edge and master branches also have `test-acceptance-core-api` in their `Makefile` but it does not seem to be used by the drone CI of `cs3org/reva` - the drone CI fetches all the test code from the ocis repo, and uses the ocis `Makefile` for running the tests.

1) see if there is anything else that uses the `test-acceptance-*` `Makefile` targets in cs3org/reva (maybe they are useful for developers who want to run tests, or?)

2) if they are not used, then remove them from `Makefile` to avoid future confusion.
if they are used, then get the names consistent with what is used in ocis.

**Comment by grgprarup** [comment]
Currently, there are two make targets in `reva edge` branch Makefile, `test-acceptance-api` and `test-acceptance-core-api` the latter one was added in PR https://github.com/cs3org/reva/pull/3591, but the CI in Reva use make targets from ocis and make targets of reva itself have not used in CI. 
IMO those make targets `test-acceptance-api` and `test-acceptance-core-api` in the cs3org/reva Makefile can be removed. @phil-davis what do you say?
I think, refactoring of `README.md` in cs3org/reva, where `core` is cloned to run the acceptance test is needed.

**Comment by phil-davis** [comment]
> what do you say?

yes, remove both Makefile targets, and refactor the README instructions. Do that in a PR to reva edge.

Then I will make the same changes to https://github.com/cs3org/reva/pull/3592 (reva master) and that will be merged "some day".

**Comment by phil-davis** [comment]
@grgprarup please also make a PR to reva master to remove this stuff. (similar to https://github.com/cs3org/reva/pull/3622 )

Then I can review it and get it merged.
