### ISSUE TITLE
OCS space members: users and groups not distinguishable

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#5454]
## Describe the bug

When fetching a space via graph api there is an attribute `drive.spaceRoles.kind` which can be `user` or `group`. This is ok and quite important for being able to distinguish user and group type members.

Unfortunately the OCS api handles both user and group type space members the same: both have a share type value of `7`. While OCS distinguishes regular user (share type `0`) and group (share type `1`)  shares, it does not do the same differentiation for space members.

To my knowledge this only affects `write` requests, i.e. inviting a new space member or updating an existing one. Listing space members happens via graph api (at least for `web`).

## Steps to reproduce

1. Create a space `test`
2. Invite group `physics-lovers` to be member of the space `test`
3. Have a look at the OCS POST request payload on `/ocs/v1.php/apps/files_sharing/api/v1/shares`

## Expected behavior
When inviting a group as a member, a new share type `8` should be required.

## Actual behavior
Share type `7` is required.

**Comment by kulmann** [comment]
cc @micbar this is needed to properly handle `group` and `user` type space members in web. At the moment it just works for the write requests because web didn't introduce a differentiation in the share objects for users and groups which would be consistent with regular shares ( share types `0` and `1` for users and groups). We'd like to do the same for our internal handling of space members with a share type `7` for users and `8` for groups, but we can't because then the write requests would fail for group invites.

**Comment by kulmann** [comment]
cc @jstehle blocker/prerequisite for https://github.com/owncloud/web/pull/8248

**Comment by micbar** [comment]
This was just overlooked during the implementation and maybe a 🐔  / 🥚 problem.

Needs server side fix @C0rby @kobergj

**Comment by kobergj** [comment]
@kulmann I added the type here: https://github.com/cs3org/reva/pull/3620

But I am a bit confused. As far as I see the backend doesn't handle these ShareTypes. They are only used so the backend knows which share to create. For both (share types `7` and `8`) the same endpoint is called therefore the server doesn't need this information. 

It never returns a ShareType anywhere.

Do I get correctly that this is only needed for client convenience and the server doesn't need to understand it?

**Comment by micbar** [comment]
> It never returns a ShareType anywhere.

I thought the share type is returned on the ocs API

**Comment by kobergj** [comment]
`ShareTypeUser` and `ShareTypeGroup` are being returned. `ShareTypeSpaceMembership` (`7`) is not.

**Comment by kobergj** [comment]
No. The server needs to know which kind of share to create. But both user and group invitation point to the same endpoint. That means you could create a group invitation using `shareType=7` or a user inviation using `shareType=8`. It is the same for the server. 

You cannot however create a user invitation with `shareType=0` as this will direct the server to another endpoint.

**Comment by kulmann** [comment]
thanks, that makes perfect sense. 🚀 

cc @JammingBen next reva bump after https://github.com/cs3org/reva/pull/3620 was merged will unblock introducing a shareType `8` for groups. 👍

**Comment by kobergj** [comment]
closing as this is in master now. Please reopen if there is still work to do.
