### ISSUE TITLE
Make `language` setting available via graph user (read & write)

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#5455]
## Is your feature request related to a problem? Please describe.
Actually two ideas:
1. ownCloud Web currently has quite some boilerplate code to fetch or update the current value of the language setting. Using the anyways generated graph client would reduce code complexity in ownCloud Web.
2. the settings service currently validates the provided value on save. The language is actually something that should be defined by the respective client. At the moment the settings service holds a hardcoded list of available languages. Just having a `language` attribute on the user data type and being able to update that to any string would be much appreciated. That way ownCloud Web could define the available languages based on translation coverage from transifex.

## Acceptance Criteria
- We have`language` prop in GET `/me` and GET `/users/{user-id}`
- ~Clients can set Being able to set any alphanumeric value in PATCH `/users/{user-id}`~
- ~Clients can set the language during the POST request to create a user~

NOTE: we removed the requirement to do any admin related read or write with the preferred language because that would be a major change to the settings service. The settings service can currently only read and write settings for the acting user.

**Comment by mmattel** [comment]
@2403905 we just discussed language a view minutes ago, maybe this one is interresting for you too.

**Comment by butonic** [comment]
We will extend the libregraph user resuource with a `preferredLanguage` property, following MS graph: https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties

Property | Type | Description
-- | -- | --
preferredLanguage | String | The preferred language for the user. The  preferred language format is based on RFC 4646. The name is a  combination of an ISO 639 two-letter lowercase culture code associated  with the language, and an ISO 3166 two-letter uppercase subculture code  associated with the country or region. Example: "en-US", or "es-ES". Returned by default. 

*Note: Clients can store `en` but need to be able to interpret `en-US` in case another client stores a region code*

**Comment by butonic** [comment]
To persist the language setting we have to use the settings service, as it contains the currently configured language of the user. We also cannot use the User resource of the CS3 API to store the language, as it has no language property. For the LDAP backend we could use the inetOrgPerson optional preferredLanguage attribute, but it might be readonly.

To avoid problems with these backends we will stick to the settings service at the cost of making an additional request to the settings service (which requires a new grpc client) that can be aquired with eg.:
```

	traceProvider, err := tracing.GetServiceTraceProvider(cfg.Tracing, cfg.Service.Name)
	if err != nil {
		l.Error().Err(err).Msg("cannot initialize tracing")
		return err
	}

	grpcClient, err := grpc.NewClient(
		append(
			grpc.GetClientOptions(cfg.GRPCClientTLS),
			grpc.WithTraceProvider(traceProvider),
		)...,
	)
	if err != nil {
		l.Error().Err(err).Msg("cannot create grpc client")
		return err
	}

	valueService := settingssvc.NewValueService("com.owncloud.api.settings", grpcClient)
```

**Comment by dragonchaser** [comment]
can we close this now?
