### ISSUE TITLE
[QA] Character '?' in folders cause errors in clients' uploads

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#546]
Steps to reproduce:

1. Create a folder that contains  `?` character
2. Upload a file inside this folder

Current behaviour:

Uploads fails. Response `500` with no extra info in iOS client. 

Backend: EOS storage via via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
Version: v1.0.0-rc1
Client: iOS App v11.4 over iOS13

**Comment by davitol** [comment]
From webUI it is not possible to upload a folder that contains a ?.

**Comment by michaelstingl** [comment]
@jesmrec this still an issue?

**Comment by jesmrec** [comment]
Not reproducible with `ocis-2.0.0`. Any way to check with EOS storage?

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
