### ISSUE TITLE
Fix KeyCloak examples when using CORS

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5473]
References:
[ocis KeyCloak examples](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_keycloak)
[CORS policy while getting token information from Keycloak](https://github.com/owncloud/ocis/issues/5466) (issue)

Possibly we need to update `owncloud.dev` referenced by the example with the info that was provided  in the issue above. IMHO the key sentence made is:

...I found out that I need to setup `web origins` option in keycloak client setting...

@wkloucek maybe you can have a look on it
@micbar fyi

**Comment by mmattel** [comment]
@wkloucek ping for mind to have a look

**Comment by mmattel** [comment]
dont close

**Comment by mmattel** [comment]
keep open

**Comment by wkloucek** [comment]
Keycloak needs to be properly configured.
And our example is properly configured when it comes to CORS https://github.com/owncloud/ocis/blob/ca929abd3aa1745912e33a99a83cc2c7ac0c3a06/deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json#L1128-L1130. "e could also use `+` there which has other downsides, but this is up to the Keycloak documentation from my POV.

https://www.keycloak.org/docs/latest/server_admin/index.html#con-basic-settings_server_administration_guide -> `Web Origins`
