### ISSUE TITLE
Search service envvar questions

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5482]
There are some questions that raised reading the search service:

* `SEARCH_ENGINE_TYPE`
defaults to `bleve`
Which supported types are allowed?
Even if it is only bleve, we need to adapt the description to reflect this.
* `SEARCH_EXTRACTOR_TYPE`
defaults to `basic`
Which supported types are allowed?
Even if it is only basic, we need to adapt the description to reflect this.

I also have found some other envvar description issues that can be fixed when addressing the above.

@fschade @kobergj

**Comment by kobergj** [comment]
`SEARCH_ENGINE_TYPE` allows only `bleve` at the moment. 

`SEARCH_EXTRACTOR_TYPE` allows `basic` and `tika` with afaik `tika` needed for full text search

**Comment by mmattel** [comment]
Additional question, I understand tika for FTS, but where is/are the limits of basic?

I will create a PR for the envvar description where we can finetune.

**Comment by kobergj** [comment]
At the moment that exactly is the difference. `basic` cannot handle FTS. 

`tika` provides more functionality, so we might add more features in the future that basic cannot handle.
