### ISSUE TITLE
 graph: Add support for filtering users by groupMembership

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#5487]
Allow to query all users belonging to a specific group. By using filters on the /users API

`/users?$filter=memberOf eq ''`

First thing to clarify: Is this really needed? It's already possible to list all group members using

`/groups/<group-id>/members/`

Maybe that is good enough.

**Comment by rhafer** [comment]
@kulmann @JanAckermann do we really need  this on the `/users/` endpoint?

We already have: [`/groups/{group-id}/members`](https://owncloud.dev/libre-graph-api/#/group/ListMembers) which return all members of a specific group.

**Comment by JammingBen** [comment]
@rhafer It's still needed, because `/groups/{group-id}/members]` can only filter by one group ID, whereas `/users?$filter=memberOf eq ''` has (should have) the possibility to handle multiple group ids. What we want to have in Web is a filter in the users list where you can filter e.g. "List all users that are in the groups `admin` and `physics-lovers`".

**Comment by rhafer** [comment]
After reading  a bit more through the odata specs and MS Graph docs. I think the filter is somewhat more complex than initially thought. As `memberOf` is not a property of a `user` but a relation we need to use some more ~crazy~ "advanced" filters here. Basically to filter all users that a member of a group with id=`some-id` the filter looks like:

`$filter=memberOf/any(m:m/id eq 'some-id')`

 to filter by group name it would be:

`$filter=memberOf/any(m:m/displayName eq 'some-name')`

My intention is to get the filter by id working first. And see from there.

**Comment by JammingBen** [comment]
> My intention is to get the filter by id working first. And see from there.

By ID is totally fine, Web does not need more (for now at least) 🙂
