### ISSUE TITLE
support dynamic client registration

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#5498]
We currently hardcoded the default client identifiers for openid connect because lico disabled it by default: https://github.com/owncloud/ocis/pull/2026

When trying to develop a new client for ocis developers would like to use [OpenID Connect Dynamic Client Registration](https://openid.net/specs/openid-connect-registration-1_0.html) OOTB.

**Comment by butonic** [comment]
It is possible to enable dynamic client registration by setting `IDP_ALLOW_DYNAMIC_CLIENT_REGISTRATION=true`. But when testing with our clients we encountered some problems. Maybe @michaelstingl can elaborate.

**Comment by butonic** [comment]
There is a huge docs issue trying to sort out what should be documented: https://github.com/owncloud/docs/issues/3499

**Comment by butonic** [comment]
The problems seem to have been caused by the client registration expiring after an hour. They no longer expire, but this can be reenabled by setting `IDP_DYNAMIC_CLIENT_SECRET_DURATION` if desired.

**Comment by michaelstingl** [comment]
DCR when announced in `[/.well-known/openid-configuration](https://ocis.ocis-keycloak.released.owncloud.works/.well-known/openid-configuration)`, and when it fails, desktop + mobile apps fall back to client id + secret.

**Comment by micbar** [comment]
DCR works with the example ocis deployment.
