### ISSUE TITLE
Deploy using a single binary

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis#55]
This is part of oCIS Extensions, as a single binary is about to bundle the multiply microservice extensions, and providing good configuration conventions.

- [x] https://github.com/owncloud/ocis/issues/2
- [ ] https://github.com/owncloud/ocis-webdav/issues/1
- [x] https://github.com/owncloud/ocis-phoenix/issues/3
- [ ] https://github.com/owncloud/ocis-ocs/issues/1

---

**Comment by butonic** [comment]
ocis-simple is intended to show how to build extensions. As that it will run the full stack, but a self contained set of services that serve as an example for how to write extensions with front and backend parts:
- **hello** contains the example extension, including a protobuf generated api and a phoenix extension/app?
- **phoenix** server the web framework. *hello* adds a ? to it
- **konnectd** as the openid connect provider for authentication
- **devldap** as the user backend for konnectd, comes with a few demo users

It will not contain *reva* or the *graph*, yet. We will add that to the ocis full sever.

**Comment by refs** [comment]
Why is this issue closed again? There's a PR that can make use of this issue to track. Also, it's part of the backlog. #79

**Comment by butonic** [comment]
webdav and ocs are currently covered by ocis-reva. moving them into ocis extensions is tracked in
- https://github.com/owncloud/ocis-ocs/issues/10
- https://github.com/owncloud/ocis-webdav/issues/10
