### ISSUE TITLE
[QA] Delete or Restore from trashbin fails

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#551]
Steps:

1. Delete some files from the file list
2. Go to trashbin
3. Remove the files from trashbin after selecting them

Current:
![Screenshot 2020-09-11 at 10 13 41](https://user-images.githubusercontent.com/14894746/92891345-2aa3ed00-f418-11ea-96e9-4117badf1cb2.png)

Not posible to clean the trashbin

Backend: EOS storage via via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
Version: v1.0.0-rc1
Client: iOS App v11.4 over iOS13

**Comment by jnweiger** [comment]
Workaround: Delete trashbin of all users via command line:
```docker-compose exec ocis eos recycle purge -g```

**Comment by PVince81** [comment]
is that on EOS storage ?

**Comment by jesmrec** [comment]
Backend: EOS storage via via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

**Comment by kulmann** [comment]
Can confirm that 👍  Fix works as intended. Was just old, broken data on that machine.
