### ISSUE TITLE
Upload speed indication

### ISSUE THREAD

**Issue by mamay** [owncloud/ocis#5511]
It's good to see the upload speed in web interface, not only the current estimate, so the user will better understand if upload is stalled / etc.

**Comment by ChrisEdS** [comment]
Hello @mamay,

I saw there is a draft for this feature: https://github.com/owncloud/web/pull/8187
Do you know a developer who might work on that?

**Comment by mamay** [comment]
Don't know, will try to look at this and maybe put some ideas there.

**Comment by pascalwengerter** [comment]
Please close in favor of [#8166](https://github.com/owncloud/web/issues/8166) if applicable (this is where the `web` tickets go 🙂 )
