### ISSUE TITLE
Folder upload merge is not working

### ISSUE THREAD

**Issue by mamay** [owncloud/ocis#5512]
Folder reupload using web-interface merge is not working - Unknown error.

## Steps to reproduce the behavior:

1. Upload folder
2. Stop upload
3. Upload the same folder - select Merge
4. Server exits 405 - The resource already exists

## Expected behaviour 
New files are uploaded to the same folder / continued upload of the stopped ones.

## Actual behavior
Error 405.

**Comment by ScharfViktor** [comment]
retested on:
ocis - `5.1.0-prealpha+d14935ad78`
web - `8.0.0-rc.1`

> 1. Upload folder
> 2. Stop upload
after reloding page you can see that the uploaded folder is partially uploaded with contents
> 3. Upload the same folder - select Merge
> 4. Server exits 405 - The resource already exists
server contains `405` only for MKCOL request (folder creation). We overwrite the file (create a new version of the file), but do not create a new version of the folder -> if the folder already exists, we get 405 and upload the contents to the existing folder 

> ## Actual behavior
> Error 405.
the folder is fully uploaded
