### ISSUE TITLE
Inconsistant description of OCIS_ADMIN_USER_ID

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5517]
Referencing:
https://github.com/owncloud/ocis/issues/3917#issuecomment-1190038158
https://github.com/owncloud/ocis/pull/4235/files
https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_ldap/config/ldap/ldif
https://doc.owncloud.com/ocis/next/deployment/services/env-vars-special-scope.html

The envvar description for `OCIS_ADMIN_USER_ID` shown in our admin docs is:
`ID of the user that should receive admin privileges.`

But when reading the referenced PR above, you can see:
```
You need to enter the uuid of LDAP user.
In the .ldif file in this example, the admin user id is base64 encoded.
You need to decode it to make it work.
```

1. There is a difference in the description
2. Possible valuable information is missing in the envvar description which shows up in the admin docs
Should be fixed in this repo

@micbar @rhafer can you clarify and make a proposal text for `OCIS_ADMIN_USER_ID` - I could do a PR based on your info

**Comment by micbar** [comment]
@mmattel  

`NOTE: Be aware that the uuid can be encoded in some LDAP deployment cofiguration files (e.g. .ldif files). You need to decode it beforehand.`
