### ISSUE TITLE
Refactor public link preview API  in acceptance tests

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5519]
Currently, we are making API requests on this endpoint

"/index.php/apps/files_sharing/ajax/publicpreview.php?file=$fileName&t=$token";

But in ocis we use a new API endpoint to make a public link preview request

`curl -XGET "https://host.docker.internal:9200/remote.php/dav/public-files/PaJOVsaiCmSdwUK/ss.png?preview=1&x=32&y=32" -vk`

**Comment by amrita-shrestha** [comment]
- [ ] Add new api in documentation

**Comment by SwikritiT** [comment]
The PR's have been merged so closing now
