### ISSUE TITLE
[QA] Resharing is always allowed even when we do not add that permission

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#552]
Tested with ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh

### Steps to reproduce

1. user A shares a file with user B without enabling `Allow re-Sharing ` checkbox
2. user B shares the file with user C

### Expected behavior

user B should not be able to reshare the file

### Current behavior

The file is reshared

<img width="471" alt="Screenshot 2020-09-11 at 10 38 41" src="https://user-images.githubusercontent.com/10596560/92894540-f8e05580-f41a-11ea-8a43-f5bca9d93181.png">
<img width="209" alt="Screenshot 2020-09-11 at 10 38 53" src="https://user-images.githubusercontent.com/10596560/92894548-faaa1900-f41a-11ea-8dc6-6e49ec733f5d.png">

**Comment by dpakach** [comment]
Also reported in https://github.com/owncloud/product/issues/270

**Comment by refs** [comment]
With the latest [efforts],(https://github.com/cs3org/reva/pull/1368/) this is not happening anymore
