### ISSUE TITLE
cs3: Exclude disabled users from lookup

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#5556]
Users on the CS3 API currently don't have an enable/disabled flag. We need to add that. (Or completely exclude disabled user from being returned by the CS3 API).

**Comment by rhafer** [comment]
As agreed in the planning: For now it should be good enough if we just filter out disabled users on the CS3 API level. (i.e. no need to add a new attribute to the users)

**Comment by rhafer** [comment]
@ainmosni  Correct me if I am wrong, but I think this is what you are currently working on, right?

**Comment by rhafer** [comment]
reva PR https://github.com/cs3org/reva/pull/3686

**Comment by ainmosni** [comment]
@rhafer sorry for the slow response, I missed the notification, yes this is the one.

**Comment by rhafer** [comment]
reva PR is merged. We just need to set it up currently from ocis now.

**Comment by rhafer** [comment]
PR https://github.com/owncloud/ocis/pull/5692
