### ISSUE TITLE
Access to the space does not end after the expiration date

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5558]
```
ownCloud | Infinite Scale
Community
2.0.0+139cf79f6
7.0.0-rc.12
```

Steps: 
- create space 
- share space to einstein with expiration date using api (**set the time for the expiration date to expire in a few minutes**)
```
curl --location --request POST 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--form 'shareType="7"' \
--form 'shareWith="einstein"' \
--form 'space_ref="spaceUUID"' \
--form 'role="viewer"' \
--form 'expireDate="CURRENT DATE + 2 min 2023-02-13T12:53:59.999+01:00"'
```
- wait a few minutes

Expected: einstein has not access.
for admin response `graph/v1.0/me/drives ` doesn't contain info about `sharing to einstein`

Actual: einstein has access and can continue use space
![Screenshot 2023-02-13 at 13 01 44](https://user-images.githubusercontent.com/84779829/218453146-0acd42b6-978f-462e-9f49-37eaf3654038.png)

**Comment by micbar** [comment]
to my knowledge, Spaces can, like shares only expire at 23.59.59

**Comment by ScharfViktor** [comment]
front end set this time. via api you can select the desired time

**Comment by phil-davis** [comment]
Note: for oC10, expiration of anything (that exists - shares, links...) is only done at the resolution of 1 day. The resource is accessible until right up to the end of the expiration date (to 23:59:59.99...) Any time that happens to be specified in an API request is ignored, only the date is used.

So the requirement in oCIS needs to be defined - what resolution is required for expiration.

**Comment by ScharfViktor** [comment]
It is another problem, we can create different issue for that. The important point about my issue is that the expiration date is not DELETED after expire.

I see difference between old and new web:
`old front` set time like: `2023-02-15T00:00:00+0100` - user has access only until 2023-02-15
new web like: `2023-02-15T23:59:59+0100`- user has access during 2023-02-15 (+1 day if the same date is selected)

<img width="1379" alt="Screenshot 2023-02-13 at 13 47 31" src="https://user-images.githubusercontent.com/84779829/218461807-036c89fd-031c-4bbc-bc6f-5c64ea9279d5.png">

**Comment by ScharfViktor** [comment]
fixed https://github.com/cs3org/reva/pull/3655
