### ISSUE TITLE
API tests to get appRoleAssigment of a user by graph API

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#5564]
API description: https://owncloud.dev/libre-graph-api/#/user.appRoleAssignment/user.ListAppRoleAssignments
- [x]  assign roles via settings API, check if assignment is correctly displayed by graph API https://github.com/owncloud/ocis/pull/5584

**Comment by amrita-shrestha** [comment]
Backport : https://github.com/owncloud/ocis/pull/5584
