### ISSUE TITLE
API tests to get a single group via graph API

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#5567]
API description: https://owncloud.dev/apis/http/graph/groups/
- [x] test getting details of a single group (ocis returns only `displayName` & `id`) @PrajwolAmatya  https://github.com/owncloud/ocis/pull/5641
- [x] add user to group, test getting users of a group using the group endpoint with `?%24expand=members` parameter https://github.com/owncloud/ocis/pull/5593
- [x] test getting a non-existing group @PrajwolAmatya https://github.com/owncloud/ocis/pull/5701
- [x] test getting a group that has UTF8 characters in the name @PrajwolAmatya https://github.com/owncloud/ocis/pull/5748

**Comment by PrajwolAmatya** [comment]
All the test have been added and forward port to the master branch. So, closing this issue.
