### ISSUE TITLE
API tests to add multiple users to a group at once using graph API

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#5569]
API description: https://owncloud.dev/apis/http/graph/groups/#adding-multiple-members-in-a-single-request

- [x] add multiple users to a group, check if the graph API shows them as member of the group, check if they receive shares of that group(@amrita-shrestha )https://github.com/owncloud/ocis/pull/5678
- [x] try to add not existing users to a group @amrita-shrestha https://github.com/owncloud/ocis/pull/5678
- [x] try to add user-ids that have invalid characters @amrita-shrestha https://github.com/owncloud/ocis/pull/5864
- [x] try to send a wrong host in the host-part of the user-id @PrajwolAmatya https://github.com/owncloud/ocis/pull/5875
- [x] try to send not valid JSON @PrajwolAmatya https://github.com/owncloud/ocis/pull/5898
- [x] try to add users to the group that are already part of the group @amrita-shrestha https://github.com/owncloud/ocis/pull/5693
- [x] try to add a group to a group @amrita-shrestha https://github.com/owncloud/ocis/pull/5693

**Comment by amrita-shrestha** [comment]
Forward port - https://github.com/owncloud/ocis/pull/5678

**Comment by amrita-shrestha** [comment]
Done
