### ISSUE TITLE
[Graph Api] Normal user not authorized to get their assigned role 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5583]
## Describe the bug
Normal users ( user with role User, Guest, SpaceAdmin) are not authorized to get their assigned roles. Only admin user can get their assigned role.

## Steps to reproduce

1. create user `rosy` with role `User`
2. do API request to get assign role
`curl -vk -X GET -u rosy:rosy https://localhost:9200/graph/v1.0/users/05e63eb1-d2e3-40b5-966e-97e0cbe22dd8/appRoleAssignments`
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Length: 158
< Content-Type: application/json; charset=utf-8
< Date: Thu, 16 Feb 2023 04:39:01 GMT
< X-Graph-Version: 2.0.0+92923f680
< 
{ [158 bytes data]
100   158  100   158    0     0   1961      0 --:--:-- --:--:-- --:--:--  1975
* Connection #0 to host localhost left intact
{
   "error" : {
      "code" : "accessDenied",
      "innererror" : {
         "date" : "2023-02-16T04:39:01Z",
         "request-id" : "amrita-OptiPlex-3050/VTXGkwheNT-001625"
      },
      "message" : "Unauthorized"
   }
}
```
4. change user role to `Admin`
```
< HTTP/1.1 200 OK
< Content-Length: 285
< Content-Type: application/json; charset=utf-8
< Date: Thu, 16 Feb 2023 04:39:36 GMT
< X-Graph-Version: 2.0.0+92923f680
< 
{ [285 bytes data]
100   285  100   285    0     0   3682      0 --:--:-- --:--:-- --:--:--  3701
* Connection #0 to host localhost left intact
{
   "value" : [
      {
         "appRoleId" : "71881883-1768-46bd-a24d-a356a2afdf7f",
         "id" : "b6c26c6c-24a5-4160-99df-c6a728d85c55",
         "principalId" : "05e5d2ec-31d6-48e3-9d6c-730a67b98b20",
         "principalType" : "User",
         "resourceDisplayName" : "ownCloud Infinite Scale",
         "resourceId" : "4ac207ac-3a4b-4aa3-993d-2f33ca29d215"
      }
   ]
}
```

## Question
- Is this expected behavior?

## Actual behavior
only user with the role `Admin` can get assign role

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by kulmann** [comment]
Question, why would you expect to be able to retrieve the assigned role of the user?

**Comment by kulmann** [comment]
@amrita-shrestha 

I don't know how the endpoint is secured in the backend, but at least I can tell you that the endpoint is not relevant for a non-admin user. IMO it **should** only be available to admins.

At the moment the settings api is used to get the role of the user (like you mentioned it). As soon as web transitioned to the new permissions endpoint we will not fetch the role of the logged in user anymore in web.

That's why I wanted to know what you plan to do with the role. An API test for just checking the role of the logged in user is not needed.

**Comment by amrita-shrestha** [comment]
@kulmann thank you for the information

**Comment by ScharfViktor** [comment]
I discus also with @C0rby about it. Behavior is expect. endpoint was implemented only for admin user. we can close issue
