### ISSUE TITLE
integrate with kopano connectd and kapi/grapi

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#56]
OCIS deployments needs an openId Connect Provider that handles user authentication. While ocis can integrate with existing IdPs we also need an easy deployment that includes an IdP.

On of the challenges is to align users from the IdP with a user management that is used to look up share recipients.

Kopano provides both: an IdP (konnectd) and a user management (acessible via kapi/grapi) that already does the alignment. Users can be found in the kapi using the sub from the konnectd ID token.

Integrating reva / ocis and kopano also allows using reva as a drive provider for the kapi.

We need to clarify how tokens are passed on and how authentication works in this scenario as well as custom IdP scenarios.

**Comment by DeepDiver1975** [comment]
Ping me to chat about details if you like :wave:

**Comment by refs** [comment]
we integrated Konnectd as part of our default set of extensions.
