### ISSUE TITLE
graph: use user `userType` property to distinguish `Member` vs `Guest` accounts

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#5603]
To let the WebUI expose to admins if a user is provisioned to the master ldap or if it is a guest account for a slave.

The former is stored in the global LAP subtree of users and we should set the `userType` to `Member`.
The latter  is stored in a school specific subtree of users and we should set the `userType` to `Guest`.

The Web UI can then mark all `userType=Member` users as read only.

Having a dedicated subtree for users also allows setting specific LDAP ACLs to allow an instance to manage only the guest accounts for its school...

🤔 

so we can have the same guest user in multiple schools? that would break the login for them ... so wea are back to a single huge list of accounts with an ldap property that allows us to distinguish them?

cc @rhafer

**Comment by Excds** [comment]
Suggestion:
- Calling /graph/v1.0/users with userType not set will create a user as "Member"
- Calling /graph/v1.0/users with userType set as "Member" or "Guest" will create a user as "Member" or "Guest"
- Calling /graph/v1.0/users with userType set as anything but "Member" or "Guest" returns error

- Calling /graph/v1.0/education/users with userType not set will create a user as "Member"
- Calling /graph/v1.0/education/users with userType set as "Member"  will create a user as "Member" and primary role as parameter specifies
- Calling /graph/v1.0/education/users with userType set as "Guest" will create a user as "Guest" and primary role as "student"
- Calling /graph/v1.0/education/users with userType not set as anything but "Member" or "Guest" returns error

**Comment by Excds** [comment]
>     * Calling /graph/v1.0/education/users with userType set as "Guest" will create a user as "Guest" and primary role as "student"

When thinking about it, it doesn't make sense to force the "student" primary role, there might be guest teachers or something.

Updated version:

- Calling /graph/v1.0/users with userType not set will create a user as "Member"
- Calling /graph/v1.0/users with userType set as "Member" or "Guest" will create a user as "Member" or "Guest"
- Calling /graph/v1.0/users with userType set as anything but "Member" or "Guest" returns error
- Calling /graph/v1.0/education/users with userType not set will create a user as "Member"
- Calling /graph/v1.0/education/users with userType set as "Member" will create a user as "Member" and primary role as parameter specifies
- Calling /graph/v1.0/education/users with userType set as "Guest" will create a user as "Guest" and primary role as parameter specifies
- Calling /graph/v1.0/education/users with userType not set as anything but "Member" or "Guest" returns error
