### ISSUE TITLE
Ocis against ldap. login problem

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5636]
CC @rhafer 

Steps: 
- docker pull owncloud/ocis - need get ocis with disabling/enabling feature
- start ocis with ldap https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_ldap/docker-compose.yml
- try to login as admin with correct password

Actual: Logon failed

ldap_server_log:
```
63f73ebe conn=1004 fd=12 ACCEPT from IP=172.29.0.5:59784 (IP=0.0.0.0:389)

63f73ebe conn=1004 op=0 BIND dn="cn=admin,dc=owncloud,dc=com" method=128

63f73ebe conn=1004 op=0 BIND dn="cn=admin,dc=owncloud,dc=com" mech=SIMPLE ssf=0

63f73ebe conn=1004 op=0 RESULT tag=97 err=0 text=

63f73ebe conn=1004 op=1 SRCH base="ou=users,dc=owncloud,dc=com" scope=2 deref=0 filter="(&(&(objectClass=inetOrgPerson)(objectClass=ownCloud)(!(?ownCloudUserEnabled=FALSE)))(uid=admin))"

63f73ebe conn=1004 op=1 SRCH attr=dn givenName ownclouduuid binary uid mail displayName sn

63f73ebe conn=1004 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=

63f73ebe conn=1004 fd=12 closed (connection lost)
```

**Comment by rhafer** [comment]
This is partially related to https://github.com/owncloud/ocis/pull/5625#discussion_r1115466171 

The other part is that the LDAP server in the compose example needs a config update. (I am working on that now)

@ScharfViktor as a workaround you can set `LDAP_USER_ENABLED_ATTRIBUTE=""` for now.
