### ISSUE TITLE
we killed the writeable ocs users api

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#5638]
https://github.com/owncloud/ocis/pull/5428 actually killed our ocs users endpoint. cdperf k6 can no longer provision users using the `ocs/v1.php/cloud/users` endpoint. The ocis implementation can only return the sharing key. The reva implementation is a read only version and cannot be used to create users.

Either revert some of the commits and enable tests on it to bring back the writeable part, or kill it with fire and switch cdperf to graph api (but oc10 requires an app that is not pre installed)

**Comment by ScharfViktor** [comment]
I can switch api to creating and deleting users using graph api 
do we run perfomance test with oc10?

**Comment by butonic** [comment]
we do as a comparison, yes

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/cdperf/pull/40 should solve issue. 
until PR doesn't merge as temporary solution we can use [branch](https://github.com/owncloud/cdperf/pull/44) 

probably we can close it

**Comment by rhafer** [comment]
cdperf was released. This can be closed I think.
