### ISSUE TITLE
support redis sentinel

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#5645]
## Is your feature request related to a problem? Please describe.
I'd like to use Redis sentinel as a cache.

## Describe the solution you'd like
oCIS must allow the admin to configure the Mastername Option in Reva:

```diff
diff --git a/pkg/storage/cache/cache.go b/pkg/storage/cache/cache.go
index 07842c32..0b4f595d 100644
--- a/pkg/storage/cache/cache.go
+++ b/pkg/storage/cache/cache.go
@@ -29,6 +29,7 @@ import (
        provider "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
        natsjs "github.com/go-micro/plugins/v4/store/nats-js"
        "github.com/go-micro/plugins/v4/store/redis"
+       redisopt "github.com/go-redis/redis/v8"
        "github.com/nats-io/nats.go"
        microetcd "github.com/owncloud/ocis/v2/ocis-pkg/store/etcd"
        microstore "go-micro.dev/v4/store"
@@ -173,6 +174,11 @@ func getStore(store string, nodes []string, database, table string, ttl time.Dur
                        microstore.Database(database),
                        microstore.Table(table),
                        microstore.Nodes(nodes...),
+                       microstore.Option(
+                               redis.WithRedisOptions(redisopt.UniversalOptions{
+                                       MasterName: "mymaster",
+                               }),
+                       ),
                ) // only the first node is taken into account
        case "memory":
                return microstore.NewStore(
```

Background see: https://github.com/redis/go-redis/blob/6ec458549ed0808ec57c303df9c922aba9520e14/universal.go#L214-L219

## Describe alternatives you've considered
- 

## Additional context
#5137 -> cache down, means oCIS dead. Therfore I need a way to provide a HA Redis like with sentinel.

**Comment by butonic** [comment]
The ocs cache defaults to an in memory cache with a TTL of 0. We should allow `redis-sentinel` as I expect a lot of shares... 

urgh but it is not implemented with a go micro store interface but reva/pkg/cache

In the gateway and storage providers we are using the go micro store, but it cannot get multiple keys with a single request. I haven't found a good way to request multiple keys with the micro api, yet.

**Comment by butonic** [comment]
related: https://github.com/cs3org/reva/issues/3742
