### ISSUE TITLE
[QA] Deleting a file larger than trashbin size fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#565]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

Try delete a 2GB file on a system where the trashbin is set up with `eos recycle config --size 1G`

![image](https://user-images.githubusercontent.com/1108546/93146375-f3229280-f6ee-11ea-8742-3896b34b13b2.png)

Try delete via desktop client:

![image](https://user-images.githubusercontent.com/1108546/93233413-55c17000-f77b-11ea-83fc-cf4e6291c016.png)

Expected behaviour: deletion is possible, Maybe warn and let user confirm.

Workaround: delete via command line: `eos -r 0 0 rm -F '/eos/dockertest/reva/users/4/4c510ada-c86b-4815-8820-42cdf82c3d51/New folder/2048MB-1B.mp3'`

**Comment by jnweiger** [comment]
Enhancement idea: Allow a user to disable their trashbin temporarily. It might be helpful when deleting very large objects.

**Comment by kobergj** [comment]
eos problem with rc1. Probably not relevant any more. Closing.
