### ISSUE TITLE
[QA] Phoenix: Large file download cannot be resumed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#566]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy
 * firefox on Ubuntu

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1
</pre>
</details>

Start download a 5.5GB file via firefox. While the download is in progress, pause the download:
![image](https://user-images.githubusercontent.com/1108546/93147630-126eef00-f6f2-11ea-93b6-46ed5adff070.png)

Then try to resume:
![image](https://user-images.githubusercontent.com/1108546/93147711-4518e780-f6f2-11ea-963a-3762b3d29cd7.png)

It hangs a while there with 'unknown time left'

![image](https://user-images.githubusercontent.com/1108546/93147751-5bbf3e80-f6f2-11ea-9eaf-38783dd4bf19.png)

then fails

![image](https://user-images.githubusercontent.com/1108546/93147577-f1a69980-f6f1-11ea-9891-9f69a1ef2a79.png)

**Comment by PVince81** [comment]
range requests currently not supported, so no resuming supported: https://github.com/owncloud/ocis-reva/issues/12

but I'd expect it to at least restart from the beginning ??

maybe the headers are not properly set or missing some proper status codes to inform browsers correctly

**Comment by jnweiger** [comment]
Reprodued with Deployed ocis-1.0.0-rc8 via ocis/deployments/examples/ocis_traefik/

Unchanged: downloads always restart.

**Comment by pascalwengerter** [comment]
Should be possible since Uppy has been introduced last summer

**Comment by kulmann** [comment]
> Should be possible since Uppy has been introduced last summer

Uppy is `everything upload` but not relevant for downloads. ;-)

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
