### ISSUE TITLE
Use Folder's name as ZIP filename, when downloading a folder

### ISSUE THREAD

**Issue by TheGranadilla** [owncloud/ocis#5668]
Archiver currently generate "download.zip" when user download a folder.
Archiver should use folder's name as zipfile name.

----------------------------------------------------------------------
Downloading multiple folders one by one will makes "download(1).zip, download(2).zip, download(3).zip..." files,
and it's painfull to sort this out once downloaded ^^

_Note :  Using ownCloud Web UI 6.0.0 / Infinite Scale 2.0.0 Community_

**Comment by micbar** [comment]
@fschade @kulmann Didn't we fix that already?

**Comment by kulmann** [comment]
Not to my knowledge. Just tested again on [our web demo instance](https://ocis.ocis-web.latest.owncloud.works) and that still announces `download.tar` as filename from the archiver service. As of https://github.com/owncloud/web/pull/8466 web really uses the filename that's announced in the archiver response. So I assume it needs to be fixed in the reva archiver service.

**Comment by pascalwengerter** [comment]
> Not to my knowledge. Just tested again on [our web demo instance](https://ocis.ocis-web.latest.owncloud.works) and that still announces `download.tar` as filename from the archiver service. As of [owncloud/web#8466](https://github.com/owncloud/web/pull/8466) web really uses the filename that's announced in the archiver response. So I assume it needs to be fixed in the reva archiver service.

Just dug around reva out of curiosity and found https://github.com/cs3org/reva/blob/605cec43f46ebef9846f50041dcf82af5027b138/internal/http/services/archiver/handler.go#L239 (using the name defined in the configuration) - also, there would need to be a differentiation between "downloading a folder as archive" (where it would be fine to use the folder name as archive name) and "downloading a selection of files" (where it is kinda unavoidable to have potentially repeating names, unless you e.g. pre-/postfix them with a download timestamp maybe?)
