### ISSUE TITLE
[QA] PROPFIND does not return the share-types of every item

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#567]
Requesting a `PROPFIND` to `/remote.php/dav/files/<user>`, share-types is empty (of course, item is shared):

oCIS:

`<oc:share-types></oc:share-types>`

oC10:

```
<oc:share-types>
          <oc:share-type>3</oc:share-type>
          <oc:share-type>0</oc:share-type>
</oc:share-types>
```

that makes the mobile clients not to show the sharing badges in the file list

Backend: EOS storage via via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
Version: v1.0.0-rc1
Client: iOS App v11.4 over iOS13

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
