### ISSUE TITLE
[QA] Cannot sync files shared with me using Desktop Client

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#568]
**Tested with** ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy and Desktop Client for Mac with Built from Git revision 4cb5cf on Sep 14 2020, 02:12:32 using Qt 5.12.9, OpenSSL 1.1.1g 21 Apr 2020

### Steps to reproduce

1. user A shares a file with user B
2. User b accepts the share
3. Try to sync the file shared (force sync)

### Expected behavior

File should be synced

### Current behavior

The file is not synced and we get a 500 error

<img width="1000" alt="Screenshot 2020-09-15 at 09 15 38" src="https://user-images.githubusercontent.com/10596560/93179856-8fbc5300-f736-11ea-8306-7dfbc10a6a7a.png">

Logs here: https://cloud.owncloud.com/index.php/s/DDcMTPgpk3hqpiE

**Comment by jesmrec** [comment]
Checking this issue with the iOS client, 500 is returned as well when trying to download an item inside the `/Shares` folder (shared with me):

![Screenshot 2020-09-15 at 09 42 43](https://user-images.githubusercontent.com/14894746/93180701-d78faa00-f737-11ea-9815-b2211b073222.png)

response's payload is empty

**Comment by phil-davis** [comment]
Similar issue in automated API tests: https://github.com/owncloud/product/issues/208
The share can be accepted, but downloading the data fails.

**Comment by jnweiger** [comment]
similar issue: https://github.com/owncloud/ocis/issues/582

**Comment by davitol** [comment]
> similar issue: #582

that issue looks like more to https://github.com/owncloud/ocis/issues/545 IMHO

**Comment by michaelstingl** [comment]
> response's payload is empty

@jesmrec this still an issue?

**Comment by jesmrec** [comment]
Not reproducible with `ocis-2.0.0`

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
