### ISSUE TITLE
[Extension] oCIS service configuration mgmt

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis#57]
oCIS extension following the extension framework #54 
- Allows extensions to add config options
- Allows sysadmins to configure config values, via cli, api, ...?

Question:
- can we map oc10 configs into this config mgmt extenison?

**Comment by PVince81** [comment]
Should we assume that OCIS endpoint/domain that serves the Phoenix frontend is also able to server the dynamic config.json ?

If not, then we need to keep the static config.json in place with a single value that advertises where the config endpoint is located.

**Comment by PVince81** [comment]
> can we map oc10 configs into this config mgmt extenison?

As far as I remember, not all config values are meant to be read by authenticated regular user clients.

In OC 10 we have:
- oc_appconfig: accessible via HTTP for reading/writing, only for **admin** users
- oc_preferences: not accessible via HTTP, but some custom endpoints allow changing some values by **regular users**
- capabilities: most values useful for clients are exposed here

So when designing what we call "config endpoints" we need to keep in mind these scopes.

**Comment by PVince81** [comment]
For the Phoenix specific ability to load configs and apps from custom URLs, I've raised https://github.com/owncloud/phoenix/issues/2544.

**Comment by butonic** [comment]
While owncloud/phoenix#2544 is partly solved by https://github.com/owncloud/phoenix/pull/1986 we still need to be able to pass a different config.json to ocis-phoenix when using the ocis single binary to run eg the demo flavor build, which only should only use the hello phoenix ui app.

I agree with @tboerger that we can automate it by discovering the ocis extensions via the registry. The registry can be watched for changes would allow dynamically updating the list of ocis extensions. Tracked in https://github.com/owncloud/ocis-phoenix/issues/20

Although that might be an opt in thing or an explicit admin action ... maybe by setting a flag for an extension or specifiying the groups/roles that have access?

**Comment by refs** [comment]
We'd need to distinguish between service configuration (port etc...) and dynamic config (settings), like phoenix configuration, where services poll or receive update messages from a config service.

@butonic this diverges from this issue, I suggest we open a new ticket with a more concrete description and define config vs settings and decide on an approach (viper vs [micro's go config](https://micro.mu/docs/go-config.html)).

**Comment by butonic** [comment]
@felixboehm please clarify the title of the issue. There is configuration management and there is settings management. It is not clear what we are tracking here.

The former is used to configure the services, eg ports, hostnames, tls, certificates. Whatever is necessary to run a service.

The latter is used to change the user, group or role based settings that affect the services functionality.
- They can be preconfigured by the admin, or any other user or group with the correct permissions.
- They may be set to readonly.
- They may be changed by users themselves.
Examples:
- default app for a filetype (= use mycustom app for .md files),
- background color (= readonly&always red if you have admin rights)

I assume you meant settings mgmt in the title. If so please clarify the title.

**Comment by butonic** [comment]
hehe so yeah @felixboehm  ... whit is this issue about? config or settings

**Comment by butonic** [comment]
As discussed in the standup this is about settings mgmt.

Micro has a [store service](https://godoc.org/github.com/micro/go-micro/store) which we could use to implement a settings service, based on kv pairs.

**Comment by tboerger** [comment]
> * store using go.micro.store service?

This is not released yet, 11 hours old.

**Comment by refs** [comment]
nah it's been around for a while, latest changes are the ones not yet released, they changed some interface and changes propagated.

**Comment by butonic** [comment]
when an extension evaluates settings it has to merge them according to precedence:
* cli option - highest precedence
* env var
* settings service
* default setting - lowest precedence
- [ ] there is a difference between specifying defaults and overriding the settings service ... not sure if env vars should override the settins service

micro uses the go.micro.config.Store interface for configuration and allows merging them: https://micro.mu/docs/go-config.html#multiple-sources
```
config.Load(
	// base config from env
	env.NewSource(),
	// override env with flags
	flag.NewSource(),
	// override flags with file
	file.NewSource(
		file.WithPath("/tmp/config.json"),
	),
)
```

The interface also allows watching config options: https://micro.mu/docs/go-config.html#watch-path

The ChangeSet used for values also uses an encoder and decoder so we can store arbitrary values and complex config structs as eg for phoenix external apps

Unfortunately, there is no namespacing or access control.
Furthermore, user or group specific spec settings are not handled.

AFAICT we really need a dedicated settings service with it's own proto based api.

**Comment by butonic** [comment]
@felixboehm I may have pushed this ticket too far into the direction of user settings. If this really is only about how to configure services, regardless of user or group preferences, then we have this covered:
- extensions use a config package to define their configuration, eg [ocis-hello](https://github.com/owncloud/ocis-hello/blob/master/pkg/config/config.go) or [ocis-phoenix](https://github.com/owncloud/ocis-phoenix/blob/master/pkg/config/config.go)
- admins can provide the configuration as env vars or cli options as described by a flagset [ocis-hello](https://github.com/owncloud/ocis-hello/blob/master/pkg/flagset/flagset.go) [ocis-phoenix](https://github.com/owncloud/ocis-phoenix/blob/master/pkg/flagset/flagset.go)

What is not covered is reading the config from another source, eg. redis or etcd, which would allow dynamic configuration. Which brings me back to https://micro.mu/docs/go-config.html#multiple-sources ... go micro has a way of loading config from multiple sources, but I cannot find the place where we could change that.

**Comment by butonic** [comment]
I reverted the title change of the issue back to configuration. It better reflects the current status of ongoing work.

What is missing is a plan how to add a kv store to the stack of config sources that can be used to dynamically change the service configuration.

go micro has the [config package](https://micro.mu/docs/go-config.html) to do that, but AFAICT it would require replacing the viper the configuration framework we are currently using. We can postpone this until next month though, unless we want to use and demo that in the upcoming worshops.

An opinion from @tboerger would be great. And a rough estimation.

**Comment by micbar** [comment]
-> closing in favour of https://github.com/owncloud/product/issues/17
