### ISSUE TITLE
[QA] public file link has actions that dont work

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#572]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * firefox on ubuntu 18.04

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

User einstein creates a shared linl on a file. E.g. Speech.ogg 
There are other files in the same folder

anonymous user opens the link in a different browser session.
The ogg file file is visible in a "folder view" -- only this file. OK.
It can be downloaded or played with the builtin media player. OK.

![image](https://user-images.githubusercontent.com/1108546/93182010-779a0300-f739-11ea-982e-dcb85174bfc1.png)

The "folder" offers "New+". The actions however don't work (and should not).
The "folder" offers a 3 dots menu. The "Remove" and "Rename" actions however don't work (and should not).

Expected behaviour: Hide actions from anonymous users that are not available.

**Comment by PVince81** [comment]
known issue, public link share permissions are not implemented yet, neither their enforcement nor exposing the correct letters in "oc:permissions" so the UI doesn't know yet what to hide.

ref https://github.com/owncloud/ocis-reva/issues/292 and https://jira.owncloud.com/browse/OCIS-193

**Comment by PVince81** [comment]
closing as duplicate
