### ISSUE TITLE
[QA] Ocis CI fails with SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5723]
## Describe the bug

Recently CI has been failing due to SignatureDoesNotMatch
```
1 error occurred:
	* MultipartUpload: upload multipart failed
	upload id: c7531398-a196-4816-924d-52a3441b308e
caused by: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: 1748D3AD50B028D2, host id: 
```

Failed Build :
- https://drone.owncloud.com/owncloud/ocis/19800/4/1
- https://drone.owncloud.com/owncloud/ocis/19578/4/5
- https://drone.owncloud.com/owncloud/ocis/19582/4/5

**Comment by saw-jan** [comment]
Haven't seen in a while. Can we close this now.
