### ISSUE TITLE
PROPPATCH to Favorites returns 500

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#573]
Request:

`PROPPATCH <url>/remote.php/dav/files/<user>/<itemName>`

with payload:

```
<?xml version="1.0" encoding="UTF-8"?>
<D:propertyupdate xmlns:D="DAV:" xmlns:oc="http://owncloud.org/ns">
  <D:set>
    <D:prop>
      <favorite xmlns="http://owncloud.org/ns">1</favorite>
    </D:prop>
  </D:set>
</D:propertyupdate>
```

returns `500 Internal Server Error`

So, in iOS client, when an item is favorited, an error is shown:

![Screenshot 2020-09-15 at 09 56 30](https://user-images.githubusercontent.com/14894746/93182235-bfb92580-f739-11ea-95b5-df17723697c7.png)

Environment:

Backend: EOS storage via via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
Version: v1.0.0-rc1
Client: iOS App v11.4 over iOS13

**Comment by PVince81** [comment]
EOS or OC storage ?

**Comment by jesmrec** [comment]
EOS

**Comment by PVince81** [comment]
EOS doesn't support Webdav properties yet, tracked in https://github.com/owncloud/ocis-reva/issues/189

**Comment by PVince81** [comment]
backlogged here https://jira.owncloud.com/browse/OCIS-534
