### ISSUE TITLE
[QA] Cannot name a file and a folder with the same name

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#575]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * firefox and Chrome in Mac

### Steps to reproduce

1. Create a folder named AAA
2. Try to create a text file with no extension named AAA

### Expected behavior

It should be possible to create the file

### Current behavior

It says  `AAA already exists`

<img width="1263" alt="Screenshot 2020-09-15 at 11 32 58" src="https://user-images.githubusercontent.com/10596560/93193652-6a841080-f747-11ea-80c2-635d2492c970.png">

**Comment by phil-davis** [comment]
Why is this a problem?
You can't do this in ownCloud10 either, or in most file-systems.

**Comment by PVince81** [comment]
agreed, not supported by any filesystems (except maybe GDrive which allows multiple names, yay)
