### ISSUE TITLE
Allow desktop client to cache resources

### ISSUE THREAD

**Issue by fmoc** [owncloud/ocis#5754]
Related: #5513, https://github.com/owncloud/client/pull/10526, https://talk.owncloud.com/channel/infinitescale?msg=9yG3dcnfCHiXygFDk

The desktop client wants to use Qt's built-in network cache to cache resources to both reduce the amount of data that needs to be fetched from the server and also to make data available for offline use.

The server's current cache policies prevent that. Qt prevents caching of resources that have `must-revalidate` set in the `Cache-Control` header (whether that is 100% accurate or not may be debated). Unfortunately,

Of course, we could hack around this locally, but I think it's better for everyone (and of course easier for us, too) if the server reviews the current cache policies and adjusts them where needed.

We are supposed to cache the following resources due to customer requests:

- server side theme (`theme.json` as well as the resources it points to; all of them can be downloaded without authentication)

Furthermore, what would be nice to cache in my opinion:

- user avatars

(These lists may be extended if we find additional resources to be cached.)

As far as I can tell, just removing `must-revalidate` should do the trick. To quote the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control):

> HTTP allows caches to reuse [stale responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#fresh_and_stale_based_on_age) when they are disconnected from the origin server. must-revalidate is a way to prevent this from happening - either the stored response is revalidated with the origin server or a 504 (Gateway Timeout) response is generated.

In general, `max-age` should be chosen in a sensible way. Instance themes rarely change, user avatars may change more frequently. It's up to you to decide on these values, of course.

If needed, you could serve different `Cache-Control` headers based on the user agent, but I don't think it makes a lot of sense to differentiate between web and native clients.

**Comment by michaelstingl** [comment]
@TheOneRing FYI

**Comment by micbar** [comment]
@fmoc See linked PR.
