### ISSUE TITLE
Using # in the onPremisesSamAccountName breaks getting users 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5755]
steps: 

- run ocis localy with demo users or create new user
- edit userName using `#`
`curl -XPATCH -uadmin:admin -vk   'https://localhost:9200/graph/v1.0/users/einstein' -H 'accept: application/json'   --data-raw '{"onPremisesSamAccountName":"einstein#1a"}'`

Actual: using of characters is allowed on the web and if I send a request with `#` I get 404. 
After that I cannot get all users with param `orderBy=displayName`. 
`curl -GET -uadmin:admin -vk https://localhost:9200/graph/v1.0/users?orderby=displayName`

https://user-images.githubusercontent.com/84779829/223475184-81dfcf62-16ee-4199-84ca-a86deada93d3.mov

- if I use `+` or `;` in the user name -> I get 500

<img width="1243" alt="Screenshot 2023-03-07 at 16 56 11" src="https://user-images.githubusercontent.com/84779829/223476515-c4c5dc32-05c7-403d-ac99-2138f24a923a.png">

- if use name as space -> server crashes

```
curl --location --request PATCH 'https://localhost:9200/graph/v1.0/users/marie' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: text/plain' \
--data-raw '{"onPremisesSamAccountName":" "}: '

```
```
panic: runtime error: index out of range [0] with length 0

goroutine 641 [running]:
github.com/libregraph/idm/pkg/ldbbolt.(*LdbBolt).EntryModifyDN(0x140010bee10, 0x140017abbd0)
        /Users/scharfviktor/Work/ocis/vendor/github.com/libregraph/idm/pkg/ldbbolt/ldbbolt.go:327 +0x200
github.com/libregraph/idm/server/handler/boltdb.(*boltdbHandler).ModifyDN(0x14000f93b00, {0x14000e3a060, 0x2b}, 0x140017abbd0, {0x108030e78, 0x14001e9c700})
        /Users/scharfviktor/Work/ocis/vendor/github.com/libregraph/idm/server/handler/boltdb/handler.go:240 +0x28c
github.com/libregraph/idm/pkg/ldapserver.HandleModifyDNRequest(0x131b44be0?, {0x14000e3a060, 0x2b}, 0x14000f938c0, {0x108030e78, 0x14001e9c700})
        /Users/scharfviktor/Work/ocis/vendor/github.com/libregraph/idm/pkg/ldapserver/modifydn.go:36 +0x32c
github.com/libregraph/idm/pkg/ldapserver.(*Server).handleConnection(0x14000f938c0, {0x108030e78, 0x14001e9c700})
        /Users/scharfviktor/Work/ocis/vendor/github.com/libregraph/idm/pkg/ldapserver/server.go:370 +0x628
created by github.com/libregraph/idm/pkg/ldapserver.(*Server).Serve
        /Users/scharfviktor/Work/ocis/vendor/github.com/libregraph/idm/pkg/ldapserver/server.go:204 +0xac
```

**Comment by rhafer** [comment]
The issues with `;` and `+`  are because we failed to properly escape the new LDAP DN in the Update Request: https://github.com/owncloud/ocis/blob/master/services/graph/pkg/identity/ldap.go#L587 

The `#` issue also seems to be related to escaping. But I am not quite sure yet where the bug is. Need to read up on that.

The crash with the single space user name is likely a but in libregraph-idm. But we should also add code to the graph api  to reject all whitespace users names.

**Comment by Excds** [comment]
I tested running this with an openldap as backend, and then I don't have a problem with a `#` in the username.

@rhafer Doesn't adding code to reject whitespaces kind of go against this one? https://github.com/owncloud/ocis/issues/5255
