### ISSUE TITLE
[QA] Client upload 1000 files has a nonfatal  authentication error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#576]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * and desktop daily (20200915) client ownCloud version 2.7.0 (build 2106) on Ubuntu 20.04

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

Reproducer

* connect client, wait for initial sync done.
* create a flat folder with 1000 files in the client sync folder with e.g. `randfiles.py -m 1000 -f 0  -b 1000000 -c 1000000 1000files_flat`
* the client syncs for ca 5 minutes, then shows one or few errors
![image](https://user-images.githubusercontent.com/1108546/93201839-061a7e80-f752-11ea-9d4c-60a1f3002b39.png)

* same with bigger files: `randfiles.py -m 1000 -f 0  -b 10000900 -c 10009000 1000files10M_flat`
![image](https://user-images.githubusercontent.com/1108546/93207122-c60bc980-f75a-11ea-904c-1f8a39d31171.png)

* the errors are resolved fine during a second sync run.

@TheOneRing Maybe one upload breaks while the auth token refreshes?

**Comment by jnweiger** [comment]
Client logfile:

[oc-200915_1223.log.zip](https://github.com/owncloud/ocis/files/5224351/oc-200915_1223.log.zip)

**Comment by TheOneRing** [comment]
```
09-15 12:33:39:594 [ info sync.httplogger ]:	"94ad4aa3-af5f-4f35-81bf-fd1463b738bc: Response: PROPFIND 401 https://135.181.96.230:9200/remote.php/webdav/ Header: { Content-Type: text/plain; charset=utf-8, X-Content-Type-Options: nosniff, Date: Tue, 15 Sep 2020 10:33:39 GMT, Content-Length: 25, } Data: [invalid or missing token\n]"
09-15 12:33:39:595 [ warning sync.networkjob ]:	QNetworkReply::AuthenticationRequiredError "Host requires authentication" QVariant(int, 401)

**Comment by TheOneRing** [comment]
Mybe I should have kept the client issue.
I assume the client should be more sturdy when that happens...

**Comment by jnweiger** [comment]
another variant. 
[oc-200915_1223.log.zip](https://github.com/owncloud/ocis/files/5224568/oc-200915_1223.log.zip)
during upload, it throws half a page of red error messages, faster than I can read, but immediately resums the upload. Not logging anything in activity not synced. and then eventually succeeds to upload just fine.

**Comment by PVince81** [comment]
I thought we increased the timeout to an hour or more @butonic

**Comment by jnweiger** [comment]
@butonic @PVince81 (sigh...) : fresh ocis deployment 5h ago also logs me out from web UI after 10min.

## Retested with
 * ocis master from 5h ago
 * appliance from https://github.com/owncloud/client/actions/runs/255830173

<details>
<summary> ocis master version details</summary>

<pre>
OCIS_VERSION:         master
ocis --version:       ocis version 7b8e9bc
git log:              commit 7b8e9bc2981c0fd9917bc576a291ab5231c02685 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
eos --version:        EOS 4.6.5 (2019)
xrootd -v:            v4.11.0
bin/ocis contains:
	owncloud/ocis-accounts@v0.4.2-0.20200911161616-e55b8ae2f440
	owncloud/ocis-glauth@v0.5.1-0.20200909064150-0735ec933777
	owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
	owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
	owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
	owncloud/ocis-konnectd@v0.3.2
	owncloud/ocis-migration@v0.2.0
	owncloud/ocis-ocs@v0.3.2-0.20200916110615-7ca52baa61c4
	owncloud/ocis-phoenix@v0.13.1-0.20200910090722-8e3ed0e966a5
	owncloud/ocis-pkg/v2@v2.4.1-0.20200902134813-1e87c6173ada
	owncloud/ocis-proxy@v0.7.1-0.20200907105449-201b9a652685
	owncloud/ocis-reva@v0.14.0
	owncloud/ocis-settings@v0.3.2-0.20200903035407-ad5de8264f91
	owncloud/ocis-store@v0.1.1
	owncloud/ocis-thumbnails@v0.3.0
	owncloud/ocis-webdav@v0.1.1
</pre></details>

@TheOneRing appliance from https://github.com/owncloud/client/actions/runs/255830173 did an upload of 1000 files. No temporary error messages seen! :partying_face:

**Comment by kobergj** [comment]
No action since ~4 years. Closing.
