### ISSUE TITLE
Changing user with an uppercase name gives 404 error

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5763]
Steps:

- Create a user with an uppercase name (it's important)
curl -XPOST -uadmin:admin -vk   'https://localhost:9200/graph/v1.0/users' -H 'accept: application/json'   --data-raw '{"onPremisesSamAccountName":"Bob","displayName":"bob bob","mail":"bob@bob.de","passwordProfile":{"password":"123"}}:'

- try to change userName:
curl -XPATCH -uadmin:admin -vk   'https://localhost:9200/graph/v1.0/users/Bob' -H 'accept: application/json'   --data-raw '{"onPremisesSamAccountName":"newName"}'

Actual: 404 instead of 200 but user name was changed cc @rhafer

**Comment by rhafer** [comment]
This is a bug in libregraph/idm. It doesn't handled the the case ignore matching correctly it seems.

This but should not be an issue with a "real" LDAP server.

**Comment by S-Panta** [comment]
Closing this issue because a similar issues has been reported here. https://github.com/owncloud/ocis/issues/7044
