### ISSUE TITLE
Renaming (deprecate) ennvar FRONTEND_OCS_HOME_NAMESPACE

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5767]
References: #5749

The envvar: `FRONTEND_OCS_HOME_NAMESPACE` should be renamed and the description updated using the [deprecation process](https://owncloud.dev/ocis/development/deprecating-variables/).

`FRONTEND_OCS_HOME_NAMESPACE` --> `FRONTEND_OCS_PRIVATE_NAMESPACE`

In all documentations including the webui and writings we use `PRIVATE` (like private space, contrary to public space) and not `HOME`. We should keep it consistent.

@butonic, @kobergj
@C0rby as discussed

**Comment by butonic** [comment]
Why `PRIVATE`? In the msgraph api the type of a users personal drive is `personal` not `private`. Project spaces have type `project`. I do understand that `HOME` is bad but `PRIVATE` is actuallyy too strong and in unix systems may be connotated with an encrypted 'Private' folder. So I'd go with `FRONTEND_OCS_PERSONAL_NAMESPACE`.

**Comment by mmattel** [comment]
🤦‍♂️ it should be PERSONAL 🤦‍♂️ (sorry...)
