### ISSUE TITLE
Improve max_quota setting - Backend edition

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#5778]
# Description

Backend edition of https://github.com/owncloud/web/issues/8536

## To do

- [x] Do not return 500 error code, better "invalid request" or something fitting
- [x] Handle `0` values (which are resolving as `unlimited`)
- [x] Quick check with @JanAckermann 

## Bonus

- [ ] move the logic from the DecomposedFS to the storage provider to have it driver-agnostic

**Comment by micbar** [comment]
@C0rby

**Comment by C0rby** [comment]
The fixes were implemented here: https://github.com/owncloud/ocis/pull/5785 and https://github.com/cs3org/reva/pull/3714
