### ISSUE TITLE
[QA] Several kind of files returned as octet-stream 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#578]
Video files like mp4, txt files, MS Office files, zip files (probably more) are returned as:

`<d:getcontenttype>application/octet-stream</d:getcontenttype>`

instead of their types.

That makes the mobile clients to show a placeholder instead of the correct file icon.

Backend: EOS storage via via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
Version: v1.0.0-rc1
Client: iOS App v11.4 over iOS13

**Comment by PVince81** [comment]
need to check if the docker containers are installing the mime types package for detection, like https://github.com/owncloud/ocis-reva/pull/221/commits/b03529224f422ee1c496b1982260193799da56f1
that used to be an issue for the OC storage, not sure if EOS also uses the same Golang library

**Comment by michaelstingl** [comment]
@jesmrec this still an issue?

**Comment by jesmrec** [comment]
Not reproducible with `ocis-2.0.0`. Any way to check with EOS storage?

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
