### ISSUE TITLE
add/remove multiple users from group via one request

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/ocis#5783]
## Describe the solution you'd like
To keep the backend request for web limited, we need the possibility to add/remove multiple users from a group via one request

MS Graph also provides an example for this 
https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http

```
PATCH https://graph.microsoft.com/v1.0/groups/{group-id}
Content-type: application/json

{
  "members@odata.bind": [
    "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
    "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
    "https://graph.microsoft.com/v1.0/directoryObjects/{id}"
    ]
}
```

**Comment by rhafer** [comment]
@JanAckermann For adding multiple members this is already implemented since quite a while.

For removing multiple members MS Graph doesn't make any specification IIRC. Also I am unsure if this is really worth it. Yeah, you'd save a couple of roundtrips between web and graph, but OTOH the user management APIs are not that performance critical.  It's not that we constantly add and remove groupmembers in batches.

**Comment by rhafer** [comment]
@JanAckermann BTW, please note that there is a limit of how many members you can add in one batch. (AFAIK it defaults to 20)

**Comment by JanAckermann** [comment]
@rhafer 
Thank you. 
I think it is crucial that we add those information to the specs e.G. swagger.

**Comment by JanAckermann** [comment]
@rhafer oh that's weird tho, I always have a look in the swagger UI or here https://owncloud.dev/apis/http/graph/groups instead of some yaml files. 
Anyways, I would love to implement the chunking for add/remove users from groups if both endpoints exist and we have a consistency

**Comment by micbar** [comment]
Just asking, what happens when a single group fails in the request?

We have the API promise that we don't do "bad things" like doing non-atomic operations which could fail silently.

**Comment by rhafer** [comment]
> Just asking, what happens when a single group fails in the request?

We currently only allow adding multiple users to a single group in one request.  In the LDAP backend that boils down to a single LDAP request on the group. That request either succeeds completely (all members added) or fails (no member added)

> We have the API promise that we don't do "bad things" like doing non-atomic operations which could fail silently.

I think at least for the "add multiple user to a group at once" operation this promise is ful-filled.

Somehow I think adding support for https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#example-2-add-multiple-members-to-a-group-in-a-single-request to libregraph was a bad idea.

Especially as it lacks the counter part of being able to remove users from a group in batch. And (as you might have noticed :smile: ) I am really hesitant to invent something libregraph specific here.

**Comment by ScharfViktor** [comment]
I guess it's not going to be fixed. closed as not planned
 please re-open if I'm wrong
