### ISSUE TITLE
 Try to add group to a group return 204 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5793]
## Describe the bug

While trying to add a group to a group, 204 HTTP status code was returned but the group doesn't contain any user or group in it

## Steps to reproduce

1. Create two groups `student` and `CSIT`
2. add user `einstein` to the group `CSIT`
3. add group `CSIT` to group `student`

## Expected behavior
The HTTP status code should be 400 or 403 

## Actual behavior
Http status code 204 but the user of group `CSIT` doesn't list as a group member of `student`

**Comment by Excds** [comment]
@amrita-shrestha The PR #5993 "fixes" this problem, but probably not in the way it was meant. The new behavior returns a 400 error with '"json: unknown field "@odata.id"', so then the request to try to add a group to a group is invalid because of the stricter json decoding.

Can you update the feature test so that it doesn't get a problem with  the 400 because of json parsing? I think the incorrect returning of a 204 is still there if we wouldn't be more strict with the json parsing.

**Comment by individual-it** [comment]
@Excds I think that is the same data that is needed to add correctly a user to group. The only difference I see is that when trying to add a group to a group a "PATCH" request is send and correctly adding a user to a group uses a POST request
What would be the data to trigger the original tag?

**Comment by rhafer** [comment]
@individual-it Can you paste the exact request you're sending to add a group to a group? I am still surprised that #5993 would really fix this issue.

**Comment by rhafer** [comment]
@amrita-shrestha really? Looking at https://github.com/owncloud/ocis/blob/master/tests/TestHelpers/GraphHelper.php#L599 it seem the test suite still sends a patch request with the `@odata.id` property. That would be wrong.

**Comment by amrita-shrestha** [comment]
@rhafer Later I tried to find the bug excds mentioned in a different way so I sent you a different approach I tried.  
In the feature file I have done a combination of two API requests.
```
curl --location --request PATCH 'https://localhost:9200/graph/v1.0/groups/167cbee2-0518-455a-bfb2-031fe0621e5d' \
--header 'Content-Type: application/json' \
--data-raw '{
    "@odata.id": "https://localhost:9200/graph/v1.0/groups/cedc21aa-4072-4614-8676-fa9165f598ff"
}'
```

**Comment by rhafer** [comment]
> @rhafer Later I tried to find the bug excds mentioned in a different way so I sent you a different approach I tried. In the feature file I have done API requests.
> 
> ```
> curl --location --request PATCH 'https://localhost:9200/graph/v1.0/groups/167cbee2-0518-455a-bfb2-031fe0621e5d' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "@odata.id": "https://localhost:9200/graph/v1.0/groups/cedc21aa-4072-4614-8676-fa9165f598ff"
> }'
> ```

This one is actually wrong. We should fix that in the test suite to issue either of the requests you mentioned in https://github.com/owncloud/ocis/issues/5793#issuecomment-1497334266
Otherwise we're testing the wrong thing I think.

**Comment by amrita-shrestha** [comment]
issue resolved so closing this issue
