### ISSUE TITLE
[QA] paused client upload does not resume from file offset

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#581]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * and desktop daily (20200915) client ownCloud version 2.7.0 (build 2106) on Ubuntu 20.04

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

Reproducer

* connect client, wait for initial sync done.
* copy a 2GB file in the client sync folder.
* watch the sync progress bar. 
* pause sync, when progress is beyond 50%
* resume sync

Result: the upload is restarted from the beginning of the file

Expected behaviour: The upload continues from the file position it was paused.

@TheOneRing please check if the expected behaviour is feasable.

**Comment by PVince81** [comment]
please note that range requests are not implement yet in ocis: https://github.com/owncloud/ocis-reva/issues/12

**Comment by TheOneRing** [comment]
This is a client bug, at the moment the client only keeps track of the upload in the upload job, which supports 90% of all uses cases besides a client restart or pause. pause is probably deleting the upload job.....

**Comment by felixboehm** [comment]
@TheOneRing do you have a link to a corresponding issue in client repo?
Please post here and close this one.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/issues/8126

**Comment by michaelstingl** [comment]
Can be solved when clients can send their own ID prior to the upload.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
