### ISSUE TITLE
Changing the expiration date to past date for a shared sub item of project space in group share breaks ocis

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#5823]
## Describe the bug

Changing the expiration date to past date for a shared sub-item of project space in group share breaks ocis

## Steps to reproduce

1. Make user `einstien` space admin
2. As Einstein create a project space `test` and a resource inside the project space for eg. `testFolder`
3. Share the resource with a group for eg `radium-lovers`  with an expiration date
```console
curl -vk -u einstein:relativity --location --request POST 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' \
--form 'expireDate="2023-05-15T23:59:59+0545"' \
--form 'role="viewer"' \
--form 'shareType=1' \
--form 'space_ref="<file-id>"' \
--form 'shareWith="radium-lovers"'
```
4. Update the share by sending the expiration date to some past date
```console
curl -vk -u einstein:relativity --location --request PUT 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/<share-id>' \
--form 'expireDate="2023-01-10T23:59:59.999+01:00"'
```

> Note: the response of this request returns successfully. But after sometimes the server just crashes.

## Expected behavior
The share is removed when share is updated with a past expiration date in case of user/group share of resources of personal space and the behavior is the same for the sharing of project space as well.

## Actual behavior
The ocis server breaks. This behavior only exists while updating the expiration date of the sub-item of space in a group share to a past date, in case of user share it behaves normally.  The ocis server cannot be restarted after this. Only after removing the `.ocis` file and initializing the server again, it starts working. 

## Setup

OCIS_COMMIT_ID = 06e2fee99ac77e8c24b37ac6b4829f1b58ab4a83

## OCIS LOGS
```console
{"level":"error","service":"sharing","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"curl/7.81.0","from":"tcp://127.0.0.1:57692","uri":"/cs3.sharing.link.v1beta1.LinkAPI/GetPublicShare","start":"14/Mar/2023:14:04:01 +0545","end":"14/Mar/2023:14:04:01 +0545","time_ns":1166256,"code":"Unknown","time":"2023-03-14T14:04:01.373415469+05:45","message":"unary"}
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"curl/7.81.0","from":"tcp://127.0.0.1:48992","uri":"/cs3.gateway.v1beta1.GatewayAPI/GetPublicShare","start":"14/Mar/2023:14:04:01 +0545","end":"14/Mar/2023:14:04:01 +0545","time_ns":1410647,"code":"Unknown","time":"2023-03-14T14:04:01.373501374+05:45","message":"unary"}
{"level":"error","service":"userlog","error":"error getting user: user not found","userid":"37dc7a6a-cf9b-49b3-9ca6-c94b791de822","time":"2023-03-14T14:04:22.889845739+05:45","message":"failed to impersonate user"}
panic: cannot create context from nil parent

goroutine 440 [running]:
context.WithValue({0x0?, 0x0?}, {0x24d5b80?, 0x3cb3708?}, {0x28befe0?, 0x54b3f78?})
	/home/swikriti/.gobrew/current/go/src/context/context.go:525 +0x178
go.opentelemetry.io/otel/trace.ContextWithSpan(...)
	/home/swikriti/go/pkg/mod/go.opentelemetry.io/otel/trace@v1.14.0/context.go:25
go.opentelemetry.io/otel/trace.noopTracer.Start({}, {0x0, 0x0}, {0xc002ca16f8?, 0x414116?}, {0x262eb40?, 0x2685a80?, 0xc003f43300?})
	/home/swikriti/go/pkg/mod/go.opentelemetry.io/otel/trace@v1.14.0/noop.go:53 +0x7c
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryClientInterceptor.func1({0x0, 0x0}, {0x2b837c1, 0x28}, {0x28c3c40, 0xc003f43280}, {0x28c3d60, 0xc003f43300}, 0xc001910700, 0x37eebc8, ...)
	/home/swikriti/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.4/interceptor.go:93 +0x273
google.golang.org/grpc.(*ClientConn).Invoke(0x7f6c8cb1cf18?, {0x0?, 0x0?}, {0x2b837c1?, 0x0?}, {0x28c3c40?, 0xc003f43280?}, {0x28c3d60?, 0xc003f43300?}, {0x0, ...})
	/home/swikriti/go/pkg/mod/google.golang.org/grpc@v1.53.0/call.go:35 +0x223
github.com/cs3org/go-cs3apis/cs3/gateway/v1beta1.(*gatewayAPIClient).GetGroup(0xc000612110, {0x0, 0x0}, 0xc003e5e7e0?, {0x0, 0x0, 0x0})
	/home/swikriti/go/pkg/mod/github.com/c0rby/go-cs3apis@v0.0.0-20230110100311-5b424f1baa35/cs3/gateway/v1beta1/gateway_api.pb.go:1835 +0xc9
github.com/owncloud/ocis/v2/services/userlog/pkg/service.(*UserlogService).getGroup(0xc001a26210, {0x0, 0x0}, {0xc003a17410, 0x24})
	/home/swikriti/www/ocis/services/userlog/pkg/service/service.go:388 +0xd6
github.com/owncloud/ocis/v2/services/userlog/pkg/service.(*UserlogService).resolveGroup(0xc003e5e7e0?, {0x0?, 0x0?}, {0xc003a17410?, 0x24?})
	/home/swikriti/www/ocis/services/userlog/pkg/service/service.go:328 +0x35
github.com/owncloud/ocis/v2/services/userlog/pkg/service.(*UserlogService).resolveID(0xc001a26210?, {0x0?, 0x0?}, 0xc002ca1cb8?, 0x20?)
	/home/swikriti/www/ocis/services/userlog/pkg/service/service.go:323 +0x46
github.com/owncloud/ocis/v2/services/userlog/pkg/service.(*UserlogService).MemorizeEvents(0xc001a26210, 0xc000b52600?)
	/home/swikriti/www/ocis/services/userlog/pkg/service/service.go:110 +0x34c
created by github.com/owncloud/ocis/v2/services/userlog/pkg/service.NewUserlogService
	/home/swikriti/www/ocis/services/userlog/pkg/service/service.go:72 +0x378

```

**Comment by micbar** [comment]
@butonic @C0rby Can one of you take a look?

**Comment by C0rby** [comment]
Yes, I can take a look tomorrow.

**Comment by C0rby** [comment]
I found out what is happening but don't have an idea for a fix yet.

The root cause is here: https://github.com/owncloud/ocis/blob/ea8181548aba80a2e55398ca11daef79ef6a44a8/services/userlog/pkg/service/service.go#L113

The call to `ul.impersonate` is supposed to return an authenticated `context.Context`. In this error case this call returns `nil` instead which is why a subsequent step in the grpc tracing interceptor panics.

Now the reason why `ul.impersonate` returns nil is because it can't find the user. `e.ShareOwner` in this case is this technical "space owner user" of type `USER_TYPE_SPACE_OWNER` because this share exists inside of a project space.

I'm not sure if it should be able to impersonate this type of user. 

@kobergj, maybe you have an idea how to properly fix this?

**Comment by kobergj** [comment]
I see. Good Finding!

We should not send further request when the `ctx == nil` this is imho the first step to avoid future panics.

Second we need to find another user to impersonate. Any space member would do I think. Do we have such information on the event already? If not we need to add it.

**Comment by C0rby** [comment]
> We should not send further request when the `ctx == nil` this is imho the first step to avoid future panics.

Agree. :+1: 

> Second we need to find another user to impersonate. Any space member would do I think. Do we have such information on the event already? If not we need to add it.

No, unfortunately we don't have such information. I'm also seeing the risk of bloating the events when we would add all members of a space or even just some members (which ones?).

**Comment by kobergj** [comment]
Mmmh. We don't need to add all of them. Just one is enough. Maybe we could add a field `SpaceOwner` that contains a random manager of this space? (or the space owner in case of a personal space)

Note: We have all members already attached to the `SpaceDeleted` event. This is necessary as we otherwise can't reconstruct the members of this space.

**Comment by kobergj** [comment]
Avoid of the panic is here: https://github.com/owncloud/ocis/pull/6115

Proper fix comes with service accounts

**Comment by SwikritiT** [comment]
Sending the request with past expiration date doesn't break ocis now and the share is also removed successfully. I'll make a PR enabling the skipped test
