### ISSUE TITLE
using so many ports 

### ISSUE THREAD

**Issue by happyxhw** [owncloud/ocis#5844]
## Describe the bug

./ocis server: using two many ports

## Steps to reproduce

1. ./ocis init
2. ./ocis server

## Expected behavior
start service

## Actual behavior
use many ports, service did not run

![image](https://user-images.githubusercontent.com/44490504/225344810-96cecb0b-8b31-4a45-a2f7-83b565aab482.png)

**Comment by isasmendiagus** [comment]
This is an expected behaviour. The binary bundles severals services, that's why you see all of those ports

**Comment by butonic** [comment]
So, yeah we open up a ton of ports. Every service opens at least two ports: a service port for e.g. HTTP/GRPC/LDAP ... and a debug port that is used to check the health of the service.

What I am not happy about is that we currently statically assign most of the ports. go micro, the framework we use actually allows us to just register ports dynamically and use a proper service registry e.k. in kubernetes.

At the other end of the spectrum for small deployments we could use unix sockets or ... and I am aware of the joke ... even use in memory transports. The go micro registry should be able to make this configurable.

Currently, our focus is [on other things](https://owncloud.com/roadmap). Happy to review any PRs ;-)

**Comment by dragotin** [comment]
Not a real bug report, as that is expected for microservices architecture.
