### ISSUE TITLE
[notifications] Notification received about own action

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ocis#5865]
## Describe the bug

I received a notification about my own action

## Steps to reproduce

1. Create space
2. Disable space

## Expected behavior
I don't get a notification.

## Actual behavior
I get a notification "{username} deactivated space {spacename}

Interestingly, I don't get a notification when activating the space.

## Setup
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by ScharfViktor** [comment]
Just wondering, should the user get a notification if the user shares a space or resource with a group of which he is a member?

Actual: he gets notification

**Comment by hurradieweltgehtunter** [comment]
Also: When I delete a space, I also get a notification about my own action.

**Comment by hurradieweltgehtunter** [comment]
> Just wondering, should the user get a notification if the user shares a space or resource with a group of which he is a member?
> 
> Actual: he gets notification

From my point of view, the user performing an action should not get any notification about the particular action. From my understanding, the purpose of notifications is to notify the user about actions he is a passive participant of.

**Comment by kobergj** [comment]
I agree, no need to bother POs. Here is the fix: https://github.com/owncloud/ocis/pull/5873

Note: For `SpaceEnabled` events currently no notification is send.

**Comment by kobergj** [comment]
@ScharfViktor in tests/e2e/cucumber/features/smoke/notifications.ocis.feature:15 it is tested that a user receives a notification for his own event. Should I set it as expected failure?

https://drone.owncloud.com/owncloud/ocis/20572/66/10

**Comment by ScharfViktor** [comment]
I change e2e test for that

**Comment by kobergj** [comment]
I'll fix it in same PR.

**Comment by ScharfViktor** [comment]
Closed as completed https://github.com/owncloud/ocis/pull/5873
