### ISSUE TITLE
Space admin cannot get space by ID

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#5867]
Current grpc endpoints will not allow a spaceadmin to get space by ID. Decomposedfs implementation will only allow space members to get the space when id filter is set.

Workaround: Get all spaces, then loop through result until you find your space.

**Comment by ScharfViktor** [comment]
retested: space admin can get spaces by ID

<img width="887" alt="Screenshot 2024-01-17 at 23 05 14" src="https://github.com/owncloud/ocis/assets/84779829/5a0a4ac7-e501-4f5a-8e06-d49a2d5a4da4">
