### ISSUE TITLE
Add service/<service>/README.md contents to dev docs

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#5881]
We started to create README.md files for all services in ocis a while ago.

Currently there is some overlap between those README files and what is written in the dev docs on https://owncloud.dev

We should avoid duplication add some automation that adds the contents of the various READMEs  to the appropriate sections
when building the developer docs. (Avoiding to duplicate the content within the ocis repo)

**Comment by butonic** [comment]
When generating the documentation we can iterate over the services/*/Readme.md files and use them to populate the _index.md file used by hugo.

Using a template we can
1. use the Readme h1 as the title in the markdown preamble
2. use the text below the h1 in the readme as the content for the abstract
3. add a toc 
4. copy the rest of the readme.md as is
5. bump the date in the markdown preamble

We may have to think about images in the readme ... either by convention or as a subsequent PR. The graph service has a sequence diagram .... maybe we inline them via mermaid...

**Comment by kobergj** [comment]
Implemented here: https://github.com/owncloud/ocis/pull/5903
