### ISSUE TITLE
Adding multiple users in a group with invalid attribute returns 204

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#5888]
## Describe the bug

While adding multiple users in a group using the attribute `@odata.id` instead of `members@odata.bind` returns `204`.
Users are not added in the group which is as expected but the status returned in the response is not as expected.

## Steps to reproduce

1. Create multiple users `Alice` and `Carol`
2. Create a group `group1`
3. Add users `Alice` and `Carol` to group `group1` using the attribute `@odata.id`

```
{
    "@odata.id": [
        "https://localhost:9200/graph/v1.0/users/4c510ada-c86b-4815-8820-42cdf82c3d51",
	"https://localhost:9200/graph/v1.0/users/c54b0588-7157-4521-bb52-c1c8ca84ea71"
    ]
}
```

## Expected behavior
Users should not be added in the group and the status code should be `400`.

## Actual behavior
Users are not added in the group and the status code is `204`.

**Comment by rhafer** [comment]
@butonic, @micbar We're currently unmarshalling the incoming request bodys with the default settings for the JSON decoder, which means that unknown fields in the json body will just get ignored. (In this case e.g. the `@odata.id` property, which means the request is basically a no-op, hence the 204 status)

Should we change that behaviour and set  json.Decoder.DisallowUnknownFields() (https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields) ? That would make the decoder throw an error on such a request. wdyt?

BTW: This is not limited to the /groups endpoint. I think all the graph endpoint behave similar in the regard.

**Comment by PrajwolAmatya** [comment]
If empty JOSN is send then it returns `400`.
