### ISSUE TITLE
Update the typescript version in IDP to be aligned with web

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5899]
With the [bump of I18next](https://github.com/owncloud/ocis/pull/4941), we identified that the typescript version in the IDP service
(typescript: ^4.1.2 and 4.7.4, pnpm-lock.yaml)
could be upgraded to 4.9.4 to be aligned to the version used in web, though it is independent to web.

@micbar @rhafer @JammingBen

**Comment by mmattel** [comment]
dont close

**Comment by pascalwengerter** [comment]
This has been done by @rhafer ~14 months ago and can be closed

**Comment by rhafer** [comment]
I guess this was the PR https://github.com/owncloud/ocis/pull/7207
