### ISSUE TITLE
Extend oCIS extensions for native clients (desktop and mobile)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#59]
As an example, we could have a look at [The Swan Service](https://swan.web.cern.ch/) (Jupyter notebook) that can be integrated nicely in the ownCloud web UI, but what about usage on native clients on desktop and mobile…

### 1) [Desktop] Support to open certain file types in 3rd party app in web UI

- Swan extension registered in oCIS backend
- Swan extension registered in Phoenix web UI (additional entry in `⋯` / `︙` menu)
- API needed to announce capability for this file type to the ownCloud desktop client
- ownCloud desktop sync client then could add a custom "Use Swan…" context menu entry in the file explorer
- ownCloud desktop client then should open `https://cloud.example.com/apps/swan/5032562…` in system browser

### 2) [iOS] Support to open certain file types in 3rd party web app in app-internal web view or in system browser

- Swan extension registered in oCIS backend
- Swan extension registered in Phoenix web UI (additional entry in `⋯` / `︙` menu)
- API needed to announce server capability for this file type to the ownCloud iOS app
- ownCloud iOS app then could add a custom "Open in Swan…" action menu entry in the "More…"  /  `⋯` / `︙` menu
- ownCloud iOS app then should open `https://cloud.example.com/apps/swan/5032562…` in app-internal web view or in system browser (tbd)

### 3) [iOS] Support to open certain file types in 3rd party native app installed on the users device

- Swan extension registered in oCIS backend
- Swan extension registered in Phoenix web UI (additional entry in `⋯` / `︙` menu)
- API needed to announce server capability for this file type to the ownCloud iOS app
- ownCloud iOS app then could add a custom "Open in Swan app…" action menu entry in the "More…"  /  `⋯` / `︙` menu
- ownCloud iOS app then should open 3rd party native app, using URI/URL scheme (`swan://…`) or something, to let the other app know how to access the file (needs detailed concept)

Imagine also a [native DICOM viewer](https://www.osirix-viewer.com/osirix/osirix-hd/) or similar apps for special use cases…

**Some technical background:**

- [iOS: Custom URL Scheme](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app)
- [Win/UWP: Launch an app with a URI](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-app-with-uri)
- [Ubuntu: URL protocol handlers](https://askubuntu.com/questions/514125/url-protocol-handlers-in-basic-ubuntu-desktop)
- [Uniform Resource Identifier (URI) Schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)

Maybe related: https://github.com/owncloud/core/issues/33337

Related Epic: https://github.com/owncloud/ocis/issues/54

**Comment by felix-schwarz** [comment]
From the iOS app side, this should all be doable - with one exception: since files live in the respective app's sandboxes, I'm not sure we can pass local copies of files without showing the share sheet. A quick round of research returned nothing relevant. :-/

**Comment by michaelstingl** [comment]
From an oC010 perspective, one approach would be, to announce to native clients via the capabilities endpoint (`/ocs/v1.php/cloud/capabilities?format=json`):

`ocs > data > capabilities > appSupport`
(proposal)

The following information is needed:

| platform-scope  | mime-type                | query-api                 | query-data-format | ui-text                             |
|-----------------|--------------------------|---------------------------|-------------------|-------------------------------------|
| web             | application/msword       | /apps/collabora/link-api  | path              | Edit Word file in Collabora         |
| web             | application/msword       | /apps/onlyoffice/link-api | path              | Edit Word file in OnlyOffice        |
| web             | application/vnd.ms-excel | /apps/collabora/link-api  | path              | Edit Word file in Collabora         |
| web             | application/vnd.ms-excel | /apps/onlyoffice/link-api | path              | Edit Word file in OnlyOffice        |
| web-ios         |                          |                           |                   |                                     |
| desktop         | application/swan         | /apps/swan/link-api       | path, fileID      | Edit in Swan web UI                 |
| desktop         | application/msword       | /apps/collabora/link-api  | path              | Edit Word file in Collabora web UI  |
| desktop         | application/msword       | /apps/onlyoffice/link-api | path              | Edit Word file in OnlyOffice web UI |
| desktop         | application/vnd.ms-excel | /apps/collabora/link-api  | path              | Edit Word file in Collabora web UI  |
| desktop         | application/vnd.ms-excel | /apps/onlyoffice/link-api | path              | Edit Word file in OnlyOffice web UI |
| desktop-windows | application/foo          | /apps/foo/link-api        |                   |                                     |
| ios             |                          |                           |                   |                                     |

Desktop app (all desktop platforms) would add an entry to the right-click/context menu for all file types that are associated with the Swan web editor. When clicking this entry, desktop client would query the provided  endpoint with the `path` OR `fileID` and, the app endpoint would return a link that points to the opened file view in the Swan web UI.

This way, also local applications could be opened. (needs an extension for this local application). `foo://some/info/here` would open local application that's associated with `foo` custom protocol.

**Comment by michaelstingl** [comment]
> I'm not sure we can pass local copies of files without showing the share sheet

I was more thinking about passing a link to the resource, not the actual file itself.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
