### ISSUE TITLE
Add an image to the ocis repo settings

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5926]
The ocis repo settings provide the ability to add an image used for social media preview inlcuding central. If not set and the repo gets linked, an empty frame with some standard text is shown and looks very unprofessional.

In docs, we have for each and every repo the image set, as example see: https://github.com/owncloud/docs-ocis/settings

Because these images do have a defined size and we have a common layout, it would be best to get one from marketing similar as done for all doc repos. I already asked marketing with some ideas and will provide an image as suggestion when recieved in this issue.

The settings change must be done by one who has proper repo rights.

@micbar @butonic

**Comment by micbar** [comment]
done. Thank you for taking care!
