### ISSUE TITLE
[stable-2.0] Space admin trying to set personal space quota returns status code 200

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#5947]
## Describe the bug

In `stable-2.0`, when `Space Admin` tries to set personal space quota of other users then the HTTP Status code on response is `200`.
This behaviour is only occuring in the stable-2.0 branch.

## Steps to reproduce

1. Create a Space Admin `Alice` and a normal user `Brian`.
2. `Alice` set the personal space quota of user `Brian`.

## Expected behavior
Space Admin should not be able to set personal space quota of other users. And the HTTP status code should be `401`.

## Actual behavior
Space Admin is able to set personal space quota of other users. And the HTTP status code is `200`.

**Comment by amrita-shrestha** [comment]
A similar issue https://github.com/owncloud/ocis/issues/5475 has been closed because this issue has been resolved for the master branch. I think we don't backport developer-side changes to the stable branch so it still exists for the stable branch

**Comment by micbar** [comment]
correct, we do not backport.
