### ISSUE TITLE
2-Factor Authentication 2FA

### ISSUE THREAD

**Issue by functioneer** [owncloud/ocis#5961]
## Is your feature request related to a problem? Please describe.
Many enterprises nowadays require Multi-Factor Authentication MFA or Two-Factor Authentication 2FA.   

## Describe the solution you'd like
Email 2FA authentication for logging into OCIS.   A verification code will be sent to the user's email address.    Although email 2FA is not very secure, it is very convenient to users as compared to say TOTP authentication (e.g., Google Authenticator) which requires users to install a 2FA TOTP app on their phones (which some users might not want to do).   OCIS can have a few options of 2FA.   But start with email 2FA first.

## Describe alternatives you've considered
None

## Additional context
None

Thank you very much!

**Comment by micbar** [comment]
hi @functioneer 

Thanks for that idea!

I have good news. Ocis can be run with 2FA using our keycloak configuration example. By default, Keycloak supports ToTP, but here you can see how to use e.g. E-Mail https://medium.com/@mesutpiskin/two-factor-authentication-via-email-in-keycloak-custom-auth-spi-935bbb3952a8

## Bigger Picture

ocis is a file management solution. Identity Management is an external dependency. We are shipping a  default IdM solution together with oCIS in the binary. It is called LibreIdm (https://github.com/libregraph/idm) and we also bundle a small OpenIDConnect Provider LibreConnect (https://github.com/libregraph/lico). Lico and LibreIDM are supposed to be minimal. This is important for the agile and quick development of oCIS and for Testing purposes. 

The bundled IDM is a good solution for small installations and if you do not need features like 2FA and device management.

Anything beyond that requirement should use a "real" IDM solution like KeyCloak, authentik and others.

**Comment by functioneer** [comment]
Thank you micbar for the reply.   OCIS is great, very fast and responsive.
