### ISSUE TITLE
Renaming the group to `=` character in between a string makes the group disappear

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#5968]
## Describe the bug

Renaming the group to `=` character in between a string makes the group disappear

## Steps to reproduce

1. create a group `grp1`
```bash
curl -XPOST "https://localhost:9200/graph/v1.0/groups" -d'{"displayName":"grp1"}' -uadmin:admin -vk
```
2. Rename the group to something with `=` at  somewhere between other characters like `grp=1`
```bash
curl -XPATCH "https://localhost:9200/graph/v1.0/groups/<group-id>" \     
-d'{"displayName": "grp=1"}' -uadmin:admin -vk
```
> Note group id can be obtained from the response of POST request or `curl "https://localhost:9200/graph/v1.0/groups" -uadmin:admin -vk `
3. The request is successful with `204`
4. Now get the group
```bash
curl "https://localhost:9200/graph/v1.0/groups" -uadmin:admin -vk
```

## Expected behavior
As the rename was "successful", there should be a group with name `grp=1`

## Actual behavior
The group is not in response to the get request. Nor is it in the UI. But if resend the same request again
```bash
curl -XPATCH "https://localhost:9200/graph/v1.0/groups/792015d3-9b6c-4bb3-9147-e2114033bc37" \     
-d'{"displayName": "grp=1"}' -uadmin:admin -vk

```
I get a `409` conflict
```bash
< HTTP/1.1 409 Conflict
< Content-Length: 178
< Content-Type: application/json; charset=utf-8
< Date: Thu, 30 Mar 2023 10:19:09 GMT
< X-Graph-Version: 3.0.0-alpha.1+182c375d2
< 
{"error":{"code":"nameAlreadyExists","innererror":{"date":"2023-03-30T10:19:09Z","request-id":"swikriti-OptiPlex-3070/3oZtTCUzA1-001106"},"message":"Group name already in use"}}
* Connection #0 to host localhost left intact

```
But when I get it it's not there
```bash
curl "https://localhost:9200/graph/v1.0/groups" -uadmin:admin -vk  
```

```json
{"value":[{"displayName":"users","id":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa"},{"displayName":"sailing-lovers","id":"6040aa17-9c64-4fef-9bd0-77234d71bad0"},{"displayName":"violin-haters","id":"dd58e5ec-842e-498b-8800-61f2ec6f911f"},{"displayName":"radium-lovers","id":"7b87fd49-286e-4a5f-bafd-c535d5dd997a"},{"displayName":"polonium-lovers","id":"cedc21aa-4072-4614-8676-fa9165f598ff"},{"displayName":"quantum-lovers","id":"a1726108-01f8-4c30-88df-2b1a9d1cba1a"},{"displayName":"philosophy-haters","id":"167cbee2-0518-455a-bfb2-031fe0621e5d"},{"displayName":"physics-lovers","id":"262982c1-2362-4afa-bfdf-8cbfef64a06e"}]}
```
But if i rename it to something without `=` character in it. It gets shown again

## Setup
OCIS_COMMIT_ID= 182c375d2c46d7985339a0d9e1de8bd5cd89cd03

**Comment by SwikritiT** [comment]
Note that issues https://github.com/owncloud/ocis/issues/5966 https://github.com/owncloud/ocis/issues/5970 https://github.com/owncloud/ocis/issues/5969 might be related. I created them separately as behaviors weren't the same

**Comment by kobergj** [comment]
It's correct that the behaviour is different so creating a second issue was right :+1:

Although in this case the underlying issue is the same. So I am closing this in favor of https://github.com/owncloud/ocis/issues/5966
