### ISSUE TITLE
Add graph `api-test` to `(Delete | Change )` appRoleAssignments of a user 

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#6012]
### Description
Add `graph-api` test to change and unassign the appRoleAssignments of a user.

**EndPoint**: /graph/v1.0/users/{userID}/appRoleAssignments/{appRoleAssignmentID} 

- [x] delete app role of a user https://github.com/owncloud/ocis/pull/6030
- [x] change the app role of a user https://github.com/owncloud/ocis/pull/6040

***Note:Also check for other combination if can be added in a possible ways related to deletion and change of app role of a user***

**Comment by grgprarup** [comment]
What are the things prohibited or limited to users whose role is deleted?
Currently, when the user's role is deleted, the user can create folders through API, after folder creation user role is set to role `User`.
Some issues regarding status code are reported here https://github.com/owncloud/ocis/issues/5938, https://github.com/owncloud/ocis/issues/6035
Need some input here.
@micbar @individual-it @ScharfViktor

**Comment by rhafer** [comment]
> Currently, when the user's role is deleted, the user can create folders through API, after folder creation user role is set to role `User`.

The default behavior for users without a role assignment is described here: https://github.com/owncloud/ocis/tree/master/services/proxy#automatic-role-assignments

So, in an standard deployment, without any additional configuration, what you're seeing (user's are getting the "user" role assigned again) is the expected behavior.

**Comment by SwikritiT** [comment]
@grgprarup can this be closed now? Anything left to do?
