### ISSUE TITLE
Make Emails translatable via transifex

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#6025]
Email templates are currently stored in https://github.com/owncloud/ocis/tree/master/services/notifications/pkg/email/templates

1) Remove `RenderTemplate` code. Hardcode subjects and body as constants into a `templates.go` file. 
    - https://github.com/owncloud/ocis/blob/eb2347e1db7c7e8249113721b27ef66f42138977/services/notifications/pkg/service/service.go#L90
    - https://github.com/owncloud/ocis/blob/master/services/notifications/pkg/email/email.go

2) Use `Template` function to mark subjects and body as translatable strings
    - Compare https://github.com/owncloud/ocis/blob/master/services/userlog/pkg/service/templates.go

3) Add translation steps to `notifications` service Makefile
   - Compare https://github.com/owncloud/ocis/blob/master/services/userlog/Makefile#L37-L56

4) Not part of the ticket: Actually translate emails. We first need a way to determine the users preferred language.

cc @dragonchaser @mmattel

**Comment by micbar** [comment]
I found a new extractor which can also extract variables from template files:

https://github.com/vorlif/xspreak#xspreak

**Comment by micbar** [comment]
@kobergj @2403905 This is a good project for Roman 👍

**Comment by kobergj** [comment]
The new extractor is better than the one we use now. But we probably need a custom solution anyways because of https://github.com/owncloud/ocis/issues/5924

**Comment by 2403905** [comment]
@micbar @kobergj 
Please suggest: 
1. Should I add a new environment variable instead the NOTIFICATIONS_EMAIL_TEMPLATE_PATH?
2. Which one locale should be used until we determine the users preferred language?https://github.com/owncloud/ocis/pull/6038/files#diff-4849177b19f87c6711bf3fb8b7a84991cf06d64c8c8c05ff5e017c9cc26faa22R90
