### ISSUE TITLE
Admin user tries to unassign his/her own role gives 500 status code

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#6035]
## Describe the bug

When an Admin user tries to delete his/her own role gives a 500 status code, with a response body containing the message 403 Forbidden.

## Steps to reproduce

1. Create `user1`
2. Grant role `Admin` to `user1`
3. Delete `user1` role by `user1`

Endpoints:
- Get appRoleAssignmentId: /graph/v1.0/users/`user-id`/appRoleAssignments [id]
- Delete: /graph/v1.0/users/`user-id`/appRoleAssignments/`app-role-assignment-id`

```console
curl -kv -XDELETE -uuser1:1234 https://host.docker.internal:9200/graph/v1.0/users/37130879-7646-44be-9e6c-4ea67c2b7c50/appRoleAssignments/acd35c1a-274f-4483-8c64-83892b0a1e2d | jq
```

## Expected behavior
HTTP/1.1 403 Forbidden

## Actual behavior
HTTP/1.1 500 Internal Server Error

With response body:
```json
{
  "error": {
    "code": "generalException",
    "innererror": {
      "date": "2023-04-12T07:15:06Z",
      "request-id": "c612df5afef9/cBddd5avYf-003974"
    },
    "message": "{\"id\":\"ocis-settings\",\"code\":403,\"detail\":\"Removing own role assignment forbidden\",\"status\":\"Forbidden\"}"
  }
}
```

**Comment by rhafer** [comment]
This is proabably the same underlying problem as for #6037

**Comment by grgprarup** [comment]
Fixed by PR https://github.com/owncloud/ocis/pull/6276, so closing this.
