### ISSUE TITLE
Limit filename length

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#6049]
When creating (or renaming) files with very long names the server will throw a `500 INTERNAL SERVER ERROR` when the name is longer than the maximum filename length of the specific os.

This is not nice. Long filename should be catched and instead a `400 BAD REQUEST` should be returned. However it needs to be determined what the maximum filename length of the specific os is. It is commonly 255 bytes but can vary from os to os.

As it is easy and convenient I would create a configurable value for this. 
(But it would be killer-cool if the system could get that value somehow from os specifications)

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: create API tests

**Comment by kobergj** [comment]
Fixed with this https://github.com/cs3org/reva/pull/3807

At the moment it is not configurable, just uses hardcoded values. We can iterate over this when we see the need. Closing this for now.
