### ISSUE TITLE
Created file show different version number in ocis and oc10

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6050]
### Describe the bug
When we create the file with some content then **`the version doesn't exist in oc10`** but **`in ocis one version exist`** .

#### Question
- Is this actual behavior?

### Steps to reproduce
1. `admin ` create file `abc.txt` with content `sample text`

### Expected behaviour
Both backend should behave same

#### In oc10
No version exists for the file created with content
![versionoc10](https://user-images.githubusercontent.com/54478846/199886621-3f257ddf-b8fd-4a64-bde1-dec261d1f3f0.png)

#### In ocis
One version with 0B exists for the file created with content
![ocisversion](https://user-images.githubusercontent.com/54478846/199886664-725a3783-90d7-4b4d-8ba4-783a5a2e1a08.png)

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: both

**Comment by rhafer** [comment]
Let's close this. I think this discrepancy between oc10 and ocis is acceptable. Feel free to re-open if you disagree.
