### ISSUE TITLE
API tests for GDPR export

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#6059]
the GDPR export should be tested by API tests
1. generate personal data for a user e.g. upload files, create spaces, share items, etc.
2. send request to generate the export
3. download the report file using WebDAV
4. check content of the downloaded file using JSON schema

This might require multiple scenarios to test

CC @ScharfViktor

**Comment by SagarGi** [comment]
TODO scenarios: 
- [ ] check events when user is created
- [ ] check events when file is uploaded

and others as well.
