### ISSUE TITLE
OCIS_ADD_RUN_SERVICES description is not clear

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#6084]
References: #6071 ([full-ci] add optional services and fix config slice parser)

ocis-pkg/config/config.go

`OCIS_ADD_RUN_SERVICES` 
... Will add the listed services to the default configuration.

Where does one know what the default list looks like?

In addition we need to note that you can use both EXCLUDE and ADD, means:
`exclude` one of the default and `add` one that is not default... 

@kobergj @micbar pls clarify the "default" question.

**Comment by micbar** [comment]
We added that because we will not maintain a default list :-)

You can find out the current default by running `ocis list`.

**Comment by mmattel** [comment]
Thanks, I will file a PR to improve the description.
