### ISSUE TITLE
Determine the users preferred language to translate emails via Transifex.

### ISSUE THREAD

**Issue by 2403905** [owncloud/ocis#6087]
## Is your feature request related to a problem? Please describe.
Determine the users preferred language to translate emails via Transifex.
Related to issue https://github.com/owncloud/ocis/issues/6025

## Describe the solution you'd like
Pick up the ProfileLanguage from the user settings before the service is rendered the email for the GranteeUser. If the grantee is a group, retrieve the ProfileLanguage from each user.
Based on  ProfileLanguage render the email message.

## Describe alternatives you've considered
Currently for group events the service use the group name for greeting purpose. `Hello {ShareGrantee}, ` where ShareGrantee will be replaced by the group name. 
After the code changes, I can use the user name instead.
@micbar @kobergj Is it useful?

**Comment by micbar** [comment]
Like discussed in person: we should send individual emails per user.
