### ISSUE TITLE
panic / 502 Bad Gateway in authenticated webfinger

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#6102]
## Describe the bug

An authenticated request to `.well-known/webfinger` where the webfinger service runs as part of ocis (I did not test standalone) causes a panic in the Oidc middleware.

## Steps to reproduce

1. Start e.g. oCIS single binary or keycloak deployment example (= webfinger service running alongside ocis)
2. Obtain an access token
3. Use the access token to make an authenticated request to `.well-known/webfinger?resource=<issuerUrl>`

## Expected behavior
Webfinger service behaves as documented in https://owncloud.dev/services/webfinger/ - i.e. gives a response including the ocis instances the user has access to.

## Actual behavior
Request terminates with a `502 Bad Gateway`.

## Setup

Single binary or keycloak deployment example

## Initial findings

Running ocis with a debugger I found out that there is a panic happening in the oidc middleware:
`http: panic serving 127.0.0.1:48434: runtime error: invalid memory address or nil pointer dereference`

Set a breakpoint here:
https://github.com/owncloud/ocis/blob/0862ff6bb554268c24c6a92e10c07e1dcf03def1/ocis-pkg/middleware/oidc.go#L41
and step into `NewProvider`. The `doRequest` call will run into a `CertificateVerificationError` for an ocis with self signed certificate. Unfortunately I don't know how to make use of `OCIS_INSECURE=true` here....

The error then gets swallowed into nirvana here: https://github.com/owncloud/ocis/blob/0862ff6bb554268c24c6a92e10c07e1dcf03def1/ocis-pkg/middleware/oidc.go#L59

Finally running into a nil dereference here:
https://github.com/owncloud/ocis/blob/0862ff6bb554268c24c6a92e10c07e1dcf03def1/ocis-pkg/middleware/oidc.go#L67
when calling `provider.UserInfo`.

**Comment by dragonchaser** [comment]
It seems like, when using an internal IDP querying the oidc .well-knows an error gets thrown, resulting in an empty in https://github.com/owncloud/ocis/blob/0862ff6bb554268c24c6a92e10c07e1dcf03def1/ocis-pkg/middleware/oidc.go#L57.
