### ISSUE TITLE
ocis version shows always today as the "compiled" date

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#6124]
## Describe the bug

It looks like any version of ocis was compiled today

## Steps to reproduce

1. `ocis version`

## Expected behavior
it should show the real date of compilation

## Actual behavior
The date is always `today`
```
Version: 3.0.0-alpha.2+6ad31f113
Compiled: 2023-04-24 00:00:00 +0000 UTC

No running services found.
```

```
Version: 3.0.0-alpha.2
Compiled: 2023-04-24 00:00:00 +0000 UTC

No running services found.
```

```
Version: 2.0.0
Compiled: 2023-04-24 00:00:00 +0000 UTC

No running services found.
```

**Comment by dragonchaser** [comment]
I guess this https://github.com/owncloud/ocis/blob/master/ocis-pkg/version/version.go#L22 is the culprit
