### ISSUE TITLE
Refactor api tests code to make it DRY

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6130]
The step definition to change space name, description, and quote is almost the same. The only difference in those steps is  `$bodyData` value 
```
		$bodyData = ["quota" => ["total" => $newQuota]]; // change quote 
                $bodyData = ["description" => $newDescription];  // change description
                 $bodyData = ["Name" => $newName]; // change name 
```
https://github.com/owncloud/ocis/blob/56109f43c820d2fdd8d436185b4d294b2a0bb1f5/tests/acceptance/features/bootstrap/SpacesContext.php#L1276-L1419

I think we can DRY our code 🤔 
cc @saw-jan  @SwikritiT

**Comment by SwikritiT** [comment]
yes, that would be nice. Maybe we have such repeated codes in other places too?

**Comment by PrajwolAmatya** [comment]
- [ ] implement DRY principle https://github.com/owncloud/ocis/pull/6553
