### ISSUE TITLE
WebDAV `MKCOL` returns wrong Status Code `404` if multiple intermediate collections are missing

### ISSUE THREAD

**Issue by kaivol** [owncloud/ocis#6136]
## Describe the bug

When trying to create a collection via WebDAV (`MKCOL`) where _more than one_ intermediate collections are missing, oCIS returns `404 (Not Found)` instead of `409 (Conflict)`. 

According to RFC 4918, Status Code `409 (Conflict)` should be used to indicate that

> A collection cannot be made at the Request-URI until one or more intermediate collections have been created [^1]

[^1]: https://www.rfc-editor.org/rfc/rfc4918#section-9.3.1

## Steps to reproduce

0. _(Precondition)_ No folder `foo` exists in the users personal folder
1. `MKCOL /remote.php/webdav/foo/bar` returns `409 Conflict`
2. `MKCOL /remote.php/webdav/foo/bar/baz` returns `404 Not Found`
3. `MKCOL /remote.php/webdav/foo` returns `201 Created`
4. now `MKCOL /remote.php/webdav/foo/bar/baz` returns `409 Conflict`

## Expected behavior
In step 2, the expected Status Code is `409 Conflict`.

## Actual behavior
The actual Status Code is `404 Not Found`.

## Setup

oCIS Version: 3.0.0-rc.1 in Podman

<details>
<p>

```console
OCIS_CONFIG_DIR=/etc/ocis
OCIS_BASE_DATA_PATH=/data
OCIS_LOG_LEVEL=warn
OCIS_LOG_COLOR=true
OCIS_URL=owncloud.***
PROXY_HTTP_ADDR=0.0.0.0:9200
PROXY_TLS=false
OCIS_INSECURE=false
OCIS_OIDC_ISSUER=auth.***
WEB_OIDC_CLIENT_ID=ocis-web
PROXY_OIDC_REWRITE_WELLKNOWN=true
PROXY_ROLE_ASSIGNMENT_DRIVER=oidc
PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM=ocis_role
PROXY_AUTOPROVISION_ACCOUNTS=true
OCIS_ADMIN_USER_ID=
GRAPH_ASSIGN_DEFAULT_USER_ROLE=false
```

</p>
</details>

Reverse proxy: Caddy

<details>
<p>

```groovy
*.***, *** {
    ..
    @owncloud host owncloud.***
    handle @owncloud {
        reverse_proxy localhost:10020
    }
    ..
}
```

</p>
</details>

**Comment by micbar** [comment]
@kaivol Can you point out which impact that has for you?

**Comment by kaivol** [comment]
I encountered this problem when I tried to migrate old data to oCIS using `rclone`, as described [here](https://owncloud.dev/ocis/guides/migrate-data-rclone/). 
`rclone` fails when it tries to copy files where multiple parent folders would have to be created prior to copying the file.

**Comment by micbar** [comment]
> I encountered this problem when I tried to migrate existing data to oCIS using `rclone`, as described [here](https://owncloud.dev/ocis/guides/migrate-data-rclone/). `rclone` fails when it tries to copy files where multiple parent folders would have to be created prior to copying the file.

Ok. Thanks for that analysis. We should fix that.

**Comment by micbar** [comment]
done. Fixed in rc.2
