### ISSUE TITLE
adoc table generator should separate envvars by semicolon AND comma

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#6142]
**Works**
`OCIS_REVA_GATEWAY;REVA_GATEWAY`
renders as:
![image](https://user-images.githubusercontent.com/3321281/234502579-ec9da56c-3efa-4025-9b7a-2204b323290a.png)

**Needs fix:**
`OCIS_TRANSLATION_PATH,USERLOG_TRANSLATION_PATH`
renders as:
![image](https://user-images.githubusercontent.com/3321281/234502667-f76e1a75-23af-48f8-b841-bfad31019753.png)

@kobergj @dragonchaser

**Comment by mmattel** [comment]
Just for reference (thanks to @dragonchaser), see the [current code](https://github.com/owncloud/ocis/blob/master/docs/helpers/adoc-generator.go.tmpl#L212) which separates by semicolon only.

**Comment by kobergj** [comment]
I think we should stick to one list separator. It looks messy if every envvar uses their own delimiter

**Comment by mmattel** [comment]
keep open

**Comment by mmattel** [comment]
keep open
