### ISSUE TITLE
OIDC: backchannel logout default configuration only accepts a single client id

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#6149]
## Describe the bug

Our code verifying the backchannel logout token, tries to verify the `aud` claim of the token by default. It is possible to configure a single value that is allowed to appear in that claim (defaulting to `web`).
I think we're doing something wrong here. Keycloak for example by default sets the `aud` claim to the value of the `clientid` for which the session was created. So with the current approach only sessions initiated  one specific oidc client can be logged out (`web` by default). For sessions created by any other clients (i.e. the desktop of mobil apps) the validation of the logout token will fail because the `aud` claim does not match the expected value.

As a workaround we can disable the validation of the `aud` claim for now with `PROXY_OIDC_SKIP_CLIENT_ID_CHECK=true`

I am still not sure what the correct validation of the `aud` claim would look like in ocis. We simply don't know all the valid client ids that could appear in logout tokens. (At least when DCR is enabled in the idp).

**Comment by rhafer** [comment]
cc @micbar @wkloucek

**Comment by micbar** [comment]
Thanks. I see the PR was merged. IMO that makes sense for the time being.

**Comment by micbar** [comment]
Fixed.
