### ISSUE TITLE
creating a folder called "New folder" does not work

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#6150]
## Describe the bug

I somehow ended up in a state where I could not create a folder called "New folder". All other folders would work, but I could not upload a folder called "New folder" with the desktop client nor create this folder with the WebUI.
After restarting ocis (with more logs) it showed me that this folder already exists and had some items.

## Steps to reproduce

I cannot reproduce it so-far, but I want to log it, in case it happens again

## Expected behavior
An existing folder should be shown

## Actual behavior
Somehow the folder existed on the system, but was not shown
When trying with the desktop client, I could first create the folder and place a file in there, after a while the file would be deleted locally and then also the folder would be deleted

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_DECOMPOSEDFS_METADATA_BACKEND=messagepack
OCIS_URL=https://192.168.56.1:9200 
./ocis-3.0.0-rc.1-linux-amd64 server
```

</p>
</details>

## Additional context
The only thing I have is the log of the client
[ownCloud.zip](https://github.com/owncloud/ocis/files/11331983/ownCloud.zip)

**Comment by micbar** [comment]
could be related to the caching issue, closing.
