### ISSUE TITLE
Transifex localisation of the IDP service is not existant

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#6163]
* The translation implementation for the `notification` and the `userlog` service is ok and we can see and translate content in Transifex.
* But for the IDP service, this seems to be messed up and nothing is available in TX and the way how it is setup looks hand crafted.

We should harmonize translations in the IDP service in the same way we do for eg notifications.

When running a search in the services folder with: `find . -type f -name *.po*`
we get the following results (beautyfied):

```
./notifications/pkg/email/l10n/locale/de/LC_MESSAGES/notifications.po
./notifications/pkg/email/l10n/locale/es/LC_MESSAGES/notifications.po
./notifications/pkg/email/l10n/locale/de_DE/LC_MESSAGES/notifications.po
./notifications/pkg/email/l10n/locale/ca/LC_MESSAGES/notifications.po
./notifications/pkg/email/l10n/locale/ko/LC_MESSAGES/notifications.po
./notifications/pkg/email/l10n/locale/sq/LC_MESSAGES/notifications.po

./idp/i18n/es.po
./idp/i18n/zh-CN.po
./idp/i18n/it.po
./idp/i18n/translation.pot
./idp/i18n/de.po
./idp/i18n/fr.po
./idp/i18n/nl.po

./userlog/pkg/service/l10n/locale/de/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/pt_BR/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/es/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/es_AR/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/de_DE/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/ru/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/en_GB/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/bg_BG/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/ko/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/tr/LC_MESSAGES/userlog.po
./userlog/pkg/service/l10n/locale/sq/LC_MESSAGES/userlog.po
```

@micbar @2403905 @dragonchaser @kobergj @rhafer

**Comment by kulmann** [comment]
Please don’t. The idp service is mostly vendor code. Translations are provided by the vendor.

**Comment by mmattel** [comment]
Ok
Do we sync the translations?
Is there a code fragment we can reference, I would add some info to the service readme to clarify.

**Comment by kulmann** [comment]
Why would we sync the translations? They are provided by the vendor. And we don't touch the code base except for theming.

**Comment by mmattel** [comment]
It is not that WE change translations but that we get new and updated translations and languages added.

**Comment by mmattel** [comment]
just for the record:

`make stats`
```
es.po: 0 translated messages, 37 untranslated messages.
fr.po: 34 translated messages, 3 untranslated messages.
it.po: 0 translated messages, 37 untranslated messages.
de.po: 37 translated messages.
nl.po: 34 translated messages, 3 untranslated messages.
zh-CN.po: 0 translated messages, 37 untranslated messages.
```
