### ISSUE TITLE
Default value of STORAGE_SYSTEM_OCIS_METADATA_BACKEND

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#6166]
When looking into the default value and description of the envvar:
`STORAGE_SYSTEM_OCIS_METADATA_BACKEND`
we find that the default it is set to `xattrs` and possible values include `ini`, see image below.

I may be wrong but did'nt we switched to messagepack and shouldnt the values be aligned?

![image](https://user-images.githubusercontent.com/3321281/234841262-4263f8f6-acb7-48bb-b913-17f64c86926d.png)

@butonic @micbar @aduffeck

**Comment by micbar** [comment]
The default is currently still `xattr`

The description is wrong, yes.

**Comment by mmattel** [comment]
What is the other value? `mpk` ?
I could file a quick PR if I would know it.

**Comment by aduffeck** [comment]
@mmattel that's `messagepack`. `xattrs` and `messagepack` are the supported backends for both system and user storage.

**Comment by mmattel** [comment]
Closing via #6213 ([docs-only] Set messagepack as default metadata backend)
