### ISSUE TITLE
ocis vs Wopi. Cannot open file in the collabora

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6196]
ocis 3.0.0-rc.1
web 7.0.0-rc.32

ocis against wopi using https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml
or open [ocis.ocis-wopi.released.owncloud.works](https://ocis.ocis-wopi.released.owncloud.works/)

Steps: 
- create `odt` file

Expect: file opens in the new collabora window

Actual: file couldn't open in collabora 

https://user-images.githubusercontent.com/84779829/235528138-da5cde58-4b81-43dd-97f2-3c96dde6cab1.mov

**Comment by micbar** [comment]
Was a deployment problem related to https://github.com/owncloud/ocis/issues/3832

**Comment by micbar** [comment]
Fixed. please re-test.

**Comment by micbar** [comment]
where did you test? The app provider unregistering itself always happens when ocis is restarted.

**Comment by micbar** [comment]
that means locally?

Please do `docker-compose restart ocis-appprovider-collabora` That fixes it.

The underlying issue is the registry (see linked ticket)

**Comment by ScharfViktor** [comment]
ohh, sorry. I couldn't retest it because have another problem in the latest ocis

```
{"level":"error","service":"search","error":"Get \"http://tika:9998/version\": dial tcp 192.168.32.9:9998: connect: connection refused","time":"2023-05-02T13:51:40.67790467Z","line":"github.com/owncloud/ocis/v2/services/search/pkg/server/grpc/server.go:40","message":"Error initializing search service"}

{"level":"info","service":"search","error":"Get \"http://tika:9998/version\": dial tcp 192.168.32.9:9998: connect: connection refused","transport":"grpc","time":"2023-05-02T13:51:40.677947586Z","line":"github.com/owncloud/ocis/v2/services/search/pkg/command/server.go:62","message":"Failed to initialize server"}

{"level":"info","service":"ocis","event":"ocis: Failed service 'command.SutureService{cfg:(*config.Config)(0x40016ab1e0)}' (2.997855 failures of 5.000000), restarting: true, error: Get \"http://tika:9998/version\": dial tcp 192.168.32.9:9998: connect: connection refused","time":"2023-05-02T13:51:40.708733628Z","line":"github.com/owncloud/ocis/v2/ocis/pkg/runtime/service/service.go:184","message":"supervisor: ocis"}
```

**Comment by ScharfViktor** [comment]
> Please do `docker-compose restart ocis-appprovider-collabora` That fixes it.

Thank you. after restarting `ocis_wopi_ocis-appprovider-collabora` file opens in the collabora window
