### ISSUE TITLE
Ocis vs ldap. Cannot share a file that is open in collabora

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6197]
ocis 3.0.0-rc.1
web 7.0.0-rc.32

ocis against wopi using https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml
or open [ocis.ocis-wopi.released.owncloud.works](https://ocis.ocis-wopi.released.owncloud.works/)

Steps:

- share opening  in the onlyOffice file to user

Actual: `996 grpc create share request failed`

https://user-images.githubusercontent.com/84779829/235529268-7d2cf287-5157-4219-a35a-f2c804737d2d.mov

Expected:

**Comment by micbar** [comment]
The file is locked, that is the reason why this doesn't work.

@tbsbdr @kulmann This demands better error handling.

**Comment by tbsbdr** [comment]
assessing as p2 as it can block collaboration with no workaround (example: this bug can stop a teaching lesson for certain pupils)

**Comment by micbar** [comment]
Error handling will not enable sharing a locked resource.

1) We should get a better error message to the user.
2) We cannot share the file until the last person has left the editing session.

**Comment by 2403905** [comment]
> Error handling will not enable sharing a locked resource.
> 
> 1. We should get a better error message to the user.
> 2. We cannot share the file until the last person has left the editing session.

@micbar What error users have to see?

**Comment by 2403905** [comment]
@ScharfViktor Looks like we have multiple bugs.
1. Steps from the video
1.2 The document still opened via only office
2. Goto files/shares/with-others -> the share is already created!
3. log in as Sharee -> goto shares -> files/shares/with-me is empty
3.1 Sharee can see Notifications!

**Comment by 2403905** [comment]
@micbar @tbsbdr How to handle the case below?
Case 2
1. Bob create doc
2 Bob edit and close doc
3 Bob share doc to Oggy
4 Oggy open the doc
5 Bob going to share doc with Jack -> lock ! Oggy left the doc opened  for a long time!

**Comment by micbar** [comment]
> 5 Bob going to share the doc with Jack -> lock ! Oggy left the doc opened for a long time!

Bob should get a message that the document is locked with the call to action to try it later.

IMO that is the best we could do ATM

**Comment by tbsbdr** [comment]
Proposal for error notification:

**Sorry, sharing is not possible**.
The document is being edited and is locked. Please finish editing to enable sharing.

**Comment by ScharfViktor** [comment]
retested v. 3.0.0-rc.4
- [x] share opening in the onlyOffice file to user - fixed. `The file is locked until the file is in use by at least one user`
- [ ] edit share opening in the onlyOffice file to user - `996 error`
- [ ] delete share opening in the onlyOffice file to user - `996 error`
