### ISSUE TITLE
Circuit Breakers

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#621]
Circuit Breakers and High availability

This will require joint efforts of refs/pman and circuit breakers. Currently pman won't keep a process alive. If a process dies, then it's dead and no efforts towards reviving it will take place. Therefore for circuit breakers to work we need to be able to restart services on failures.

Resources
- https://martinfowler.com/bliki/CircuitBreaker.html
- https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn589784(v=pandp.10)?redirectedfrom=MSDN
- https://microservices.io/patterns/reliability/circuit-breaker.html
- https://github.com/sony/gobreaker
- https://github.com/afex/hystrix-go (go project to play with)
- https://github.com/gojek/heimdall (another go project , http client based on hystrix)

Micro take on circuit breakers:

- https://github.com/micro/go-plugins/blob/master/wrapper/breaker/gobreaker/gobreaker.go

How can we, in ownCloud, use the gobreaker wrapper?

Test scenario: accounts -> settings: report settings bundle. This is a good chance to use a gobreaker wrapper and see what happens when the settings service is not started yet.

This exact use case is showcased on the [owncloud/ocis/breaker](https://github.com/owncloud/ocis/tree/breaker) branch. To understand the scenario:

1. The accounts service registers a set of default settings and permissions.
2. There is a precondition: settings service up and running.
3. If the accounts service is launched prior to the settings, requests during the lifecycle of the accounts service will start failing.
3.1 while this is solved with a simple _retry until max retries_ logic, we have no awareness nor monitoring of the situation.
4. Start on isolation ocis accounts
5. See requests failing
6. Checkout [owncloud/ocis/breaker](https://github.com/owncloud/ocis/tree/breaker)
7. Start accounts on isolation

After that, you should see something similar to:

![image](https://user-images.githubusercontent.com/6905948/94421033-42ec6980-0185-11eb-885e-940ee988d02d.png)

Where one can clearly see 2 circuit breakers, both tripped and they both have different thresholds, one trips after 2 consecutive failures and the other trips after a single failure.

**Comment by refs** [comment]
After a few experiments `TwoStepsCircuitBreaker` is not needed since micro/micro prevents consumers from providing a slice of callbacks. It instead returns a go-micro error with the detail explaining the circuit tripping.

**Comment by IljaN** [comment]
Should we also take in to account that in k8s or similar environments the orchestrator will restart the service based on liveliness checks?

**Comment by refs** [comment]
should we? That's on an entirely different layer, circuit breakers are done in the clients.

**Comment by IljaN** [comment]
:+1: Okay miss-understanding on my side.

**Comment by refs** [comment]
Needs a broader audience. Closing and reopening a better described issue.
