### ISSUE TITLE
new api test with different env configuration

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6231]
after finishing https://github.com/owncloud/ocis/pull/6062 we can start implement api test using different env ocis configuration

list of env @micbar @individual-it please add

Doc: https://owncloud.dev/ocis/development/testing/#running-env-config-tests-env-config

### Prio1: 
- [x] `OCIS_DECOMPOSEDFS_METADATA_BACKEND STORAGE_SYSTEM_OCIS_METADATA_BACKEND`  already done

### Prio2:
- [x] `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD` (SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD) https://github.com/owncloud/ocis/pull/6409 https://github.com/owncloud/ocis/pull/6465
- [x] `OCIS_SPACES_MAX_QUOTA` @SagarGi https://github.com/owncloud/ocis/pull/6402

### Prio3:  
- [x] `OCIS_ASYNC_UPLOADS` already implemented
- [x] `STORAGE_USERS_OCIS_ASYNC_UPLOADS` already implemented

**Comment by grgprarup** [comment]
All the tests have been added. So closing this issue.
