### ISSUE TITLE
Able to share a personal space / Access personal space of other user

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ocis#6238]
## Describe the bug

Happened with an outdated iOS sharing dialog. But nevertheless, shouldn't be possible in backend.

## Steps to reproduce

1. Alice wants to share space "Space A" with einstein. Sharing dialogue looks:
![IMG_8225](https://user-images.githubusercontent.com/16665512/236420496-b3e88beb-8967-4a59-b591-bd25f61f812e.PNG)

3. Einstein receives this notification
![grafik](https://user-images.githubusercontent.com/16665512/236419752-3f66e8ad-2f57-4bb9-aa8d-bb221d6d4edd.png)

4. Clicking on it, einstein has access to the personal space of alice:
![grafik](https://user-images.githubusercontent.com/16665512/236420062-cd70f3ae-b774-4270-9477-5509f2b080b3.png)

@micbar , as discussed

**Comment by felix-schwarz** [comment]
Fixed iOS-side via new sharing UI (latest in https://github.com/owncloud/ios-app/pull/1207).

**Comment by micbar** [comment]
Backend fix in https://github.com/cs3org/reva/pull/3849

**Comment by micbar** [comment]
Fixed by #6340
