### ISSUE TITLE
Add territories to Web UI languages

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#6240]
Based on a discussion with @kulmann and @dragonchaser, documenting the outcome.

We need a way to represent different territory settings per country or language, eg:

* Swiss (special case, three major languages): de_ch, it_ch, fr_ch
* German speaking: de_de, de_at
(probability of governmental regulations regarding language gendering )
* Spanish speaking countries like: es_cl, es_co, es_ar, es_mx,... (south america)
* Portugese speaking countries like: pt_br
* ...

Solution:
* Add white-listing for language files being distributed to `make generate` to the web service
* Add territory codes to the request made by the webui

This is not the request to actually support each of those special constellations, but to implement the technical ability to do so (white-listing solution). Translations from Transifex can be white-listed as needed and as they mature (company internal or via community).

**Comment by tbsbdr** [comment]
product decision was not have territories, thus I don't see the need to prepare it technically. we have enough work maintaining good translations for en and de;
