### ISSUE TITLE
Userlog service not updating redis key if it doesn't exist

### ISSUE THREAD

**Issue by Excds** [owncloud/ocis#6251]
In the userlog service redis keys will not be updated if they do not exist. The problem is with catching an exception from the redis store at line: https://github.com/owncloud/ocis/blob/4354f5a84bff5f7196869946d9fca2d7e691b102/services/userlog/pkg/service/service.go#L249

The PR https://github.com/go-micro/plugins/pull/97 introduced the problem because the store.ErrNotFound was replaced with the redis error.

**Comment by micbar** [comment]
what is the user impact?

**Comment by micbar** [comment]
should be fixed in rc.3
