### ISSUE TITLE
Sharing of project space root via public link does no longer work.

### ISSUE THREAD

**Issue by aduffeck** [owncloud/ocis#6278]
To be discussed.

**Comment by ScharfViktor** [comment]
after merging https://github.com/owncloud/ocis/pull/6271 we haven't ability to create public link for project space

<img width="1328" alt="Screenshot 2023-05-11 at 11 25 20" src="https://github.com/owncloud/ocis/assets/84779829/1c1b0961-c25f-4359-acfc-04a7246596e5">

before I change e2e tests for that we need disable `add link` button on the web. @tbsbdr @micbar

**Comment by ScharfViktor** [comment]
not relevant. works fine
