### ISSUE TITLE
WASM Build of all backend services

### ISSUE THREAD

**Issue by lemanschik** [owncloud/ocis#6285]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Go is the problem inherent in it self do not take me by word do your research.

## Describe the solution you'd like
A clear and concise description of what you want to happen. We need to use the new WebAssembly for Memory Managed languages to get a c++ copy of the source GO=>WASM=>C++=>JS 

## Describe alternatives you've considered
A clear and concise description of any alternative solutions would be to write a parser to extract the API in a serialize able generativ way and call it a day.

## Additional context
Ufff transporting over 30 years of Language Implementation knowledge in a single issue is to much.
But even being able to run the code on eg: docker with docker wasm would be beneficial even for none Tech users. 

## Process
will start with the frontend as that is the meaningfull part that contains maybe max 1300 sloc useful code without css and assets.

- [ ] https://github.com/lemanschik/owncloud-web/issues/1

most usefull as described in this issue is the general api spec so what input produces what output and is it Idempotent or not 

there exist only this 2 classes of interactions Idempotent and not Idempotent. 

## Extending knowledge transfer
Idempotent and not Idempotent tells us what is static and so cache able and store able and 
what is temp and not cache store able everything that is not store able cache able is by design generativ so that is the real code that is not design dependent.

**Comment by butonic** [comment]
> Go is the problem inherent in it self do not take me by word do your research.

Thats ... you know ...  just your opinion. 

> We need to use the new WebAssembly for Memory Managed languages to get a c++ copy of the source GO=>WASM=>C++=>JS

Um, no we don't.

@frank-dspeed @lemanschik Happy to discuss WASM for service workes or anything ocis related in person. Maybe at a conference in Hamburg, Berlin, Hannover or Nürnberg ... but not in our issue tracker.
