### ISSUE TITLE
[Notifications] notification message should be more specific

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6286]
### Steps to reproduce
1. `Admin` creates space `hello` 
2. `Admin` add user `Roy` to space `hello` with  space-role `manager`
3. notification contains message `Admin added you to Space hello`
4. `Admin` changed `Roy` space-role to 'editor'
5. new notification pop-up with the message `Admin added you to Space hello`
![Screenshot from 2023-05-08 11-10-38](https://user-images.githubusercontent.com/54478846/236741040-61cba585-abcc-452c-ac58-df9e9aed6024.png)

### Expected behaviour
While role changed notification message should be something like this `Admin changed your role to the editor in Space hello``

### Actual behaviour
`Admin added you to Space hello`

### Environment general
**Operating system**: ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** latest

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

**Comment by ScharfViktor** [comment]
The user does not receive notification of a space role change anymore 
https://github.com/owncloud/ocis/issues/6649#issuecomment-1707919956
