### ISSUE TITLE
[CI] Randomly failing tests

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#629]
https://drone.owncloud.com/owncloud/ocis/129
https://drone.owncloud.com/owncloud/ocis/134
*Rebase with master*
https://drone.owncloud.com/owncloud/ocis/143
https://drone.owncloud.com/owncloud/ocis/147

Passing: https://drone.owncloud.com/owncloud/ocis/146

**Comment by individual-it** [comment]
the UI test issues seem also to happen in the phoenix repo https://drone.owncloud.com/owncloud/phoenix/11216/42/12
