### ISSUE TITLE
Bug: Web Interface Downloading Fails for Multiple Files Totaling Over 1GB

### ISSUE THREAD

**Issue by isasmendiagus** [owncloud/ocis#6301]
## Describe the bug

Downloading multiple files of more than 1GB from the web interface generates an incomplete .tar file of 980MB. The following error is logged: {"level":"error","service":"frontend","pkg":"rhttp","time":"2023-05-13T12:44:22.339036398Z","message":"reached max total files size"}.

## Steps to reproduce

1. Go to the web interface.
2. Select multiple files that together exceed 1GB.
3. Download the selected files.

## Expected behavior
The expected behavior is to download all the selected files, regardless of their total size.

## Actual behavior
A .tar file of 980MB is generated, which is incomplete because the total size of the selected files exceeds this amount.

## Setup

The infrastructure I'm using is an LXC container with Debian, running OCIS with docker compose. The template being used is: https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_wopi

**Comment by micbar** [comment]
@isasmendiagus This is not a bug. This value is configurable.

`FRONTEND_ARCHIVER_MAX_SIZE` is your friend. It is an `int64` type and the default is `1073741824`.

You can find that in the ocis documentation https://doc.owncloud.com/ocis/next/deployment/services/s-list/frontend.html

**Comment by isasmendiagus** [comment]
@micbar Thanks!
