### ISSUE TITLE
Search: combine tags with an additional query

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#6305]
## Describe the bug

I want to be able to combine multiple search features (Tags and file name or full text search) in an `AND` way. Currently they seem to be combined with an `OR`.

## Steps to reproduce

1. Create file context as follows:
  - create a folder "asdf" and assign tag "asdf"
  - create a file "test.txt" with content "asdf test" and assign tag "asdf" 
2. Enter search term `Tags:"asdf" Content:"test"` (with fulltext search) or `Tags:"asdf" test` (search by file name)

## Expected behavior
Search features are combined and as a result only the file `test.txt` is found.

## Actual behavior
Search result shows both the folder and the file.

**Comment by kulmann** [comment]
Could you shed some light on this @aduffeck ? :-)

**Comment by aduffeck** [comment]
Please see https://github.com/owncloud/ocis/issues/6343#issuecomment-1554743702 for some details on the query syntax.

**Comment by aduffeck** [comment]
@kulmann Can this be closed?

**Comment by kulmann** [comment]
Yes, thank you for the extensive documentation!
