### ISSUE TITLE
Provider is nil if oidc unresolvable

### ISSUE THREAD

**Issue by jamu85** [owncloud/ocis#631]
https://github.com/owncloud/ocis/blob/e0c94f6c21d9dee340d5eff3ee3d95c0229c72d0/ocis-pkg/middleware/openidconnect.go#L76

needs graceful exit if provider still nil.

Reproducible by using docker and ufw firewall. Reasons not exactly clear.
Docker container is not able to resolve own domain due to firewall mess-up.

**Comment by rhafer** [comment]
This has been fixed a while ago (part of #877) in the proxy middleware. The oidc middleware in ocis-pkg does not exist anymore.
