### ISSUE TITLE
After deleting a user who was the sole manager of a space or was one of multiple managers of a space, he is still shown by name as a manager in Admin Settings>Spaces

### ISSUE THREAD

**Issue by tschiebel** [owncloud/ocis#6320]
## Error description
After deleting a user who was the sole manager of a space or was one of multiple managers of a space, he is still shown by name as a manager in Admin Settings>Spaces.

## Steps to reproduce
* User has created two Spaces. In one he is manager alone, for the second Space he sets a second manager.
* User is deleted in cloud-IDM and shortly after he also disappears from the user list in Admin Settings>People.
* In Admin Settings>Spaces the name still appears.
*

## Expected behavior
All user data must be deleted.

## Actual behavior
In Admin Settings>Spaces the name still appears.

## Additional context
Context to understand the problem

![image](https://github.com/owncloud/ocis/assets/132444655/2dbe7ed1-f012-4618-a55c-3c074a146cce)
![image](https://github.com/owncloud/ocis/assets/132444655/5af25c52-600e-4570-8167-268cf9efca8a)
![image](https://github.com/owncloud/ocis/assets/132444655/5d5a3377-35d6-4253-ba49-76176070cd59)

## comment
Addendum to the screenshot from 09.05.2023: The user is no longer displayed, but there is still a comma (see screenshot from 11.05.2023, 12.36 o'clock).

The test case was repeated on 05/11/2023, 12:36 PM. Same result: account Gesine Kaya has been deleted, no longer appears under persons or groups, registration is also no longer possible. However, her name still appears in the list of space admins of the affected space.

She is also listed in the display of Space members. The red circle (screenshot 11.05.2023, 12.42 p.m.) also indicates that the old Space Manager has not yet been completely removed.

**Comment by rhafer** [comment]
@micbar The graph service has a couple of caches with a default TTL of 30min (which IMO is way too long).  https://github.com/owncloud/ocis/blob/master/services/graph/pkg/config/defaults/defaultconfig.go#L61

We could reconfigure the setup to use a shorter ttl. But I would also recommend the default to something lower (somewhere in the range from 30s to 5min).

**Comment by rhafer** [comment]
We still have a couple of places where `ttlcache` is used in reva. Need to check the default settings there as well...
