### ISSUE TITLE
Refactor share api tests

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6325]
# Description
Currently, we don't have an API step  where sharer removes sharee 
The previous steps are
```
 * @When /^user "([^"]*)" (?:deletes|unshares) (?:file|folder) "([^"]*)" using the WebDAV API$
 * @Given /^user "([^"]*)" has (deleted|unshared) (file|folder) "([^"]*)"$/
 * @Given /^user "([^"]*)" has (deleted|unshared) the following (files|folders|resources)$/
```

Look over the whole share-related tests-suite and find out the scenario where we delete shared resources in place of unshare resources. Refactor those scenarios. 

# Done
-  step, where sharer removes sharee, has been added in this PR https://github.com/owncloud/ocis/pull/6324

**Comment by SwikritiT** [comment]
@S-Panta will be working on this

**Comment by saw-jan** [comment]
Done in https://github.com/owncloud/ocis/pull/6608
