### ISSUE TITLE
creating a file 2 times yields different result when renaming the first one

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6335]
## Describe the bug

Inconsequent behaviour when uploading a file, renaming it and then uploading it again.

## Steps to reproduce

1. Log into https://ocis.ocis-s3.latest.owncloud.works/
2. Upload a file
3. Rename the uploaded file on the server
4. upload the file again

## Expected behavior
Have two files:
- one with the renamed name
- on with the original name

## Actual behavior
We have two files:
- two with the same name

If it's an image, one shows a thumbnail, the other doesn't. Both can be opened.

![image](https://github.com/owncloud/ocis/assets/34452982/c0161894-e1b2-4840-b8da-35175fedb54c)

## Context

Infinite Scale 3.0.0-rc.3+4aad1db78 Community

**Comment by ScharfViktor** [comment]
that is bad. We haven't test for that. CC @individual-it

**Comment by phil-davis** [comment]
Can we clarify step 3 "Rename it"
Rename the file on the server that was just uploaded, or
Rename the local file, and upload the local file again (which now has a different local name)

**Comment by ScharfViktor** [comment]
same with creating file


https://github.com/owncloud/ocis/assets/84779829/ef7d3e27-31f2-4e7e-a8c8-ba96ee1f3a5b
