### ISSUE TITLE
Invalid `Access-Control-Allow-Origin` header for the /data route

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6345]
## Describe the bug

After mitigating https://github.com/owncloud/ocis/issues/5108, I was able to initialize an upload that fails with CORS issues due to a invalid [`Access-Control-Allow-Origin` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) for the /data route

## Steps to reproduce

1. configure `OCIS_CORS_ALLOW_ORIGINS` so that uploads from the oC filepicker domain
2. upload a file with the filepicker

## Expected behavior
Upload works

## Actual behavior
Upload is blocked because of CORS error:

```
Access to XMLHttpRequest at 'https://yyyy/data/ey...' from origin 'https://xxxxx' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, https://xxxxx', but only one is allowed.
```

## Additional context
https://github.com/cs3org/reva/blob/98d8707dea33f8120f6499d0dbfdf71a9c3a9317/internal/http/services/datagateway/datagateway.go#L142 looks fishy

**Comment by micbar** [comment]
Fixed by https://github.com/owncloud/ocis/pull/6355
