### ISSUE TITLE
Search: Confusing behaviors

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ocis#6366]
While playing around with the search (based on https://github.com/owncloud/ocis/issues/6343), we came across some difficulties. Maybe it's not all bugs, but it seems confusing at some points.

## Difference between *test* and *Name:test*
As far as I understood, no prefix will search for file and folder names.
Prefixing *Name:* will also do a search for file and folder names.
Where is the difference for the user?

## Compare searching for *test* and *Name:test*
*test* finds “test.txt”, “test123.pdf and folder “test”
*Name:test* finds only folder “test”

While this is surely technically correct, it is rather confusing, why one appends an asterisk per default and the other one does an exact match. 
I was expecting *Name:test* would show also “test.txt”, “test123.pdf” and folder “test”

## Placeholders
*Name:Deutsch* finds folder “Deutsch”
<img width="478" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/47b4e71a-ffae-4609-a2f0-39a2ac79971e">

*Name:Deutsch\** finds nothing
<img width="473" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/725147fb-f5a9-43df-8c99-9d1bf5e754c1">

Might correspond to the upper/lowercase scenario below. Changing the search term to lowercase *Name:deutsch* shows correct results. Still confused about two different outcomes.

## Upper-/Lowercase
Lowercase shows case-insensitive results. Works as expected:
<img width="470" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/7b20fc49-8f34-4f64-a610-a80fe3327194">

VS. Uppercase - shows nothing?!
<img width="477" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/0e656968-2210-48a6-a8a2-c02ae7d2cfc8">

## Highlighting of results
Search results are not always highlighted. 
Highlighted:
<img width="475" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/2065c6b2-cf97-4ea3-917d-1a7f7e8b51db">

not highlighted:
<img width="475" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/bba3b3f5-e6ae-48ea-9e01-5b117b682bed">

<img width="470" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/7c5c0d45-c3af-42c3-a2d5-7bd2f130a716">

<img width="470" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/35aef161-8268-4052-85e0-1036f7620bd2">

## Inconsistent usage of upper/lowercase in combination with placeholder

Imagine an existing tag “intern”, at least on file, is marked with that tag.

*Tags:intern* works
*Tags:inter\** works -> cool, I can use placeholders within tags
*Tags:InTeRn* works --> cool, search is case-insensitive
*Tags:InTe\** does not work - ?!
<img width="476" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/d60769c4-4878-478a-9cfc-986cfb0fa607">

! simple mode search works as expected and does not make a difference between *test\** and *TEst\**

## Unknown files appear
Note: Logged in as Alice

#6343 tells me:
```
Complex search: 'Tags:bar file' (all tagged bar OR that match 'file')
Result bar.txt
```

Result:
<img width="474" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/90bc3675-82ad-4569-969c-01c4484aa85d">

- I have no json files and no files called somewhat `export` in my personal space.
- Clicking on the search results filename downloads the file (path: `./export.json`) Clicking on the folder name (`Personal`) below leads me to a broken "Shared with me" page:
<img width="835" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/d6b92bc6-a295-49ea-ab3c-ce917ed8c67a">

- They are surely not taged with tag "internal", compare searching for this tag:
<img width="472" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/37b77231-2246-4369-a207-382faa1ecdf9">

- Searching for *deutsch* also does not show them: 
<img width="475" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/9b455f75-de20-43dc-9d60-70f76a6c40b9">

- Changing the search term to capitalized *Tags:intern Deutsch* removes the json files but also loses correct folders in a space (Folder "Deutsch" in Space "Sommerfest 2024" is missing):
<img width="466" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/50b116e6-9903-4452-b5ae-6fe80ec517bc">

- Logging in with another user (Bob) makes the confusion perfect. Doing the same search results in same results:
<img width="470" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/6f2d4d05-e9c1-4995-ad63-a0c155a9ce44">

**EXCEPT** the json files are not located in `personal` anymore, but in a space called `Sommerfest 2024`. And there they really are:
<img width="593" alt="grafik" src="https://github.com/owncloud/ocis/assets/16665512/5dec2685-58f0-4310-81f3-b6944635695d">

Logging in back with Alice, the space does not appear in her space overview. Therefore she shouldn't have access to those files.
Logging back in with Bob. Go to the space and check members. I can see that Alice is member of this space via a group.

Summary:
- Alice is member of group "Staff"
- Group "Staff" is member of space "Sommerfest 2024", permission `editor`
- ❗  Alice does not see space "Sommerfest 2024"
- Space "Sommerfest 2024" contains some json files called "export", "realm-export", etc.
- Files are not tagged with any tag
- ❗ Alice can see files of this space when typing "Tags:internal deutsch" in the search bar

**Comment by fschade** [comment]
> ## Compare searching for _test_ and _Name:test_
> _test_ finds “test.txt”, “test123.pdf and folder “test” _Name:test_ finds only folder “test”
> 
> While this is surely technically correct, it is rather confusing, why one appends an asterisk per default and the other one does an exact match. I was expecting _Name:test_ would show also “test.txt”, “test123.pdf” and folder “test”

i agree, it is (or could be) confusing, but as explained above, 99% of all users will only use the search as they do in google, type and expect the result.

same for the google engine (even if it is slightly more powerful ;) ), they have the default search but you're able to search for dedicated fields (advanced search): `related:XY`, `inurl:XY`, ...

this is why we've decided to use a wildcard (prefix, suffix) search here. The downside is that those wildcard searches cost more time then a explicit search. long term i hope we adopt the ios query syntax: https://github.com/owncloud/ios-app/pull/933

**Comment by aduffeck** [comment]
With https://github.com/owncloud/ocis/pull/6371 we are changing the field queries in complex searches to also be case insensitive like simple searches, fixing much of the confusing behavior you saw:

## Placeholders

`Name:Deutsch` and `Name:Deutsch*` both find the folder.

## Upper-/Lowercase

Both `Name:*deutsch*` and `Name:*Deutsch*` show the results.

## Inconsistent usage of upper/lowercase in combination with placeholder

`Tags:InTe*` works as well.

<hr>
 
The issues that are still left are

## Highlighting of results

I *think* we're currently not using the search engine's highlight capabilities but web does the highlighting. So this would either need to be fixed by web or we'd have to switch over to rely on the search engine to mark the highlighted parts in the returned results.

## Unknown files appear

That one's not quite clear yet. I think it might actually be two problems:

The reason that Alice gets those json files (which are GDPR reports) as results for the `Tags:intern deutsch` query likely is that the full-text index was also added to the composite field which is being used for simple terms in complex queries (i.e. `deutsch` in this case). This has been changed with https://github.com/owncloud/ocis/pull/6356 so those files shouldn't show up with new indexes anymore.

That also explains why you don't see those export files with neither the `Tags:intern` nor the `Deutsch` query.

The export files Bob sees are likely (hopefully!) different files. Maybe you could verify that by downloading and comparing the content of the files.

What's not clear to me is why Alice's export results take her to the `Shared with me` page. That doesn't really make sense to, could you maybe paste the result of the according `REPORT` call? It might also be a little bug in web.

**Comment by hurradieweltgehtunter** [comment]
Topic "Unkown files appear" seems to be partly resolved. The space, which did not appear, was required to renew the shares because of a reverse index problem on rc2/3.
What can't be explained by this is, why the files appeared as search results at all, since the file names nor tags did not correspond to the search term.

**Comment by aduffeck** [comment]
I think that one makes sense to me. Your search term `Tags:intern deutsch` forced the search into complex mode and as a result the `deutsch` term was applied to the composite field in the index. That field also contained the full-text index until https://github.com/owncloud/ocis/pull/6356, so - assuming the export files contain the word `deutsch` (or a variant the stemmer reduces to `deutsch`) - it makes sense that they showed up in the result list.

**Comment by micbar** [comment]
Ok. We consider it as fixed.
