### ISSUE TITLE
Add capability for full-text search

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#6367]
Web will have a UI for en- or disabling full-text search on the search result page in the future. We need a capability for this so the filter is not showing if the server does not support full-text search.

Maybe it makes sense to couple this with the `SEARCH_EXTRACTOR_TYPE` setting? Meaning if the value of this setting is set to `tika`, the capability will return `true`. Just an idea though.

**Comment by JammingBen** [comment]
> I'd suggest to put the capability in `"files.fullTextSearch"`. Please let me know if you have a better idea...

Fine for me, although the capabilities in `files` seem to use snake_case. So `"files.full_text_search"` would be nice.

**Comment by kobergj** [comment]
files capabilities also use camelCase for example: `privateLinks` and it uses all lower, for example: `bigfilechunking`

I'll stick to snake_case anyways. Just wanted to let you know how great our capabilities are...

**Comment by kulmann** [comment]
> files capabilities also use camelCase for example: `privateLinks` and it uses all lower, for example: `bigfilechunking`
> 
> I'll stick to snake_case anyways. Just wanted to let you know how great our capabilities are...

yep, `it's complicated`. 😆 the majority of capabilities seem to be snake_case though 😁
