### ISSUE TITLE
Search: Add capability for search engine

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#6378]
In addition to https://github.com/owncloud/ocis/issues/6367, Web also needs a capability for the supported search engine because the new filter UI utilizes the engine's search syntax (currently `bleve`).

Suggestion: `files.search_engine` (= `bleve` currently).

**Comment by kobergj** [comment]
Imho web should not know about the underlying search engine. This a backend dependency and should not bother clients. 

A better approach would be to have a stable search syntax that the server will translate into whatever searchengine might be used. We could use bleve syntax for this. 

Is there a point I am missing why this is needed?

cc @kulmann @fschade @micbar

**Comment by kulmann** [comment]
> Is there a point I am missing why this is needed?

oc10 doesn't understand the bleve syntax, but web still kind of supports oc10.

**Comment by kobergj** [comment]
How does using (configurable) bleve syntax fix that issue?

Shouldn't we convert `oc10` to `bleve` on server side?

**Comment by JammingBen** [comment]
We can decide on a stable syntax that never changes (as you mentioned), but that still needs to be announced via a capability. So the capability would then be... `files.search_syntax_support`? Something like that? It's simply for Web to differentiate between oCIS and oC10.

**Comment by kulmann** [comment]
... and since we need that capability anyway we can just allow the `bleve` query syntax in the web ui now and if we ever come up with a stable ownlcoud search query language we can announce it in the capability and discontinue the support for the `bleve` syntax with proper deprecation.

**Comment by kobergj** [comment]
My problem is just that if  I announce `bleve` as search syntax, I can never change the underlying search engine without all clients supporting it. 

Just yesterday we talked about removing bleve for another solution. If clients are assuming "bleve" syntax we cannot do that any more. 

Anyways I would strongly encourage you to forget that server is using bleve search engine. If it is just about differentiating oc10 and ocis, I would use a field like `files.ocis_search_syntax` (bool). This would be false on oc10 automatically.

I really feel like we shoot ourselves by binding the webclient to `bleve`. However if I am the only one who thinks so I'm fine with getting overruled by the teams decision.

**Comment by JammingBen** [comment]
`files.ocis_search_syntax` would be fine for me as well. Web would still use the bleve syntax, so if oCIS changes the search engine some time, it would either need to translate that to the new syntax, or we introduce our own syntax then.

**Comment by kulmann** [comment]
discussed with @micbar and @kobergj in a zoom chat: we will not add a new capability for this. We will accept the broken oc10 search in web master for the moment - this will only become relevant when we target a new final web release from the master, that will take a couple of weeks or even months. ocis will come up with a query language that will be mapped to bleve in the backend internally. discussions will come up in the next days.

**Comment by ScharfViktor** [comment]
I guess we can already close issue. If not reopen please
