### ISSUE TITLE
 `ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE` error in CI

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6384]
# Describe
https://drone.owncloud.com/owncloud/ocis/22684/6/2
CI broken down with error 
`pnpm install
 ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the version of the lockfile is incompatible with this version of pnpm`

pnpm issue - https://github.com/pnpm/pnpm/issues/6307
need to upgrade pnpm version

**Comment by saw-jan** [comment]
Need to update the pnpm-lock file using `pnpm 8`
