### ISSUE TITLE
Branding of OnlyOffice does not work in the current version.

### ISSUE THREAD

**Issue by tschiebel** [owncloud/ocis#6413]
## Error description
Unfortunately, the branding of OnlyOffice does not work in the current version.

## Steps for reproduction
The onlyoffice logo is in the upper left corner

## Expected behavior
The customer Office logo appears on the top left

## Additional context
The branding must also be available via WOPI, but currently it is not.

**Comment by micbar** [comment]
onlyoffice issue, closing here.
