### ISSUE TITLE
Exceeding quota after `ocis_max_size_quota` set gives 500 status code

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#6414]
### Description
Configuring and running ocis with env `OCIS_SPACES_MAX_QUOTA`, when a space is created exceeding the quota. The status code is `500`.

Steps to reproduce:
1. Run ocis with env `OCIS_SPACES_MAX_QUOTA=50`
2. And try to create a space project with quota size `51`.

### curl command to create space with quota with `admin` user:
```bash
curl -XPOST -k -uadmin:admin https://localhost:9200/graph/v1.0/drives -H 'Content-Type: application/json' --data-raw '{"Name": "testQuota", "description": "This is a test quota", "quota": {"total": 51}}' -v
```

### Expected Behaviour:
The status code should be `507` insufficient storage.

### Actual Behaviour
```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 157
< Content-Security-Policy: frame-ancestors 'none'
< Content-Type: application/json; charset=utf-8
< Date: Wed, 31 May 2023 08:42:19 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Graph-Version: 3.0.0-rc.4+3bbed2fc7
< 
{"error":{"code":"generalException","innererror":{"date":"2023-05-31T08:42:19Z","request-id":"desktop/gWCjfgA4bL-000516"},"message":"error creating space"}}
```

**Comment by saw-jan** [comment]
CC @micbar @ScharfViktor

**Comment by ScharfViktor** [comment]
You cannot create space with certain quota in the real life (first we create space with default quota)
and if you have correct configuration `GRAPH_SPACES_DEFAULT_QUOTA < OCIS_SPACES_MAX_QUOTA` You will never have this problem.

my settings: `OCIS_SPACES_MAX_QUOTA=2000000000 GRAPH_SPACES_DEFAULT_QUOTA=1000000000`

you cannot change quota more than `MAX_QUOTA` via web
<img width="437" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/ac13b146-4944-49ab-8fff-d430dc9e5345">

**Comment by SagarGi** [comment]
> You cannot create space with certain quota in the real life (first we create space with default quota) and if you have correct configuration `GRAPH_SPACES_DEFAULT_QUOTA < OCIS_SPACES_MAX_QUOTA` You will never have this problem.
> 
> my settings: `OCIS_SPACES_MAX_QUOTA=2000000000 GRAPH_SPACES_DEFAULT_QUOTA=1000000000`
> 
> you cannot change quota more than `MAX_QUOTA` via web <img alt="image" width="437" src="https://user-images.githubusercontent.com/84779829/243299801-ac13b146-4944-49ab-8fff-d430dc9e5345.png">

From UI it might not be possible but giving `500` status code with API seems not be feasible IMO.

**Comment by phil-davis** [comment]
> From UI it might not be possible but giving 500 status code with API seems not be feasible IMO.

I don't understand the sentence.

IMO it is possible to send an API request to create a space, specifying a quota that is too large, and a `500` status is returned.

Even if the web UI does not make a request like that, some other client might one day. Any API request that can result in a `500` response is a bug, by definition, and should be fixed.

**Comment by ScharfViktor** [comment]
I would suggest another expected result, like when we set a quota higher than the max quota

`400` 
```
{
    "error": {
        "code": "notAllowed",
        "innererror": {
            "date": "2023-06-06T07:51:08Z",
            "request-id": "Viktors-Air.local/S5s3y8xnwl-015573"
        },
        "message": "decompsedFS: requested quota is higher than allowed"
    }
}
```
