### ISSUE TITLE
[OCIS-Storage] are not updated for share receiver

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#642]
when receiving a share it seems not to matter what happens to the content of the share, for the receiver the etags always stay the same

**Comment by refs** [comment]
@individual-it if still relevant, care to add more context or steps to reproduce?

**Comment by phil-davis** [comment]
Another etag-propagation issue https://github.com/owncloud/product/issues/279

**Comment by individual-it** [comment]
I've just tried with upload and cannot reproduce it anymore with OCIS storage, etags seem to be updated also no tests are tagged with #642 in the expected to fail list, so closing this for now
