### ISSUE TITLE
CI fail intermittently on `docs` pipeline 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6432]
## Describe intermittently
Sometimes CI builds fail on the `docs` pipeline with an error. 
```
/go/pkg/mod/google.golang.org/grpc@v1.43.0/status/status.go:35:2: google.golang.org/genproto@v0.0.0-20220112215332-a9c7c0acf9f2: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20220112215332-a9c7c0acf9f2.zip: 403 Forbidden
```
Failed builds:
- https://drone.owncloud.com/owncloud/ocis/22861/96/3
- https://drone.owncloud.com/owncloud/ocis/22815/78/3

@micbar @kulmann

**Comment by SwikritiT** [comment]
failing here too : https://drone.owncloud.com/owncloud/ocis/22894/78/3

**Comment by micbar** [comment]
This is happening on almost every run now. We need to find the root cause.

How much time do we have between the assignment of the "Admin" role and the space creation?

**Comment by SwikritiT** [comment]
@micbar maybe you're talking about this issue https://github.com/owncloud/ocis/issues/6431 ? This one's related to `docs` pipeline

**Comment by SwikritiT** [comment]
@grgprarup is working on the e2e intermittent failure
