### ISSUE TITLE
Updating public share without password when enforce-password is enabled returns 996 ocs code

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#6476]
## Describe the bug

While updating the public link from `read` permission to `edit` permission without a password when `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD` is set to `true`, the OCS message is as expected `Error sending update request to public link provider: the public share needs to have a password` but the OCS status code is `996`.

## Steps to reproduce

1. Set `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD` to `true`
2. upload a file `testfile.txt`
3. create a public link with `read` permission using `curl -k -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d 'shareType=3&path=/testfile.txt&permissions=1' -u <username>:<password> -v`
4. Try to update the public link to `edit` permission without a password `curl -k -X PUT https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/<share-id> -d 'permissions=3' -u <username>:<password> -v`

## Expected behavior
The status code should be relevant to the error message

## Actual behavior
The OCS message is as expected but the status code is `996` for both OCS API versions.

Actual Response:
```
> PUT /ocs/v1.php/apps/files_sharing/api/v1/shares/GVZMxWJjuvkMSfN HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 227
< Content-Type: text/xml; charset=utf-8
< Date: Thu, 08 Jun 2023 04:27:34 GMT
< Ocs-Api-Version: 1
< Vary: Origin
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<ocs><meta><status>error</status><statuscode>996</statuscode><message>Error sending update request to public link provider: the public share needs to have a password</message></meta></ocs>
```

**Comment by ScharfViktor** [comment]
`OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD=true` only affects the web, but through the api we can still create a link(more than read permission) without a password. Updating give us `996`

to write test correct we need to know: 
- should we be able to create link via api
- should we be able to update link via api
@micbar

**Comment by PrajwolAmatya** [comment]
> @micbar @kobergj I added the enforce password configuration to the reva for the update method. Also, we have to fix the create method because the user is able to make the public link for edit via API. Should it be in a same PR?

I have a separate PR on creating the public link with enforce password enabled. There's a issue related to it. https://github.com/owncloud/ocis/issues/6401

**Comment by 2403905** [comment]
> 

Added the enforce password in a reva backend for the create /update actions. @ScharfViktor or @PrajwolAmatya Please validate manually.
@ScharfViktor Also the test cases that covers OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD=true / false have to be added to the ocis.

**Comment by 2403905** [comment]
Related ticket [#6409](https://github.com/owncloud/ocis/pull/6409)

**Comment by 2403905** [comment]
@PrajwolAmatya Please validate this case and https://github.com/owncloud/ocis/issues/6401

**Comment by PrajwolAmatya** [comment]
> @PrajwolAmatya Please validate this case and #6401

Now, creating and trying to updating a public link  without password is returning OCS code `400`. 
But in case of removing the password the returned status code is still `996`.

**Comment by 2403905** [comment]
> @2403905 Now, creating and trying to updating a public link without password is returning OCS code `400`.
> But in case of removing the password the returned status code is still `996`.
> Related test scenario: #6465

@PrajwolAmatya Can ton reproduce some why. Please describe the steps shortly.

**Comment by PrajwolAmatya** [comment]
@2403905 I have created a separate issue with steps to reproduce the bug. https://github.com/owncloud/ocis/issues/6619
