### ISSUE TITLE
[antivirus_service] Wrong notification message when ANTIVIRUS_INFECTED_FILE_HANDLING set to "continue"

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#6494]
## Describe the bug

Wrong notification message is shown to the user when the environment variable ANTIVIRUS_INFECTED_FILE_HANDLING is set to "continue".

## Steps to reproduce

1.  start ocis with antivirus service enabled and setting the ANTIVIRUS_INFECTED_FILE_HANDLING = "continue"
> I used clamAV following this [docs](https://doc.owncloud.com/ocis/next/deployment/services/s-list/antivirus.html)
2.  Upload a virus file with text `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`
3.  Wait for the notification

## Expected behavior
The virus file is shown to the user and  the notification should say something like "Virus found; upload successful"

## Actual behavior
The virus file is shown to the user but the notification says something like:
![image](https://github.com/owncloud/ocis/assets/64484313/159a55b6-f655-4f4d-98f8-2198a5e47f37)

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
PROXY_ENABLE_BASIC_AUTH=true IDM_CREATE_DEMO_USERS=true OCIS_INSECURE=true  ANTIVIRUS_SCANNER_TYPE="clamav" OCIS_ASYNC_UPLOADS=true POSTPROCESSING_STEPS="virusscan" ANTIVIRUS_CLAMAV_SOCKET="/var/run/clamav/clamd.ctl" OCIS_ADD_RUN_SERVICES="antivirus" ANTIVIRUS_INFECTED_FILE_HANDLING="continue" ./ocis/bin/ocis server

```

</p>
</details>

## ocis log 
```console
{"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"PATCH","uri":"/data/tus/6c61e5d5-c3a5-48c6-8ea0-6cd46ae094c3","url":"/6c61e5d5-c3a5-48c6-8ea0-6cd46ae094c3","proto":"HTTP/1.1","status":500,"size":69,"start":"13/Jun/2023:11:21:24 +0545","end":"13/Jun/2023:11:21:24 +0545","time_ns":926009,"time":"2023-06-13T11:21:24.437349135+05:45","message":"http"}
{"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"PATCH","uri":"/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjg2NzIwOTg0LCJpYXQiOjE2ODY2MzQ1ODQsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1OC9kYXRhL3R1cy82YzYxZTVkNS1jM2E1LTQ4YzYtOGVhMC02Y2Q0NmFlMDk0YzMifQ.6GcjD1S5n4oakuZWafQGO39pPssFb5v9UcCj14As5q8","url":"/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjg2NzIwOTg0LCJpYXQiOjE2ODY2MzQ1ODQsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1OC9kYXRhL3R1cy82YzYxZTVkNS1jM2E1LTQ4YzYtOGVhMC02Y2Q0NmFlMDk0YzMifQ.6GcjD1S5n4oakuZWafQGO39pPssFb5v9UcCj14As5q8","proto":"HTTP/1.1","status":500,"size":0,"start":"13/Jun/2023:11:21:24 +0545","end":"13/Jun/2023:11:21:24 +0545","time_ns":1407203,"time":"2023-06-13T11:21:24.437437442+05:45","message":"http"}
2023-06-13T11:21:24+05:45 DBG Starting virus scan. filename=eicar.com line=/home/sabin/www/ocis/services/antivirus/pkg/service/service.go:126 service=antivirus uploadid=6c61e5d5-c3a5-48c6-8ea0-6cd46ae094c3
2023-06-13T11:21:24+05:45 DBG Downloaded file successfully, starting virusscan line=/home/sabin/www/ocis/services/antivirus/pkg/service/service.go:189 service=antivirus uploadid=6c61e5d5-c3a5-48c6-8ea0-6cd46ae094c3
2023-06-13T11:21:24+05:45 INF File scanned filename=eicar.com infected=true line=/home/sabin/www/ocis/services/antivirus/pkg/service/service.go:143 outcome=continue resourceID={"opaque_id":"42a4e922-b98c-4d82-8f22-9837d1065c18","space_id":"0aedc5d2-3623-435c-8664-450f5b928899"} service=antivirus uploadid=6c61e5d5-c3a5-48c6-8ea0-6cd46ae094c3 user=0aedc5d2-3623-435c-8664-450f5b928899 virus=Win.Test.EICAR_HDB-1
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"internal error: gateway: error finding an auth provider for type: bearer","type":"bearer","time":"2023-06-13T11:21:26.147583636+05:45","message":"error getting auth provider client"}
```

**Comment by kobergj** [comment]
Good finding :+1: 

If we want `"continue"` to be a valid option for the user we need to adjust the message.

However `"continue"` is a very unsafe option to use. Maybe it's better to declare it as some sort debug option, then the message doesn't matter.

@micbar is using `ANTIVIRUS_INFECTED_FILE_HANDLING = "continue"` an option we want to support?

**Comment by micbar** [comment]
@kobergj @SwikritiT This `continue` option is IMO not supported and only for debugging.

We should reflect it in the config docs.

**Comment by SwikritiT** [comment]
I've created a PR to update the wording in docs https://github.com/owncloud/docs-ocis/pull/547

**Comment by SwikritiT** [comment]
As this is a debug option we probably don't care about the message. Closing this issue
