### ISSUE TITLE
Support builtin storage (BLOBs) encryption

### ISSUE THREAD

**Issue by iFrozenPhoenix** [owncloud/ocis#6496]
## Is your feature request related to a problem? Please describe.
I'd like to encrypt the ocis blob data stored at rest (at the application layer) to provide an additional layer of security.

## Describe the solution you'd like
For encryption I would expect a builtin solution in ocis and not purely rely on other storage backends capabilities
like mentioned in #6273 because this would make it impossible in simple deployments to encrypt the data at rest at
the application level.
I would suggest that an option is introduced to allow encryption of the blobs (Enable + Algo (at least AES GCM + ChaCha20Poly1305). Additionally there should be an option to provide an KEK.
If this options are given ocis starts, generates a random encryption key and encrypts the random encryption key with the provided KEK. The encrypted key is then stored in the metadata.
This approach would allow easy key rotation without the need to reencrypt all blobs.
When ocis starts with enabled encryption and the blobs are not already encrypted, ocis should encrypt them.

## Describe alternatives you've considered
One alternative would be to use the S3 storage driver and encrypt the blobs with S3 SSE. But this solution is not preferred because the metadata are still saved on disk and this could lead to a split brain behavior (A general drawback of the current S3 driver implementation).

**Comment by tbsbdr** [comment]
We currently go with the S3 SSE which is good enough for current usecases. Currently we do not plan to implement another solution; Closing as not planned in the foreseable future; we can reopen if this gets more requests

**Comment by micbar** [comment]
I would suggest not to go down that rabbit hole. We have been there with ownCloud 10.

Storage Encryption at rest should be done with encrypted file systems like GoCryptFS

There is a nice comparison to other encryption mechanisms https://nuetzlich.net/gocryptfs/comparison/

**Comment by iFrozenPhoenix** [comment]
@micbar did you test ocis with gocryptfs?
It looks indeed promising.

**Comment by iFrozenPhoenix** [comment]
Cool, thanks for the info 👍. I'll give it a try
