### ISSUE TITLE
How to create an OCIS Integration (OCIS Apps)?

### ISSUE THREAD

**Issue by switchupcb** [owncloud/ocis#6503]
## Describe the bug

I cannot find the guide to create an integration for the OwnCloud Infinite Scale platform.

## Steps to reproduce

1. Search the search engines.
2. Search the documentation at https://doc.owncloud.com/ocis/next/.

## Expected behavior
Add documentation that specifies how to create integrations (apps) for OwnCloud Infinite Scale. This guide (e.g., [NextCloud App Development](https://docs.nextcloud.com/server/latest/developer_manual/app_development/index.html)) should cover the following tasks:
- Installation: How is the app installed on the instance when a user installs it? A top-view of the process that puts in perspective the significance of each step.
- Frontend: How to integrate a UI (HTML, JS, CSS) with OCIS or modify the OCIS UI (in an idiomatic manner to OCIS that prevents errors on each OCIS update).
- Backend API: How to create the required routes for the application in an idiomatic manner to OCIS.
- Backend Data: How to define additional structured data the application needs in various places (e.g., file metadata, external database, etc) for OCIS.
- OCIS Data: How to fetch the data stored in OCIS (i.e file metadata, API, etc).

This guide also helps integrations integrate with each other since it is clear how to interact with other integrations.

## Actual behavior
Confusion.

**Comment by kobergj** [comment]
@switchupcb you are probably looking for dev documentation which can be found here: https://owncloud.dev/ocis/development/getting-started/

See also subchapter about Extensions: https://owncloud.dev/ocis/development/extensions/ it should cover at least some of the desired topics

**Comment by switchupcb** [comment]
Thanks @kobergj.

# Solution

NextCloud and ownCloud "applications" or other third-party services' "integrations" are equivalent to ownCloud Infinite Scale [extensions](https://owncloud.dev/ocis/development/extensions/).

# Implementation

## Installation (Extension)

ownCloud Infinite Scale (oCIS) does not have an extension marketplace right now. So the oCIS Host is expected to manage the installation of an oCIS extension directly.
1. When the extension uses a User Interface (UI), modify the [ownCloud Web extension configuration file](https://owncloud.dev/extensions/ocis_hello/running/#configure-and-start-ocis).
2. When the extension has API endpoints, modify the  [ownCloud Proxy extension configuration file](https://owncloud.dev/extensions/ocis_hello/running/#configure-and-start-ocis:~:text=file%20from%20the-,oCIS%20proxy,-.%20Just%20add%20an).
3. When the extension uses a backend application, run the application on a server.
4. [Activate the modified configuration files.](https://owncloud.dev/extensions/ocis_hello/running/#configure-and-start-ocis:~:text=activate%20the%20config%20files)
5. Restart the oCIS Server extension by running the command `ocis server` on the computer that hosts the ownCloud Infinite Scale server extension.

## Backend

A backend is an abstract web development concept that describes the software tasked with processing non-visual information. This work typically involves an application with a runtime environment that interacts with storage options (e.g., file system, database).

_oCIS uses a [microservices architecture](https://switchupcb.com/blog/when-do-i-need-microservices/) for its backend._

ownCloud Infinite Scale (oCIS) extensions are hosted independently from other oCIS extensions. So the backend of an oCIS extension can be created in any programming language.

### Data Storage

https://owncloud.dev/ocis/development/extensions/#storage

### File Management

When an extension must interact with the file system of an oCIS instance, it's recommended to use the [CS3 API](https://cs3org.github.io/cs3apis/). You must use the oCIS Proxy Extension user context and authentication token to request files on behalf of the user.

### Metadata

When an extension must store persistent data related to the oCIS instance (outside of a user’s home folder), it's recommended to use the **oCIS Metadata Storage extension [1]**. Metadata is preferred over usage of the local file system because it defaults to the storage backend that the oCIS instance has configured (e.g., EOS, S3).

**[1] This extension is undefined in the documentation.**

_Metadata is attached to a file and describes additional properties of the file [\[2\]](https://owncloud.dev/ocis/adr/0016-files-metadata/)._ 

### Structured Data

oCIS does not have an official database extension right now. See **Other Data** for more information about storing structured data.

### Other Data

Data that is unrelated to the oCIS instance can be stored using any method available. However, it's essential to consider the costs of using an alternative storage system.

For example, an extension that uses an external database (e.g., PostgreSQL) requires the oCIS Host to set up an instance of that database with the extension's backend application (in step 3 of the extension's installation).

Using alternative storage options to store data affects your extension's compatibility with other extensions: A primary extension that uses alternative storage options requires other secondary extensions to use that alternative storage option to interact with the primary extension's data. In contrast, extensions that use metadata store data in a location accessible to all other extensions by default.

### Settings

Data used for settings can be stored in the backend using any method available.

## API

An extension's API endpoints must be registered in the [oCIS Proxy Service](https://owncloud.dev/ocis/development/extensions/#proxy) (in step 2 of the extension's installation).

## Frontend (UI)

The [oCIS Web extension](https://owncloud.dev/ocis/development/extensions/#owncloud-web) is an official oCIS extension that provides an interactable User Interface for the end user. Develop an extension for the oCIS Web extension to add UI components to an oCIS instance.

ownCloud Web uses the [Vue.js JavaScript Framework](https://vuejs.org/) [ownCloud Web library](https://github.com/owncloud/web) to develop its UI: Use this library's classes and components to develop a UI that visually blends with the default oCIS Web UI.

### Settings

An extension's settings UI can be configured using the [settings extension](https://owncloud.dev/services/settings/) to provide the extension settings to the end user via the settings tab in the ownCloud Infinite Scale UI.

## Example

An example of an oCIS extension is the [oCIS Hello extension](https://owncloud.dev/extensions/ocis_hello/).

# Notes

## Officialization

An ownCloud extension functions similarly to every service in the [main ownCloud Infinite Scale GitHub Repository](https://github.com/owncloud/ocis). In other words, extensions are microservices similar to"ownCloud services". This means an extension is "official" (maintained by the ownCloud team) when it's included in the main repository.

# Resources

This documentation is a simplified version of the [official ownCloud Extensions Documentation](https://owncloud.dev/ocis/development/extensions/#owncloud-web). You can request an edit or summary of any technical document using a [SwitchUpCB one-time sponsorship tier](https://github.com/sponsors/switchupcb?frequency=one-time&sponsor=switchupcb).
