### ISSUE TITLE
POSTPROCESSING_STORE_TABLE has empty default

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#6514]
The `POSTPROCESSING_STORE_TABLE` env var is empty by default, causing keys in redis to have no prefix. To prevent collisions we should default to `postprocessing`. Unfortunately, this requires a key migration of postprocessing keys ... which currently have no prefix and only consist of a uuid.
- [ ] set default to `postprocessing`
- [ ] provide key migration
- [ ] update helm chart to run key migration

**Comment by kobergj** [comment]
`postprocessing` is storing data only temporary. (Only while files are being processed). If there are no uploads during the update then the migration is not needed.

We probably have the same issues for `userlog` and `eventhistory`? We will need migration there.

**Comment by kobergj** [comment]
scratch my comment, `userlog` and `eventhistory` have it already
