### ISSUE TITLE
Custom web + WOPI example broken?

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#6531]
## Describe the bug

I've tried following https://owncloud.dev/ocis/deployment/ocis_wopi/ to change my changes from https://github.com/owncloud/web/pull/8447, but when linking my own `/web/dist` seems to mess with the registration of appProvider app actions?

## Expected behavior
Guide should work flawlessly ™️ 

## Actual behavior
- If I just start the vanilla `docker-compose.yml` from latest master, I can create e.g. OpenOffice files
- If I link my custom `/web/dist/`, I see my local web changes but clicking the `Create +` button doesn't offer me any appProvider-actions (like creating OpenOffice files).

## Additional context
Pulled fresh images and deleted volumes before starting docker. I could try and debug this myself, but maybe I'm missing something obvious/undocumented (like linking/modifying a config file)?

**Comment by pascalwengerter** [comment]
Following a discussion with @kulmann that _may_ be a Mac M1 + docker issue (on Docker Desktop `v4.15-19`)

**Comment by kulmann** [comment]
> Following a discussion with @kulmann that _may_ be a Mac M1 + docker issue (on Docker Desktop `v4.1{5-9}`)

Yes, I had the same issues. Would be great if someone with a linux system could check as well before any other debugging takes place.

**Comment by mmattel** [comment]
@micbar just an idea to think about, maybe not related to this issue but could be:

Atm we have deployment examples with a particualr state in various tags. What we dont have is a kind of release notes file in the main directory where we just summarize changes made from one to another version. What about creating one which would ease finding differences? Note that these examples are not only available for devs but also linked by the admin docs.

**Comment by micbar** [comment]
@pascalwengerter Which version are you using?

Do you have my changes includedhttps://github.com/owncloud/ocis/commit/a86aba1c4144d54d80fd956ddcb9139518cbfc04 ?

**Comment by micbar** [comment]
Can you check what the /app/list request returns?

**Comment by pascalwengerter** [comment]
I'll close here since I retried this morning (updated oCIS and docker-for-mac before), and if you wait long enough the `/app/list` endpoint does return the extensions...it just takes quite a while, which I didn't expect
