### ISSUE TITLE
OIDC: configurable post_logout_redirect_uri

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6536]
## Feature Request

Currently the OIDC `post_logout_redirect_uri` is not configurable.

https://github.com/owncloud/web/blob/c77a531e52f0f16292fb37f76b9596b9bcbdf58a/packages/web-runtime/src/services/auth/userManager.ts#L48

As an admin I want the user to redirect to another site than ownCloud Web after logout.

**Comment by kulmann** [comment]
> Which should be the default value?

Can you omit the option if not set? Meaning: no default? Web has a sensible default value.

**Comment by micbar** [comment]
Yes, that is possible.

**Comment by wkloucek** [comment]
oCIS now has `WEB_OIDC_POST_LOGOUT_REDIRECT_URI`
