### ISSUE TITLE
Can't login to v3.0.0 after upgrade from v2.0.0 because of cookie

### ISSUE THREAD

**Issue by willmackay** [owncloud/ocis#6557]
## Describe the bug

After upgrading from OCIS 2.0.0 to 3.0.0, users were unable to use Owncloud via the web interface. It showed an "Authentication Failed" error message (attached).

Upon troubleshooting the issue, I found that other browsers and devices were able to log in as the same user, and I discovered that clearing cookies resolved the issue.

## Setup

Contents of /etc/ocis/ocis.env
```
PROXY_HTTP_ADDR=127.0.0.1:9200
OCIS_URL=https://ocis.alyrica.net
OCIS_BASE_DATA_PATH=/var/lib/ocis
OCIS_LOG_PRETTY=true
GATEWAY_STORAGE_USERS_MOUNT_ID=6c90f11c-02f6-41dc-9091-df245ee3644f
STORAGE_USERS_MOUNT_ID=6c90f11c-02f6-41dc-9091-df245ee3644f
GRAPH_APPLICATION_ID=b730882a-6dd8-455b-8b26-54268ddce457
```

## Additional context

When a login cookie is invalid, OCIS should clear it by setting the same cookie in the HTTP headers with a Max-Age of 0 or -1. This would result in the user getting the login page again and being able to access Owncloud. By leaving the bad cookie, the user is left with no obvious way to regain access to the server and it is effectively offline for them.

![MicrosoftTeams-image](https://github.com/owncloud/ocis/assets/24301649/c9112c83-4bee-4f20-9f98-3a4d01d77901)

**Comment by micbar** [comment]
@rhafer @dragonchaser Does that ring any bells at our side?

**Comment by rhafer** [comment]
https://github.com/owncloud/ocis/pull/6326 cause the `sub` claim of users to change. Which I guess causes the cookie to be no longer valid (just an educated guess though). It's not really nice, but we needed to change that to fix a real bug.

I can't say why the cookie is not removed, that's probably a question for the web folks.

**Comment by willmackay** [comment]
Since this is a problem with the Owncloud Web front-end, I am closing this ticket in favor of one on the Web project: https://github.com/owncloud/web/issues/9285
