### ISSUE TITLE
sharee does not receive a mail notification when sharer changes permission to a shared resource

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#6637]
## Describe the bug

User does not get mail notification when shared file/folder's permission is changed

## Steps to reproduce

1. `Alice` creates a resource `textfile.txt`
2. share the resource to `Brian` using command `curl -kv -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d 'shareType=0&path=/testfile.txt&permissions=17&role=viewer&shareWith=brian' -u alice:123456`
3. `Brian` accepts the share
4. `Alice` changes permission of the resource 
```
curl -kv -X PUT https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/<space-id> -d 'permissions=19&role=editor' -u alice:123456
```
## Expected behavior
`Brian` should receive mail notification when shared file/folder's permission is changed by `Alice`

## Actual behavior
`Brian` does not receive mail notification when shared file/folder's permission is changed by `Alice`

## Setup
Ocis : latest master

**Comment by SwikritiT** [comment]
the behaviour is same for the project spaces too now

**Comment by SwikritiT** [comment]
According to https://github.com/owncloud/ocis/issues/6649#issuecomment-1707919956 this comment this is a feature request and not an issue so closing this

cc: @ScharfViktor
