### ISSUE TITLE
the content of email notification is same when inviting a user to a space and changing his permission

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#6649]
## Describe the bug
When a space is shared to a user he gets a mail notification with following body

```
Hello <User>,

Admin has invited you to join "<space-name>".

Click here to view it: <base-url>/f/<space-id>
```
when the permission of the user is changed the he gets the mail notification with the same body content 
```
Hello <User>,

Admin has invited you to join "<space-name>".

Click here to view it: <base-url>/f/<space-id>
```
in case of notification the same behavior is seen.
`<user>  added you to Space <space-name>`
does user suppose to get same mail notification, or is the mail notification suppose to be different?

## Steps to reproduce

1. create a space as `marie`
```bash
curl -kv -X POST -H "Content-Type: application/json" -d '{"name":"space"}' -u marie:radioactivity https://localhost:9200/graph/v1.0/drives 
```
2. share that space with `einstein` as a viewer
```bash
curl -kv -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d 'shareType=7&shareWith=einstein&role=viewer&space_ref=<space-id>' -u marie:radioactivity
```
3. `einstein` gets a mail notification
4. `marie` changes permission of `einstein` to editor
```bash
curl -kv -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d 'shareType=7&shareWith=einstein&role=editor&space_ref=<space-id>' -u marie:radioactivity
```

## Expected behavior
`einstein` should receive mail notification related to change of permission. 

## Actual behavior
~`einstein` receives mail notification with same content~
`einstein` does not receives mail notification about the change of permissions

## Setup

inbucket 
run using
```
docker run --name email -p 9000:9000 -p 2500:2500 -p 1100:1100 inbucket/inbucket
```
Ocis : latest master
with following env
```
NOTIFICATIONS_SMTP_HOST=localhost
NOTIFICATIONS_SMTP_INSECURE=true
NOTIFICATIONS_SMTP_PORT=2500
NOTIFICATIONS_SMTP_ENCRYPTION=none
NOTIFICATIONS_SMTP_SENDER='ownCloud <noreply@owncloud.com>'

```

**Comment by SwikritiT** [comment]
I tested this locally and the behavior is different now the user only gets in-app notifications and email notification when the space/resources are shared and not when the permissions are updated. @niraj can you check it and update the issue accordingly?

**Comment by ScharfViktor** [comment]
that means issue isn't actual
