### ISSUE TITLE
the email body does not contain the name of the receiver when the receiver has set the language to german

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#6656]
## Describe the bug
When a space is shared to a group and if a member of that group is using german language he gets a mail notification without his name.

```
Hallo <no value>,

Admin hat Sie eingeladen, dem Space "<space-name>" beizutreten.

Zum Ansehen hier klicken: <base-url>/f/<space-id>
```

## Steps to reproduce

1. create a space as `marie`
2. create a group `group1`
3. add `einstein` to that group
4. change `einstein`'s language to `de`
5. share that space with `group1`
6. `einstein` gets a mail notification

## Expected behavior
`einstein` should receive mail notification with his name

## Expected email body

```
Hallo <user-name>,

Admin hat Sie eingeladen, dem Space "<space-name>" beizutreten.

Zum Ansehen hier klicken: <base-url>/f/<space-id>
```

## Actual behavior
`einstein` receives mail notification without his name

## Setup
Ocis : latest master

**Comment by phil-davis** [comment]
Do `space-name` and `base-url` get filled in correctly in the email?

**Comment by micbar** [comment]
I fixed the placeholder in transifex.

Needs a re-sync

**Comment by micbar** [comment]
Should be fixed now https://github.com/owncloud/ocis/commit/164b24cc41295587ef9baeb2dee9d8f06d0c7b87

Can you re test please?

**Comment by nirajacharya2** [comment]
> Do `space-name` and `base-url` get filled in correctly in the email?

yes `space-name` gets filled with the spaces name and `base-url` with `https://localhost:9200`
