### ISSUE TITLE
Full-search. No result on some words or characters

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6674]
Start ocis with `tika` use https://github.com/owncloud/web/blob/master/docker-compose.yml

`tika` cuts and stores only the words. all characters, numbers, prepositions, and punctuation marks are cut off. 
you can't find something using non-words or words with character and it won't show up in the search results 

### Example: 
1. #### content with a number `user1 shares the file to Marie` 
- Search doesn't get result by `user1`. 
- if we search for `user` ->  `<mark>user</mark> user shares file marie` -> no numbers, no article `the` and preposition `to` 

2. #### content with a link `https://localhost/remote.php/dav/files/admin/Photos/San%20Francisco.jpg`. 
- Upload `ownCloud manual.pdf`. here can download it: https://cloud.owncloud.com/s/5stDcdTW7K7XJio  - 
- search for `localhost`. 
- result -> `<oc:highlights>...xml &#39;http <mark>localhost</mark> remote php dav files admin photos san francisco jpg&#39;return…</oc:highlights>`

3. #### content with a `find` `can` `should` `will` ....  words
- no search results for words

**Comment by ScharfViktor** [comment]
when we use keywords like `where`, `this`, `what` to search the file via full-search then it does not search

**Comment by saw-jan** [comment]
TODO (when fixed):
- [ ] add test coverage

**Comment by fschade** [comment]
confirmed, everything expect 3. is a bug, 3 is intended since those words are part of the stop word list.
Anyway, it makes sense to have a option if stop word cleaning should take place or not, i take care.

**Comment by ScharfViktor** [comment]
> TODO (when fixed):
> * [x]  add test coverage

https://github.com/owncloud/ocis/pull/7574
