### ISSUE TITLE
Glauth Backend and Fallback Servers env variable name and flag name inconsistent

### ISSUE THREAD

**Issue by jamu85** [owncloud/ocis#670]
Glauth can be configured to take fall back end backend servers via env variable or command line flag.
While the Environment variable is in Plural, the command line flag is in singular which might lead to confusion.
GLAUTH_BACKEND_SERVERS vs --backend-server
GLAUTH_FALLBACK_SERVERS vs --fallback-server

https://github.com/owncloud/ocis/blob/f9e1b7be9499c51497cb45252cf9874f746a4b98/glauth/pkg/flagset/flagset.go#L209
https://github.com/owncloud/ocis/blob/f9e1b7be9499c51497cb45252cf9874f746a4b98/glauth/pkg/flagset/flagset.go#L212
https://github.com/owncloud/ocis/blob/f9e1b7be9499c51497cb45252cf9874f746a4b98/glauth/pkg/flagset/flagset.go#L268
https://github.com/owncloud/ocis/blob/f9e1b7be9499c51497cb45252cf9874f746a4b98/glauth/pkg/flagset/flagset.go#L271

**Comment by wkloucek** [comment]
glauth service was removed from ocis, therefore no longer valid
