### ISSUE TITLE
Deleting a user breaks personal shares

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6730]
### Steps to reproduce
1. share a file with two persons
2. delete one share receiver
3. restart oCIS to clear caches
4. try to edit the personal share of the leftover person / share the file to another person

### Expected behaviour
I can edit the personal share / share the file to another person

### Actual behaviour
I can no longer see the personal sharing section on that file

![image](https://github.com/owncloud/web/assets/34452982/6e7bbd8c-9e34-4059-8a49-d255ffd9648e)

### Environment general
oCIS-3.1.0-next.2 with Web 7.0.1

### Additional information

originally reported in https://github.com/owncloud/enterprise/issues/5828#issuecomment-1614935038

**Comment by JanAckermann** [comment]
As spoken with @butonic, the share shouldn'be exposed via the api, so transfering this to ocis and closing my pr

**Comment by JanAckermann** [comment]
@micbar @butonic 
can you guys give me an update :D ? 
I can fix the problem in web as well

**Comment by JanAckermann** [comment]
So there should be no error anymore, or is there a pr I should check working in conjunction with the web?

**Comment by butonic** [comment]
@micbar Is there a PR?

**Comment by micbar** [comment]
@tbsbdr @butonic We need to clarify expectations first.

Should the user see "stale" shares to be able to remove them? Or should we filter them out on the server side?

**Comment by tbsbdr** [comment]
stale shares should not be shown in the frontend; I assess that showing stale shares would be more an information overload rather than a information gain for a regular user. lets keep it simple.

**Comment by 2403905** [comment]
@tbsbdr Should we filter out the list on the backend or the frontend side?

**Comment by tbsbdr** [comment]
@butonic said on the backend so that we dont break oc10. generally: this decision is up to you as I don't see major end-user facing implications. so mainly technical decision i guess. or: from my side no objections against **filtering in the backend**

**Comment by butonic** [comment]
we are going to filter on the server side

**Comment by wkloucek** [comment]
@2403905 is this fixed in oCIS 4.0.1?

**Comment by rhafer** [comment]
fixed in 4.0.1
