### ISSUE TITLE
Uploading a folder with more than 25'000 files corrupts itself

### ISSUE THREAD

**Issue by 7ritn** [owncloud/ocis#6746]
## Describe the bug

I tried to upload around 70'000 files into a single folder in OCIS 3.0: However, after some time I'm no longer able to access the folder. A folder with 15'000 files is fine

## Steps to reproduce

1. Upload more than ~25'000 files to a single folder using the OwnCloud Desktop App or WebDAV interface

## Expected behavior
The upload should finish with all files uploaded. I should be able to view the folder.

## Actual behavior
The folder gets corrupted. Trying to view the folder in the web app results in a "Resource not found" message and the following server console log entries:

```
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0","from":"tcp://127.0.0.1:53582","uri":"/cs3.gateway.v1beta1.GatewayAPI/ListContainer","start":"08/Jul/2023:12:44:24 +0000","end":"08/Jul/2023:12:44:27 +0000","time_ns":2858681059,"code":"ResourceExhausted","time":"2023-07-08T12:44:27.635045663Z","message":"unary"}

{"level":"error","service":"ocdav","name":"com.owncloud.web.ocdav","traceid":"00000000000000000000000000000000","request-id":"53163330-643f-4fdf-8f2c-1d2d0ee24a80","path":"/Fotos/Backups","spaceid":"e2b7746d-5fc8-4a16-88dc-4bd337e70105$12cc65d3-ae9f-426f-93c1-5881287f1722","error":"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (25380466 vs. 10240000)","time":"2023-07-08T12:44:27.635672427Z","message":"error sending list container grpc request"}
```

## Setup

Running pretty much the stock OCIS 3.0 Docker image using rootless Podman.

**Comment by micbar** [comment]
@butonic Can you qualify?

**Comment by kobergj** [comment]
I could reproduce locally. The max size for grpc requests is hardcoded in two different places (in ocis and reva seperately of course). 

I'll file PRs to make them configurable.

Not sure how we should handle the error though. We would need to catch the error in the storageprovider and pass them down to webdav somehow. Maybe with specific status codes?

**Comment by kobergj** [comment]
@7ritn we now have a fix in master. You can set the envvar `OCIS_GRPC_MAX_RECEIVED_MESSAGE_SIZE=25380467` to be able to open your folder in the web ui. You will observe that loading this folder takes very long. It's recommended to use subfolders to avoid having so many entries in one folder.

Thanks for reporting and feel free to reopen if the issue persists.
