### ISSUE TITLE
Add step wait-for-fakeoffice to drone pipeline

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6750]
## Description
Currently, ocis-server doesn't wait for fakeoffice service to start.
Sometimes fakeoffice service takes a long time to start. In such cases, ocis-server fail to start with an error message
```
{"level":"error","service":"app-provider","error":"unable to register services: rgrpc: grpc service appprovider could not be started,: Get \"http://fakeoffice:8080/hosting/discovery\": dial tcp: lookup fakeoffice on 127.0.0.11:53: no such host","time":"2023-07-10T05:07:14.481033933Z","message":"error starting the grpc server"}
```
Maybe we could add wait-for-fakeofice to avoid fakeoffice service not being available

https://drone.owncloud.com/owncloud/ocis/24040/46/4

@saw-jan @SwikritiT

**Comment by saw-jan** [comment]
The wopi test pipeline steps should be in order like in stable-3

![Screenshot from 2023-07-10 13-15-52](https://github.com/owncloud/ocis/assets/52366632/8fdc9e74-de02-4c88-9ca3-fe2a9eca1202) | ![Screenshot from 2023-07-10 13-16-05](https://github.com/owncloud/ocis/assets/52366632/12dd5e77-d201-4081-b028-f0320d1bd4f8)
--|--
master | stable-3

**Comment by wkloucek** [comment]
The order on master changed recently, see https://github.com/owncloud/ocis/pull/6416

> Currently, ocis-server doesn't wait for fakeoffice service to start. Sometimes fakeoffice service takes a long time to start. In such cases, ocis-server fail to start with an error message

Aren't the containers guaranteed to be starte one after another? :thinking: Because fakeoffice should take no time to start:

https://github.com/owncloud/ocis/blob/master/tests/config/drone/serve-hosting-discovery.sh#L1-L5

**Comment by wkloucek** [comment]
> > Aren't the containers guaranteed to be starte one after another?
> 
> they should but the fakeoffice step is run in detached mode which means let's other steps to run parallel with it

Ok, my understanding was that the startup order is still guaranteed. But it seems like this is not the case. Adding a wait step seems fine and the best solution :+1:
