### ISSUE TITLE
Add preview tests coverage for space dav version

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6752]
Currently, API tests don't cover space webdav of preview in personal space and share space. 
- [x] Add preview tests coverage for space webdav https://github.com/owncloud/ocis/pull/7218
- [x] add tests coverage for previewing shared resource in spaces webdav @PrajwolAmatya  https://github.com/owncloud/ocis/pull/7234
- [x] add tests coverage for preview space shares https://github.com/owncloud/ocis/pull/7544

**Comment by amrita-shrestha** [comment]
https://github.com/owncloud/ocis/pull/6770

**Comment by SwikritiT** [comment]
Blocked by https://github.com/owncloud/ocis/issues/2071 see discussion or more info https://github.com/owncloud/ocis/pull/6770#discussion_r1269042862

**Comment by PrajwolAmatya** [comment]
All test coverages are completed, so closing this issue.
