### ISSUE TITLE
NATS registry caching services forever

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6762]
## Describe the bug

When using the NATS service registry, we can get quite quickly in a broken state.

## Steps to reproduce

1. start the oCIS with NATS Helm chart example https://github.com/owncloud/ocis-charts/tree/master/deployments/ocis-nats
2. restart the gateway pods: `kubectl -n ocis rollout restart deploy gateway`

## Expected behavior
Requests will fail for ~30 seconds. Afterwards everything is fine.

## Actual behavior
Requests will fail forever. The proxy will log IPs of the gone gateway pods. `ocis version` will discovery the current gateway services when run inside any pod.

## Additional context
oCIS 3.1.0-next.2

**Comment by wkloucek** [comment]
> Severity? Blue Ticket?

Not too pressing. Meanwhile I can use etcd but other projects may not. I guess ~ Feb 2024 would be nice.

**Comment by kobergj** [comment]
Needs an upstream fix in go-micro: https://github.com/go-micro/plugins/blob/v4/registry/nats/v1.2.1/v4/registry/nats/nats.go#L325  Change `"create"`  to `"put"` (prolly we need a configuration for this) I'll file a PR

**Comment by kobergj** [comment]
go-micro PR is here: https://github.com/go-micro/plugins/pull/120
