### ISSUE TITLE
userlog never forgets events for deleted resources

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#6773]
Once you see this in the log:
```json
{"level":"error","service":"userlog","error":"Unexpected status code while getting space: CODE_NOT_FOUND","eventid":"390be748-bd9a-4017-8923-bfc61037bc5a","eventtype":"events.ShareCreated","time":"2023-07-11T14:43:38.153272463Z","line":"github.com/owncloud/ocis/v2/services/userlog/pkg/service/http.go:64","message":"failed to convert event"}
```

You have an event that the userlog service will ignore, but never delete, [leading to traces](https://github.com/owncloud/ocis/pull/6772) like this:
![image](https://github.com/owncloud/ocis/assets/956847/cc89af95-c209-4995-a09c-09c2312c57ca)

In this case there are 528 of these events. And every request creates a stat request, because errors are not cached.

We should delete the event if the shared resource is not found ... or the permission is denied? or on any error?

**Comment by kobergj** [comment]
Userlog deletes events in two cases:
A) It is instructed through `Delete` endpoint
B) The event is deleted in the `eventhistory` service

We could also delete events when the conversion fails. But how can we separate temporal from general errors?

**Comment by butonic** [comment]
we could delete the event on not found and permission denied errors. in those cases I think we are good. when a connection error occurs we can continue with the next event ... hm ... or just abort the whole request? with a retry after header?

for now I'd delete events for not found or permission denied errors ...
