### ISSUE TITLE
Unable to access personal space

### ISSUE THREAD

**Issue by alceasan** [owncloud/ocis#6781]
## Describe the bug

After a container restart, I can't access my files. I can login using OIDC with Authentik, but I don't see my personal space anymore. This is the error in the logs:

`ERR failed to list storage spaces error="error reading user index: unable to parse index: msgpack : invalid code c4 decoding string" filters=[{"Term":{"SpaceType":"personal"},"type":4},{"Term":{"Owner":{"idp":"https://XXXXXX.XXX/application/o/ocis-web-client/","opaque_id":"2dcbeaee-c802-43a7-b451-a54faeef0d46"}},"type":3}] line=github.com/cs3org/reva/v2@v2.14.1-0.20230711102918-b095db01ac36/internal/grpc/services/storageprovider/storageprovider.go:550 pkg=rgrpc service=storage-users status=traceid=db59f32280e2a2706e9201d830beefd4`

I haven't done any recent change in the configuration, I'm currently using version 3.1.0-next.2+56c48df0b

I also tried to login with admin account without OIDC, but I have the same problem: no personal space.

**Comment by github-ninja** [comment]
Same here. Happened after update.

**Comment by kobergj** [comment]
Looks like there was an reva bump yesterday that broke something.

Steps to reproduce:
- start ocis on commit 465d27f8f6f1b1fd7632f67a25b78bf59dd0452e (or earlier)
- upload a file or create a space
- bump ocis to the next usable commit b74eeed359c7a598e58d558d2c5e84106ee63dfd (or later)
- -> The described error occurs. Rolling back did not fix the issue in my test

This is the reva bump that introduced the bug: https://github.com/owncloud/ocis/pull/6748

I'm looking into it...

**Comment by kobergj** [comment]
@alceasan @github-ninja thanks for reporting this. There is an error in an automatic migration we implemented. We will need another PR to fix this. Unfortunately there is no workaround available. You will need to wait for the fix before you can update.

**Comment by aduffeck** [comment]
I'm on it. I hope to get the fix in today.

**Comment by alceasan** [comment]
> @alceasan @github-ninja thanks for reporting this. There is an error in an automatic migration we implemented. We will need another PR to fix this. Unfortunately there is no workaround available. You will need to wait for the fix before you can update.

Thank you @kobergj . Will it be able to repopulate the missing spaces or it'll be necessary to recover data from backup?

**Comment by kobergj** [comment]
@alceasan yes. Updating to new version will fix the problem :+1:
