### ISSUE TITLE
traces show wrong service names

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#6813]
The service names in tracing are wrong after merging some of the trace PRs:
![image](https://github.com/owncloud/ocis/assets/956847/9df78ba5-20df-4da0-bdac-62f02dd5e106)

The IdP has nothing to do with ListStorageSpaces, not as a client, not as a server ...

**Comment by butonic** [comment]
this only seems to happen when running in single process ...

**Comment by micbar** [comment]
@ainmosni @dragonchaser Can you fix that?

**Comment by ainmosni** [comment]
I'm not able to reproduce this in the single process mode.

![Screenshot_20230719_091317](https://github.com/owncloud/ocis/assets/1147920/b1b0c285-e9cd-4770-83a3-883e8efd942c)

**Comment by dragonchaser** [comment]
closing, could not reproduce
