### ISSUE TITLE
Content of owncloud.dev/admin docs does not match code (envvar in gateway service)

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#6816]
Stumbling over this by chance because I saw that the envvar `OCIS_REVA_GATEWAY` in the `gateway` service shows a wrong deprecation version of 3.1 instead of 4.0.0 _which was already fixed_ some time ago, I wondered why there are inconsistencies.

Digging deeper, it became more curious as the `OCIS_REVA_GATEWAY` envvar in the `gateway` service **is no longer present** in master. I was looking in both my rebased local repo as here in master and the envvar is totally gone but shows up in [owncloud.dev](https://owncloud.dev/services/gateway/#environment-variables) and [admin docs](https://doc.owncloud.com/ocis/next/deployment/services/s-list/gateway.html#environment-variables).

Additionally looking in the [docs](https://github.com/owncloud/ocis/blob/docs/services/_includes/adoc/gateway_configvars.adoc) branch of master and also do a local `make docs-generate`, you see that the envvar `OCIS_REVA_GATEWAY` is still present for the gateway service with deprecation 3.1 See the extract of the local make command with the actual date:

```
[#deprecation-note-2023-07-15-11-54-58]
[caption=]
.Deprecation notes for the gateway service
[width="100%",cols="~,~,~,~",options="header"]
|===
| Deprecation Info
| Deprecation Version
| Removal Version
| Deprecation Replacement

| REVA_GATEWAY changing name for consistency
| 3.0
| 3.1
| OCIS_REVA_GATEWAY
```
This means that there is something broken in the automatic documentation generation that needs urgent care as we to not know if other stuff is affected too.

@dragonchaser @kobergj

**Comment by dragonchaser** [comment]
https://github.com/owncloud/ocis/blob/ca929abd3aa1745912e33a99a83cc2c7ac0c3a06/ocis-pkg/shared/shared_types.go#L36 there is your culprit
