### ISSUE TITLE
Search location filter. doesn't search by shares jail

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6825]
steps:

- admin creates `f1/f2/test.txt`
- admin shares folder `f1` to einstein
- einstein accepts `f1` and goes inside the folder `f1`
- einstein searches by `test` using search filter `current folder`

using api: 
- einstein gets uuid f1: `curl https://host.docker.internal:9200/graph/v1.0/drives -ueinstein:relativity -vk | jq --raw-output '.value'`
einstein searches by `test` <oc:pattern>test scope:UUID</oc:pattern>: 
```
curl -XREPORT https://host.docker.internal:9200/remote.php/dav/files/einstein/ -ueinstein:relativity -vk --data '<?xml version="1.0"?>
<oc:search-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <oc:permissions />
    <oc:favorite />
    <oc:fileid />
    <oc:file-parent />
    <oc:name />
    <oc:owner-id />
    <oc:owner-display-name />
    <oc:shareid />
    <oc:shareroot />
    <oc:share-types />
    <oc:privatelink />
    <d:getcontentlength />
    <oc:size />
    <d:getlastmodified />
    <d:getetag />
    <d:getcontenttype />
    <d:resourcetype />
    <oc:downloadURL />
    <oc:tags />
  </d:prop>
  <oc:search>
    <oc:pattern>test scope:a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!1284d238-aa92-42ce-bdc4-0b0000009157:some-admin-user-id-0000-000000000000:dc90b19b-4886-400e-93b3-152ada0c5b4d</oc:pattern>
    <oc:limit>8</oc:limit>
  </oc:search>
</oc:search-files>'
```

Actual: no search result
Expected: it's possible to find objects in the accepted shared folder

CC @2403905

**Comment by 2403905** [comment]
@ScharfViktor  @JanAckermann 
For search by shares, we have to use the nodeid 
`<oc:pattern>file scope:storage-users-1$some-admin-user-id-0000-000000000000!nodeid</oc:pattern>`
instead of
`<oc:pattern>file scope:storage-users-1$some-admin-user-id-0000-000000000000</oc:pattern>`

See https://github.com/owncloud/ocis/pull/6713

**Comment by ScharfViktor** [comment]
I searched by 3 ids (see scren) but couldn't find nothing. 
<img width="1384" alt="Screenshot 2023-07-18 at 16 53 22" src="https://github.com/owncloud/ocis/assets/84779829/351d67bf-1977-4659-a6c8-32bfa9bf0f69">

**Comment by ScharfViktor** [comment]
@2403905 what identifier should I use? looking at my screen

**Comment by ScharfViktor** [comment]
> For a shared folder f2 we are using `fileId` (1) like a scope And add the `\f3` if we want to search in a subfolder

empty result 
![image](https://github.com/owncloud/ocis/assets/84779829/8f3a61b7-8ef0-4043-9601-b73ccabe753e)

**Comment by 2403905** [comment]
There are two examples of the same request
`curl 'https://localhost:9200/remote.php/dav/files/einstein/' \
  -X 'REPORT' \
  --data-raw $'<?xml version="1.0"?>\n<oc:search-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">\n  <d:prop>\n    <oc:permissions />\n    <oc:favorite />\n    <oc:fileid />\n    <oc:file-parent />\n    <oc:name />\n    <oc:owner-id />\n    <oc:owner-display-name />\n    <oc:shareid />\n    <oc:shareroot />\n    <oc:share-types />\n    <oc:privatelink />\n    <d:getcontentlength />\n    <oc:size />\n    <d:getlastmodified />\n    <d:getetag />\n    <d:getcontenttype />\n    <d:resourcetype />\n    <oc:downloadURL />\n    <oc:tags />\n  </d:prop>\n  <oc:search>\n    <oc:pattern>file scope:a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!storage-users-1:some-admin-user-id-0000-000000000000:8003d521-f9eb-4698-ace9-f18093443fe3/f2</oc:pattern>\n    <oc:limit>8</oc:limit>\n  </oc:search>\n</oc:search-files>' \
  -ik \
  -ueinstein:relativity




curl 'https://localhost:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!storage-users-1:some-admin-user-id-0000-000000000000:8003d521-f9eb-4698-ace9-f18093443fe3' \
  -X 'REPORT' \
  --data-raw $'<?xml version="1.0"?>\n<oc:search-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">\n  <d:prop>\n    <oc:permissions />\n    <oc:favorite />\n    <oc:fileid />\n    <oc:file-parent />\n    <oc:name />\n    <oc:owner-id />\n    <oc:owner-display-name />\n    <oc:shareid />\n    <oc:shareroot />\n    <oc:share-types />\n    <oc:privatelink />\n    <d:getcontentlength />\n    <oc:size />\n    <d:getlastmodified />\n    <d:getetag />\n    <d:getcontenttype />\n    <d:resourcetype />\n    <oc:downloadURL />\n    <oc:tags />\n  </d:prop>\n  <oc:search>\n    <oc:pattern>file scope:a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!storage-users-1:some-admin-user-id-0000-000000000000:8003d521-f9eb-4698-ace9-f18093443fe3</oc:pattern>\n    <oc:limit>8</oc:limit>\n  </oc:search>\n</oc:search-files>' \
  -ik \
  -ueinstein:relativity`

The id we can retrieve from here ` curl https://host.docker.internal:9200/graph/v1.0/me/drives -ueinstein:relativity -vk | jq --raw-output '.value'`

**Comment by ScharfViktor** [comment]
works fine on backend side 
I close in favor of https://github.com/owncloud/web/issues/9439
