### ISSUE TITLE
The ocis_wopi docker stack doesn't work properly

### ISSUE THREAD

**Issue by 2403905** [owncloud/ocis#6830]
## Describe the bug

Can not create/open the OpenDocument

## Steps to reproduce

1. Pull the latest master
2. Go to deployments/examples/ocis_wopi and run docker-compose up -d
3. Login as admin. Open the onlyoffice.owncloud.test, wopiserver.owncloud.test and ocis.owncloud.test in a browser
4. Go to personal > Create new OpenDocument

## Expected behavior
A new OpenDocument will be created.

## Actual behavior
The user can see an error message.
The file will appear after the page reload.
The user can not open the created file.

![Screenshot 2023-07-17 at 17 10 31](https://github.com/owncloud/ocis/assets/11679989/d7069e4f-ba47-4dd7-81e9-d4f6f233cc0e)

## Setup

owncloud/ocis:latest
sha256:13b4f07c97eff4e3549fe7a2d429c06379a135c6574e2a508476f919ccaf672d

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

docker-compose up -d

**Comment by ScharfViktor** [comment]
can confirm: 
<img width="1202" alt="Screenshot 2023-07-18 at 09 51 59" src="https://github.com/owncloud/ocis/assets/84779829/a6115a5d-3094-4502-bfba-be13208f97c1">

**Comment by micbar** [comment]
fixed by #6828
