### ISSUE TITLE
Share links are pointing to the wrong backend when glauth backend is owncloud

### ISSUE THREAD

**Issue by jamu85** [owncloud/ocis#687]
Scenario as following: 

- ocis as frontend and oc10 as backend
- Logged in as oc10 user
- Sharing a file via public link in Phoenix

The generated link to the file is pointing to oc10 instead of ocis

Reproduce
visit https://ocis-bridge.owncloud.works
login Felix:1234
create a public link for e.g. folder "pictures"
results in `https://oc10-bridge.owncloud.works/s/onhWsuVbvhTr427`

Expectation is a public link that is pointing to ocis instead of oc10

**Comment by wkloucek** [comment]
closed in favor of https://github.com/owncloud/ocis/issues/4002. Currently there is no public share integration for the parallel deployment
