### ISSUE TITLE
Ocis vs keycloak. Failed to log in due to missing email

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6909]
start `ocis` using https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_keycloak

steps: 
- go to https://keycloak.owncloud.test/admin/master/console/#/oCIS/users/add-user
- create user without email - it's not required
<img width="357" alt="Screenshot 2023-07-27 at 14 06 23" src="https://github.com/owncloud/ocis/assets/84779829/8d549a61-1b1c-4f00-a13d-007fc15e971d">

- add a role to the user
- log in as new user

Actual:
![image](https://github.com/owncloud/ocis/assets/84779829/a70615dd-42c6-4139-9f76-1bd2203b302c)

log: `ocis-ocis-1  | {"level":"error","service":"proxy","error":"Missing claim 'email'","claims":{"email_verified":false,"family_name":"test","given_name":"test","name":"test test","preferred_username":"test","sub":"61f8257f-e67b-4e56-8e8d-c019d09c3885"},"time":"2023-07-27T10:57:02.595321005Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/user/backend/cs3.go:162","message":"Error creating user from claims"}`

Expected: creating users without email is possible

cc @wkloucek

**Comment by rhafer** [comment]
Hm, true. With `PROXY_AUTOPROVISION_ACCOUNTS` we still require a `email` claim to be set. (Technically it's not a required attribute for the libregraph User we're creating.

**Comment by rhafer** [comment]
I am trying to fix this together with #8635
