### ISSUE TITLE
MDNS Flood (and CPU overload)

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#6918]
When running ocis with an active mdns registry inside a network with an active AVM FritzBox! (7530, v7.56 in my case),
ocis and the FritzBox will start playing message ping pong and ocis will clog up the whole CPU of its host machine.
The FritzBox will also become slower.

We assume that this needs an upstream go-micro fix.

/cc @micbar 
/bcc @aduffeck @kobergj @2403905 

**Note:**
Temporary workaround for affected devs:

```bash
iptables -A OUTPUT -p udp --dport=5353 -j DROP
```

To figure out if you are affected you can use an mdns sniffer:

```bash
docker run --rm --network host --name sapito -it stratosphereips/sapito:latest  python3 sapito.py -i <interfacename>
```

**Comment by micbar** [comment]
wasn't that the reason why we switched from mdns to memory?

**Comment by dragonchaser** [comment]
@micbar still the default in https://github.com/owncloud/ocis/blob/master/ocis-pkg/registry/registry.go#L69-L70

**Comment by micbar** [comment]
yes. we override it and per default we use `memory`

**Comment by micbar** [comment]
We use memory and in more complex deployments etcd.

**Comment by dragonchaser** [comment]
That is AFAIK a setting through the environment variables `MICRO_REGISTRY` and `MICRO_REGISTRY_ADDRESS`.

**Comment by micbar** [comment]
nitpicking 😄  You start ocis, you get `memory`.
