### ISSUE TITLE
Add Static API token to the Deprovisioning Request

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#6938]
# Description

- Add a possibility to use a static API token to create a deprovisioning notification.
- Using the token should have more prio and overrule the permission check.

**Comment by micbar** [comment]
@wkloucek FYI

**Comment by wkloucek** [comment]
> @wkloucek userlog service is still behind the proxy so it will require a valid authenticated user. Do we need to make the endpoints available without any authentication (except the static secret)?

For me / the current project it's fine if we consider this as an internal API authentication method (not supported to be used through the proxy). For the product I cannot answer this.

So I can go to the userlog service(s) directly with the API token and set the global notification, right?

**Comment by kobergj** [comment]
You mean you call the `userlog` service without going via proxy? I didn't know that's possible. Yes that would work also. 

So we don't need to add the global notifications endpoints to the `no authentication` routes in the proxy?

**Comment by kobergj** [comment]
@wkloucek @micbar I still need input here. Do I need to make the global notification endpoint reachable from outside without any authentication?
