### ISSUE TITLE
No error when S3 upload fails

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6962]
## Describe the bug

There is no error message / log when the S3 upload fails.

## Steps to reproduce

1. use the S3 deployment example: https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_s3
2. start it and upload a file into oCIS, try to download it - everything should be fine
3. change the access key `STORAGE_USERS_S3NG_SECRET_KEY` to something else, eg. `foobar`
4. ensure you redeploy
5. upload a file into oCIS and try to download it

## Expected behavior

Upload fails when we don't use async uploads. It also should produce a error log.
Upload succeeds when we use async uploads, but fail on a later point in time. I'm not sure how to handle this exactly but it definitively should produce a error log.

## Actual behavior

Upload succeeds, no error log.
I have no way to notice that it doesn't work.

## Setup

S3 deployment example with oCSI 3.1.0-rc.1

## Additional context

To check S3 bucket accessibility without triggering user requests is proposed here: https://github.com/owncloud/ocis/issues/6774

**Comment by micbar** [comment]
Added it to the board.

**Comment by aduffeck** [comment]
Should be fixed when https://github.com/cs3org/reva/commit/a944f8fb14d6b66133756edbaaa88f716692037a lands in ocis

**Comment by ScharfViktor** [comment]
re-tested
error log in ocis:

`{"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"GET","uri":"/data/spaces/9df28291-5d07-43b0-b4de-0a2882dabc9e$56c68034-7f67-4208-a95e-dfdfb116ee51%2156c68034-7f67-4208-a95e-dfdfb116ee51/testavatar100.JPG","url":"/testavatar100.JPG","proto":"HTTP/1.1","status":500,"size":0,"start":"09/Aug/2023:18:53:25 +0000","end":"09/Aug/2023:18:53:25 +0000","time_ns":8492042,"time":"2023-08-09T18:53:25.316496627Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230809113840-3ceaf17cf7fb/internal/http/interceptors/log/log.go:112","message":"http"}`

**Comment by wkloucek** [comment]
> re-tested error log in ocis:

That's the case when async postprocessing is off? Async postprocessing on on behaves differntly probably.


> `{"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"GET","uri":"/data/spaces/9df28291-5d07-43b0-b4de-0a2882dabc9e$56c68034-7f67-4208-a95e-dfdfb116ee51%2156c68034-7f67-4208-a95e-dfdfb116ee51/testavatar100.JPG","url":"/testavatar100.JPG","proto":"HTTP/1.1","status":500,"size":0,"start":"09/Aug/2023:18:53:25 +0000","end":"09/Aug/2023:18:53:25 +0000","time_ns":8492042,"time":"2023-08-09T18:53:25.316496627Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230809113840-3ceaf17cf7fb/internal/http/interceptors/log/log.go:112","message":"http"}`

Why is your log `"method":"GET"`?

**Comment by micbar** [comment]
reva update was successful

**Comment by ScharfViktor** [comment]
> That's the case when async postprocessing is off? Async postprocessing on on behaves differntly probably.
https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_s3

I run ocis using https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_s3 
it doesn't say anything about postprocessing

> Why is your log `"method":"GET"`?
hm, method HEAD gives ьу 200 like everything's fine. Attached is a more complete log

```
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"097f3f34-f7fa-4b8d-9246-ad7d7f333e41","remote-addr":"192.168.96.1","method":"HEAD","status":200,"path":"/remote.php/dav/spaces/adbd530f-191a-4576-8623-3a46002ca2de$e0b2cf77-5bc8-4165-8975-52e7bdec58ba/ownCloud Manual.pdf","duration":27.061583,"bytes":0,"time":"2023-08-10T09:36:50.198453132Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:31","message":"access-log"}

{"level":"info","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","data-server":"http://localhost:9158/data","ref":{"resource_id":{"storage_id":"adbd530f-191a-4576-8623-3a46002ca2de","opaque_id":"e0b2cf77-5bc8-4165-8975-52e7bdec58ba","space_id":"e0b2cf77-5bc8-4165-8975-52e7bdec58ba"},"path":"./ownCloud Manual.pdf"},"time":"2023-08-10T09:36:50.336835132Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230809113840-3ceaf17cf7fb/internal/grpc/services/storageprovider/storageprovider.go:279","message":"file download"}

{"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","request-id":"dc8caa393e6b/ue7QX3aeJc-000562","svc":"datatx","handler":"download","error":"Decomposedfs: error download blob '66bcd8f3-7e28-4162-9b51-5a22f95464e2': blob path: e0b2cf77-5bc8-4165-8975-52e7bdec58ba/02/af/01/dd/-8a9a-48a9-b7cf-d0e009207822: Access Denied.","action":"download","time":"2023-08-10T09:36:50.354138507Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230809113840-3ceaf17cf7fb/pkg/rhttp/datatx/utils/download/download.go:227","message":"unexpected error"}

{"level":"error","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"GET","uri":"/data/spaces/adbd530f-191a-4576-8623-3a46002ca2de$e0b2cf77-5bc8-4165-8975-52e7bdec58ba%21e0b2cf77-5bc8-4165-8975-52e7bdec58ba/ownCloud%20Manual.pdf","url":"/ownCloud%20Manual.pdf","proto":"HTTP/1.1","status":500,"size":0,"start":"10/Aug/2023:09:36:50 +0000","end":"10/Aug/2023:09:36:50 +0000","time_ns":5621917,"time":"2023-08-10T09:36:50.354205882Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230809113840-3ceaf17cf7fb/internal/http/interceptors/log/log.go:112","message":"http"}

{"level":"error","service":"frontend","pkg":"rhttp","traceid":"50bfe45369de1c5da434df5c30b029ab","host":"127.0.0.1","method":"GET","uri":"/data","url":"/","proto":"HTTP/1.1","status":500,"size":0,"start":"10/Aug/2023:09:36:50 +0000","end":"10/Aug/2023:09:36:50 +0000","time_ns":6611833,"time":"2023-08-10T09:36:50.35436359Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230809113840-3ceaf17cf7fb/internal/http/interceptors/log/log.go:112","message":"http"}
```
