### ISSUE TITLE
Translation not working properly on some menu items

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#697]
The translation is not working correctly for some of the menu items.

eg. When setting language to Deutsch

![Screenshot from 2020-10-14 12-39-55](https://user-images.githubusercontent.com/19869344/95954182-a11e7b00-0e1a-11eb-9e43-02f7f525d9ee.png)
![Screenshot from 2020-10-14 12-40-01](https://user-images.githubusercontent.com/19869344/95954189-a2e83e80-0e1a-11eb-849e-d271816e7366.png)

**Comment by refs** [comment]
still happens [with the current master](https://github.com/owncloud/ocis/commit/8fa89f50676d065fc469ccb780037135a29639f4)

**Comment by refs** [comment]
I'm in the impression that this could be a quick win with a large impact. Mixing locals is pretty embarrassing :(

**Comment by kulmann** [comment]
`Mixing locals` is a result of not having everything translated. Each oC Web release brings new translations to oCIS - at least for the strings that come from the oC Web repository. When a string is not translated, we show the english string as a fallback. The strings shown in the screenshots of this ticket are translated when we merge https://github.com/owncloud/ocis/pull/1191

**Comment by refs** [comment]
since #1191 is merged, can this be closed?

**Comment by kulmann** [comment]
Yeah... on retesting: the screenshots from the original issue are not fully translated in all supported languages. :-(

**Comment by pascalwengerter** [comment]
Should be closed since we've translated `en` and `de` for the a11y update and made sure the relevant strings are translate-able. Closing for now, please open new issues if you come across any occurances!
