### ISSUE TITLE
Recycle bin data retention

### ISSUE THREAD

**Issue by hendrikreuhl** [owncloud/ocis#6977]
## Is your feature request related to a problem? Please describe.
I have a backup software that stores large files in ocis. The software has a backup retention and automatically deletes old files.
OCIS moves them to the bin and keeps them there. This results in the LXC-Container running full of storage letting the container crash

## Describe the solution you'd like
It would be great to have a recycle bin data rentention, to clear the bin after a specified amount of time.

**Comment by micbar** [comment]
This is already possible via https://doc.owncloud.com/ocis/next/deployment/services/s-list/storage-users.html##purge-expired-space-trash-bin-items

**Comment by hendrikreuhl** [comment]
> 

Thanks for your reply. I thought this was only valid for the manual execution of the `ocis storage-users trash-bin purge-expired` command, but I will give it a try
