### ISSUE TITLE
Mount points should return shares despite of their current status

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#6997]
In the future, the WebUI will list incoming shares by fetching all spaces that are of type `mountpoint`. For that we need this endpoint to return all shares despite of their status, meaning: all pending, accepted and declined shares.

Also we need the sync status property to be available on the API.

cc @micbar

**Comment by butonic** [comment]
As discused in https://github.com/owncloud/ocis/pull/6995, in the future clients should list incoming shares using the dedicated libre graph endpoint `/me/drive/sharedWithMe`, following https://learn.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0&tabs=http

right?
