### ISSUE TITLE
[QA] File entries in the Propfind response is not strictly checked with the expected file entries resulting in false positive results

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7006]
## Describe the bug

While checking the file entry in the profind response, the existing code checks with the ends with the method which results false positive outcome.
https://github.com/owncloud/ocis/blob/96e5e2e1ba3dddf965edeb51cdad2378e29414c5/tests/acceptance/features/bootstrap/WebDav.php#L5310-L5313

**Comment by saw-jan** [comment]
Done for REPORT https://github.com/owncloud/ocis/pull/7007
- [ ] need to do for PROPFIND
