### ISSUE TITLE
ApiTest. X-Request-ID in the output 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7022]
Sometimes api tests fail in CI. To easily see the issue, we should:
-  send in every request (random uuid X-RequestID in the header). 
- If the test fails, we should be able to get the X-RequestID in the output and easily find the server log by X-RequestID

Related PR's
- [x] master https://github.com/owncloud/ocis/pull/7085
- [x] stable-4.0 https://github.com/owncloud/ocis/pull/7238

CC @individual-it @saw-jan

**Comment by saw-jan** [comment]
Done in https://github.com/owncloud/ocis/pull/7085

**Comment by saw-jan** [comment]
Didn't find required-id for some of the API test pipelines.

@PrajwolAmatya I think we have to inspect it again.

**Comment by ScharfViktor** [comment]
- [ ] check please that ocis log contains `x-requestID` if we use `ociswrapper`

**Comment by saw-jan** [comment]
We don't get `request-id` for some `error` logs but the `request-id` is available in `info` log.
For example; trying to do an unauthenticated request (with log level `info`):
```json
{
  "level": "error",
  "service": "proxy",
  "error": "could not authenticate with username and password user: admin, got code: 8",
  "authenticator": "basic",
  "path": "/remote.php/dav/files/admin",
  "time": "2023-09-18T13:44:47.935305279+05:45",
  "line": "/mnt/workspace/owncloud/ocis/services/proxy/pkg/middleware/basic_auth.go:39",
  "message": "failed to authenticate request"
}
{
  "level": "info",
  "service": "proxy",
  "proto": "HTTP/1.1",
  "request-id": "1234",
  "remote-addr": "127.0.0.1:49850",
  "method": "PROPFIND",
  "status": 401,
  "path": "/remote.php/dav/files/admin",
  "duration": 139.635712,
  "bytes": 211,
  "time": "2023-09-18T13:44:47.93538145+05:45",
  "line": "/mnt/workspace/owncloud/ocis/services/proxy/pkg/middleware/accesslog.go:31",
  "message": "access-log"
}
```

**Comment by saw-jan** [comment]
> * [x]  check please that ocis log contains `x-requestID` if we use `ociswrapper`

Checked. we do get the `request-id` while using ociswrapper too

**Comment by PrajwolAmatya** [comment]
I have seen `request-id` appear in the error logs when the response is `>=500`. In other cases, `request-id` is not present in the error log.

**Comment by amrita-shrestha** [comment]
looks like this is not an issue from the test code. So closing as completed from our side. cc @ScharfViktor
