### ISSUE TITLE
renaming user to any string with capital letter gives error response

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#7044]
## Describe the bug

Renaming an existing user to a string with capital letters in it will result in a 404 response code but the username is changed. 

## Steps to reproduce

1. Create a user `Alice` and note the user-id
2. As admin, try to rename the username of `Alice` to `CapLetter` :x:

```bash
curl -X PATCH https://host.docker.internal:9200/graph/v1.0/users/<alice-user-id> \
-d'{"onPremisesSamAccountName": "CapLetter", "accountEnabled": true}' \
-uadmin:admin -vk
```
```bash
< HTTP/2 404 
< access-control-allow-origin: *
< content-type: application/json; charset=utf-8
< content-length: 147
<
...
{
  "error": {
    "code": "itemNotFound",
    "innererror": {
      "date": "2023-08-16T05:52:50Z",
      "request-id": "328a6cd7107e/65aLZWnZaO-000757"
    },
    "message": "not found"
  }
}
```
3. check username (username gets renamed)
```bash
curl https://host.docker.internal:9200/graph/v1.0/users/<alice-user-id> -uadmin:admin -vk
```
```bash
{
...
  "accountEnabled": true,
  "displayName": "Alice Hansen",
  "onPremisesSamAccountName": "CapLeter",
...
}
```

## Expected behavior
Expected `200` HTTP code with user information.
```json
{
  "accountEnabled": true,
  "displayName": "Alice Hansen",
  "id": "1aab9aed-d4be-472b-bda9-863f21839dfc",
  "mail": "alice@example.org",
  "onPremisesSamAccountName": "CapLeter",
  "surname": "alice",
  "userType": "Member"
}
```

**Comment by S-Panta** [comment]
Same issue https://github.com/owncloud/ocis/issues/5763#issuecomment-1460491813

**Comment by 2403905** [comment]
@rhafer Maybe you remember why the `value := strings.ToLower(a.Value)` is commented out.
Looks like it is a cause of the issue.

https://github.com/go-ldap/ldap/commit/c4ad4d4beca2bafff6c1592071328b9ea2ddab1b#diff-03848630a4ea01c65fbf82a2d193901b54438b6b43387db0c4d91038ee8091f8R30
