### ISSUE TITLE
redesign authentication

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#708]
Currently, the proxy has a middleware to authenticate the requests using oidc and then fetch the accountid and roles.

We should make this more modular and introduce a (or use the reva) auth registry and several auth providers.

An auth provider each for:
- [x] basic auth
- [x] bearer auth
- [ ] public link tokens
- [x] presigned requests

ocis-proxy (or any service with the appropriate middleware) can then delegate authentication to that auth service. extensions could optionally use the middleware if they should run without the proxy. then the proxy would become only necessary in cases a user based routing is necessary.

**Comment by refs** [comment]
This concepts belong on Reva.
