### ISSUE TITLE
[QA] Check and remove the use of `setResponse()` and `$this->response` in the Given/Then steps

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#7082]
We have used `setResponse()` and `$this->response` in the Given/Then steps and some helper functions (maybe to reuse existing available methods). But storing responses from Given/Then steps and helper functions is not a good idea because it can lead to a false positive assertion in the Then steps.

For example, https://github.com/owncloud/ocis/blob/ff304dfc5051db6c6bbfa55443b9829ff527e471/tests/acceptance/features/coreApiVersions/fileVersions.feature#L18-L21

Here, the When step is upload resource and Then step checks that the When step's response code is `200` which is wrong here but the test passes. This is because of the saved response from Given step.

Open tasks:
- [x] check the use of `setResponse()` and `$this->response` in
  - [x] Given steps
  - [x] Then steps (Then steps can use `$this->response` but must prevent saving to it)
  - [x] Helper functions
- [ ] Prevent use of step-def functions in other steps-defs wherever possible (strictly prevent the reuse between cross steps). 
- [x] Refactor `theHTTPStatusCodeShouldBe()` so that it can accept response object to get statuscode from https://github.com/owncloud/ocis/pull/7169
    ```
    theHTTPStatusCodeShouldBe($response)
    ```

**Comment by amrita-shrestha** [comment]
maybe this old issue help https://github.com/owncloud/core/issues/39512

**Comment by saw-jan** [comment]
Never save responses in Given steps. Let the response code be only within the Given steps. That way we don't have to worry about clearing the response/statuscode stores.

**Comment by amrita-shrestha** [comment]
so there is two tasks here 
- remove the response saved by setResponse()
-  clean previously saved HTTP step  by pushToLastHttpStatusCodesArray()

Am I correct @saw-jan

**Comment by saw-jan** [comment]
If those are done in Given/Then steps or helper functions then yes. But if you mean everywhere in the test code then no.

**Comment by amrita-shrestha** [comment]
recently something catches my attention we call `When` step function in `Given`  step. So `Given` and `When` are interlinked so how could we remove setResponse(). cc @saw-jan

**Comment by saw-jan** [comment]
Yeah, that should be part of this ticket.
we should not and never use step-def functions in other steps-defs wherever possible (strictly not between cross steps).
What we can do in that case:
- create a helper function
- use the helper function in the step definition function

**Comment by phil-davis** [comment]
> use the helper function in the step definition function

yes, I agree. We did this sort of pattern in quite a lot of places already. Forexample, I see in FavoritesContext (happens to be in core, but similar examples will be in ocis test code:
```
	public function userFavoritesElement(string $user, string $path):void {
		$response = $this->changeFavStateOfAnElement(
			$user,
			$path,
			1
		);
		$this->featureContext->setResponse($response);
	}
```

```
	/**
	 * @When user :user favorites element :path using the WebDAV API
	 */
	public function userFavoritesElementUsingWebDavApi(string $user, string $path):void {
		$this->userFavoritesElement($user, $path);
	}
```

```
	/**
	 * @Given user :user has favorited element :path
	 */
	public function userHasFavoritedElementUsingWebDavApi(string $user, string $path):void {
		$this->userFavoritesElement($user, $path);
		$this->featureContext->theHTTPStatusCodeShouldBeSuccess();
	}
```

The `setResponse` call can be moved into the When step code, so that only the When step remembers the response.

**Comment by saw-jan** [comment]
If you go on refactoring Given steps and helper functions then you will know which test suites are affected. So, IMO, this ticket cannot be divided by test suites. But I am just letting you know, continue your way.

**Comment by KarunAtreya** [comment]
> If you go on refactoring Given steps and helper functions then you will know which test suites are affected. So, IMO, this ticket cannot be divided by test suites. But I am just letting you know. You can continue your way.

should i go context wise then?

**Comment by saw-jan** [comment]
> should i go context wise then?

maybe yes.

**Comment by SwikritiT** [comment]
@KarunAtreya I've updated the above checklist to include the backport checklist as well can you please backport your related PRs and link them there

**Comment by Salipa-Gurung** [comment]
> Prevent use of step-def functions in other steps-defs wherever possible (strictly prevent the reuse between cross steps). 
We will continue to work on this in next issue https://github.com/owncloud/ocis/issues/8199
