### ISSUE TITLE
REPORT request return multi-status 207 even there is no `personal-space-id` in space dav-path-version endpoint

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7104]
## Describe the bug

When making a report request without having `personal-spaces-id` on the endpoint, it returns a response of multi-status 207 result.
This bug also occurs while sharee do report request and there is no `sharee-personal-space-id` at the endpoint. That also returns multi-status 207.

## Steps to reproduce

1. As `einstein`, created a file `file.txt`
2. As `einstein`, search resources using `file` through API

```bash
curl -kv -XREPORT https://localhost:9200/dav/spaces/ \                                                                                                                                
-u einstein:relativity \
-d "<?xml version='1.0' encoding='utf-8' ?>
<oc:search-files xmlns:a='DAV:' xmlns:oc='http://owncloud.org/ns' >
<oc:search>
<oc:pattern>file</oc:pattern>
</oc:search>
</oc:search-files>" | xmllint --format -

```

## Expected behavior
<details>
<summary>There should be a return 404 status code</summary>

```bash
< HTTP/1.1 404 Not Found
. . . 
< 
{ [19 bytes data]
100   200  100    19  100   181    363   3466 --:--:-- --:--:-- --:--:--  3846
* Connection #0 to host localhost left intact
-:1: parser error : Start tag expected, '<' not found
404 page not found
^
```

</details>

## Actual behavior
<details>
<summary>without einstein-personal-space-id in the endpoint</summary>

```
< HTTP/1.1 207 Multi-Status
. . .
<?xml version="1.0"?>
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/spaces/2b17cd6e-5ce0-468c-b474-b382c0f79e30$4c510ada-c86b-4815-8820-42cdf82c3d51/file11.txt</d:href>
    <d:propstat>
      <d:prop>
        <oc:fileid>2b17cd6e-5ce0-468c-b474-b382c0f79e30$4c510ada-c86b-4815-8820-42cdf82c3d51!ac323d5a-8bbe-4362-b481-393024d5a3db</oc:fileid>
        <oc:file-parent>2b17cd6e-5ce0-468c-b474-b382c0f79e30$4c510ada-c86b-4815-8820-42cdf82c3d51!4c510ada-c86b-4815-8820-42cdf82c3d51</oc:file-parent>
        <oc:name>file11.txt</oc:name>
        <d:getlastmodified>2023-08-23T05:55:55Z</d:getlastmodified>
        <d:getcontenttype>text/plain</d:getcontenttype>
        <oc:permissions>RDNVW</oc:permissions>
        <oc:highlights/>
        <oc:tags/>
        <d:getetag/>
        <d:resourcetype/>
        <d:getcontentlength>0</d:getcontentlength>
        <oc:score>1.4402849674224854</oc:score>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

</details>

**Comment by saw-jan** [comment]
I think, this is the expected behavior. Web also makes use of this.

![Screenshot from 2023-09-08 11-55-53](https://github.com/owncloud/ocis/assets/52366632/80ff2a9c-5ae6-4bfe-90ef-73ebd84365e6)


CC @ScharfViktor

**Comment by ScharfViktor** [comment]
> CC @ScharfViktor

Yes, that expected. `-XREPORT https://localhost:9200/dav/spaces/` and `-XREPORT https://localhost:9200/dav/spaces/spaceUUID` behave the same way.
Question: do we need adapt test for that?

**Comment by saw-jan** [comment]
It depends whether we want to have tests with `.../dav/spaces/` or `.../dav/spaces/<personal-space-id>`

**Comment by saw-jan** [comment]
Also, I noticed that there is no difference in using
`.../dav/spaces/<personal-space-id>`
and
`.../dav/spaces/<project-space-id>`
both gives same result.
was it expected? similar issue https://github.com/owncloud/ocis/issues/7096

**Comment by saw-jan** [comment]
> both gives same result.

If using spaces id gives same result then I think we have to refactor it in the tests also.

**Comment by ScharfViktor** [comment]
That is mess  :sob: 
using REPORT `https://localhost:9200/remote.php/dav/spaces/` without spaceUUID seams logic. 
we set location:
- for REPORT request in `body`. 
- for PROPFIND request in `url`. 

so the developers cut off everything beyond `/remote.php/dav/spaces/` in the REPORT request https://github.com/owncloud/ocis/issues/7096

**Comment by ScharfViktor** [comment]
My suggestion: 
accept it as it is and close issue:
- https://github.com/owncloud/ocis/issues/7104
- https://github.com/owncloud/ocis/issues/7096
- https://github.com/owncloud/ocis/issues/7060
- https://github.com/owncloud/ocis/issues/6954

change api test for using REPORT https://localhost:9200/remote.php/dav/spaces/ request without `spaceUUID`
