### ISSUE TITLE
Renaming a received shared folder does not work

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#711]
1. as `einstein` share a folder with `richard`
2. as `richard` accept the folder
3. as `richard` try to rename the received shared folder

expected:
user should be able to rename a received folder

actual:
HTTP code 500 is returned
ocis log:
```
2020-10-16T12:36:53+05:45 ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.2-0.20200924071957-e6676516e61e/internal/grpc/services/storageprovider/storageprovider.go:444 > error moving file error="ocfs: error moving /var/tmp/ocis/owncloud/932b4540-8d16-481e-8ef4-588e4b6b151c/files/Shares/123 to /var/tmp/ocis/owncloud/932b4540-8d16-481e-8ef4-588e4b6b151c/files/Shares/renamed: rename /var/tmp/ocis/owncloud/932b4540-8d16-481e-8ef4-588e4b6b151c/files/Shares/123 /var/tmp/ocis/owncloud/932b4540-8d16-481e-8ef4-588e4b6b151c/files/Shares/renamed: no such file or directory" pkg=rgrpc service=storage traceid=4ea2a5ea20c3da69080cf5f259c62e62
2

**Comment by refs** [comment]
This is not happening anymore, however renaming a shared folder does not rename the original folder. Opening a new ticket for this.

**Comment by phil-davis** [comment]
> This is not happening anymore, however renaming a shared folder does not rename the original folder. Opening a new ticket for this.

The share receiver should be able to rename the folder that they receive. And the original owner (the sharer) should still have the folder with the original name.

Maybe I misunderstand what you wrote, but the original shared folder should not get renamed.

**Comment by refs** [comment]
> > This is not happening anymore, however renaming a shared folder does not rename the original folder. Opening a new ticket for this.
> 
> 
> 
> @refs The share receiver should be able to rename the folder that they receive. And the original owner (the sharer) should still have the folder with the original name.
> 
> 
> 
> Maybe I misunderstand what you wrote, but the original shared folder should not get renamed.

So, are we treating shared folders as copies and not a reference to the original folder?

A good analogy the way I see it is pointer semantics; the current approach treats shared folders as pointers to the original folder, and not something that belongs to the sharee. I think I also don't have oc10 background, and my interpretation might be unfounded 😅.

As I didn't manage to reproduce the original issue report I closed it and made a note to open a new one with my findings.

**Comment by phil-davis** [comment]
> So, are we treating shared folders as copies and not a reference to the original folder?

They are a reference to the original folder. Like a soft-or-hard-link, the sharee (share receiver) can rename that reference to have whatever name they want. It still "points"/"links" to the sharer's files.

If the sharee renames a folder (or file) within the received share, then the sharer sees that change. The sharer and sharee have the same view of all the resources inside the share.

It is just the "top-level" name of the received share that the sharee can rename. IMO the logic of that is that the sharee might receive multiple shares from different people, that happen to have the same (or similar) names. So the sharee can "sort out" their local file system view by renaming received shared folders to names that make more sense to them.

**Comment by refs** [comment]
> > So, are we treating shared folders as copies and not a reference to the original folder?
> 
> They are a reference to the original folder. Like a soft-or-hard-link, the sharee (share receiver) can rename that reference to have whatever name they want. It still "points"/"links" to the sharer's files.
> 
> If the sharee renames a folder (or file) within the received share, then the sharer sees that change. The sharer and sharee have the same view of all the resources inside the share.
> 
> It is just the "top-level" name of the received share that the sharee can rename. IMO the logic of that is that the sharee might receive multiple shares from different people, that happen to have the same (or similar) names. So the sharee can "sort out" their local file system view by renaming received shared folders to names that make more sense to them.

Thanks for clarifying it, it makes sense.

**Comment by individual-it** [comment]
> IMO the logic of that is that the sharee might receive multiple shares from different people, that happen to have the same (or similar) names. So the sharee can "sort out" their local file system view by renaming received shared folders to names that make more sense to them.

It actually has even to happen automatically. If the sharee receives shares with the same name from multiple parties oC10 renames them on the the sharee side by adding a number to it e.g. `Documents (2)`
