### ISSUE TITLE
[search] No response from server while searching inside a folder containing space in name

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#7114]
## Describe the bug
The server response is empty when the file is searched inside a current folder if the parent folder name has `whitespace character` in it.

## Steps to reproduce

1. As user `einstein`, Create a folder `New Folder`
2. Create a file `file1.txt` in the root and inside of `New Folder`
3. Search for the keyword `file` from inside the `New Folder`

## Expected behavior
Must return a list of files.

## Actual behavior

<details><summary>Payload</summary>

```console
<?xml version="1.0"?>
<oc:search-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <oc:permissions />
    <oc:favorite />
    <oc:fileid />
    <oc:file-parent />
    <oc:name />
    <oc:owner-id />
    <oc:owner-display-name />
    <oc:shareid />
    <oc:shareroot />
    <oc:share-types />
    <oc:privatelink />
    <d:getcontentlength />
    <oc:size />
    <d:getlastmodified />
    <d:getetag />
    <d:getcontenttype />
    <d:resourcetype />
    <oc:downloadURL />
    <oc:tags />
  </d:prop>
  <oc:search>
    <oc:pattern>file scope:f42859af-f142-4691-97e2-9ba377d61acd$4c510ada-c86b-4815-8820-42cdf82c3d51/New folder</oc:pattern>
    <oc:limit>8</oc:limit>
  </oc:search>
</oc:search-files>
```
</details>

<details><summary>Response</summary>

```console
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"></d:multistatus>
```
</details>

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

```console
OCIS_version= 3.1.0-rc.1, 4.0.0-rc.1
```

**Comment by individual-it** [comment]
@grgprarup is the problem if the name contains the string `"space"` or if the name contains a space character `" "`?

**Comment by grgprarup** [comment]
> @grgprarup is the problem if the name contains the string `"space"` or if the name contains a space character `" "`?

its the space character " ", e.g. `New Folder`, `Sample Folder`

**Comment by hodyroff** [comment]
It seems that when I switch to "all folders" it works. Therefor easy workaround, not a blocker.
To be fixed ASAP.

**Comment by fschade** [comment]
```<oc:pattern>aa scope:44df7993-16c0-4159-a6de-6f5aacb4dc50$9959421d-a0e9-4013-bbb8-7f0f539923b7/Neuer Ordner</oc:pattern>```

`scope` looks fishy to me, i have a look

**Comment by fschade** [comment]
cc: @2403905 looks like a scope issue, should I check or do you take over

**Comment by fschade** [comment]
its the whitespace character: 

```
Entry("When scope contains whitespace",
  `scope:<uuid>/new folder/subfolder file`,
  `file`,
  `<uuid>/new folder/subfolder`,
),
```

regex: ``scope:\s*([^" "\n\r]*)``

it cannot handle the whitespace...

**Comment by dj4oC** [comment]
IMHO annoying bug but no release blocker

**Comment by fschade** [comment]
will be fixed in the next release, i take this as a test item for the kql story, we have to quote it!

**Comment by grgprarup** [comment]
Test Coverage:
- [ ] Add examples in the test for these case
- [ ] Check for other cases as well

**Comment by ScharfViktor** [comment]
I guess the issue can be closed. 

using resourceID in `scope` solved issue 

before: `<oc:pattern>file scope:f42859af-f142-4691-97e2-9ba377d61acd$4c510ada-c86b-4815-8820-42cdf82c3d51/New folder</oc:pattern>`
   
now: `<oc:pattern>name:&quot;*file*&quot; scope:e49de8ab-e3c5-43dc-b83e-6337e680ae7c$96a25d9d-e174-4af1-90d1-e94c8a165401!9a1c05ac-0956-4592-86db-79d8ae311010</oc:pattern>`
