### ISSUE TITLE
REVA_GATEWAY has been missed from removal process

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#7124]
Needs removal in master ~and "updating" the adoc output in the `docs-stable-4.0` branch because it had a wrong removal version and was therefore not catched~ 😢 

![image](https://github.com/owncloud/ocis/assets/3321281/8986b1aa-eee7-4a85-9fb3-72a11d5eba78)

@dragonchaser pls fix in master

~I will "update" the docs branch manually~

**Comment by micbar** [comment]
> I will "update" the docs branch manually

please don't

The stable `docs-stable-4.0` depends on the CI of the `stable-4.0` branch. Needs to be fixed on the `stable-4.0` branch.

**Comment by mmattel** [comment]
hmmm, there is only a `docs-stable-4.0` but no `stable-4.0` branch...

Which might also explain why other stuff is additionally present in the tables that was fixed before. Seems that the `docs-stable-4.0` was based on `docs-stable-3.0`.

Maybe to remove that bad `docs-stable-4.0` branch and create a new one based on master.
Then we have the stuff clean and fixed.

I have seen you message too late, but that does not matter. When recreated we get correct data. At least it has shown that when changed, the content rendered locally looks correct 😅 

* We either should wait for the fix in master and then create `stable-4.0` or
* create as soon as possible `stable-4.0` and manually backport the upcoming changes from master with regards to the deprecation.

Finally, we need more internal documentation for that process `stable-4.0` --> `docs-stable-4.0`

**Comment by mmattel** [comment]
@micbar just for my info: if we push a commit to a `stable-x.y` branch:

* can we create a PR from it and does a merge trigger the pipeline creating the relevant .adoc files, or
* do we need to adapt the adoc files in the branch directly?

We should also document this somewhere in case a fix in the adoc files is needed. By accident, we have in 3.0 stated for the above envvar that depreaction version is 3.1 which should be corrected.

**Comment by dragonchaser** [comment]
I can not find this in the code, could this be manually added? `git grep REVA_GATEWAY` just gives me an occurrence in a docker-compose we have missed.......

**Comment by mmattel** [comment]
Note, post a discussion with @dragonchaser, this is not a code, but a branching issue. When branching has been done correectly and the reusult got checked, we can close this issue.

**Comment by mmattel** [comment]
I am closing this issue - solved.
* the `stable-4.0` got created
* the `docs-stable-4.0` got updated based on `stable-4.0`
* the wrong remaining deprecation-version 3.1 on some envvars got updated in `stable-3.0` --> `docs-stable-3.0`
