### ISSUE TITLE
Accepting different shares with same filename from different users overwrites one file

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#713]
### Steps to reproduce
1. As Einstein share `simple-folder` to Marie
2. As Richard share `simple-folder` to Marie
3. As Marie accept both shares and browse to Shares folder

### expected Result
1. Both `smple-folder` and `simple-folder (2)` should exist

### Result
1. The share accepted later will overwrite the share accepted first. So only `simple-folder` is listed in the webUI.

**Comment by refs** [comment]
it still happens [with the current master](https://github.com/owncloud/ocis/commit/8fa89f50676d065fc469ccb780037135a29639f4)

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0

Result: the first accept of the file is successful
the second - unsuccessful. `500 Internal Server Error` it is not possible to accept a second folder with the same name
<img width="1427" alt="Screenshot 2021-09-01 at 16 13 00" src="https://user-images.githubusercontent.com/84779829/131688305-85d7a9da-4716-4be2-9845-3605fb1778cb.png">

**Comment by ScharfViktor** [comment]
there is a similar task https://github.com/owncloud/ocis/issues/2131, so I close it
