### ISSUE TITLE
move search related feature files to api search suites

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7135]
There is need to move search-related fetaure files to the single suites `apiFullTextSearch` and rename them if required.
It will contribute to taking less CI time for other suites than before.
The files need to move:
- `acceptance/features/apiGraph/fullSearch.feature`
-  `acceptance/features/apiSpaces/search.feature`

**Comment by saw-jan** [comment]
Done in https://github.com/owncloud/ocis/pull/7139
