### ISSUE TITLE
NATS registry not distributing load

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#7188]
## Describe the bug

When using the NATS service registry, load is not distributed correctly

## Steps to reproduce

1. run oCIS in Kubernetes with multiple replicas / autoscaling
2. apply load with K6
3. look at different service instances' CPU  / RAM load

## Expected behavior
Load distributes almost evenly. New service instances get a share of the requests

## Actual behavior
Not all service instances receive requests / have load

## Additional context

@butonic could you please add some of your findings to this ticket?

**Comment by wkloucek** [comment]
will be supersed if https://github.com/owncloud/ocis/issues/7272 is implemented

**Comment by dj4oC** [comment]
@tbsbdr please schedule

**Comment by tbsbdr** [comment]
@dj4oC in progress, see https://github.com/owncloud/ocis/issues/7272

**Comment by wkloucek** [comment]
This was about the `natsjs` registry and not about the `nats-js-kv` registry available now. I guess loadtests for `nats-js-kv` are still pending
