### ISSUE TITLE
share receiver gets ERROR 500 on any PROPFIND after the sharer deletes the collaborator 

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#720]
1. as `einstein` share a folder to `richard`
1. as `richard` accept the share
1. as `einstein` stop sharing the folder
1. as `richard` check `Shared with me` => no share can be seen
1. as `richard` check the `Shares` folder => the share can still be accessed

**Comment by individual-it** [comment]
the bug got worse, after `einstein` stops sharing to `richard`, `richard` receives HTTP 500 when trying to PROPFIND any files/folders

**Comment by micbar** [comment]
@butonic JFYI
