### ISSUE TITLE
Deleting share response does not contain `data` field

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#721]
delete a share response in oc10:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message/>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

delete a share response on OCIS:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>ok</status><statuscode>100</statuscode><message>OK</message></meta></ocs>
```

**Comment by refs** [comment]
happens [on the current master](https://github.com/owncloud/ocis/commit/8fa89f50676d065fc469ccb780037135a29639f4)

**Comment by individual-it** [comment]
Then it looks like it was changed in oc10. Need to see if the case is covered by tests

- [ ] ToDo QA:team double-check if there are API tests for that case

**Comment by phil-davis** [comment]
Should be fixed by https://github.com/cs3org/reva/pull/2054
