### ISSUE TITLE
Upload-only public link does not refer to files-drop page, nor are the permissions enforced

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#723]
1. in the webUI create a public link with "Uploader" role
2. copy the URL
3. paste the URL into the browser address

Result: content of the folder is listed and the user has full access

The only way to get to the drop files is to replace `public-files` in the final URL with `files-drop`

In the case of a password protected link even that does not work. After entering the password the user is always referred to the normal public-files page

**Comment by dpakach** [comment]
Might be related to https://github.com/owncloud/ocis-reva/issues/292

**Comment by refs** [comment]
Can this be retested since https://github.com/cs3org/reva/pull/1368/ got merged?

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: retest, check if there are automated tests, if not add UI tests
