### ISSUE TITLE
Favourite a received share or any item in a share is impossible

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#724]
1. as `einstein` create a folder with a file as content
2. as `einstein` share that folder with `richard`
3. as `richard` accept the share
4. as `richard` try to favourite the file inside the received folder `curl -v -k -u richard:superfluidity -X PROPPATCH https://localhost:9200/remote.php/webdav/Shares/f1/english.png -d '<?xml version="1.0"?><d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"> <d:set><d:prop><oc:favorite xmlns:oc="http://owncloud.org/ns">1</oc:favorite></d:prop></d:set></d:propertyupdate>'`

Result: `HTTP/1.1 404 Not Found `

ocis logs: 
```
2020-10-21T15:53:09+05:45 WRN resource not found path=/home/Shares/f1/english.png pkg=rhttp service=storage traceid=ff5dde45d2697a8b5c5dc82c7380983c
2020-10-21T15:53:09+05:45 WRN http end="21/Oct/2020:15:53:09 +0545" host=127.0.0.1 method=PROPPATCH pkg=rhttp proto=HTTP/1.1 service=storage size=0 start="21/Oct/2020:15:53:09 +0545" status=404 time_ns=365185929 traceid=ff5dde45d2697a8b5c5dc82c7380983c uri=/remote.php/webdav/Shares/f1/english.png url=/remote.php/webdav/Shares/f1/english.png

**Comment by refs** [comment]
Perhaps because favorites are not yet implemented? @butonic is working on it right now, perhaps back-reference this issue in your PR?

**Comment by refs** [comment]
possible duplicate of https://github.com/owncloud/ocis/issues/724 ?

**Comment by individual-it** [comment]
@refs this IS `724` ;-)

**Comment by refs** [comment]
grrrrr, wrong one. Let me fix it. Thanks for the heads up.

**Comment by refs** [comment]
> @refs this IS `724` ;-)

fixed. I was referring to #1228

**Comment by individual-it** [comment]
This is only about files in received shares and it seems only to happen on owncloud storage not on ocis storage

**Comment by refs** [comment]
thanks! labeling as storage:oc and moving on. We need to decide at some point what to do with all the storage:oc issues, and if the OC Storage will survive at all

**Comment by individual-it** [comment]
closing in favour of  #1228
