### ISSUE TITLE
[QA] add API tests for auto accepting shares (`FRONTEND_AUTO_ACCEPT_SHARES`)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#7241]
PR https://github.com/owncloud/ocis/pull/7097 has added the capability to auto-accept the shares when configured.

Add API tests for this feature. (add tests for various scenarios)
- enable auto-accept shares via env config: `FRONTEND_AUTO_ACCEPT_SHARES=true` (enables for all)
- enable/disable auto-accept shares per user

**Comment by saw-jan** [comment]
>According to story auto-accept should be true by default, but test pipeline cannot handle this for now

@kobergj, if it's required to be enabled by default in oCIS then maybe enable it by default and run tests with `FRONTEND_AUTO_ACCEPT_SHARES=false` for now, the later we can fix the tests and remove `FRONTEND_AUTO_ACCEPT_SHARES=false`. And we add some test scenarios with `FRONTEND_AUTO_ACCEPT_SHARES=false`.

**Comment by ScharfViktor** [comment]
closed as comleted https://github.com/owncloud/ocis/pull/7477
