### ISSUE TITLE
folder name not rename for sharee when sharer rename the folder

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7260]
## Describe the bug

When sharer renamed the share folder then the folder name is not renamed for sharee. Due to this, there is also difficult to search for sharee to search the folder by name

## Steps to reproduce

1. As `marie`, create a folder `folder1`
2. As `marie`, share a folder to `einstein`
3. As `einstein`, accept the share
4. As `marie`, rename folder `folder1` to `folder2`

## Expected behavior
The folder should be renamed

for sharer `marie`

![image](https://github.com/owncloud/ocis/assets/61624650/81f7c00b-4058-46a0-bf7a-6a6d3e6d31de)

for sharee `einstein`
![image](https://github.com/owncloud/ocis/assets/61624650/8cbda625-e267-4e0f-94a9-80f6757f62e1)

## Actual behavior
The folder is not renamed for sharee

for sharer `marie`
![image](https://github.com/owncloud/ocis/assets/61624650/8711e0ed-f309-45b2-af4f-d21cb07b43b1)

for sharee `einstein`
![image](https://github.com/owncloud/ocis/assets/61624650/5be08a98-e044-4a94-a7aa-f2b777c26f53)

**Comment by phil-davis** [comment]
The screen shots show folders called `folders` and `folder`, but the test description of the steps to reproduce has `folder` and `folder1` - that makes it confusing to understand the issue.

Also, the Actual Behavior section has the text "The response contains resource named folder in the response"
IMO it should say "The response **does not contain** resource named folder in the response"

**Comment by nabim777** [comment]
> The screen shots show folders called `folders` and `folder`, but the test description of the steps to reproduce has `folder` and `folder1` - that makes it confusing to understand the issue.
> 
> Also, the Actual Behavior section has the text "The response contains resource named folder in the response" IMO it should say "The response **does not contain** resource named folder in the response"

oh sorry for that mistake. I've updated

**Comment by saw-jan** [comment]
AFAIK, the behavior where the resource **(accepted share)** doesn't get renamed in the sharee side is expected.

CC  @ScharfViktor

**Comment by phil-davis** [comment]
Now the issue describes what is known expected behavior. When a sharer renames a resource, a sharee who has already received the resource still sees it with its original name. This is the way "the system" is expected to work. A sharee can also renme a received resource, and the sharee is the only user that sees the changed name.

I think that this issue is supposed to be about searching?

**Comment by ScharfViktor** [comment]
the behavior is expected. same issue https://github.com/owncloud/ocis/issues/6376

**Comment by saw-jan** [comment]
Then I will close this here. @nabim777 open another issue that is related to REPORT

**Comment by nabim777** [comment]
> Then I will close this here. @nabim777 open another issue that is related to REPORT

Here is related to REPORT https://github.com/owncloud/ocis/issues/7262
