### ISSUE TITLE
ocis build gmake  generate error

### ISSUE THREAD

**Issue by jostreff** [owncloud/ocis#7283]
#pnpm lint #TODO: activate
#pnpm test #TODO: activate
pnpm build

> identifier@1.0.0 build /usr/home/jostreff/ocis/services/idp
> node scripts/build.js && rm -f build/service-worker.js

Creating an optimized production build...
Failed to compile.

./src/i18n.ts
You attempted to import /usr/home/jostreff/ocis/services/idp/node_modules/.pnpm/@babel+runtime@7.18.6/node_modules/@babel/runtime/helpers/esm/toConsumableArray.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

 ELIFECYCLE  Command failed with exit code 1.
gmake[1]: *** [Makefile:57: pnpm-build] Грешка 1
gmake[1]: излизане от директория „/usr/home/jostreff/ocis/services/idp“

**Comment by kobergj** [comment]
Can you elaborate what you did to run into this problem? What command did you run? Why did you run this command? Did you do changes to the source code? Which version are you using?

**Comment by ScharfViktor** [comment]
please reopen if it's still relevant.
