### ISSUE TITLE
Use built-in NATS service in the single process deployment

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#7296]
# User Story

Make it possible to use the shipped NATS service in the single process.

## Acceptance criteria

- [x] Default config uses the shippped nats for registry / cache / stores
- [x] The startup process is "graceful enough" to accept that the NATS service need some startup time.

**Comment by wkloucek** [comment]
Registry default is now `nats-js-kv`: https://github.com/owncloud/ocis/pull/8011

> Default config uses the shippped nats for registry / cache / stores

Cache and store switch missing? @micbar @kobergj

**Comment by kobergj** [comment]
caches and stores are also running on nats-js-kv now. Only nats authentication is open.

**Comment by wkloucek** [comment]
> caches and stores are also running on nats-js-kv now

Should we close then? Seems like all acceptance criteria are fulfilled of this ticket
