### ISSUE TITLE
deleting a received share is not possible

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#730]
1. as `einstein` share a folder to `richard`
2. as `richard` accept the offered share
3. as `richard` try to delete the share from shared-with-me page or from inside `/Shares`

both DELETE requests fail with 404, in oc10 those requests unshare the folder

**Comment by dpakach** [comment]
Also tracked here https://github.com/owncloud/ocis/issues/714

**Comment by dpakach** [comment]
Closing in favour of #714
