### ISSUE TITLE
Sonarcloud reports errors

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#7301]
In current builds. Example: https://drone.owncloud.com/owncloud/ocis/26650/46/4

```bash
INFO: Importing /drone/src/cache/checkstyle/proxy_checkstyle.xml
ERROR: No issue information will be saved as the report file '/drone/src/cache/checkstyle/proxy_checkstyle.xml' can't be read.
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.path" is null
	at org.sonar.api.batch.fs.internal.predicates.AbsolutePathPredicate.apply(AbsolutePathPredicate.java:32)
	at org.sonar.api.batch.fs.internal.predicates.OrPredicate.apply(OrPredicate.java:46)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800)
	at 

ERROR: No issue information will be saved as the report file '/drone/src/cache/checkstyle/webdav_checkstyle.xml' can't be read.
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.path" is null
	at org.sonar.api.batch.fs.internal.predicates.AbsolutePathPredicate.apply(AbsolutePathPredicate.java:32)
	at org.sonar.api.batch.fs.internal.predicates.OrPredicate.apply(OrPredicate.java:46)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800)
```

Effect: PRs don't get :heavy_check_mark: 

![Screenshot from 2023-09-19 10-02-11](https://github.com/owncloud/ocis/assets/52366632/76285219-c4d6-4d41-81e7-20af55573e14)

CC @ScharfViktor

**Comment by rhafer** [comment]
> ```shell
> ERROR: No issue information will be saved as the report file '/drone/src/cache/checkstyle/webdav_checkstyle.xml' can't be read.
> java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.path" is null
> 	at org.sonar.api.batch.fs.internal.predicates.AbsolutePathPredicate.apply(AbsolutePathPredicate.java:32)
> 	at org.sonar.api.batch.fs.internal.predicates.OrPredicate.apply(OrPredicate.java:46)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
> 	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800)
> ```
> 
> Effect: PRs don't get ✔️

I am not sure if the above error really is the problem. AFAICS the sonarcloud reports go get submitted properly.
E.g. from https://github.com/owncloud/ocis/pull/7313 (https://drone.owncloud.com/owncloud/ocis/26685/46/4)

```
INFO: ANALYSIS SUCCESSFUL, you can find the results at: https://sonarcloud.io/dashboard?id=owncloud_ocis&pullRequest=7313
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at https://sonarcloud.io/api/ce/task?id=AYqt-lZoEGrrLNqonflR
INFO: Time spent writing ucfgs 0ms
INFO: Analysis total time: 28.374 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 33.435s
INFO: Final Memory: 48M/188M
INFO: ------------------------------------------------------------------------
```

And looking at https://sonarcloud.io/dashboard?id=owncloud_ocis&pullRequest=7313 you see it `Passed`. This seems to be a general sonarcloud issue. See e.g. https://community.sonarsource.com/t/github-integration-pull-request-status-not-beeing-displayed/99487/1 (though according to that the issue should be resolved now, needs rebuilds though...)

cc @micbar

**Comment by rhafer** [comment]
Seems to work again now see e.g.  https://github.com/owncloud/ocis/pull/7313
