### ISSUE TITLE
[QA] naming of security settings is negative

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#7314]
Seen in ocis 4.0.0 and before

We currently have an environment variable OCIS_INSECURE which needs to be set to false, when securing the ssl connection with a certificate.
We also have a init option `--inscecure` to allow an unencrypted internal communication between proxy and ocis.

I suggest to instead use a variable `OCIS_SECURE=true`
and an init option `--trusted-network` or similar.

@hodyroff @tbsbdr does this cover, what we just discussed?

**Comment by micbar** [comment]
@jnweiger thanks for the feedback.

I agree with the general idea, BUT: just renaming a crucial variable and going through all the deprecation process just to make it "nicer" is IMO questionable.

**Comment by rhafer** [comment]
> We currently have an environment variable OCIS_INSECURE which needs to be set to false, when securing the ssl connection with a certificate.

Just to be clear: OCIS_INSECURE does not need to be set at all, when using a valid certificate (it defaults to `false`). The `secure` behavior is the default (if that is not the case, there's a bug somewhere that we need to fix).
So the `insecure` behavior has to be explicitly requested by the user. I don't see anything wrong with also naming that option `insecure` then.

Also, requiring the user to explicitly set `INSECURE`/ `insecure` to disable certificate verification is AFAICT a pretty  broadly established practice and used in a ton of other projects.

**Comment by mmattel** [comment]
Only if we are going to address this, we could, to relax any deprecation needs, add a global envvar named: `OCIS_SECURE` with inverse behaviour _in parallel_ to `OCIS_INSECURE`. The rest is a docs issue.

**Comment by micbar** [comment]
i agree with @rhafer 

Naming is clear.

**Comment by Vogeluff** [comment]
> > We currently have an environment variable OCIS_INSECURE which needs to be set to false, when securing the ssl connection with a certificate.
> 
> Just to be clear: OCIS_INSECURE does not need to be set at all, when using a valid certificate (it defaults to `false`). The `secure` behavior is the default (if that is not the case, there's a bug somewhere that we need to fix). So the `insecure` behavior has to be explicitly requested by the user. I don't see anything wrong with also naming that option `insecure` then.
> 
> Also, requiring the user to explicitly set `INSECURE`/ `insecure` to disable certificate verification is AFAICT a pretty broadly established practice and used in a ton of other projects.

i know this is old but i just set up owncloud infinite scale and removed the OCIS_INSECURE: false from my docker compose file because of your comment but if i do that i get a spam about not doing that in a production version or something similar and it stops working through my reverse proxy. so i added that line back in and it works again. was just wondering why that is, since your comment made me think if its not present it defaults to false anyways...
