### ISSUE TITLE
Duplication of docs https://owncloud.dev/

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7323]
we have some duplication in the dev docs

example
- https://owncloud.dev/clients/web/docs/testing/testing/ - old page. is no longer updated
- https://owncloud.dev/clients/web/testing/testing/ - actual page. CI automatically generates this page

![Screenshot 2023-09-21 at 11 02 53](https://github.com/owncloud/ocis/assets/84779829/fd383ef0-d6e5-4d71-b7a1-905f2cd4b4c4)

same situation: 
- https://owncloud.dev/extensions/ocis_hello/
- https://owncloud.dev/extensions/ocis_hello/hello/

- https://owncloud.dev/integration/file_picker/
- https://owncloud.dev/integration/file_picker/docs/

need somehow delete duplication. as solution can suggest to drop old documentation from `docs` branch https://github.com/owncloud/web/blob/docs/docs/testing/testing.md

@micbar can I delete old docs pages or we have another way?

**Comment by micbar** [comment]
@ScharfViktor yes, please do the cleanup.

**Comment by micbar** [comment]
Web Repo https://github.com/owncloud/web/pull/9770

**Comment by ScharfViktor** [comment]
docs looks better :thumbsup: 

only this double links still exist: 
https://owncloud.dev/extensions/ocis_hello/
https://owncloud.dev/extensions/ocis_hello/hello/


need fix in the https://github.com/owncloud/web-extensions ?  if yes, do please because I haven't access

**Comment by micbar** [comment]
Fix for ocis hello https://github.com/owncloud/ocis-hello/pull/147

**Comment by ScharfViktor** [comment]
awesome
