### ISSUE TITLE
Autodetect SMTP auth methods

### ISSUE THREAD

**Issue by xoxys** [owncloud/ocis#7356]
## Is your feature request related to a problem? Please describe.

It's required to explicitly set `NOTIFICATIONS_SMTP_AUTHENTICATION` on most production systems, as the default is set to `none`. This is not optimal, especially as the used mail library supports auto-detection of the supported auth methods of the server.

https://github.com/xhit/go-simple-mail/blob/v2.16.0/email.go#L152

You might want to add some more sanitizing in the same step to avoid issues. For example, what happens if username + password are provided, but auth is not supported by the server. Example https://github.com/go-gitea/gitea/blob/main/services/mailer/mailer.go#L259

Auth/security related options shouldn't fail silently.

## Describe the solution you'd like

Switch to `NOTIFICATIONS_SMTP_AUTHENTICATION=auto` as default.

**Comment by rhafer** [comment]
Hm, NOTIFICATIONS_SMTP_ENCRYPTION also defaults to `none`. Which IMO is a really bad default as well.

**Comment by xoxys** [comment]
But it's hard to guess and depends on the port. Also, common in other projects that it must be set.

**Comment by xoxys** [comment]
If you want to touch this part, you might want to take https://github.com/owncloud/ocis/issues/7345 into account as well.

**Comment by rhafer** [comment]
> But it's hard to guess and depends on the port.

True, IMO  the defaults should be either:
- port=465 and encryption=ssltls
- port=587 and encryption=starttls

or

- no defaults at all 

I am leaning towards the last options. Simply because we're already using an empty default for the host.

Or current defaults (port=1025 and encryption=none) don't make any sense IMO.
