### ISSUE TITLE
Disable DEPTH:infinity in PROPFIND is only applicable to dav/spaces path

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#7359]
## Describe the bug
It is possible to do PROPFIND request with `Depth: infinity` header using old (`/webdav`) and new (`/dav/files`) endpoints in the oCIS server started with default configs (mainly disable depth:infinity).

But the same request using `spaces` endpoint gives expected error message.

## Steps to reproduce
1. Start oCIS server with default configs (that has `OCDAV_ALLOW_PROPFIND_DEPTH_INFINITY=false`)
    ```bash
    PROXY_ENABLE_BASIC_AUTH=true \
    OCIS_ASYNC_UPLOADS=true \
    ./ocis/bin/ocis server
    ```
1. Add some nested folders/files
2. Do PROPFIND request using `old`/`new` dav paths with `Depth: infinity` (Possible - :question:)
    ```bash
    curl -XPROPFIND "https://localhost:9200/remote.php/dav/files/admin" -uadmin:admin -H"Depth: infinity" -vk
    ```

    <details>
    <summary>Response</summary>

    ```xml
    <?xml version="1.0"?>
    <d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
      <d:response>
        <d:href>/remote.php/dav/files/admin/</d:href>
        <d:propstat>
          <d:prop>
            ...
          </d:prop>
          <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
      </d:response>
      <d:response>
        <d:href>/remote.php/dav/files/admin/New%20folder/</d:href>
        <d:propstat>
          <d:prop>
            ...
          </d:prop>
          <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
      </d:response>
      <d:response>
        <d:href>/remote.php/dav/files/admin/New%20folder/file.txt</d:href>
        <d:propstat>
          <d:prop>
            ...
          </d:prop>
          <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
      </d:response>
      <d:response>
        <d:href>/remote.php/dav/files/admin/Shares/</d:href>
        <d:propstat>
          <d:prop>
            ...
          </d:prop>
          <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
          <d:prop>
            <oc:file-parent/>
          </d:prop>
          <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
      </d:response>
    </d:multistatus>
    ```
    </details>
4. Do PROPFIND request using `spaces` dav path with `Depth: infinity` (Error)
    ```bash
    curl -XPROPFIND "https://localhost:9200/remote.php/dav/spaces/<personal-space-id>" -uadmin:admin -H"Depth: infinity" -vk
    ```
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
      <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
      <s:message>Invalid Depth header value: infinity</s:message>
    </d:error>
    ```

NOTE: other endpoints unaffected by `OCDAV_ALLOW_PROPFIND_DEPTH_INFINITY` are:
- Public link share `/remote.php/dav/public-files/<token>`
- Trashbin `/remote.php/dav/spaces/trash-bin/<personal-space-id>`

## Expected behavior
all endpoints yield same response

## Actual behavior
disable depth:infinity work for spaces but not for old/new dav paths

**Comment by micbar** [comment]
@case0sh @kobergj This could be a candidate.

**Comment by 2403905** [comment]
@saw-jan I made the PR and a lot of tests failed. Please take a look if it is expected.

**Comment by 2403905** [comment]
@saw-jan fix already merged.
