### ISSUE TITLE
Concurrent shares test

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7363]
after discussing about test concurrent shares here https://confluence.owncloud.com/pages/viewpage.action?pageId=58296733

Step1: 
we want to have e2e test: 
- [x] multiple sharing https://github.com/owncloud/web/pull/9734
- [x] multiple accepting https://github.com/owncloud/web/pull/9734
- [x] moving and copying https://github.com/owncloud/web/pull/9895

Step2: 
- [ ] deploying one ocis & 2 storage user services
- [ ] e2e test agains new deployment during the release process
- [ ] using CI (Separate issue https://github.com/owncloud/ocis/issues/7614)

**Comment by saw-jan** [comment]
Similar to https://github.com/owncloud/QA/issues/828 but in API level

**Comment by ScharfViktor** [comment]
step 2 will be implement in the[ #7614](https://github.com/owncloud/ocis/issues/7614)
