### ISSUE TITLE
Starlark file not compiling on starlark

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#738]
Running:

```
drone starlark .drone.star
2020/10/22 15:29:44 starlark evaluation error:
Traceback (most recent call last):
  .drone.star:121:33: in main
Error: "build" struct has no .title attribute
```

causes Starlark compilation to fail. The offending line is:

`if '[docs-only]' in (ctx.build.title + ctx.build.message):`

**Comment by refs** [comment]
cc @micbar, low hanging fruit

**Comment by micbar** [comment]
I have it
Check out https://github.com/drone/drone-cli/pull/175 and build locally

**Comment by refs** [comment]
ahá, let's still use the issue here as anchor?

**Comment by refs** [comment]
even if https://github.com/drone/drone-cli/pull/175 is merged, leaving it open until we update to a new drone release, if that happens at all
