### ISSUE TITLE
Random failure in Core-API-Tests-ocis-storage-6

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#739]
This pipeline was red: https://drone.owncloud.com/owncloud/ocis/884/27/7
Reason: 
```
\| new         \| ",,,.txt"      \|
--
2144 | HTTP status code was not 201 or 204 while trying to upload file '/welcome.txt' for user 'Alice'
2145 | Failed asserting that an array contains 401.
```

A restarted version of the same code had the same pipeline green: https://drone.owncloud.com/owncloud/ocis/888/27/7

Needs investigation.

**Comment by saw-jan** [comment]
@kulmann ran the related tests numerous time locally still, no fails
