### ISSUE TITLE
Ocis vs ldap. No check for the same user and group uuid

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7390]
Steps:
- start ocis with ldap using https://github.com/owncloud/ocis/blob/stable-4.0/deployments/examples/ocis_ldap/docker-compose.yml
- go to the https://ldap.owncloud.test and copy richard user (new user has same UUID)
- copy `users` group (new group has same UUID)

Actual: it is possible 
Expected: not possible to create users or group with same UUID

sharing and login for new user doesn't work:

- open ocis and try to share to new user or group
<img width="1140" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/a97521bb-ab91-4cad-935e-0babc844a596">

- try to login as new user 
![image](https://github.com/owncloud/ocis/assets/84779829/8370048f-303c-400e-ac2d-5c87d8a60685)

`2023-09-29 16:39:07 {"level":"error","service":"idp","error":"ldap identifier backend get user connect error: LDAP Result Code 200 \"Network Error\": dial tcp: lookup ldap-server: operation was canceled","time":"2023-09-29T14:39:07.221281555Z","line":"github.com/owncloud/ocis/v2/ocis-pkg/log/logrus_wrapper.go:50","message":"IdentifierIdentityManager: fetch failed to get user from userID"}
2023-09-29 16:39:07 {"level":"error","service":"idp","error":"ldap identifier backend get user error: LDAP Result Code 4 \"Size Limit Exceeded\": ","time":"2023-09-29T14:39:07.22989443Z","line":"github.com/owncloud/ocis/v2/ocis-pkg/log/logrus_wrapper.go:50","message":"IdentifierIdentityManager: fetch failed to get user from userID"}`

**Comment by rhafer** [comment]
> * go to the https://ldap.owncloud.test and copy richard user (new user has same UUID)
> 
> * copy `users` group (new group has same UUID)

@ScharfViktor You're copying the user and group using some generic LDAP client (e.g. php-ldapadmin) I assume?. In that case there is not much more we (ocis) can to against that than preventing a login with a non-unique userid. The LDAP server is basically an external database. If there is garbage in there (like e.g. duplicated UUID) the only useful with we can do is to error out. 

> Expected: not possible to create users or group with same UUID

As you didn't create the user from ocis (using the graph API). How should we prevent you from shooting yourself in the foot here?

**Comment by ScharfViktor** [comment]
Yes, you're right. bug is not related `ocis`, so I close it
