### ISSUE TITLE
Master branch is broken?

### ISSUE THREAD

**Issue by isbm** [owncloud/ocis#7391]
After cloning the repo, `make generate` results into this:

```
Progress: resolved 1477, reused 1477, downloaded 0, added 1477, done
node_modules/.pnpm/core-js-pure@3.32.1/node_modules/core-js-pure: Running postinstall script...
node_modules/.pnpm/core-js@3.32.1/node_modules/core-js: Running postinstall script...
 ELIFECYCLE  Command failed.
make[1]: *** [Makefile:61: node_modules] Error 1
```

While ocis builds/compiles, it still can't start the server, since some HTML files not found. Any quickfix for this?

Ubuntu 22.04 LTS, build-essentials, pnpm etc is there. Go 1.21

**Comment by isbm** [comment]
After fiddling a bit with no idea how Node.js works 😆, it turns out that the documentation is incomplete. The missing parts:

- Installing `pnpm` alone is not enough, Node.js needs to be installed as well.
- Installing _any_ Node.js is also not enough. Ubuntu 22.04 provides version v12.22.9, which is too old. There are several ways how to update it, but maybe the best one is here: https://deb.nodesource.com

After this, build is sort of ends (ignoring all the warnings while generating protos). However, `ocis` still does not work, because even though the configuration was initialised as "insecure" (no SSL checks), nothing really happens in the browser, because of this (message repeats 25 times with different port:

```
2023/10/01 13:01:18 http: TLS handshake error from 192.168.122.1:33674: remote error: tls: unknown certificate
...
```

**Comment by kobergj** [comment]
Thanks for finding this, we will update our documentation :+1:

Regarding your problem: Can you try starting ocis with enviroment variable `OCIS_INSECURE=true`?

**Comment by isbm** [comment]
@kobergj 
thanks to the reply, actually I called `ocis init` so it generates `./ocis/config/ocis.yaml` where `tls_insecure` is always set to `true`. Looking at the code, if I understand it correctly, it is loading default configuration for each component, and then the parser supposed to bind other parts of the config to the structs, overriding the values.

But seems this does not happen. So I dumped the configuration object for each service right before HTTP server starts and it looks that it is always set to false: `TLSInsecure: (bool) false`.

For example:
```
 Events: (config.Events) {
   Endpoint: (string) (len=14) "127.0.0.1:9233",
   Cluster: (string) (len=12) "ocis-cluster",
   TLSInsecure: (bool) false,
   ^^^^^^^^^^^
   TLSRootCACertificate: (string) "",
   EnableTLS: (bool) false
  },
```

As you can see, the env variable does not even affects it. The configuration itself is explicitly generated (initialised) with TLS set to be insecure. I double-checked, and seems that `./ocis/config/ocis.yaml` is picked up properly (otherwise ocis fails to start if I remove it at all, asking to init the config). However, `tls_insecure: true` seems to be completely ignored.

What else I could try?

**Comment by kobergj** [comment]
Mmh. I cannot reproduce, the envvar is picked up correctly for me. But it anyways doesn't matter because in your case `EnableTLS` is set to false also. 

But maybe the `insecure` option is not passed everywhere correctly when loaded from the `ocis.yaml`. Do you have the same problem when setting the envvar explicitly?

**Comment by isbm** [comment]
OK, maybe because I am actually building it directly on a fresh VM. 😉 So my scenario:
- git clone
- cd ocis
- make....

Ubuntu 22.04 LTS, requirements I update as in my original message above. Then I run `ocis` and then it fails like that. Are you sure your environment is not "contaminated" with long-lasting fixes? Have you tried to reproduce it on a completely fresh VM with a minimal server setup? Because for me this is always reproducible, if I follow the existing documentation. Looks like either our envs are different and/or I am missing some steps while building it. At the end I end up with a forever spinner in a browser and lots of TLS errors.

NOTE: no containers involved.

**Comment by kobergj** [comment]
Yes I understand. I think the problem is that `OCIS_INSECURE` does more than only set `Events.TLSInsecure`. But when I run ocis init it will only set the `insecure` option for event related features.  That is why it is important to also run the binary with `OCIS_INSECURE=true`. That is also what the (e.g.) systemd documentation recommends: https://doc.owncloud.com/ocis/next/deployment/binary/binary-setup.html#setting-up-systemd-for-infinite-scale

Can you try setting the envvar when starting ocis?

**Comment by isbm** [comment]
```
$ export OCIS_INSECURE=true
$ export OCIS_URL=https://localhost:9200
$ export PROXY_HTTP_ADDR=0.0.0.0:9200
$ ./ocis/bin/ocis server
2023/10/04 12:54:55 http: TLS handshake error from 192.168.122.1:40762: remote error: tls: unknown certificate
2023/10/04 12:54:55 http: TLS handshake error from 192.168.122.1:40776: remote error: tls: unknown certificate
2023/10/04 12:54:55 http: TLS handshake error from 192.168.122.1:49526: remote error: tls: unknown certificate
2023/10/04 12:54:55 http: TLS handshake error from 192.168.122.1:49540: remote error: tls: unknown certificate
```

**Comment by isbm** [comment]
OK, a bit better happens if I do this:
```
export OCIS_URL=https://[IP-OF-MY-VM]:9200
```
So `https://localhost:9200` is wrong, it should be an actual IP. Now I finally see the owncloud login.

But I still see the see TLS errors on the STDOUT.

**Comment by isbm** [comment]
Yes, the login works, admin/einstein and Co, I can upload stuff. Except I still get load of errors on STDOUT about TLS handshakes and like these:

```
{"level":"error","service":"idp","error":"ldap identifier backend get user connect error:
LDAP Result Code 200 \"Network Error\": dial tcp 127.0.0.1:9235: operation was
canceled","time":"2023-10-04T13:06:04Z","message":"IdentifierIdentityManager: fetch failed
to get user from userID"}
```

or:

```
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000
","error":"internal error: gateway: error finding an auth provider for type:
bearer","type":"bearer","time":"2023-10-04T13:06:06Z","message":"error getting auth provider client"}
```

**Comment by kobergj** [comment]
Yes this can be. We are sometimes a bit noisy with some error messages. We assume these happen when the web client refreshes its access tokens. We are working on getting rid of them. 

They should not have an impact on system operations :+1:

**Comment by isbm** [comment]
Ah OK. Well so to summarise, missing parts on the Quickstart:

- Add node.js setup and note it requires never version.
- Setup detail where `OCIS_URL` should be explicitly set to the machine IP, if the whole thing is not running on a localhost.

Now, at this very point it is probably sufficient for me to poke around into the Go code, so this issue can be closed. 😉 

@kobergj thanks for the help!
