### ISSUE TITLE
Accessing shared resource can be done using either `mount share id` or `virtual share id`.

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#7423]
In spaces dav version, when sending API request, the endpoint can either use `mount share id` as `https://localhost:9200/remote.php/dav/spaces/<mount-share-id>` or we can use `virtual share id` as `https://localhost:9200/remote.php/dav/spaces/<virtual-share-id>/<resource-name>`. In both cases, we can access the shared resources.

We have multiple scenarios where we need to access the shared resources. In those scenarios, what should we prefer `mount-share-id` or `virtual share id`, for test cases or should we test for both `mount share id` or `virtual share id`?

Related:
- https://github.com/owncloud/ocis/issues/4393
- https://github.com/owncloud/ocis/issues/6752

CC @individual-it @phil-davis @ScharfViktor @micbar @saw-jan

**Comment by ScharfViktor** [comment]
web uses `https://localhost:9200/remote.php/dav/spaces/<mount-share-id>` 

look here
<img width="1422" alt="Screenshot 2023-10-10 at 11 05 46" src="https://github.com/owncloud/ocis/assets/84779829/d616fbd2-0be1-46dd-9559-b461c8d36029">


let have test for that IMHO

or add new path to our collection of path

**Comment by PrajwolAmatya** [comment]
With the discussion of this issue, we used the `mount-shared-id` to access the shared resources. The test has been covered in the PR https://github.com/owncloud/ocis/pull/7234. So, closing this issue as completed.
