### ISSUE TITLE
OIDC callback, Client timeout error while ocis serve using docker

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7438]
**Tested on**: Ubuntu 22.04.3 LTS
**Docker version**: 24.0.6
**Docker compose version**: 2.21.0
**docker compose file**: [docker-compose.zip](https://github.com/owncloud/ocis/files/12856831/docker-compose.zip)

## Describe the bug
While running ocis with the help of docker locally faced an error 

## Step to reproduce

step 1: clone web repository
`$ git clone git@github.com:owncloud/web.git`

Step 2: go to ***web*** path `$ cd web`  and run
`$ make dist`

Step 3:  run docker command
`$ docker compose up ocis`

## Server log

```bash
web_ocis  | 2023-10-09T10:26:58Z ERR failed to authenticate the request error="failed to verify access token: Get \"https://host.docker.internal:9200/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" authenticator=oidc path=/api/v0/settings/values-list service=proxy
web_ocis  | 2023-10-09T10:26:58Z ERR error getting auth provider client error="internal error: gateway: error finding an auth provider for type: bearer" pkg=rgrpc service=gateway traceid=00000000000000000000000000000000 type=bearer
web_ocis  | 2023-10-09T10:27:08Z ERR failed to authenticate the request error="failed to verify access token: Get \"https://host.docker.internal:9200/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" authenticator=oidc path=/ocs/v1.php/cloud/user service=proxy
```
## Console

![image](https://github.com/owncloud/ocis/assets/61624650/64af3688-af33-4d96-ab0a-2667faaf5515)

**Comment by individual-it** [comment]
@nabim777 please post your docker compose file

**Comment by nabim777** [comment]
> @nabim777 please post your docker compose file

Okay

**Comment by individual-it** [comment]
I can login but not upload any files or create folders
![grafik](https://github.com/owncloud/ocis/assets/2425577/daf883fb-3245-431f-a428-86821a6ea865)

**Comment by micbar** [comment]
> Step 3: go to web path and run docker command
$ docker compose up ocis

Why do you leave the reverse proxy out?

**Comment by individual-it** [comment]
The problem turned out to be a firewall issue.

**Comment by nabim777** [comment]
This error is due to the firewall problem.
This issue arises when the firewall is turned on because the containers cannot communicate with eachother. In order to prevent from this error there are two options:

Option 1: Just allow TCP traffic from any source to the 127.0.0.0/8
```zsh
sudo ufw route allow proto tcp from any to 172.0.0.0/8
```

**or**

Option 2: Disable the firewall
```zsh
sudo ufw disable
```

**Comment by individual-it** [comment]
@nabim777 should we close this issue?

**Comment by nabim777** [comment]
Yes we can close this issue since we get a solution https://github.com/owncloud/ocis/issues/7438#issuecomment-1761319695 
thanks @micbar for giving time in this issue and
thanks @individual-it for the solution
