### ISSUE TITLE
New dav doesn't return resources if auto accepting enabled

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7440]
### case with disabled autoaccepting
- start ocis with `FRONTEND_AUTO_ACCEPT_SHARES: "false"`
- marie shares folder `disabled` to admin
- admin accepts folder `disabled` and can get folder using `curl -XPROPFIND "https://host.docker.internal:9200/remote.php/dav/files/admin/Shares/disabled" -uadmin:admin -H "Content-Type: application/json" -vk`

Actual: request returns folder

### case with enabled autoaccepting
- start ocis with `FRONTEND_AUTO_ACCEPT_SHARES: "true"`
- marie shares folder `enabled` to admin
- admintries to get folder `enabled` `curl -XPROPFIND "https://host.docker.internal:9200/remote.php/dav/files/admin/Shares/enabled" -uadmin:admin -H "Content-Type: application/json" -vk`

Actual: not found: `<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception>Sabre\DAV\Exception\NotFound</s:exception><s:message>Resource not found</s:message>`

but space dav works fine: `curl -XPROPFIND "https://host.docker.internal:9200/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%210be2e235-4298-416a-aad0-4bdf2aaff6e6:f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c:5d657ace-1e41-49ed-b044-e54c07067166/" -uadmin:admin -H "Content-Type: application/json" -vk`

**Comment by kobergj** [comment]
Underlying issue is the same as in https://github.com/owncloud/ocis/issues/7441 - no mountpoint is set.
