### ISSUE TITLE
The `remaining quota` for unrestricted spaces doesn't make sense in case of s3 storage

### ISSUE THREAD

**Issue by aduffeck** [owncloud/ocis#7461]
The admin view of spaces lists the remaining quota for each of the spaces. In case of unrestricted spaces the `remaining quota` is derived from what the storage layer reports as available disk space.

That logic doesn't really make sense in case of S3 storage because only the metadata of the files is stored on that disk and the actual blobs are offloaded to the object storage. We should either find a way to show the actual bucket quota (if possible) or adjust the UI in a way that's not confusing anymore.

**Comment by micbar** [comment]
@tbsbdr Needs an Enhancement IMO

**Comment by micbar** [comment]
can you give it some prio?

**Comment by rhafer** [comment]
This has been fixed as part of https://github.com/cs3org/reva/pull/4897
