### ISSUE TITLE
Custom Theming not applying to Login Page

### ISSUE THREAD

**Issue by scarmonar** [owncloud/ocis#7468]
## Describe the bug
I'm playing around with custom theming, everything's working after login (colors, images, etc) but in the Login page it doesn't affect at all and stay with the default theme. Also, owncloud logo url in that page is a static one and isn't referenced from the theme file. 

## Steps to reproduce

Initialize OCIS 4.0.2 with Docker Compose with a Custom Theme.

## Expected behavior
Custom theme applied to the login page. 

## Actual behavior
Custom theme not working on login page.

## Setup
Docker version 24.0.6, build ed223bc
Ubuntu 22.04.3 LTS
OCIS 4.0.2 Image

Enviroment Variables.
<details>
<p>
     - OCIS_URL=https://####.${DOMAINNAME}
      - OCIS_LOG_LEVEL=info
      - OCIS_LOG_COLOR=true
      - OCIS_INSECURE=false
      - PROXY_ENABLE_BASIC_AUTH=false
      - IDM_ADMIN_PASSWORD=#############
      - FRONTEND_AUTO_ACCEPT_SHARES=true
      - WEB_UI_THEME_SERVER=https://####.${DOMAINNAME}
      - WEB_UI_THEME_PATH=/themes/theme.json
</p>
</details>

## Additional context
Theme is stored in "ocis-data\web\assets\themes" amd "ocis-data" is binded to "/etc/ocis"

**Comment by wkloucek** [comment]
This is because the IDP service ships it's own website (the login forms). Since this service is supposed to be replaced in most corporate / integrated use cases (because of limitations), there was no effort for branding the login pages, too.

@tbsbdr @micbar  Is branding of the IDP login pages on the roadmap or is this a limitation, that will continue to apply on the oCIS builtin IDP service?

**Comment by gitekelund** [comment]
See this thread on how to modify the IDP https://central.owncloud.org/t/theming-settings-in-ocis-yaml/45276/9

you have to build it then host it, and point "IDP_ASSET_PATH" to it..

**Comment by wkloucek** [comment]
> See this thread on how to modify the IDP https://central.owncloud.org/t/theming-settings-in-ocis-yaml/45276/9
> 
> you have to build it then host it, and point "IDP_ASSET_PATH" to it..

Yes, changing the code is possible. But I'd no longer call it "theming" because you can't change it via configuration.

You'd also could use a IDP (like eg. Keycloak) that supports branding / theming out of the box if you want to take the effort.

**Comment by micbar** [comment]
> @tbsbdr @micbar Is branding of the IDP login pages on the roadmap or is this a limitation, that will continue to apply on the oCIS builtin IDP service?

This is not on the roadmap.

**Comment by wkloucek** [comment]
@mmattel no theming / not being brandable could also be listed as a limitation of the builtin IDP (next to session management and scaleability)

**Comment by wkloucek** [comment]
I'm closing this since it's not planned.
