### ISSUE TITLE
Additional permissions for creating shares and favorites

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#7497]
CERN would like to disable creating shares and favorites for their lightweight accounts. We figured it would be best to work with permissions here, as they offer maximum flexibility and could be a benefit for us as well in the future.

That would mean we need new permissions:

* ~`Favorites.ReadWrite`~
* `Favorites.List`
* `Favorites.Write`
* `Shares.Write`

Also see https://github.com/owncloud/web/issues/9381.

## Acceptance criteria

- [ ] `Favorites.List` allows / denies the Favorites Listing Request
- [ ] `Favorites.Write` is implemented to be enforced on marking/unmark files as favourites
- [ ] `Share.Write` permission denies / allows sharing completely for a user on all share CUD requests. (User, Group)

**Comment by JammingBen** [comment]
@micbar Any opinions on this?

**Comment by micbar** [comment]
I understand the `Shares.Write` permission.

What about the favourites? Why `ReadWrite`?

**Comment by micbar** [comment]
Ah you mean the "list-all-favourites" permission?

That would be a new one IMO `Favorites.List`

**Comment by micbar** [comment]
Just to be on the same page, should the use also not be able to see the favorite flag in the file list?

Because that is difficult from a backend POV. We currently do not distinguish different metadata.

**Comment by JammingBen** [comment]
> Just to be on the same page, should the use also not be able to see the favorite flag in the file list?

No, it's about not showing the Favorite-navitem. The flag itself will never show when the user doesn't have permissions to mark files as favorite, so that's okay.

`Favorites.List` would be fine for us as well. You mean additionally to `Favorites.Write`, right?

**Comment by micbar** [comment]
> Favorites.List would be fine for us as well. You mean additionally to Favorites.Write, right?

Yes.

**Comment by JammingBen** [comment]
Sounds good! 👍
