### ISSUE TITLE
CI pipeline fails in `docs` step

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#7509]
CI pipeline sometimes fails in the `docs` step. See https://drone.owncloud.com/owncloud/ocis/27722/106/2 for example.

Reason is that `bingo` tries to download some dependencies and gets a `403` somehow. We need to vendor these dependencies somehow or get rid of `bingo`

**Comment by micbar** [comment]
I see that these pipelines are not routed through our proxy. So the ip addresses of the runners are sometimes blacklisted.

We can add 

```
"environment": {
                "HTTP_PROXY": {
                    "from_secret": "drone_http_proxy",
                },
                "HTTPS_PROXY": {
                    "from_secret": "drone_http_proxy",
                },
            },
``
`

**Comment by kobergj** [comment]
Good idea :+1: Let's try it like this. We can reopen the ticket if we still see issues...
