### ISSUE TITLE
Moving between share mountpoints breaks tests

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7555]
moving between spaces is forbidden we get 502 now (expect 409)
but moving between `Shares/folder1` and `Shares/folder2` is possible. but we get mess

example: tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature:462

Step `And user "Brian" has moved folder "/Shares/parent" to "/Shares/sharedParent"` causes to flaky. 

<img width="1423" alt="Screenshot 2023-10-20 at 15 40 15" src="https://github.com/owncloud/ocis/assets/84779829/414bd9a6-a6f2-460a-bd63-17447b18dd47">

**Comment by saw-jan** [comment]
@ScharfViktor do we expect 409 now? I think 502 is the correct one right?

**Comment by saw-jan** [comment]
Should be fixed by https://github.com/cs3org/reva/pull/4439
