### ISSUE TITLE
User is automatically logged out despite "permanent access" checkbox

### ISSUE THREAD

**Issue by rmk-ch** [owncloud/ocis#7558]
## Describe the bug
Users need to log in again into OCIS with Windows, IOS and Android clients.

## Steps to reproduce
1. User setup on different devices (all versions up-to-date).
2. When logging in all tickmarks are set (incl. the second checkbox, "permanent access")
![image003](https://github.com/owncloud/ocis/assets/3728276/19e323a8-1038-4377-b118-52f0caa88340)
4. Wait a few weeks (maybe 2, not clear how long this is). 
5. User receives this error:
![image001](https://github.com/owncloud/ocis/assets/3728276/401f8b97-668b-424e-86d0-e268dda82ed0)
6. User must log in again

## Expected behavior
When having ticked "permanent access" I would expect that the user is not logged out after a while.

## Actual behavior
User is automatically logged out after a few weeks (maybe 2)

## Setup
OCIS v4.0.2 in Docker under Linux, behind nginx proxy. 

```console
      - OCIS_URL=https://my-url.com
      - OCIS_INSECURE=true
      - PROXY_TLS=false
      - PROXY_HTTP_ADDR=0.0.0.0:9200
```

Windows client 4.2.0.11670 (f5a29b)

**Comment by rmk-ch** [comment]
Hi 
Any comments by the devs for this annying bug? Thanks for taking a look.

**Comment by rhafer** [comment]
It might just be that the refresh token expired. Has the client been offline for some extended time before that happened?
AFAIK the builtin IDP sets a default lifetime of 30days for the refresh token.

If that is not the case, I guess log files from the client would help to figure out what happened.

@TheOneRing anything else you can think of?

**Comment by TheOneRing** [comment]
Certain scenarios leading to a token refresh failure also result in a client log out (desktop) but the above sounds more like a timeout.

**Comment by rmk-ch** [comment]
@rhafer @TheOneRing Thanks for the hint, it could be the case here, yes. Is IDP_REFRESH_TOKEN_EXPIRATION the correct setting to change? (Taken from https://doc.owncloud.com/ocis/next/deployment/services/s-list/idp.html, default value corresponds to 30 days)

**Comment by rhafer** [comment]
> Is IDP_REFRESH_TOKEN_EXPIRATION the correct setting to change?

Yes

**Comment by rmk-ch** [comment]
Working fine now.
Thanks a lot.
