### ISSUE TITLE
Banned Password List: Provide Compatibility with HIBP List

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#7571]
# Description

## User Stories

* > As a CISO I want to use an offline password list from HIBP so that I don't need to create the list myself.

## Value

- Use readymade lists
- Don't disclose the passwords searched for
- Comply with Policies

## Acceptance Criteria

- tracked times are sent to @tschiebel 
- use specified hash formats in our passwords list
- passwordlist config value points to a directory
- directory contains 1 or more subdirectories, named with the used hash algorithm 
- our validation works with https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader and uses SHA1
- `plain` and `SHA1` lists are implemented

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by tbsbdr** [comment]
https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader

**Comment by 2403905** [comment]
So, I downloaded 15% and it is 5.6Gb. Let's see tomorrow it will be ~45Gb

**Comment by 2403905** [comment]
The full size of the base that I downloaded is 34 Gb. It looks like it should be some dedicated service or some db...
@tbsbdr @micbar We have to decide do we want to move forward with this task.

**Comment by micbar** [comment]
I would like the idea of providing an API for cecking passwords on a standalone service.

**Comment by 2403905** [comment]
I found out that the single file contains the 40-character hash but the individual files contain the 35-character hash and the file name is the first 5 characters. So, all files are already sorted.

**Comment by micbar** [comment]
on hold. The requirements are not clear.

**Comment by micbar** [comment]
Closing. Guest users will be implemented later via Keycloak plugin.
