### ISSUE TITLE
[ocis] Make the order of the app-registry config the same on the output

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#7582]
# Description

## User Stories

* > As a user who wants to create a new file, I want to have the most important file types clearly accessible so that I don't have to search long.

## Value

- improve usability & productivity

## Acceptance Criteria

- the order of the app registry config should make the order in the client

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

### Current: Not sorted by importance
![screenshot_001839](https://github.com/owncloud/ocis/assets/26610733/45fd9c94-41a3-4a85-a883-8526b006698e)

### Should: Sorted by importance
![screenshot_001838](https://github.com/owncloud/ocis/assets/26610733/48acb038-4717-4a84-8073-2c8df84497a9)

**Comment by tbsbdr** [comment]
fyi @michaelstingl

**Comment by micbar** [comment]
NOTE from the planning: It is questionable if the story is needed at all. WebClient implemented sorting.

**Comment by micbar** [comment]
Not needed. Web client side sorting was implemented.
