### ISSUE TITLE
`hidden` state of a share is not being persisted

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#7589]
## Steps to reproduce

1. Make sure auto-accepting shares is enabled
2. As `user1`, share a folder with `user2`
3. As `user2`, try to hide the share via `https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/shares/pending/YOUR_ID?hidden=true&format=json` -> the response from the server looks good, it returns `hidden: true`
4. As `user2`, query all incoming shares -> the `hidden` property is `false` again. So there seems to be a problem with persisting the state.

\cc @dragonchaser

**Comment by dragonchaser** [comment]
There seems to be an issue with the persistance, looking into it.
