### ISSUE TITLE
Extensions: Monorepo vs Multirepo

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#76]
Implementing a change on each and every repository is a tedious task, see the recent example with adding a `namespace` flags.

As a means of documentation, at least, could we list the pros and cons of having a mono vs multi [repo] to host the extensions? A bit [like micro does](https://github.com/micro/go-plugins)

**Comment by tboerger** [comment]
I personally really dislike mono repos. You aren't really able to further develop extensions on their own. Beside that, the drone support for mono repos is really limited.

Next to that we will get into the same pita we already had with the old core.

**Comment by phil-davis** [comment]
I have the same "problem" with the ownCloud core app repos. There are about 50 of them, and every time we change some common piece of CI script, phpunit.xml test settings, acceptance test settings, dependencies... there are often up to 50 PRs to do.

But having 50 individual repos does mean that we can choose when to introduce a new dependency... in each app.

There does not seem to a simple clear "best" way for this sort of thing.

**Comment by tboerger** [comment]
For this kind of change you should use simple shell scripts, loops and cli helpers like github hub. That reduces the complexity a lot.

**Comment by refs** [comment]
Fair points. Just wanted to have a bit of a write down for track record :D
