### ISSUE TITLE
User can access version metadata of a received share before accepting it

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#760]
1. upload a file `curl -v -k -u richard:superfluidity -X PUT https://localhost:9200/remote.php/dav/files/richard/file.txt -d "123"`
2. save the fileid from `Oc-Fileid` header 
3. share the file `curl -v -k -u richard:superfluidity -X POST https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/shares -d 'permissions=1&path=%2Ffile.txt&shareType=0&shareWith=einstein' -H "Content-Type: application/x-www-form-urlencoded"`
4. as receiver access the versions information of the file `curl -k -u einstein:relativity -X PROPFIND https://localhost:9200/remote.php/dav/meta/<<FILEID>>/v`

in oc10 this is not possible before accepting the share

**Comment by refs** [comment]
trying to reproduce but I cannot manage to see the `Oc-Fileid` header on any requests, in fact, I see no `Oc-*` headers. Perhaps a bit more context / reproducible steps for future us?

**Comment by individual-it** [comment]
@refs the first request (upload) `curl -v -k -u richard:superfluidity -X PUT https://localhost:9200/remote.php/dav/files/richard/file.txt -d "123"` returns me an `Oc-Fileid` header
![image](https://user-images.githubusercontent.com/2425577/104869310-d41e6080-596d-11eb-87f8-2934536d8ac4.png)

It does not do that for you?

**Comment by refs** [comment]
@individual-it aaah, sorry, got it. Can confirm I was able to reproduce it 👍

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
it reproduces

**Comment by ScharfViktor** [comment]
is not possible yet fixed #5531
