### ISSUE TITLE
Changing the status of a share resets its `hidden` property

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#7608]
## Steps to reproduce

1. As `user1`, share a folder with `user2`
2. As `user2`, hide the share by setting `hidden=true` via API
3. As `user2`, change the status of the share, e.g. decline it -> the `hidden` property of share will revert back to `false`

I'm not sure if that's considered a bug or not. The web client could handle that shortcoming by manually hiding the share again, but I'm not a fan of that tbh.

\cc @micbar @dragonchaser

**Comment by dragonchaser** [comment]
If said PR is merged, just needs an reva bump in ocis

**Comment by dragonchaser** [comment]
If said PR is merged, just ne
