### ISSUE TITLE
Tus upload: The file name limit of 255bytes is applied against the file path

### ISSUE THREAD

**Issue by zerolabnet** [owncloud/ocis#7610]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

At this point there is a check for a path length of 255 bytes, not 255 characters. I am using Cyrillic, which character encoding takes 2 bytes. So the OwnCloud client is restricting me to use a path length that is actually half as long as if I were using Latin characters. This is the problem:

![Снимок экрана от 2023-10-27 13-46-16](https://github.com/owncloud/client/assets/71016736/06121e79-c1f5-45fe-8c52-fb64ab523604)

Path:
`/Деснол/Разработка регламентов/Управление пользователями ИТ инфраструктуры компании/2023-05-15 Управление пользователями ИТ инфраструктуры компании.docx`

String in UTF-8:
```
2f,d094,d0b5,d181,d0bd,d0be,d0bb,2f,d0a0,d0b0,d0b7,d180,d0b0,d0b1,d0be,d182,d0ba
d0b0,20,d180,d0b5,d0b3,d0bb,d0b0,d0bc,d0b5,d0bd,d182,d0be,d0b2,2f,d0a3,d0bf,d180
d0b0,d0b2,d0bb,d0b5,d0bd,d0b8,d0b5,20,d0bf,d0be,d0bb,d18c,d0b7,d0be,d0b2,d0b0,d182
d0b5,d0bb,d18f,d0bc,d0b8,20,d098,d0a2,20,d0b8,d0bd,d184,d180,d0b0,d181,d182,d180
d183,d0ba,d182,d183,d180,d18b,20,d0ba,d0be,d0bc,d0bf,d0b0,d0bd,d0b8,d0b8,2f,32,30
32,33,2d,30,35,2d,31,35,20,d0a3,d0bf,d180,d0b0,d0b2,d0bb,d0b5,d0bd,d0b8,d0b5,20,d0bf
d0be,d0bb,d18c,d0b7,d0be,d0b2,d0b0,d182,d0b5,d0bb,d18f,d0bc,d0b8,20,d098,d0a2,20
d0b8,d0bd,d184,d180,d0b0,d181,d182,d180,d183,d0ba,d182,d183,d180,d18b,20,d0ba,d0be
d0bc,d0bf,d0b0,d0bd,d0b8,d0b8,2e,64,6f,63,78
```
Number of characters: 152
Number of bytes: 275

In fact, I have to take a shortcut to:
`/Деснол/Разработка регламентов/Управление пользователями ИТ инфраструктуры компании/2023-05-15 Управление пользователями ИТ инфраструкту.docx`

String in UTF-8:
```
2f,d094,d0b5,d181,d0bd,d0be,d0bb,2f,d0a0,d0b0,d0b7,d180,d0b0,d0b1,d0be,d182,d0ba
d0b0,20,d180,d0b5,d0b3,d0bb,d0b0,d0bc,d0b5,d0bd,d182,d0be,d0b2,2f,d0a3,d0bf,d180
d0b0,d0b2,d0bb,d0b5,d0bd,d0b8,d0b5,20,d0bf,d0be,d0bb,d18c,d0b7,d0be,d0b2,d0b0,d182
d0b5,d0bb,d18f,d0bc,d0b8,20,d098,d0a2,20,d0b8,d0bd,d184,d180,d0b0,d181,d182,d180
d183,d0ba,d182,d183,d180,d18b,20,d0ba,d0be,d0bc,d0bf,d0b0,d0bd,d0b8,d0b8,2f,32,30
32,33,2d,30,35,2d,31,35,20,d0a3,d0bf,d180,d0b0,d0b2,d0bb,d0b5,d0bd,d0b8,d0b5,20,d0bf
d0be,d0bb,d18c,d0b7,d0be,d0b2,d0b0,d182,d0b5,d0bb,d18f,d0bc,d0b8,20,d098,d0a2,20
d0b8,d0bd,d184,d180,d0b0,d181,d182,d180,d183,d0ba,d182,d183,2e,64,6f,63,78
```
Number of characters: 141
Number of bytes: 254

Basically I can't use ownCloud client properly. I fit within the limitations of most file systems (255 characters per path), but I don't fit within the limitations of the ownCloud client (255 bytes per path).

### Expected behavior

I believe that the developers did not think about encoding characters larger than 1 byte. I suggest to rewrite the check for 255 characters, not bytes.

### Client version number

![Снимок экрана от 2023-10-27 14-04-22](https://github.com/owncloud/client/assets/71016736/583f6b2e-0f1d-4174-afe1-dab92c4e5e72)

### Desktop environment (Linux only)

Manjaro Linux with GNOME version 44.5

### Client package version and origin (Linux only)

From my distribution

### Server information

ownCloud | Infinite Scale
-- | --
Edition|Community
Version|4.0.0+13f66cbf8
Web client version|8.0.0-alpha.4

**Comment by TheOneRing** [comment]
The problem is that ocis checks the file filename metadata against the limit of 255 bytes, but filename contains the full path relative to the space.
