### ISSUE TITLE
MOVE a file from `Project` space (manager/editor) to `Personal` space returns 502 code

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7618]
## Describe the bug

When a user makes an API request to move a file from the `project space` to `personal space` and vice versa then it returns `502` status code

## Steps to reproduce

1. As `admin`, create a space `project-space`
2. As `admin`, upload file `file.txt` inside space `project-space`
3. As `admin`, move file `file.txt` from space `Project-space` to `Personal` space using curl command
```zsh
curl -kv -XMOVE -uadmin:admin 'https://localhost:9200/remote.php/dav/spaces/<file-id>' \
-H 'Destination: https://localhost:9200/remote.php/dav/spaces/<personal-space-id>/file.txt' | xmllint --format -
```

## Expected behavior
Expected to be returns between 400-405

## Actual behavior
<details>
<summary>Returns 502</summary>

```zsh
HTTP/1.1 502 Bad Gateway
< Access-Control-Allow-Origin: *
< Content-Length: 207
< Content-Security-Policy: default-src 'none';
< Content-Type: text/xml; charset=utf-8
< Date: Mon, 30 Oct 2023 08:43:58 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Request-Id: nabin-OptiPlex-3050/6iKFbNOAye-003454
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 
{ [207 bytes data]
100   207  100   207    0     0   4215      0 --:--:-- --:--:-- --:--:--  4312
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
  <s:exception/>
  <s:message>move:error: not supported: cannot move across spaces</s:message>
</d:error>

```

</details>

**Comment by saw-jan** [comment]
CC @ScharfViktor @micbar 
One of the 502 from https://github.com/owncloud/ocis/issues/8063#issuecomment-1873994662 is this one

**Comment by saw-jan** [comment]
Also same response for MOVE `Personal`/file to `Project`/file (manager/editor)

**Comment by saw-jan** [comment]
As per https://github.com/owncloud/ocis/issues/8063#issuecomment-1883281975, https://github.com/owncloud/ocis/issues/8063#issuecomment-1883281975 and https://github.com/owncloud/ocis/issues/4087#issuecomment-1177951438, the 502 statuscode is the correct code that server should respond. So closing this.
