### ISSUE TITLE
adding mutil url

### ISSUE THREAD

**Issue by solivehong** [owncloud/ocis#7623]
I set up a local version of the service with ip:9200 but I don't have a pubilc ip , 
use DDNS and can access the link from the extranet but the OCIS_URL has to be set to a ddns domain,
is there a way to set the local address with pubilc domain at the same time?
```
docker run     --name ocis_runtime        -d  --restart=always   -p 9200:9200 -p 9100:9100    --mount type=bind,source=/shareData/docker_env/ocis/ocis-config,target=/etc/ocis     --mount type=bind,source=/shareData/docker_env/ocis/ocis-data,target=/var/lib/ocis     -e OCIS_INSECURE=true     -e PROXY_HTTP_ADDR=0.0.0.0:9200      -e OCIS_URL=https://10.10.10.200:9200   owncloud/ocis
```

**Comment by micbar** [comment]
Sorry for the late response. That is unfortunately not possible because ocis brings an OpenIDConnect Identity Provider. The url is a crucial part of the protocol and needs to be specific for each client and the idp.
