### ISSUE TITLE
[OCIS-storage] reading a file that a collaborator uploaded is impossible

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#763]
1. create a folder: `curl -k -u richard:superfluidity -X MKCOL https://localhost:9200/remote.php/dav/files/richard/folder1`
2. share a folder: `curl -k -u richard:superfluidity -X POST https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/shares -d 'permissions=31&path=%2Ffolder1&shareType=0&shareWith=einstein' -H "Content-Type: application/x-www-form-urlencoded" | xmllint --format -`
3. as receiver accept the share `curl -k -u einstein:relativity -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/pending/2cb918c7-f7f7-4b3a-96d3-50b2359de165`
4. as receiver upload a file `curl -k -u einstein:relativity -XPUT -d"123" https://localhost:9200/webdav/Shares/folder1/file1.txt`
5. as receiver download the file `curl -k -u einstein:relativity -XGET https://localhost:9200/webdav/Shares/folder1/file1.txt` => works
6. as sharer check the content of the folder `curl -k -u richard:superfluidity -X PROPFIND https://localhost:9200/webdav/folder1 | xmllint --format -` => file is listed
7. as sharer try to download the file `curl -k -u richard:superfluidity -X GET https://localhost:9200/webdav/folder1/file1.txt -v` => HTTP 403 Forbidden

OCIS logs:
```
2020-10-28T14:04:28+05:45 ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/storageprovider/storageprovider.go:505 > permission denied error="error: permission denied: 2091ff03-e325-409d-a74e-a5615067a082" pkg=rgrpc service=storage traceid=6da7e9f5ad3f9efa5b487b2a466f91c2

**Comment by individual-it** [comment]
same when trying to overwrite such a file, the sharer gets a 403 response

**Comment by individual-it** [comment]
as sharer trying to `PROPFIND` the uploaded file (`curl -k -u richard:superfluidity -X PROPFIND https://localhost:9200/webdav/folder1/file1.txt -v`) returns `207 Multi-Status` but with an empty content

**Comment by refs** [comment]
This is no longer the case with the ocis storage:

![image](https://user-images.githubusercontent.com/6905948/104318894-5a572480-54e0-11eb-82c4-33158c63904a.png)
