### ISSUE TITLE
[OCIS-storage] overwriting a file as share receiver, does not create a new file version for the sharer

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#766]
1. share a file
2. accept the share
3. as share receiver overwrite the file
4. as sharer check the versions of the file

current behaviour:
as sharer no versions are shown

maybe related to #763

**Comment by ScharfViktor** [comment]
tested with local server oCIS version 1.11.0

current behaviour: receiver can overwrite file if file is located "Shares/Folder(with edit right)/file". receiver cannot add or overwrite a file to the folder "Shares"

as sharer can see new version of file. I suggest to close @individual-it

**Comment by individual-it** [comment]
There is still a test that is marked as failing because of this issue https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-API-on-OCIS-storage.md#ocis-storage-overwriting-a-file-as-share-receiver-does-not-create-a-new-file-version-for-the-sharer
we need to find out why that test still fails and tag it correctly, I suggest to keep this issue open for that

ToDo QA:team:
- [ ] find out why apiVersions/fileVersionsSharingToShares.feature:32 still fails and tag it with the correct issue. If the problem is not this issue, close it

**Comment by dpakach** [comment]
As of now the issue failing 

> ToDo QA:team:
> 
> * [ ]  find out why apiVersions/fileVersionsSharingToShares.feature:32 still fails and tag it with the correct issue. If the problem is not this issue, close it

as of now the issue breaking that scenario is https://github.com/owncloud/ocis/issues/2706
So closing this issue.
