### ISSUE TITLE
Unable to login - failed to authenticate request

### ISSUE THREAD

**Issue by 7ritn** [owncloud/ocis#7677]
## Describe the bug
Today I noticed, that I'm not able to log in to Owncloud. I'm stuck at the Oidc callback screen. Using the app is also no longer possible. Would love getting this resolved as soon as possible since the instance is no longer accessible at all.

## Steps to reproduce
1. Try to log in
2. Getting stuck

## Expected behavior
Able to log in.

## Actual behavior
Stuck at Oidc callback screen. Log of owncloud has following errors:
```
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"internal error: gateway: error finding an auth provider for type: bearer","type":"bearer","time":"2023-11-08T00:43:16.862556479Z","message":"error getting auth provider client"}

{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://cloud.hymalia.duckdns.org:39135/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2023-11-08T00:43:26.85862312Z","message":"failed to authenticate the request"}
```

## Setup
Currently using the ocis 4.0.0 docker image in a rootless podman. Everything worked perfectly before today.

**Comment by micbar** [comment]
Seems like your ocis container can not connect to https://cloud.hymalia.duckdns.org:39135/.well-known/openid-configuration

please verify that this is reachable from the ocis container.

**Comment by 7ritn** [comment]
Yes, that seemed to fix it. Thanks for the fast reply!
