### ISSUE TITLE
creating group give 200 status code

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#7678]
## Describe the bug
according to the api specification on https://owncloud.dev/libre-graph-api/#/groups/CreateGroup
creating group gives `201` status code but it actually gives `200`

## Steps to reproduce
create a group
```bash
curl -k -v "https://localhost:9200/graph/v1.0/groups" --data "{\"displayName\":\"team2\"}" -u admin:admin
```
response
```bash
> POST /graph/v1.0/groups HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 23
> Content-Type: application/x-www-form-urlencoded
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 84
< Content-Security-Policy: frame-ancestors 'none'
< Content-Type: application/json
< Date: Wed, 08 Nov 2023 04:14:30 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Graph-Version: 5.0.0-alpha.1+2c46b2beb2
< X-Request-Id: neer-OptiPlex-3050/LiAmcrh5bD-000460
<
{"displayName":"team2","groupTypes":[],"id":"115e9844-9bc9-470d-b096-1cb6287fe0bb"}
* Connection #0 to host localhost left intact

```

## Expected behavior
http status code should be `201`

## Actual behavior
http status code should is `200`

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=master
```

</p>
</details>

**Comment by ScharfViktor** [comment]
I found a couple other inconsistencies between specification and actual behavior. 

### creating users:
https://owncloud.dev/libre-graph-api/#/users/CreateUser expects `201` 
actual behavior: `200`

### export GDPR: 
https://owncloud.dev/libre-graph-api/#/user/ExportPersonalData - `202`
actual- `201`

**Comment by micbar** [comment]
Let us please align that. @kulmann @JammingBen can we change on the server side? Is that a breaking change for web?

**Comment by kulmann** [comment]
> ### creating users:
> https://owncloud.dev/libre-graph-api/#/users/CreateUser expects `201` actual behavior: `200`

Web doesn't care about the status code. But it needs the id of the created user within the response body. I.e. could be changed in the backend without breaking web.


> ### export GDPR:
> https://owncloud.dev/libre-graph-api/#/user/ExportPersonalData - `202` actual- `201`

Web triggers the request and only reacts on error status codes. Immediately goes into a scheduled task which checks if the gdpr export file is already available / not in processing (`425`) state anymore. I.e. could also be changed in the backend without breaking web.

**Comment by amrita-shrestha** [comment]
we need to adjust the status code in the test file
https://github.com/owncloud/ocis/blob/2009114060042120804a97a5d9bd0252bc4f0b64/tests/acceptance/features/apiGraph/createGroup.feature#L13
https://github.com/owncloud/ocis/blob/2009114060042120804a97a5d9bd0252bc4f0b64/tests/acceptance/features/apiGraph/createUser.feature#L24-L37
https://github.com/owncloud/ocis/blob/2009114060042120804a97a5d9bd0252bc4f0b64/tests/acceptance/features/apiGraph/createUser.feature#L91
https://github.com/owncloud/ocis/blob/2009114060042120804a97a5d9bd0252bc4f0b64/tests/acceptance/features/apiGraph/createUser.feature#L105

https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/userGDPRExport.feature

**Comment by phil-davis** [comment]
> we need to adjust the status code in the test file after fix

The status code expected in the test will need to be adjusted in the PR that implements the fix into ocis.
