### ISSUE TITLE
Error 500 when user try to unlock project space file

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#7696]
## Describe
When a user try to unlock the project space file, the user get 500 status code

## Steps to reproduce
1. As `admin`, create a space `space` in project space
2. As `admin`, upload a file `file.txt` inside space `space`
3. As `admin`, lock the file `file.txt`
4. As `admin`, unlock the file `file.txt` using curl command:
```bash
curl -kv -XUNLOCK -uadmin:admin 'https://localhost:9200/remote.php/dav/spaces/<project-space-id>/file.txt' -H 'Lock-Token: <file-lock-token>' | xmllint --format -
```

## Expected behavior
status 204

## Actual behavior
status 500
```xml
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Origin: *
< Content-Length: 187
.
.
< Date: Thu, 09 Nov 2023 06:47:33 GMT
< Vary: Origin
< 
{ [187 bytes data]
100   187  100   187    0     0   3408      0 --:--:-- --:--:-- --:--:--  3462
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
  <s:exception/>
  <s:message>error: not found: no space found</s:message>
</d:error>
```
![image](https://github.com/owncloud/ocis/assets/61624650/79da8c08-8ed7-4d3e-8ee8-1dbb8ee624e6)

**Comment by SwikritiT** [comment]
@nabim777 is this issue also solved by https://github.com/owncloud/ocis/pull/7726 ?

**Comment by nabim777** [comment]
@SwikritiT Yes, that PR  https://github.com/owncloud/ocis/pull/7726  solves the issues.
