### ISSUE TITLE
CHANGELOG.md: collect and reference changelog data of versions lower than 2 into an own file

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#7701]
After we have successfully created a TOC for the changelog, see #7691, I suggest for better readbility to strip the collected changelog into a pre 2 and post 1 version. Means CHANGELOG.md contains everything including version 2.x upwards and a link to a file that holds all data for releases of 1.x

**Benefits:**
* Improved readability
* Reduced filesize - the current one cant be viewed in GH - it is too big - timeout while loading

@micbar

**Comment by mmattel** [comment]
Note that we have a similar situation in the client repos where there are older changelogs that are not inlcuded by the process but have been manually added to the file. From the idea, one can add a static link to a manually added section on the bottom where we have a text and a linkt to the final destination where the old changelog data resides. That location could be any resolvable address. See a client template for details.

**Comment by micbar** [comment]
Acccording to the discussion in chat, the need for this seems low.
