### ISSUE TITLE
Add banned password list to default deployments

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#7724]
# Description

Follow up of https://github.com/owncloud/ocis/issues/7682

## User Stories

* > As a  client developer i want to test the new server implementation.

## Value

Easy integration

## Acceptance Criteria

- [ ] Continous ocis deployments have configured list as banned passwords which meet the policy

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by micbar** [comment]
@michaelstingl

**Comment by ScharfViktor** [comment]
> @ScharfViktor do you need a dev to work on that?

I don't know yet. I'll ask Roman for help if I can't figure out how to do it.

**Comment by 2403905** [comment]
`ocis tries to load a file from the FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST if file is not exists then ocis tries OCIS_CONFIG_DIR/FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST`
@wkloucek What is the better way to put the file in to the OCIS_CONFIG_DIR directory?

**Comment by 2403905** [comment]
@micbar Please clarify what exactly default deployments should be.The ci? The helmchart? The docker compose?

**Comment by michaelstingl** [comment]
> @micbar Please clarify what exactly default deployments should be.

Here:
- https://owncloud.dev/ocis/deployment/continuous_deployment/

**Comment by micbar** [comment]
Yes, the docker-compose examples in the ocis repo.
