### ISSUE TITLE
Get metadata without permission causes a 403 error

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#773]
1. as `einstein` upload a file `curl -k -u einstein:relativity -XPUT -d"123" https://localhost:9200/webdav/file1.txt`
1. find the fileid of the file `curl -k -u einstein:relativity -XPROPFIND https://localhost:9200/webdav/file1.txt`
1. as `richard` try to get the versions of the file `curl -k -u richard:superfluidity -XPROPFIND https://localhost:9200/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjFkYTJjNjI5LThhMWItNDk2NC05YTRjLTQ3NmQ0ZWM1NDA5NA==/v -v`

current behaviour:
HTTP/1.1 403 Forbidden with empty body

oc10 behaviour:
HTTP/1.1 404 Not Found with xml in the body
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message/>
</d:error>

**Comment by refs** [comment]
uhm I'm getting a segfault:

![image](https://user-images.githubusercontent.com/6905948/104320191-4f04f880-54e2-11eb-96fd-bbd61473075a.png)

**Comment by ScharfViktor** [comment]
Re-tested with local server oCIS version 1.12.0 and oC10 version 10.8
behavior is the same (except there is no message: "Resource not found")

<img width="1328" alt="Screenshot 2021-09-16 at 21 51 22" src="https://user-images.githubusercontent.com/84779829/133676992-7321cc86-9bd5-47d4-829c-40c670869d77.png">



<img width="952" alt="Screenshot 2021-09-16 at 21 47 32" src="https://user-images.githubusercontent.com/84779829/133676558-63bbb36b-2843-4302-9e2b-0422b7ab99e2.png">

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
