### ISSUE TITLE
Graceful exit results in exit code 1

### ISSUE THREAD

**Issue by paladincorners** [owncloud/ocis#7730]
## Describe the bug
When gracefully stopping ocis server, e.g., with SIGTERM, the process exits with code 1, which typically signifies some error. The  process should exit with a more appropriate code (e.g., 0 or even 143) to signify a graceful exit, unless there actually was some error while performing shutdown tasks (such as writing the decomposed fs to disk).

## Steps to reproduce
1. Launch ocis, e.g., in docker
2. Issue SIGTERM (e.g., with docker stop ...)
3. Observe exit code (e.g., with docker ps -a)

## Expected behavior
Exit code should be 0 or 143 (for SIGTERM)

## Actual behavior
Exit code is 1.

## Setup
ocis running in docker

**Comment by 2403905** [comment]
Could you place more information about how you performed your test? Are you waiting until the ocis runs successfully in a container? The docker stop command forces the SIGKILL after 10 seconds. Possibly in your case, the ocis doesn't have time to finish gracefully.
