### ISSUE TITLE
Cannot access owncloud via WebDAV

### ISSUE THREAD

**Issue by aLitschgy** [owncloud/ocis#7731]
I have no idea of the address of my webDAV endpoint
I red that I'm supposed to look at https://{domain}/graph/1.0/me/drive but this doesn't return anything so I have no idea of my space address to access it via file explorer.

**Comment by SwikritiT** [comment]
I think the endpoint should be `https://{domain}/graph/v1.0/me/drives`

**Comment by michaelstingl** [comment]
Planned to show in web UI:
- https://github.com/owncloud/web/issues/9714

**Comment by aLitschgy** [comment]
> I think the endpoint should be `https://{domain}/graph/v1.0/me/drives`

I've got a 401 error on this page even though I've logged in before.
