### ISSUE TITLE
[QA] Flaky API tests due to `index is closed` error in search service

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#7757]
Search and tag related API tests can fail sometimes even having a wait time of 5 seconds. It can be either search indexing was not complete in 5 seconds or there was some problem with the search service.

 
The server log has the following errors:
```
[ociswrapper] Restarting oCIS server...
...
{"level":"error","service":"search","error":"jwt: secret for signing payloads is not defined in config","time":"2023-11-21T12:55:13.263649053Z","message":"Error initializing search service"}
[ociswrapper] oCIS server is ready to accept requests
{"level":"error","service":"search","error":"index is closed","Id":{"storage_id":"8ee8176d-1375-452e-bdc2-b35df8eef9d2","opaque_id":"5277a738-2587-4072-8bae-b5cbb3c4624b","space_id":"c511a724-bf96-4d6f-a512-bfb28596bbac"},"time":"2023-11-20T01:40:36.928492352Z","message":"failed to remove item from index"}
{"level":"error","service":"search","error":"index is closed","time":"2023-11-20T01:40:45.500509894Z","message":"error adding updating the resource in the index"}
{"level":"error","service":"search","error":"index is closed","time":"2023-11-20T01:40:45.500521726Z","message":"error getting document count from the index"}
```

Related issues/prs:
https://github.com/owncloud/ocis/issues/7693, https://github.com/owncloud/ocis/issues/7694
https://github.com/owncloud/ocis/pull/7707, https://github.com/owncloud/ocis/pull/7733

ocis server is started via `ociswrapper` which can restart the ocis server whenever needed. One of the speculations is that restart of ocis server caused the search service to have some issues thus leading to flaky tests.
 We need to find out if that really is the case.

CI builds:
https://drone.owncloud.com/owncloud/ocis/28941/14/3
https://drone.owncloud.com/owncloud/ocis/28935/14/5
https://drone.owncloud.com/owncloud/ocis/28926/27/7

**Comment by micbar** [comment]
> ocis server is started via ociswrapper which can restart the ocis server whenever needed. One of the speculations is that restart of ocis server caused the search service to have some issues thus leading to flaky tests.
We need to find out if that really is the case.

That sounds like a good hunch. Search indexing happens asynchronously. If we restart the ocis server in the single binary mode, the services have no graceful shutdown.

**Comment by saw-jan** [comment]
PR #7759 was not enough. Tests can still fail
https://drone.owncloud.com/owncloud/ocis/29026/14/5
https://drone.owncloud.com/owncloud/ocis/29023/26/7

**Comment by saw-jan** [comment]
Sometimes for search service the `jwt_secret` can be empty.
```json
{"level":"error","service":"search","error":"jwt: secret for signing payloads is not defined in config","time":"2023-11-22T07:50:20.387043282Z","message":"Error initializing search service"}
```
CC @kobergj @aduffeck

**Comment by saw-jan** [comment]
There might be something not right with the search service. It usually happen after restart by ociswrapper but I can see jwt_secret in the config file
```yml
token_manager:
  jwt_secret: <some-secret-value>
```
E.g. build https://drone.owncloud.com/owncloud/ocis/29068/2/4
