### ISSUE TITLE
Update api test to use graph api for changing system language

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7764]
Language change using graph:  https://github.com/owncloud/ocis/pull/7817
`curl --insecure -XPATCH -uadmin:admin https://localhost:9200/graph/v1.0/me -d '{"preferredLanguage":"de"}' `
change Given step `And user "Brian" has switched the system language to "es"` to using graph

**Comment by SwikritiT** [comment]
@ScharfViktor for `Language change using graph:` are you suggesting that we change the step `And user "Brian" has switched the system language to "es"` to use graph API internally? or should we cover both the cases for 

```
And user "Brian" has switched the system language to "es" using the Graph API
```

```
And user "Brian" has switched the system language to "es" using the settings API
```

**Comment by SwikritiT** [comment]
@ScharfViktor has the feature for changing language using graph already been implemented? I'm getting 500
```console
curl -XPOST -uadmin:admin https://localhost:9200/graph/v1.0/me -d '{"preferredLanguage":"de"}' -vk 
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:9200...
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=Acme Corp; CN=OCIS
*  start date: Nov 28 05:59:51 2023 GMT
*  expire date: Nov 27 05:59:51 2024 GMT
*  issuer: O=Acme Corp; CN=OCIS
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* Server auth using Basic with user 'admin'
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /graph/v1.0/me HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 26
> Content-Type: application/x-www-form-urlencoded
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< Allow: GET
< Allow: PATCH
< Content-Length: 0
< Content-Security-Policy: frame-ancestors 'none'
< Date: Tue, 28 Nov 2023 06:04:08 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Graph-Version: 5.0.0-alpha.3+4a94388a25
< X-Request-Id: swikriti-OptiPlex-3070/QBrGWJWQhf-000493
< 
* Connection #0 to host localhost left intact


```

**Comment by SwikritiT** [comment]
> @ScharfViktor has the feature for changing language using graph already been implemented? I'm getting 500
> 
> ```
> curl -XPOST -uadmin:admin https://localhost:9200/graph/v1.0/me -d '{"preferredLanguage":"de"}' -vk 
> Note: Unnecessary use of -X or --request, POST is already inferred.
> *   Trying 127.0.0.1:9200...
> * Connected to localhost (127.0.0.1) port 9200 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * TLSv1.0 (OUT), TLS header, Certificate Status (22):
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS header, Finished (20):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.2 (OUT), TLS header, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
> * ALPN, server did not agree to a protocol
> * Server certificate:
> *  subject: O=Acme Corp; CN=OCIS
> *  start date: Nov 28 05:59:51 2023 GMT
> *  expire date: Nov 27 05:59:51 2024 GMT
> *  issuer: O=Acme Corp; CN=OCIS
> *  SSL certificate verify result: self-signed certificate (18), continuing anyway.
> * Server auth using Basic with user 'admin'
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> > POST /graph/v1.0/me HTTP/1.1
> > Host: localhost:9200
> > Authorization: Basic YWRtaW46YWRtaW4=
> > User-Agent: curl/7.81.0
> > Accept: */*
> > Content-Length: 26
> > Content-Type: application/x-www-form-urlencoded
> > 
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 405 Method Not Allowed
> < Allow: GET
> < Allow: PATCH
> < Content-Length: 0
> < Content-Security-Policy: frame-ancestors 'none'
> < Date: Tue, 28 Nov 2023 06:04:08 GMT
> < Vary: Origin
> < X-Content-Type-Options: nosniff
> < X-Frame-Options: DENY
> < X-Graph-Version: 5.0.0-alpha.3+4a94388a25
> < X-Request-Id: swikriti-OptiPlex-3070/QBrGWJWQhf-000493
> < 
> * Connection #0 to host localhost left intact
> ```

The request is PATCH. It works.

**Comment by SwikritiT** [comment]
I've broken down all the checklists of this issue to be separate issues 
- https://github.com/owncloud/ocis/issues/7823
- https://github.com/owncloud/ocis/issues/7824
- https://github.com/owncloud/ocis/issues/7825
- https://github.com/owncloud/ocis/issues/7826
- https://github.com/owncloud/ocis/issues/7827

and updated this one as well

**Comment by ScharfViktor** [comment]
> @ScharfViktor for `Language change using graph:` are you suggesting that we change the step `And user "Brian" has switched the system language to "es"` to use graph API entirely ? or should we cover both the cases for

done here #7817
