### ISSUE TITLE
Show geogebra thumbnails

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#7768]
# Description

## User Stories

* > As a user, I want to see preview images for my geogebra notes files so that i can get a quick perception of the content before opening it.

## Value

Integration in GeoGebra creates a more unified UX for the whole platform

## Acceptance Criteria

- [x] GeoGebra Notes mime-type and file extension are known to the backend
- [x] GeoGebra Notes Files show up in the file list, and file details view with their preview image

## File example

https://cloud.owncloud.com/s/Pa39gtzeoRQVfOL

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by dragonchaser** [comment]
.ggs Downloaded from the example is basically a zip-archive `../21.11.2023 11_18.ggs: Zip archive data, at least v2.0 to extract, compression method=deflate` and contains a thumbnail, is it legit to use that for display?

**Comment by kulmann** [comment]
> .ggs Downloaded from the example is basically a zip-archive `../21.11.2023 11_18.ggs: Zip archive data, at least v2.0 to extract, compression method=deflate` and contains a thumbnail, is it legit to use that for display?

Yes! Nice finding. Just use it 👍

**Comment by dragonchaser** [comment]
![image](https://github.com/owncloud/ocis/assets/1058116/042ca5ea-5714-4752-bc83-25290906500f)

Just need to add tests...
