### ISSUE TITLE
Moving a file out of folder removes the versions

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#777]
1. start ocis with OWNCLOUD storage
1. create a folder
1. upload a file into that folder
1. overwrite the file to create a version
1. move the file out of the folder to the root
1. check the versions => no versions are shown

**Comment by individual-it** [comment]
with point `4` I mean to upload a new version with a normal `PUT` request.
How does it behaves if you upload the file again?

**Comment by saw-jan** [comment]
Tested with ocis 5.0.0
File versions are there

Test coverage extended in https://github.com/owncloud/ocis/pull/8183
So closing this here.
