### ISSUE TITLE
FRONTEND_AUTO_ACCEPT_SHARES env doesn't work

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#7792]
## Describe the bug
set auto accept using env `FRONTEND_AUTO_ACCEPT_SHARES` false doesn't disable auto accept share functionality
![Screenshot from 2023-11-23 17-04-18](https://github.com/owncloud/ocis/assets/54478846/45d4c190-a5cd-4cb1-955e-69679d23731b)

## Expected behavior
The share should not be auto-accepted on the receiver side when sharer shares the resources

## Actual behavior
On receiver side shared resource has auto accepted and no decline option is visible

## Setup
1. clone web and ocis from github 
2. build web with command
    - make dist
3. build ocis
   - make generate
   - make -C ocis build
4. Initialize OCIS configuration
    - IDM_ADMIN_PASSWORD='admin' ./ocis/bin/ocis init --insecure true
5. Run Ocis
    - OCIS_LOG_LEVEL=debug PROXY_ENABLE_BASIC_AUTH=true IDM_CREATE_DEMO_USERS=true WEB_ASSET_PATH=path/to/web/dist OCIS_INSECURE=true FRONTEND_AUTO_ACCEPT_SHARES=false ./ocis/bin/ocis server 

<details>
<p>

```console
ocis=master
web=master
```

</p>
</details>

**Comment by ScharfViktor** [comment]
sorry but I cannot confirm it: works fine to me

<img width="1326" alt="Screenshot 2023-11-24 at 15 44 08" src="https://github.com/owncloud/ocis/assets/84779829/b88a5474-1575-4603-9ef1-454c6449ff51">

**Comment by amrita-shrestha** [comment]
so declined share means uncheck enable sync

**Comment by ScharfViktor** [comment]
> If the context menu has Enable sync item then it means the share is not accepted yet (i.e. Pending state)
And Disable sync should mean decline share

Yes, correct  :thumbsup:
