### ISSUE TITLE
Add api tests for deleting link password

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#7823]
## Test scenarios to add
- only Admin and Space Admin can remove the password in read-only public link https://github.com/owncloud/ocis/pull/7540
- all users can remove their password if set the permission `0` (invite people) https://github.com/owncloud/ocis/pull/7894

## Related Bugs
- https://github.com/owncloud/ocis/issues/7821

**Comment by SagarGi** [comment]
Related PRs for the test coverage has been merged. So closing this issue.
