### ISSUE TITLE
Add API tests for hide file versions for share receivers

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#7824]
## Test scenario to add 
- [x] Hide file versions for share receivers https://github.com/owncloud/ocis/issues/7738 https://github.com/owncloud/ocis/pull/8013
- [x] share a file inside of a project space and check if the file versions are visible https://github.com/owncloud/ocis/pull/7829
  - Editor
  - Viewer
  - All
- [x] share a space and check if versions of files inside are visible https://github.com/owncloud/ocis/pull/7969
  - Manager
  - Editor
  - Viewer
 - [x] back port https://github.com/owncloud/ocis/pull/7980
 - [x]  back port https://github.com/owncloud/ocis/pull/8172

**Comment by saw-jan** [comment]
We can add check and add the coverage for https://github.com/owncloud/ocis/issues/7738 and then close this issue
