### ISSUE TITLE
Add API test coverage for mountpoints for pending and declined shares

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#7827]
## Test scenarios to add
- Coverage for Mountpoints for pending and declined shares 

## Related Bugs

**Comment by PrajwolAmatya** [comment]
Need to wait for https://github.com/owncloud/ocis/issues/7702

**Comment by PrajwolAmatya** [comment]
According to this https://github.com/owncloud/ocis/issues/7702#issuecomment-1833397409 it is unable to navigate to pending and declined share. Also there's this PR https://github.com/owncloud/web/pull/10097 that disables router links for pending and declined shares.
