### ISSUE TITLE
[sharing-ng] trying to share a resource with a user that its already shared with causes a 500 error

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#7842]
## Describe the bug
When sharing a resource that is already shared with the same user

## Steps to reproduce
1. share and item to a user using the GraphAPI `invite` endpoint
2. do the same with the same user

## Expected behavior
409 or 403 response

## Actual behavior
500 response

CC @fschade

**Comment by rhafer** [comment]
related #6993
