### ISSUE TITLE
Listing of Trashbin Items Slow

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#7844]
Based on findings in https://github.com/owncloud/enterprise/issues/6213 it is understood that listing the trashbin items is taking too long if a significant amount of files were deleted and are in the trashbin.

The code is known to be not optimized. So the action to undertake is

- [ ] Check the code and find the bottlenecks 
- [ ] Find a way to increase the listing performance by (probably) parallelize the reading of the items from the trashbin structure
- [ ] Propose a as small as possible code patch to fix the behaviour and increase listing performance that can be applied to the v4 code branch.

**Comment by dragonchaser** [comment]
With #4374 & delay (vm nfs-server, delay via `tc`):

| delay | edge cold | edge warm | pr cold | pr warm |
| -------- | ---------------| ----------------- | ---------- | ------------ |
|2.5ms | 33.5ms | 12.7ms | 20ms | 10.29ms |

**Comment by dragonchaser** [comment]
After parallelizing the globbing we end up with the following values:

| delay | edge cold | edge warm | pr cold | pr warm |
| -------- | ---------------| ----------------- | ---------- | ------------ |
|2.5ms | 28.46s | 10.58s | 703ms | 280ms  |

**Comment by micbar** [comment]
fixed and relased with ocis v4.0.4
