### ISSUE TITLE
CLI Tool to Handle Trashbin Item Restore 

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#7845]
As an admin of a larger instance I want to be able to help users to restore files from the trashbin of their instance if they can not do it in self service.

For that, a CLI tool would be handsome that is able to 
- list the trashbin content of a certain user
- restore all files in the users trashbin
- optional: restore by name selected files  

The CLI tool could be completely separate from oCIS but should be maintained in the oCIS repo with the main code. A backport to v4 needs to be provided.

**Comment by dragotin** [comment]
Reference: https://github.com/owncloud/enterprise/issues/6213

**Comment by 2403905** [comment]
@micbar Should we allow overwriting existing files by demand or better add some suffixes like `(1)` or (restored 1)?

**Comment by wkloucek** [comment]
> @micbar @wkloucek Should we allow overwriting existing files by demand or better add some suffixes like `(1)` or (restored 1)?

How do we handle this on a regular trashbin restore? I wouldn't expect it to behave differently, right?

**Comment by 2403905** [comment]
Now we ask for action  [skip][replace][keep both]. Let's use a similar dialog in cli!

**Comment by micbar** [comment]
Still working.

Backporting needs more efforts.

**Comment by micbar** [comment]
backport was also merged.
