### ISSUE TITLE
[sharing-ng] update/disable virtual space returns 500 error

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#7881]
## Describe the bug
Trying to send a PATCH or DELETE to a virtual space (Shares) throws an 500 error

## Expected behavior
405 HTTP response

## Actual behavior
HTTP 500
`{"error":{"code":"generalException","innererror":{"date":"2023-12-05T09:26:13Z","request-id":"eb2eb607293d/ADjidDU61G-030279"},"message":"grpc error"}}`

**Comment by individual-it** [comment]
See also https://github.com/owncloud/ocis/issues/6993

**Comment by rhafer** [comment]
#8235 fixes the reponse code for now.

AFAIK `DELETE /v1.0/drives/<drive-id-of-a-received-share>` is supposed to be use for unmounting a share at some point. (Probably part of #7885)
