### ISSUE TITLE
Deprecate sub par registries, stores and caches

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#7942]
We learned that some implementations do not scale in a kubernetes cluster. We should mark them as deprecated and log a warning? when they are configured. Preferably, before the ocis 5 release.

**Comment by wkloucek** [comment]
why not deprecate all except the ones we know that are reliably working / are proven to be scalable?

I know following to work as of oCIS 4:
- registry: etcd
- cache: redis
- store: redis

For oCIS 5 I don't have these information yet.

**Comment by butonic** [comment]
I would leave:
- registry:
  - memory, for testing
  - nats, because it is the only built in registrd that works with the cli
  - etcd, because it works
  get rid of consul (unused) and kubernetes (too slow)
- store/cache:
  - memory, for testing
  - noop, used - actually we should rip out the code where we use noop, eg the gateway registry, but that is a different issue
  - redis, because it works
  - redis-sentinel, needed for scaling redis
  - nats-js, for a build in implementation
  get rid of ocmem (unused? or move to micro?)

so ... we can only really deprecate the consul and kubernetes registries and ocmem store?

**Comment by wkloucek** [comment]
> nats, because it is the only built in registrd that works with the cli

you mean `natsjs` right?

> noop

I didn't think about this as a actual cache / store implementation, but obviously it is :laughing: We're actually using it for PROD purposes in the Helm Chart like you said

> redis, because it works

how do you know that? I though we've always used `redis-sentinel`

> redis-sentinel, needed for scaling redis

actually it's only HA (failover) not scaling

**Comment by wkloucek** [comment]
I propose:
- registry (MICRO_REGISTRY): ~nats~, ~kubernetes~, ~etcd~, ~consul~, ~memory~, natsjs (default)
- cache / store (OCIS_CACHE_STORE): memory, ~ocmem~, ~etcd~, ~redis~, redis-sentinel, nats-js (default), ~noop~

**Comment by wkloucek** [comment]
ahhh I don't know if we can really get rid of `noop`...

**Comment by wkloucek** [comment]
on question to ask if we really should keep `memory` or `ocmem`. Isn`t  `ocmem` the more advanced implementation (max number of keys limit, TTL, ...)?

**Comment by kobergj** [comment]
@butonic @wkloucek @micbar one thing open to discuss: Do we want to keep supporting `etcd`?

**Comment by wkloucek** [comment]
As a sidenote: using the graph api as a provisioning api requires setting the services registry to something non-external, eg `memory`.

The same applies when you plan to run the webfinger service standalone (without oCIS proxy)

**Comment by dj4oC** [comment]
@tbsbdr @dragotin @micbar 

Can I ask for a product decision on that? We have a Training next week and don't want to mention unsupported components. :THX:

**Comment by butonic** [comment]
we still support a lot of registry implementations:
```go
	rRegistry "github.com/cs3org/reva/v2/pkg/registry"
	consulr "github.com/go-micro/plugins/v4/registry/consul"
	etcdr "github.com/go-micro/plugins/v4/registry/etcd"
	kubernetesr "github.com/go-micro/plugins/v4/registry/kubernetes"
	mdnsr "github.com/go-micro/plugins/v4/registry/mdns"
	memr "github.com/go-micro/plugins/v4/registry/memory"
	natsr "github.com/go-micro/plugins/v4/registry/nats"
	"github.com/owncloud/ocis/v2/ocis-pkg/natsjsregistry"
```

The default now is `nats-js-kv`

the available cache implementations are defined in reva/pkg/store:
```go
	// TypeMemory represents memory stores
	TypeMemory = "memory"
	// TypeNoop represents noop stores
	TypeNoop = "noop"
	// TypeEtcd represents etcd stores
	TypeEtcd = "etcd"
	// TypeRedis represents redis stores
	TypeRedis = "redis"
	// TypeRedisSentinel represents redis-sentinel stores
	TypeRedisSentinel = "redis-sentinel"
	// TypeOCMem represents ocmem stores
	TypeOCMem = "ocmem"
	// TypeNatsJS represents nats-js stores
	TypeNatsJS = "nats-js"
	// TypeNatsJSKV represents nats-js-kv stores
	TypeNatsJSKV = "nats-js-kv"
```

**Comment by micbar** [comment]
@butonic i think we decided that we only keep nats-js-kv and memory as registries.

and redis-sentinel and nats-js-kv and noop as a cache store.

**Comment by micbar** [comment]
Docs have been done with 5.0.0 Release.
