### ISSUE TITLE
[QA][Sharing NG] ApiTest: sent sharing invitation

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7947]
https://owncloud.dev/libre-graph-api/#/drives.permissions/Invite

sync enabled and disabled introduced in ocis with the help of env maybe we need to tests this also (ticket: https://github.com/owncloud/ocis/issues/8318)

- [x] invite users/group with: @grgprarup 
  - [x] different permissions
    - [x] to user https://github.com/owncloud/ocis/pull/8046
    - [x] to group https://github.com/owncloud/ocis/pull/8047
  - [x] different roles 
    - [x] to user https://github.com/owncloud/ocis/pull/7984
    - [x] to group https://github.com/owncloud/ocis/pull/8009
    - [x] with expiration date https://github.com/owncloud/ocis/pull/8092
- [x] invite users: @grgprarup 
  - [x] normal user https://github.com/owncloud/ocis/pull/8226
  ~- [ ] multiple users (not implemented yet)~
  - [x] disabled user https://github.com/owncloud/ocis/pull/8139
  - [x] deleted user https://github.com/owncloud/ocis/pull/8110, https://github.com/owncloud/ocis/pull/8179
  - [x] wrong `objectId` -> 400 https://github.com/owncloud/ocis/pull/8129
  - [x] empty  `objectId` -> 400 https://github.com/owncloud/ocis/pull/8133, https://github.com/owncloud/ocis/pull/8189
  - [x] wrong `@libre.graph.recipient.type` -> 404 https://github.com/owncloud/ocis/pull/8136
  - [x] empty `@libre.graph.recipient.type` -> 404 https://github.com/owncloud/ocis/pull/8137
  - [x] already shared to the user -> 409 https://github.com/owncloud/ocis/pull/8308
  - [x] resource from project space
    - [x] user/group https://github.com/owncloud/ocis/pull/8327
  - [x] share deleted resource with user/group -> 404 https://github.com/owncloud/ocis/pull/8326
- [x] invite groups with different permissions and roles @PrajwolAmatya 
  - [x] normal group https://github.com/owncloud/ocis/pull/8226
  - [x] deleted group -> 400 https://github.com/owncloud/ocis/pull/8166
  - [x] unknown group -> 400 https://github.com/owncloud/ocis/pull/8175
  - [x] already shared to the group -> 409 https://github.com/owncloud/ocis/pull/8181
  - [x] multiple group https://github.com/owncloud/ocis/pull/8167
 - [x] invite groups and user in one request (Not possible: https://github.com/owncloud/ocis/pull/8019) https://github.com/owncloud/ocis/pull/8168
- [x] try to share `file`/`folder` with not available roles (See [comment](https://github.com/owncloud/ocis/pull/8175#discussion_r1462779871), [comment](https://github.com/owncloud/ocis/pull/8175#discussion_r1464286878)) @PrajwolAmatya  https://github.com/owncloud/ocis/pull/8302
https://github.com/owncloud/ocis/pull/8347
- [x] share spaces @PrajwolAmatya 
  - [x] share project-space with different roles https://github.com/owncloud/ocis/pull/8304
  - [x] share disabled/deleted space -> 404 https://github.com/owncloud/ocis/pull/8319 
  - [x] share to group https://github.com/owncloud/ocis/pull/8328
  - [ ] try to share (Personal/Shares) drive with different roles
- [x] reshare @PrajwolAmatya -> No new tests to be added for resharing. See [comment](https://github.com/owncloud/ocis/pull/8275#pullrequestreview-1840955948) https://github.com/owncloud/ocis/issues/8335
    - [x] user
      - [x] normal user https://github.com/owncloud/ocis/pull/8114 https://github.com/owncloud/ocis/pull/8275
      - [x] higher roles https://github.com/owncloud/ocis/pull/8147
      ~- [ ] parent sharer deleted~
      ~- [ ] parent share disabled~
    - ~[ ] group~ https://github.com/owncloud/ocis/pull/8123

**Comment by PrajwolAmatya** [comment]
All tests have been covered. So, closing this issue.

**Comment by PrajwolAmatya** [comment]
Re-opening this issue, as I have added tasks for two cases, sharing Personal and Shares space with different roles.

**Comment by amrita-shrestha** [comment]
> Re-opening this issue, as I have added tasks for two cases, sharing Personal and Shares space with different roles.

@PrajwolAmatya do you mean by Personal and share drive? Or you mean by project with name Share and Personal

**Comment by PrajwolAmatya** [comment]
> @PrajwolAmatya do you mean by Personal and share drive? Or you mean by project with name Share and Personal

Its Personal and Shares drive.

**Comment by saw-jan** [comment]
> @PrajwolAmatya do you mean by Personal and share drive? Or you mean by project/space with name Share and Personal

Sorry, that was me who edited the list. The case is to try to share Personal and Shares drive

**Comment by amrita-shrestha** [comment]
> Re-opening this issue, as I have added tasks for two cases, sharing Personal and Shares space with different roles.

Share invite on personal and virtual drive has bug, all bug report is listed on this issue-8428. So closing this issue
