### ISSUE TITLE
Update IDP and dependencies

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#7957]
# Description

We are approaching a new major release and need to keep the IdP dependencies up to date and free of vulnerabilities.

**Comment by kulmann** [comment]
Asked the kpop devs if we can remove `cldr` (which brings in the outdated `xmldom` package`) from the dependencies upstream, see https://github.com/Kopano-dev/kpop/issues/40

**Comment by micbar** [comment]
@kulmann Assigning you to avoid confusion in the ocis team.

**Comment by kulmann** [comment]
We made https://github.com/owncloud/ocis/pull/7988 to mitigate the security concerns. @rhafer voiced his opinion here https://github.com/owncloud/ocis/pull/7988#issuecomment-1859824376 to stay in sync with upstream as much as possible. I'm not in favour of that "busy work". Needs a decision.

**Comment by micbar** [comment]
Fine for now.

**Comment by rhafer** [comment]
> nobody here has in depth understanding of the lico ui

That alone already sound like a really good reason to stay as close to upstream as possible IMO. Keeping it diverging further makes maintenance even harder.

 > there are plans to switch to Authelia

We have been mumbling about that for a while now. But there has been very little progress, nor a full understanding what we actually need for that. And we'll have to live with lico for at least the whole 5.0.0 lifetime.
