### ISSUE TITLE
Error when using builtin IDP

### ISSUE THREAD

**Issue by farapholch** [owncloud/ocis#7959]
## Describe the bug
Using the builtin IDP with external LDAP connection and defining environment variables referenced in https://doc.owncloud.com/ocis/next/deployment/services/s-list/idp.html:

`
ldap bind request BindDN outside of Database tree error=null bind_dn=CN=ServiceAccount,OU=ServiceAccounts,OU=Domain,OU=Data,DC=Domain,DC=local line=github.com/owncloud/ocis/v2/ocis-pkg/log/logrus_wrapper.go:50 op=bind remote_addr=10.128.57.33:40626 service=idm
`

## Steps to reproduce
1. Using ocis-charts 0.5.0
2. Configure IDP for using LDAP.
3. IDM pod displays error message.

## Expected behavior
Should be able to login using builtin IDP.

## Actual behavior
Login screen:
![image](https://github.com/owncloud/ocis/assets/52049523/e30e10fb-1d4f-4874-a976-e99db22f354e)

## Setup

Defining env var:
 
OCIS_LDAP_BIND_DN= CN=SyncAccount,OU=ServiceAccounts,OU=XX,OU=Data,DC=XX,DC=local
OCIS_LDAP_URI= ldaps://ldaps.domain     
OCIS_LDAP_BIND_PASSWORD
             valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.ldapBindSecret" . }}
                  key: reva-ldap-bind-password

OCIS_LDAP_USER_BASE_DN: OU=Users,OU=OU,OU=Data,DC=Domain,DC=local
OCIS_LDAP_USER_SCHEMA_USERNAME: samAccountName
OCIS_LDAP_USER_FILTER: (&(objectclass=user)(memberOf=cn=GroupName,ou=MemberGroups,ou=Groups,ou=ouName,ou=Data,dc=domain,dc=local))

**Comment by rhafer** [comment]
Please provide all the other config vars you're setting. I guess you want to use some external LDAP server? Just setting `OCIS_LDAP_BIND_DN` is not enough for that.

**Comment by Farapholch** [comment]
@rhafer thanks, yes I've updated with more config values.

**Comment by rhafer** [comment]
@Farapholch So you seem to be using helm. Is that using the charts from https://github.com/owncloud/ocis-charts or are that some self created charts? Please provide more details about what you're actually trying to achieve.

I don't know exactly what is wrong with your configuration, but if you're using an external LDAP server the `idm` service should not be running at all (the owncloud/ocis-charts helm charts should take care of that if properly configured). The fact the some other service even tries to contact the `idm` service also indicates a problem with the config.

**Comment by Farapholch** [comment]
@rhafer Thanks for answering. Ah yes that's correct, using the ocis-charts 0.5.0 and adjusting the idp deployment with env variables . I'm trying to use external ldap without the use of an external idp, but as I read now in the chart it needs both I guess, I was hoping to use the internal idp for it, or maybe I can configure it?

We are experiencing redirect issues when placing oCIS with keycloak behind a reverse proxy when authenticating with keycloak due to browser switching between the sites and the auth-cookie is somehow lost.

**Comment by rhafer** [comment]
> I'm trying to use external ldap without the use of an external idp, but as I read now in the chart it needs both I guess, I was hoping to use the internal idp for it, or maybe I can configure it?

Yes. The AFAICT the charts currently only support the case where both are external or both are internal. For other setup I think you'd need to change the charts.

I am closing this issue now, as it does not seem to indicate an issue with ocis itself. It sounds more like configuration problem to me. You might wanna ask you question on central.owncloud.com or our matix channel (https://app.element.io/#/room/#ocis:matrix.org)
