### ISSUE TITLE
default config given on idp documentation is not working

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#7972]
## Describe the bug
when using example config from [ocis idp doc](https://owncloud.dev/services/idp/#example-yaml-config), ocis crashes.

## Steps to reproduce
1. copy example idp config from doc to ~/.ocis/config
2. build and run ocis

## Expected behavior
ocis should run without error

## Actual behavior
ocis throws error
```bash
The ldap bind_password has not been set properly in your config for idp. Make sure your /home/user/.ocis/config config contains the proper values (e.g. by running ocis init or setting it manually in the config/corresponding environment variable).
```
when i give the `bind_password` that is in `~/.ocis/config/ocis.yaml`
it again crashes with following message.
```json
{
"level":"fatal",
"service":"idp",
"error":"failed to read CA certificate(s) from '~/.ocis/idm/ldap.crt': open ~/.ocis/idm/ldap.crt: no such file or directory",
"time":"2023-12-14T14:33:54+05:45",
"line":"/home/user/ocis/services/idp/pkg/service/v0/service.go:88",
"message":"could not bootstrap idp"
}
```

in the example it uses path `~/.ocis/idm/ldap.crt` in `cacert` but ocis dose not take that as a valid path. but giving the full path (`/home/user/.ocis/idm/ldap.crt`) works.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS latest master
```

</p>
</details>

**Comment by rhafer** [comment]
Not sure yet how the `~` ends up in the examples, but that is wrong (go doesn't do any `~` expansion).

Also I think we should generate the example files using the release build flags (setting BaseDataPathType and friends) so that the default basepath would be `/var/lib/ocis`  instead of the home dir. (Or maybe it's time to default BaseDataPathType to `path`)

**Comment by brandon1024** [comment]
Agreed, @nirajacharya2 you might want to create an issue in [owncloud/docs](https://github.com/owncloud/docs)?

**Comment by mmattel** [comment]
* I am reopening this issue as the fix must be as @rhafer said made here.
* I will also close the docs issue, as admin and dev docs gets the data from the ocis repo automatically.
* Removing the documentation label as it is a code bug

Just to remind, it is about:
`~/.ocis/idm/ldap.crt` ❌ 
`/home/user/.ocis/idm/ldap.crt` ✔️ 

@micbar @rhafer

**Comment by dragonchaser** [comment]
Example configs should not contain home directory paths, but `/var/ocis` and `/etc/ocis` references.
