### ISSUE TITLE
Simplified Chinese language support

### ISSUE THREAD

**Issue by jugggao** [owncloud/ocis#7999]
Is there any plan to add support for simplified Chinese?

**Comment by phil-davis** [comment]
@kulmann https://github.com/owncloud/web/issues/10217
translation-sync for web failed last night related to `zh-Hans`
does something need to be tweaked/removed to get rid of that error?

**Comment by kulmann** [comment]
I'll look into it today

**Comment by kulmann** [comment]
@jugggao we've moved the `Chinese Simplified` (zh-Hans) translations into `Chinese` (zh) in transifex, since we only deal with language codes in translations. We've added Chinese to web, and that will be part of the ocis 5.0.0 release. 🥳

**Comment by jugggao** [comment]
Thank you so much for your support, It's very useful for me!🥳

**Comment by kulmann** [comment]
> Thank you so much for your support, It's very useful for me!🥳

Our pleasure - thanks for bringing it up!

I don't know if you were already involved with translations, but in any case, if you want to help with Chinese community translations, you can join the `ownCloud Web` project here and help translating. https://explore.transifex.com/owncloud-org/owncloud-web/

As you can see there, Chinese (= Simplified) has a coverage of 85%. That is quite good, but you will still find English strings in the UI. ;-)
