### ISSUE TITLE
[reva] owncloud storage sharing with guest accounts

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#8]
Instead of thinking of a black and white solution where a storage provider is either using users that are known to the underlying os or not we should implement the storing of metadata / share information as acls as an optional step when the user is known. We need to be able to store shares for unknown users / guest accounts anyway. Instead of trying to find a way how we can create guest accounts on the fly so they get a non colliding userid in the filesystem (by adding them to an ldap server under our control) we should thing about that being the primary use case. If the user happens to be available in the os we can use a tighter filesystem integration and actuallly store eg. ACLs.

We need to try hard to not recreate a situation where eg acls and non native acls need to be kept in sync.

Also some maintenance considerations:
- How can we convert a system user to a virtual user and back?
- How can we split share metadata in acls and additional metadata?

for the ownCloud storage provider I started with putting NFSv4 like ACLs into the user namespace of extended attributes. This can be an option when trying to store share permissions for virtual users (that should be identified by a uuid with a seperate lookup service, maybe based on scim).

note: the `user` namespace of extended attributes can be edited by any user with write permissions. the `system` namespace might be an option if only root should be able change the attributes. for eos cern plans to implement a dedicated set of extended attributes that users cannot control.

tbc

**Comment by butonic** [comment]
OpenID Connect has a discovery mechanism to look up the issuer for a given user: https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery
or mor specifically for emails:
https://openid.net/specs/openid-connect-discovery-1_0.html#EmailSyntax

If the guest email issuer implements the oidc federation we can use it to dynamically establish a trust relationship: https://openid.net/specs/openid-connect-federation-1_0.html

If it does (or in case we want to stay in control of guest accounts) we can omit this optional step and handle guest accounts in a dedicated IdP that is fully under our control.

There is even a draft for SCIM integration: https://openid.net/specs/openid-connect-scim-profile-1_0.html which we could use to provision guest accounts.

**Comment by refs** [comment]
belongs to reva
