### ISSUE TITLE
Creating a public link to a shared resource with the "invite people" role is broken

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8039]
5.0.0-beta.1+dc2f151eb4
8.0.0-beta.2

Steps: 
- user creates a public link to a file or folder with the `invite people` role in the shares space

or: 
- user creates a public link to a file or folder with the `viewer` role in the shares space (it works) and after that changes link to `invite people` role

Expected: creating and updating link with the `invite people` role works. it was possible in `4.0.0`

Actual: regression. it's not possible

creating:  `<statuscode>996</statuscode><message>grpc create public share request failed</message>`

updating: `</status><statuscode>996</statuscode><message>Error sending update request to public link provider: insufficient permissions to update that kind of share</message>`

https://github.com/owncloud/ocis/assets/84779829/d8eace68-99d8-4f40-b21b-ede428cc84c8

**Comment by micbar** [comment]
Do you mean creating a link (internal link) by selecting "only invited people"?

**Comment by ScharfViktor** [comment]
> Do you mean creating a link (internal link) by selecting "only invited people"?

Yes, it is creating or updating internal link issue

**Comment by kulmann** [comment]
Can't reproduce with ocis current master and web current `stable-8.0` 😱

**Comment by micbar** [comment]
Could have been broken on 5.0.0-beta.1

Can you re-test with 5.0.0-beta.2?

**Comment by ScharfViktor** [comment]
I could reproduce it on beta2


https://github.com/owncloud/ocis/assets/84779829/f246d46b-0712-458b-b0d7-4efef5a0847b

**Comment by rhafer** [comment]
I am able to reproduce it as well. (Seems to happen only when trying to create a link for a received share)

**Comment by rhafer** [comment]
https://github.com/cs3org/reva/pull/4429 should fix the issue. @micbar I'd appreciate a review.
