### ISSUE TITLE
Ocis-ldap. Admin cannot manage user quota using ldap

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8059]
5.0.0-beta.2
8.0.0-beta.2

Steps: 
- start ocis `5.0.0-beta.2` against ldap using https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_ldap/docker-compose.yml
- log in as `marie`  (needs first log in to change quota)
- using https://ldap.owncloud.test/ logs in as admin (login: cn=admin,dc=owncloud,dc=com, password: admin)
- add attribute `ownCloudQuota` and set value
- check marie's quota in the Administration Settings

Expected: we can manage user quota using ldap
Actual: quota is not changed (no restriction by default)

https://github.com/owncloud/ocis/assets/84779829/9a8cf6f5-b117-476c-b244-1e23ead9d93b

**Comment by rhafer** [comment]
The quota setting in ocis is not set via an LDAP Attribute (I have no idea where the `ownCloudQuota` attribute is coming from in the schema, must be something historic, we should clean that up to avoid confusion).

The quotas in ocis are actually a property of the personal/project spaces (you can set them via the user management, but the setting itself is stored with the spaces' attributes).

**Comment by butonic** [comment]
I think I added it for migration purposes. In oc10 it is read from LDAP. But we can drop it. The quota needs to be migrated in another way.
