### ISSUE TITLE
can edit files with view access in Collabora and Onlyoffice

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#8060]
## Describe the bug
when a user shares a file (`.ods, .odp, docx, xlsx, pptx`) with view permission 

## Steps to reproduce
1. run ocis with Collabora and Onlyoffice services
2. create a file (`.ods, .odp, docx, xlsx, pptx`) as `admin`
3. share it to `marie` with edit permission
4. open the file and don't close it as `marie`
5. change the permission to view as `admin`
6. make some edits and close it as `marie`
7. close the file as `marie`
8. open the file again as `marie` can still edit it with view permission

## Expected behavior
`marie` should not be able to edit the file

## Actual behavior
`marie` can still edit it with view permission

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

running ocis from web repos docker-compose file
```bash
OCIS_IMAGE=owncloud/ocis:5.0.0-beta.2 docker compose up traefik ocis wopiserver ocis-appprovider-onlyoffice onlyoffice ocis-appprovider-collabora collabora
```
<details>
<p>

```console
ownCloud Web UI 8.0.0-beta.2
Infinite Scale 5.0.0-beta.2 Community 
```

</p>
</details>

**Comment by ScharfViktor** [comment]
can confirm it:
 
Actual: 
admin changed role of the locked file and:
- got a message on the web that everything is fine
- but in the response  `<statuscode>996</statuscode><message>grpc update share request failed<message/>`
- permission is changed for admin but not changed for recipient


https://github.com/owncloud/ocis/assets/84779829/f8b68b7f-4c12-47b1-9174-c81006dc11e8

**Comment by ScharfViktor** [comment]
same issue: https://github.com/orgs/owncloud/projects/338

**Comment by micbar** [comment]
> same issue: https://github.com/orgs/owncloud/projects/338

Copy&Paste error?

**Comment by ScharfViktor** [comment]
> Copy&Paste error?

yes. I changed my comment. thanks

**Comment by 2403905** [comment]
@ScharfViktor FYI
 v4.0.5, v5.0.0-rc.1 
The public links don't have an issue if the behavior below is expected:
1. user A created file.odt and created a public link with an edit permissions 
2. user B opens the link.
3. user A changed permission to view -> no errors in a response, code 100
4. user B can edit a file until closes it. 
5. after reopen the file, user B can't edit.

**Comment by 2403905** [comment]
After the share has already updated the update the grant is failed because the file is locked. 
https://github.com/cs3org/reva/blob/bde86a38bd77917251a8bc97da5a1bd1dc4c85f2/pkg/storage/utils/decomposedfs/grants.go#L313
We can try to roll back the updateShare before returning an error or try to check locks before the updateShare.


The similar issue [https://github.com/owncloud/ocis/issues/6368](https://github.com/owncloud/ocis/issues/6368)

**Comment by micbar** [comment]
I sketched a possible approach in the linked ticket.

**Comment by butonic** [comment]
@aduffeck and @2403905 were digging into this. most recent comment with options going forward: https://github.com/owncloud/ocis/issues/8273#issuecomment-1918827974

@aduffeck is in posix wonderland. @2403905 are you looking into this? If so, assign yourself?

**Comment by 2403905** [comment]
@butonic If I am not mistaken @aduffeck added the fix [https://github.com/cs3org/reva/pull/4464](https://github.com/cs3org/reva/pull/4464) and now we shouldn't see an error when try to change the permission of the locked file.

**Comment by 2403905** [comment]
I retested. The bug is gone with the [Don't check locks grants](https://github.com/cs3org/reva/pull/4464) changes.
