### ISSUE TITLE
Could not use "Spaces" feature with 's3ng' storage driver

### ISSUE THREAD

**Issue by inferno-umar** [owncloud/ocis#8064]
Infinite Scale Spaces feature not working when storage is `STORAGE_USERS_DRIVER=s3ng`.
Other file operations do work using this s3ng setup.

This is how it looks like when I visit spaces page
![image](https://github.com/owncloud/ocis/assets/70754989/98935a8e-08c5-4593-9b52-4b6d70e05f15)

VERSION ocis:5.0.0-beta.1

Here is my few env variables
```
STORAGE_USERS_DRIVER: s3ng
STORAGE_USERS_S3NG_ACCESS_KEY: <ACCESS_KEY>
STORAGE_USERS_S3NG_SECRET_KEY: <SECRET_KEY>
STORAGE_USERS_S3NG_ENDPOINT: https://s3.pingolia.com
STORAGE_USERS_S3NG_BUCKET: <BUCKET_NAME>
GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
GRAPH_USERNAME_MATCH: "none"
```

**Comment by inferno-umar** [comment]
Spaces must be compatible with Software level storage systems like S3 to support large scale deployments.

**Comment by micbar** [comment]
Can you please re test on our continuous deployment instance?

we have the spaces feature up and running in PROD with S3NG.

please be aware that you need to have the admin or space admin user role to create spaces. 

Log in as admin and check the Admin UI users view. There you can see the user roles.

normally user roles are assigned manually or via OIDC claims.

**Comment by inferno-umar** [comment]
THANKS! fixed it was having user roles error on my custom OIDC provider side
