### ISSUE TITLE
checking the ocis version returns `Failed to connect to NATS Server`

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#8070]
## Describe the bug
According to the document while installing ocis by binary [set up](https://doc.owncloud.com/ocis/next/deployment/binary/binary-setup.html#installation), the output comes different while using the command `ocis version`

## Expected behavior
something similar to:
```bash
$ ocis version

Version: 5.0.0-beta.2
Compiled: 2023-12-20 00:00:00 +0000 UTC

No running services found.
```

## Actual behavior
![image](https://github.com/owncloud/ocis/assets/61624650/7c168450-8f7e-4a4a-a76b-9c16c633df05)

## Tested on
OCIS version : [5.0.0-beta.2](https://download.owncloud.com/ocis/ocis/testing/5.0.0-beta.2/ocis-5.0.0-beta.2-linux-amd64)

**Comment by kobergj** [comment]
Cannot reproduce locally. It works with the default setup. 

When nats is not running on the standart port you need to set `MICRO_REGISTRY_ADDRESS` . How did you set up ocis? Anything special you set?

**Comment by saw-jan** [comment]
> How did you set up ocis? Anything special you set?

It should be binary from https://download.owncloud.com/ocis/ocis/testing/5.0.0-beta.2/?sort=time&order=asc
Also, built the latest ocis from git and same error with `./ocis/bin/ocis version`

**Comment by saw-jan** [comment]
sometimes while running ocis server as well. See https://github.com/owncloud/ocis/issues/7838

**Comment by dragonchaser** [comment]
I can reproduce it in two cases
- ocis is not running
- ocis is in startup and nats is not available jet

**Comment by saw-jan** [comment]
>The ocis version cmd listed all services by default. This is not always intended,
so we allow to skip the listing of the services by using the --skip-services flag.

We must use `--skip-services` to only check the versions string
```
$ ./ocis version --skip-services

Version: 5.1.0-prealpha+c7f80767ec
Compiled: 2024-02-29 00:00:00 +0000 UTC
```
