### ISSUE TITLE
[Extensions] Changing config defaults build flags does not work

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#81]
Setting default values for ocis-phoenix from ocis binary (cli) does not work when the ocis-phoenix flagset has a default value set. when calling service.Init() ot the service created with http.NewService all the config settings will be reset to the defaults ...

It works correctly when using env vars or config options ... when the flags are evaluated the currently configured values will get overwritten with the defaults ...

**Comment by butonic** [comment]
as a workaround setting envirenmont variables like this works:
```

    if len(os.Getenv("PHOENIX_OIDC_METADATA_URL")) == 0 {
        os.Setenv("PHOENIX_OIDC_METADATA_URL", "http://localhost:9135/.well-known/openid-configuration")
    }
    if len(os.Getenv("PHOENIX_OIDC_AUTHORITY")) == 0 {
		os.Setenv("PHOENIX_OIDC_AUTHORITY", "http://localhost:9135")
	}
```

- does not work for more complex configs.configuring an external_app for phoenix can still be done because there is no default set for it(, yet):
```

	// disable built in apps
	cfg.Phoenix.Phoenix.Config.Apps = []string{}
	// enable ocis-hello extension
	cfg.Phoenix.Phoenix.Config.ExternalApps = []svcconfig.ExternalApp{
		svcconfig.ExternalApp{
			ID: "hello",
			Path: "http://localhost:9105/hello.js",
			Config: map[string]interface{}{
				"url": "http://localhost:9105",
			},
		},
	}
```

**Comment by micbar** [comment]
Done
