### ISSUE TITLE
Auto-accepting doesn't work after switching ocis to new version

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8106]
As a result of compatibility testing, I found that auto-acceptance does not work by default

use: https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_traefik/docker-compose.yml

Steps: 
- start ocis 4.0.5: `git checkout stable-4.0.5` -> `OCIS_DOCKER_TAG=4.0.5 docker-compose up -d`
- create folders `f1` and `f2` and share them to einstein
- einstein accepts only `f1`
- upgrade ocis: `git checkout master` -> `OCIS_DOCKER_TAG=5.0.0-rc.1 docker-compose up -d`
- admin creates `f3` and shares to `einstein`
- einstein opens `Shares`

Expected: 
I'm not sure about `f2` (was not accepted in `4.0.5`) but  I expect that `f3` should be accepted by default

Actual: 
<img width="1656" alt="Screenshot 2024-01-02 at 13 28 24" src="https://github.com/owncloud/ocis/assets/84779829/a025c562-5be3-4c1f-becc-69d899b4504f">

**Comment by micbar** [comment]
Did you configure service accounts?

That is the breaking change from 4.x to 5.0

**Comment by ScharfViktor** [comment]
> Did you configure service accounts?

Yes, sorry I forgot to mention about it. I ran ocis `5.0.0-rc.1` with: 
```
MICRO_REGISTRY: "nats-js-kv"
OCIS_SERVICE_ACCOUNT_ID: "d738470e-d561-48ca-aefb-f8686ebb2e52"
OCIS_SERVICE_ACCOUNT_SECRET: "test"
```

**Comment by 2403905** [comment]
Can not reproduce. 
Works well if I set 
`OCIS_SERVICE_ACCOUNT_ID: "d738470e-d561-48ca-aefb-f8686ebb2e52"
OCIS_SERVICE_ACCOUNT_SECRET: "test"`


If I set the `MICRO_REGISTRY: "nats-js-kv"` leads to the starting problem.
```
2024-01-04 20:54:05 Registry nats-js-kv not found
```
Need to check it.

**Comment by ScharfViktor** [comment]
> Can not reproduce. Works well if I set `OCIS_SERVICE_ACCOUNT_ID: "d738470e-d561-48ca-aefb-f8686ebb2e52" OCIS_SERVICE_ACCOUNT_SECRET: "test"`
> 

I'll check again

> If I set the `MICRO_REGISTRY: "nats-js-kv"` leads to the starting problem.
> 
> ```
> 2024-01-04 20:54:05 Registry nats-js-kv not found
> ```

it's a known issue:  https://github.com/owncloud/ocis/issues/8104

**Comment by ScharfViktor** [comment]
> Can not reproduce. 

yes, me too. notification also work
