### ISSUE TITLE
JSON schema is in incorrect format for some tests

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#8115]
in our tests we have some incorrect json schema assertions
for example
https://github.com/owncloud/ocis/blob/a3583118a4e1bb466a30346cc27bc818debd0e16/tests/acceptance/features/apiGraph/getUser.feature#L265-L275

it should be

```json
"properties": { 
"message":{
   "type": "string", 
   "enum": ["Unauthorized"] 
  }
}
```
which is not valid schema to check response so `the JSON data of the response should match` look up for the step and check if those schemes are in correct format

**Comment by saw-jan** [comment]
Closing as done

**Comment by saw-jan** [comment]
@nirajacharya2 maybe we can close it now?
