### ISSUE TITLE
[QA] template identifier-registration.yml.tmpl missing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#812]
Seen in ocis v1.0.0-rc3 using  ocis/ocis/docker-compose-eos-test.yml
```
Attaching to ocis
ocis          | Waiting for EOS MGM
ocis          | ----- [ocis] DOMAIN setup -----
ocis          | Domain / IP: 95.217.161.245
ocis          | sed: can't read /config/identifier-registration.yml.tmpl: No such file or directory
ocis          | ----- [ocis] Starting oCIS -----
ocis          | + echo '----- [ocis] LDAP setup -----'
ocis          | + authconfig --enableldap --enableldapauth --ldapserver=ocis.testnet:9125 --ldapbasedn=dc=example,dc=org --update
```

This is in https://github.com/owncloud/ocis/blob/master/ocis/docker/eos-ocis/entrypoint#L15

I've logged into the system, there is no *.tmpl file in /config/ and a 0-bytes /etc/ocis/identifier-registration.yml gets created.

Expected behaviour: have the template or abort on error.

Ocis creates a default /config/identifier-registration.yml instead. Featuring only `localhost` of course.
This causes ant http error 400 when trying to login at a remote instance. E.g. 'invalid redirect: https://95.216.209.166:9200/oidc-callback.html' is logged.

Current workaround in hetzner-deploy/make_ocis_eos_compose_test.sh:
```
docker-compose -f docker-compose-eos-test.yml exec ocis sed -i -e 's@://localhost:9@://$IPADDR:9@' /config/identifier-registration.yaml
docker-compose -f $compose_yml restart ocis
```

Please ping me when addressed, so that I can remove my workaround.

**Comment by felixboehm** [comment]
the sed command requires you to use it like in this example:
https://github.com/owncloud-docker/compose-playground/tree/master/examples/eos-compose

it is not robust in matter of the config folder having a template file.
Either have the template in the image and use sed or remove the sed magic.

**Comment by jnweiger** [comment]
Why was it removed? this is a step backwards. Instead the template should have been added.
The removal of official code indicates to me that I am stuck with my workarounds forever.
