### ISSUE TITLE
Ocis crashes on load

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8171]
use fresh ocis `master` branch: 

k6 tests run every night on remote server using fresh master. 
all tests were successful until January 6th. first `ocis` crash:  https://drone.owncloud.com/owncloud/ocis/30679/14/3

Steps: 
- start ocis binary
- run k6 tests:
    - clone https://github.com/owncloud/cdperf.git
    - go to the `cdperf` dir
    - install k6 sudo `apt-get install k6` or `brew install k6`
    - run sh script(in zip) [run_k6_test 2.sh.zip](https://github.com/owncloud/ocis/files/13893930/run_k6_test.2.sh.zip)
    - `TEST_SERVER_URL=your_ocis_ sh location/run_k6_test.sh`
    - wait `090` tests.

Actual: server crash. `fatal error: concurrent map read and map write` same log as https://github.com/owncloud/ocis/issues/7697

<details>
<summary>  ## ocis_log </summary>

```
fatal error: concurrent map read and map write

goroutine 4402519 [running]:
github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache.(*Cache).Persist(0xc00231e250, {0x44d8df0, 0xc00b9fae70}, {0xc01abb3ef0, 0x24})
	/root/k6-ocis/vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache/sharecache.go:304 +0x2d3
github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache.(*Cache).Add.func1()
	/root/k6-ocis/vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache/sharecache.go:115 +0x287
github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache.(*Cache).Add(0xc00231e250, {0x44d8e28, 0xc010207c20}, {0xc01abb3ef0, 0x24}, {0xc014c23030, 0x6e})
	/root/k6-ocis/vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache/sharecache.go:125 +0xb63
github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3.(*Manager).Share.func2()
	/root/k6-ocis/vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/jsoncs3.go:319 +0x72
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/root/k6-ocis/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 4402531
	/root/k6-ocis/vendor/golang.org/x/sync/errgroup/errgroup.go:72 +0x96

```

</details>

[ocis_server_log_full.txt](https://github.com/owncloud/ocis/files/13893913/ocis_server_log_full.txt)

**Comment by aduffeck** [comment]
Fixed by https://github.com/cs3org/reva/pull/4457
