### ISSUE TITLE
Domain-subdirectory support

### ISSUE THREAD

**Issue by ElHado** [owncloud/ocis#8184]
## Is your feature request related to a problem? Please describe.
I would like to handle all my services with subdirectories because my provider don't let me create subdomains.

## Describe the solution you'd like
I want to load oCIS with such an url: https://www.myhomeserver.org/ocis

## Describe alternatives you've considered
Need to place it on the main domain what I don't want to. 

## Additional context
Maybe it's already possible (I'm using nginx) but I didn't find a solution and my tries aren't working.

**Comment by ElHado** [comment]
Is this generally possible or not? Thank you!

**Comment by dragonchaser** [comment]
You have to use a reverse proxy to achieve this. Ocis itself does not support this.

**Comment by ElHado** [comment]
Do you have a sample for ngix? I tried to do it but all things didn't work...

**Comment by dragonchaser** [comment]
Not with a subdirectory, but you could start from here: https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html#nginx-as-reverse-proxy

**Comment by ElHado** [comment]
Thanks. I think I try to swap my actual service on the domain to a subdirectory and try to deploy ocis directly on the domain. Thanks for your help

**Comment by dragonchaser** [comment]
Ok, closing this then.
