### ISSUE TITLE
ocis does not search tags

### ISSUE THREAD

**Issue by nazarifard** [owncloud/ocis#8185]
## Describe the bug
OCIS web does not search tags. apparently OCIS doesn't index tags at all while based on Owncloud 's documents tags are parts of metadata and should be searched by default in basic version.  

## Steps to reproduce
1. create new empty file.txt
2. add new tag; example: mytag
3. search mytag by search box 

## Expected behavior
should find and return file.txt

## Actual behavior
returns: no result

## Setup
online demo https://ocis.owncloud.com/
as well as docker based container, have similar behavior.

**Comment by ScharfViktor** [comment]
@nazarifard thank you for your input 

please use `Tags:mytag` in the search box for tag searching:

<img width="415" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/882503e1-34da-4347-a601-b29ff5c7cd1f">



or open advanced search:

<img width="608" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/b92609de-9369-4045-9596-421878c5ee5e">
 


and choose your tag in the filter tags:

<img width="469" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/c76fcce9-15f7-4a31-9ff9-2b7ee889a1d0">

**Comment by ScharfViktor** [comment]
Please reopen if still not working

**Comment by nazarifard** [comment]
![image](https://github.com/user-attachments/assets/d85277db-2fed-4d06-8905-6009e995e68f)

seemingly the issue is not resolved yet. I also visit that problem in demo.owncloud.com and in last version of docker based OCIS.
is there any trick or configuration options to solve the problem?
