### ISSUE TITLE
Acceptance tests are unreliable

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#819]
Since sometime late last week CI has been getting acceptance test pipelines that suddenly start having a big list of failures. It might be that the accounts provisioning is not working reliably, and so when an account (e.g. `Alice`) does not get fully deleted, then all the remaining test scenarios fail in the pipeline.

Needs investigation. First try to determine which commit started the problem...

**Comment by dpakach** [comment]
The failing tests are because of issue https://github.com/owncloud/ocis/issues/820

**Comment by dpakach** [comment]
CI issues fixed by #835
