### ISSUE TITLE
Link password turns into "not mandatory" for links with viewer permission

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#8237]
## Describe the bug

Password is mandatory for public links in creation. But, if link has "Viewer" permission, it's allowed to remove the password and check the content without typing password.

## Steps to reproduce

1. In web, create a link over an item adding the mandatory password that fulfills all criteria about uppercase, lowercase etc...
2. Open the link in other browser -> password is required 
3. In web, go to the link description, click 3-dot-button -> `Remove password` is available, so click on it
4. Open the link in other browser -> password is NOT required 

## Actual behavior

Password is allowed to be removed from the link, whereas it is mandatory in link creation. Check the following video with the steps and the final result:

https://github.com/owncloud/ocis/assets/14894746/07a2da8f-a805-47d9-93df-864535335e89

## Expected behavior

Password enforced is not allowed to be removed.

## Setup

`ownCloud Web UI 8.0.0-rc.1 index.html-MZztZoFM.mjs:1:449459`

`Infinite Scale 5.1.0-prealpha+f56cf085a Community`

## Additional context

This is reproducible in server returning the following capabilities:

```
"password": {
    "enforced": false,
    "enforced_for": {
           "read_only": true,
           "read_write": true,
           "read_write_delete": true,
           "upload_only": true
     }
}
```

password is enforced for every permission level, so, it should be never allowed to be removed from the link.

**Comment by micbar** [comment]
This is actually a feature called 

„opt out of mandatory password for viewer links when you have the respective permission in the user role“

**Comment by micbar** [comment]
Opt out means „you can create the share only with a password but can remove it afterwards“

**Comment by jesmrec** [comment]
I did not know about this kind of exception, but this is not implemented in the android mobile client. If password is enforced via capabilities, is enforced for creation and edition cases with no exceptions. That means, web and other clients diverge in a behaviour that should be the same. 

Should coordinate in order to align behaviours.
