### ISSUE TITLE
`login_hint` and `user` params in login are not working

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/ocis#8263]
## Describe the bug
The `login_hint` and `user` params in the login URL are not having effect in https://ocis.owncloud.works: not showing in the username text field by default the value that is passed to these 2 parameters. Could be a problem with the IdP, as some of them seem not to support these parameters.

## Steps to reproduce
Go here: [login link](https://ocis.ocis-traefik.latest.owncloud.works/signin/v1/identifier/_/authorize?redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD&response_type=code&scope=openid%20offline_access%20email%20profile&prompt=select_account%20consent&code_challenge=jh6kcEV2-tTWKdLjFmUyr1ve9ZaJWUmmxa5i4MPSh-0&code_challenge_method=S256&state=op2p7mDQhpNTz6i_zcis&user=admin&login_hint=admin)
The complete URL is:
```
https://ocis.ocis-traefik.latest.owncloud.works/signin/v1/identifier/_/authorize?
redirect_uri=oc%3A%2F%2Fandroid.owncloud.com
&client_id=e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
&response_type=code
&scope=openid%20offline_access%20email%20profile
&prompt=select_account%20consent
&code_challenge=jh6kcEV2-tTWKdLjFmUyr1ve9ZaJWUmmxa5i4MPSh-0
&code_challenge_method=S256
&state=op2p7mDQhpNTz6i_zcis
&user=admin
&login_hint=admin
```

## Expected behavior
"admin" should appear written on the Username text field in web.

## Actual behavior
Username text field in web is empty although `user` and `login_hint` parameters are in the URL.

## Setup
I'm using `ocis-traefik.latest`, redirected from https://ocis.owncloud.works: 
```
ownCloud Web UI 8.0.0-rc.1
Infinite Scale 5.1.0-prealpha+cb0090e84 Community
```

## Additional context
We also realised that the `user` parameter is not present in the [OIDC RFC](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), so we wonder if it is even a standard parameter in the request?

**Comment by michaelstingl** [comment]
> We also realised that the `user` parameter is not present in the [OIDC RFC](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), so we wonder if it is even a standard parameter in the request?

Works with the oC10 login which is used for the oC10 OAuth 2.0 implementation.
https://demo.owncloud.org/login?user=test

**Comment by rhafer** [comment]
Yes `login_hint` is not supported by our default IDP lico. AFAIK keycloak does support it, you might wanna try https://ocis.ocis-traefik.latest.owncloud.works for that. I don't think there are plans to add support for it it lico currently.

`user` is indeed not part of the spec. Seems to be something oc10 specific.

**Comment by JuancaG05** [comment]
> AFAIK keycloak does support it, you might wanna try https://ocis.ocis-traefik.latest.owncloud.works for that. I don't think there are plans to add support for it it lico currently.

That's what I tried, but seems to not be working, as stated in the first comment, see the full link in "Steps to reproduce" (https://ocis.owncloud.works redirects to https://ocis.ocis-traefik.latest.owncloud.works/).

> `user` is indeed not part of the spec. Seems to be something oc10 specific.

Thanks for clarifying 👍

**Comment by rhafer** [comment]
Argh, sorry. I pasted the wrong URL :man_facepalming:  it's https://ocis.ocis-keycloak.latest.owncloud.works/ for keycloak

**Comment by rhafer** [comment]
I am closing this. I don't think we have plans to put any efforts in lico to add support for `login_hint`. Going forward we're thinking about a switch to authelia, which already supports it AFAIK.
