### ISSUE TITLE
Option to disable checking of ownCloudUserEnabled LDAP attribute

### ISSUE THREAD

**Issue by zerolabnet** [owncloud/ocis#8270]
I need an option to disable checking the ownCloudUserEnabled attribute. I have MS AD and changing LDAP schema is undesirable.

Setting OCIS_LDAP_USER_ENABLED_ATTRIBUTE: "" does not work.

**Comment by rhafer** [comment]
That setting does already exist. `OCIS_LDAP_DISABLE_USER_MECHANISM=none` should do the trick. If that does not work, please reopen.

**Comment by zerolabnet** [comment]
Yes, I have used this option, it doesn't help.
