### ISSUE TITLE
[QA] Password protected public link asks for a username

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#828]
Tested with ocis-bridge.owncloud.works as of 2020-11-10 09:50h 

* connect as einstein desktopclient 2.7.0-rc3, create a public link via folder rightclick
* log in as einstein at the web gui, edit the public link to include `tttt` as a password
* open the public link with a fresh browser
* a login requester is shown, asking for username and password.

![image](https://user-images.githubusercontent.com/1108546/98651700-df845880-233a-11eb-8e49-d2200ae2646d.png)

* empty username and the link password does not work.
* workaroud: cancel that dialog. a new (different) dialog appears and accepts the password.

**Comment by IljaN** [comment]
Seeing the same on linux: 
testpilotcloud 2.7.2daily20201202 (build 2624) 56cddb Dec 1 2020 17:53:45

**Comment by refs** [comment]
@IljaN can you give it a try with the current master and the latest changes on permissions?

**Comment by refs** [comment]
Can this be re-tested?

**Comment by kulmann** [comment]
<img width="2631" alt="Screenshot 2021-01-13 at 12 17 38" src="https://user-images.githubusercontent.com/3532843/104445491-75d23600-5599-11eb-9d2d-216aaa821036.png">

With current master and desktop client 2.7.4 this works as expected. Password protected password link shows the expected password prompt, no browser popup for basic auth anymore.

The page misses its background, but I will open another issue for that.

**Comment by refs** [comment]
Thanks for the update!
