### ISSUE TITLE
[QA] password protected public link asks for username

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#829]
Tested with ocis-bridge.owncloud.works as of 2020-11-10 09:50h 

* connect as einstein desktopclient 2.7.0-rc3, create a public link via folder rightclick
* log in as einstein at the web gui, edit the public link to include `tttt` as a password
* open the public link with a fresh browser
* a login requester is shown, asking for username and password.

https://ocis-bridge.owncloud.works/#/files/public-link/z06il6lirWjc3OU
![image](https://user-images.githubusercontent.com/1108546/98651700-df845880-233a-11eb-8e49-d2200ae2646d.png)

* empty username and the link password does not work.
* workaroud: cancel that dialog. a new (different) dialog appears and accepts the password.

**Comment by jnweiger** [comment]
This can be reproduced without ocis.

**Comment by refs** [comment]
duplicated of https://github.com/owncloud/ocis/issues/829
