### ISSUE TITLE
Secret File Drop: Uploads with same name don't get renamed to file (1).txt

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#8291]
## Steps to reproduce
1. Create a Secret File Drop `MyFiledropFolder`
2. Upload `file.txt` to `MyFiledropFolder` via the sharing link
3. Repeat: Again upload `file.txt` via the sharing link
4. `MyFiledropFolder` contains

```
 ├── file.txt
```
## Expected behavior
- `MyFiledropFolder` contains 2 files `file.txt` and `file (1).txt` 

```
 ├── file.txt
 └── file (1).txt
```

## Actual behavior
 - `MyFiledropFolder` contains

```
 ├── file.txt
```

**Comment by tbsbdr** [comment]
@micbar lets discuss the severity
After discussion with @kulmann 
- collision-check must happen in backend (client does not know about existing files because there are no read permissions)

**Comment by ScharfViktor** [comment]
we have api tests for that which are in the expected failures file with issue tag https://github.com/owncloud/ocis/issues/1267

**Comment by phil-davis** [comment]
And that links to discussion in https://github.com/cs3org/reva/issues/2480
Which links to discussion in https://github.com/cs3org/reva/pull/2510
with what I thought was the end decision in comment https://github.com/cs3org/reva/pull/2510#issuecomment-1047089220 on Feb 21, 2022 - nearly 2 years ago.

But nothing happened after that.

**Comment by phil-davis** [comment]
And more related discussion about what the behavior should be in #5074

**Comment by butonic** [comment]
@tbsbdr what naming scheme should be used?
0) pm:  `file.txt`, `file (1).txt`, `file (2).txt`
1) oc10 & windows: `file.txt`, `file (2).txt`, `file (3).txt` (humans count the file.txt as 1)
2) phil: `file.txt`, `file_fs93e.txt`, `file_pa4io.txt`
3) CERN: `{uuid} file.txt`
4) timestamp: `file.txt`, `file (2024-02-01 14:56:54.003Z).txt`, `file (2024-02-01 14:56:55.004Z).txt`

I highly recommend not deviating from what other systems like windows do. Endusers might expect this behavior. Also ... our oc10 tests already expect option 1)

**Comment by tbsbdr** [comment]
**option 1** like in Windows
`file.txt`, `file (1).txt`, `file (2).txt`

**Comment by JanAckermann** [comment]
@tbsbdr could you check that with the current implementation with web? IHMO we go f, f(1) (you skipped that). Maybe we need to adjust web then

**Comment by tbsbdr** [comment]
I would just align it if the effort is < 30 mins as I bet no one will notice it (except for the pain we experience by being aware of that inconsistency)

**Comment by dragonchaser** [comment]
@tbsbdr should we close this here and track this on web?

**Comment by tbsbdr** [comment]
fixed via https://github.com/owncloud/ocis/pull/8340
