### ISSUE TITLE
HTTP statuscode while MOVE between cross-spaces with Viewer role

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#8315]
**Q: What should be the status code while moving between cross-spaces with Viewer role?**

Currently, most cases return `403` which seems reasonable (because viewer role is not permitted to do so).
But MOVE to/from shares space returns `502` regardless of the role.

Should they return `502` as mentioned in https://github.com/owncloud/ocis/issues/8063#issuecomment-1883281975 or `403` is the correct one for Viewer role.

Here are test cases:

1. :exclamation: Using path

| from                     | to                              | result |
| ------------------------ | ------------------------------- | ------ |
| project (manager/editor) | project (viewer)                | 403 :question: |
| project (viewer)         | project (manager/editor/viewer) | 403   :question:  |
| project (viewer)         | personal                        | 403    :question: |
| personal                 | project (viewer)                | 403    :question: |

2. :exclamation: Using file-id

| from                     | to                              | result |
| ------------------------ | ------------------------------- | ------ |
| project (manager/editor) | project (viewer)                | 403 :question: |
| project (viewer)         | project (manager/editor/viewer) | 403   :question:  |
| project (viewer)         | personal                        | 403    :question: |
| personal                 | project (viewer)                | 403    :question: |
| shares (read)         | personal                        | 403    :question: |
| shares (read)         | project (manager/editor/viewer) | 403   :question:  |
| shares (editor/uploader)         | project (viewer)                | 403    :question: |

:heavy_check_mark: Working as expected
| from                     | to                              | result |
| ------------------------ | ------------------------------- | ------ |
| project (viewer)         | shares (all/change/read)        | 502   :+1:  |
| personal                 | shares (read)                   | 502   :+1:  |
| shares (read)            | personal                        | 502    :+1: |
| shares (read)            | project (manager/editor/viewer) | 502   :+1:  |
| shares (read)            | shares (all/change/read)        | 502    :+1: |

**Comment by saw-jan** [comment]
CC @ScharfViktor @micbar

**Comment by ScharfViktor** [comment]
> CC @ScharfViktor @micbar

403 is fine IMHO. if it isn't important for client I'd leave it as it is

**Comment by saw-jan** [comment]
403 seems correct for viewer role but MOVE from/to Shares space returns `502` so that's confusing.
If `502` is expected for shares space then we can close this one

**Comment by saw-jan** [comment]
@micbar I would like to close this issue if `403` is the expected code for the above cases.

**Comment by micbar** [comment]
That is ok.
