### ISSUE TITLE
[QA][Sharing NG] ApiTest: sent sharing invitation with auto-accept disabled

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#8318]
From https://github.com/owncloud/ocis/issues/7947#issue-2038180230
> sync enabled and disabled introduced in ocis with the help of env maybe we need to tests this also

Add API tests with auto-accept disabled. Available step:`user "Brian" has disabled auto-accepting `
- check `sharedWithMe`
    ```
    check these props:
     - "@UI.Hidden"
     - "@client.synchronize"
    ```
- [x] Personal resource @grgprarup
  - [x] sharing resource to 
    - [x] user https://github.com/owncloud/ocis/pull/8371
    - [x] group https://github.com/owncloud/ocis/pull/8373
  - [x] sharing resource to user and to group(user is member) with different permissions https://github.com/owncloud/ocis/pull/8397
  - [x] sharing resources with same name. Checking name updating `suffix(1)` https://github.com/owncloud/ocis/pull/8449
- [x] Project space resource @nabim777 
  - [x] sharing resource to 
    - [x] user https://github.com/owncloud/ocis/pull/8406
    - [x] group https://github.com/owncloud/ocis/pull/8414
  - [x] sharing resource to user and to group(user is member) with different permissions https://github.com/owncloud/ocis/pull/8484
  - [x] sharing resources with same name. Checking name updating `suffix(1)` https://github.com/owncloud/ocis/pull/8516

Cases: 
- sharing resource to user and group
- sharing resource to user and to group(user is member) with different permissions
- sharing resources with same name. Checking name updating `suffix(1)` https://github.com/owncloud/ocis/issues/8471

**Comment by nabim777** [comment]
all share invite tests having been covered so closing this issue
