### ISSUE TITLE
[Sharing NG] getting permissions for drive via driveId doesn't work

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8351]
## Describe the bug
Permissions of a drive currently can't be fetched when using the `driveId` as `itemId`.

## Steps to reproduce
1. Create a drive
2. Try fetching permissions for that drive via the drive's id: `curl "https://localhost:9200/graph/v1beta1/drives/{drive-id}/items/{drive-id}/permissions" -u admin:admin -vk | jq`

## Expected behavior
The permissions for that drive should be returned by the server.

## Actual behavior
The server complains about an invalid `itemId`. This probably happens because the `driveId` only consists of 2 parts and is missing the `nodeId` as third part. Appending the last part of the `driveId` as `nodeId` works. But consumer of the API shouldn't need to care about id formats.

cc @rhafer

**Comment by 2403905** [comment]
Tested for the personal space. It works properly `/graph/v1beta1/drives/storage-users-1$some-admin-user-id-0000-000000000000/items/storage-users-1$some-admin-user-id-0000-000000000000!some-admin-user-id-0000-000000000000/permissions`
What format did you use?

**Comment by saw-jan** [comment]
> Tested for the personal space. It works properly `/graph/v1beta1/drives/storage-users-1$some-admin-user-id-0000-000000000000/items/storage-users-1$some-admin-user-id-0000-000000000000!some-admin-user-id-0000-000000000000/permissions` What format did you use?

Yeah, this works. But the issue is about using:
```diff
-/graph/v1beta1/drives/storage-users-1$some-admin-user-id-0000-000000000000/items/storage-users-1$some-admin-user-id-0000-000000000000!some-admin-user-id-0000-000000000000/permissions`
+/graph/v1beta1/drives/storage-users-1$some-admin-user-id-0000-000000000000/items/storage-users-1$some-admin-user-id-0000-000000000000/permissions`
```

**Comment by rhafer** [comment]
> Permissions of a drive currently can't be fetched when using the `driveId` as `itemId`.

Yes a `driveId` is not `itemId`. So this is kind of expected I guess. Having that endpoint accept `driveId` as `itemId` shouldn't be to hard, however I think we would be better of implementing:

`GET /graph/v1beta1/drives/{driveId}/root` which basically returns the drives root item,  and `/graph/v1beta1/drives/{driveId}/root/permissions` which would return the permissions.

**Comment by JammingBen** [comment]
> `GET /graph/v1beta1/drives/{driveId}/root` which basically returns the drives root item, and `/graph/v1beta1/drives/{driveId}/root/permissions` which would return the permissions.

So Web would need to make an extra call to `/graph/v1beta1/drives/{driveId}/root` just to retrieve the correct `itemId`?

**Comment by micbar** [comment]
Ralf is trying to make the item id obsolete for space roots.

The /root url part is basically an alias for the item id of the space root
