### ISSUE TITLE
[Sharing NG] Available roles do not match the given file type

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8403]
## Describe the bug
The available roles (`@libre.graph.permissions.actions.allowedValues`) given by the `permissions` endpoint do not match the given file t ype.

## Steps to reproduce
1. Query the permissions for a file (not folder!) and check the `@libre.graph.permissions.actions.allowedValues` property of the server response.

## Expected behavior
The server should return 2 roles: Viewer and one of the 2 available Editor roles.

## Actual behavior
The server returns 4 roles, including 2 roles that are incompatible with files (Uploader role and the other Editor role).

**Comment by rhafer** [comment]
There is already https://github.com/owncloud/ocis/issues/8331. Which I think is a duplicate.
