### ISSUE TITLE
[Sharing NG] Creating invites with expiration date does not work

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8404]
## Describe the bug
Creating invites with `expirationDateTime` in the payload does not work.

## Steps to reproduce
1. Create an invite including an expiration date (payload: `{"roles":["b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5"],"expirationDateTime":"2024-02-29T23:59:59 0100","recipients":[{"objectId":"058bff95-6708-4fe5-91e4-9ea3d377588b","@libre.graph.recipient.type":"user"}]}:`).

## Expected behavior
The permission should be created with the given data.

## Actual behavior
The server responds with `invalid request body`.

**Comment by rhafer** [comment]
@JammingBen Are you sure this is a valid time format? Our JSON parser doesn't like that. Bascially we accept RFC3339 timestamps.

e.g. `2024-02-29T23:59:59+01:00` should work.

**Comment by saw-jan** [comment]
We have API test covered for sharing with expiration. Should be possible to share with expiration date
https://github.com/owncloud/ocis/blob/ef77055c09858cf2895aab6c9cce223b42d157c8/tests/acceptance/features/apiSharingNg/shareInvitations.feature#L571-L581

**Comment by rhafer** [comment]
I don't think there's a bug here. So I am closing this. @JammingBen please re-open if you disagree.
