### ISSUE TITLE
[Sharing NG] Expiration dates can't removed from link permissions

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8405]
## Describe the bug
Expiration dates can't removed from link permissions.

## Steps to reproduce
1. Create a link permission for a file
2. Update the permission by giving it an expiration date
3. Try removing that expiration date by setting `expirationDateTime` to `null` in the update permission request (similar to how it's done for collaborator shares).

## Expected behavior
The expiration date is being removed from the link.

## Actual behavior
The server responds with an error: `expiration date is in the past: 1754-08-31T22:43:44Z`.

**Comment by rhafer** [comment]
I can reproduce this. Happens only for links. Not for "real" shares.

**Comment by micbar** [comment]
weird, I thought that was working.
