### ISSUE TITLE
go-micro related

### ISSUE THREAD

**Issue by vtolstov** [owncloud/ocis#841]
as you know author of go-micro not want to maintain go-micro and provide PaSS.
I'm using go-micro latest two years and provide many improvements to it and now have "hard fork" - i'm fork go-micro to https://github.com/unistack-org/micro preserving all history. After that i'm extract all stuff to dedicated repos so etcd hell or other big deps now are not problem.
I'm use go-micro (and now fork) on my own project to create cloud hosting, and also i'm consult and write services for two banks in Russia that used microservices.
So i'm provide support for forked repo and already have many improvements. Differences are not so big (mostly now all interfaces receives context to easy trace and debug). So if you interesting on it - feel free to switch and also we can improve framework together.

**Comment by vtolstov** [comment]
i'm not plan to change license and also plan to maintain it for long time

**Comment by butonic** [comment]
wep hear you ... politics is involved ... internal :gear: are churning ...

**Comment by vtolstov** [comment]
politics.... =)
