### ISSUE TITLE
 Add the `introductionVersion` field to all existing environment variables

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#8434]
Prerequisite to #8258

- Add the `introductionVersion` field to all existing environment variables
- The value **MUST** be `pre5.0` (all newer Variables get their correct value upon introduction) for all currently existing variables in all services.
- This Task needs to be commited before release 5.0

**Comment by dragonchaser** [comment]
A make target to validate the work can be found in https://github.com/owncloud/ocis/pull/8436 just run `make check-env-var-annotations` from the project root.

**Comment by dragonchaser** [comment]
Mentioned make target has been merged to `master`

**Comment by kulmann** [comment]
@jacob-nv do you have capacity to look into this?

**Comment by kulmann** [comment]
@individual-it @phil-davis do you guys have someone who could get this done quickly? It's a super easy task, busy work.

**Comment by phil-davis** [comment]
@saw-jan I am having a look at what is involved in this. If it can be automated pretty well in the IDE then I might "just do it", or I will hand over for someone to do when I understand what variations there are that need to be "manually" edited.

**Comment by phil-davis** [comment]
PR #8469 is ready for review and discussion.

**Comment by phil-davis** [comment]
PR #8574 added this to ocis master.
Backport to stable-5.0 was done in PR #8583 

`make check-env-var-annotations` was added to CI in both these PRs.

I think that this is done. @dragonchaser close? Or is there anything else to tweak?
