### ISSUE TITLE
Cleanup continous deployment links

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#8445]
## Describe the bug
Quite a bit of continous deployments URLS on https://owncloud.dev/ocis/deployment/continuous_deployment seem to be outdated/broken

## Steps to reproduce
1. Go to https://owncloud.dev/ocis/deployment/continuous_deployment
2. Click through the continous deployment examples and expect a working oCIS instance
3. See certificate errors or "unable to connect" messages in the browser 

## Expected behavior
Documented links work

## Actual behavior
Some links are broken

**Comment by micbar** [comment]
Problem with the hetzner cloud creation of nodes. Needs to be fixed in the deployment pipelines.

**Comment by micbar** [comment]
Was fixed. Working fine.
