### ISSUE TITLE
ERR could not remove temporary etag attribute

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis#848]
starting `ocis server` from master branch throws repeated

`ERR could not remove temporary etag attribute error="xattr.Remove /var/tmp/ocis/metadata/nodes/1a78323b-08e6-4d63-be97-8a54fc9a0585 user.ocis.tmp.etag: attribute not found" node={"Exists":true,"ID":"1a78323b-08e6-4d63-be97-8a54fc9a0585","Name":"groups","ParentID":"root"} pkg=rhttp service=storage`

I don't understand the reason of the error.

- Fix the error
- Add explanation to FaQ in devdocs if it is a valid scenario

---
https://github.com/cs3org/reva/blob/master/pkg/storage/fs/ocis/tree.go#L382

**Comment by refs** [comment]
has already been addressed 🎉
