### ISSUE TITLE
Repeated useless INF http logs

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis#849]
Move to debug level and add a better message.

INF http end="12/Nov/2020:12:13:00 +0100" host=::1 method=PUT pkg=rhttp proto=HTTP/1.1 service=storage size=0 start="12/Nov/2020:12:13:00 +0100" status=200 time_ns=1364374 traceid=2d8376ba1635087f41305c9d8aaa0ffb uri=/data/groups/6040aa17-9c64-4fef-9bd0-77234d71bad0 url=/data/groups/6040aa17-9c64-4fef-9bd0-77234d71bad0

**Comment by IljaN** [comment]
Maybe we have a conceptual problem as in that we might want to separate access logs from application logs. 
In OC10 owncloud.log and apache.log was a separated thing so the "flood" was hidden.

Both are equally important. I guess that in a cloud environment you want to consume from one stream and filter in your log-management solution (graylog...) 

But for simpler setups and development different log-classes might make sense.  

SAMBA for example has very granular logging (10 levels) and is a mix of domain-based logging (locks, vfs)
and components (registry)

http://bicosyes.com/2014/03/custom-log-levels-for-different-components-of-samba/

**Comment by felixboehm** [comment]
this is internal communication from reva -> debug
Access log would come from Proxy, would like to see that, yes
