### ISSUE TITLE
[Sharing-Ng]Add API test coverage for PROPFIND shared resources with same name

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#8493]
## Description
Currently, we do not have test coverage for PROPFIND the shared resources with same name. When two users share resource with same name, it is expected to have `suffix(1)` added on the second share.

Current behavior for PROPFIND request of the shared resources for `old` and `new` dav path returns `suffix(1)` in the response as `<oc:name>test-folder (1)</oc:name>`. In case of `spaces` dav path the response returns `<oc:name>test-folder</oc:name>`.

Cover tests for ~old~ , `new and spaces` dav paths

- [x] Add test coverage for PROPFIND of shared resources with same name. 
  - https://github.com/owncloud/ocis/pull/8622
  - https://github.com/owncloud/ocis/pull/8671
  - https://github.com/owncloud/ocis/pull/8674
  - https://github.com/owncloud/ocis/pull/8675
- [x] Match the ids between share and propfind responses (https://github.com/owncloud/ocis/issues/8420) @PrajwolAmatya https://github.com/owncloud/ocis/pull/8767

~- [ ] shareid (https://github.com/owncloud/ocis/issues/8510)~

Related issues:
- https://github.com/owncloud/ocis/issues/3859
- https://github.com/owncloud/ocis/issues/4421
- https://github.com/owncloud/ocis/issues/8420
- https://github.com/owncloud/ocis/issues/8510

**Comment by grgprarup** [comment]
Tests coverage for `Add test coverage for PROPFIND of shared resources with same name` are added and all related PRs are merged.
