### ISSUE TITLE
Split the changelog into two files

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#8554]
The changelog is now in a size where GH will not longer render it. This means that you have to download the file and view it locally. To overcome this issue, we should split the changelog into a working file and a "historic" file which gets linked.

* `CHANGELOG.md`
This file should imho ONLY contain the working and max two major versions, maybe only the latest major version.
* Anything that is older than a defined major release will be transferred into a new file like
`CHANGELOG-historic.md`
* In `CHANGELOG.md`, we will add a general section on the bottom like `## Older Releases` and just add a link to `CHANGELOG-historic.md`.
* Whenever we have a new major version published, we then relocate older content from
`CHANGELOG.md` --> `CHANGELOG-historic.md`

@micbar as discussed

**Comment by kulmann** [comment]
IMO not needed. People are usually not interested in the historic changelog, so I don't expect it to be relevant at all that you'd need to download the file to read the historic changelog.

**Comment by mmattel** [comment]
This issue was discussed upfront with @micbar and it was agreed to create it as he will take care. I reopen. Pls discuss with him.

**Comment by micbar** [comment]
I don’t like to be mentioned to give a ticket more prio 🤣

I asked Martin to open it. 

But it is totally fine that others have different opinions on the prio.

It creates additional effort and complexity. If not needed, we should not do it.

**Comment by mmattel** [comment]
> I don’t like to be mentioned to give a ticket more prio 🤣

This has nothing to do with prio but keeping things open for further processing. The underlaying problem does not go away by closing the issue.

**Comment by kulmann** [comment]
> The underlaying problem does not go away by closing the issue.

Well that's what I was trying to say. There is no underlying problem. Nobody cares about the historic changelog in the changelog.md file. People care about release notes first and changelog on the respective github release page second. Close the issue, wait for 10 people to actually ask for what you are proposing. I bet there won't even be 2. Writing this comment is already too expensive compared to the importance of this issue.

But not my repo. Not my decision. Do whatever you want.

**Comment by mmattel** [comment]
I would be totally fine if we just cut off old changelog content to reenable viewing the actual one via GH. Just thought that it maybe worth keeping the cut off one in another file. Keeping historic data is possibly too much effort and not needed/required, but the current situation is also not satisfying.

**Comment by tbsbdr** [comment]
wont fix
