### ISSUE TITLE
More granular roles : user restricted to sharing with his groups

### ISSUE THREAD

**Issue by cheegui** [owncloud/ocis#8560]
## Is your feature request related to a problem? Please describe.
Right now, any user can share with anyone, including users who are not members of the groups the user belongs to.   Any user can see all the other user accounts in oCIS, including the administrator accounts, and share with those accounts.    

## Describe the solution you'd like
Request for a restricted user role which can only share with groups of which he is a member.   
The user should only be able to see the names of the members of the groups to which he belongs when he tries to do a share.  For example, if user Tom is a member of the Marketing group and Finance group, he should only be able to share with members of the Marketing and Finance groups.   In the Search box of Share with People, he should only be able to see the usernames of the Marketing group and the Finance group, and nobody else.   I believe this is how NextCloud works.  Nextcloud has a "Restrict users to only share with users in their groups" setting.   Owncloud also has these "Restrict users to only share with users in their groups" and "Restrict users to only share with groups they are member of" settings.
  
This is for a very common use case of file sharing for a company doing projects for many clients.   The company needs to share files with the clients but obviously does not want the clients to be able to share files with other clients.  Neither does the company want a client to be able to share files with everybody in the company.  The company would want to restrict the client to sharing files with members  of the client project team (including company staff assigned to the project).
   
Another restricted role nice to have is a role with no sharing ability at all.   The user can only upload/download/delete/edit but cannot share.   When he wants to share a file, he just uploads it to the shared spaces of which he is a member.    

Also, if there is a setting to open a particular space by default whenever the user logs in, that would be very helpful in the use case mentioned above.

## Describe alternatives you've considered
None

**Comment by micbar** [comment]
There is a roadmap item about that.

Linking it here https://github.com/owncloud/product/issues/343

**Comment by cheegui** [comment]
Thank you Michael!
