### ISSUE TITLE
Lost access to space after backup/restore with lost users

### ISSUE THREAD

**Issue by bobslaede** [owncloud/ocis#8561]
After a restore where I have lost my original users in my original ldap server, I cannot access my Spaces anymore. 
As an admin I can see the space, and I can see the users who where in the space as empty avatars.  
Unfortunately I have lost the users from the original ldap server, and therefor lost the connection to the user ids.  

Is there any way, as an admin on my self hosted ocis instance, to regain access to the space?  
I do not have the content of the space completely downloaded to one single machine, so I cannot re-upload the content. 

Is there any way to edit the users ID so I can get the original stuff back?  

Before I was running in kubernetes with keycloak and openldap. After I lost my cluster, I have set up ocis in docker instead, to simplify, and that enables me to run ocis with its build in ldap server, and keycloak as auth. That was not possible with the kubernetes setup before.  
I have the original users in keycloak, but they where mapped to my ocis instance via the ldap server before. 

Related  
#5967  
#7265

**Comment by micbar** [comment]
Basically I think you could do a manual migration of the user ids.

1) lookup the new id from the ldap and change the id in the filesystem, which is manual and multiple steps per space

2) lookup the old ids from the filesystem and change the ones in the ldap

I would recommend 2

**Comment by bobslaede** [comment]
Thank you! I will try it out :)

**Comment by micbar** [comment]
Closing. Please re-open if help is still needed.
