### ISSUE TITLE
[Sharing NG] add OCM Shares to SharingNG

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#8564]
# Description

## User Stories

* > As an app developer, i need to interact with ocm shares on the graph API to list my shares

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by butonic** [comment]
This requires being able to list users from remote instances. Our graph DriveRecipients use the ObjectId and a LibreGraphRecipientType ... which is used to differentiate users and groups ... we could use "remote_user" and "remote_group" ...

The cs3 Gateway has a FindAcceptedUsers in addition to FindUsers. It uses the OCMInviteManager which is filled by invite requests.

But how are invites actually sent out? I don't see ui ... maybe part of sciencemesh. Needs further investigation. Maybe with curl requests for now ... 

These users would then have type UserType_USER_TYPE_FEDERATED. 

I still need to wrap my head around this further ...

**Comment by micbar** [comment]
#8909

**Comment by micbar** [comment]
This has been done. QA findings need to create new tickets.
