### ISSUE TITLE
[keycloak] Can't login after role re-assgin

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#8567]
## Describe the bug
admin assign role `spaceAdmin` from keycloak panel to user. Try to log in to ocis with user credential. Most of the time return `500 status code`. Sometimes login could be successful    
updated bug-report according to commit ocis commit 5f831c0b4735bd3cbb4d7ab049133e6480f70672

## Steps to reproduce
1. create user `anu` on keycloak and assign role `User` and initiate created user (login to ocis)
2. user `anu` logout on ocis 
3. admin re-assigns `spaceAdmin` role to user `anu` from keycloak UI
4. try to log in to ocis with user `anu` Credential 
[Screencast from 4-3-24 04:14:48 अपराह्न +0545.webm](https://github.com/owncloud/ocis/assets/54478846/eb004417-b2c5-47a3-9e43-3e94ef0f3f79)

## Expected behaviour
login should be successful everytime

## Actual behaviour
1. found that api request on endpoint `v1.0/me?%24expand=memberOf` returns `500 status code`.
      ``` 
         GET https://ocis.owncloud.test/graph/v1.0/me?%24expand=memberOf

         Status Code:
         500 Internal Server Error
      ```
2. api request on endpoint `/v0/settings/roles-list` sometimes returns `500 status code ` and sometimes returns `success status code`
![Screenshot from 2024-03-04 15-51-52](https://github.com/owncloud/ocis/assets/54478846/453318e0-eec5-489a-b871-536574193fb3)

## Setup
run `docker-compose up` on https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_keycloak

<details>
<p>

![Screenshot from 2024-03-04 16-02-28](https://github.com/owncloud/ocis/assets/54478846/a79049e2-2ecd-456a-9cb5-937f868e7c91)

</p>
</details>

**Comment by ScharfViktor** [comment]
I can confirm this bug. If `admin` assigns `ocisUser` role to user `anu` - works fine

**Comment by micbar** [comment]
> admin assigns spaceAdmin role to user anu

In which UI do you change the role?

**Comment by amrita-shrestha** [comment]
> > admin assigns spaceAdmin role to user anu
> 
> In which UI do you change the role?

keycloak UI

**Comment by micbar** [comment]
hm. I cannot reproduce the issue.

**Comment by ScharfViktor** [comment]
> I can confirm this bug. If `admin` assigns `ocisUser` role to user `anu` - works fine

I tested here https://owncloud.dev/ocis/deployment/continuous_deployment/#ocis-with-keycloak and I was confident to reproduce it 500 Error but I couldn't reproduce it together with @micbar

Steps were: 
- create new user https://keycloak.ocis-keycloak.latest.owncloud.works with `ocisSpaceAdmin` role
- try to login 

Actual: works fine 

I tried to run e2e test with keycloak instance 
`KEYCLOAK=true BASE_URL_OCIS=ocis.ocis-keycloak.latest.owncloud.works KEYCLOAK_HOST=keycloak.ocis-keycloak.latest.owncloud.works  pnpm test:e2e:cucumber tests/e2e/cucumber/features/smoke/admin-settings/spaces.feature:127` - green

**Comment by amrita-shrestha** [comment]
ci is failing on https://drone.owncloud.com/owncloud/web/42946/16/15

**Comment by amrita-shrestha** [comment]
> > I can confirm this bug. If `admin` assigns `ocisUser` role to user `anu` - works fine
> 
> I tested here https://owncloud.dev/ocis/deployment/continuous_deployment/#ocis-with-keycloak and I was confident to reproduce it 500 Error but I couldn't reproduce it together with @micbar
> 
> Steps were:
> 
> * create new user https://keycloak.ocis-keycloak.latest.owncloud.works with `ocisSpaceAdmin` role
> * try to login
> 
> Actual: works fine
> 
> I tried to run e2e test with keycloak instance `KEYCLOAK=true BASE_URL_OCIS=ocis.ocis-keycloak.latest.owncloud.works KEYCLOAK_HOST=keycloak.ocis-keycloak.latest.owncloud.works pnpm test:e2e:cucumber tests/e2e/cucumber/features/smoke/admin-settings/spaces.feature:127` - green

@ScharfViktor, instead of "assigning roles while creating a user," we should "change the role" after user creation. I believe this discrepancy in steps might have led to the inability to reproduce the bug.

**Comment by ScharfViktor** [comment]
> @ScharfViktor, instead of "assigning roles while creating a user," we should "change the role" after user creation. I believe this discrepancy in steps might have led to the inability to reproduce the bug.

> 1. create user anu on keycloak and initiate created user (login to ocis)

do you assign role `ocisUser` while creating user `anu`? I guess so, because `anu` cannot login without role.

my actions:

https://github.com/owncloud/ocis/assets/84779829/2f607f6a-4f78-4f8e-8a24-2c3c52d2694f

after changing role -> user can log in


@amrita-shrestha could you please attach video how to reproduce bug?

**Comment by amrita-shrestha** [comment]
latest ocis commit 73d7f324fbbccd3c17c809fbea8f4c50a17569f4 has no such bug so closing this issue
