### ISSUE TITLE
Version up Keycloak to 23.0

### ISSUE THREAD

**Issue by nicholas-wilson-au** [owncloud/ocis#8569]
https://github.com/owncloud/ocis/blob/3b79c1c40a00d70d524ed1a7bf5493d4553bba8e/deployments/examples/ocis_keycloak/docker-compose.yml#L112

Can we please version up Keycloak to the latest 23.0 for our latest release.

https://github.com/owncloud/ocis/blob/3b79c1c40a00d70d524ed1a7bf5493d4553bba8e/deployments/examples/ocis_keycloak/docker-compose.yml#L115

Will also need a change from:
"--proxy edge"
to
"--proxy=edge"

**Comment by 2403905** [comment]
@nicholas-wilson-au @micbar 
Should we bump the keycloak to [24.0.1](https://github.com/keycloak/keycloak/releases/tag/24.0.1) or [23.0.7](https://github.com/keycloak/keycloak/releases/tag/23.0.7) will be ok?

**Comment by nicholas-wilson-au** [comment]
24 is already out so if it works I would go with that.

**Comment by micbar** [comment]
Fixed in https://github.com/owncloud/ocis/pull/9413
