### ISSUE TITLE
User Light role automatically reverted to User role after user login

### ISSUE THREAD

**Issue by cheegui** [owncloud/ocis#8573]
## Describe the bug
Admin changed the role of a user from User role to User Light role.   But after the user logs in, the role reverts from User Light to User.

## Steps to reproduce
1.  Admin changed the role of a user from User Role to User Light Role.
2.  User logs in
3.  Admin logs in again and finds that the user role has reverted to User Role.

## Expected behavior
User Role should change.

## Actual behavior
User Role doesn't change.

## Setup
N/A 

<details>
<p>
OCIS  5.0.0-rc.5
Web client version	8.0.0-rc.5
--
```console
OCIS_XXX=5.0.0-rc.5
--




</p>
</details>

## Additional context
NA

Thank you

Update:  Okay somebody posted this issue before: https://github.com/owncloud/ocis/issues/6688
But I still think this is a bug.

**Comment by micbar** [comment]
Which setup do you use?

The keycloak setup has the roles stored in keycloak, they are updated in ocis after the user logs in. That might explain your behavior.

**Comment by cheegui** [comment]
Yes, we are using the Keycloak setup.  Thank you Michael!

**Comment by rhafer** [comment]
@cheegui In that case you have to change the role assignment for the user in keycloak. oCIS will pick it up the next time the user logs in.
