### ISSUE TITLE
Preview request in public links are broken

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#8602]
## Describe the bug
Thumbnail service in public links (i.e. preview requests via `/dav/public-files`) lead to http 500.

## Steps to reproduce
1. Create a project space
2. Upload some images
3. Create a public link to the space itself or a single file public link to one of the images
4. Public link must be password protected
5. Open the public link in a private tab and try to open one of the images

## Expected behavior
Image renders successfully

## Actual behavior
Preview app shows error state

## Setup
I built the single binary from `HEAD` (`009f1e508efe56f31b6c203567931c507f387d04`) of `stable-5.0` and run it locally.

<img width="2246" alt="Screenshot 2024-03-07 at 13 14 30" src="https://github.com/owncloud/ocis/assets/3532843/c929bcdc-9164-47b3-b568-320d8ae9f4ca">

**Comment by fschade** [comment]
i can confrimt 😢 list item previews are working here but as soon as i open the file.... broken

**Comment by saw-jan** [comment]
Is this a flaky one? because I couldn't reproduce with current `stable-5.0` (commit: `a18d54afeb`)
Started just with:
```bash
PROXY_ENABLE_BASIC_AUTH=true \
./ocis/bin/ocis server
```

versions:
```bash
ownCloud Web UI 8.0.0-rc.6 
Infinite Scale 5.0.0-rc.5+a18d54afeb Community 
```

**Comment by kulmann** [comment]
> Is this a flaky one? because I couldn't reproduce with current `stable-5.0` (commit: `a18d54afeb`) Started just with:
> 
> ```shell
> PROXY_ENABLE_BASIC_AUTH=true \
> ./ocis/bin/ocis server
> ```
> 
> versions:
> 
> ```shell
> ownCloud Web UI 8.0.0-rc.6 
> Infinite Scale 5.0.0-rc.5+a18d54afeb Community 
> ```

Not flaky. 100% reproducible for me. But it only happens for password protected public links, maybe yours didn't have a password?

**Comment by saw-jan** [comment]
The link was password-protected because I used the default ocis config. Maybe I missed something?
I just built the latest stable-5.0 and ran ocis with `PROXY_ENABLE_BASIC_AUTH=true ./ocis/bin/ocis server`

**Comment by saw-jan** [comment]
Still the same versions but now it reproduces after couple of retries:
```
ownCloud Web UI 8.0.0-rc.6
Infinite Scale 5.0.0-rc.5+a18d54afeb Community 
```
