### ISSUE TITLE
Public cannot download file

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8621]
maybe related https://github.com/owncloud/ocis/issues/8618

`5.1.0-prealpha+a3044d1dd2
`
`9.0.0-alpha.1
`

Steps:

- admin uploads image file and creates piblic link with view permission
- public opens link 
- public closes image viewer and tries to downloads file

Actual: not possible to dowload file

log: 
```
2024/03/12 10:35:43 http: TLS handshake error from [::1]:56620: remote error: tls: unknown certificate
2024/03/12 10:35:50 http: TLS handshake error from [::1]:56677: remote error: tls: unknown certificate
2024/03/12 10:36:01 http: TLS handshake error from 127.0.0.1:56766: remote error: tls: unknown certificate
```

https://github.com/owncloud/ocis/assets/84779829/abd80aca-f56c-4fbd-b9f5-6b6d377a2474

**Comment by kobergj** [comment]
@ScharfViktor I cannot reproduce. Public can download the file without any problems. Must be a configuration issue...

**Comment by ScharfViktor** [comment]
> @ScharfViktor I cannot reproduce. Public can download the file without any problems. Must be a configuration issue...

double-checked it. I can reproduce on a fresh master

**Comment by kobergj** [comment]
> double-checked it. I can reproduce on a fresh master. Try to do it please in incognito tab

That is what I did. Can you double check if download works if you when you click the download button in the image viewer?

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/ocis/assets/84779829/61d97d6c-a50d-46a0-9671-749d7bd10f96

**Comment by nabim777** [comment]
Bug not reproduced in
`ownCloud Web UI 9.0.0-alpha.1`
`Infinite Scale 5.1.0-prealpha+db3ed9fc4 Community` 

@ScharfViktor  could you try in latest commit id of ocis

**Comment by ScharfViktor** [comment]
> @ScharfViktor could you try in latest commit id of ocis

what I did: 
- git checkout master
- git pull
- make -C ocis clean generate build
- `PROXY_ENABLE_BASIC_AUTH=true OCIS_LOG_COLOR=true OCIS_LOG_PRETTY=true IDM_CREATE_DEMO_USERS=true ocis/bin/ocis server`

browser - `chrome Version 121.0.6167.184 (Official Build) (arm64)`

**Comment by ScharfViktor** [comment]
clear chrome data helped me. sorry for noise
