### ISSUE TITLE
[QA] account chooser prints black text on dark blue background

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#864]
Setup
* docker-compose-eos-test.yml at v1.0.0-rc3
* login marie at the WEB UI,
* connect desktop client 2.7.0 to https://localhost:9200
![image](https://user-images.githubusercontent.com/1108546/99268968-191aff00-2826-11eb-9afd-3d3777a04d92.png)

Expected behaviour: white text

**Comment by micbar** [comment]
known as #698

**Comment by micbar** [comment]
@LukasHirt JFYI

**Comment by LukasHirt** [comment]
Fixed in #887 Should be possible to already test with ocis.owncloud.works

**Comment by jnweiger** [comment]
Confirmed fixed in rc6. Thanks!
