### ISSUE TITLE
[QA] Desktop client re-login is attempted with last WEB UI user

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#865]
Setup
* docker-compose-eos-test.yml at v1.0.0-rc3
* connect desktop client 2.7.0 to https://localhost:9200 as user einstein
* logout the desktop client
* login marie at the WEB UI,
* re-login the desktop client
![image](https://user-images.githubusercontent.com/1108546/99271812-55029400-2827-11eb-97df-8732a1fac454.png)

Expected behaviour: user einstein should be suggested.

Accepting the suggested user marie on the IDP page seems to work well in the beginning, there is no hint that the `ownCloud desktop app` wants the access for a different user.

The information "Hi marie, ... ownCoud desktop app wants to ... Access your basic account ..." is wrong. Not her account, einstein's. 

![image](https://user-images.githubusercontent.com/1108546/99272273-e540d900-2827-11eb-89f2-4025dc5fa974.png)

When 'Allow' is clicked. The client probably receives permisson for using marie's account, but then detects the mismatch -- luckily

![image](https://user-images.githubusercontent.com/1108546/99272862-96477380-2828-11eb-9dce-fdd4f7a55c4d.png)

The mismatch should be detected before sending a token to the client.

**Comment by jnweiger** [comment]
@TheOneRing @michaelstingl is this more a server or a client issue?

**Comment by TheOneRing** [comment]
Support for login_hint is not yet supported by Konnect @IljaN

**Comment by micbar** [comment]
@jw branding issue in your screenshot is known as #698

**Comment by refs** [comment]
Does this need to be re-tested?

**Comment by ScharfViktor** [comment]
re-tested. reproduce with local server oCIS version 1.11.0

**Comment by micbar** [comment]
@IljaN Is there some news regarding the login hint in konnect?

**Comment by micbar** [comment]
Still happening in ocis 2.0.0-beta1

**Comment by micbar** [comment]
Not supported.
