### ISSUE TITLE
[Sharing NG] Make `@UI.hidden` property editable through API

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8654]
The `@UI.hidden` property on a `DriveItem` is currently not editable via API, hence the Web client needs to use the old OCS endpoint for this. It would be nice to have this implemented in Sharing NG in the future.

cc @rhafer

**Comment by fschade** [comment]
question, what is your preferred way to change the ui.hidden state?

`PATCH /v1beta1/drives/{drive-id}/items/{item-id}/uiHidden` and then toggle the bool?

fine?

**Comment by rhafer** [comment]
> question, what is your preferred way to change the ui.hidden state?
> 
> `PATCH /v1beta1/drives/{drive-id}/items/{item-id}/uiHidden` and then toggle the bool?

Just for completeness, since we discussed this in a different channel: It should actually be a `PATCH  /v1beta1/drives/{drive-id}/items/{item-id}` with the new `@UI.Hidden` value in the body
