### ISSUE TITLE
[Sharing NG] Add tests coverage for download shared resources

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#8662]
## Description
 This PR adds tests related to downloading shared resources from share drive. `Sync/Disable sync`  related test coverage is ongoing on this https://github.com/owncloud/ocis/issues/8486.    
- default (auto-accept) @nabim777 
  - [x] sharee (share reciever) tries to download resource
       - [x] user https://github.com/owncloud/ocis/pull/8697
       - [x] group 
       The scenario for this above two(user, group) will be covered in this line while doing the issue #8717.
       - https://github.com/owncloud/ocis/blob/8f0b536ef75c552703d84e5e541d99727e6a5c31/tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature#L50
       - https://github.com/owncloud/ocis/blob/8f0b536ef75c552703d84e5e541d99727e6a5c31/tests/acceptance/features/apiArchiver/downloadById.feature#L75

- disable sync  @nabim777 
  - [x] sharee tries to download resource (file/folder) after share 
       - [x] user https://github.com/owncloud/ocis/pull/8737
       - [x] group https://github.com/owncloud/ocis/pull/8754
       
   - [x] sharee tries to download resource (file/folder) after share inside project spaces
        - [x] user https://github.com/owncloud/ocis/pull/8944
        - [x] group https://github.com/owncloud/ocis/pull/8945

**Comment by PrajwolAmatya** [comment]
All open tasks have been completed. So, closing this issue.
