### ISSUE TITLE
I can't view mp4 files in browser, when i use ocis with httpd as proxy - login via web to ocis

### ISSUE THREAD

**Issue by ipitsec** [owncloud/ocis#8694]
## Describe the bug
Hello there!

For testing i configured ocis with httpd proxy as described here: https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html

Then all goes allmost ok, but i have trouble, when logged into ocis via web panel, to see in web browser my .mp4 files. I got this in browser:

![obraz](https://github.com/owncloud/ocis/assets/164104196/6653e97d-3a7e-4a86-b2e7-68476529511f)

Then in /var/log/messages:

Mar 20 01:40:38 utility-server ocis[5315]: {"level":"error","service":"proxy","error":"signature mismatch: expected 41c582c6ece861ca7bc85751e981b13f9ce6d4da386a9026855c4291230a1edd != actual 6547525df6655166501bdb6148f87b7d78d3a3489c53d107bfe4175f8290f49b","authenticator":"signed_url","path":"/remote.php/dav/spaces/d79a5198-9ae2-4edc-82b8-1c3f13dd98a9$9101cfe9-9a6d-4e4f-be57-9e935d74e44e/20171001_113045.mp4","url":"/remote.php/dav/spaces/d79a5198-9ae2-4edc-82b8-1c3f13dd98a9$9101cfe9-9a6d-4e4f-be57-9e935d74e44e/20171001_113045.mp4?OC-Credential=admin&OC-Date=2024-03-20T00%3A40%3A38.260Z&OC-Expires=86400&OC-Verb=GET&OC-Algo=PBKDF2%2F10000-SHA512&OC-Signature=6547525df6655166501bdb6148f87b7d78d3a3489c53d107bfe4175f8290f49b","time":"2024-03-20T01:40:38+01:00","message":"Could not get user by claim"}
}

then in /var/log/httpd/ssl_error_log i have:

[Wed Mar 20 01:42:48.269851 2024] [proxy_http:error] [pid 5967:tid 6018] (70007)The timeout specified has expired: [client x.x.x.x:47824] AH01110: error reading response, referer: https://ocis.it-sec.internal:10334/preview/personal/admin/20171001_113045.mp4?fileId=d79a5198-9ae2-4edc-82b8-1c3f13dd98a9%249101cfe9-9a6d-4e4f-be57-9e935d74e44e%215ac21e16-6a6d-4fdd-bb65-80b380fa60dd&contextRouteName=files-spaces-generic&contextRouteParams.driveAliasAndItem=personal%2Fadmin&contextRouteQuery.fileId=d79a5198-9ae2-4edc-82b8-1c3f13dd98a9%249101cfe9-9a6d-4e4f-be57-9e935d74e44e%219101cfe9-9a6d-4e4f-be57-9e935d74e44e&tiles-size=1

When i acess this files without a httpd proxy, via https://localhosty:9200 are is fine, i can view this file in web browser.

## Steps to reproduce
1. configure env like in this tutorial: ocis with httpd as proxy
2.
3.

## Expected behavior
mp4 files should be viewable wehen accesing using httpd as proxy and ocis.

## Actual behavior
As above - some problems, dosen't work.

## Setup
I started by systemd - as in tutorial.
I use ocis 5.0.0 binary for linux amd64.

**Comment by micbar** [comment]
Can you test that with 5.0.5 please and provide a full log please?

I am still trying to understand the underlying problem.

**Comment by ipitsec** [comment]
Hi again. With version 5.0.0 i switched from httpd apache  to ngnix as proxy and all goes ok. I think, some wrong config is in tutorial to use httpd as proxy with ocis.

Now i'm at ocis 5.0.5 and all is ok with mp4 files viwed in browser and nginx as proxy.
