### ISSUE TITLE
[ocis] Implement Events for Shares and Space membership

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#8708]
# Description

## User Stories

* > As a user I want to see in real time in my client when I was added to a space so that my collaborative resources instantly become available.
* > As a user I want to see in real time in my client when I was removed from a space so that I instantly know when my collaborative resources are not available anymore.
* > As a user I want to see in real time in my client when my role in a space changes so that I can always perform exactly the tasks in the client that I'm allowed to perform.

## Value
Transparency and guided user interaction

## Acceptance Criteria
- publish SSE event when `space` members get added
- publish SSE event when `space` members get removed
- publish SSE event when `space` member role gets changed
- publish SSE event when `share` get added
- publish SSE event when `share` get removed
- publish SSE event when `share` role gets changed

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by kobergj** [comment]
@kulmann should other space members also receive these events when a member is added/removed or only the one that is added/removed newly?

Similar question for shares: Who should get these sses? All Space Members? Only the Sharee? All but the Sharer?
