### ISSUE TITLE
Make space templates production ready

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#8713]
Just so I don't forget details.

Needs rework:
- `readme.md` must be translated
- image not good, color should be `#4c5f79;` ratio should be 16:9

**Comment by AlexAndBear** [comment]
After we create a space, the quota field is missing a lot of data 
```
remaining: 999996097
state: "normal"
total: 1000000000
used: 3903
```
We need all of these attributes ^

**Comment by AlexAndBear** [comment]
![layout-grid-fill (1)](https://github.com/owncloud/ocis/assets/26169327/fb4a1e31-96f1-4eab-9d7b-fac442606be7)

Here is the image with the correct color, but we will need someone who creates a 16:9 image of it (background, don't stretch the icon)

**Comment by AlexAndBear** [comment]
![layout-grid-fill (4)](https://github.com/owncloud/ocis/assets/26169327/ddeae9a0-02c2-47ca-8414-a02e06c29d7a)


This should be sufficient

**Comment by tbsbdr** [comment]
the one with the smaller icons, agree

**Comment by AlexAndBear** [comment]
@kobergj that means you can use the provided png

**Comment by TheOneRing** [comment]
The 16:9 is hand tailored for the web client.
An we at least try to be a bit more agnostic?

**Comment by AlexAndBear** [comment]
> The 16:9 is hand tailored for the web client.
> 
> Can we at least try to be a bit more agnostic?

Sure, open for any suggestions. 
I feel that we need to touch the thumbnail/preview service if we want to have the original images in a 1:1 aspect ratio but keep up the landscape mode representation in web. Same goes for the emoji images.

**Comment by AlexAndBear** [comment]
@TheOneRing just after seeing your implementation, I think it could be also quite fitting to have the 16:9 landscape mode on the desktop client, do you think otherwise ?

**Comment by TheOneRing** [comment]
Users will upload any format, I'm not a fan of randomly cropping the image.
For the desktop, increasing the space for the image, would reduce the space available for the progress and upload information.
![image](https://github.com/owncloud/ocis/assets/200626/c983a708-cc9d-4304-97e0-3d88d4124619)

**Comment by AlexAndBear** [comment]
I think we need to discuss this in a bigger round, especially with @tbsbdr to find out, what we should do then across all clients. 
We agreed on the 16:9 banner format for space images as we started this feature, maybe it's time to change this or try to find a solution, so that web will be able to display the space image, I provided, in the 16:9 aspect ratio format, even if its 1:1 ratio on the server.
I don't think we will come to conclusion here

**Comment by kulmann** [comment]
> The 16:9 is hand tailored for the web client.
> Can we at least try to be a bit more agnostic?

It's not tailored for the web client. I asked for feedback here https://github.com/owncloud/web/pull/10546#discussion_r1520878813 and apparently at least the iOS client is happy about a 16:9 aspect ratio. 😉

**Comment by AlexAndBear** [comment]
Here is a future proposal, to make the space image/readme upload process more convenient 
https://github.com/owncloud/ocis/issues/8719
