### ISSUE TITLE
[QA] Use SharingNG to share/list resources in the Given/Then steps

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#8717]
We are moving from OCS sharing to SharingNG for resource sharing. So let's slowly start using SharingNG in the Given steps to share resource.

Open Tasks:
- [x] share using SharingNg in the Given steps

  <details><summary>Available Steps</summary>

  - Resource sharing via `permission endpoint`
  ```
  And user "Alice" has sent the following resource share invitation:
      | resource        | <resource-name>    |
      | space           | <space-name>       |
      | sharee          | <sharee-name>      |
      | shareType       | <user|group>       |
      | permissionsRole | <permissions-role> |
  ```
   - Space sharing via `drives.root endpoint`
  ```
  And user "Alice" has sent the following space share invitation:
      | space           | <space-name>       |
      | sharee          | <sharee-name>      |
      | shareType       | <user|group>       |
      | permissionsRole | <permissions-role> |
  ```
  - Resource link creation via `permission endpoint`
  ```
  And user "Alice" has created the following resource link share:
      | resource           | <resource-name>    |
      | space              | <space-name>       |
      | permissionsRole    | <permissions-role> |
      | password           | <password>         |
      | expirationDateTime | <datetime>         |
      | displayName        | <link-name>        |
  ```
  - Space link creation via `drives.root endpoint`
  ```
  And user "Alice" has created the following space link share:
      | space              | <space-name>       |
      | permissionsRole    | <permissions-role> |
      | password           | <password>         |
      | expirationDateTime | <datetime>         |
      | displayName        | <link-name>        |
  ```
  </details>

- [x] check Then steps (need to be careful)
- [ ] Cleanup leftovers and step implementation @grgprarup 

**NOTE: ocs sharing in When steps should not be changed (Keep ocs sharing suites)**

Check over these files
<details>
<summary><strong>Local API Test Suites</strong></summary>

- [x] apiAntivirus/antivirus.feature https://github.com/owncloud/ocis/pull/8914 https://github.com/owncloud/ocis/pull/9024
- [x] apiArchiver/downloadById.feature (@Salipa-Gurung) https://github.com/owncloud/ocis/pull/8965
- [x] apiArchiver/downloadByPath.feature (@Salipa-Gurung ) https://github.com/owncloud/ocis/pull/8990
- [x] apiContract/propfind.feature @S-Panta  https://github.com/owncloud/ocis/pull/9017
- [x] apiContract/sharesReport.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9045
- [x] apiContract/spacesSharesReport.feature @S-Panta  https://github.com/owncloud/ocis/pull/9023
- [x] apiDepthInfinity/propfind.feature @S-Panta  https://github.com/owncloud/ocis/pull/9019
- [x] apiDownloads/download.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9027
- [x] apiDownloads/spaceDownload.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9027
- [x] apiGraph/enforcePasswordPublicLink.feature @grgprarup  https://github.com/owncloud/ocis/pull/9040
- [x] apiGraph/userGDPRExport.feature @grgprarup https://github.com/owncloud/ocis/pull/9040
- [x] apiGraphUserGroup/deleteGroup.feature @grgprarup https://github.com/owncloud/ocis/pull/9016
- [x] apiGraphUserGroup/deleteUser.feature @grgprarup https://github.com/owncloud/ocis/pull/9016
- [x] apiLocks/lockFiles.feature @S-Panta https://github.com/owncloud/ocis/pull/9055
- [x] apiLocks/unlockFiles.feature @S-Panta https://github.com/owncloud/ocis/pull/9063 https://github.com/owncloud/ocis/pull/9221
- [x] apiNotification @S-Panta https://github.com/owncloud/ocis/pull/9081
- [x] apiReshare/resharing.feature https://github.com/owncloud/ocis/pull/9221
- [x] apiSearch1/dateSearch.feature @grgprarup https://github.com/owncloud/ocis/pull/9057
- [x] apiSearch1/Search.feature @grgprarup https://github.com/owncloud/ocis/pull/9057
- [x] apiSearch2/mediaTypeSearch.feature @grgprarup https://github.com/owncloud/ocis/pull/9060
- [x] apiSearch2/tagSearch.feature @grgprarup https://github.com/owncloud/ocis/pull/9060
- [x] apiSearchContent/contentSearch.feature @grgprarup https://github.com/owncloud/ocis/pull/9061
- [x] apiSpaces/changeSpaces.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/disableAndDeleteSpaces.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/editPublicLinkOfSpace.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/filePreviews.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/listSpaces.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/publicLink.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/removeSpaceObjects.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9082
- [x] apiSpaces/restoreSpaces.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9122
- [x] apiSpaces/setQuota.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9122
- [x] apiSpaces/tag.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9122 https://github.com/owncloud/ocis/pull/9221
- [x] apiSpaces/trashBin.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9122
- [x] apiSpaces/tusUpload.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9122
- [x] apiSpaces/uploadSpaces.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9122
- [x] apiSpacesDavOperation @S-Panta https://github.com/owncloud/ocis/pull/9092
- [x] apiSpacesDavOperation/moveByFileId.feature @S-Panta https://github.com/owncloud/ocis/pull/9105
- [x] apiSpacesShares/changingFilesShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9080
- [x] apiSpacesShares/checksum.feature @grgprarup https://github.com/owncloud/ocis/pull/9080
- [x] apiSpacesShares/copySpaces.feature @grgprarup https://github.com/owncloud/ocis/pull/9080 https://github.com/owncloud/ocis/pull/9221
- [x] apiSpacesShares/etagPropagation.feature @grgprarup https://github.com/owncloud/ocis/pull/9090
- [x] apiSpacesShares/favorite.feature @grgprarup https://github.com/owncloud/ocis/pull/9090
- [x] apiSpacesShares/moveSpaces.feature @grgprarup https://github.com/owncloud/ocis/pull/9090
- [x] apiSpacesShares/publicLinkDownload.feature @grgprarup https://github.com/owncloud/ocis/pull/9120
- [x] apiSpacesShares/shareOperations.feature @grgprarup https://github.com/owncloud/ocis/pull/9120
- [x] apiSpacesShares/shareSpaces.feature @grgprarup https://github.com/owncloud/ocis/pull/9140 https://github.com/owncloud/ocis/pull/9221
- [x] apiSpacesShares/shareSpacesViaLink.feature @grgprarup https://github.com/owncloud/ocis/pull/9140
- [x] apiSpacesShares/shareSubItemOfSpace.feature @grgprarup https://github.com/owncloud/ocis/pull/9140
- [x] apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature @grgprarup https://github.com/owncloud/ocis/pull/9143
- [x] apiSpacesShares/shareUploadTUS.feature @grgprarup https://github.com/owncloud/ocis/pull/9143
- [x] apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature https://github.com/owncloud/ocis/pull/9221
- [x] parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature https://github.com/owncloud/ocis/pull/9221
</details>

<details>
<summary><strong>API Test Suites</strong></summary>

- [x] coreApiFavorites/favoritesSharingToShares.feature @S-Panta https://github.com/owncloud/ocis/pull/9118
- [x] coreApiMain/checksums.feature @grgprarup https://github.com/owncloud/ocis/pull/9217
- [x] coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature @grgprarup https://github.com/owncloud/ocis/pull/9217
- [x] coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature @grgprarup https://github.com/owncloud/ocis/pull/9217
- [x] coreApiShareManagementBasicToShares @S-Panta https://github.com/owncloud/ocis/pull/9142
- [x] coreApiShareManagementToShares @S-Panta https://github.com/owncloud/ocis/pull/9184 https://github.com/owncloud/ocis/pull/9221
- [x] coreApiShareOperationsToShares1/accessToShare.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/changingFilesShare.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/gettingShares.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9162
- [x] coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9191 https://github.com/owncloud/ocis/pull/9221
- [x] coreApiShareOperationsToShares2/shareAccessByID.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9191
- [x] coreApiShareOperationsToShares2/uploadToShare.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9191 https://github.com/owncloud/ocis/pull/9221
- [x] coreApiSharePublicLink1/accessToPublicLinkShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9174
- [x] coreApiSharePublicLink1/changingPublicLinkShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9174
- [x] coreApiSharePublicLink1/createPublicLinkShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9174
- [x] coreApiSharePublicLink1/deletePublicLinkShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9174
- [x] coreApiSharePublicLink2/copyFromPublicLink.feature @grgprarup https://github.com/owncloud/ocis/pull/9202
- [x] coreApiSharePublicLink2/multilinkSharing.feature @grgprarup https://github.com/owncloud/ocis/pull/9202
- [x] coreApiSharePublicLink2/updatePublicLinkShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9202
- [x] coreApiSharePublicLink2/uploadToPublicLinkShare.feature @grgprarup https://github.com/owncloud/ocis/pull/9202
- [x] coreApiShareUpdateToShares/updateShare.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9218 https://github.com/owncloud/ocis/pull/9221
- [x] coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature @Salipa-Gurung https://github.com/owncloud/ocis/pull/9218
- [x] coreApiTrashbin/trashbinFilesFolders.feature @grgprarup https://github.com/owncloud/ocis/pull/9215
- [x] coreApiTrashbin/trashbinSharingToShares.feature @grgprarup https://github.com/owncloud/ocis/pull/9215
- [x] coreApiVersions/fileVersionAuthor.feature @grgprarup https://github.com/owncloud/ocis/pull/9216
- [x] coreApiVersions/fileVersions.feature @grgprarup https://github.com/owncloud/ocis/pull/9216
- [x] coreApiWebdavEtagPropagation1/deleteFileFolder.feature @grgprarup https://github.com/owncloud/ocis/pull/9203
- [x] coreApiWebdavEtagPropagation1/moveFileFolder.feature @grgprarup https://github.com/owncloud/ocis/pull/9203
- [x] coreApiWebdavEtagPropagation2/copyFileFolder.feature @grgprarup https://github.com/owncloud/ocis/pull/9203
- [x] coreApiWebdavEtagPropagation2/createFolder.feature @grgprarup https://github.com/owncloud/ocis/pull/9203
- [x] coreApiWebdavEtagPropagation2/upload.feature @grgprarup https://github.com/owncloud/ocis/pull/9203
- [x] coreApiWebdavMove2/moveShareOnOcis.feature @grgprarup https://github.com/owncloud/ocis/pull/9204
- [x] coreApiWebdavOperations/listFiles.feature @grgprarup https://github.com/owncloud/ocis/pull/9207
- [x] coreApiWebdavOperations/propfind.feature @grgprarup https://github.com/owncloud/ocis/pull/9207
- [x] coreApiWebdavPreviews/previews.feature @grgprarup https://github.com/owncloud/ocis/pull/9206
- [x] coreApiWebdavProperties/copyFile.feature @grgprarup https://github.com/owncloud/ocis/pull/9213
- [x] coreApiWebdavProperties/createFileFolderWhenSharesExist.feature @grgprarup https://github.com/owncloud/ocis/pull/9213
- [x] coreApiWebdavProperties/getFileProperties.feature @grgprarup https://github.com/owncloud/ocis/pull/9213
- [x] coreApiWebdavProperties/getQuota.feature @grgprarup https://github.com/owncloud/ocis/pull/9213
- [x] coreApiWebdavProperties/setFileProperties.feature @grgprarup https://github.com/owncloud/ocis/pull/9213
- [x] coreApiWebdavUpload/uploadFile.feature https://github.com/owncloud/ocis/pull/9221
- [x] coreApiWebdavUploadTUS/uploadFileMtimeShares.feature https://github.com/owncloud/ocis/pull/9221
- [x] coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature https://github.com/owncloud/ocis/pull/9221
- [x] coreApiWebdavUploadTUS/uploadToShare.feature https://github.com/owncloud/ocis/pull/9221
</details>

**Comment by S-Panta** [comment]
To-do
- [ ] antivirus.feature
- [ ] downloadById.feature
- [ ] downloadByPath.feature
- [ ] propfind.feature
- [ ] sharesReport.feature
- [ ] spacesSharesReport.feature
- [ ] propfind.feature
- [ ] download.feature
- [ ] spaceDownload.feature
- [ ] enforcePasswordPublicLink.feature
- [ ] userGDPRExport.feature
- [ ] deleteGroup.feature
- [ ] deleteUser.feature
- [ ]

**Comment by S-Panta** [comment]
Function to be refactored
- [ ] userHasCreatedAPublicLinkShareWithSettings

**Comment by S-Panta** [comment]
What about sharing spaces? @saw-jan

**Comment by saw-jan** [comment]
> What about sharing spaces? @saw-jan

All sharing Given steps need to be done using graphAPI wherever possible

**Comment by S-Panta** [comment]
@saw-jan should this  `acceptance/features/apiReshare/resharing.feature` file be refactored?

**Comment by saw-jan** [comment]
> @saw-jan should this `acceptance/features/apiReshare/resharing.feature` file be refactored?

Let's skip that one for now

**Comment by S-Panta** [comment]
I think anyone working in this PR, it would be easier to work as folderwise.

**Comment by saw-jan** [comment]
The sharing steps have changed. Please be aware of the new available steps: https://github.com/owncloud/ocis/pull/9097

CC @grgprarup @Salipa-Gurung @S-Panta

**Comment by grgprarup** [comment]
> The sharing steps have changed. Please be aware of the new available steps: #9097
> 
> CC @grgprarup @Salipa-Gurung @S-Panta

The available steps are updated at the top of this issue.

**Comment by saw-jan** [comment]
> - [ ] Cleanup leftovers and step implementation @grgprarup

let's wait for removal of ocs sharing for this.

we can close this if all suites and features have been through

**Comment by grgprarup** [comment]
The `graph API` steps are used instead of the `sharing API` in the `given` steps. All the suites are covered and related PRs are merged so closing this issue.

**Comment by ScharfViktor** [comment]
great job 👍 
maybe we could change Given steps for e2e tests?
example https://github.com/owncloud/web/blob/master/tests/e2e/support/api/share/share.ts#L35-L67
@saw-jan do we have task for that?

**Comment by saw-jan** [comment]
>do we have task for that?

I don't remember any ticket. If we want to go full-on with sharingNG in e2e then I can create one.

**Comment by saw-jan** [comment]
Anyway, I create the one. https://github.com/owncloud/web/issues/10949
