### ISSUE TITLE
Make space image and readme upload more convinient

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/ocis#8719]
To enhance the efficiency and convenience of managing the `.space` folder and its associated functionalities, the following improvements are proposed:

1. Ensure the Persistence of the .space Folder:
   The `.space` folder should be inherently integral to the system and therefore should not be subject to deletion unless the entire space or drive itself is deleted. This ensures the stability and consistency of the structure.
The same applies to the auto-generated markdown file in the .space folder

2. Implement Automatic Patching during Upload:
   Rather than requiring clients to manually patch the drive (specialFolder) after uploading a space image or readme, the server should handle this task automatically. This can be achieved by introducing parameters such as `isSpaceReadme=true` or `isSpaceImage=true` during the upload process. By incorporating this functionality into the upload procedure, unnecessary requests are eliminated, streamlining the process for clients and facilitating easier implementation by other clients.

By adopting these enhancements, we not only optimize the management of the `.space` folder but also improve the overall integration for other clients. These modifications are designed to be non-disruptive, ensuring compatibility with existing systems while offering significant benefits in terms of efficiency and usability.

cc @kulmann @micbar

**Comment by micbar** [comment]
@AlexAndBear @kobergj

I think you already implemented some improvements. Can this be closed?

**Comment by AlexAndBear** [comment]
@micbar none of these has been implemented. This is a follow up after the improvements @kobergj did

**Comment by AlexAndBear** [comment]
@micbar none of these has been implemented. This is a follow up after the improvements @kobergj did

**Comment by butonic** [comment]
- [ ] prevent deleting .space
- [ ] WebDAV request should check `isSpaceReadme=true` and `isSpaceImage=true` query headers to automatically set the file as space readme / image if the path is in the .space folder.

**Comment by AlexAndBear** [comment]
I don't think setting isSpaceReadme=true is not necessary anymore, if we disable the ability to delete the .space/readme.md file (which is auto generated, when a space is created).

**Comment by AlexAndBear** [comment]
In every folder? What's the purpose of this ? 

Space readme can an should be hardcoded now. For image: can do that as well but I don't know how you might do this because of the different formats.

**Comment by butonic** [comment]
So you can give subfolders their own Readme / image. Github also renders the Readme in every directory of a repo.

And on my desktop I can also assign a custom folder icon.

**Comment by 2403905** [comment]
The @butonic 's approach is looking more generic  👍

**Comment by butonic** [comment]
> The .space folder is used to store metadata, such as images and readme files, related to the space.

anything else? the .space folder was originally intended to allow users to sync the image and readme to edit them on their desktop machines, IIRC.

> We introduced this hidden .space folder to protect these files from being accidentally deleted by non-technical users who might not know how to restore or recreate them.

They can always be restored from the trash.

> However, there are some issues with the current approach, particularly with using hardcoded image formats (.png, .bmp, .gif, .jpg, etc.):
> 
> If multiple images with the same name but different formats are present, it becomes unclear which image should be displayed. While we could default to a preferred file type, this can be difficult to communicate to users.

Stick to two formats or just one ... IIRC windows would show folder.jpg as icons ... which seems to be an interesting feature, as [as tons of people are complaining if ms tries to ditch it](https://answers.microsoft.com/en-us/windows/forum/windows_11-files/windows-11-folder-custom-icon-issue/1e909c04-28be-4843-b126-f2b8befed0fd?messageId=775802b5-d592-4dee-aabb-687dfe8e6546&page=2)

We would have to document something anyway. The less options we give the easier it is to document and implement.

> The user interface includes a convenient feature that allows users to right-click and set an image as the space image. With the .space folder in use, the selected image is copied to the metadata folder. If we were to use the root folder for this purpose, it would require replacing an existing file, potentially leading to unintended data loss if the previous image is overwritten.

Again, we have revisions. Nothing is lost.

**Comment by AlexAndBear** [comment]
> The @butonic 's approach is looking more generic 👍

It is, but it requires some additional work:

1. Clear communication to users about how to set the image and readme.
2. A method for choosing which `image.x` to display when multiple options exist (perhaps based on the last modified date).
3. Measures to prevent data loss, such as an overwrite confirmation dialog.
4. Ensuring that the space template is copied to the root folder of the space, rather than the `.space` folder.
5. Removing any leftover `specialFolder` elements in web.
6. Adjusting code paths to enable displaying images and readme files not just for spaces but also for regular folders in web.

**Comment by tbsbdr** [comment]
@tbsbdr schedule meeting to clarify how to proceed

**Comment by butonic** [comment]
I propose to proceed in two steps:
1. To prevent users from accidentially deleting metadata, deny deletion of the `.space` folder and the auto-generated markdown file.
2. ADR a generic solution for any space and folder using a `README.md` (as known from github) and `folder.jpg` (as known from windows, [osx does not seem to support it](https://discussions.apple.com/thread/1965156)). We can discuss other file name options in the ADR.

Regarding 1: I remember problems with the oc10 `Shares` folder being readonly/undeletable and the deskop client trying to sync a local deletion back to the server. @TheOneRing how would the client handle this today? I imagine the VFS could prevent deletion, but sync on linux cannot ... but ... I know nothing ;-)

**Comment by tbsbdr** [comment]
puh, I dont know what problem we are trying to solve here. could you please rephrase your issue with our bug- or story template @AlexAndBear ?

**Comment by AlexAndBear** [comment]
I am closing the issue, this should be just an easy enhancement to save some requests and solve some edge cases on top the improvements @kobergj already this. But since the issue is getting out of our hands and leads to endless discussions: **closed**
