### ISSUE TITLE
[Sharing-NG] creating a drive item with random item id results in 201 response.

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#8724]
## Describe the bug
Giving any random string ( other than an empty string) as a remote item ID for creating a drive item gives a 201 status code. The response will be empty though. 

## Steps to reproduce
1. login to ocis as user `user`.
2. go to shares and make API post request to create a drive item with some string.
```
curl -X POST 'https://host.docker.internal:9200/graph/v1beta1/drives/{share-Space-Id}/root/children'  
-d '{
    "remoteItem": {
        "id":"'123"
    }
}' -uadmin:admin
```
4. The status code is 201.

It only checks for valid sharespace id and if remoteitem has empty string or not. 
What should the expected behavior and status code be?

**Comment by rhafer** [comment]
I think this should return a 400 (Bad Request)

**Comment by S-Panta** [comment]
Also, once the sharer send the request for creating drive item and if the shares is `unmounted`, API call to this endpoint change the @client.synchronize property of the driveItem  to true and the body returns drive item.  If multiple API call is done to same endpoint, the status code will still be 201 though the body remain empty. Is this the expected behavior?
