### ISSUE TITLE
Enumeration of email adresses is possible

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#8726]
## Steps to reproduce
1. open share panel and type "alb"
2. email adress of albert is exposed
3. Enumeration of email adresses is possible

![screenshot_002503](https://github.com/owncloud/web/assets/26610733/05ecfabb-f8f6-402b-a6a2-1713cdd395c4)

## Expected behavior
email adresses of users can not be enumerated
- remove email adress so that it complies with GDPR (remove from `get user` and `search` using graphapi)
- show username (eg. alb.einstein) next to display name so that users can be identified uniquely 

![screenshot_002504](https://github.com/owncloud/web/assets/26610733/6984c363-77f3-4e5b-a12a-4bf01905c23c)

## Actual behavior
- Enumeration of email adresses is possible

relates to
https://github.com/owncloud/enterprise/issues/6516

## Implementation detail
- fix for OCS and graph

**Comment by micbar** [comment]
Needs fix on ocs and backport to 5.0

**Comment by dragonchaser** [comment]
@tbsbdr should this be a configuration switch to choose whether the mail should be shown/searchable or not?

**Comment by tbsbdr** [comment]
Yes, agreed. Making ist configurable would ne Cherry in top. Default should be the "Safe path" - No email

**Comment by dragonchaser** [comment]
fixed in master, backport incoming

**Comment by dragonchaser** [comment]
@JammingBen is it working for you to use the additionalAttributes again?

**Comment by JammingBen** [comment]
> @JammingBen is it working for you to use the additionalAttributes again?

I don't quite understand, what do you mean by "use it again"? 😅 

In the OCS API, the `shareWithAdditionalInfo` prop just needs to replace the email with the username for Web to display it correctly. In graph I think you just mask the `mail` property in the response? Web then goes for the `onPremisesSamAccountName` instead I suppose.

**Comment by JammingBen** [comment]
Ah no, but the endpoint for retrieving users to share a file with has been changed with sharing NG. Web is using `graph/v1.0/users` for that. And since it doesn't return `shareWithAdditionalInfo`, Web currently uses the `mail` prop (`onPremisesSamAccountName` in the future then).

**Comment by JammingBen** [comment]
Web actually doesn't need a backport since the old version only relies on the `shareWithAdditionalInfo` property. Meaning if this now contains the username instead of the email, Web is totally fine with it.

**Comment by dragonchaser** [comment]
Merged in Master backport in progress, currently blocked until https://github.com/cs3org/reva/pull/4609 is merged

**Comment by dragonchaser** [comment]
All backports done, just needs a new ocis release for the backports, can we close this?

**Comment by micbar** [comment]
Released with ocis 5.0.1.

**Comment by ScharfViktor** [comment]
tested on stable-5.0 branch
 
- by default: `OCIS_SHOW_USER_EMAIL_IN_RESULTS=true` that matches docs https://doc.owncloud.com/ocis/5.0/deployment/services/s-list/frontend.html - ✅ 

start ocis with `OCIS_SHOW_USER_EMAIL_IN_RESULTS=false`:
- no email in the sharees response 
`GET https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=mar` ✅ 
- but recipient email is exist in the shares response 
`POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares` :x:
<img width="1672" alt="Screenshot 2024-04-15 at 09 43 03" src="https://github.com/owncloud/ocis/assets/84779829/bddc48d0-21e7-4228-b631-fc66201e6a2e">
- recipient email is exist in the Access details: :x:
<img width="618" alt="Screenshot 2024-04-15 at 09 45 07" src="https://github.com/owncloud/ocis/assets/84779829/ecd32f31-0ffd-45d4-b3fd-b5ff709830df">
<img width="611" alt="Screenshot 2024-04-15 at 09 44 24" src="https://github.com/owncloud/ocis/assets/84779829/f29be956-ca61-47ea-a9f5-bbf4d3050085">
- recipient's email is available using the graph endpoints :x:
<img width="1218" alt="Screenshot 2024-04-15 at 09 49 01" src="https://github.com/owncloud/ocis/assets/84779829/2b5d0ee8-947c-4c1c-ba7c-10f7e4b8c20d">
<img width="1048" alt="Screenshot 2024-04-15 at 09 52 01" src="https://github.com/owncloud/ocis/assets/84779829/586c8115-23e8-48e6-a293-716b6280945c">
