### ISSUE TITLE
[QA] Moving files in a shared folder causes errors but succeeds

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#873]
Setup: docker-compose-eos-test.yml
* user einstein shares a folder 'to-marie' containing two files with user marie
* user marie accepts the folder,
* user marie enter the folder, creates a subfolder, and moves the two files in the subfolder.

Errors appear:
![image](https://user-images.githubusercontent.com/1108546/99374113-87ad9a80-28c2-11eb-92b4-3301475f4bc5.png)

Althoug the move was executed correctly.

**Comment by jnweiger** [comment]
Reproduced differently with rc6

* as above
* marie sees no errors,
* but when einstein visits the folder after marie did the move, he gets
![image](https://user-images.githubusercontent.com/1108546/100766053-8028de00-33f8-11eb-9650-7fcdc67f5543.png)
[ocis.log.zip](https://github.com/owncloud/ocis/files/5623891/ocis.log.zip)

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: check if there ad API & UI tests for that case, if not add them
