### ISSUE TITLE
[QA] sharer breaks sharees home by removing a shared folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#875]
Setup with docker-compose-eos-test.yml at v1.0.0rc3
* einstein creates folder `to-richard` and adds two files in there.
* einstein shares with user richard as editor,
* richard accepts the share, and sees that everything is there in his /Shared folder.
* einstein deletes the folder `to-richard`

Richard refreshes his view and gets an error:
![image](https://user-images.githubusercontent.com/1108546/99383221-d90f5700-28cd-11eb-80d9-45647d9af4d3.png)

His home folder is now broken. He cannot do anything there.
'Sharred with me' shows an unnamed folder from einstein now:
![image](https://user-images.githubusercontent.com/1108546/99383732-9732e080-28ce-11eb-8aeb-31df395fd22c.png)

Logs snippet:
ocis          | 2020-11-17T11:11:25Z DBG NodeFromPath() walk node={"Exists":true,"ID":"f82924ba-4954-4eff-9d95-a595c128d408","Name":"einstein@example.org","ParentID":"e80f1cd7-d510-4911-a78e-3a03b5cb8c96"} pkg=rht
tp service=storage traceid=f4c702e880d7b62f11ed93ded32f8a24 
ocis          | 2020-11-17T11:11:25Z DBG user is owner, returning owner permissions node={"Exists":true,"ID":"f82924ba-4954-4eff-9d95-a595c128d408","Name":"einstein@example.org","ParentID":"e80f1cd7-d510-4911-a78e
-3a03b5cb8c96"} pkg=rhttp service=storage traceid=f4c702e880d7b62f11ed93ded32f8a24
ocis          | 2020-11-17T11:11:25Z INF http end="17/Nov/2020:11:11:25 +0000" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=36 start="17/Nov/2020:11:11:25 +0000" status=200 time_ns=31062
4 traceid=f4c702e880d7b62f11ed93ded32f8a24 uri=/data/index.cs3/unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.Mail/einstein@example.org url=/data/index.cs3/unique.github.com.owncloud.ocis.accounts.p
kg.proto.v0.Account.Mail/einstein@example.org
ocis          | 2020-11-17T11:11:25Z DBG found account AccountEnabled=true CreatedDateTime=null DeletedDateTime=null Description= DisplayName="Albert Einstein" GidNumber=30000 Id=4c510ada-c86b-4815-8820-42cdf82c3d
51 Identities=null IsResourceAccount=false Mail=einstein@example.org MemberOf=[{"id":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa"},{"id":"6040aa17-9c64-4fef-9bd0-77234d71bad0"},{"id":"dd58e5ec-842e-498b-8800-61f2ec6f911
f"},{"id":"262982c1-2362-4afa-bfdf-8cbfef64a06e"}] OnPremisesDistinguishedName= OnPremisesLastSyncDateTime=null OnPremisesSamAccountName=einstein OnPremisesSecurityIdentifier= OnPremisesSyncEnabled=false OnPremise
sUserPrincipalName= PreferredName=einstein UidNumber=20000 service=accounts
ocis          | 2020-11-17T11:11:25Z DBG Associated claims with uuid account={"accountEnabled":true,"displayName":"Albert Einstein","gidNumber":"30000","id":"4c510ada-c86b-4815-8820-42cdf82c3d51","mail":"einstein@
example.org","memberOf":[{"description":"A group every normal user belongs to.","displayName":"Users","gidNumber":"30000","id":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa","onPremisesSamAccountName":"users"},{"displayNa
me":"Sailing lovers","gidNumber":"30001","id":"6040aa17-9c64-4fef-9bd0-77234d71bad0","onPremisesSamAccountName":"sailing-lovers"},{"displayName":"Violin haters","gidNumber":"30002","id":"dd58e5ec-842e-498b-8800-61f2ec6f911f","onPremisesSamAccountName":"violin-haters"},{"displayName":"Physics lovers","gidNumber":"30007","id":"262982c1-2362-4afa-bfdf-8cbfef64a06e","onPremisesSamAccountName":"physics-lovers"}],"onPremisesSamAccountName":"einstein","passwordProfile":{},"preferredName":"einstein","uidNumber":"20000"} claims={"email":"einstein@example.org","family_name":"einstein","iss":"https://localhost:9200","name":"einstein","preferred_username":"einstein","sub":"XtSi_miyWSB-pkvGnxPoC5A4flih0UCLgvU7cLwjmjCKX7FYn2HWk6rRCEuy2G5qAy_yMQc_FK9aNFhUMrX2pQ@konnect"} service=proxy
ocis          | 2020-11-17T11:11:25Z DBG found account AccountEnabled=true CreatedDateTime=null DeletedDateTime=null Description= DisplayName="Albert Einstein" GidNumber=30000 Id=4c510ada-c86b-4815-8820-42cdf82c3d51 Identities=null IsResourceAccount=false Mail=einstein@example.org MemberOf=[{"id":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa"},{"id":"6040aa17-9c64-4fef-9bd0-77234d71bad0"},{"id":"dd58e5ec-842e-498b-8800-61f2ec6f911f"},{"id":"262982c1-2362-4afa-bfdf-8cbfef64a06e"}] OnPremisesDistinguishedName= OnPremisesLastSyncDateTime=null OnPremisesSamAccountName=einstein OnPremisesSecurityIdentifier= OnPremisesSyncEnabled=false OnPremisesUserPrincipalName= PreferredName=einstein UidNumber=20000 service=accounts
ocis          | 2020-11-17T11:11:25Z DBG skipping auth method=/cs3.gateway.v1beta1.GatewayAPI/CreateHome pkg=rgrpc service=storage traceid=cbbb9ca00f68127f43188bf465ab2e96
ocis          | 2020-11-17T11:11:25Z INF unary code=OK end="17/Nov/2020:11:11:25 +0000" from=tcp://127.0.0.1:59592 pkg=rgrpc service=storage start="17/Nov/2020:11:11:25 +0000" time_ns=90263 traceid=cbbb9ca00f68127f43188bf465ab2e96 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
ocis          | 2020-11-17T11:11:25Z DBG eos: wrap external=/ internal=/eos/dockertest/reva/users/4/4c510ada-c86b-4815-8820-42cdf82c3d51 pkg=rgrpc service=storage traceid=cbbb9ca00f68127f43188bf465ab2e96
ocis          | 2020-11-17T11:11:25Z INF eos cmd args="[/usr/bin/eos -r 20002 30000 file info inode:49 -m --comment 63ad77ba1d237d1e35ada5cbbd26d587]" env=[EOS_MGM_URL=root://mgm-master.testnet:1094] err= exit=0 pkg=rgrpc service=storage traceid=63ad77ba1d237d1e35ada5cbbd26d587
ocis          | 2020-11-17T11:11:25Z ERR root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/storageprovider/storageprovider.go:507 > error stating: id:<storage_id:"1284d238-aa92-42ce-bdc4-0b0000009157" opaque_id:"49" >  error="eos: error resolving reference: error: not found: eos: path is outside namespaces: path=/eos/test/proc/recycle/uid:20000/2020/11/17/0/#:#eos#:#dockertest#:#reva#:#users#:#4#:#4c510ada-c86b-4815-8820-42cdf82c3d51#:#to-richard.0000000000000031.d namespaces=[/eos/dockertest/reva/users /eos/dockertest/reva/users/.shadow]" pkg=rgrpc service=storage traceid=63ad77ba1d237d1e35ada5cbbd26d587
ocis          | 2020-11-17T11:11:25Z INF unary code=OK end="17/Nov/2020:11:11:25 +0000" from=tcp://127.0.0.1:38112 pkg=rgrpc service=storage start="17/Nov/2020:11:11:25 +0000" time_ns=15339897 traceid=63ad77ba1d237d1e35ada5cbbd26d587 uri=/cs3.storage.provider.v1beta1.ProviderAPI/Stat user-agent=grpc-go/1.26.0
ocis          | 2020-11-17T11:11:25Z ERR root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1637 > gateway: error resolving reference:/home/Shares/to-richard error="gateway: error stating target reference" pkg=rgrpc service=storage traceid=63ad77ba1d237d1e35ada5cbbd26d587
ocis          | 2020-11-17T11:11:25Z ERR root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1267 > gateway: error stating shares folder error="gateway: grpc failed with code CODE_INTERNAL" pkg=rgrpc service=storage traceid=63ad77ba1d237d1e35ada5cbbd26d587
ocis          | 2020-11-17T11:11:25Z ERR root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1224 > gateway: error stating shares folder error="gateway: grpc failed with code CODE_INTERNAL" pkg=rgrpc service=storage traceid=63ad77ba1d237d1e35ada5cbbd26d587
ocis          | 2020-11-17T11:11:25Z INF unary code=OK end="17/Nov/2020:11:11:25 +0000" from=tcp://127.0.0.1:59738 pkg=rgrpc service=storage start="17/Nov/2020:11:11:24 +0000" time_ns=898243736 traceid=63ad77ba1d237d1e35ada5cbbd26d587 uri=/cs3.gateway.v1beta1.GatewayAPI/Stat user-agent=grpc-go/1.26.0
ocis          | 2020-11-17T11:11:25Z ERR grpc stat request failed path=/home pkg=rhttp service=storage status={"code":15,"message":"gateway: error stating shares folder","trace":"63ad77ba1d237d1e35ada5cbbd26d587"} traceid=63ad77ba1d237d1e35ada5cbbd26d587
ocis          | 2020-11-17T11:11:25Z ERR http end="17/Nov/2020:11:11:25 +0000" host=127.0.0.1 method=PROPFIND pkg=rhttp proto=HTTP/1.1 service=storage size=0 start="17/Nov/2020:11:11:24 +0000" status=500 time_ns=899200123 traceid=63ad77ba1d237d1e35ada5cbbd26d587 uri=/remote.php/webdav/ url=/remote.php/webdav/
ocis          | 2020-11-17T11:11:25Z INF eos cmd args="[/usr/bin/eos -r 0 0 file info /eos/dockertest/reva/users/4/4c510ada-c86b-4815-8820-42cdf82c3d51 -m --comment cbbb9ca00f68127f43188bf465ab2e96]" env=[EOS_MGM_URL=root://mgm-master.testnet:1094] err= exit=0 pkg=rgrpc service=storage traceid=cbbb9ca00f68127f43188bf465ab2e96
ocis          | 2020-11-17T11:11:25Z DBG director found path=/konnect/v1/userinfo policy=reva prefix=/konnect/ routeType=prefix service=proxy
ocis          | 2020-11-17T11:11:25Z DBG Bind request basedn=dc=example,dc=org binddn=cn=reva,ou=sysusers,dc=example,dc=org handler=ocis service=glauth src={"IP":"127.0.0.1","Port":34590,"Zone":""}
ocis          | 2020-11-17T11:11:25Z INF access token is already provided pkg=rhttp service=storage traceid=abcd47b404be3030e83b7701c5e08b33
ocis          | 2020-11-17T11:11:25Z DBG http routing: head=data tail=/index.cs3/unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.OnPremisesSamAccountName/reva svc=data pkg=rhttp service=storage
ocis          | 2020-11-17T11:11:25Z DBG NodeFromPath() fn=/index.cs3/unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.OnPremisesSamAccountName/reva pkg=rhttp service=storage traceid=abcd47b404be3030e

**Comment by jnweiger** [comment]
[ocis875.logs.zip](https://github.com/owncloud/ocis/files/5553088/ocis875.logs.zip)

**Comment by phil-davis** [comment]
@individual-it @dpakach I feel like this issue was notice a week or 2 ago and one of you (?) raised an issue about it, and we should link to this issue also.

**Comment by jnweiger** [comment]
(I actually tried to break it the other way round. Share receiver does somthing that break the share for the share owner. I think I had that situation too, but cannot reproduce now.)

**Comment by individual-it** [comment]
there are multiple issues with deleting shares:
 - deleting share response does not contain `data` field #721 
 - deleting a folder should delete share links to it as well #801 
 - Cannot delete a received share #714 

we should write a test for this particular situation (if there are non yet)

**Comment by refs** [comment]
Just replicated this set of steps using the ocis storage and was not able to reproduce it, after reloading my home folder as Richard, the `/Shares` folder still exists but it contains nothing since Einstein deleted the shared folder.
