### ISSUE TITLE
https://owncloud.dev/ocis/deployment/ocis_wopi/#local-setup-for-web-development

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/ocis#8757]
https://owncloud.dev/ocis/deployment/ocis_wopi/#local-setup-for-web-development

```pnpm && pnpm build:w``` seems wrong

I assume this should be
```pnpm i && pnpm build:w```

**Comment by kulmann** [comment]
> https://owncloud.dev/ocis/deployment/ocis_wopi/#local-setup-for-web-development
> 
> `pnpm && pnpm build:w` seems wrong
> 
> I assume this should be `pnpm i && pnpm build:w`

Yes, that's a search&replace error from when we switched from `yarn` to `pnpm`.

**Comment by DeepDiver1975** [comment]
pr open ....

**Comment by DeepDiver1975** [comment]
Looks like there is more to change .....
```
DEPRECATION: WEB_ASSET_PATH is deprecated and will be removed in the future. Use WEB_ASSET_CORE_PATH instead.
```
