### ISSUE TITLE
WSL does not support `:` in extended attribute names

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#876]
When trying to run ocis in WSL the ocis driver tries to persist the grants using an extended attribute like this:
`user.ocis.grant.u:f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c` which leads to an `invalid argument` error because it does not like the `:`.

Can be reproduced with:
```
➜  4c510ada-c86b-4815-8820-42cdf82c3d51 setfattr -n user.ocis.grant.u:f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c -v a . 
setfattr: ../19941f00-0dd8-411a-b3a3-99004aad42bd: Invalid argument
➜  4c510ada-c86b-4815-8820-42cdf82c3d51 setfattr -n user.ocis.grant.u.f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c -v "a" .
➜  4c510ada-c86b-4815-8820-42cdf82c3d51
```

We could change all xattr names to only use dots.

What works: `.#()~$!@{}%&^`
What not works `:;[]=|+?\/<>",`

**Comment by micbar** [comment]
ocis doesn't use xattrs anymore.
