### ISSUE TITLE
[Sharing NG] Unable to remove groups from spaces

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8768]
## Describe the bug
Removing groups from space memberships is not possible.

## Steps to reproduce
1. Add a group to a space as member (see curl down below)
2. Remove this group again (see curl down below)

## Expected behavior
The group will be removed.

## Actual behavior
There is an error: `rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference`.

## Curls
Invite: `curl $'https://host.docker.internal:9200/graph/v1beta1/drives/1c1a1c30-ec26-434e-b328-faf26ee52999%24bed97b18-a645-4946-933f-663d3f589af4/items/1c1a1c30-ec26-434e-b328-faf26ee52999%24bed97b18-a645-4946-933f-663d3f589af4\u0021bed97b18-a645-4946-933f-663d3f589af4/invite' \
  -H 'authorization: {token}' \
  --data-raw '{"roles":["a8d5fe5e-96e3-418d-825b-534dbdf22b99"],"expirationDateTime":null,"recipients":[{"objectId":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa","@libre.graph.recipient.type":"group"}]}' \
  --insecure`

Remove: `curl $'https://host.docker.internal:9200/graph/v1beta1/drives/1c1a1c30-ec26-434e-b328-faf26ee52999%24bed97b18-a645-4946-933f-663d3f589af4/items/1c1a1c30-ec26-434e-b328-faf26ee52999%24bed97b18-a645-4946-933f-663d3f589af4\u0021bed97b18-a645-4946-933f-663d3f589af4/permissions/g%3A509a9dcd-bb37-4f4f-a01a-19dca27d9cfa' \
  -X 'DELETE' \
  -H 'authorization: {token}' \
  --insecure`

**Comment by phil-davis** [comment]
I am surprised that there is no test case for this, I expected that there would be a failing test.
