### ISSUE TITLE
Build to dev docs is broken 

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#8774]
As discussed in chat, changes to dev docs content dont arrive there as building errors.

These are the current findings respectively comments I got:

* @micbar https://drone.owncloud.com/owncloud/owncloud.github.io/14355/1/4
* From @fschade -->
@JammingBen can you have a look, [web.md](https://web.md/) not there, maybe you forgot to commit it?
https://github.com/owncloud/web/blob/693d6e35aba2832db2c031c3e174abd9a4bd8a8a/docs/extension-system/_index.md?plain=1#L89
* @kulmann The file ref is wrong
Web also only deploys from master
The reference is supposed to point to the ocis web service main dev docs page

@mbarz for reference, the discussion started on March 22nd

This needs to be fixed.

**Comment by JammingBen** [comment]
> * @JammingBen can you have a look, [web.md](https://web.md/) not there, maybe you forgot to commit it?
>   https://github.com/owncloud/web/blob/693d6e35aba2832db2c031c3e174abd9a4bd8a8a/docs/extension-system/_index.md?plain=1#L89

The "Web" page I wanted to link to is a file in the [ocis repository](https://github.com/owncloud/ocis/blob/master/services/web/README.md#L40), therefore it's not present in the Web repository.

The question someone needs to answer: is it possible to link from the Web docs to the ocis docs? Because if not, we need to remove that reference. Maybe @micbar knows how to achieve it?

**Comment by mmattel** [comment]
> is it possible to link from the Web docs to the ocis docs?

Most likely via a full hard coded link like `https://owncloud.dev/...` as this crosses repos and as far I know, there is no equivalent of a content catalog like in antora where you can do internal cross repo references.

**Comment by JammingBen** [comment]
Also, the page we need to link to is actually not `web.md` but the `README.md` file of the web service in ocis (https://github.com/owncloud/ocis/blob/master/services/web/README.md). Does that mean the reference must be something like `../../../web/README.md` then? I'm really missing know-how about how these docs are being built/merged.

Again, as a quick fix I can offer to remove this reference for now. It would at least fix the pipeline issue.

**Comment by micbar** [comment]
We can find that out.

web code gets copied to a subfolder in the docs `content/clients/web` where ocis is copied into `content/`.

**Comment by micbar** [comment]
And we need to know, that the file https://github.com/owncloud/ocis/blob/master/services/web/README.md will be converted to `_index.md`

That means from the web docs root we have the relative path `../../services/web/_index.md`

**Comment by micbar** [comment]
Coming from https://github.com/owncloud/web/blob/693d6e35aba2832db2c031c3e174abd9a4bd8a8a/docs/extension-system/_index.md?plain=1#L89

It means you need to travel two more additional levels up because you are in `<web docs root>/extension-system/extension-types`.

**Comment by micbar** [comment]
so finally `../../../../services/web/_index.md` 

Let us give that a try 😏

**Comment by JammingBen** [comment]
As discussed in chat: it's currently not possible to go higher than the Web root level from inside the Web repository. Hence we decided to remove the reference.
