### ISSUE TITLE
[QA] unprivileged users can promote themselves to admin

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#879]
Setup via docker-compose-eos-test.yml at branch `fix-yml-for-rc5` on localhost
* `eos space set default on` for #862 
* Login user marie
* Click the 9 dots menu, select accounts.
* Note that marie is Role User.
* Try '+Create new account' -> it fails. Good.
* Switch Role from User to Admin.
![image](https://user-images.githubusercontent.com/1108546/99464216-e3663b00-2937-11eb-8eb9-b01b17a9d13e.png)
* Try '+Create new account' again.

![image](https://user-images.githubusercontent.com/1108546/99464303-19a3ba80-2938-11eb-8a05-11c1011e7637.png)

Oops.

Expected behavior: normal user cannot.

**Comment by kulmann** [comment]
We recently introduced a `SelfManagement` permission to the `User`role. As a result the accounts UI shows the logged in user. This made it possible here, to uncover that we in fact don't have any permission checks for assigning/unassigning roles. Needs to be implemented ASAP. Might make sense to move the role assignments to the account service in the same PR.

**Comment by C0rby** [comment]
@kulmann, what is the reason for moving the role assignments to the accounts service?
I understand that right now the accounts UI is depending on the settings service but when we move the assignments to the accounts service then the accounts backend will still depend on the settings service.

**Comment by kulmann** [comment]
@C0rby 
1. it would save us a request in the `account_resolve` middleware in the proxy, because we could return the role assignments directly from the account service instead of having to make a second request to the settings services.
2. when creating users we assign a role. that could happen in the same service then, so it reduces latency.

**Comment by C0rby** [comment]
Ah you mean we would even move the store to the accounts service?

**Comment by jnweiger** [comment]
Confirmed fixed in rc6

einstein can still change his role to admin in the web UI, but it has no effect. On a reload his role is shown as 'user' again. OK.
