### ISSUE TITLE
[QA][Sharing NG] test coverage for `/graph/v1beta1/drives/{driveId}/root` endpoint

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#8810]
There are few new API endpoint for graph API. 
https://github.com/owncloud/ocis/pull/8727

- [x] `POST` `/drives/{driveID}/root/invite`  https://github.com/owncloud/ocis/pull/8850
- [x] `POST` `/drives/{driveID}/root/createLink` @amrita-shrestha https://github.com/owncloud/ocis/pull/9076
- [x] `GET` `/drives/{driveID}/root/permissions` @amrita-shrestha https://github.com/owncloud/ocis/pull/8824 https://github.com/owncloud/ocis/pull/9125
- [x] remove access to the drive `DELETE` `/drives/{driveID}/root/permissions/{permissionID}` https://github.com/owncloud/ocis/pull/8879 https://github.com/owncloud/ocis/pull/8920 https://github.com/owncloud/ocis/pull/8986
- [x] remove space link `DELETE` `/drives/{driveID}/root/permissions/{permissionID}`  https://github.com/owncloud/ocis/pull/9123
- [x] `PATCH` `/drives/{driveID}/root/permissions/{permissionID}` @amrita-shrestha  https://github.com/owncloud/ocis/pull/8906
- [x] `POST` `/drives/{driveID}/root/permissions/{permissionID}/setPassword` https://github.com/owncloud/ocis/pull/9078

--------------------------Issues------------------------------------
- invite
     - https://github.com/owncloud/ocis/issues/8839

**Comment by amrita-shrestha** [comment]
all PR has been merged so closing this issue.
