### ISSUE TITLE
[Sharing NG] Wrong status code when editor member tries delete a space member 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8819]
Steps: 

- `user1` creates space 
- `user1` adds `user2` as manager member and `user3` as editor or viewer
- `user3` tries to delete `user1` or `user2` (space has have min one manager so we need 2 managers in this case)

Actual: `user3` can delete manager 
`curl $'https://host.docker.internal:9200/graph/v1beta1/drives/1c1a1c30-ec26-434e-b328-faf26ee52999%24bed97b18-a645-4946-933f-663d3f589af4/items/1c1a1c30-ec26-434e-b328-faf26ee52999%24bed97b18-a645-4946-933f-663d3f589af4\u0021bed97b18-a645-4946-933f-663d3f589af4/permissions/u:user1UUID' \ -X 'DELETE' \ -H 'authorization: {token}' \ --insecure`

Update: 500 error with `"message": "error removing storage grant"`
<img width="1434" alt="Screenshot 2024-04-11 at 11 35 01" src="https://github.com/owncloud/ocis/assets/84779829/9ddc58a5-73d0-425b-b8ec-d12e9c7c0e73">

Expect: 403 error with no permission

**Comment by rhafer** [comment]
Updated the title to better reflect the issue. It's not that Editor member can actually remove any other member. The request just fails with an inappropriate Status Code.

**Comment by rhafer** [comment]
proposed fix: https://github.com/cs3org/reva/pull/4652
