### ISSUE TITLE
[QA] Upgrade php version 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#8831]
## Describe
The PHP version employed in testing has reached its end of life, yet the tests continue to utilize an outdated PHP version on Drone CI.
![Screenshot from 2024-04-11 10-09-24](https://github.com/owncloud/ocis/assets/54478846/27be5a53-65a1-4754-a1a8-4ebdcf06336b)

## Drone screenshot
![image](https://github.com/owncloud/ocis/assets/54478846/de25f24a-fbf8-4206-a1fb-2c1ae53e6c5b)
![Screenshot from 2024-04-11 10-12-33](https://github.com/owncloud/ocis/assets/54478846/31069b41-b801-41d5-8a5a-3aa76a3229df)

## Question
1. Is there any reason for not using the latest PHP version?

cc @SagarGi @saw-jan @grgprarup

**Comment by phil-davis** [comment]
We added a lot of type declarations and associated "modern" stuff to the PHP test code.
The PHP test code is in the ocis repo these days, so is now separate from the oC10 PHP acceptance test code.
I think that it should be quite easy to run the PHP-based tests with PHP 8. We can try with the latest PHP 8.3

**Comment by micbar** [comment]
I agree, let us move forward.

**Comment by saw-jan** [comment]
- [ ] Need to update the version in compose setup:
https://github.com/owncloud/ocis/blob/43621b455551e2df93f7c44bb5159375cf5789a9/tests/acceptance/docker/src/acceptance.yml#L3
