### ISSUE TITLE
Deleting re-sharing from the code base

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8842]
resharing feature is not supported anymore: https://github.com/owncloud/docs-ocis/pull/739/files#diff-04cd79e526c8a7f0162d8fc5bc5fa8c501fe9e5899024268837c05a74349b26cR148-R149

- [x] make all api and ui tests happy https://github.com/owncloud/ocis/pull/8704
- [x] create negative tests when we verify that a resharing is not possible `tests/acceptance/features/apiReshare/resharing.feature`
- [x] delete all resharing unit tests. here were commented tests https://github.com/owncloud/ocis/pull/8704/files#diff-8b57150852b437d73b32911784f40991ab7f0d8f94468201c405ee3e7a5686feR735-R764 and https://github.com/owncloud/ocis/pull/8704/files#diff-af2466555f3858dc080336a3201445475fc162a82a0592d214f930b1ebdfa534R354-R375
- [x] deleting re-sharpening from the code base
- [x] delete all envs related re-sharing like `OCIS_ENABLE_RESHARING`
- [x] remove resharing from reva https://github.com/cs3org/reva/pull/4606
- [ ] default web client with `resharing=false`

cc @kobergj @saw-jan

**Comment by micbar** [comment]
Follow up here https://github.com/owncloud/web/issues/10771
