### ISSUE TITLE
[QA] Application switcher content shows settings element only after it was selected once

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#885]
Tested using oCIS 1.0.0.-RC5

Go to settings section in order to make it appear in the Application switcher menu. After refreshing the browser, it disappears again

![Screenshot 2020-11-18 at 11 17 38](https://user-images.githubusercontent.com/10596560/99521407-abd9ac00-2994-11eb-90db-e16c2544dec0.png)
![Screenshot 2020-11-18 at 11 47 14](https://user-images.githubusercontent.com/10596560/99521416-ada36f80-2994-11eb-891c-7eda775d17a3.png)

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0 vs web 4.1.0
is not reproducible
