### ISSUE TITLE
[ocis] SSE for moving a resource

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#8854]
# Description

## User Stories

* > As a user I want to know if a file got moved so that I know if the file is available for working. 

## Value
Transparency and user experience without errors.

## Acceptance Criteria
- let the client know if a resource got moved

**Implementation detail**
- needs a new backend event for file moved

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by AlexAndBear** [comment]
Unfortantly the item-moved SSE Event isn't firing but the item-renamed event, reopening
