### ISSUE TITLE
Changelog rendering for unreleased - summary seems to be broken

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#8887]
While working on the release notes for 5.0.2, checking the lastest changelog locally in my browser, I saw that rendering of the summary section of unreleased is broken, see image.

`Summary * Bugfix` should be:
```
Summary
* Bugfix ...
```
And each `* Bugfix` should be on its own line.

![image](https://github.com/owncloud/ocis/assets/3321281/97646457-1f13-403b-b3f9-4d94f39d6b5c)

@micbar

**Comment by micbar** [comment]
@JammingBen @kulmann This is the web changelog details. Can we make that render better?
