### ISSUE TITLE
[QA][Sharing NG] ApiTest: Extend update share permission test coverage 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#8888]
Some test cases have been covered on this PR https://github.com/owncloud/ocis/pull/8329. 
Extend test coverage for update share permission
- [x] update share permissionRole of project space https://github.com/owncloud/ocis/pull/8913
- [x] update share permissionRole of project space items https://github.com/owncloud/ocis/pull/8913
- [x] update `@UI.hidden` ([Feat. PR](https://github.com/owncloud/ocis/pull/8750))
    - [x] resource shared from personal space https://github.com/owncloud/ocis/pull/8999
    - [x] resource shared from project space https://github.com/owncloud/ocis/pull/8999

**Comment by SagarGi** [comment]
All the test coverage for extending update share permission has been merged. So this issue can be closed.
