### ISSUE TITLE
Upload of last chunk of Tus-Resumable returns 502 error status

### ISSUE THREAD

**Issue by dkocher** [owncloud/ocis#8893]
For larger uploads the transfer of the last chunk (with an offset of `14608089071` in the sample below) causes the server to respond with `502 Bad Gateway`. I suspect the underlying cause may be a timeout assembling the parts.

```
PATCH /data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNzEzNTI4NTcwLCJpYXQiOjE3MTM0NDIxNzAsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE1OC9kYXRhL3R1cy84ODMxYWJmYy1jYWZjLTQ4ZDAtOGRjZS05NDI3YTdmYWZmMzAifQ.X2p1UodnjOy7nrt9eN3UTGFkfh-f0aVb-ULX7tLpYTg HTTP/1.1
Tus-Resumable: 1.0.0
Upload-Checksum: MD5 1312a31eebd3242a005a4f152af41867
Upload-Offset: 14608089071
Content-Type: application/offset+octet-stream
Content-Length: 9582745
Host: ocis.ocis-keycloak.latest.owncloud.works
Connection: Keep-Alive
User-Agent: Cyberduck/8.8.3.41359 (Mac OS X/14.4.1) (aarch64)
Accept-Encoding: gzip,deflate
Authorization: Bearer 
HTTP/1.1 502 Bad Gateway
Date: Thu, 18 Apr 2024 12:32:28 GMT
Content-Length: 11
Content-Type: text/plain; charset=utf-8
Connection: close
```

The upload is not expected to fail.

**Comment by micbar** [comment]
Is this reproducable?

our latest instance is updated multiple times during the day. Maybe you got unlucky.

**Comment by dkocher** [comment]
> Is this reproducable?
> 
> our latest instance is updated multiple times during the day. Maybe you got unlucky.

I have seen it several times. Currently unable to reproduce as upload of `14G` fails with `507 Insufficient Storage.` Not able to reproduce with smaller files.
