### ISSUE TITLE
[QA] Public links made by a share receiver are not visible to the share owner

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#892]
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost

At the WEB UI:
* login in as einstein, create a folder share it with richard.
* login as richard, accept the folder, reshare it with moss and create a public link
![image](https://user-images.githubusercontent.com/1108546/99542219-16e5ab80-29b2-11eb-8f1f-4c64efa56e15.png)
![image](https://user-images.githubusercontent.com/1108546/99542410-53b1a280-29b2-11eb-8853-3119bc68f249.png)
* log in as einstein, check the sharing dialog
![image](https://user-images.githubusercontent.com/1108546/99542484-6f1cad80-29b2-11eb-865f-443cfbb396e5.png)
![image](https://user-images.githubusercontent.com/1108546/99542540-7e9bf680-29b2-11eb-86e8-d024b01f0ce0.png)

-> the extra share to moss via richard is there. GOOD.
-> the public link made by richard is not there. BAD.

Expected behaviour: the share owner is in control. He can see (and change) all sharing done by share receivers.

**Comment by ScharfViktor** [comment]
re-sharing is off. Need a re-test when we turn it on

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
