### ISSUE TITLE
[QA] Re-Sharer can increase permissions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#893]
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost

Via WEB UI:
* login as einstein, share a folder with richard as viewer only
* log in as richard, accept the folder, re-share to moss as editor
* login as moss, accept the folder, enter the folder, upload a file into it. Works. BAD.
* check the situation as einstein:
![image](https://user-images.githubusercontent.com/1108546/99544048-26fe8a80-29b4-11eb-848c-34c7268dba4a.png)

Although richard is clearly only Viewer, and moss received the share through richard, moss is Editor.
(At least einstein can clearly see what happend). Okayish.

Expected behaviour: share receiver can only reshare with same or subset of his own permissions.

**Comment by jnweiger** [comment]
A public link created by richard with Editor role behaves differently:
Richard sees, that  the link has Editor permissions, but 
users of the link cannot upload *until* einstein gives richard editor permissons.

**Comment by jnweiger** [comment]
According to @pmaier1 re-sharing should not be possible at all.

**Comment by micbar** [comment]
@butonic Can you please confirm, that this was expected?

**Comment by davitol** [comment]
Kind of dupe of https://github.com/owncloud/ocis/issues/552 ?

**Comment by dpakach** [comment]
Also similar issue https://github.com/owncloud/product/issues/270

**Comment by jnweiger** [comment]
Retested with ocis-1.0.0-rc8 via ocis/deployments/examples/ocis_traefik/

No more resharing conspiracy possible:
share receiver gets an GRPC error when trying to re-share a readonly share.

That is an acceptable workaround, but not nice.

**Comment by pmaier1** [comment]
> Retested with ocis-1.0.0-rc8 via ocis/deployments/examples/ocis_traefik/

Try a reload after encountering the error. Unfortunately the share is created nevertheless.

**Comment by refs** [comment]
@pmaier1 @micbar just want to bring this to the picture again. As it has `p2-high` is this something we should re-test and come to a conclusion?

**Comment by micbar** [comment]
We should fix it during our hardening of the share features.

**Comment by ScharfViktor** [comment]
re-sharing is щаа. Need a re-test when we turn it on

**Comment by micbar** [comment]
Resharing is disabled.
