### ISSUE TITLE
Issues with spaces and deleted users and/or groups

### ISSUE THREAD

**Issue by someone-somenet-org** [owncloud/ocis#8948]
## Describe the bug
Deleting users and groups can lead to spaces with no more managers and/or the spaces can become fully inaccessible.

There doesn't seem to be a way to add managers to spaces as system admin or spaces admin.

Also deleted users and groups are still considered existent, somehow, but cant be deleted from the space managers' memberships view.

## Steps to reproduce
1. create group or user (doesn't matter, both lead to the same set of issues).
2. create space.
3. add group or user (as manager) to said space.
4. delete group or user.

## Expected behavior
+ Refuse to delete user and/or group if they are still mapped to some space.
+ Allow system/space admins to edit every space's memberships.
+ Allow removing or automatically remove deleted users and/or groups from space memberships.

## Actual behavior
![image](https://github.com/owncloud/ocis/assets/5354356/4c727833-a268-473e-8dff-9fd23ee81beb)

Not only did I end up with an inaccessible space as I deleted all members, the admin page still displays 3 members (2 deleted users + 1 deleted group) which no longer exist, there seems to be no way to fix this.

![image](https://github.com/owncloud/ocis/assets/5354356/3486e38e-ebd1-4655-b5b8-50ba32d41884)
Also if im still a spaces' manager, I cant remove deleted users/groups from space memberships, since they dont show up in the membership view...

![image](https://github.com/owncloud/ocis/assets/5354356/f196bfe6-b866-4f88-9770-bb518cd54d79)
... yet they somehow show up in the administrative space membership view...

## Setup
Localhost test setup.

``OCIS_INSECURE=true PROXY_HTTP_ADDR=0.0.0.0:9200 OCIS_URL=https://localhost:9200 ./ocis server``

**Comment by kobergj** [comment]
There is already a proposed fix: https://github.com/owncloud/ocis/issues/5967

**Comment by micbar** [comment]
Closing here, duplicate has already been linked above.
