### ISSUE TITLE
New File in Sub Folder of Public Share cannot been created

### ISSUE THREAD

**Issue by dj4oC** [owncloud/ocis#8957]
Testing:
https://github.com/owncloud/ocis/issues/8691

1. Receive a Public Link of a folder
2. Create a (sub-)folder
3. Create a office file in that sub folder

Result: Failed to create file
Expected: File can been created

Workaround: 
1. Create a file on the received link "root" folder level.
2. move the file into the created (sub-)folder 

@micbar 
\cc @wkloucek @d7oc @dragotin

**Comment by micbar** [comment]
Please provide more info about used ocis version and setup.

**Comment by micbar** [comment]
Severity is not possible because no blue ticket

**Comment by phil-davis** [comment]
@PrajwolAmatya @Salipa-Gurung 
Please see if we have API test scenarios for this sort of thing - creating a sub-folder and uploading a file into it, for a read-write public link.

**Comment by micbar** [comment]
Note: create office file is not WebDAV, it it the app/new endpoint.

**Comment by rhafer** [comment]
I am able to reproduce. Seems to be yet another issue with the publicshare token scope verification :sob:
