### ISSUE TITLE
Collabora in docker compose: no disk space ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/ocis#8978]
Any ideas aka hints to fix this?

Mainly doc relevant I guess .... 

![image](https://github.com/owncloud/ocis/assets/1005065/a34efecc-d6f9-4aa7-b096-1b9d43476eb1)

**Comment by DeepDiver1975** [comment]
@mmattel FYI

**Comment by micbar** [comment]
What is that about? I have seen some times, that collabora needs disk space on my device, and i needed to free up some more.

Solution: Provide more diskspace.

**Comment by DeepDiver1975** [comment]
Happens to me every now and then ... no idea why. Enough disk space should be available ..... well - how much is needed? ;-)

**Comment by micbar** [comment]
Could not observer this more often or in our public deployments.
