### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#9]
avatars should be available at an IdP, but it will require additional cors setup. also owncloud already has an avatars andpoint that we need to implement it can look up the avatar url in the user metadata and either stream the content or eg fetch it from ldap. We might have to cache them in our service.

```
HTTP/1.1 200 OK
Content-Type: application/json

{
 "sub"         : "248289761001",
 "name"        : "Jane Doe"
 "given_name"  : "Jane",
 "family_name" : "Doe",
 "email"       : "janedoe@example.com",
 "picture"     : "http://example.com/janedoe/me.jpg"
}
```

The ocs service can fetch that `picture` url, cache it an serve it when a requests avatars, eg. when searching recipients.

**Comment by refs** [comment]
bump. Should we schedule and categorize this one?

**Comment by micbar** [comment]
Will be handled on the roadmap as feature development. This ticket is stale
