### ISSUE TITLE
cannot use phoenix with `bin/ocis server`

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#90]
after #88 got merged I cannot use phoenix when starting the complete server `bin/ocis server`
accessing http://localhost:9100 gives me an empty page and this in the console log:
![image](https://user-images.githubusercontent.com/2425577/72581748-7beef180-3908-11ea-8c20-3d882558f2f3.png)

http://localhost:9100/#/login works but hangs on the phoenix Redirect page with this error
![image](https://user-images.githubusercontent.com/2425577/72581795-aa6ccc80-3908-11ea-95d2-f1841f27c8cb.png)

@butonic @refs do I miss setting some settings? `--web-config-apps` seems not to work

**Comment by refs** [comment]
@individual-it the PR was depending on ocis-phoenix to be updated, dependencies should have been updated, but weren't. Fix is coming :)!
