### ISSUE TITLE
[QA] unsolicited sharing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#900]
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost
From the WEB UI:

* login as einstein
* login as richard
* "perform several other tests"
* richard creates a folder 'sub' and enters that folder.
* richard uploads several files and is surprised that these files are shared with einstein
* einstein double checks, and no, he does not see them.

![image](https://user-images.githubusercontent.com/1108546/99703147-0d823f00-2a97-11eb-97b7-af90266fd2d7.png)

Note that this happens outside of the Shares folder.
Note how richard has advanced permissions on the just uploaded files.

Sorry, no idea how to get into this situation. Maybe the logs have a hint:

**Comment by jnweiger** [comment]
[ocis.log.zip](https://github.com/owncloud/ocis/files/5568747/ocis.log.zip)

**Comment by micbar** [comment]
https://github.com/cs3org/reva/pull/1302

**Comment by micbar** [comment]
Please re-open if not fixed.
