### ISSUE TITLE
[Sharing NG] disabling share sync for non-existing resource gives 400

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#9001]
## Describe the bug
Disabling the share sync for non-existing resources gives a ~422~400 status code.

## Steps to reproduce
1. Send disable share sync request for a non-existent resource

```sh
curl -X DELETE 'https://host.docker.internal:9200/graph/v1beta1/drives/{drive-id}/items/{item-id}' -ueinstein:relativity
```

## Expected behavior
HTTP status code must be 404 (https://github.com/owncloud/ocis/pull/8992#discussion_r1582814331)

## Actual behavior
HTTP status code is ~422~400

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

```console
OCIS= `Infinite Scale 5.1.0-prealpha+49395e0a2 Community`
```

**Comment by grgprarup** [comment]
After this PR https://github.com/owncloud/ocis/pull/8939/ got merged, the actual status code was changed to `400` from `422`.

**Comment by grgprarup** [comment]
I think this PR https://github.com/owncloud/ocis/pull/9197 fixed the issue.

@2403905

**Comment by saw-jan** [comment]
Tests coverage has been added in https://github.com/owncloud/ocis/pull/8992
Tests are ex[ecting 404 which is correct.

So closing this issue.

CC @2403905
