### ISSUE TITLE
Assimilate `clean` command into `sessions`

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#9003]
`ocis storage-users uploads clean` cleans up unfinished uploads when executed. 

`ocis storage-users uploads sessions` lists unfinished uploads. It takes filters to only list specific uploads (e.g. processing=true). It already has a `--restart` flag that restarts listed uploads. If we deprecate the `clean` command and add a `--clean` flag to the `sessions` command instead, we will use the same logic on both commands.

Acceptance Criteria:
- deprecate `ocis storage-users uploads clean`
- add a `--clean` flag and logic to `sessions` command
- make sure virus infected files can be filtered in some way

**Comment by micbar** [comment]
@d7oc @kobergj Should we backport this?

When it fits into a patch release, i think it would be worth a backport.

**Comment by kobergj** [comment]
If we want it: Full feature would need another reva release.

**Comment by d7oc** [comment]
I would really appreciate a backport.

**Comment by tbsbdr** [comment]
@d7oc is the current solution which is currently rolled out "good enough"? (we would prefer not to backport with efforts in mind)

**Comment by d7oc** [comment]
No backport means we would get it when according to the current planning?

**Comment by kobergj** [comment]
Still not clear if this needs to be backported. If not backported this feature will only come with ocis 6.x

@tbsbdr @d7oc please decide so I can either close this ticket or proceed with the backport

**Comment by kobergj** [comment]
backport merged
