### ISSUE TITLE
[ocis][technical document] Add documentation about backup options - 3PD

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#9005]
# Description

## User Stories

* > As an Admin I want to know what I need to include in my backups so that I can tailor a backup concept for my ocis installation.

## Value
- Documentation

## Acceptance Criteria
- Add documentation about:
  - config options that need to be kept forever stable (eg. `storage-user-id-thingy` or `JWT-Token` ...)
  - stores that can and can not be backed up (userlog, clientlog etc.)
  - data in `var/lib/ocis/*`  eg. "please consider to backup the search index"
  - BLOBs: if you use an external blob store, this needs to be backed up externally  

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by mmattel** [comment]
https://github.com/owncloud/ocis/issues/5351

**Comment by wkloucek** [comment]
@kobergj is there already a PR that can be linked here?  

CC @RaniaMidaoui

**Comment by kobergj** [comment]
Yes. Only document is ready. Only waits for final touches: https://github.com/owncloud/ocis/pull/9227

Will be merged today.
