### ISSUE TITLE
How can I install and manage apps?

### ISSUE THREAD

**Issue by serhattsnmz** [owncloud/ocis#9037]
I have a module/app I developed for ownCloud Server. I want to switch to OCIS and use this app. I looked through the OCIS documentation but I didn't see any resources about installing and using the apps. 

My questions are

1. Can I use this app I developed for OCS also for OCIS?
2. Is there any documentation about this that I have overlooked? 
3. Even if I can't use my existing app, is there any documentation on how to create a new app? 

I would be grateful if you could help me with this. 
Thanks.

**Comment by micbar** [comment]
Hi @serhattsnmz 

Thank you for your questions.

>I have a module/app I developed for ownCloud Server. I want to switch to OCIS and use this app. I looked through the OCIS documentation but I didn't see any resources about installing and using the apps.

I assume with ownCloud Server you mean ownCloud 10 PHP based server. Let me explain the major differences.

- Infinite Scale uses microservices while ownCloud 10 is a monolith with a plugin concept.
- Infinite Scale uses compiled go code while ownCloud 10 uses a scripting language which can be extended during runtime.

1. That means, you cannot use the php app in infinite scale.

2. To extend Infinite Scale, you can check out how we are splitting functionality into [microservices](https://owncloud.dev/services/). 

4. You can replace a microservice or add a new one to add backend functionality.
We created an[ hello world example ](https://owncloud.dev/extensions/ocis_hello/). The documentation is not yet very detailed. There is already a small ecosystem of web apps, which are adding features to our frontend. https://owncloud.dev/clients/web/extension-system/

**Comment by serhattsnmz** [comment]
Thanks for the answer. It helps.
