### ISSUE TITLE
Reseting password via cli doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9047]
https://doc.owncloud.com/ocis/5.0/deployment/general/general-info.html#password-reset-for-the-admin-user

`ocis version`: `5.0.2` and `master`

steps: 
- run ocis binary 
- go to the terminal and reset password `ocis/bin/ocis idm resetpassword`

Expected: password is changed
Actual: error: 

```
vscharf:ocis scharfviktor$ ocis/bin/ocis idm resetpassword
Resetting password for user 'uid=admin,ou=users,o=libregraph-idm'.
Enter new password: 
Re-enter new password: 
{"level":"error","service":"idm","db":"/Users/scharfviktor/.ocis/idm/ocis.boltdb","error":"timeout","time":"2024-05-02T13:04:07+02:00","message":"Error opening database"}
Failed to open database: 'timeout'. Please stop any running ocis/idm instance, as this tool requires exclusive access to the database.
timeout
```

- reseting password using web/graph api `https://localhost:9200/graph/v1.0/me/changePassword` works fine.
- admin can see password in the `config/ocis.yaml` but after reseting password via web `ocis.yaml` the password is not overwritten.  that means if admin forgot password second time -> he will not be able to regain access

CC @mmattel @mfeilner

**Comment by mmattel** [comment]
Note that we must add a reset pwd test case to our test suite to catch such issues.

**Comment by micbar** [comment]
> Note that we must add a reset pwd test case to our test suite to catch such issues.

We are currently not testing cli commands. The end user facing feature uses the graph api

**Comment by mmattel** [comment]
> We are currently not testing cli commands. The end user facing feature uses the graph api

Maybe not atm, but we should. As @ScharfViktor stated, we now have the situation that an admin is locked out of his instance if he had forgotten his pwd and he cant reset it - since v5! Such major issues must not happen.

**Comment by micbar** [comment]
@ScharfViktor 

You should stop ocis and try again.

**Comment by ScharfViktor** [comment]
> You should stop ocis and try again.

oops, right! 

might we write it to the docs? or it's obvious and I didn't know it?

**Comment by ScharfViktor** [comment]
@micbar should we rewrite `ocis.yaml` after password change?

**Comment by mmattel** [comment]
> oops, right!

Ok for the binary deployment.
How are we dealing with ocis in the container, doesn't it try to restart automatically when ocis stopped? Which would mean we never can reset the pwd? I may be wrong...

**Comment by micbar** [comment]
> 👍 Suggesting we should make the reset pwd command not blocking the db access which would solve the issue on both deployment versions. Just my 2c.

Needs thinking. IMHO p4. We have a solution.

**Comment by mmattel** [comment]
> We have a solution.

Sorry to instist, mind to explain me how we do it with our containers? Happy to add that procedure to the docs --> needed for all of our install guides.

**Comment by ScharfViktor** [comment]
1. get containerId: `docker ps`
2. run the command: `docker exec -it containerId ocis idm resetpassword`

<img width="1172" alt="Screenshot 2024-05-02 at 20 49 31" src="https://github.com/owncloud/ocis/assets/84779829/9f4cca90-e5bd-481d-a8a3-d44409967851">

**Comment by micbar** [comment]
# Guide for a normal docker compose

## ocis traefik example

```sh
docker compose stop ocis
 ✔ Container ocis_traefik-ocis-1  Stopped
```

```sh
docker run --rm -ti \
-v ocis_traefik_ocis-config:/etc/ocis \
-v ocis_traefik_ocis-data:/var/lib/ocis \
owncloud/ocis:latest \
idm resetpassword

Resetting password for user 'uid=admin,ou=users,o=libregraph-idm'.
Enter new password: 
Re-enter new password: 
Password for user 'uid=admin,ou=users,o=libregraph-idm' updated.
```

**Comment by mmattel** [comment]
Thanks a lot, I will incoroprate the info asap to the admin docs!

**Comment by micbar** [comment]
> Thanks a lot, I will incoroprate the info asap to the admin docs! When done, I will close that issue.

I see that in the docs you are not working with the `-v` volumes syntax but with `-m`(mounts). That should also work in a similar way, as long as you have the correct volumes. `idm resetpassword` needs both: the config volume and the data volume.

**Comment by mmattel** [comment]
> I see that in the docs you are not working with the -v volumes syntax but with -m(mounts)

This is a legacy I will correct with the upcoming reset pwd docs change - thanks for the tip.
