### ISSUE TITLE
[QA] xml files have no icon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#905]
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost
From the WEB UI:
* upload an xml file and a few other items
* the xml file misses its icon. BAD.
![image](https://user-images.githubusercontent.com/1108546/99740249-e5163700-2ace-11eb-9618-88fb84ad8a62.png)

Expected behaviour: all file types have some sort of icon or placeholder. The columns should not shift.

**Comment by kulmann** [comment]
Thank you, will be fixed with https://github.com/owncloud/phoenix/pull/4357

**Comment by kulmann** [comment]
We will have to make a phoenix release though, to get it into ocis. So merging the linked PR is not sufficient for closing this issue.
