### ISSUE TITLE
[ocis] Unblock Thomas - 1 PD Time Box 

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9066]
# Description

## User Stories

* > As a  sysadmin, I want to migrate all users to ocis to use the new Software generation

## Value

- Increase Adoption

## Acceptance Criteria

- [ ] Migration tool (rclone) can upload files to all users to migrate their data via command line
- [ ] Impersonation feature is default off
- [ ] Impersonation is logged in the audit log

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

## Process

- Cli Tool
- Executed by the sysadmin to migrate all users & their data to the target system
  - Create all users on the target system
  - Each user gets an "App Token" on both sides (via special API where admin can create tokens for all users)
  - Invoke rclone with the user access tokens (can recover etc)
  - Shares are recreated

**Comment by micbar** [comment]
Middleware PR: https://github.com/owncloud/ocis/pull/8522

**Comment by rhafer** [comment]
New reva `appauth` based middleware and service: https://github.com/owncloud/ocis/pull/9079

**Comment by DeepDiver1975** [comment]
I am basically unblocked now .... not really happy .... but unblocked ...

THX @rhafer for your patience :beers:
