### ISSUE TITLE
[ocis][Secure View] Open files in Collabora with watermark

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9067]
# Description

Open File in Collabora with watermark and exports (print, download) disabled
## User Stories

* > As a user, i want to share files which cannot be downloaded to keep confidential content secure

## Value

Make ocis usable for higly confident data

## Acceptance Criteria

- [ ] Collabora can open the possible file types in watermark mode 
- [ ] with download disabled
- [ ] with printing disabled

## Research results

From #8855 

We can modify the response of the "CheckFileInfo" WOPI call to control the viewing mode of Collabora.

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by 2403905** [comment]
@micbar  Should we add the new env variable for the watermark or just use some default text?

**Comment by micbar** [comment]
Username and email if you ask me, no config var.

@tbsbdr

**Comment by tbsbdr** [comment]
👍 yes, Username and email, no config var

**Comment by ScharfViktor** [comment]
> 👍 yes, Username and email, no config var

should we consider here `OCIS_SHOW_USER_EMAIL_IN_RESULTS=false/true`? 
I would suggest -> no email if `OCIS_SHOW_USER_EMAIL_IN_RESULTS=false`

**Comment by micbar** [comment]
IMHO different use case.

In this case the email is only shown to the user which belongs to it. It should prevent making a screenshot because that would be connected to the user and email.

**Comment by 2403905** [comment]
> IMHO different use case.
> 
> In this case the email is only shown to the user which belongs to it. It should prevent making a screenshot because that would be connected to the user and email.

Do you mean if `Albert Einstein` opened a doc it should be `Albert Einstein einstein@example.org` watermark ?

**Comment by micbar** [comment]
Yes. The viewer should be in the watermark.

**Comment by 2403905** [comment]
Already merged
