### ISSUE TITLE
[ocis][Secure View] Open files in Collabora which have no download permission

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9068]
# Description

Open files in Collabora which have no download permission

## User Stories

* > As a user, i want to share highly confidential data which can only be viewed on the server to keep the information undisclosed.

## Value

Make ocis usable for highly confidential data

## Acceptance Criteria

- [ ] Collabora can download a file via WOPI which has no `InitiateFileDownload` permission granted to the requesting user.

## Research outcome

- The gateway should provide a second reva token to a trusted App provider that can only download the single file.

See #8855 

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by 2403905** [comment]
@micbar Are we going to add a `Secure View` mode for the public links?

**Comment by butonic** [comment]
prerequisite: reva mint view only token pr: https://github.com/cs3org/reva/pull/4686

**Comment by butonic** [comment]
- [ ] needs reva bump to 8fb71adbe50042ed2e252518ff7c15381ee37e6e

**Comment by butonic** [comment]
@ScharfViktor How do we best test this? AFAICT it needs an end 2 end test

**Comment by ScharfViktor** [comment]
> @ScharfViktor How do we best test this? AFAICT it needs an end 2 end test

I have look. thanks that moved it to `Need Tests `

**Comment by ScharfViktor** [comment]
close as completed
