### ISSUE TITLE
[ocis][Secure view] Indicator for Secure view in the WebDAV response

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9077]
# Description

## User Stories

* > As client, i want to know when a resource is only secure viewable to not display its file actions

## Acceptance Criteria

- [ ] Secure View context is indicated on the WebDAV response

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by butonic** [comment]
IIRC we wanted to just add a new char the propfind permissions element. I implemented it with `I` (as in Initiate Download). The permissions are all positive, but this would make new clients incompatible with old owncloud or ocis versions.

So I decided to add an `X` to indicate that a resource can be securely viewed in https://github.com/cs3org/reva/pull/4694
