### ISSUE TITLE
Not possible to up ocis with wopi

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9085]
Steps: 

- go to the: deployments/examples/ocis_wopi/docker-compose.yml
- run ocis with wopi: `docker-compose up -d`

Actual: `2024-05-06 15:09:19 read etc/ocis/web.yaml: is a directory`
we haven't `web.yaml` anymore so ocis doesn't start. see here https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml#L97

if we use web-daily.yaml or web-latest.yaml (I'm not sure that we should use this files. if not-> what file should I use?)
https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/config/ocis/web-daily.yaml

ocis starts but we cannot upload (similar issue https://ocis.ocis-wopi.latest.owncloud.works/)
![Screenshot 2024-05-06 at 16 53 32](https://github.com/owncloud/ocis/assets/84779829/cba154ac-19fd-4a4f-94c2-f84c10b6d47e)

cc @dschmidt @fschade

**Comment by micbar** [comment]
@ScharfViktor Understood

The example needed this workaround to enable the uppy companion deployment.

Now we have a new option how to solve that differently. I spoke with @fschade , we are working on a fix.
