### ISSUE TITLE
[QA] Already shared users should not be longer listed in Add People

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#911]
Setup via docker-compose-eos-test.yml from branch fix-yml-for-rc5 on localhost

## Steps to reproduce

1. Share a file with Alice
2. Try to share same file with Alice again

## Expected behavior

Alice should not be listed

## Current behavior

Alice is listed and when you try to share with her an error is shown

![Screenshot 2020-11-20 at 10 31 33](https://user-images.githubusercontent.com/10596560/99784096-95119180-2b1b-11eb-96c5-81b497fcf8e2.png)

**Comment by refs** [comment]
Closing, as it is not happening on master anymore.
