### ISSUE TITLE
[QA] More options than granted are listed in Public links

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#913]
Setup via docker-compose-eos-test.yml from branch fix-yml-for-rc5 on localhost

## Steps to reproduce

1. Share a file using Public Link option setting Role as Visor (Can see and download content)
2. Copy/paste the link and see the options shown in the 3 dots menu

## Expected behavior

user should be only able to view/download the file

## Current behavior

All options are listed even when an error is shown when trying to do them (e.g. not possible to delete, rename etc . A warning appears)

**Comment by micbar** [comment]
Duplicate of #1029
