### ISSUE TITLE
Access token renewal fails in web ui

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#9163]
## Describe the bug
Access token renewal in the web ui fails.

## Steps to reproduce
1. Log in to https://ocis.ocis-wopi.latest.owncloud.works/ with `admin:admin`
2. Wait for the access token expiry

## Expected behavior
Access token renewal happens.

## Actual behavior
Access token renewal fails with error message `Refused to frame 'https://ocis.ocis-wopi.latest.owncloud.works/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

## Additional context
Happens in current `master`. Might be fallout from https://github.com/owncloud/ocis/pull/8777

`Preserve logs` must be active in the browser dev tools to observe the error message.

**Comment by micbar** [comment]
@DeepDiver1975 Can you please take a look? That seems related to your changes.

**Comment by DeepDiver1975** [comment]
![image](https://github.com/owncloud/ocis/assets/1005065/0ad7d694-7a4a-43c5-a41f-e4244a81f15c)

**Comment by DeepDiver1975** [comment]
> Access token renewal fails with error message `Refused to frame 'https://ocis.ocis-wopi.latest.owncloud.works/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

Why (aka who) is trying to load ocis in an iframe? oidc client?

**Comment by kulmann** [comment]
> > Access token renewal fails with error message `Refused to frame 'https://ocis.ocis-wopi.latest.owncloud.works/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`
> 
> Why (aka who) is trying to load ocis in an iframe? oidc client?

Yes, `oidc-client-ts` does this as part of the silent token renewal.
