### ISSUE TITLE
[QA] folder upload ignores empty folders

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#917]
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost
From the WEB UI with firefox 82.0.3 :
* login user einstein
* upload folder 100dirs as created below:

```
mkdir 100dirs
for i in $(seq 100); do mkdir 100dirs/subdir_$i; done
for i in $(seq  10); do touch 100dirs/subdir_$i/file_$1; done
```
* The 10 folders that have a file are uploaded correctly.
* the 90 empty folders are ignored. BAD

![image](https://user-images.githubusercontent.com/1108546/99798704-c2693a00-2b31-11eb-87e7-8b9d33073265.png)

Expected behavour: A tree is a tree. upload as it is. Do not try to be clever.

Use case: "Let me prepare the folder structure that I have in mind now, we will fill in the files later!"

**Comment by jnweiger** [comment]
```
for i in $(seq 100); do mkdir empty_dirs_only/subdir_$i; done
```

Folder upload on 'empty_dirs_only' does nothing. No error, no upload.

**Comment by jnweiger** [comment]
google-chrome says before starting:
![image](https://user-images.githubusercontent.com/1108546/99803082-17f51500-2b39-11eb-9a24-76cf2583a4e6.png)

**Comment by jnweiger** [comment]
```
for i in $(seq 100); do mkdir empty_dirs_only/subdir_$i; done
```

Folder upload on 'empty_dirs_only' does nothing with firefox. No error, no upload.

**Comment by davitol** [comment]
works for me using  Chrome for Mac Version 87.0.4280.67 (Official Build) (x86_64)
 

![Screenshot 2020-11-20 at 14 16 48](https://user-images.githubusercontent.com/10596560/99804286-0e6cac80-2b3b-11eb-9641-315b4a0da2a2.png)

**Comment by kobergj** [comment]
*Probably* fixed with newest ocis version. closing.
