### ISSUE TITLE
[Sharing NG] status code list for enable and disable share sync

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#9176]
`Enable Share Sync`

```
curl -X POST 'https://host.docker.internal:9200/graph/v1beta1/drives/{share-Space-Id}/root/children'  
-d '{
    "remoteItem": {
        "id":"'remote-item-id"
    }
}'
```

| Scenerio  | Status Code    | message  | 
| :---: | :---: |:---: |
| enable share sync of a non-existent resource   | 400    | mounting share failed |
| multiple share sync of a  resource   | 400    | mounting share failed |
| enable share sync with empty item id   | 400    | invalid id |
| enable share sync of a resource nout shared with sharee  | 400    | mounting share failed |
| try to enable sync of shared resource when sharer is deleted {if this request is done second time it result is 400 status code but gives `mounting share failed` message ) | 400 | converting to drive items failed |
| try to enable sync of group shared resource when sharer is deleted | 400 | mounting share failed |  
| mount share multiple time | 400 | mounting share failed | 

`Disable Share Sync`
```
curl -X DELETE 'https://host.docker.internal:9200/graph/v1beta1/drives/{drive-id}/items/{item-id}' -u username:password
```
| Scenerio  | Status Code    | message  | 
| :---: | :---: |:---: |
| non existence resource | 400 | unmounting share failed |
| when sharer get deleted | 400 |  unmounting share failed |
} unmount multiple time | 400 | unmounting share failed | 
| invalid item id | 400 | invalid driveId or itemID | 
 
Should all these give same `400 status code`? 

Related PR : https://github.com/owncloud/ocis/pull/8939

**Comment by S-Panta** [comment]
@fschade @rhafer

**Comment by rhafer** [comment]
@2403905 I think this one is at least partially related to #8876

**Comment by S-Panta** [comment]
Related issue: https://github.com/owncloud/ocis/issues/9001 https://github.com/owncloud/ocis/issues/8876

**Comment by S-Panta** [comment]
Updated status code and messages
`enable share sync scenarios `
| Scenerio  | Status Code    | message  | 
| :---: | :---: |:---: |
| enable share sync of a non-existent resource   | 404    | no shares found |
| multiple share sync of a  resource   | 409    | shares already mounted |
| enable share sync with empty item id   | 400    | invalid id |
| enable share sync of a resource not shared with sharee  | 404    | no shares found |
| try to enable sync of shared resource when sharer is deleted  | 400 | converting to drive items failed |
| try to enable sync of group shared resource when sharer is deleted | 404 | no shares found" |  

`disable share sync scenarios`
| Scenerio  | Status Code    | message  | 
| :---: | :---: |:---: |
| when sharer get deleted | 404 |  error getting received share|
} unmount multiple time | 404 | shares already unmounted | 
| invalid item id | 400 | invalid driveId or itemID |

**Comment by S-Panta** [comment]
imo this issue can be closed as the status code given by graph API now make sense in these different scenarios.
@saw-jan  @grgprarup
