### ISSUE TITLE
Support basic auth in OCIS

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#918]
To allow old clients to fallback to BASIC auth, ocis proxy should check the Agent header and return different `WWW-Authenticate` headers.

**Comment by labkode** [comment]
![desktop-basic-auth](https://user-images.githubusercontent.com/5175912/99802242-a49ed380-2b37-11eb-8da4-c70f5ba94bae.png)

**Comment by refs** [comment]
can we close this since it's addressed on #1009 ? I would also update the title, "Support basic auth in OCIS" seems very broad.

**Comment by refs** [comment]
closing as it was already implemented on #1009

**Comment by ishank011** [comment]
Needs this to be merged https://github.com/owncloud/ocis/pull/1750/commits/a650ac748ebe35ddcfa0b8411a7cbfdf4bb6edb9#diff-922421e29a6c3ee7ed52a7304b092a945236a1ca8ff37a146fd17ec711af378e
