### ISSUE TITLE
[QA] Files version does not work

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#919]
Setup via docker-compose-eos-test.yml from branch fix-yml-for-rc5 on localhost

## Steps to reproduce

1. Upload a file
2. Upload the file again and resolve the conflict dialog creating a new version

## Expected behavior

A new version of the folder should be shown in the right sidebar in versions section

## Current behavior

File is listed twice in the Files view. No versions are shown in version section in the right sidebar

![Screenshot 2020-11-20 at 15 14 50](https://user-images.githubusercontent.com/10596560/99809883-3829d180-2b43-11eb-8946-1750bc6a5b50.png)

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
