### ISSUE TITLE
Autoprovisioning misses documentation about the envvars used

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9193]
Referencing: #8952 (Autoprovsioning fixes)

New envvars have been implemented but, though commented, no documentation in the proxy readme has been made. This must be added with a new PR.

@rhafer @micbar

**Comment by rhafer** [comment]
Adding this to the backlog so we can add it to a regular sprint.

**Comment by mmattel** [comment]
Closed via PR: #9458
