### ISSUE TITLE
SkeletonFolder functionality

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#92]
core has the option to set a `skeletonFolder`, this is heavily used in the API tests, so having it also in OCIS would make things easier

**Comment by butonic** [comment]
related: https://github.com/cs3org/reva/pull/476

**Comment by micbar** [comment]
Related to https://github.com/owncloud/enterprise/issues/3779

**Comment by phil-davis** [comment]
Note: we have reduced the use of the skeleton directory a lot in the test suite. Now there are not so many scenarios left that have to "fake" the skeleton at the start of a scenario.
