### ISSUE TITLE
Add ocis_wopi deployment backports from stable-5.0 into the next patch release 

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9223]
There are some smaller changes that have been created for `ocis_wopi` in master and backported to `stable-5.0`. Bigger changes are still in master only and will not get backported.

For the [easy entry docs](https://github.com/owncloud/docs-ocis/pull/837), we need the backports to be part of the next release like 5.0.5
Else, our examples lack important things we depend on.

Maybe to be added as task for the next sprint?

@micbar @ScharfViktor @tbsbdr

**Comment by ScharfViktor** [comment]
@kulmann do we want to have it in the new 5.0.5 patch release?

**Comment by kulmann** [comment]
> @kulmann do we want to have it in the new 5.0.5 patch release?

No, any next `5.0.x` is fine for what Martin proposes (that's also what I read from Martins comment). Just go ahead with `5.0.5` with what we have in `stable-5.0`.

**Comment by micbar** [comment]
git diff for the wopi shows only

```diff
diff --git a/deployments/examples/ocis_wopi/README.md b/deployments/examples/ocis_wopi/README.md
index adfbf2a754..9a346f6505 100644
--- a/deployments/examples/ocis_wopi/README.md
+++ b/deployments/examples/ocis_wopi/README.md
@@ -2,5 +2,9 @@
 document this deployment example in: docs/ocis/deployment/ocis_wopi.md
 ---
 
-Please refer to [our documentation](https://owncloud.dev/ocis/deployment/ocis_wopi/)
-for instructions on how to deploy this scenario.
+# Infinite Scale WOPI Deployment Example
+
+This deployment example is documented in the [developer documentation](https://owncloud.dev/ocis/deployment/ocis_wopi/).
+See the link for more details and instructions on how to deploy this scenario.
+
+Also see the [Admin Documentation](https://doc.owncloud.com/ocis/latest/index.html) for administrative and more configuration details.
diff --git a/deployments/examples/ocis_wopi/config/ocis/csp.yaml b/deployments/examples/ocis_wopi/config/ocis/csp.yaml

```

**Comment by micbar** [comment]
PR in https://github.com/owncloud/ocis/pull/9353
