### ISSUE TITLE
Thumbnailer frequently rejecting portrait mode images

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#9234]
## Describe the bug
With https://github.com/owncloud/ocis/pull/9069 scan limitations for image width and height were introduced to the thumbnail service. However, the width to height aspect ratio is favouring landscape mode images over portrait mode images. ;-)

## Steps to reproduce
1. Upload a portrait mode image from a low price segment DSLR
2. Try to see a thumbnail or open the image in the preview app

## Expected behavior
Our defaults work for thumbnail generation for images from for this kind of camera

## Actual behavior
Our defaults are too restrictive for portrait mode images
Image width and height should be the same value, so that thumbnail generation works for both landscape and portrait mode images.

**Comment by jnweiger** [comment]
See also: https://central.owncloud.org/t/cannot-view-vertical-photos-on-the-web-side/47758/2
