### ISSUE TITLE
Restrict users to only share with users in their groups and groups they are member of

### ISSUE THREAD

**Issue by cheegui** [owncloud/ocis#9235]
## Is your feature request related to a problem? 
Owncloud has these settings: "Restrict users to only share with users in their groups" and "Restrict users to only share with groups they are member of"   Can you implement the same for OCIS?

## Describe the solution you'd like
Have "Restrict users to only share with users in their groups" and "Restrict users to only share with groups they are member of" settings so that user cannot see everybody including admin accounts on the system (which is no good).

## Describe alternatives you've considered
None

## Additional context
NextCloud also has this "Restrict users to only share with users in their groups" setting.

Thank you very much

**Comment by cheegui** [comment]
This is a duplicate of https://github.com/owncloud/ocis/issues/9293
Thank you.

**Comment by micbar** [comment]
The linked issue is something different about roles.

**Comment by cheegui** [comment]
Oops, this is the correct linked issue:
https://github.com/owncloud/ocis/issues/8560
