### ISSUE TITLE
[to discuss] running sharing to root tests in CI

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#924]
currently we run also suites in CI that do sharing to root (`/`), those tests are all skipped on OCIS because shares in OCIS always are received in a subfolder e.g. `/Shares`
The suites with 0 tests still need to compile ocis etc. Should we delete those suites from CI?

advantage: less CI time (will make less of a difference when we manage to cache the artifacts)
disadvantage: more brain time is needed to remember the fact that those tests do not run in ocis. Just copy-paste the suites list from oC10 does not work anymore. e.g. between phoenix oC10 tests & ocis tests

**Comment by individual-it** [comment]
CC @phil-davis @micbar

**Comment by dpakach** [comment]
@individual-it, in ci we run tests by using `DIVIDE_INTO_NUM_PARTS` settings that break the entire suite into smaller parts each having approximately an equal number of scenarios. furthermore, we also cache the build products so we dont have to build ocis on each pipeline.
can we close this now?

**Comment by individual-it** [comment]
with the caching the issue is much smaller, lets close this
