### ISSUE TITLE
Thumbnailer allows generating thumbnails for images shared as secure view only

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#9249]
When an image is shared in view only mode it should not be possible to fetch a thumbnail for it. Or not without a watermark.

**Comment by tbsbdr** [comment]
secureview should not generate a thumbnail.

**Comment by AlexAndBear** [comment]
Not only images but as well txt files, which makes it even more critical

**Comment by dragonchaser** [comment]
@AlexAndBear with PR #9299 txt-files got accidentally fixed aswell :laughing:

**Comment by dragonchaser** [comment]
![image](https://github.com/owncloud/ocis/assets/1058116/c64b92a4-2e4f-4944-80f5-06825331893a)

**Comment by dragonchaser** [comment]
![image](https://github.com/owncloud/ocis/assets/1058116/83e1234b-7c82-4a71-ba64-59fc101191d7)

**Comment by mmattel** [comment]
@tbsbdr after a discussion with @dragonchaser I propose that we add a small info into the thumbnail readme that thumbnails will return a 403 (forbidden) for a thumbnail request that belongs to a secure view shared object when the share reciever accessses the data. we already have such info for 404 (unavailable) and too many requests (429). this readme change should directly go into the corresponding (and currently open) PR, see: #9299. pls advice.

**Comment by AlexAndBear** [comment]
> ![image](https://private-user-images.githubusercontent.com/1058116/336428572-83e1234b-7c82-4a71-ba64-59fc101191d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDM2NTYsIm5iZiI6MTcxNzUwMzM1NiwicGF0aCI6Ii8xMDU4MTE2LzMzNjQyODU3Mi04M2UxMjM0Yi03YzgyLTRhNzEtYmE2NC01OWZjMTAxMTkxZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTIxNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQxMTg4ODI5YzY5NTQ5OGNkMTFmOTdkZTM4YTFkMDczZmMxYzY2NjMzMTc0MGYwMTliNDVjN2FiMjljYzRkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O3-mr09D3eRZH-ocDxJt1lXEuml3uhdqfDssxaXNMZQ)

Nice, but with latest web master, we don't even request the thumbnails anymore when secure view is active, so this is more a security feature for attacks or somthing

**Comment by dragonchaser** [comment]
@AlexAndBear I was not aware of that, but that change would be needed anyway. Otherwise someone could craft a thumbnail link for a certain file and read the contents (as you said security...)

**Comment by AlexAndBear** [comment]
Yeah, just wanted to update all people here in the ticket, so no one is under the impression web is still requesting endpoints, that should not be requested ;)
