### ISSUE TITLE
[Proposal] Improve handling of new environment variables in releases

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#9254]
We have an annotation that describes the `introductionVersion`  of a variable.
At the moment we try to guess the next release number when we add variables to the codebase. 
To streamline the process and make it less error-prone I propose we use a placeholder in the future like `%%NEXT%%`. This would allow us to create a script in `docs/helpers` that is run during the release-process. This script automatically insert a release version resulting in no wrong `introductionVersions` in the documentation in the future.

/cc @mmattel @micbar @butonic

**Comment by micbar** [comment]
Good idea, Let us do that.

**Comment by micbar** [comment]
Created PR #9312
