### ISSUE TITLE
Implement an accounts repo that talks to the cs3 users service directly.

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#927]
- [ ] extend cs3 api with user and group write capabilities
- [ ] allows using the ldap backend
- [ ] implement reva users backend that uses a cs3 storage provider

**Comment by butonic** [comment]
started in branch https://github.com/owncloud/ocis/tree/accounts-cs3-users-repo

needs a custom indexer and some caching to not be a performance hit

related to moving ocs from reva to ocis

**Comment by labkode** [comment]
The driver should not be needed in the accounts service because we can bypass it to the Reva userprovider service by using custom config in the ocis proxy routing table.
