### ISSUE TITLE
Deleting or restoring a trash item does not clean up empty dirs

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#9271]
When deleting or restoring an entry from the trash directory of a space we do not clean up empty nodes. This clutters the trash bin directory and slows down the listing because it has to glob all empty dirs. Which is even slower on NFS.

Another possibility to speed up listing the trashbin is to not shard the nodes in the trashbin dir and then cache the directory listing until the mtime of the `./trash` directory changes. We could also do the caching with the sharded node layout by touching the trash directory, whenever a file is added or removed from the trash.

But removing empty dirs should be the first step:
- [x] clean up empty dirs when a node is removed from the trash https://github.com/cs3org/reva/pull/4700
- [ ] #9393

**Comment by butonic** [comment]
can be closed with the next reva bump

**Comment by d7oc** [comment]
I still vote for a CLI command. Not for myself, but I think our final approach is still to also address other users and as long as we don't want to document the workarounds presented here in our official documentation we need a CLI tool for them.

**Comment by butonic** [comment]
@tbsbdr not for me to decide

**Comment by tbsbdr** [comment]
👍 lets have a CLI

**Comment by micbar** [comment]
We will do the CLI in a follow up.

**Comment by micbar** [comment]
Closing here.
