### ISSUE TITLE
SecureView is not secure because of previews

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/ocis#9273]
## Describe the bug
It's still possible to request thumbnails/previews for resources that are shared via secure view. If we share a .txt file, a preview will be created, that can be downloaded and viewed without a watermark 

## Steps to reproduce
1.
2.
3.

## Actual behavior
A clear and concise description of what happened.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by rhafer** [comment]
duplicate: https://github.com/owncloud/ocis/issues/9249

**Comment by AlexAndBear** [comment]
closing in favor of https://github.com/owncloud/ocis/issues/9249
