### ISSUE TITLE
Metadata storage creates file revision for every upload

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#9282]
## Describe the bug

As part of addressing #8938 I experimented a bit  with the the sharecache implementation in reva `pkg/share/manager/jsoncs3/sharecache/sharecache.go` while doing that I noticed that with every update (i.e. upload) of the cache file a file revision is created in the storage.

For my experiments with a cache for roleassignments keyed by roleid that means I end up with 1000 file revisions of the cache files after creating 1000 users. This accumulates quite some wasted space (and probably quite some additional I/O).

We should think about allowing to disable versioning on the metadata storage.

**Comment by kobergj** [comment]
> We should think about allowing to disable versioning on the metadata storage.

Just to be clear since it is a P2:

Scope of this ticket is to deactivate versioning for the `storage-system` service?

@rhafer @micbar

**Comment by micbar** [comment]
Good addition: We also need a CLI command to purge old versions.

**Comment by micbar** [comment]
Needs backport to `stable-5.0`

**Comment by kobergj** [comment]
backport overview:
* [ ] reva pr: https://github.com/cs3org/reva/pull/4743
* [ ] ocis pr:
* [ ] backport finished

**Comment by micbar** [comment]
We need to talk about backporting please with @d7oc

**Comment by d7oc** [comment]
Also adding @wkloucek here. As I will not be available next week.

**Comment by kobergj** [comment]
It depends on the posix PR which also contains a huge refactor of the decomposedfs. I would not recommend backporting this. But if you insist we can backport both PRs.

I still think backporting the cli would be the more feasible (and safe) solution

**Comment by micbar** [comment]
Done in sprint 27.

Backporting of the CLI needs extra ticket.
