### ISSUE TITLE
Test backup consistency command in ci

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#9286]
We would like to test the new [ocis backup consistency command](https://github.com/owncloud/ocis/pull/9238) in the ci. Since the implementation relies heavily on decomposedfs interns it is likely that it will break if there are breaking changes to decomposedfs. 

The straight forward implementation of such a test proved difficult. We need the complete ocis data structure which is only available in `ocis server` ci step. However this step is detached, therefore there is no chance to run the command after the tests are finished. Additionally ocis tests clean users after each run, which will delete their data also.

The new idea is to use the ocis wrapper to test this feature. This requires several changes:
* add an endpoint to ocis wrapper to run a ocis command 
* add an endpoint to ocis wrapper to start/stop ocis (or do this as part of the above step)
* write a test that stops ocis, runs the `ocis backup consistency` command and restarts ocis after.
* this test should fail if there are inconsistencies
* this test should NOT run as the first test in the suite

We would wait for the opinion of @ScharfViktor on this before we start implementing.

cc @butonic @dragonchaser

**Comment by saw-jan** [comment]
Necessary implementation and setup done https://github.com/owncloud/ocis/pull/9546

**Comment by saw-jan** [comment]
We added a scenario to create some user data and do the backup consistency check.

```feature
Scenario: check backup consistency via CLI command
    Given these users have been created with default attributes and without skeleton files:
      | username |
      | Alice    |
      | Brian    |
      | Carol    |
    And user "Alice" has created folder "/uploadFolder"
    And user "Carol" has created folder "/uploadFolder"
    And user "Alice" has sent the following resource share invitation:
      | resource        | uploadFolder |
      | space           | Personal     |
      | sharee          | Brian        |
      | shareType       | user         |
      | permissionsRole | Editor       |
    And user "Carol" has deleted file "/uploadFolder"
    And the administrator has stopped the server
    When the administrator checks the backup consistency using the CLI
    Then the command should be successful
    And the command output should contain "💚 No inconsistency found. The backup in '%storage_path%' seems to be valid."
```

@kobergj if this is enough.
