### ISSUE TITLE
Display share indicator when listing files

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#929]
When a resource (file/folder) has been shared we should show the appropriate share indicator.

**Comment by pascalwengerter** [comment]
@C0rby could you update this issue / close it if it was finished off in the current sprint (sync bot suggests so)

**Comment by C0rby** [comment]
So there are multiple things to this.

- Propfinds include shareinformation for direct shares (users,groups)
  - The indicators for direct shares are displayed for the items in the root and in subfolders
- Propfinds to not include share information for public links
  - Share indicators for public links are not shown in the root but in subfolders
  This is because the webui does an extra request in subfolders to receive a list with shares

Including public link share information into the propfind response is a bit difficult since it would require to do a request against the share manager for every file in the propfind response. This would slow down the process significantly which is why we haven't implemented this yet.

If this has a high priority/is a strict requirement than we need to take another look and possibly refactor the sharing architecture.

**Comment by wkloucek** [comment]
This looks all solved to me. See also https://github.com/owncloud/ocis/issues/1038#issuecomment-990711232.

Please reopen and describe if there is still a TODO.
