### ISSUE TITLE
Please provide CRUDS for creating Ukrainian localization.

### ISSUE THREAD

**Issue by if0else9** [owncloud/ocis#9305]
Please provide CRUDS for creating Ukrainian localization.

**Comment by micbar** [comment]
Our translations are done in transifex. www.transifex.com

They are done by the community and individuals on "best effort".

Feel free to contribute.

## Ocis

https://app.transifex.com/owncloud-org/owncloud/ocis-notifications/
https://app.transifex.com/owncloud-org/owncloud/ocis-userlog/
https://app.transifex.com/owncloud-org/owncloud/ocis-graph/

## Web

https://app.transifex.com/owncloud-org/owncloud-web/content/

New contributions will be automatically bundled into a new release as soon as the percentage of translated content for a specific language exceeds 75%

**Comment by micbar** [comment]
- > nothing to do for DEV, closing.

**Comment by if0else9** [comment]
Please apply the Ukrainian language https://app.transifex.com/
Can't join :-(



------ Original Message ------
From "Michael Barz" ***@***.***>
To "owncloud/ocis" ***@***.***>
Cc "if0else9" ***@***.***>; "Author" ***@***.***>
Date 6/4/2024 11:14:02 AM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by if0else9** [comment]
Please add


------ Original Message ------
From "Michael Barz" ***@***.***>
To "owncloud/ocis" ***@***.***>
Cc "if0else9" ***@***.***>; "Author" ***@***.***>
Date 6/4/2024 11:14:41 AM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by DeepDiver1975** [comment]
Ukrainian language has been added

**Comment by if0else9** [comment]
OCIS UI successfully changes to Ukrainian.

But OO and Collabora - not.
Is it a bug?

вт, 4 черв. 2024 р. о 16:26 Thomas Müller ***@***.***> пише:

**Comment by DeepDiver1975** [comment]
> But OO and Collabora - not.

please post links to the projects on transifex. thx

**Comment by if0else9** [comment]
https://explore.transifex.com/owncloud-org/owncloud-web/

This project ?

вт, 4 черв. 2024 р. о 17:22 Thomas Müller ***@***.***> пише:

**Comment by DeepDiver1975** [comment]
please try again

**Comment by if0else9** [comment]
On it. thank you

вт, 4 черв. 2024 р. о 17:50 Thomas Müller ***@***.***> пише:

**Comment by if0else9** [comment]
Please help something wrong with the Ukrainian translation (Video attached)
https://app.transifex.com/owncloud-org/owncloud-web/dashboard/


compulsory Ukrainian language. We mourn for our employees who died in the
war. More than 30 employees lost their housing due to the Russian-Ukrainian
war.
(We will finish the translation this week and notify you about it from
***@***.***);
https://nir.gov.ua/



вт, 4 черв. 2024 р. о 11:14 Michael Barz ***@***.***> пише:

**Comment by if0else9** [comment]
Please help. None Editable rows (Ukrainian):
1
%{ errors } of %{ uploads } items failed
2
%{ filesInProgressCount } items uploading...
3
%{ roundedRemainingHours } hours left
4
%{ roundedRemainingMinutes } minutes left
5
%{ successfulUploads } items uploaded
166
%{ filesCount } files
167
%{ filesCount } files including %{ filesHiddenCount } hidden
168
%{ foldersCount } folders
169
%{ foldersCount } folders including %{ foldersHiddenCount } hidden
170
%{ itemCount } items selected
171
%{ itemsCount } items in total (%{ filesStr}, %{foldersStr}, %{spacesStr})
172
%{ itemsCount } items in total (%{ filesStr}, %{foldersStr})
173
%{ itemsCount } items with %{ itemSize } in total (%{ filesStr},
%{foldersStr}, %{spacesStr})
174
%{ itemsCount } items with %{ itemSize } in total (%{ filesStr},
%{foldersStr})
175
%{ spacesCount } spaces
177
%{count} members
451
This folder contains %{ amount } items.
499
Show %{totalResults} results
541
%{ amount } items selected. Actions are available above the table.
542
%{ itemCount } spaces selected
544
%{count} items were copied successfully
545
%{count} items were moved successfully
547
%{itemCount} items were moved to trash bin
548
%{linkShareCount} links giving access.
552
%{spaceCount} spaces were deleted successfully
553
%{spaceCount} spaces were disabled successfully
554
%{spaceCount} spaces were enabled successfully
579
Are you sure you want to delete %{count} selected spaces?
583
At least %{param1} characters long
584
At least %{param1} lowercase characters
585
At least %{param1} numbers
587
At least %{param1} uppercase characters
588
At most %{param1} characters long
617
Create links for the selected items
619
Create Space from selection
621
Create Space with the selected files.
630
Delete %{spaceCount} Spaces?
634
Disable %{spaceCount} Spaces?
650
Enable %{spaceCount} Spaces?
657
Failed to change quota for %{count} spaces
659
Failed to change quota for %{count} users
664
Failed to create links
669
Failed to delete %{spaceCount} spaces
671
Failed to disable %{spaceCount} spaces
673
Failed to disable sync for the selected shares
674
Failed to download the selected files.
677
Failed to enable %{spaceCount} spaces
678
Failed to enable sync for the selected shares
719
If you disable the %{count} selected spaces, they can no longer be
accessed. Only Space managers will still have access. Note: No files will
be deleted from the server.
720
If you enable the %{count} selected spaces, they can be accessed again.
770
Permanently delete %{amount} selected resources?
846
Quota of %{count} spaces was changed successfully
853
Sync for the selected shares was disabled successfully
854
Sync for the selected shares was enabled successfully
870
This %{ resourceType } is shared via %{ shareCount } invites
878
This space has %{memberShareCount} members.
881
This space has one member and %{linkShareCount} links.
891
Quota of %{count} users was changed successfully
893
You can't paste the selected files at this location because you can't paste
an item into itself.
962
%{groupAssignmentCount} group assignments were added successfully
963
%{groupAssignmentCount} group assignments were deleted successfully
964
%{groupCount} groups were deleted successfully
967
%{groupCount} members
970
%{userCount} users logins edited successfully
971
%{userCount} users were deleted successfully
975
Add %{userCount} users to groups
980
Are you sure you want to delete the %{groupCount} selected groups?
981
Are you sure you want to delete the %{userCount} selected users?
987
Delete %{groupCount} groups?
988
Delete %{userCount} users?
994
Edit login for %{userCount} users
1002
Failed to add %{groupAssignmentCount} group assignments
1006
Failed to delete %{groupAssignmentCount} group assignments
1007
Failed to delete %{groupCount} groups
1008
Failed to delete %{userCount} users
1012
Failed to edit %{userCount} user logins
1030
Group assignments already added
1031
Group assignments already removed
1068
Remove %{userCount} users from groups







нд, 9 черв. 2024 р. о 14:06 Dmytro Kolesnyk ***@***.***> пише:

**Comment by DeepDiver1975** [comment]
@if0else9 you have now the role 'reviewer' - let me know if this allows you to execute the desired changes. THX a lot

**Comment by if0else9** [comment]
account ***@***.***
Permissions:
1 -Same. (Can't save)
2- Same. (Can't save)

Nothing changes



------ Original Message ------
From "Dmytro Kolesnyk" ***@***.***>
To "owncloud/ocis" 
***@***.***>
Date 6/4/2024 5:25:48 PM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by DeepDiver1975** [comment]
> 1 -Same. (Can't save) 2- Same. (Can't save)

what are you referring to?

**Comment by if0else9** [comment]
I can't add a translation for:
1
%{ errors } of %{ uploads } items failed
2
%{ filesInProgressCount } items uploading...
3
%{ roundedRemainingHours } hours left
4
%{ roundedRemainingMinutes } minutes left
5
%{ successfulUploads } items uploaded
166
%{ filesCount } files
167
%{ filesCount } files including %{ filesHiddenCount } hidden
168
%{ foldersCount } folders
169
%{ foldersCount } folders including %{ foldersHiddenCount } hidden
170
%{ itemCount } items selected
171
%{ itemsCount } items in total (%{ filesStr}, %{foldersStr}, 
%{spacesStr})
172
%{ itemsCount } items in total (%{ filesStr}, %{foldersStr})
173
%{ itemsCount } items with %{ itemSize } in total (%{ filesStr}, 
%{foldersStr}, %{spacesStr})
174
%{ itemsCount } items with %{ itemSize } in total (%{ filesStr}, 
%{foldersStr})
175
%{ spacesCount } spaces
177
%{count} members
451
This folder contains %{ amount } items.
499
Show %{totalResults} results
541
%{ amount } items selected. Actions are available above the table.
542
%{ itemCount } spaces selected
544
%{count} items were copied successfully
545
%{count} items were moved successfully
547
%{itemCount} items were moved to trash bin
548
%{linkShareCount} links giving access.
552
%{spaceCount} spaces were deleted successfully
553
%{spaceCount} spaces were disabled successfully
554
%{spaceCount} spaces were enabled successfully
579
Are you sure you want to delete %{count} selected spaces?
583
At least %{param1} characters long
584
At least %{param1} lowercase characters
585
At least %{param1} numbers
587
At least %{param1} uppercase characters
588
At most %{param1} characters long
617
Create links for the selected items
619
Create Space from selection
621
Create Space with the selected files.
630
Delete %{spaceCount} Spaces?
634
Disable %{spaceCount} Spaces?
650
Enable %{spaceCount} Spaces?
657
Failed to change quota for %{count} spaces
659
Failed to change quota for %{count} users
664
Failed to create links
669
Failed to delete %{spaceCount} spaces
671
Failed to disable %{spaceCount} spaces
673
Failed to disable sync for the selected shares
674
Failed to download the selected files.
677
Failed to enable %{spaceCount} spaces
678
Failed to enable sync for the selected shares
719
If you disable the %{count} selected spaces, they can no longer be 
accessed. Only Space managers will still have access. Note: No files 
will be deleted from the server.
720
If you enable the %{count} selected spaces, they can be accessed again.
770
Permanently delete %{amount} selected resources?
846
Quota of %{count} spaces was changed successfully
853
Sync for the selected shares was disabled successfully
854
Sync for the selected shares was enabled successfully
870
This %{ resourceType } is shared via %{ shareCount } invites
878
This space has %{memberShareCount} members.
881
This space has one member and %{linkShareCount} links.
891
Quota of %{count} users was changed successfully
893
You can't paste the selected files at this location because you can't 
paste an item into itself.
962
%{groupAssignmentCount} group assignments were added successfully
963
%{groupAssignmentCount} group assignments were deleted successfully
964
%{groupCount} groups were deleted successfully
967
%{groupCount} members
970
%{userCount} users logins edited successfully
971
%{userCount} users were deleted successfully
975
Add %{userCount} users to groups
980
Are you sure you want to delete the %{groupCount} selected groups?
981
Are you sure you want to delete the %{userCount} selected users?
987
Delete %{groupCount} groups?
988
Delete %{userCount} users?
994
Edit login for %{userCount} users
1002
Failed to add %{groupAssignmentCount} group assignments
1006
Failed to delete %{groupAssignmentCount} group assignments
1007
Failed to delete %{groupCount} groups
1008
Failed to delete %{userCount} users
1012
Failed to edit %{userCount} user logins
1030
Group assignments already added
1031
Group assignments already removed
1068
Remove %{userCount} users from groups


------ Original Message ------
From "Thomas Müller" ***@***.***>
To "owncloud/ocis" ***@***.***>
Cc "if0else9" ***@***.***>; "Mention" 
***@***.***>
Date 6/10/2024 12:33:27 PM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by DeepDiver1975** [comment]
in which resource on transifex? as requested before: please post a link - much easier to collaborate - thx

**Comment by if0else9** [comment]
https://app.transifex.com/owncloud-org/owncloud-web/language/uk/

I have issue with:
admin-settings
core
  files
pkg
search




admin-settings:
3
%{groupAssignmentCount} group assignments were added successfully
4
%{groupAssignmentCount} group assignments were deleted successfully
5
%{groupCount} groups were deleted successfully
8
%{groupCount} members
11
%{userCount} users logins edited successfully
12
%{userCount} users were deleted successfully
16
Add %{userCount} users to groups
21
Are you sure you want to delete the %{groupCount} selected groups?
22
Are you sure you want to delete the %{userCount} selected users?
28
Delete %{groupCount} groups?
29
Delete %{userCount} users?
35
Edit login for %{userCount} users
43
Failed to add %{groupAssignmentCount} group assignments
47
Failed to delete %{groupAssignmentCount} group assignments
48
Failed to delete %{groupCount} groups
49
Failed to delete %{userCount} users
53
Failed to edit %{userCount} user logins
71
Group assignments already added
72
Group assignments already removed


core:
1
%{ errors } of %{ uploads } items failed
2
%{ filesInProgressCount } items uploading...
3
%{ roundedRemainingHours } hours left
4
%{ roundedRemainingMinutes } minutes left
5
%{ successfulUploads } items uploaded


pkg:
6
%{ amount } items selected. Actions are available above the table.
7
%{ itemCount } spaces selected
9
%{count} items were copied successfully
10
%{count} items were moved successfully
12
%{itemCount} items were moved to trash bin
13
%{linkShareCount} links giving access.
17
%{spaceCount} spaces were deleted successfully
18
%{spaceCount} spaces were disabled successfully
19
%{spaceCount} spaces were enabled successfully
48
At least %{param1} characters long
49
At least %{param1} lowercase characters
50
At least %{param1} numbers
52
At least %{param1} uppercase characters
53
At most %{param1} characters long
82
Create links for the selected items
84
Create Space from selection
86
Create Space with the selected files.
95
Delete %{spaceCount} Spaces?
122
Failed to change quota for %{count} spaces
124
Failed to change quota for %{count} users
129
Failed to create links
134
Failed to delete %{spaceCount} spaces
136
Failed to disable %{spaceCount} spaces
138
Failed to disable sync for the selected shares
142
Failed to enable %{spaceCount} spaces
143
Failed to enable sync for the selected shares
184
If you disable the %{count} selected spaces, they can no longer be 
accessed. Only Space managers will still have access. Note: No files 
will be deleted from the server.
185
If you enable the %{count} selected spaces, they can be accessed again.

------ Original Message ------
From "Thomas Müller" ***@***.***>
To "owncloud/ocis" ***@***.***>
Cc "if0else9" ***@***.***>; "Mention" 
***@***.***>
Date 6/10/2024 12:33:27 PM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by DeepDiver1975** [comment]
> 3 %{groupAssignmentCount} group assignments were added successfully 4 %{groupAssignmentCount} group assignments were deleted successfully 5 %{groupCount} groups were deleted successfully


Non of these holds a translation - so anybody should be capable to add a translations - TBH: no idea what's wrong - sorry

This is how it looks on my end:
![image](https://github.com/owncloud/ocis/assets/1005065/2b2d966a-5e3a-474d-95dd-e1339254b60d)

**Comment by if0else9** [comment]
But I can't save translations in these fields :-(


------ Original Message ------
From "Thomas Müller" ***@***.***>
To "owncloud/ocis" ***@***.***>
Cc "if0else9" ***@***.***>; "Mention" 
***@***.***>
Date 6/10/2024 1:13:50 PM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by DeepDiver1975** [comment]
> But I can't save translations in these fields :-(

please share a screenshot

**Comment by if0else9** [comment]
Attached video shows these


------ Original Message ------
From "Thomas Müller" ***@***.***>
To "owncloud/ocis" ***@***.***>
Cc "if0else9" ***@***.***>; "Mention" 
***@***.***>
Date 6/10/2024 1:23:34 PM
Subject Re: [owncloud/ocis] Please provide CRUDS for creating Ukrainian 
localization. (Issue #9305)

**Comment by DeepDiver1975** [comment]
> Attached video shows these

no - attachments are are removed when answering to github tickets via email

**Comment by micbar** [comment]
Please upload attachments directly on https://github.com/owncloud/ocis/issues/9305

**Comment by if0else9** [comment]
https://github.com/owncloud/ocis/assets/52785502/f3c4bb5d-e5ca-4ef9-81d7-743e4a49ba50

**Comment by DeepDiver1975** [comment]
And you are logged in with which account on transifex?

**Comment by if0else9** [comment]
***@***.***

**Comment by DeepDiver1975** [comment]
PLEASE USE THE BROWSER TO ANSWER!

**Comment by DeepDiver1975** [comment]
Just in case this is not known - these translatable texts hold multiple translations depending on the count.
All translations have to be entered before saving.

**Comment by DeepDiver1975** [comment]
![image](https://github.com/owncloud/ocis/assets/1005065/7a9c0c2a-b4e5-45c0-92f9-fea8078bf600)

**Comment by if0else9** [comment]
My GitHub account is if0else9.


Same story. Can't save translation

**Comment by if0else9** [comment]
The translation into Ukrainian is almost ready. Please tell me how I can
see the translation in the OCIS interface. Is it possible to access the
night build?

пн, 10 черв. 2024 р. о 18:28 Dmytro Kolesnyk ***@***.***> пише:

**Comment by if0else9** [comment]
@DeepDiver1975 Please

**Comment by adminnirgovua** [comment]
@DeepDiver1975 The translation into Ukrainian is almost ready. Please tell me how I can
see the translation in the OCIS interface. Is it possible to access the
night build?

**Comment by DeepDiver1975** [comment]
https://owncloud.dev/ocis/deployment/continuous_deployment/

**Comment by adminnirgovua** [comment]
@DeepDiver1975 No Ukrainian language in preferences (Checked all versions https://owncloud.dev/ocis/deployment/continuous_deployment/#ocis-with-latest-owncloud-web)

**Comment by DeepDiver1975** [comment]
@micbar ^ please have a look - THX

**Comment by adminnirgovua** [comment]
@micbar @DeepDiver1975 Thank you very much for adding the Ukrainian language. The entire interface works fine in Ukrainian, I also checked the Russian language. But only in Russian and Ukrainian languages, ​​there is an OnlyOffice and Collabora in English. 

In all other languages, OnlyOffice and Collabora take the right language.

**Comment by adminnirgovua** [comment]
Please tell us how to fix this.

**Comment by adminnirgovua** [comment]
https://github.com/owncloud/ocis/assets/172592814/db2e15c2-5db7-4b8f-a270-566b3d782651

**Comment by adminnirgovua** [comment]
@micbar  @DeepDiver1975 Please help. 

https://github.com/owncloud/ocis/assets/172592814/a9a39996-5562-43b5-8fda-4deb1a294750
