### ISSUE TITLE
[Keycloak] ocis can delete Keycloak user (user created on keycloak side)

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#9307]
## Describe the bug
From the OCIS side, the user can be deleted, which was created from the keycloak. We were able to login from the deleted user, but the data of the user was deleted.

## Steps to reproduce

1. As an user `admin`, log in the keycloak `https://keycloak.owncloud.test`
2. From keycloak, create a user `demo` with the following attributes and values:

  |  Attributes | values  |
  |---|---|
  | Username | demo |
  Email: demo@example.com
  |  First name | demo |
  |  last name  |  Bahadur |

3. from keycloak, set the user password and assign the role with `ocisUser` 
4. As a user `demo`, log in the OCIS `https://ocis.owncloud.test`
5. As a user `demo`, create a folder named `folder`
6. As a user `admin`, log in the OCIS `https://ocis.owncloud.test`
7. **admin** deletes `demo` user through ocis-web UI  
    Note: demo user is deleted from ocis server but demo user still exist on Keycloak server)
8. We can relogin deleted **demo** user on ocis-web (no previous resource is available :heavy_check_mark: i.e `folder` is deleted)

## Questions
-  **ocis-web** can delete `demo` user (demo user which is created from Keycloak) . Is this bug or a feature :question:  

## Screen Record
[Screencast from 06-04-2024 09:54:20 AM.webm](https://github.com/owncloud/ocis/assets/61624650/68e1e730-e906-4b07-a495-e1173d9caa29)

## Tested on
Web: ownCloud Web UI 9.0.0-alpha.5 
OCIs:  Infinite Scale 5.1.0-prealpha+d200dfc03 Community 
Keyclock: 24.0.1

**Comment by saw-jan** [comment]
I believe this behavior is expected (as of now). But not in a place to confirm it.
1. keycloak user logs in - ocis recognizes it :heavy_check_mark: 
2. admin deletes recognized user from ocis webUI :heavy_check_mark:
3. user and its data gets deleted from ocis :heavy_check_mark: 
4. keycloak user still present :heavy_check_mark: 

CC @rhafer @micbar @ScharfViktor

**Comment by micbar** [comment]
Works as designed.
