### ISSUE TITLE
User with Role `User Light` can't see Space shared with it through its group

### ISSUE THREAD

**Issue by shishouyuan** [owncloud/ocis#9310]
User with Role `User Light` can't see Space shared with it through its group, but can see notifications like *Admin added you to Space xxx*. However, if share the space to the user through its user name it can see the space, even after replace user with its group in the space member.

### Steps to reproduce
1. Set up a NEW user with role `User Light`, add it into a group.
2. Create a NEW space, add the new user's group into the members(no matter for `Can view`, `Can edit` or `Can manage`).
3. Login with the new user, nothing can be seen in Spaces, but there will be notification like *Admin added you to Space xxx*.

### Expected behaviour
See the space shared with it.

### Actual behaviour
User with Role `User Light` can't see Space shared with it through its group, but can see notifications like *Admin added you to Space xxx*

### Environment general
**Operating system**: Linux

**Backend (ownCloud Core or Infinite Scale)**: Infinite Scale

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** 3.1.0-next.2+038520778 with web clent 7.0.1

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** Docker with tag latest

**Comment by micbar** [comment]
checking...

**Comment by micbar** [comment]
weird. Cannot reproduce.

What I did:

1. Set user Richard to role "User Light"
2. As "admin" invite group "quantum-lovers" to space "Test"
3. As "richard" browse to the Spaces Overview

**Comment by kulmann** [comment]
> weird. Cannot reproduce.
> 
> What I did:
> 
> 1. Set user Richard to role "User Light"
> 2. As "admin" invite group "quantum-lovers" to space "Test"
> 3. As "richard" browse to the Spaces Overview

Like stated in the previous comments it only works on newly created users. Just try it with a new user and a new group.

**Comment by micbar** [comment]
ok, found the issue

`2024-06-04T11:25:00+02:00 ERR failed to list storage spaces error="error reading user index: stat /Users/mbarz/.ocis/storage/users/indexes/by-user-id/f2aed455-8177-4ad6-aa7b-b7e800fb275a.mpk: no such file or directory" filters=[{"Term":{"SpaceType":"personal"},"type":4},{"Term":{"User":{"opaque_id":"f2aed455-8177-4ad6-aa7b-b7e800fb275a"}},"type":6}] pkg=rgrpc service=storage-users status={"code":15,"message":"error listing spaces","trace":"2024134a5a00f14a06964293f65a8bdf"} traceid=2024134a5a00f14a06964293f65a8bdf`

**Comment by micbar** [comment]
@kobergj @aduffeck that points for me in the direction that when adding a grant for a group, the space index for the user is not created.

**Comment by kobergj** [comment]
> when adding a grant for a group, the space index for the user is not created.

This is intended behaviour, the group has another index. But the problem is related. It fails here: https://github.com/cs3org/reva/blob/edge/pkg/storage/utils/decomposedfs/spaces.go#L329

That makes sense. A light user has no space, therefore no spaceindex for them is created. If you invite the user to another space (personally, not via group), the spaceindex is created and the user can now also access the space that was shared via group.

We should ignore the `not found` error here and just continue. With light users not every user might have a space index.
