### ISSUE TITLE
4 typos in /services/notifications/pkg/email/l10n/locale/ru/LC_MESSAGES/notifications.po

### ISSUE THREAD

**Issue by dutty5** [owncloud/ocis#9318]
There are 4 typos in the translation file https://github.com/owncloud/ocis/blob/4c3ad07bf8c2fc151c486bb961c2fd712a383bea/services/notifications/pkg/email/l10n/locale/ru/LC_MESSAGES/notifications.po#L88

`{ShareShare}` instead of `{ShareSharer}` (lines 88 and 93) and `{SpaceShare}` instead of `{SpaceSharer}` (lines 107, 119).

As Russian translations look abandoned in transifex and blocked for editing, nothing can be done there to fix the issue.

**Comment by micbar** [comment]
@dragotin Can you clarify.

**Comment by DeepDiver1975** [comment]
Translations are wrong - fixed them.

@dutty5 what is your account handle on transifex and I can promote you to get the russian translation back in shape
