### ISSUE TITLE
State of this project post acquisition?

### ISSUE THREAD

**Issue by asim** [owncloud/ocis#9321]
I've just noticed ownCloud got acquired by Kiteworks. What's the state of this project post acquisition? Is it business as usual?

**Comment by micbar** [comment]
We are working on that project with unrestricted working forces. Please check the public roadmap www.owncloud.com/roadmap (links to our github project) for more details.

The project is mainly driven by public projects and tenders in the science and education segment.

**Comment by asim** [comment]
Ok thanks for letting me know. Anyway somewhat related. You have two maintainers on the [Go Micro](https://github.com/go-micro/go-micro) project (@dragonchaser and @kobergj) who I don't have contact info for. I am now removing them as maintainers as I'm pruning inactive maintainers. If you require further assistance please contact me directly.

**Comment by micbar** [comment]
@asim 

@dragonchaser and @kobergj are members of my team. They contribute from time to time to go micro.

**Comment by dragonchaser** [comment]
@asim Morning, just received your mail about the removal, sorry about the missing contact, how can we change that? As @micbar mentioned I am part of the ocis team here at owncloud.

**Comment by asim** [comment]
Future versions of Go Micro will be BSL licensed. There needs to be a real discussion around maintenance and sustainability. I tried to engage with your CTO but didn't get a response. If you'd like to discuss further please email me: asim at micro dot mu

**Comment by micbar** [comment]
@dragotin FYI

**Comment by ChristophWolffNabu** [comment]
> We are working on that project with unrestricted working forces. Please check the public roadmap [www.owncloud.com/roadmap](http://www.owncloud.com/roadmap) (links to our github project) for more details.
> 
> The project is mainly driven by public projects and tenders in the science and education segment.

There are some features that a not visibile to me. Will there be an enterprise version that excludes features OpenID Connect SAML etc? This would be horrible for most institutions

**Comment by wkloucek** [comment]
> Will there be an enterprise version that excludes features OpenID Connect SAML etc?

I doubt this is even possible with the architecture of ownCloud Infinite scale. There is basically only OIDC authentication for users (except basic auth), so I see a close to zero chance that it will be a enterprise only feature in the future.
