### ISSUE TITLE
[QA] remove all OCS related tests from the expected-failure list

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9324]
OCS is deprecated and the bug reports related to it will not have a fix. So we should remove all OCS related tests from the expected failure list.

Expected failure files:
https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-API-on-OCIS-storage.md
https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

TODO:
- check expected-failure list for ocs related issues
- check if the test is rewritten using Sharing NG API, if not -> create a new test
- remove the failing tests from the list
- remove the failing test scenarios
- close the issue as OCS is deprecated and won't have a fix\

From https://github.com/owncloud/ocis/issues/1710#issuecomment-2149017968

Pull Requests:
- [x] https://github.com/owncloud/ocis/pull/9349
- [x] https://github.com/owncloud/ocis/pull/9351
- [x] https://github.com/owncloud/ocis/pull/9352
- [x] https://github.com/owncloud/ocis/pull/9354
- [x] https://github.com/owncloud/ocis/pull/9357
- [x] https://github.com/owncloud/ocis/pull/9368
- [x] https://github.com/owncloud/ocis/pull/9370
- [x] https://github.com/owncloud/ocis/pull/9381
- [x] https://github.com/owncloud/ocis/pull/9409
- [x] https://github.com/owncloud/ocis/pull/9417
- [x] https://github.com/owncloud/ocis/pull/9420
- [x] https://github.com/owncloud/ocis/pull/9421
- [x] https://github.com/owncloud/ocis/pull/9422
- [x] https://github.com/owncloud/ocis/pull/9431
- [x] https://github.com/owncloud/ocis/pull/9433
- [x] https://github.com/owncloud/ocis/pull/9435

**Comment by ScharfViktor** [comment]
> TODO:
> 
> * check expected-failure list for ocs related issues
> * remove the tests from the list
> * remove the test scenarios
> * close the issue as OCS is deprecated and won't have a fix\

I would add one line here: 

- check if the test is rewritten using Sharing NG API, if not -> create a new test

**Comment by saw-jan** [comment]
@ScharfViktor Please, update in the description

**Comment by ScharfViktor** [comment]
> @ScharfViktor Please, update in the description

done

**Comment by phil-davis** [comment]
Note: in some cases the server behavior is now good, but the test expectation is just a little bit different to what the server code implemented - usually the status code might be a little different (200, 201, 204 etc. 400, 404, etc.)

An example is PR #9315 for issue #2111

I suggest that, if the current server behavior is "OK", that we adjust the test scenario(s) to make it pass. That will allow us to remove it from expected failures but not need to delete it yet. That will help us to continue to provide good protection against regressions for the coming months, until the OCS API is actually removed (and we delete all the OCS-related test scenarios).

**Comment by grgprarup** [comment]
OCS-related scenarios are adjusted wherever needed and removed from the expected failures. The issues mentioned in expected failures are closed. All the PRs related to this issue are merged. I am closing this issue as completed.
