### ISSUE TITLE
Inconsistencies in OCIS_REVA_GATEWAY

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9332]
Stumbled over by chance while working on something totally different, I found some inconsistencies in the `OCIS_REVA_GATEWAY` envvar:

As you can see from the output below we have three issues:

1. Rename the envvar text in `collaboration` to be inline with the others (easy)
2. Deprecate `CLIENTLOG_REVA_GATEWAY` from the clientlog service if this is not explicily necessary
3. Remove `COLLABORATION_CS3API_GATEWAY_NAME` from the collaboration service if this is not explicily necessary.

(Output shortned from `grep -rn OCIS_REVA_GATEWAY | grep -v OCIS_REVA_GATEWAY_`)
```
thumbnails "OCIS_REVA_GATEWAY" desc:"CS3 gateway used to look up user metadata" introductionVersion:"pre5.0"

notifications "OCIS_REVA_GATEWAY" desc:"CS3 gateway used to look up user metadata" introductionVersion:"pre5.0"

clientlog "OCIS_REVA_GATEWAY;CLIENTLOG_REVA_GATEWAY" desc:"CS3 gateway used to look up user metadata" introductionVersion:"5.0"

collaboration "OCIS_REVA_GATEWAY;COLLABORATION_CS3API_GATEWAY_NAME" desc:"The service name of the CS3API gateway." introductionVersion:"%%NEXT%%"

webdav "OCIS_REVA_GATEWAY" desc:"CS3 gateway used to look up user metadata" introductionVersion:"pre5.0"

search "OCIS_REVA_GATEWAY" desc:"The CS3 gateway endpoint." introductionVersion:"pre5.0"

userlog "OCIS_REVA_GATEWAY" desc:"CS3 gateway used to look up user metadata" introductionVersion:"pre5.0"
```

@micbar @jvillafanez @kobergj @2403905

**Comment by kobergj** [comment]
The service based gateway envvars like "CLIENTLOG_REVA_GATEWAY" and "COLLABORATION_CS3API_GATEWAY_NAME" should be removed (if possible) or at least deprecated.

It makes no sense to point one service to another reva gateway then the others.
