### ISSUE TITLE
DAV report search finds users personal space

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/ocis#9335]
The report search endpoint returns the users own personal space eg “admin” if the search term contains for example "admin" and the username is "admin". 
This might be implemented as designed but showing this result in the Web search confuses the user and has no use case. 

Unfortunately filter this from the search result in Web is not enough as we still get the number of the found results in the response headers. 

I appreciate if we can omit this from the search report

**Comment by dragonchaser** [comment]
Can we discuss this quickly in the zoom? We see this as expected behavior.

**Comment by dragonchaser** [comment]
As discussed with @kobergj, @fschade and @AlexAndBear: This needs typed search which is a feature-request. The current implementation works as specified. 

@tbsbdr how do we proceed here?

**Comment by kulmann** [comment]
I'll close here. This is not important enough to spend any more time on discussing it. Please forget about it.
