### ISSUE TITLE
[QA] API test SpacesContext userTriesToDownloadFileVersions index parameter is unused

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#9342]
## Describe the bug
Test code has a step:
```
	 * @When /^user "([^"]*)" tries to get version of the file "([^"]*)" with the index "([^"]*)" of the space "([^"]*)" using the WebDAV API$/

	public function userTriesToDownloadFileVersions(string $user, string $file, string $index, string $spaceName):void {
```

But `$index` is not used in the function.

That seems strange - why specify the version index in the step and then not use it.

Investigate what the test step is doing, what `Then` steps are being used after it, and sort out the code so that the tests do what they say.

If there is some good reason that `$index` is not actually used, then write comment for the function so that people will understand this.

## Setup
CI

**Comment by prashant-gurung899** [comment]
@phil-davis Phil Ji, the only **Then** after the above mentioned **When** step is:
Then the HTTP status code should be "403"
Meaning the file that user tried to download is forbidden.

**Comment by prashant-gurung899** [comment]
> @phil-davis Phil Ji, the only **Then** after the above mentioned **When** step is: Then the HTTP status code should be "403" Meaning the file that the user tries to download is forbidden.

Forgot to mention this :  Then the HTTP status code should be "200"

**Comment by prashant-gurung899** [comment]
This issue has been fixed with this PR:
https://github.com/owncloud/ocis/pull/9455
