### ISSUE TITLE
[QA] API test TrashbinContext userTriesToRestoreElementInTrash

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#9344]
## Describe the bug
`restoreElement` has no return value if the path to restore `$originalPath` does not exist.
But `restoreElement` says that it always returns `ResponseInterface`

It currently can end up returning `null`

Investigate, and sort out the proper return type, and what happens in `userTriesToRestoreElementInTrash` if `restoreElement` does not return a `ResponseInterface`

## Setup
CI

**Comment by prashant-gurung899** [comment]
I'm currently working on this issue.

**Comment by prashant-gurung899** [comment]
The fix for this issue has been merged with this PR :
https://github.com/owncloud/ocis/pull/9471
So, im closing this issue ass completed.
