### ISSUE TITLE
[QA] API test WebDav downloadedContentWhenDownloadingWithRangeShouldBe

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#9345]
## Describe the bug
```
	/**
	 * @Then /^the downloaded content when downloading file "([^"]*)" with range "([^"]*)" should be "([^"]*)"$/
	 *
	 * @param string $fileSource
	 * @param string $range
	 * @param string $content
	 *
	 * @return void
	 */
	public function downloadedContentWhenDownloadingWithRangeShouldBe(
		string $fileSource,
		string $range,
		string $content
	):void {
		$this->checkDownloadedContentMatches($content);
	}
```

`$fileSource` and `$range` are not used. That looks strange.

Investigate what the step is doing, and where it is used in scenarios. Fixup the step code, or delete it if it is unused.

## Setup
CI

**Comment by prashant-gurung899** [comment]
@phil-davis Ji, looks like the step is not used in any of the scenario. So, i am gonna delete it and make a PR.

**Comment by prashant-gurung899** [comment]
> @phil-davis Ji, looks like the step is not used in any of the scenario. So, i am gonna delete it and make a PR.

And it looks like there are more stepDefinitions that is unused in any scenarios.

**Comment by PrajwolAmatya** [comment]
This issue has been fixed by this PR, https://github.com/owncloud/ocis/pull/9519. And there's a follow up issue https://github.com/owncloud/ocis/issues/9539.
So, closing this issue for now.
