### ISSUE TITLE
[QA] API test WebDav checkElementList call to listFolderAndReturnResponseXml

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#9346]
## Describe the bug
`checkElementList` calls `listFolderAndReturnResponseXml` with only 2 parameters:
```
			$responseXmlObject = $this->listFolderAndReturnResponseXml(
				$user,
				"/",
			);
```

But `listFolderAndReturnResponseXml` requires 3 parameters.

Investigate and fix.

## Setup
CI

**Comment by amrita-shrestha** [comment]
assigned to @prashant-gurung899
