### ISSUE TITLE
[QA] API test WebDav checkAuthorOfAVersionOfFile array_reverse

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#9347]
## Describe the bug
In `checkAuthorOfAVersionOfFile` the PHP https://www.php.net/manual/en/function.array-reverse.php function is used twice, but the result is never assigned to anything. 
```
		// reverse the array to get the latest version first
		\array_reverse($authors);
```

```
		// reverse the array to get the latest version first
		\array_reverse($displaynames);
```

So the code does not actually do what the comment says.

Investigate and fix.

## Setup
CI

**Comment by anon-pradip** [comment]
My findings are:
- The steps that use the parent of the function containing `\array_reverse($authors);` and `\array_reverse($displaynames);` i.e., `asUsersAuthorsOfVersionsOfFileShouldBe` come under expected to failure scenarios. And the scenarios are as follows:
```feature
  Scenario: enable file versioning and check the history of changes from multiple users
  Scenario: enable file versioning and check the history of changes from multiple users for shared folder in the group
  Scenario: enable file versioning and check the history of changes from multiple users for shared file in the group
  Scenario: enable file versioning and check the history of changes from multiple users while moving file in/out of a subfolder
  Scenario: enable file versioning and check the history of changes from multiple users after renaming file by sharer
  Scenario: enable file versioning and check the history of changes in sharer after renaming file by sharee
  Scenario: enable file versioning and check the history of changes from multiple users when reshared after unshared by sharer
  Scenario: enable file versioning and check the history of changes from multiple users who have a matching folder/file
  Scenario: enable file versioning and check the history of changes from multiple users who have a matching file
  Scenario: enable file versioning and check the version author after restoring a version of a file inside a folder
  Scenario: enable file versioning and check the version author after restoring a version of a file

```
- Removing/commenting both the lines i.e., `\array_reverse($authors);` and `\array_reverse($displaynames);` will cause no effects in the test results; meaning, produces same results before and after removing/commenting.
- Also, as mentioned in the issue above, the results of both the functions: `\array_reverse($authors);` and `\array_reverse($displaynames);` are never assigned to anything. Moreover, reversing the array using `array_reverse()` method doesn't modify the original array. 
**So, those usages seems unnecessary**

**Comment by phil-davis** [comment]
Have a look at the logic of the function - maybe the person that wrote the code intended that `array_reverse` should actually happen, and fixing that might help make the tests pass.

**Comment by phil-davis** [comment]
The unused code was also removed in core PR https://github.com/owncloud/core/pull/41277

**Comment by anon-pradip** [comment]
Closing as the aim of this issue is resolved.
