### ISSUE TITLE
Config permission denied error with rootless podman

### ISSUE THREAD

**Issue by vwkd** [owncloud/ocis#9378]
## Describe the bug

I'm trying to run OCIS with rootless podman on Fedora following the [Container Setup](https://doc.owncloud.com/ocis/next/deployment/container/container-setup.html) guide. I've verified the logged in user has the default user and group ID 1000 matching the container user and group ID.

However, I'm getting a permission denied error when creating or accessing the config file `/etc/ocis/ocis.yaml`. When running podman as root no error is thrown.

## Steps to reproduce

1. Verify the logged in user has the default user and group ID 1000 matching the container user and group ID.

```console
> id
uid=1000(foobar) gid=1000(foobar) groups=1000(foobar),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
> podman inspect -f '{{.Config.User}}' owncloud/ocis
1000
```

2. Create the `config` and `data` folders and verify the user and group ID again.

```console
> mkdir config data
> ls -n
total 4
drwxr-xr-x. 1 1000 1000  18 Jun 13 16:35 config
drwxr-xr-x. 1 1000 1000   0 Jun 13 14:54 data
-rw-r--r--. 1 1000 1000 396 Jun 13 16:06 docker-compose.yml
```

3. Run the [First Time Initialization](https://doc.owncloud.com/ocis/next/deployment/general/general-info.html#initialize-infinite-scale) to create the config. This fails with the error.

```console
> podman run -it -v ./config:/etc/ocis:Z owncloud/ocis:latest init
2024/06/13 14:31:58 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
Do you want to configure Infinite Scale with certificate checking disabled?
 This is not recommended for public instances! [yes | no = default]
2024/06/13 14:31:58 Could not create config: open /etc/ocis/ocis.yaml: permission denied
```

4. Run the command as `sudo` again. This creates the config successfully.

```console
> sudo podman run -it -v ./config:/etc/ocis:Z owncloud/ocis:latest init
2024/06/13 14:43:01 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
Do you want to configure Infinite Scale with certificate checking disabled?
 This is not recommended for public instances! [yes | no = default]

=========================================
 generated OCIS Config
=========================================
 configpath : /etc/ocis/ocis.yaml
 user       : admin
 password   : <redacted>
```

5. Run the [container](https://doc.owncloud.com/ocis/next/deployment/container/container-setup.html#recurring-start-of-infinite-scale). This fails with the error.

```console
> podman compose up
>>>> Executing external compose provider "/usr/bin/podman-compose". Please refer to the documentation for details. <<<<

2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae
fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9
[ocis] | 2024/06/13 14:35:23 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
[ocis] | open etc/ocis/ocis.yaml: permission denied
[ocis] | open etc/ocis/ocis.yaml: permission denied
```

6. Run the command as `sudo` again. This starts the container successfully.

```console
> sudo podman compose up
>>>> Executing external compose provider "/usr/bin/podman-compose". Please refer to the documentation for details. <<<<

2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae
fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9
[ocis] | 2024/06/13 14:45:55 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
[ocis] | {"level":"info","service":"nats","time":"2024-06-13T14:45:55Z","line":"github.com/owncloud/ocis/v2/services/nats/pkg/logging/nats.go:2
1","message":"Starting nats-server"}
<truncated>
```

## Expected behavior

No permission denied error.

## Actual behavior

Permission denied error.

## Setup

- `docker-compose.yml`

```yml
version: "3.7"

services:
  ocis:
    image: docker.io/owncloud/ocis:latest
    environment:
      - OCIS_INSECURE=true
      - OCIS_URL=https://192.168.1.42:9200
      - OCIS_LOG_LEVEL=info
    restart: unless-stopped
    volumes:
      - ./config:/etc/ocis:Z
      - ./data:/var/lib/ocis:Z
    ports:
      - "9200:9200"
```

(Note: the `:Z` is necessary with podman for a SELinux issue.[^selinux])

## Additional context

- podman 5.0.3
- Fedora 40
- owncloud OCIS 5.1.0-prealpha+b6141627e

[^selinux]: https://github.com/containers/podman/issues/3683#issuecomment-517239831

**Comment by rhafer** [comment]
I don't think this is a problem with ocis. It's causes by the fact that rootless podman uses user namespacest. That means that the uidnumbers inside the container don't match the uids on the host system. You need to adjust the ownership of the directories to the mapped uids of the namespace. What I usually use  is `podman unshare` to enter the user namespace and adjust file ownership from there.

So in your case:

open a new terminal cd into the directory on the host containing the desired config and data directory and run:
```
> podman unshare
```

this basically makes you root in the user namespace then you can change the ownership of config directory. Now run:

```
# chown 1000 config
# chown 1000 data
```
then exit  the terminal session. On the host the directory should now have changed the ownership to the mapped userids of the namespace (on my system that is `1000999` e.g., might be different on yours).

**Comment by vwkd** [comment]
That worked flawlessly. Thanks so much!
