### ISSUE TITLE
New community ready deployment example using WOPI necessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9388]
Based on a discussion with @dragonchaser, with many thanks for the insights!

When writing the [easy install docs](https://github.com/owncloud/docs-ocis/pull/837), I came to the point that the current deployment example `deployments/examples/ocis_wopi/docker-compose.yml` is focused on dev needs. We need an example that fits to community needs (and could name it `ocis_community`).

Deriving from the current example, we need in particular the following changes:

* Use the actual traefik version --> v3
* Reduce the web office apps used to one
* Remove companion if not mandatory required
* Remove the supplemental monitoring configuration
* Remove inbucket and make the ocis email notification settings configurable

The new example must be backported to 5.0 to be available for the admin docs.

Note that the admin docs are more or less finished to use the deployment example. Only a few minor adaptions need to be made. Text adaptions could be made really quick and we would have 2 out of 3 scenarious live.

@micbar @tbsbdr

**Comment by prohtex** [comment]
+1

**Comment by micbar** [comment]
done on s`stable-5.0`

**Comment by dragotin** [comment]
There is the oCIS "full" example which is flexible and with all relevant services. I think that should cut it.
