### ISSUE TITLE
Document how to access ocis web interface.. 

### ISSUE THREAD

**Issue by domdorn** [owncloud/ocis#9396]
The readme mentions
./ocis init
./ocis server
to run ocis locally.. however, it doesn't mention anywhere how I can then access the server.. http://localhost / http://localhost:8080 both don't work.. which port does this bind to? I'm really surprised that I'm apparently the first one to ask this. 
also the console output does not show how to access the web ui.. 

![grafik](https://github.com/owncloud/ocis/assets/100349/3319d65f-bbbf-4b74-bd75-8b8a2c1395e8)

I also searched through the documentation at https://doc.owncloud.com/ocis/next/deployment/general/general-info.html but couldn't find out how I can access ocis ... 
Please put this info in a prominent place, e.g. right after the call `./ocis server` in the README

**Comment by micbar** [comment]
Does that work for you?

**Comment by domdorn** [comment]
@micbar  not sure what you mean.. the README still does not tell me how to access the web ui ? 
https://github.com/owncloud/ocis
![grafik](https://github.com/owncloud/ocis/assets/100349/74296d79-917c-48b6-8872-ca276b6e77ce)

**Comment by micbar** [comment]
Sorry forgot to post the link to the docs. In the section quick guide it says it.

**Comment by domdorn** [comment]
@micbar thanks for the pointer! I added the information that I was expecting in the README with the linked pull request. Feel free to simply commit the same/similar change by yourself instead of going through contributor processes etc. :-)
