### ISSUE TITLE
[ocis] collaboration service: allow disabling chat

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#9398]
## Is your feature request related to a problem? Please describe.
The current appprovider + wopiserver setup has the option `APP_PROVIDER_WOPI_DISABLE_CHAT`.

## Describe the solution you'd like
The collaboration service should also have a way to disable such wopi application features. Maybe there is a more generic way to inject options than the current `APP_PROVIDER_WOPI_DISABLE_CHAT` option.

## Describe alternatives you've considered
none.

## Additional context

There is a project that wants to switch to the collaboration service but relies on chat to be disabled on OnlyOffice.

cc @jvillafanez @micbar @d7oc

**Comment by jvillafanez** [comment]
In theory, it should be easy to do. It's just adding the `dchat=1` parameter in the app URL. Around https://github.com/owncloud/ocis/blob/master/services/collaboration/pkg/service/grpc/v0/service.go#L139

```
		q := u.Query()
		q.Add("WOPISrc", wopiSrcURL.String())
		q.Add("dchat", "1")
		qs := q.Encode()
```
The question is how we want to handle everything around this feature:
* Using a config parameter such as `COLLABORATION_APP_FEAT_DCHAT=1` could be reasonable. However, what about similar features provided by the WOPI app? I don't think we need a flag for every feature, but if we need to use any other feature, it should follow the same pattern.
  For a list of parameters: 
  * office365: https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/discovery#action-urls .
  * OnlyOffice: https://api.onlyoffice.com/editors/wopi/discovery#wopi-standart
  * Collabora: I haven't found info.
* In theory, we should be parsing the URLs coming for the discovery endpoint and then replace the parameters with proper values. Right now, all the parameters are being removed from the URL, and the `WOPIsrc` parameter is added later. We might use this same approach, so we could still skip the parsing of the URL and assume it's safe to send the parameter.
* As far as I know, Collabora doesn't advertise the parameters, so it's unclear how it will behave with the parameter. We could assume it will ignore the parameter if it isn't supported.

**Comment by wkloucek** [comment]
> I don't think we need a flag for every feature, but if we need to use any other feature, it should follow the same pattern.

I fully agree
