### ISSUE TITLE
add reverse proxy to hide services behind a single endpoint

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#94]
with ocis we currenty start multiple http services on different ports.

go-micro has a built in way of accessing these, because the go.micro.web service has a built in reverse proxy, which is used to do api calls with the web ui that should be reserved to admin users and probably disabled in production envionments.

The go.micro.api gateway can route requests if they follow a go micro pattern.

If we want to provide a single binary that can provide a single entry point for ocis I think we may need to implement our own routing service. There is an examples for it in the go micro plugins repo  https://github.com/micro/go-plugins/blob/master/micro/router/examples/router.go.

**Comment by refs** [comment]
Isn't the go-micro api on itself the definition of a reverse proxy? [src](https://micro.mu/docs/api.html#web-handler). My understanding is that starting the gateway with `--handler=web` does routing like the web service but still allow us to to grpc calls through the gateway. How does this not cover our requirements?

**Comment by DeepDiver1975** [comment]
The requirment is basically this:
- there is one domain hosting all service - e.g. ocis.example.net
- any requests by any client by any protocol goes to this domain
- openid connect well known is living in ocis.example.net/.well-known/openid-configuration
- phoenix live in ocis.example.net/phoenix
- graph endpoint is ocis.example.net/graph
- ...

^ please add further public routes we need - THX

**Comment by butonic** [comment]
If we want to use the micro plugin router we may need to extend it a little: https://github.com/micro/go-plugins/pull/477

**Comment by refs** [comment]
we're rolling with ocis proxy, if the needs arise to use micro proxy we'd reopen.
