### ISSUE TITLE
Convert locust benchmark tests to K6

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#940]
A summary of what the locust script did: by @phil-davis 
- be able to run against an OCIS server or an oC10 server
- provision test users, and remove them at the end of the test (can be optional scripted steps, in case the system-under-test has existing users already provisioned, and we want to just test with those, or need to create them at test startup) (needs to understand any differences in user provisioning on OCIS and oC10)
- test user names can just be sequentially numbered (e.g. they were `locust1` `locust2` ...), or whatever
- generate a different password for each test user
- generate a different email address for each test user
- "init" new users before the real test run by uploading a small file `initial-file.txt` and creating a folder `data` (that avoids "init" overhead effecting "ordinary" testing)
- have 6 small example files up to 100KB

For each user the "test workflow" is:
- download `initial-file.txt` (optional)
- upload each of the 6 files
- repeat...

Other:
- allow the number of users to be ramped up to 50, 100, 200, 300 (these were the numbers used in locust to record some older results) (we will be able to vary this!)
- record separate result statistics for download and upload
- be able to get requests/sec, average response time, counts of successful and unsuccessful requests
- output results to file in some "easily understood" format (e.g. locust produced CSV files)

- be able to run the K6 test runner on a different system to the system-under-test, across a real network

Afterwards we can make it flexible to change the mix of MKCOL, download, upload, delete, rename etc to get results for combinations of transactions...

**Comment by fschade** [comment]
let me know if you need help on this topic

**Comment by individual-it** [comment]
closing this issue after chatting with @fschade 
all whats needed for now is done
