### ISSUE TITLE
notification can't send mails if the displayname has a comma

### ISSUE THREAD

**Issue by b1schumacher** [owncloud/ocis#9402]
## Describe the bug
If the display name of a user has a comma, the notification service can't send a mail, because the sender is not in commas which has to be with a comma in the string.

## Steps to reproduce
1. Change the display name to "Tux, Eberhard"
2. Send a Mail via the notification

## Expected behavior
Mails should be send from this user.

## Actual behavior
Mails are not send and have a error in the notifications logs

{"level":"error","service":"notifications","error":"Mail Error: mail: missing '@' or angle-addr; Header: [From] Address: [Tux, Eberhard via owncloud@mymail.com]","e
vent":"SendEmail","time":"2024-06-14T16:06:31Z","line":"github.com/owncloud/ocis/v2/services/notifications/pkg/service/service.go:129","message":"failed to send a message"}

## Setup
OCIS 5.0.5 with helm charts deployed

**Comment by 2403905** [comment]
@b1schumacher Thank you for your report. I'll take a look ASAP.

**Comment by blicknix** [comment]
@2403905 There is already a merge request which fixes this #9403
