### ISSUE TITLE
Pipeline fails with `EVENTHISTORY_STORE=nats-js-kv`

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#9448]
In https://github.com/owncloud/ocis/pull/9361 I switched the default store type for the eventhistory service to `nats-js-kv`. This is needed to make the use of the activity feature.

However the pipeline fails because of this. Specifically the `gdpr export` test is failing every time. Needs investigation if this a code or test problem.

**Comment by saw-jan** [comment]
we will have a first look on test side.

**Comment by amrita-shrestha** [comment]
https://drone.owncloud.com/owncloud/ocis/36273/54/9

**Comment by SagarGi** [comment]
@S-Panta will investigate into it!

**Comment by S-Panta** [comment]
Locally, this seems to be flaky

**Comment by saw-jan** [comment]
The main problem was because of the server responding with `425` while downloading the GDPR report (UI button action). This happens only during e2e test.

**Comment by kobergj** [comment]
Mmh. This  is not supposed to happen. 
You mean the call to the `graph/v1.0/users/{userid}/exportPersonalData` returns a `425`?

**Comment by saw-jan** [comment]
> Mmh. This is not supposed to happen. You mean the call to the `graph/v1.0/users/{userid}/exportPersonalData` returns a `425`?

No, I mean the HEAD request `/.personal_data_export.json` to download the report file.
