### ISSUE TITLE
[QA] cleanup test feature file for `@skiponRevaMaster` tag

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#9451]
Currently, we bump oCIS test only on Reva-edge. In the drone config, skiponReva is used to skip those tests on edge. Therefore using the `@skiponrevamaster` tag is redundant since the tag isn't used in the edge branch. 

`reva edge drone config file:`
```yml
 "BEHAT_FILTER_TAGS": "~@toImplementOnOCIS&&~comments-app-required&&~@federation-app-required&&~@notifications-app-required&&~systemtags-app-required&&~@provisioning_api-app-required&&~@preview-extension-required&&~@local_storage&&~@skipOnOcis-OCIS-Storage&&~@skipOnGraph&&~@caldav&&~@carddav&&~@skipOnReva&&~@env-config",

```

**Comment by S-Panta** [comment]
@phil-davis  Can we clean this tag?

**Comment by phil-davis** [comment]
> @phil-davis Can we clean this tag?

Yes, it is old history. The current tests are aimed at the behavior of reva edge, and ocis. The behavior of reva master will be quite different. We have not been running on reva master for a long time, so we have no idea which scenarios would need this tag anyway.

Delete the tag.

**Comment by amrita-shrestha** [comment]
@S-Panta duplication of https://github.com/owncloud/ocis/issues/5337 so closing this issue
