### ISSUE TITLE
Add cli to remove versions

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#9472]
Follow up of https://github.com/owncloud/ocis/issues/9282

We want a cli command to delete all revisions on a storage provider. This is needed for user who use the new `DisableVersioning` feature and want to clean up their storage. (aka "delete all old versions of my files")

Acceptance criteria:
* glob all spaces
* delete all old revisions of files
* DO NOT TOUCH current the version of the files, only old revisions!
* include a `--dry-run` flag that doesn't actually delete the revisions but only prints what it would delete.

@rhafer @micbar @tbsbdr any more acceptance criteria?

**Comment by okrikos** [comment]
Would it be possible to add a flag for deleting all old revisions of one particular file? Is the new CLI command able to detect and purge orphan revisions of deleted files?

**Comment by kobergj** [comment]
> Would it be possible to add a flag for deleting all old revisions of one particular file? 

Not in the scope in of this ticket. This is about removing ALL revisions after disabling versioning. What is the usecase of this scenario?

>  orphan revisions of deleted files

Those should not exist. When a file is deleted the revision should be deleted as well. If this is not the case it is a bug.

To detect orphaned blobs/nodes or other inconsistencies, one should use the `ocis backup consistency` command. It currently does not have a delete flag, so deleting would need to be done manually. But such a flag could easily be added if there is a need for it.

**Comment by okrikos** [comment]
The primary motivation for this request is to get some control over the disc usage by spaces. Let’s take as an example one of my installations. Three spaces, each with the limit of 1GB, no personal folders. One space size is 395MB, the second 59MB and the last 41 MB = 485MB in total.  
`du -sh /home/ocis/.ocis/storage/users/spaces` gives 12G.
We need at least the very basic tool for removing old revisions in order not to run out of the disc space. Actually, I don’t want to disable versioning – my users love it.

**Comment by okrikos** [comment]
It’s perfect, thank you! What would be an appropriate way to get a file id, preferably via the web interface? Or could you display a file id with the `--dry-run` flag? 
Regarding a comprehensive solution, I think that setting up the max number of revisions doesn’t ensure that disk space is not overused. It was done just fine in  [https://doc.owncloud.com/webui/next/classic_ui/files/version_control.html](https://doc.owncloud.com/webui/next/classic_ui/files/version_control.html) and as an admin I really love this quote:

>  The version app never uses more that 50% of the user’s currently available free space.

**Comment by kobergj** [comment]
Unfortunately I cannot print the fileid with this command as I am missing essential information. It can be obtained through inspecting web requests (should be in every PROPFIND) or looking into the logs. Here is an example for one:
```
d419032c-65b9-4f4e-b1e4-0c69a946181d$44b5a63b-540c-4002-a674-0e9c833bbe49!e8a73d49-2e00-4322-9f34-9d7f178577b2
```
I am afraid there is no simpler way to acquire this information right now. This would need another feature request.


> Regarding a comprehensive solution, I think that setting up the max number of revisions doesn’t ensure that disk space is not overused. It was done just fine in https://doc.owncloud.com/webui/next/classic_ui/files/version_control.html and as an admin I really love this quote:

Please open a feature request for this, my paygrade is not hight enough to decide on such features ;)

> One space size is 395MB, the second 59MB and the last 41 MB = 485MB in total.
du -sh /home/ocis/.ocis/storage/users/spaces gives 12G.

This sounds a very large discrepancy. It would be interesting to know if `ocis backup consistency` shows any inconsistencies for those spaces, or if these 11.5G are really actual versions.

**Comment by kobergj** [comment]
> Unfortunately I cannot print the fileid with this command as I am missing essential information.

Scratch that. I found a way to print the fileid within the command. Will be visible when used with `-v` flag. Of course it also works when the fileid is copied from web.

I also added possibility to remove all versions on one space - just because it was easily doable.

**Comment by okrikos** [comment]
That is marvelous! Thank you very much!

> It would be interesting to know if ocis backup consistency shows any inconsistencies for those spaces 

I am afraid, it does not work for me right away:
```
# ocis backup consistency /home/ocis/.ocis/
No help topic for 'backup'
# ocis version
Version: 4.0.2
Compiled: 2023-10-06 00:00:00 +0000 UTC
```

> Please open a feature request for this

[https://github.com/owncloud/ocis/issues/9512](https://github.com/owncloud/ocis/issues/9512)

**Comment by kobergj** [comment]
> I am afraid, it does not work for me right away:

The backup consistency command needs ocis v5 at least.

Thanks for the feature request. I'll push it when I get a chance!
