### ISSUE TITLE
Password reset does not work with running ocis

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#9480]
The `ocis idm resetpassword`  command does not work when ocis is running. We need to move the functionality of the command to the idm service and just call an endpoint there. 

MAKE SURE THIS ENDPOINT CAN NOT BE CALLED BY THE PUBLIC.

cc @micbar

**Comment by micbar** [comment]
This limitation was already known.
I have no issues with that.

This is only relevant for the internal IDM, so that doesn' need to be "turing complete"

**Comment by kobergj** [comment]
That's PM for "wont fix"
