### ISSUE TITLE
fixed endpoint for app provider apps

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#9489]
# Description
The endpoint for app provider mimetype to app mappings gets announced via capabilities. This makes it unnecessarily complex in web to fetch the app provider listing and dynamically register the web-apps according to the listing. It would be far easier if it was a fixed endpoint (not announced by capability but a fixed route in the ocis proxy) which would return an empty list if no app provider apps are registered. Additionally it would be nice if the endpoint would work unauthenticated.

## User Stories

* > As a web ui developer, I want to have a fixed endpoint for the app provider listing, so that I can keep my app initialization as easy as possible.

## Value
DX for the web client

## Acceptance Criteria
- an endpoint that can be hardcoded in web (instead of looking it up in the capabilities)
- ideally unauthenticated if that's not a security concern
- returns an empty list if no app provider apps are configured server side

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by kulmann** [comment]
@micbar all 3 acceptance criteria are already fulfilled, correct? What about the third, returning an empty list if no app provider is set up at all, does that work as well?

**Comment by micbar** [comment]
Correct. It will always show up, can be accessed unauthenticated and returns an empty json body if apps are not or not yet available.

**Comment by kulmann** [comment]
Thank you! Then we can close here 😎
