### ISSUE TITLE
port conflict: consider changing default port 9200 

### ISSUE THREAD

**Issue by domdorn** [owncloud/ocis#9511]
9200 and 9300 is commonly used by elasticsearch, consider if changing the default port would be possible
so users will less-likely run into conflicts.

**Comment by micbar** [comment]
You can change that by config

**Comment by domdorn** [comment]
I know.. this is about the "out of the box experience"

**Comment by dragonchaser** [comment]
I do not see a real conflict here. Ocis is not supposed to run on that port in productive systems, but behind a reverse proxy like traefik or nginx which will result in remapping this port to 443 anyway. For evaluation purposes I think it is fine to run on 9200, if you evaluate a more complex setup changing the port to your likes should be done via config as @micbar mentioned.
