### ISSUE TITLE
[Needs discussion] Bump of rs/cors and resulting issues

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#9527]
Due to changes in rs/cors (https://github.com/rs/cors/commit/4c32059b2756926619f6bf70281b91be7b5dddb2#diff-bf80d8fbedf172fab9ba2604da7f7be972e48b2f78a8d0cd21619d5f93665895R367)  we have a security issue that would cause some fallout in **ALL** clients. This security issue is valid and the fix in rs/cors needed, but the acceptance-factor in the community and developers of projects attached should be zero.

The change requires all `Access-Control-Request-Headers` to be lower-case and in alphabetical order. 

We tried to enforce this in https://github.com/owncloud/ocis/pull/9518 but realized that his might break **ALL** clients (web, desktop...)

Can we come up with a roadmap how to implement this?

For now we suggest the following: 
- silence those security issues in the vulnerability scanner (go vuln-check) if possible
- merge all release relevant PRs to unblock us
- wait for clients to adapt the changes and then merge the remainders of #9518 

@TheOneRing @kulmann @micbar @dragotin can you please join the discussion on this since you are directly affected.

| Client | Affected |
|--------|--------|
| Web | unknown |
| Moodle integration | unknown  |
| Desktop client |unknown|

**Comment by dragonchaser** [comment]
Silencing is not possible, see: https://github.com/golang/go/issues/61211 we might have to disable the step in the pipeline.

**Comment by 2403905** [comment]
I noticed that after bumping the upload of the files became broken. We should keep an eye on it.

**Comment by butonic** [comment]
The bump just hurdens the parsing of malicious cors headers. Only browsers make preflight requests. So this does not affect any of our web, desktop or mobile developers. Just Merge.

**Comment by dragonchaser** [comment]
Closing not relevant to us.
