### ISSUE TITLE
OCM. sharing issues

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9534]
precondition: 

- run two ocis instances `ocis-server` and `federation-ocis-server` see here https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm

### test 1. users shares folder to federation users after receiver accepted invitation
`TEST_SERVER_URL="https://ocis-server:9200" TEST_SERVER_FED_URL="https://federation-ocis-server:10200" BEHAT_FEATURE="tests/acceptance/features/apiOcm/share.feature:12" make test-acceptance-api`
Steps: 
 ```
Given using server "LOCAL"
    And "Alice" has generated invitation
    And using server "REMOTE"
    And "Brian" has accepted invitation
    And using server "LOCAL"
    And user "Alice" has created folder "folderToShare"
    When user "Alice" sends the following resource share invitation using the Graph API:
      | resource        | folderToShare |
      | space           | Personal      |
      | sharee          | Brian         |
      | shareType       | user          |
      | permissionsRole | Viewer        |
    Then the HTTP status code should be "200"
    When using server "REMOTE"
    And user "Brian" lists the shares shared with him using the Graph API
    Then the HTTP status code should be "200"
    And the JSON data of the response should match
```

Actual: no share for Brian. Alice refresh page-> share disappears 

Uploading Screen Recording 2024-01-30 at 12.36.58.mov…

### test 2. users shares folder to federation users after accepting invitation
`TEST_SERVER_URL="https://ocis-server:9200" TEST_SERVER_FED_URL="https://federation-ocis-server:10200" BEHAT_FEATURE="tests/acceptance/features/apiOcm/share.feature:90" make test-acceptance-api`
Steps: 
```
Given using server "LOCAL"
    And "Alice" has generated invitation
    And using server "REMOTE"
    And "Brian" has accepted invitation
    And user "Brian" has created folder "folderToShare"
    When user "Brian" sends the following resource share invitation using the Graph API:
      | resource        | folderToShare |
      | space           | Personal      |
      | sharee          | Alice         |
      | shareType       | user          |
      | permissionsRole | Viewer        |
    Then the HTTP status code should be "200"
    When using server "LOCAL"
    And user "Alice" lists the shares shared with her using the Graph API
    Then the HTTP status code should be "200"
    And the JSON data of the response should match
```

Actual: 
<img width="2069" alt="Screenshot 2024-07-04 at 14 01 26" src="https://github.com/owncloud/ocis/assets/84779829/76911d58-15ed-4a4e-847b-4482e18e80c9">
1. federated share is not accepted by default
2. no displayName of the user sharer
3. how is the web supposed to determine that it's a federated resource? there's no type in the response. 
4. no `eTag` in the response - no clue maybe we don't need to.

CC @butonic @aduffeck

**Comment by micbar** [comment]
Needs #9554

**Comment by ScharfViktor** [comment]
checked again: 
1.  users shares folder to federation users after receiver accepted invitation  -  works fine 
2. users shares folder to federation users after accepting invitation - doesn't work 

user can share but after refreshing -> share disappears


https://github.com/user-attachments/assets/03811934-5431-4ee2-8cfd-5fa61e6d0afc

**Comment by ScharfViktor** [comment]
retest again after getting this fix https://github.com/cs3org/reva/pull/4840

Steps: 
- tom(ocis-server:9200) generate invitation
- alice(federation-ocis-server:10200) accepts invitation 
- alice(federation-ocis-server:10200) creates folder and shares to tom(ocis-server:9200) - works ✅️. after refresh page - works ✅️
- tom(ocis-server:9200) checks share with me - share exist ✅️. filter by shareType=external works ✅️
- tom(ocis-server:9200) creates folder and shares to alice(federation-ocis-server:10200)  - works ✅️. after refresh page - works ✅️
- alice(federation-ocis-server:10200) checks share with me - share doesn't exist - Fail

**Comment by micbar** [comment]
@ScharfViktor The last step `alice(federation-ocis-server:10200) checks share with me - share doesn't exist - Fail`

should work now.

**Comment by ScharfViktor** [comment]
> should work now.

yes I know, I want to change test today

**Comment by ScharfViktor** [comment]
Checked and closed as fixed
