### ISSUE TITLE
[QA] API test WebDav: unused stepDefinitions

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/ocis#9539]
```
WebDav.php
* @Then /^the downloaded content should be "([^"]*)" plus end-of-line$/
* @When user :user using password :password downloads the file :fileName using the WebDAV API
* @When the user downloads the file :fileName using the WebDAV API
* @Then the downloaded content should start with :start
* @Given the HTTP-Request-timeout is set to :seconds seconds
* @Given /^the user has moved (?:file|folder|entry) "([^"]*)" to "([^"]*)"$/
* @When user :user moves entry :source to :destination using the WebDAV API
* @When /^the user copies file "([^"]*)" to "([^"]*)" using the WebDAV API$/
* @Given /^the user has copied file "([^"]*)" to "([^"]*)"$/
```

Many step definitions in WebDav.php are unused in any scenarios. These are some of them and there are about 50 of them that are unused.
Investigate whether to keep the step definitions and add test coverage for it or remove them.

**Comment by prashant-gurung899** [comment]
I found these unused step defintions while working on these issues:
https://github.com/owncloud/ocis/issues/9345
https://github.com/owncloud/ocis/issues/9520

**Comment by phil-davis** [comment]
I looked through the full list of unused test steps. Many of them were used in UI test scenarios for the oC10 classic webUI.IN oC10 there were `Given` steps and `Then` steps to setup before webUI actions, and to check that the webUI action had done the expected thing on the server. Other steps are related to special "chunking" uploads, that are superseded by TUS on oCis, etc.

Please delete all the unused steps @prashant-gurung899

**Comment by prashant-gurung899** [comment]
@phil-davis  Yeah, i was also looking into oc10 and some of them were used on it.
Okay i will work on it and make a PR for it.

**Comment by prashant-gurung899** [comment]
This issue has been fixed by the following PRs:
For Given steps : https://github.com/owncloud/ocis/pull/9553
For When steps : https://github.com/owncloud/ocis/pull/9557
For Then steps : https://github.com/owncloud/ocis/pull/9564

So closing this issue.
