### ISSUE TITLE
[ocis] Update CS3 API to 1.0

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9554]
# Description

We are currently running on a  0.0.9 version of the CS3 Apis

To be able to make future changes, possibly in the scope of OCM, we need to bring reva edge up to use the `main` branch of the CS3 Apis.

The change we need to adapt is mainly this one https://github.com/cs3org/cs3apis/pull/215
## User Stories

* > As a developer, i want to use the lates API to unblock further changes

## Value

Unblock OCM improvements

## Acceptance Criteria

- [ ] Reva edge uses the lates CS3 API

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by rhafer** [comment]
This is the reva part: https://github.com/cs3org/reva/pull/4759

To get it running with ocis this is needed: https://github.com/owncloud/ocis/pull/9587
