### ISSUE TITLE
Trying to upload a file using `.` and drive root as destination fails with 500 error

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9568]
## Describe the bug
While trying to upload content to paths `.` and drive root, the server return `500 Internal Server Error`

## Steps to reproduce
```bash
curl -XPUT "https://localhost:9200/remote.php/dav/spaces/<drive-id>" -d"lorem" -uadmin:admin -vk
curl -XPUT "https://localhost:9200/remote.php/dav/spaces/<drive-id>/." -d"lorem" -uadmin:admin -vk
```
```bash
< HTTP/1.1 500 Internal Server Error
```

## Expected behavior
`405` or `400`?

## Actual behavior
500 Internal Server Error

**Comment by 2403905** [comment]
TODO: Cleanup the expected failures in a reva  https://github.com/cs3org/reva/pull/4768/files#diff-d06f0265b57142c2bbad97953c887323699f80e366ee85ea9173c241345c1d41

**Comment by phil-davis** [comment]
> Cleanup the expected failures in reva

That should happen when the next ocis test commit id bump happens to reva (PR like https://github.com/cs3org/reva/pull/4770 )

@saw-jan @Salipa-Gurung it would be nice to get someone to do the commit id bump in reva, since there are expected-failures that should be able to be removed.

**Comment by 2403905** [comment]
https://github.com/cs3org/reva/pull/4773

**Comment by phil-davis** [comment]
https://github.com/cs3org/reva/pull/4773 passed and merged.
