### ISSUE TITLE
OCM. generation invitation doesn't send email

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9583]
precondition: 

- run two ocis instances `ocis-server` and `federation-ocis-server` see here https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm

how to run ocis with inbucket: 
- set up inbucket docker run -d -p9000:9000 -p2500:2500 --name inbucket inbucket/inbucket
- run ocis with this envs: `OCIS_ADD_RUN_SERVICES=notifications NOTIFICATIONS_SMTP_HOST=localhost NOTIFICATIONS_SMTP_PORT=2500 NOTIFICATIONS_SMTP_INSECURE=true NOTIFICATIONS_SMTP_SENDER="owncloud <noreply@example.com>"`
- inbucket should be available on http://localhost:9000

Steps: 
- user `admin` generates invitation with description and inviteUser email

Expected: email sent
Actual: email not sent

https://github.com/owncloud/ocis/assets/84779829/5960c2c9-bac9-4501-9a47-f70f8a7f284f

**Comment by 2403905** [comment]
@micbar @kobergj It is a new event type. Should it be a bug or an enhancement?

**Comment by kobergj** [comment]
`enhancement`. Afaik email notification where not part of latest ocm improvements.

**Comment by ScharfViktor** [comment]
tested. works fine 👍 

<img width="949" alt="image" src="https://github.com/user-attachments/assets/3af3ad45-2fd7-4fbd-9f98-00d249273317">
