### ISSUE TITLE
Missing Securely Viewable permission in the REPORT response 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9607]
related https://github.com/owncloud/ocis/issues/9608

we have `X: Securely Viewable` in the webdav https://owncloud.dev/apis/http/webdav/#supported-webdav-properties
but` REPORT` response doesn't contain this permission

Steps: 

- admin shares `file/folder with files` with secure view role
- recipient searches shared file

Expected: 
<oc:permissions>SM</oc:permissions> contains `X`

Actual: 
REPORT doesn't contain `X`

<img width="1253" alt="Screenshot 2024-07-15 at 16 21 10" src="https://github.com/user-attachments/assets/8204d943-1721-4dd6-859e-7695a0fd86fe">

`PROPFIND` works correct
<img width="1431" alt="Screenshot 2024-07-15 at 16 22 41" src="https://github.com/user-attachments/assets/31527ee0-fe63-4c6d-92d0-c7c4ab82db71">

**Comment by micbar** [comment]
@butonic @aduffeck @kobergj 

It seems to be a big problem, that the ocdav and search WebDAV implementations are split up 🙈

**Comment by ScharfViktor** [comment]
-[ ] TODO - add contract test for `secure view` role

**Comment by AlexAndBear** [comment]
Will probably fix: https://github.com/owncloud/ocis/issues/9608
