### ISSUE TITLE
Proxy service readme - autoprovisioning - unclear text

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9613]
There are two statements in the proxy readme in section `Automatic User and Group Provisioning` that sound contradictionary and need clarification. This was found by @kobergj reading the [admin docs PR](https://github.com/owncloud/docs-ocis/pull/912).

**This is a copy/paste of the finding:**

> you must ensure that the user's email address or username never changes.

Later you state:

> If the user does already exist, the proxy will check if the user's email or displayname has changed and updates those accordingly via `graph` service.

So what is it now? Do I need to take care the email never changes or will it be updated automatically?
...

Also read additional comments in the referenced admin docs PR.

@rhafer @micbar pls help sorting this out

**Comment by phil-davis** [comment]
I made a comment here https://github.com/owncloud/docs-ocis/pull/912#discussion_r1678915286
which might help or confuse the discussion.

**Comment by rhafer** [comment]
> I made a comment here [owncloud/docs-ocis#912 (comment)](https://github.com/owncloud/docs-ocis/pull/912#discussion_r1678915286) which might help or confuse the discussion.

Your comment is exactly right. I'll try to come of with some additional working to clarify in the README
