### ISSUE TITLE
Basepath of decomposeddf of trashbin command doesn't match with other cli command base path 

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#9615]
## Describe the bug
`ocis trash purge-empty-dirs --help` gives information on the path to be provided to the command. The help shows that basepath should be `(e.g. /var/tmp/ocis/storage/users)`
However, providing this path throws an error message of path not found because of https://github.com/owncloud/ocis/blob/d98a05d2df67ca5308d12d980d8f45a3d7343ffe/ocis/pkg/trash/trash.go#L10-L25

What should be the proper basepath?

**Comment by S-Panta** [comment]
@dragonchaser

**Comment by kobergj** [comment]
Correct path is something like `/var/tmp/ocis` without the `storage/users`. I'll file a docu fix
