### ISSUE TITLE
The users can't see more than the 10 shares 

### ISSUE THREAD

**Issue by 2403905** [owncloud/ocis#9642]
## Steps to reproduce
1. `admin` created 11 folders.
2. `admin` shared 11 folders to `moss`
3. `moss` opened https://{ocis}/files/shares

## Expected behavior
The users can see the list of the shares. 

## Actual behavior
The users can't see more than the 10 shares. The `graph/v1beta1/me/drive/sharedWithMe` request takes forever.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

https://ocis.ocis.rolling.owncloud.works/

ocis version  6.1.0
Web client version 9.1.0

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

## Additional context

<img width="2559" alt="Screenshot 2024-07-18 at 11 35 30" src="https://github.com/user-attachments/assets/a0bbca22-240e-4f7d-aa60-88ba75e47b5c">
<img width="2560" alt="Screenshot 2024-07-18 at 11 35 05" src="https://github.com/user-attachments/assets/2e82a4cb-8b01-4184-913d-98b58de9949c">

**Comment by ScharfViktor** [comment]
relevant for `ocis` v.6 where we use sharingNG `graph/v1beta1/me/drive/sharedWithMe`
I checked `ocis:5.0.6` - this error is not present because we use `ocs` endpoind

**Comment by micbar** [comment]
I am very curious how we managed to create this bug 😸

**Comment by butonic** [comment]
we did not initialize a buffered channel:
```
diff --git a/services/graph/pkg/service/v0/utils.go b/services/graph/pkg/service/v0/utils.go
index 62c2d362f1..5db86e2152 100644
--- a/services/graph/pkg/service/v0/utils.go
+++ b/services/graph/pkg/service/v0/utils.go
@@ -145,7 +145,6 @@ func cs3ReceivedSharesToDriveItems(ctx context.Context,
        identityCache identity.IdentityCache,
        receivedShares []*collaboration.ReceivedShare) ([]libregraph.DriveItem, error) {
 
-       ch := make(chan libregraph.DriveItem)
        group := new(errgroup.Group)
        // Set max concurrency
        group.SetLimit(10)
@@ -160,6 +159,7 @@ func cs3ReceivedSharesToDriveItems(ctx context.Context,
                receivedSharesByResourceID[rIDStr] = append(receivedSharesByResourceID[rIDStr], receivedShare)
        }
 
+       ch := make(chan libregraph.DriveItem, len(receivedSharesByResourceID))
        for _, receivedSharesForResource := range receivedSharesByResourceID {
                receivedShares := receivedSharesForResource
 
```

currently, the unbuffered channel blocks when trying to write a driveItem into it because no one is reading from it. See [Go by Example: Channel Buffering](https://gobyexample.com/channel-buffering)
> By default channels are unbuffered, meaning that they will only accept sends (chan <-) if there is a corresponding receive (<- chan) ready to receive the sent value. Buffered channels accept a limited number of values without a corresponding receiver for those values.
