### ISSUE TITLE
Mtime send in the `Upload-Metadata` header when uploading via TUS not used

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#965]
use phoenix to upload a file that is a couple of days old or run the tests from: https://github.com/owncloud/core/pull/38148

the modification time will always end up to be "now"

owncloud-storage handles that case correctly.

mtime is read in
https://github.com/cs3org/reva/blob/57da0c27434c6308dd4dda1d379867dc4f5b3f6a/pkg/storage/fs/ocis/upload.go#L125

but looks like its not used anymore after that

**Comment by individual-it** [comment]
- [ ]  todo QA-Team: make API tests to check the deletion time.
      It's reported in the `oc:trashbin-delete-datetime` field when doing a PROPFIND on the trashbin endpoint. e.g.: `curl 'http://localhost/owncloud-core/remote.php/dav/trash-bin/admin/' -uadmin:admin -X PROPFIND -d'<?xml version="1.0"?><d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"> <d:prop><oc:trashbin-original-filename /><oc:trashbin-original-location /><oc:trashbin-delete-datetime /><d:getcontentlength /> <d:resourcetype /></d:prop></d:propfind>'`

**Comment by butonic** [comment]
related: https://github.com/owncloud/ocis-reva/issues/174

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
