### ISSUE TITLE
Remove accounts service locking

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#966]
The accounts service locks on every request. This can ba a bottleneck in situation with lots of load.
Plan is it to investigate some time why this happened in the past and move locking to the responsible storage implementations.

history: https://github.com/owncloud/ocis-accounts/pull/82

**Comment by refs** [comment]
adding a `help-wanted` label since it needs to be brought up in the near future in order not to shoot ourselves in the foot.

**Comment by fschade** [comment]
I already started to optimize, but haven’t found the time to finalize it. It can be found here: https://github.com/owncloud/ocis/commit/80004589df5ccb14553b814f98a1fedf913b163e

**Comment by fschade** [comment]
@refs , PR is done, after ci is green we can merge it

**Comment by fschade** [comment]
@refs , merged. Thanks for your support
