### ISSUE TITLE
Activities. Wrong activity log when public changes file content

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9676]
Steps: 

1. admin creates a public link for a file with edit permissions
2. public or authorized user opens file and edits content
3. admin sees activities
 
Expected: something like: public added content or `einstein` added `forPublic.odt` using public link

Actual: `admin added forPublic.odt to Admin` - wrong activity log. It was public (not admin)

https://github.com/user-attachments/assets/647293db-8785-4f52-8275-126bddeeb841

**Comment by kobergj** [comment]
@ScharfViktor I can't reproduce this. What I see is `DeletedUser added forPublic.odt to Admin`.

The `DeletedUser` string comes from the backend (hardcoded). I could change that to `Anonymous` that would fit both deleted and public case.

Or do we need a more advanced logic for that?

**Comment by ScharfViktor** [comment]
> @ScharfViktor I can't reproduce this. What I see is `DeletedUser added forPublic.odt to Admin`.

re-tested. is still reproducing: 
<img width="305" alt="image" src="https://github.com/user-attachments/assets/da61a571-5f49-422a-a6bc-fb0676178ba2">

`admin` instead of `public`

**Comment by kobergj** [comment]
It's different in personal and project spaces. I'll check why.
