### ISSUE TITLE
PROPFIND on a file uploaded by share receiver is not possible

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#968]
1. create a folder
1. share the folder
1. as receiver upload a file into the folder
1. as sharer make a PROPFIND on that file
    `curl -XPROPFIND https://localhost:9200/remote.php/dav/files/Einstein/folder/fromreceiver -ueinstein:relativity -k`

Result: HTTP 207, but empty body

works on owncloud storage and also if the file is uploaded by the sharer

**Comment by individual-it** [comment]
related / duplicate of #763 ?

**Comment by C0rby** [comment]
https://github.com/cs3org/reva/pull/1346 seems to fix this.
See unexpected passed tests: https://cloud.drone.io/cs3org/reva/3250/13/6

**Comment by C0rby** [comment]
Okay nevermind... now they are listed in the unexpected failed list...

**Comment by phil-davis** [comment]
Those TUS tests were only just added today. There will be a cross-over of PRs, rebase needed.

**Comment by micbar** [comment]
fixed by reva update in #2230

**Comment by individual-it** [comment]
manually retested and it work, closing the issue
