### ISSUE TITLE
Cannot download shortcut on windows os

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9680]
ocis: `6.1.0+6c82a6560`
web: `9.2.0-alpha.1`

Steps: 
- create a shortcut to a file or external site
- try to download the shortcut using: 

1. Widows os: 

Actual: not possible to download file
![Bild](https://github.com/user-attachments/assets/fd749737-7258-4a09-84a7-ddba56bdc820)

Expected: 

2. Mac Os - firefox browser 128.0.2 (64-bit)

Actual: file is downloaded as: 
<img width="751" alt="Screenshot 2024-07-23 at 16 45 44" src="https://github.com/user-attachments/assets/1627c3f8-d73c-4b68-9f46-24b60dec08c4">

`.download` is at the end - it is impossible to open the shortcut (the shortcut can be opened only after deleting `.download`) 

Expected:

**Comment by hodyroff** [comment]
Chrome on Windows worked like a charm.
Edge blocked the download ... 
It seems different  end user apps make different decisions ...

**Comment by AlexAndBear** [comment]
```
File Type Recognition: Firefox may not recognize .url as a standard file type and might append .download to ensure it doesn't execute or open in an unexpected manner.
```

Based on browser, user system, preferences (smartScreen on Windows) and so on, nothing that is wrong on our side, just security stuff

**Comment by ScharfViktor** [comment]
that means we can close this issue. Please reopen if you think it's relevant
