### ISSUE TITLE
[QA] API tests for `/app/` endpoints

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9682]
:exclamation: Pre-requisites:
~- setup collaboration service with Collabora and OnlyOffice~
- [x] setup FakeOffice (should be sufficient) #9885

API tests for endpoints:
- POST: `/app/open?file_id={file_id}`
  - [x] query: `app_name=FakeOffice` - e.g: `/app/open?file_id={file_id}&app_name=FakeOffice`
  - [x] text file https://github.com/owncloud/ocis/pull/9911
  - [x] `.odt` file https://github.com/owncloud/ocis/pull/9885
  - [x] shared `.odt` file https://github.com/owncloud/ocis/pull/9922
  - [x] public link `.odt` file https://github.com/owncloud/ocis/pull/9912
  - [x] Different `&view_mode=[view|read|write]` https://github.com/owncloud/ocis/pull/9954
- POST: `/app/open-with-web?file_id={fileid}` @anon-pradip 
  - [x] query: `app_name=FakeOffice` - e.g: `/app/open-with-web?file_id={fileid}&app_name=FakeOffice`
  - [x] text file https://github.com/owncloud/ocis/pull/9939
  - [x] `.odt` file https://github.com/owncloud/ocis/pull/9931
  - [x] shared `.odt` file https://github.com/owncloud/ocis/pull/9941
  - [x] public link `.odt` file https://github.com/owncloud/ocis/pull/9968
  - [x] Different `&view_mode=[view|read|write]` https://github.com/owncloud/ocis/pull/9969
- POST: `/app/new?parent_container_id={parent_folder_id}&filename={filename}` @PrajwolAmatya 
  - [x] create text file https://github.com/owncloud/ocis/pull/9960
  - [x] create `.odt` file https://github.com/owncloud/ocis/pull/9964
  - [x] create `.odt` file in a share received folder https://github.com/owncloud/ocis/pull/9967
  - [x] create `.odt` file in public link folder https://github.com/owncloud/ocis/pull/9978
  - [x] create `.odt` file in public link space (https://github.com/owncloud/ocis/issues/8691) https://github.com/owncloud/ocis/pull/9983
  - [x] create `.odt` file inside deleted parent folder https://github.com/owncloud/ocis/pull/10064
- Edge cases:
  - [x] request `/app/open` without `app_name` query for a text file
    - https://github.com/owncloud/ocis/pull/9911
  - [x] request with unsupported file format
    - https://github.com/owncloud/ocis/pull/9945
    - https://github.com/owncloud/ocis/pull/9984
  - [x] request with non-existing file-id or deleted file
    - https://github.com/owncloud/ocis/pull/9953
    - https://github.com/owncloud/ocis/pull/9985

Bug Reports:
- https://github.com/owncloud/ocis/issues/9495
- https://github.com/owncloud/ocis/issues/9928

**Comment by PrajwolAmatya** [comment]
All the test coverage has been covered, so closing this issue as done.
