### ISSUE TITLE
[oCIS] New Sharing Role "Editor without versions"

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9699]
# Description

Create A new Unified Sharing Role "Editor without Versions".

## Epic

[#6794](https://github.com/owncloud/enterprise/issues/6794)

## User Stories

* > As a user, I want to decide to not share the history of a resource to keep unfinished / private content for myself.

## Value

- Compliance
- Control over your Data

## Acceptance Criteria

- [ ] We have a Role "Editor without Versions" which can be used on files and folders in the personal space
- [ ] The new Editor role is not enabled by default
- [ ] The new Editor role is enabled in the CI

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by 2403905** [comment]
@tbsbdr  It needs to be clarified. The `editor` role doesn't have version permissions.  The `space editor` has. 
So, we should add a new role `space editor without versions`, correct?

**Comment by 2403905** [comment]
>  The new Editor role is not enabled by default
How should we manage it, via an env variable?

**Comment by tbsbdr** [comment]
1) yes, correct
2) could be okay, but more up to you. most important is, that the role is somehow included in ci
3) `Space editor` and Space `editor without versions` will co-exist

**Comment by 2403905** [comment]
Waiting for related PR https://github.com/owncloud/ocis/pull/9727

**Comment by fschade** [comment]
@2403905 https://github.com/owncloud/ocis/pull/9727 is merged, happy coding:)
