### ISSUE TITLE
[oCIS] Add Transparent Sharing Roles for the Personal Space

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9701]
# Description

The sharing from a personal space and from individual files / folders currently does not give the permission "ListGrants"

We will add a new set of Roles which all have the permission "List Grants"

## Epic

https://github.com/owncloud/enterprise/issues/6795

## User Stories

* > As an admin, I want to control which permissions are avaiable to enforce sharing rules

## Value
- Compliance
- Transparency

## Acceptance Criteria

- [ ] Added Role "Editor" with condition "File/ Folder" and "ListGrants" Permission
- [ ] Added Role "Viewer" with confition "File/Folder" and "ListGrants" Permission
- [ ] These roles should not be enabled by default

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by 2403905** [comment]
@micbar @tbsbdr Should the existing roles `Editor` - new `Editor` and `Viewer` - new `Viewer` be mutually exclusive or can they be enabled simultaneously?

**Comment by micbar** [comment]
Can be enabled simultaneously.
