### ISSUE TITLE
OCM. Identify federated users

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9702]
precondition: 

- run two ocis instances `ocis-server` and `federation-ocis-server` see here https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm

Steps: 
- create federation connection between `admin`(ocis-server) and `marie`(federation-ocis-server)
- admin searches users by `mar` in the Share with people dialog

Actual: admin gets two marie users. but we cannot identify which one is the federated user
![Screenshot 2024-07-11 at 10 58 21](https://github.com/owncloud/web/assets/84779829/24c0750b-6def-4903-b141-07867660fd30)

Expected: federated user has different icon

**Comment by butonic** [comment]
@rhafer will add 'Federated' (OCM user, has no password and cannot login, only serves as a reference for shares) the `userType` property of a user, in addition to `Member` (of the instance) and `Guest` (invited by invites service).

**Comment by rhafer** [comment]
I created https://github.com/owncloud/libre-graph-api/pull/190 to document the new usertype `Federated`.

**Comment by JammingBen** [comment]
Is there something left to do here, other than the correlating web issue https://github.com/owncloud/web/issues/11361?

**Comment by rhafer** [comment]
@JammingBen I don't think so. So I guess this can be closed.
