### ISSUE TITLE
Feature: Sharing - "Return shared File" 

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#972]
To strengthen the collaboration over ownCloud I could envision the following feature:

User Marie shares a file with me and asks for review. Her share appears in my  "My Shares" directory. I want to review it for her and maybe have some changes.

A few basic things could enable this very basic workflow: 

- Marie could write a short _comment_ when she shares the file that becomes visible to me in my Shares folder
- I download her file and do some changes. Now I want to return my work to her. For that, an additional menu item "Return shared File" appears in my UI. It allows me to upload the changed file, again allowing me to give a short comment. 
- Maries original file would be overwritten by mine but of course kept in the versioning system.
- Marie can see in her web client that she got a file reply and my comment.
- For file types which support useful diffs a diff could be displayed.
- Marie has an easy way to revert to her original version

**Comment by dragotin** [comment]
I realize that this works today: One can, given the right permissions, overwrite the same shared file. But my believe is that people are hesitant to do that. The normal workflow is: Download the file, change it, save it with some strange postfix (ie. new version, name or date) and send back, so that initial owner has both files. However that is pretty difficult with the current implementation because the receiver has to overwrite the original filename, or create a new share for Marie, which looses the connect to the previous version.

**Comment by refs** [comment]
@dragotin is it worth bringing this into someone else's attention? I also don't see a JIRA label here, perhaps is not connected with JIRA, and it makes discoverability suboptimal :)

**Comment by kobergj** [comment]
I will just close this as a similar workflow is now possible (without comments). Needs a new ticket if this should still be implemented.
