### ISSUE TITLE
OCM. Admin Settings > Users: indicate which account is a federated account ++ remove actions from users.

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#9747]
- [x] api changes to indicate user type tracked in https://github.com/owncloud/ocis/issues/9702
- [ ] web also needs changes https://github.com/owncloud/web/issues/11361

**Comment by butonic** [comment]
@JammingBen @fschade can you elaborate on the web progress?

**Comment by JammingBen** [comment]
There are 2 Web PRs:

* https://github.com/owncloud/web/pull/11357
* https://github.com/owncloud/web/pull/11351

The first PR is a prerequisite for the second (main) one and just needs a review. The second one is almost done, I still need to add the filter query once the first PR is merged.
