### ISSUE TITLE
COPY file/folder to share mountpoint: inconsistent behavior between dav paths

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9753]
### 1. File to shared File
`old/new/spaces` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/webdav/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/webdav/Shares/admin-lorem.txt" \
-udemo:demo -vk

curl -XCOPY "https://localhost:9200/remote.php/dav/files/demo/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/dav/files/demo/Shares/admin-lorem.txt" \
-udemo:demo -vk

curl -XCOPY "https://localhost:9200/remote.php/dav/spaces/{demo-space-id}/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/dav/spaces/{shares-space-id}/admin-lorem.txt" \
-udemo:demo -vk
```

- `< HTTP/1.1 204 No Content` :exclamation:
- share is not deleted :heavy_check_mark: 
- share mountpoint is not lost :heavy_check_mark: 

### 2. File to shared Folder
`old/new` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/webdav/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/webdav/Shares/admin-folder" \
-udemo:demo -vk

curl -XCOPY "https://localhost:9200/remote.php/dav/files/demo/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/dav/files/demo/Shares/admin-folder" \
-udemo:demo -vk
```
- `< HTTP/1.1 400 Bad Request` :heavy_check_mark:
- share is not deleted :heavy_check_mark: 
- share mountpoint is not lost :heavy_check_mark: 

`spaces` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/dav/spaces/{demo-space-id}/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/dav/spaces/{shares-space-id}/admin-folder" \
-udemo:demo -vk
```

- `< HTTP/1.1 412 Precondition Failed` :question:
- share is deleted :exclamation: 
- share mountpoint is lost :exclamation: 

### 3. Folder to shared File
`old/new` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/webdav/demo-folder" \       
-H"Destination: https://localhost:9200/remote.php/webdav/Shares/admin-lorem.txt" \
-udemo:demo -vk

curl -XCOPY "https://localhost:9200/remote.php/dav/files/demo/demo-folder" \       
-H"Destination: https://localhost:9200/remote.php/dav/files/demo/Shares/admin-lorem.txt" \
-udemo:demo -vk
```
- `< HTTP/1.1 400 Bad Request` :heavy_check_mark:
- share is not deleted :heavy_check_mark: 
- share mountpoint is not lost :heavy_check_mark: 

`spaces` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/dav/spaces/{demo-space-id}/demo-folder" \       
-H"Destination: https://localhost:9200/remote.php/dav/spaces/{shares-space-id}/admin-lorem.txt" \
-udemo:demo -vk
```

- `< HTTP/1.1 403 Forbidden` :question:
- share is not deleted :heavy_check_mark: 
- share mountpoint is not lost :heavy_check_mark:

### 4. Folder to shared Folder
`old/new` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/webdav/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/webdav/Shares/admin-folder" \
-udemo:demo -vk

curl -XCOPY "https://localhost:9200/remote.php/dav/files/demo/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/dav/files/demo/Shares/admin-folder" \
-udemo:demo -vk
```
- `< HTTP/1.1 400 Bad Request` :heavy_check_mark:
- share is not deleted :heavy_check_mark: 
- share mountpoint is not lost :heavy_check_mark:

`spaces` dav path:
```bash
curl -XCOPY "https://localhost:9200/remote.php/dav/spaces/{demo-space-id}/demo-lorem.txt" \       
-H"Destination: https://localhost:9200/remote.php/dav/spaces/{shares-space-id}/admin-folder" \
-udemo:demo -vk
```

- `< HTTP/1.1 204 No Content` :question:
- share is deleted :exclamation:  
- share mountpoint is lost :exclamation:

**Comment by saw-jan** [comment]
Recent partial fix: https://github.com/cs3org/reva/pull/4785

Related issues:
- https://github.com/owncloud/ocis/issues/6999
- https://github.com/owncloud/ocis/issues/3874

**Comment by saw-jan** [comment]
CC @kobergj

**Comment by kobergj** [comment]
@saw-jan Case 1 (File to shared File) is a special case. The `204 No Content` is correct here, as it will just create a new version for the existing file. This is expected and wanted behaviour. 

All other cases we block. The fix comes with this reva PR: https://github.com/cs3org/reva/pull/4802
