### ISSUE TITLE
Listing permissions for disabled spaces not possible

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#9764]
## Describe the bug
Listing permissions for disabled spaces is not possible and returns a 404 error.

## Steps to reproduce
1. Create a new space
2. Disable the space
3. List its permissions (e.g. `https://host.docker.internal:9200/graph/v1beta1/drives/309ae7c7-2db4-4c08-8e7c-d272086aa607%24449cb542-3d80-4ef5-9d94-12ef5444adac/root/permissions`)

## Expected behavior
The permissions are being listed despite the space being disabled. I believe this was the behavior pre sharing NG.

## Actual behavior
The server responds with a 404 error.

**Comment by kobergj** [comment]
Are you sure this was the behaviour before. There corresponding code path seems much older than sharing NG: https://github.com/cs3org/reva/blob/edge/pkg/storage/utils/decomposedfs/node/node.go#L290-L291

If we allow listing permissions for disabled spaces, should we also allow changing them? As of now disabled spaces cannot be edited in any way (save restore)

**Comment by JammingBen** [comment]
Pre Sharing NG you were able to list space members of disabled spaces (although not change them):

<img width="441" alt="image" src="https://github.com/user-attachments/assets/07453a3d-10c7-4da8-b045-499fc764a305">

**Comment by kobergj** [comment]
Yes. But that information is included in the GET drive call. You don't need to call permissions endpoint for this. Are you sure web called this before?

**Comment by JammingBen** [comment]
Ahh now I get it, you're right. The old ocm `/shares` endpoint didn't return any space members, no matter if the space was enabled or disabled. We always got this information via the drive itself and then querying each and every user/group (ouch). With sharing NG though, we're using the `/permissions` endpoint.

So before jumping into any kind of implementation or fix, I'd raise the question if it is necessary for as disabled space to display its members. Might be a little tricky, but definitely possible. @tbsbdr What do you think?

**Comment by tbsbdr** [comment]
As long as one can see the managers in den details panel, I'd not require to see all other space members. if someone needs it, we can discuss again. until then, lets not implement it an focus on more important features.
i.e. we could remove the members panel.

**Comment by JammingBen** [comment]
Ok thanks, then I'll close here since there is nothing for the server to do.
