### ISSUE TITLE
Docker hub production: latest does not point to the currently latest release but an older one

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9792]
When looking on https://hub.docker.com/r/owncloud/ocis/tags (production) you will find `latest` and (currently) `5.0.6`

We have a nasty mismatch:
* `latest` points to a release that is `Last pushed 2 months ago` and 
* `5.0.6` points to a release that is `Last pushed a month ago`

Note, compared to rolling, where we have `latest` and `6.2.0` telling: `Last pushed 14 days ago`.

This impacts downloading the correct production container when using e.g. the ocis full deployment example using the `latest` tag.

In addition, when fixing this, to make it clear from the entry text on docker hub, we should print:
`Docker images for ocis production` and `Docker images for ocis rolling`.

@tbsbdr fyi, as discussed

**Comment by KillerTic** [comment]
It seems, that the latest tag now is completly gone from Docker Hub.
Also my version in OCIS (5.1.0) shows a release, which I can not find anywhere.

The 6.0 releases are also not on Docker Hub.

**Comment by micbar** [comment]
The stable has currently no latest tag. Please use version 5.0.6. With the upcoming 5.0.7 we will have a new latest pointer.


Please note: rolling releases are a different docker image. Please use owncloud/ocis-rolling for that channel. Currently on 6.3.0.

**Comment by micbar** [comment]
Small Note: it is best practise in Production environments to not use the latest tag but a pinned version 😇.

**Comment by KillerTic** [comment]
Looking forward to have latest tag back.
Yes got some core services pinned, but most are on latest, but I do my updates manually :)

**Comment by micbar** [comment]
Fixed by #9963
