### ISSUE TITLE
graph/v1.0/drives/{drive-id}/root returns 404

### ISSUE THREAD

**Issue by blicknix** [owncloud/ocis#9799]
## Describe the bug
I try to build a tool to provision spaces from a csv. And while I'm able to create spaces via api, I always get a 404 if I try to access any drives.root calls.

I'm using the owncloud.dev and https://owncloud.dev/libre-graph-api/api/openapi-spec/v1.0.yaml resources.

## Steps to reproduce
1. Create a space via api
2. Get ID of the space
3. Call the graph/v1.0/drives/{drive_id}/root api call

## Expected behavior
I should be able to access the api without any errors.

## Actual behavior
The API call gives me the status code 404

## Setup
OCIS is running in kubernetes, deployed with the helmchart.

<details>
<p>

```console
ownCloud	Infinite Scale
Edition	Community
Version	5.0.6
Web client version	8.0.4
```

</p>
</details>

## Additional context

```python
#This one has no issue
r = requests.get('https://xxx/graph/v1.0/drives/{drive_id}', headers=headersAPI)

#This one returns a 404
r = requests.get('https://xxx/graph/v1.0/drives/{drive_id}/root', headers=headersAPI) 
```

**Comment by kobergj** [comment]
I checked and `graph/v1.0/drives/{drive_id}/root` is not implemented. API specs are wrong. We do however offer the other `root/...` endpoints: 
`graph/v1.0/drives/{drive_id}/root/children`
`graph/v1.0/drives/{drive_id}/root/invite`
`graph/v1.0/drives/{drive_id}/root/createLink`
`graph/v1.0/drives/{drive_id}/root/permissions`

**Comment by rhafer** [comment]
> `graph/v1.0/drives/{drive_id}/root/children`
> `graph/v1.0/drives/{drive_id}/root/invite`
> `graph/v1.0/drives/{drive_id}/root/createLink`
> `graph/v1.0/drives/{drive_id}/root/permissions`

Please not that those are on the `v1beta` routes. So the correct paths for those is `graph/v1beta1/drives/{drive_id}/root/...`

**Comment by rhafer** [comment]
@blicknix which release are you on? And what exactly do you need to achieve?

**Comment by blicknix** [comment]
OCIS 5.0.6
I have to add users to spaces via api or any other way that is not manually

**Comment by blicknix** [comment]
It seems that the functions are not implemented with the major [version 5](https://github.com/owncloud/ocis/blob/v5.0.6/services/graph/pkg/service/v0/service.go#L217).

@rhafer Is there any other way to do that?

**Comment by blicknix** [comment]
Found a workaround with the snippet.
```
r = requests.post('https://xxx/ocs/v1.php/apps/files_sharing/api/v1/shares?shareType=7&shareWith=jwalker&space_ref={client_id}&permissions=1&role=manager', headers=headersAPI)
```

**Comment by rhafer** [comment]
@blicknix Yeah, that's true. Full support for setting permissions on spaces via the graph API is only available in  the 6.x releases.
