### ISSUE TITLE
ocis full deployment example WOPISERVER_DOMAIN(s)

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9810]
In the deployment example valid for v5, we only have one `WOPISERVER_DOMAIN` valid for both office products which are onlyoffice and collabora.

With v6 (rolling) we now have:
* `WOPISERVER_DOMAIN` which is valid for collabora only, see the collabora.yml file
* `WOPISERVER_ONLYOFFICE_DOMAIN` which is valid for onlyoffice only, see the onlyoffice.yml file.

Q1: is there a particular reason splitting that up?
Q2: what is planned when integrating office 365? (see PR: #9686) will there be an additional envvar in `.env`?

The background of the question is, that we have deployment examples in the admin docs where we need do document if wopiserver domains need to be considered in the setup when using valid certificates with letsencrypt.

@micbar 
@tbsbdr fyi

**Comment by micbar** [comment]
Please wait after my vacation

**Comment by micbar** [comment]
Simple explanation: The collaboration service needs a wopiserver domain for every single web office.
