### ISSUE TITLE
OCIS CLI command not respecting OCIS_CONFIG_DIR

### ISSUE THREAD

**Issue by BEBU88** [owncloud/ocis#9835]
## Describe the bug
ocis CLI command is looking for the ocis.yaml in /root/.ocis/config although OCIS_CONFIG_DIR is set to other destination
## Steps to reproduce
1. Try to run ocis maintenance command in terminal e.g. ocis storage-users uploads sessions 

## Expected behavior
List existing upload sessions

## Actual behavior
This error appears:

The jwt_secret has not been set properly in your config for storage-users. Make sure your /root/.ocis/config config contains the proper values (e.g. by running ocis init or setting it manually in the config/corresponding environment variable).

## Setup
Version: 6.2.0

ocis is running on debian as systemd service. The EnvironmentFile is set in the systemd service file. The OCIS_CONFIG_DIR is set to /etc/ocis

**Comment by jvillafanez** [comment]
It works for me?
Could you try to run something like `OCIS_CONFIG_DIR=/etc/ocis/ ocis storage-users uploads sessions`? You might not be picking the right environment; I mean, you might have set it up for systemd but not for regular users.

**Comment by mmattel** [comment]
> I mean, you might have set it up for systemd but not for regular users.

A very good point I will consider for the [admin documentation](https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html) !

**Comment by BEBU88** [comment]
> It works for me? Could you try to run something like `OCIS_CONFIG_DIR=/etc/ocis/ ocis storage-users uploads sessions`? You might not be picking the right environment; I mean, you might have set it up for systemd but not for regular users.

Thank You for that hint. Actually OCIS_BASE_DATA_PATH=/mnt/OCIS OCIS_CONFIG_DIR=/etc/ocis ocis storage-users uploads sessions did the trick. Without the base data path I got an empty list while some uploads were in process.

**Comment by mmattel** [comment]
@BEBU88 thanks for the update.
For curiousity, if not adapting the env file: as systemd is running as root, if you change your command using sudo, do you also get the error message? That info would help me for the docs update.

**Comment by BEBU88** [comment]
@mmattel 

I ran the command as root user directly and got the error without the env vars. I would assume that the error also occurs with sudo command.

**Comment by mmattel** [comment]
@BEBU88 I just have updated our [bare metal deployment with systed](https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html). Though it already contained the info to add the paths into the env file, I added an `important` marker with some text about the importance to do so. With that PR, I also added an update note at the end of the documentation.

FYI, you may want to have a look to our other deployment examples using docker. That has been been added recently for rolling.

I am closing this. You are welcomed to add another issue if something arises 😄
