### ISSUE TITLE
Activities. Sharee can get the shared file activities using the file-id

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/ocis#9849]
### Steps to reproduce
1. share a folder to `demo` user
2. as `demo`, create some files in the received share
3. as `demo`, check the shared file activities using share mountpoint id (same as webUI)

    ```
    curl 'https://localhost:9200/graph/v1beta1/extensions/org.libregraph/activities?kql=itemid%3A{folder-share-mountpoint}' \
    -udemo:demo -vk | jq 
    ```
    ```json
    {"value": []}
    ```
4. as `demo`, check the shared file activities using shared file id :question: 
    ```
    curl 'https://localhost:9200/graph/v1beta1/extensions/org.libregraph/activities?kql=itemid%3A{folder-fileid}' \
    -udemo:demo -vk | jq
    ```
    ```yml
    {"value": [
      {
       ... # activities
      }
    ]}
    ```

**Comment by prashant-gurung899** [comment]
@ScharfViktor

**Comment by ScharfViktor** [comment]
> Actual: einstein can see all action of folder f1

user can see not only activity of the shared folder `f1`. he can see all activity of the admin personal space if he uses `kql=itemid%3A{spaceUUID}` CC @kobergj 


2 question: @tbsbdr should be `einstein` see activity of the shared folder? or the recipient should not see activity of the shared resources anyway?

**Comment by ScharfViktor** [comment]
related #9860

**Comment by tbsbdr** [comment]
@ScharfViktor lets do it this way: recipients should not see activity of the shared resources. Lets keep it simple and gdpr compliant

**Comment by kobergj** [comment]
Currently `view` access is enough to query activities. (That was agreed on initial implementation). We will need to check for another permission instead. 

@micbar should we use `ListGrants`? This should probably be enough as you cannot share with `Share` permission any more.

**Comment by micbar** [comment]
@kobergj @tbsbdr 

I like the idea to use `ListGrants`. Then we would see activitites only in "Transparent" Shares.

**Comment by tbsbdr** [comment]
I'm not a fan of having too many variations of the product behaviour, but I do not veto your propsal @micbar . I just want to document my concerns: I expect "transparent shares" to be a project specific feature, so same would then apply to the visibility of activities.

**Comment by micbar** [comment]
@kobergj Please add that to the dev docs on the unified Roles Page.
