### ISSUE TITLE
Activities. activity lack language translation.

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/ocis#9856]
### Steps to reproduce
1. create a folder and add/edit/delete file inside that folder.
2. change the preferred language to any.('Spanish' in this case)
3. list the activities for that folder.

## Expected behavior

Expected to get all the activity messages to be translated to preferred langauage.

## Actual behavior
List of activity messages are not translated.

![image](https://github.com/user-attachments/assets/2db02eec-344e-4aa3-bb89-bfe5d0f73f39)

**Comment by kobergj** [comment]
Missing step in our translation process. Thanks for finding!

**Comment by mmattel** [comment]
Note, with the fix applied by @kobergj, activitylog will appear on transifex as `ocis-activitylog` and can be translated. I can check tomorrow if the first sync went well. In case, I will start the translation to German and ask our spanish colleagues to do the same. @2403905 and @ScharfViktor can help with Ukrainan and Russian 😃

**Comment by prashant-gurung899** [comment]
@mmattel Great!!! Works fine now. :+1:

**Comment by mmattel** [comment]
Thanks for the screenshots. I just corrected two tranlsations as I now have seen how they got used 😅

**Comment by prashant-gurung899** [comment]
> Thanks for the screenshots. I just corrected two tranlsations as I now have seen how they got used 😅

Alright! @mmattel Thanks
