### ISSUE TITLE
Activitylog translation/Transifex/doc issues

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9865]
Some more findings after #9857 has been merged:

According to the [Add Translations](https://owncloud.dev/services/general-info/add-translations/) description:

* The `OCIS_DEFAULT_LANGUAGE` envvar in `services/<service-name>/pkg/config/config.go`
The necessary envvar, the functionality and the readme part is missing.
* Comparing `userlog` and `activitylog`:
[userlog](https://github.com/owncloud/ocis/blob/master/services/userlog/pkg/service/templates.go) defines internal vars and translations different than activitylog (missing: Subject/Message)

@kobergj fyi

**Comment by kobergj** [comment]
The second finding is as designed.
