### ISSUE TITLE
[QA][API test] organize the test folders within the acceptance directory

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9872]
In order to better scope and organize the files and folders related to API tests, here is a proposed `acceptance` directory structure.

Current:
```
📁tests
|--📁acceptance
|  |--📁features
|  |  |--📁apiSuiteX
|  |  |--📁bootstrap
|--📁TestHelpers
```

Proposed:
```
📁tests
|--📁acceptance
|  |--📁features
|  |  |--📁apiSuiteX
|  |--📁bootstrap
|  |--📁TestHelpers
```
- [x] `bootstrap` moved out of the features dir (`features` only contains the test suites - feature files)
- [x] `TestHelpers` moved into acceptance dir (because those helpers are only for API acceptance tests)

**Comment by saw-jan** [comment]
CC @ScharfViktor @phil-davis

**Comment by ScharfViktor** [comment]
I agree 👍 
One suggestion: maybe we can join `make test-acceptance-from-core-api` to `make test-acceptance-api`?
but keep the old set naming (prefixes with `core`) to use only one command to run tests: 

```
TEST_SERVER_URL="https://localhost:9200" \ BEHAT_FEATURE="tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature:242" \ 
make test-acceptance-api
```

```
TEST_SERVER_URL="https://localhost:9200" \ 
BEHAT_FEATURE="tests/acceptance/features/apiGraph/activities.feature" \ 
make test-acceptance-api
```

**Comment by phil-davis** [comment]
I agree with the acceptance test folder restructuring. 

I will let @saw-jan and @ScharfViktor decide what `make` command targets should do what things.

**Comment by saw-jan** [comment]
>One suggestion: maybe we can join make test-acceptance-from-core-api to make test-acceptance-api?
>but keep the old set naming (prefixes with core) to use only one command to run tests:

currently, we have two different behat configs for them. But it looks doable. :+1: 
I will add to the list or create another ticket for this
