### ISSUE TITLE
Web Asset Paths - location: base_dir --> config_dir

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9886]
We have these envvars in the web service:

`WEB_ASSET_CORE_PATH`
`WEB_ASSET_THEMES_PATH`
`WEB_ASSET_APPS_PATH`

According their definition and description, the use the _base directory_ as default path.

I am questioning this as in my understanding, this should be the config directory.

No data except user related stuff should be in the base dir and the envvars are definitely config stuff - but I may be wrong...

Technically an easy fix: redefine the path and correct the envvar description.

Note, because these envvars have been introduced with 6.0, we have no issue in changing them.

@fschade

**Comment by fschade** [comment]
discussed today, artifacts are not configuration assets. We keep it as it is.
