### ISSUE TITLE
Permissions endpoint is not listing federated shares

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#9898]
## Describe the bug
Querying permissions of a resource via the `/permissions` endpoint does not list federated shares.

## Steps to reproduce
1. Create a federated share on a resource
2. Query its permissions via the `/permissions` endpoint

## Expected behavior
The federated share should be part of the server response.

## Actual behavior
It is missing in the server response.

**Comment by butonic** [comment]
fixed by https://github.com/owncloud/ocis/pull/9905
