### ISSUE TITLE
federated shares cannot be updated (sharing role / expiry date)

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#9926]

**Comment by ScharfViktor** [comment]
retested after merging https://github.com/cs3org/reva/pull/4840

bug still exist
<img width="1694" alt="Screenshot 2024-09-11 at 11 09 25" src="https://github.com/user-attachments/assets/15cfaa7f-5610-4ebc-af61-b7e00f2af4d6">

**Comment by dragonchaser** [comment]
@ScharfViktor schould be fixed with #9980
