### ISSUE TITLE
generate a dedicated uuid for federated users instead of using the one from the remote instance

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#9927]
we are only comaring the opaque id of users when checking permissions. Anywhere we are using `utils.UserIDEqual()`.

We want to assign our own uuid for users anyway and store the identity used to authenticate a user as an additional property (list).

For normal users the proxy should exchange the sub@iss claims for our internal uuid and then only compare that uuid.

For federated users we need to  create a new uuid when accepting an invite so the user is guaranteed to have a non colliding user id. If there are cases where we should return the original remote userid, e.g. in the graph user listing we can use the opaque id for now.

duh the userid has no opaque id ... only the user struct.

**Comment by kulmann** [comment]
> For federated users we need to create a new uuid when accepting an invite so the user is guaranteed to have a non colliding user id.

I don't understand that part. I thought we're using `uuid`s so that we have globally unique ids and don't need to add some issuer or instance id to it.

**Comment by butonic** [comment]
AFAICT even if the CS3 api is intended to be consumed directly by clients it still only represents a single instance. If instances talk to each other they do that using the OCM apis. The gateway has dedicated endpoints to forward and accept invites. as a consequence of inviting a user two federated users are created: one in each instance. So an instance implementing the CS3 api still nedds to keep track of all users. If an implementation would use integers for its users it would have to store the id the remote system provided for the user in addition to the internal id. In our case we roll our own uuid instead of assigning an int.

I think consequently we would have to replace the remote issuer with ourself ... or ... since we are already ignoring it ... drop the issuer. 

In any case, to be able to list the identity in the graph api we could keep the original issuer ... but I'd prefer to make identity a dedicated property in the cs3 user. Or we add a graphid property to the user object and treat the userid property as a single identity? urgt hat sucks.

Hm, the cleanest way to represent users with the CS3 user and userid is to use the userid to store our uuid and the type of user. Instead of filling the userid IdP property I'd prefer to store the identities in the opaque blob as json.

**Comment by butonic** [comment]
After revisiting the code ... and how ocm and federated sharing works I can say that the invite process is only used to create local representations of remote users in both instances. They are completely independent of any actual users and are only relevant when searching for recipients.

They are not used to check access to the ocm share. When sharing a token is generated that is used in bearer auth when accessing the public link share.

So, instead of extending the ocm implementation with sth like this:
```go
type RemoteUser struct {
	*userpb.User
	LocalID string `json:"local_id"`
}
```

And then having to implement a migration I think we can ̀ base64(userid.opaqueid@userid.idp)` and use that as the id of the federated user.

The sql implementation for ocm shares uses a ocm_remote_users table:
```
CREATE TABLE IF NOT EXISTS ocm_remote_users (
    initiator VARCHAR(255) NOT NULL,
    opaque_user_id VARCHAR(255) NOT NULL,
    idp VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (initiator, opaque_user_id, idp)
)
```

we could add a migration to add a colum if someone is really using that ... same goes for the json implementation...

**Comment by butonic** [comment]
hrhr so we are storing a grant in decomposedfs, but only to be able to list it in the propfind... the actual access is only granted on based on the token. The ocmshare scope only jails the requests in the subtree, same as public link shares / scopes.

🤪

**Comment by butonic** [comment]
so whd do we still have a user id collision? because we mix the federated users into the normal users without replacing their userid with a local id in the graph api. we could in the graph endpoint base64 encode userid@idp and use that as the userid for federated users only.

That leaves the permission checks in decomposedfs ... they still might collide:

normal grants are stored and actually grant permission.
ocm grants are stored as well, but they are only used to efficiently list the remote ocm users that a resource has been shared with.

I need to double check if we take into account the user type

👀

**Comment by butonic** [comment]
ok, when persisting a grant for a federated user we store a different string than for other users:
```go
func UserAce(id *userpb.UserId) string {
	if id.GetType() == userpb.UserType_USER_TYPE_FEDERATED {
		return "u:" + id.OpaqueId + "@" + id.Idp
	}

	return "u:" + id.OpaqueId
}
```

`UserACE` is used as the principal.

Now, when parsing it back we never try to split this again. Turning an ACE inte a grant blindly uses the complete principal:
```go

// Grant returns a CS3 grant
func (e *ACE) Grant() *provider.Grant {
	// if type equals "D" we have a full denial which means an empty permission set
	permissions := &provider.ResourcePermissions{}
	if e._type == "A" {
		permissions = e.grantPermissionSet()
	}
	g := &provider.Grant{
		Grantee: &provider.Grantee{
			Type: e.granteeType(),
		},
		Permissions: permissions,
		Creator:     userIDFromString(e.creator),
	}
	id := e.principal[2:]
	if e.granteeType() == provider.GranteeType_GRANTEE_TYPE_GROUP {
		g.Grantee.Id = &provider.Grantee_GroupId{GroupId: &grouppb.GroupId{OpaqueId: id}}
	} else if e.granteeType() == provider.GranteeType_GRANTEE_TYPE_USER {
		g.Grantee.Id = &provider.Grantee_UserId{UserId: &userpb.UserId{OpaqueId: id}}
	}

	if e.expires != 0 {
		g.Expiration = &typesv1beta1.Timestamp{
			Seconds: uint64(e.expires / int64(time.Second)),
			Nanos:   uint32(e.expires % int64(time.Second)),
		}
	}

	return g
}
```

**Comment by butonic** [comment]
I need a review of https://github.com/cs3org/reva/pull/4833

**Comment by butonic** [comment]
https://github.com/cs3org/reva/pull/4833 got merged, needs reva bump

**Comment by butonic** [comment]
all merged
