### ISSUE TITLE
[QA] extend search test scenarios

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9948]
We have search related tests in [apiSearch1/search.feature](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiSearch1/search.feature)

Add more scenarios: https://github.com/owncloud/ocis/pull/10119
```
- have a file (`lorem.txt`) in personal space
- have similar named file (`another-lorem.txt`) in project space
- have a share with similar file name (`shared-lorem.txt`)
```

- [x] search `lorem` globally (check all three files are retruned in the response) &rarr; https://github.com/owncloud/ocis/pull/10119/commits/97f6fa045aee66ef1b4510cc797e7955e53f90b6
- [x] search `lorem` with scope: &rarr; https://github.com/owncloud/ocis/pull/10119/commits/a4b1f57d71fe4961382464bf4efb9c6810bdead0
  - [x] Personal root (check that files from other spaces are not returned)
  - [x] Project root (check that files from other spaces are not returned)
  - [x] Shares root (check that files from other spaces are not returned)

- [x] Check test coverage for bug reports:  https://github.com/owncloud/ocis/issues/7060 
  &rarr; https://github.com/owncloud/ocis/pull/10189
 &rarr; Test coverage will be covered in: https://github.com/owncloud/ocis/pull/10078

**Comment by anon-pradip** [comment]
I am closing this issue now
cc @saw-jan
