### ISSUE TITLE
[QA] Add acceptance test for new role space editor without version

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#9955]
### Description
There's a new sharing role `Editor without Versions` for files and folders, added in PR https://github.com/owncloud/ocis/pull/9881.

| Location | Role                              | Status  | Verions visible? |
| -------- | --------------------------------- | ------- | ---------------- |
| Personal | Share: can view                   | current | no               |
| Personal | Share: can edit                   | current | no               |
| Space    | Member: can view                  | current | no               |
| Space    | Member: can edit                  | current | yes              |
| **Space**    | **Member: can edit without versions** | **new**     | **no**               |
| Space    | Share: can view                   | current | no               |
| Space    | Share: can edit                   | current | no               |

Need to add tests for the role `Member: can edit without versions` mentioned in the table.
- [x] Add test for the new sharing role `Editor without Versions` https://github.com/owncloud/ocis/pull/9972
- [ ] Check test scenarios for other roles mentioned in the table above
  - [ ] link share https://github.com/owncloud/ocis/pull/9982

**Comment by prashant-gurung899** [comment]
Closing this issue as the tests are covered in: https://github.com/owncloud/ocis/pull/9972 and https://github.com/owncloud/ocis/pull/9982
And for following cases, there are tests written already:
| Location | Role                              | Status  | Verions visible? |
| -------- | --------------------------------- | ------- | ---------------- |
| Space    | Member: can view                  | current | no               |
| Space    | Member: can edit                  | current | yes              |
