### ISSUE TITLE
Patch Release 5.0.7

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#9962]
### Prerequisites

- [x] DEV: Bump web #9958 
- [x] DEV: Fix latest docker tag #9963
- [x] DEV: Create pre release `v5.0.7-rc.1`

* [x] DEV: Create branch `release-x.x.x-rc.x` - tested in stable-5.0
  * [x] DEV: bump ocis version in necessary files
    * [x] DEV: `sonar-project.properties`
    * [x] DEV: `ocis-pkg/version/version.go`
  * [x] DEV: prepare changelog folder in [changelog](https://github.com/owncloud/ocis/releases/tag/v5.0.7)
  * [x] DEV: update production docker tag in the production.yml file in the continuous deployments
* [x] DEV: Check successful CI run on release branch
* [x] DEV: Create signed tag `[v5.0.7](https://github.com/owncloud/ocis/releases/tag/v5.0.7)`
* [x] DEV: Check successful CI run on `v5.0.7` tag / BLOCKING for all further activity
* [x] DEV: Merge back release branch

### QA Phase

 
* [x] QA: Compatibility testing between 5.0.6 and 5.0.7
~* [ ] QA: Performance test  see result here~ skipped for this release until @ScharfViktor is back from vacation
* [x] QA: e2e with different deployment:
  * [x] QA: wopi against smoke test https://github.com/owncloud/web/pull/11503

**Comment by micbar** [comment]
### Compatibility test between `owncloud/ocis:5.0.5` and `ocis:dev` (I build dev ocos on stable-5.0 branch)

shares:
- [ ] public share (with an expiration date)
- [ ] share with user as role editor (with an expiration date)
- [ ] share with user as role viewer
- [ ] share with group "Users"

project space:
- [ ] uploaded folder & files
- [ ] trashed files
- [ ] share space with user
- [ ] public share space

files:
- [ ] uploaded folder & files
- [ ] version of files
- [ ] trashed files
- [ ] GDPR export

users
- [ ] non demo user with role admin
- [ ] non demo user with role user
- [ ] created new user
- [ ] disabled user
- [ ] created new group

settings
- [ ] language settings
- [ ] update logo админ
- [ ] new password

Remarks: no remarks

**Comment by micbar** [comment]
# 📝  Changes in 5.0.7-rc.1

## Summary

* Enhancement - Add virus filter to sessions command: [#9041](https://github.com/owncloud/ocis/pull/9041)
* Enhancement - Assimilate `clean` into `sessions` command: [#9828](https://github.com/owncloud/ocis/pull/9828)
* Enhancement - Update web to v8.0.5: [#9958](https://github.com/owncloud/ocis/pull/9958)

## Details

* Enhancement - Add virus filter to sessions command: [#9041](https://github.com/owncloud/ocis/pull/9041)

   Allow filtering upload session by virus status (has-virus=true/false)

   https://github.com/owncloud/ocis/pull/9041

* Enhancement - Assimilate `clean` into `sessions` command: [#9828](https://github.com/owncloud/ocis/pull/9828)

   We deprecated `ocis storage-user uploads clean` and added the same logic to
   `ocis storage-users uploads session --clean`

   https://github.com/owncloud/ocis/pull/9828

* Enhancement - Update web to v8.0.5: [#9958](https://github.com/owncloud/ocis/pull/9958)

   Tags: web

   We updated ownCloud Web to v8.0.5. Please refer to the changelog (linked) for
   details on the web release.

   - Bugfix [owncloud/web#11395](https://github.com/owncloud/web/pull/11395):
   Missing space members for group memberships - Bugfix
   [owncloud/web#11263](https://github.com/owncloud/web/pull/11263): Show more
   toggle in space members view not reactive - Bugfix
   [owncloud/web#11263](https://github.com/owncloud/web/pull/11263): Space show
   links from other spaces - Bugfix
   [owncloud/web#11303](https://github.com/owncloud/web/pull/11303): Uploading
   nested folders

**Comment by butonic** [comment]
hm ... https://github.com/owncloud/ocis/issues/8589#issuecomment-2290886061 still needs to be done ... AFAICT scaling in kubernetes with nats js kv is still completely broken

**Comment by JammingBen** [comment]
Just to make sure: Does this also include a reva bump so that https://github.com/cs3org/reva/pull/4761 is included?

**Comment by micbar** [comment]
> Just to make sure: Does this also include a reva bump so that [cs3org/reva#4761](https://github.com/cs3org/reva/pull/4761) is included?

No, that is not included. We need a 5.0.8 for that.

**Comment by micbar** [comment]
# 🎉  Infinite Scale 5.0.7

## Docker

`docker pull owncloud/ocis:latest` 

OR

`docker pull owncloud/ocis:5.0.7`

## Binaries

https://download.owncloud.com/ocis/ocis/stable/5.0.7/
