### ISSUE TITLE
[QA] [UI] Unprivileged user has UI element to change his role

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#998]
env OCIS_VERSION=v1.0.0-rc6 BRANCH=v1.0.0-rc6 EOS_OCIS_TAG=1.0.0-rc6 docker-compose -f docker-compose-eos-test.yml up -d
 https://localhost:9200

User einstein can apparently change his own role between guest, user, admin. 
The change has no effect. On a refresh, his role is back at user. OK.

Expected behaviour: Hide the useless UI elements.

This is a remainder of #879

**Comment by kulmann** [comment]
Duplicate. Closing in favour of https://github.com/owncloud/product/issues/167
