### ISSUE TITLE
Running the ocis_full deployment example returns an error for NATS

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9990]
When running the `ocis_full` deployment example (6.3.0 and master) with self signed certificates (and inbucket to populate notification settings), I get the following error in the ocis docker log reported:

`sudo docker logs 7a785dbab3fb 2>&1 | grep nats`

`{"level":"warn","service":"storage-system","pkg":"rhttp","time":"2024-09-06T07:29:13Z","line":"github.com/cs3org/reva/v2@v2.23.1-0.20240905133054-2de6ff31c4e3/internal/http/services/dataprovider/dataprovider.go:83","message":"missing or incomplete nats configuration. Events will not be published."}`

@micbar

**Comment by micbar** [comment]
That can be ignored. This is a false positive during startup because the bats service is not up and ready.
