### ISSUE TITLE
[QA] API test for `REPORT` request to webdav endpoint

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#9991]
### Description
It seems there might not be full test coverage for `REPORT` request for endpoint `/remote.php/dav/spaces/` with and without `spaceUUID`,
- `-XREPORT https://localhost:9200/dav/spaces/`
- `-XREPORT https://localhost:9200/dav/spaces/spaceUUID`

Both seems to behave the same way.

TODO:
- [ ] Check for the related test coverages
- [ ] Add test coverages for these endpoint
- [ ] Check with and without `remote.php` in dav-path

Related bug reports:
- https://github.com/owncloud/ocis/issues/7104
- https://github.com/owncloud/ocis/issues/7096
- https://github.com/owncloud/ocis/issues/7060
- https://github.com/owncloud/ocis/issues/6954

**Comment by saw-jan** [comment]
>- [ ] Check for the related test coverages
>- [ ] Add test coverages for these endpoint

Tests now use these paths for REPORT request: (#10044)
`https://localhost:9200/webdav`
`https://localhost:9200/dav/files`
`https://localhost:9200/dav/spaces`

And as per https://github.com/owncloud/ocis/issues/7104#issuecomment-1711310103, we really don't need to test with space-id in the request path.

>- [ ] Check with and without `remote.php` in dav-path

This will be done in another PR with different implementation.

And I want to move bug reports coverage in ticket https://github.com/owncloud/ocis/issues/9948

So maybe we can close this one? 
CC @prashant-gurung899 @amrita-shrestha

**Comment by saw-jan** [comment]
I am closing this here.
